### ISSUE TITLE
Добавление нового типа документа в выгрузку и обмен

### ISSUE THREAD

**Issue by ImKiLL** [diadoc/diadocsdk-1c-docs#10]
Добрый день. Используем конфигурацию "Аренда и управление недвижимостью для 1С:Управление производственным предприятием, редакция 1.3". В этой конфигурации есть специализированные документы, для отражения операции по аренде. В частности, вместо "Реализации товаров и услуг" используется документ "Начисление арендной платы", на его основании выписывается СФ исходящая. Вопрос, есть ли возможность аккуратного добавления новых типов документов в модуль диадока, и если есть, то подскажите куда смотреть.

**Comment by denver069** [comment]
Чтобы добавить отраслевой документ к отправке в типовой модуль текущей версии (5.11.04) нужно исправить следующее:

1)	Формирование списка к отправке:
Форма «Модуль_ИнтеграцияУПП13», процедура «ПодготовитьВТ_Накладные»: добавить вызов процедуры получения списка нужного типа документов (можно по аналогии с процедурой «ПодготовитьВТ_Накладные_РеализацияТоваровУслуг»);

2)	Заполнение контента для предварительного просмотра и отправки документа:
Получение данных табличной части документа: форма «Модуль_ИнтеграцияУПП13», процедура «ТЧПолучитьТекстЗапроса» - добавить условие на новый тип документов и процедуру получения данных (можно по аналогии с процедурой «ТЧПолучитьТекстЗапросаРеализацияТоваровУслуг» формы «Модуль_ИнтеграцияУниверсальнаяЛогика»);

Возможно потребуется доработка связанных процедур и функций заполнения контента (если реквизиты отраслевого документа отличаются от реквизитов РТУ, используемых при заполнении).

**Comment by ImKiLL** [comment]
Спасибо за наводку. Будем разбираться.
