### ISSUE TITLE
Возвращаемое значение Send() объекта AcquireCounteragentTask

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#100]
Отправляем приглашения к партнерству
```
Organization.CreateSendTaskFromFile(ИмяФайла, "TrustConnectionRequest");
AcquireCounteragentTask = Organization.CreateAcquireCounteragentTask(ПолныйПуть);
Если ЗначениеЗаполнено(CounteragentId) тогда
  AcquireCounteragentTask.CounteragentBoxId = CounteragentId; 
КонецЕсли;
AcquireCounteragentTask.Inn 				= ИНН;
AcquireCounteragentTask.Message 			= Комментарий; 
AcquireCounteragentTask.FileName 			= ИмяФайла;
 //       AcquireCounteragentTask.SignatureRequested  = истина; // SignatureRequested (булево, чтение/запись) - запрос подписи контрагента, выдает ошибку 
CounteragentId_new =  AcquireCounteragentTask.Send(); //возвращает идентификатор организации-получателя приглашения
```
В справке метода [Send](http://diadocsdk-1c.readthedocs.io/ru/latest/Send-(AcquireCounteragentTask).html) сказано "Возвращаемое значение Строка, идентификатор организации-получателя приглашения", но этот идентификатор отличен для контрагентов, которые имеют кабинет, если найти контрагента методом GetCounteragentListByInnKpp(ИНН)
и получить его свойство id.
```
CounteragentList = Organization.GetCounteragentListByInnKpp(ИНН);
Counteragent =  CounteragentList.GetItem(0);
CounteragentId = Counteragent.id;
```
Например:
1) CounteragentId_new= 7b51640c-4cf0-4a63-99e4-885dc55d8914 
CounteragentId= 4da280d3f6c844628725f1f63f6b5244@diadoc.ru 
для ИНН= 3435304120 КПП= 343501001

2) CounteragentId_new= 725de8cc-a70a-4534-8f02-1d2ab61c6a5c 
CounteragentId= ffbbc142b6b440adb402fdd3aa9856e5@diadoc.ru 
для ИНН= 344407109789 КПП=

3) CounteragentId_new= a76cdd68-2b1b-4caa-a37f-4c058e7a46e9 
CounteragentId= 63ef3174eec34f079a043c27a5bf8fd5@diadoc.ru 
для ИНН= 3435117553 КПП= 343501001

4) CounteragentId_new= a674e6b7-8a46-4e8b-acf8-82329f087e44 
CounteragentId= 96ed37ca8283410b836ee0f6fc4bb977@diadoc.ru 
для ИНН= 3405011704 КПП= 340501001

5) CounteragentId_new= 5096a2e5-1207-4702-ab97-b3f07095f6a8 
CounteragentId= d2cbf86bda8641e6bff531e9dd66857b@diadoc.ru 
для ИНН= 344406306103 КПП=

6) CounteragentId_new= 8d333b26-1c6e-49a2-bdf4-38eeafd5dd6f 
CounteragentId= f63e3feaa6bb457eb117d54a1786aa9c@diadoc.ru 
для ИНН= 3435701617 КПП= 343501001

Соответственно, после отправки приглашений контрагентам, которые не имеют личных кабинетов Диадок, не получается найти отправленное приглашение, т.к. метод Send возвращает не верный идентификатор контрагента. Необходимо исправить, либо подсказать почему идентификаторы для одного и того контрагента отличаются (получены разными способами)

**Comment by denver069** [comment]
В результате выполнения метода AcquireCounteragentTask.Send() возвращается не BoxID а OrgID.
В следующей версии внешней компоненты мы добавим метод Organization.GetCounteragentByOrgID, с помощью которого можно будет получить данные контрагента в том числе и BoxID.

Для получения информации о выходе новой версии внешней компоненты, вы можете подписаться на ленту новостей [RSS](http://diadocsdk-1c.readthedocs.io/ru/latest/index.rss)

**Comment by jakeqwert** [comment]
Добрый день. Прошу по возможности, ускорить добавления нового метода Organization.GetCounteragentByOrgID, т.к. необходимо повторно массово отправить новые приглашения к партнерству. Диадок потеряет свои позиции в сравнении с другими используемыми нами операторами ЭДО.

**Comment by azhipaigor** [comment]
Добрый день. Войдет в следующий релиз 5.18.1.

**Comment by azhipaigor** [comment]
Зарелизили [5.18.1.219](http://diadocsdk-1c.readthedocs.io/ru/latest/Downloads.html)
