### ISSUE TITLE
Соотношение "Алфавитный указатель объектов компоненты" и "Форматы документов" 

### ISSUE THREAD

**Issue by TulDuRu** [diadoc/diadocsdk-1c-docs#1000]
Как относятся эти две структуры не очень понятно 
Верно ли утверждение что Act552SellerContent = XmlAcceptanceCertificate ?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Нет, не верно.
[XmlAcceptanceCertificate](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/XmlAcceptanceCertificate.html) - это тип документа
Act552SellerContent  - это тип контента, притом старый, его нет в алфавитном указателе, использовать его не рекомендуется

У [XmlAcceptanceCertificate](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/XmlAcceptanceCertificate.html) могут быть и другие контенты, если пользуетесь устаревшим методом DocumentBase.GetContent(). Например AcceptanceCertificateSellerContent или UtdSellerContent

Если же пользуетесь актуальным методом [DocumentBase.GetDynamicContent(...)](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html#DocumentBase.GetDynamicContent), то вам вернётся [DynamicContent](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html)
