### ISSUE TITLE
Аннулирование в роуминге (компонента 1С)

### ISSUE THREAD

**Issue by vlseregin** [diadoc/diadocsdk-1c-docs#1002]
Добрый день. При попытке аннулирования (ReplySendTask = CreateReplySendTask2("RevocationRequest"), ReplySendTask.Send()) выдает ошибку Revocation request is not available for recipient's roaming operator 2LD. С другими провайдерами в роуминге такого не наблюдалось.
Версию  брал последнюю 5.50.

Подскажите пожалуйста, что делать?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Проблема не в компоненте, а в том, что этот оператор не поддерживает аннулирование в роуминге. Документы можно аннулировать на бумаге

**Comment by vlseregin** [comment]
Да, Вы правы. Вопрос закрыт.
