### ISSUE TITLE
Метод GetDocuments() и документы на согласовании.

### ISSUE THREAD

**Issue by Alkonig58** [diadoc/diadocsdk-1c-docs#1003]
Добрый день.
Не удается получить список исходящих документов содержащий документы на согласовании.
Вопрос: как получить список документов находящихся на согласовании ?

П.С. ниже приведен код, этот код получает список исходящих, но в этом списке отсутствую документы которые отправлены на согласование.

Мой код:
	Organization = DiadocConnection.GetOrganizationById(Стр.Guid);
	SearchDocumentTask = Organization.GetDocumentsTask();
	SearchDocumentTask.FromSendDate = НачалоНедели(ТекущаяДата());
	SearchDocumentTask.ToSendDate   = КонецНедели(ТекущаяДата());
	SearchDocumentTask.Category     = "Any.Outbound";
	dd_Documents = SearchDocumentTask.GetDocuments();
	Для Каждого dd_Document Из dd_Documents Цикл
		НовСтр = СписокИсходящие.Добавить();
		ЗаполнитьЗначенияСвойств(НовСтр, dd_Document);
	КонецЦикла;

**Comment by Alkonig58** [comment]
Похожая проблема: https://github.com/diadoc/diadocsdk-1c-docs/discussions/891
Вы рекомендуете не ставить "дату конца".

**Comment by GilimkhanovDenis** [comment]
@Alkonig58 

Вы нашли ответ на свой вопрос в #891 или вас интересуется другой сценарий? Если другой, то просьба описать чем он отличается
