### ISSUE TITLE
Проверка остатка документов в пакете

### ISSUE THREAD

**Issue by AlexanderShiryaev** [diadoc/diadocsdk-1c-docs#1004]
Коллеги, добрый день!

Не планируется реализация интерфейса (например, через AdminTools), для получения информации оставшихся документов в оплаченном пакете документов?
Или подскажите, пожалуйста, если я его не вижу

**Comment by NickZubashevskiy** [comment]
Добрый день!

Добавил задачу в бэклог, по поводу сроков выполнения сейчас трудно сказать.  Если данная функциональность необходима, просьба обратиться к менеджеру, ведущему вашу организацию
