### ISSUE TITLE
Визуализация неформализованных документов

### ISSUE THREAD

**Issue by VictorPetrov2016** [diadoc/diadocsdk-1c-docs#1006]
Здравствуйте! 
Возможно ли с помощью API отправить контрагенту неформализованный **счет на оплату** в файле формата XML, но так, чтобы контрагент увидел не текст файла XML, а читабельный счет на оплату?
Спасибо!
 
Вот пример XML-файла:
 
<?xml version="1.0" encoding="windows-1251"?>
<Файл ИдФайл="ON_NSCHFDOPPR_2BM-9671359891-967101000-202111010235323023806_2BM-9677329734-967701000-202311210136311165039_20243026_5554BD26-8954-4C1C-BE7F-344987995200" ВерсФорм="5.01" ВерсПрог="Diadoc 1.0">
  <СвУчДокОбор ИдОтпр="2BM-9677329734-967701000-202111010235323023806" ИдПол="2BM-9671359891-967101000-202311210136311165039">
    <СвОЭДОтпр НаимОрг="Тестовая фирма 7732973" ИННЮЛ="9677329734" ИдЭДО="2BM" />
  </СвУчДокОбор>
  <Документ>
    <СвСчет НомерСчет="19/03-1" ДатаСчет="19.03.2024" КодОКВ="643">
      <СвПокуп>
        <ИдСв>
          <СвЮЛУч НаимОрг="Тестовая 7135989" ИННЮЛ="9671359891" КПП="967101000"/>
        </ИдСв>
        <Адрес>
          <АдрИнф КодСтр="643" АдрТекст="Сущевкий вал, 44,корп.3" />
        </Адрес>
      </СвПокуп>
   </СвСчет>
    <ТаблСчет>
      <СведТов НомСтр="1" НаимТов="Ноутбук Huawei MateBook D 16 MCLF-X 53013YDN, 16&quot;, 2024, IPS, Intel Core i3 1215U 1.2ГГц, 6-ядерный, 8ГБ LPDDR4x, 512ГБ SSD, Intel UHD Graphics, без операционной системы, серый космос" ОКЕИ_Тов="796" КолТов="1.00" ЦенаТов="49980.00" СтТовБезНДС="41650.00" НалСт="20%" СтТовУчНал="49980.00" >
        <Акциз>
          <БезАкциз>без акциза</БезАкциз>
        </Акциз>
        <СумНал>
          <СумНал>8330.00</СумНал>
        </СумНал>
        <ДопСведТов КодТов=" " НаимЕдИзм="шт" КрНаимСтрПр=" ">
           <СведПрослеж НомТовПрослеж=" " ЕдИзмПрослеж="796" КолВЕдПрослеж="0" НаимЕдИзмПрослеж="шт" />
        </ДопСведТов>
      </СведТов>
      <СведТов НомСтр="2" НаимТов="Монитор AOC 22E1Q(00/01) 21.5" ОКЕИ_Тов="796" КолТов="1.00" ЦенаТов="13480.00" СтТовБезНДС="11233.33" НалСт="20%" СтТовУчНал="13480.00" >
        <Акциз>
          <БезАкциз>без акциза</БезАкциз>
        </Акциз>
        <СумНал>
          <СумНал>2246.67</СумНал>
        </СумНал>
        <ДопСведТов КодТов="1069703" НаимЕдИзм="шт" КрНаимСтрПр=" ">
           <СведПрослеж НомТовПрослеж="10013160/051021/В011215/2" ЕдИзмПрослеж="796" КолВЕдПрослеж="1" НаимЕдИзмПрослеж="шт" />
        </ДопСведТов>
      </СведТов>
      <СведТов НомСтр="3" НаимТов="Монитор AOC 24B2XD 23.8" ОКЕИ_Тов="796" КолТов="1.00" ЦенаТов="10910.00" СтТовБезНДС="9091.67" НалСт="20%" СтТовУчНал="10910.00" >
        <Акциз>
          <БезАкциз>без акциза</БезАкциз>
        </Акциз>
        <СумНал>
          <СумНал>1818.33</СумНал>
        </СумНал>
        <ДопСведТов КодТов="1422203" НаимЕдИзм="шт" КрНаимСтрПр=" ">
           <СведПрослеж НомТовПрослеж=" " ЕдИзмПрослеж="796" КолВЕдПрослеж="0" НаимЕдИзмПрослеж="шт" />
        </ДопСведТов>
      </СведТов>
      <ВсегоОпл СтТовБезНДСВсего="61975" СтТовУчНалВсего="74370">
        <СумНалВсего>
      </ВсегоОпл>
    </ТаблСчет>
</Документ>
</Файл>

**Comment by GilimkhanovDenis** [comment]
Добрый день

Да, такое возможно, но решение лежит не в области использования API - необходимо подключить услугу "Кастомная печатная форма". Подробнее [здесь](https://support.kontur.ru/diadoc/40527-kastomnye_pechatnye_formy)
