### ISSUE TITLE
Некорректное заполнение должности при подписании формализованного акта сверки

### ISSUE THREAD

**Issue by MaximGlazunov** [diadoc/diadocsdk-1c-docs#1007]
Добрый день.

При подписании входящих актов сверок (формализованных) наблюдается проблема с заполнением должности подписанта.
Если в контенте покупателя Signers.Signer.Position.SimpleContentValue заполнить должность, то на печатной форме она будет задублирована (например, "Генеральный директорГенеральный директор"). Если же это поле не заполнять вовсе, то и на печатной форме должность указана не будет.
Все это независимо от значения поля PositionSource: указывали и "Manual", и "Certificate". При этом в XSD написано, что если мы указываем "Certificate", то должность берется из сертификата, а в случае ее отсутствия - из поля Position.
Объясните, пожалуйста, что мы делаем не так, и как нужно, чтобы должность указывалась верно?

Примеры.
1. ИНН: 7730569579, DocID: 7726b9ba-677b-48c8-ab3e-0433b811d5ddd23de783-d757-4661-be18-22722127dab8
2. ИНН: 7730569353, DocID: b950729d-172a-4da2-8d34-5e0705b016f81e023e0f-9765-4fee-bbc1-c11b1afe9027

**Comment by GilimkhanovDenis** [comment]
Добрый день

Попробуйте для начала обновить компоненту до актуальной версии. Для подписания этих документов использовалась компонента [5.39.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.39.0)

**Comment by GilimkhanovDenis** [comment]
Проверил на версии 5.50.0 - не воспроизводится, должность не дублируется
