### ISSUE TITLE
Узнать кто принял приглашение

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#1008]
Можно ли с помощью компоненты узнать кто из пользователей принял приглашение контрагента к обмену?

**Comment by GilimkhanovDenis** [comment]
Добрый день

приглашение  было с вложением? Если да, то оно подписывается, этот документ можно найти и посмотреть данные подписи и пользователе

**Comment by GilimkhanovDenis** [comment]
В противном случае нет. Но думаю, в техподдержке могут посмотреть такую информацию

**Comment by dorexpro** [comment]
> Добрый день
> 
> приглашение было с вложением? Если да, то оно подписывается, этот документ можно найти и посмотреть данные подписи и пользователе

Интересует получение информации по произвольному приглашению вне зависимости от наличия вложения.



> В противном случае нет. Но думаю, в техподдержке могут посмотреть такую информацию

Техподдержка уже ответила, что только через официальный запрос на фирменном бланке организации, подписанном кровь десяти девственниц.

Странно, что такие сложности с элементарным функционалом. При том, что по документам любые эвенты доступны.

**Comment by GilimkhanovDenis** [comment]
@dorexpro

Увы, получить данные о принявшем приглашение без вложения сотруднике сейчас, кроме официального запроса и  просмотра логов, нет

Для сценария принятия приглашения с вложением такую информацию получить можно, найдя документ-вложение и получив данные о подписи

К сожалению, сейчас не вижу вариантов как можно закрыть вашу потребность изменениями только компоненты. Если получение информации о принявшем приглашение без оф. запроса - типовой сценарий, то рекомендую обратиться к вашему менеджеру, чтобы тот принёс и драйвил ваш запрос среди других задач разработки

**Comment by dorexpro** [comment]
Спасибо большое за ответ. Задача не критичная, будем решать организационными внесистемными методами.
