### ISSUE TITLE
Ошибка при выполнении метода AddDocument

### ISSUE THREAD

**Issue by KirillSagach** [diadoc/diadocsdk-1c-docs#1009]
Всем привет!
Делаем интеграцию 1С:Документооборот - Диадок. Используем AddIn компоненту версии "Diadoc_5_50_0_950_x64".
Проблем с авторизацией и просмотром доступных организаций нет.

Пытаемся отправить простенький документ: неформализованный счет на оплату.
У объекта Box вызываем метод CreatePackageSendTask2:
`SendTask = Box.CreatePackageSendTask2()`

Далее из него вызываем метод AddDocument с параметрами (функцию и версию для параметров взял из функции Box .GetDocumentTypes()):
`Document = SendTask.AddDocument("ProformalInvoice", "default", "v1")`

И тут же выскакивает ошибка: Отсутствует представление контента.

Никак не могу понять - с чем это связано. Обшарил документацию - там про такую ошибку ничего нет, на форумах тоже не встречал. Кто-нибудь может, пожалуйста, подсказать куда копать в данном случае?

Заранее спасибо

**Comment by GilimkhanovDenis** [comment]
Добрый день

В качестве аргументов метода можно указывать только те Тип, Функцию и Версию, у которых есть представление контента (см. например [FlatDocumentTypes](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/FlatDocumentTypeInfo.html).[Titles.GetItem(0)](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentTitle.html).**HasDynamicContent** из ответа [Box.GetFlatDocumentTypes()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.GetFlatDocumentTypes) или аналогичной структуры из [Box .GetDocumentTypes()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.GetDocumentTypes) )

Иначе контент нужно готовить самостоятельно. Для конкретно этого типа документа это может быть любой файл (doc, pdf, txt и т.д.), и, соответственно использовать метод [PackageSendTask2.AddDocumentFromFile(...)](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocumentFromFile) или [PackageSendTask2.AddDocumentFromBase64(...)](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocumentFromBase64)

пример подобной отправки [здесь](https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_post_document.html)
