### ISSUE TITLE
Новые форматы документов, чем отличается УПД (СЧФ) от UtdInvoice

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#101]
Отправляем документы через COM-компоненту.

1. Чем отличается УПД (UniversalTransferDocument) с функцией СЧФ (Invoice) от UtdInvoice?
2. Чем отличается УПД (UniversalTransferDocument) с функцией ДОП (Basic) от UtdTorg12, UtdAcceptanceCertificate?

**Comment by denver069** [comment]
UtdInvoice - это промежуточный тип для отправки счета-фактуры с приложенным к нему файлом xml в формате УПД с функцией СЧФ. Во внешней компоненте объект Document отражен как Invoice, а в результате Document.GetContent() возвращается UtdSellerContent.

UtdTorg12 - это промежуточный тип для отправки ТОРГ-12 с приложенным к нему файлом xml в формате УПД с функцией ДОП. Во внешней компоненте объект Document отражен как XmlTorg12, а в результате Document.GetContent() возвращается UtdSellerContent. В результате Document.GetBuyerContent возвращается UtdBuyerContent.

UtdAcceptanceCertificate - работает аналогично UtdTorg12 только для акта.

Нужно учесть тот факт, что при отправке титула покупателя по таким документам в результате CreateReplySendTask будет возвращаться UtdBuyerContent.

Отличительной особенностью таких Invoice, XmlTorg12 и XmlAcceptanceCertificate является то, что значение в поле AttachmentVersion = UniversalTransferDocument.

**Comment by geron4** [comment]
Какая цель создания таких документов? Теперь непонятно что использовать, например для Счет-фактуры - UniversalTransferDocument с функцией Invoice или UtdInvoice?

**Comment by LyubovZykova** [comment]
Даже если вы не переходите на УПД, т.е. не меняете свою учетную политику и не начинаете работать с документами типа УПД как 2 в 1, вам по законодательству необходимо к 1.07 обновить привести свои электронные СФ к формату, утвержденному Приказом ФНС от 24.03.2016 № ММВ-7-15/155@. Более подробно можно узнать из наших вебинаров по УПД, например, https://www.diadoc.ru/webinars/upd_diadoc

Соответственно, в зависимости от того, переходите вы полностью на работу с УПД, с внесением изменений в учетную политику, или нет, зависит то, какой объект компоненты вам нужно будет использовать - UniversalTransferDocument с функцией Invoice (если переходите на УПД) или UtdInvoice (если продолжаете работать с СФ, но нужно обновить формат согласно законодательству).

При этом технически, при получении контента покупателя или продавца (UtdSellerContent, UtdBuyerContent) вы получите одинаковые данные. Видимые различия в Диадоке будут заключаться в разных печатных формах документов - если используете UniversalTransferDocument, то увидите печатную форму УПД, а если UtdInvoice  - печатную форму СФ.

**Comment by geron4** [comment]
Спасибо! Отличный ответ, все стало понятно.
