### ISSUE TITLE
Подписание черновиков из Диадок

### ISSUE THREAD

**Issue by GulshatF** [diadoc/diadocsdk-1c-docs#1010]
Подскажите, пожалуйста, можно ли с помощью API диадок в 1С:УТ автоматически получать документы из раздела Диадока "Черновики" и подписывать их? (API пока не используем.)
Документы создаются не в 1С (в др. учетной системе), так что Контур.EDI не подходит. Универсальный модуль Диадок с черновиками не позволяет работать. Может, хоть API может дотянуться до черновиков?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Нет получения списка черновиков в компоненте нет. Когда сделаем новую ленту событий, тогда такая возможность появится.

Сейчас черновики можно получать, только зная идентификатор
