### ISSUE TITLE
ОШИБКА? Странные расхождения в статусах МЧД

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#1011]
**Добрый день.**

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
КПП2: 783450001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html

Текущая используемая версия: **COM x64 5.46.1.920**.

## Суть проблемы 
На некоторых документах, которые мы со своей стороны подписываем ЭП с МЧД или подписываем ИОП ЭП с МЧД, мы заметили странное расхождение в данных статусов проверки МЧД.

**И в первом, и во втором примере с нашей стороны для подписания ИОП использована одна и та же ЭП с одной и той же МЧД!**

### Пример №1:
Документ НЕ роуминговый.
PathURL = /c4390c58-315b-4323-a9b4-b5d87d6e868b/Document/Show?letterId=3946c5c9-739a-4632-96de-8d610a40d8a7&documentId=e761f726-d159-42a8-a27a-8820dc5493d4

Сводный статус МЧД:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/2afa8598-bd71-4b51-be4c-730eeed1576b)

На сайте (нас интересует выделенная «наша» доверенность):
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/2cf643ad-5437-447d-b771-bc0baf679d8b)

Данные статуса конкретной доверенности:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/f71e4a68-ec8e-4cca-aee4-1f198abb9d38)

Доверенность на сайте ФНС:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/129c9144-6a9e-4f0a-8f51-ffdeffe2a37b)

Т.е., судя по всему, всё хорошо – и у конкретной МЧД есть статус, что доверенность прошла проверку, и сводный статус такой же, и на сайте тоже самое по документу указано. И на сайте ФНС тоже указано, что всё с МЧД хорошо.

НО!

### Пример №2:
Документ роуминговый.
PathURL = /c4390c58-315b-4323-a9b4-b5d87d6e868b/Document/Show?letterId=4d69cad3-13cf-4687-a9d3-dd034f25c5ac&documentId=793bc592-f0d2-4df2-9d8b-f4a75ce88fb7

Сводный статус МЧД:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/7cbe95dd-7b56-4c66-844e-81eff2c337ee)

На сайте:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/1d6be614-b912-4d4f-af18-d1cacee42b31)

Данные статуса конкретной доверенности:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/a22fd60c-14cb-40b2-bae2-34e5b3f72c4b)

**И в первом, и во втором документе с нашей стороны для подписания ИОП использована одна и та же ЭП с одной и той же МЧД!**

Ранее мы уже обращались в Контур по поводу того, как интерпретировать статус МЧД = Неопределено. 

Нам было отвечено, что это состояние МЧД, когда она еще до конца не проверена и мы находимся в ожидании проверки статуса. И, когда проверка будет выполнена, то статус изменится и получит какое-то явное значение. 

На основании этого для таких документов мы у себя в системе на таких МЧД показываем, что по МЧД идет ожидание проверки статуса:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/0b319934-d2b7-4a98-afae-7df72af26e0e)

## Выявленная проблема

Получается очень странная штука – одна и та же конкретная МЧД в одних документах (судя по всему, НЕ роуминговых) в данных АПИ видна, как уже прошедшая проверку, а в других документах (судя по всему – роуминговых) видна, как только ожидающая проверку!

При этом, что еще удивительнее, сводный статус МЧД в обеих случаях указывает, что МЧД прошли проверку. И, похоже, что именно на основании этого статуса и формируется информация по статусу МЧД на сайте.

При этом для документов из примера №2 в ваших данных налицо явное расхождение между сводным статусом МЧД и «реальным» статусом конкретной МЧД, использованной при обработке документа! И это при том, что кроме этой МЧД для обработки документа никакие другие МЧД не использовались. Но все равно - статус самой МЧД один, а сводный (по данным только этой одной МЧД!) - другой!

Пока что у нас такое ощущение, что есть какая-то из двух ошибок:

1. Либо по каким-то документам неверно формируется сводный статус МЧД – почему-то не учитывая, что какие-то конкретные МЧД еще не прошли проверку (типа, _«ну это же роуминг – чёрт его знает, что там у них происходит, а всё остальное хорошо – поэтому пишем в сводный статус, что всё ОК»_).

3. Либо по каким-то документам неверно обрабатываются результаты проверки МЧД – когда проверка наконец-то прошла, происходит правильное формирование сводного статуса, но почему-то не обновляется состояние статуса самой конкретной проверенной МЧД.

В любом случае текущее поведение кажется нам явно ошибочным, т.к. даже в случае применения при обработке документа только одной ЭП с одной МЧД (см. ранее пример №2) сводный статус МЧД полностью расходится со статусом этой одной конкретной использованной МЧД. 

## Итого
Хотелось бы получить от вас какую-то информацию о том, действительно ли такое поведение – это выявленная ошибка (и тогда, когда она может быть исправлена)?

Или же это не ошибка, а в таких расхождениях статусов есть какой-то практический смысл? Тогда очень хотелось бы увидеть объяснение – как понимать такие расхождения и как на них правильно реагировать при обработке документов?

Спасибо.

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev, Добрый день

Исправлено в [5.51.2](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_51_2.html)
