### ISSUE TITLE
Использование согласующей подписи при использовании метода DssSign

### ISSUE THREAD

**Issue by JuliaVeselova2024** [diadoc/diadocsdk-1c-docs#1013]
Добрый День!
В API Контура есть метод DssSign и метод PostMessagePatch. Подскажите, можно ли их использовать совместно? Т.е. подписывать документ согласующей подписью при использовании сертификата формата DSS.

**Comment by GilimkhanovDenis** [comment]
Добрый день

В компоненте не используется метод DssSign

Возможно, Вам нужно задать вопрос в https://github.com/diadoc/diadocapi-docs/issues
