### ISSUE TITLE
ОШИБКА?! Проблема с подключением AddIn компоненты версии 5.51.3

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#1014]
Добрый день.

При попытке подключения новой версии компоненты Diadoc_5_51_3_965 при выполнении:

### DiadocInvoiceAPI_ = Новый("AddIn.Api.DiadocInvoiceAPI");

Получаем исключение:
### Тип не определен (AddIn.Api.DiadocInvoiceAPI)

Если откатиться на предыдущую версию Diadoc_5_51_2_962 или более ранние - проблем нет.

**Comment by JohnSergeev** [comment]
На всякий случай прикладываю файлы манифестов от 51-2 и 51-3:

51-2:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/85fc29cc-9077-4644-943f-f2e678914f36)

51-3:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/c90a73c3-f813-4a41-b60c-017ab8dbdd9e)

**Comment by JohnSergeev** [comment]
### Дополнительно:
А вы можете посмотреть, всё ли у вас в поставке хорошо в плане вирусов и т.п.?

У нас сегодня с утра массовые глюки пошли по ранее установленной компоненте Diadoc_5_51_2_962.

Пока еще не разобрались, пришлось откатится на старую Diadoc_5_46_1_920 - с ней всё нормально.

Но предварительно админы подозревают, что вашу компоненту стал Касперский рубить по какой-то причине.

Плюс у нас по ней начала стабильно вылетать ошибка:

>Имя сбойного приложения: rphost.exe, версия: 8.3.23.1865, метка времени: 0x64e2794f
Имя сбойного модуля: DiadocCom_5_51_2_962_x64.dll, версия: 5.51.2.962, метка времени: 0x66388e04
Код исключения: 0xc0000409
Смещение ошибки: 0x0000000000439878
Идентификатор сбойного процесса: 0x2a3c
Время запуска сбойного приложения: 0x01daaa5738bed609

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev Добрый день

Можете предоставить минидамп падения ?

> Имя сбойного приложения: rphost.exe, версия: 8.3.23.1865, метка времени: 0x64e2794f
> Имя сбойного модуля: DiadocCom_5_51_2_962_x64.dll, версия: 5.51.2.962, метка времени: 0x66388e04
> Код исключения: 0xc0000409
> Смещение ошибки: 0x0000000000439878
> Идентификатор сбойного процесса: 0x2a3c
> Время запуска сбойного приложения: 0x01daaa5738bed609

**Comment by JohnSergeev** [comment]
Эээ... 
Т.к. из-за него у нас все процессы встали, то мы откатились на версию Diadoc_5_46_1_920 - а то просто на проде не работало ничего!

Специально опять ставить сбойную версию на прод... не очень хочется, если честно. Она падает где-то "внутри" rphost без вылета в исключения 1С, и у нас просто все фоновые ЭДО отваливаются в никуда.

По поводу этой ошибки наши админы подозревают, что у Касперского обновились сигнатуры и он почему-то стал вашу компоненту за зараженную принимать. Я поэтому и спросил, нет ли у вас каких-либо проблем с заражением.
Они тоже дампы снять не успели, т.к. решили, что пока что нам важнее вернутся на стабильную версию, чтобы процессы работали нормально. 

А можно исправить проблему с подключением компоненты Diadoc_5_51_3_965 - мы уже ее исправленную накатим и посмотрим, как на ней пойдет? **А то может проблемы и не будет вовсе на обновленной версии?**

**Comment by GilimkhanovDenis** [comment]
Хорошо, понял

Пока воспроизвожу проблему подключения

**Comment by GilimkhanovDenis** [comment]
По поводу заражения: VirusTotal ничего не обнаруживает

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev 
Попробовал воспроизвести проблемы с подключением. Итоги такие:

- `ProgId = "AddIn.DiadocInvoiceAPI";    ПодключитьВнешнююКомпоненту(ProgID)` без проблем подключает зарегистрироанную компоненту что версии `5.46.1`, что версии `5.53.1`. И далее отрабатывает `DiadocInvoiceAPI_ = Новый(ProgID);`
- `ПодключитьВнешнююКомпоненту(ИмяМакета, "Api", ТипВнешнейКомпоненты.COM)` таким способом не удалось подключить ни `5.46.1`, ни `5.53.1`. Вероятно, как-то не так формирую макет. До `DiadocInvoiceAPI_ = Новый("AddIn.Api.DiadocInvoiceAPI");` даже не доходит логика

Притом, код Addin интерфейса на нашей стороне не менялся. Возможно. если предоставите пример обработки, с помощью которой можно будет воспроизвести проблему с тем, что старая версия подключается, а новая нет, можем посмотреть глубже. Пока похоже на то, что проблему нужно искать в особенностях подключения компонент из макета в 1С.

Ещё может помочь [API-Monitor](http://www.rohitab.com/apimonitor) - там будут видны вызовы системного API и можно лучше понять что пошло не так. Например успешная загрузка Addin из реестра выглядит так:
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/524dfb00-b30e-4827-a68a-b1b9ae54239d)

Лог этой утилиты можно прислать нам, если не получится по нему определить причину ошибку подключения самостоятельно

**Comment by GilimkhanovDenis** [comment]
Что касается падения, то одно нашёл - в отправке запроса аннулирования. Тот же это случай, что поймали Вы, не уверен

**Comment by JohnSergeev** [comment]
Добрый день.

Долго не получалось найти времени разобраться.

Заново загрузил с сайта компоненты, удалил зареганную DLL из кеша компонент 1С.
После чего снова успешно сработала регистрация и - О, чудо! - заработала и компонента.

Все стало подключаться нормально.

Либо 1С у меня как-то глюкнула при регистрации, либо при загрузке каким-то образом залился битый файл (что вероятнее).

**Возможно, вам стоит на странице с компонентами публиковать и контрольные суммы файлов. 
Чтобы при загрузке можно было проверить, что загрузилось без ошибок.**

Вопрос снимается, проблема решена.
Спасибо за содействие!

P.S.
Зато мы, похоже, нашли ошибку в другом месте. ))
Сегодня постараюсь опубликовать.

**Comment by GilimkhanovDenis** [comment]
Пожелание про чексуммы зафиксировал
этот тикет закрываю
