### ISSUE TITLE
Должность в строке 20 УПД.

### ISSUE THREAD

**Issue by chipdip-partner-1C** [diadoc/diadocsdk-1c-docs#1015]
Добрый день.

Подписываем подписью физ лица с МЧД.
Для подписания входящих документов используем:

Signer = КонтентТитула.Signers.AddItems();
Signer.SignerReference.BoxId = Organization.Guid;
Signer.SignerReference.CertificateThumbprint = ОтпечатокСертификата;

Что еще надо заполнить и где чтобы в строке 20 УПД появилась должность.

![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/165677667/f35885d4-6fb8-4355-b23f-4cf6ded0347b)

https://diadoc.kontur.ru/ba4b8cc3-3e6c-4298-a002-39e990f04ea2/Document/Show?letterId=0dae9b13-74d5-42da-9f68-139eb190bc70&documentId=30982404-7c90-4b79-9fee-022b55cc17a4

**Comment by GilimkhanovDenis** [comment]
Добрый день

Насколько понимаю, в `SignerReference.CertificateThumbprint` передаётся отпечаток сертификата, выданного на физлицо, и генерируется [Подписант](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=6482296)/[ФЛ](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=6482298) (Физическое лицо). Чтобы сгенерировался [Подписант](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=6482296)/[ЮЛ](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=6482297) (Представитель юридического лица) необходимо заполнить данные об МЧД.

Судя по UserDataXSD, в SignerReference есть поле с коллекцией для указания МЧД (PowerOfAttorney)
```
  <xs:complexType name="SignerReferenceWithPowerOfAttorney">
    <xs:sequence>
      <xs:element minOccurs="0" name="PowerOfAttorney" type="PowerOfAttorney" />
    </xs:sequence>
    <xs:attribute name="BoxId" type="string100" use="required">
      ...
    </xs:attribute>
    <xs:attribute name="CertificateBytes" type="xs:base64Binary" use="optional">
      ...
    </xs:attribute>
    <xs:attribute name="CertificateThumbprint" type="string100" use="optional">
      ...
    </xs:attribute>
  </xs:complexType>
```

**Comment by chipdip-partner-1C** [comment]
Добрый день.
Спасибо.
Не очевидное поведение.
У задания на ответные действия с документом указываем МЧД должно оттуда подтягиваться.

Для ищущих ответ:
Действительно чтоб должность появилось в 20 строке надо у Signer.SignerReference.PowerOfAttorney свойству UseDefault прописать "true", тогда появится должность.

**Comment by chipdip-partner-1C** [comment]
Добрый день.
Тот же вопрос по 970 приказу, что надо заполнить чтобы в поле 20 появилась должность.
Делаю через PatchTask.
