### ISSUE TITLE
Ограничения в перемещении документов могут порождать неудаляемые подразделения организаций

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#1018]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: COM x64 5.46.1.920.

На текущий момент у вас существует весьма странное на наш взгляд ограничение на количество возможных перемещений документа между подразделениями.

Какое-то время назад (~ 2 года назад) мы натыкались на то, что максимальное число перемещений равно 15 (пятнадцати).

Сейчас видим, что оно равно уже 50 (пятидесяти). 
Попытка выполнения операции перемещения возвращает ошибку:
>_Ошибка при вызове метода контекста (Move): Произошла исключительная ситуация (DocumentBase.Move): ##100[Ошибка сервера Диадок]code:409, HTTP error: Too many movements. Max allowed movements count is 50_

### Момент №1
**А с чем связано ограничение на количество перемещений?**

Единственное, что мы можем предположить - что это связано с хранением истории перемещений по всем вашим документам, которое, если не будет ограничений, может стать крайне объемным.

НО! 
Непонятно, почему бы тогда не сделать неограниченное количество перемещений, и просто хранить начальное подразделение (куда, например, изначально был получен документ) и историю последних 50 перемещений? Тогда и объем хранимых данных о перемещениях был бы конечен, и очень странного и явно искусственного запрета на перемещение некоторых документов просто бы не было!

### Момент №2
Наличие ограничений на перемещение документов само по себе не является большой проблемой, т.к. в реальности крайне малое число документов на "своем жизненном пути" "прыгает" между подразделениями 50 и более раз.

НО!
**Гораздо большей проблемой является странное следствие этого ограничения!**

Если попробовать удалить какое-то подразделение организации у вас на сайте, то, при наличии документов в этом подразделении будет предложено сперва переместить документы из этого подразделения в какое-то другое подразделение. И только после такого перемещения будет выполнено само удаление подразделения.

АПИ же, при попытке удаления подразделения, в такой ситуации вернет:
>_{
"Описание": "Department has documents"
}_

и не будет ничего удалять. 
И надо будет сперва методами АПИ переместить все документы из этого подразделения в какое-то другое подразделение. И уже потом удалить нужное подразделение.

И всё бы ничего... 
Вот только, если в подразделении оказался документ у которого вышел лимит перемещений, то при попытке удаления и перемещения на сайте - ничего в итоге не произойдет. Причем, что интересно, похоже, что у вас есть какой-то скрытый функционал, который предварительно проверяет, можно ли переместить все документы из подразделения. И, как только он нарывается на запрещенный к перемещению документ, то все перемещения отменяются, все остается на своих местах и подразделение не удаляется. Что еще забавнее, при этом пользователю не выводится никаких сообщений ни о чем!

Если же мы решим повторить этот функционал через АПИ, то нам придется выполнять предварительное перемещение документов из планируемого к удалению подразделения в какое-то другое... Но при попадании на попытку перемещения заблокированного документа - у нас его переместить не получится. Но остальные-то документы мы уже переместим!

**Тут появляются 2 вопроса:**
1. А как вы предварительно проверяете, что все документы из подразделения могут быть перемещены и не попадут на блокировку по количеству перемещений? В АПИ для компоненты и в http-api мы таких возможностей не нашли.
2. А как вообще возможно удаление подразделения в котором "завис" такой вот документ с ограничением на доступные перемещения?! Сейчас ни через сайт, ни с помощью АПИ такое подразделение **никак, из-за лежащего в нем неперемещаемого документа, удалить нельзя!**

**Не кажется ли вам текущая реализация, скажем так, несколько странной в архитектурном плане?**

Очень бы хотелось увидеть ваши комментарии по этому поводу.

### Интересует:
1. Почему нельзя избавиться от странного ограничения на количество перемещений, сделав хранение истории последних N перемещений?
2. Как удалить подразделение, которые удалить надо, но в котором случайно "завис" такой неперемещаемый документ, по которому закончилось число доступных перемещений?
3. Как вы предварительно понимаете возможно ли выполнить перемещение всех документов подразделения до самого этого перемещения? Мы не видим возможности текущими методами АПИ организовать подобное поведение.

Спасибо.

**Comment by ZalesskayaLesya** [comment]
Добрый день.
По каждому документу записывается лента событий (https://developer.kontur.ru/Docs/diadoc-api/instructions/docflow.html). Уже хранящаяся в ней информация не может быть изменена или удалена, ее можно только дополнить.

Для удаления подразделения с "зависшим" документом, пожалуйста, напишите комментарий с идентификатором этого подразделения.

**Comment by GilimkhanovDenis** [comment]
Тикет закрываю

Если нужно удалить "неудаляемое" подразделение предлагаю либо здесь в комментарии, либо в новом тикете, либо через менеджера сообщить идентификатор(ы) подразделения(-й)
