### ISSUE TITLE
Не удается получить динамический контент УПД

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#1019]
Версия компоненты AddIn x86 5.51.3.965. Используется в 1С 7.7

`1.Document=Box.GetDocumentById(MessageId+EntityId)`
`2.DynamicContent=Document.GetDynamicContent("Seller")`
`3.Content=DynamicContent.UniversalTransferDocumentWithHyphens`

Первые два шага отрабатываются корректно, на третьем шаге 1С зависает. 

На версии AddIn x86 5.49.1.933 всё работает корректно, в чём может быть проблема?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Нужен дамп зависшего процесса

**Comment by evgen421** [comment]
Здравствуйте. Обнаружилась интересная особенность, вот так можно получить значение:
`ОписаниеОбъекта = Рефлектор.Describe(DynamicContent)`
`Content = ОписаниеОбъекта.GetProperty("UniversalTransferDocumentWithHyphens")`
А так: `Content=DynamicContent.UniversalTransferDocumentWithHyphens` - нет!
Так можно:
`ОписаниеОбъекта = Рефлектор.Describe(Content)`
`Table = ОписаниеОбъекта.GetProperty("Table")`
А так: `Table=Content.Table` - нет!

**Comment by mar-264** [comment]
У нас аналогичная проблема при использовании библиотеки Diadoc COM x86 5.51.3.965 и всех предыдущих 5.51.* . При обращении к IUtd:UniversalTransferDocument или IUtd:UniversalTransferDocumentWithHyphens происходит Runtime ошибка, приводящая к аварийному завершению программы. Из сообщений программы при аварийном завершении: Fault address:  77770B82 01:0013FB82 C:\WINDOWS\System32\KERNELBASE.dll
А если использовать Описание объекта через Рефлектор, при обращении к GetProperty("UniversalTransferDocumentWithHyphens") - ошибки нет.

**Comment by evgen421** [comment]
mar-264, у вас тоже 1С 7.7?

**Comment by mar-264** [comment]
> mar-264, у вас тоже 1С 7.7?

Нет, у нас своя программа.

**Comment by evgen421** [comment]
Здравствуйте Денис, видимо это глобальная проблема и вы наверняка сможете воспроизвести её у себя.

**Comment by NickZubashevskiy** [comment]
Добрый день!

Попробовали воспроизвести у себя: на компоненте версии 5.51.3 x86, в 1c7.7 - баг не воспроизводится. Также было проверено через другое окружение, не 1с, с x86 и x64 версиями компоненты - результат тот же. 

В связи с этим для того, чтобы было возможно найти и устранить баг необходим дамп зависшего процесса, в идеале также нужен дамп процесса до зависания. 

[mar-264](https://github.com/mar-264), дамп падения вашей программы также может существенно помочь устранить баг,  т. к. в вашем случае поведение несколько отличается

**Comment by evgen421** [comment]
Здравствуйте. 1С перестала зависать, просто ничего не происходит. Сделал два мини дампа, один перед получением контента другой сразу после.
[1cv7s.exe_240625_102955.dmp](https://github.com/user-attachments/files/15964292/1cv7s.exe_240625_102955.dmp)
[1cv7s.exe_240625_102831.dmp](https://github.com/user-attachments/files/15964293/1cv7s.exe_240625_102831.dmp)

**Comment by GilimkhanovDenis** [comment]
@evgen421 К сожалению, для ситуации, когда ничего не происходит, довольно проблематично найти в дампе полезную информацию.
Попробую покопать что в 1С 7.7 может происходить при обращении к интерфейсу `IDispatch`. Давайте попробуем понять сценарий:
- зависания и невозврат результата при обращении через точку происходят случайно для одного и того же документа или для разных? Возможно, будут полезны ссылки на эти документы
- Пробовали перезагрузить 1С?
- Есть разница на какой машине запускается интеграция?

**Comment by GilimkhanovDenis** [comment]
@mar-264 У вас, скорее всего, что-то другое - у вас приложение крашится, притом где-то в `KERNELBASE.dll`. Здесь нужен дамп.

Было бы полезно узнать какую платформу/язык используете и пригодился бы листинг кода для воспроизведения ошибки

**Comment by GilimkhanovDenis** [comment]
Смог получить падение в 1С 7.7, но не факт, что это то же, с чем столкнулись вы

**Comment by evgen421** [comment]
Здравствуйте Денис. Невозврат результата происходит для любого УПД. Проблема возникла сразу на рабочем сервере, как только установил свежую версию компоненты, причем был именно невозврат  результата, а не зависание 1С. На рабочем сервере пришлось откатиться на старую версию компоненты, а тестирование новой версии проводить на тестовом сервере. С начала на тестовом были зависания, затем просто невозврат результата, поэтому сделать дамп зависшей 1С не удалось, так как зависания на момент, когда предложили сделать дамп, прекратились.

**Comment by mar-264** [comment]
Добрый день Денис. Проблема с новой библиотекой  Diadoc COM x86 5.52.0.978 так же сохраняется. Дамп выгрузила в облако: [https://cloud.mail.ru/public/Ww8o/AJcUrbVHr](url) 
язык Progress 10.1B03
код примерно такой, последняя строка приводит к падению:
vDocumentChild = iDocument:GetDynamicContent("Seller")
для форматов не Hyphens: 
vContent = vDocumentChild:UniversalTransferDocument.
та же ошибка для УПД формата Hyphens:
vContent = vDocumentChild:UniversalTransferDocumentWithHyphens.
(тут iDocument - это component-handle на IUtd)

**Comment by evgen421** [comment]
Здравствуйте. Тоже проверил на версии 5.52.0.978, проблема осталась.

**Comment by GilimkhanovDenis** [comment]
Исправление будет на этой неделе

**Comment by GilimkhanovDenis** [comment]
@evgen421 @mar-264 

Должно исправиться на [5.52.1](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_52_1.html)
[Ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)

Отпишитесь, пожалуйста, по результатам

**Comment by evgen421** [comment]
Здравствуйте Денис. Проверил на версии 5.52.1, теперь работает корректно! Спасибо!

**Comment by mar-264** [comment]
> @evgen421 @mar-264
> 
> Должно исправиться на [5.52.1](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_52_1.html) [Ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)
> 
> Отпишитесь, пожалуйста, по результатам

Да, с новой версией работает, спасибо!
