### ISSUE TITLE
Подписание извещения о получении одного документа

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#102]
Сделана интеграция со своей конфигурацией 1С 8.3.
Подскажите, пожалуйста, входящий счет-фактура (или входящий УПД) загружен в 1С есть id документа "76d83345-bc8d-4abb-89f6-a4e3a2f394bca6568f2e-6966-48f1-a1db-fa508d3ac3ab".
Какими методами COM можно подписать извещение о получении документа, именно конкретного документа, а не всех во входящем журнале.
С остальными видами документа все работает, с этим видом не могу разобраться, как именно для конкретного документа подписать извещение о получении.
Помогите, пожалуйста.

**Comment by denver069** [comment]
В таком случае можно использовать метод [Document.SendReceiptsAsync](http://diadocsdk-1c.readthedocs.io/ru/latest/SendReceiptsAsync.html), для УПД с функцией СЧФ он тоже [есть](http://diadocsdk-1c.readthedocs.io/ru/latest/SendReceiptsAsync-(Utd).html). Объект Document можно получить методом [Organization.GetDocumentById](http://diadocsdk-1c.readthedocs.io/ru/latest/GetDocumentById.html).

Для работы с этим методом обязательно обновите внешнюю компоненту до версии не младше 5.17.0.201, т.к. в этой версии в методе была исправлена ошибка отправки извещений для Invoice, InvoiceRevision, InvoiceCorrection.
