### ISSUE TITLE
Проблема с определением всех марок в УПД нового формата 970

### ISSUE THREAD

**Issue by mar-264** [diadoc/diadocsdk-1c-docs#1021]
Добрый день!
Версия библиотеки Diadoc COM x86 5.46.1.920
В УПД имеется несколько марок:
<ТаблСчФакт>
      <СведТов НомСтр="1" НаимТов="Товар1" ОКЕИ_Тов="796" НаимЕдИзм="шт" КолТов="30" ЦенаТов="200" СтТовБезНДС="6000" НалСт="20%" СтТовУчНал="7200">
        <СвДТ КодПроисх="980" НомерДТ="123456" />
        <ДопСведТов ПрТовРаб="5" ДопПризн="Приз" КрНаимСтрПр="ДопСведТов-КрНаимСтрПр" НадлОтп="102" СортТов="СортТов" СерияТов="ДопСведТов-СерияТов" ГТИН="10000057074365" КодВидТов="1111111111">
          <НомСредИдентТов>
            <НомУпак>010456888888888321KkWb4K=8005150000</НомУпак>
            <НомУпак>010456888888888321sGZmYfF8005150000</НомУпак>
            <НомУпак>010456888888888321chkg8vE8005150000</НомУпак>
          </НомСредИдентТов>
        </ДопСведТов>
        <Акциз>
          <БезАкциз>без акциза</БезАкциз>
        </Акциз>
        <СумНал>
          <СумНал>1200</СумНал>
        </СумНал>
      </СведТов>
...
Но не удается определить все эти марки, найти все данные, которые заданы в каждом тэге <НомУпак>, удается определить только первое значение <НомУпак>010456888888888321KkWb4K=8005150000</НомУпак>.
Обращение происходит следующим образом:
IUtd:GetDynamicContent("Seller"):UniversalTransferDocument:Table:Item:GetItem(vi):ItemIdentificationNumbers:ItemIdentificationNumber:GETITEM(vii):items:GETITEM(viii):PackageId
Во всех коллекциях, к которым обращаемся, только одно значение - IValueCollection:Count = 1 (переменные vi, vii, viii равны 0).
Прошу подсказать, как найти все значения <НомУпак>, возможно они лежат в какой-то еще коллекции?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Можете дать ссылку на документ?

**Comment by mar-264** [comment]
> Добрый день
> 
> Можете дать ссылку на документ?

https://diadoc-test.kontur.ru/36622be6-38b3-4b2a-8917-9ed082c72d3f/Document/Show?letterId=48782aaa-d857-4a9a-abcf-991d9b5bc275&documentId=8b236b51-a3df-433e-a226-4305f1c98231

**Comment by NickZubashevskiy** [comment]
Добрый день!
Проблема была решена, фикс выйдет в следующем релизе

**Comment by GilimkhanovDenis** [comment]
@mar-264 
Попробуйте [версию 5.52.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_52_0.html)
[ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)
