### ISSUE TITLE
"Поле объекта не обнаружено (MyEmployee)"

### ISSUE THREAD

**Issue by 186elitan** [diadoc/diadocsdk-1c-docs#1023]
Добрый день!
Пытаемся прочитать MyEmployee, получаем ошибку: "Поле объекта не обнаружено (MyEmployee)"
Код:
DiadocApi_ = Новый("AddIn.DiadocInvoiceAPI");
DiadocApi  = DiadocApi_.CreateObject();

//Считываем КлючРазработчика
...
DiadocApi.ApiClientId = КлючРазработчика;
DiadocApi.ServerUrl   = "https://diadoc-api.kontur.ru:443";
Certificates = DiadocApi.GetPersonalCertificates();

//Находим ОтпечатокСертификата
...
DiadocConnection = DiadocApi.CreateConnectionByCertificate(ОтпечатокСертификата);		

//Находим BoxId
...
Organization = DiadocConnection.GetOrganizationById(BoxId);		
dd_MyEmployee = Organization.MyEmployee; //Получаем ошибку: "Поле объекта не обнаружено (MyEmployee)"

**Comment by GilimkhanovDenis** [comment]
Добрый день

Проверьте, что подключилась компонента `5.37.0+`, вызвав метод [DiadocAPI.GetFullVersion()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DiadocAPI.html)

Обычно такие ошибки связаны с тем, что подключена старая компонента или возникли какие-то проблемы с регистрацией компоненты

**Comment by 186elitan** [comment]
Предварительно была установлена Diadoc_5_51_3_965_x64.dll.
Как проверить версию активной компоненты?

**Comment by GilimkhanovDenis** [comment]
вызвав метод [DiadocAPI.GetFullVersion()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DiadocAPI.html)

**Comment by 186elitan** [comment]
Спасибо, вопрос снят.
Проблема действительно в регистрации компоненты.
