### ISSUE TITLE
Обращение к Result метода SendAsync

### ISSUE THREAD

**Issue by gnp900** [diadoc/diadocsdk-1c-docs#1025]
Формируются документы XML, создается CreatePackageSendTask2() заполняется данными, прикрепляется файл и отправляется методом SendAsync(). Ожидали получить Флаг завершения IsCompleted - означающий что метод завершил свою работу, и Result - произвольного типа, содержащий ошибки, если значение REsult принимает тип COMОбъект, все хорошо. Но вот когда там содержится текст, Тип пустой, те он не определён и обратиться к нему не получается никак, возникает ошибка
К примеру 
СтрНайти(ОтправленныеДокументы.Result,"ошибка")
Возвращается "{(1)}: Ошибка при получении значения атрибута контекста (Result)

**Comment by GilimkhanovDenis** [comment]
Добрый день

Можете ещё раз написать какой какой результат в получаете и какой ожидаете получить и в каком сценарии

Если возникает ошибка, то в каком сценарии (возможно листинг).

Пока догадка, что в Result ожидаете строку, если произошла ошибка. Если это так, то в поле лежит не строка, а сама ошибка и обращение к полю вызовет проброс этой ошибки

**Comment by gnp900** [comment]
Добрый день, прошу прощения что долго отвечал, да мы пытаемся обратиться к Result и получить значение, выпадает в ошибку

**Comment by gnp900** [comment]
Пытаюсь получить строку из Result, ну или прочитать ошибку, получаю краш программы
![Result](https://github.com/user-attachments/assets/0b6d422c-952e-42b3-ab4e-c5debeca2fcd)

Result	Произошла исключительная ситуация (AsyncResult.Result): ##100[Ошибка сервера Диадок]code:409, HTTP error: Recipient forbids to receive messages from blocked senders	

Я вижу что тип пустой у Result

**Comment by GilimkhanovDenis** [comment]
В результате лежит ошибка. а не строка, как уже писалось ранее

Чтобы не получать ошибку вам нужно ["подружить" свой ящик и ящик контрагента](https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_trust_counteragent.html)

**Comment by gnp900** [comment]
То что подружить ящики это понятно, но там же к примеру будет ошибка в файле к примеру
Если это ошибка, как её обработать программно? Или никак?

**Comment by GilimkhanovDenis** [comment]
Кажется, так это пишется в 1С:

```
Попытка
    СделатьЧтоТо(AsyncResult.Result);
Исключение
    СделатьЧтоТоНаОсновеТекстаОшибки(ОписаниеОшибки());
КонецПопытки;
```

**Comment by gnp900** [comment]
Вот в том то и дело, что при обращении к Result (AsyncResult.Result), возникает ошибка {(1)}: Ошибка при получении значения атрибута контекста (Result), что означает "Ошибка при получении значения атрибута контекста указывает на невозможность прочитать значение атрибута объекта в силу его отсутствия, либо отсутствия прав на его чтение."

**Comment by GilimkhanovDenis** [comment]
Это если вы в конфигураторе смотрите значение поля - обращение к полю прокидывает ошибку.

Если ам нужно в логике программы обработать ошибку, то это делается через `Попытку...Исключение`
