### ISSUE TITLE
Странная проблема в работе COM-компоненты версии 5.51.3.965 (было на 5.51.2 и снова вылезло)

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#1027]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: COM x64 5.51.3.965.

К сожалению, у нас опять вылезла проблема с COM-компонентой версии x64 5.51.3.965 практически полностью совпадающая с описанной ранее [здесь](https://github.com/diadoc/diadocsdk-1c-docs/issues/1014):
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/b73c854b-b9d9-4cb1-9aee-6b63de346f6f)

### Более детально:

**Хронология:**

1.	13.06.2024 примерно в 16-00 мы обновляем на сервере COM-компоненту ЭДО. С версии x64 5.46.1.920 на версию x64 5.51.3.965. Все работает нормально.
2.	С 13.06.2024 16-00 по 18.06.2024 ~00-20 всё работает нормально и без проблем.
3.	С 18.06.2024 ~00-20 начинает падать со следующими симптомами:
a.	rphost работает, фоновые работают, логи пишутся…
b.	НО! rphost после запуска живет около 1-й минуты (с секундомером не засекал, но что-то типа того) и после его Винда убивает.
c.	При этом в журнале событий постоянно фиксируется одна и та же ошибка:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/022471c2-a063-46e3-900f-e4174b42e553)

 

d.	Затем rphost запускается снова, опять начинают работать фоновые и писаться логи… и опять все через ~ 1 минуту rphost подыхает, а в журнал записывается такая же ошибка. 

Т.е. мы переходим на пп. а) и начинается всё с начала.

Частота появления ошибок:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/af22bf53-dfc6-4fc9-bb00-a9cae463d42d)

**Интересно и странно:**
1.	Отменили регистрацию компоненты (regsvr32 /u), перезапустили сервер.
2.	Он минут 7-8 поработал, фиксируя ошибки в логи ЭДО (что логично, ругался на невозможность выполнения методов незарегистрированной компоненты).
3.	Зарегистрировали ТУ ЖЕ САМУЮ компоненту (regsvr32), перезапустили сервер.

При этом я на всякий случай сравнил содержимое DLL компоненты на сервере и в полученном от вас архиве – файлы совпадают.

После этого около 8-9 минут все работало нормально, без проблем, а затем опять начало падать с теми же симптомами.

Я в разное время работы rphost’a снял 3 дампа: https://disk.yandex.ru/d/_9iJvMEwh3M7vQ
Может быть в них вы что-то увидите.

Затем откатил компоненту на старую стабильную версию x64 5.46.1.920.
По ней подобных проблем не возникает. На текущий момент работает она.

Очень смущает, что проблемы начались не сразу, а, как и с прошлой попыткой (!), примерно спустя 4 дня.

### Может быть это что-то у нас?
Будто какая-то наша защита (антивирус, брандмауэр?) на компоненту посмотрели-посмотрели и решили её все-таки в черный список занести.

В прошлый раз я больше думал на антивирус (и наши админы тоже), но антивирус на сервере ничего не находит. И вы в прошлый раз тоже вроде на вирусы всё проверяли и вроде ничего не нашли.

Не может ли это быть какое-то поведение нашей сетевой защиты? Компонента активно читает и передает данные по сети (ЭДО!), может её активность какой-то защите кажется подозрительной?

С другой стороны, почему тогда стабильно работает предыдущая версия x64 5.46.1.920? 

Нашим специалистам я всю эту информацию тоже передал, может быть они что-то найдут.

### Может быть что-то у вас?

Может быть все-таки что-то с самой компонентой?

**У вас в компонентах после 5.46.1.920 ничего в работе с сетью не поменяли? Может новые компоненты что-то дополнительное отправляют/получают? Как-то взаимодействуют с какими-то новыми серверами, с которыми 5.46.1.920 не работала?**

Очень хотелось бы разобраться в проблеме, т.к. практически впервые за уже многие годы столкнулись с ситуацией, когда мы по факту просто не можем нормально обновиться!

Спасибо.

**Comment by JohnSergeev** [comment]
Дополнение.

Админы посмотрели тех. журнал, но нашли только подтверждение, что rphost падает. 
Ничего особо криминального не увидели.

```
June 18th 2024, 10:12:33.993	12:33.993267-0,CLSTR,2,process=rmngr,p:processName=RegMngrCntxt,p:processName=ServerJobExecutorContext,OSThread=6656,t:clientID=60228,t:applicationName=AgentProcess,t:computerName=adm-1c-m01,Event=Register rphost,Txt=processID:6cc77d28-9d81-4777-bd7f-022197a98988 hostName:adm-1cedo.partner.ru
```

О том, что регистрация прошла успешно, говорит событие:
```
June 18th 2024, 10:12:33.993	12:33.993248-0,CLSTR,2,process=rmngr,p:processName=RegMngrCntxt,p:processName=ServerJobExecutorContext,OSThread=6656,t:clientID=60228,t:applicationName=AgentProcess,t:computerName=adm-1c-m01,Event=Process requirements changed,Registered=(1):6cc77d28-9d81-4777-bd7f-022197a98988(adm-1cedo.partner.ru);
```
Дальше происходит некая деятельность этого процесса, и спустя какое-то время видим следующее:
```
June 18th 2024, 10:13:06.650	13:06.650225-0,CLSTR,2,process=rmngr,p:processName=RegMngrCntxt,p:processName=ServerJobExecutorContext,OSThread=10056,t:clientID=60395,t:applicationName=AgentProcess,t:computerName=adm-1c-m01,Event=Unregister rphost,Txt=processID:6cc77d28-9d81-4777-bd7f-022197a98988 hostName:adm-1cedo.partner.ru
```
Это произошла отмена регистрации рабочего процесса в кластере, а затем:
```
June 18th 2024, 10:13:06.650	13:06.650133-0,CLSTR,2,process=rmngr,p:processName=RegMngrCntxt,p:processName=ServerJobExecutorContext,OSThread=10056,t:clientID=60395,t:applicationName=AgentProcess,t:computerName=adm-1c-m01,Event=Process requirements changed,Obsolete=(1):6cc77d28-9d81-4777-bd7f-022197a98988;
```
Obsolete – говорит о том, что данный рабочий процесс устарел, что логично, ведь мгновением ранее кластер отменил его регистрацию, а значит состав рабочих процессов требуется актуализировать.

**Comment by GilimkhanovDenis** [comment]
Есть предположение что происходит (вызов std::abort() внутри Protobuf). Исправим в ближайшем фиксе (попробуем выпустить на этой неделе или в начале следующей)

P.S. В дампах, к сожалению, полезной информации не увидел - компонента там уже выгружена или ещё не загружена. Но если я что-то в них пропустил, что увидят ваши спецы, то хотел бы узнать как это тоже увидеть

**Comment by JohnSergeev** [comment]
Ну пока наши смотрят. Плюс мы пробуем все-таки пробить вариант, что компонента стала стучаться по каким-то сетевым адресам, которые блокируют наши файерволы и далее грохается на ошибках работы с сетью.

Ну, т.е. типа возможный сценарий, когда:
1. Мы блокируем что-то, куда новые версии компоненты лезут, чтобы что-то прочесть или передать
2. А в компоненте есть какая-то проблема с обработкой сетевых ошибок, приводящая к итоговой проблеме.

Это просто гипотеза, но решили попробовать и ее исключить.
Пока ждем ответа сетевиков на вопрос типа:

> Замечали ли ваши системы контроля сетевой активности / файерволы какой-то подозрительный траффик с сервера / на сервер ЭДО в период с 00-00 по 10-00 18.06.2024 по Владивостоку? Блокировали ли вы какую-то сетевую активность с этого сервера в указанный период? Если да, то какую?

Вдруг что-то обнаружим. А, если нет, то всё равно хорошо - закроем неверную гипотезу.

Спасибо за оперативность в рассмотрении проблемы!

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev
Попробуйте [версию 5.52.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_52_0.html)
[ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)
