### ISSUE TITLE
ОШИБКА! Проблемы при получении данных МЧД (Возможно, это то из-за чего возникла #1027)

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#1029]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: COM x64 5.46.1.920.

Мы нарвались на очень странную вещь, которая, возможно, является причиной проблем, возникающих [здесь](https://github.com/diadoc/diadocsdk-1c-docs/issues/1027).

### Суть:

Мы отправили исходящий документ:
PathURL = /c4390c58-315b-4323-a9b4-b5d87d6e868b/Document/Show?letterId=32b9e41b-14dd-4837-9117-5e0345fe12b8&documentId=668bad7b-fd58-49b5-8e24-e0cc0d642a4e

Он прекрасно от нас ушел и мы видим его в исходящих.

При попытке его обработки в 1С мы добираемся до данных МЧД в нем... и вызов GetPowersOfAttorney()

### На версии компоненты x64 5.46.1.920:
Приводит к вылету в исключение 1С со следующей ошибкой:
>Ошибка при вызове метода контекста (GetPowersOfAttorney): Произошла исключительная ситуация (DocumentBase.GetPowersOfAttorney): Ошибка при конвертировании FILETIME в SYSTEMTIME]. 

## Приводит к падению 1С!

Т.е. мы не падаем в исключение, а просто 1С вылетает!
При локальной отладке, например, это выглядит так, что при выполнении строки с GetPowersOfAttorney() указатель текущей строки выполнения никуда не перемещается, "ничего не происходит", но конфигуратор остается запущенным, а запущенный сеанс 1С предприятия просто исчезает.

И вот тут мы подумали, что, возможно, это та ошибка из-за которой у нас возникла проблема, описанная в [#1027](https://github.com/diadoc/diadocsdk-1c-docs/issues/1027) и ранее возникавшая с версией 5.51.2.962.

Просто, возможно, что запускаемое фоновое по обработке документов в самом начале работы "нарывалось" на обработку именно этого документа (ну просто так получилось) - и при попытке чтения данных МЧД по этому документу - **убивало запущенный сеанс!**

Это, конечно, всего лишь гипотеза.
Но проблема с GetPowersOfAttorney() имеет место и 100% у нас воспроизводится.

Плюс по ней хотелось бы не только решения с вылетом 1С, но и какого-то решения/объяснения ситуации с ошибкой 
>Произошла исключительная ситуация (DocumentBase.GetPowersOfAttorney): Ошибка при конвертировании FILETIME в SYSTEMTIME].

Т.к. тоже совершенно непонятно, что это, из-за чего и что с этим делать.

Очень надеемся на оперативную проверку и исправление проблемы.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Воспроизвёл. У МЧД время начала действия очень странное - `0119-12-31​T21:00:00.000Z` (в тиках `37551924000000000`)

Пока думаю что с этим делать

**Comment by JohnSergeev** [comment]
Ага! Посмотрим, возможно, с датой МЧД мы накосячили внутри учетной системы или при передаче.

**Но в любой ситуации по идее не должно же быть падения 1с в такой ситуации!**

Да и какая бы дата не была в данных МЧД - по идее же ее нужно просто передать / показать, как есть.
А уже принимающая сторона на нее ругнется, если там ерунда какая-то. И, например, не будет подписывать документ.

Т.е. по идее (наивное мнение):
1. При такой ситуации не должно быть вылета 1С в никуда!
2. При такой ситуации нужно просто передавать дату как есть. Что указали, то и указали. Тот, кто будет обрабатывать данные этой МЧД приложенной к документу должен будет по идее, например, отказаться подписывать документ, т.к. дата "кривая".

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Полностью согласен с Вами

**Comment by GilimkhanovDenis** [comment]
К слову, это ошибка относится к МЧД, приложенной получателем, а не Вами (отправителем)

**Comment by JohnSergeev** [comment]
Ну, тогда, когда почините, и мы сможем прочитать данные МЧД по этому документу - проверим, правильно ли у нас на такую МЧД отработает логика, что МЧД "кривая".

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev
Попробуйте [версию 5.52.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_52_0.html)
[ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)
