### ISSUE TITLE
Ошибка или так должно быть, тип документа, COM-Компонента 5.17.0.201

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#103]
Оправляем документы пакетом, формируем в пакете документы с типами "UtdAcceptanceCertificate", "UtdInvoice", после отправки методом: 

DocumentPackage = PackageSendTask.Send();

Изучая DocumentPackage, видим, что типы документов указаны "XmlAcceptanceCertificate", "Invoice"
DocumentPackage.Documents.GetItem(0).type
DocumentPackage.Documents.GetItem(1).type

Т.е. произошла подмена типов. 
Это нормально? Или это ошибка?

**Comment by denver069** [comment]
Это нормально, тип документа будет старым (XmlAcceptanceCertificate, XmlTorg12 или Invoice) а тип контента будет UniversalTransferDocument.
