### ISSUE TITLE
Обновление компоненты

### ISSUE THREAD

**Issue by Artem040401994** [diadoc/diadocsdk-1c-docs#1030]
Добрый день, подскажите, как на https://developer.kontur.ru/docs/Diadoc/COM/Downloads.html скачать более ранние версии компоненты? Вижу, что скачать можно только актуальную

**Comment by GilimkhanovDenis** [comment]
Добрый день

Скопируйте ссылку для скачивания конкретной  версии и уберите последнюю часть пути (имя файла с расширением)

**Comment by Artem040401994** [comment]
Понял, спасибо
