### ISSUE TITLE
Ошибка при выполнении метода DocumentBase.CreateReplySendTask2

### ISSUE THREAD

**Issue by Artem040401994** [diadoc/diadocsdk-1c-docs#1031]
Добрый день, подскажите пожалуйста, в какую сторону копать.
Ошибка:
Произошла исключительная ситуация (DocumentBase.CreateReplySendTask2): Нет документов, для которых возможно формирование ответного задания выбранного типа.
Именно с УКД такая проблема. Версия компоненты 5_40_0_869, при чем начинал с 5_34_2_707 и обновлял поступательно, но ошибка не уходила. На последней версии ушла эта ошибка, но потом много других сыпется. DocumentID: cbfe5eb1-0e37-4c23-acbb-191ed414a2f54e31e43a-1a71-4f6c-8a4f-ccbcb1b7e9bb. 

![Безымянный](https://github.com/diadoc/diadocsdk-1c-docs/assets/60171225/e824d057-1b8e-47a0-93b2-bf4dc875a0bd)

**Comment by GilimkhanovDenis** [comment]
Добрый день

С каким типом создаёте ReplySendTask2. Какие ошибки потом возникают?

**Comment by Artem040401994** [comment]
Document.CreateReplySendTask2("AcceptDocument") - вот так обращаюсь, где Document это DocumentBase.
Вот сейчас снёс старую версию, поставил 5_51_3_965.
И вот такая ошибка:
Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 4, Position: 282, /UniversalCorrectionDocumentBuyerTitle[1]/Signers[1]/SignerDetails[1]/@SignerPowers: The 'SignerPowers' attribute is invalid - The value '2' is invalid according to its datatype 'Integer' - The Enumeration constraint failed.
И я бы с удовольствием  указал с типом Integer, но только в SignerDetails типы строка, и хоть число подставляй, всё равно преобразует в строку.
![Uploading Безымянный.jpg…]()

**Comment by GilimkhanovDenis** [comment]
Эта ошибка означает, что в SignerPowers заполнено значение, которого не может быть для этого типа документа

**Comment by Artem040401994** [comment]
а какое может? Пробовал и не заполнять

**Comment by GilimkhanovDenis** [comment]
Из UserDataXSD:

```
  <xs:complexType name="ExtendedSignerDetails_CorrectionBuyerTitle736">
    <xs:complexContent mixed="false">
      <xs:extension base="ExtendedSignerDetails736">
        <xs:attribute name="SignerPowers" use="required">
          <xs:annotation>
            <xs:documentation>ОблПолн - Область полномочий</xs:documentation>
            <xs:documentation>
							0 - лицо, ответственное за подписание счетов-фактур;
							3 – лицо, ответственное за оформление свершившегося события;
							6 - лицо, совершившее сделку, операцию и ответственное за подписание счетов-фактур;
							29 - лицо с иными полномочиями
						</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:enumeration value="0" />
              <xs:enumeration value="3" />
              <xs:enumeration value="6" />
              <xs:enumeration value="29" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
```

**Comment by Artem040401994** [comment]
Понял, помогло, спасибо
