### ISSUE TITLE
При отправке УКД с функцией КСЧФДИС - ошибка

### ISSUE THREAD

**Issue by LevKrykov** [diadoc/diadocsdk-1c-docs#1032]
Здравствуйте. 
Прошу помощи.
При отправке УКД с функцией КСЧФДИС - ошибка:
PackageSendTask2.Send: ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: Невозможно отправить документ с функцией ДИС/КСЧФДИС/СвИСРК/СвИСЗК. Измените функцию документа или выберите другой тип документа

**Comment by GilimkhanovDenis** [comment]
Предположу, что функция в контенте отличается от функции, указанной в параметрах [метода добавления документа в таску](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocument)

**Comment by LevKrykov** [comment]
> Предположу, что функция в контенте отличается от функции, указанной в параметрах [метода добавления документа в таску](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocument)

Так и было, Спасибо!
