### ISSUE TITLE
Подписание входящих документов поставщика из 1С (установка даты подписания).

### ISSUE THREAD

**Issue by KrasnovaAn** [diadoc/diadocsdk-1c-docs#1034]
Добрый день!
Подскажите, пожалуйста, как можно программно поменять дату подписи входящего документа от поставщика?
Если пользователь подписывает документ в личном кабинете Диадок, то он вручную устанавливает необходимую дату подписания.
Если он подписывает документ из 1С, то дата подписания устанавливается равной дате документа ЭДО.
А нам необходимо подписывать документ из 1С определенной датой (датой определенного документа в 1С).

Какой метод можно использовать, чтобы в параметре передавать нужную нам дату подписания входящего документа поставщика?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Используете модуь, компоненту или HTTP API ?

**Comment by KrasnovaAn** [comment]
Компоненту.

**Comment by GilimkhanovDenis** [comment]
Тогда, вероятно, речь о данных во втором титуле. Например, для УПД 970 во втором титуле есть поле `AcceptanceDate` (если заполняете через DynamicContent), которое заполнит тэг `ДатаПрин` в XML

И аналогичные поля, видимо, есть в других двухтитульных документах. Притом на дату формирования подписи и дату проверки подписи Диадоком это никак не влияет

**Comment by KrasnovaAn** [comment]
Мы подписываем один титул (прилагаю пример).
![photo_2024-07-02_11-13-14](https://github.com/diadoc/diadocsdk-1c-docs/assets/174345561/285d02f4-1937-40ab-ad46-b5c535b13f0c)

**Comment by GilimkhanovDenis** [comment]
Как раз второй титул (титул покупателя) и формируете

**Comment by KrasnovaAn** [comment]
Верно ли мы поняли, что надо добавить поле AcceptanceDate:
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/174345561/d12fee5c-9ba1-4096-803b-1a58557dc22a)

**Comment by GilimkhanovDenis** [comment]
Да. должно сработать

**Comment by KrasnovaAn** [comment]
Благодарим.
