### ISSUE TITLE
Значение перечислений

### ISSUE THREAD

**Issue by Alex2574-Dev** [diadoc/diadocsdk-1c-docs#1035]
Доброго времени суток.

При использовании интеграции посредством COM библиотеки некоторые свойства заполняются значениями перечислений. Например, для функции AddDocument необходимо передать значение Version, т.е. указать версию документа. Передав значение utd820_05_01_02_hyphen указываем на создание документа в формате приказа 820, Но сейчас есть еще приказ 970, Какое должно передаваться значение для создания документа по приказу 970?
Еще для добавления документа необходимо передать значение типа документа. Передав UniversalTransferDocument создаем УПД. Какие еще значения можно передать?
Вопрос: где можно ознакомиться с возможными значениями свойств и перечислений? В документации нет этой информации.
Вот все что есть в документации:
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/174593080/46fdbe63-8b0b-41be-9ae1-d7c24369dbe2)
P.S. Интеграция разрабатывается не для 1С, а для другой программы, поддерживающей COM библиотеки.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Информация есть [здесь](https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_document.html)

**Comment by Alex2574-Dev** [comment]
Может она должна быть там? Но информации там нет.

**Comment by GilimkhanovDenis** [comment]
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/2336bcb0-d09d-43ea-9758-1e1634bb33a0)

**Comment by GilimkhanovDenis** [comment]
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/f7b42d20-084c-475f-92a6-162724b01845)

**Comment by GilimkhanovDenis** [comment]
Для УПД 970 доступная версия сейчас только одна - `utd970_05_02_01`

**Comment by Alex2574-Dev** [comment]
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/174593080/37336c43-8068-4968-8957-217ca3357f38)
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/174593080/b40f5da1-83c4-4cb0-a22a-215162d5b953)
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/174593080/13734abb-cdeb-431c-8056-81d141015edf)
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/174593080/522eee3e-8c36-4285-a8dd-1a81d42aa0e7)
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/174593080/65d4b065-d6c0-4d6b-b7e1-59bbaa8327a5)
И т.д. Интересующей информации нет.

**Comment by GilimkhanovDenis** [comment]
У каждого описания есть Name
Внутри описания есть коллекция Functions, внутри каждой функции есть её имя и список версий

**Comment by GilimkhanovDenis** [comment]
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/d14b226d-93eb-48fb-891d-523e937af937)
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/71b0d136-c892-46fb-8336-48f663114861)
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/d9b5fbba-e0ce-47c3-98e2-1ab19aaa7971)

**Comment by Alex2574-Dev** [comment]
Хорошо, воспользуемся поиском.
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/174593080/874ee64c-ddcd-41c9-9ef7-97ae6362476a)

**Comment by GilimkhanovDenis** [comment]
У компоненты нет информации в компайлтайме про то какие типы, функции и версии документов подключены в конкретном ящике. Поэтому по конкретной версии в документации ничего нет - информацию нужно получить из ответа метода

**Comment by Alex2574-Dev** [comment]
Правильно ли я понимаю, что ответ метода GetItem()?

**Comment by GilimkhanovDenis** [comment]
Речь про метод [Box.GetDocumentTypes()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.GetDocumentTypes)
либо, если хотите не древовидной структурой, а плоской получить эту же информацию, то [Box.GetFlatDocumentTypes()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.GetFlatDocumentTypes)

**Comment by Alex2574-Dev** [comment]
Спасибо. Но все же удобней было бы получить эту информацию из документации.

**Comment by GilimkhanovDenis** [comment]
Возможно в будущем добавим примеры с какими-то популярными типами документов в документацию. Но точно не все (их несколько сотен)

**Comment by Alex2574-Dev** [comment]
А как получить, к примеру, возможные значения свойства OrgType?

**Comment by GilimkhanovDenis** [comment]
Они описаны в UserDataXSD. Подробнее в [DynamicContent](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html)

**Comment by Alex2574-Dev** [comment]
А можно по подробней? Не совсем понятно.

**Comment by GilimkhanovDenis** [comment]
Если скачать UserDataXSD, то можно увидеть, что информацию об организации (допустим Seller) можно указать как 
`ExtendedOrganizationInfoUtd970`
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/94ad3638-c597-412f-893b-68b49b8fc06f)

И, допустим хотим заполнить через указание `OrganizationDetails`. У него тип `ExtendedOrganizationDetailsUtd970` - там есть `OrgType`

![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/195dc489-2f7a-4759-8d13-00ebbc2e2436)

Смотрим что указано для этого типа:

![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/9a9f5eb4-c23a-4bb3-993e-c49a71430450)

т.е. в DynamicContent'е для соответсвующего поля можно указать "1", "2", "3" или "4"

**Comment by Alex2574-Dev** [comment]
Спасибо!
