### ISSUE TITLE
Invalid data UserContractData

### ISSUE THREAD

**Issue by Alex2574-Dev** [diadoc/diadocsdk-1c-docs#1036]
Доброго времени суток!

При отправке документа средствами COM библиотеки возникает ошибка:
##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalTransferDocumentWithHyphens: TransferInfo is required.

Поиски свойства UserContractData результата не дали.

С чем это связано и как ее устранить? Может я что-то пропустил?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Судя по тому, что ошибка ссылается на `UniversalTransferDocumentWithHyphens : TransferInfo` , предположу, что отправляете УПД с версией `utd820_05_01_02_hyphen` или `utd820_05_01_01_hyphen`.

Поле TransferInfo находится на том же уровне, что `Table`, `Signers`, `Sellers` и т.д.
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/689d08ed-7611-47e8-81ba-610a1966baba)

В XSD:
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/a9802f8a-73fd-4a8e-9028-19b2aec7f5d7)

**Comment by Alex2574-Dev** [comment]
Добрый день!

Т.е. документ о доставке все равно заполнять?

А если нет договора?

**Comment by GilimkhanovDenis** [comment]
Похоже, Диадок в каких-то случаях его требует (логические проверки, не форматные). Возможно, когда заполнен Shippers или Consignees. Попросил добавить информацию об условиях обязательности в XSD

**Comment by Alex2574-Dev** [comment]
Денис,
Закомментировал заполнение Shippers и Consignees. Ошибка та же.

**Comment by Alex2574-Dev** [comment]
Денис,

Добавил инфо в TransferInfo.
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/174593080/f1a8de34-91af-475d-b4f3-93e71636c6ca)

Теперь ошибка другая:
"Для выполнения операции необходимо авторизоваться по сертификату".

Но по сертификату не авторизовывается:
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/174593080/a48ef45a-85ef-463a-b328-e9b26e0b2431)

Код подключения:
	var DiadocApi = new ActiveXObject('Diadoc.DiadocClient');
	DiadocApi.ApiClientId = '...'; // Ключ разработчика
	DiadocApi.ServerUrl = "https://diadoc-api.kontur.ru:443";
	var Certificates = DiadocApi.GetPersonalCertificates();
	var Certificate = Certificates.GetItem(0);
	var DiadocConnection = DiadocApi.CreateConnectionByCertificate2(Certificate);

**Comment by GilimkhanovDenis** [comment]
Обычно ошибка означает, что сертификат отозван. Но не вижу этого сертификата ни у одного пользователя в Диадок. С этой ошибкой предлагаю обратиться в техподдержку - они помогут привязать сертификат к пользователю

**Comment by Alex2574-Dev** [comment]
В техподдержку через чат?

**Comment by GilimkhanovDenis** [comment]
https://www.diadoc.ru/ здесь справа внизу должно быть меню для обращения в техподдежрку
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/8af07e75-2341-41a5-ba28-fd0a7bea7f76)
