### ISSUE TITLE
Sender department is not found

### ISSUE THREAD

**Issue by Alex2574-Dev** [diadoc/diadocsdk-1c-docs#1037]
Добрый день!

Подскажите, пожалуйста, с чем может быть связана ошибка при отправке документа с помощью СОМ библиотеки.
##100[Ошибка сервера Диадок]code:400, HTTP error: Sender department is not found

**Comment by GilimkhanovDenis** [comment]
Добрый день

Какими данными заполняете PackageSendTask2 ?

**Comment by Alex2574-Dev** [comment]
CounterAgentId, FromDepartmentId и ToDepartmentId

**Comment by GilimkhanovDenis** [comment]
Судя по логам в FromDepartmentId указан идентификатор ящика-отправителя, а не идентификатор подразделения

**Comment by Alex2574-Dev** [comment]
Для FromDepartmentId указываю Guid организации. Надо другое указывать?

**Comment by GilimkhanovDenis** [comment]
нужно указывать идентификатор подразделения

или не указывать вовсе

**Comment by Alex2574-Dev** [comment]
Т.е. FromDepartmentId и ToDepartmentId не заполнять?

**Comment by GilimkhanovDenis** [comment]
зависит от того, что вам нужно. Но заполнять эти поля идентификаторами ящиков неверно - нужно заполнять идентиификатрами подразделений внутри ящико

**Comment by Alex2574-Dev** [comment]
Я точно не знаю что нужно т.к. только начал разбираться с интеграцией. Но у организации нет подразделений

**Comment by GilimkhanovDenis** [comment]
не указывайте тогда

**Comment by Alex2574-Dev** [comment]
Убрал заполнение. Теперь другая ошибка.
##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.ToBoxId is required field

А где он заполняется не могу найти

**Comment by GilimkhanovDenis** [comment]
Заполните PackageSendTask2.CounteragentId
