### ISSUE TITLE
MessageToPost.ToBoxId

### ISSUE THREAD

**Issue by Alex2574-Dev** [diadoc/diadocsdk-1c-docs#1038]
При отправке документа ошибка:
 
##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.ToBoxId is required field

Не могу найти где заполняется это свойство.

**Comment by GilimkhanovDenis** [comment]
PackageSendTask2.CounteragentId

**Comment by Alex2574-Dev** [comment]
Да, совсем одинаково ToBoxId и CounteragentId...
