### ISSUE TITLE
Помощь с загрузкой компоненты в приложении

### ISSUE THREAD

**Issue by batistadude** [diadoc/diadocsdk-1c-docs#1039]
Всем доброго дня!

1С 8.3 х64 и клиент, и сервер.
Пытаюсь загрузить компоненту в приложение. 

Скачал 1С AddIn x64 отсюда https://developer.kontur.ru/docs/Diadoc/COM/Downloads.html 1С AddIn x64, разархивировал и положил в папку файл Diadoc_5_52_1_982_x64.dll, который был в архиве, предварительно разархивировав. Пытаюсь в приложении загрузить эту компоненту. 

В мануалах указано:
//Загрузка внешней компоненты
ИмяФайла = "C:\Temp\AddInDiadocAPI.dll";
ЗагрузитьВнешнююКомпоненту(ИмяФайла);

Вопрос: 
Вместо AddInDiadocAPI.dll я должен указать имя скачанного и разархивированного файла?
	
//Загрузка внешней компоненты
ИмяФайла = "C:\Users\knaz\Documents\DiadocDLL\api\Diadoc_5_52_1_982_x64.dll";
ЗагрузитьВнешнююКомпоненту(ИмяФайла);

Так должно быть? Или я совсем не в ту степь?
Нужно ли предварительно регистрировать эту dll? Если нужно, то на сервере или на клиенте? И где предпочтительнее загружать компоненту?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Особенности использования функции ЗагрузитьВнешнююКомпоненту есть в справке в самой 1С
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/370cf9ab-62c0-49c8-91ea-4e12076266df)

Таким образом, нужно указать имя файла, который есть на диске. Регистрировать предварительно не обязательно (насколько нам известно 1С сама попробует вызвать регистрацию)

Обратите внимание на раздел **Доступность** в справке. Возможно, вам нужно использовать другие функции для подключения библиотеки:

- ПодключитьВнешнююКомпонентуАсинх
- ЗагрузитьВнешнююКомпоненту
- УстановитьВнешнююКомпоненту
- НачатьПодключениеВнешнейКомпоненты

Решение о том, где загружать компоненту зависит полностью от архитектуры интеграции - компоненте всё равно.

Подробнее про способы подключения Addin и COM в 1С стоит искать на форумах по 1С или в их документации и методических рекомендациях.

**Comment by batistadude** [comment]
То есть первая строчка будет правильной?

//Загрузка внешней компоненты
ИмяФайла = "C:\Users\knaz\Documents\DiadocDLL\api\Diadoc_5_52_1_982_x64.dll";
ЗагрузитьВнешнююКомпоненту(ИмяФайла);


где Diadoc_5_52_1_982_x64.dll - имя файла, скачанного с https://developer.kontur.ru/docs/Diadoc/COM/Downloads.html и разархивированного в "C:\Users\knaz\Documents\DiadocDLL\api"

**Comment by batistadude** [comment]
То есть первая строчка будет правильной?

//Загрузка внешней компоненты
ИмяФайла = "C:\Users\knaz\Documents\DiadocDLL\api\Diadoc_5_52_1_982_x64.dll";
ЗагрузитьВнешнююКомпоненту(ИмяФайла);

где Diadoc_5_52_1_982_x64.dll - имя файла, скачанного с https://developer.kontur.ru/docs/Diadoc/COM/Downloads.html и разархивированного в "C:\Users\knaz\Documents\DiadocDLL\api"

**Comment by GilimkhanovDenis** [comment]
да

**Comment by batistadude** [comment]
Спасибо!
