### ISSUE TITLE
УКД. Как заполнить поле "Код товара"

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#104]
Добрый день.
Использую "COM-компонента для встраивания в произвольные системы- версия 5.17.1.207", отправляю УКД (UniversalCorrectionDocument)
Как через эту компоненту заполнить в таблице колонку "Код товара / работ, услуг".
Есть объект [ExtendedInvoiceCorrectionItem](http://diadocsdk-1c.readthedocs.io/ru/latest/ExtendedInvoiceCorrectionItem.html) Сведения о товаре (работе, услуге) универсального корректировочного документа, как через него задать "Код товара / работ, услуг", чтобы он отобразился на форме?
Возможно через StructedAdditionalInfos, но тогда какой нужно указать ключ, что значение вышло на визуализацию формы?
![img-2017-05-23-17-10-53](https://cloud.githubusercontent.com/assets/20082460/26358547/8fac8184-3fdb-11e7-9acf-01011a819927.png)

**Comment by azhipaigor** [comment]
Для УКД это не предусмотрено форматом. Код товара определен в УПД, на который делается корректировка.
