### ISSUE TITLE
Заполнение информации при интеграции СОМ библиотеки

### ISSUE THREAD

**Issue by Alex2574-Dev** [diadoc/diadocsdk-1c-docs#1040]
Подскажите, пожалуйста, какие свойства нужно заполнить чтобы появилась информация "Документ об отгрузке" и "Основания передачи"

![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/174593080/232bf331-29c5-42cc-b0cf-e6cc95b424c0)
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/174593080/258070e8-8a34-4fae-9adc-d8c046249637)

Так же интересует есть ли возможность просто передать документ в Диадок не отправляя его. А уже в Диадоке подписать и отправить?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Эти данные берутся из контента XML  титула документа - необходимо смотреть на описание в UserDataXSD и искать подходящие по смыслу тэги, команда разработки компоненты мало чем может здесь помочь. Возможно, удобнее приобрести услуги консультации

Что касается отправки отправки в Диадок без доставки документов до контрагента, то за это отвечает поле [PackageSendTassk2](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html).DelaySend
