### ISSUE TITLE
Передача КСФ с помощью AddIn Diadoc API

### ISSUE THREAD

**Issue by asvlasov** [diadoc/diadocsdk-1c-docs#1041]
Здравствуйте.

Сделал в 1С передачу УПД с помощью
Second_DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01", ФайлПередачи);
и далее
SendTask.Send();
В такой конструкции УПД отправляется без ошибки

Теперь есть задача передать КСФ
Изменил строчку на
Second_DocumentToSend = SendTask.AddDocumentFromFile("UniversalCorrectionDocumentRevision", "КСЧФДИС", "ucd736_05_01_02", ФайлПередачи);
Но при отправке SendTask.Send();
Выходит ошибка 
Ошибка передачи файла УПД по причине: Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: Документ не может быть отправлен в указанном формате. 

Сам XML файл через веб интерфейс загружается без ошибок.

Помогите разобраться:
1) Может мне нужно использовать другой метод, если Да, то какой?
2) Или проблемы с файлом. Если ДА, то пришлите образец
3) Или не та кодировка"ucd736_05_01_02", которую я указал в методе

[ON_NKORSCHFDOPPR_2BM-5040118248-2013022203381897025680000000000_2BM-7705603716-2012052808400776622630000000000_20240710_3f8adc6b-3904-11ef-bab4-00505698c1ea.zip](https://github.com/user-attachments/files/16159798/ON_NKORSCHFDOPPR_2BM-5040118248-2013022203381897025680000000000_2BM-7705603716-2012052808400776622630000000000_20240710_3f8adc6b-3904-11ef-bab4-00505698c1ea.zip)

**Comment by GilimkhanovDenis** [comment]
Добрый день

`UniversalCorrectionDocumentRevision` - иУКД. Но в XML не вижу номера исправления

Вероятно, вам нужен `UniversalCorrectionDocument`

**Comment by asvlasov** [comment]
Здравствуйте.

Спасибо большое. Получилось.
