### ISSUE TITLE
Подписание входящих документов поставщика из 1С (установка даты подписания). 

### ISSUE THREAD

**Issue by KrasnovaAn** [diadoc/diadocsdk-1c-docs#1042]
Добрый день!
Писали вам ранее по этой проблеме и сделали так, как вы советовали, а именно:
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/174345561/3564c0e3-5d61-4372-b601-049f3a645b5f)

В AcceptanceDate передаём дату документа 1С (Приемки).
Итог: документ вообще перестал подписываться из 1С (до этого всё подписывалось, но датой УПД, то есть, датой самого документа ЭДО).

Нам нужно подписывать документ из 1С датой документа приемки. В ЛК пользователь вот здесь выбирает эту дату:
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/174345561/7cf8fdc3-4c7d-4138-b91c-a362c797a0ce)

**Comment by GilimkhanovDenis** [comment]
> документ вообще перестал подписываться из 1С (до этого всё подписывалось, но датой УПД, то есть, датой самого документа ЭДО).

Что здесь имеется ввиду? Какая ошибка?

**Comment by KrasnovaAn** [comment]
Никакой ошибки нет, просто перестало работать подписание.
То есть, по рекомендациям, добавили строку с AcceptanceDate - перестало подписывать.
Закомментировали её - всё подписалось.

**Comment by GilimkhanovDenis** [comment]
Что возвращает PatchTask.Send() ?

**Comment by KrasnovaAn** [comment]
Тикет можно закрывать, проблему решили. Спасибо.
