### ISSUE TITLE
Для УПД нового формата 970 неизвестный тип титула: DocumentTitleType

### ISSUE THREAD

**Issue by mar-264** [diadoc/diadocsdk-1c-docs#1043]
Добрый день! При запросе типа титула документа УПД формата 970 DocumentTitleType возвращает значение UNKNOWN . 
В перечне возможных значений по ссылке: https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Enums/DocumentTitleType.html
так же отсутствует тип для формата 970 (в отличии от формата 820). 
Планируете ли добавить новое значение типа для формата УПД 970 (продавца и покупателя), или для данного формата не предусмотрено определение типа титула?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Да, планируем обновить в ближайшее время

**Comment by GilimkhanovDenis** [comment]
@mar-264 

Добавили новые значения в релизе [5.52.2](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_52_2.html)

[Ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)
