### ISSUE TITLE
УПД с функцией ДОП при отгрузке комиссионеру

### ISSUE THREAD

**Issue by NickVStepin** [diadoc/diadocsdk-1c-docs#1044]
Использую библиотеки версии 5,51,2,962.
Пытаюсь отправить УПД с функцией ДОП (статус = 2), чтобы отразить передачу товара комиссионеру.
Согласно приказа 820 поле "ОбстФормСЧФ" при функции ДОП в моем случае должно быть равно "4".
Однако, если я заполняю CircumFormatInvoice в COM-объекте, то получаю при отправке ошибку "/UniversalTransferDocumentWithHyphens: @CircumFormatInvoice should be omitted when Function=ДОП:" - типа его не надо заполнять.
Второй момент, то что в случае УПД статус 2 при отгрузке комиссионеру поля (по печатной форме) 2, 2а, 2б (Продавец) и 6, 6а, 6б (Покупатель) должны быть с прочерками. Я такого результата получить не могу, т.к. если я в COM-объекте заполняю Seller и Buyer, то они появляются и в визуализации УПД и в структуре, а если я их не заполняю, то документ не отправляется, сообщая, что "/UniversalTransferDocumentWithHyphens[1]: The element 'UniversalTransferDocumentWithHyphens' has incomplete content. List of possible elements expected: 'Buyers, Sellers'."

**Comment by GilimkhanovDenis** [comment]
Добрый день

Можете дать ссылку на законодательсто, где сказано, что `ОбстФормСЧФ` должно быть `4`?
Например, [здесь](https://www.consultant.ru/document/cons_doc_LAW_316356/424ce10585186e5a41390743004019e3d31c9033/) указано, что тэг заполняется для функции СЧФ, а не ДОП и значения от 1 до 3
![image](https://github.com/user-attachments/assets/1b5d362f-b2bb-4941-93f9-ca332f32eeed)

В UserDataXSD тоже только 1, 2, 3 значения указаны

Что касается второго вопроса, то пробовали заполнять поле `HyphenInn` в `OrganizationDetails` ?

**Comment by NickVStepin** [comment]
https://normativ.kontur.ru/document?moduleId=1 <https://normativ.kontur.ru/document?moduleId=1&documentId=464695> &documentId=464695 – 970

https://normativ.kontur.ru/document?moduleId=1 <https://normativ.kontur.ru/document?moduleId=1&documentId=328588> &documentId=328588 - 820

Да и на сайте ФНС в приложении тоже, что и у контура https://www.nalog.gov.ru/html/sites/www.new.nalog.ru/docs/formats/ON_NSCHFDOPPR_1_997_01_05_01.docx

Только Консультант зачем-то решил усечь

**Comment by GilimkhanovDenis** [comment]
А версию документа какую указываете? Провверьте, что указываете версию `utd820_05_01_02_hyphen`, а не `utd820_05_01_01_hyphen`

**Comment by NickVStepin** [comment]
Поле ДефИНН (HyphenInn) заполнять не пробовал, ибо судя по приказу не наш случай
![image](https://github.com/user-attachments/assets/82cd9117-b9da-45d0-9241-7c2bc59e46ce)
т.к. у нас функция ДОП.

Про версию, да указываю utd820_05_01_01_hyphen. С utd820_05_01_02_hyphen должен атрибут ОбстФормСЧФ заработать? Или это к тому, чтобы Seller и Buyer не заполнять?

**Comment by GilimkhanovDenis** [comment]
В `utd820_05_01_01_hyphen` значения для `ОбстФормСЧФ` - 1..3

В `utd820_05_01_02_hyphen` значения для `ОбстФормСЧФ` - 1..8

**Comment by GilimkhanovDenis** [comment]
Про прочерки в печатной форме ответим позже

**Comment by NickVStepin** [comment]
C utd820_05_01_02_hyphen ОбстФормСЧФ  = 4 получилось.
Спасибо.

Осталость разобраться с Покупателем и Поставщиком.

**Comment by NickVStepin** [comment]
попробовал из разряда "посмотрим что получится" заполнить у Продавца и Покупателя HyphenInn, т.е. структура заполнения выглядит примерно так:
			Seller.OrganizationDetails.FnsParticipantId		= ДанныеДляОтправки.Seller.FnsParticipantId;
			Seller.OrganizationDetails.OrgType				= ДанныеДляОтправки.Seller.Type;
			Seller.OrganizationDetails.OrgName				= "-";
			Seller.OrganizationDetails.HyphenInn 			= "true";
Документ успешно отправляется, но в печатной форме в поле "Адрес" вместо "-" написано "Не заполнено".
Но только на экране в веб-морде Диадока, если ее скачать в PDF, то там прочерки, как и положено

**Comment by GilimkhanovDenis** [comment]
Кроме описанного Вами выше способа

```
Seller.OrganizationDetails.FnsParticipantId = ДанныеДляОтправки.Seller.FnsParticipantId;
Seller.OrganizationDetails.OrgType = ДанныеДляОтправки.Seller.Type;
Seller.OrganizationDetails.OrgName = "-";
Seller.OrganizationDetails.HyphenInn = "true";
```

похоже. вариантов нет

Что касается надписи `Не заполнено`: можете дать ссылку на этот документ?

**Comment by NickVStepin** [comment]
https://diadoc.kontur.ru/7c284534-68f4-4ce8-9c0b-e33ef24d1f56/Document/Show?letterId=4f98a3a0-80aa-4a5e-b179-6af2992a36ff&documentId=f3f39f41-7dfb-484c-a2fd-7a9c83598892

**Comment by GilimkhanovDenis** [comment]
Для новых документов должен быть прочерк вместо `Не заполнено`
