### ISSUE TITLE
Подпись УПД формата 970

### ISSUE THREAD

**Issue by mar-264** [diadoc/diadocsdk-1c-docs#1045]
Добрый день! 
Пытаемся установить подпись для титула документа Utd970Buyer, как делали это для 820 формата:
TasksetSign = iBox:MyEmployee:CreateSetExtendedSignerDetailsTask().
TasksetSign:DocumentTitleType = "Utd970Buyer".
TasksetSignDetal = TasksetSign:ExtendedSignerDetailsToPost.
TasksetSignDetal:JobTitle  = JobTitle . /* должность работника */
TasksetSignDetal:SignerType = iBox:MyEmployee:SessionInfo:Certificate:OwnerType . 
TasksetSignDetal:Powers = "PersonDocumentedOperation". 
TasksetSignDetal:Status = "BuyerEmployee". 
TasksetSignDetal:PowersBase = "Должностные обязанности".
TasksetSign:send().
В результате получаем ошибки:
##100[Ошибка сервера Диадок]code:400, HTTP error: Wrong SignerType for TitleTypeId=13: LegalEntity (Unspecified are only allowed);Wrong SignerPowers for TitleTypeId=13: PersonDocumentedOperation (Unspecified are only allowed);Wrong SignerStatus for TitleTypeId=13: BuyerEmployee (Unspecified are only allowed);SignerPowersBase:Должностные обязанности must not be filled

Подскажите, пожалуйста, для установки значений ExtendedSignerDetails для формата 970 теперь другие возможные значения у свойств SignerType, Powers, Status, и не нужно заполнять PowersBase ? Или надо как-то иначе задавать подпись для нового формата? Или это ошибка, и не задан список возможных значений для УПД покупки и продажи 970 формата? Для Utd970Seller аналогично не работает.

**Comment by NickZubashevskiy** [comment]
Добрый день!
Судя по ошибке, значения свойств SignerType, Powers, Status нужно задать как Unspecified, которые были добавлены в [релизе 5.52.3](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_52_3.html)
