### ISSUE TITLE
Добавление неформализованного документа через COM 1С.

### ISSUE THREAD

**Issue by KolesnikovMedFlex** [diadoc/diadocsdk-1c-docs#1047]
Здравствуйте!
Не получается передать код валюты при отправке документа "Счет на оплату" из 1С.

Что делаю:
```
DocumentToSend = SendTask.AddDocumentFromFile(...
```
Далее добавляются метаданные 
```
&НаКлиенте
Процедура ДобавитьМетаданныеDocumentToSend(DocumentToSend, Key, Value)
	MetadataItem = DocumentToSend.AddMetadata();
	MetadataItem.Key = Key;
	MetadataItem.Value = Value;
КонецПроцедуры
```
Успешно передаются и отображаются данные (`Key` для процедуры выше) в личном кабинете:
`FileName`
`TotalSum` - Общая сумма с НДС
`Grounds` - Основание
`DocumentNumber`
`DocumentDate`
Для кода валюты использовал `Key` - `"Currency"`; `Value`(Число), поле `Валюта` документа (в личном кабинете) остается пустым.

Подскажите, пожалуйста, как корректно передать "валюту" при отправке счета из 1С COM соединение?

**Comment by GilimkhanovDenis** [comment]
Добрый день

дайте ссылку на документ

**Comment by KolesnikovMedFlex** [comment]
> Добрый день
> 
> дайте ссылку на документ

[Ссылка на счет](https://diadoc.kontur.ru/93586e53-ede7-4d8b-907c-6eb1f37bccfc/Folder/Send?draftId=c86db3dc-cba3-4333-83d7-20c0ff5adf4d)

**Comment by GilimkhanovDenis** [comment]
Судя по ответу метода [Box.GetDocumentTypes()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.GetDocumentTypes), метаданные для указания валюты называются `CurrencyCode`, а не `Currency`

**Comment by KolesnikovMedFlex** [comment]
@GilimkhanovDenis параметр корректно передался, спасибо за помощь!
