### ISSUE TITLE
ОШИБКА! Краш 1С при обращении к текущему подразделению пользователя

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#1048]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: COM x64 5.52.1.982.

Переводя локальную работу пользователей с АПИ версии 5.46.1.920 на 5.52.1.982 совершенно неожиданно столкнулись со следующей проблемой:

Работая с объектами АПИ "добираемся" до объекта **Box.MyEmployee.EmployeeInfo.Permissions.**

Т.е. до прав текущего подключенного сотрудника - объекта типа EmployeePermissions.

Смотрим отладчик:
![изображение](https://github.com/user-attachments/assets/a64c8dc6-fd3a-447f-bf74-f4a9cac7f257)

Видим, что, согласно
![изображение](https://github.com/user-attachments/assets/faac1c60-e95f-47ca-b607-0d7e68d9a254)

для текущего подразделения теперь используется поле "**Department2**".

Однако!
На самом деле поле "**Department**" тоже есть, просто его не видно. 

### Оно устарело, но еще не удалено!

И вот тут наступает самое интересное:
Если обратиться к устаревшему, но еще существующему полю "**Department**" - при выполнении кода или даже просто добавив его в данные, отображаемые отладчиком 1С...

## Сразу же происходит падение 1С

![изображение](https://github.com/user-attachments/assets/b06c3927-30e4-478a-a776-e2c3c0f871c4)

## Важно

Такое падение происходит при работе версии АПИ AddIn x64 5.52.1.982. 
У нас это 100% воспроизводится при работе на клиентской стороне 1С. 

На сервере не проверяли.

Однако, похожий код у нас есть в серверной части, работающей на версии АПИ COM x64 5.52.1.982.

Но там мы обращаемся к полю "**Department**"  пользователя только, если у него IsAdministrator = true.
И в этом случае ошибок не возникает.

(в варианте из примера краша шло обращение к полю пользователя, у которого IsAdministrator = false, что видно на ранее приведенном скрине).

Почему происходит падение:
- то ли из-за AddIn на клиенте вместо COM на сервере
- то ли из-за различия прав пользователя (падаем на IsAdministrator = false и не падаем на = true)
- то ли из-за обеих причин...

**Мы не знаем.**

**Естественно, что на версии 5.46.1.920 никаких проблем нет, все прекрасно работает без ошибок!**

### Итого

Даже несмотря на то, что в коде происходит доступ к устаревшему полю, кажется, что падение 1С в таком случае - это явно неправильно! И скорее всего говорит о какой-то ошибке в реализации компоненты.

Очень надеемся на ее нахождение и исправление!

Спасибо.

### Дополнительно

Проверили поведение на последней версии АПИ 5.52.3.987 - полностью такое же поведение.
100% падение при обращении к указанному полю.

### Дополнительно 2
Часть данных из отчета по ошибке:

{
	"time": "2024-07-31T16:30:29+10:00",
	"clientInfo": {
		"platformType": "Windows_x86_64",
		"appVersion": "8.3.23.1865",
		"appName": "1CV8C",
		"systemInfo": {
			"osVersion": "Microsoft Windows 10 version 10.0  (Build 18363)",
			"fullRAM": 17039040512,
			"freeRAM": 7357124608,
			"processor": "GenuineIntel Intel64 Family 6 Model 165 Stepping 3 2904 MHz",
		}
	},
	"sessionInfo": {
		"userName": "Сергеев Евгений В.",
		"platformInterfaceLanguageCode": "ru",
		"configurationInterfaceLanguageCode": "ru",
		"localeCode": "ru_RU"
	},
	"infoBaseInfo": {
		"localeCode": "ru_RU"
	},
	"serverInfo": {
		"appVersion": "8.3.23.1865",
		"type": "Windows_x86_64",
		"dbms": "MSSQLServer"
	},
	"configInfo": {
		"compatibilityMode": "Version8_3_14",
	},
	"errorInfo": {
		"systemErrorInfo": {
			"clientStack": "v8_5A2_8.tmp:0x0000000000000000 unknown:0x0000000000000000 unknown:0x0000000000000000 unknown:0x0000000000000000 unknown:0x0000000000000000 unknown:0x0000000000000000 unknown:0x0000000000000000 ",
			"clientStackHash": "FD306A6AA7484A85029937D0AF7D9172",
			"systemCrash": true
		},
		"applicationErrorInfo": {
			"errors": [
				[
					"Аварийное завершение",
					[],
					"",
					""
				]
			]
		}
	}
}

**Comment by GilimkhanovDenis** [comment]
По идее должно и для администратора воспроизводиться
+
при обращении к полю `VisibleDepartments` аналогичное падение

**Comment by GilimkhanovDenis** [comment]
Исправлено в [5.52.4](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_52_4.html)

[Ссылки для скачивания ](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)
