### ISSUE TITLE
Ответные действия по входящим документам

### ISSUE THREAD

**Issue by batistadude** [diadoc/diadocsdk-1c-docs#1049]
Доброго дня. Пишу код на выполнение ответных действий. Нашел документацию, по ней возникли вопросы.
1. ДокументИлиДокументы - это ссылка на документ, по которому я буду давать ответ? Как его получить?
2. Что за функция ВычислитьОтветноеДействие?

![Screenshot_11](https://github.com/user-attachments/assets/3860fedf-f7a1-4530-a743-85c010de2630)

**Comment by batistadude** [comment]
Я создал PatchTask, а дальше что делать, не могу понять

**Comment by GilimkhanovDenis** [comment]
Про возможные варианты аргументов написано [здесь](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PatchTask.html#PatchTask.AddToPatch)

Функция "ВычислитьОтветноеДействие" - какая-то функция, в которой определяете что хотите сделать с документом/документами (какая-то бизнес логика). Например, если сумма документа больше числа N, то хотим подписать, иначе отказать. Что-то такое

**Comment by GilimkhanovDenis** [comment]
Можете подсмотреть в #992 ещё пример

**Comment by batistadude** [comment]
А как найти документы, которые подписывать? Через MessageID?

**Comment by batistadude** [comment]
Как определить, какие документы надо подписать? Через какую функцию?

**Comment by GilimkhanovDenis** [comment]
Это какая-то бизнес логика, которую определяете вы сами

**Comment by GilimkhanovDenis** [comment]
Выше я привёл только пример. Она может быть какой угодно

**Comment by GilimkhanovDenis** [comment]
Можете подписать хоть всё - решение за вами как интегратором. Компонента со своей стороны только проверит, что действие доступно для документа в Диадок в том состоянии, в котором он сейчас находится

**Comment by batistadude** [comment]
> Можете подписать хоть всё - решение за вами как интегратором. Компонента со своей стороны только проверит, что действие доступно для документа в Диадок в том состоянии, в котором он сейчас находится

А как на стороне Диадок найти тот документ, который я хочу подписать?

**Comment by GilimkhanovDenis** [comment]
Например, [так](https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_get_documents.html) или, если какой-то конретный документ, то [по идентификатору](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.GetDocumentById)

**Comment by batistadude** [comment]
Документ нахожу, но на строчке "ЗаполнитьОтвет(dd_PatchItem)", ошибка... Что делаю не так?

![image](https://github.com/user-attachments/assets/de17d603-6940-4af4-8dbc-4dd37ded7313)


![image](https://github.com/user-attachments/assets/b68174fe-ac44-46c9-b00d-630d894b42e8)

**Comment by GilimkhanovDenis** [comment]
Это что-то из 1С. Могу только предполагать, что происходит передача даныых м/у клиентом и сервером и ожидается, что будет передан XDTO, а передаётся COMObject. Ошибка не из компоненты идёт
