### ISSUE TITLE
Target department is not found

### ISSUE THREAD

**Issue by SlothFive** [diadoc/diadocsdk-1c-docs#1050]
Заполняю на подпись ToDepartmentId и при подписи выдает ошибку 
Ошибка при получении значения атрибута контекста (Result): Произошла исключительная ситуация (AsyncResult.Result): ##100[Ошибка сервера Диадок]code:400, HTTP error: Target department is not found

**Comment by SlothFive** [comment]
ID подразделения контрагента проверил, всё верно подставляется.
Может кто подскажет почему он не находит его?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Какие значения указываете в CounteragentId и в ToDepartmentId?

**Comment by SlothFive** [comment]
Вопрос снят, не заметил ID контрагента пользователи изменили на такском.
