### ISSUE TITLE
Получить контент документа основания с помощью API методов.

### ISSUE THREAD

**Issue by 492Sky** [diadoc/diadocsdk-1c-docs#1051]
На основании документа диадок в 1С создан документ.
Для созданного документа в 1С мне известен ИдентификаторДокументаВДиадок и ИдентификаторЯщикаДиадок

Делаю внешнюю обработку, которую нужно будет разово использовать.
С помощью каких API методов имея эти данные можно получить контент документа из диадока на основании которого был создан документ в 1С ?

**Comment by GilimkhanovDenis** [comment]
Добрый день

посмотрите на методы объекта [DocumentBase](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html) из раздела `Информация о контенте и подписях`

**Comment by 492Sky** [comment]
Я с получаю объект производного от ([Document](https://sdk-new.readthedocs.io/en/latest/Document.html)) типа с помощью метода GetDocumentById. А вот как уже из этого Document вытащить контент документа основания, вообще не могу понять. Возможно ли это вообще ?

**Comment by GilimkhanovDenis** [comment]
У вас ссылка на чей-то личный старый форк документации, многие из указанных там методов не работают для новых типов документов

Что имеете ввиду под документом основания?
Если это какой-то другой документ, на который ссылается исходный, то можно по коллекциям `InitialDocumentIds`, `SubordinateDocumentIds` пробежаться и получить документы по их идентификаторам
Если это какие-то данные из контента, то нужно искать их в контенте:
- [DocumentBase.GetDynamicContent()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html#DocumentBase.GetDynamicContent), если хотите упрощённое представление контента обрабатывать
- [DocumentBase.GetBase64Content()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html#DocumentBase.GetBase64Content), если хотите с исходным контентом работать

**Comment by GilimkhanovDenis** [comment]
В [прошлом обращении](https://github.com/diadoc/diadoc1cpro-docs/issues/222) Вы спрашивали про модуль `Diadoc_4_34_1`. Если сейчас вопрос тоже про него, а не про COM-библиотеку, то лучше задать вопрос [в репозитории про модуль](https://github.com/diadoc/diadoc1cpro-docs/issues)

**Comment by 492Sky** [comment]
[GilimkhanovDenis](https://github.com/GilimkhanovDenis) Спасибо за ответ. Очень помогли. Все получилось.
