### ISSUE TITLE
Отправка подписи УПД в 970 формате

### ISSUE THREAD

**Issue by mar-264** [diadoc/diadocsdk-1c-docs#1052]
Добрый день.
После установки подписи документу УПД в формате 970 (указываем подписанта и сертификат подписанта) и далее отправки методом Send() получаем ошибку: 
```
Error occurred while accessing component property/method: Send.
##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
```

Скажите, пожалуйста, что за объект UserContractData (в описании CommonXmlNodes.cs такой найти не удалось) и что необходимо заполнить, что бы он не был пустым?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Что такое CommonXmlNodes.cs ?
Про контент написано [здесь](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html)

**Comment by GilimkhanovDenis** [comment]
Ошибка означает, что что-то в DynamicContent заполнено неправильно. Что именно написано после `##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:`. Насколько знаю, ошибки там перечислены через перевод строки

**Comment by mar-264** [comment]
> Ошибка означает, что что-то в DynamicContent заполнено неправильно. Что именно написано после `##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:`. Насколько знаю, ошибки там перечислены через перевод строки

К сожалению мы не можем прочитать остальные строки, наша система, из которой идет вызов, не позволяет их получить. Есть ли еще какая-то возможность понять причину ошибки? Можно ли получить полный текст ошибки в каком-то логе или как-то еще?

**Comment by GilimkhanovDenis** [comment]
**Простой вариант**: вы можете залогировать HTTP запросы - ошибка будет в теле ответов одного из последних вызванных методов. Например, использовать [fiddler](https://www.telerik.com/fiddler) в качестве прокси (не реклама)

**Вариант сложнее**: ошибка пишется с помощью [SetErrorInfo](https://learn.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-seterrorinfo) и если вы сможете её прочитать до того как это сделает текущий обработчик исключения, то тоже сможете получить полный текст ошибки (с переводами строки). Похожий сценарий для FoxPro был в #971 

**Разовый вариант**: можно попробовать по логам поискать ошибку. для этого нужна информация: на какой документ отвечаете (ссылка) и время ошибки (с указанием часового пояса)

Возможно, есть какие-то ещё пути, специфичные для вашей среды исполнения, но их я уже вряд ли смогу подсказать
