### ISSUE TITLE
Пакет документов повторно не появляется в черновиках

### ISSUE THREAD

**Issue by crashsip** [diadoc/diadocsdk-1c-docs#1053]
Отправляем пакет документов из 1С в ДИАДОК, AddIn, Diadoc_5_52_4_989_x64.dll.
Пакет попадает в черновики и ожидает проверки, подписания и отправки ответственным лицом.
Безответственное лицо случайно удаляет пакет документов из черновиков (по рукам уже надавали и тому кто удалил, и тому кто доступ ему дал, но над ситуацией задумались).
Повторно отправляем тот же самый пакет документов, 1С пишет - ОК, отправлено, вот вам ID...
В Черновиках пакет не появляется. 

Если внести изменения в пакет документов (отправить больше или меньше) - появится в черновиках, но это "костыль".
В Удаленных тоже черновика этого нет. 
При получении документа по ID видим, что свойство isDeleted  = True.
Как можно вернуть пакет/документ в черновики?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Заполняйте **OperationId** в [PackageSendTask2](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html) уникальным значением тогда отправится новый пакет. иначе сработает защита от дублей в Диадок и вернётся результат предыдущей отправки аналогичного черновика

P.S. если документ сразу отправляется контрагенту, то будет формирована новая подпись (-и) и Диадок скорее всего воспримет такую отправку как новую
