### ISSUE TITLE
Метод SaveAllContent

### ISSUE THREAD

**Issue by 492Sky** [diadoc/diadocsdk-1c-docs#1054]
Добрый день.

Для сохранения файлов каждого документа из пакета использую метод SaveAllContent.
Все работает, но случается такое что отсутствует файл печатной формы. Редкость но случается. После перезапуска обработки файлы выгружаются уже в полном объеме. Есть ли метод который проверяет были ли ошибки при выполнении SaveAllContent ?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Метод и так выкидывает исключение, если в процессе выполнения произошла ошибка, например, если не удалось построить печатную форму
