### ISSUE TITLE
Отправка уточнения УПД

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#1055]
Здравствуйте. Отправили покупателю УПД. Покупатель запросил уточнение. В личном кабинете в исходящем УПД есть действие "Отправить уточнение". А как отправить уточнение с помощью компоненты? В описании метода PatchTask.AddToPatch(Documents, Action) нет такого действия.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Этот статус предполагает, что будет отправлен новый документ - исправительный или корректировочный счёт-фактура (или УПД). Т.е. вам нужен [PackageSendTask2](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html)

В отправляемом ИСФ/КСФ/ИУПД/УКД необходимо указать идентификатор исправляемого/корректируемого документа методом [DocumentToSend.AddInitialDocument(DocumentID) ](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentToSend.html#DocumentToSend.AddInitialDocument)

**Comment by evgen421** [comment]
Спасибо.
