### ISSUE TITLE
Ошибка при подписании документа - NotAllowedToSignWithPowerOfAttorney

### ISSUE THREAD

**Issue by SlothFive** [diadoc/diadocsdk-1c-docs#1056]
Ошибка Подписание и отправка пакета ПЭД (Диадок) 00000924799 от 19.08.2024 12:38:49 d64df5fd-5e0e-11ef-86cb-00505601d337 {Расширение_ИнтеграцияДиадок ОбщийМодуль.Диадок_Клиент_Модуль.Модуль(2440)}: Ошибка при получении значения атрибута контекста (Result): Произошла исключительная ситуация (AsyncResult.Result): ##100[Ошибка сервера Диадок]code:400, HTTP error: ErrorCode: DocumentService.NotAllowedToSignWithPowerOfAttorney (Http.BadRequest)

Не могу понять с чем это ошибка связана. Может кто сталкивался?

**Comment by GilimkhanovDenis** [comment]
@SlothFive

Единственную такую ошибку за вчера-сегодня вижу на компоненте 5.39.0. Вероятно, это ваша ошибка, поэтому рекомендую обновить компоненту.

В целом она означает, что идёт попытка использовать МЧД для подписи, формируемой служебным тестовым сертификатом Диадок.
Подробнее в описании релиза [5.42.2](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.42.2)

**Comment by SlothFive** [comment]
Спасибо! Больше всего хотел понять из-за чего данная ошибка возникает. Да компонента 5.39.0 и ошибка возникает только с тестовой организацией.
