### ISSUE TITLE
Вопросы по формированию УПД 970

### ISSUE THREAD

**Issue by dnab2** [diadoc/diadocsdk-1c-docs#1057]
1. Не принимаются значения ставки НДС (Item.TaxRate). В 820-м формате использовалось например "20%". 
Где почитать про тип TaxRateUtd970?
/UniversalTransferDocument[1]/Table[1]/Item[1]/@TaxRate: The 'TaxRate' attribute is invalid - The value '20%' is invalid according to its datatype 'TaxRateUtd970' - The Enumeration constraint failed.
2. Не проходит контроль ИНН продавца. Изменлся тип OrgType? В формате 820 контроль проходит.
/UniversalTransferDocument/Sellers/Seller/OrganizationDetails: @OrgType=1: @Inn=1832060*** has wrong checksum.
3. Где почитать про Signer.PowersConfirmationMethod? 
/UniversalTransferDocument/Signers/Signer: @SignerPowersConfirmationMethod must be filled
Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Ответы на все эти вопросы содержатся в [UserDataXSD](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html) соответствующего типа документа

**Comment by dnab2** [comment]
Спасибо, с программно полученной схемой все понятно.
А тут у вас старая схема, кстати:
https://www.diadoc.ru/docs/forms/upd/structure/47#on_nschfdoppr
нет новых реквизитов

**Comment by GilimkhanovDenis** [comment]
Спасибо

**Comment by SergeyNShestakov** [comment]
> Добрый день
> 
> Ответы на все эти вопросы содержатся в [UserDataXSD](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html) соответствующего типа документа

Здравствуйте.
У меня тот же вопрос по ставке налога.
И ответа я в XSD не нашёл 
Почему ругается UniversalTransferDocument[1]/Table[1]/Item[1]/@TAXRATE: The 'TaxRate' attribute is invalid - The value '20%' is invalid according to its datatype 'TaxRateUtd970' - The Enumeration constraint failed если в описании 970 формата явно сказано что поле НалСт Принимает значение: 0% | 10% | 18% | 20% | 10/110 | 18/118 | 20/120 | без НДС | НДС исчисляется налоговым агентом. Что мне там указывать?
