### ISSUE TITLE
УПД 970. Циклическая ошибка проверки заполнения

### ISSUE THREAD

**Issue by dnab2** [diadoc/diadocsdk-1c-docs#1059]
При проверке возникает ошибка:

Metadata errors: 
Validation errors: Location: /Файл/Документ/СвСчФакт/ДокПодтвОтгрНом/@РеквНаимДок, Message: @Функция=СЧФДОП: Поле @РеквНаимДок=Документ об отгрузке товаров (выполнении работ), передаче имущественных прав (документ об оказании услуг) должно совпадать с НаимДокОпр=Счет-фактура и документ об отгрузке товаров (выполнении работ), передаче имущественных прав (документ об оказании услуг)

При замене DocumentShipment.DocumentName на "Счет-фактура и документ об отгрузке товаров (выполнении работ), передаче имущественных прав (документ об оказании услуг)" возникает обратная ошибка :

Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalTransferDocument/DocumentShipments/DocumentShipment: When Function=СЧФДОП: @DocumentName=Счет-фактура и документ об отгрузке товаров (выполнении работ), передаче имущественных прав (документ об оказании услуг) should be equal Документ об отгрузке товаров (выполнении работ), передаче имущественных прав (документ об оказании услуг)

**Comment by dnab2** [comment]
Скажите, пожалуйста, на данный момент функционал формирования УПД через СОМ-компоненту работоспособен?
Ведь описанная здесь ошибка возникает для обязательного реквизита.

**Comment by GilimkhanovDenis** [comment]
Генерация титула и валидация происходит не в самой COM-компоненте, а в Диадоке. Ждём ответа

**Comment by dnab2** [comment]
Упомянутый реквизит формата ДокПодтвОтгрНом (графа 5а "Документы отгрузки") отсутствует в редакторе на сайте. То есть даже вручную его нельзя заполнить.
Кроме того в печатной форме на сайте отсутствует колонка с реквизитом СтТовБезНДСПрослеж. Если выгрузить документ с сайта в xml, то реквизит в файле есть.

**Comment by dnab2** [comment]
С чем связано, что УПД 970 с функцией СЧФДОП не требует заполнения DocumentShipments (графа 5а), а с функцией ДОП требует? 
Кроме того и в редакторе на сайте графа 5а отсутствует для заполнения в функции "Счет-фактура и передаточный документ", но присутствует в "Передаточный документ".

**Comment by GilimkhanovDenis** [comment]
Воспроизводится ли проблема с `РеквНаимДок` / `НаимДокОпр` сейчас ?

**Comment by dnab2** [comment]
> Воспроизводится ли проблема с `РеквНаимДок` / `НаимДокОпр` сейчас ?

да, все по-прежнему как описано выше.
Вот такой код:

```
Для Каждого ОтгрузочныйДокумент Из ДанныеШапки.ДокументыОбОтгрузке Цикл				
			DocumentShipment        = Doc.DocumentShipments.AddDocumentShipment(); 			   			
			DocumentShipment.DocumentNumber    = ОтгрузочныйДокумент.НомерДокумента;
			DocumentShipment.DocumentDate     = Формат(ОтгрузочныйДокумент.ДатаДокумента, "ДЛФ='Д'");
			//DocumentShipment.DocumentName     = "Накладная";
			DocumentShipment.DocumentName = "Документ об отгрузке товаров (выполнении работ), передаче имущественных прав (документ об оказании услуг)";
КонецЦикла;
```

Если закомментировать этот код, то выгрузка происходит и даже проходит проверку на сайте файл xml.
Но для функции СЧФДОП этот параметр должен быть обязателен (поправьте если я не прав).

**Comment by dnab2** [comment]
Стал работать следующий код:
Для Каждого ОтгрузочныйДокумент Из ДанныеШапки.ДокументыОбОтгрузке Цикл				
			DocumentShipment        = Doc.DocumentShipments.AddDocumentShipment(); 			   			
			DocumentShipment.DocumentNumber    = ОтгрузочныйДокумент.НомерДокумента;
			DocumentShipment.DocumentDate     = Формат(ОтгрузочныйДокумент.ДатаДокумента, "ДЛФ='Д'");
			//DocumentShipment.DocumentName     = "Накладная";
			DocumentShipment.DocumentName = "Счет-фактура и документ об отгрузке товаров (выполнении работ), передаче имущественных прав (документ об оказании услуг)";
КонецЦикла;
В первом посте я писал, что это приводило к ошибке.
В результате в графе 5а выводится "тот же" (до этого выводился прочерк).
Вопрос спорный. 1с например считает, что там должно выводиться "Универсальный передаточный документ", номер, дата.
Мнение Диадока читал: 
https://support.kontur.ru/diadoc/53278-pechatnaya_forma_scheta_faktury

**Comment by GilimkhanovDenis** [comment]
Про печатные формы в веб интерфейсе  предлагаю обратиться в техподдержку

**Comment by GilimkhanovDenis** [comment]
Ошибка генерации титула из обращения решена на стороне сервиса. Обращение закрываю
