### ISSUE TITLE
Подписи ответственных лиц в UtdTorg12

### ISSUE THREAD

**Issue by Sergguha** [diadoc/diadocsdk-1c-docs#106]
Добрый день!
Используемая версия компоненты 5.17.1.207. Подскажите, пожалуйста, как правильно при отправке документа с типом UtdTorg12 указывать должностных лиц организации для их корректного отображения в форме ("Главный бухгалтер", "Отпуск груза произвел"). В XmlTorg12 были соответствующие поля ChiefAccountant, SupplyPerformedBy.

**Comment by denver069** [comment]
SupplyPerformedBy равен полю [Employee](http://1c-docs.diadoc.ru/ru/latest/Employee.html) в [UtdSellerContent.TransferInfo](http://1c-docs.diadoc.ru/ru/latest/UtdSellerContent.html?highlight=transferinfo)
ChiefAccountant в УПД нет. Попробуйте добавить данные главного бухгалтера как второго подписанта через [AddSigner](http://1c-docs.diadoc.ru/ru/latest/AddSigner-(UtdSellerContent).html) с заполненным [ExtendedSignerDetails](http://1c-docs.diadoc.ru/ru/latest/ExtendedSignerDetails.html) с необходимой областью полномочий [Powers](http://1c-docs.diadoc.ru/ru/latest/ExtendedSignerDetails.html?highlight=Powers). Таким образом в файле xml будут 2 подписанта, но на форме визуализации будет отражен только первый в разделе "Отпуск груза разрешил".

**Comment by denver069** [comment]
Да все верно.
