### ISSUE TITLE
преобразовать timestamp в дату и время

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#1060]
Здравствуйте. Подскажите пожалуйста какой нибудь не сложный вариант преобразования для 1С 7.7

**Comment by dnab2** [comment]
Как то так:
Дата = '01.01.1970'+КвоСекунд/(60 * 60 * 24)
Правый операнд надо округлить до целых, я не помню уже как в 77.
Время аналогично.
И скорее всего будет время по Гринвичу, надо скорректировать по часовому поясу.

**Comment by GilimkhanovDenis** [comment]
Думаю, вам стоит обратиться на форум по 1С 7.7

При работе с COM есть ещё такая проблема, что тип OLE DATE превращается в тип Дата, а время 1С 7.7 решило не учитывать. Возможно, и при преобразовании из timestemp'а своими силами, возникнет какая-то такая же проблема

Какую задачу хотите решить? Возможно, компонента чем-то может помочь

**Comment by evgen421** [comment]
Здравствуйте **dnab2**. Спасибо, но в 1С 7.7 к дате можно добавить только количество дней.

**Comment by dnab2** [comment]
>  Здравствуйте **dnab2**. Спасибо, но в 1С 7.7 к дате можно добавить только количество дней.
Вот поэтому:
**>  Правый операнд надо округлить до целых, я не помню уже как в 77.**

**Comment by evgen421** [comment]
Здравствуйте Денис. Я в #853 уже излагал проблему и компонента к сожалению возвращает только дату. А что за форум по 1С 7.7?

**Comment by evgen421** [comment]
**dnab2** возможно сработает, надо проверить

**Comment by GilimkhanovDenis** [comment]
Ну, компонента как раз возвращает полностью дату и время, а 1С 7.7 приводит всё к своему типу Дата, где времени нет

Под форумом по 1С 7.7 имею ввиду какой-то абстрактный форум, где возможно, кто-то задавался таким же опросом. Какой точно на знаю. Миста?

В целом, начало решения видится таким:

1. вычислить какую-то константу с количеством тиков в дне - пусть `TicksInDay`.
2. нацело поделить timestamp на `TicksInDay` - это будут дни, значимые для вычисления даты
3. взять остаток от деления timestamp на `TicksInDay` - это будут тики, значимые для вычисления времени

**Comment by evgen421** [comment]
**dnab2** Воистину всё гениальное просто! Спасибо!
