### ISSUE TITLE
SendRevocationRequest ошибка Аннулирования

### ISSUE THREAD

**Issue by SlothFive** [diadoc/diadocsdk-1c-docs#1061]
Установлена последняя версия компоненты.
Подскажите пожалуйста что использовать вместо метода:
DocumentBase.SendRevocationRequest(Comment="")

**Comment by GilimkhanovDenis** [comment]
Добрый день

[PatchTask.AddToPatch()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PatchTask.html#PatchTask.AddToPatch)

**Comment by SlothFive** [comment]
Спасибо!
