### ISSUE TITLE
Компонента 5_52_5_991 - Самопроизвольно завершается отладка

### ISSUE THREAD

**Issue by SlothFive** [diadoc/diadocsdk-1c-docs#1062]
При отладке в конфигураторе 1С когда использую компоненту 5_52_5_991 отладка завершается когда пытаюсь посмотреть comобъект.
С компонентой версии 5.39.0.861 такого нет.
Специально проверил сейчас на одной процедуре.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Нужен дамп в момент падения

**Comment by SlothFive** [comment]
Дамп чего именно?

**Comment by GilimkhanovDenis** [comment]
Процесса

**Comment by GilimkhanovDenis** [comment]
Например с помощью [ProcDump](https://learn.microsoft.com/en-us/sysinternals/downloads/procdump)

`procdump -e -ma -w <process_name>`

**Comment by SlothFive** [comment]
какого процесса? Простите за тупость, но правда не оч понимаю. В диспетчере не вижу ничего похожего на запущенный процесс компоненты или может я не там смотрю?

**Comment by GilimkhanovDenis** [comment]
Компонента живёт внутри процесса вашего приложения. Если падает отладка, то нужен дамп процесса отладчика

**Comment by SlothFive** [comment]
https://disk.yandex.ru/d/DVu1qBH5fmkGJg

**Comment by GilimkhanovDenis** [comment]
Исправлено в [5.53.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_53_0.html)

[Ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)
