### ISSUE TITLE
УПД 970. Заполнение ответного титула

### ISSUE THREAD

**Issue by SlothFive** [diadoc/diadocsdk-1c-docs#1063]
Заполняю ответный титул:
	dd_PatchTask = dd_Box.CreatePatchTask();
	
    ОтветноеДействие = "Sign";

	dd_ValueCollection = dd_PatchTask.AddToPatch(Document, ОтветноеДействие);
	
	Для Каждого dd_PatchItem Из dd_ValueCollection Цикл 
		
		dd_RecipientTitleToSend = dd_PatchItem.PatchContent;
		ЗаполнитьМЧД(dd_RecipientTitleToSend.PowerOfAttorneyToAttach);
		dd_RecipientTitleToSend.NeedReceipt = True;
		dd_DynamicContent = dd_RecipientTitleToSend.DynamicSigners;
		UniversalTransferDocumentBuyerTitle = dd_DynamicContent.UniversalTransferDocumentBuyerTitle;
		
	КонецЦикла;

Поле объекта не обнаружено (DynamicSigners)
{ВнешняяОбработка.ПолучитьСтруктуруПЭД_ТЛ.Форма.Форма.Форма(37)}:dd_DynamicContent = dd_RecipientTitleToSend.DynamicSigners;

Так же пробовал так:
	ReplyTask = Document.CreateReplySendTask2("AcceptDocument");
	
	ContentItems = ReplyTask.ContentItems; 
	
	КоличествоКонтентов = ContentItems.Count();
	Для счИндекс = 0 По КоличествоКонтентов - 1 Цикл
		ContentItem = ContentItems.GetItem(счИндекс);
		Content = ContentItem.Content;
		Signers = Content.UniversalTransferDocumentBuyerTitle.Signers;
		NewSigner = Signers.AddItems();  
	КонецЦикла;    

Но там выдает ошибку - Метод объекта не обнаружен (AddItems)

Подскажите пожалуйста что делаю не так?

**Comment by SlothFive** [comment]
Добрый день!
может нужно использовать другой метод для УПД 970? Просто в примерах использования есть только 820

**Comment by SlothFive** [comment]
Формируем титул покупателя:
![image](https://github.com/user-attachments/assets/64c1bc31-d152-4aa6-903e-024043d3d500)

Выдает ошибку - Метод объекта не обнаружен (AddItems)

Подскажите пожалуйста в чем причина?
Компонента 5.52.2

**Comment by GilimkhanovDenis** [comment]
В УПД 970 у коллекции подписантов есть имя, поэтому так:

`dd_PatchItem.PatchContent.Content.UniversalTransferDocumentBuyerTitle.Signers.AddSigner()`

![image](https://github.com/user-attachments/assets/6411c754-1163-4482-a727-95f05999c8cf)

**Comment by SlothFive** [comment]
Понял, спасибо!
