### ISSUE TITLE
Зачем нужен "ключ разработчика"

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#1064]
При авторизации через компоненту необходимо указывать ключ разработчика. Авторизация идет с помощью сертификата. По этому сертификату доступны несколько организация. Доступ по АПИ проплачен только у одно и, соответственно, компонента позволяет работать только с этой организацией. При попытке работать с другими возвращает ошибку "code:402, HTTP error: Доступ запрещён. Необходима оплата тарифа АПИ". Все понятно и логично.
Теперь нам надо организовать работу со второй организацией. Менеджер Контура сказал, что при оплате доступа на вторую организацию будет выдан другой ключ разработчика.
Вопрос: зачем? Проверка оплаты доступа к АПИ явно не на ключе основана. В авторизации ключ этот так же не участвует. Типовое решение Контура, насколько я понимаю, идет с одним ключом для всех.
Это какое-то неудачное решение со стороны Контура? Или это неграмотность со стороны менеджера?

**Comment by GordanovaKseniya** [comment]
Добрый день! Конечно, все будет работать и с предыдущим ключом, достаточно оплаты на апи. Возможно, менеджер не знал, что у вас уже есть ключ.

**Comment by dorexpro** [comment]
Большое спасибо.
