### ISSUE TITLE
Как отправить пакет документов, чтобы подписать можно было только все документы в пакете?

### ISSUE THREAD

**Issue by crashsip** [diadoc/diadocsdk-1c-docs#1066]
Добрый день. 
Подскажите, пожалуйста, как отправить пакет неформализованных документов так, чтобы в пакете получатель не мог по отдельности документ отклонить/подписать?
т.е. если подписывает - то весь пакет документов сразу принимает. Есть вообще такая возможность?

сейчас в 1С исполняется такой код: 

ЗаданиеОтправки = КонтекстОрганизации.CreatePackageSendTask2();
ЗаданиеОтправки.IsDraft = Истина;   
ЗаданиеОтправки.LockDraft = Истина; 
ЗаданиеОтправки.LockMode = "Full"; 		
ЗаданиеОтправки.CounterAgentId = ИДКонтрагента;
ОтправленныеДокументы = ЗаданиеОтправки.Send();

Черновик от изменений блокируется.
Но, когда ответственный сотрудник заходит в WEB-интерфейс, подписывает и отправляет эти документы, контрагенту приходит пакет, в котором он может часть документов подписать, а часть отклонить.

**Comment by JohnSergeev** [comment]
Добрый день.
А зачем это нужно?

К нам часто присылают пакеты, в которых, часть документов "хорошие", а часть - какая-то бредятина.

И это здорово, что мы "хорошие" можем подписать, а "плохие" - отказать в подписании.
Это же очень удобно. Да и правильно!

**Comment by GilimkhanovDenis** [comment]
Диадок почему-то игнорирует `LockMode` при создании черновика (если запросить черновик, это должно быть видно)

Из временных решений могу предложить использовать не черновики, а `DelaySend`

**Comment by GilimkhanovDenis** [comment]
Диадок не поддерживает отправку залоченного пакета из черновиков

Если функциональность необходима, то предлагаю обратиться к менеджеру, чтобы эту задачу продвигать в очереди на разработку

Альтернатива - использовать отложенную отправку (DelaySend)

**Comment by crashsip** [comment]
> Добрый день. А зачем это нужно?
> 
> К нам часто присылают пакеты, в которых, часть документов "хорошие", а часть - какая-то бредятина.
> 
> И это здорово, что мы "хорошие" можем подписать, а "плохие" - отказать в подписании. Это же очень удобно. Да и правильно!

Добрый.
От нас уходит из 1С пакет согласованных с нашей стороны документов, тесно связанных между собой. Договор и приложения, допы к договору.  Очень много нюансов завязано на приложения, много особенностей формирования всего пакета документов - не буду углубляться, чтобы не флудить. Но общая суть в том, что договор отдельно не должен быть подписан, а одно из приложений, например, отклонено. Либо весь пакет подписан, либо весь не принят (и тогда заново согласовываем то, что не устроило какую-то из сторон).
