### ISSUE TITLE
TaxRateUtd970

### ISSUE THREAD

**Issue by MaximGlazunov** [diadoc/diadocsdk-1c-docs#1067]
Добрый день.

Возникли проблемы, точно такие же как в инциденте #1057.
Только при вызове метода SaveTitleDynamicContentXSD падает ошибка "Метод объекта не обнаружен", поэтому получить XSD не получается, а по предоставленной в #1057 ссылке (где написано, что схема старая) до сих пор висит старая схема (во всяком случае в ней написано, что надо ставку указывать "20%", а компонента говорит, что это недопустимое значение).
Компонента старая, версия COM x64 5.39.0.861.
Ставить новую компоненту большого смысла нет - планируем уйти от использования компоненты.
Проблема с вызовом вышеуказанного метода только в версии компоненты или может быть и другая причина?
Где все таки взять актуальный XSD?

Спасибо.

**Comment by GilimkhanovDenis** [comment]
В старой компоненте метод называется по-другому

[Box.SaveUserDataXSD(TitleName, Function, Version, DocflowSide, FilePath)](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.SaveUserDataXSD)

**Comment by MaximGlazunov** [comment]
Точно, спасибо.
