### ISSUE TITLE
Ошибка при отправке документа УПД 970. Не заполнен номер ГТД

### ISSUE THREAD

**Issue by MaximGlazunov** [diadoc/diadocsdk-1c-docs#1068]
Добрый день.

При отправке УПД в формате 970 приказа возникла ошибка: не заполнен номер ГТД. Код страны производителя указываю "643".
В приказе написано: При <Функция> = СЧФ | СЧФДОП элемент обязателен, кроме случая, когда <СпОбстФСЧФ> = 2 или в отношении товаров, страной происхождения которых не являются государства - члены Евразийского экономического союза.
Для товаров произведенных в России нужен <СпОбстФСЧФ> = 2?
А если в документе и российские товары, и товары с ГТД (на них не ругается)?
Или ошибка в чем-то другом?
Компонента COM x64 5.39.0.861.
Текст ошибки (в строках 2, 5, 6 и т.д. есть гтд): 
Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalTransferDocument/Table/Item[1]/CustomsDeclarations/CustomsDeclaration: When Function=СЧФДОП: @DeclarationNumber should be filled
/UniversalTransferDocument/Table/Item[3]/CustomsDeclarations/CustomsDeclaration: When Function=СЧФДОП: @DeclarationNumber should be filled
/UniversalTransferDocument/Table/Item[4]/CustomsDeclarations/CustomsDeclaration: When Function=СЧФДОП: @DeclarationNumber should be filled
/UniversalTransferDocument/Table/Item[7]/CustomsDeclarations/CustomsDeclaration: When Function=СЧФДОП: @DeclarationNumber should be filled
/UniversalTransferDocument/Table/Item[8]/CustomsDeclarations/CustomsDeclaration: When Function=СЧФДОП: @DeclarationNumber should be filled
/UniversalTransferDocument/Table/Item[11]/CustomsDeclaration

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Правильно понимаю, что [Сведения о декларации на товары](https://normativ.kontur.ru/document?moduleId=1&documentId=464695&rangeId=6517010) вы заполняете потому, что у вас случай закупки для обеспечения государственных и муниципальных нужд?

В остальных случая, насколько понимаю, в принципе не нужно заполнять этот тэг, если страна происхождения - РФ

**Comment by GilimkhanovDenis** [comment]
Про `СпОбстФСЧФ` есть [статья](https://www.diadoc.ru/blog/50533-novyy_format_upd)

Судя по ней, `СпОбстФСЧФ` не относится напрямую к тому, где произведён товар

**Comment by MaximGlazunov** [comment]
У нас НЕ госзакупка, поэтому мы и не указываем номер ГТД для российский товаров. С форматом по 820 приказу все работает, а 970 выдает ошибку

**Comment by GilimkhanovDenis** [comment]
Попробуйте не заполнять эту коллекцию - по формату она не обязательна

**Comment by MaximGlazunov** [comment]
Попробовал. Эта ошибка ушла, но появилась ошибка ИНН "has wrong checksum". В #1057 Вы советовали изучить XSD.
Сейчас посмотрю, если не пойму, снова буду писать. Не закрывайте, пожалуйста, пока обращение.

**Comment by GilimkhanovDenis** [comment]
Про ИНН.
В УПД 820 для организаций заполняется такой тип::
```
<xs:complexType name="ExtendedOrganizationDetails_ManualFilling">
    <xs:attribute name="OrgType" type="OrganizationType" use="required">
      <xs:annotation>
        <xs:documentation>СвИП - СвЮЛУч - СвИнНеУч</xs:documentation>
      </xs:annotation>
    </xs:attribute>
...
<xs:simpleType name="OrganizationType">
    <xs:annotation>
      <xs:documentation>
				1 - Сведения о юридическом лице, состоящем на учете в налоговых органах // СвЮЛУч
				2 - Сведения об индивидуальном предпринимателе// СвИП
				3 - Сведения об иностранном лице, не состоящем на учете в налоговых органах // СвЮлНеУч, СвИнНеУч
				4 - Сведения о физическом лице // СвФл
			</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="1" />
      <xs:enumeration value="2" />
      <xs:enumeration value="3" />
      <xs:enumeration value="4" />
    </xs:restriction>
  </xs:simpleType>
```

для УПД 970:
```
<xs:complexType name="ExtendedOrganizationDetailsUtd970">
    <xs:complexContent mixed="false">
      <xs:extension base="ExtendedOrganizationDetails_ManualFilling_Utd970">
...
<xs:attribute name="OrgType" type="OrganizationType_DatabaseOrder" use="required">
          <xs:annotation>
            <xs:documentation>СвИП - СвЮЛУч - СвФЛ - СвИнНеУч</xs:documentation>
          </xs:annotation>
        </xs:attribute>
...

<xs:simpleType name="OrganizationType_DatabaseOrder">
    <xs:annotation>
      <xs:documentation>
				1 - Сведения об индивидуальном предпринимателе// СвИП
				2 - Сведения о юридическом лице, состоящем на учете в налоговых органах // СвЮЛУч
				3 - Сведения о физическом лице // СвФл
				4 - Сведения об иностранном лице, не состоящем на учете в налоговых органах // СвИнНеУч
			</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="1" />
      <xs:enumeration value="2" />
      <xs:enumeration value="3" />
      <xs:enumeration value="4" />
    </xs:restriction>
  </xs:simpleType>
```

Т.е. поле называется одинаково, но значения другой смысл несут. Не смогу ответить почему так сделано, но предположу, что где-то в других типах документов уже ведён `OrganizationType_DatabaseOrder` и он почему-то привлекательнее во внутренней логике Диадока, поэтому для нового формата решили использовать его

**Comment by MaximGlazunov** [comment]
Значения оргтайпов местами поняли.
Документ отправился, большое спасибо.
