### ISSUE TITLE
Как скачивать документы регламентным заданием?

### ISSUE THREAD

**Issue by batistadude** [diadoc/diadocsdk-1c-docs#1069]
Всех приветствую. Возможно ли реализовать, чтобы документы скачивались регламентным заданием или что-то вроде этого? Сейчас скачиваю по кнопке - всё скачивается, но хотелось бы, чтобы документы скачивались заложенным сценарием, допустим раз в час.

**Comment by GilimkhanovDenis** [comment]
А в чём проблема?

Компонента может и в РЗ работать

**Comment by batistadude** [comment]
Спасибо!

**Comment by GilimkhanovDenis** [comment]
Единственное, что стоит учитывать, насколько помню, РЗ выполняется на сервере  и загрузка компоненты как Addin на сервере не работает

Нужно загружать как COM ([можно Addin загружать как COM](https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_load.html))
