### ISSUE TITLE
УПД (InvoiceAndBasic)

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#107]
Документ поставщика находится в состоянии "OutboundWithRecipientSignature", соответствующий документ покупателя - в "InboundWithRecipientSignature". Когда они перейдут в "OutboundFinished" и "InboundFinished" соответственно? Как можно ускорить процесс перехода?

**Comment by denver069** [comment]
Похоже для УПД не сформированы [необходимые извещения](http://api-docs.diadoc.ru/ru/latest/docflows/UtdDocflow.html).
Извещения можно сформировать с помощью [ReceiptGenerationProcess](http://1c-docs.diadoc.ru/ru/latest/ReceiptGenerationProcess.html)

**Comment by prog22** [comment]
Пробую и ReceiptGenerationProcess и SendReceiptsAsync. Статусы не меняются.

**Comment by prog22** [comment]
Аналогично с отказом в подписании. Документ покупателя в состоянии "InboundRecipientSignatureRequestRejected",  а поставщика "OutboundWaitingForInvoiceReceipt".

**Comment by denver069** [comment]
Какая используется версия компоненты?
Сертификаты используете подходящие?
Как покупатель так и продавец запускал ReceiptGenerationProcess?

Покажите ссылки на документ.
