### ISSUE TITLE
Как подключиться к Диадоку через сервер?

### ISSUE THREAD

**Issue by batistadude** [diadoc/diadocsdk-1c-docs#1070]
Необходимо, чтобы подписание в Диадок происходило через серверную процедуру. Пишу процедуру в общем модуле на сервере:

&НаСервере
Процедура Подписать(Документ)     Экспорт   

	КлючРазработчика = "api-*****";	
	BoxId = "49d****-******";	
	
	//создаем корневой элемент COM-объекта
	DiadocApi = Новый ComОбъект("Diadoc.Api.InvoiceApi");
	
	//////Задаем параметры подлючения к серверу
	DiadocApi.ApiClientId = КлючРазработчика;
	DiadocApi.ServerUrl   = "https://diadoc-api.kontur.ru:443";
	
	//ищем сертификат, по которому будем подключаться
	ОтпечатокСертификата = "998***";
	СертификатДляПодключения = DiadocApi.GetPersonalCertificate(ОтпечатокСертификата);	
	
	// Создание соединения
	Connection = DiadocApi.CreateConnectionByCertificate2(СертификатДляПодключения);
	
	Документ.Комментарий = "Дошло6"; 
	Документ.Записать();
	
КонецПроцедуры

На сервере установлен сертификат с указанным отпечатком. Сам код подписания еще не написал. так как не получается подключиться к Диадок через сертификат. 

Выходит следующая ошибка:
![image](https://github.com/user-attachments/assets/376ff42b-3747-4b3f-ac8f-95500003b8fb)

В чем может быть ошибка? Причем если создаю соединение через логин и пароль, ошибок нет.

**Comment by batistadude** [comment]
Еще такой вопрос в продолжении предыдущего. Если я авторизуюсь по имени пользователя и паролю, как мне выбрать сертификат для подписания?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Подписание происходит тем сертификатом, по которому произошла авторизация.

Что касается ошибки на скрине, то подсказать не смогу - это ошибка от платформы 1С, а не от компоненты. Возможно, 1С куда-то пишет подробности ошибки

**Comment by batistadude** [comment]
> Добрый день
> 
> Подписание происходит тем сертификатом, по которому произошла авторизация.
> 
> Что касается ошибки на скрине, то подсказать не смогу - это ошибка от платформы 1С, а не от компоненты. Возможно, 1С куда-то пишет подробности ошибки

А в моем коде есть ошибки*?

**Comment by GilimkhanovDenis** [comment]
Выглядит валидно

**Comment by batistadude** [comment]
А вообще возможно ли реализовать, чтобы подписание в диадок проходило в "фоновом режиме"? 
У меня 1с:Документооборот 3.0. Например, по маршруту согласования у меня проходит документ. После его подписания директором, в "фоновом режиме" вызывается процедура, которая подписывает документ с необходимым id в диадок?

**Comment by GilimkhanovDenis** [comment]
Почему нет

Нужно обеспечить, чтобы системный пользователь, от которого запущен сервер 1С имел доступ  к контейнеру закрытого ключа в момент выполнения фонового задания и нужен доступ к интернету

Кажется, это единственные нюансы

**Comment by batistadude** [comment]
> Добрый день
> 
> Подписание происходит тем сертификатом, по которому произошла авторизация.
> 
> Что касается ошибки на скрине, то подсказать не смогу - это ошибка от платформы 1С, а не от компоненты. Возможно, 1С куда-то пишет подробности ошибки

А если авторизация произошла по логину-паролю, как выбрать сертификат?

**Comment by GilimkhanovDenis** [comment]
никак

если авторизация произошла по логину, то для тестовых документов будет использован специальный тестовый сертификат сервиса Диадок
а для боевых документов будет ошибка

**Comment by GilimkhanovDenis** [comment]
Особой разницы нет, будете вы только подписывать документы каким-то сертификатом или же будете авторизовываться под ним - в обоих случаях нужен доступ к закрытому ключу

**Comment by batistadude** [comment]
> Почему нет
> 
> Нужно обеспечить, чтобы системный пользователь, от которого запущен сервер 1С имел доступ к контейнеру закрытого ключа в момент выполнения фонового задания и нужен доступ к интернету
> 
> Кажется, это единственные нюансы

Как предоставить доступ к контейнеру закрытого ключа системному пользователю, от которого запущен сервер 1С? Для этого достаточно установить сертификат с контейнером закрытого ключа в личные сертификаты пользователя?

**Comment by GilimkhanovDenis** [comment]
В личные вы устанавливаете открытую часть и по сути создаёте ссылку на закрытую.

Сама закрытая часть может быть на токене, флешке, в реестре. Будет ли она доступна пользоателю заисит от того как настроите
Думаю, с этим вопросом вам нужно обратиться в техподдержку или во внедрение.
