### ISSUE TITLE
Заполнение основания для счета

### ISSUE THREAD

**Issue by MaximGlazunov** [diadoc/diadocsdk-1c-docs#1072]
Добрый день.

Контрагент попросил нас заполнять поле "Основание" для счета.
В вэб-интерфейсе Диадок данное поле доступно для редактирования (у счета, акта и накладной).
В ком-объекте документа - это поле "Grounds"
Но когда я создаю документ через компоненту методом AddDocumentFromFile("ProformaInvoice", "default", "v1", ПутьКФайлу), поле Grounds отсутствует.
Возможно ли его заполнять через компоненту?
Версия компоненты COM x64 5.39.0.861

**Comment by GilimkhanovDenis** [comment]
Эта информация указывается в метаданных

[CustomDocumentToSend.AddMetadata()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/CustomDocumentToSend.html#CustomDocumentToSend.AddMetadata)

```
dd_Metadata = dd_DocumentToSend.AddMetadata();
dd_Metadata.Key = "Grounds";
dd_Metadata.Value= "Основание";
```

**Comment by MaximGlazunov** [comment]
Я думал об этом варианте, но не думал, что будет так просто.
Огромное спасибо.
