### ISSUE TITLE
Дата приемки в DLL компоненте

### ISSUE THREAD

**Issue by gnp900** [diadoc/diadocsdk-1c-docs#1073]
Добрый день, подскажите кто знает или может, в ВЕБ версии при подписании входящих документов есть поле Дата приемки, в которое указывается дата оказания услуг или дата фактической приемки товара.
Вопрос:
Как при использовании API DLL компоненты, при подписании входящего документа ответной подписью, можно передать дату приемки?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Ответ есть в #670, #1034 и [прочих обращениях](https://github.com/diadoc/diadocsdk-1c-docs/issues?q=is%3Aissue+AcceptanceDate+is%3Aclosed)
