### ISSUE TITLE
Дополнительная информация о контрагенте

### ISSUE THREAD

**Issue by X-BANZAJ** [diadoc/diadocsdk-1c-docs#1074]
Добрый день. Подскажите, если отношения с контрагентом были установлены (и до сих пор) и в какой-то момент организация была ликвидирована, как-то можно получить текстовку через Api которая отражена "красным" в карточке контрагента в Диадоке: "Организация ликвидирована с ..." ? При банкротстве и другом статусе что будет написано "красным"?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Есть флаг [Counteragent](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Counteragent.html).IsLiquidated

Дату не прокидываем. Можем рассмотреть возможность её добавления, но хочется понимать как её планируется использовать.

**Comment by X-BANZAJ** [comment]
@GilimkhanovDenis, да флаг уже посмотрел. Просто эта информация была бы полнее и не было бы надобности лезть искать эту информацию о дате когда организация была ликвидирована. Я так понимаю в Диадоке эта дата и статус тоже результат запроса в API налоговой.

**Comment by GilimkhanovDenis** [comment]
Откуда Диадок тянет дату - детали имплементации сервиса

Зачем нужна эта дата? Что меняется в бизнес процессах, от того будет это дата, или это будет флаг как сейчас?

**Comment by X-BANZAJ** [comment]
@GilimkhanovDenis. в бизнес процессах ничего не поменяется абсолютно, но если на сервисе эта информация есть, то почему бы не иметь возможность ее получить у себя в прикладном решении и не лезть лишний раз за ней в сервис, это всего лишь пожелание, а реализовывать его или нет..

**Comment by GilimkhanovDenis** [comment]
Исторически эта информация в компоненте никому не была нужна

Запишу в бэклог. Может быть когда-нибудь сделаем
