### ISSUE TITLE
Переход с версии компоненты 5.50.0.950 (x64) на 5.53.0.996 (x64)

### ISSUE THREAD

**Issue by dimok22prog1** [diadoc/diadocsdk-1c-docs#1075]
Добрый день.
Планировали перейти с версии компоненты 5.50.0.950 (x64) на 5.53.0.996 (x64).

Создаем документ так: 
**DocumentToSend1 = SendTask.AddDocument("UniversalTransferDocument", ФункцияДокумента, "utd820_05_01_02_hyphen");**

![image](https://github.com/user-attachments/assets/7aec3a81-e31b-47f3-896a-2d907134bb08)

Заполнение и состав данных не меняли. 
Получаем ошибку на заполнении атрибутов com-объекта вот так: 
**ЗаполнитьЗначенияСвойств(UtdSellerContent, UtdSellerContent_Src)**, где 

**UtdSellerContent:**
![image](https://github.com/user-attachments/assets/d8cfbe7f-839d-4000-9bb5-109bcd541f89)

**UtdSellerContent_Src:**
![image](https://github.com/user-attachments/assets/a97c2d30-a39d-4fda-b515-ed94c41bd6b3)
![image](https://github.com/user-attachments/assets/7b84ff4c-e374-4130-b5e9-62f19b2771b4)

Получаем ошибку и исключение: Ошибка при вызове метода контекста (ЗаполнитьЗначенияСвойств): Ошибка установки значения свойства 'DocumentCreator': Неизвестная ошибка

Если не заполнять 'DocumentCreator' (ЗаполнитьЗначенияСвойств(UtdSellerContent, UtdSellerContent_Src,, "DocumentCreator")), то в **UtdSellerContent**:

![image](https://github.com/user-attachments/assets/0f84ed58-e827-4491-b8b8-87400b21efc2)

Я так понимаю, это AppCrash?
Думал, из-за формата электронного документа, попробовал перейти на "utd970_05_02_01", но получил то же.
Подскажите, пожалуйста, в каком направлении двигаться для локализации ошибки.

**Comment by NickZubashevskiy** [comment]
Добрый день! 
Обнаружил ошибку в компоненте, в результате которой выбрасывается исключение при задании имени свойства кириллицей. В ближайшем релизе выйдет фикс

Пока что  могу предложить удалить из `UtdSellerContent_Src` свойства, заданные кириллицей (`ДанныеЗаполненияГрузополучателя`, `ДанныеЗаполненияПокупателя` и т.д.), т.к. в исходной структуре (`UtdSellerContent`) их все равно нет, и они заполняться не будут.

**Comment by dimok22prog1** [comment]
Спасибо!

**Comment by NickZubashevskiy** [comment]
Добрый день!
Ошибка с русскими символами была исправлена в новом [релизе](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_53_1.html)
