### ISSUE TITLE
УПД 970 заполнение подписанта титула покупателя

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#1076]
Здравствуйте. При заполнение подписанта для УПД 820 всё очень просто:
```
Signer=Content.Signers.AddItems()
Signer.SignerReference.BoxId = BoxId
Signer.SignerReference.CertificateThumbprint = Box.Certificate.Thumbprint
```
то есть все данные (ФИО, должность) берутся из сертификата, а как то же самое сделать для УПД 970?
Смотрел UserDataXSD для УПД 970, но так и не понял, есть ли такая возможность.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Что-то похожее спрашивали в https://github.com/diadoc/diadocsdk-1c-docs/issues/1063

Структура подписанта несколько отличается от 820, но в целом должно быть возможно

**Comment by evgen421** [comment]
Я посмотрел #1063, но там вариант заполнения не из сертификата.
Попытался вот так:
```
Content.Signers.BoxId = Фирма.BoxId;
Signer=Content.Signers.AddSigner();
Signer.Certificate.CertificateThumbprint = Box.Certificate.Thumbprint;
```
Получаю ошибку;
```
Ошибка: HTTP error: Invalid data UserContractData:
Line: 8, Position: 3, /UniversalTransferDocumentBuyerTitle[1]: The element 'UniversalTransferDocumentBuyerTitle' has incomplete content. List of possible elements expected: 'ContentOperCode'.
/UniversalTransferDocumentBuyerTitle/Signers/Signer: @SignerPowersConfirmationMethod must be filled
```

**Comment by chipdip-partner-1C** [comment]
Заполните Signer.SignerPowersConfirmationMethod = "2";  
Поле обязательное для заполнения.
способ подтверждения полномочий представителя на подписание документа [СпосПодтПолном]

Принимает значение:
1 - в соответствии с данными, содержащимися в электронной подписи \|
2 - в соответствии с доверенностью в электронной форме в машиночитаемом виде, если представление доверенности осуществляется посредством включения в каждый пакет электронных документов, подписываемых представителем \|
3 - в соответствии с доверенностью в электронной форме в машиночитаемом виде, если представление доверенности осуществляется из информационной системы. При этом необходимая информация для запроса доверенности из информационной системы, указана в электронном документе \|
4 - в соответствии с доверенностью в электронной форме в машиночитаемом виде, если представление доверенности осуществляется из информационной системы. При этом необходимая информация для запроса доверенности из информационной системы представляется способом, отличным от указания в электронном документе \|
5 - в соответствии с доверенностью в форме документа на бумажном носителе \|
6 - иное

**Comment by evgen421** [comment]
Спасибо.
