### ISSUE TITLE
Длина строки "наименование товара".

### ISSUE THREAD

**Issue by ElenaBurnasheva** [diadoc/diadocsdk-1c-docs#1078]
Здравствуйте. 
Нужно в поле наименование товара через API передать строку длиной более 1000 символов.  Это как то возможно сделать?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Ограничения как правило прописаны в формате документа (могут был отличия между разными форматами документов и их редакцией). А формат регулируется ФНС. Поэтому нет, невозможно - какие ограничения прописаны в формате или в UserDataXSD, те и нужно использовать

Исключение. Форматы документов, которые разрабатывались специально под вас (услуга "Свои типы документов") - там ограничения не такие строгие, так как сам заказчик формата может менять требования к формату и документу

Уточнение. Свой тип документов не может заменять документы, регулируемые ФНС (нельзя разработать свой формат Счёта-фактуры и использовать его вместо установленного ФНС)
