### ISSUE TITLE
Повторно: УПД (InvoiceAndBasic)

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#108]
Документ поставщика находится в состоянии "OutboundWithRecipientSignature", соответствующий документ покупателя - в "InboundWithRecipientSignature". Когда они перейдут в "OutboundFinished" и "InboundFinished" соответственно? Как можно ускорить процесс перехода?

Пробую и ReceiptGenerationProcess и SendReceiptsAsync. Статусы не меняются.

Аналогично с отказом в подписании. Документ покупателя в состоянии "InboundRecipientSignatureRequestRejected", а поставщика "OutboundWaitingForInvoiceReceipt".

Я делаю так: 
1) формирую титул продавца; 
2) формирую титул покупателя; 
3) запускаю SendReceiptsAsync от Document покупателя; 
4) запускаю SendReceiptsAsync от Document продавца.

**Comment by denver069** [comment]
Ссылка на первый запрос https://github.com/diadoc/diadocsdk-1c-docs/issues/107#issuecomment-304263679

**Comment by denver069** [comment]
Какая используется версия компоненты?
Сертификаты для ReceiptGenerationProcess те-же что и при подписи титулов?
Покажите ссылку на документ.

**Comment by prog22** [comment]
Использую COM-компоненту для встраивания в произвольные системы, для 64-х битных приложений - 5.17.0.201.
Сертификат один. Привязан к двум ящикам.
Примеры документов (поставщика):
1) Подписание: https://diadoc.kontur.ru/5cc59872-767d-471d-8f28-f125aabfaf8a/Document/Show?letterId=1e62be45-13f0-490b-afe6-53ca116ddbfc&documentId=3adc9e51-205f-43a3-b7de-b6f9d8f169d9

2) Отказ в подписи: https://diadoc.kontur.ru/5cc59872-767d-471d-8f28-f125aabfaf8a/Document/Show?letterId=f8a593f6-25b7-4f8b-80ee-e6aaccbe1900&documentId=d0462936-598d-44bf-b21c-5b649b394b88

**Comment by denver069** [comment]
В следующей версии компоненты после 5.18.1.219, метод _SendReceiptsAsync_ будет доработан и отправка извещений будет выполнятся без задержек.

На данный момент стабильно работает фоновый процесс [ReceiptGenerationProcess](http://diadocsdk-1c.readthedocs.io/ru/latest/ReceiptGenerationProcess.html), который периодически опрашивает Диадок о наличии подтверждений оператора требующих извещений и выполняет их генерацию подпись и отправку.

Для получения информации о выходе новой версии внешней компоненты, вы можете подписаться на ленту новостей [RSS](http://diadocsdk-1c.readthedocs.io/ru/latest/index.rss)
