### ISSUE TITLE
CertificateOwnerType

### ISSUE THREAD

**Issue by defin85** [diadoc/diadocsdk-1c-docs#1080]
Добрый день, где SDK берет информацию о CertificateOwnerType ?

**Comment by DmitryModin** [comment]
Добрый день!

Информация вычисляется из контента сертификата.

**Comment by defin85** [comment]
> Добрый день!
> 
> Информация вычисляется из контента сертификата.

А можете алгоритмом поделиться ?

**Comment by DmitryModin** [comment]
Добрый день!

Такой возможности нет, но найти информацию про КЭП и их структуру можно тут -  https://www.consultant.ru/document/cons_doc_LAW_125557/
