### ISSUE TITLE
Ошибка при авторизации по сертификату CreateConnectionByCertificate2

### ISSUE THREAD

**Issue by batistadude** [diadoc/diadocsdk-1c-docs#1081]
Есть процедура, написанная на сервере
![image](https://github.com/user-attachments/assets/33fe5136-477f-46d8-a551-c48754f1c136)

При ее выполнении выходит ошибка "Ошибка при вызове метода контекста (CreateConnectionByCertificate2)". В чем может быть причина?
На сервере есть сертификат и контейнер закрытого ключа.

**Comment by batistadude** [comment]
Причем если я делаю подписание через кнопку, то ошибки не возникает 
![image](https://github.com/user-attachments/assets/69a70fa2-b8e0-4fbb-841a-f33a40501477)

**Comment by NickZubashevskiy** [comment]
Добрый день!
Первое, что приходит в голову - возможно, на контейнере закрытых ключей сервера стоит пароль. Если так, то его нужно задать через метод [SetPin](https://developer.kontur.ru/docs/Diadoc/COM/ComObjects/CertificateInfo.html#CertificateInfo.SetPin) до вызова `CreateConnectionByCertificate2`

**Comment by GilimkhanovDenis** [comment]
Предлагаю всё же начать с того, чтобы получить полный текст ошибки, возвращаемым методом
