### ISSUE TITLE
Проблема отображения поля Документ об отгрузке 

### ISSUE THREAD

**Issue by XXXPenguinXXX** [diadoc/diadocsdk-1c-docs#1083]
Добрый день!
Формирую Счет-фактуру с помощью компоненты DiadocCom_5_50_0_950_x64.dll
При отправке в сам Диадок поле которое было заполненно с помощью компоненты
	ДокументПодтверждающийОтгрузку = Utd820_SellerContent.DocumentShipments;
	НовыйДокументОбОтгрузке = ДокументПодтверждающийОтгрузку.AddDocumentShipment();
	НовыйДокументОбОтгрузке.Name = ДанныеДокумента.НаименованиеДокументаОбОтгрузке;
	НовыйДокументОбОтгрузке.Number = ДанныеДокумента.НомерДокументаОбОтгрузке;
	НовыйДокументОбОтгрузке.Date = Формат(ДанныеДокумента.Дата, "ДФ=dd.MM.yyyy");

не отображает в печатной форме документа (5а), его в принципе там нет 
В чем может быть проблема?
Использую данные параметры:
First_DocumentToSend = SendTask.AddDocument("Invoice", "default", "utd820_05_01_02_hyphen");
Utd820_SellerContent.Function = "СЧФ";

**Comment by GilimkhanovDenis** [comment]
Добрый день

предоставьте, пожалуйста:

1. ссылку на отправленный документ
2. информацию какими значениями по факту заполнен `Utd820_SellerContent.DocumentShipments` перед отправкой документа

**Comment by XXXPenguinXXX** [comment]
Документ был заполнен тестовыми данными:
https://diadoc.kontur.ru/3b876717-876f-49e0-bd13-6abffd76a343/Document/Show?letterId=da4168cc-01c5-48c9-b31c-f273f1fabf4c&documentId=8de66312-51aa-4699-94b6-ae4abbf101fd

НовыйДокументОбОтгрузке.Name = "Наименование документа об отгрузке";
НовыйДокументОбОтгрузке.Number = "9826";
НовыйДокументОбОтгрузке.Date = Формат(ТекущаяДата(), "ДФ=dd.MM.yyyy");

**Comment by GilimkhanovDenis** [comment]
Данные в XML документе заполнены:
`<ДокПодтвОтгр НаимДокОтгр="Наименование документа об отгрузке" НомДокОтгр="9826" ДатаДокОтгр="31.05.2021" />`

именно XML имеет юридическую силу, а не печатная форма. Если вопрос только про печатную форму. то обратитесь в техподдержку. Со стороны компоненты всё корректно
