### ISSUE TITLE
Проблема с отправкой УПД для грузополучателя - физлица

### ISSUE THREAD

**Issue by heratei** [diadoc/diadocsdk-1c-docs#1085]
Добрый день!

Отправляем УПД, в которой контрагент - юрлицо, а грузополучатель - физлицо. При этом мы не знаем ИНН грузополучателя физлица. Получаем ошибку отправки:
/UniversalTransferDocument/Consignees/Consignee/OrganizationDetails: @Inn is required

Метод:
SendTask = Organization.CreatePackageSendTask2();
DocumentToSend = SendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01")

Внешняя компонента: x86 5.49.0.932

Подскажите, можно ли отправить УПД без ИНН физлица грузополучателя?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Попробуйте использовать версию `utd820_05_01_02_hyphen` - там можно заполнять значения прочерками.

Имена полей в DynamicContent'е могут отличаться между версиями
