### ISSUE TITLE
AddDocumentFromFile для 970 приказа

### ISSUE THREAD

**Issue by nikolaenko-e-v** [diadoc/diadocsdk-1c-docs#1086]
Используем компоненту. Хотим отправить документ УПД в 970 приказе. В документации сказано так: 
// Добавление документа УПД с контентом, взятым из файла
    Second_DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_02_hyphen", "С:\\Moй УПД.xml");
    Second_DocumentToSend.Comment = "Это УПД с контентом, загруженным из файла";

Что надо писать в DocumentVersion для 970 приказа (вместо "utd820_05_01_02_hyphen")

**Comment by GilimkhanovDenis** [comment]
Добрый день

Обратите внимание на страницу https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_type_function_version.html
