### ISSUE TITLE
Срочно! Ошибка. Не отправляются приглашение к партнерству.

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#109]
Добрый день.
Используем COM-компоненту для встраивания в произвольные системы- версия 5.18.0.210,
отправляю приглашение к партнерству контрагенту 3459071763 (Контрагент работает в Диадоке)
![img-2017-06-05-11-54-08](https://cloud.githubusercontent.com/assets/20082460/26777458/fe237f78-49e5-11e7-9016-c7472fc9738d.png)
```
Если ЗначениеЗаполнено(ИмяФайла) Тогда			
    AcquireCounteragentTask = Organization.CreateAcquireCounteragentTask(ПолныйПуть);
    Если ЗначениеЗаполнено(CounteragentId) тогда
       AcquireCounteragentTask.CounteragentBoxId = CounteragentId; 
    КонецЕсли;
   AcquireCounteragentTask.Inn 				= ИНН;
  AcquireCounteragentTask.Message 			= Комментарий; 
  AcquireCounteragentTask.FileName 			= ИмяФайла;
 ИдентОрг =  AcquireCounteragentTask.Send(); //возвращает идентификатор организации-получателя приглашения
```
Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (AcquireCounteragentTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Can't deserialize request body into type: AcquireCounteragentRequest

Просим исправить, работал данный код успешно с начала года.

**Comment by jakeqwert** [comment]
В объекте все поля заполнены верными значениями, файл приглашения существует.

**Comment by azhipaigor** [comment]
Проблема связана с libproto в x64 конфигурации. Сейчас разбираемся почему только сейчас сломалось и изыскиваем пути решения. В качестве временного решения можно использовать [x86-билд](http://diadocsdk-1c.readthedocs.io/ru/latest/_downloads/DiadocComApi.dll).

**Comment by denver069** [comment]
Как только ошибка в libproto в x64 будет исправлена, обновим внешнюю компоненту.

Для получения информации о выходе новой версии внешней компоненты, вы можете подписаться на ленту новостей [RSS](http://diadocsdk-1c.readthedocs.io/ru/latest/index.rss)
