### ISSUE TITLE
Заполнение Emails 970 формат

### ISSUE THREAD

**Issue by SlothFive** [diadoc/diadocsdk-1c-docs#1093]
Как заполнить Emails? В новом формате вместо Email (тип строка) добавили com объект Emails, в котором содержится com объект Email, но при попытки добавить методом addEmail() выдает ошибку. Как нужно правильно заполнять?
![image](https://github.com/user-attachments/assets/448653b6-dd22-44d4-a73f-099e8440d656)

![image](https://github.com/user-attachments/assets/3019c219-e837-4ab8-993a-66f5ea332c68)

**Comment by GilimkhanovDenis** [comment]
Добрый день

`Email` - коллекция строк. метод добавления принимает единственный параметр - значение нового элемента. Т.е.

`Emails.AddEmail("example@domen.com")`

https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html

![image](https://github.com/user-attachments/assets/9a9a3e7b-d32b-4d4d-8c24-c03a0d652b3e)

**Comment by SlothFive** [comment]
Спасибо!
