### ISSUE TITLE
WIN32[0x00002EF3]WinHttpReceiveResponse при работе через прокси на 5.53.1.1004 (com x64)

### ISSUE THREAD

**Issue by dimok22prog1** [diadoc/diadocsdk-1c-docs#1094]
Здравствуйте.
Пытаемся перейти с версии компоненты 5.50.0.950 (com x64) на 5.53.1.1004 (com x64).

На одном и том же окружении получаем:

![Pic](https://github.com/user-attachments/assets/a574a968-2114-47f6-8f9c-0a340c41b9f7)

При вызове objConnection = ДиадокАпи.TestConnection2(), старая версия возвращает objConnection.ConnectionSuccess = Истина.
А новая возвращает objConnection.ConnectionSuccess = Ложь, а objConnection.ErrorText = WIN32[0x00002EF3]WinHttpReceiveResponse.

Подскажите, с чем может быть связано такое поведение? Как работать через Proxy?

**Comment by GilimkhanovDenis** [comment]
Добрый день

какой способ аутентификации на прокси используется (`NTLM`, `Kerberos`, ...)?

**Comment by GilimkhanovDenis** [comment]
Ошибка на любое подключение возникает или же иногда `ДиадокАпи.TestConnection2()` завершается успехом?

**Comment by dimok22prog1** [comment]
>>какой способ аутентификации на прокси используется

логин-пароль

>>Ошибка на любое подключение возникает или же иногда ДиадокАпи.TestConnection2() завершается успехом?

на любое, ни разу не завершился успехом ДиадокАпи.TestConnection2()

**Comment by dimok22prog1** [comment]
Если это поможет, то предыдущая версия 5.53.0.996 x64 работает, ДиадокАпи.TestConnection2() через Proxy проходит без ошибок.

**Comment by dimok22prog1** [comment]
Подскажите, пожалуйста, ждать ли нового релиза компоненты?
Не хотелось бы переходить на 5.53.0, т.к. критично:

**AppCrash в процессе автоматической отправки ИоП [ReceiptGenerationProcess](https://developer.kontur.ru/Docs/Diadoc/Com/ComObjects/ReceiptGenerationProcess.html)**

**Comment by GilimkhanovDenis** [comment]
Добрый день

Да, постараемся на этой неделе выпустить, причину ошибки нашёл

**Comment by GilimkhanovDenis** [comment]
Проверьте. пожалуйста, на версии [5.53.2](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_53_2.html)

[Ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)

**Comment by dimok22prog1** [comment]
Соединение устанавливается, но при выносе на рабочее окружение получаем AppCrash процесса.
Пробую собрать дампы.

**Comment by dimok22prog1** [comment]
Собрал и выполнил анализ дампов по статье:
[Сбор и анализ dump](https://learn.microsoft.com/ru-ru/troubleshoot/windows/win32/com-supports-collect-dump-file).

Результат во вложении.
[MultipleDumps_MultipleRules.zip](https://github.com/user-attachments/files/17943219/MultipleDumps_MultipleRules.zip)

**Comment by GilimkhanovDenis** [comment]
А можно получить сами dmp файлы?

**Comment by dimok22prog1** [comment]
Подскажите, их можно чем-то / как-то просмотреть? Безопасность не пропускает в таком виде (беспокоятся за наличие конфиденциальной информации) :(

**Comment by GilimkhanovDenis** [comment]
Просмотреть-то их можно, например WinDBG. Например там будет состояние стека в момент падения. Но без отладочных символов вряд ли увидите что-то осмысленное

**Comment by GilimkhanovDenis** [comment]
Возможно, сможем воспроизвести у себя, если опишите способ воспроизведения подробнее:

- падает на `ДиадокАпи.TestConnection2()` или на другом методе, обращении к какому-то полю и т.д.
- Чем отличаются тестовое окружение, где, насколько понял, всё работает, от боевого. Возможно, полезная информация будет в [диагностиках](https://help.kontur.ru/diadoc) с этих мест
- любая другая информация

**Comment by dimok22prog1** [comment]
> Возможно, сможем воспроизвести у себя, если опишите способ воспроизведения подробнее:
> 
> * падает на `ДиадокАпи.TestConnection2()` или на другом методе, обращении к какому-то полю и т.д.
> * Чем отличаются тестовое окружение, где, насколько понял, всё работает, от боевого. Возможно, полезная информация будет в [диагностиках](https://help.kontur.ru/diadoc) с этих мест
> * любая другая информация

Попробуем воспроизвести сценарий. Дело в том, что на тестовом окружении нет нагрузочного тестирования и проверялся один сценарий.

**Comment by dimok22prog1** [comment]
> Просмотреть-то их можно, например WinDBG. Например там будет состояние стека в момент падения. Но без отладочных символов вряд ли увидите что-то осмысленное

[](https://disk.yandex.ru/d/M-qe_NxWYh6TpQ)

**Comment by dimok22prog1** [comment]
> Просмотреть-то их можно, например WinDBG. Например там будет состояние стека в момент падения. Но без отладочных символов вряд ли увидите что-то осмысленное

[](https://disk.yandex.ru/d/M-qe_NxWYh6TpQ)

**Comment by dimok22prog1** [comment]
> Просмотреть-то их можно, например WinDBG. Например там будет состояние стека в момент падения. Но без отладочных символов вряд ли увидите что-то осмысленное

[https://disk.yandex.ru/d/M-qe_NxWYh6TpQ](url)

**Comment by NickZubashevskiy** [comment]
Дампы немного не то содержат, попробуйте собрать с помощью [ProcDump](https://learn.microsoft.com/en-us/sysinternals/downloads/procdump):

`procdump -e -ma -w <process_name>`

**Comment by NickZubashevskiy** [comment]
Все-таки нашли в дампах нужную информацию, и дополнительные пока не нужны

**Comment by GilimkhanovDenis** [comment]
@dimok22prog1 Правильно понимаю, что appcrash происходит на сервере 1С, на котором одновременно с компонентой работает много пользователей?

**Comment by dimok22prog1** [comment]
> @dimok22prog1 Правильно понимаю, что appcrash происходит на сервере 1С, на котором одновременно с компонентой работает много пользователей?

Совершенно верно. И работа с компонентой выполняется в несколько параллельных процессов.

Как вариант, почему работало на тестовом сервере: с компонентой работали в один поток + пользователей на нем практически не было. Если это связано, конечно.

Все сценарии еще не тестировали (если это ошибка какого-то конкретного метода). В планах.

**Comment by GilimkhanovDenis** [comment]
Сегодня или в начале следующей недели выпустим фикс

**Comment by GilimkhanovDenis** [comment]
Добрый день

Попробуйте, пожалуйста, версию [5.53.3](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_53_3.html)

[Ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)

**Comment by dimok22prog1** [comment]
Доброе утро.
С appcrash проблема ушла.

Но появилась новая, не всегда, но очень часто появляется ошибка:

- Произошла исключительная ситуация (DiadocCom.CreateConnectionByLogin): LIBHTTP[0x0000001F] base address must be absolute

- Произошла исключительная ситуация (DiadocCom.CreateConnectionByCertificate2): LIBHTTP[0x0000001F] base address must be absolute

- Нет соединения с ИНТЕРНЕТ (сервис Диадок, TestConnection2()): LIBHTTP[0x0000001F] base address must be absolute

**Comment by GilimkhanovDenis** [comment]
Предлагаю в [отдельном треде](https://github.com/diadoc/diadocsdk-1c-docs/issues/1104) обсудить эту проблему

Данное обращение закрываю
