### ISSUE TITLE
Тарификация по контрагентам

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#1095]
Как выяснилось, по документам разных контрагентов в Диадоке идет разная тарификация: EDI или Diadoc. Даже если работа ведется только в Диадоке и EDI с клиентом не используется.
Можно ли как-то через API получить информацию о тарификации?

**Comment by ButurlakinSemyon** [comment]
@dorexpro Добрый день!
К сожалению, через API такую информацию получить нельзя. Можете уточнить ваш сценарий? Какую проблему хотите решить?

**Comment by dorexpro** [comment]
Хотим на момент подключения контрагента к ЭДО понимать к какому типу тарификации он относится. Из-за той фичи с тарификацией приходится оплачивать два пакета документов. При этом абсолютно непонятно какой объем документов на какой пакет приходится.

**Comment by ButurlakinSemyon** [comment]
@dorexpro Можете поделиться идентификаторами (BoxId) вашей организации и контрагента, чтобы разобрать кейс на конкретном примере?
И еще уточните, пожалуйста, ваш кейс касается отправки документов исключительно через интеграцию на [COM Diadoc API](https://developer.kontur.ru/docs/Diadoc/COM/index.html)?

**Comment by dorexpro** [comment]
GUID нашей организации: e65822e9-be34-49cc-8dd6-a256fcfae77b
GUID контрагента, тарифицирующегося по EDI: b8c6e66e-da6d-4607-9a85-02182cc0a708
GUID контрагента, тарифицирующегося по Diadoc: ef1f27d4-48da-4b4e-b063-a292bb0feddb

Мы используем вашу компоненту для работы с Диадок версии AddIn x86 5.45.0.912 в собственной разработке на 1С версии 7.7. Так же у нас оплачен доступ к Контур.EDI и мы можем оттуда тянуть какую-то нужную информацию.

**Comment by ButurlakinSemyon** [comment]
@dorexpro добрый день!
К вашей организации привязано два лицевых счета: EDI и Диадок. При этом ни один из них не был выбран в качестве основного лицевого счета. Мы установили лицевой счет Диадока в качестве основного, теперь все отправленные документы будут списываться с тарифа Диадока.

**Comment by dorexpro** [comment]
@ButurlakinSemyon доброго дня.
Спасибо большое. Посмотрим, как это теперь будет работать.
