### ISSUE TITLE
Как получить список входящих шаблонов?

### ISSUE THREAD

**Issue by viga1979** [diadoc/diadocsdk-1c-docs#1097]
Ранее в https://github.com/diadoc/diadocsdk-1c-docs/issues/899?ysclid=m3pe91f0te289459658 
 упоминалось что "Сценарий получения списка входящих шаблонов не реализован". Чтото изменилось с тех пор?
Есть ли какой-то способ получить список входящих шаблонов? То есть для того, чтобы получить входящий шаблон нужен идентификатор, но откуда его можно  получить?

**Comment by GilimkhanovDenis** [comment]
Добрый день

На данный момент ничего не изменилось. После нового года планируем сделать новую ленту событий в ящике (вместо [ Box.GetDocumentEventList](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.GetDocumentEventList))
Можно будет получить через неё
