### ISSUE TITLE
Часто слетает компонента

### ISSUE THREAD

**Issue by SlothFive** [diadoc/diadocsdk-1c-docs#1098]
Добрый день! 

Часто слетает компонента, при подключении выдает ошибку - Ошибка при вызове конструктора (ComОбъект): -2147221164(0x80040154): Class not registered

Компоненту перерегистрировали,  перезагружали сервер но ошибка остается.

Подскажите, в чем может быть проблема?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Значит что-то/кто-то её разрегистрирует или регистрирует так, что при следующем подключении не хватает прав на подключение
Возможно, разрегистрация проходит как-то частично и остаются ветки в реестре. которые потом мешают зарегистрироваться новой компоненте и подключение не возможно

Зависит ещё от того как перерегистрируете (с какими ключами), закрыты ли при этом приложения, использующие компоненту и завершены ли их службы.
Иногда проблема в том, что контроль учётных записей (UAC) мешает и достаточно его выключить.
Иногда помогает подключить компоненту, запустив интеграцию от имени администратора.
Или антивирус меняет поведение регистрации и регистрирует DLL внутри своей песочницы

Предлагаю с этим вопросом в техподдержку или внедрение обратиться - в рамках гитхаба можно только гадать, так как очень многое заисит от локального окружения, а не самой компоненты

**Comment by SlothFive** [comment]
Спасибо!

**Comment by SlothFive** [comment]
Проблему решили.  Зарегистрировали компоненту под юзером под которым запускается 1С и тогда все заработало.
Получается инструкция https://developer.kontur.ru/docs/Diadoc/COM/HowTo/HowTo_register.html не очень корректна или возможно проблема в компоненте т.к. на сервере стоит старая версия 5_39_0_861.
