### ISSUE TITLE
Отправка документ с подписью через оператора ЭДО

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#11]
Необходима возможность отправлять документ уже с подписью. Для ускорения массового процесса отправки документа.
Пользователи на местах подписывают документы, а сервер их выкладывает Оператору ЭДО.
Как можно отправить средствами API документ уже с подписью?

**Comment by vasbur** [comment]
Во внешней компоненте для 1С такого механизма не предусмотрено.
Можете воспользоваться инструментами базового АПИ, там эти операции можно разделить
