### ISSUE TITLE
Ошибка при выполнении метода "SendDraftAsync"

### ISSUE THREAD

**Issue by DemyanSima** [diadoc/diadocsdk-1c-docs#110]
Добрый день. 

После выполнения строчки.

РезультатОтправки = Organization.SendDraftAsync(ИДЧерновика); 

Происходит разрыв соединения с сервером

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html><head><title>1C:Enterprise 8 application error</title></head><body><h2>1C:Enterprise 8 application error:</h2>Error executing query<br><b>by reason: </b><br> server_addr=tcp://****:1560 descr=104(0x00000068): Connection reset by peer line=1562 file=./src/DataExchangeTcpClientImpl.cpp</body></html>

В чем может быть проблема ?

**Comment by azhipaigor** [comment]
Ошибка в компоненте, исправлена в ревизии 5.18.1
