### ISSUE TITLE
Невозможно получить данные по ключу: /Файл/СвУчДокОбор/@ИдОтпр

### ISSUE THREAD

**Issue by ElenaBurnasheva** [diadoc/diadocsdk-1c-docs#1101]
Здравствуйте. 
Возникла ошибка при попытке отправить еще раз ранее отправленные документы (август 2023 г) через АПИ.
При отправке возникает ошибка "Невозможно получить данные по ключу: /Файл/СвУчДокОбор/@ИдОтпр". 
Текущие документы отправляются.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Какие Type, Function и Version у документа на отправку?

Как/какими данными заполняете контент в документе на отправку?

**Comment by ElenaBurnasheva** [comment]
Документ на отправку создается так;
DocumentToSend = SendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01");
Данные для заполнения получаю так:
DynamicContent = DocumentToSend.Content;
Utd820_SellerContent = DynamicContent.UniversalTransferDocument;
Потом заполняю Utd820_SellerContent. 
Работает один механизм и для новых и для старых документов.

**Comment by GilimkhanovDenis** [comment]
Какими данными заполняете информацию о продавце(-ах) ?

**Comment by ElenaBurnasheva** [comment]
Во всех случаях организация выступает как агент поставщика, в поле отправитель данные сторонней организации. 
Нужен конкретный пример?

**Comment by GilimkhanovDenis** [comment]
Да, нужен конкретный пример.

ИдОтпр генерируется по данным из контента. в данном случае - из данных продавца. Если ящик по реквизитам не  найден или неоднозначен, то будет такая ошибка

Если использовать версию выше `utd820_05_01_01`, то в контенте будет отдельное поле для заполнения тэга в XML

**Comment by ElenaBurnasheva** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\MOROZO~1\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\MOROZO~1\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Выражение | Значение | Тип
-- | -- | --
OrganizationDetails | COMОбъект | COMОбъект
Address | COMОбъект | COMОбъект
AddressCode | "" | Строка
ForeignAddress | COMОбъект | COMОбъект
Address | "440064,   Пензенская обл, Пенза г, Строителей пр-кт, дом 69, квартира 42" | Строка
Country | "643" | Строка
RussianAddress | COMОбъект | COMОбъект
Apartment | "" | Строка
Block | "" | Строка
Building | "" | Строка
City | "" | Строка
Locality | "" | Строка
Region | "" | Строка
Street | "" | Строка
Territory | "" | Строка
ZipCode | "" | Строка
BankAccountNumber | "40702810129840001290" | Строка
BankId | "042202824" | Строка
BankName | "ФИЛИАЛ   "НИЖЕГОРОДСКИЙ" АО "АЛЬФА-БАНК"" | Строка
CorrespondentAccount | "30101810200000000824" | Строка
Country | "" | Строка
Department | "" | Строка
Email | "" | Строка
FnsParticipantId | "" | Строка
IndividualEntityRegistrationCertificate | "" | Строка
Inn | "5823009329" | Строка
Kpp | "583501001" | Строка
LegalEntityId | "" | Строка
Okdp | "" | Строка
Okopf | "" | Строка
Okpo | "" | Строка
OrgName | "ООО   "ЕВРОТРАНС"" | Строка
OrgType | "1" | Строка
OrganizationAdditionalInfo | "" | Строка
OrganizationOrPersonInfo | "" | Строка
Phone | "" | Строка
ShortOrgName | "" | Строка
OrganizationReference | COMОбъект | COMОбъект
BankAccountNumber | "" | Строка
BankId | "" | Строка
BankName | "" | Строка
BoxId | "" | Строка
CorrespondentAccount | "" | Строка
Country | "" | Строка
Department | "" | Строка
Email | "" | Строка
IndividualEntityRegistrationCertificate | "" | Строка
LegalEntityId | "" | Строка
Okdp | "" | Строка
Okopf | "" | Строка
Okpo | "" | Строка
OrgType | "" | Строка
OrganizationAdditionalInfo | "" | Строка
OrganizationOrPersonInfo | "" | Строка
Phone | "" | Строка
ShortOrgName | "" | Строка



</body>

</html>

**Comment by GilimkhanovDenis** [comment]
Похоже, на ошибку со стороны сервиса

**Comment by GilimkhanovDenis** [comment]
Ждём исправления

**Comment by GilimkhanovDenis** [comment]
Добрый день

Проверьте, пожалуйста, сценарий сейчас
