### ISSUE TITLE
Подписание вх. УПД по 970  Титул покупателя UTD970BuyerContent

### ISSUE THREAD

**Issue by lsp71** [diadoc/diadocsdk-1c-docs#1102]
Описание по ссылке https://developer.kontur.ru/Docs/Diadoc_UM/objects/970%40/UTD970BuyerContent.html
не соответствует (по структуре и именам полей) реальному Com-объекту. Приходится заполнять наугад (глядя в текст приказа ФНС). Тем не менее, некоторые поля отгадать не удалось, а именно:
Подписант.**SignerStatus**
Подписант.**Position.PositionSource**
Подскажите, пожалуйста, что это за поля, чему (в 970-м приказе) соответствуют и как заполнять?
Ошибки при PatchTask.Send():
HTTP error: Invalid data UserContractData:
Line: 6, Position: 11, /UniversalTransferDocumentBuyerTitle[1]/Signers[1]/Signer[1]/@SignerStatus: The 'SignerStatus' attribute is invalid - The value '5' is invalid according to its datatype 'String' - The Enumeration constraint failed.
Line: 9, Position: 14, /UniversalTransferDocumentBuyerTitle[1]/Signers[1]/Signer[1]/Position[1]/@PositionSource: The 'PositionSource' attribute is invalid - The value 'PositionSourceUnspecified' is invalid according to its datatype 'String' - The Enumeration constraint failed.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Вы ссылаетесь на документацию модуля, которая никакого отношения не имеет к COM-компоненте.

Вам нужна [эта статья](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html) - поля есть в UserDataXSD, поэтому они есть в контенте. Описание полей так же находится в этой XSD

Возможно, будет полезно https://github.com/diadoc/diadocsdk-1c-docs/issues/1077
