### ISSUE TITLE
Вопрос по формированию utd970_05_02_01

### ISSUE THREAD

**Issue by dimok22prog1** [diadoc/diadocsdk-1c-docs#1103]
Создаем DocumentToSend1 = SendTask.AddDocument("UniversalTransferDocument", ФункцияДокумента, "utd970_05_02_01").

Показалось странным:

1) Ранее (при формировании "utd820_05_01_02_hyphen"), при заполнении OrganizationDetails (UtdSellerContent.Sellers.AddSeller() / UtdSellerContent.Buyers.AddBuyer() / UtdSellerContent.Consignees.AddConsignee()), OrganizationDetails.OrgType = 1 определял ЮрЛицо ("LegalEntity"), а OrganizationDetails.OrgType = 2 - ИП ("IndividualEntity").

Теперь наоборот. Иначе возникает ошибка при отправке.

2) При заполнении TaxRate допустимые значения перечисления:

      <xs:enumeration value="NoVat" />
      <xs:enumeration value="ZeroPercent" />
      <xs:enumeration value="TenPercent" />
      <xs:enumeration value="TwentyPercent" />
      <xs:enumeration value="TenFraction" />
      <xs:enumeration value="TwentyFraction" />
      <xs:enumeration value="TaxedByAgent" />

вместо (раньше):

      <xs:enumeration value="0%" />
      <xs:enumeration value="10%" />
      <xs:enumeration value="18%" />
      <xs:enumeration value="20%" />
      <xs:enumeration value="10/110" />
      <xs:enumeration value="18/118" />
      <xs:enumeration value="20/120" />

Это так и останется или будут правки (схемы или компоненты)?

**Comment by GilimkhanovDenis** [comment]
Добрый день

1. Насколько знаю, это было осознанное решение Диадока поменять порядок значений в енуме. В части документов он был как у УПД 820, а у части - как сейчас у УПД 970. Решено было к единому виду привести.

2. Скорее всего так и останется, но ещё уточню у авторов XSD

**Comment by dimok22prog1** [comment]
Еще странное:

1) Формируем Акт МХ-1: 

DocumentToSend1 = SendTask.AddDocument("StorageInventoryAcceptanceCertificate", "default", "utd820_05_01_02_hyphen");

Получаем ошибку: COM1C.HTTP_ERROR[0x00000193]code 403:
Document type StorageInventoryAcceptanceCertificate-default-utd820_05_01_02_hyphen is not allowed to send.

А схемы для 970 формата нет, ошибка: Ошибка при вызове метода контекста (AddDocument): Произошла исключительная ситуация (PackageSendTask2.AddDocument): COM1C[0x0000028E] Неверный тип документа.

Аналогичная ситуация с ReturnInventoryAcceptanceCertificate (Акт МХ-3).

2) На части клиентов установлена версия компоненты 5.36.4.756. Была слабая надежда, что на ней можно будет сформировать utd970_05_02_01.

Но получаем ошибку: Ошибка при вызове метода контекста (AddDocument): Произошла исключительная ситуация (PackageSendTask2.AddDocument): В схеме не найден тип элемента.

Только переход на новую версию компоненты или как то можно схему 970 добавить для нее (для старых версий компоненты)?

**Comment by GilimkhanovDenis** [comment]
Боюсь, это зависит не от компоненты

`Document type StorageInventoryAcceptanceCertificate-default-utd820_05_01_02_hyphen is not allowed to send.` - в ящике, из которого пытаетесь отправить документ, тип документа подключен но только на получение от какого-то из контрагентов

`(PackageSendTask2.AddDocument): COM1C[0x0000028E] Неверный тип документа` - в ящике не подключен указанный тип документа

С ними нужно обратиться к менеджеру, чтобы типы документов включили для нужных вам ящиков

`В схеме не найден тип элемента` - это на 5.36.4 версии или на свежей? Если на свежей, то для какого типа документов такое поведение? для `(StorageInventoryAcceptanceCertificate, default, utd820_05_01_02_hyphen)` ?

**Comment by dimok22prog1** [comment]
1. А utd970_05_02_01 будет реализована для StorageInventoryAcceptanceCertificate?
2. На 5.36.4.756 хотели создавать DocumentToSend1 = SendTask.AddDocument("UniversalTransferDocument", "InvoiceAndBasic", "utd970_05_02_01"). Только смена версии компоненты или как-то можно схему 970 добавить для нее? Через техподдержку(?)

**Comment by GilimkhanovDenis** [comment]
1. Не знаю. от компоненты это не зависит - лучше обратиться к менеджеру
2. Функции `InvoiceAndBasic` нет. Вероятно, вам нужна `СЧФДОП`

**Comment by dimok22prog1** [comment]
1. По  Акт МХ-1/ Акт МХ-3 понятно, спасибо;
2. На версии компоненты **5.36.4.756** DocumentToSend1 = SendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd970_05_02_01") для SendTask.DelaySend = Истина получаем ошибку:

Ошибка при вызове метода контекста (AddDocument): Произошла исключительная ситуация (PackageSendTask2.AddDocument): В схеме не найден тип элемента.

**Comment by GilimkhanovDenis** [comment]
Это был баг компоненты. Что-то похожее фиксили в [5.38.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.38.0). Видимо, в 970 формате есть похожая организация тэгов в XSD, что у указанных в ошибке типов. 
Т.е. для решения этой ошибки придётся обновить компоненту
