### ISSUE TITLE
Ошибка Invalid data UserContractData:/UniversalTransferDocument/Consignees/Consignee/OrganizationDetails: @Inn is required

### ISSUE THREAD

**Issue by ElenaBurnasheva** [diadoc/diadocsdk-1c-docs#1105]
Здравствуйте.  При отправке через АПИ возникла ошибка Invalid data UserContractData:¶/UniversalTransferDocument/Consignees/Consignee/OrganizationDetails: @Inn is required.

Покупатель - контрагент из России, но грузополучатель - из Казахстана. 
Что нужно заполнить, чтобы УПД ушла покупателю?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Какие [TFV](https://developer.kontur.ru/Docs/Diadoc/COM/Glossary/Glossary.html#term-TFV) у отправляемого документа?

**Comment by ElenaBurnasheva** [comment]
DocumentToSend = SendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01")

**Comment by GilimkhanovDenis** [comment]
В https://github.com/diadoc/diadocsdk-1c-docs/issues/1085 была похожая проблема. можно сменить версию на `utd820_05_01_02_hyphen`  и в ней есть поля предназначенные для указания прочерков в части полей
