### ISSUE TITLE
ОШИБКА?! Вылетает 1С при обращении к полю Name объекта CertificateInfo на сертификатах, у которых Name = "" (пустая строка)

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#1106]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: x64 5.53.0.996.

Попробовали обновиться на последнюю на текущий момент версию 5.53.3.1008.

**И столкнулись с неожиданной проблемой вылета 1С при подключении к ЭДО!**

Стали разбираться и выяснили следующее:
1. Само подключение компоненты происходит без проблем.
2. Далее мы получаем информацию по установленным в системе сертификатам. Это тоже работает нормально.
3. Но при переборе данных сертификатов (объектов CertificateInfo) у нас происходит падение 1С при обработке одного из них.

Дальнейшее тестирование выявило следующее:
1. Это некий служебный сертификат(ы), устанавливаемый нашими админами на все компьютеры. Для каких-то своих целей, не связанных с ЭДО.
2. Такой же сертификат или типа такого есть и на сервере ЭДО. 
3. На версиях компоненты до 5.53.0.996 включительно всё работает без ошибок.
4. Начиная с версии 5.53.1.1004 и далее (т.е. на 5.53.1.1004, 5.53.2.1007 и 5.53.3.1008) проявляется одна и та же ошибка.

**Детали ошибки:**

### №1
Подключаем версию **5.53.0.996** и смотрим данные сертификата в отладчике:

![изображение](https://github.com/user-attachments/assets/0494b5f3-6a1d-4b2d-8111-da7daa6bc03d)

Всё прекрасно работает без ошибок.
И мы видим, что у этого сертификата просто пустая строка в имени (в поле Name).

### №2
Подключаем любую версию из **5.53.1.1004**, **5.53.2.1007** и **5.53.3.1008** и смотрим данные в отладчике:

![изображение](https://github.com/user-attachments/assets/0388c272-afb8-4e0e-acbf-f8e993da7056)

Похоже, что по какой-то загадочной причине где-то в коде компоненты происходит падение в исключение при попытке формирования значения в поле Name. Такое ощущение, что нет какой-то проверки на то, что там может быть пустая строка.

**Далее при обращении кода 1С к такому полю происходит исключение и вылет сеанса 1С.**

### Итого

Очень хотелось бы увидеть исправление данной проблемы!

Скоро новый год. По идее у вас должна появится какая-то поддержка новых ставок НДС 5% и 7%. Мы беспокоимся, что вдруг для учета новых ставок придется еще и компоненты на новые версии с поддержкой этих ставок обновлять.

И очень хотелось бы, чтобы, если действительно будет новая версия компоненты для поддержки ставок 5% и 7%, то мы могли бы на нее обновиться не нарываясь на эту странную ошибку.

Ну и вообще хотелось бы, чтобы такой странной ошибки не было бы.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Ошибку в сертификатах посмотрю

@JohnSergeev  Можете приложить открытый ключ этого RSA сертификата (.cer)?

Про новые ставки подробнее отвечу позже - здесь полностью зависим от появления изменений в сервисе. Контент и тип документа появятся в компоненте автоматически

**Comment by JohnSergeev** [comment]
Добрый день.


По сертификату – попробую узнать. Это наших админов надо дернуть, как они скажут.

Я сейчас еще проверяю, пока не понятно, но такое ощущение, что еще на каких-то полях тоже падает.

Если что-то найду, в ветку на гитхабе напишу добавку.

С уважением,
Сергеев Евгений.

**Comment by JohnSergeev** [comment]
Добрый день.

Проблема оказалась даже более "интересная", чем казалось на первый взгляд.

Я написал вам сюда о проблеме и решил быстренько сделать обход таких "плохих" сертификатов по косвенным признакам. Т.е. проверять их по какому-то читаемому без ошибок полю и, если это "плохой" сертификат, то не обрабатывать его вообще. Просто пропускать в цикле и всё. И не обращаться к его полю Name.

Ну, типа "_пока их пропустим, а там, глядишь, и починят ошибку_".

**Но нарвался на бОльшую проблему, с которой возился и так, и эдак... и ничего не смог сделать!**

Суть:
Сертификаты перебираются в функции в которую COM-объект  списка сертификатов передается в качестве параметра <Переменная со списком сертификатов>.
Т.е. мы получаем список через GetPersonalCertificates() и передаем его в функцию на обработку.

**Важно!**
**Между клиентом и сервером не бегаем! Всё выполняется в одном контексте. В нашем конкретном примере - на клиенте.**

В новой версии мы пропускаем плохие сертификаты, цикл перебора завершается, никаких ошибок....

### И при возврате из функции в вызывающий её код - 1С вылетает!

Появляется мысль - _"ну давай переменные начнем принудительно очищать, может там что-то в компоненте при этой ошибке происходит и, если мы явно все очистим, то может не будет вылетать"_.

Вставляем по итогу цикла очистку переменной. 
Делаем явно перед выходом из функции <Переменная со списком сертификатов> = Неопределено;

Запускаем. цикл перебора завершается, никаких ошибок....

### И при выполнении кода <Переменная со списком сертификатов> = Неопределено; - 1С вылетает!

Тогда появляется мысль - _"это она из-за передачи по ссылке чего-то чудит"_ - давай переменную в функцию через Знач передавать!
Т.е. заголовок функции сменился с:
- ФункцияОбработкиСертификатов(СписокСертификатов)
на
- ФункцияОбработкиСертификатов(Знач СписокСертификатов)

Запускаем. цикл перебора завершается, никаких ошибок....

Выполняется присвоение <Переменная со списком сертификатов> = Неопределено; - всё прекрасно, без ошибок!

### И при возврате из функции в вызывающий её код - 1С опять и всё равно вылетает!

## Итого

**Как бы мы ни бились, мы эту ошибку даже обойти никак не можем!**

Т.к. даже, если "отловить" такие проблемные сертификаты и не обрабатывать их.... то все равно 1С падает!

Похоже, в компоненте при обработке "плохих" сертификатов, при фиксации ранее показанной ошибки с исключением, что-то происходит и в дальнейшем она так или иначе приводит к падению 1С. Обойти это не получается.

**Поэтому просьба решить проблему и сделать всё, как было в версии 5.53.0.996, которая работала без проблем, еще сильнее!**

Свои сертификаты админы с серверов удалять не будут никаким образом.
И получается, что без решения проблемы (а оно явно возможно - см. версию **5.53.0.996**!) мы вообще никак не сможем обновить версию используемой компоненты.

Спасибо.

**Дополнительно:**
По .cer-файлу - постараюсь завтра у админов получить разрешение на передачу.

Хотя очень кажется, что это просто "убили" какую-то проверку на пустую строку. В **5.53.0.996** всё же работало.

**Comment by GilimkhanovDenis** [comment]
Если правильно понял, то есть код вроде такого

```
Функция Подходит(dd_Cert)
    Результат = Ложь;
    ...
    Возврат Результат;
КонецФункции


Функция ОтфильтроватьСертификаты(dd_Certs)
    ПодходящиеСертификаты = Новый Массив;

    Для Каждого dd_Cert Из dd_Certs Цикл
        Если Подходит(dd_Cert) Тогда
            ПодходящиеСертификаты.Добавить(dd_Cert);
        КонецЕсли;
    КонецЦикла;

    Возврат ПодходящиеСертификаты;
КонецФункции


Процедура ПоказатьСписокСертификатов(dd_COM)
    Сертификаты = ОтфильтроватьСертификаты(dd_COM.GetPersonalCertificates());
    ...
КонецПроцедуры
```

И падение происходит в момент `Возврат ПодходящиеСертификаты;` (хотя в * приведённом примере, скорее при ыходе из ПоказатьСписокСертификатов должно происходить, но не суть)

**Comment by GilimkhanovDenis** [comment]
В целом, если проходили [диагностику](https://help.kontur.ru/diadoc) с рабочего места, то в результатах должны быть открытые ключи сертификатов, установленных на рабочем месте. Могу по номеру диагностики найти интересующий нас сертификат

**Comment by GilimkhanovDenis** [comment]
@kobets504, @shultzMAN87 вы лайкнули тикет - у вас такая же ошибка или вопрос про новые ставки?

**Comment by JohnSergeev** [comment]
Добрый день.
Разрешение на выгрузку .cer- файла запросил.

### А вы не можете посмотреть, что поменяли по отношению к версии **5.53.0.996**?
### На ней-то всё работало прекрасно и без ошибок.

По вашему псевдо-примеру:

Функция Подходит(dd_Cert)
    Результат = Ложь;
    ...
    Возврат Результат;
КонецФункции


Функция ОтфильтроватьСертификаты(dd_Certs)
    ПодходящиеСертификаты = Новый Массив;

    Для Каждого dd_Cert Из dd_Certs Цикл
        Если Подходит(dd_Cert) Тогда
            ПодходящиеСертификаты.Добавить(dd_Cert);
        КонецЕсли;
    КонецЦикла;

**dd_Certs = Неопределено;**

    Возврат ПодходящиеСертификаты;
КонецФункции


Процедура ПоказатьСписокСертификатов(dd_COM)
    Сертификаты = ОтфильтроватьСертификаты(dd_COM.GetPersonalCertificates());

**продолжение = 8;**
    ...
КонецПроцедуры

Да. Примерно так.
Если есть добавленная мною строка: **dd_Certs = Неопределено;**, то падает на ее выполнении.
Если ее нет, то падает в ПоказатьСписокСертификатов() на возврате из ОтфильтроватьСертификаты(). Т.е. следующая строка **продолжение = 8;** уже не выполняется. 

Если функцию ОтфильтроватьСертификаты(dd_Certs) сделать как Функция ОтфильтроватьСертификаты(Знач dd_Certs), то, Если есть добавленная мною строка: **dd_Certs = Неопределено;**, то уже НЕ падает на ее выполнении. Но падает в ПоказатьСписокСертификатов() на возврате из ОтфильтроватьСертификаты(). Т.е. следующая строка **продолжение = 8;** уже не выполняется.

**Comment by JohnSergeev** [comment]
Денис, сертификат передать разрешили.
Напомните, пожалуйста, как вам его персонально переслать.
Здесь не очень хочется его в открытую выкладывать.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev 
[Здесь](https://github.com/diadoc/diadocsdk-1c-docs/issues/770#issuecomment-1055035074) через техподдержку отправляли

**Comment by JohnSergeev** [comment]
Эээ... просто на Поддержка Контур.Диадок <diadoc@skbkontur.ru> отправить?

А что-то написать надо, чтобы вам это письмо передали?

**Comment by GilimkhanovDenis** [comment]
Да, туда
В ответ вам номер обращения дадут. Я смогу по нему найти данные

**Comment by GilimkhanovDenis** [comment]
Можете ещё домен указать, с которого будет письмо, чтоб быстрее смогли найти

**Comment by JohnSergeev** [comment]
отправил

**Comment by JohnSergeev** [comment]
ничего пока в ответ не прислали (((

**Comment by GilimkhanovDenis** [comment]
Сертификат получил

**Comment by JohnSergeev** [comment]
Хорошо.
Надеюсь, поможет.

Хотя, по идее, дело же не в нем. 

Версия 5.53.0.996 же без ошибок с этими сертификатами работала.
По идее стоит посмотреть, что поменялось с переходом на 5.53.1.1004.

Впрочем,  вам виднее.

**Comment by GilimkhanovDenis** [comment]
Там случился переезд с нашей внутренней имплементации криптографии на общую библиотеку криптографии Контура

Ошибка возникает именно с этим сертификатом. Поправим

**Comment by JohnSergeev** [comment]
Ясно. Спасибо. 

Будем ждать.

Посмотрим по итогу всё ли заработает - у нас админы на все компы вообще подобные сертификаты напихали. 
По идее они все однотипно выпускались и проблема с ними одна и та же (я предполагаю, что дело в пустом значении Субъекта сертификата). Надеюсь, что исправление и по остальный сертификатам нормально будет без ошибок работать.

**Comment by kobets504** [comment]
> @kobets504, @shultzMAN87 вы лайкнули тикет - у вас такая же ошибка или вопрос про новые ставки?

Мы с автором тикета коллеги, вот и лайкнули)

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev 
Проверьте. пожалуйста на версии [5.53.4](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_53_4.html)

[Ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)

**Comment by GilimkhanovDenis** [comment]
Что касается новых ставок.

Думаю, официальный анонс ещё будет, но примерные даты такие:
- для документов с версиями `utd820_05_01_02_hyphen` и `ucd736_05_01_02` новых версий в Диадок не появится, и новые ставки будут введены в уже существующие XSD схемы. Начало января
- для УПД 970 будет добавлена новая версия с новыми ставками - вторая половина января

В компоненте, благодаря [DynamicContent](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html)'у изменения произойдут автоматически. Лучше переподключить компоненту

**Comment by JohnSergeev** [comment]
Добрый день.

А что значит "начало января"?! 
А что делать, если нам уже 1 января кто-то такие документы слать начнет?!

**И можно ли получить какую-то предварительную информацию в каком виде будут новые ставки в документах приходить? В 820 формате - в виде строковых значений "5" и "7" в соответствующих полях? Или как?**

Как-то до 29.12.2024 (последний рабочий день в этом году) можно это узнать и проверить, что все будет работать?

Хотелось бы заранее все подготовить и на новогодних праздниках отдыхать, а не бежать с выпученными глазами в 8 часов утра 1 января на работу - срочно дорабатывать код, чтобы верно обрабатывались входящие документы!

Спасибо.

**Comment by JohnSergeev** [comment]
Добрый день.

### Хотелось бы задать важный уточняющий вопрос!

Вы писали:

- для документов с версиями utd820_05_01_02_hyphen и ucd736_05_01_02 новых версий в Диадок не появится, и новые ставки будут введены в уже существующие XSD схемы. Начало января
- для УПД 970 будет добавлена новая версия с новыми ставками - вторая половина января

В компоненте, благодаря [DynamicContent](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html)'у изменения произойдут автоматически. Лучше переподключить компоненту

И мы сперва вроде всё поняли, но потом поняли, что поняли не очень )))

Правильно ли мы поняли, что:
1. для документов с версиями utd820_05_01_02_hyphen и ucd736_05_01_02 работа с новыми ставками появится "сама собой", **без необходимости обновления компонент**? И, например, на версии компоненты 5.53.0.996 новые ставки нормально появятся и с ними можно будет работать как на прием, так и на отправку документов?
2. для УПД 970 поддержка новых ставок появится только при обновлении компоненты на новую версию? И без такого обновления работать не будет?
3. А что это за действие _"переподключить компоненту"_? И зачем его выполнять, если версия компоненты не поменяласть и это тот же самый DLL-файл?

Спасибо.

**Comment by JohnSergeev** [comment]
Добрый день. 

Проверили исправление ошибки данного топика на версии 5.53.4.1010.

Подтверждаем, ошибка исправлена, проблемы нет.

Спасибо!

### Дополнительно:
Продолжив тестирование изменений после версии 5.53.0.996 мы обнаружили

### ОЧЕНЬ большую проблему, внесенную изменениями в версии 5.53.1.1004

С нашей точки зрения в том виде, как эти изменения были сделаны, они ломают для нас возможность работы с ЭДО на сервере в фоновом режиме.

Я сегодня детально всё распишу и в отдельный топик скину.

Надеюсь, это как-то получится решить.
