### ISSUE TITLE
Отправить доверенность (файл)

### ISSUE THREAD

**Issue by ElenaBurnasheva** [diadoc/diadocsdk-1c-docs#1108]
Здравствуйте. Имеется файл (pdf). Нужно отправить его с типом доверенность.
При вызове SendTask.AddDocumentFromFile("PowerOfAttorney","default","v1",ПутьДоФайла) возникает ошибка: Неверный тип документа.
Что делаю не так?

**Comment by GilimkhanovDenis** [comment]
Видимо, такой тип документа не подключен в ящике, в котором пытаетесь произвести действия

**Comment by GilimkhanovDenis** [comment]
Обратитесь к менеджеру, чтобы вам подключили такой тип

**Comment by ElenaBurnasheva** [comment]
Спасибо.
