### ISSUE TITLE
Ошибка при отправке документа УПД

### ISSUE THREAD

**Issue by DemyanSima** [diadoc/diadocsdk-1c-docs#111]
Добрый день. 

При отправке УПД возникает ошибка 
##100[Ошибка сервера Диадок]code:400, HTTP error: Info.Seller.Address.RussianAddress.Region is required

Текст запроса:
```
PackageSendTask = Organization.CreatePackageSendTask();                    
PackageSendTask.CounteragentId = CounteragentId;
DocumentToSend = PackageSendTask.AddDocument(Элемент.Ключ);
													
DocumentToSend.CustomDocumentId = Строка(Новый УникальныйИдентификатор);
	
Заполнить(DocumentToSend.content, Элемент.Значение, Элемент.Ключ);
Signer = DocumentToSend.Content.Signer;
Signer.Surname=	Сертификат.Фамилия;
Signer.FirstName=	Сертификат.Имя;
Signer.Patronymic=	Сертификат.Отчество;
Signer.JobTitle = 	Сертификат.Должность;		
Signer.Inn = ИНН;			
PackageSendTask.DelaySend = Ложь;		
PackageSendTask.OperationId = OperationIdПакета;

ОтправленныйПакет = PackageSendTask.Send();

```

Заполнение данных адреса

![untitled](https://user-images.githubusercontent.com/29306118/27073299-304d7200-5045-11e7-8d93-edab262f9cc2.png)

**Comment by volodkindv** [comment]
Добрый день.
Заполнено ли поле Seller.Type?
http://1c-docs.diadoc.ru/ru/latest/ExtendedOrganizationInfo.html?highlight=type

**Comment by DemyanSima** [comment]
Добрый, да заполнено значением “LegalEntity”
![image](https://user-images.githubusercontent.com/29306118/27639837-e99b0136-5c30-11e7-8d1e-d6c93cbb3cb7.png)

**Comment by denver069** [comment]
Проверьте пожалуйста **юридический адрес** в реквизитах организации на сайте [diadoc.kontur.ru](https://diadoc.kontur.ru).
Возможно в _DocumentToSend.content.Seller_ вы заполняете поле _BoxID_, в результате чего остальные поля заполняются из реквизитов организации указанных на сайте.

**Comment by DemyanSima** [comment]
Да,  именно так и есть. У контрагента в diadoc.kontur.ru адрес не заполнен. Убрал заполнения BoxID и документ отправился.

Спасибо
