### ISSUE TITLE
Отправка пакета документов на сервер Диадок в виде черновиков без ЭЦП

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#112]
COM-компонента.
Возможна ли отправка пакета документов на сервер Диадок в виде черновиков без ЭЦП, т.е. авторизация идет по логину паролю.

алгоритм такой:
1. Создаю COM-объект DiadocAPI
2. DiadocConnection = DiadocAPI.CreateConnectionByLogin("LOGIN", "PASSWORD")
3. Выбираю организацию (OrganizationDiadoc) через ".GetOrganizationList()"
4. Создаю пакет PackageSendTask = OrganizationDiadoc.CreatePackageSendTask()
5. Флаги PackageSendTask.IsDraft и PackageSendTask.DelaySend ставлю Истина
6. Добавляю документы SendTask = PackageSendTask.AddDocument
7. PackageSendTask.Send()

При вызове метода PackageSendTask.Send() выходит ошибка 
Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask.Send): ##100[Ошибка сервера Диадок]code:500, HTTP error: The server encountered an internal error or misconfiguration and was unable to complete your request

Что я сделал неправильно? Может такое действие невозможно с авторизацией логин/пароль?
С сертификатом получается, но мне нужна отправка для тестовых целей и хотелось бы это делать без сертификата.

**Comment by denver069** [comment]
При отправке черновика поле DelaySend устанавливать в истину не нужно.

**Comment by geron4** [comment]
Разобрался, на самом деле были неправильно заполнены данные о подписанте. (ExtendedSigner = Content.AddSigner()). Компонента выводила ошибку без явного указания на нее.
