### ISSUE TITLE
Торг 12->УПД

### ISSUE THREAD

**Issue by Migele** [diadoc/diadocsdk-1c-docs#115]
Здравствуйте
При работе с Торг12 с 01.07 начались ошибки. Документ "превращается" в УПД.
Причем эта ситуация не по всем документам.
Сначала получаю список документов, из списка по DocumentId ищу конкретный документ.
`ДокументПоИД	= ОрганизацияПоИД.GetDocumentById(ТекСтрока.DocumentId);`

в отладчике вижу
ДокументПоИД.type	"XmlTorg12"	Строка

Далее мне необходимо получить содержимое этого документа:
`СодержимоеДокумента	= ДокументПоИД.GetContent();`

в отладчике:
СодержимоеДокумента.type	"UniversalTransferDocument"	Строка

Ну и соответственно далее выходит ошибка
`КолСтрок	= СодержимоеДокумента.Items.Count();`
т.к. у UniversalTransferDocument нет коллекции Items.

Вопрос: так в дальнейшем и будет? Может мне тип документа проверять из GetContent()?
сейчас у меня есть такая проверка
```
Если ТекСтрока.Type	= "UniversalTransferDocument" Тогда
	КолСтрок	= СодержимоеДокумента.InvoiceTable.Items.Count();
Иначе
	КолСтрок	= СодержимоеДокумента.Items.Count();
КонецЕсли;
```
мне переделать в: 
```
Если СодержимоеДокумента.Type	= "UniversalTransferDocument" Тогда
	КолСтрок	= СодержимоеДокумента.InvoiceTable.Items.Count();
Иначе
	КолСтрок	= СодержимоеДокумента.Items.Count();
КонецЕсли;
```
или ситуация исправится?
Заранее спасибо

**Comment by azhipaigor** [comment]
Это "старые типы" в формате УПД - регламентированная ситуация. У документа есть поле AttachmentVersion - можно ориентироваться по нему, или по типу контента.
