### ISSUE TITLE
UtdInvoice [HTTP error: Could not find organization for Info.Seller]

### ISSUE THREAD

**Issue by dkamyshn** [diadoc/diadocsdk-1c-docs#116]
Добрый день.

При формировании счет-фактуры (UtdInvoice) клиенту, в которой наша организация является агентом, получаю ошибку:

(PackageSendTask.Send): ##100[Ошибка сервера Диадок]code:404, HTTP error: Could not find organization for Info.Seller: Inn: 7705952690, Kpp: 770501001

Если указать в качестве продавца (Seller) контрагента с данными:  Inn: 7705938310, Kpp:773401001 счет фактура формируется.

Два этих поставщика, не подключены к нам в качестве контрагентов с которыми мы осуществляем электронный документооборот.

Получается, некоторых контрагентов я могу указывать в качестве продавца, а некоторых нет?

**Comment by dkamyshn** [comment]
![100](https://user-images.githubusercontent.com/29984533/28057767-c37940e6-6629-11e7-8bd0-b1c161f609dc.jpg)

**Comment by denver069** [comment]
Всё немного сложнее.

Все дело в **идентификаторе ЭДО**, в терминах [внешней компоненты](http://diadocsdk-1c.readthedocs.io/) это поле [FnsParticipantId](http://diadocsdk-1c.readthedocs.io/ru/latest/Counteragent.html?highlight=FnsParticipantId).
Если в контенте документа на отправку поля [UtdInvoice.Seller.FnsParticipantId](http://diadocsdk-1c.readthedocs.io/ru/latest/ExtendedOrganizationInfo.html?highlight=FnsParticipantId) или [UtdInvoice.Buyer.FnsParticipantId](http://diadocsdk-1c.readthedocs.io/ru/latest/ExtendedOrganizationInfo.html?highlight=FnsParticipantId) не заполнены, то при генерации xml файла, Диадок пытается найти в своей базе ящик с аналогичным ИНН и КПП и заполнить из него идентификатор ЭДО. Если организация не зарегистрирована в Диадоке, возвращается указанная вами ошибка.

### Внимание важный момент!
Идентификаторы ЭДО должны соответствовать **отправителю** и **получателю** документа, а не продавцу и покупателю!

В вашем случае получается что идентификатор ЭДО **именно вашей компании** должен быть указан в поле [UtdInvoice.Seller.FnsParticipantId](http://diadocsdk-1c.readthedocs.io/ru/latest/UtdSellerContent.html?highlight=Seller), несмотря на то что счет-фактура выставляется от лица вашего поставщика.
