### ISSUE TITLE
УПД - AddExtendedSigner()

### ISSUE THREAD

**Issue by mishgan75** [diadoc/diadocsdk-1c-docs#118]
Доработанная конфигурация на базе Бухгалтерии Версия 1С:Предприятие 8.3 (8.3.10.2252)
при отправке счет фактуры при вызове функции AddExtendedSigner
![default](https://user-images.githubusercontent.com/30045276/28018029-52d72a4c-6584-11e7-98cd-1dfac788515b.jpg)

Вместо возврата объекта типа ExtendedSigner  - 
1с "падает":
![default](https://user-images.githubusercontent.com/30045276/28018071-8190070a-6584-11e7-887c-eccc515aadaa.jpg)

Расшифровка ошибки:
"Ошибка выполнения запроса
Ошибка при выполнении запроса POST к ресурсу /e1cib/logForm:
по причине:
На сервере 1С:Предприятия произошла неисправимая ошибка. Приложение будет закрыто"

Используется COM-компонента для встраивания в произвольные системы, для 64-х битных приложений - 5.18.1.219

А это собственно состав Документа из которого и "Скреативили" - SignTask

![image](https://user-images.githubusercontent.com/30045276/28020239-468e292c-658c-11e7-9717-923bfb7dea5c.png)

**Comment by mishgan75** [comment]
пока ждал выяснились некоторые подробности. При создании (получении с сервера Диадок) на сервере с помощью COM-компонента для встраивания в произвольные системы, для 64-х битных приложений - 5.18.1.219 DiadocComApi1.dll реквизит объект производного от объекта  Document ConfirmationDate принимает значение 30.12.1899 0:00:00, тогда как на клиенте, полученный с сервера Диадок созданных из обработки "Diadok OF5.17.01.epf" использующую внутреннюю dll "AddInDiadocAPI_x86_64" из макета, тот же реквизит принимает значение 01.01.0001 0:00:00. В качестве иллюстрации прилагаю файл где можно наглядно видны различия между объектами
 
[Сравнение Объектов Диадок.xlsx](https://github.com/diadoc/diadocsdk-1c-docs/files/1140977/default.xlsx)

**Comment by azhipaigor** [comment]
Здравствуйте! Воспроизвел. Пофиксил. Исправление войдет в ближайший релиз 5.18.5.
COM-компонента и AddIn действительно различаются, в силу особенностей 1Ски - для дат используются разные типы.

**Comment by mishgan75** [comment]
1. Когда примерно выйдет ближайший релиз?

**Comment by mishgan75** [comment]
1. Когда примерно выйдет ближайший релиз?
   2. Правильно ли я понял, что 1с аварийно завершал работу из-за
   некорректной даты и после установки нового релиза эта проблема исчезнет?


7 августа 2017 г., 12:46 пользователь azhipaigor <notifications@github.com>
написал:

**Comment by azhipaigor** [comment]
1. скорее всего на будущей неделе, лучше следить в [rss](http://diadocsdk-1c.readthedocs.io/ru/latest/index.rss)
2. с датой проблема не связана, проблема была в методе AddExtendedSigner. А даты вполне корректные, просто ConfirmationDate не задан и имеет значение по-умолчанию, соответственно 30.12.1899 0:00:00 для COM и 01.01.0001 0:00:00 для AddIn.
