### ISSUE TITLE
Роуминг отправка пакета из Сбиса в Диадок

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#12]
Настроен роуминг мы отправляем из Сбиса контрагенту в Диадок.
В Сбисе в одном пакете 4 документа: счет-фактуру, накладная, акт, счет. (в сбисе они подписываются в пакете разом, нельзя отдельно отклонить документ, только все).
Как этот пакет документов выглядит в Диадоке у контрагента?
Если в Диадоке документы подписывают отдельно, или они ввиде залоченного пакета?

**Comment by vasbur** [comment]
В случае роуминга документы связываются в пакет, но могут быть подписаны по-отдельности

**Comment by jakeqwert** [comment]
А как же это будет выглядеть в Сбисе, там же подписывается весь пакет  сразу?
