### ISSUE TITLE
1С SDK Видно не все неформализованные документы.

### ISSUE THREAD

**Issue by vlaved** [diadoc/diadocsdk-1c-docs#120]
Помогите с такой проблемой. Диадок внедрен в 1С 8.2 с помощью SDK через DiadocComApi.dll версии 5.18.1.219.

```
DocumentsTask = Organization.GetDocumentsTask();
DocumentsTask.FromDocumentDate = НачалоДня(НачПериода);
DocumentsTask.ToDocumentDate = КонецДня(КонПериода);
DocumentsTask.Category = "Any.Inbound";
DocumentsTask.CounteragentId = CounteragentId;
	  
DocumentList = DocumentsTask.GetDocuments();
```

Получаю список документов. Категорию выбираю Any.Inbound. То есть я так понимаю что это абсолютно все входящие документы. Так оно и есть, но на 99%. Есть пакеты с неформализованными документами которые я вижу в веб-интерфейсе, а в 1с этим методом их нет.

Внешне они ничем не отличаются от остальных. Просто пакет из двух .doc файлов.
![- -1](https://user-images.githubusercontent.com/30136182/28150142-4f5ea654-67c5-11e7-8e18-4c633bdab7ed.png)

https://diadoc.kontur.ru/d1529954-6f65-416d-b4a0-fee07869b457/Document/Show?letterId=463a4995-a418-43dc-9766-7d740e9cdede&documentId=f5b5f581-f201-4897-a723-496a7baae0e7

https://diadoc.kontur.ru/d1529954-6f65-416d-b4a0-fee07869b457/Document/Show?letterId=463a4995-a418-43dc-9766-7d740e9cdede&documentId=a5d12a28-3162-45d3-9598-eb7f9d567dca

Почему такое может быть? Откуда начать копать? Чем они могут отличаться от других неформализованных документов/пакетов? Период и контрагент выбраны верные.

**Comment by denver069** [comment]
Возможно даты этих документов (поле DocumentDate) не входят в указанный вами диапазон.
Вместо:
```
DocumentsTask.FromDocumentDate = НачалоДня(НачПериода);
DocumentsTask.ToDocumentDate = КонецДня(КонПериода);
```
Попробуйте использовать:
```
DocumentsTask.FromSendDate = НачалоДня(НачПериода); 
DocumentsTask.ToSendDate = КонецДня(КонПериода);
```

**Comment by vlaved** [comment]
Спасибо, помогло. Но по причине того, что в документах Document.Timestamp равен 07.07.2017 16:47:22, а Document.DocumentDate равен 30.11.1999  0:00:00   Видимо вопрос к отправителю.

**Comment by einfoman** [comment]
При фильтрации документов по DocumentDate находятся документы, у которых указана дата (именно как реквизит документа, а не, например, дата создания или отправки в диадоке). Это значит, что те документов, у которых нет такой даты (а документы выше не имеют даты), в результатах не будет. Дата из скриншота (30.11.1999) больше напоминает какую-нибудь дату по умолчанию.
