### ISSUE TITLE
Заполнить в УПД поле 12 через COM-компонента для встраивания в произвольные системы

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#122]
Добрый день.
Использую "COM-компонента для встраивания в произвольные системы- версия 5.18.2.232", отправляю УПД 
Как через эту компоненту заполнить поле 12 формы представления документа
См картинку
![img-2017-08-01-17-24-16](https://user-images.githubusercontent.com/20082460/28830574-d1e663b8-76df-11e7-9a11-a89660e3f8f2.png)

**Comment by denver069** [comment]
Нужно заполнить коллекцию [StructedAdditionalInfos](http://diadocsdk-1c.readthedocs.io/ru/latest/AdditionalInfoId.html) объекта [UtdSellerContent.AdditionalInfoId](http://diadocsdk-1c.readthedocs.io/ru/latest/UtdSellerContent.html?highlight=additionalinfoid)

**Comment by jakeqwert** [comment]
Спасибо большое, все получилось.
