### ISSUE TITLE
Прошу привести пример кода авторизации  по логину/паролю из 1с .

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#123]

**Comment by MikeFilimonov** [comment]
Речь об API(через компоненту(COM) и web-based API значения нет)

**Comment by sergro** [comment]
Получаем объект
DiadocInvoiceAPI(ДиадокАпи) -Описано при подключение по сертификату. А потом используем метод
CreateConnectionByLogin(<Login>, <Password>). 
ДиадокСоединение=ДиадокАпи.CreateConnectionByLogin(<Login>, <Password>)

**Comment by MikeFilimonov** [comment]
&НаКлиенте
Процедура ПодключитьсяКДиадок(Команда)
	//СерверПодключитьсяКДиадок(Объект.Логин, Объект.Пароль);
	
	КлючРазработчика = "actual key value";//тут указываю ключ
	
	
	ЗагрузитьВнешнююКомпоненту(Объект.ПутьКБиблиотеке);
//Объект.ПутьКБиблиотеке = "C:\Program Files (x86)\1cv8\8.3.10.2252\bin\AddInDiadocAPI.dll"
	ДиадокАПИ_ = Новый("AddIn.AddInDiadocAPI");
	ДиадокАПИ = ДиадокАПИ_.CreateObject();
	
	ОбъектКлассаСоединение =  ДиадокАПИ.CreateConnectionByLogin(Объект.Логин, Объект.Пароль);
	//
	//ДиадокАпи.ApiClientId = КлючРазработчика;
	//ДиадокАпи.ServerUrl = "https://diadoc-api.kontur.ru:443";
	
	
КонецПроцедуры

_получаю 

> ошибку:_{ВнешняяОбработка.тестимДиадок.Форма.Форма.Форма(56)}: Ошибка при вызове метода контекста (ЗагрузитьВнешнююКомпоненту)
	ЗагрузитьВнешнююКомпоненту(Объект.ПутьКБиблиотеке);
по причине:
Ошибка при загрузке внешней компоненты


Читаю ман: 

Для работы с системой Диадок необходимо: - загрузить внешнюю компоненту, - создать соединение с
сервером Диадок - создать контекст работы с организацией:
Как загрузить внешнюю компоненту
• Загрузка компоненты и инициализация объекта интерфейса Диадок на клиенте 1С.
//Загрузка внешней компоненты
ИмяФайла = "C:\Temp\AddInDiadocAPI.dll";
ЗагрузитьВнешнююКомпоненту(ИмяФайла);
//Создание объекта DiadocInvoiceAPI
ДиадокАПИ_ = Новый("AddIn.DiadocInvoiceAPI");
ДиадокАПИ = ДиадокАпи_.CreateObject();
//Задаем параметры подлючения к серверу
ДиадокАпи.ApiClientId = КлючРазработчика;
ДиадокАпи.ServerUrl = "https://diadoc-api.kontur.ru:443";
• Загрузка внешней компоненты на сервере 1С
В случае, когда режим запуска 1С не позволяет запуск внешних компонент, использующих техно-
логию COM, (например, на стороне сервера 1С 8.2) необходимо использовать сборку компоненты,
которая реализована в виде классического COM-объекта. В этом случае перед использованием
компоненты нужно зарегистрировать файл DiadocComApi.dll с помощью команды regsvr32.
В случае запуска компоненты на 64-х битном сервере 1С, необходимо использовать 64-битную
сборку данной компоненты. (64-битным должно быть именно приложение “сервер 1С”)
После этого загрузка и инициализация компоненты производится следующим образом:
//создаем корневой элемент COM-объекта
ДиадокАпи = Новый ComОбъект("Diadoc.DiadocClient");
//Задаем параметры подлючения к серверу
ДиадокАпи.ApiClientId = КлючРазработчика;
ДиадокАпи.ServerUrl = "https://diadoc-api.kontur.ru:443";


Делаю вывод, что мне нужно работать через сборку компоненты,
которая реализована в виде классического COM-объекта.
Но в этом случае получаю ошибку :
DiadocApiInvoiceApi.CreateConnectionByCertificate): ##100[Ошибка сервера Диадок]code:401, HTTP error: Certificate with thumbprint AE74C584D75DA01F3D1D5D4368483E05DE9BEC59 is not authorized."


Тут уже встает вопрос установки СКЗИ, которого планировал не касаться и обойтись авторизацией по логину/ паролю.

Вопрос: Что я делаю не так? 
 Прошу привести пример рабочего кода авторизации по логину/паролю из 1с.

**Comment by denver069** [comment]
Создаете COM объект установленной ранее [внешней компоненты для встраивания в произвольные системы](http://diadocsdk-1c.readthedocs.io/ru/latest/):
```
DiadocClient = Новый COMОбъект("Diadoc.DiadocClient"); 
DiadocClient.ApiClientId = КлючРазработчика;
DiadocClient.ServerUrl   = "https://diadoc-api.kontur.ru:443";
```
Если в сети есть прокси-сервер, заполняете настройки прокси в полях [DiadocClient.ProxyMode](http://diadocsdk-1c.readthedocs.io/ru/latest/Root-method.html?highlight=ProxyMode) и [DiadocClient.ProxySettings](http://diadocsdk-1c.readthedocs.io/ru/latest/Root-method.html?highlight=ProxySettings).

Выполняете[ авторизацию по логину и паролю](http://diadocsdk-1c.readthedocs.io/ru/latest/CreateConnectionByLogin.html), получая в результате объект подключения [DiadocConnection](http://diadocsdk-1c.readthedocs.io/ru/latest/Connection.html):

`DiadocConnection = DiadocClient.CreateConnectionByLogin(Логин, Пароль);`

Получаете доступные пользователю объекты [Organization](http://diadocsdk-1c.readthedocs.io/ru/latest/Organization.html), через которые выполняются операции с ящиками Диадока:
```
OrganizationList = DiadocConnection.GetOrganizationList();

Для Индекс = 0 По OrganizationList.Count - 1 Цикл
	
	Organization = OrganizationList.GetItem(Индекс);
	
КонецЦикла;
```

**Comment by MikeFilimonov** [comment]
denver069, спасибо!

**Comment by batistadude** [comment]
Компоненту надо регистрировать через regsvr32? На сервере или на клиенте?
