### ISSUE TITLE
Заполнение ExtendedOrganizationInfo

### ISSUE THREAD

**Issue by sergro** [diadoc/diadocsdk-1c-docs#124]
Добрый день. просьба помочь разобраться с объектом ExtendedOrganizationInfo. На странице http://diadocsdk-1c.readthedocs.io/ru/latest/ExtendedOrganizationInfo.html написано, что В свойствах объекта нужно указать либо идентификатор ящика организации, либо всю остальную информацию, обязательную для заполнения. В описании BoxId (строка, чтение/запись) - идентификатор ящика организации в Диадок. Если указан идентификатор ящика организации и тип организации, заполнять все остальные поля не нужно. Указано что кроме самого BoxID необходимо указать Type. Получается в 2 местах на 1 странице противоречивая информация либо можно указать только boxid либо boxid+Type. Где правда?

**Comment by geron4** [comment]
Да какая разница, мы пользуемся этим механизмом, работает ОК

**Comment by sergro** [comment]
При чем здесь пользуемся или нет. Я тоже заполняю оба свойства и пользуюсь. Хочется полного понимания того, что задумали разработчики. Из описания этого объекта мне это до конца не понятно.
