### ISSUE TITLE
Отбор по нескольким типам документов, это возможно?

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#125]
![image](https://user-images.githubusercontent.com/3480769/29111598-9afcb16c-7cf3-11e7-8cdc-688d113762f9.png)
Прошу уточнить, возможно ли  получение входящих  документов нескольких типов.
Если возможна, прошу привести код.

**Comment by denver069** [comment]
Комбинация различных типов документов в одном [DocumentsTask ](http://diadocsdk-1c.readthedocs.io/ru/latest/DocumentsTask.html)не предусмотрена.
Доступные фильтры можно посмотреть в документации к [DocumentsTask.Category](http://diadocsdk-1c.readthedocs.io/ru/latest/DocumentsTask.html?highlight=Category), все остальные комбинации выполняются через несколько запросов. Запросы можно выполнять параллельно через асинхронный вызов [DocumentsTask.GetDocumentsAsync()](http://diadocsdk-1c.readthedocs.io/ru/latest/GetDocumentsAsync.html).
