### ISSUE TITLE
метод GetContent() для Invoice

### ISSUE THREAD

**Issue by NNNataly** [diadoc/diadocsdk-1c-docs#126]
Почему-то в InvoiceContent не заполнены некоторые свойства, например Seller.INN (выдает значение "") , хотя при этом адрес и банк заполнены (Seller.BankName). В веб-версии все поля заполнены. C чем может быть связано? 
Рассматривается процесс получения входящих документов и открытия их в обработке Диадок

**Comment by denver069** [comment]
Покажите ссылку на документ пожалуйста.

**Comment by NNNataly** [comment]
https://diadoc.kontur.ru/f8544e7a-66b8-4955-bcdc-02f81017d0fc/Document/Show?letterId=d8345271-4da7-4970-99b9-b3746163c01f&documentId=10c9ce23-1499-4923-8835-d0607443ef82

**Comment by denver069** [comment]
На первый взгляд xml документ заполнен правильно, при попытке прочитать данные ошибка не воспроизводится Document.GetContent().Seller.Inn заполнен.

Попробуйте переустановить внешнюю компоненту с помощью команд
RegSvr32 <ПутьКФайлуВнешнейКомпоненты> /u
RegSvr32 <ПутьКФайлуВнешнейКомпоненты> /s /n /i:user

Если ошибка не исправится и вы используете стандартный модуль Диадок для 1С, обратитесь в  [техподдержку](https://www.diadoc.ru/support). Если вы пишете собственную интеграцию, попробуйте обновить внешнюю компоненту до текущей версии.

**Comment by NNNataly** [comment]
Спасибо, помогло обновление AddInDiadocAPI.dll
