### ISSUE TITLE
Заполнение GovermentContactInfo для счет фактур

### ISSUE THREAD

**Issue by IgorB123** [diadoc/diadocsdk-1c-docs#127]
Добрый день.
Работаем через COM-компоненту - версия 5.18.2.232
Пытаемся создать и отправить счет фактуру в соответствии с http://1c-docs.diadoc.ru/ru/latest/How-sign-outcoming.html#id3  
Процедура ОтправитьЭлектронныйCчетФактуру(Organization, CounteragentId)

  SendTask = Organization.CreateSendTask("InvoiceContent");
  SendTask.CounterаgentId   = CounteragentId;

  InvoiceContent = SendTask.Content;
  InvoiceContent.Date        = '20130101';
  InvoiceContent.Number      = "1";
  InvoiceContent.Currency    = "643";

  InvoiceContent.Seller.Name = "ООО Продавец";
  InvoiceContent.Seller.Inn  = "2012500001";
  InvoiceContent.Seller.Kpp  = "111111111";
  InvoiceContent.Seller.Address.RegionCode = "66";

  InvoiceContent.Buyer.Name  = "ООО Покупатель";
  InvoiceContent.Buyer.Inn   = "2012600006";
  InvoiceContent.Buyer.Kpp   = "222222222 ID   ";
  InvoiceContent.Buyer.Address.RegionCode = "66";

  Item = InvoiceContent.AddItem();
  Item.Product               = "Товар";
  Item.UnitCode              = "166";
  Item.Quantity              = 10;
  Item.Price                 = 100;
  Item.TotalWithVatExcluded  = 1000;
  Item.TaxRate               = "18";
  Item.Vat                   = 180;
  Item.Total                 = 1180;

  SendTask.Send();

КонецПроцедуры

Но у InvoiceContent нет свойства GovermentContactInfo, как я могу заполнить Идентификатор госконтракта?

**Comment by denver069** [comment]
Дело в том что [InvoiceContent](http://1c-docs.diadoc.ru/ru/latest/InvoiceContent.html) не содержит поле для заполнения идентификатора государственного контракта. Сам по себе [InvoiceContent](http://1c-docs.diadoc.ru/ru/latest/InvoiceContent.html) с 01.07.2017 является устаревшим, поэтому отправлять новые счета-фактуры нужно одним из двух вариантов:

1. УПД с функцией СЧФ - `Organization.CreateSendTask("UniversalTransferDocument")`
2. Счет-фактура в формате 155 приказа - `Organization.CreateSendTask("UtdInvoice")`

О разнице между этими вариантами можно почитать [здесь](https://github.com/diadoc/diadocsdk-1c-docs/issues/101)

**Comment by IgorB123** [comment]
Спасибо огромное! Проблема решена. Используем UtdInvoice.
