### ISSUE TITLE
Ошибка HTTP error: The server encountered an internal error or misconfiguration and was unable to complete your request

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#128]
Ув.Разработчики!

При отправке УКД через COM-компоненту версии 5.18.4.238 возникает ошибка:
##100[Ошибка сервера Диадок]code:500, HTTP error: The server encountered an internal error or misconfiguration and was unable to complete your request

я понимаю, что скорее всего я что-то неверно заполнил, но как это понять по такому тексту ошибки? особенно учитывая скромность Вашей документации по компоненте.

Прошу выдавать более информативные сообщения об ошибках, чтобы понятно было, в каком направлении копать. Прошу учесть при разработке новых версий!!!

**Comment by denver069** [comment]
К сожалению предоставленной вами информации недостаточно для того, чтобы понять характер ошибки.
Если вам удалось понять в чем ошибка, то опишите её пожалуйста, чтобы мы подумали как сделать её описание более информативным.
Если вам не удалось понять в чем ошибка, то покажите все данные объекта SendTask или PackageSendTask в том числе и объекты коллекции DocumentsToSend и мы вместе попробуем разобраться.

**Comment by geron4** [comment]
В этом и проблема, что информации недостаточно для определения проблемы, при такой не информативной ошибке. Опытным путем я нашел, что информация о подписанте была указана не верно. Я же предлагаю доработать в вашей компоненте информацию об ошибках.

**Comment by denver069** [comment]
Дело в том что данная ошибка транслирована из API Диадока и интерпретировать её на уровне внешней компоненты не представляется возможным.

**Comment by geron4** [comment]
Я об этом и говорю, что API Диадока должен выдавать более конкретную ошибку, насколько я понял, у вас занимается им другое подразделение? Может им нужно озвучить проблему?

**Comment by i82** [comment]
Если возможно локализовать, напишите при вызове какого метода получилась ошибка.
Ещё нужна информация о том, в какой организации и в какой период времени (МСК) произошла ошибка.
