### ISSUE TITLE
свойство CounterAgentId объекта SendTask

### ISSUE THREAD

**Issue by sergro** [diadoc/diadocsdk-1c-docs#129]
Добрый день. У Объекта SendTask есть свойство CounterAgentId  (строка, чтение/запись) - идентификатор контрагента. Не совсем понятно кто подразумевается в данном случае: контрагент которому отправляется эл. документ или сама организация являющаяся контрагентом Диадок.

**Comment by azhipaigor** [comment]
Добрый день! Это BoxId того кому отправляется документ.

**Comment by sergro** [comment]
Добрый день, спасибо.  Опытным путем уже попробовал в это свойство вставить Boxid контрагента которому отправляется документ. Все получилось.
