### ISSUE TITLE
Заполнение макета формализованного УПД и УКД

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#13]
Предусмотреть возможность в заполнении макета формализованного УПД и УКД возможность управлять заполнением выделенного текста, см. приложенный рисунок.
![img-2016-08-05-16-30-29](https://cloud.githubusercontent.com/assets/20082460/17438211/686bd548-5b2a-11e6-931a-e2d4c7f7bf9b.png)

**Comment by vasbur** [comment]
В каких тегах XML-формата вы хотите передавать этот текст?

**Comment by jakeqwert** [comment]
Нам бы в компоненте 1С иметь возможность передавать такую информацию

**Comment by vasbur** [comment]
Любая информация, которую вы передаете через компоненту, должна быть в итоге помещена в xml-документ в какой-либо тэг. Поэтому хочется получить ответ на предыдущий вопрос

**Comment by jakeqwert** [comment]
Вопрос с текстом снимается.
Но в формате есть элемент НеттоВс описан см. скрин.
![img-2016-08-30-09-52-09](https://cloud.githubusercontent.com/assets/20082460/18080563/cbce79ce-6e9e-11e6-9b1d-7d97375e8605.png)
Не забудьте его реализовать в представлении, т.к. данные реквизит не обязательный, но когда УПД используется в качестве и счет-фактуры и накладной, то важно помимо суммы и суммындс и общее количество.
