### ISSUE TITLE
Комментарий к аннулированию

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#130]
Добрый день!
Подскажите, пожалуйста, как программно получить комментарий к запросу на аннулирование.

**Comment by denver069** [comment]
Нужно найти в коллекции [Document.Resolutions](http://diadocsdk-1c.readthedocs.io/ru/latest/Document.html?highlight=Resolutions) элемент [Resolution](http://diadocsdk-1c.readthedocs.io/ru/latest/Resolution.html), в котором [Resolution.ResolutionType](http://diadocsdk-1c.readthedocs.io/ru/latest/Resolution.html?highlight=ResolutionType) = "RevocationRequest". В поле [Comment](http://diadocsdk-1c.readthedocs.io/ru/latest/Resolution.html?highlight=Comment) этого элемента и будет записан комментарий к запросу на аннулирование.
