### ISSUE TITLE
После обновления на релиз 5.18.5.245 UtdInvoice

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#131]
Добрый день.
Раньше отправляли авансовые счет-фактуры как Organization.CreateSendTask("UtdInvoice"), после установке релиза COM-компонента для встраивания в произвольные системы- версия 5.18.5.245,
стала выходить ошибка на UtdInvoice, что нет такого типа, подставил вместо  UtdInvoice UniversalTransferDocument документ отправился, но печатная форма на сайте как у УПД, а необходима форма счет-фактуры с xml формата приказа 155.
Как теперь отправлять авансовую счет-фактуру в формате приказа 155.

**Comment by jakeqwert** [comment]
Ошибка при вызове метода контекста (CreateSendTask): Произошла исключительная ситуация (Box.CreateSendTask): Unknown attachment type

**Comment by denver069** [comment]
Да подтверждаю, ошибка действительно имеет место быть.

Не работает [Organization.CreateSendTask](http://diadocsdk-1c.readthedocs.io/ru/latest/CreateSendTask.html) с типами 
- UtdInvoice
- UtdTorg12
- UtdAcceptanceCertificate
- UcdInvoiceCorrection

В самое ближайшее время выпустим исправление.

Для получения информации о выходе новой версии внешней компоненты, вы можете подписаться на ленту новостей [RSS](http://diadocsdk-1c.readthedocs.io/ru/latest/index.rss)

**Comment by jakeqwert** [comment]
Кстати отправляю через 32 битную DiadocComApi.dll

**Comment by jakeqwert** [comment]
Добрый день. СРОЧНО
Огромная просьба исправить, т.к. сегодня отгрузка документов контрагентам, не можем отправить.
Не работает Organization.CreateSendTask с типами
UtdInvoice
UcdInvoiceCorrection

**Comment by denver069** [comment]
На данный момент есть проблема публикации компоненты и документации к ней.
В связи с этим, скачайте пожалуйста новую версию внешней компоненты [отсюда](https://github.com/diadoc/diadocsdk-1c-docs/tree/master/docs/source/data/v50).

**Comment by jakeqwert** [comment]
Попробовал данную версию 32 бита не помогает. 5.18.6.248.
Сделал в командной строке от имени администратора: RegSvr32 <ПутьКФайлуВнешнейКомпоненты> /u
В командной строке с обычными правами пользователя: RegSvr32 <ПутьКФайлуВнешнейКомпоненты> /s /n /i:user
В таком варианте компонента будет установлена в профиль текущего пользователя
Так же попробовал в командной строке от имени администратора: RegSvr32 <ПутьКФайлуВнешнейКомпоненты>

Не работает Organization.CreateSendTask с типом UtdInvoice
Ошибка при вызове метода контекста (CreateSendTask): Произошла исключительная ситуация (Box.CreateSendTask): Unknown attachment type

**Comment by jakeqwert** [comment]
SOS

**Comment by azhipaigor** [comment]
Пофиксили. Версия [5.18.7.252](https://github.com/diadoc/diadocsdk-1c-docs/tree/master/docs/source/data/v50)

**Comment by jakeqwert** [comment]
Спасибо, проверили работает.

**Comment by mishgan75** [comment]
3 дня как пофиксили а на сайте diadoc нет никаких изменений, "Для получения информации о выходе новой версии внешней компоненты, вы можете подписаться на ленту новостей RSS" в RSS тоже никаких изменений. КАК это понимать. Можно пользоваться или нет?

**Comment by jakeqwert** [comment]
По ссылке проверили работает, мы пользуемся, ошибок пока не обнаружили
