### ISSUE TITLE
Как сохранить подпись в файл?

### ISSUE THREAD

**Issue by Scopatutto** [diadoc/diadocsdk-1c-docs#132]
Добрый день!
Каким образом можно объект типа Signature сохранить в файл? 
Если скачать документооборот целиком через веб интерфейс, то в архиве есть файлы с подписями, как их получить программно?

**Comment by denver069** [comment]
В текущей версии внешней компоненты, скачать **отдельно** файлы с подписями невозможно.

Скачать все файлы относящиеся к документу (в т.ч. электронные подписи) программно, можно методами объекта [Document](http://1c-docs.diadoc.ru/ru/latest/Document.html):

- [SaveAllContent](http://1c-docs.diadoc.ru/ru/latest/SaveAllContent.html)
- [SaveAllContentAsync](http://1c-docs.diadoc.ru/ru/latest/SaveAllContentAsync.html)
- [SaveAllContentZip](http://1c-docs.diadoc.ru/ru/latest/SaveAllContentZip.html)
- [SaveAllContentZipAsync](http://1c-docs.diadoc.ru/ru/latest/SaveAllContentZipAsync.html)
