### ISSUE TITLE
Счет-фактура по старому формате

### ISSUE THREAD

**Issue by DurkinVA** [diadoc/diadocsdk-1c-docs#133]
Добрый день! Подскажите пожалуйста, что нужно сделать для выгрузки фактур из "1с" в "Диадок", обновить лишь компоненту,что сделали версия 5,18.5.245,  или еще требуется какие-нибудь доработки кода?  После обновления dll в Веб-интерфейсе наблюдаем "Счет-фактура отправлен в устаревшем формате". 
 Спасибо.

**Comment by denver069** [comment]
Для работы с документами в формате УПД во внешней компоненте добавлены новые объекты.

Соответственно при отправке в метод [PackageSendTask.AddDocument](http://diadocsdk-1c.readthedocs.io/ru/latest/AddDocument.html) добавлены новые типы

- UniversalTransferDocument
- UniversalTransferDocumentRevision
- UniversalCorrectionDocument
- UniversalCorrectionDocumentRevision
- UtdTorg12
- UtdAcceptanceCertificate
- UtdInvoice
- UcdInvoiceCorrection

В чем отличие УПД с функцией СЧФ от счета-фактуры в формате УПД можно прочитать [здесь](https://github.com/diadoc/diadocsdk-1c-docs/issues/101)
