### ISSUE TITLE
Ошибка при попытке сохранения ПФ документа в pdf

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#134]
Пытаюсь сохранить ПФ документа  через API:

```
DocumentList = DocumentsTask.GetDocuments();
a = 0;
ПутьКФайлам = проверяемыйПутьККаталогу;
//ТипДокументаВКонтексте1с = СопоставитьТипДокументаС1С(ТипДокументов);

Пока a < DocumentList.Count Цикл
Document = DocumentList.GetItem(a);
полныйПутьКФайлу = ПутьКФайлам + Document.FileName;
Document.SaveContent(полныйПутьКФайлу);


путьДляПФ = "C:\Mike\Работа\201708\20170811\Диадок\Docs\";
Document.GetPrintForm(путьДляПФ);
..................................................
КонецЦикла;

```
Получаю ошибку: 

> {ВнешняяОбработка.тестимДиадок.Форма.Форма.Форма(250)}: Ошибка при вызове метода контекста (GetPrintForm)
> Document.GetPrintForm(путьДляПФ);
> по причине:
> Произошла исключительная ситуация (DocumentBase.GetPrintForm): Ошибка записи в файл

Прошу пояснить как сохранить в pdf  печатную форму документа.

**Comment by denver069** [comment]
В параметр <FileName> метода [Document.GetPrintForm](diadocsdk-1c.readthedocs.io/ru/latest/GetPrintForm.html) запишите полный путь к файлу (с именем).

**Comment by denver069** [comment]
Покажите пожалуйста ссылку на документ.

**Comment by MikeFilimonov** [comment]
Разобрался. Не было прав на запись в папку со стороны 1с.
