### ISSUE TITLE
Ошибка при подписании документов

### ISSUE THREAD

**Issue by egor-bogdanov** [diadoc/diadocsdk-1c-docs#136]
Добрый день.
При подписании документа возникает ошибка "##100[Ошибка сервера Диадок]code:409, HTTP error: Команда AddBuyerTitle не поддерживается документом dc4acce1-9348-46c8-b962-9a2e4bc52bdc:e89b508a-d22f-41f0-afef-6b0fee45ab84".

Версия компоненты 5.18.5.245;
ReplySendTask создается методом CreateReplySendTask объекта типа, производного от Document.

[ReplySendTask.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/1239266/ReplySendTask.txt)
[Document.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/1239267/Document.txt)
[Signers.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/1239268/Signers.txt)

**Comment by denver069** [comment]
УПД с функцией СЧФ не поддерживает ответного титула покупателя.
Для такого документа достаточно выполнить регламентный документооборот счетов-фактур с помощью [Organization.GetReceiptGenerationProcess](http://1c-docs.diadoc.ru/ru/latest/GetReceiptGenerationProcess.html) или [Document.SendReceiptsAsync](http://1c-docs.diadoc.ru/ru/latest/SendReceiptsAsync-(Utd).html).
