### ISSUE TITLE
Ошибка при отправке документа

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#137]
Работаем через COM-компонента для встраивания в произвольные системы- версия 5.18.5.245
Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (SendTask.Send): ##100[Ошибка сервера Диадок]code:403, HTTP error: Organization is liquidated. BoxId: d7105f79-9364-4010-a246-588838698270
![img-2017-08-22-09-41-52](https://user-images.githubusercontent.com/20082460/29552301-580fcfde-871f-11e7-839c-9ac38eeaff6f.png)

**Comment by denver069** [comment]
Организация ликвидирована.

**Comment by jakeqwert** [comment]
А на картинке "Работает в Диадоке". Исправьте статус

**Comment by denver069** [comment]
Я передал информацию в тех. поддержку ядра Диадока.
