### ISSUE TITLE
Контрагент, получить по нему дату последнего возникновения статуса "Контрагент"

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#138]
Причина банальная, собрать статистику прироста базы Контрагентов по месяцам.
Возможно ли это через COM-компоненту?

**Comment by denver069** [comment]
Используйте поле [Counteragent.LastEventTimestampTicks](http://diadocsdk-1c.readthedocs.io/ru/latest/Counteragent.html?highlight=LastEventTimestampTicks).

**Comment by geron4** [comment]
LastEventTimestampTicks (дата и время, чтение) - метка времени последнего события из истории взаимодействия с данным контрагентом.

Вопрос: Какие события изменяют этот реквизит? Направленный документ или еще что-нить, кроме смены статуса, меняет этот реквизит?
