### ISSUE TITLE
Ошибка при отправке счет-фактура корректировочной документа за 04.2016

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#139]
Отправляем документ
SendTask = Organization.CreateSendTask("InvoiceCorrectionContent");
Заполняем SendTask.Content, как обычно, но при отправке возникает ошибка
Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (SendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Could not parse InvoiceCorrectionInfo.Items[0].OriginalValues.Excise: без акциза
В прошлых версиях компоненты документы уходили без проблем.
Через отладку видно, что при инициализации поля Excise строкой "без акциза", компонента валиться в исключение "Ошибка при установке значения атрибута контекста (Excise): Произошла исключительная ситуация (InvoiceItemFields.PutExcise): invalid stod argument", но при этом значение поля компоненты устанавливается (если строку кода добавить в исключение).
Но отправка все равно не проходит: 
"Произошла исключительная ситуация (SendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Could not parse InvoiceCorrectionInfo.Items[0].OriginalValues.Excise: без акциза"

Необходимо исправить, т.к. не можем отправить корректировочные документы в формате приказа 189 налоговой.

**Comment by jakeqwert** [comment]
COM-компонента для встраивания в произвольные системы- версия 5.18.5.245

**Comment by denver069** [comment]
Попробуйте не инициализировать поле Excise вообще.

**Comment by jakeqwert** [comment]
Получилось, стал использовать UcdInvoiceCorrection вместо InvoiceCorrectionContent, вообще InvoiceCorrectionContent теперь получается не нужен.  И функцию для заполнения контента туже самую для UniversalCorrectionDocument, все ушло, xml верная и печатная форма тоже.

**Comment by jakeqwert** [comment]
Всем спасибо.
