### ISSUE TITLE
«Модуль работы с электронными документами через Диадок»

### ISSUE THREAD

**Issue by alexsemushin** [diadoc/diadocsdk-1c-docs#14]
Компания ООО «Линия 7» (ИНН 5903002350/ КПП 590150001).Как в обработке «Модуль работы с электронными документами через Диадок» для 1с, организовать выгрузку накладны и счет фактур, чтобы обработка при выгрузке количества по товару учитывала количество частичных возвратов ,которые формируется перед тем как наши операторы печатают ТТН и СФ на бумажных носителях.
Какие процедуры необходимо дорабатывать в модуле этой обработки.

**Comment by denver069** [comment]
Если вы используете модуль на обычных формах то посмотрите ветку https://github.com/diadoc/diadocsdk-1c-docs/issues/10, только у вас вместо отраслевого документа нужно добавлять возврат.
