### ISSUE TITLE
Не корректный идентификатор получателя для роуминговых ящиков в xml документах.

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#140]
COM-компонента для встраивания в произвольные системы- версия 5.18.5.245.
![img-2017-09-13-08-31-25](https://user-images.githubusercontent.com/20082460/30365092-5cfe67c4-986f-11e7-8423-226bbf847e85.png)
Заполняем объект
![img-2017-09-13-08-19-24](https://user-images.githubusercontent.com/20082460/30365150-7add9e36-986f-11e7-9690-0044b197ee00.png)
Смотрим в отладке:

**Comment by jakeqwert** [comment]
![img-2017-09-13-08-17-26](https://user-images.githubusercontent.com/20082460/30365651-151188c2-9871-11e7-8e2e-56dbcc4aad55.png)
![img-2017-08-02-15-29-21](https://user-images.githubusercontent.com/20082460/30365941-17788a7e-9872-11e7-981e-6763b149bfec.png)
Видно из картинки, что  ИД получателя 2AL-ADFAE945-5F8C-4F73-B87F-FE1CC15AB8B6-00000 , в найденном контрагенте верно.
Но в xml документах УПД и авансовых счет-фактурах xml (соответсвенно и исправительные и корректировочные), отправляем как UniversalTransferDocument, UniversalCorrectionDocument,  UtdInvoice (авансовый счет-фактура), InvoiceCorrectionContent.
```
SendTask = Organization.CreateSendTask("UniversalTransferDocument");
ЗаполнитьКонтентДляUniversalTransferDocument(SendTask.Content, СтрТЗКомплект, СтруктураПараметровДок, НомерЗаказа, ПараметрыОтправкиНаСогласование);
SendTask.CounterAgentId = CounteragentId;
Если ЗначениеЗаполнено(DepartmentID) тогда
   SendTask.ToDepartmentId = DepartmentID;// (строка, чтение/запись) - идентификатор подразделения получателя
КонецЕсли;
SendTask.CustomDocumentId =строка(новый УникальныйИдентификатор());
ПутьФ = ""+КаталогВременныхФайлов()+СтруктураПараметровДок.ИдДок+".xml";
SendTask.SaveContent(ПутьФ); //!!! посмотрим что сформировалось для проверки, тут уже не верные Ид получателя
Document =  SendTask.Send();
```

**Comment by jakeqwert** [comment]
В объекте SendTask видно через отладку, все реквизиты заполнены верно, но если получить xml SendTask.SaveContent(ПутьФ), либо посмотреть отправленный документ методом SendTask.Send() на сайте Диадок:

**Comment by jakeqwert** [comment]
ИД получателя не то что в контрагенте указано:
![img-2017-09-13-11-11-17](https://user-images.githubusercontent.com/20082460/30366635-6680b932-9874-11e7-90ec-f11c8a451027.png)

**Comment by jakeqwert** [comment]
И тоже самое в авансовом счет-фактуре:
![img-2017-09-13-11-15-11](https://user-images.githubusercontent.com/20082460/30366759-d9056372-9874-11e7-9901-2aa956b185ee.png)

**Comment by denver069** [comment]
Попробуйте указать значение [FnsParticipantId](http://diadocsdk-1c.readthedocs.io/ru/latest/Counteragent.html?highlight=FnsParticipantId%20) в контенте документа на отправку SendTask.Content.Buyer.FnsParticipantId.

**Comment by jakeqwert** [comment]
Спасибо, помогло, но только остается вопрос, это лучше по всем контрагентам заполнять или только для роуминговых,  просто по идеи контрагента ID SendTask.CounterAgentId задан, а FnsParticipantId не из контрагента берет, отдельно нужно еще инициализировать поле.

**Comment by denver069** [comment]
В текущих версиях стандартных модулей Диадока для 1С, мы добавили прямо в базу 1С идентификаторы участников ЭДО для всех сопоставленных контрагентов и организаций.
 
При отправке мы всегда заполняем:
- `Content.Seller.FnsParticipantId` идентификатором ЭДО отправителя.
- `Content.Buyer.FnsParticipantId` идентификатором ЭДО получателя.

Таким образом, мы не используем функцию автоматического заполнения поля `FnsParticipantId` вообще.

Ошибка автозаполнения `FnsParticipantId` может быть не только при отправке документов в роуминговый ящик. Подобная ошибка будет также и при перевыставлении документов агентом, когда либо продавец не соответствует отправителю, либо покупатель не соответствует получателю.
