### ISSUE TITLE
Ошибка при подписании ТОРГ-12

### ISSUE THREAD

**Issue by egor-bogdanov** [diadoc/diadocsdk-1c-docs#141]
Добрый день. 
При создании ReplySendTask из документа типа "XmlTorg12", создается объект, с типом "UniversalTransferDocumentBuyerTitle", хотя по документации должен быть объект с типом "Torg12BuyerContent", соответственно после заполнения ReplySendTask и отправки его, получаю ошибку "Произошла исключительная ситуация (ReplySendTask.Send): ##100[Ошибка сервера Диадок]code:403, HTTP error: Не отправлено заявление в ФНС". Подскажите, в чем проблема?

[ReplySendTask.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/1322134/ReplySendTask.txt)
[Document.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/1322125/Document.txt)

**Comment by volodkindv** [comment]
Добрый день.
Обратите внимание на поле

AttachmentVersion	"UniversalTransferDocument"	Строка

в Document.

Это означает, что Вы получили документ "ТОРГ-12" в формате 155 приказа, т.е. в формате УПД.
Поэтому и ответ должен быть в формате УПД.

**Comment by egor-bogdanov** [comment]
А почему может возникать ошибка "Произошла исключительная ситуация (ReplySendTask.Send): ##100[Ошибка сервера Диадок]code:403, HTTP error: Не отправлено заявление в ФНС"?

**Comment by volodkindv** [comment]
Возможно, заявление действительно не отправлено.
Вызовите Document.Organization.CanSendInvoice(Document.Organization.Certificate.Thumbprint)

http://1c-docs.diadoc.ru/ru/latest/CanSendInvoice.html?highlight=cansendinvoice

Если он выдаст такую же ошибку, заполните заявление в веб-интерфейсе:

![image](https://user-images.githubusercontent.com/12305552/30740746-a9bfbd86-9fab-11e7-8fef-fa94c8b44aa4.png)

Раздел "Реквизиты организации", кнопка "Заполнить заявление" примерно в середине формы.
