### ISSUE TITLE
Ошибка при создании счёта-фактуры

### ISSUE THREAD

**Issue by sergeb72** [diadoc/diadocsdk-1c-docs#142]
Добрый день.
При создании счета-фактуры через COM-интерфейс для Diadoc API (DiadocComApi.dll версии 5.18.7.252) методом CreateSendTask('UtdInvoice') возвращается ошибка:
**'[Ошибка сервера Диадок]code:400, HTTP error: Info.InvoiceTable.Items[0].Subtotal is required'**
Хотя атрибут Subtotal устанавливается (код во вложении). Нужно ли что-либо изменить в коде или это баг?
[codeUTD_delphi.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/1337073/codeUTD_delphi.txt)

**Comment by denver069** [comment]
Повторить ошибку на DiadocComApi.dll **5.18.7.252** для 32 и 64 битной архитектуры не удалось.

Если вы ставили на компьютер компоненту под обе архитектуры, то попробуйте последовательно удалить обе и поставить только одну. 

Также не увидел в вашем коде заполнения итогов: 
```
UtdSellerContent.InvoiceTable.TotalNet := 1;
UtdSellerContent.InvoiceTable.TotalWithVatExcluded := 100;
UtdSellerContent.InvoiceTable.Vat := 18;
UtdSellerContent.InvoiceTable.Total := 118;
```
Без этого кода у вас будет ошибка: **[Ошибка сервера Диадок]code:400, HTTP error: Info.InvoiceTable.Total is required**

**Comment by sergeb72** [comment]
Нет, устанавливали компоненту только 32-битную. На соседнем компьютере для чистоты эксперимента установили 64-битную, ошибка аналогичная: **Info.InvoiceTable.Items[0].Subtotal is required**. Скорее всего, проверка на заполнение Info.InvoiceTable.Items[0].Subtotal выполняется раньше, чем на Info.InvoiceTable.Total, поэтому до приведённого Вами сообщения очередь не доходила.
Текущий вариант кода с учётом заполнения итогов во вложении. Ошибка прежняя. Причем, если закомментировать, например, строку "Item.Product := 'Товар 1';", то ошибка меняется на "Info.InvoiceTable.Items[0].Product is required". Следовательно, Product передаётся нормально, а Subtotal почему-то нет.
[codeUTD_delphi_mod1.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/1341144/codeUTD_delphi_mod1.txt)

**Comment by sergeb72** [comment]
Удалось победить ошибку, передавая все числовые атрибуты в виде строк:
`    Item := UtdSellerContent.InvoiceTable.AddItem;
    Item.Product := 'Товар 1';
    Item.UnitCode := '166';
    Item.Quantity := '1000';
    Item.Price := '1.00';
    Item.TaxRate := '18';
    Item.SubtotalWithVatExcluded := '1000';
    Item.Vat := '180';
    Item.Subtotal := '1180';
`

**Comment by denver069** [comment]
Все так, поле Item.Subtotal принимает тип `string` или `decimal`.
Я вам все таки рекомендую разобраться, почему в Item.Subtotal не записывается тип `decimal`.
