### ISSUE TITLE
УПД статус документа

### ISSUE THREAD

**Issue by MikhailNTS** [diadoc/diadocsdk-1c-docs#143]
Здравствуйте!
Бухгалтерия 2.0, обработка ДиаДок 5.18.33
Список документов на вкладке "Полученные через Диадок", у УПД-документов колонка "Состояние согласования" пустая, двойной клик по документу открывается карточка УПД-документа, здесь Согласование = Согласовано: Иванов И.И.
В момент открытия карточки документа изменяется статус в таблице списка документов (колонка  "Состояние согласования" = Согласовано), но если опять обновить список документов вкладки "Полученные через Диадок" колонка "Состояние согласования" вновь становится пустой.
Я так понимаю метод Box.getDocumentsTask() (стр.4426 модуля Модуль_РаботаССерверомДиадок) работает некорректно. Можно как-нибудь это поправить?

**Comment by denver069** [comment]
Обратитесь пожалуйста в службу [техподдержки](https://www.diadoc.ru/support).
