### ISSUE TITLE
Кодировка ответа метода ValidateContent()

### ISSUE THREAD

**Issue by Sergguha** [diadoc/diadocsdk-1c-docs#144]
Добрый день, версия компоненты x32 5.18.7.252.
Почему-то метод ValidateContent() объекта SendTask в некоторых случаях стал возвращать список ошибок в ответе в другой кодировке (CP1251):
![2017-10-05_11-16-46](https://user-images.githubusercontent.com/24603503/31217872-161c8670-a9c1-11e7-8295-c8100d4a9d4a.png)
Попробовал на другой версии компоненты (5.18.2.232) и на другой локальной машине, проблема аналогичная.
Причем, складывается впечатление, что возвращается некорректная кодировка при валидации данных адреса (или контрагента):
_В отправляемом документе есть ошибки:
Consignee.Address.Building: РґРѕРј РЅРµ РґРѕР»Р¶РµРЅ Р±С‹С‚СЊ РґР»РёРЅРЅРµРµ 20 СЃРёРјРІРѕР»РѕРІ
TransferInfo.Employee.EmployeePosition: должность должна быть заполнена
TransferInfo.Employee.FullName.Surname: фамилия должна быть указана
TransferInfo.Employee.FullName.FirstName: имя должно быть указано_

**Comment by denver069** [comment]
Да действительно есть такая проблема, но я настоятельно рекомендую вам отказаться от использования метода ValidateContent. Метод ValidateContent является устаревшим и не содержит всех необходимых правил проверки контента.

**Comment by Sergguha** [comment]
А есть какой-то метод, выполняющий аналогичную функцию, но при этом не устаревший? К сожалению, в описании компоненты об этом ничего не написано.

**Comment by denver069** [comment]
Нет, нового метода нет и его разработка не планируется.
В наших модулях проверка выполняется непосредственно в 1С.
Также контент в любом случае проходит валидацию по схеме ФНС при генерации xml файла в момент отправки через внешнюю компоненту.

**Comment by denver069** [comment]
Мы допишем в документации к ValidateContent что он устаревший, спасибо что обратили на это внимание.
