### ISSUE TITLE
Ошибка при использовании AdditionalInfoId

### ISSUE THREAD

**Issue by Scopatutto** [diadoc/diadocsdk-1c-docs#145]
Добрый день! Пытаюсь заполнить AdditionalInfoId через подключаемый модуль. При выгрузке документа получаю сообщение AdditionalInfoId.InfoFileId should be GUID. Никак не могу разобраться, как правильно заполнять? Может быть есть примеры использования?

**Comment by piskaly** [comment]
Как разрешилась проблема?

**Comment by Scopatutto** [comment]
Заполняю значение новым ГУИДом.

**Comment by piskaly** [comment]
Новый УникальныйИдентификатор?

**Comment by Scopatutto** [comment]
Да, так помогло.

**Comment by piskaly** [comment]
Спасибо!
