### ISSUE TITLE
Параллельная работа нескольких пользователей с Diadoc через DiadocConnection.Возможно ли это?

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#148]
Добрый день

При разработке собственного решения на основе API использую ключ разработчика
Для получения данных из ЛК "Диадок" нужен объект класса DiadocConnection
Возможно ли параллельное создание/существование нескольких DiadocConnection  на основании одного ключа разработчика ?

**Comment by denver069** [comment]
Да параллельное использование возможно.
