### ISSUE TITLE
Фильтр для GetDocumentsAsync

### ISSUE THREAD

**Issue by Scopatutto** [diadoc/diadocsdk-1c-docs#149]
Добрый день! Возникла задача получить список документов с использованием фильтра по дате изменения статуса. В документации нашёл только параметры FromSendDate/ToSendDate и FromDocumentDate/ToDocumentDate. В тоже время через веб-интерфейс ящика можно задать поиск, указав в качестве параметра интервал смены статуса документа. Подскажите, есть ли возможность получить документы с фильтром по дате смены статуса через API?

**Comment by Jannelli** [comment]
Здравствуйте! Присоединяюсь к вопросу.

**Comment by Scopatutto** [comment]
Разработчики здесь отвечают очень неохотно...
В другом месте посоветовали использовать механизм событий http://api-docs.diadoc.ru/ru/latest/http/GetNewEvents.html

**Comment by Jannelli** [comment]
Спасибо за подсказку! А Вы пробовали фильтр по параметрам периода? У меня ощущение что он как-то не верно работает. Документ в дате 29.09.17 (тогда же отправлялся) - задаю FromDocumentDate/ToDocumentDate за август - документа нет, за сентябрь - тоже нет, только если по октябрь появляется.. через  FromSendDate/ToSendDate тоже самое. Пробую на тестовом ящике

**Comment by Scopatutto** [comment]
Проверьте реквизиты документа, когда получите методом GetDocumentsAsync. Сейчас как раз использую эти параметры, вопросов к ним нет, всё отрабатывает честно.

**Comment by Jannelli** [comment]
Спасибо! действительно все работает, была путаница с периодами создания/отправки

**Comment by denver069** [comment]
Все верно, вам действительно в таком случае нужно использовать механизм ленты событий  http://api-docs.diadoc.ru/ru/latest/http/GetNewEvents.html.
