### ISSUE TITLE
DocumentsTask свойство top100 

### ISSUE THREAD

**Issue by Jannelli** [diadoc/diadocsdk-1c-docs#150]
Здравствуйте!
У объекта DocumentsTask свойство top100 - как описано здесь:
http://diadocsdk-1c.readthedocs.io/ru/latest/DocumentsTask.html?highlight=GetDocumentsTask
позволяет получить первые 100 документов. Получается, можно по заданному отбору получить или все, или только часть. А способа читать порциями по 100 нет? Или может быть еще не описано?

**Comment by denver069** [comment]
Внешняя компонента вычитывает документы с сервера Диадока порциями по 100 штук, далее собирает их в общую коллекцию и передает клиенту.
Функции по передаче клиенту документов порциями нет и её реализация пока не планировалась.
