### ISSUE TITLE
Имя файла в архиве SaveAllContentZip

### ISSUE THREAD

**Issue by Jannelli** [diadoc/diadocsdk-1c-docs#151]
Здравствуйте! Еще один вопрос/уточнение. При сохранении файлов документа через SaveAllContentZip возвращается архив, в котором имя основного файла документа и подписи короче, чем если сохранять в папке методом SaveAllContent. В общем-то содержимое точно такое же, как сохранять из веб-интерфейса "Документооборот целиком". А при сохранении из веб-интерфейса "Документ с подписью" - имя у файла и подписи длинное (полностью такое как указано в протоколе). У этого способа подсказка "подходит для представления в ИФНС". Значит ли это, что сохраненный целиком документооборот в архиве (скачанный из веб-интерфейса или методом SaveAllContentZip) - для ИФНС подходящим не является? И если требуется иметь сохраненный вариант обязательно пригодный если что для налоговой - лучше сохранять файлы с помощью SaveAllContent и у себя уже их запаковывать в архив?

**Comment by denver069** [comment]
Имена файлов в zip архиве обрезаются из-за ограничения в Windows длины имени файла в 256 символов, для того чтобы была возможность их извлечь.

В ФНС передается файл документа + файл подписи, протокол передачи в ФНС не сдается.
Сдавать в ФНС файлы с обрезанными именами можно, ошибок не возникает.
