### ISSUE TITLE
Получение имени файла счёта-фактуры

### ISSUE THREAD

**Issue by sergeb72** [diadoc/diadocsdk-1c-docs#152]
Подскажите, пожалуйста, существует ли штатный способ получения утверждённого ФНС имени XML-файла счёта-фактуры при работе с COM-компонентой для встраивания в произвольные системы? Для сохранения на локальный диск методом SendTask.SaveContent(...).

**Comment by denver069** [comment]
Имя файла возникает только после отправки документа в Диадок, доступно в поле Document.FileName.
Сохранить файл можно так:
Document = SendTask.Send();
Document.SaveSenderContent(КаталогДляФайлов + "\" + Document.FileName)
