### ISSUE TITLE
Внешняя компонента для 1С - версия 5.18.7.252

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#153]
Добрый день.
Скачал "Внешняя компонента для 1С - версия 5.18.7.252" и положил в "C:\Temp\AddInDiadocAPI.dll".

В примере использования на сайте указано:
ЗагрузитьВнешнююКомпоненту("C:\Temp\AddInDiadocAPI.dll");
ДиадокАПИ_ = Новый("AddIn.DiadocInvoiceAPI");

В толстом клиенте 1С:Предприятие 8.2 (8.2.18.82), 1С:Предприятие 8.3 (8.3.5.1486), 1С:Предприятие 8.3 (8.3.9.1850) возвращает AddIn.DiadocInvoiceAPI.

В тонком клиенте (на клиенте) 1С:Предприятие 8.2 (8.2.18.82), 1С:Предприятие 8.3 (8.3.5.1486), 1С:Предприятие 8.3 (8.3.9.1850) выдает ошибку:
Ошибка при вызове метода контекста (ЗагрузитьВнешнююКомпоненту) ЗагрузитьВнешнююКомпоненту("C:\Temp\AddInDiadocAPI.dll");
по причине:
Ошибка при загрузке внешней компоненты

Пробовал инициализировать объект через ПодключитьВнешнююКомпоненту().
В толстом клиенте после этого ДиадокАПИ_ = Новый("AddIn.DiadocAPI.DiadocInvoiceAPI") возвращает AddIn.DiadocInvoiceAPI.
В тонком клиенте 8.3 ПодключитьВнешнююКомпоненту() работате после НачатьУстановкуВнешнейКомпоненты() и ДиадокАПИ_ = Новый("AddIn.DiadocAPI.DiadocInvoiceAPI") возвращает AddIn.DiadocInvoiceAPI.
Но в 8.2 НачатьУстановкуВнешнейКомпоненты() нет.

Как загрузить и инициализировать объект интерфейса Диадок в ТОНКОМ клиенте 1С универсально для 8.2 и 8.3.

**Comment by denver069** [comment]
Универсального решения нет.

В 8.2 нет асинхронных вызовов и ограничения по режиму использования модальности, поэтому и нет асинхронного метода `НачатьУстановкуВнешнейКомпоненты`, но есть синхронный метод `УстановитьВнешнююКомпоненту`. Кстати в 8.3 он тоже есть, но в конфигурациях где режим использования модальности установлен в `НеИспользовать` вызов этого метода невозможен.

Попробуйте сделать несколько вариантов инициализации и использовать их в зависимости от версии 1С, а конструкции которые не проходят синтаксический контроль обернуть в метод `Выполнить`.
