### ISSUE TITLE
Invalid API client id

### ISSUE THREAD

**Issue by Jannelli** [diadoc/diadocsdk-1c-docs#155]
Здравствуйте!
Работаю с тестовой организацией через компоненту для 1С, подключение по логину. Второй раз за месяц получаю ошибку:
Произошла исключительная ситуация (DiadocApiInvoiceApi.CreateConnectionByLogin): ##100[Ошибка сервера Диадок]code:401, HTTP error: Invalid API client id
До этого она тоже возникала, но потом все заработало. Сейчас вот снова перестало. Ключ разработчика один и тот же (который выслали для реальной организации).
В первый раз писали в поддержку, ответ был "передадим экспертам" и запрашивали подробности, хотя к моменту ответа все уже заработало. Снова писать в поддержку?

**Comment by denver069** [comment]
Да, обратитесь пожалуйста в техподдержку.

**Comment by Jannelli** [comment]
Спасибо за ответы!
