### ISSUE TITLE
Вопрос по DocumentPackage

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#156]
Версия компоненты 5.18.5.245 (32-х разрядная). Контекст выполнения Толстый клиент, зарегистрирована на локальном компьютере.

Есть 3 документа с PackageId = "faaa6416-7b35-49d3-9549-7cff7a131e56".
Если от любого из этих Document взять GetDocumentPackage(), возвращается DocumentPackage ТОЛЬКО с ним самим (в коллекции Documents только один документ, а по описанию д.б. 3 документа). Как быть, мне нужен DocumentPackage с 3 документами для формирования CreateReplySendTask(AcceptDocument) и подписания ОБЛАЧНОЙ подписью, одним СМС-сообщением всего пакета.

**Comment by prog22** [comment]
Документы пакета:

https://diadoc.kontur.ru/7f648ced-4718-4958-884e-02dac0220d4a/Document/Show?letterId=1ef57b55-7d8d-4f8f-82d1-0e354b742dc0&documentId=95e6f5ce-dbb0-46ad-b866-989ed2c6a0e0

https://diadoc.kontur.ru/7f648ced-4718-4958-884e-02dac0220d4a/Document/Show?letterId=89070231-483a-476f-861d-1a0131fefeaf&documentId=467dab2e-6353-4af4-9d9f-e06f199df6f2

https://diadoc.kontur.ru/7f648ced-4718-4958-884e-02dac0220d4a/Document/Show?letterId=a9e6ace1-f0ab-4cb3-a7a1-c43abd217b19&documentId=a79e8542-9b2a-4681-8d3c-5d4806619c49

**Comment by prog22** [comment]
Используем "COM-компонента для встраивания в произвольные системы"

**Comment by denver069** [comment]
Метод [GetDocumentPackage](http://diadocsdk-1c.readthedocs.io/ru/latest/GetDocumentPackage.html) объекта [Document](http://diadocsdk-1c.readthedocs.io/ru/latest/Document.html) возвращает пакет документов из одного сообщения, идентификатор сообщения отражен в параметре `letterId` [URL](http://diadocsdk-1c.readthedocs.io/ru/latest/Document.html?highlight=PathURL) документа.

Метода для получения и подписания коллекции документов с одинаковым [PackageId](http://diadocsdk-1c.readthedocs.io/ru/latest/Document.html?highlight=PackageId) из разных сообщений во внешней компоненте нет.

Указанные вами документы отправлены разными сообщениями.
 
Идентификаторы связанных документов вы можете получить из коллекций [InitialDocumentIds](http://diadocsdk-1c.readthedocs.io/ru/latest/Document.html?highlight=InitialDocumentIds) и [SubordinateDocumentIds ](http://diadocsdk-1c.readthedocs.io/ru/latest/Document.html?highlight=SubordinateDocumentIds)
