### ISSUE TITLE
Отправка на подпись документов типа "SupplementaryAgreement"

### ISSUE THREAD

**Issue by VladGreBB** [diadoc/diadocsdk-1c-docs#158]
Можно ли через компонент версии 5.19.0.275. Отправить на подписание документ с типом "SupplementaryAgreement" (дополнительное соглашение). Метод "AddDocumentFromFile" объекта "PackageSendTask" для данного типа возвращает ошибку. В web сервисе отправка и получение документов данного типа реализовано.

**Comment by LyubovZykova** [comment]
Добрый день! На текущий момент возможности работы с этим типом документа в компоненте нет, задача добавлена в бэклог разработки.
