### ISSUE TITLE
Ошибка при отправлении УПД

### ISSUE THREAD

**Issue by Alex463** [diadoc/diadocsdk-1c-docs#159]
Добрый день! Версия компоненты 5.18.5.245
Помогите, пожалуйста, решить следующую проблему:
Создаю УПД методом Organization.CreateSendTask("UniversalTransferDocument"), заполняю его.

При отправлении SendTask.Send() выдает следующую ошибку:
"Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (SendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Info.Buyer.Address.RussianAddress.Region is required"

Скрин заполненного региона:
![1](https://user-images.githubusercontent.com/24681242/32269966-2229a3d6-bf05-11e7-89b9-9bcb9ee6f544.JPG)

**Comment by denver069** [comment]
На [текущей версии](http://1c-docs.diadoc.ru/ru/latest/Downloads.html) внешней компоненты (**5.19.0.275**) воспроизвести ошибку не удалось, попробуйте обновить версию компоненты до текущей.
