### ISSUE TITLE
Получить zip контейнер документа методом COM объекта SDK

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#16]
В Web-интерфейсе Диадок у документа есть кнопка "Скачать"->"Документоборот целиком".
Используем SDK для 1С. Каким методом COM объекта получить этот zip контейнер?
Очень необходимо, по регламенту нашего учета в организации, мы крупная организация, необходимо хранить zip контейнеры у себя. /Если такого метода нет, реализуйте, пожалуйста.
Или подскажи как выйти из ситуации.

**Comment by denver069** [comment]
Используйте метод [Document.SaveAllContent()](http://diadocsdk-1c.readthedocs.io/ru/latest/SaveAllContent.html). Данный метод позволит сохранить все файлы на диск, далее с помощью объекта 1С ЗаписьZipФайла вы можете подготовить zip контейнер и сохранить его в базе.

**Comment by jakeqwert** [comment]
Добрый день. Но сайт возвращает уже в одном zip файле, что очень удобно.
А так как документов много и часто возникают проблемы с получением представлений документов с отметкой (на текущий момент необходимы для судебных органов), то есть большой шанс не получить весь пакет документов целиком, если сервер вернет целиком zip будет надежнее. Хотелось бы иметь такой метод через COM, тем более у остальных оператов ЭДО которыми мы пользуемся у всех такие есть и это удобно. Реализуйте, пожалуйста.

**Comment by denver069** [comment]
Понял ваше опасение, постараемся добавить необходимый метод при разработке новой версий внешней компоненты. Но на текущий момент во внешней компоненте кроме предложенной модели альтернативы нет.

**Comment by jakeqwert** [comment]
Спасибо ждем.

**Comment by denver069** [comment]
Опубликована компонента версии [5.8.0.138](http://1c-docs.diadoc.ru/ru/latest/Downloads.html) с возможностью получения файлов документооборота в zip архиве, методы: [SaveAllContentZip](http://1c-docs.diadoc.ru/ru/latest/SaveAllContentZip.html?highlight=saveallcontentzip) и [SaveAllContentZipAsync](http://1c-docs.diadoc.ru/ru/latest/SaveAllContentZipAsync.html?highlight=saveallcontentzipasync)

**Comment by jakeqwert** [comment]
Спасибо. Применим себе.
