### ISSUE TITLE
Создать нового пользователя для подключения в ЛК

### ISSUE THREAD

**Issue by Alex463** [diadoc/diadocsdk-1c-docs#160]
Добрый день!
Консультанты прислали инструкцию как добавить сертификат нового сотрудника организации.
"Войдите в Диадок, откройте меню «Настройки и оплата» и перейдите в раздел «Сотрудники». Нажмите «Добавить сотрудника». Выберите способ работы «По сертификату КЭП». Загрузите с компьютера файл открытого ключа сертификата сотрудника, которого вы хотите добавить в организацию. Когда сертификат загрузится, укажите:
адрес электронной почты;
должность;
подразделение в структуре Диадока, к которому он будет относиться;
при необходимости наделите его правами на согласование документов, подписание документов, отправку документов на согласование/подписание и администрирование организации;
определите для него возможность пользоваться сообщениями. Как отправить сообщение →
Нажмите «Добавить».
Теперь сотрудник может входить в Диадок по сертификату."
Вопрос: можно ли сейчас реализовать аналогичное через компоненту (добавление нового сертификата сотрудника для подключения)? Если можно, то напишите, пожалуйста, какие объекты и методы можно для этого использовать.

**Comment by denver069** [comment]
Такого функционала во внешней компоненте для 1С нет и его реализация не планируется.

**Comment by German09** [comment]
А как нам возможно загрузить примерно 1000 пользователей, только руками?

**Comment by denver069** [comment]
Попробуйте обратится по этому вопросу в [техподдержку](https://www.diadoc.ru/support).
