### ISSUE TITLE
В печатной форме УПД не заполняется Строка [10]

### ISSUE THREAD

**Issue by Scopatutto** [diadoc/diadocsdk-1c-docs#161]
Добрый день!
Модуль для обычных форм 5.19.13.
В печатной форме УПД не заполняется Строка [10] «Товар (груз) передал/услуги, результаты работ, права сдал», если в УПД услуги. Это ошибка?

**Comment by denver069** [comment]
Скорее всего вы имеете ввиду **УПД** с функцией **СЧФ**.
Элемент  `Документ.СвПродПер.СвЛицПер` в xml документе не обязателен, тем более для **УПД** с функцией **СЧФ** и потому его отсутствие ошибкой не является.
