### ISSUE TITLE
Отправка запроса на согласование с типом "ApprovementSignatureRequest"

### ISSUE THREAD

**Issue by VladGreBB** [diadoc/diadocsdk-1c-docs#162]
Добрый день. Можно ли через компонент версии 5.19.0.275. Отправить на согласование документ с типом согласования "ApprovementSignatureRequest" - запрос на согласующую подпись под документом? При попытке установить значение"ApprovementSignatureRequest" у свойства "ResolutionRequestType" объекта "ResolutionRequestTask", возникает ошибка "Ошибка при установке значения атрибута контекста (ResolutionRequestType): Произошла исключительная ситуация (ResolutionRequestTask.PutResolutionRequestType): Неверное значение перечисления". В web версии существует возможность отправки таких запросов.

**Comment by denver069** [comment]
В текущей версии внешней компоненты функционал по работе с согласующей подписью не реализован.

**Comment by LyubovZykova** [comment]
Задача добавлена в бэклог разработки, для повышения приоритета задачи - пожалуйста, обратитесь в нашу техподдержку любым удобным способом, https://www.diadoc.ru/support
