### ISSUE TITLE
Облачная подпись

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#163]
Добрый день. 
Используем "COM-компонента для встраивания в произвольные системы" версии 5.18.5.245 (32-х разрядная).
Есть ящик организации: Тестовая организация №2943248 ИНН 9629432481, КПП 962901000. Туда добавлен сотрудник с облачной подписью. Подключаюсь к ящику AuthenticateType = Login. Пытаюсь получить облачные сертификаты CloudCerts = ДиадокСоединение.GetCloudCertificates(), в результате CloudCerts.Count = 0. Почему?

**Comment by prog22** [comment]
Забыл указать. В ящике организации заведено 2 сотрудника. Первый с почтовым адресом 1, второй с облачной подписью и почтовым адресом 2. Выше указанное подключение было через первого сотрудника (почтовый адрес 1).

**Comment by denver069** [comment]
Если я вас правильно понял, ошибка заключается в том что вы пытаетесь получить облачные сертификаты пользователя №2 но при этом авторизуетесь данными пользователя №1.
