### ISSUE TITLE
Чтение тестовых документов с помощью компоненты в 1с

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#164]
Добрый день.

Будут ли прочитаны  с помощью метода GetDocuments() тестовые документы, отправленные тестовой организацией -партнером  в НЕ тестовую организацию при подключении из базы не тестовой организации к ЛК Диадок через API по  COM - технологии?

Для пояснения привожу код:

Organization = DiadocConnection.GetOrganizationList();
DocumentTask = Organization.GetDocumentsTask();
DocumentList = DocumentTask.GetDocuments();

**Comment by denver069** [comment]
Если документы доступны в вэб версии Диадока то и метод [GetDocuments](http://1c-docs.diadoc.ru/ru/latest/Document.html) с соответствующими параметрами их вернет.
Код пояснения содержит ошибки и в таком виде работать не будет.

**Comment by MikeFilimonov** [comment]
Документы доступны в веб-версии, но скачать через API не смог.

**Comment by denver069** [comment]
Тогда покажите рабочий листинг кода и ссылку на документ.

**Comment by MikeFilimonov** [comment]
Ссылка на тестовый док  у организации, отправившей док: 

https://diadoc.kontur.ru/eeae69fd-dc25-4147-b443-fe63a2bbe512/Document/Show?letterId=597adda0-ccd0-4186-ad9e-e2ef7c25eeab&documentId=be695e1b-1772-4bc4-9761-1af23c912959

Ссылка на док у Организации, получившей док:
https://diadoc.kontur.ru/19bb544b-6a04-4874-b639-2637a1c10f0a/Document/Show?letterId=597adda0-ccd0-4186-ad9e-e2ef7c25eeab&documentId=be695e1b-1772-4bc4-9761-1af23c912959

Листинг кода прилагаю в файле: 
DocumentList  -  не содержит элементов
[не загружает тестовый.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/1470198/default.txt)

**Comment by denver069** [comment]
В фильтрации по периоду вы используете дату документа:
```
DocumentTask.FromDocumentDate = НачалоПериода;
DocumentTask.ToDocumentDate = КонецПериода;
```
У неформализованного документа её нет, поэтому для таких документов используйте дату отправки:
```
DocumentTask.FromSendDate = НачалоПериода;
DocumentTask.ToSendDate = КонецПериода;
```

**Comment by MikeFilimonov** [comment]
Спасибо Вам
