### ISSUE TITLE
Некорректное представление адреса

### ISSUE THREAD

**Issue by Scopatutto** [diadoc/diadocsdk-1c-docs#165]
Добрый день!
Модуль Диадок для ОФ 5.19.13, формирую УПД, при формировании представления адреса некорректно формируется часть с корпусом/строением, офисом/квартирой.
Если у организации в адресе есть "строение", то в представлении будет заменено на "корпус", "офис" будет заменен на "квартира".  Это ошибка? Ниже код из модуля:
ПредставлениеАдреса = ДобавитьРазделитель(Индекс)+ДобавитьРазделитель(НаименованиеРегиона(КодРегиона))+ДобавитьРазделитель(Район)+ДобавитьРазделитель(Город)+ДобавитьРазделитель(НаселПункт)+ДобавитьРазделитель(Улица)+ДобавитьРазделитель(Дом, "дом №")+ДобавитьРазделитель(Корпус, "корпус ")+ДобавитьРазделитель(Кварт,"кв ");

**Comment by denver069** [comment]
Нет ошибки не будет.
Дело в том что в [xsd схеме УПД](https://www.diadoc.ru/docs/forms/upd/structure/1) в атрибутах адреса нет строения и офиса, поэтому эта информация записывается в атрибуты `Корпус` и `Кварт`.

**Comment by Scopatutto** [comment]
Вопрос не в том, в какие атрибуты записывается, а в формировании печатной формы. Разве это верно всегда подставлять разделитель "кв ", даже если это "офис"?

**Comment by denver069** [comment]
Все верно, но контрагенту отправляется не печатная форма, а xml документ, в котором эта информация записана в атрибуты `Корпус` и `Кварт`. То что вы видите в модуле Диадока для 1С - лишь его визуализация.
Визуализацию xml документа в модуле Диадока для 1С мы выполняем по аналогии с вэб версией. Если в веб версии вам нужен собственный вариант визуализации УПД, обратитесь в [техподдержку](https://www.diadoc.ru/support) для того чтобы узнать как это сделать.

Я ответил на ваш вопрос?

**Comment by Scopatutto** [comment]
Нет, но, боюсь, я не смогу Вас переубедить.
