### ISSUE TITLE
Некорректное представление адреса #165

### ISSUE THREAD

**Issue by Scopatutto** [diadoc/diadocsdk-1c-docs#166]
Добрый день!
Модуль Диадок для ОФ 5.19.13, формирую УПД, при формировании представления адреса некорректно формируется часть с корпусом/строением, офисом/квартирой.
Если у организации в адресе есть "строение", то в представлении будет заменено на "корпус", "офис" будет заменен на "квартира". Это ошибка? Ниже код из модуля:
ПредставлениеАдреса = ДобавитьРазделитель(Индекс)+ДобавитьРазделитель(НаименованиеРегиона(КодРегиона))+ДобавитьРазделитель(Район)+ДобавитьРазделитель(Город)+ДобавитьРазделитель(НаселПункт)+ДобавитьРазделитель(Улица)+ДобавитьРазделитель(Дом, "дом №")+ДобавитьРазделитель(Корпус, "корпус ")+ДобавитьРазделитель(Кварт,"кв ");

Получил ответ, прошу разъяснить.
"Нет ошибки не будет.
Дело в том что в xsd схеме УПД в атрибутах адреса нет строения и офиса, поэтому эта информация записывается в атрибуты Корпус и Кварт."

Прошу уточнить: вопрос не в том, в какие атрибуты записывается, а в формировании печатной формы. Разве это верно всегда подставлять разделитель "кв ", даже если это "офис"?

**Comment by denver069** [comment]
Повторно открыл изначальный вопрос https://github.com/diadoc/diadocsdk-1c-docs/issues/165, поэтому этот закрываю.
