### ISSUE TITLE
Возможная ошибка в наименовании поля GovermentContractInfo в УПД и УКД

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#167]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.18.7.252.

Заметили одну странность, очень похожую на ошибку. Суть:

1. Документ УПД, UtdSellerContent. Документация:
![default](https://user-images.githubusercontent.com/33707226/32870056-cb21e658-cac5-11e7-8466-053a8e85be52.png)

2. Объект UtdSellerContent, как он есть при получении данных через АПИ:
![default](https://user-images.githubusercontent.com/33707226/32870034-b14bece2-cac5-11e7-9960-01287fb9178a.png)
Поле названо «GovermentContractInfo» - в точности, как в документации.

3. Документ УКД, UcdSellerContent. Документация
![default](https://user-images.githubusercontent.com/33707226/32870066-d8c5a4fc-cac5-11e7-8f10-ecd7e62926db.png)
Точно такое же (по идее) поле, как и в УПД.

4. Объект UcdSellerContent, как он есть при получении данных через АПИ:
![default](https://user-images.githubusercontent.com/33707226/32870284-e4678a7c-cac6-11e7-9d5a-7d2e8c0f6250.png)

!!! Поле названо «Gover**N**mentContractInfo» - **не так, как в документации!**

Т.е. между «r» и «m» появилось «n» и, согласно переводу, вместо «госзакупки» возникло «правительство». 

Самое главное – это, во-первых, расходиться с документацией и, во-вторых, явно расходиться название по сути одного и того же поля в документе УПД и документе УКД!

По идее, судя по переводу слов, именно в поле документа УКД «затесалась» лишняя буква «N», а наименование поля «GovermentContractInfo» (как в УПД) – это верный вариант.

**Вопросы:**
А вы будете это как-то исправлять? Если да, то какой вариант будет признан правильным? Или оставите, как есть для какой-то обратной совместимости? Или мы что-то недопонимаем, и такое различие абсолютно верно?

Спасибо.

**Comment by azhipaigor** [comment]
Добрый день!
В какой-то момент действительно была опечатка и поле называлось GovermentContractInfo. Верный вариант Gover**N**mentContractInfo. В компоненте с версии 5.18.1, для UtdSellerContent существуют оба поля, для UcdSellerContent, только верный вариант. Документацию давно поправили, свежую версию всегда можно найти здесь [http://1c-docs.diadoc.ru](http://1c-docs.diadoc.ru).

**Comment by JohnSergeev** [comment]
Ясно. Спасибо.
