### ISSUE TITLE
Странность в документе "Неформализованный Договор" (тип "Contract")

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#168]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.18.7.252.

Заметили следующую странность в документе Contract:

1. Информация по отправке документа:
![default](https://user-images.githubusercontent.com/33707226/32870524-14bc6584-cac8-11e7-8a02-040fa72c39b2.png)

2. Информация по его получению:
![default](https://user-images.githubusercontent.com/33707226/32870545-29e9b7cc-cac8-11e7-8139-85af4917c160.png)

По факту - это одно и то же поле, т.е., если я при отправке укажу некое значение в поле ContractPrice, то получатель документа увидит это значение у себя в поле Price.

В результате это **единственный документ** в вашей системе типов документов у которого **одно и то же свойство имеет различные наименования в зависимости от того, получаем мы этот документ, как входящий или же отправляем его, как исходящий**. 

При получении мы должны прочитать поле «Price», но при отправке такого поля нет, а заполнить надо поле «ContractPrice» – тогда при получении именно введенное в него значение будет читаться из поля «Price». 

В дополнение это поле еще и по-разному названо в PDF документации – в одном месте оно фигурирует как «цена», а в другом – как «сумма». 

**Вопросы:**
Вы будете это как-то исправлять? Если да, то какой вариант будет выбран? Или оставите, как есть для какой-то обратной совместимости? Или мы что-то недопонимаем, и такое различие абсолютно верно?

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Выпустили релиз 5.22.2 . В нём появилось поле Price у объекта ConteractToSend. Для обратной совместимости старое имя поля так же присутствует, но в дальнейшем будет удалено
