### ISSUE TITLE
Странное поведение функции VerifyThatUserHasAccessToAnyBox

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#169]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.18.7.252.

В АПИ есть следующая функция:
![default](https://user-images.githubusercontent.com/33707226/32871012-632ba41c-caca-11e7-9417-f8d97108738f.png)

**Либо мы как-то не до конца понимаем ее смысл, либо она просто неправильно работает!** 

Суть проблемы – эта функция у нас возвращает «Истина» (т.е. доступ есть) всегда и для всех сертификатов! В том числе и для тех, которые «отключены» от Диадок (не авторизированы), и для тех, которые уже давно просрочены.

**Примеры.** 
У меня в обработке для тестирования в окне выбора сертификатов для подключения в колонке, которая заполняется  результатом вызова этой функции («Доступ в Диадок») для каждого из сертификатов из списка всегда возвращается «Истина»:
![default](https://user-images.githubusercontent.com/33707226/32871192-65d5d13c-cacb-11e7-8898-243ef6413f6d.png)

Причем сертификаты, указанные серым цветом – это те, по которым уже закончился срок действия. А некоторые сертификаты вообще «отключены» от Диадок, т.к. была смена юр. лица и сейчас у нас доступ к рабочему ящику осуществляется по новым сертификатам, выданным на новое юр. лицо.

При попытке подключения по просроченным и "отключенным" сертификатам, никакого подключения не происходит, и выдается ошибка (на примере первого сертификата из списка):

_Ошибка при вызове метода контекста (CreateConnectionByCertificate): Произошла исключительная ситуация (DiadocApiInvoiceApi.CreateConnectionByCertificate): ##100[Ошибка сервера Диадок]code:401, HTTP error: Certificate with thumbprint 0AD138B434906D00733C0560185C973CDDEFB72F is not authorized._

При этом, как видно на скрине выше, функция VerifyThatUserHasAccessToAnyBox почему-то для данного сертификата возвращает, что доступ в Диадок по нему есть (т.е. возвращает «Истина»).

**Вопросы:**
Хотелось бы понять – это мы как-то не понимаем поведения этой функции и на самом деле она все показывает верно (тогда что она на самом деле делает?! И может стоит это как-то отметить в документации?)? Или же это действительно ошибка – тогда хотелось бы увидеть ее исправление.

Спасибо.

**Comment by sergro** [comment]
Добрый день.   Насколько я понял разбираясь с этой функцией.
Функция GetPersonalCertificates() Возвращает зарегистрированные на клиентской машине личные сертификаты пользователя. Это могут быть сертификаты не только Диадока.
VerifyThatUserHasAccessToAnyBox () сертификаты не имеющие отношение к диадоку.

**Comment by JohnSergeev** [comment]
А причем здесь это? Речь о том, что VerifyThatUserHasAccessToAnyBox почему-то **возвращает для сертификатов, по которым доступа к Диадок нет - информацию о том, что этот доступ есть!** И это, как минимум, странно. И очень похоже на ошибку.

**Comment by azhipaigor** [comment]
VerifyThatUserHasAccessToAnyBox просто пытается найти юзера по сертификату и проверяет, что этот юзер является сотрудником хотя бы одной организации, сертификат при этом не проверяется. При подключении по сертификату, выполняется проверка сертификата и соответственно для невалидных сертификатов вернется ошибка.

**Comment by JohnSergeev** [comment]
Добрый день.

Тогда, из вашего определения, прямо следует, что данная функция **полностью не соответствует** своему описанию в документации:
![default](https://user-images.githubusercontent.com/33707226/33692366-a92e9c34-db38-11e7-9d92-704d7b07748b.png)

Тогда надо либо привести функцию в соответствие описанию, либо привести описание в соответствие функции. А сейчас, по факту, документация вообще не соответствует поведению функции и вводит в заблуждение.

Как раз в нашем случае - для некоторых сертификатов функция возвращает Истина (что, согласно документации, означает, что **доступ в Диадок** по этому сертификату есть), а на деле доступа к Диадок по этим сертификатам **нет**!

Возможно, стоит как-то более детально написать в документации, что именно в случае данной функции понимается под "доступом".

**Comment by GilimkhanovDenis** [comment]
Описание метода было изменено, теперь соответствует поведению
