### ISSUE TITLE
Не отправляется приглашение в ЭДО

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#17]
Для контрагента с  ИНН 344708036767 не отправляется приглашение к ЭДО.
По остальным 5000 контрагентам все ушло замечательно, что в этом не так?

**Comment by denver069** [comment]
Спасибо за обращение!
Контрагент с ИНН 344708036767 не зарегистрирован в Диадоке, то что он попал в список на отправку приглашений - является ошибкой. В ближайшем релизе модуля ошибка будет исправлена.
