### ISSUE TITLE
Вопросы по реализации работы с удаленными документами

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#170]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.18.7.252.

Согласно документации, в АПИ компоненты для 1С просто вообще толком нет никакого функционала по работе с удаляемыми и удаленными документами!

Что я могу делать у вас на сайте (кратко – и это минимальный логичный набор операций):
1.	Удалить документ (перенести в удаленные)
2.	Посмотреть какие документы лежат в папке «Удаленные»
3.	Восстановить документ из папки «Удаленные» обратно туда, откуда он в «Удаленные» попал

Что я могу делать через АПИ (согласно документации – и это какой-то куцый огрызок от нужных возможностей):
1.	Удалить документ (перенести в удаленные)

В рамках АПИ мы, получается ничего толком сделать-то не можем! Удалил я документ и ошибся (всякое бывает) – и что дальше? Восстановить документ я не могу, нет такой команды. Посмотреть, что у меня в удаленных – не могу, поиск и отбор документов не показывает документы в папке «Удаленные» - только «Входящие» и «Исходящие». 

Как с этим работать? **Получается, что если действуешь в рамках АПИ, то даже права на ошибку не имеешь! Удалил – всё, уже никак не восстановишь!** Нужно заходить на сайт и там восстанавливать. 

А с другой стороны еще хуже. Например, пришел мне документ входящий. Я на его основе в своей базе сделал документ, с которым далее работает уже наша внутренняя система. Решили, что он плохой, а т.к. он роуминговый, то его удаляют обе стороны. 

И наш бухгалтер удалил его не через АПИ, а зайдя на ваш сайт – оттуда. Ну, так получилось. 

**У нас по идее полностью теряется синхронизация состояния документа!**

В Диадок документ числится удаленным, а у нас в базе – нормальным! Быстро посмотреть раз в день, например, что лежит в удаленных и синхронизировать состояние документов я не могу – мне нельзя посмотреть, что в удаленных, нет в АПИ такой возможности. При получении, например, входящих документов, я этот документ Диадок в списке также уже не увижу – его уже нет в папке  входящих… Поэтому и понять, что он удален не смогу. **А как тогда синхронизироваться?!** 

Перебирать вообще все документы во входящих и в исходящих и, если такой есть в нашей БД, но нет в полученных списках, то получать уже этот отдельный документ снова по ID и проверять не стоит ли у него признак удаления?! А если у меня ОЧЕНЬ МНОГО документов?!

Ведь правильнее и проще было бы быстро просмотреть документы в папке удаленные и быстро все синхронизировать, точно зная, что критерий железобетонный – раз документ в папке удаленных, то он уж точно удален. Но такой возможности в АПИ нет!

В связи с этим вопросы:
1.	Точно ли кроме удаления документа никаких возможностей по работе с удалениями в АПИ для компоненты 1С нет? Или что-то все-таки есть – тогда что?
2.	Если действительно нет – то вообще предполагается эту недоработку как-то решать? Ну просто с точки зрения здравого смысла **в АПИ должен быть такой же минимальный функционал, что и на сайте**: а) удаление; б) просмотр удаленных; в) восстановление ошибочно удаленного. Вы планируете это добавить?
3.	Как с вашей точки зрения в текущей ситуации, когда нельзя посмотреть, что же удалено понимать для каждого полученного документа – а он уже удален в Диадок или еще нет? Проверяя это поштучно для каждого имеющегося документа?!

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Доброго времени суток

1. Ни в api компоненты, ни в http api нет метода для запроса списка удалённых документов. Если такая возможность необходима, то рекомендую обратиться к менеджеру, чтобы он данную задачу всячески продвигал в очереди разработки (если не знаете кто менеджер, то позвоните в техподдержку, ребята помогут сориентироваться)

2. Метод удаления документа есть у объекта Document.
Метод восстановления документа будет в релизе 5.25.1. Синтаксис будет такой:
Organization.RestoreDocument(<DocumentId>)

3. Пока другой возможности, кроме поштучной проверки нет. В планах другой функциональности не планируется (если это критично, то см. п.1)
