### ISSUE TITLE
Проблема с полем ОКДП при отправке документов УПД

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#171]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.18.7.252.

Если при заполнении любых данных из списка: продавца, покупателя, грузоотправителя, грузополучателя для документов с форматом данных УПД заполнить поле «ОКДП» (т.е. поле ExtendedOrganizationInfo.Okdp), то оно прекрасно заполниться в формируемом объекте документа. 

Затем документ успешно отправляется… И после этого оказывается, что и в данных исходящего документа, и в данных входящего документа это поле уже не заполнено – там пусто!

Выглядит это как явная и очень странная ошибка! Непонятно, почему оно очищается. Если мы внесли в поле некорректные данные, то было бы логично не отправлять исходящий документ с какой-то очисткой полей, а сообщить об ошибке. Однако, документ успешно уходит. И у отправителя в исходящих, и у получателя во входящих это поле в документе оказывается пустым!

Это какая-то ошибка или мы что-то не понимаем и так и должно быть?

**Дополнительно:** в PDF документации до сих пор ошибка – в ней это поле названо не «Okdp», а «Okpd»:

![default](https://user-images.githubusercontent.com/33707226/32871747-8ebd4ea6-cace-11e7-9f6c-b73d8e3f438a.png)

Спасибо.

**Comment by etalipov** [comment]
Добрый день!
Форматом 155 приказа ФНС не предусмотрен тег ОКДП, т.е. в xml нет установленного тега, куда эти данные можно поместить.
