### ISSUE TITLE
Проблема с заполнением данных по ГТД в УПД

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#173]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.18.7.252.

Суть проблемы – Если при заполнении таблицы ГТД для товара в УПД заполнить в таблице, например, одну строку в которой будет задан код страны «Россия» и не будет задан ГТД (т.е. код страны есть, а номер ГТД в этой строке не задан), то такой документ будет невозможно отправить! 

Будет выдаваться ошибка не некорректном заполнении данных по ГТД с требованием указания корректного номера ГТД в строке:

_Ошибка при получении значения атрибута контекста (Result): Произошла исключительная ситуация (PackageSendTaskAsyncResult.get_Result): ##100[Ошибка сервера Диадок]code:400, HTTP error: Info.InvoiceTable.Items[0].CustomsDeclarations[0].DeclarationNumber is required]_

**Однако, такое поведение противоречит законодательству!** Для передачи товаров российского производства можно в данных ГТД указывать страну, но не указывать при этом ГТД (что логично – никакой работы с таможней при передаче товаров внутри страны нет). Наши бухгалтера предоставили следующий отрывок информации по этому поводу:

-----------------------------------------------------------
Это не ошибка. Товар в документе - произведен в России и не имеет ГТД.
C точки зрения законодательства в графе 10, 10а (страна пр-ва) и 11 (ГТД), если товар российского пр-ва можно указывать прочерк, либо вообще пустую графу оставлять.
Но если прописать значение "Россия" и проставить числовой код страны, а вместо ГТД прочерк - ошибки в этом нет. 
Если в графах 10 и 10а счета-фактуры, заполненного при реализации отечественного товара, указаны код 643 и наименование "Россия", отказать в вычете НДС нельзя
05.03.2013 4588

В своем письме от 10.01.2013 № 03-07-13/01-01 Минфин России рассмотрел вопрос о правомерности вычета по счету-фактуре, выставленному при реализации товаров отечественного производства с заполненными графами 10 и 10а.

Финансовое ведомство напомнило, что в графах 10 и 10а счета-фактуры указывается страна происхождения товаров (цифровой код и соответствующее ему краткое наименование). Данные графы заполняются в отношении товаров, страной происхождения которых не является Российская Федерация. При реализации товаров, произведенных на территории Российской Федерации, в данных графах ставятся прочерки (подпункты "к" и "л" п. 2 Правил заполнения счета-фактуры, утв. постановлением Правительства РФ от 26.12.2011 № 1137).

**При этом Министерство отметило, что данные Правила не запрещают указывать дополнительную информацию в счете-фактуре. Поэтому проставление в графе 10 цифрового кода Российской Федерации "643" и в графе 10а краткого наименования страны происхождения товаров "Россия" не является основанием для отказа в вычете НДС.**

Напомним, ранее финансовое ведомство разъясняло, что при оказании услуг, а также при реализации товаров, страной происхождения которых является Российская Федерация, графах 10, 10а и 11 ставятся прочерки.

В "1С: Предприятии 8" порядок заполнения граф 10, 10а и 11 счетов-фактур реализован в соответствии с рекомендациями Минфина России. При формировании документа Реализация товаров и услуг в случае реализации товаров, произведенных в России, в графах 10, 10а и 11 по умолчанию проставляются прочерки. **При этом есть возможность указать страну и код страны для Российской Федерации.**

Новость подготовлена специалистами ИТС
Источник: buh.ru
-----------------------------------------------------------

Мы видим тут 2 варианта:
1.	У вас действительно есть недоработка в этом плане, которую надо исправить (т.е., если указан код страны Россия, то не считать ошибкой отсутствие ГТД)
2.	У вас все работает верно, просто в такой ситуации нам надо не оставлять поле ГТД пустым, а ставить туда некий «прочерк». 

Тогда возникает вопрос – а что это за «прочерк», т.е. какие именно символы писать в поле ГТД, чтобы ваша система (да получатель документа, кстати, тоже!) посчитала эти символы за «прочерк». В вашей документации ни слова о «прочерках» нет!

![default](https://user-images.githubusercontent.com/33707226/32871938-b282d328-cacf-11e7-842b-34532bc49833.png)

Как быть с этой проблемой?

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Согласно формату электронного документа, в тэге <СвТД/> обязательным является указание как кода страны так и номера таможенной декларации
https://normativ.kontur.ru/document?moduleId=1&documentId=271958&rangeId=35464

Соответственно, в электронном УПД даже при указании страны происхождения Россия необходимо заполнять номер таможенной декларации, например дефисом

**Comment by JohnSergeev** [comment]
Вы бы в документации этот момент отразили! Так сказать, для будущих поколений...
