### ISSUE TITLE
Вопросы по формированию адресных данных

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#174]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.18.7.252.

Ранее я писал вам, что указанная вами в документации информация по размерности полей в структуре AddressInfo не соответствует реальности. Методом «научного тыка» были установлены реальные размеры указанных полей, и информация была передана вам. В результате этого вы обновили документацию на сайте:

![default](https://user-images.githubusercontent.com/33707226/32872103-97b30e22-cad0-11e7-85ad-fd35f4f5d2ab.png)

Но не обновили документацию в PDF (размерность полей Дом, Корпус, Квартира):

![default](https://user-images.githubusercontent.com/33707226/32872110-a1cc8dde-cad0-11e7-9774-b3d89c2c9a31.png)

Плюс вы так и не ответили нам на вопрос, что делать с поставщиками в адресах которых встречается следующее заполнение номера дома и помещения (_это реальные данные, поставщик так пишет в бумажных документах!_):

**«№ 20, ЛИТЕР А, пом. 8-Н-116-121, 126-130»**

Ровно 40 символов.

И, если разделить на номер дома «№ 20, ЛИТЕР А» и номер квартиры «пом. 8-Н-116-121, 126-130», то в 20 символов квартиры все равно толком не входит!

**Вопросы:**
Как быть с такими адресами? 
Надо убеждать поставщика, что такие данные сами по себе некорректны? Или же надо как-то разделять адресные данные на равные блоки, не заботясь о логической целостности элементов адреса (типа, номер дома = «№ 20, ЛИТЕР А, пом. » и номер квартиры = «8-Н-116-121, 126-130»)?

А так вообще правильно?

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Ограничение в 20 символов на поля Building/Block/Apartment - требование [формата](https://normativ.kontur.ru/document?moduleId=1&documentId=271958&rangeId=35487) 

кроме заполнения адреса в указанных полях, адрес может быть заполнен и в поле [AddressText](http://diadocsdk-1c.readthedocs.io/ru/latest/AddressInfo.html?highlight=AddressText) (с одновременным заполнением поля CountryCode и флагом IsForeign, установленным в True )
В формате это соответствует заполнению адреса в структуре [АдрИнф](https://normativ.kontur.ru/document?moduleId=1&documentId=271958&rangeId=35488)

**Comment by JohnSergeev** [comment]
А разве в такой ситуации к нам не возникнет вопросов от разного рода инспекций - типа, "а чего это вы российские адреса как иностранные заполняете?!". Или это в нашем странном законодательстве считается абсолютно нормальным?
