### ISSUE TITLE
Ошибка! при отправке документа нового типа TovTorg (формат 551-го приказа ФНС для торг-12)

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#175]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.18.7.252.

Сегодня установили последнюю версию АПИ (5.19.0.275) для доработки и тестирования работы с новыми типами документов - в частности для документов типа TovTorg  (формат 551-го приказа ФНС для торг-12).

После реализации работы с документами типа TovTorg обнаружили воспроизводимую ошибку!
Суть проблемы (на пошаговом примере):

1. Создаем и заполняем объект документа и отправляем его как исходящий. Отправка нормально происходит, никаких ошибок не выдается. Документ виден у отправителя в исходящих и у получателя во входящих.

Данные документа (по которому сделаны все скрины):
Id Документа = 17f4678f-7e06-4f6e-9bb2-f3c75f6115bba862593d-b434-43cf-a449-011c71abb117
URL документа = /8015d19a-35ef-421f-84d1-2fbc7258c309/Document/Show?letterId=17f4678f-7e06-4f6e-9bb2-f3c75f6115bb&documentId=a862593d-b434-43cf-a449-011c71abb117

2. У документа нормальная печатная форма:

[т12_551.pdf](https://github.com/diadoc/diadocsdk-1c-docs/files/1477781/12_551.pdf)

А вот дальше при попытках работы с документом через АПИ происходит следующее:

3. Получим данные объекта документа:
![default](https://user-images.githubusercontent.com/33707226/32881184-20f6e7fa-cafc-11e7-8993-060d2de1746c.png)
Пока все хорошо.

4. А теперь выполняем элементарное действие - GetContent()
![default](https://user-images.githubusercontent.com/33707226/32881294-85060190-cafc-11e7-9e64-66046207cfb5.png)

И видим, что в качестве объекта контента мы получили не объект типа **TovTorgSellerContent**, а объект типа **Torg12SellerContent**! Причем без выдачи каких-либо ошибок, да еще и абсолютно пустой за исключением подписанта - в него почему-то данные перекинулись. Но все остальное пусто - не заполнены данные состава, данные покупателя, продавца и т.д.

![default](https://user-images.githubusercontent.com/33707226/32881408-e6066624-cafc-11e7-8366-7a1f0069ba94.png)

![default](https://user-images.githubusercontent.com/33707226/32881443-fa91f036-cafc-11e7-9c3b-4fa417cd169f.png)

![default](https://user-images.githubusercontent.com/33707226/32881457-0679edc2-cafd-11e7-8eb2-c535eaf1c5ff.png)

Причем видно, что на печатной форме (см. вложение PDF выше) все данные есть! Такое ощущение, что ошибка где-то в GetContent - она просто "выгребает" данные не того типа! Ей нужно получить TovTorgSellerContent, а она возвращает Torg12SellerContent.

Надеемся, что такое явно ошибочное поведение будет исправлено. 

Дополнительно: 
Проблема воспроизводима - как оказалось, в наш рабочий ящик поставщик ИП Бородкин Павел Владимирович (e5f6117c50894db09b07f01f1663e7eb@diadoc.ru) выслал 34 Торг-12 в таком формате. С ними такая же проблема при получении. И также - у них нормально заполненные печатные формы, что еще раз намекает, что дело именно в работе метода GetContent(). 

ID нескольких из этих документов для примера:
abc4a9f1-2575-44f2-8e5f-d285d7925a76a1334893-e2eb-4ce8-9d2c-07ef258a1493
85cbbd8b-e3de-4a0e-ba60-fba52f603c1df41feb82-6c20-476e-9c65-5cc6c1d26039
d7fea689-abb6-4a38-bfb9-05e2f3f14bf26b5c3425-7f5f-47fb-b212-6db1f6f2e528
991d2b4c-ec47-4694-9085-3deee3c626fab8fd10f9-d286-418e-8b42-9e19a76434f6

Надеемся на скорейшее исправление проблемы.
Спасибо.

**Comment by denver069** [comment]
Судя по всему вы обрабатываете полученный документ старой внешней компонентой - версией до *5.19.0.275*.
Проверьте версию компоненты в модуле которым выполняется метод GetContent.

**Comment by JohnSergeev** [comment]
Добрый день.
К сожалению, судя по всему, вы не очень внимательно прочитали мое сообщение.

Я писал:

_Сегодня установили последнюю версию АПИ (5.19.0.275) для доработки и тестирования работы с новыми типами документов - в частности для документов типа TovTorg (формат 551-го приказа ФНС для торг-12)._

Т.е. вся работа выполняется под версией **5.19.0.275**. Последней. Это 100% точно еще и потому, что в тестовой обработке в которой мы выполняем тестирование нового функционала у нас как раз, чтобы случайно не напороться со смешением версий при регистрации com-компонент, просто выводиться версия компоненты, с которой идет работа. И у меня на скрине видна именно нужная версия:

![default](https://user-images.githubusercontent.com/33707226/32923167-cb9708e0-cb81-11e7-99f8-42a5d268c1cc.png)

Во-вторых, я же писал, что **я сам отправил документ нового формата** (у нас 2 тестовых ящика, и я отправил из одного в другой). Плюс то, что это именно TovTorg опять же видно на первом скрине:

![default](https://user-images.githubusercontent.com/33707226/32923202-fde16606-cb81-11e7-9891-ede00f43d4e3.png)

Каким бы образом я смог отправить документ новом формате из старой версии компоненты, которая этот формат просто-напросто не поддерживает?!

И проблема видна и в ящике отправителя для исходящего документа, и в ящике получателя для входящего документа. Это опять же воспроизведено в 2 тестовых ящиках - отправителя и получателя.

Так что проблема имеет место быть!

**Comment by JohnSergeev** [comment]
Дополнение.
Точно такое же поведение и с документом - Акт в формате 552-го приказа.

Сегодня добавили поддержку.

Также:
Создаем
Отправляем
Без ошибок есть и в исходящих, и во входящих
При выполнении GetContent() возвращается объект типа AcceptanceCertificateSellerContent, а не объект типа Act552SellerContent (что по идее должно быть)

![default](https://user-images.githubusercontent.com/33707226/32935609-a6f26bf2-cbbc-11e7-9fea-59ef84b6d1b2.png)

Версия АПИ:
![default](https://user-images.githubusercontent.com/33707226/32935662-d81f80e8-cbbc-11e7-8d66-a5497a774b8b.png)

Работаем через внешнюю com-компоненту. 

Спасибо.

**Comment by denver069** [comment]
Пробовали использовать [внешнюю компоненту для 1С](http://1c-docs.diadoc.ru/ru/latest/Downloads.html)?

**Comment by JohnSergeev** [comment]
Добрый день.
Нет, в нашей реализации все работает на сервере через фоновые задания, поэтому мы пользуемся только com-вариантами.

**Comment by JohnSergeev** [comment]
Я вполне допускаю ненулевую вероятность того, что у нам при обновлении что-то так странно "слетело", что ваше АПИ показывает одну версию через вызов GetVersion(), а при вызове GetContent() вдруг каким-то образом вызывает откуда-то старый код. Но с оооочень маленькой долей вероятности! Это было бы что-то весьма странное...

Поэтому хотелось бы, чтобы вы просто попробовали воспроизвести ошибку - это же просто! И сразу стало бы понятно - либо проблема воспроизводиться и ошибка есть, либо не воспроизводиться - и скорее всего, у нас что-то странное происходит. Тогда может быть проблема вообще не в приеме, а в отправке (я давал ссылки на документы) - может там что-то не до конца или неверно заполнилось и поэтому чтение неправильно принимает документ за документ другого типа.

Вам виднее - вы разработчик.

**Comment by JohnSergeev** [comment]
Протестировал в новой версии 5.19.1.282 - проблема ушла, все работает на новых Торг-12 и Акте.

Спасибо!
