### ISSUE TITLE
Ошибка получения данных согласования/подписи документов

### ISSUE THREAD

**Issue by AleksandrAAV** [diadoc/diadocsdk-1c-docs#176]
Как получить дату подписи и дату согласования сотрудником организации и сотрудником КА?

Метод ‘Timestamp’, объекта ‘Document’, возвращает дату отправки документа на согласование (дата есть), но документ можно отправить без согласования, а согласовать позже. Необходимо получить даты ФИО ответственного сотрудника (ов), который (ые) подписали и согласовали документ (либо отклонили). 

Метод ‘GetSenderSignature’ возвращает значение SignDate пустым.
Метод ‘GetRecipientSignature’ возвращает неопределенное значение, получить данные невозможно.
  
Как получить историю согласования по документу? Метод ‘Resolutions’ заполняется в единичных случаях (какие условия должны совпасть?).

Даты совершения действия сотрудников (подпись/согласование) не совпадают с действительностью и по какому принципу они отбираются? К чему относятся даты событий так и не понял - брал пул следующих дата (ни одна не подошла!!!): дата отправки, дата подписи (орг), дата подписи (КА), дата согласования (орг), дата согласования (КА). Пример в виде скрина могу на почту выслать с более подробным описанием, опираясь на пример. 
Ряд событий, в частности согласование сотрудником КА документа, получить так же невозможно, хотя в описании API возможность получения заявлено!

**Comment by denver069** [comment]
Покажите ссылку на документ и опишите несоответствие, в этом запросе.

**Comment by AleksandrAAV** [comment]
Идентификатор документа: FKrhx64wkK6vF6MUsTG9p9kPD417q5IxKgnbKSCMqd+
Несоответствие дат действия сотрудников организации и контрагента.
На скрине информация по согласованию/подписанию документа в личном кабинете на сайте.
При обращении программно (цель: получение данных всех действий в разрезе сотрудника КА/Орг , статуса, а так же даты статуса) получить данные невозможно. В рамках данного примера последняя доступная информация - по завершению документооборота (но потом ведь еще и согласование прошло!), при этом дата подписи (получаемая по API) не совпадает с данными на скрине. Совпадает только первая дата (дата отправки на согласование и подписи), да и то только потому что она заполняется на нашей стороне при отправке документа, из диадока мы ее не получаем. Откуда берется дата (по этому же примеру) '01.11.2017 15:27'? - данную дату я получаю, но не понятно к какому именно событию она относится (на скрине выведены все события по документу).
![example](https://user-images.githubusercontent.com/18366340/33063577-e548fb4c-ceb3-11e7-9c19-6287a7ccaf1a.jpg)

**Comment by AleksandrAAV** [comment]
Есть решение по данному вопросу?

**Comment by denver069** [comment]
Пришлите пожалуйста *ссылку* на документ, только по идентификатору документ в Диадоке  посмотреть не получится.

**Comment by alevanov** [comment]
@AleksandrAAV Вам удалось получить историю обработки документа в том виде, как она есть на сайте? Если да, то как?

**Comment by GilimkhanovDenis** [comment]
> Метод ‘GetSenderSignature’ возвращает значение SignDate пустым.
В тестовых организациях это поле будет оставаться пустым. Однако поле SignatureAuthenticityDate будет заполнено. В реальных (боевых) ящиках и то, и другое поле будет заполнено.

> Метод ‘GetRecipientSignature’ возвращает неопределенное значение, получить данные невозможно.
> 
> Как получить историю согласования по документу? Метод ‘Resolutions’ заполняется в единичных случаях (какие условия должны совпасть?).

Нужны ссылки на документы, чтобы можно было воспроизвести ситуации.

**Comment by GilimkhanovDenis** [comment]
Закрываю за давностью и отсутствием информации от инициатора запроса
