### ISSUE TITLE
Ошибка! Несоответсвие документации и реальных объектов (несовпадение названий полей и методов)

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#177]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.19.1.282.

Замечено несоответствие документации и реальных объектов.

В документации:
![default](https://user-images.githubusercontent.com/33707226/33112108-30d58596-cf9d-11e7-827f-97126d8425bb.png)

А объекте:
![default](https://user-images.githubusercontent.com/33707226/33112296-39b47c52-cf9e-11e7-85b3-9094d447c578.png)

Т.е. поле на самом деле называется Singers. И ф-я добавления подписанта также вызывается как AddSinger(), а не как AddExtendedSigner().

![default](https://user-images.githubusercontent.com/33707226/33112195-b3a30430-cf9d-11e7-9516-65a6ed9ab32f.png)

**Comment by azhipaigor** [comment]
Добрый день! Спасибо. Обновили документацию.
