### ISSUE TITLE
Критическая ошибка при работе с GetDocumentEventList

### ISSUE THREAD

**Issue by OdintsovSergey** [diadoc/diadocsdk-1c-docs#178]
Столкнулись  с очень серьезной проблемой. Мы не можем получить все документы от контрагента.

Проблема в том, что они отправляют пакеты с большим  количеством документов.
Мы  используем для получения документов библиотеку AddInDiadocAPI.

В своей системе мы сохраняем последние событие и используем метод  GetDocumentEventList (http://1c-docs.diadoc.ru/ru/latest/GetDocumentEventList.html) для получения следующих.

Проблема возникает если 100 документ получается внутри пакета и мы не можем получить все документы из этого пакета.

Опять запоминаем у 100 документа EventId в последние событие. Но при последующем вызове GetDocumentEventList не полученные документы из пакета исключаются.

Я думаю два варианта исправления этой ошибки:
1.       Для каждого документа из пакета должно быть свое событие
2.       Должны возвращаться все  события с одинаковым EventId в методе GetDocumentEventList.
a.       Если все не входят в 100, то убираем и остальные  с таким же EventId
b.      Возвращаем больше 100, если  есть документы с таким же EventId.

**Comment by GilimkhanovDenis** [comment]
На новых версия компоненты должно быть неактуально
