### ISSUE TITLE
Обработка утверждения аннулирования

### ISSUE THREAD

**Issue by OdintsovSergey** [diadoc/diadocsdk-1c-docs#179]
Добрый день.

При использовании DiadocComApi.dll EventType приходит равным Accept. Как отличить утверждение аннулирования от простого утверждения документа. Особенно это важно для неформализованных документов, так как для них метод GetFileContent так же возвращает пустое имя файла и EventType равен так же Accept. Нельзя ли для утверждения аннулирования сделать другое значение EventType.

**Comment by GilimkhanovDenis** [comment]
Добрый день
Пожелание зафиксировано, сроков дать не можем, так как задача затронет архитектуру всей ленты событий
