### ISSUE TITLE
как заполнить AdditionalInfo для торг-12

### ISSUE THREAD

**Issue by ivanzavr** [diadoc/diadocsdk-1c-docs#18]
Здравствуйте
Партнер просит добавить дополнительное текстовое поле с указанием GLN. 
Прислал такой текст:
Требования к формализованному формату ТОРГ-12:
 - В дополнительном текстовом поле документа ЭДО (XML)  должен быть указан GLN магазина согласно нижеприведенному примеру:
	<ИнфПол ТекстИнф="получатель:4604985999968 " />

могу ли я в модуле обработки в процедуре ЗаполнитьКонтентXmlTorg12() написать просто:
content.AdditionalInfo = "получатель:4604985999968";

или надо делать как-то так:
content.AdditionalInfo = "<ИнфПол ТекстИнф="""+"получатель:4604985999968"+""""+" />";

**Comment by denver069** [comment]
Для XmlTorg12 достаточно указать: Content.AdditionalInfo = "получатель:4604985999968";
Сделать это можно в подключаемом модуле в функции ОбработатьСобытиеПослеЗаполненияКонтента() предварительно удалив её комментирование в функции ОбработатьСобытиеДиадок().
