### ISSUE TITLE
Ошибка! Ошибка в формировании составов Торг12 в формате 551-го приказа ФНС - пропадает наименование товара

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#181]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.19.1.282.

При реализации работы с Торг-12 в формате 551-го приказа ФНС столкнулись с поведением, крайне похожим на грубую ошибку!

Суть проблемы:

Формируем состав Торг-12 в таком виде (для примера):
![default](https://user-images.githubusercontent.com/33707226/33161925-68b29fb4-d072-11e7-8610-26fcb00d8103.png)
(видна только часть колонок, т.к. остальные для данного примера не важны).

Отправляем документ от отправителя к получателю (в нашем случае - из одного тестового ящика в другой). Документ формируется и отправляется. А дальше получается вот что:

Если получить сформированный документ в ящике отправителя (как исходящий) или если получить этот документ в ящике получателя (как входящий) - в любой ситуации оказывается, что данные в составе были изменены!

И у отправителя, и у получателя в документе будет такой состав:
![default](https://user-images.githubusercontent.com/33707226/33162060-434947b8-d073-11e7-81ea-7f5033fe25cd.png)

В печатной форме это выглядит так:
![default](https://user-images.githubusercontent.com/33707226/33162124-82fbfb08-d073-11e7-8f7a-e33ade3a868c.png)

**Т.е. получается, что, если для товара задано значение в колонке Характеристика (поле Feature объекта TovTorgItem), то в формируемом документе эта характеристика запишется вместо наименования товара, а значение самой характеристики будет пустым!**

Пожалуйста, если это ошибка - исправьте ее. А если такое поведение правильное, то напишите в чем суть такого поведения - мы сами информации по такому поведению не нашли.

Спасибо.

**Comment by JohnSergeev** [comment]
Дополнение.
Ошибка не при отправке, а еще в момент формирования. Делаем ОбъектСтрокиСостава.Feature = <Значение характеристики> и тут же в отладчике видно, что значение попадает не в поле Feature, а в поле Product.

**Comment by GilimkhanovDenis** [comment]
ответ был дан в рамках обращения в техподдержку №14672280
на новых версиях не воспроизводится
