### ISSUE TITLE
403 ошибка при отправке неформализованного документа 

### ISSUE THREAD

**Issue by AleksandrAAV** [diadoc/diadocsdk-1c-docs#182]
Отправка документов на согласование/подпись завершается 403 ошибок ("У вас нет доступа к документу" - что это значит?). Сегодня, в 10:43, был отправлен (успешно, с первого раза), пакет, состоящий из двух неформализованных документов (у всех документов подразделение установлено одно и тоже, организация/контрагент - такие же). В чем может быть ошибка?
Документы отправляются идентичные.

![screenshot_1](https://user-images.githubusercontent.com/18366340/33164373-83846392-d043-11e7-8922-c5dc093a6d63.png)

**Comment by GilimkhanovDenis** [comment]
Вопросы связанные с ошибами при работе в модуле рекомендуется решать через техподдержку Диадок (тел. 8-800-500-10-18)
