### ISSUE TITLE
Ошибка подключения внешней компоненты

### ISSUE THREAD

**Issue by AleksandrAAV** [diadoc/diadocsdk-1c-docs#183]
Обновил внешнюю библиотеку  (на скрине версия).
Теперь не то что бы не отправляет документы, а даже не подключается ...
Вы ее вообще тестировали?

ПутьКМакету - путь к макету (двоичные данные)

НачатьУстановкуВнешнейКомпоненты(Новый ОписаниеОповещения("ИнициализацияКомпонентыЗавершение", ОбменДИАДОККлиент, СтруктураДействий), ПутьКМакету);

ПодключитьВнешнююКомпоненту(ПутьКМакету, "DiadocAPI", ТипВнешнейКомпоненты.COM)

![screenshot_2](https://user-images.githubusercontent.com/18366340/33170849-ee8eebb4-d05a-11e7-937c-ed0306b4cfaf.png)

**Comment by AleksandrAAV** [comment]
Методом тыка и костылей была худо бедно зарегистрирована, но это не исключает ошибку в компоненте. Соединение появилось, но все-равно при попытке отправки документов на подписание возникает ошибка 403 ("У вас нет доступа к документу") - какой еще доступ нужен? По какой причине ранее два таки же документа ушил на подпись, а последующие нет?

**Comment by GilimkhanovDenis** [comment]
вопрос по ошибке есть в #182 . Этот Issue закрываю
