### ISSUE TITLE
Ошибка в отправке Акта о выполнении работ в формате 552-го приказа ФНС

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#184]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.19.1.282.

Обнаружили следующие странности:

1. 
В документации к Акту о выполнении работ в формате 552-го приказа ФНС указано:
![default](https://user-images.githubusercontent.com/33707226/33193201-ad0eafe0-d112-11e7-89f5-9dad635c8a96.png)
![default](https://user-images.githubusercontent.com/33707226/33193207-b9bb8966-d112-11e7-94d8-22b524132355.png)

Видно, что все показатели сумм, количеств и т.п. указаны как "**(число c плавающей точкой, чтение/запись)**".

Однако, на самом деле в реальных объектах соответствующих типов все эти поля указаны как строковые:
![default](https://user-images.githubusercontent.com/33707226/33193259-1e236d6a-d113-11e7-80cd-493a1a069521.png)
![default](https://user-images.githubusercontent.com/33707226/33193296-50c96814-d113-11e7-94fd-2d00322d9034.png)

Т.е. тут явное расхождение документации и реального состояния объекта!

**Кстати, точно такое же расхождение у документа типа Торг-12 в формате 551-го приказа ФНС! Там также в документации все числовые поля указаны как "(число c плавающей точкой, чтение/запись)", но в объекте по факту указаны как строки!**

И это приводи нас к следующему пункту:

2.
Если создать Торг-12 551-го приказа ФНС с, например, таким составом (целые числа):
![default](https://user-images.githubusercontent.com/33707226/33193391-fb796f34-d113-11e7-896f-da3646dd733e.png)
то он нормально создастся и отправится получателю.

Если создать Торг-12 551-го приказа ФНС с, например, таким составом (значения с копейками):
![default](https://user-images.githubusercontent.com/33707226/33193425-3252fb10-d114-11e7-8d44-87a14e5cdf0f.png)
то он также нормально создастся и отправится.

НО!
Если создать Акт в формате 552-го приказа с таким составом (целые числа):
![default](https://user-images.githubusercontent.com/33707226/33193448-65332640-d114-11e7-8e21-cf960fe074f1.png)
![default](https://user-images.githubusercontent.com/33707226/33193456-7432135e-d114-11e7-8c23-1ba6d80d2aec.png)
то он нормально создастся и отправиться получателю.

А вот если создать такой же акт с таким составом ((значения с копейками):
![default](https://user-images.githubusercontent.com/33707226/33193470-91fa46ea-d114-11e7-9cd4-02f73628d3b4.png)
![default](https://user-images.githubusercontent.com/33707226/33193482-a6e66944-d114-11e7-8d7b-5f78c2d7e8e7.png)

То при попытке отправки будет выдана ошибка:

_Ошибка при получении значения атрибута контекста (Result): Произошла исключительная ситуация (PackageSendTaskAsyncResult.get_Result): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid generated title:
Line: 36, Position: 20: The 'СтУчНДСИт' attribute is invalid - The value '18,1' is invalid according to its datatype 'Decimal' - The string '18,1' is not a valid Decimal value.
Line: 36, Position: 81: The 'СтБезНДСИт' attribute is invalid - The value '15,34' is invalid acc_

и документ не создастся!

**Т.е. при формировании акта в котором суммы указаны с копейками у вас выполняется какая-то внутренняя проверка или преобразование, которое не пропускает нецелые значения. При этом точно такие же значения в Торг-12 (да и в остальных документах) нормально пропускаются и документы успешно создаются.**

Вопросы:
А что это такое - ошибка в акте? Или наоборот - в остальных документах не срабатывает какая-то нужная проверка?

Хотелось бы, чтобы такое странное поведение было бы приведено в соответствие с поведением остальных документов. Также хотелось бы, чтобы в документации были указаны актуальные типы полей объектов, соответствующие реальному состоянию объектов.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
ответ был дан в рамках обращения в техподдержку №14672280
на новых версиях не воспроизводится
