### ISSUE TITLE
Ошибка в отправке неформализованного договора (Contract) в пакете документов

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#185]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.19.1.282.

Заметили, что в новой версии неправильно работает функция **PackageSendTask.AddDocumentFromFile**.

Суть проблемы:
Ранее при выполнении этой функции для всех не формализованных документов в объекте возвращаемого результата - объекте документа на отправку **было автоматом уже заполнено поле FileName**. Т.е. эта функция его сама где-то у себя заполняла.

Однако, сейчас обнаружили удивительное - эта функция по-прежнему работает, как указано выше, но только если это не документ типа Договор (Contract). При добавлении документа этого типа данной функцией с параметрами: Type = "Contract" и Path = <Имя передаваемого файла> **в объекте, возвращаемом данной функцией поле FileName остается незаполненным!**

В более ранних версиях АПИ такой проблемы не было.

Хотелось бы, чтобы это явно ошибочное поведение было исправлено и при помещении в пакет на отправку документа с типом Contract в результирующем объекте было бы заполнено поле FileName, как это происходит при добавлении всех других не формализованных документов.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
ответ был дан в рамках обращения в техподдержку №14672262
на новых версиях не воспроизводится
