### ISSUE TITLE
Ошибка! Ошибка при заполнении сведений о передаче товара (TovTorgTransferInfo) в документе Торг-12 551-го приказа ФНС для исходящего документа

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#186]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.19.1.282.

При тестировании отправки исходящих Торг-12 551-го приказа ФНС заметили грубую ошибку в поведении АПИ при заполнении полей структуры TovTorgTransferInfo.

Суть ошибки:
При вызове для структуры TovTorgTransferInfo метода AddStructedAdditionalInfo для добавления элементов в коллекцию StructedAdditionalInfos на самом деле добавляются элементы **в коллекцию Waybills**! Затем туда совершенно спокойно, без ошибок, добавляются данные по доп. инфо в парах <Key, Value> типа StructedAdditionalInfo (в дополнение в уже имеющимся в коллекции парам <DocumentNumber, DocumentDate> типа Waybill!).

Затем документ с таким "забавным" наполнением спокойно и без ошибок отправляется. А затем и в исходящих, и во входящих у такого документа и коллекция Waybills, и коллекция StructedAdditionalInfos - пустые!

Пример (скрины из отладчика 1С):

1. Сформировали данные документа и уже добавили в Waybills данные по транспортным накладным:

![default](https://user-images.githubusercontent.com/33707226/33246791-a09b6fc4-d364-11e7-9e6b-5b5e7c135814.png)

2. А теперь пробуем добавить поля в StructedAdditionalInfos 

До вызова метода AddStructedAdditionalInfo:
![default](https://user-images.githubusercontent.com/33707226/33246831-2ebc65ce-d365-11e7-9145-1ebbf2992659.png)

После вызова:
![default](https://user-images.githubusercontent.com/33707226/33246919-e0970204-d365-11e7-8e78-9d162b15dbe8.png)

**Видно, что метод AddStructedAdditionalInfo добавил элемент типа StructedAdditionalInfo в коллекцию элементов типа Waybill! Затем они прекрасно заполнились, и получилась какая-то дикая смесь объектов разных типов в одной коллекции.**

Затем, как я писал ранее, такой документ прекрасно и без ошибок отправляется, но после формирования документа, при его получении, что в ящике исходящих, что в ящике входящих - в нем пусто и в коллекции Waybills, и в коллекции StructedAdditionalInfos!

Нам представляется, что это грубая ошибка в поведении кода компоненты! Надеемся, что в ближайшем релизе это ошибочное поведение будет исправлено.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
ответ был дан в рамках обращения в техподдержку №14672232
на новых версиях не воспроизводится
