### ISSUE TITLE
ВНИМАНИЕ!!! Ошибка!!! Ошибка при заполнении состава документа Торг-12 551-го приказа ФНС. Не заполняется колонка ставки НДС!

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#187]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.19.1.282.

При тестировании работы с новым документом Торг-12 в формате 551-го приказа ФНС заметили грубую ошибку.

Суть ошибки:

**При формировании данных состава документа поле Ставки НДС (TaxRate) корректно заполняется. Затем документ отправляется без ошибок. После чего и у отправителя, и у получателя в составе документа вместо заданной ставки НДС оказывается установленной ставка "без НДС".**

Пример:

Заполнение строки состава документа перед его формированием и отправкой:
![default](https://user-images.githubusercontent.com/33707226/33249298-90078e70-d375-11e7-9c2e-6b5e48045654.png)
Видно, что по позиции установлена ставка 18%.

Отправили документ. Получаем и смотрим - а что же в составе:
![default](https://user-images.githubusercontent.com/33707226/33249341-c26b492e-d375-11e7-8f1a-6c63db55ab6d.png)
Видно, что поле TaxRate поменяло значение, и вместо ставки 18% там теперь фигурирует ставка "без НДС".

Надеемся, что эта ГРУБАЯ ошибка будет исправлена в ближайшее время.

Спасибо

**Comment by JohnSergeev** [comment]
Дополнительная информация:
Начали приходить документы Торг-12 от поставщиков в формате 551-го приказа.
С ними такая же проблема:

На печатной форме ставка НДС есть:
![default](https://user-images.githubusercontent.com/33707226/33462723-f4041832-d684-11e7-8bdd-63ec69b38626.png)

В XML документе ставка НДС есть:
![default](https://user-images.githubusercontent.com/33707226/33462917-2b746e42-d686-11e7-8e95-84791b162b62.png)

Но при получении данных состава через АПИ - **ставки НДС нет!**
![default](https://user-images.githubusercontent.com/33707226/33462941-496a7590-d686-11e7-8433-254896438c7d.png)

Пожалуйста, прореагируйте как-то на это сообщение. Это же явная ошибка в работе АПИ!
Спасибо.

**Comment by GilimkhanovDenis** [comment]
исправлено в новом релизе комопненты http://diadocsdk-1c.readthedocs.io/ru/latest/feed/bugs_5_19_3.html
