### ISSUE TITLE
Ошибка! Мусорные случайные значения в новом поле УКД (OriginalInvoiceRevisionDate)

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#188]
Добрый день.
Работаем через внешнюю x64 com компоненту для 1С. Своя реализация работы с вашим АПИ. Версия АПИ 5.19.1.282.

В этой последней версии вы добавили в УКД новые поля:
![default](https://user-images.githubusercontent.com/33707226/33254791-3b8b6972-d396-11e7-9339-d41bbf219917.png)

При получении объекта УКД в нем действительно есть все эти поля, но при этом поле OriginalInvoiceRevisionDate ведет себя крайне странным образом!

**В нем откуда-то берутся разные значения при каждом получении документа. При этом дата всегда стоит на 6198 год (что это вообще такое?!), а вот месяцы, дни и время постоянно пляшут туда-сюда случайным образом.**

В один момент там такое:
![default](https://user-images.githubusercontent.com/33707226/33254974-24dbf04c-d397-11e7-8658-9617f6ac64a0.png)

А через пару минут, например, такое:
![default](https://user-images.githubusercontent.com/33707226/33255045-69b02260-d397-11e7-9e5b-7613bb13c50b.png)
 (что интересно, время прыгнуло назад).

И так далее - в этом поле почти каждый раз оказывается какое-то случайное значение из далекого будущего.

Полное ощущение, что это какой-то датчик случайных времен! Похоже, что где-то есть ошибка и в это поле попадает что-то странное, откуда-то из неправильного места или даже участка памяти. Да и сама дата от 6198 года тоже очень смущает...

Объясните, пожалуйста, в чем суть такого поведения этого поля? И, если это ошибка, то исправьте ее, пожалуйста.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Исправлено в  версии компоненты 5.21.10.342
