### ISSUE TITLE
Ошибка при подписании документа

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#190]
##100[Ошибка сервера Диадок]code:500, HTTP error: The server encountered an internal error or misconfiguration and was unable to complete your request

Отправляю из 1с документ на подписание  в контексте тестовой организации, работаю по ключу разработчика основной (рабочей) организации: 
![image](https://user-images.githubusercontent.com/3480769/33477990-d387f240-d698-11e7-8455-5cf905a1ba1d.png)

Параметры replySendTask
![image](https://user-images.githubusercontent.com/3480769/33478191-7af8ee80-d699-11e7-9fbc-bcc43c3823bc.png)

Параметры подписантов Signers:

![image](https://user-images.githubusercontent.com/3480769/33478212-8f5934f2-d699-11e7-8249-219284576035.png)

Прошу уточнить, что делаю не так.

**Comment by MikeFilimonov** [comment]
![image](https://user-images.githubusercontent.com/3480769/33479873-c68478dc-d69f-11e7-9d87-43c2f86ded1c.png)
Вот такая ошибка при получении тестового сертификата для подписания

**Comment by MikeFilimonov** [comment]
Вот сертификат тестовой организации для подписи: 

![image](https://user-images.githubusercontent.com/3480769/33482127-a23450a2-d6a8-11e7-90b5-c23fae216503.png)

Как на тестовых организациях (или документах отладить  механизм подписи из 1с)?

**Comment by GilimkhanovDenis** [comment]
Данная ошибка присутствовала в версии компоненты 5.19.4.289. На свежих версиях не воспроизводится.
