### ISSUE TITLE
Как получить список актуальных сертификатов для подписания из 1с 

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#191]
На сегодня в рабочей организации 6231000023 есть 3 сертификата с активным сроком действия для подписания документов.

Метод GetPersonalCertificate объекта DiadocInvoiceAPI возвращает список неактивных сертифкатов при передаче в  метод параметра  Истина.
Ни одного из 3 активных в возвращаемом списке нет. 
Прошу пояснить, что  я делаю не так и каким образом получить сертификаты для получения на их основе отпечатка для подписания  входящего документа из 1с.

Код прилагаю:

КорневойЭлементCOM = Новый ComОбъект("Diadoc.DiadocClient");
ПолныйСписокСертификатов = КорневойЭлементCOM.GetPersonalCertificates();

**Comment by denver069** [comment]
Сертификаты точно установлены в хранилище текущего пользователя а не компьютера?

**Comment by MikeFilimonov** [comment]
Не уверен,  что  они установлены в хранилище тек.пользователя.Можете уточнить,  как в этом убедиться?

**Comment by denver069** [comment]
Попробуйте выполнить `КорневойЭлементCOM.GetPersonalCertificates(Ложь)`, если сертификаты будут получены успешно это будет означать то, что они установлены в хранилище компьютера.
