### ISSUE TITLE
Заполнение полей объекта UniversalTransferDocumentBuyerTitle

### ISSUE THREAD

**Issue by OlgaArtamonova** [diadoc/diadocsdk-1c-docs#195]
Добрый день!
Можно образец заполнения полей Creator, CreatorBase, OperationCode и OperationContent? Может быть есть какие-то функции для их формирования?

Пытаюсь подписать акт со стороны покупателя
https://diadoc.kontur.ru/184f66df-afda-4192-88de-b14002842176/Document/Show?letterId=0a6672e7-9658-4a79-bb6d-a97ac7a87f2d&documentId=a5db1483-8d62-406b-af26-cfae536b7771

**Comment by GilimkhanovDenis** [comment]
Заполняется строками в соответствие с форматом. Так как это Акт в формате УПД, то заполнена должна быть структура: https://diadocsdk-1c.readthedocs.io/ru/latest/ReplySendTask.html?highlight=UtdBuyerContent. Методов генерации этих полей нет.
