### ISSUE TITLE
Как получить список услуг из акта и товаров из УПД?

### ISSUE THREAD

**Issue by vlapenkov** [diadoc/diadocsdk-1c-docs#196]
Доброго времени суток! Есть такой код который получает документы. А дальше нужны работы , количество и сумма.
DocumentsTask.Category = "XmlAcceptanceCertificate.Inbound";
DocumentList = DocumentsTask.GetDocuments();
сч= 0;
Пока сч < DocumentList.Count Цикл
  Document = DocumentList.GetItem(сч);
  Сообщить("Акт №" + Document.DocumentNumber + " от " + Document.DocumentDate);
  сч = сч + 1;
КонецЦикла;

**Comment by GilimkhanovDenis** [comment]
DocumentsTask.GetDocuments() Возвращается коллекцию объектов [Document](http://diadocsdk-1c.readthedocs.io/ru/latest/Document.html)
У Document можно вызвать метод GetContent(). В зависимости от типа документа вернётся или [UtdSellerContent](http://diadocsdk-1c.readthedocs.io/ru/latest/UtdSellerContent.html) или [AcceptanceCertificateSellerContent](http://diadocsdk-1c.readthedocs.io/ru/latest/AcceptanceCertificateSellerContent.html). В зависимости от типа контента, список работ будет находиться или в поле [InvoiceTable](http://diadocsdk-1c.readthedocs.io/ru/latest/InvoiceTable.html).[Items](http://diadocsdk-1c.readthedocs.io/ru/latest/ExtendedInvoiceItem.html) или в Items[](http://diadocsdk-1c.readthedocs.io/ru/latest/AcceptanceCertificateItem.html)
