### ISSUE TITLE
Искажение текста неформализованного документа, созданного из текстового файла

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#197]
В тестовой организации(О1)  в ЛК "Диадок" создал неформализованный док. на основе текстового файла. (см. приложение "Исходный файл").
Отправил в рабочую организацию(О2) это документ с запросом на подписание. 
При загрузке вложения этого документа в 1с О2  файл вызвал метод GetPrintForm(), он вернул файл с расширением .txt, который фактически является PDF.

Прошу пояснить, это баг или фича?

[afterSending_20171220_uploaded.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/1575463/afterSending_20171220_uploaded.txt)
[beforeSending__20171220.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/1575464/beforeSending__20171220.txt)
[Converted2PDFAfterSending_20171220.pdf](https://github.com/diadoc/diadocsdk-1c-docs/files/1575465/Converted2PDFAfterSending_20171220.pdf)

**Comment by GilimkhanovDenis** [comment]
Исправлено в  версии компоненты 5.21.10.342
