### ISSUE TITLE
Ошибка при получении организации по id

### ISSUE THREAD

**Issue by yadimetrio** [diadoc/diadocsdk-1c-docs#198]
При выполнении 
```	//создаем корневой элемент COM-объекта
	ДиадокАпи = Новый ComОбъект("Diadoc.DiadocClient");
	
	//Задаем параметры подлючения к серверу
	ДиадокАпи.ApiClientId = КлючРазработчика();
	ДиадокАпи.ServerUrl   = "https://diadoc-api.kontur.ru:443";
	
	// Получить сертификаты пользователя
	Certificates = ДиадокАПИ.GetPersonalCertificates();
	
	// Прочитать список доступных сертификатов и выбрать нужный.
	СертификатДляАвторизации = Certificates.GetItem(0);
	
	ДиадокСоединение = ДиадокАПИ.CreateConnectionByCertificate(СертификатДляАвторизации.Thumbprint);
	
	BoxId 			 = ИдентификаторЯщикаДиадок();
	OrganizationList = ДиадокСоединение.GetOrganizationById(BoxId);
```
На последней строке получаем ошибку: "Произошла исключительная ситуация (DiadocConnection.GetOrganizationById): Не указанны значения инициализирующих параметров COM объекта"
Все это выполняется на тестовой базе. Крипто про установлен, контейнер закрытого ключа тоже. Соединение по сертификату проходит. Но доступных по сертификату организаций нет. На рабочей базе все работает. Ключ разработчика может влиять на доступность организаций по сертификату?

**Comment by etalipov** [comment]
Добрый день!
Ключ разработчика не влияет на доступность организации по сертификату.
Похоже, что дело в регистрации внешней компоненты. Проверьте, пожалуйста, чем у вас заполняются "ДиадокСоединение" и "ДиадокАпи". Попробуйте перерегистрировать внешнюю компоненту.

**Comment by yadimetrio** [comment]
Добрый день.

Забыл описать сюда. Разобрались. Проблема была в сертификате, было два одинаковых, но с разными отпечатками и в апи передавали не верный. Задачу можно закрывать.
