### ISSUE TITLE
Сертификаты не видно в GetPersonalCertificates

### ISSUE THREAD

**Issue by 1cAPI** [diadoc/diadocsdk-1c-docs#199]
Добрый день. 1С серверная. Компонента COM-компонента, для 64-х битных приложений - 5.20.0.293. Сертификат добавили на сервере в личные через реестр. COMобъект создали, используя ключ разработчика подключаемся, подключение проходит, TestConnection тоже true, но метод GetPersonalCertificates(false) показывает 1 сертификат, но какой-то вообще левый - без привязки к организации, а сертификата диадока нет. Метод CreateConnectionByLogin(login,pass) показывает нашу организацию, но авторизации по сертификату не произошло (Certificate пусто). Что сделать, чтобы сертификат появился здесь GetPersonalCertificates?

**Comment by GilimkhanovDenis** [comment]
Необходимо более детально посмотреть, что происходит при запросе сертификатов и почему компонента их может не видеть. Попробуйте обратиться в техподдержку (тел. 8-800-500-10-18)
