### ISSUE TITLE
методы COM для документа входящий счет-фактура

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#20]
Сделана интеграция со своей конфигурацией 1С 8.3. 
Подскажите, пожалуйста, входящий счет-фактура загружен в 1С есть id документа "76d83345-bc8d-4abb-89f6-a4e3a2f394bca6568f2e-6966-48f1-a1db-fa508d3ac3ab".
Какими методами COM можно:
- запросить аннулирование,
- подписать извещение о получении документа.

С остальными видами документа все работает, с эти видом после обновления не могу разобраться.
Помогите, пожалуйста.

**Comment by denver069** [comment]
Запросить аннулирование можно методом [SendRevocationRequest](http://diadocsdk-1c.readthedocs.io/ru/latest/SendRevocationRequest.html).
Для обработки извещений используйте объект [ReceiptGenerationProcess](http://diadocsdk-1c.readthedocs.io/ru/latest/ReceiptGenerationProcess.html)
