### ISSUE TITLE
Не получается подписать Акт через API

### ISSUE THREAD

**Issue by ivtroitskiy** [diadoc/diadocsdk-1c-docs#200]
Работаем из 1с с апи через com компонент.
![syjxekf 1](https://user-images.githubusercontent.com/13430286/34411571-41e031d8-ebf9-11e7-820b-86997aafa4bd.png)

Процедура подписи акта, первый вариант: 

```
document = Organization.GetDocumentById(СписокПараметров.id_doc);
ReplySendTask = document .CreateReplySendTask("AcceptDocument");
UTDBuyerContent = ReplySendTask.Content;
UTDBuyerContent.AcceptanceDate = ТекущаяДата();
UTDBuyerContent.DocumentCreator = "DiadocCreator";
UTDBuyerContent.OperationContent = "OperationContent";
Signer = UTDBuyerContent.AddSigner();
Signer.BoxId = Organization.Id;
Signer.CertificateThumbprint = Organization.Certificate.Thumbprint;
ReplySendTask.Send();

```
Получаем ошибку:

> Error calling context method (Send): An exception has occurred (ReplySendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
> Schematron validation: Schematron validation failed
> /AcceptanceCertificate552BuyerTitle/Signers/SignerReference: @Inn is required
> /AcceptanceCertificate552BuyerTitle/Signers/SignerReference: SignerDetails not found in DB for boxId=2ce0a946-fe10-4979-b097-db65eb74d9d

В тех. поддержке мне сказали:

> Пытаются подписать входящий акт 552, но не заполнены параметры подписанта для 551/552.
> 
> В вебе ДД их заполнить нельзя, поэтому их нужно заполнить при отправке ReplySendTask. Они заполняются в объекте ExtendendSigner, свойство SignerDetails. Эти настройки сохранятся на сервере ДД и в дальнейшем достаточно будет заполнять только BoxId и CertificateThumbprint.

и посоветовали использовать метод [http://diadocsdk-1c.readthedocs.io/ru/latest/GetExtendedSignerDetails2.html](url) который имеет входящие параметры (CertificateThumbprint, DocTitleType)  для проверки, есть сохраненные реквизиты подписанта или нет. Метод я использовал следующим образом:
`Organization.GetExtendedSignerDetails(Organization.Certificate.Thumbprint,"AccCert552Buyer")`
и получал ошибку:

> Error calling context method (GetExtendedSignerDetails)

Возможно у нас какая-нибудь старая версия библиотеки? и убрав 2 из урла описания метода, нашел описание этого же метода с другими параметрами: (CertificateThumbprint, IsSeller, forCorrection) и который выполнился
Благодаря ему я узнал, что реквизиты подписанта на сервере все таки есть (но для какого типа документа?) , поэтому решил заполнить значения вручную:
```
SignerDetails = Organization.GetExtendedSignerDetails(Organization.Certificate.Thumbprint, False, False);
Signer.SignerDetails.Surname = SignerDetails.Surname;
Signer.SignerDetails.FirstName = SignerDetails.FirstName;
Signer.SignerDetails.Patronymic = SignerDetails.Patronymic;
Signer.SignerDetails.JobTitle = SignerDetails.JobTitle;
Signer.SignerDetails.Inn = SignerDetails.Inn;
Signer.SignerDetails.SignerType = SignerDetails.SignerType;
Signer.SignerDetails.OrganizationName  = SignerDetails.OrganizationName;
Signer.SignerDetails.Powers = SignerDetails.Powers;
Signer.SignerDetails.Status = SignerDetails.Status;
Signer.SignerDetails.PowersBase = SignerDetails.PowersBase;
```

Документ подписался.

Решил проверить, сохранили ли данные подписанта на сервере, я вернул первоначальный код, с указанием сертификата и boxId, но при попытке подписать следующий акт, снова получил ошибку.
Уважаемые разработчики, что я делаю неправильно?

**Comment by etalipov** [comment]
Добрый день!

1. При подписании документа в формате 551/552 впервые, следует закрепить за используемым сертификатом параметры подписанта на сервере Диадок.
Для того, чтобы закрепить параметры подписанта, первое подписание документа нужно совершать со следующими параметрами (на примере вашего кода): 
Signer = UTDBuyerContent.AddSigner();
Signer.SignerDetails.Surname = SignerDetails.Surname;
Signer.SignerDetails.FirstName = SignerDetails.FirstName;
Signer.SignerDetails.Patronymic = SignerDetails.Patronymic;
Signer.SignerDetails.JobTitle = SignerDetails.JobTitle;
Signer.SignerDetails.Inn = SignerDetails.Inn;
Signer.SignerDetails.SignerType = SignerDetails.SignerType;
Signer.SignerDetails.OrganizationName  = SignerDetails.OrganizationName;
Signer.SignerDetails.Powers = SignerDetails.Powers;
Signer.SignerDetails.Status = SignerDetails.Status;
Signer.SignerDetails.PowersBase = SignerDetails.PowersBase;

2. Для того, чтобы проверить, сохранились ли эти параметры на сервере ДД, используйте метод GetExtendedSignerDetails2 (обратите внимание на цифру 2 в конце метода):
Organization.GetExtendedSignerDetails2(Organization.Certificate.Thumbprint,"AccCert552Buyer")

3. Когда параметры подписанта 551/552 сохранились на сервере ДД, при подписании документов можно использовать:
Signer = UTDBuyerContent.AddSigner();
Signer.BoxId = Organization.Id;
Signer.CertificateThumbprint = Organization.Certificate.Thumbprint;

таким образом, первоначально закрепленные за сертификатом параметры подтянутся в запрос с сервера ДД.
Параметры подписанта закрепляются за связкой boxId и Thumbprint. Т.е. если у вас меняется сертификат, то параметры подписанта нужно перезаполнять.

**Comment by ivtroitskiy** [comment]
1.  не могу найти отличия от моего кода, второй фрагмент я привет без купюр, очевидно чтоб перед этими строками следует 
`Signer = UTDBuyerContent.AddSigner();`

2. История правок статьи меня успокоила, проблема не в моих глазах :)

3. Не сохраняются, в том и проблема! Отправлял как вы рекомендуете в пункте 1.

**Comment by etalipov** [comment]
Добрый день!

1. Пример вашего кода:
SignerDetails = Organization.GetExtendedSignerDetails(Organization.Certificate.Thumbprint, False, False);
Signer.SignerDetails.Surname = SignerDetails.Surname;
Signer.SignerDetails.FirstName = SignerDetails.FirstName;
Signer.SignerDetails.Patronymic = SignerDetails.Patronymic;
Signer.SignerDetails.JobTitle = SignerDetails.JobTitle;
Signer.SignerDetails.Inn = SignerDetails.Inn;
Signer.SignerDetails.SignerType = SignerDetails.SignerType;
Signer.SignerDetails.OrganizationName  = SignerDetails.OrganizationName;
Signer.SignerDetails.Powers = SignerDetails.Powers;
Signer.SignerDetails.Status = SignerDetails.Status;
Signer.SignerDetails.PowersBase = SignerDetails.PowersBase;

Предлагаемый пример:
Signer = UTDBuyerContent.AddSigner();
Signer.SignerDetails.Surname = SignerDetails.Surname;
Signer.SignerDetails.FirstName = SignerDetails.FirstName;
Signer.SignerDetails.Patronymic = SignerDetails.Patronymic;
Signer.SignerDetails.JobTitle = SignerDetails.JobTitle;
Signer.SignerDetails.Inn = SignerDetails.Inn;
Signer.SignerDetails.SignerType = SignerDetails.SignerType;
Signer.SignerDetails.OrganizationName  = SignerDetails.OrganizationName;
Signer.SignerDetails.Powers = SignerDetails.Powers;
Signer.SignerDetails.Status = SignerDetails.Status;
Signer.SignerDetails.PowersBase = SignerDetails.PowersBase;

Различие в отсутствии метода на получение параметров подписанта:
SignerDetails = Organization.GetExtendedSignerDetails(Organization.Certificate.Thumbprint, False, False);

Т.к. на сервере параметры подписанта 551/552 ещё не сохранились, следовательно, и получать с сервера нечего. :) 
Поэтому, уберите строку на получение параметров подписанта с сервера (GetExtendedSignerDetails) из вашего кода и повторите, пожалуйста, отправку документа.

**Comment by ivtroitskiy** [comment]
В предлагаемом примере не определена переменная SignerDetails, программа выдала ошибку.

Organization.GetExtendedSignerDetails(Organization.Certificate.Thumbprint, False, False) возвращает результат, содержащий данные подписанта.

**Comment by etalipov** [comment]
Если я правильно понимаю ваш код, то здесь:
SignerDetails = Organization.GetExtendedSignerDetails(Organization.Certificate.Thumbprint, False, False);
вы определяете переменную SignerDetails. 
Используя метод GetExtendedSignerDetails для определения переменной, вы заполняете переменную данными подписанта, взятыми с сервера Диадок. 
И далее подставляете полученные данные для заполнения свойства Signer:
Signer.SignerDetails.Surname = SignerDetails.Surname;
Signer.SignerDetails.FirstName = SignerDetails.FirstName;
Signer.SignerDetails.Patronymic = SignerDetails.Patronymic;
Signer.SignerDetails.JobTitle = SignerDetails.JobTitle;
Signer.SignerDetails.Inn = SignerDetails.Inn;
Signer.SignerDetails.SignerType = SignerDetails.SignerType;
Signer.SignerDetails.OrganizationName = SignerDetails.OrganizationName;
Signer.SignerDetails.Powers = SignerDetails.Powers;
Signer.SignerDetails.Status = SignerDetails.Status;
Signer.SignerDetails.PowersBase = SignerDetails.PowersBase;

но возвращаемый сервером результат на запрос:
Organization.GetExtendedSignerDetails(Organization.Certificate.Thumbprint, False, False)
не является данными подписанта для AccCert552Buyer, т.к. у метода GetExtendedSignerDetails нет возможности указать для какого типа документа вам нужны параметры подписанта (УПД/УКД/551/552), т.е. нет возможности указать, что вам нужны для 552. Из этого следует, что вы заполнили переменную SignerDetails данными, не подходящими для формата 552 приказа ФНС.

У второй версии метода GetExtendedSignerDetails2 есть возможность указать тип документа, но если вы попытаетесь определить переменную SignerDetails  так: 
SignerDetails =  Organization.GetExtendedSignerDetails2(Thumbprint, "AccCert552Buyer ");
то наверняка получите ошибку, т.к. на сервере Диадок ещё нет данных по типу документа AccCert552Buyer.

Для первого подписания документа AccCert552Buyer не нужно получать параметры подписанта с сервера Диадок, т.е. не нужно использовать методы GetExtendedSignerDetails и GetExtendedSignerDetails2, а нужно заполнить данными из вашей системы, например:
Signer = UTDBuyerContent.AddSigner();
Signer.SignerDetails.Surname = "Ivanov";
Signer.SignerDetails.FirstName = "Ivan";
Signer.SignerDetails.Patronymic = "Ivanovic";
Signer.SignerDetails.JobTitle = "Director";
Signer.SignerDetails.Inn = "1234567890";
Signer.SignerDetails.SignerType = "LegalEntity";
Signer.SignerDetails.OrganizationName = "vasilek";
Signer.SignerDetails.Powers = "PersonDocumentedOperation";
Signer.SignerDetails.Status = "SellerEmployee";
Signer.SignerDetails.PowersBase = "Doverennost";

после успешного подписания вышеуказанные данные сохранятся на сервере Диадок, и вы сможете получить их методом Organization.GetExtendedSignerDetails2(Thumbprint, "AccCert552Buyer "). Или же использовать их указав boxid и Thumbprint.

**Comment by ivtroitskiy** [comment]
Вот теперь спасибо, теперь я понял, что вы предлагаете и смогу спокойно уснуть, а завтра попробовать!
Боюсь только, что я уже так пробовал, акт подписался, но данные не сохранились. Но всё равно завтра проделаю все ещё раз, спасибо!

**Comment by ivtroitskiy** [comment]
После обновления сертификата снова столкнулся с такой же проблемой. Что сделал я:
1. при первой подписи документ явно указал реквизиты подписанта
```
Signer = UTDBuyerContent.AddSigner();
Signer.SignerDetails.Surname = "Трунов";
Signer.SignerDetails.FirstName = "Иван";
Signer.SignerDetails.Patronymic = "Викторович";
Signer.SignerDetails.JobTitle = "Главный бухгалтер";
Signer.SignerDetails.Inn = "6679104850";
Signer.SignerDetails.SignerType = "LegalEntity";
Signer.SignerDetails.OrganizationName = "vasilek";
Signer.SignerDetails.Powers = "PersonDocumentedOperation";
Signer.SignerDetails.Status = "SellerEmployee";
Signer.SignerDetails.PowersBase = "Должностные обязанности";
```
2. при второй попытке подписи указывал 
```
		Signer.BoxId = Organization.Id;
		Signer.CertificateThumbprint = Organization.Certificate.Thumbprint;
```
 и получил ошибку 

> Error calling context method (Send): An exception has occurred (ReplySendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
> /TovTorgBuyerTitle/Signers/SignerReference: @Inn is required
> /TovTorgBuyerTitle/Signers/SignerReference: SignerDetails not found in DB for boxId=2ce0a946-fe10-4979-b097-db65eb74d9de, thumbprint=550311B1BBD49AA7F94C491875F4F2EB4128757D, documentTitleType=5

3. Захотел проверить сохранились ли данные на сервере диадок, для чего вызывал функцию `Organization.GetExtendedSignerDetails2(Organization.Certificate.Thumbprint,"AccCert552Buyer")`
но выдало ошибку 

> Error calling context method (GetExtendedSignerDetails2)

**Comment by ivtroitskiy** [comment]
я решил, что передаю некорректный второй параметр, ведь в описание ошибки фигурирует TovTorg, но 
Organization.GetExtendedSignerDetails2(Organization.Certificate.Thumbprint,"TovTorg551Seller")
Organization.GetExtendedSignerDetails2(Organization.Certificate.Thumbprint,"TovTorg551Buyer")
тоже приводит к ошибке 

> Error calling context method (GetExtendedSignerDetails2)

Organization.GetExtendedSignerDetails2(Organization.Certificate.Thumbprint,"UtdSeller") отрабатывает нормально

**Comment by etalipov** [comment]
Добрый день!
В таком случае, попробуйте воспользоваться отдельными методами для установки параметров подписанта:
http://diadocsdk-1c.readthedocs.io/ru/latest/CreateSetExtendedSignerDetailsTask.html?highlight=ExtendedSigner

http://diadocsdk-1c.readthedocs.io/ru/latest/SetExtendedSignerDetailsTask.html?highlight=ExtendedSigner
