### ISSUE TITLE
Подскажите, каким методом можно получить идентификатор приглашения, при отправке

### ISSUE THREAD

**Issue by NadezhdaLunkova** [diadoc/diadocsdk-1c-docs#201]
Добрый день. Отправляю приглашения контрагентам методом CreateAcquireCounteragentTask. Пример,
"…
TrustConnectionRequest=Organization.CreateAcquireCounteragentTask(ИмяФайла);			
TrustConnectionRequest.CounteragentBoxId= CounteragentId;
TrustConnectionRequest.Inn  			= ИНН;
TrustConnectionRequest.Message 		= Комментарий;
TrustConnectionRequest.FileName 		= ПолучитьКраткоеИмяФайла(ИмяФайла);
			
Попытка
	Результат=TrustConnectionRequest.Send(); //возвращает идентификатор 
									 //организации-получателя приглашения
Исключение 
	...
КонецПопытки;
…"
Данный метод возвращает BoxId и не совсем мне подходит для последующего отслеживания состояния отправленных приглашений. Подскажите, каким методом можно получить идентификатор приглашения (документа) - DocumentId.

**Comment by GilimkhanovDenis** [comment]
Компонента не может вернуть идентификатор документа, отправленного вместе с приглашением. Можем вернуть только идентификатор организации - это ограничение метода [AcquireCounteragentResult](http://api-docs.diadoc.ru/ru/latest/http/AcquireCounteragentResult.html)

Подобные пожелания уже поступали, но сроков у задачи пока нет.
