### ISSUE TITLE
Из входящего акта не могу получить список услуг и цены

### ISSUE THREAD

**Issue by vlapenkov** [diadoc/diadocsdk-1c-docs#202]
Доброго времени суток! Есть такой акт https://diadoc.kontur.ru/54d0b467-aade-47d6-8136-a2bbe2eeb67d/Document/Show?letterId=71f0c943-b4fd-4019-b973-32a178d42bb0&documentId=3a167952-4eca-425b-878c-66f33177036d

Пока сч < DocumentList.Count Цикл
  Document = DocumentList.GetItem(сч);
  Сообщить("Акт №" + Document.DocumentNumber + " от " + Document.DocumentDate);
  cnt=Document.GetContent();
  сч = сч + 1;
КонецЦикла;
Для данного акта при обращении к cnt.InvoiceTable.Items Получаю только ComObject Count=3  и это Всё!
В issue https://github.com/diadoc/diadocsdk-1c-docs/issues/196 вы писали что **список работ будет находиться или в поле InvoiceTable.Items** , но там только их кодичество, без содержания и цен

**Comment by Sergguha** [comment]
Используйте для получения элементов коллекции метод [GetItem](http://diadocsdk-1c.readthedocs.io/ru/latest/GetItem.html). Должно получиться что-то вроде этого:

```
Пока Счет < cnt.InvoiceTable.Items.Count Цикл
	Item = cnt.InvoiceTable.Items.GetItem(Счет);
	//... обработка элемента коллекции
	Счет = Счет + 1;
КонецЦикла;
```

**Comment by GilimkhanovDenis** [comment]
Ответ был дан. закрываю
