### ISSUE TITLE
Как подписывать извещения УПД (счет-фактур).

### ISSUE THREAD

**Issue by sergro** [diadoc/diadocsdk-1c-docs#204]
Добрый день. В веб интерфейсе подпись извещений происходит автоматически. 
А как подписывать извещения используя API. 
В документации нашел объект ReceiptGenerationProcess 
(Объект предназначен запуска процесса автоматического формирования и подписания документов по регламентному документообороту счетов-фактур.)
И метод SendReceiptsAsync()  
(Формирует и подписывает документы по регламентному документообороту УПД с функцией СЧФ)
С помощью них подписываются извещения?
метод SendReceiptsAsync() подписывает только извещения или сам документ тоже?

**Comment by denver069** [comment]
Объект **ReceiptGenerationProcess** обрабатывает в фоновом режиме все необходимые извещения для всех документов ящика доступных пользователю, в том числе и для УПД с функцией СЧФ.

Метод **SendReceiptsAsync** обрабатывает в фоновом режиме все необходимые извещения только для одного конкретного документа.

**Comment by sergro** [comment]
Добрый день. Небольшое уточнение. Оба эти метода подписывают извещение у УПД только с функцией "СЧФ"? Столкнулся с ситуацией есть УПД с функцией "СЧФ ДОП". Применяю к этому документу метод SendReceiptsAsync() выскакивает ошибка метод объекта не обнаружен. После подписания документа через API статус документа меняется с InboundWaitingForRecipientSignature (документ входящий, ответная подпись, либо отказ от ее формирования еще не отправлены) на InboundNotFinished (документ входящий, документооборот не завершен). И приходится заходить через Вэб-интерфейс для того чтобы подписались извещения. Просьба помочь разобраться что я делаю не так или действительно для УПД с функцией  "СЧФ ДОП" через API извещение не получится подписать.
