### ISSUE TITLE
Можно ли найти документ по documentId

### ISSUE THREAD

**Issue by vlapenkov** [diadoc/diadocsdk-1c-docs#205]
Доброго времени суток!
У входящих УПД (UniversalTransferDocument), Акта(XmlAcceptanceCertificate) и Торг-12 
есть реквизит documentId, который видимо определяет уникальный идентификатор документа, (например db4c350c-77f4-4baa-9e31-c4a6f564b724fe3f6f31-8220-4590-a01c-25af99bced91).
**Вопрос: можно ли получить Document сразу по этому идентификатору, а не через перебор в цикле ?**

**Comment by GilimkhanovDenis** [comment]
Если идентификатор известен, то документ можно получить методом [GetDocumentById()](http://diadocsdk-1c.readthedocs.io/ru/latest/GetDocumentById.html)

**Comment by vlapenkov** [comment]
Спасибо! Проверил, работает
