### ISSUE TITLE
Можно ли получить связанную счет-фактуру по documentId из Торг-12

### ISSUE THREAD

**Issue by vlapenkov** [diadoc/diadocsdk-1c-docs#206]
Добрый день!
1.Как получить счет-фактуру из документа Торг-12 ?
2.Можно ли получить pdf этой счет-фактуры программно?
Спасибо!

**Comment by denver069** [comment]
1. Получить связанные документы можно через коллекции [Document.InitialDocumentIds](http://diadocsdk-1c.readthedocs.io/ru/latest/Document.html?highlight=InitialDocumentIds) и [Document.SubordinateDocumentIds](http://diadocsdk-1c.readthedocs.io/ru/latest/Document.html?highlight=SubordinateDocumentIds)
2. Получить печатную форму документа в формате **pdf** можно методом [Document.GetPrintForm()](http://1c-docs.diadoc.ru/ru/latest/GetPrintForm.html)
