### ISSUE TITLE
diadoc-api.kontur.ru Получить статус документа

### ISSUE THREAD

**Issue by komissarovev** [diadoc/diadocsdk-1c-docs#207]
Добрый день!

Подскажите метод diadoc-api.kontur.ru, которым можно получить статус документа (к примеру: подписан). Авторизоваться и получить token получилось.

**Comment by denver069** [comment]
Почитайте 
тут http://diadocsdk-1c.readthedocs.io/ru/latest/GetDocumentsTask.html
и тут http://diadocsdk-1c.readthedocs.io/ru/latest/Document.html

**Comment by komissarovev** [comment]
Каким методом получить объект документ? Или сначала нужно получить объект организация, а потом вызвать метод объекта организация? (если так то как получить объект организация)
У меня получилось поулчить GetMyOrganizations

**Comment by komissarovev** [comment]
Это все не то. Интеграцию настраиваю через api post, get запросы.
