### ISSUE TITLE
diadoc-api.kontur.ru - HTTP API -  GetDocument - где взять messageId?

### ISSUE THREAD

**Issue by komissarovev** [diadoc/diadocsdk-1c-docs#208]
Каким методом получить объект документ? Или сначала чтобы получить документ нужно получить объект организация, а потом вызвать метод объекта организация? (если так то как получить объект организация)
У меня получилось поулчить GetMyOrganizations

**Comment by komissarovev** [comment]
Вопрос про post и Get запросы. Нужно получить статус документа. 
Возможно вопрос про объекты не верен. Меня ввели в заблуждение ответом в предыдущей теме.
https://github.com/diadoc/diadocsdk-1c-docs/issues/207

**Comment by volodkindv** [comment]
Вам нужна эта документация по HTTP API, а не по внешней компоненте 1С:
http://api-docs.diadoc.ru/ru/latest/
Через GetDocument получаете описание документа:
http://api-docs.diadoc.ru/ru/latest/http/GetDocument.html
Внутри ищете структуры вроде "XmlTorg12Metadata", в зависимости от типа документа.
Внутри этой структуры будет BilateralDocumentStatus - похоже, это то, что вам требуется.

**Comment by komissarovev** [comment]
у меня в 1с есть:
ИдентификаторДокументаВДиадок
AtYF2YydUqquY2ves5htArJlZO5AKRKNYmgG1N1U0Ig
ИдентификаторЯщикДокументаВДиадок
2d1f65f6b08a41b890e87f60f36cd57d@diadoc.ru
в параметрах GetDocument
не пойму где взять messageId?

**Comment by volodkindv** [comment]
В модуле 1С поищите 
`	Функция Документ_2_DocumentID(Документ, DocumentType= Неопределено) Экспорт 
`
Она по ссылке на документ 1С даст вам длинную строку, которая на самом деле является объединением 2 гуидов - MessageId и DocumentId. Режете ее посередине и получаете MessageId и DocumentId для HTTP запроса.

Кстати, вам вроде предлагали модуль, который статусы документов пишет в отдельные справочники в 1С. Вы решили все-таки остаться на том, который только id документов в базу сохраняет?

**Comment by komissarovev** [comment]
![image](https://user-images.githubusercontent.com/36499475/36297171-3bca5ab4-1302-11e8-82b7-910c2b35077d.png)

получилось получить документ. Только странная кодировка. Можно ее исправить? Не нашел там тегов BilateralDocumentStatus . Статус по русски написан?

**Comment by volodkindv** [comment]
Вы получили содержимое документа (т.е. сам xml файл). В нем статуса нет и не будет - он не в содержимом, а в метаданных.
XML обычно закодирован в 1251, поскольку именно 1251 прописана в XSD от налоговой.

**Comment by komissarovev** [comment]
а как получить метаданные?
я посылаю get запрос получаю ответ 200 делаю ПолучитьТелоКакСтроку().

**Comment by volodkindv** [comment]
Покажите пример запроса, который вы выполняете, и ответа. Адрес, заголовки, тело.

**Comment by komissarovev** [comment]
https://diadoc-api.kontur.ru/V3/GetDocument?boxId=2d1f65f6b08a41b890e87f60f36cd57d@diadoc.ru&messageId=9bc68589-933f-4f66-b87c-1c8fc5a7fb75&entityId=461957eb-f32c-434c-a929-351eca424b1c

Authorization: DiadocAuth ddauth_api_client_id=хххххх,ddauth_token=ххххх
Host: diadoc-api.kontur.ru

**Comment by volodkindv** [comment]
Понятно, вам возвращается бинарный protobuf.
Перед выполнением http запроса можно настроить заголовки для получения json в ответе:

```
		Заголовки = Новый Соответствие;
		Заголовки.Вставить("Accept",		"application/json");  // без этого вернется протобуфер
		Заголовки.Вставить("Content-Type",	"application/json; charset=utf-8");  // для отправки в JSON вместо protobuf
		Заголовки.Вставить("Authorization",	"DiadocAuth ddauth_api_client_id=" + КлючАПИ + ",ddauth_token=" + Токен);

```

Для чего вам http api? Впереди у вас возникнет еще несколько десятков вопросов.

**Comment by komissarovev** [comment]
Поставили задачу сделать через http api.
Получил json. А где статус документа?)

**Comment by volodkindv** [comment]
Верно, это он.

**Comment by komissarovev** [comment]
спасибо.

**Comment by komissarovev** [comment]
а как обратиться не к http api. а к компоненте 1с api? можете пример кода дать или куда посмотреть?

**Comment by denver069** [comment]
Читайте документацию http://1c-docs.diadoc.ru/ru/latest/Document.html

**Comment by mavDev** [comment]
> В модуле 1С поищите
> ` Функция Документ_2_DocumentID(Документ, DocumentType= Неопределено) Экспорт `
> Она по ссылке на документ 1С даст вам длинную строку, которая на самом деле является объединением 2 гуидов - MessageId и DocumentId. Режете ее посередине и получаете MessageId и DocumentId для HTTP запроса.
> 
> Кстати, вам вроде предлагали модуль, который статусы документов пишет в отдельные справочники в 1С. Вы решили все-таки остаться на том, который только id документов в базу сохраняет?

В общем для получения ИдентификаторДокументаВДиадок нужно сложить MessageId+EntityId и вызвать метод "КонвертироватьГуидВЧисло64"

ПолучитьМодульПрог("Модуль_Логика_РаботаСBase64").КонвертироватьГуидВЧисло64("bb01d4fb-6640-4c26-85d1-318370870bd1cd4628f1-2bb6-4080-9aba-7bf07b3d1eea")

**Comment by miklnuton-art** [comment]
> > В модуле 1С поищите
> > `Функция Документ_2_DocumentID(Документ, DocumentType= Неопределено) Экспорт`
> > Она по ссылке на документ 1С даст вам длинную строку, которая на самом деле является объединением 2 гуидов - MessageId и DocumentId. Режете ее посередине и получаете MessageId и DocumentId для HTTP запроса.
> > Кстати, вам вроде предлагали модуль, который статусы документов пишет в отдельные справочники в 1С. Вы решили все-таки остаться на том, который только id документов в базу сохраняет?
> 
> В общем для получения ИдентификаторДокументаВДиадок нужно сложить MessageId+EntityId и вызвать метод "КонвертироватьГуидВЧисло64"
> 
> ПолучитьМодульПрог("Модуль_Логика_РаботаСBase64").КонвертироватьГуидВЧисло64("bb01d4fb-6640-4c26-85d1-318370870bd1cd4628f1-2bb6-4080-9aba-7bf07b3d1eea")

Подскажите, сейчас похожая задача. Использую модуль для старой версии УТ 10.3. ИдентификаторДокументаВДиадок  хранится в РС ЗначенияСвойствОбъектов для каждого документа.


Через GetDocuments получаю список документов, дальше хочу понять с чем каждый из них сопоставлен у нас в системе1С, но не могу понять как реквизиты гуид соотнести с ИдентификаторДокументаВДиадок  в регистре, пробовал следующее:

1) сложить СтрокаКодирования =  MessageId+EntityId. 
Далее преобразовать 
ДвоичныеДанныеСтроки = ПолучитьДвоичныеДанныеИзСтроки(СтрокаКодирования);
СтрокаBase64 = Base64Строка(ДвоичныеДанныеСтроки);

Полученное значение не соотносится с ИдентификаторДокументаВДиадок  , там 43 символа.
2)  Искал Документ_2_DocumentID, не нашел такой функции в модуле
3) Задавал вопрос в поддержку, диадок говорит это платные консультации

Может кто выручит как соотнести реквизиты документа полученные по АПИ, со значением, которое при ручном сопоставлении хранится в регистре. Логику трансформации пока не понял.

**Comment by GilimkhanovDenis** [comment]
@miklnuton-art Если вопрос про идентификаторы документа в современном модуле, то  поищите ответ [здесь](https://github.com/diadoc/diadoc1cpro-docs).
Если вопрос про модуль "Стандарт", то он уже несколько лет снят с поддержки - вряд ли кто-то ответит про него что-то отличное от выше описанного.

И увы, это вопрос не про компоненту саму по себе, поэтому не сможем ничего дополнительно подсказать

**Comment by GilimkhanovDenis** [comment]
Добавлю только, что код модуля, что старого, что современного открыт и, возможно, где-нибудь в построении списка документов на отправку или чём-то подобном можно поотлаживаться и посмотреть что там с идентификаторами происходит

**Comment by miklnuton-art** [comment]
> [@miklnuton-art](https://github.com/miklnuton-art) Если вопрос про идентификаторы документа в современном модуле, то поищите ответ [здесь](https://github.com/diadoc/diadoc1cpro-docs). Если вопрос про модуль "Стандарт", то он уже несколько лет снят с поддержки - вряд ли кто-то ответит про него что-то отличное от выше описанного.
> 
> И увы, это вопрос не про компоненту саму по себе, поэтому не сможем ничего дополнительно подсказать

Модуль современный https://support.kontur.ru/1s/41562-informaciya_ob_obnovleniyax_modulya_diadok_pro. 4.54.3.

Я хочу понять логику как реализовано в модуле сопоставление документов. Насколько я понял он преобразует MessageId (36 символов) и EntityId (36 символов) в значение свойства для документа ИдентификаторДокументаВДиадок, который содержит 43 символа.

Самому такую трансформацию не получается сделать программно, пробовал методом как описал выше в п.2, отладкой смотрел, не нашел(

Думал может тут кто подскажет логику.

**Comment by GilimkhanovDenis** [comment]
Увы. Здесь только по [этой dll-ке](https://developer.kontur.ru/Docs/Diadoc/COM/index.html) можем помочь. Вся помощь по модулям 1С - через техподдержку и отдел внедрения (платные консультации)

Может быть вам повезёт и кто-то, знающий про современный модуль сюда заглянет, но я бы не сильно на это рассчитывал

**Comment by repaqq** [comment]
> > > В модуле 1С поищите
> > > `Функция Документ_2_DocumentID(Документ, DocumentType= Неопределено) Экспорт`
> > > Она по ссылке на документ 1С даст вам длинную строку, которая на самом деле является объединением 2 гуидов - MessageId и DocumentId. Режете ее посередине и получаете MessageId и DocumentId для HTTP запроса.
> > > Кстати, вам вроде предлагали модуль, который статусы документов пишет в отдельные справочники в 1С. Вы решили все-таки остаться на том, который только id документов в базу сохраняет?
> > 
> > 
> > В общем для получения ИдентификаторДокументаВДиадок нужно сложить MessageId+EntityId и вызвать метод "КонвертироватьГуидВЧисло64"
> > ПолучитьМодульПрог("Модуль_Логика_РаботаСBase64").КонвертироватьГуидВЧисло64("bb01d4fb-6640-4c26-85d1-318370870bd1cd4628f1-2bb6-4080-9aba-7bf07b3d1eea")
> 
> Подскажите, сейчас похожая задача. Использую модуль для старой версии УТ 10.3. ИдентификаторДокументаВДиадок хранится в РС ЗначенияСвойствОбъектов для каждого документа.
> 
> Через GetDocuments получаю список документов, дальше хочу понять с чем каждый из них сопоставлен у нас в системе1С, но не могу понять как реквизиты гуид соотнести с ИдентификаторДокументаВДиадок в регистре, пробовал следующее:
> 
> 1. сложить СтрокаКодирования =  MessageId+EntityId.
>    Далее преобразовать
>    ДвоичныеДанныеСтроки = ПолучитьДвоичныеДанныеИзСтроки(СтрокаКодирования);
>    СтрокаBase64 = Base64Строка(ДвоичныеДанныеСтроки);
> 
> Полученное значение не соотносится с ИдентификаторДокументаВДиадок , там 43 символа. 2) Искал Документ_2_DocumentID, не нашел такой функции в модуле 3) Задавал вопрос в поддержку, диадок говорит это платные консультации
> 
> Может кто выручит как соотнести реквизиты документа полученные по АПИ, со значением, которое при ручном сопоставлении хранится в регистре. Логику трансформации пока не понял.

В модуле КонтурДиадокХранениеДанных ищите функцию GUID_2_Base64(GUID)  и Base64_2_GUID(Base64) для прямого и обратного преобразования, оно вот это делает:
	GUID = Идентификаторы.LetterID + Идентификаторы.DocumentID;
	Результат = GUID_2_Base64(GUID);
А вторая,обратно, поделив строку на 2 как раз найдете нужное.
