### ISSUE TITLE
Перестало работать подпись документов  через API

### ISSUE THREAD

**Issue by vlapenkov** [diadoc/diadocsdk-1c-docs#209]
Произошла исключительная ситуация (ReplySendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Torg12BuyerTitleInfo.ShipmentReceiptDate is required

Я так понимаю, не хватает каких-то данных. Что надо заполнять?
Спасибо.

**Comment by GilimkhanovDenis** [comment]
Необходимо заполнить поле [ShipmentReceiptDate](https://diadocsdk-1c.readthedocs.io/ru/latest/Torg12BuyerContent.html?highlight=ShipmentReceiptDate)
