### ISSUE TITLE
Заполнение макета формализованного УПД и УКД. Общее кол-во

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#21]
В формате есть элемент НеттоВс описан см. скрин.
![cbce79ce-6e9e-11e6-9b1d-7d97375e8605](https://cloud.githubusercontent.com/assets/20082460/19142270/d2993dc0-8ba4-11e6-928d-72732be9b0b5.png)
Реализуйте в представлении, когда УПД используется в качестве и счет-фактуры и накладной, то важно помимо суммы и суммындс и общее количество.

**Comment by jakeqwert** [comment]
![default](https://cloud.githubusercontent.com/assets/20082460/19142337/56bf9ad6-8ba5-11e6-8c52-2492ffc59263.jpg)

**Comment by denver069** [comment]
Данный элемент будет отражен во внешней компоненте в поле:
TotalNet (число с плавующей запятой, чтение/запись) - нетто всего.

**Comment by jakeqwert** [comment]
Хорошо. Бухгалтерия решила не отображать общее количество в представлении, как в рекомендованной форме на сайте ФНС. Так что вопрос не актуален. Большое спасибо, за ответы.

**Comment by TPEHER** [comment]
Добрый день. Подскажите пожалуйста как вы это в коде реализовали.
