### ISSUE TITLE
Ошибка при использовании GetDocumentById

### ISSUE THREAD

**Issue by Scopatutto** [diadoc/diadocsdk-1c-docs#210]
Добрый день, сегодня при использовании метода получил ошибку "protobuf parse error, required fields missing: InvoiceMetadata.Vat".
Что это за ошибка? На прошлой неделе ошибки на этих же данных не было.

**Comment by GilimkhanovDenis** [comment]
Здравствуйте. уточните на какой версии компоненты возникла данная ошибка, какой метод при этом использовался, какие данные использовались для отправки

**Comment by GilimkhanovDenis** [comment]
Обновите компоненту. Если ошибка воспроизводится, то переоткройте issue
