### ISSUE TITLE
Не получается получить DocumentsTask.GetDocuments();

### ISSUE THREAD

**Issue by komissarovev** [diadoc/diadocsdk-1c-docs#211]
Делаю так, но DocumentList.Count = 0

   OrganizationList = ДиадокСоединение.GetOrganizationList();
   Organization = OrganizationList.GetItem(0);
   DocumentsTask = Organization.GetDocumentsTask();
   DocumentsTask.FromSendDate = НачалоГода(ТекущаяДата());
    DocumentsTask.ToSendDate = КонецГода(ТекущаяДата());
    DocumentsTask.Category = "Invoice.Outbound";
    DocumentList = DocumentsTask.GetDocuments();
    ц1 = 0;
    Пока ц1 < DocumentList.Count цикл
              Document = DocumentList.GetItem(ц1);
               ц1 = ц1 +1;
    КонецЦикла;

**Comment by sergro** [comment]
Если DocumentList.Count = 0, то DocumentsTask.GetDocuments() отработал вы получили объект DocumentList. Просто он пустой. Т.е нет таких документов (исходящих счет-фактур у этой организации. У вас сколько организация к сертификату прикреплено OrganizationList.Count()=1 ?
У организации Organization = OrganizationList.GetItem(0) точно есть исходящие документы?

**Comment by komissarovev** [comment]
спасибо, разобрался. использовал UniversalTransferDocument.Outbound
