### ISSUE TITLE
Опять пакет документов

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#213]
Есть документ: https://diadoc.kontur.ru/7f648ced-4718-4958-884e-02dac0220d4a/Document/Show?letterId=096fd1a2-a732-4057-b162-859f114ade78&documentId=63d70962-703a-477d-a4e4-9b847117069c
Он входит в пакет из трек документов, требующих подписания.
Document.GetDocumentPackage().Documents.Count от него возвращает 3, но когда выполняю: 		

DocumentPackage = Document.GetDocumentPackage();
ReplySendTask 	= DocumentPackage.CreateReplySendTask(Type);	

В ReplySendTaskContent.ContentItems.Count - один документ. Ранее возвращал три документа.
Почему сейчас возвращает 1?

**Comment by prog22** [comment]
Цель - подписание пакета из трех документов облачной подписью, одной СМС.

**Comment by prog22** [comment]
Выполняемые действия:
1) Подписал пакет документов облачной подписью. При этом статусы входящих в пакет документов стали "InboundInvalidRecipientSignature";
2) Повторно выполнил ReplySendTask = DocumentPackage.CreateReplySendTask(Type), он вернул один документ - УПД и успешно подписал его той же облачной подписью, что была использована в п.1.

**Comment by prog22** [comment]
Ранее, таких проблем не было, пакет подписывался облачной подписью одной СМС, например: https://diadoc.kontur.ru/7f648ced-4718-4958-884e-02dac0220d4a/Document/Show?letterId=cddfb546-72c2-4cdd-a017-5164bb9186ae&documentId=2b3b5537-bc7b-4c04-8c77-6c99209318ee

**Comment by prog22** [comment]
При этом обычной КЭП (не облачной подписью) каждый документ по отдельности подписывается нормально, например:
https://diadoc.kontur.ru/7f648ced-4718-4958-884e-02dac0220d4a/Document/Show?letterId=4658ee9b-3f79-42d5-8a50-f2915c36e2d5&documentId=7b20848f-ae9f-448b-a015-dbcb7df3341c

**Comment by GilimkhanovDenis** [comment]
Исправлено в версии 5.22.5.373
