### ISSUE TITLE
Подписание документов вида (PriceListAgreement) со стороны Покупателя

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#214]
Почему перестало работать программное подписание документов вида (PriceListAgreement) со стороны Покупателя, например:

https://diadoc.kontur.ru/7f648ced-4718-4958-884e-02dac0220d4a/Document/Show?letterId=43ca5f72-cb43-4b03-92b6-6c0aa84984a8&documentId=a833e256-d656-4f35-b5c6-002440906359

Возвращает ошибку:

Ошибка при вызове метода контекста (CreateReplySendTask)
	ReplySendTask = Document.CreateReplySendTask();	
по причине:
Произошла исключительная ситуация (DocumentBase.CreateReplySendTask): Нет документов, для которых возможно формирование ответного задания выбранного типа.

**Comment by GilimkhanovDenis** [comment]
Исправлено в  версии компоненты 5.21.10.342
