### ISSUE TITLE
Не определяется тип документа DP_REZRUISP

### ISSUE THREAD

**Issue by Alex463** [diadoc/diadocsdk-1c-docs#215]
Добрый день! Загружаю документ аналогичный этому https://diadoc.kontur.ru/098ab78b-ca53-42ae-89f9-fd07ca3d320b/Document/Show?letterId=2763ef87-f0ac-4cc3-9849-a3a966f66ca4&documentId=454607c2-148e-4e8b-9232-48f65dd9a0f8 в обработку 1с (версия 5.23.01) 
![screenshot_26](https://user-images.githubusercontent.com/24681242/38199680-4e580472-369a-11e8-96ce-da5a05ca0c74.jpg). Определяется тип документа неформализованный, хотя в ЛК - 
это акт. 
Если я выберу в обработке тип документа "Акт выполненных работ", то документ будет аналогичный этому: https://diadoc.kontur.ru/098ab78b-ca53-42ae-89f9-fd07ca3d320b/Document/Show?letterId=c1689f00-00c7-4375-9b72-c329cd4e1c8d&documentId=ab108303-86d4-4398-8283-6377c827687a
Можно ли работать с формализованными документами DP_REZRUISP через обработку 1с и компоненту?

**Comment by GilimkhanovDenis** [comment]
Отправки документов Торг-12 и Акт в форматах 551/552 приказов (TovTorg и Rezruisp соответственно) в модуле Standart не планируется

**Comment by Alex463** [comment]
Ок, спасибо, а если мне пришел такой документ, то я могу его подписать через компоненту (не через модуль 1с)?

**Comment by GilimkhanovDenis** [comment]
Да, подписание через компоненту доступно.
Более того, в модуле Standart для управляемого приложения в версии 5.**24**.01 добавлена возможность просмотра, подписания и отказа в подписи для входящих документов в форматах 551, 552

**Comment by Alex463** [comment]
Понял, спасибо.
