### ISSUE TITLE
Ошибка при вызове getpersonalsertificates().

### ISSUE THREAD

**Issue by usrborisk** [diadoc/diadocsdk-1c-docs#216]
Для выгрузки в диадок использую Com объект. 
С определенного момента при вызове метода getsertificates()
Появляется окно выбора носитей сертификатов, в которых нет нужно сертификата.
Также не получается использовать ключ установленный в реестр.
Подскажите в чем может быть дело.

**Comment by GilimkhanovDenis** [comment]
Проблема очень похожа на то, что описано в https://github.com/diadoc/diadocsdk-1c-docs/issues/199.
Попробуйте обратиться в тех.поддержку (тел. 8-800-500-10-18)
