### ISSUE TITLE
ReceiptGenerationProcess

### ISSUE THREAD

**Issue by GeorgyElovskih** [diadoc/diadocsdk-1c-docs#218]
Добрый день.
Имеем ситуацию, что периодически, по неясным пока причинам, останавливается "магия" и на определенный момент времени перестают подписываться извещения о получении СФ.
Можете описать принцип работы, в случае если СФ был получен, но извещение не было подписано должно ли извещение подписаться при следующем запуске?

**Comment by GilimkhanovDenis** [comment]
Здравствуйте.
Магия запрашивает все документы в ящике, по которым необходимо сформировать ИоП. В последних версиях компоненты у объекта [ReceiptGenerationProcess](https://diadocsdk-1c.readthedocs.io/ru/latest/ReceiptGenerationProcess.html) появилось поле Error, в которых будут перечислены ошибки, если таковые возникли за время работы магии.
