### ISSUE TITLE
Описание новых методов для работы с УПД и УКД из 1С 8.3

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#22]
Подскажите, где можно увидеть описание новых методов для работы с УПД и УКД из 1С 8.3 и скачать новую библиотеку для 1С.

**Comment by jakeqwert** [comment]
Уточнение нужно "COM-компонента для встраивания в произвольные системы" Именно ее используем для 1С.

**Comment by denver069** [comment]
На данный момент поддержка УПД во внешней компоненте не реализована.
Как только выпустим новую версию внешней компоненты с поддержкой УПД, обязательно добавим описание новых объектов в документацию http://1c-docs.diadoc.ru/ru/latest/.
