### ISSUE TITLE
Ошибка в компоненте, включая версию 5.21.4.324

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#220]
Клиент нам прислал документ (doc) с длинным именем, см. скриншот, при вызове метода Document.SaveAllContent(КаталогВременныхФайлов, Истина); - Выходит ошибка, что "каталог не обраружен". Это понятно, т.к. имя файла некорректное, тем не менее, такие файлы надо как-то уметь сохранять.
Предлагаю разработчикам подумать и исправить, либо не позволять такие имена при отправке, либо доработать процедуру сохранения.

![image](https://user-images.githubusercontent.com/20473774/40231147-5e9928b0-5ab3-11e8-904d-8d536af45d8e.png)

**Comment by GilimkhanovDenis** [comment]
Исправлено в  версии компоненты 5.21.10.342
