### ISSUE TITLE
Данные о доверенности

### ISSUE THREAD

**Issue by iolko** [diadoc/diadocsdk-1c-docs#221]
Как можно добавить данные о доверенности в документ ? На в API ни в Web интерфейсе не смог найти как это сделать.

**Comment by GilimkhanovDenis** [comment]
Данные о доверенности указываются в подписи к файлу. Например, при отправке УПД необходимо заполнить поле [PowerBase](https://diadocsdk-1c.readthedocs.io/ru/latest/ExtendedSignerDetails.html?highlight=PowersBase)
