### ISSUE TITLE
Акт выполненных работ, UnitCode обязателен для заполнения

### ISSUE THREAD

**Issue by iolko** [diadoc/diadocsdk-1c-docs#222]
Добрый день! При отправке Акта выполненных работ по услугам поле UnitCode должно быть пустым или должен стоять "-". При попытке создать АКТ, используя "AddInDiadocAPI.dll" версии 5.20.3.304 возникает ошибка "Если поле Name заполнено, то необходимо указать UnitCode".

**PackageSendTask.Send: ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/AcceptanceCertificateSellerTitle/Works/Work/Item: @UnitCode is required when @Name is filled**

UnitCode (строка, чтение/запись, числовая строка длиной 3 символа. Код должен содержаться в Общероссийском классификаторе единиц измерения. ) - код единицы измерения

Ссылка на документацию: http://diadocsdk-1c.readthedocs.io/ru/latest/AcceptanceCertificateItem.html

Но по услугам нет единиц измерения.

Так же возникает ошибка:

**PackageSendTask.Send: ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/AcceptanceCertificateSellerTitle/Works/Work/Item: @Quantity is required when @Name is filled**

Т.е. поле количество должно быть заполнено если заполнено Name, но у услуг нет количества.

В описании API указано:
Quantity (число, чтение/запись, — ) - количество
Price (число, чтение/запись, — ) - цена
но если передать 0 то это не верно, если передать "-" то ошибка несовпадения типов, 
если не заполнять то ошибка, указанная выше.

**Comment by etalipov** [comment]
Добрый день!
Данные ограничения обусловлены форматом 172 приказа ФНС. Согласно ему, количество и код ЕИ обязательны, если указано наименование работ. В случае с услугами без количества и кода ЕИ можно воспользоваться не наименованием работ, а описанием работ - оно не требует указания количества и кода ЕИ. 
![default](https://user-images.githubusercontent.com/34828350/40528218-930b1d8c-6009-11e8-9eba-6b1f60071779.png)
![default](https://user-images.githubusercontent.com/34828350/40528228-a39fc0c6-6009-11e8-9e45-7ad38dc0a2f2.png)

**Comment by iolko** [comment]
Спасибо, да все получилось
