### ISSUE TITLE
HTTP error: Info.Buyer.Address.RussianAddress.Apartment is too long

### ISSUE THREAD

**Issue by AllianceAvia** [diadoc/diadocsdk-1c-docs#223]
Используем AddInDiadocAPI для отправки документов из своей учетной системы. 
Есть контрагент (ИНН 4223056766) с реальным юридическим адресом, где офис следующего вида: "1 К-Ты 9Т 9У 9С 9О 9М 9Ц Ч-Ть П 9Н" 
Но в API https://diadocsdk-1c.readthedocs.io/ru/latest/AddressInfo.html указано, что максимальная длина Info.Buyer.Address.RussianAddress.Apartment - 20 символов. 
Соответственно, при отправке документов этому контрагенту мы получаем ошибку: ##100[Ошибка сервера Диадок]code:400, HTTP error: Info.Buyer.Address.RussianAddress.Apartment is too long: 1 К-Ты 9Т 9У 9С 9О 9М 9Ц Ч-Ть П 9Н 

Возможно ли увеличить максимальную длину свойства Apartment?

**Comment by GilimkhanovDenis** [comment]
Ограничение на длину полей задано законодательством, поэтому изменить максимальную длину невозможно. Можно передавать адрес строкой, устанавливая признак isForeign в истину и заполняя CountryCode и AddressText.

**Comment by AllianceAvia** [comment]
В Приказе по КЛАДРу указано: "Длина блока номера квартиры (офиса) не должна превышать 40 символов.", в API Диадок - 20 символов

**Comment by GilimkhanovDenis** [comment]
в [приказе, регламентрирующим формат xml для электронных документов](https://normativ.kontur.ru/document?moduleId=1&documentId=271958&rangeId=71524) стоит ограничение в 20 символов

**Comment by AllianceAvia** [comment]
Благодарю за ссылку
