### ISSUE TITLE
Отправки приглашений контрагента к партнерству и отправить письмо на эл. адрес

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#225]
На сайт www.diadoc.ru появилась возможность загрузить реестр будущих партнеров контрагентов, при этом указав их адреса e-mail, поступит уведомление на электронную почту контрагента с адреса diadoc-invites@kontur.ru и будет содержать краткую информацию о поступившем приглашении и ссылку на вход в Диадок.

**Хотелось бы иметь такую возможность указывать в приглашении к партнерству e-mail контрагента при использовании COM компоненты для встраивания в произвольные системы.**
AcquireCounteragentTask = Organization.CreateAcquireCounteragentTask(ПолныйПуть);
Указав e-mail контрагента в соответствующем реквизите объекта.
Данное мероприятие позвонить сделать два дела одновременно: обновить приглашения и отправить письмо на эл. адрес, что повысить % принятие приглашений.

Используем Com, а не web интерфейс сайта ввиду, того что при отправке запоминает id документа, который после подписания, автоматом прокачивается в нашу учетную систему и проставляет признак ЭДО у контрагента, ввиду большого кол-ва контрагентов более 10 000.

**Comment by GilimkhanovDenis** [comment]
Такой функциональности в API Диадок в ближайшее время не предвидится. Если такая функциональность нужна, то необходимо обратиться к вашему менеджеру, чтобы он продвигал данную идею в разработку
