### ISSUE TITLE
Ошибка при отправлении черновика "Счет фактуры"

### ISSUE THREAD

**Issue by Annuto4ka** [diadoc/diadocsdk-1c-docs#227]
Версия компоненты v5.20.3.
При попытки оправить черновик методом Оrganization.SendDraftAsync() возвращается ошибка.

"Произошла исключительная ситуация (SearchDocumentTaskAsyncResult.Result): ##100[Ошибка сервера Диадок]code:404, HTTP error:  "

В чем может быть причина?

**Comment by GilimkhanovDenis** [comment]
Если ошибка актуальна, то уточните BoxId по которому возникает ошибка

**Comment by Annuto4ka** [comment]
Задача не актуальна. 
Ошибка возникала, при передаче несуществующего идентификатора черновика.
