### ISSUE TITLE
Ошибка отправки документа через XML файл с помощью CreateSendTaskFromFile

### ISSUE THREAD

**Issue by avorontcov** [diadoc/diadocsdk-1c-docs#229]
Добрый день.

Есть УПД XML-файл, который проходит проверку на https://www.diadoc.ru/docs/forms/validation-xml.
В личном кабинете, через интерфейс нормально загружается и отправляется.
Но через функцию organization.CreateSendTaskFromFile() получаю ошибку:
Метод "Send" класса "ISendTask" возвратил: ##100[Ошибка сервера Диадок]code:400, HTTP error: Info.TransferInfo is required.

Что необходимо заполнить для загрузки, и почему. если чего-то не хватает, файл нормально грузится через интерфейс?

**Comment by denver069** [comment]
Раздел [TransferInfo](http://1c-docs.diadoc.ru/ru/latest/TransferInfo.html) описывает элемент [Файл/Документ/СвПродПер](https://www.diadoc.ru/docs/forms/upd/structure/1). Согласно [XSD схеме УПД](https://www.diadoc.ru/docs/forms/upd/structure/xsd/1), этот элемент является обязательным если Функция=**СЧФДОП** или Функция=**ДОП**. Файл нормально грузится через интерфейс, потому что внешняя компонента не содержит в себе функцию валидации XML по XSD схеме. Валидация контента по XSD схеме происходит при отправке на стороне оператора.

**Comment by avorontcov** [comment]
Спасибо! Эта ошибка ушла.
Теперь: Метод "CreateSendTaskFromFile" в классе "IBox" возвратил: ##100[Ошибка сервера Диадок]code:500, HTTP error: The server encountered an internal error or misconfiguration and was unable to complete your request.

Как бы мне распознать, где я ошибся?

**Comment by denver069** [comment]
@azhipaigor посмотри пожалуйста.

**Comment by avorontcov** [comment]
разобрался. Ошибка в структуре файла.
Почему бы не выдавать в сообщение элемент, в котором есть ошибка, как и в случае отсутствия элемента ([ObjectName] is required.)?

**Comment by avorontcov** [comment]
Метод "Send" в "ISendTask" возвратил : ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.ToBoxId is required field.
В файле в секции СвУчДокОбор заполнены и ИдОтпр и ИдПол
где ошибка?

**Comment by GilimkhanovDenis** [comment]
Проверьте, что заполнен [идентификатор контрагента](https://diadocsdk-1c.readthedocs.io/ru/latest/SendTask.html?highlight=CounterAgentId)

**Comment by avorontcov** [comment]
да, оно. Спасибо
