### ISSUE TITLE
Вызов метода CreateConnectionByCertificate приводит к ошибке AV at 0838DB01

### ISSUE THREAD

**Issue by AlexeyDynnikov** [diadoc/diadocsdk-1c-docs#23]
Код - как в примере:
`_DiadocCom := CoDiadocCom.Create;`
`// Ищем сертификат - находится успешно, `
`// _Cert.Thumbprint = 'EC62B0B00836A4CC3E2F0066898950148EF308FA'`
`_DiadocCom.ApiClientId := '<ставлю свой, рабочий>';`
`_DiadocCom.ServerUrl := 'https://diadoc-api.kontur.ru:443';`
`_DiadocConnection := _DiadocCom.CreateConnectionByCertificate(_Cert.Thumbprint, '');` <- Здесь падает

Текст ошибки:
`Access violation at address 0838DB01 in module 'DiadocComApi.dll'. Read of address 00000000`

Альтернативный вариант - по логину и паролю - работает:
`_DiadocConnection := _DiadocCom.CreateConnectionByLogin(МойЛогин, МойПароль);` // Успешно

**Comment by denver069** [comment]
Алексей, при вызове метода [CreateConnectionByCertificate](http://diadocsdk-1c.readthedocs.io/ru/latest/CreateConnectionByCertificate.html?highlight=CreateConnectionByCertificate) вы используете пустую строку в качестве второго параметра. Я не нашел в [документации по методу](http://diadocsdk-1c.readthedocs.io/ru/latest/CreateConnectionByCertificate.html?highlight=CreateConnectionByCertificate) информацию о втором параметре, попробуйте вызвать метод без него. Если не поможет, напишите в какой операционной системе используете компоненту и откуда её вызываете.

**Comment by AlexeyDynnikov** [comment]
Т.к. я пишу на Delphi, то использую явно описанные в библиотеке типов интерфейсы. В  библиотеке типов этот метод содержит второй параметр:

![screenshot](https://cloud.githubusercontent.com/assets/22746301/19281042/f0e4c10a-8ff0-11e6-98b1-e3ef44b645a9.PNG)

Я попробовал вызвать этот метод через IDispatch с одним параметром - сработало.

Попробовал скорректировать описание интерфейса вручную, убрав второй параметр - сработало ограниченно - код собрался, метод вызвался, по протоколу обмен с сайтом состоялся (с двумя параметрами до него дело не доходило) однако возвращенный результат оказался непригоден - вернулся нерабочий интерфейс. 

Теоретически с IDispatch жить, конечно, можно, но было бы лучше, если бы все работало напрямую через объявленные интерфейсы.

**Comment by denver069** [comment]
Что значит вернулся нерабочий интерфейс?
Если с сайта вернулась ошибка, покажите текст ошибки.

**Comment by denver069** [comment]
Закрыл запрос из-за отсутствия ответа пользователя в течении недели.
