### ISSUE TITLE
Узнать размер файла(-ов) до скачивания

### ISSUE THREAD

**Issue by AdrianBerk** [diadoc/diadocsdk-1c-docs#232]
Не нашел в  документации ни полей ни методов позволяющих получить размер документа перед скачивание с  сервера. особенно актуально для больших массивов данных. Чтобы заранее знать примерное время на закачку и  какое дисковое пространство потребуется.
В идеале для объекта Document добавить свойство Size() или что то типа того.
Может оно где то глубже запрятано? ну поскольку размер архива заранее не вычислить... может тогда
размер контента в  него до вложения в  архив выдавать. И то бы помогло. Выполнил GetDocuments  и сразу получил что и  сколько весит....

**Comment by GilimkhanovDenis** [comment]
Добрый день.
Уточните пожалуйста, в каком из полей после выполнения GetDocuments у Вас получилось найти размер файла.
Также просьба уточнить каким методом сохраняете документы на диск. Вас интересует размер только титула продавца или нужны размеры других сущностей, связанных с документов (подписи, ответные титулы и т.п.)? Размер каких конкретно сущностей необходимо знать?

**Comment by GilimkhanovDenis** [comment]
Ответа не вопросы не последовало
Закрываю

**Comment by aboba38** [comment]
aboba
