### ISSUE TITLE
Получить историю обработки документа

### ISSUE THREAD

**Issue by alevanov** [diadoc/diadocsdk-1c-docs#233]
Добрый день!
Как получить историю обработки документа, которую можно видеть, открыв документ в web-интерфейсе Диадока?
![image](https://user-images.githubusercontent.com/40228820/41342850-e16b59e6-6f05-11e8-8d77-6f084677dfa0.png)
Интересует именно история, а не текущий статус обработки документа.

**Comment by GilimkhanovDenis** [comment]
Добрый день.
Попробуйте использовать [GetDocumentEventList](https://diadocsdk-1c.readthedocs.io/ru/latest/GetDocumentEventList.html) для получения всего списка событий в ящике и на его основе построить выборку событий по конкретному документу.
Отдельного метода для получения истории конкретного документа в ближайшее время не предвидится.

**Comment by BaevaSvetlana** [comment]
Добрый день, не было ли расширение методов для получения истории изменения статусов документов с момента формирования темы: по-прежнему можно использовать только методы GetDocumentEventList, сам документ и его коллекцию Resolutions?

**Comment by GilimkhanovDenis** [comment]
Изменения компоненты, в том числе появление новых методов можно найти в истории [изменений](http://1c-docs.diadoc.ru/ru/latest/History.html)

Новых методов получения DocumentEvent'ов не было
