### ISSUE TITLE
Подписание облачной подписью

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#234]
При подписании облачной подписью приходит СМС с кодом на телефон.
После ввода кода возвращается сообщение:
"##100[Ошибка сервера Диадок]code:403, HTTP error: MessagePatchToPost.UniversalTransferDocumentBuy".
Подписания не происходит.
Область полномочий сотрудника настроена.
С чем это связано?

**Comment by prog22** [comment]
Ошибка возникает при подписи сертификатом в https://diadoc.kontur.ru/3b126c36-ce05-42bc-aea3-0a2429e9b2ad/Preferences

**Comment by GilimkhanovDenis** [comment]
ApiClientMessage: MessagePatchToPost.UniversalTransferDocumentBuyerTitles[0]: Сертификат не зарегистрирован в ФНС. Отпечаток сертификата: 3C58515544C40E19F8BF30C459393C7BF49078C2

выполните метод [SendFnsRegistrationMessage](https://diadocsdk-1c.readthedocs.io/ru/latest/SendFnsRegistrationMessage.html)
