### ISSUE TITLE
Разный формат DateTimeTicks

### ISSUE THREAD

**Issue by GeorgyElovskih** [diadoc/diadocsdk-1c-docs#235]
Добрый день.
При работе с обработкой получением объектов из метода (работа компоненты) почтового ящика getDocumentsTask получаем объект ЭДО (COM-объект), который содержит пустую дату в значении ’01.01.0001’
 
![1](https://user-images.githubusercontent.com/37666179/42632547-f8db5d44-85f6-11e8-8355-fb2903bbd511.png)

При обновлении событий и работе с API Диадока (получаем события методом GetDocflowEvents, а затем объект ЭДО (COM-объект) методом почтового ящика GetDocumentById) получаем объект, который содержит пустую дату в значении ’30.12.1899’. 

![2](https://user-images.githubusercontent.com/37666179/42632915-435dfbfa-85f8-11e8-849d-ad89a70b2a77.png)

С чем связано получение значения одного и того же объекта в разном формате?

**Comment by GeorgyElovskih** [comment]
Компонента 5.21.10.342 64-разрядная. на клиенте AddIn, Com версия на сервере.

**Comment by GilimkhanovDenis** [comment]
Проверьте формат дат на релизе 5.22.0.349
