### ISSUE TITLE
Метод GetDocumentEventList() возвращает пустое значение для параметра EventType

### ISSUE THREAD

**Issue by NadezhdaLunkova** [diadoc/diadocsdk-1c-docs#236]
С недавнего времени (впервые замечено 03.07.18) метод GetDocumentEventList() стал возвращать пустое значение для параметра EventType (EventType=""), например:
  
Свойство | Значение
мEvent.GetItem(Count) | COMОбъект
DocumentDirection | "Outbound"
DocumentType | "XmlAcceptanceCertificate"
EventType | ""
Timestamp | 19.07.2018 15:26:18
counteragentId | "c88f13e535d7419fbf87337a092110c7@diadoc.ru"
documentId | "33e8684c-3dc0-4a2c-87f2-862b4ebda9397a720138-0e88-45d1-8345-12c668e5e953"
eventId | "4d0c478f-855a-4e2f-9ec5-7023d07dc3d9"

Подскажите, с чем это связано и как можно исправить?

**Comment by GilimkhanovDenis** [comment]
На какой версии компоненты воспроизводится?

**Comment by NadezhdaLunkova** [comment]
Версия компоненты: 5.21.6.329

**Comment by NadezhdaLunkova** [comment]
Версия модуля: UF.5.26.01
Похоже, как раз после обновления случилось.

**Comment by GilimkhanovDenis** [comment]
Обновите компоненту до актуальной 5.21.10.342

**Comment by NadezhdaLunkova** [comment]
Спасибо! Помогло.
