### ISSUE TITLE
После подписание формализованного документа статус документа "InboundNotFinished"

### ISSUE THREAD

**Issue by Alex463** [diadoc/diadocsdk-1c-docs#237]
Коллеги, добрый день! Ситуация редкая, но бывает. После подписания формализованного документа (в частности УПД), статус документа в поле "Status" объекта "Document" присваивается "InboundNotFinished". Документ при этом подписывается, весь пакет документов с подписями присутствует. Если же зайти в документ через личный кабинет с авторизацией ЭЦП, то статус меняется на "InboundFinished" (если по почте, то статус остается прежним). Для нашей работы это не вариант. Хочется понять причины возникновения ошибки и, чтобы ситуация больше не повторялась.
Версия компоненты - 5.21.10
Пример документа с которым произошла ситуация- https://diadoc.kontur.ru/098ab78b-ca53-42ae-89f9-fd07ca3d320b/Document/Show?letterId=fe1b0391-8c9f-4a6f-b82c-2fb0b558c31b&documentId=1638941f-97cf-4736-a6a8-8211657cd688

**Comment by GilimkhanovDenis** [comment]
Для завершения документооборота УПД необходимо не только сформировать ответный титул, но и подписать извещения о получении (см. http://api-docs.diadoc.ru/ru/latest/docflows/UtdDocflow.html ).
Для формирования ИоПов из компоненты используйте [ReceiptGenerationProcess](https://diadocsdk-1c.readthedocs.io/ru/latest/ReceiptGenerationProcess.html)
