### ISSUE TITLE
Свойства объекта UserPermissions

### ISSUE THREAD

**Issue by OlegSharma66** [diadoc/diadocsdk-1c-docs#238]
Работа с порталом Диадок осуществляется с использованием библиотеки AddInDiadocAPI.dll (версия 5.18.1.219). Обратил внимание, что не могу получить значение свойства "Создавать документы и работать с черновиками" объекта UserPermissions. (ссылка на страницу документации http://1c-docs.diadoc.ru/ru/latest/UserPermissions.html). 
Подскажите пожалуйста планируется ли организовать доступ в указанному свойству в новых версиях библиотеки AddInDiadocAPI.dll ?

**Comment by GilimkhanovDenis** [comment]
в 5.22.1.354 (релиз от 09 августа 2018) добавили просмотр права на создание документов в ящике
