### ISSUE TITLE
COM-компонента для встраивания в произвольные системы

### ISSUE THREAD

**Issue by andreevlex** [diadoc/diadocsdk-1c-docs#24]
Господа, интуитивно не понятно где искать эту компоненту. 
Может стоит уделить данной компоненте отдельный раздел в документации?

**Comment by denver069** [comment]
В каком разделе какой именно документации по вашему мнению стоит разместить ссылку?

**Comment by andreevlex** [comment]
Вот здесь раздел есть, а вот ссылки на скачивание нет.
[.NET/COM-библиотека](http://api-docs.diadoc.ru/ru/latest/DiadocApiDll.html)

**Comment by denver069** [comment]
А ведь вы правы, отличная идея!
Спасибо за подсказку!

**Comment by denver069** [comment]
Документацию поправили.
