### ISSUE TITLE
метод SendRevocationRequest.

### ISSUE THREAD

**Issue by IrinaZ86** [diadoc/diadocsdk-1c-docs#240]
Добрый день. Пытаюсь применить метод SendRevocationRequest для отправки запроса по аннулированию документа. При вызове метода просто закрывается сторонняя программа из которой запускаю код. В чем может быть причина?

**Comment by GilimkhanovDenis** [comment]
Уточните используемую версию компоненты, разрядность и тип (AddIn или Com)

**Comment by IrinaZ86** [comment]
версия 5_22_0_349 для 32 битных систем, Com

**Comment by IrinaZ86** [comment]
Может быть это дело в версии? Есть возможность скачать более старую? Дополнительно: работаю с тестовым ящиком. Уникальный номер документа, который пытаюсь аннулировать fef08f04-bbb7-42af-a78b-3a11b3e07fffb6b9e0e2-4855-42e7-9001-fd81dcb6c699

**Comment by GilimkhanovDenis** [comment]
Если запрос аннулирования происходит на стороне получателя, то будет выброшено исключение "Текущее состояние документа не позволяет создать запрос на аннулирование или выполнить отзыв". Проверьте, что обрабатываете данное исключение.

Если данное предположение неверно, то не могли бы предоставить фрагмент кода, при выполнении которого вылетает программа (желательно указать на каком языке он написан)

**Comment by IrinaZ86** [comment]
В том то и дело что не могу обработать как ошибку, потому что просто закрывается клиент при попытке вызвать метод. Аннулирование на стороне отправителя. 

      Call Diadoc_InitializeComponent ()	
	If Not IsConnection  Then
		msgbox "Не удалось установить соединение с сервером Diadoc"
		Exit Sub
	End If	
	orgID = {52c0455581964de5acd748ace7dc5a51@diadoc.ru}
	evID = ""
	Set objOrg = DiadocConnection.GetOrganizationById(orgID)
	Set packDocs = objOrg.CreatePackageSendTask()
	packDocs.OperationId = "RSHH-AXVH62E685" 
	Set packDocs_send = packDocs.send ()
	
	Set objDocs = packDocs_send.Documents()	
	n = objDocs.count
	For i = 0 To n-1
		Set doc_item = objDocs.getitem(i)				
		doc_item.SendRevocationRequest({Аннулировать})				
	Next

При попытке выполнить doc_item.SendRevocationRequest({Аннулировать})	 падает клиент. Язык - LotusScript

**Comment by GilimkhanovDenis** [comment]
Попробуйте на вчерашнем релизе компоненты - добавили обработчики исключительных ситуаций, которые могут возникнуть при выполнении этого метода

**Comment by GilimkhanovDenis** [comment]
Выпустили релиз (5.22.2). Ошибка не должна воспроизводиться

**Comment by IrinaZ86** [comment]
В релизе 5.22.2 при запуске приведенного в примере кода ошибка та же.

Переделала код:
		Set packDocs = objOrg.CreatePackageSendTask()	
		
		packDocs.OperationId = opID
		Set packDocs_send = packDocs.send ()		
		Set objDocs = packDocs_send.Documents()		
		n = objDocs.count
		For i = 0 To n-1
			Set doc_item = objDocs.getitem(i)							
			UNID = doc_item.DocumentId	
			Set Doc_found = objOrg.GetDocumentById(UNID)		
			statusRevocation = Doc_Found.RevocationStatus		
		Next		
	
Аннулирование происходит успешно. Спасибо.

**Comment by IrinaZ86** [comment]
Извините, в последней строке 	Doc_found.SendRevocationRequest
