### ISSUE TITLE
Заполнение данных о доверенности (Attorney) при отправке документа 

### ISSUE THREAD

**Issue by iolko** [diadoc/diadocsdk-1c-docs#241]
Добрый день! 

Отправляем ТОРГ-12, ссылка на API:  http://diadocsdk-1c.readthedocs.io/ru/latest/Torg12SellerContent.html

При отправке получаем для заполнения "Torg12SellerContent", но нам необходимо так же заполнить данные о доверенности, а это поле  "Attorney" из "Torg12BuyerContent".  Но это поле доступно только для чтения.

Можно ли заполнить во время отправки документа данные о доверенности стороны покупателя: "Attorney".

Так же хотелось бы видеть эту возможность не только в API, но и как базовую в веб версии ДиаДок.

Я понимаю, что это поле не случайно закрыто от редактирования при отправке, но наши бухгалтера готовы объяснить необходимость заполнения данного поля.

**Comment by GilimkhanovDenis** [comment]
Torg12BuyerContent это титул покупателя и формируется самим покупателем, то есть тем, кто подписывает документ. В момент отправки на него влиять нельзя

**Comment by iolko** [comment]
В случае, когда работник покупателя забирает товар на складе продавца, он предъявляет доверенность, в бумажном виде продавец в торг-12 заполняет данные о предъявленной доверенности.
Можно ли эти данные (номер и дату доверенности) продавцу заполнять в электронном виде в диадок?

С уважением,
заместитель главного бухгалтера по автоматизации
ПАО "Южный Кузбасс"

**Comment by GilimkhanovDenis** [comment]
Сведения о доверенности заполняются внутри контента объекта replySendTask. Например, 
[Torg12BuyerContent](https://diadocsdk-1c.readthedocs.io/ru/latest/CreateReplySendTask-(Document).html?highlight=Torg12BuyerContent)

**Comment by iolko** [comment]
replySendTask требует указания Типа ответного действия, а нам же нужно не формировать доп действие заранее, а просто получить титул продавца и заполнить данные о доверенности.

Мы общались с другими предприятиями , которые работают в системе ДД, им так же нужна эта возможность, и не только на стороне API, но и на стороне Web интерфейса. 

<Type> (строка, обязательный) - тип ответного действия. В случае, если тип не указан, по умолчанию будет выполняться действие “AcceptDocument”.
Параметр Type может принимать одно из следующих значений:

“AcceptDocument” - подписание документа
“RejectDocument” - отказ в подписи документа
“CorrectionRequest” - запроc на уточнение документов “счет-фактура” и “исправление счета-фактуры” (только для редактируемых пакетов)


PS извиняюсь за задержку с ответом, был в отпуске

**Comment by GilimkhanovDenis** [comment]
Не очень понятен сценарий работы.
Вы как отправитель подписываете и отправляете Торг-12.
И при этом хотите задать по какой доверенности документ будет подписан получателем?

Давайте уточним, доверенность отправителя или получателя хотите заполнить?

**Comment by iolko** [comment]
Пример: Мы - ПАО ЮК (Выступаем стороной продавца) , к нам пришел покупатель с доверенностью (это очень часто бывает) тогда мы выписываем ТОРГ-12 и уже на своей стороне заполняем доверенность покупателя.

**Comment by GilimkhanovDenis** [comment]
Данной функциональности в текущей версии компоненты нет и её добавление - трудоёмкий процесс. Если такая функциональность необходима, то рекомендую обратиться в ближайший сервисный центр (где, например приобретали лицензию на API или приобретали КЭП), чтобы менеджер продвигал эту задачу в разработку
