### ISSUE TITLE
Метод Send и SendAsync при отправки пакет!

### ISSUE THREAD

**Issue by SedovStanislav** [diadoc/diadocsdk-1c-docs#242]
Не могу понять принципиальную разницу между методами Send и SendAsync при отправки пакета. Я понимаю что создаются два разных объекта, но результат выполнения один. Расскажите разницу между методами/результатами их работы, буду признателен за пример отличия. Каким методом лучше пользоваться при отправки документов?

**Comment by GilimkhanovDenis** [comment]
**Какой метод лучше выполнять**: зависит от архитектуры вашего приложения. Для сервера Диадока оба вызова выглядят одинаково, асинхронность достигнута на уровне внешней компоненты.
**Разница**: один метод синхронный, другой асинхронный.
