### ISSUE TITLE
HTTP API, diadoc-api.kontur.ru, Запрос подписи.

### ISSUE THREAD

**Issue by komissarovev** [diadoc/diadocsdk-1c-docs#243]
Добрый день!
Каким методом запросить подпись. Направить документ на подпись?

**Comment by GilimkhanovDenis** [comment]
Уточните, что понимаете под "запросить подпись".

Направить документ на подпись другому сотруднику можно методом https://diadocsdk-1c.readthedocs.io/ru/latest/CreateResolutionRequestTask.html

**Comment by komissarovev** [comment]
"запросить подпись" Направить документ на подпись в организацию конкретному сотруднику этой организации имеющему сертификат ЭЦП.

Как можно обратиться к методу CreateResolutionRequestTask? Есть пример?
Это точно метод HTTP API?
 "diadoc-api.kontur.ru/V3/CreateResolutionRequestTask?boxId="+boxId+"&messageId="+messageId+"&entityId="+entityId;

**Comment by GilimkhanovDenis** [comment]
Как указано в документации, CreateResolutionRequestTask - метод объекта Document. Он не является методом HTTP-API, но является методом компоненты. В HTTP-API используйте метод http://api-docs.diadoc.ru/ru/latest/http/PostMessagePatch.html с заполненным ResolutionRequestAttachment в теле запроса
