### ISSUE TITLE
Прислан акт в формате pdf

### ISSUE THREAD

**Issue by IrinaZ86** [diadoc/diadocsdk-1c-docs#244]
Добрый день! Настраиваю API для работы с нашей системой. Использую Com-компоненту для встраивания в произвольные системы (версия 5.22.2.358). Прислали акт типа Nonformalized с прикрепленным документом в формате pdf.Скажите, есть какая-то возможность разобрать на объекты подобные документы - получить позиции, перечисленные в документы, суммы по ним и т.д.?

**Comment by GilimkhanovDenis** [comment]
Здравствуйте! Увы, разбора pdf-файлов в компоненте нет. Если бы акт прислали так же в pdf формате, но с типом AcceptanceCertificate (см. http://1c-docs.diadoc.ru/ru/latest/AcceptanceCertificateContent.html), то можно было бы получить общие сведения о переданном документе, но табличной части в нём тоже нет возможности получить.
Единственный вариант, когда можно получить табличную часть документа - формализованный акт.
Разбор pdf-файлов в планы разработки не входит, по крайней мере, на данный момент.
