### ISSUE TITLE
status

### ISSUE THREAD

**Issue by rewiel** [diadoc/diadocsdk-1c-docs#245]
Добрый день подскажите, есть ли возможность менять статус с помощью API.
1)Необходимо после сверки в БД менять статус у конкретного документа на "ожидание подписи".
2) GetDocument возвращает content.data с русскими атрибутами, возможно ли как-то автоматизированно поменять их согласно вашим xsd схемам на латинские, для дальнейшего парса, или есть метод для этого?

**Comment by GilimkhanovDenis** [comment]
1) Если документ в Диадоке был отправлен с запросом подписи или его документооборот по умолчанию подразумевает, что нужна ответная подпись, то поле RecipientResponseStatus  документа будет иметь значение “WaitingForRecipientSignature” - ожидается ответное действие получателя. Поле только для чтение и меняется после ответного действия по документу (см. https://diadocsdk-1c.readthedocs.io/ru/latest/Document.html)
2) При вызове метода [GetContent()](https://diadocsdk-1c.readthedocs.io/ru/latest/GetContent-(BaseDocument).html) возвращается "Объект титула продавца, производный от BaseContent". О каких русских аттрибутах речь? Можете привести пример?
