### ISSUE TITLE
HTTP API, diadoc-api.kontur.ru, Запрос подписи. 2

### ISSUE THREAD

**Issue by komissarovev** [diadoc/diadocsdk-1c-docs#246]
В Продолжение темы https://github.com/diadoc/diadocsdk-1c-docs/issues/243
Был в отпуске не успел ответить.

Спасибо, смотрю метод
/V3/PostMessagePatch

В теле запроса должно содержаться отправляемое дополнение к сообщению, сериализованное в протобуфер MessagePatchToPost.

Не могу поянть как сериализовать MessagePatchToPost. У вас есть пример?

**Comment by etalipov** [comment]
Добрый день!
Пример передачи документа на подпись с помощью HTTP-API и Postman
![default](https://user-images.githubusercontent.com/34828350/44714382-9a174000-aace-11e8-9f53-147bf555723b.png)

**Comment by komissarovev** [comment]
Заполнил MessagePatchToPost JSON тип строка.
Возвращает ответ: BoxId field is not valid box id:
Может еще какие-то HTTP заголовки нужны? у меня такие заполнены

(POST /V3/PostMessagePatch HTTP/1.1)
("Host", "diadoc-api.kontur.ru")
("Authorization", "DiadocAuth ddauth_api_client_id="+ddauth_api_client+",ddauth_token="+ПолеДокумента1)
("MessagePatchToPost", СтрJSON)

**Comment by etalipov** [comment]
Добрый день!
Заголовки передаются следующие:
![default](https://user-images.githubusercontent.com/34828350/44834768-86ddaf00-ac4b-11e8-978c-0e4ef41742da.png)

Пришлите скриншот заполнения boxid.
