### ISSUE TITLE
Порядок соответствия ИдОтпр и ИдПок  после обновления от 20.08

### ISSUE THREAD

**Issue by Fibba** [diadoc/diadocsdk-1c-docs#247]
Добрый день. Несколько дней назад к нам обратился один из клиентов с вопросом "почему у нас перепутано содержимое атрибутов "ИдОтпр" и "ИдПок" в актах формата XmlAcceptanceCertificate?". Как выяснилось из общения с онлайн-консультантом, "...был изменен порядок таким образом, чтобы seller соответствовал ИдПок, buyer - ИдОтпр." т.е. по этой информации подразумевается, что теперь нам необходимо, чтоб данные нашей организации соответствовали атрибуту "ИдОтпр", заполнить объект контента "Buyer", вместо "Seller"-а. 

Обновили Com-компоненту на сервере до актуальной версии (5.22.2.358), запустили формирование и заполнение контента, но никакого Buyer-а там нет.
![image](https://user-images.githubusercontent.com/42743750/44667011-5d8e0a80-aa22-11e8-91fe-7da925ebb1c0.png)

что мы делаем не так? или как нам интерпретировать последние обновления связанные с ИдОтпр и ИдПок?

**Comment by GilimkhanovDenis** [comment]
На COM-объекте это никак не отражается. Изменения касаются только генерируемого xml-файла титула отправителя

**Comment by GilimkhanovDenis** [comment]
Нет, ничего не требуется
