### ISSUE TITLE
HTTP API, метод /V3/PostMessage

### ISSUE THREAD

**Issue by komissarovev** [diadoc/diadocsdk-1c-docs#248]
Добрый день!
Нужно передать в диадок pdf файл, чтобы его в дальнейшем подписать.
Использую метод /V3/PostMessage
В структуре данных метода заполняю MessageToPost
В ней есть поле DocumentAttachment. Не пойму как передать файл? какой тип данных должен быть?
Двоичные данные строкой?

**Comment by etalipov** [comment]
Добрый день!
Пример отправки документа через Postman
![default](https://user-images.githubusercontent.com/34828350/44900412-ef955c00-ad1d-11e8-949a-dbe474d60641.png)

Файл передается поле Content в виде base64 строки
![default](https://user-images.githubusercontent.com/34828350/44900493-279c9f00-ad1e-11e8-9ce4-0c0b4cb1e4b0.png)

http://api-docs.diadoc.ru/ru/latest/proto/SignedContent.html?highlight=signedcontent

Просьба дальнейшие вопросы по HTTP-API адресовать в соответствующий репозиторий:
https://github.com/diadoc/diadocapi-docs/issues
Данный репозиторий относится к внешней компоненте.
