### ISSUE TITLE
Подпись входящего УПД

### ISSUE THREAD

**Issue by IrinaZ86** [diadoc/diadocsdk-1c-docs#249]
Использую компоненту для внешних систем версия 5_22_2_358
Хочу подписать входящий УПД через API
При подписании выдает ошибку: ReplySendTask.Send: ##100[Ошибка сервера Диадок]code:400, HTTP error: Info.DocumentCreator is required

используемый код:
               Set objPack = objDoc.CreateReplySendTask("AcceptDocument")						
		objPack.Content.AcceptanceDate = Now		
		Set Signer = objPack.Content.AddSigner()
		Signer.SignerDetails.Surname = "Фамилия"		
		Signer.SignerDetails.FirstName = "Имя" 
		Signer.SignerDetails.Patronymic = "Отчество" 
		Signer.SignerDetails.JobTitle = "Директор"
		Signer.SignerDetails.SignerType = "LegalEntity" 
		Signer.SignerDetails.Inn = "1111111111"
		Signer.SignerDetails.Powers = "MadeAndResponsibleForOperationAndSignedInvoice"	
		Signer.SignerDetails.OrganizationName = {Организация}
		
		objPack.Send
Какие данные еще нужно заполнить чтобы подписать документ?

**Comment by GilimkhanovDenis** [comment]
Заполните
objPack.Content.Creator
https://diadocsdk-1c.readthedocs.io/ru/latest/UtdBuyerContent.html?highlight=Creator
