### ISSUE TITLE
На отправку через модуль интеграции для 1С не попадают авансовые счета фактуры, основание которых - взаимозачёт задолженности.

### ISSUE THREAD

**Issue by SuperioMax** [diadoc/diadocsdk-1c-docs#25]
Здравствуйте! Компания Азия Цемент (ИНН 7713591359). Мы используем доработанную конфигурацию 1C: ERP. Модуль интеграции для Диалок дорабатывали своими силами, но столкнулись со следующей проблемой, которую сами решить не можем. Не попадают вообще в список для отправки счета-фактуры (аванс), основанием которых является взаимозачёт задолженности.
Соответственно, не можем их отправить. 
В конфигураторе 1С видно, что список документов для отправки формируется в закрытом блоке (двоичные данные), соответственно не можем ничего там проанализировать и отладить.
Прошу помочь!

**Comment by denver069** [comment]
Добрый день!
Тексты запросов для формирования списка документов на отправку Для конфигурации 1С:ERP размещены макете Модуль_ИнтеграцияУТ11, но вызов методов этого модуля выполняется в макете Модуль_ИнтеграцияУниверсальный. Эти макеты представляют из себя внешние обработки 1С. Для изменения обработок, сохраните данные макетов в файлы с расширением epf. Начать анализ кода рекомендую с функции СформироватьТЗВыгрузкиВДиадок в макете Модуль_ИнтеграцияУниверсальный.

**Comment by SuperioMax** [comment]
Спасибо, информация была полезна на 10 из 10!
