### ISSUE TITLE
Ошибка получения контента документа в версии АПИ 5.22.3.364

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#250]
Добрый день.

После установки последней версии АПИ 5.22.3.364 для документов типа InvoiceCorrection при попытке получения контента происходит ошибка:

_Ошибка при вызове метода контекста (GetContent): Произошла исключительная ситуация (InvoiceCorrection.GetContent): bad_weak_ptr_

**Comment by GilimkhanovDenis** [comment]
Выпустили hotFix 5.22.4.365. Проверьте на нём

**Comment by JohnSergeev** [comment]
Добрый день.
На новой версии 5.22.4.365 для InvoiceCorrection функция GetContent выполняется без ошибок.

**Comment by GilimkhanovDenis** [comment]
Тогда тикет закрываю
