### ISSUE TITLE
HTTP API, метод /V3/PostMessage, DocumentAttachment

### ISSUE THREAD

**Issue by komissarovev** [diadoc/diadocsdk-1c-docs#251]
Добрый день! Пишу в ветку 1с. Потому-что в ветке diadocapi-docs никто не отвечает. 
https://github.com/diadoc/diadocapi-docs/issues/381 - 7 дней ответа нет

В продолжение diadoc/diadocsdk-1c-docs#248
Ругается что слишком большой заголовок. А в заголовок вставлен файл. Может что-то нужно еще в заголовках указать?
Метод возвращает сообщение:

400 Request Header Or Cookie Too Large
400 Bad Request
Request Header Or Cookie Too Large
nginx

Сделал так в заголовок MessagePatchToPost вставил это:
{
"FromBoxId": "2d1f65f6-b08a-41b8-90e8-7f60f36cd57d",
"IsInternal": true,
"DocumentAttachments": [
{
"SignedContent": {
"Content": "ыаываываываываываываыв_много букв base64 "
},
"TypeNamedId": "Nonformalized",
"Metadata": [
{
"Key": "FileName",
"Value": "test.pdf"
}
]
}
]
}

**Comment by GilimkhanovDenis** [comment]
Это тело запроса, а не header
```
Сделал так в заголовок MessagePatchToPost вставил это:
{
"FromBoxId": "2d1f65f6-b08a-41b8-90e8-7f60f36cd57d",
"IsInternal": true,
"DocumentAttachments": [
{
"SignedContent": {
"Content": "ыаываываываываываываыв_много букв base64 "
},
"TypeNamedId": "Nonformalized",
"Metadata": [
{
"Key": "FileName",
"Value": "test.pdf"
}
]
}
]
}
```

**Comment by komissarovev** [comment]
![image](https://user-images.githubusercontent.com/36499475/45305100-41aa5e80-b522-11e8-803f-00021381ac16.png)
Спасибо, что поправили.
Теперь пишет сообщение: Can't deserialize request body into type: MessageToPost
Что может быть не так?
