### ISSUE TITLE
TotalNet в  InvoiceTable

### ISSUE THREAD

**Issue by iolko** [diadoc/diadocsdk-1c-docs#254]
Ссылка на описание: 
https://diadocsdk-1c.readthedocs.io/ru/latest/InvoiceTable.html

TotalNet (число с плавающей запятой/строка, чтение/запись) - нетто всего, при передаче в это поле числа, оно проставляется в документе  ТОРГ -12  в поле: Масса груза (нетто).
Допустим, передаем 150. В печатной форме документа ТОРГ-12, будет проставлено 150.

Но в это поле должно записаться "Масса нетто прописью", если передать в качестве параметра строку, допустим Сто пятьдесят", система выдает ошибку. 

Выгрузка происходит из 1С 7,7, версия [компоненты:]
5.22.4.365

**Comment by GilimkhanovDenis** [comment]
Насколько понимаю, речь идёт только о печатной форме в вебе или модуле 1С.

Согласно формату УПД, в котором сейчас передаётся документ, в "Итогах" нет поля для массы нетто прописью - только числовое значение
https://normativ.kontur.ru/document?moduleId=1&documentId=271958&rangeId=116636

"Нетто прописью" есть в формате 172 приказа: https://normativ.kontur.ru/document?moduleId=1&documentId=261859&rangeId=116637 - передавайте документ в этом формате (в компоненте это объект [Torg12SellerContent](https://diadocsdk-1c.readthedocs.io/ru/latest/Torg12SellerContent.html))
