### ISSUE TITLE
Метод SetOneSDocumentId

### ISSUE THREAD

**Issue by iolko** [diadoc/diadocsdk-1c-docs#255]
Добрый день!

Получаю список документов:

`	DocumentsTask = Организация.GetDocumentsTask();
	//Получаем вообще все исходящие документы
	DocumentsTask.Category = "Any.Outbound";
	DocumentList = DocumentsTask.GetDocuments();
	Для Сч = 0  По DocumentList.Count() -1 цикл
		Document = DocumentList.GetItem(Сч);	
		Если СтрДлина(Document.CustomDocumentId) > 0 Тогда
			Document.SetOneSDocumentId (Document.CustomDocumentId);
			Сообщить (Строка(Сч) + Document.OneSDocumentId); // вижу, что установлен
		КонецЕсли;	
	КонецЦикла;		
`
Следующим циклом пробегаю по тем же документам и вывожу 
Сообщить (Строка(Сч) + Document.OneSDocumentId); 

Окно сообщений выводит только Сч

Пробовал перед SetOneSDocumentId делать Document.ReSetOneSDocumentId();

Так же не получается.

Документы исходящие, просто изначально мы записывали ИД в Document.CustomDocumentId, потом решили переделать на правильно, но не получается. 

В чем может быть дело ?

версия [компоненты:]
5.22.4.365

PS
**Вспомнил почему записываем Ид документа 1С в поле "Document.CustomDocumentId", потому что  при отправке  в такой конструкции:
DocumentToSend = PackageSendTask.AddDocument ("UtdTorg12"); 
мы получаем  UtdSellerContent, где нет поля OneSDocumentId, так же таких полей нет, при отправке:  DocumentToSend = PackageSendTask.AddDocument ("UtdInvoice");**

![snag-0050](https://user-images.githubusercontent.com/26030755/45675073-a1bf8700-bb58-11e8-9624-939ad1b59b49.png)
![snag-0051](https://user-images.githubusercontent.com/26030755/45675074-a1bf8700-bb58-11e8-91e5-02fe14fb8adc.png)

**Comment by iolko** [comment]
Не понятно почему Label "help wanted", приведен кусок кода, а так же скрины, где видно, что это "bug"

**Comment by GilimkhanovDenis** [comment]
Кроме поля Category в объекте DocumentsTask какие-то поля заполняются? Если да, то которые и какими значениями

**Comment by GilimkhanovDenis** [comment]
Асинхронный метод получения документов не учитывал флаг RequireOneSDocumentId (исправлено в v5.24.1). Установите этот флаг в истину
