### ISSUE TITLE
ОШИБКА - при формировании запросов на аннулирование и отказе от аннулирования в данные Resolutions не попадают комментарии!

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#256]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас с версии АПИ 5.19.1.282 планируем переход на версию АПИ 5.22.4.365.

Совершенно случайно заметили на версии АПИ 5.22.4.365 следующее:

Если сделать запрос на аннулирование и указать комментарий, используя вызов Документ.SendRevocationRequest(Комментарий), то произойдет следующее:

1. Все прекрасно выполнится и по документу появится запрос на аннулирование (он получит нужный статус "RevocationIsRequestedByMe").
2. У вас на сайте прекрасно отобразится информация об этом. **И там будет присутствовать введенный комментарий**:
![default](https://user-images.githubusercontent.com/33707226/45867354-a1c4be80-bdc6-11e8-828e-f3f3a5aef0c4.png)
3. В данных документа .Resolutions появится запись о запросе на аннулирование.

 **НО! ОШИБКА! Там не будет комментария!**

![default](https://user-images.githubusercontent.com/33707226/45867562-0e3fbd80-bdc7-11e8-8222-d3c4f83b9d1c.png)
4. Через вашу новую систему комментариев GetAnyComment() эти данные тоже получить нельзя - нет такого параметра!
![default](https://user-images.githubusercontent.com/33707226/45867794-97ef8b00-bdc7-11e8-9954-60ecb994c002.png)

Подобное поведение одинаково и для входящего документа, и для исходящего (у нас 2 тестовых ящика и мы смотрели на документ как на исходящий в одном ящике и как на входящий в другом).

**Точно такое же поведение и для операции отказа от аннулирования**, используя вызов Документ.RejectRevocationRequest(Комментарий).

**При этом в версии АПИ 5.19.1.282 все работает правильно и заданные комментарии в Resolutions попадают!**

Большая просьба разобраться в проблеме и исправить такое странное поведение.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Исправлено в версии 5.22.5.373
