### ISSUE TITLE
ОШИБКА! Не соответвие документации и объектов АПИ 

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#257]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас с версии АПИ 5.19.1.282 планируем переход на версию АПИ 5.22.4.365.

Совершенно случайно заметили на версии АПИ 5.22.4.365 следующее:

У вас еще для версии 5.21.7 было декларировано логгирование ошибок у ReceiptGenerationProcess:
![default](https://user-images.githubusercontent.com/33707226/45868819-14836900-bdca-11e8-99e2-55ea9e12b8e1.png)
![default](https://user-images.githubusercontent.com/33707226/45868853-2533df00-bdca-11e8-815c-e660bcacbc84.png)

Однако в версии АПИ 5.22.4.365 объект ReceiptGenerationProcess после выполнения, например, такого кода:
![default](https://user-images.githubusercontent.com/33707226/45868922-544a5080-bdca-11e8-8303-561c69b1fb63.png)

имеет следующие свойства:
![default](https://user-images.githubusercontent.com/33707226/45868932-5f04e580-bdca-11e8-81c6-1ee441a6cb2e.png)

Во-первых, здесь нет вышеуказанной коллекции Errors!
Во-вторых, есть свойсво IsRun, не отмеченное в документации (кстати, оно у вас в разных версиях то появляется, то исчезает).

Вопросы:
1. Как должно быть на самом деле?
2. Будет ли это странное несоответствие документации и документируемых объектов исправлено?
3. Если вдруг у вас свойство Errors появляется только, если ошибки реально есть, то это неверный дизайн объекта! Проверить наличие или отсутствие свойства в вашем АПИ невозможно - а значит для доступа к нему постоянно придется использовать обращение в попытке - что не очень хорошо. Пусть лучше, если ошибок нет - коллекция будет пустой - это же логичнее!

Надеемся на разъяснение этого вопроса и скорейшее исправление замеченного расхождения.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Это поле оказалось добавлено только в компоненту AddIn. Поправим в ближайшем релизе

**Comment by GilimkhanovDenis** [comment]
Исправлено в версии 5.22.5.373
