### ISSUE TITLE
Транзакционный механизм при отправке документов

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#26]
Необходимо отправить пакет из 3 документов, например "Накладная"+"Сч.фактура"+"Неформализованный PDF". Как вариант, Накладная и Сч.ф. отправляются нормально, а "Неформализованный PDF" отправиться не может, из-за внутренней ошибки со стороны Отправителя, например "Не удалось получить PDF файл из-за блокировки" или "Произошел разрыв связи" и т.д.

Для нас важно, чтобы ушел весь пакет целиком или ни одного документа из пакета.
Удалять документы, которые уже были отправлены - на мой взгляд, плохое решение.

Решение вижу, как отправку документов через транзакцию, т.е. либо все документы отправляются, либо ни одного, поддерживаются ли такой механизм при отправке документов? 
(Механизм подобен механизму транзакций в СУБД)

Какое решение предложите Вы?

**Comment by denver069** [comment]
Используйте для отправки документов объект [PackageSendTask](http://1c-docs.diadoc.ru/ru/latest/PackageSendTask.html), т.к. в таком случае документы будут отправлены одним сообщением.
