### ISSUE TITLE
Ошибка при подписании облачной подписью

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#261]
Подскажите, пожалуйста, с чем может быть связана ошибка: (CloudSignTask.AddContent): ##100[Ошибка сервера Диадок]code:400, HTTP error: info.Employee.Employee.EmployeePosition is required

**Comment by GilimkhanovDenis** [comment]
При добавлении контента титула покупателя заполните поле EmployeePosition объекта Employee
http://1c-docs.diadoc.ru/ru/latest/UtdBuyerContent.html
