### ISSUE TITLE
Проблема с отправкой из черновиков в последних версиях компоненты

### ISSUE THREAD

**Issue by DmVKonst** [diadoc/diadocsdk-1c-docs#262]
Здравствуйте!
Являемся интеграторами и используем COM-компоненту (x32) для встраивания в произвольные системы.
В последних версиях перестали подписываться документы при отправке с использованием методами Organization.CreateSendDraftTask() - SendAsync().
Точно сказать с какой версии перестало работать не могу, но в версии 5.23.0.374 уже точно не работает, в 5.20.3.304 - точно работает.

Использую следующий алгоритм (кратко, чтобы было понятно, что в каком порядке вызывается):

1. Авторизация по сертификату, поиск контрагента. Здесь проблем нет

2. Создание черновика. Здесь тоже все работает на всех версиях
oPackageSendTask = Organzation.CreatePackageSendTask();
oPackageSendTask.CounterAgentId   = …; определен раньше 
oPackageSendTask.OperationId      = … ; новый гуид
oPackageSendTask.IsDraft          = 1;
Добавляем файлы в пакет (формализованные и неформализованные):
oDocToSend = oPackageSendTask.AddDocumentFromFile( тип, путь )
# для формализованных в oDocToSend ничего не заполняю, для неформализованных - дату, номер, необходимость подписи получателем.
# Signer-ы не заполняю - они будут указаны при отправке черновика.
Cохраняем в черновики:
oPackageSendTask.SendAsync()
Из результата сохраняю PackageId - он будет использоваться в п.3
Пакет появляется в черновиках. Если в браузере нажать отправить - подписывается и отправляется без проблем

3. Отправка черновика (по времени может быть сильно оторвана от п.2):
oSendDraftTask = Organzation.CreateSendDraftTask(PackageId)
Заполняю Signer данными (из свой системы, по сути - из сертификата)
oSendDraftTask.Signer.IsSoleProprietor                  = 0;
oSendDraftTask.Signer.Surname                            = Фамилия;
oSendDraftTask.Signer.FirstName                          = Имя;
oSendDraftTask.Signer.Patronymic                         = Отчество;
oSendDraftTask.Signer.JobTitle                               = Должность;
oSendDraftTask.Signer.INN                                    = ИНН;
oSendDraftTask.Signer.SoleProprietorRegistrationCertificate  = "";
и ExtendedSigner для УПД (добавляю всегда, независимо от того, есть в пакете УПД или нет): 
oExtendedSigner = oSendDraftTask.AddExtendedSigner()
oExtendedSigner.SignerDetails.Surname        = Фамилия;
oExtendedSigner.SignerDetails.FirstName      = Имя;
oExtendedSigner.SignerDetails.Patronymic     = Отчество;
oExtendedSigner.SignerDetails.JobTitle       = Должность; # не обязательно
oExtendedSigner.SignerDetails.Inn            = ИНН;
oExtendedSigner.SignerDetails.SignerType     = "LegalEntity";
oExtendedSigner.SignerDetails.Powers         = "ResponsibleForOperationAndSignerForInvoice";
oExtendedSigner.SignerDetails.Status         = "SellerEmployee";
oExtendedSigner.SignerDetails.PowersBase     = "Должностные обязанности"
т.е. заполнение из "сохраненных" не использую - всегда заполняю перед отправкой

oSendDraftTask.SendAsync(). Ошибок и исключений не дает
В ответ приходит то, что и видим в кабинете:
в версии 5.20.3.304 - пакет успешно подписан и отправлен.
в версии 5.23.0.374 - в кабинете пакет появляется в исходящих, но у него состояние "Ошибка при подписании документа", "Подписанные данные были искажены после момента подписания" (в ответе: SenderSignatureStatus="SenderSignatureUnchecked"). Если нажать отправить - подписывается и отправляется без проблем.
Возникает как при отправке отдельно неформализованного/формализованного документа, так и при их совместной отправке.

Может в новых версиях что-то заполнять по-другому надо?
Примечание: Клиентов много, проблема наблюдается у всех одинаковая, независимо от клиентской ОС

**Comment by GilimkhanovDenis** [comment]
Исправлено в v5.24.1
