### ISSUE TITLE
Ошибка при отправке документа с использованием облачной подписи

### ISSUE THREAD

**Issue by Sergguha** [diadoc/diadocsdk-1c-docs#263]
Добрый день!
Версия компоненты 5.24.0.377 для 1с. После заполнения контента документа UniversalTransferDocument и подтверждения его Confirm кодом облачной подписи из СМС при вызове метода Send возникает ошибка:
_Произошла исключительная ситуация (SendTask.Send): Для подписания и отправки юридически значимого документа необходимо выполнить вход по сертификату_
На найденной более старой версии (5.22.4.365) подобной ошибки не возникает и документ успешно отправляется.

**Comment by GilimkhanovDenis** [comment]
исправлено в v5.24.1
