### ISSUE TITLE
Получение типа статуса согласования Doc.ResolutionStatus.Type

### ISSUE THREAD

**Issue by zelinskayas** [diadoc/diadocsdk-1c-docs#264]
Подскажите пожалуйста, как правильно получить тип статуса согласования.
Были попытки таким образом:
Doc := DocList.GetItem(i);
Doc.ResolutionStatus.Type;
Если документ не согласовывался еще, то падает с пустотой, то есть вот эта часть Doc.ResolutionStatus = $00000000. 
По идее должен быть Type = None.
https://diadocsdk-1c.readthedocs.io/ru/latest/ResolutionStatus.html

**Comment by azhipaigor** [comment]
Здравствуйте! Это особенность АПИ Диадока, если нет ResolutionStatus, то просто не возвращается объект (http://api-docs.diadoc.ru/ru/latest/proto/ResolutionStatus.html).
