### ISSUE TITLE
Ошибка при вызове метода "GetDocumentById"

### ISSUE THREAD

**Issue by Alex463** [diadoc/diadocsdk-1c-docs#265]
Добрый день! При вызове метода GetDocumentById() выходит сообщение об ошибке: 
"Ошибка при вызове метода контекста (GetDocumentById): Произошла исключительная ситуация (MyBox.GetDocument): vector<T> too long"
Стала возникать после обновления компоненты на 5.24.2.386

фрагмент кода:
Организация = DiadocConnection.GetOrganizationById(ИДОрганизации);
ЭД = Организация.GetDocumentById(ИДДокумента);
				
ИДОрганизации - "098ab78bca5342ae89f9fd07ca3d320b@diadoc.ru"
ИДДокумента - "43ac7456-3f33-42b8-8690-9ebaafd7f108b87c7027-c02c-40a8-97c5-78655c84b653"
Ссылка на док: https://diadoc.kontur.ru/098ab78b-ca53-42ae-89f9-fd07ca3d320b/Document/Show?letterId=43ac7456-3f33-42b8-8690-9ebaafd7f108&documentId=b87c7027-c02c-40a8-97c5-78655c84b653

Можете подсказать как исправить?

**Comment by GilimkhanovDenis** [comment]
Попробуйте на новой версии компоненты

**Comment by Alex463** [comment]
Спасибо, поставил компоненту 5.25.0.394, ошибок нет
