### ISSUE TITLE
Не работает метод Document.CreateReplySendTask()

### ISSUE THREAD

**Issue by pavlmax** [diadoc/diadocsdk-1c-docs#266]
Добрый день. 

Используем актуальную версию компоненты DiadocCom_5_25_0_394_x64.dll
COM-компонента для встраивания в произвольные системы, для 64-х битных приложений - 5.25.0.394

Выполняется следующий код:
ДиадокСоединение = ДиадокАПИ.CreateConnectionByCertificate(Отпечаток);
    
    OrganizationList = ДиадокСоединение.GetOrganizationList();
    Organization = OrganizationList.GetItem(0);
    
    DocumentsTask = Organization.GetDocumentsTask();
    DocumentsTask.FromSendDate = НачалоГода(ТекущаяДата());
    DocumentsTask.ToSendDate = КонецГода(ТекущаяДата());
    DocumentsTask.Category = "XmlTorg12.InboundWaitingForRecipientSignature";
    
    DocumentList = DocumentsTask.GetDocuments();
    
    ц = 0;
    Пока ц < DocumentList.Count Цикл
        Document = DocumentList.GetItem(ц);
        
        ReplySendTask = Document.CreateReplySendTask();
       ....
   КонецЦикла;

При вызове Document.CreateReplySendTask() возникает ошибка:

Произошла исключительная ситуация (DocumentBase.CreateReplySendTask): ##100[Ошибка сервера Диадок]code:403, HTTP error: Access to Box [9ef604cc-701c-4a76-8a94-c53bf009800e] is denied

где 9ef604cc-701c-4a76-8a94-c53bf009800e это ID ящика контрагента от которого поступил входящий документ.

В чем может быть дело?

**Comment by pavlmax** [comment]
Уточнение - если делать 
ReplySendTask = Document.CreateReplySendTask("RejectDocument");
то ошибки нет.

**Comment by pavlmax** [comment]
Если использовать вызов ReplySendTask = Document.CreateReplySendTask("AcceptDocument"); то ошибка та же самая.

**Comment by GilimkhanovDenis** [comment]
Этот тикет закрываю. решение будет в 
https://github.com/diadoc/diadocsdk-1c-docs/issues/267
