### ISSUE TITLE
Идентификатор 1С для документа отправляемого в составе пакета

### ISSUE THREAD

**Issue by AndreyKITO** [diadoc/diadocsdk-1c-docs#268]
Здравствуйте!
 
На нашем предприятии используется интеграция с системой Диадок посредством внешней компоненты AddIn Diadoc API (версия dll-ки: v.2.05.07b). В связи с адаптацией к нашим учетным задачам обработок обмена между 1С и Диадок (полученных от Диадок) есть необходимость в помощи в решении следующего вопроса:
Суть:
При отправке одиночного документа в Диадок применяется метод «CreateSendTask» объекта «Organization». При этом создается объект «SendTask». У этого объекта есть свойство «OneSDocumentId», установив значение которого, возможно установить связь с объектом базы 1С.
Для отправки пакета документов, согласно инструкциям, следует воспользоваться методом «CreatePackageSendTask» объекта «Organization».  При этом будет создан объект «PackageSendTask». Добавить документ в этот объект можно методом «AddDocument» или «AddDocumentFromFile». Результатом использования любого из этих методов будет объект «DocumentToSend». 
Вопрос: 
Каким образом, для отправляемого в составе пакета документа, установить связь с объектом базы данных 1С?

**Comment by GilimkhanovDenis** [comment]
В модуле для 1С 7.7 логика такая:
1) Заполняется PackageSendTask
2) PackageSendTask.Send()
3) После выполнения пункта 2 получаем коллекцию отправленных документов и для каждого вызывается https://diadocsdk-1c.readthedocs.io/ru/latest/SetOneSDocumentId.html
