### ISSUE TITLE
Ставка НДС 20%

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#269]
С 01.01.2019 будет ставка НДС 20%. Если сейчас формировать и передавать УПД (через компоненту DiadocComApi) возникает ошибка: ##100[Ошибка сервера Диадок]code:400, HTTP error: Info.InvoiceTable.Items[0].TaxRate is invalid for UTD: Percent_20.
Будет ли новая версия компоненты, поддерживающая ставку 20% или все заработает с 01.01.2019?

**Comment by GilimkhanovDenis** [comment]
Компонента поддерживает ставку 20% и 20/120
Возможность работы зависит от сервера Диадок, где сейчас работа с этой ставкой отключена

**Comment by prog22** [comment]
Подскажите пожалуйста, начиная с какой версии? Мы используем старую версию компоненты 5.18.5.245 x64.
