### ISSUE TITLE
##200[Ошибка передачи данных через интернет]WinHttpSendRequest error , error = 12175 (0x2f8f)

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#27]
добрый день
Возникла техническая проблема при работе через Диадок API (DiadocComApi.dll).
Соединение программно устанавливается (по логину/паролю).
Тест соединения проходит.
При попытке передачи данных возвращает ошибку:
{….}: Ошибка при вызове метода контекста (Send)
  SendTask.Send(); 
по причине:
Произошла исключительная ситуация (SendTask.Send): ##200[Ошибка передачи данных через интернет]WinHttpSendRequest error , error = 12175 (0x2f8f) 
С чем это может быть связано?
Код результата диагностики (утилита https://help.kontur.ru/check) = 3116404.

**Comment by denver069** [comment]
Судя по коду ошибки [12175](https://msdn.microsoft.com/ru-ru/library/windows/desktop/aa383770(v=vs.85).aspx) объекта WinHttpSendRequest - это ошибка сертификата в SSL. Данная ошибка не связана с работой внешней компоненты. Обратитесь в службу поддержки https://kontur.ru/support
