### ISSUE TITLE
не работает GetUsers

### ISSUE THREAD

**Issue by mishgan75** [diadoc/diadocsdk-1c-docs#271]
Произошла исключительная ситуация (MyBox.GetUsers): ##100[Ошибка сервера Диадок]code:402, HTTP error: Доступ запрещён. Необходима оплата тарифа АПИ.
 Все Оплачено.

**Comment by 1swd** [comment]
Добрый день!
Это ошибка связана неактивной подпиской и оплатой. Сообщите, пожалуйста ваш ИНН КПП здесь, либо вместе с описанием ошибки на почту diadoc@skbkontur.ru

**Comment by mishgan75** [comment]
Счет выписан на 8 организаций. Счет оплачен, Ваша коммерческая служба просто не в состоянии договорится с тех отделом, результатом которой периодически отключают от доступа ту или иную организацию. Почему выбранная такая идиотская, схема контроля. Если Ваша организация считает что ей не хватает денег ну не давали бы доступ до сервера, пока денег не дадут, Ваша же система выстроена таким образом, что позволяет отправлять документы, но не дает возможности подписать уже отправленный документ. В результате такой "Подлянки" На вашем сервере уже скопилось 300-400 экземпляров одного документа которые невозможно подписать. Как правильно их  удалить c Вашего сервера?
