### ISSUE TITLE
Возможность подписания с уточнением.

### ISSUE THREAD

**Issue by sharafutdinov1987** [diadoc/diadocsdk-1c-docs#272]
Подскажите, пожалуйста, есть ли возможность подписания входящих формализованных документов с уточнением/комментарием.
При отклонении документов с помощью эл. подписи возможность указания произвольной причины/комментария отказа есть. Есть похожая возможность передачи уточнения при утверждении эл. подписью.?

**Comment by GilimkhanovDenis** [comment]
Для формализованного акта 172 приказа можно заполнить поле Complaints
https://diadocsdk-1c.readthedocs.io/ru/latest/AcceptanceCertificateBuyerContent.html
Для документов в 155, 551 и 552 формате это разногласия попадают в тэг
<СвПрин СодОпер="Принято с разногласиями: Разногласия" ДатаПрин="05.12.2018">
что аналогично заполнению поля OperationContent соответствующего объекта

см. https://diadocsdk-1c.readthedocs.io/ru/latest/ReplySendTask.html
https://diadocsdk-1c.readthedocs.io/ru/latest/TovTorgBuyerContent.html
https://diadocsdk-1c.readthedocs.io/ru/latest/Act552BuyerContent.html
