### ISSUE TITLE
Компонента поддерживает ставку 20% и 20/120

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#273]
Возможность работы зависит от сервера Диадок, где сейчас работа с этой ставкой отключена

_Originally posted by @GilimkhanovDenis in https://github.com/diadoc/diadocsdk-1c-docs/issues/269#issuecomment-444019091_

Подскажите пожалуйста, начиная с какой версии? Мы используем старую версию компоненты 5.18.5.245 x64.

**Comment by GilimkhanovDenis** [comment]
5.25.0
см. http://1c-docs.diadoc.ru/ru/latest/History.html
