### ISSUE TITLE
Подписание XmlAcceptanceCertificate

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#274]
При подписании документа с id = "aba46827-254b-459b-849f-11eaba068e883cca7bae-1a15-4e8e-87e0-c038baf7e103" возникает ошибка: Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid generated title: Metadata errors: Could not get metadata by key: /Файл/СвУчДокОбор/@ИдОтпр.

Титул покупателя:
![image](https://user-images.githubusercontent.com/22831210/49508313-d27fa480-f89b-11e8-83db-4489f9ac0c91.png)

Может быть связана с версией компоненты?

**Comment by GilimkhanovDenis** [comment]
В версии 5.22.2 изменялось поведение, связанное, с заполнением тэгов ИдОтпр и ИдПок у документа "Формализованный Акт в 172 формате".  Судя по сегодняшним тикетам, используете старую версию компоненты.
Попробуйте обновить до актуальной версии. Если ошибка будет актуальной, то укажите, пожалуйста, box_id ящика, в котором находится данный документ

**Comment by GilimkhanovDenis** [comment]
Через пару дней, кстати, будет очередное обновление компоненты

**Comment by prog22** [comment]
Мы не можем выбрать стабильную версию компоненты. Дело в том, что мы используем как x64, так и x32 версию. В одной - одни ошибки, в другой - другие. Например, как с подписанием в x64, недавно. А нам нужен функционал подписания (формализованных/неформализованных) документов КЭП и облачной подписью, согласования документов, работа с пользователями и полномочиями. Посоветуете подождать новую версию?

**Comment by prog22** [comment]
> В версии 5.22.2 изменялось поведение, связанное, с заполнением тэгов ИдОтпр и ИдПок у документа "Формализованный Акт в 172 формате". Судя по сегодняшним тикетам, используете старую версию компоненты.
> Попробуйте обновить до актуальной версии. Если ошибка будет актуальной, то укажите, пожалуйста, box_id ящика, в котором находится данный документ

Да, 5.18.5.245.

**Comment by GilimkhanovDenis** [comment]
В ближайшей версии исправим ошибку из https://github.com/diadoc/diadocsdk-1c-docs/issues/267 , если вы говорите про данную ошибку

**Comment by prog22** [comment]
> Через пару дней, кстати, будет очередное обновление компоненты

Подскажите, пожалуйста, когда будет новая версия компоненты?

**Comment by GilimkhanovDenis** [comment]
Через пару минут обновится документация и можно будет скачать новую версию.
Отпишитесь, пожалуйста по результатам

**Comment by prog22** [comment]
Новая версия компоненты возвращает Act552BuyerContent и формирует type = XmlAcceptanceCertificate552BuyerTitle. Вопрос снят.
