### ISSUE TITLE
Компонента поддерживает ставку 20% и 20/120

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#275]
Возможность работы зависит от сервера Диадок, где сейчас работа с этой ставкой отключена

_Originally posted by @GilimkhanovDenis in https://github.com/diadoc/diadocsdk-1c-docs/issues/269#issuecomment-444019091_

После перехода на версию компоненты, которая поддерживает ставку 20 и 20/120 будет ли возможность протестировать передачу и подписание через сервис Диадок до 01.01.2019 в тестовом режиме? Опасаюсь ситуации, в случае которой не сможем передавать документы через Диадок 01.01.2019.

**Comment by GilimkhanovDenis** [comment]
Здравствуйте. Обратите внимание на сегодняшнюю новость: https://www.diadoc.ru/blog/7838

**Comment by prog22** [comment]
Здравствуйте. Спасибо за информацию.

**Comment by GilimkhanovDenis** [comment]
Релиз, в котором поддержали нововведения, сделанные Диадоком, вышёл
Доступен на странице http://1c-docs.diadoc.ru/ru/latest/Downloads.html
