### ISSUE TITLE
Проблема с облачной подписью 5.25.1.398 x32

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#276]
После обновления перестала работать облачная подпись входящих документов на версии 5.25.1.398 x32.
После подтверждения СМС выходит ошибка: "Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask.Send): Для подписания и отправки юридически значимого документа необходимо выполнить вход по сертификату".
На данный момент используем версию компоненты 5.21.3.321. 
Пришлось откатиться.

**Comment by prog22** [comment]
Подскажите пожалуйста, когда, примерно, будет устранена проблема?

**Comment by GilimkhanovDenis** [comment]
Релиз будет в начале недели

**Comment by GilimkhanovDenis** [comment]
Пока откладывается. В лучше случае до четверга

**Comment by GilimkhanovDenis** [comment]
Вышёл релиз 5.25.3 с исправлением ошибки
