### ISSUE TITLE
Получение файла неформализованного документа

### ISSUE THREAD

**Issue by pavlmax** [diadoc/diadocsdk-1c-docs#277]
Коллеги, подскажите, пожалуйста.

Есть задача - скачать файл неформализованного документа (в частности, неформализованного акта - AcceptanceCertificate). 

Использую для этого метод Document.SaveContent(ИмяФайла);

Но как узнать какое расширение у файла неформализованного документа (и соотв-но в файл с каким расширением его сохранять)?

**Comment by GilimkhanovDenis** [comment]
У объекта Document есть свойство [Filename](https://diadocsdk-1c.readthedocs.io/ru/latest/Document.html?highlight=FileName) - в нём можно увидеть полное имя файла и его расширение, с которым он пришёл в Диадок

**Comment by pavlmax** [comment]
Спасибо!
