### ISSUE TITLE
есть хот фикс https://disk.skbkontur.ru/index.php/s/JAPDS2YJrGysYwF

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#279]
есть хот фикс https://disk.skbkontur.ru/index.php/s/JAPDS2YJrGysYwF
// в него НЕ входит фикс #276

_Originally posted by @GilimkhanovDenis in https://github.com/diadoc/diadocsdk-1c-docs/issues/278#issuecomment-449946052_

Подскажите, эта версия будет заявляться как официальная (которая не ранее четверга) или же будет новая?

**Comment by GilimkhanovDenis** [comment]
Это неофициальная версия, на сайт она выкладываться не будет
Релиз будет позже и в него уже войдёт фикс #276 
О выпуске релиза сообщу отдельно в #276

**Comment by GilimkhanovDenis** [comment]
Вышла официальная версия. доступна на http://1c-docs.diadoc.ru/ru/latest/Downloads.html
фикс #276 в нём отсутствует - ошибка оказалась серьёзней, чем хотелось бы. информация о фиксе будет в соответствующем тикете
