### ISSUE TITLE
Произошла исключительная ситуация (SendTask.Send)

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#28]
Добрый день.
Не могу понять причину ошибки. Передаю адрес контрагента РФ, соответственно CountryCode (для иностранных контрагентов) не заполняю.

Ошибка при вызове метода контекста (Send)
  SendTask.Send(); 
по причине:
Произошла исключительная ситуация (SendTask.Send): �������� ������� �������� CountryCode � DeclarationNumber.

**Comment by denver069** [comment]
Проверьте табличную часть, скорее всего в поле номер ГТД есть какое то значение, а в поле страна происхождения значения нет.
