### ISSUE TITLE
UniversalTransferDocument как принять запрос на аннулирование?

### ISSUE THREAD

**Issue by dkamyshn** [diadoc/diadocsdk-1c-docs#280]
Добрый день.

Подскажите пожалуйста, как принять запрос на аннулирование для документа УПД с функцией СЧФ с помощью методов компоненты "AddIn Diadoc API"?

Метод Document.AcceptRevocationRequest() генерирует ошибку: "(DocumentBase.AcceptRevocationRequest): Отсутствует действующий запрос на аннулирование документа" несмотря на то, что Document.RevocationStatus = "RequestsMyRevocation" т.е. по этому документу получено входящее предложение об аннулировании.

Другого метода в документации я не нашёл
https://diadocsdk-1c.readthedocs.io/ru/latest/How-cancel.html

**Comment by GilimkhanovDenis** [comment]
Пожалуйста, уточните версию компоненты и приложите ссылку на документ в веб-интерфейсе

**Comment by dkamyshn** [comment]
После обновления компоненты, проблемы больше нет.
