### ISSUE TITLE
Проверка документа перед отправкой

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#281]
Несколько лет нормально перед отправкой документ УПД проверяли на правильность заполнения с помощью метода ValidateContent(). С нового года стало на всех документах выдавать ошибку "ставка налога для УПД не может быть 20%". Только после этого выяснилось, что метод ValidateContent() объявлен устаревшим и не рекомендуется к использованию. Но в документации не указано что именно теперь следует использовать для проверки документа перед отправкой либо как проверять статус отправленного документа.
Как решить проблему?

**Comment by GilimkhanovDenis** [comment]
Метод ValidateContent устаревший и не поддерживается.
Если документ составлен неверно, например, не хватает каких-то полей или поля имеют неверный формат, тогда ядро Диадока ответит ошибкой в терминах прото с указанием неверно заполненного поля. Сам документ отправлен не будет.
Проверки, которые хотите использовать помимо проверок на стороне Диадока рекомендуется реализовать в самой интеграции
