### ISSUE TITLE
Ошибка метода Utd.GetContent: Некорректное значение для типа НалоговаяСтавка

### ISSUE THREAD

**Issue by IrinaZ86** [diadoc/diadocsdk-1c-docs#282]
Использую COM-компоненту для встраивания в произвольные системы версии 5_22_1_354.

При попытке применить метод Utd.GetContent к входящих УПД с датой УПД 2019 года (по ним НДС 20%) - сервер выдает ошибку:
   _Utd.GetContent: ##100[Ошибка сервера Диадок]code:400, HTTP error: Некорректное значение для типа НалоговаяСтавка 'Item20' для указанной версии 'utd_05_01_04'_

Обновление версии компоненты до 5_25_4_411 не помогло - ошибка осталась.

Помогите, пожалуйста, разобраться.

**Comment by IrinaZ86** [comment]
Спасибо за быстрый ответ. После перезагрузки компьютера ошибки больше нет. Спасибо

**Comment by GilimkhanovDenis** [comment]
Тикет закрываю
