### ISSUE TITLE
Обработка шаблонов

### ISSUE THREAD

**Issue by OdintsovSergey** [diadoc/diadocsdk-1c-docs#283]
Добрый день.

К нам поступили шаблоны от контрагента.
Доступ пользователей в  ящик через web  у нас запрещен.
Мы получаем документы через AddIn Diadoc API. 
Информации в документации  по получению шаблонов нет.
При вызове  метода GetDocumentEventList данные документы не выбираются.
Как выбрать новые поступившие шаблоны?

**Comment by GilimkhanovDenis** [comment]
Такого метода нет даже на стороне ядра Диадок (см. https://github.com/diadoc/diadocsdk-csharp/issues/309#):
"К сожалению, сейчас шаблоны не возвращаются в лентах новостей. У нас эта задача есть в планах, но я пока не могу сориентировать по срокам.

Вы можете обратиться к вашему менеджеру, или передать вашу просьбу через ЦФР. Это поможет ускорить разработку."
