### ISSUE TITLE
Ошибка при заполнения ТЧ Обработки Диадок  Отправка документов

### ISSUE THREAD

**Issue by StanislavAprell** [diadoc/diadocsdk-1c-docs#284]
При заполнении табличной части "Отправка документов". При выборе типа документа "УПД счф доп"
Возникает ошибка ссылающаяся на код в модуле указанный на скриншоте. 
 #https://pastenow.ru/dd2edd675f97820d17843597cd854bc9
Как решить данную проблему?

**Comment by GilimkhanovDenis** [comment]
Конфигурация не поддерживается. Есть предположение, что это конфигурация на базе старой Управление Производственным Предприятием 1.3 или Управление Торговлей 10.3

Необходимо как минимум добавить реквизит ВидСчетаФактуры в документ СчетФактураВыданный и заполнять его аналогично последним релизам УТ 10.3

Либо можете обратиться в техподдержку и заказать доработку под свою конфигурацию
