### ISSUE TITLE
Не подписывается УПД через API

### ISSUE THREAD

**Issue by OlgaArtamonova** [diadoc/diadocsdk-1c-docs#285]
Версия компоненты 5.26.0.416

Пытаюсь подписать УПД. 
Применяю метод SendReceiptsAsync(). Ошибок никаких не выдается, но документ на платформе остается неподписанным, в статусе InboundWaitingForRecipientSignature. 
AsyncResult.IsCompleted = False, AsyncResult.Result = False
Как понять, что не так?

Документ остается неподписанным на платформе продолжительное время (несколько часов и более, далее не ждали, подписывали на платформе)

**Comment by GilimkhanovDenis** [comment]
Уточните boxId в котором пытались подписать ИоПы
и userId пользователя под которым это происходило (или отпечаток сертификата под которым авторизовались)

**Comment by OlgaArtamonova** [comment]
ID организации 184f66dfafda419288deb14002842176@diadoc.ru, по пользователю уточню

**Comment by OlgaArtamonova** [comment]
5b 15 62 1e a1 a3 bf ed 50 57 05 86 f1 c2 8d 13 20 cf a6 06  - отпечаток сертификата

**Comment by OlgaArtamonova** [comment]
Еще вопросы:
1) Я правильно понимаю, что после отправки мы должны обращаться к объекту AsyncResult с некоей периодичностью и ждать, что AsyncResult.IsCompleted = Истина?
2) Где посмотреть, что должен возвращать AsyncResult.Result при подписании, если подписано успешно?
В документации нашла только:
Свойство <Result> устанавливается после завершения операции. Тип результата зависит от типа асинхронной операции.

**Comment by GilimkhanovDenis** [comment]
> 1. Я правильно понимаю, что после отправки мы должны обращаться к объекту AsyncResult с некоей периодичностью и ждать, что AsyncResult.IsCompleted = Истина?
Верно

> 2. Где посмотреть, что должен возвращать AsyncResult.Result при подписании, если подписано успешно?
>     В документации нашла только:
>     Свойство  устанавливается после завершения операции. Тип результата зависит от типа асинхронной операции.
Речь всё ещё о [подписании ИоПов](https://diadocsdk-1c.readthedocs.io/ru/latest/ReceiptGenerationProcess.html) ?
Или уже про какой-то другой асинхронный вызов?

**Comment by GilimkhanovDenis** [comment]
Извиняюсь. Неправильно понял вопрос

**Comment by OlgaArtamonova** [comment]
Спасибо, с комбинацией ReplySendTask SendReceiptsAsync() для СЧФДОП подписать получилось.

А как для УПД с функцией ДОП или СЧФДОП определить товары или услуги в документе для заполнения ReplySendTask.Content.OperationContent?

**Comment by GilimkhanovDenis** [comment]
У объекта https://diadocsdk-1c.readthedocs.io/ru/latest/ExtendedInvoiceItem.html должен быть заполнен признак ItemMark (заполняется отправителем)
