### ISSUE TITLE
Подписание АВР в форме приказа 552 (SignerDetails not found in DB for boxId)

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#286]
При подписании АВР в форме приказа 552 возникает ошибка:

Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/AcceptanceCertificate552BuyerTitle/Signers/SignerReference: @Inn is required
/AcceptanceCertificate552BuyerTitle/Signers/SignerReference: SignerDetails not found in DB for boxId=9789dfe7-9fca-4ee2-ba3c-7c29fb427d49, thumbprint=8688C6508199B3752AD58CA6CD87B031FF88B7E

ID документа: 13266df0-420a-479c-babe-72d7f2457ad262b66d2a-16ff-476e-9a8b-2451e60f0aff
Область полномочий подписанта настроена.
Подскажите, что это может быть?

**Comment by GilimkhanovDenis** [comment]
Такая ошибка возникает, если не настроена область полномочий для титула при указанном отпечатке сертификата в ящике.
Выполните https://diadocsdk-1c.readthedocs.io/ru/latest/GetExtendedSignerDetails2.html чтобы проверить данные подписанта для указанного типа документа
Дозаполните их, вызвав https://diadocsdk-1c.readthedocs.io/ru/latest/SetExtendedSignerDetailsTask.html

На всякий случай переавторизуйтесь после того

Примечание: в веб интерфейсе указываются данные подписанта для **УПД**, для форматов **551 / 552,** можно указать только через интеграцию

**Comment by prog22** [comment]
Спасибо. Ключевое: "для форматов **551 / 552,** можно указать только через интеграцию". А искали настройку в web-интерфейсе.
