### ISSUE TITLE
Проблема с подписанием неформализованных документов облачной подписью в составе пакета

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#287]
Использую компоненту 5.26.0.416 x32 (для встраивания в произвольные системы).
Пример документов, входящих в пакет:

https://diadoc.kontur.ru/7f648ced-4718-4958-884e-02dac0220d4a/Document/Show?letterId=315004a1-3fdc-4abf-a18a-c6cc0beb1dd4&documentId=9f2bc994-133a-4e38-aa8e-c47363d1965b

https://diadoc.kontur.ru/7f648ced-4718-4958-884e-02dac0220d4a/Document/Show?letterId=315004a1-3fdc-4abf-a18a-c6cc0beb1dd4&documentId=92923bfe-b3bd-4610-8b82-07d24c96d856

Проблема вернулась:

Исправлено в версии 5.22.5.373

_Originally posted by @GilimkhanovDenis in https://github.com/diadoc/diadocsdk-1c-docs/issues/213#issuecomment-425886687_

**Comment by GilimkhanovDenis** [comment]
Добрый день
Ошибка ещё актуальна?
