### ISSUE TITLE
Периодические падения DiadocComApi.dll

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#288]
Использую версию компоненты 5.26.0.416 x64 на сервере для отправки документов.
Периодически возникает ошибка, фиксируемая в журнале событий:

Система вызвала пользовательский компонент, а он дал сбой и создал исключение. Это свидетельствует об ошибке в компоненте. Уведомите об этом разработчика компонента и сообщите следующие сведения.
Код серверного приложения: {6639D4D9-A8C6-442E-9C45-7FB94515DE51}
Код экземпляра серверного приложения:
{CA07CB07-FC55-4314-9B67-8CB3EC8E2E7B}
Имя серверного приложения: Diadoc
Ошибка оказалась серьезной, процесс завершен.
Исключение: c0000005
Адрес: 0X00007FFEB9DD2643

Имя сбойного приложения: dllhost.exe, версия: 6.3.9600.16384, метка времени: 0x5215dfc6
Имя сбойного модуля: DiadocComApi.dll, версия: 5.26.0.416, метка времени: 0x5c59507a
Код исключения: 0xc0000005
Смещение ошибки: 0x00000000003a2643
Идентификатор сбойного процесса: 0x20a0
Время запуска сбойного приложения: 0x01d4c8a69e516a4e
Путь сбойного приложения: C:\Windows\system32\dllhost.exe
Путь сбойного модуля: C:\Windows\SysWOW64\DiadocComApi.dll
Идентификатор отчета: 94dcc057-34a9-11e9-80f2-00155d00e600
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 

С этим можно что-то сделать в очередном релизе компоненты или бесполезная информация?

**Comment by GilimkhanovDenis** [comment]
Можете сказать при выполнении какого метода крашится приложение?

**Comment by prog22** [comment]
CreateConnectionByCertificate

**Comment by GilimkhanovDenis** [comment]
Случайно ОС не Windows XP SP3 / Server 2003 SP2 ?
Дамп получится собрать, хотя бы мини?

**Comment by prog22** [comment]
Windows Server 2012R2 Standart x64

**Comment by prog22** [comment]
Дамп полный - 2 Гб был.

**Comment by GilimkhanovDenis** [comment]
Попробуйте на новом релизе. Если падения продолжаются, то нужен дамп (хотя бы мини дамп)
