### ISSUE TITLE
обработка контента

### ISSUE THREAD

**Issue by 2michael** [diadoc/diadocsdk-1c-docs#289]
через генератор шаблона добавил "генерация контента" (обработать типовой результат) для УПД.
(мне нужны манипуляции с номером договора).  сгенерировались процедуры по контенту, там все понятно, я поправил что надо.
Но не понятно как происходит вызов этих переопределенных процедур. Конкретно  Заполнить_UtdSellerContent.
В таком виде модуль вообще выдавал ошибку, что нет события.

Добавил собтытие  ПодготовитьПакет (обработать типовой результат).  В подключаемый модуль попадает сюда:

Функция ПодготовитьПакет(Параметры)
	Если ТипЗнч(Параметры) = Тип("Структура") И Параметры.Свойство("Результат_ИМ") Тогда
		Если Параметры.ВидПакетаРазвернутый.ID = "ID_ПАКЕТА" Тогда	
ОсновнойМодуль.ЭДО_ДокументМенеджер_ПодготовитьИДобавитьДокументВПакет(Параметры.Пакет, Параметры.СтрокаСписка.Документ, "ID_ДОКУМЕНТА");
		КонецЕсли;
	
		Возврат Истина;

	КонецЕсли;

КонецФункции

Подскажите, как организовать вызов Заполнить_UtdSellerContent.

**Comment by volodkindv** [comment]
Добрый день!
Вопросы по модулю Про лучше задавать в репозитории
https://github.com/diadoc/diadoc1cpro-docs
Там как раз есть примеры кода.

Под ваш случай подходит этот раздел:
http://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Podgotovka_Paketa_Dlya_Otpravki.html#id6
Т.е. вам надо определить событие "ПодготовитьЭлектронныйДокумент" и в нем вызвать "Заполнить_UtdSellerContent"

**Comment by 2michael** [comment]
Спасибо!
