### ISSUE TITLE
Повторная отправка документа с заполненным CustomDocumentId

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#29]
Мы отправили документ с заполненным CustomDocumentId, потом его аннулировали и перенести в "Удаленные". При повторной отправке этого же документа выдается ошибка:

Произошла исключительная ситуация (PackageSendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: CustomDocumentId 'ХХХХХХХХХХХХХХХХХХХХХХХХХХХХХХХ' is not unique

Ответ сервера понятен. 
Вопрос в том, как повторно отправить документ, если ИД в нашей системе не поменялся (хотим его сохранить), удалить документ с вашего сервера полностью невозможно (или непонятно как).

Как быть в таком случае? Что посоветуете?

**Comment by denver069** [comment]
Ошибка "CustomDocumentId is not unique" возвращается при попытке отправить несколько документов с одним CustomDocumentId в одном сообщении. Опишите пожалуйста каким образом вы выполняете повторную отправку документа.

**Comment by geron4** [comment]
В первом сообщении я описал достаточно подробно, прошу еще раз ознакомиться. Речь идет о повторной отправке, того же документа. Например после отправки заметили ошибку, исправили ее в нашей БД, на сайте оператора ЭДО аннулировали, перенесли в папку Удаленные и решили его повторно отправить с другими данными, но CustomDocumentId тот же. Т.е. есть ли возможность полностью удалить из вашей БД аннулированный документ?

**Comment by denver069** [comment]
Прошу прощения, я не совсем правильно выразился.
Сценарий повторной отправки мне понятен. Хочется увидеть код, которым выполняется повторная отправка. Дело в том что если отправлять документ новым сообщением, то ошибки "CustomDocumentId is not unique" не будет.

**Comment by geron4** [comment]
Код тот же самый что и при первой отправке и CustomDocumentId тот же, мы его генерируем сами. Мы отправляем пакетами, OperationId - новый для повторной отправке..

**Comment by denver069** [comment]
Ошибка "CustomDocumentId is not unique" может возникать только в случае, если один и тот же CustomDocumentId присвоен разным документам в одном PackageSendTask.
Проверяйте отправляемый пакет.
