### ISSUE TITLE
Отзыв запроса на подписание

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#290]
Подскажите, пожалуйста, как отозвать запрос на подписание, отправленный вот так:

DocumentPackage = Document.GetDocumentPackage();
		
ResolutionRequestTask = DocumentPackage.CreateResolutionRequestTask();
ResolutionRequestTask.ResolutionRequestType = "SignatureRequest";
ResolutionRequestTask.Comment 				= ПараметрыСогласования.Комментарий;
ResolutionRequestTask.TargetUserId 			= ПараметрыСогласования.ИдентификаторПользователя;
	
ResolutionRequestTask.Send();

Желательно под пользователем, отправившим запрос.

**Comment by GilimkhanovDenis** [comment]
На данный момент такой возможности нет
Добавил задачу на реализацию данной функциональности в бэклог. По срокам реализации пока сориентировать не смогу

**Comment by GilimkhanovDenis** [comment]
У [Document ](https://diadocsdk-1c.readthedocs.io/ru/latest/Document.html)есть коллекция ResolutionRequests с объектами [ResolutionRequests](https://diadocsdk-1c.readthedocs.io/ru/latest/ResolutionRequest.html)
