### ISSUE TITLE
Ошибка при попытке подключения

### ISSUE THREAD

**Issue by OlgaArtamonova** [diadoc/diadocsdk-1c-docs#291]
При попытке входа по сертификату через библиотеку интеграции у одного из пользователей возникает ошибка
Не удалось выполнить действие по причине: Произошла исключительная ситуация (DiadocCom.CreateConnectionByCertificate): WIN32[0x00002EF3]WinHttpQueryHeaders.WINHTTP_QUERY_STATUS_CODE
Библиотеку обновили на последнюю версию. При входе по сертификату через веб-интерфейс все нормально. 
Подскажите,  пожалуйста, куда копать.

**Comment by GilimkhanovDenis** [comment]
Пройдите [диагностику](https://help.kontur.ru/diadoc) с машины, на которой возникает ошибка и сообщите её номер
Также укажите отпечаток сертификата, по которому пытаетесь авторизоваться

**Comment by OlgaArtamonova** [comment]
Отпечаток сертификата 
‎24 78 e8 46 f2 61 4a 54 62 8b ab cf 33 0c 26 3f 5e 0b 39 f6
Номер диагностики 7654511

**Comment by GilimkhanovDenis** [comment]
Обычно данная ошибка связана с настройками прокси сервера, антивируса или сетевого экрана. Проверьте, правильно ли они настроены,, не блокируют ли соединения для нашей компоненты

**Comment by OlgaArtamonova** [comment]
Спасибо, проблема решена
