### ISSUE TITLE
Ошибка при получении списка событий

### ISSUE THREAD

**Issue by sergeb72** [diadoc/diadocsdk-1c-docs#293]
COM-компонента для встраивания в произвольные системы - версия 5.26.2.424
Организация: 0540926453394dc7aa362625f812119e@diadoc.ru
Запрашивается список событий методом GetDocumentEventList с параметром
63661a6a-b552-4282-8282-5dfbfd6fdc63
Метод возвращает ошибку:
##100[Ошибка сервера Диадок]code:400, HTTP error: Could not parse messageId query param:.

Более ранние события возвращаются без ошибок.

**Comment by GilimkhanovDenis** [comment]
фикс будет в следующем релизе. В качестве временной меры можете продолжить выгрузку событий, указав в качестве параметра методу eventId=8580a1a8-6810-4f73-aa5c-c4d854d1c2e4

**Comment by GilimkhanovDenis** [comment]
Пробуйте релиз 5.26.3.434
скачать релиз можно со страницы http://1c-docs.diadoc.ru/ru/latest/Downloads.html
