### ISSUE TITLE
Доступ к серверам Диадок

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#295]
Добрый день. Использую компоненту 5.26.0.416 x64 (для встраивания в произвольные системы). Последние несколько дней (18.03.2019-20.03.2019) участились ошибки вида:

1) Ошибка при вызове метода контекста (GetOrganizationList): Произошла исключительная ситуация (DiadocConnection.GetOrganizationList): WIN32[0x00002EE2]WinHttpReceiveResponse
2) Ошибка при вызове метода контекста (GetOrganizationList): Произошла исключительная ситуация (DiadocConnection.GetOrganizationList): WIN32[0x00002EE2]WinHttpSendRequest
3) Ошибка при вызове метода контекста (GetDocuments): Произошла исключительная ситуация (SearchDocumentTask.GetDocuments): ##200[Ошибка передачи данных через интернет]Не удается найти указанный адрес сервера
4) Ошибка при вызове метода контекста (GetDocuments): Произошла исключительная ситуация (SearchDocumentTask.GetDocuments): ##200[Ошибка передачи данных через интернет]Превышено время ожидания сервера.

При повторном подключении (м.б. несколько раз) ошибки не возникают.
Т.е. увеличилось время передачи документов до серверов Диадок.
Подскажите, пожалуйста, с чем это связано.

**Comment by volodkindv** [comment]
Добрый день.
По описанным вами симптомам больше похоже, что проблема с сетью на вашей стороне.
Пройдите диагностику: https://help.kontur.ru и приложите сюда ее номер.
Выполните в командной строке: tracer diadoc-api.kontur.ru и посмотрите, нет ли подозрительных лагов. Желательно в то время, когда возникают ошибки.

Если явных проблем с сетью обнаружить не удастся, то обратитесь в техподдержку. Для анализа понадобятся: ключ разработчика API и ID организации, от имени которой выполняются запросы.

**Comment by prog22** [comment]
7783377

**Comment by volodkindv** [comment]
Обратите внимание на раздел "Связь с сервером" в результатах диагностики:
![image](https://user-images.githubusercontent.com/12305552/54683930-c3fc8680-4b34-11e9-8470-e5f994b829fe.png)
Похоже, проблемы все-таки с сетью на вашей стороне.
Выполните в командной строке "tracert diadoc-api.kontur.ru" и попробуйте проанализировать маршрут. Также посмотрите на статистику пингов: в командной строке "ping diadoc-api.kontur.ru -t".

**Comment by volodkindv** [comment]
Да, еще стоит проверить работоспособность прокси сервера.

**Comment by prog22** [comment]
Спасибо за помощь.
