### ISSUE TITLE
ExtendedSignerDetails поле Status у подписанта покупателя

### ISSUE THREAD

**Issue by OlgaArtamonova** [diadoc/diadocsdk-1c-docs#296]
Подскажите, пожалуйста, что нужно выбирать у подписанта в поле status при подписании акта в формате 552 со стороны покупателя:

“SellerEmployee” - работник организации продавца товаров (работ, услуг, имущественных прав)
“InformationCreatorEmployee” - работник организации - составителя информации продавца
“OtherOrganizationEmployee” - работник иной уполномоченной организации
“AuthorizedPerson” - уполномоченное физическое лицо (в том числе индивидуальный предприниматель)

отдельного статуса для покупателя нет, выбираем OtherOrganizationEmployee?

**Comment by aeremina88** [comment]
Добрый день!
С точки зрения формата номера статусов подписанта не отличаются для покупателя и продавца, т.е. все статусы подходят и для покупателя:
“SellerEmployee” - 1
“InformationCreatorEmployee” - 2
“OtherOrganizationEmployee” - 3
“AuthorizedPerson” - 4
Подробнее [здесь](https://normativ.kontur.ru/document?moduleId=1&documentId=265283&rangeId=178270)
