### ISSUE TITLE
Вопрос по форме накладной

### ISSUE THREAD

**Issue by sergeb72** [diadoc/diadocsdk-1c-docs#297]
COM-компонента для встраивания в произвольные системы - версия 5.26.2.424

При создании документа TovTorgToSend без указания значений параметров RevisionDate и RevisionNumber печатная форма содержит строку "Исправление" с прочерками.

При создании документа накладной из web-интерфейса форма ТОРГ-12 не содержит этой строки вообще.

Контрагент изъявляет желание получать документ без строки "Исправление" в том случае, если исправления не было. Можно ли этого достичь при формировании документа с помощью COM-компоненты?

**Comment by volodkindv** [comment]
Нет, компонента здесь никак не влияет. 
Компонента влияет только на формирование xml файла документа, который вы можете скачать из веб-интерфейса. Теги, отвечающие за номер и дату исправления, там будут отсутствовать. 
Кроме того, отправка TovTorg через веб-интерфейс сейчас невозможна. Может быть, вы отправляете накладную в 155 формате? У нее немного другой алгоритм визуализации.

**Comment by sergeb72** [comment]
"При создании документа накладной из web-интерфейса"  - это операции "Новый документ" - "Накладная".
То есть через COM визуально исключить "Исправление" нет возможности, я правильно понял?

**Comment by volodkindv** [comment]
"Новый документ" -> "Накладная" создает накладную в 155 формате. Можете убедиться в этом, скачав отправленный документ: имя файла будет ON_SCHFDOPPR_...
Для TovTorg файл будет называться DP_TOVTORGPR_...

Верно, через COM отключить "Исправление" невозможно.

**Comment by sergeb72** [comment]
Спасибо.
