### ISSUE TITLE
Protobuf parse error

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#298]
Использую компоненту 5.26.0.416 x64 (для встраивания в произвольные системы).
При получении GetContent() от документа (УПД) с id = ffd84d80-4805-4393-bdb3-92df94efc2867c60aa4d-4756-4ac4-892d-9f3c54a86249 возникает ошибка:

Ошибка при вызове метода контекста (GetContent): Произошла исключительная ситуация (Utd.GetContent): Protobuf parse error: required fields missing: (cannot determine missing fields for lite message)

Подскажите, пожалуйста, что это такое.

**Comment by GilimkhanovDenis** [comment]
Обновите компоненту. Если ошибка актуальна, то укажите в каком ящике происходит ошибка (boxId)

**Comment by prog22** [comment]
Поставил 5.26.3.434 x64. Ошибка та же, ящик 5cc59872767d471d8f28f125aabfaf8a@diadoc.ru.

**Comment by GilimkhanovDenis** [comment]
Ждём исправления со стороны Диадока

**Comment by GilimkhanovDenis** [comment]
Исправлено. Компоненту обновлять не требуется
