### ISSUE TITLE
Ошибка при отправке УКД

### ISSUE THREAD

**Issue by Fibba** [diadoc/diadocsdk-1c-docs#299]
Добрый день. 
Пытаемся отправить УКД. для SendTask-а устанавливаем тип "UniversalCorrectionDocument" и Function = "Basic". Заполнили контент. 
![image](https://user-images.githubusercontent.com/42743750/55614537-e37eea80-5795-11e9-9df7-ca0d4da34bc0.png)

В документе 2 строки:
![image](https://user-images.githubusercontent.com/42743750/55614558-f42f6080-5795-11e9-8e1a-176f2f528887.png)

данные строки 1:
![image](https://user-images.githubusercontent.com/42743750/55614572-fdb8c880-5795-11e9-9ce8-52a8aa5fb577.png)

данные строки 2:
![image](https://user-images.githubusercontent.com/42743750/55614614-0a3d2100-5796-11e9-8c50-2c7388ac27b6.png)

Отправляем и имеем ошибку:
![image](https://user-images.githubusercontent.com/42743750/55614668-2ccf3a00-5796-11e9-8049-b586486e96c9.png)

Собственно вопрос: про какой Subtotal идет речь? Излазил все свойства объекта описанные в документации по API https://diadocsdk-1c.readthedocs.io/ru/latest/UcdSellerContent.html Что я делаю не так? Текущая версия компоненты: Diadoc_5_25_1_398

**Comment by GilimkhanovDenis** [comment]
При заполнении контента заполняется ли поле  SendTask.Content.InvoiceCorrectionTable.Items.GetItem(1).AmountInc.Vat ?
Насколько понимаю, заполняется (на скриншотах это поле заполнено нулём)
Не заполняйте его и никак не трогайте, иначе требуется заполнить ВСЮ структуру SendTask.Content.InvoiceCorrectionTable.Items.GetItem(1).AmountInc

В строке SendTask.Content.InvoiceCorrectionTable.Items.GetItem(0) заполнено правильно

**Comment by Fibba** [comment]
Спасибо, получилось пройти проверку сервера. 

Хотелось бы обратить внимание, что свойство AmountInc.Vat заполняется значением "0", если это же значение устанавливается для свойства OriginalValues.Vat. они оба должны быть "неопределено", чтобы всё прошло хорошо.
