### ISSUE TITLE
Ошибка при получении xml счет-фактуры

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#30]
Ошибка при вызове метода контекста (SaveContent): Произошла исключительная ситуация (SendTask.SaveContent): ##100[Ошибка сервера Диадок]code:400, HTTP error: InvoiceInfo.Items[0].Subtotal is required.
Со вчерашнего дня началась такая проблема, до этого с мая работало.
Ниже привожу заполненный COM.
 SendTask = Organization.CreateSendTask("InvoiceContent");
ЗаполнитьКонтентДляInvoice(SendTask.Content, СтрТЗКомплект, СтруктураПараметровДок, НомерЗаказа, ПараметрыОтправкиНаСогласование);
// заполним ЭП для счет фактуры	  
ПутьФ = ""+КаталогВременныхФайлов()+СтруктураПараметровДок.ИдДок+".xml";
SendTask.SaveContent(ПутьФ);  <-- ошибку в этом месте, до этого все работало
Что-то изменилось у Вас на сервере
![img-2016-11-02-17-09-59](https://cloud.githubusercontent.com/assets/20082460/19957290/620f6aee-a1a6-11e6-8d1a-d2c9b0366520.png)
![img-2016-11-03-08-47-43](https://cloud.githubusercontent.com/assets/20082460/19957292/688ac850-a1a6-11e6-832d-f79150da7043.png)
![img-2016-11-03-08-48-44](https://cloud.githubusercontent.com/assets/20082460/19957295/6e0aeada-a1a6-11e6-8c87-799df1c48de8.png)

**Comment by jakeqwert** [comment]
Такая ошибка не только при получении xml документа, но и при отправке. "Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (SendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: InvoiceInfo.Items[0].Subtotal is required"
Не можем отправить отгрузочные документы за октябрь, работа стоит. На что он ругается не понятно, через COM нет таких полей?

**Comment by denver069** [comment]
Проверьте заполнение поля Total в [строке счета-фактуры](http://1c-docs.diadoc.ru/ru/latest/InvoiceItem-(Invoice).html). Поле Total должно быть заполнено обязательно. Если при визуализации формы в колонке № 9 должен стоять прочерк, то в поле Total нужно записать значение Неопределено.
