### ISSUE TITLE
Ошибка при вызове метода CreateSendTaskFromFile(Path, "UniversalTransferDocument")

### ISSUE THREAD

**Issue by Aleksey2W** [diadoc/diadocsdk-1c-docs#300]
файл прошел проверку https://www.diadoc.ru/docs/forms/validation-xml
Вызываю с такими параметрами:
SendTask = Organization.CreateSendTaskFromFile(ИмяФайлаВоВременномХранилище, "UniversalTransferDocument");

(Box.CreateSendTaskFromFile): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid document version: versionFilters=[TypeNamedId: UniversalTransferDocument, Function: ДОП, Version: utd_05_01_05;TypeNamedId: UniversalTransferDocument, Function: СЧФ, Version: utd_05_01_05;TypeNamedId: UniversalTransferDocument, Function: СЧФДОП, Version: utd_05_01_05;TypeNamedId: UniversalTr

в блоке "Документ" - Функция="СЧФДОП"

**Comment by GilimkhanovDenis** [comment]
Здравствуйте
Нужен сам файл и версия компоненты, которую используете

**Comment by Aleksey2W** [comment]
> Здравствуйте
> Нужен сам файл и версия компоненты, которую используете

COM Компонента 5_26_2_424_x64

[ТЦ_УПД_ЭДО00000052.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/3072168/_._.00000052.zip)

**Comment by GilimkhanovDenis** [comment]
На последнем релизе (5.26.5.438) не воспроизводится. Обновите компоненту.
Если ошибка будет актуальна, то нужен будет листинг кода, на котором ошибка воспроизводится

**Comment by Aleksey2W** [comment]
> На последнем релизе (5.26.5.438) не воспроизводится. Обновите компоненту.
> Если ошибка будет актуальна, то нужен будет листинг кода, на котором ошибка воспроизводится

Обновил. Проверил - ДиадокАпи.GetVersion() возвращает 5.26.5.438

Листинг- если собрать из процедур, то как то так:
			
`ДиадокАпи = Новый ComОбъект("Diadoc.DiadocClient");`
`	ДиадокАпи.ApiClientId		= СтруктураОрганизации.КлючРазработчикаДиадок;`
`	ДиадокАпи.ServerUrl			= "https://diadoc-api.kontur.ru:443";`
`	ДиадокАпи.OneSConfigaration = "OneS_DiadokClient_v1001";`
`	`
`	Диадок_Соединение = ДиадокАпи.CreateConnectionByCertificate(СтруктураОрганизации.КлючЭЦП);`
`	`
`	ИмяФайлаВоВременномХранилище = мКаталогХраненияФайлов + Строка(ИсходящийДокумент.Ссылка.УникальныйИдентификатор()) + ".xml";`
`	ТекстовыйДокумент = Новый ТекстовыйДокумент;`
`	ТекстовыйДокумент.УстановитьТекст(ИсходящийДокумент.ТелоДокумента);`
`	ТекстовыйДокумент.Записать(ИмяФайлаВоВременномХранилище);`
`	`
`	SendTask = Диадок_КонтекстОрганизации.CreateSendTaskFromFile(ИмяФайлаВоВременномХранилище, СтруктураКонтекста.ТипКонтента);`

СтруктураКонтекста.ТипКонтента = "UniversalTransferDocument"
Файл - тот, который отправлял ранее.

Ошибка та же:
 Ошибка при вызове метода контекста (CreateSendTaskFromFile)
		SendTask = Диадок_КонтекстОрганизации.CreateSendTaskFromFile(ИмяФайлаВоВременномХранилище, СтруктураКонтекста.ТипКонтента);
по причине:
Произошла исключительная ситуация (Box.CreateSendTaskFromFile): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid document version: versionFilters=[TypeNamedId: UniversalTransferDocument, Function: ДОП, Version: utd_05_01_05;TypeNamedId: UniversalTransferDocument, Function: СЧФ, Version: utd_05_01_05;TypeNamedId: UniversalTransferDocument, Function: СЧФДОП, Version: utd_05_01_05;TypeNamedId: UniversalTr

**Comment by GilimkhanovDenis** [comment]
На таком же коде воспроизвести не удаётся. 
Так же заметил, что при выполнении запроса с нашей стороны, Content-Length отличается от того который формируется у вас.
Можете подтвердить, что приложили именно тот файл, на котором происходит ошибка?

**Comment by Aleksey2W** [comment]
нашел проблему, сори, мой косяк.
При сохранении из 1С при не указанной кодировке выставляется по умолчанию UTF-8, а нужно было windows-1251.
