### ISSUE TITLE
Помогите заполнить ExtendedSignerDetailsToPost в 1C

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#301]
Добрый день! Пытаюсь создать задание SetExtendedSignerDetailsTask:
SetExtendedSignerDetailsTask = Оrganization.CreateSetExtendedSignerDetailsTask(CertificateThumbprint);
SetExtendedSignerDetailsTask.IsSeller = Ложь;
SetExtendedSignerDetailsTask.ExtendedSignerDetailsToPost =  СвойстваПодписанта;
SetExtendedSignerDetailsTask.DocumentTitleType("AccCert552Buyer");
SetExtendedSignerDetailsTask.Send();
Как получить объект ExtendedSignerDetailsToPost(чтобы поместить в СвойстваПодписанта) и правильно заполнить для подписания входящего акта

**Comment by GilimkhanovDenis** [comment]
Заполнить его можно по полям. например так

```
task = dd_Organization.CreateSetExtendedSignerDetailsTask(ОтпечатокСертификата);
task.DocumentTitleType = ТипТитула;
signerDetails = task.ExtendedSignerDetailsToPost;
signerDetails.JobTitle = ДолжностьПодисанта;
signerDetails.RegistrationCertificate = НомерСвидетельстваРегистрацииИП;
signerDetails.SignerType = ТипПодписанта;
signerDetails.SignerInfo = СведенияОФизЛице;
signerDetails.Powers = Полномочия;
signerDetails.Status = Статус;
signerDetails.PowersBase = ОснованияПолномочия;
signerDetails.OrganizationPowersBase  = ОснованияПолномочияОрганизации;
	
task.send();
```

**Comment by GuninaY** [comment]
Для подписания акта подойдет Powers = “InvoiceSigner”  и Status =“SellerEmployee”? ТипПодписанта = "Сотрудник"?

**Comment by GilimkhanovDenis** [comment]
Возможные значения SignerType перечислены в [документации](https://diadocsdk-1c.readthedocs.io/ru/latest/ExtendedSignerDetailsToPost.html?highlight=SignerType)

Значения Powers тоже можно взять из документации.  Для  актов и накладных валидными являются те значения, в которых нет подстроки Invoice (PersonMadeOperation, MadeAndSignOperation, PersonDocumentedOperation). Полномочия, где есть подстрока Invoice, могут применяться только для документов содержащих фактурную часть

Status может быть любым из перечисленных в документации

**Comment by GuninaY** [comment]
Спасибо!
