### ISSUE TITLE
Проблемы с сертификатом при входе через модуль 1С

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#302]
На нескольких компьютерах установлен сертификат, модуль 1с открывается на всех кроме одного. Выдает ошибку: ДиадокСоединение = АПИ.CreateConnectionByCertificate(PersonalCertificate);
по причине:
Произошла исключительная ситуация (DiadocApiInvoiceApi.CreateConnectionByCertificate): ##100[Ошибка сервера Диадок]code:401, HTTP error: Certificate with thumbprint ****is not authorized.
Номер сертификата совпадает с оригиналом. Какие могут быть причины?

**Comment by GilimkhanovDenis** [comment]
Проверьте, что сертификат не отозван

**Comment by GuninaY** [comment]
Извините, непонятно написала, сертификат у нас один, несколько компьютеров, на всех срабатывает, на одном нет.

**Comment by GuninaY** [comment]
на одном не срабатывает

**Comment by GilimkhanovDenis** [comment]
приложите, пожалуйста, открытый ключ сертификата. инструкцию по экспорту можно найти [здесь](https://www.kontur-extern.ru/support/faq/34/420)

**Comment by GuninaY** [comment]
[тестовый.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/3089552/default.zip)

**Comment by GilimkhanovDenis** [comment]
По логам ошибки для сертификата из вложения не возвращалось.
Какой отпечаток указан в ошибке?

**Comment by GilimkhanovDenis** [comment]
Проверьте, что действительно в авторизации указываете сертификат с отпечатком 9767ceca18acf29dcdc564f84da6da2da90e4690

Отпечаток 32E093F73BA252A7847DFDB8E940BD05FA6637D0 - отпечаток сертификата, выпущенного на этого же человека, но истёкший 1 сентября 2018 (возможно, где-то закэшился и теперь по умолчанию используется)

**Comment by GuninaY** [comment]
Да, все верно, брался первый попавшийся, сделала отбор по EndDate и все заработало. Спасибо!
