### ISSUE TITLE
Облачные подписи

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#303]
Добрый день.
Вчера от менеджера по сопровождению клиентов Диадок получили информацию:

"Обещала к Вам вернуться с обратной связью по поводу облачных КЭП – данные сертификаты Контур больше не выпускает, т.к. переходит на новую технологию по выпуску новых сертификатов с технологией подписания через мобильное приложение.
Ориентировочный срок перехода 1-1,5 месяца.
Выпущенные ранее сертификаты действительны до момента окончания".

Наша текущая инфраструктура не предполагает установки КриптоПРО и КЭП на удаленных рабочих местах, поэтому выбрали вариант с Облачной подписью.

Будет ли компонента поддерживать какой либо механизм подписания, кроме как через "железный" КЭП.

**Comment by volodkindv** [comment]
Добрый день.
На данный момент решение о поддержки облачной подписи в каком-либо виде в компоненте для 1С не принято.
Решение будет приниматься исходя из востребованности данного механизма и трудозатрат на его реализацию и поддержку.
Ваш интерес зафиксировали. О решении сможем сообщить не раньше июня-июля.
