### ISSUE TITLE
TotalWithVatExcluded тип неопределено

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#305]
Обращаюсь  через InvoiceCorrectionTable.TotalsInc.TotalWithVatExcluded. Пытаюсь поместить туда строку, пишет, что типы не совпадают, так как типу TotalWithVatExcluded  неопределено.  Как к нему обращаться?

**Comment by GuninaY** [comment]
DocumentToSend = PackageSendTask.AddDocument("UniversalCorrectionDocument");
				
Content = DocumentToSend.Content; 
Content.InvoiceCorrectionTable.TotalsInc.TotalWithVatExcluded = &Summa

**Comment by GilimkhanovDenis** [comment]
Content.InvoiceCorrectionTable.TotalsInc.TotalWithVatExcluded принимает только число с плавающей точкой в качестве значения

**Comment by GuninaY** [comment]
Спасибо!
