### ISSUE TITLE
Отправить документ на согласование

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#306]
Добрый день! 
Создаю корректировочный документ:
DocumentToSend = PackageSendTask.AddDocument("UniversalCorrectionDocument");
и отправляю DocumentPackage = PackageSendTask.Send();
Появилась потребность сотруднику без права подписи отправлять документ на согласование.
Правильно ли я понимаю, что теперь нужно использовать ResolutionRequestTask для документа из пакета и тогда он отправится на согласование?

**Comment by GuninaY** [comment]
Но у моего DocumentToSend нет такого метода

**Comment by GilimkhanovDenis** [comment]
Метод [CreateResolutionRequestTask ](https://diadocsdk-1c.readthedocs.io/ru/latest/CreateResolutionRequestTask.html)- метод объекта [Document](https://diadocsdk-1c.readthedocs.io/ru/latest/Document.html), а не [DocumentToSend](https://diadocsdk-1c.readthedocs.io/ru/latest/DocumentToSend.html)
Соответственно, сначала необходимо выполнить отправку документа с помощью PackageSendTask, возможно? с флагом DelaySend и после вызывать CreateResolutionRequestTask  у уже существующих в Диадоке документов

**Comment by GuninaY** [comment]
Ага, так получается воспользоваться методом:
ResolutionRequestTask = Document.CreateResolutionRequestTask();
ResolutionRequestTask.ResolutionRequestType = "SignatureRequest";
Подскажите как получить TargetDepartmentId? У нас одно Головное подразделение.
И после нужно ResolutionRequestTask.Send()?

**Comment by GilimkhanovDenis** [comment]
Если запрос необходимо передать пользователю, то заполните у объекта  поле [TargetUserId ](https://diadocsdk-1c.readthedocs.io/ru/latest/ResolutionRequestTask.html?highlight=TargetUserId)

**Comment by GuninaY** [comment]
Нет, нам нужно в подразделение. Как получить его идентификатор?

**Comment by GuninaY** [comment]
Вижу у Organization коллекцию Departments. Как мне ее обойти?

**Comment by GilimkhanovDenis** [comment]
У объекта Organization есть поле [Departments](https://diadocsdk-1c.readthedocs.io/ru/latest/Organization.html?highlight=Departments). У каждого подразделения есть [идентификатор](https://diadocsdk-1c.readthedocs.io/ru/latest/Department.html?highlight=Id)

У головного подразделения любой организации DepartmentId = "00000000-0000-0000-0000-000000000000"

**Comment by GuninaY** [comment]
Спасибо, отправить на согласование получилось только вот не подцепился первичный документ:
InvoiceForCorrectionInfo = Content.AddInvoice();
				InvoiceForCorrectionInfo.InvoiceDate = ДокументРеализации.Дата; 
				InvoiceForCorrectionInfo.InvoiceNumber  = ОбщегоНазначения.ПолучитьНомерНаПечать(ДокументРеализации);
Хотя если отправлять в черновик, то получается

**Comment by GuninaY** [comment]
https://diadoc.kontur.ru/54d0b467-aade-47d6-8136-a2bbe2eeb67d/Document/Show?letterId=eb8860fc-2131-4d88-903c-24cbf7da481d&documentId=c0195da1-977d-44f1-9c15-3346b6a45cc4 
Данные УПД заполнились в этом УКД, но связь отсутствует

**Comment by GuninaY** [comment]
Видимо нужно использовать AddInitialDocument(<Id>). Могу я по номеру и даты родительского документа получить его ID?

**Comment by GuninaY** [comment]
GetDocumentsTask мне помог)
