### ISSUE TITLE
Не подписываются некоторые документы

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#307]
Получаем ошибку: Произошла исключительная ситуация (ReplySendTask.Send): ##100[Ошибка сервера Диадок]code:409, HTTP error: Текущее состояние документа не позволяет его подписать

**Comment by OlgaPetushina** [comment]
Это ошибка означает, что текущий статус документа таков - что подписание не требуется (например, документ уже подписан или не требует подписания)

**Comment by GuninaY** [comment]
статус у документа "требуется подпись" https://diadoc.kontur.ru/54d0b467-aade-47d6-8136-a2bbe2eeb67d/Document/Show?letterId=c5576a9a-88a8-4fb5-9de9-cd7b4df0f702&documentId=7d962cea-f332-4c91-bf8f-f26d7a1c439d

**Comment by GilimkhanovDenis** [comment]
Данную ошибку получаете при подписании другого документа:
letterId=76a239a0-57ab-45a1-ab4c-dbceaa39b95e
documentId=d812ea1c-702e-4518-b161-3be51ca38dd7

По указанному вами документу ошибки в логах нет
