### ISSUE TITLE
Не подписывается УПД

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#308]
Есть УПД входящий https://diadoc.kontur.ru/54d0b467-aade-47d6-8136-a2bbe2eeb67d/Document/Show?letterId=bf862b3e-f21e-4637-b477-a2ed7f7c9d9f&documentId=1b777677-aeed-407e-8dd1-bd19b1909fb7. При попытке подписать вылезает: Произошла исключительная ситуация (ReplySendTask.Send): # # 100 [Ошибка сервера Диадок] код: 409, ошибка HTTP: Текущее состояние документа не позволяет его подписать

**Comment by GilimkhanovDenis** [comment]
Данную ошибку получаете при подписании другого документа:
letterId=76a239a0-57ab-45a1-ab4c-dbceaa39b95e
documentId=d812ea1c-702e-4518-b161-3be51ca38dd7

По указанному вами документу ошибки в логах нет

**Comment by GuninaY** [comment]
У меня вот такой DocumentId  = bf862b3e-f21e-4637-b477-a2ed7f7c9d9f1b777677-aeed-407e-8dd1-bd19b1909fb7. Я неправильно смотрю?

**Comment by agarochka** [comment]
DocumentId - это guid, 32 символа. Ваше значение для DocumentId = bf862b3e-f21e-4637-b477-a2ed7f7c9d9f1b777677-aeed-407e-8dd1-bd19b1909fb7 в Диадоке невозможно.

**Comment by GilimkhanovDenis** [comment]
Можете со скринами показать для какого документа вызываете CreateReplySendTask, чтобы было видно DocumentId и Status

Укажите время ошибки по UTC, когда получили ошибку

Используете AddIn или Com версию компоненты?

Неплохо было бы получить листинг кода, где будет видно:
1) как получаете документ, который будете подписывать
2) работа с ReplySendTask'ом вплоть до выполнения метода Send

**Comment by GuninaY** [comment]
Компонента последней версии
ДиадокАПИ_ = Новый("AddIn.DiadocInvoiceAPI");
ДиадокСоединение = ДиадокАПИ.CreateConnectionByCertificate(PersonalCertificate);
OrganizationList = ДиадокСоединение.GetOrganizationList();
Organization = OrganizationList.GetItem(0);
DocumentsTask = Organization.GetDocumentsTask();
DocumentList = DocumentsTask.GetDocuments();
//Далее заполняем таблицу на форме нашей обработки
Пока сч < DocumentList.Count Цикл
		Document = DocumentList.GetItem(сч);
		
		НоваяСтрока= ТаблицаДокументовДиадок.Добавить();
		
		ЗаполнитьСтрокуТаблицыДокументовВходящих(Document, НоваяСтрока, Неопределено, Ложь);
КонецЦикла;
//соответственно DocumentId  берутся у меня из списка DocumentList
//далее для при нажатии кнопки подписать для каждой строки таблицы выполняем
Document=Organization.GetDocumentById(стр.DocumentId);
ReplySendTask= Document.CreateReplySendTask("AcceptDocument");
BuyerTitleInfo = Новый Структура;
		BuyerTitleInfo.Вставить("Creator","Компания");
		BuyerTitleInfo.Вставить("DocumentCreator","Компания");

		BuyerTitleInfo.Вставить("CreatorBase",Неопределено);
		BuyerTitleInfo.Вставить("OperationCode","");
                BuyerTitleInfo.Вставить("OperationContent","Товары и услуги получены, работы приняты");
                BuyerTitleInfo.Вставить("AcceptanceDate",НачалоДня(ТекущаяДата()));
		BuyerTitleInfo.Вставить("AdditionalInfoId",Неопределено);

ТЗ = Новый ТаблицаЗначений;
	ТЗ.Колонки.Добавить("BoxId");
	ТЗ.Колонки.Добавить("CertificateThumbprint");	
	стр=ТЗ.Добавить();	
	стр.BoxId=BoxID;	
	стр.CertificateThumbprint=CertificateThumbprint;
        BuyerTitleInfo.Вставить("Signers",ТЗ);
		
соотв=Новый Соответствие;
     соотв.Вставить("_Signers_SignerDetails","Новый_ExtendedSignerDetails");		
BuyerTitleInfo.Вставить("Конструкторы",соотв);

ЗаполнитьContent(BuyerTitleInfo, ReplySendTask.Content);

ReplySendTask.Send();

**Comment by GuninaY** [comment]
![Безымянный](https://user-images.githubusercontent.com/49683051/57754518-52d1ed80-76f7-11e9-8a4f-e616f4aee461.png)

**Comment by GuninaY** [comment]
Вторая строка наш документ

**Comment by GuninaY** [comment]
Прихожу к выводу, что ошибка из-за того что это пакет документов, видимо берется ID счета

**Comment by GilimkhanovDenis** [comment]
Укажите, пожалуйста, время последнего возникновения ошибки по UTC - по логам не вижу ни одной ошибки "Текущее состояние документа не позволяет его подписать" за последнюю неделю в указанном ящике.
Последняя ошибка с данным текстом была 8 мая и возвращалась для документа
[letterId=76a239a0-57ab-45a1-ab4c-dbceaa39b95e
documentId=d812ea1c-702e-4518-b161-3be51ca38dd7](https://diadoc.kontur.ru/54d0b467-aade-47d6-8136-a2bbe2eeb67d/Document/Show?letterId=76a239a0-57ab-45a1-ab4c-dbceaa39b95e&documentId=d812ea1c-702e-4518-b161-3be51ca38dd7)
