### ISSUE TITLE
В печатной форме нет отметки об ЭП

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#31]
В печатной форме нет отметки об ЭП.
Например, входящий документ 
https://diadoc.kontur.ru/3bfb9c4d-0203-4610-83c8-e15ba95fd8d2/Document/Show?letterId=6b612b2c-b00a-40f0-8c52-d3bc9b9c660a&documentId=cd7349f4-824f-4d10-9fc5-00ee3b3904b3
Скачиваю с сайте и pdf исходная и pdf Печатная форма полностью идентичны и нет штампа(отметки) о подписанте ЭП

**Comment by denver069** [comment]
Данная ошибка не связана с работой внешней компоненты [AddInDiadocAPI](http://1c-docs.diadoc.ru/ru/latest). Обратитесь пожалуйста в службу техподдержки http://www.diadoc.ru/support.
