### ISSUE TITLE
Создать CreateResolutionRequestTask() для пакета документов 

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#310]
Нужно создать задание на подпись пакета документов, в который входит https://diadoc.kontur.ru/54d0b467-aade-47d6-8136-a2bbe2eeb67d/Document/Show?letterId=6b266462-84fc-4890-96a0-45190384d276&documentId=064de63a-5622-4775-b556-6ada6558d183. PackageID у них одинаковые, но GetDocumentPackage() возвращает по одному документу. как я поняла нужно использовать коллекцию SubordinateDocumentIds.  Но тогда получается они уйдут на подпись по отдельности, а мне нужно пакетом. Как быть?

**Comment by GilimkhanovDenis** [comment]
Увы, это невозможно.

Если спуститься на уровень ниже абстракций компоненты, то в конечном итоге мы отправляем структуру [PostMessagePatch](http://api-docs.diadoc.ru/ru/latest/proto/MessagePatchToPost.html), и в ней невозможно указать несколько messageId. А для данного сценария работы каждый документ был прислан отдельным сообщением (message'ом). Исходя из этих двух фактов техническая реализация на уровне компоненты неосуществима.
Возможно, необходимые изменения Вам удастся протолкнуть в разработку через менеджера или можете оставить пожелание по такой функциональности через линию техподдержки (8-800-500-10-18)
