### ISSUE TITLE
Падает клиент 1С при отправке документа УПД

### ISSUE THREAD

**Issue by Aleksey2W** [diadoc/diadocsdk-1c-docs#312]
Используется COM-компонента для встраивания в произвольные системы (64 битная, v5.26.6.440).
При создании и отправки УПД крашится клиент на строке кода:
`МассивЗадач.Добавить(Новый Структура("Документ,Задача", ИсходящийДокумент.Ссылка, SendTask.SendAsync()));`
![image](https://user-images.githubusercontent.com/49516183/58451771-9546f180-811d-11e9-995f-9b1cde9acf79.png)

SendTask создается из файла:
`Диадок_КонтекстОрганизации.CreateSendTaskFromFile(ИмяФайлаВоВременномХранилище, СтруктураКонтекста.ТипКонтента);`
Данный файл проходит логическую проверку, а так же через веб загружается в диадоке без ошибок:
![image](https://user-images.githubusercontent.com/49516183/58451914-11d9d000-811e-11e9-82d7-61bdbfd3ecac.png)

Файл прилагаю.
[УПД.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/3225751/default.zip)

**Comment by Aleksey2W** [comment]
На всякий случай листинг:
```
SendTask = Диадок_КонтекстОрганизации.CreateSendTaskFromFile(ИмяФайлаВоВременномХранилище, СтруктураКонтекста.ТипКонтента);
SendTask.CounteragentId = ИсходящийДокумент.ИдПолучателя;
			
Если SendTask.Content.Signers.Count = 0 Тогда
	Подписант = SendTask.Content.AddSigner();
Иначе
	Подписант = SendTask.Content.Signers.GetItem(0);
КонецЕсли;

Подписант.boxId = Диадок_КонтекстОрганизации.Id;
Подписант.CertificateThumbprint = Диадок_КонтекстОрганизации.Certificate.Thumbprint;
		
МассивЗадач.Добавить(Новый Структура("Документ,Задача", ИсходящийДокумент.Ссылка, SendTask.SendAsync()));
```

**Comment by GilimkhanovDenis** [comment]
Баг поправим в ближайшем релизе.
Конкретно по этому документу: если нужно ОКПО заполнить в печатной форме дефисом , то не указывайте его совсем (строки 20 и 29 приложенного файла)

**Comment by Aleksey2W** [comment]
> Конкретно по этому документу: если необходимо пропустить заполнение ОКПО , то не указывайте этот атрибут совсем (строки 20 и 29 приложенного файла)

т.е. проблема в заполнении ОКПО? Если сейчас их убрать, то документ отправится?
Или это не относится к отправке?

**Comment by GilimkhanovDenis** [comment]
Если убрать ОКПО, то отправится
