### ISSUE TITLE
Прочерки в полях количества и цены УПД

### ISSUE THREAD

**Issue by sergeb72** [diadoc/diadocsdk-1c-docs#313]
При создании УПД из браузера есть возможность получить в печатной форме прочерки в графах количества и цены, не вводя туда значений (для строки оказания услуг).

При работе через COM-компоненту для встраивания в произвольные системы такого эффекта можно добиться при создании счёта-фактуры (AddDocument('UtdInvoice'), не передавая атрибуты Quantity и Price), но при создании УПД (AddDocument('UniversalTransferDocument')) такой способ не работает, вызывая ошибку "Quantity is required".

Контрагент настаивает на прочерках в УПД, мотивируя возможностью их получения при создании из браузера. Как можно этого добиться через COM-компоненту?

**Comment by IrinaShmonina** [comment]
Здравствуйте, 
1. Подскажите какую функцию УПД вы указываете?
2. Указываете ли вы единицы измерения?

**Comment by sergeb72** [comment]
Спасибо за наводящие вопросы. :)
Действительно, если не передавать единицы измерения, то цена с количеством становятся необязательными значениями.
