### ISSUE TITLE
Не найден метод Reject()

### ISSUE THREAD

**Issue by Aleksey2W** [diadoc/diadocsdk-1c-docs#314]
Пытаюсь отказать в подписи входящий:
```

ДокументДиадок = КонтекстОрганизации.GetDocumentById("1bb3bbc2-8ea3-4f82-b0c2-5f430f0835611b156b33-94bb-49c8-a923-0ff9218a10a8");
ДокументДиадок.Reject(ВходящийДокумент.ТекстОтказаПодписи);
```
ДокументДиадок.type	- "UniversalTransferDocument".
Метод объекта не обнаружен (Reject)

**Comment by GilimkhanovDenis** [comment]
Добрый день

У документа УПД нет метода Reject. Вместо него используйте [ReplySendTask](https://diadocsdk-1c.readthedocs.io/ru/latest/CreateReplySendTask-(Document).html)
Лучше вообще для всех документов использовать данный объект.
Примеры в документации поправим
