### ISSUE TITLE
Расхождения значений статусов

### ISSUE THREAD

**Issue by zelinskayas** [diadoc/diadocsdk-1c-docs#315]
Добрый день!
Есть пример документа. 
При запросе через COM-интерфейс для Diadoc API:

=== Запрос документа ========
ID=dbd5fe61-bc88-4bdc-8a6b-eebdddff2c991e07a003-12f4-4029-9d35-e91334aa6645
FileName=ON_SCHFDOPPR_2BM-7705872331-770501001-201407040938463928272_2BM-7709963597-770901001-201412090309094020194_20190429_556840f0-b340-42ff-b65e-f37fc7339b70.xml
Status=OutboundWaitingForSenderSignature
RevocationStatus=RevocationStatusNone
RoamingNotificationStatus=RoamingNotificationStatusNone
SenderSignatureStatus=WaitingForSenderSignature
RecipientResponseStatus=RecipientResponseStatusUnknown
=============================

На сайте https://diadoc.kontur.ru документ подписан и отправлен.
При его сохранении из веб-страницы название файла совпадает с тем, что указано выше.
То есть, мы предполагаем, что это один и тот же документ. 
В чем может быть причина такого расхождения значений статусов и как исправить эту ситуацию?

**Comment by GilimkhanovDenis** [comment]
Попробуйте перезапросить документ
На компоненте 5.27.1 воспроизвести не удалось

**Comment by zelinskayas** [comment]
Обновили компоненту, перезапросили, на всякий случай вывели версию.
Кроме версии, остальные значения атрибутов объекта, полученного методом GetDocumentById('dbd5fe61-bc88-4bdc-8a6b-eebdddff2c991e07a003-12f4-4029-9d35-e91334aa6645')

Ситуация не изменилась:
GetVersion=5.27.1.458
ID=dbd5fe61-bc88-4bdc-8a6b-eebdddff2c991e07a003-12f4-4029-9d35-e91334aa6645
FileName=ON_SCHFDOPPR_2BM-7705872331-770501001-201407040938463928272_2BM-7709963597-770901001-201412090309094020194_20190429_556840f0-b340-42ff-b65e-f37fc7339b70.xml
Status=OutboundWaitingForSenderSignature
RevocationStatus=RevocationStatusNone
RoamingNotificationStatus=RoamingNotificationStatusNone
SenderSignatureStatus=WaitingForSenderSignature
RecipientResponseStatus=RecipientResponseStatusUnknown

**Comment by GilimkhanovDenis** [comment]
dbd5fe61-bc88-4bdc-8a6b-eebdddff2c991e07a003-12f4-4029-9d35-e91334aa6645 - это идентификатор черновика
после того как черновик превращается в отправленный документ, меняется идентификатор, по которому можно запросить отправленный документ.

Из этого черновика был создан документ с идентифкатором 07e33e67-02eb-47f1-8689-f7b41c66c5961e07a003-12f4-4029-9d35-e91334aa6645

Для черновика указанные статусы - нормальное поведение. Чтобы получить статусы уже отправленного документа укажите идентификатор созданного из черновика документа
