### ISSUE TITLE
ReplySendTask.Send: HTTP error 409 DocumentService.InvalidDocumentState. При отказе в подписании документа УПД (RejectDocument)

### ISSUE THREAD

**Issue by olleksa** [diadoc/diadocsdk-1c-docs#316]
При попытке отказа в подписании документа УПД, получаю ошибку InvalidDocumentState.
О каком состоянии документа идет речь? В чем может быть ошибка?

Версия 5.26.5.438

![изображение](https://user-images.githubusercontent.com/41576111/60268363-e69cf900-98f4-11e9-8848-cbcfd1113e50.png)

![изображение](https://user-images.githubusercontent.com/41576111/60268592-67f48b80-98f5-11e9-8e99-593be82e1338.png)

![1Снимок](https://user-images.githubusercontent.com/41576111/60269021-59f33a80-98f6-11e9-915a-5771d9a4b653.JPG)
![2Снимок](https://user-images.githubusercontent.com/41576111/60269022-59f33a80-98f6-11e9-86fe-dd9ed09fd528.JPG)

**Comment by GilimkhanovDenis** [comment]
Если ошибка актуальна, то нужна ссылка на документ, на котором воспроизводится
