### ISSUE TITLE
Ошибка акцепта входящего приглашения от контрагента

### ISSUE THREAD

**Issue by Aleksey2W** [diadoc/diadocsdk-1c-docs#317]
Используется COM компонента v5.27.3.462 x64 для произвольных систем.

`Counteragent.AcquireCounteragent(Сообщение);`

Выходит ошибка:
##100[Ошибка сервера Диадок]code:409, HTTP error: Cannot accept invitation from 6d1d9592-9117-4775-b593-d57d21bc28fc with attachment with signature requested; use PostMessagePatch instead

Метод PostMessagePatch нашел только в документации для api 
http://api-docs.diadoc.ru/ru/latest/http/PostMessagePatch.html?highlight=PostMessagePatch

Для компоненты не описано.

**Comment by volodkindv** [comment]
Добрый день.
Контрагент прислал приглашение с вложенным файлом. Для принятия таких приглашений необходимо найти входящий документ с типом TrustConnectionRequest и подписать его через ReplySendTask.
Найти можно через GetDocuments:
https://diadocsdk-1c.readthedocs.io/ru/latest/DocumentsTask.html?highlight=TrustConnectionRequest
