### ISSUE TITLE
Значения реквизита OrgType  в версии 5.27.4.463

### ISSUE THREAD

**Issue by NickVStepin** [diadoc/diadocsdk-1c-docs#318]
При формировании на отправку УПД столкнулся с проблемой реквизита OrgType у Seller.
Пытался заполнить как "LegalEntity", "СвЮЛУч" все одно получаю ошибку:

{ОбщийМодуль.ЭДОВызовСервера(1565)}: Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 14, Position: 27, /UniversalTransferDocument[1]/Sellers[1]/Seller[1]/OrganizationReference[1]/@OrgType: The 'OrgType' attribute is invalid - The value 'СвЮЛУч' is invalid according to its datatype 'OrganizationType' - The Enumeration constraint failed.
Line: 14

Какие значения он может принимать по последней версии?

**Comment by NataliaShumikhina** [comment]
Добрый день! В OrgType надо указывать числовой идентификатор 1, 2, 3 или 4,  где:
1 - Сведения о юридическом лице, состоящем на учете в налоговых органах // СвЮЛУч
2 - Сведения об индивидуальном предпринимателе// СвИП
3 - Сведения об иностранном лице, не состоящем на учете в налоговых органах // СвЮлНеУч, СвИнНеУч
4 - Сведения о физическом лице // СвФл

**Comment by NickVStepin** [comment]
так работает.
