### ISSUE TITLE
5.27.4.463 проблема со структурами Seller, Buyer, Signer

### ISSUE THREAD

**Issue by NickVStepin** [diadoc/diadocsdk-1c-docs#319]
Наткнулся на следующее:
заполняю в документе Seller.OrganizationReference, Buyer.OrganizationReference и Signer.SingerReference

парсер требует заполнить:

{ОбщийМодуль.ЭДОВызовСервера(1571)}: Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalTransferDocument/Signers/SignerReference: @Inn is required
/UniversalTransferDocument/Sellers/Seller/OrganizationReference: Address is required
/UniversalTransferDocument/Buyers/Buyer/OrganizationReference: Address is required

Но у структуры SignerReference нет реквизита Inn, а у структуры OrganizationReference - нет Address.

Для примера скриншот com-объекта для Seller

![image](https://user-images.githubusercontent.com/52532223/60669954-368d3a00-9e78-11e9-9e1a-d40db7529a72.png)

**Comment by GilimkhanovDenis** [comment]
Необходимо заполнить или OrganizationReference или OrganizationDetails

Предлагаю воспользоваться методом https://diadocsdk-1c.readthedocs.io/ru/latest/SaveUserDataXSD.html и посмотреть правила заполнения объектов для динамического контента

**Comment by NickVStepin** [comment]
я и заполняю структуру OrganizationReference (а OrganizationDetails - нет), а парсер хочет чтобы я внутри OrganizationReference заполнил Address, а его там нет.

пробовал для COM-объекта Организация вызвать сей метод (SaveUserDataXSD) - пишет метод не найден.
Пример вызова можете привести

**Comment by NickVStepin** [comment]
![image](https://user-images.githubusercontent.com/52532223/60672561-62132300-9e7e-11e9-9aec-913a8a0c4cb1.png)

**Comment by NickVStepin** [comment]
Вот объект, к которому пытаюсь вызвать SaveUserDataXSD

![image](https://user-images.githubusercontent.com/52532223/60674173-35f9a100-9e82-11e9-8d4a-01ed11d70fb6.png)

**Comment by NickVStepin** [comment]
А вот результат вызова
![image](https://user-images.githubusercontent.com/52532223/60674251-65101280-9e82-11e9-82f6-8f6f540fadb8.png)

**Comment by GilimkhanovDenis** [comment]
Про отсутствие метода: если правильно понимаю, то используете COM версию. Туда забыли этот метод протянуть, скоро исправим.

про заполнение seller'ов:
я делаю так

```

Процедура Заполнить_DynamicExtendedOrganizationInfo(ExtendedOrganizationInfo, BoxId=Неопределено, OrgType = "1")
	
	Если BoxId <> Неопределено Тогда
		OrganizationReference = ExtendedOrganizationInfo.OrganizationReference;
		OrganizationReference.BoxId = СтрокаВГУИД(BoxId);
		OrganizationReference.OrgType = OrgType;
	КонецЕсли;
	
КонецПроцедуры


Процедура ЗаполнитьКоллекцию_DynamicSellers(ВладелецКоллекции, BoxId)
	
	Seller = ВладелецКоллекции.AddSeller();
	Заполнить_DynamicExtendedOrganizationInfo(Seller, BoxId);
	
КонецПроцедуры


Процедура Заполнить_DynamicContent(Content, MyOrganization, Counteragent)
    ...
    UniversalTransferDocument = Content.UniversalTransferDocument;
    ЗаполнитьКоллекцию_DynamicSellers(UniversalTransferDocument.Sellers,  MyOrganization.Id);
    ...	
КонецПроцедуры


```

**Comment by NickVStepin** [comment]
Да бог с ним, с методом. Когда добавят, посмотрим.

У меня примерно Ваш же вариант заполнения работает. Беда в том, что парсер требует, чтобы в коллекции OrganizationReference я заполнил Address, которого там нет.
Т.е. я для Seller заполняю OrganizationReference.BoxId и OrganizationReference.OrgType и получаю отлуп:

Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalTransferDocument/Signers/SignerReference: @INN is required
/UniversalTransferDocument/Sellers/Seller/OrganizationReference: Address is required

ну и подобного же рода проблему с подписью, т.к. в коллекции SignerReference нет INN.

**Comment by GilimkhanovDenis** [comment]
7c284534-68f4-4ce8-9c0b-e33ef24d1f56 - идентификатор тестовой организации. у неё не заполнен адрес
Если [заполните его](https://diadoc.kontur.ru/7c284534-68f4-4ce8-9c0b-e33ef24d1f56/CompanyDetails), то данные по адресу подтянутся

То есть, если указаны данные в OrganizationReference / SignerReference и т.п. то будут взяты данные, которые есть на сервере Диадок
Если заполнено ...Details - это данные, которые заполняются вручную

Для SignerReference заполните полномочия подписанта: либо [через веб](https://diadoc.kontur.ru/7c284534-68f4-4ce8-9c0b-e33ef24d1f56/Preferences), либо объектом https://diadocsdk-1c.readthedocs.io/ru/latest/CreateSetExtendedSignerDetailsTask.html

**Comment by NickVStepin** [comment]
про seller и signer - понятно, а как с buyer быть? Там та же проблема, а я же не могу за покупателя его адрес заполнить... :) Т.е. за чужую сторону лучше всегда OrganizationDetails использовать вместо OrganizationReference?

**Comment by GilimkhanovDenis** [comment]
Как правило у организаций, работающих в Диадок заполнен адрес. Исключениями являются тестовые организации
для контрагента можно проверить, заполнен ли адрес: https://diadocsdk-1c.readthedocs.io/ru/latest/Counteragent.html?highlight=Address

**Comment by NickVStepin** [comment]
заполнил адреса у продавца и покупателя, заполнил для подписанта полномочия.
Теперь парсер не ругается, но получаю вот такое:

Не удалось получить данные покупателя документа из Диадок
{ОбщийМодуль.ЭДОВызовСервера(1076)}: Ошибка при вызове метода контекста (GetDynamicContent): Произошла исключительная ситуация (DocumentBase.GetDynamicContent): ##100[Ошибка сервера Диадок]code:400, HTTP error: Request body is empty, but XML document content expected

покупателя задаю через OrganizationReference, заполняя BoxId = uuid и OrgType = 1.
Покупатель тоже тестовый

**Comment by GilimkhanovDenis** [comment]
Для какого документа вызываете метод GetDynamicContent, можете дать ссылку?

**Comment by NickVStepin** [comment]
Это вопрос снят. Документ передался, это я уже когда пытаюсь статус документа прочитать возникает.

Спасибо за помощь.

**Comment by GilimkhanovDenis** [comment]
Могу закрыть этот тикет?
