### ISSUE TITLE
Объект AcceptanceCertificateSellerContent

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#32]
Прошу пояснить, чем отличается Signer (подписант) от Official (лицо, подписывающее со стороны исполнителя)

**Comment by denver069** [comment]
Объект [Signer](http://diadocsdk-1c.readthedocs.io/ru/latest/Signer.html?highlight=Signer) представляет информацию о подписанте документа, в то время как объект [Official](http://diadocsdk-1c.readthedocs.io/ru/latest/Official.html?highlight=Official) представляет информацию только должностном лице без полей связанных с подписью.
