### ISSUE TITLE
Возможно ли получить печ.форму УПД с подписями

### ISSUE THREAD

**Issue by NickVStepin** [diadoc/diadocsdk-1c-docs#320]
Возможно ли получить печ.форму УПД с подписями?

Сделал вызов GetPrintForm, надеясь увидеть печ.форму УПД в формате PDF. А получил PDF c xml-структурой.

**Comment by GilimkhanovDenis** [comment]
Какую версию компоненты используете?
Для какого документа воспроизводится  (по возможности ссылку на документ)?

**Comment by GilimkhanovDenis** [comment]
Для УПД 820 пока нет печатной формы - она в разработке

**Comment by NickVStepin** [comment]
А когда будет?

**Comment by GilimkhanovDenis** [comment]
Ориентировочный срок появления печатных форм УПД 820 - конец лета
