### ISSUE TITLE
Как получить список измененных документов

### ISSUE THREAD

**Issue by Alexandr1604** [diadoc/diadocsdk-1c-docs#321]
Каким методом можно получить список только измененных документов за период.

Пример:
За период с 01.07.19 по 10.07.19 было заведено 10 документов в Диадок. 
12.07.19 было произведено изменение 3 документов в Диадоке.
Каким методом мы сможем получить выборку именно этих 3 документов, которые редактировались 12.07.19. 
Использование метода для получения всех 10 документов и проведение сравнения для выявления отличий не подходит, так как приходится обрабатывать большой объем данных.

**Comment by einfoman** [comment]
Добрый день!
Я правильно понимаю, что хочется фильтровать документы по дате изменения? Примерно как в вебе  по Дате изменения статуса в расширенном поиске? К сожалению, в данный момент в апи такой возможности нет

**Comment by Alexandr1604** [comment]
Я так понимаю, что есть похожий метод, который выдает изменения - GetDocumentEventList. Но нужно знать eventID.

**Comment by GilimkhanovDenis** [comment]
Какая-то помощь ещё требуется?
