### ISSUE TITLE
Аннулировать собственную УПД 820

### ISSUE THREAD

**Issue by NickVStepin** [diadoc/diadocsdk-1c-docs#323]
Как для  библиотеки версии 5.27.4.463 правильно сформировать задание на аннулирование ранее отправленного покупателю документа УПД.

Пробовал через ДокументДиадок.CreateReplySendTask2("RevocationRequest") - ничего не происходит, ошибок не возвращается, но и у покупателя ничего не меняется, также как и в статусе документа.
Если важно, то документ еще не подписан со стороны покупателя.

**Comment by NickVStepin** [comment]
при заполнении подписи, требует заполнения поля "LastName", которого в структуре COM-объекта Signer нет.

![Снимок](https://user-images.githubusercontent.com/52532223/61374687-a7cfe280-a8a5-11e9-8f43-6919019a8663.PNG)

**Comment by GilimkhanovDenis** [comment]
Обновите компоненту
Для решения нужна ссылка на документ, на котором воспроизводится сценарий
и полный текст получаемой ошибки

**Comment by NickVStepin** [comment]
DocumentId = "a5ac80ca-c8f6-4c53-8f96-e0cf3dba545a20d9c9de-6667-435d-a730-6d8035dd33c9"
PathUrl = "/858f928a-ed7d-4c04-ac5b-0169b30de77a/Document/Show?letterId=a5ac80ca-c8f6-4c53-8f96-e0cf3dba545a&documentId=20d9c9de-6667-435d-a730-6d8035dd33c9"

Content.type = "RevocationRequest"
Content.comment = "Подтвердите аннулирование ошибочно отправленного документа"
Content.Signer.FirstName = "Николай"
Content.Signer.IsSoleProprietor = True
Content.Signer.SoleProprietorRegistrationCertificate = "FECDED6AC90C68250C0FCCF01E9EBBD8BE038B91"

но пробовал и без сертификата и IsSoleProprietor = false

результат:

Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: LastName is required
Position is required

как я присылал ранее в структуре Signer поля LastName, Position отсутствуют как класс.

**Comment by NickVStepin** [comment]
компонента 27.5.465

**Comment by GilimkhanovDenis** [comment]
Попробуйте заполнить JobTitle

**Comment by NickVStepin** [comment]
Такой вариант сработал.
Только я не понял (может быть это проблема тестового режима), когда я подписывал запрос, то указал Фамилию, Имя, должность, отпечаток сертификата (не тестового), а у покупателя подпись видна как будто подписывал тестовым сертификатом сотрудник в нем указанный.

**Comment by NickVStepin** [comment]
А как правильно получить комментарии при ответах покупателя. AnyComment() возвращает только пустые значения

**Comment by GilimkhanovDenis** [comment]
Тестовые документы всегда подписываются служебным тестовым сертом

**Comment by GilimkhanovDenis** [comment]
Про комментарий:  Document.GetAnyComment("RecipientAttachmentComment") сейчас возвращается комментарий к титулу отправителя

**Comment by GilimkhanovDenis** [comment]
Проверьте на релизе 5.28.0

**Comment by GilimkhanovDenis** [comment]
Закрываю тикет
Если проблема актуальна, то переоткройте его

**Comment by volodkindv** [comment]
Вряд ли это актуально, но для истории оставлю.
```
Content.Signer.SoleProprietorRegistrationCertificate = "FECDED6AC90C68250C0FCCF01E9EBBD8BE038B91"
```
В поле "soleproprietorregistrationcertificate" необходимо указывать не отпечаток сертификата, а строку: [свидетельство о гос.регистрации ИП](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Signer.html?highlight=soleproprietorregistrationcertificate).
