### ISSUE TITLE
Отмена аннулирования

### ISSUE THREAD

**Issue by NickVStepin** [diadoc/diadocsdk-1c-docs#324]
Если отправленный документ находится в статусе аннулирования RevocationAccepted, то можно ли и как это аннулирование отменить?

**Comment by agarochka** [comment]
Добрый день. Аннулирование документа не отменить.

**Comment by NickVStepin** [comment]
А отменить собственный запрос на аннулирование, пока он не принят второй стороной тоже нельзя?
Статус аннулирования - RevocationIsRequestedByMe

**Comment by agarochka** [comment]
Такой возможности тоже нет.

**Comment by sunnybear** [comment]
отличная система электронного документооборота, браво!
