### ISSUE TITLE
Проблема с указанием полей в формализованных док-тах TovTorg, UniversalTransferDocument. Ошибка в PackageSendTask2.AddDocument()

### ISSUE THREAD

**Issue by SlashSep** [diadoc/diadocsdk-1c-docs#325]
Добрый день!
Используем COM компонента v5.27.5.465 x64 для произвольных систем.
Особенность - DLL зарегистрирована на сервере, вся работа с COM реализована через  MSSQL.
1. Получаю объект @DocumentToSend (формализованый Торг12)
EXECUTE @rc = sp_OAMethod @PackageSendTask, 'AddDocument(TovTorg)', @DocumentToSend output
Все поля Content. задаются без проблем. Проблема возникает при попытке задать Content.Table.Total - полуаю ошибку "TovTorgTable.put_Total. Неверный тип варианты".
declare @Total float
select @Total = 100
EXECUTE @rc = sp_OASetProperty @DocumentToSend, 'Content.Table.Total', @Total
Перепробовал все типы переменной (int, string, numeric, decimal и т.п.) - ни один не походит, в любом случае ошибка.
Все то же самое по полям TotalGross, TotalNet, TotalWithVatExcluded, TotalVat

2. Получаю объект @DocumentToSend (формализованый УПД)
EXECUTE @rc = sp_OAMethod @PackageSendTask, 'AddDocument(UniversalTransferDocument)', @DocumentToSend output
Все тоже самое что в пункте 1, только никаких ошибок не возникает, но и значенте не заполняется.
declare @Total float
select @Total = 100
EXECUTE @rc = sp_OASetProperty @DocumentToSend, 'Content.InvoiceTable.Total', @Total
То же самое для табличной части Content.InvoiceTable.AddItem()

3. Получаю объект  @PackageSendTask2
EXECUTE @rc = sp_OAMethod @Organization, 'CreatePackageSendTask2', @PackageSendTask2 output
При попытке вызова метода AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01") - получаю ошибку "Неверная версия вложения".
Попробовал с разными типами документов - все равно ошибка.

С уважением, Алексей.

**Comment by GilimkhanovDenis** [comment]
I
Ошибку "Неверная версия вложения" чинили в версии 5.27.3
Проверьте, что нигде не закэшилась старая версия:
1) разрегистрируйте все версии нашей компоненты командой regsvr32 /u
2) проверьте, что в реестре не осталось веток объектов нашей компоненты (можно искать по слову "diadoc") ни в ветке пользователя, из-под которого вызывается код, ни в ветке администратора
3) Зарегистрируйте последнюю версию компоненты и проверьте вызов метода PackageSendTask2.AddDocument ещё раз

II
"Неверный тип варианты"
Попробую воспроизвести. Ответ дам позже

**Comment by SlashSep** [comment]
Добрый день!
Разрегистрация DLL, чистка реестра и регистрация по новой вылечила PackageSendTask2.AddDocument.
Остальные проблемы остались.

С уважением, Алексей.

**Comment by GilimkhanovDenis** [comment]
Добрый день
Обновили компоненту до версии [5.28.1.479](http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_28_1.html). Ошибка должна уйти. Проверьте, пожалуйста

**Comment by SlashSep** [comment]
Добрый день!
Обновили версию до 5.28.1.479

Метод AddDocument(TovTorg) - ошибка "Неверный тип варианты" пропала, значения нормально устанавливаются и считываются.

Осталась проблема с AddDocument(UniversalTransferDocument), при установки значения в Content.InvoiceTable.Total - ошибки нет, но значение не устанавливается, при считывании null. Это же касается значений табличной части. Получаем Content.InvoiceTable.AddItem(), пытаюсь записать например Price (EXECUTE @rc = sp_OASetProperty @InvoiceItems, 'Price', 100.0) - ошибки нет, но при считывании значение пустое.

С уважением, Алексей.

**Comment by GilimkhanovDenis** [comment]
Какой тип у переменной в которую получаете значение Content.InvoiceTable.Total ?

**Comment by GilimkhanovDenis** [comment]
Алексей, добрый день.
К сожалению что-то сделать с данным поведением мы пока не сможем, подробности ниже


Попробовал такие варианты (опыта программирования на sql почти нет, поэтому код не очень красивый):
`-- Создаём задание на отправку
DECLARE @PackageSendTask int
EXECUTE @hr = sp_OAMethod @MyOrganization, 'CreatePackageSendTask', @PackageSendTask OUTPUT

IF @hr <> 0  
BEGIN  
   EXEC sp_OAGetErrorInfo @PackageSendTask, @src OUT, @desc OUT   
   raiserror('Error Creating COM Component 0x%x, %s, %s',16,1, @hr, @src, @desc)   
END;


DECLARE @TovTorgToSend int
EXECUTE @hr = sp_OAMethod @PackageSendTask, 'AddDocument', @TovTorgToSend OUTPUT, 'TovTorg'

-- FLOAT
DECLARE @Total_float float
SELECT @Total_float = 100
EXECUTE @hr = sp_OASetProperty @TovTorgToSend, 'Content.Table.Total', @Total_float

IF @hr <> 0  
BEGIN  
   EXEC sp_OAGetErrorInfo @TovTorgToSend, @src OUT, @desc OUT   
   raiserror('Error Set Value 0x%x, %s, %s',16,1, @hr, @src, @desc)   
END;

DECLARE @OLETotalValue_float float
EXECUTE @hr = sp_OAGetProperty @TovTorgToSend, 'Content.Table.Total', @OLETotalValue_float output
PRINT 'Значение Total (float):'
PRINT @OLETotalValue_float
PRINT '-------'

IF @hr <> 0  
BEGIN  
   EXEC sp_OAGetErrorInfo @TovTorgToSend, @src OUT, @desc OUT   
   raiserror('Error Creating COM Component 0x%x, %s, %s',16,1, @hr, @src, @desc)   
END;



-- DECIMAL
DECLARE @Total_decimal decimal
SELECT @Total_decimal = 101
EXECUTE @hr = sp_OASetProperty @TovTorgToSend, 'Content.Table.Total', @Total_decimal

IF @hr <> 0  
BEGIN  
   EXEC sp_OAGetErrorInfo @TovTorgToSend, @src OUT, @desc OUT   
   raiserror('Error Set Value 0x%x, %s, %s',16,1, @hr, @src, @desc)   
END;

DECLARE @OLETotalValue_decimal decimal
EXECUTE @hr = sp_OAGetProperty @TovTorgToSend, 'Content.Table.Total', @OLETotalValue_decimal output
PRINT 'Значение Total (decimal):'
PRINT @OLETotalValue_decimal
PRINT '-------'

IF @hr <> 0  
BEGIN  
   EXEC sp_OAGetErrorInfo @TovTorgToSend, @src OUT, @desc OUT   
   raiserror('Error Creating COM Component 0x%x, %s, %s',16,1, @hr, @src, @desc)   
END;



-- INT
DECLARE @Total_int int
SELECT @Total_int = 102
EXECUTE @hr = sp_OASetProperty @TovTorgToSend, 'Content.Table.Total', @Total_int

IF @hr <> 0  
BEGIN  
   EXEC sp_OAGetErrorInfo @TovTorgToSend, @src OUT, @desc OUT   
   raiserror('Error Set Value 0x%x, %s, %s',16,1, @hr, @src, @desc)   
END;

DECLARE @OLETotalValue_int int
EXECUTE @hr = sp_OAGetProperty @TovTorgToSend, 'Content.Table.Total', @OLETotalValue_int output
PRINT 'Значение Total (int):'
PRINT @OLETotalValue_int
PRINT '-------'

IF @hr <> 0  
BEGIN  
   EXEC sp_OAGetErrorInfo @TovTorgToSend, @src OUT, @desc OUT   
   raiserror('Error Creating COM Component 0x%x, %s, %s',16,1, @hr, @src, @desc)   
END;




-- BIGINT
DECLARE @Total_bigint bigint
SELECT @Total_bigint = 103
EXECUTE @hr = sp_OASetProperty @TovTorgToSend, 'Content.Table.Total', @Total_bigint

IF @hr <> 0  
BEGIN  
   EXEC sp_OAGetErrorInfo @TovTorgToSend, @src OUT, @desc OUT   
   raiserror('Error Set Value 0x%x, %s, %s',16,1, @hr, @src, @desc)   
END;

DECLARE @OLETotalValue_bigint bigint
EXECUTE @hr = sp_OAGetProperty @TovTorgToSend, 'Content.Table.Total', @OLETotalValue_bigint output
PRINT 'Значение Total (bigint):'
PRINT @OLETotalValue_bigint
PRINT '-------'

IF @hr <> 0  
BEGIN  
   EXEC sp_OAGetErrorInfo @TovTorgToSend, @src OUT, @desc OUT   
   raiserror('Error Creating COM Component 0x%x, %s, %s',16,1, @hr, @src, @desc)   
END;




-- REAL
DECLARE @Total_real real
SELECT @Total_real = 104
EXECUTE @hr = sp_OASetProperty @TovTorgToSend, 'Content.Table.Total', @Total_real

IF @hr <> 0  
BEGIN  
   EXEC sp_OAGetErrorInfo @TovTorgToSend, @src OUT, @desc OUT   
   raiserror('Error Set Value 0x%x, %s, %s',16,1, @hr, @src, @desc)   
END;

DECLARE @OLETotalValue_real real
EXECUTE @hr = sp_OAGetProperty @TovTorgToSend, 'Content.Table.Total', @OLETotalValue_real output
PRINT 'Значение Total (real):'
PRINT @OLETotalValue_real
PRINT '-------'

IF @hr <> 0  
BEGIN  
   EXEC sp_OAGetErrorInfo @TovTorgToSend, @src OUT, @desc OUT   
   raiserror('Error Creating COM Component 0x%x, %s, %s',16,1, @hr, @src, @desc)   
END;





-- VARCHAR255
DECLARE @Total_varchar VARCHAR(255)
SELECT @Total_real = '105'
EXECUTE @hr = sp_OASetProperty @TovTorgToSend, 'Content.Table.Total', @Total_varchar

IF @hr <> 0  
BEGIN  
   EXEC sp_OAGetErrorInfo @TovTorgToSend, @src OUT, @desc OUT   
   raiserror('Error Set Value 0x%x, %s, %s',16,1, @hr, @src, @desc)   
END;

DECLARE @OLETotalValue_varchar VARCHAR(255)
EXECUTE @hr = sp_OAGetProperty @TovTorgToSend, 'Content.Table.Total', @OLETotalValue_varchar output
PRINT 'Значение Total (varchar):'
PRINT @OLETotalValue_varchar
PRINT '-------'

IF @hr <> 0  
BEGIN  
   EXEC sp_OAGetErrorInfo @TovTorgToSend, @src OUT, @desc OUT   
   raiserror('Error Creating COM Component 0x%x, %s, %s',16,1, @hr, @src, @desc)   
END;`

Результаты таковы:
числовые типы возвращаются;
Строковые типы (nvarchar, varchar) по какой-то причине считаются, пустыми. При этом в отладке мы видим, что значение в поле присваивается и из getter'а мы его возвращаем;
Пробовал также возвращать значение поля в sql_variant и приводить значение к varchar(255) - тот же htpekmnfn, что для обычных строк.


Причина: похоже, что MSSQL не умеет работать с полями, у которых тип принимаемого значения в setter'е отличается от типа возвращаемого значения в getter'е.

В данных случаях принимаем на вход [VARIANT](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-oaut/3fe7db9f-5803-4dc4-9d14-5425d3f5461f), а возвращаем [BSTR](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-oaut/9c5a5ce4-ff5b-45ce-b915-ada381b34ac1). Возможно, у вас как у специалиста по MSSQL есть какие-то рецепты как обойти такие сценарии.

Так как внутреннее состояние объектов всё-таки меняется при установке значений, то отправляться  документ должен.

**Comment by SlashSep** [comment]
Добрый вечер!
У меня вот какие мысли по этом поводу.
Уточним, мы используем метод AddDocument объекта PackageSendTask (не PackageSendTask2).
В качестве параметра FormalizedDocumentType мы определяем создаваемую структуру.
Имеем две ситуации.

Первая ситуация - до исправления предыдущей ошибки выполняем 'AddDocument(TovTorg)'.
Получили объект DocumentToSend. Пытаемся задать Content.Table.Total - получали исключение с описанием (спс. программеру) "TovTorgTable.put_Total. Неверный тип варианты".
Это исправлено.

Вторая ситуация - отличие только в параметре вызова метода AddDocument. В данном случае AddDocument(UniversalTransferDocument). В полученном DocumentToSend указываем подобный параметр другой структуры и не получаем исключения! Вроде как все без ошибок, но значение не задано.

Вопрос, неужели методы записи параметров для разных структур отличаются (put_)? Почему не получаем исключение во втором варианте?

На мой взгляд необходимо сравнить методы записи параметров для различных структур и типы данных. 

Возможно я не прав?

С уважением, Алексей.

**Comment by GilimkhanovDenis** [comment]
> Уточним, мы используем метод AddDocument объекта PackageSendTask (не PackageSendTask2)
Да, у себя воспроизводил тоже на [PackageSendTask](http://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask.html)'е



> Первая ситуация - до исправления предыдущей ошибки выполняем 'AddDocument(TovTorg)'.
> Получили объект DocumentToSend. Пытаемся задать Content.Table.Total - получали исключение с описанием (спс. программеру) "TovTorgTable.put_Total. Неверный тип варианты".
> Это исправлено.
Предлагаю эту ситуацию не рассматривать в дальнейшем обсуждении - эта ошибка ушла



> Вторая ситуация - отличие только в параметре вызова метода AddDocument. В данном случае AddDocument(UniversalTransferDocument). В полученном DocumentToSend указываем подобный параметр другой структуры и не получаем исключения! Вроде как все без ошибок, но значение не задано

Такое поведение будет для всех полей, которые можно задать что числом, что строкой - там мы принимаем VARIANT; а возвращаемое значение полей имеет строковый тип BSTR.
MSSQL, видимо, не может такую ситуацию понять:
В числовой тип значение возвращается, а возврат в строковую переменную оказывается пустым. Код у нас в обоих случаях один и тот - мы всегда возвращаем строку.
При этом во внутреннем объекте значение заполняется. Не может только правильно интерпретироваться возвращаемое значение на стороне MSSQL.
Такое поведение воспроизводится что для TovtorgToSend.TovTorgTable.Total, что для UtdToSend.InvoiceTable.Total

> На мой взгляд необходимо сравнить методы записи параметров для различных структур и типы данных
Запись, как я сказал выше, происходит без проблем - внутренние объекты заполняются. Проблема в обработке возвращаемого значения.
Попробовал изменить возвращаемое значение в объявлении функции getter'а на VARIANT. Такой код
`DECLARE OLETotalValue_sql_variant sql_variant
-- пропущен код, который заполняет значение
PRINT CONVERT(varchar(255), OLETotalValue_sql_variant)`
вывел заданное значение на печать.

!!!!
Увы, изменение возвращаемого типа может сломать других интеграторов, поэтому на такой шаг мы пока не готовы идти

С уважением, Денис.

**Comment by SlashSep** [comment]
Добрый день!
Огромное спасибо за помощь!

С уважением, Алексей
