### ISSUE TITLE
проблемы с Diadoc_5_28_0_472  версия для 32 разрядной машины

### ISSUE THREAD

**Issue by amore1302** [diadoc/diadocsdk-1c-docs#326]
проблемы с Diadoc_5_28_0_472  версия для 32 разрядной машины

В Описании что добавлено в 5.28.0 написано что эта версия поддерживает 
приказ ФНС от 8 апреля 2019 г. N ММВ-7-15/176@ 

Формируем новый УПД и при этом получаем 
ВерсФорм="5.01" ВерсПрог="Diadoc 1.0">

т.е. получается что документ не в новом приказе ?

**Comment by amore1302** [comment]
вот пример электронного домумента созданного этой версией библиотеки

[https://diadoc.kontur.ru/13776489-a5d8-4514-bc95-f8cddadd2d00/Document/Show?letterId=e969e392-d2de-4b8b-abce-d065c3a2f02a&documentId=822c0344-f847-4176-b292-bc23c3b695b7](url)

**Comment by volodkindv** [comment]
Здравствуйте.
Эта сборка поддерживает работу со входящими документами в формате 5.02. Отправка происходит в формате 5.01. При необходимости отправлять именно 5.02 можно воспользоваться [PackageSendTask2](https://diadocsdk-1c.readthedocs.io/ru/latest/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocument): 
Подробнее можно почитать в новости: https://www.diadoc.ru/blog/7878

**Comment by amore1302** [comment]
Метод
 PackageSendTask2.AddDocument(TitleName, Function, Version)
Описание в документации

TitleName: строка название типа документа
Function строка функция документа
Version строка версия документа

Кроме параметра параметра Title
Для параметров Function и Version абсолютно непонятно
допустимые значения этих параметром
меня сейчас интересует эти параметры для документ УПД и УКД
можно расписать подробно допустимые значения этих параметров

**Comment by GilimkhanovDenis** [comment]
Получить возможные версии тройки TitleName, Function, Version можно методом [GetDocumentTypes](https://diadocsdk-1c.readthedocs.io/ru/latest/ComObjects/Organization.html#Organization.GetDocumentTypes)

**Comment by amore1302** [comment]
> 
> 
> Получить возможные версии тройки TitleName, Function, Version можно методом [GetDocumentTypes](https://diadocsdk-1c.readthedocs.io/ru/latest/ComObjects/Organization.html#Organization.GetDocumentTypes)
Это не то функция возвращает возможные типы документов
тип документа я и так знаю
мне нужно создать тип = УПД
значение функцмя в этом случае мне что писать СЧФДОП или как раньше  "InvoiceAndbasic"
Про третий параметр вообще непонятно.
Если ошибаюсь то просьба привести примерчик.

**Comment by GilimkhanovDenis** [comment]
В [DocumentTypeDescription](https://diadocsdk-1c.readthedocs.io/ru/latest/ComObjects/DocumentTypeDescription.html) есть поле Functions. У каждой [Function](https://diadocsdk-1c.readthedocs.io/ru/latest/ComObjects/DocumentFunction.html) есть Name - то что нужно поставить в качестве аргумента Function
У каждой [Function](https://diadocsdk-1c.readthedocs.io/ru/latest/ComObjects/DocumentFunction.html) есть поле Versions. У каждой [Version](Versions) есть поле Version - то. что нужно поставить в качестве аргемента Version

Для добавления УПД с помощью метода [PackageSendTask2.AddDocument](https://diadocsdk-1c.readthedocs.io/ru/latest/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocument) нужно указать версию "СЧФДОП"

Пример есть на странице документации [Как отправить документы](https://diadocsdk-1c.readthedocs.io/ru/latest/HowTo/HowTo_post_document.html)

**Comment by amore1302** [comment]
Так в том и дело раньше в документации был подробно расписан для каждого документа
возможные значения  параметра Function
Сейчас документация ( по крайней мере для 1с ) кардинально изменилось
и для того чтобы вытащить константые значения надо проделать множество действий которых раньше не было и только для того чтобы узнать допустимые значения номера версии

**Comment by amore1302** [comment]
безуспешно пытался создать документ через
PackageSendTask2

что получилось
	Пакет_2 = ТекущиаяОрганизация.CreatePackageSendTask2();
	DocumentContent =  Пакет_2.AddDocument(ДиадокЧтоСоздаем, "СЧФДОП", "utd_05_02_01");
	InvoiceContent =  DocumentContent.Content;	
Далее ничего не получается
Как из этого контекста получить  стандартный контекст УПД
Если пытаться просто проставлять значение полей в этом динамическом контексте то ничего не работает

например не выставляется код валюты и.т.д.
	InvoiceContent.Currency = "643"; // на этой строке порграмма выдает ошибку
       при заполнении других полейто же получаю ошибку )

Т.е как от динамического контекста перейти к заполнению полей УПД.



или из примера документации на странице http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html
просьба подробно расписать 
процедуру ЗаполнитьДинамическийКонтентДокумента(First_DocumentToSend.Content);

**Comment by IrinaShmonina** [comment]
Добавили в инструкцию [пример работы с динамическим контентом](http://1c-docs.diadoc.ru/ru/dev/ComObjects/DynamicContent.html).

**Comment by amore1302** [comment]
IrinaShmonina - спасибо
Спасибо за пример стало гораздо лучше но все  равно программа валиться (

Вот новый текст программы ( библиотека версии 5_28_3_491 )


Пакет_2 = Организация.CreatePackageSendTask2();

DocumentContent  =  Пакет_2.AddDocument(ДиадокЧтоСоздаем, "СЧФДОП", "utd_05_02_01");   
DynamicContent  =  DocumentContent.Content;   
InvoiceContent = DynamicContent.UniversalTransferDocument;           
.........
.........
            // 1с останавливается и выдает ошибку на следующей строке
            Платеж = InvoiceContent.AddPaymentDocument();

       
        Ошибка в 1с выглядит так
ИСХОДЯЩИЙЭЛДОК.ERT(1988)}: Поле агрегатного объекта не обнаружено (AddPaymentDocument)

**Comment by amore1302** [comment]
спасибо большое за пример
Ситуация улучшилась
но все равно документ УПД еще не создается — в этой ветке описал с чем далее столкнулся.

**Comment by volodkindv** [comment]
PaymentDocuments не является коллекцией. Внутри есть вложенный объект с именем Document, который уже является коллекцией.

![image](https://user-images.githubusercontent.com/12305552/63840555-b3312600-c99a-11e9-8646-8765935f8ca9.png)

Поэтому правильный вызов будет такой:
```DynContent_Seller.UniversalTransferDocument.PaymentDocuments.AddDocument()```

![image](https://user-images.githubusercontent.com/12305552/63840595-c512c900-c99a-11e9-82e8-64a00b775646.png)

**Comment by amore1302** [comment]
добрый день
так у меня в программе и написано как и у Вас,
но почему-то не работает.

**Comment by volodkindv** [comment]
Добрый день.
У Вас написано иначе. Во всяком случае в тикете.

> // 1с останавливается и выдает ошибку на следующей строке
> Платеж = InvoiceContent.AddPaymentDocument();

**Comment by amore1302** [comment]
вот как написано у меня в тикете ( да и в программе также )
DynamicContent = DocumentContent.Content;
InvoiceContent = DynamicContent.UniversalTransferDocument;
// 1с останавливается и выдает ошибку на следующей строке
Платеж = InvoiceContent.AddPaymentDocument();
 
отличие что Вы написали через две точки а я через помежуотчную переменную.

**Comment by volodkindv** [comment]
Вы попробовали предложенный вариант? Он у вас заработал?
`DynContent_Seller.UniversalTransferDocument.PaymentDocuments.AddDocument()`

**Comment by amore1302** [comment]
Спасибо
метод
DynContent_Seller.UniversalTransferDocument.PaymentDocuments.AddDocument()
заработал.( но раньше был немного другой метод )
 
 
Сейчас программа прерывается на операторе :
DynamicContent.UniversalTransferDocument.Creator = СтрСоздательДокумента;
 
с сообщением
Поле агрегатного объекта не обнаружено (Creator)
 
 
  
>Четверг, 29 августа 2019, 7:36 +03:00 от Данила Володькин <notifications@github.com>:
> 
>Вы попробовали предложенный вариант? Он у вас заработал? 
DynContent_Seller.UniversalTransferDocument.PaymentDocuments.AddDocument()
