### ISSUE TITLE
Вопрос по удаленным документам

### ISSUE THREAD

**Issue by zelinskayas** [diadoc/diadocsdk-1c-docs#327]
Добрый день!
Есть пример документа.
ID = 2f3b72e4-75c9-449d-8589-f8fc9ec946b5a2a89aad-3085-41bb-80f6-9d73bae6de59
На сайте https://diadoc.kontur.ru документ удален.
Подскажите пожалуйста по каким критериям можно понять, что документ был удален, интересует как из исходящих, так и на стадии нахождения документа в черновиках.
Может какой-то статус или признак?

**Comment by GilimkhanovDenis** [comment]
у объекта Document есть свойство [IsDeleted](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html)

**Comment by zelinskayas** [comment]
Спасибо! Подскажите пожалуйста, а когда обновляется этот признак, происходит ли какое-то событие Event? Документов много выгружается и нужно как-то понимать какие дозапросить на предмет удаления.

**Comment by GilimkhanovDenis** [comment]
При удалении документа будет новое событие с типом "MetaModify"

События по черновикам методом [GetDocumentEventList](https://diadocsdk-1c.readthedocs.io/ru/latest/ComObjects/Organization.html#Organization.GetDocumentEventList) не получить

**Comment by zelinskayas** [comment]
Здравствуйте! Коллеги, вы писали о том, что для исходящего документа и для черновика можно получить признак IsDeleted, только лишь уточнение что для черновика эвентов не ждать.
Мой пример-черновик:
d9135e31-1502-4a25-8629-757381d389c932205607-5e89-4ce8-9632-8254ce425687
был удален, но GetDocumentById возвращает следующее:
=== Запрос документа ========
GetVersion=5.27.1.458
ID=d9135e31-1502-4a25-8629-757381d389c932205607-5e89-4ce8-9632-8254ce425687
FileName=ON_SCHFDOPPR_2BM-7705872331-770501001-201407040938463928272_2BM-7709963597-770901001-201412090309094020194_20190806_005b2885-9034-4351-a481-8f28fcc08143.xml
CustomDocumentId=SF_RLZ_638901
Status=OutboundWaitingForSenderSignature
RevocationStatus=RevocationStatusNone
RoamingNotificationStatus=RoamingNotificationStatusNone
SenderSignatureStatus=WaitingForSenderSignature
RecipientResponseStatus=RecipientResponseStatusUnknown
IsDelete=False
=============================
