### ISSUE TITLE
Две ошибки при подписании документов

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#33]
Добрый вечер. Возникает две ошибки при подписании документов:
 
1) Возникает при попытке подписать покупателем Торг-12:
 
{.....}: Ошибка при вызове метода контекста (Send)
  ReplySendTask.Send();  
по причине:
Произошла исключительная ситуация (ReplySendTask.Send): ##100[Ошибка сервера Диадок]code:409, HTTP error: Команда AddBuyerTitle не поддерживается документом b1d8f3d1-1be3-486c-900f-602efaacf0f6:cce33363-21bc-4451-bc68-a2d019b9372f
 
2) Возникает при попытке подписать покупателем АВР:
 
{.....}: Ошибка при вызове метода контекста (Send)
  ReplySendTask.Send();  
по причине:
Произошла исключительная ситуация (ReplySendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: AcceptanceCertificateBuyerTitleInfo.Signature is required

**Comment by proger1c** [comment]
Добрый вечер.

Подскажите пожалуйста, 
 - какую версию компоненты используете?
 - ReplySendTask создается как сущность Document или DocumentPackage?

**Comment by prog22** [comment]
1) Версия 5.7.3.135, 64-х разрядная;
2) ReplySendTask создается методом CreateReplySendTask объекта типа, производного от Document.

**Comment by proger1c** [comment]
Надо посмотреть как заполнили ReplySendTask.Content

По торг - 12:
Нужен скрин содержимого сущности Document, более всего интересует поле type.
Нужен скрин содержимого самого ReplySendTask, какими данными заполнены все поля контента.

По акту выполненных работ:
Signer в ReplySendTask.Content заполнили корректно?

**Comment by prog22** [comment]
ТОРГ-12: [https://diadoc.kontur.ru/475d4e62-179c-422a-9795-110901f5a833/Document/Show?letterId=b1d8f3d1-1be3-486c-900f-602efaacf0f6&documentId=cce33363-21bc-4451-bc68-a2d019b9372f](url)

АВР: [https://diadoc.kontur.ru/475d4e62-179c-422a-9795-110901f5a833/Document/Show?letterId=1d0fe44b-f93e-47a0-9fab-0fc94eeea4c7&documentId=8ad80770-f633-481a-bb17-69e2401e4f9c](url)
![_1](https://cloud.githubusercontent.com/assets/22831210/20170354/56068b20-a745-11e6-854e-823019cd4f7e.jpg)
![_2](https://cloud.githubusercontent.com/assets/22831210/20170355/560a13f8-a745-11e6-898f-c3a2a25cd855.jpg)
![-12_1](https://cloud.githubusercontent.com/assets/22831210/20170356/56214744-a745-11e6-840a-afd299893dd2.jpg)
![-12_2](https://cloud.githubusercontent.com/assets/22831210/20170357/5624c37e-a745-11e6-846d-c485bf0a61b2.jpg)

**Comment by proger1c** [comment]
Судя по первому скрину, Вы пытаетесь поставить ответную подпись на исходящий документ. ReplySendTask предназначен для работы с входящими документами.

**Comment by prog22** [comment]
Спасибо. С ТОРГ-12 помогло.
По АВР - прежняя ошибка:

{.....}: Ошибка при вызове метода контекста (Send)
ReplySendTask.Send();
по причине:
Произошла исключительная ситуация (ReplySendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: AcceptanceCertificateBuyerTitleInfo.Signature is required

Обновленные скриншоты:
![_document](https://cloud.githubusercontent.com/assets/22831210/20175935/c6bb702e-a75e-11e6-9e3b-45facbeb5a68.JPG)
![_replysendtask](https://cloud.githubusercontent.com/assets/22831210/20175936/c6be7a8a-a75e-11e6-82d4-54989fb3a9f9.JPG)

**Comment by proger1c** [comment]
Судя по скрину, остался не заполненным Official, являющийся обязательным для заполнения.
http://diadocsdk-1c.readthedocs.io/ru/latest/AcceptanceCertificateBuyerContent.html

**Comment by prog22** [comment]
Спасибо. Вопросы закрыты.
