### ISSUE TITLE
Удаленные черновики

### ISSUE THREAD

**Issue by zelinskayas** [diadoc/diadocsdk-1c-docs#331]
Здравствуйте! Был вопрос по удаленным документам #327. 
Был получен ответ, что для исходящего документа и для черновика можно получить признак IsDeleted, только лишь уточнение что для черновика эвентов не ждать.
Мой пример-черновик:
d9135e31-1502-4a25-8629-757381d389c932205607-5e89-4ce8-9632-8254ce425687
был удален, но GetDocumentById возвращает следующее:
GetVersion=5.27.1.458
ID=d9135e31-1502-4a25-8629-757381d389c932205607-5e89-4ce8-9632-8254ce425687
FileName=ON_SCHFDOPPR_2BM-7705872331-770501001-201407040938463928272_2BM-7709963597-770901001-201412090309094020194_20190806_005b2885-9034-4351-a481-8f28fcc08143.xml
CustomDocumentId=SF_RLZ_638901
Status=OutboundWaitingForSenderSignature
RevocationStatus=RevocationStatusNone
RoamingNotificationStatus=RoamingNotificationStatusNone
SenderSignatureStatus=WaitingForSenderSignature
RecipientResponseStatus=RecipientResponseStatusUnknown
IsDelete=False

**Comment by GilimkhanovDenis** [comment]
Исправим в ближайшем релизе

**Comment by GilimkhanovDenis** [comment]
Выпустили релиз. можно проверить. Переоткройте тикет, если проблема актуальна
