### ISSUE TITLE
Не отправляется документ на подпись

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#332]
Создаю задание на согласование, все выполняется, но документ на подпись не уходить, до сегодняшнего дня прекрасно работало, что-то изменилось? 
Id документа 8297137a-4315-4776-8aa7-bef9ebe8b74b919c0e3c-b09a-42d6-b6db-b843d92a7c88
https://diadoc.kontur.ru/54d0b467-aade-47d6-8136-a2bbe2eeb67d/Document/Show?letterId=8297137a-4315-4776-8aa7-bef9ebe8b74b&documentId=919c0e3c-b09a-42d6-b6db-b843d92a7c88

ResolutionRequestTask = Document.CreateResolutionRequestTask();
				ResolutionRequestTask.ResolutionRequestType = "SignatureRequest";
				ResolutionRequestTask.TargetDepartmentId = "00000000-0000-0000-0000-000000000000";
				ResolutionRequestTask.Send();

**Comment by GilimkhanovDenis** [comment]
Добрый день
Подскажите, на какой версии компоненты такое поведение?

Пока есть подозрение, что такое может происходить на компоненте до 5.28.2 в  случае, если ранее уже был сформирован запрос на подпись (вижу, что такой был сделан 2019-08-07 09:09:03 по UTC, после чего отменён из веб-интерфейса)

**Comment by GuninaY** [comment]
Diadoc_5_26_5_438, да было такое

**Comment by GilimkhanovDenis** [comment]
Обновите компоненту до 5.28.2. Изменение

> Каждому патчу документов присваивается уникальный идентификатор

позволяет принудительно сказать серверу Диадок, что выполняется новое действие, а не повторы одного из предыдущих.
В Вашем сценарии Диадок считает, что запрос подписи уже был, завершился удачно и поэтому ничего не делает
