### ISSUE TITLE
Неизвестная ошибка при вызове метода GetPersonalCertificates

### ISSUE THREAD

**Issue by ivtroitskiy** [diadoc/diadocsdk-1c-docs#333]
Есть простой код 1с
```
&НаСервере
Функция testDiadocНаСервере()
	
	Diadoc = Новый ComОбъект("Diadoc.DiadocClient");
	Diadoc.ApiClientId = "API-11111";
	Diadoc.ServerUrl   = "https://diadoc-api.kontur.ru:443";
			
	Certificates = Diadoc.GetPersonalCertificates();
	
	return Certificates.Count();
	
КонецФункции

&НаКлиенте
Процедура testDiadoc(Команда)
	
	Count = testDiadocНаСервере();

КонецПроцедуры

```
Выдает ошибку "Неизвестная ошибка" на строке с вызовом метода Diadoc.GetPersonalCertificates()

Версия Windows 7 64 разрядная
Версия компоненты: DiadocCom_5_28_1_479_x64.dll
Диагностику на сайте проходил, всё хорошо

С компонентой версии "DiadocCom_5_25_2_407_x64.dll" метод отрабатывает, но выдает ошибку уже на другом методе.

Подскажите в чем может быть проблема?

**Comment by GilimkhanovDenis** [comment]
Техподдержка сообщила, в обращении 22359185 установка компоненты в профиль пользователя решила проблему.
Подтвердите, пожалуйста

**Comment by ivtroitskiy** [comment]
Подтверждаю, проблема разрешилась!
