### ISSUE TITLE
CreateReplySendTask2

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#334]
Добрый день.
Создаю CreateReplySendTask2 для пакета документов на подписание.
1) Как программно получить, DynamicContent или BaseContent содержится в свойстве Content объекта PackageContentItem?
2)  В случае DynamicContent, как получить тип контента (UniversalTransferDocumentBuyerTitle, XmlAcceptanceCertificate552BuyerTitle и т.п.)? Только путем анализа type и version свойства Document объекта PackageContentItem?

**Comment by GilimkhanovDenis** [comment]
Вариант определения какой контент нужен для заполнения [примере](http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_reply_document.html)

Теоретически, можем добавить поле Type для DynamicContent'а. Но, поле Type будет на каждом уровне иерархии DynamicContent'а - объект рекурсивный. Насколько это будет удобно?

Есть запрос на смежную функциональность #339

**Comment by JohnSergeev** [comment]
Со своей стороны (автор #339) дополню - в любом случае поле Type, **даже если оно будет торчать везде и всюду**, нам, пользователям АПИ, **точно не помешает**. А вот помочь в некоторых ситуациях может ОЧЕНЬ сильно!

Поэтому, если бы было голосование ;-) , то я бы однозначно проголосовал бы за добавление поля Type во все объекты динамического контента. Хуже не будет, поверьте!

**Пожалуйста, добавьте поле Type!**

Спасибо.

**Comment by prog22** [comment]
Type было бы хорошо. Спасибо.

**Comment by azhipaigor** [comment]
В https://github.com/diadoc/diadocsdk-1c-docs/issues/349 решили, что будем делать reflector, как более универсальное решение. Через него можно будет получить ProgId COM-объекта, что по сути и есть Type.
