### ISSUE TITLE
Ошибка в получаемых адресных данных - неверная кодировка ЧАСТИ данных

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#335]
Добрый день.

Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ **5.28.2.481**.

На текущий момент мы пока что еще используем для получения данных принимаемых документов, объявленный в этой версии АПИ устаревшим метод **GetContent()**. В получаемых данных документа есть информация о покупателе и продавце. В числе прочего там есть их адресные данные в объектах типа **AddressInfo**. 

А у объекта **AddressInfo** есть метод **GetAddressString()**:
 
![image](https://user-images.githubusercontent.com/33707226/63149294-04f6b980-c047-11e9-846c-67c239bcdd8d.png)

В текущей версии компоненты данный метод явно работает с ошибкой! Очень часто он в формируемой строке адреса, то название страны, то название региона, то название города указывает **в какой-то нестандартной кодировке** и в итоге вместо читаемого текста получаются «кракозябры». Причем в этой версии это происходит практически всегда!

Примеры (данные из отладчика 1С):

№1:
 ![image](https://user-images.githubusercontent.com/33707226/63149328-1d66d400-c047-11e9-9fc0-48943b372e16.png)

На печатной форме при этом все хорошо:
 ![image](https://user-images.githubusercontent.com/33707226/63149331-248de200-c047-11e9-8515-351464387211.png)

Проблема только в данные, возвращаемых АПИ.
 
№2:
 ![image](https://user-images.githubusercontent.com/33707226/63149362-412a1a00-c047-11e9-9e58-c573df57ce53.png)

№3:
![image](https://user-images.githubusercontent.com/33707226/63149373-48e9be80-c047-11e9-9b67-d3ff463d18eb.png)

И, опять же, на печатной форме все нормально:
 ![image](https://user-images.githubusercontent.com/33707226/63149387-4f783600-c047-11e9-9e06-7c932b6a3820.png)

**В предыдущей используемой нами версии компоненты 5.26.6.440 такой проблемы ни разу не было!**

Очень хотелось бы, чтобы это поведение было исправлено.

Спасибо.

**Comment by IrinaShmonina** [comment]
Поправили в версии [5.28.3](http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_28_3.html#id1)

**Comment by JohnSergeev** [comment]
Проверено. Теперь работает нормально.

Спасибо.
