### ISSUE TITLE
Ошибка в формировании данных подписанта документов при работе с CreateReplySendTask2

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#336]
Добрый день.

Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ **5.28.2.481**.

При изучении работы с «новым» объектом **CreateReplySendTask2** в плане выполнения операции подписания входящих документов, мы столкнулись со следующей проблемой – при заполнении данных подписанта так же, как ранее мы это делали, используя «старый» объект **CreateReplySendTask**, у нас не происходило подписание документа, а выдавались ошибки о неверном заполнении данных подписанта.

Анализ возникшей проблемы и попытки заполнить данные подписанта так, чтобы ошибок не было и документ был бы подписан, привели к очень интересному результату! 

Посмотрим на то, что мы делали:

**Заполнение данных подписанта:**
![image](https://user-images.githubusercontent.com/33707226/63150100-4b4d1800-c049-11e9-81d4-b94d5613665d.png)

**Возникающая ошибка:**
_Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 9, Position: 115, /UniversalTransferDocumentBuyerTitle[1]/Signers[1]/SignerDetails[1]/@SignerType: The 'SignerType' attribute is invalid - **The value 'LegalEntity' is invalid according to its datatype 'String' - The Enumeration constraint failed**.
Line: 9, Positi_

**Дополнительно:**
Хотелось бы обратить ваше внимание на то, что текст ошибки, возвращаемый вашей системой, по какой-то причине не полон и явно обрезан где-то посредине («…_Line: 9, Positi_» – и что дальше?)! 

Такие, не до конца сформированные тексты ошибок, постоянно возникают при работе с данной версией компоненты!

Вопрос – **Почему значение «LegalEntity» считается за ошибочное?!** Ведь в документации ясно указано:
 
![image](https://user-images.githubusercontent.com/33707226/63150224-949d6780-c049-11e9-8d74-ffb6f7a7f78e.png)

Сперва мы предположили, что у нас все-таки как-то неверно задано сочетание параметров SignerType, Powers и Status в данных подписанта. Но дальнейшая проверка показала, что:

1.	Старый объект **CreateReplySendTask** с точно таким же заполнением данных подписанта прекрасно подписывает документ без каких-либо ошибок.

2.	Какие бы сочетания возможных значений при заполнении вышеуказанных реквизитов SignerType, Powers и Status мы не делали (а мы просто тупо перепробовали все варианты!) – все равно при попытке подписания документа с использованием объекта **CreateReplySendTask2** возникает ошибка вышеуказанного вида, поясняющая, что **любое возможное значение SignerType (из указанных в документации!) является ошибочным!**

В этот момент мы решили, что в компоненте просто какая-то ошибка в подписании документов через использование объекта **CreateReplySendTask2**. И решили написать вам письмо именно об этом. Но случайно вспомнили, что у вас есть сайт с документацией к вашему АПИ не только для 1С. И нашли вот эту страницу:

http://api-docs.diadoc.ru/ru/latest/proto/utd/ExtendedSigner.html

На которой увидели следующее:
![image](https://user-images.githubusercontent.com/33707226/63150400-07a6de00-c04a-11e9-90fd-9cb6b40e80ed.png)
 
И у нас появилась **очень странная мысль** – а вдруг у вас ошиблись с обработкой данных подписанта при работе с **CreateReplySendTask2**, и поэтому не срабатывают, как это работало раньше, указанные в документации к АПИ для 1С **строковые** значения для SignerType, Powers и Status, но при этом **возьмут и сработают _числовые_ значения с вышеуказанного скрина?!**

Мы попробовали для SignerType установить значение «1» (строкой, т.к. у вас в объекте тип этого поля - строка). И вот что получилось:

**Заполнение данных подписанта:**
![image](https://user-images.githubusercontent.com/33707226/63150483-39b84000-c04a-11e9-949c-a33748a3b1eb.png)

**Возникающая ошибка:**

_Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 9, Position: 200, /UniversalTransferDocumentBuyerTitle[1]/Signers[1]/SignerDetails[1]/@SignerStatus: The 'SignerStatus' attribute is invalid - **The value 'SellerEmployee' is invalid according to its datatype 'Integer' - The string 'SellerEmployee' is not a valid**_

**И оказалось, что наше, казалось бы, совершенно странное предположение было верным! Теперь ошибка была найдена уже в другом поле – Status! А с полем SignerType проблем обнаружено не было.**

При этом хотелось бы дополнительно обратить ваше внимание на два обстоятельства:
1.	Во второй ошибке по полю статус почему-то написано про тип Integer, хотя поле имеет тип «строка». И в первой показанной ошибке по SignerType как раз написано – String. Откуда здесь вообще взялся Integer?

2.	И в первой, и во второй ошибках при указании проблемы используются названия полей не из документации к компоненте для 1С, а из документации со страницы http://api-docs.diadoc.ru/ru/latest/proto/utd/ExtendedSigner.html, что немного странно.

Мы поняли, что случайно оказались на правильном пути и попробовали подписать документ, указав для всех полей SignerType, Powers и Status строковые значения чисел со значениями со скрина с enum’ами со страницы http://api-docs.diadoc.ru/ru/latest/proto/utd/ExtendedSigner.html.

**Заполнение данных подписанта:**
![image](https://user-images.githubusercontent.com/33707226/63150561-72581980-c04a-11e9-8481-c70c23508460.png)

**При попытке подписания документа с использованием объекта _CreateReplySendTask2_ и вышеуказанным заполнением данных подписанта, документ подписывается без ошибок!**

Если после этого посмотреть, что же оказалось в данных подписанта покупателя, то можно увидеть следующее:

При получении данных контента покупателя «старым» способом:
![image](https://user-images.githubusercontent.com/33707226/63150592-8ac83400-c04a-11e9-883f-9d4a363e87f1.png)
 
Т.е. это именно указанные в документации для 1С значения полей, и они полностью соответствуют элементам enum’ов со страницы http://api-docs.diadoc.ru/ru/latest/proto/utd/ExtendedSigner.html!

При получении данных контента покупателя «новым» способом:
![image](https://user-images.githubusercontent.com/33707226/63150610-94ea3280-c04a-11e9-8a05-3fefdff4cde8.png)
 
А вот при «новом» получении данных происходит очень странная штука – **возвращаются именно числа в строковом представлении!** Что, во-первых, очень странно, а, во-вторых, абсолютно не информативно. Особенно учитывая, что в документации к компоненте для 1С никакого упоминания числовых значений для значений полей SignerType, Powers и Status вообще нет!

В итоге получается следующее:
1.	У вас явно присутствует какая-то неоднозначность в данных, возвращаемых в старой и новой версиях контентов. По идее – это ошибка и такого быть не должно.

2.	У вас явно есть либо ошибка при передаче и обработке значений полей данных подписанта при работе с **CreateReplySendTask2**, либо ошибка в документации, объясняющей заполнение данных подписанта. Скорее ошибка все-таки в передаче и обработке значений полей данных подписанта, т.к. документация как минимум соответствует тому, что передается с использованием «старого» объекта **CreateReplySendTask** и принимается в «старом» контенте, получаемом через **GetBuyerContent()**.

Очень хотелось бы, чтобы это было исправлено и как-то приведено в соответствие с документацией и, как бы сказать – к одному знаменателю, т.е. чтобы не было различий в данных возвращаемых в «старых» и «новых» контентах, **т.к. это ну очень странно!** 

Спасибо.

**Comment by prog22** [comment]
Подскажите, пожалуйста, как добавить подписанта. Ранее в CreateReplySendTask работал AddSigner(). В CreateReplySendTask2 не работает.

**Comment by JohnSergeev** [comment]
Из справки сам ничего не понял. Методом тупого перебора из "чего-то похожего на справку", совершенно случайно нарвался на правильный вариант. На примере УПД:

ДанныеПодписанта = XXX.Content.UniversalTransferDocumentBuyerTitle..Signers.AddItems();

Ну а дальше уже заполняем поля. Только там ошибка в представлении данных, о которой я писал выше!

**Comment by IrinaShmonina** [comment]
@JohnSergeev , здравствуйте
В CreateReplySendTask2 нужно опираться на xsd схему. В XSD схеме описано, что значение SignarType принимает только цифровые значения 1,2,3:
Описание из xsd:

```
<xs:attribute name="SignerType" use="required">
      <xs:annotation>
        <xs:documentation>
          1 – Представитель юридического лица (ЮЛ)
          2 - Индивидуальный предприниматель (ИП)
          3 - Физическое лицо (ФЛ)
        </xs:documentation>
      </xs:annotation>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="1" />
          <xs:enumeration value="2" />
          <xs:enumeration value="3" />
        </xs:restriction>
      </xs:simpleType>
</xs:attribute>
```

**Comment by JohnSergeev** [comment]
Добрый день.

Вы, похоже, не очень внимательно прочитали мои выводы и вопросы к ним! Поэтому повторю еще раз. И постараюсь заострить внимание на ключевых моментах.

1. Берем "старый" **CreateReplySendTask** и заполнение данных подписанта в нем.

В документации написано, что для заполнения SignerType надо использовать СТРОКОВЫЕ значения:
![image](https://user-images.githubusercontent.com/33707226/63397428-de050280-c40d-11e9-9c5c-36ffbd454963.png)

т.е. вот надо прямо писать в коде 1С - **.SignerType = "LegalEntity";**

Такой вариант:
а) Работает
**б) Полностью соответствует документации**

Т.е. тут у нас всё хорошо!

2. Берем "новый" **CreateReplySendTask2** и заполнение данных подписанта в нем.

В документации СЕЙЧАС написано точно то же самое, что и для "старого" CreateReplySendTask - просто ссылки ведут туда же!

И получается, что документация говорит нам - делай так: **.SignerType = "LegalEntity";**

Такой вариант:
**а) !!! НЕ работает !!!**
**б) При этом ПОЛНОСТЬЮ соответствует документации**

Т.е. тут у нас всё НЕ хорошо - то, что прямо указано в документации, приводит к ошибке! 

Тогда мы берем и делаем так, как в документации НЕ НАПИСАНО: **.SignerType = "1";**
**(причем этот способ мы находим **наугад методом "тыка"**, т.к. в документации о нём нет ни слова!)**

Такой вариант:
а) Работает
**б) !!! НИКАК, НИ ЕДИНЫМ МОМЕНТОМ НЕ СООТВЕТСТВУЕТ ТЕКУЩЕЙ ДОКУМЕНТАЦИИ !!!**

**Всё вышеуказанное точно таким же образом касается и заполнения полей Powers и Status.**

Из этого следуют вроде бы совершенно очевидные выводы:

1. Сейчас есть очевидные расхождения между документацией и правилами заполнения данных подписанта при работе с **CreateReplySendTask2**.
2. Сейчас есть странное и непонятно зачем внесенное расхождение между тем, как надо заполнять данные подписанта при работе со "старой" **CreateReplySendTask** и при работе с "новой" **CreateReplySendTask2**.
3. Из данных документации на текущий момент совершенно невозможно понять как правильно заполнять данные подписанта при работе с **CreateReplySendTask2**! В плане работы с **CreateReplySendTask2** там сейчас указана АБСОЛЮТНО НЕВЕРНАЯ, НЕДОСТОВЕРНАЯ информация!

Поэтому:

а) Либо надо ПЕРЕПИСАТЬ документацию так, чтобы в ней было ПРАВИЛЬНО описано: _При работе с **CreateReplySendTask** надо заполнять в данных подписанта SignerType, Powers и Status такими-то СТРОКОВЫМИ значениями. А При работе с **CreateReplySendTask2** надо заполнять в данных подписанта SignerType, Powers и Status ДРУГИМИ СТРОКОВЫМИ значениями, представляющими из себя строковые представления чисел - "1", "2", "3". Что эти числа означают - смотрите в такой-то табличке._ И так далее.
б) Либо надо НЕ переписывать документацию, а **ПРИВЕСТИ РАБОТУ нового функционала в соответствие с ней!** Т.е. сделать так, чтобы и при работе с **CreateReplySendTask**, и при работе с **CreateReplySendTask2** данные подписанта заполнялись бы ОДИНАКОВО - **и именно так, как это описано в документации!**

Вот об этом речь - у вас явное расхождение в поведении компоненты и том, как вы это поведение описываете! И с этим надо что-то сделать - либо путем правки документации, либо путем приведения поведения компоненты к тому, что сейчас в документации написано.

Какой путь вы выберете - решать вам. Но как-то это расхождение точно надо устранить!

Я же со своей точки зрения **пользователя** вашей компоненты (т.е. с позиции того, _для кого вы её, собственно, и создаёте!_) полагаю, что более правильный вариант - когда при работе и со старыми объектами АПИ, и с новыми объектами АПИ ОДИНАКОВЫЕ поля данных подписанта и заполняются ОДИНАКОВО - это и в поддержке легче, и в понимании того, как работать с компонентой.

Надеюсь, теперь более понятна суть "претензии" к текущему положению дел.

Спасибо.

**Comment by volodkindv** [comment]
Добрый день.
Дело в том, что ReplySendTask и ReplySendTask2 - это совершенно разные объекты компоненты для 1С.

На примере УПД. Есть утвержденный государством формат документа, например в 155 приказе: https://www.diadoc.ru/docs/forms/upd/structure/1
В нем есть теги, которые называются так: Файл.Документ.СвСчФакт.НомерСЧФ, Файл.Документ.СвСчФакт.ДатаСЧФ, Файл.Документ.СвСчФакт.ТаблСчФакт и т.д. Это вместе с "путями" в xml-файле.
Заполнение такого xml-файла довольно трудоемко. Во-первых, очень много уровней вложенности, во-вторых, названия тегов не всегда очевидны (СвСчФакт). В-третьих, форматы часто обновляются, и порой эти изменения чисто косметические: 19 июля ФНС рекомендует в Файл.ВерсФорм писать "5.02" вместо "5.01".
Чтобы упростить подготовку xml-файла, в API Диадок в свое время ввели дополнительную абстракцию над форматом документа: [UniversalTransferDocumentSellerTitleInfo](http://api-docs.diadoc.ru/ru/latest/proto/utd/UniversalTransferDocumentSellerTitleInfo.html).
Она более "плоская", т.е. содержит меньше уровней вложенности, и заполнять ее проще. 
В компоненте 1С данная абстракция связана с объектом [UtdSellerContent](https://diadocsdk-1c.readthedocs.io/ru/latest/ComObjects/UtdSellerContent.html). Это "абстракция над абстракцией". Они не соответствуют друг другу один-в-один. Например, SignerType в компоненте представлен строкой, а в API - числом.

Поддерживать еще одну абстракцию в компоненте сложно и долго. Особенно на фоне того, что форматы документов в последние годы стали добавляться и меняться чаще.

Идея PackageSendTask2 заключается в том, чтобы убрать дополнительную абстракцию компоненты и работать именно с тем представлением документа, которым оперирует API Диадока. Это позволяет гораздо быстрее поддерживать новые требования законодательства.

Поэтому документация для объектов, рожденных из PackageSendTask и ReplySendTask, **не актуальна** для объектов, полученных из PackageSendTask2 и ReplySendTask2.
Документацией для этих объектов является **XSD-схема**. Ее можно получить через SaveUserDataXsd: https://diadocsdk-1c.readthedocs.io/ru/latest/ComObjects/DynamicContent.html.

Вот примеры XSD для титулов отправителя и получателя УПД: "UniversalTransferDocument", "СЧФДОП", "utd_05_02_01".

[UserData_utd_Buyer.xsd.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/3524722/UserData_utd_Buyer.xsd.txt)
[UserData_utd_Seller.xsd.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/3524724/UserData_utd_Seller.xsd.txt)

В них описано поле SignerPowers, вот какие ограничения для получателя:
```
  <xs:complexType name="ExtendedSignerDetails_BuyerTitle">
    <xs:complexContent mixed="false">
      <xs:extension base="ExtendedSignerDetails">
        <xs:attribute name="SignerPowers" use="required">
          <xs:annotation>
            <xs:documentation>ОблПолн - Область полномочий</xs:documentation>
            <xs:documentation>
							1 - лицо, совершившее сделку, операцию
							2 - лицо, совершившее сделку, операцию и ответственное за ее оформление
							3 - лицо, ответственное за оформление свершившегося события
						</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:enumeration value="1" />
              <xs:enumeration value="2" />
              <xs:enumeration value="3" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
```

Еще раз кратко:
1. Объекты ReplySendTask и ReplySendTask2 - разные. Документация для первого не подойдет ко второму.
2. Документацией для DynamicContent является XSD-схема, которую можно получить методом SaveUserDataXsd.

**Comment by JohnSergeev** [comment]
Ясно. Как раз и было непонятно - каким будет итоговое состояние изменений. Теперь ясно - ориентируемся на XSD, **старая** документация не соответствует **новым** объектам, на нее не обращаем внимание.

Подскажите, а мы правильно понимаем - "старые" Content и ReplySendTask полностью заменяются "новыми" DynamicContent и ReplySendTask2 и нужно переводить всю работу на использование только "новых" объектов? Есть ли какие-то конкретные сроки, когда "старые" объекты вообще перестанут работать?

Спасибо.

**Comment by volodkindv** [comment]
> "старые" Content и ReplySendTask полностью заменяются "новыми" DynamicContent и ReplySendTask2

Верно.
Удаление "старых" объектов: пока не планировали. Какое-то время точно будут работать.

Другое дело, что с 2020 года основным форматом передачи документов будет УПД 820, который в HTTPI API и в компоненте реализован только через DynamicContent. Поэтому работу со старыми форматами документов можно оставить на старых Content. Просто со следующего года они постепенно перестанут приходить.
