### ISSUE TITLE
Вопрос по новому поведению при заполнении AcceptanceDate 

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#337]
Добрый день.

Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ **5.28.2.481**.

При подписании документов УПД, Торг-12, Торг-12 (551 ФНС), Акт о выполнении работ (552 ФНС), УКД необходимо заполнить поле **AcceptanceDate** – дату принятия товаров (результатов выполненных работ) или имущественных прав (подтверждения факта оказания услуг).

Ранее при использовании **CreateReplySendTask** мы вносили в это поле нужную дату с учетом времени. В данных итоговой подписи дата оказывалась без учета времени. Подписание при этом проходило без ошибок – ну, т.е. время в заданной дате просто не учитывалось.

При использовании **CreateReplySendTask2**, если мы указываем дату со временем, то при попытке подписания происходит ошибка:

«_Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 2, Position: 127, /UniversalTransferDocumentBuyerTitle[1]/@AcceptanceDate: The 'AcceptanceDate' attribute is invalid - The value '15.08.2019 17:32:59' is invalid according to its datatype 'date' - The Pattern constraint failed.
Line: 9, Position: 115, /Universa_»

Если вносить дату в виде, например, «15.05.2019» без указания времени, то подписание документа проходит нормально.

**Вопрос:**
Правильно ли мы понимаем, что так и должно быть – эту дату нужно указывать без учета времен, и в новой версии вы просто ужесточили контроль за выполнением этого правила? Или же **время как-то можно и нужно указывать**, но надо задавать его в каком-то новом, особом формате? Если да, то в каком?

**Дополнительно:**
Хотелось бы обратить ваше внимание на то, что текст ошибки, возвращаемый вашей системой, по какой-то причине не полон и явно обрезан где-то посредине («_…Line: 9, Position: 115, /Universa_» – и что дальше?)! 

**Такие, не до конца сформированные тексты ошибок, постоянно возникают при работе с данной версией компоненты!**

**Comment by GilimkhanovDenis** [comment]
Добрый день
Динамический контент заполняется в соответствие с xsd схемой. тип date описан в ней:
```
  <xs:simpleType name="date">
    <xs:annotation>
      <xs:documentation>Дата в формате ДД.ММ.ГГГГ (01.01.1800 - 31.12.2099)</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:length value="10" />
      <xs:pattern value="(((0[1-9]{1}|[1-2]{1}[0-9]{1})\.(0[1-9]{1}|1[0-2]{1}))|((30)\.(01|0[3-9]{1}|1[0-2]{1}))|((31)\.(01|03|05|07|08|10|12)))\.(18[0-9]{2}|19[0-9]{2}|20[0-9]{2})" />
    </xs:restriction>
  </xs:simpleType> 
```

**Comment by JohnSergeev** [comment]
Ясно. Просто хотелось убедится. Вопрос закрыт.
Спасибо.
