### ISSUE TITLE
Вопрос по правильности заполнения данных подписанта при подписании входящих УПД

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#338]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ **5.28.2.481**.

При переходе к использованию текущей версии компоненты мы обратили внимание на то, что был расширен перечень возможных значений для поля **Status** при формировании данных подписанта документа. Появилось два новых пункта: 

![image](https://user-images.githubusercontent.com/33707226/63235085-82a30b00-c27b-11e9-9a0f-72b047227242.png)

**Вопросы:**
По данной вами ранее рекомендации, сейчас при подписании входящих документов от поставщиков мы устанавливаем **Status = SellerEmployee**. И документы нормально без проблем подписываются. Хотя это и кажется нам немного странным – мы же вроде как покупатели товара у нашего продавца – у поставщика. Мы принимаем от него товар, а не продаем его ему.

Как правильно заполнять поле **Status** при приеме и подписании входящих документов – разве не будет правильным в качестве статуса указывать значение **BuyerEmployee**?

Если действительно надо указывать **Status = BuyerEmployee**, то не является ли проблемой то, что мы сейчас при подписании входящих документов от поставщиков указываем **Status = SellerEmployee**? Чем это грозит? И почему тогда вообще ваша система позволяет выполнять подписание входящих документов с таким статусом?

Спасибо.

**Comment by IrinaShmonina** [comment]
@JohnSergeev , здравствуйте
BuyerEmployee = 5 и InformationCreatorBuyerEmployee = 6 предназначены только для документов [в формате 820 приказа](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=254666).

**Comment by JohnSergeev** [comment]
Понятно. Спасибо. 

Небольшое уточнение:
Когда нам будут приходить от поставщиков входящие УПД 820-го приказа - при их подписании нужно будет указывать статус подписанта = BuyerEmployee? Или, как и ранее = SellerEmployee, а BuyerEmployee нужен только для каких-то специфических случаев?

Спасибо.

**Comment by IrinaShmonina** [comment]
@JohnSergeev, если вам пришел документ в 820 формате, то при их подписании нужно будет указывать BuyerEmployee

**Comment by JohnSergeev** [comment]
Ясно. Спасибо.
Можно закрывать.
