### ISSUE TITLE
Вопросы о типе данных динамического контента - как понять, что внутри?

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#339]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ **5.28.2.481**.

При работе с данными, возвращаемыми в динамических контентах, возник вопрос:
**Как вообще можно разобраться в том, что получено в контенте?**

Рассмотрим пример:

Пробуем подписать УПД. Получаем данные подписанта для заполнения:
 ![image](https://user-images.githubusercontent.com/33707226/63235262-1543aa00-c27c-11e9-940d-435f1410bfe1.png)

Пробуем подписать Акт о выполнении работ. Получаем данные подписанта для заполнения:
![image](https://user-images.githubusercontent.com/33707226/63235275-1d9be500-c27c-11e9-8527-86bbbcf08ab1.png)

Видно, что для этих документов данные подписанта (состав полей) различны.

Понятно, что когда выражение получения написано, как на вышеприведенных скринах, то из него самого понятно какие именно это данные. Но мы же можем поместить этот объект подписанта в какую-то переменную и передать его, например, в какую-то процедуру по заполнению его состава. 
 
Тогда в этой процедуре данный объект будет выглядеть так:

Для подписанта УПД:
![image](https://user-images.githubusercontent.com/33707226/63235293-2c829780-c27c-11e9-95c1-73efd1d5212a.png)
 
Для подписанта Акта:
![image](https://user-images.githubusercontent.com/33707226/63235296-32787880-c27c-11e9-9806-2f436ccef0db.png)
 
**Вопросы:**
А каким-то образом из такого объекта **самого по себе** как-то можно понять – что это вообще такое? Какие поля есть у объекта? Какого он типа?

Может быть у объекта **DynamicContent** есть какие-то не указанные в документации методы, с помощью которых можно перебрать его поля? Узнать какой у объекта тип данных? Проверить наличие того или иного поля в объекте?

**Если из самого объекта никак нельзя узнать какого он типа и какие поля в нем есть, то может быть стоит добавить в компоненту такую возможность?**

Плюс в контентах документов, получаемых «старыми» методами, было отдельное поле типа **Type**, по которому можно было понять с чем ты работаешь. Но в динамических контентах такого поля нет!

**Может стоит добавить поле типа данных для всех динамических контентов?**

Спасибо.

**Comment by volodkindv** [comment]
Добрый день!

Технически возможны 2 варианта:
1. Сделать метод вроде DynamicContent.GetTypeName(). Здесь можно возвращать то, что указано в XSD типа документа. Т.е. такие названия: "string1000z", "ExtendedSignerDetails_SellerTitle", "ExtendedSignerDetails_BuyerTitle", "ExtendedSignerDetails_BuyerTitle820". Некоторые типы не имеют своего имени.
2. Сделать метод вроде DynamicContent.GetAttributes(), который будет возвращать список атрибутов в данном объекте. Тот список, который сейчас видно в конфигураторе при отладке (на скриншотах из тикета).

Первый вариант кажется бессмысленным: отличить 2 объекта разного типа и без собственных имен будет невозможно.
Во втором варианте непонятно, как именно вы хотите использовать информацию о списке атрибутов. Можете привести пример псевдокодом?

**Comment by JohnSergeev** [comment]
Добрый день.

Было бы **очень здорово,** если бы появился ВТОРОЙ вариант, возвращающий **список строковых наименований полей в контенте**.

Возвращать, по идее должен только по текущему уровню контента. Например, если смотреть на скрины выше, то это выглядело бы так:

Вызываем что-то типа:
Стр = текSigner.GetPropertiesNames();

Получаем:
Стр = "SignerDetails, SignerReference"

Вызываем:
Стр = текSigner.SignerReference.GetPropertiesNames();

Получаем:
Стр = "BoxId, CertificateBytes, CertificateThumbPrint"

И все остальное по такому же принципу.

Вызываем:
Стр = текSigner.SignerReference.BoxId.GetPropertiesNames();

Получаем:
Стр = "";

По последнему случаю - надо либо вот так возвращать без ошибки пустой список, либо добавить какой-то отдельный метод, возвращающий Истина, если у проверяемого объекта есть внутри какие-то поля и возвращающий Ложь, если проверяемый объект имеет "простой" тип и не содержит внутри каких-либо полей - что-то типа .HasProperties().

Использовать это было бы очень удобно в плане контроля потока выполнения кода на предмет того, как бы случайно не обратиться к полю, которого нет и не улететь в исключение.

Т.е. при наличии такой функции, возвращающей список имен свойств контента нам стало бы возможным при передаче объектов в какие-то процедуры и функции по их заполнению/обработке не тащить с ними по всем уровням кода какую-то информацию о типе данных. Мы просто на любом уровне работы с объектом могли бы проверить по составу его полей, с чем мы имеем дело.

Например, в случае данных подписанта, приведенных на скрине это выглядело бы примерно так:

СтрИменаПолей = текSigner.SignerDetails.GetPropertiesNames();

Если СтрНайти(СтрИменаПолей, "SignerType") Тогда
     текSigner.SignerDetails.SignerType = <какие-то данные>;
КонецЕсли;

Код такого типа позволил бы по месту определять что за данные к нам "приехали" без необходимости везде вместе с данными постоянно таскать их типы. Мы бы могли лучше понимать с чем мы работаем по понятному составу полей объекта. Также это позволило бы сильно снизить шансы на вылет в исключение. Т.к. если вдруг у объекта поля нет, то мы его и не будем пытаться заполнить/прочитать.

Также это сделало бы возможным выполнять обобщенное заполнение/чтение данных объектов АПИ по настраиваемым на лету спискам свойств. Как-то типа:

СтрИменаПолей = текОбъектАПИ.GetPropertiesNames();

Для Каждого ИмяПоля Из СтрРазделить(СтрИменаПолей, ", ") Цикл
   текОбъектАПИ[ИмяПоля] = ДанныеДляЗаполнения[СоответствиеИменПолейАПИНашимИменамПолей[ИмяПоля]];
КонецЦикла;

**Добавление такого функционала добавило бы нам, пользователям вашего АПИ, массу ОЧЕНЬ удобных и полезных возможностей!**

Я  о добавлении подобного функционала уже несколько раз просил более года тому назад. Тогда моя просьба осталась без ответа. **Было бы ОЧЕНЬ здорово, если бы вы добавили такую возможность!** Она хороша и сама по себе, даже применительно к объектам обычных контентов. А уж при работе с данными динамических контентов такая возможность была бы ИСКЛЮЧИТЕЛЬНО ПОЛЕЗНА!!!

Спасибо.

**Comment by volodkindv** [comment]
Решение будет примерно такое.

1. Делаем у объектов DynamicContent метод вроде Fields() или GetPropertiesNames(). Возвращает коллекцию IValueCollection, а не строку.
2. Делаем метод вроде HasProperty("имя_свойства").
3. Прокачиваем IValueCollection. Чтобы можно было смотреть в отладчике 1С, перебирать через ForEach, может быть выгружать в Массив (смотря что получится).

Когда будет готово, напишем в описании релиза.

**Comment by IrinaShmonina** [comment]
Выпустили в релизе [5.28.3](http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_28_3.html#id1)

**Comment by JohnSergeev** [comment]
Добрый день.

Проверил функционал работы со свойствами в новом релизе. Получилось очень хорошо. Всё работает. Огромное спасибо!

Единственная просьба - рассмотреть один ранее запрошенный пункт, который вы оставили без реализации.

Смотрите.
Мы получаем какое-то свойство, про которое ничего не знаем, просто перебирая поля, список которых получили через **GetPropertiesNames()** (допустим, у нас какой-то универсальный обработчик составов документов).

И у нас возникает вопрос - а у данного поля (например "Seller" или "Function") есть какие-то свои вложенные поля?! Т.е. это "простой" или "сложный составной" объект?

**Вот ответа на этот вопрос в новом функционале нет!**

Если вызвать, например, так:
![image](https://user-images.githubusercontent.com/33707226/63833221-da492100-c9b5-11e9-8a8e-6a8fc9cd8234.png)

То будет получен список свойств и будет понятно - ага, это точно "сложный" объект, имеющий в своем составе другие поля. Все хорошо.

Но, если сделать так:
![image](https://user-images.githubusercontent.com/33707226/63833283-ff3d9400-c9b5-11e9-8f9e-7066719caafc.png)

То мы попадаем в исключение!

**А было бы здорово без контроля исключений понять, что это "простое" поле, не имеющее в составе других полей!**

Поэтому ОЧЕНЬ БОЛЬШАЯ ПРОСЬБА -  сделать одно из двух добавлений к реализованному функционалу:

_Вариант №1._
Чтобы для "простых" полей типа "Function" вызов **GetPropertiesNames()** не вылетал бы в исключение, а просто возвращал бы пустую коллекцию!

_Вариант №2._ 
(Более предпочтительный)

Добавить еще одну функцию "**HasProperties()**" без параметров. Чтобы она возвращала Истину для поля, если у него есть вложенные поля, список которых можно получить используя GetPropertiesNames(). И возвращала бы Ложь, если поле "простое" и у него вложенных полей нет. Т.е. работала бы по такому принципу:

Если текОбъект.**HasProperties()** Тогда
     СписокПолейОбъекта = текОбъект.**GetPropertiesNames()**;
     <и дальше уже что-то делаем с полями объекта>
КонецЕсли

Т.е. очень полезен был бы не только вариант проверки наличия конкретного свойства у объекта:
**_Объект.HasProperty("PropertyName")_**

но и вариант проверки того, что у объекта вообще есть какие-то свойства в принципе:
**_Объект.HasProperties()_**

Подобная доработка позволила бы организовать полноценную работу с объектами любых составов, не прибегая к контролю исключений, что в 1С обходиться очень дорого. 

Например, используя уже созданный функционал с вышеуказанной добавкой, можно было бы написать универсальный рекурсивный разбор любого объекта динамического контента.

Сейчас его тоже можно будет сделать (что уже очень хорошо!), но он будет "некрасивым" и более медленным, чем мог бы быть, т.к. для понимания того, можно ли "проваливаться" в содержимое объектов, пришлось бы постоянно использовать исключения.

Спасибо.

**Comment by volodkindv** [comment]
Воспользуйтесь проверкой на ТипЗнч(). Следующие 2 утверждения будут истинными:

ТипЗнч(DynamicContent.Function) = Тип("Строка")

ТипЗнч(DynamicContent.Seller) = Тип("COMОбъект")

К Строке невозможно приделать метод HasProperties(), т.к. она не является COMОбъектом.

**Comment by JohnSergeev** [comment]
А. т.е. все объекты, которые сами еще являются динамическими контентами, а не простыми типами 1С - это объекты ComОбъект и они в любом случае всегда содержат в себе какие-то поля? 

И поэтому GetPropertiesNames() для них никогда не уйдет в исключение, а вернет список этих полей? 

Если это так, то тогда да, действительно, дополнительный метод не нужен.

Спасибо.

**Comment by volodkindv** [comment]
В общем виде - да.
Попробуйте еще работу с коллекциями. [Коллекция](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Collection.html) и единичный элемент [DynamicContent](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html) - это объекты разных типов.

**Comment by JohnSergeev** [comment]
А, кстати, насчет коллекций. У вас написано:
![image](https://user-images.githubusercontent.com/33707226/63837842-90fdcf00-c9bf-11e9-8fc4-a7bbe5b20feb.png)

Вот - "по объекту Collection можно итерироваться" - это вообще о чем речь? Более это нигде не объясняется. Это же не о GetItem(), а о чем-то другом, да? А о чем именно? Можно пример?

Спасибо.

**Comment by volodkindv** [comment]
Старый вариант обхода коллекции:
```
Для Сч = 0 По Collection.Count() - 1 Цикл
 Item = Collection.GetItem(Сч);
 Item.DoSomething();
КонецЦикла;
```

Теперь можно делать так:

```
Для Каждого Item Из Collection Цикл
 Item.DoSomething();
КонецЦикла;
```

И содержимое коллекций теперь видно в отладчике:

![image](https://user-images.githubusercontent.com/12305552/63838624-2173e980-c997-11e9-9feb-d71cd28b6737.png)

**Comment by JohnSergeev** [comment]
Ясно. Супер! Спасибо.

Может быть стоит пример с "Для каждого ... " добавить в документацию по **Collection**?

А то интуитивно предполагаешь, что "_Наверное они имели ввиду Для Каждого. Но фиг знает. Может что-то еще. Надо будет потыкаться, посмотреть_". А так сразу будет понятно.

**Еще раз огромное спасибо за новый функционал!**

**Comment by volodkindv** [comment]
У нас сейчас большая загрузка у сотрудников. Будем благодарны, если сделаете pull request в [документацию](https://github.com/diadoc/diadocsdk-1c-docs/blob/master/docs/source/ComObjects/Collection.rst).
