### ISSUE TITLE
Ошибка при выполнении запроса на отказ от партнерства

### ISSUE THREAD

**Issue by maxstarkov** [diadoc/diadocsdk-1c-docs#34]
Использую компоненту для работы на сервере (COM-компонента для 64х).
При попытке выполнить запрос на отказ от партнерства:

```
ТекущийКонтрагент =ТекущаяОрганизация.GetCounteragentById(СокрЛП(ИдентификаторКонтрагента));
ТекущийКонтрагент.BreakWithCounteragent("Отказываем в партнерстве.");
```
Получаю исключение:

`Произошла исключительная ситуация (CounteragentBox.AcquireCounteragent): LIBHTTP[0x00000015] can not parse uri`

При этом, объект контрагента получается без ошибок и, например, запросы на установку партнерства происходят успешно:

`ТекущийКонтрагент.AcquireCounteragent("Приглашем к партнерству.");`

Запрос выполняется.

**Comment by proger1c** [comment]
Подскажите:
1. Какой версией компоненты пользуетесь?
2. Что возвращает метод GetStatus() непосредственно перед использованием метода BreakWithCounteragent()?

**Comment by maxstarkov** [comment]
Версия компоненты 5.8.0.138
Метод GetStatus() для контрагента возвращает: IsMyCounteragent

**Comment by maxstarkov** [comment]
Версия компоненты: 5.8.0.138
Метод GetStatus() возвращает: IsMyCounteragent

**Comment by proger1c** [comment]
Поведение странное. Запросим комментарий от разработчика компоненты.

**Comment by proger1c** [comment]
На сайт выложена новая компонента 5.9.0.154. Попробуйте.

**Comment by maxstarkov** [comment]
В новой версии компоненты ошибок нет. Все работает.
