### ISSUE TITLE
Вопросы о содержимом динамического контента документов

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#340]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ **5.28.2.481**.

Как вообще работать с данными динамических контентов? 
Как понять какие поля будут возвращены в динамических контентах документов?
Как понять ЧТО за информация содержится в этих полях?

В документации сказано:
 ![image](https://user-images.githubusercontent.com/33707226/63235764-48873880-c27e-11e9-8252-f38788a9bcb3.png)

Смотрим описание этого метода:
 ![image](https://user-images.githubusercontent.com/33707226/63235795-63f24380-c27e-11e9-955b-db668efbbcda.png)

**Это просто кладезь вопросов и непонимания!**

**1.**
Почему только на диск? Почему нет версии для выгрузки, например, в строку?

Это же функционал для 1С. С очень большой долей вероятности, прочитанные данные будут записываться куда-то в базу 1С. Зачем промежуточный объект в виде файла? Это же совершенно лишняя сущность!

**2.**
!!! ПАРАМЕТРЫ !!!

**_TitleName_**	**более-менее понятно.** 
Хотя, похоже опечатка и далее приведена таблица для «DocumentType» – вот похоже, это как раз и есть типы документа. Или все-таки это что-то иное?

**_Function_**	**совершенно непонятно!** 
Что это? Для УПД, например, что туда подавать – «СЧФДОП»? Или «InvoiceAndBasic»? А что подавать сюда для неформализованного документа, Акта, Торг-12 и т.п. – ну всего того, у чего вроде как вообще нет такого реквизита как «Функция»? Хотя бы пример какой или описание посмотреть!

**_Version_**	**совершенно непонятно!**
Что должно быть в этой строке для УПД? Для неформализованного документа? Для Торг-12? И так далее. Что это за версия такая? Откуда ее брать?!

**3.**
А почему она так странно работает? Если задать какие попало параметры, то вместо генерации понятной ошибки, процедура молча выполняется и на диск по указанному пути записывается **файл с нулевой длиной!** Так точно должно быть?!

**4.**
Немного смущает ее вызов – из объекта Organization. Получается, что для разных организаций вызов метода с одними и теми же параметрами может вернуть разные данные – у этой организации так, а у другой – эдак? Или от организации содержимое документа не зависит?

**5.**
Согласно справки эта функция возвращает описание контента **документов**. Хорошо. А как быть с остальными динамическими контентами, например, теми, с которыми работает «новый» объект **CreateReplySendTask2**? Как и откуда можно узнать их динамическое содержимое?

**6.**
**А ЧТО, собственно, возвращает данная функция?**

Мы думали, что она возвращает XSD схему документа. Которую затем можно обойти и рекурсивно собрать все поля документа. 

Но такое ощущение, что она возвращает какую-то специфическую версию этой схемы. **Да еще и в не читаемом 1С формате!** (хотя компонента предназначена для работы с 1С).

Методом «научного тыка», подставляя параметры наугад, мы по следующему вызову:

_Документ.Organization.SaveUserDataXSD("UniversalTransferDocument", "СЧФДОП", "utd_05_01_05", "Seller", "C:\temp\1.xsd")_

Получили на выходе для документа УПД какой-то непустой XSD файл.

Судя по его содержимому – это какая-то XSD схема.

Но, например, 1С ее в XDTO-пакет импортировать не может – выдает ошибку и ничего в итоге не импортирует:
![image](https://user-images.githubusercontent.com/33707226/63235979-54272f00-c27f-11e9-8a5e-392804597350.png)
![image](https://user-images.githubusercontent.com/33707226/63235981-57221f80-c27f-11e9-834c-760b0f70e092.png)

Не хватает данных в схеме. 
 
Если вручную добавить данные targetNameSpace так:

БЫЛО:
![image](https://user-images.githubusercontent.com/33707226/63235989-6012f100-c27f-11e9-8d7e-8aaaaa124b80.png)

СТАЛО:
![image](https://user-images.githubusercontent.com/33707226/63235994-65703b80-c27f-11e9-8074-74e9e51bfa1c.png)

Тогда схема читается в 1С. Но она какая-то странная. 
**По типам реквизитов документов не получается обойти иерархию свойств!**
![image](https://user-images.githubusercontent.com/33707226/63236014-715bfd80-c27f-11e9-8f3c-81806319873f.png)
 
Видно, что часть свойств (например, **Table**, **Seller**, **TransferInfo**) нельзя обойти по иерархии и понять, что в них лежит и какого типа, **т.к. для них указан тип _anyType_**:
![image](https://user-images.githubusercontent.com/33707226/63236041-89cc1800-c27f-11e9-88c5-633a3a22bd4f.png)

**Т.е. из схемы нельзя понять – а что за данные и какого типа лежат в полях Table, Seller, TransferInfo  и т.д.**

Т.е. по-сути по данным схемы разобрать документ стандартным обходом иерархии полей схемы нельзя.

Поэтому у нас возникли вопросы:

**1.**
А это правильная схема? Может быть мы неверно задали параметры, и она просто выгрузилась неверно?

**2.**
Почему в схеме не формируются данные по targetNamespace – это опять же компонента для 1С, было бы логично, если бы выгружаемые данные были бы совместимы с 1С…

**3.**
Если она все-таки верная, то как с ней работать, если по схеме документов нельзя толком пройти по иерархии свойств и полностью разобрать документ?

**КАК работать с этой схемой для обходя полей документа?**

Допустим даже мы как-то разберемся с вашей помощью с работой со схемой и сможем читать данные из полей дин. контента. 

**Но ЧТО лежит в этих полях? Суть этих данных? Как этим пользоваться?**

Ранее для обычного контента для каждого типа документов в документации было полное описание того, как называется то или иное поле и, главное, **ЧТО за данные в нем лежат.**

**А сейчас в документации ничего не сказано о СУТИ значений в полях доп. контента!** 

Пример:
 ![image](https://user-images.githubusercontent.com/33707226/63236118-dca5cf80-c27f-11e9-8004-c69134a092d8.png)

Выделенные поля в динамическом контенте УПД – что за данные в них?! Что в них содержится? Что это содержимое означает? 

**В документации теперь нет ни слова о этих полях!** 

Пример:
![image](https://user-images.githubusercontent.com/33707226/63236134-e92a2800-c27f-11e9-97d2-99227cc9ac68.png)

Как и откуда узнать о том, что за данные лежат в **FactorInfo**? Как понимать, ЧТО в эти поля напихали и надо ли нам оно вообще?!

**Откуда мы можем узнать про поля динамических контентов, если они никак не описаны в документации?!**

**Может быть стоит добавить информацию обо всех полях в новых форматах документов в документацию?!**

Спасибо

**Comment by IrinaShmonina** [comment]
@JohnSergeev , здравствуйте.

> 1. Почему только на диск? Почему нет версии для выгрузки, например, в строку?

Можем добавить возврат в строку. Какая строка должна быть: просто контент XSD схемы записанный в строку или Base64 строку сформировать?

> 2. Параметры

Значения этой тройки можно получить методом [Organization.GetDocumentTypes](https://diadocsdk-1c.readthedocs.io/ru/latest/ComObjects/Organization.html#Organization.GetDocumentTypes)

> 3. Вместо генерации понятной ошибки, процедура молча выполняется и на диск по указанному пути записывается файл с нулевой длиной

Исправим в следующем релизе компоненты. Будет возвращаться ошибка с текстом "Неверный тип документа".

> 4. Получается, что для разных организаций вызов метода с одними и теми же параметрами может вернуть разные данные

У разных организаций отличается набор доступных XSD схем и теоретически может отличаться и содержимое.

> 5. Согласно справки эта функция возвращает описание контента документов. Хорошо. А как быть с остальными динамическими контентами, например, теми, с которыми работает «новый» объект CreateReplySendTask2?

Можете пояснить, что значит "остальные динамические контенты". Можете привести примеры?

> 6. А что, собственно, возвращает данная функция?

Возвращается XSD схема. Мы ее никак не модифицируем.

> 7. Что лежит в этих полях? Суть этих данных?

Подробная информация о полях написана в XSD. Набор полей теоретически может меняться или переименовываться

**Comment by JohnSergeev** [comment]
Добрый день.

### **1.** ###
Почему только на диск? Почему нет версии для выгрузки, например, в строку?

> Можем добавить возврат в строку. Какая строка должна быть: просто контент XSD схемы записанный в строку или Base64 строку сформировать?

Нам в принципе без разницы. Но, т.к. у вас уже есть функции типа: 

**Document.GetBase64Content(DocflowSide)**

То, наверное, было бы более цельным для АПИ, чтобы новые функции так же возвращали бы данные в Base64.

### **2.** ###
Параметры

> Значения этой тройки можно получить методом Organization.GetDocumentTypes

Ясно. Тут хотелось бы уточнить следующий момент:
![image](https://user-images.githubusercontent.com/33707226/63488833-af615780-c4f3-11e9-8d15-8f429b9d1e71.png)
 
Вот это «для отправки» - получается, что мы можем получить данные только по документам, которые МЫ можем отправить **из своей организации**?

А может быть такая ситуация, когда список доступных нам документов отличается от списка документов, доступных нашему поставщику, отправляющему нам документы? Если да, то каким образом мы можем получить данные по отправляемым ИМ документам?

### **3.** ###
Вместо генерации понятной ошибки, процедура молча выполняется и на диск по указанному пути записывается файл с нулевой длиной

> Исправим в следующем релизе компоненты. Будет возвращаться ошибка с текстом "Неверный тип документа".

Спасибо. Хотя, наверное, было бы понятнее сообщение о **неверных параметрах вызова функции**.

### **4.** ###
Получается, что для разных организаций вызов метода с одними и теми же параметрами может вернуть разные данные

> У разных организаций отличается набор доступных XSD схем и теоретически может отличаться и содержимое.

Вот тут в продолжение вопроса из пункта №2 повторюсь. А мы как-то можем узнать, что за документы доступны в других организациях? Если нет, то как бы… зачем вся суета тогда – мы же все равно не сможем узнать структуру содержимого какого-то уникального нестандартного документа, высланного нам контрагентом «Дядя Федя», раз не сможем получить XSD для документов другой организации?

Что значит **«может отличаться «содержимое»** ?! Вот есть документ УПД. У него же вроде как законодательной заданный формат документа. Как у контрагента «Дядя Федя» содержимое УПД может отличаться от того содержимого, что задано у всех остальных и полностью совпадает с тем, каким это содержимое должно быть по закону?!

Эти изменения содержимого могут быть **вообще любыми** или **речь идет только и исключительно о каких-то добавочных полях/свойствах** дополнительно к неизменному ядру, заданному описанием формата законодательно (типа содержимое УПД всегда одинаково, но вот у поставщика «Дядя Федя» есть еще два дополнительных поля в документе УПД)?

А каким образом вообще у «Дяди Феди» может появиться формат УПД, отличный от стандартного?! Что за манипуляции с реальностью надо произвести, чтобы такую «диковинку» себе заполучить? И, главное, а ЗАЧЕМ такое вообще может понадобиться?! В чем смысл заведения какого-то «документа», о сути содержимого которого из-за его нестандартности не знает никто на свете кроме того, кто этот «документ» каким-то образом завел?

### **5.** ###
Согласно справки эта функция возвращает описание контента документов. Хорошо. А как быть с остальными динамическими контентами, например, теми, с которыми работает «новый» объект CreateReplySendTask2?

> Можете пояснить, что значит "остальные динамические контенты". Можете привести примеры?

Возможно, неудачно выразился. Речь идет о объектах и их сложных полях, также являющимися объектами, которые, например, возвращаются при работе с **CreateReplySendTask2**.

Более подробно я этот момент пытался выяснить у вас в топике https://github.com/diadoc/diadocsdk-1c-docs/issues/339 - там как раз есть пример, что объект для заполнения данных подписанта имеет разный состав для разных типов документов.

И вопрос заключался в том, работает ли функция **SaveUserDataXsd** не с объектами документов «целиком», а с объектами, которые либо являются сложными полями документов (например, подписант документа или данные грузополучателя), либо могут быть и независимы от документа (например, контрагент или организация). Можно ли с помощью этой функции (или какой-то другой) получить какую-то схему состава для подобных объектов?

### **6.** ###
А что, собственно, возвращает данная функция?

> Возвращается XSD схема. Мы ее никак не модифицируем.

Это понятно. Но непонятно то, что я уже ранее спрашивал:

1.	Почему XSD, выгружаемая **для 1С**, **несовместима с 1С**?
2.	Как она устроена? Я в вопросе приводил пример, что по данным этой XSD нормально понять состав и типы полей УПД… как бы невозможно! Она точно правильная?!

**Вот смотрите:**

Вот схема УПД, загруженная в 1С в XDTO (после небольшой доработки! – см. ранее заданные вопросы). Полученная через вызов SaveUserDataXsd:
![image](https://user-images.githubusercontent.com/33707226/63489445-7a560480-c4f5-11e9-8778-61b3dca85c35.png)

Вроде как **Table** – это данные состава. Но тип у них – **anyType**. Как понять, какого типа данные лежат в **Table**?

Если посмотреть на «Типы объектов», то там есть данные по содержимому состава:
![image](https://user-images.githubusercontent.com/33707226/63489480-93f74c00-c4f5-11e9-88c8-85c55bde410a.png)

Но каким образом из данной схемы XSD можно понять, что **Table** – это данные типа **InvoiceTable**?!

Или возьмем, например, подписанта документа:
![image](https://user-images.githubusercontent.com/33707226/63489515-ad989380-c4f5-11e9-9a04-5fafb467811e.png)

Внутри вроде все верно! Но это только кажется – типы вложенных объектов – **anyType**:
![image](https://user-images.githubusercontent.com/33707226/63489527-b7ba9200-c4f5-11e9-9f12-eadf32a1a922.png)
![image](https://user-images.githubusercontent.com/33707226/63489534-bab58280-c4f5-11e9-8a55-d1f9f8d236d8.png)

Может быть из «Типов объектов» как-то по ИМЕНИ свойств SignerReference и SignerDetails можно будет понять, как они устроены? Ну, они там есть… Только состав у них не тот, что надо:
![image](https://user-images.githubusercontent.com/33707226/63489556-cacd6200-c4f5-11e9-9ff3-2f870205650e.png)

SignerReference подходит, а в данных SignerDetails содержимое явно не от подписанта УПД! 
**Как с помощью данной схемы понять какой состав полей у подписанта УПД?**

Или уж совсем простой пример – **Seller**:
![image](https://user-images.githubusercontent.com/33707226/63489593-e0428c00-c4f5-11e9-8b4c-260845f43582.png)

У него тоже тип **anyType**. А в данных типов объектов такой штуки как «Seller» его вообще нет!
Все, что есть на «s» - это:
![image](https://user-images.githubusercontent.com/33707226/63489614-eafd2100-c4f5-11e9-8d10-cfaebeb782c3.png)

Как понять, как согласно XSD заполнен **Seller**?

До этого момента мы как-то сталкивались с XSD, которые просто задавали иерархию свойств и типов объекта. Все поля можно было просто обойти рекурсивно и понять, что где лежит, к чему оно относится и какого оно типа. 

**А с этой XSD мы этого как-то понять не можем! У нас ощущение, что она выгружается как-то криво и у нас «кривая» XSD на самом деле. Либо это какой-то специфический формат схемы, с которым мы ранее не сталкивались.** 

И в связи с этим вопросы:
1.	Почему выгруженная схема несовместима с 1С? Будет ли это как-то дорабатыватьcя/исправляться?
2.	Может быть в выгрузке реально какая-то ошибка?
3.	Если дело в формате, то хотелось бы увидеть объяснение или пример того, как работая с подобной схемой можно понять содержимое документа УПД, которое она вроде как полностью описывает.

### **7.** ###
Что лежит в этих полях? Суть этих данных?

> Подробная информация о полях написана в XSD. Набор полей теоретически может меняться или переименовываться

Это теперь уже понятно. 

Но есть вопрос – **а не маловато ли информации в описаниях полей в XSD схеме?** 

Вы не планируете для "стандартных" документов вроде УПД все-таки отдельно в документации более подробно описать составы документов и работу с ними?

**Поймите, мы, ваши пользователи, работаем вне вашего контекста и часто то, что кажется вам элементарным и само собой разумеющимся, вызывает у нас массу вопросов! Либо вообще является чем-то совершенно непонятным! А о каких-то "всем известных" у вас деталях и нюансах _мы вообще ничего не знаем и даже не догадываемся_**

Спасибо.

**Comment by volodkindv** [comment]
Вопрос 5 предлагаю обсуждать в рамках #339.

Вопрос 6: **XSD-схема не предназначена для 1С**. Вы выгружаете ее с использованием внешней компоненты для 1С, но точно так же могли бы выгружать из любой другой системы. У 1С вообще свои особенности работы с XSD. Например, схемы от ФНС (для УПД, Торг-12 и т.д.) 1С тоже не понимает. Мы когда-то писали конвертер схем под формат, который понимает 1С. Если хотите, можем предоставить его вам. Он на 1С, и после него все равно немного приходилось шлифовать результат.

Вопрос 7: нет, не планировали. Если вы предложите свой вариант, как это могло бы быть, то мы его с вами обсудим.

7 вопросов в одном тикете тяжело обработать. Вынесите, пожалуйста, в отдельные тикеты те вопросы, которые для вас еще актуальны.

**Comment by regfor1c** [comment]
> Вопрос 5 предлагаю обсуждать в рамках #339.
> 
> Вопрос 6: **XSD-схема не предназначена для 1С**. Вы выгружаете ее с использованием внешней компоненты для 1С, но точно так же могли бы выгружать из любой другой системы. У 1С вообще свои особенности работы с XSD. Например, схемы от ФНС (для УПД, Торг-12 и т.д.) 1С тоже не понимает. Мы когда-то писали конвертер схем под формат, который понимает 1С. Если хотите, можем предоставить его вам. Он на 1С, и после него все равно немного приходилось шлифовать результат.
> 
> Вопрос 7: нет, не планировали. Если вы предложите свой вариант, как это могло бы быть, то мы его с вами обсудим.
> 
> 7 вопросов в одном тикете тяжело обработать. Вынесите, пожалуйста, в отдельные тикеты те вопросы, которые для вас еще актуальны.

Добрый день,
если возможно, не могли бы вы прислать обработку для конвертации к поодерживаемому формату 1С regfor1c@mail.ru.

Спасибо

**Comment by volodkindv** [comment]
@regfor1c отправил на почту

**Comment by JohnSergeev** [comment]
Добрый день.

А можно и мне копию?

Спасибо.

С уважением,
Сергеев Евгений.

**Comment by volodkindv** [comment]
[XSD_1C.ZIP](https://github.com/diadoc/diadocsdk-1c-docs/files/3754502/XSD_1C.ZIP)
Выложил сюда
