### ISSUE TITLE
Вопрос о текущем состоянии документации

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#341]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ **5.28.2.481**.

А вы можете объяснить, что у вас происходит с сайтом документации https://diadocsdk-1c.readthedocs.io/ru/latest/?

Когда выбираешь ссылки из общего списка объектов, они открываются нормально. Но, если воспользоваться поиском, то при попытках перехода к результатам поиска очень часто возникает переход на несуществующую страницу.

![image](https://user-images.githubusercontent.com/33707226/63236362-c4828000-c280-11e9-9f7a-87a205f0148f.png)

При щелчке по любой выделенной фоном ссылке со скрина получаем что-то типа такого:
 
![image](https://user-images.githubusercontent.com/33707226/63236374-cd735180-c280-11e9-813d-8654635fd65a.png)

**Подобных переходов на несуществующие страницы очень много!**

Что происходит с сайтом документации? Будет ли это исправлено?

Спасибо.

**Comment by volodkindv** [comment]
Исправлено.
