### ISSUE TITLE
Процедура GetPrintForm() работает некорректно!!!

### ISSUE THREAD

**Issue by ShibaevAnton** [diadoc/diadocsdk-1c-docs#342]
Добрый день. В 1С выполняем следующий код. По итогу получаем форму документа отличающуюся от формы выводимой в веб-интерфейсе. Как так? Это ошибка?

ЭДОбъект = Organization.GetDocumentById("3a08f971-4082-41c8-972b-08f60ef1d0329962058e-bbba-433a-a5b6-7e4d7d211db4", Истина);		
НеформализованныйДокументИмяВременногоФайлаPDF = ПолучитьИмяВременногоФайла("pdf");
ЭДОбъект.GetPrintForm(НеформализованныйДокументИмяВременногоФайлаPDF, 30);
ЗапуститьПриложение(НеформализованныйДокументИмяВременногоФайлаPDF);

**Comment by volodkindv** [comment]
Добрый день.
Приложите скриншоты печатных форм и укажите их различия.

**Comment by ShibaevAnton** [comment]
![C4A2A0AB-37D6-45CE-B7CE-C0D7F660FEDC](https://user-images.githubusercontent.com/24582236/63320103-41673580-c325-11e9-931c-6347047fe25a.png)
![0F8648AB-7F14-454C-AF6D-C98B68766A45](https://user-images.githubusercontent.com/24582236/63320106-41673580-c325-11e9-86ee-045c60ac0499.png)

**Comment by volodkindv** [comment]
На первом  скриншоте (веб) явная опечатка в названии колонки 11: "регистрационной".
Возможно, в ящике подключены кастомные печатные формы.
Укажите, пожалуйста, ID организации / ящика, или ИНН-КПП.

**Comment by ShibaevAnton** [comment]
Да форма кастомная.

ID организации / ящика - c0a186716dc34225b42bc580b328d308@diadoc.ru
ИНН - 7703552167
КПП - 770301001

**Comment by volodkindv** [comment]
Такое может происходить, если кастомная печатная форма была подключена после того, как документ первый раз просмотрели в браузере или скачали через компоненту.

Мы сбросили кэш печатных форм. Попробуйте теперь.
