### ISSUE TITLE
Каких контрагентов возвращает Organization.GetCounteragentListByInnList(INNs)

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#343]
Добрый день! Данная функция возвращает контрагентов только из списка "наших" контрагентов или из всех подключенных к Диадок?

**Comment by IrinaShmonina** [comment]
@GuninaY , здравствуйте.
GetCounteragentListByInnList - метод возвращает информацию по контрагентам по списку ИНН, который вы передаете в параметре. 

Уточните, пожалуйста, что вы подразумеваете под "наших"?

**Comment by GuninaY** [comment]
с теми с кем мы уже работаем

**Comment by GuninaY** [comment]
я хочу отправить в этом методе список инн контрагентов из 1с и в ответ получить тех, кто работает в Диадок. Получится у меня этим методом?

**Comment by IrinaShmonina** [comment]
Возможно, вам стоит ориентироваться на признак IsActive у контрагента. Он проставляется, если в организации отправили документ/подписали входящий. IsActive проставляется в true при первой активности в ящике и обратно не меняется.

**Comment by GuninaY** [comment]
![image](https://user-images.githubusercontent.com/49683051/63744273-88b27080-c8a7-11e9-90bd-5a49915baf2b.png)

ну это тогда, когда уже мы с ними работаем, а если мы еще не сотрудничаем?

**Comment by IrinaShmonina** [comment]
Можно воспользоваться методом [Counteragent.GetStatus](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Counteragent.html#Counteragent.GetStatus).
IsMyCounteragent - отношение партнерства установлено и действует,
InvitesMe - данный контрагент прислал запрос на установление отношения партнерства,
IsInvitedByMe - в адрес данного контрагента был отправлен запрос на установление отношения партнерства,
RejectsMe - отношение партнерства было разорвано со стороны контрагента, либо запрос на установление отношения партнерства был отклонен контрагентом,
IsRejectedByMe - отношение партнерства было разорвано со стороны текущей организации, либо запрос на установление отношения партнерства был отклонен текущей организацией

**Comment by GuninaY** [comment]
меня интересуют контрагенты с которыми не было никогда никаких отношений, ни приглашений, есть возможность получить таких?

**Comment by volodkindv** [comment]
Organization.GetCounteragentListByInnList(INNs) вернет всех контрагентов, которые хоть раз регистрировались в Диадоке.

Для тех, с кем вы уже работаете/работали, метод GetStatus() вернет "IsMyCounteragent", "IsInvitedByMe", "InvitesMe", "RejectsMe" или "IsRejectedByMe". 

Для тех, с кем не работали, GetStatus() вернет "NotInCounteragentList".

**Comment by GuninaY** [comment]
Спасибо!
