### ISSUE TITLE
Ошибка SaveAllContent

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#345]
Произошла исключительная ситуация (DocumentBase.SaveAllContent): Не удалось сгенерировать протокол передачи документа. Ссылка на документ https://diadoc.kontur.ru/54d0b467-aade-47d6-8136-a2bbe2eeb67d/Document/Show?letterId=14df3aca-8642-48e4-8539-a54280a83ca9&documentId=9274e4e8-3264-4c87-bfc6-42f63d011189

**Comment by GuninaY** [comment]
Последующие Торг-2 вылетают с той же ошибкой

**Comment by kulakovskaya** [comment]
Добрый день. Есть вероятность, что печатные формы документов не успели сгенерироваться. Рекомендуем повторно выполнить запрос.

**Comment by GuninaY** [comment]
со второго раза получилось
