### ISSUE TITLE
Помогите заполнить иные сведения

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#346]
![image](https://user-images.githubusercontent.com/49683051/63686989-01fc8580-c80c-11e9-9c33-9e1cbf755bd8.png)

Заполняю  в УПД
StructedAdditionalInfos = Content.TransferInfo.AdditionalInfoId.AddStructedAdditionalInfo();
			StructedAdditionalInfos.Key = "Итого количество";
			StructedAdditionalInfos.Value = строка (реализация.РеализацияСсылка.Товары.Итог("Количество"))+ " шт";
Выходит эта информация под основанием передачи, а мне надо после даты отгрузки/передачи. Может нужно не TransferInfo заполнять?

**Comment by B0ris163** [comment]
Привет.
СписокДопИнформации = Результат.Content.TransferInfo.AdditionalInfoId.StructedAdditionalInfos;  
ДопРезультат		          = НовыйКонтент(СписокДопИнформации.ВладеющееСвойство.Тип.Имя);
ДопРезультат.Key	          = "Иные сведения - по договору";
ДопРезультат.Value	= "и тут что-то про договор);
				
СписокДопИнформации.Добавить(ДопРезультат);
