### ISSUE TITLE
ПРЕДЛОЖЕНИЕ по улучшению АПИ - работа с удаленными документами

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#347]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ 5.28.3.491.

Есть одна странность в работе АПИ, на которую я ранее уже обращал ваше внимание. Хотелось бы еще раз напомнить о ней.

Документы в Диадок можно удалять (на самом деле при этом происходит перенос документа в папку "Удаленные").

**При этом (согласно документации), в АПИ компоненты для 1С просто вообще толком нет никакого функционала по работе с удаляемыми и удаленными документами!**

Судите сами:

Что я могу делать у вас на сайте (и это логичный набор операций):
1.	Удалить документ (перенести в "Удаленные")
2.	Посмотреть какие документы лежат в папке «Удаленные»
3.	Восстановить документ из папки «Удаленные» обратно туда, откуда он в «Удаленные» попал

Что я могу делать через АПИ (и это какой-то куцый огрызок от нужных возможностей):
1.	Удалить документ (перенести в "Удаленные")

**ВСЁ !!!**
**В рамках работы АПИ с удалением документов мы, получается, ничего толком сделать-то не можем!**

Вот удалил я документ и ошибся при этом (всякое бывает) – и что дальше? Восстановить документ я не могу, нет такой команды. Посмотреть, что у меня в удаленных – не могу, поиск и отбор документов не показывает документы в папке «Удаленные» - только «Входящие» и «Исходящие». 

Как с этим работать? Получается, что если действуешь в рамках АПИ, то даже права на ошибку не имеешь! Удалил – всё, уже никак не восстановишь! Нужно заходить на сайт и там восстанавливать. 

Очень бы хотелось, чтобы появилась как минимум одна новая команда - восстановить документ из "Удаленных". Чтобы через АПИ можно было бы делать то же самое, что возможно вручную на сайте Диадок!

В идеале хотелось бы иметь возможность в рамках операции получения списков документов каким-то образом получать не только что лежит во "Входящих" и "Исходящих", но и получать, что лежит в "удаленных".

Добавление подобного функционала представляется нам и полезным, и логичным (в рамках полноты АПИ).

Спасибо.

**Comment by volodkindv** [comment]
Этот вопрос уже был: #170 

Восстановление удаленных документов возможно методом [Organization.RestoreDocument](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.RestoreDocument)

Возможность получить список удаленных документов отсутствует в http api.

Для ее добавления обратитесь к менеджеру, чтобы он продвигал эту задачу в очереди разработки.

**Comment by volodkindv** [comment]
Duplicate of #170
