### ISSUE TITLE
ПРЕДЛОЖЕНИЕ по улучшению АПИ - получение списков документов

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#348]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ 5.28.3.491.

Хотелось бы предложить вам одно расширение АПИ, которое, как нам кажется, могло бы оказаться полезным для тех ваших пользователей, которые, как и мы, работают с относительно большим объемом документов.

Каким образом с помощью АПИ мы получаем документы? Мы выбираем их, используя объект **Organization** и вызов его метода **GetDocumentsTask()**. В результате этого вызова мы получаем объект **DocumentsTask**, заполняем в нем параметры отбора документов и вызываем метод **GetDocuments()** или **GetDocumentsAsync()**. 

_(пример на "старом" функционале АПИ, но на суть дела это не влияет)_

Т.е. делаем что-то типа этого (пример из вашей документации):

DocumentsTask 	= Organization.GetDocumentsTask();
DocumentsTask.FromSendDate 	= НачалоГода(ТекущаяДата());
DocumentsTask.ToSendDate 	= КонецГода(ТекущаяДата());
DocumentsTask.Category 	= "XmlTorg12.InboundWaitingForRecipientSignature";
DocumentList 	= DocumentsTask.GetDocuments();

В результате мы получаем уже готовую заполненную коллекцию найденных документов. Которые далее и обрабатываем.

Также есть еще один способ получить документ через АПИ – если у нас есть ID документа, то мы можем получить сам документ через вызов метода **GetDocumentById()** объекта **Organization**. 

**Но нужно знать ID документа!**

По результатам нашей работы с АПИ мы выделили два неудобных момента в работе отбора документов с помощью объекта **DocumentsTask**. Оба этих момента связаны с тем, что с его помощью, посредством вызова методов **GetDocuments()** и **GetDocumentsAsync()**, можно получить лишь **только уже сами готовые документы!** И ничего более.

**А это весьма затратная по ресурсам операция!**

Поэтому в ситуациях, когда происходит работа с большим количеством документов, получение большого количества уже **полностью готовых заполненных объектов документов** может оказаться очень длительным по времени, затратным по ресурсам и чреватым необходимостью полного повтора длительной операции при каком-то сбое на вашей или на нашей стороне.

**Первый момент**
Было бы здорово иметь дополнительную функцию, которая в результате своего вызова вернет не коллекцию готовых к дальнейшей обработке документов – а **только лишь их количество** (на момент обращения по установленным настройкам отбора).

При наличии такой функции можно, например, в интерактивном режиме быстро предупреждать пользователя о чем-то типа «Вы установили слишком широкие настройки отбора и под ваши условия попадает 45283 документа! Вы уверены, что хотите получить их все? Ориентировочно это займет 2 часа!».

**Сейчас же узнать количество попадающих в отбор документов можно только выполнив их полное получение, что выглядит весьма затратным по сравнению с простым получением их количества. Да и весьма странным, т.к. другого способа просто нет!**

Мы полагаем, что пользователям АПИ (ну, как минимум, нам!) была бы удобной какая-то функция **GetCountOfDocuments()** (или что-то вроде), которая по установленному отбору возвращала бы не коллекцию уже готовых и заполненных объектов документов, а только лишь **количество документов, которое попало в данные настройки отбора на момент вызова функции**. И делала это быстро – как минимум, просто по тому, что ей не надо было бы формировать и передавать на сторону вызова заполненные объекты документов.

**Второй момент**
При большом потоке входящих документов возникает естественная мысль как-то ускорить обработку их приема. И естественным же образом возникает идея о распараллеливании операций по получению документов. Но текущая реализация возможных операций по получению документов предполагает получение только уже готовых документов (или знания их ID, а для этого их все равно нужно сперва получить отбором через DocumentsTask!).

С нашей точки зрения для возможностей удобной параллельной обработки документов была бы очень полезной следующая доработка – добавление в объект **DocumentsTask** функции (что-то типа **GetDocumentIDs()**), которая по заданным настройкам отбора вернет не коллекцию уже полностью заполненных документов, а только лишь **коллекцию их ID!**  Опять же, т.к. при этом не надо формировать и заполнять данные самих документов, такая функция по определению должна быть гораздо более быстрой, чем получение коллекции полностью заполненных документов.

А быстро получив набор ID документов, мы сможем уже любым удобным нам образом работать с ними. Например, сможем запускать параллельно несколько фоновых заданий на любую обработку документов по полученным ID, используя функцию **GetDocumentById()**.

Подумайте, может быть вы сочтете подобное расширение функционала полезным.

Спасибо.

**Comment by volodkindv** [comment]
Добрый день.

Пожелания понятны. Сразу скажу, что планов по их реализации сейчас нет. Отвечу здесь про пункт 1. Пункт 2 давайте обсуждать в отдельном тикете, иначе запутаемся.

В http API метод [getDocuments ](http://api-docs.diadoc.ru/ru/latest/http/GetDocuments.html)отдает результат "постранично" - не более 100 документов в пачке. И указывает, осталось ли в выборке больше 1000 документов: http://api-docs.diadoc.ru/ru/latest/proto/DocumentList.html

Поэтому точное количество документов в выборке, если их более 1000, мы показать не сможем.

При необходимости можно ограничивать GetDocuments по контрагентам, подразделениям и т.д. Но это скорее костыли.

По опыту: при работе с большим количеством документов лучше подгружать их через ленту событий API (GetNewEvents/GetDocflowEvents в HTTP API), а не через GetDocuments. Здесь можно привести аналогию с 1С. Когда-то была выгрузка из УТ в БП "за месяц", а потом появилась через план обмена - "только изменения". Второе сложнее технически, но на больших объемах данных выигрывает на порядки.

Если в вашей организации действительно большое количество документов, то имеет смысл пересмотреть свой подход к интеграции. Или вообще заказать интеграцию силами СКБ Контур.

**Comment by JohnSergeev** [comment]
Спасибо. Мы уже давно работаем, используя вашу систему событий. С этим все нормально. Но для целей отладки и контроля у нас есть возможность получения документов по спискам, используя функционал GetDocuments - и вот тут хотелось бы просто чуть больше возможностей, т.к. когда за 1 день получаешь несколько тысяч входящих, стандартного функционала немного не хватает. Но это не критично. Переживем.

**Comment by volodkindv** [comment]
Хорошо. Этот тикет закрываю. Если второй вопрос актуален, вынесите его в отдельный тикет.
