### ISSUE TITLE
Тип данных динамического контента - как понять, что внутри? ПРОДОЛЖЕНИЕ

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#349]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ 5.28.2.481.

**Еще раз огромное спасибо за добавление функционала по работе с составом полей динамического контента!**

При более плотной попытке рассмотрения нового функционала, вылезла одна проблема, о которой хотелось бы рассказать, и решение которой хотелось бы предложить.

Ранее в уже закрытом вами тикете https://github.com/diadoc/diadocsdk-1c-docs/issues/339
мы с вами в переписке пришли к следующему:

![image](https://user-images.githubusercontent.com/33707226/63910924-e5f71f00-ca6b-11e9-8a4d-cd2a96b15169.png)

**К сожалению, это неверно для коллекций!**

Пример:
![image](https://user-images.githubusercontent.com/33707226/63911008-340c2280-ca6c-11e9-9a27-fe880a5354d4.png)

Получается, что коллекция, будучи Com-объектом тем не менее **не допускает** использования для нее **GetPropertiesNames()** - вылетает в исключение.

И, если мы увидим - _"О! Это com-объект, давай вызовем **GetPropertiesNames()** и посмотрим какие у него есть поля"_ - то мы вылетим в исключение, т.к. у коллекции нет метода **GetPropertiesNames()**. 

**Т.е. предложенная вами проверка на тип объекта, в общем случае не сработает!**

**Простым способом из данных текущего объекта невозможно понять - вот это его поле, у которого тип com-объект - это какая-то "сложная штука", поля которой можно получить используя GetPropertiesNames() или же это коллекция каких-то объектов.**

Получается, что тогда работа с полями должна строится как-то так:

![image](https://user-images.githubusercontent.com/33707226/63911724-96662280-ca6e-11e9-9d01-31ffd84a88c5.png)

Что очень "мутно" и сопряжено с обязательным использованием исключений, чего очень бы не хотелось.

Хотелось бы предложить вам следующее решение -добавить специальную функцию **GetTypeInfo()**, возвращающую для элемента динамического контента флаги того, чем он является - сложным составным объектом или же коллекцией.

С использованием такой функции, ранее приведенный код стал бы гораздо короче, понятнее и не нуждался бы в исключениях:

![image](https://user-images.githubusercontent.com/33707226/63912203-05904680-ca70-11e9-9986-84e16ffbd49f.png)

**Наличие подобной функции представляется нам исключительно полезным!**

С надеждой на ваше внимание и понимание.

Спасибо.

**Comment by volodkindv** [comment]
Обсуждаем варианты решения.
Что для вас приоритетнее - прозрачность кода или отсутствие исключений? Можно пойти двумя путями.

Прозрачность кода можно обеспечить без доработок в компоненте, рефакторингом кода 1С:
```
Функция ТипУзлаDynamicContent(Узел)
	
	Если ТипЗнч(Узел) = Тип("ComОбъект") Тогда
		
		Попытка
		
			Узел.GetPropertiesNames();
			ТипУзла = "DynamicContent";
		
		Исключение
		
			ТипУзла = "Collection";
			
		КонецПопытки;
			
	Иначе
		ТипУзла = Неопределено;
	КонецЕсли;
	
	Возврат ТипУзла;
	
КонецФункции	
```

Второе несколько сложнее. Вариант с ОбъектDynamicContent.GetTypeInfo() реализовать сложно из-за архитектурных особенностей компоненты. Есть другой вариант, через промежуточный объект-рефлектор. Примерно так:

```
	AddInDiadocInvoiceAPI = Новый("AddIn.DiadocInvoiceAPI");
	RootCOMObject = AddInDiadocInvoiceAPI.CreateObject();
	Reflector = RootCOMObject.Reflector;
	...
	
	ТипУзла = Reflector.GetObjectType(ОбъектDynamicContent);  // например, "Collection"
```
Этот вариант универсальнее и его легче реализовать. Но придется где-то держать COMОбъект "Reflector", который должен быть доступен в функции обхода дерева контента.

**Comment by JohnSergeev** [comment]
Нам бы в идеале: быстро, прозрачно и без исключений ; -)

**Вариант с рефлектором очень интересен! Это в любом случае будет лучше, чем вообще ничего**!

Но хотелось бы уточнить следующее:

У вас сейчас есть версии компонент для 1С натив и com. Вот по идее т**акая штука должна также работать как в натив, так и в com варианте**. А то ей не всегда получиться воспользоваться. И это будет странно.

И еще:
А насколько быстрым будет использование рефлектора? Основная проблема с попытками - это использование исключений "не по адресу" - для управления потоком выполнения кода в нормальной ситуации, когда проблем и ошибок нет. Это неверно идеологически, довольно-таки некрасиво, но, главное, это тупо медленнее, чем могло бы быть без использования исключений! Но, если окажется, что рефлектор еще медленнее, то, возможно, будет проще смирится с попытками и, действительно, как в вашем примере "понаделать" несколько функций, определяющих тип данных подобно тому, как показано в примере.

Очень ждем от вас информацию по этому вопросу!

**Дополнительно:**
Хотелось бы еще раз упомянуть о моем комментарии в чужом топике по поводу добавления поля **Type** для всех объектов. **Это в любом случае было бы полезно!** Чем больше информации у нас, пользователей АПИ, будет, тем лучше! От наличия еще одного поля никто не пострадает. А кому надо - смогут воспользоваться этой дополнительной информацией в своей работе.

Спасибо

**Comment by volodkindv** [comment]
Ок, буедм делать рефлектор. По срокам пока сориентировать не можем, следите за новыми релизами.
Рассчитываем, что рефлектор будет быстрый и во всех вариантах компоненты.

Поле Type добавлять не будем, т.к. оно будет конфликтовать по имени, если такое поле уже описано в XSD схеме.
