### ISSUE TITLE
Приглашение к партнерству с файлом доп. соглашения.

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#35]
Приглашение к партнерству с файлом доп. соглашения.
Используем компоненту для работы на сервере (COM-компонента для 64х).
Последний раз приглашение отправляли 10 октября 2016 и работало.
Контрагент отправил нам приглашение к партнерству, мы его отклонили с текстом, что "мы вышлем вам с доп соглашением приглашение к партнерству, вы его подпишите и мы начнем обмен ЭДО через Диадок", но не смогли отправить приглашение. Функция на нижнем скрине отрабатывает без ошибок, но на портале не появляется приглашение. Необходимо исправить. Возможно, что такая проблема именно в этом контрагенте, но пока проверить не на ком больше. 
![img-2016-11-08-12-31-08](https://cloud.githubusercontent.com/assets/20082460/20093972/413261c4-a5b0-11e6-877a-00d9f91b1b0f.png)
![img-2016-11-08-12-26-24](https://cloud.githubusercontent.com/assets/20082460/20093977/4a0f8fa6-a5b0-11e6-9a49-fff699a6c142.png)

**Comment by proger1c** [comment]
Добрый вечер.

1. Что возвращает свойство Result после выполнения метода SendAsync()?
2. Какой статус взаимоотношений с текущим контрагентом, если его проверить методом GetStatus? http://diadocsdk-1c.readthedocs.io/ru/latest/GetStatus.html

**Comment by jakeqwert** [comment]
1)  Result = ложь, а после долго промежутка времени уже com недоступен. 
2)  GetStatus = IsRejectedByMe

**Comment by jakeqwert** [comment]
![img-2016-11-08-14-40-41](https://cloud.githubusercontent.com/assets/20082460/20097770/3b81cf4c-a5c1-11e6-8e35-acc743b130cf.png)

**Comment by proger1c** [comment]
Такой ответ в Result возможен, когда сервер не может найти ящик, по переданному CounteragentBoxId.
Скиньте строкой значение параметра CounteragentId, которое передаете в AcquireCounteragentTask.CounteragentBoxId. Попробую его проверить.

**Comment by jakeqwert** [comment]
Counteragent.Id="af16a91299e24668a78e69422b7fdc11@diadoc.ru"

**Comment by proger1c** [comment]
Id корректный.

Передал Ваш кейс разработчику компоненты.
Подскажите еще какая версия компоненты, на которой работаете?

**Comment by jakeqwert** [comment]
5.5.4.83

**Comment by proger1c** [comment]
Довольно старая версия. Отчего свежий релиз не хотите попробовать?

**Comment by jakeqwert** [comment]
Зарегистрировал новую dll версии 5.8.0.138. Не отправляется приглашение.

**Comment by proger1c** [comment]
Result так же возвращает Ложь или ошибку?

**Comment by jakeqwert** [comment]
Вначале вот так:
![img-2016-11-16-14-42-51](https://cloud.githubusercontent.com/assets/20082460/20346076/4233589c-ac0b-11e6-834c-b2322ad319b5.png)
А через секунды 3 вот так:
![img-2016-11-16-14-43-53](https://cloud.githubusercontent.com/assets/20082460/20346103/5fadb4d0-ac0b-11e6-8602-16e95fd4e1f9.png)

**Comment by denver069** [comment]
В ближайшем релизе такое поведение внешней компоненты будет исправлено.

**Comment by jakeqwert** [comment]
А когда планируется релиз компоненты, а то мы не можем с такими контрагентами начать через ЭДО  обмениваться.

**Comment by jakeqwert** [comment]
Такая же проблема, но контрагент новый, не отправляет компонента приглашение:
![img-2016-11-17-13-54-41](https://cloud.githubusercontent.com/assets/20082460/20386624/82762020-accd-11e6-8f7f-7503969bb282.png)

**Comment by denver069** [comment]
Релиз состоялся, новая версия внешней компоненты [5.9.0.154](http://diadocsdk-1c.readthedocs.io/ru/latest/Downloads.html) опубликована.

**Comment by jakeqwert** [comment]
Проблема на  5.9.0.154 ушла. Спасибо.
