### ISSUE TITLE
Ошибка в адресе покупателя при заполнении boxId

### ISSUE THREAD

**Issue by sergeb72** [diadoc/diadocsdk-1c-docs#350]
Версия установленной компоненты для произвольных систем: 5.28.3.491

CreatePackageSendTask
AddDocument("UniversalTransferDocument")

При установленном значении UtdSellerContent.Buyer.boxId = "7ff5d1707b754e8bb9af62ca91d11673@diadoc.ru"

в момент отправки появляется ошибка:

'##100[Ошибка сервера Диадок]code:400, HTTP error: Only one of addresses must be filled in Info.Buyer.Address'.

Адрес покупателя вручную не заполняется, надеемся на его автоматическую подстановку.

**Comment by IrinaShmonina** [comment]
Добрый день! Ошибка возникла из-за того, что у организации указан и обычный адрес, и иностранный адрес. Мы не можем за контрагента решить какой адрес им следует оставить, какой из них верный. Поэтому контрагенту нужно самому в реквизитах организации оставить только один адрес. Тогда и ошибка у вас при генерации перестанет возникать.

**Comment by sergeb72** [comment]
Спасибо, сообщим контрагенту.
