### ISSUE TITLE
Ошибка 409 (Http.Conflict) при выполнении CloudSignTask.Sign()

### ISSUE THREAD

**Issue by Sergguha** [diadoc/diadocsdk-1c-docs#351]
Добрый день!
Компонента Диадок 5.28.4.493 (x64)
Из ящика 33c50fb3-9eed-438d-baeb-ad1b2e0e967f@diadoc.ru отправляется контент документа УПД для подписания облачным сертификатом:
CloudSignTask.AddContent(Документ.Content,CounteragentId)
При вызове метода CloudSignTask.Sign() компонента возвращает ошибку:
**(CloudSignTask.Sign): ##100[Ошибка сервера Диадок]code:409, HTTP error: ErrorCode: (Http.Conflict)**

Подскажите, с чем это связано?

**Comment by GilimkhanovDenis** [comment]
Тикет закрою. Если ошибка воспроизведётся, переоткройте его, пожалуйста
