### ISSUE TITLE
Ошибка при принятии приглашения партнерства

### ISSUE THREAD

**Issue by Aleksey2W** [diadoc/diadocsdk-1c-docs#352]
```
Counteragent = Диадок_КонтекстОрганизации.GetCounteragentById(ИДКонтрагента);
Counteragent.AcquireCounteragent(?(Сообщение = "", "Принимаем приглашение", Сообщение));
```
Ошибка:
Произошла исключительная ситуация (CounteragentBox.AcquireCounteragent): ##100[Ошибка сервера Диадок]code:409, HTTP error: Cannot accept invitation from d89b7cf4-f1c3-4a27-b56d-5636e64fc130 with attachment with signature requested; use PostMessagePatch instead

**Comment by kulakovskaya** [comment]
Добрый день.
Контрагент прислал приглашение с вложенным файлом. Для принятия таких приглашений необходимо найти входящий документ с типом TrustConnectionRequest и подписать его через ReplySendTask.
