### ISSUE TITLE
ОШИБКА в последнее версии АПИ - Не работает GetDynamicContent !

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#353]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ 5.28.3.491.

Прочитал о исправлении ошибок в версии **5.28.5.501**, установил.

И при первой же попытке работы обнаружил чудесное:

1. Получаем объект документа:
![image](https://user-images.githubusercontent.com/33707226/64398493-650dd800-d0a8-11e9-8f81-d646ec186b12.png)

2. Пробуем получить у него динамический контент продавца:
![image](https://user-images.githubusercontent.com/33707226/64398537-8b337800-d0a8-11e9-937e-c340b4655142.png)

### **Вместо объекта контента получаем ЧИСЛО 0!** ###

3. Этот документ нами еще не подписан и контента покупателя у него еще нет. Ранее, если попробовать получить такой контент, когда его еще нет, появлялась ошибка и выпадали в исключение. А сейчас:
![image](https://user-images.githubusercontent.com/33707226/64398619-d77eb800-d0a8-11e9-8c2b-11ec5d07e31e.png)

**Вот этот вариант с Неопределено, если контента еще нет, вместо выпадения в исключение, кстати, более хорош!** 
Было бы здорово, если бы это так и осталось.

Но что за проблема с контентом Seller'а ?!

Что происходит, если с тем же документом получать те же данные, используя "старую" версию АПИ **5.28.3.491**:

![image](https://user-images.githubusercontent.com/33707226/64398842-aeaaf280-d0a9-11e9-88ac-97564d86810b.png)

Т.е. в этой версии все нормально! Контент продавца получается, как и должно быть.

### **А в новой версии 5.28.5.501  - явно какая-то ошибка!** ###

Очень надеемся на быстрое исправление проблемы!

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Исправлено в 5.28.6.502
[Информация о релизе](http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_28_6.html)
[Ссылки для скачивания](http://1c-docs.diadoc.ru/ru/latest/Downloads.html)
