### ISSUE TITLE
Ошибка отправки на подпись

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#354]
Отправляем документ на подпись с компьютера одного из сотрудников, получаем ошибку Произошла исключительная ситуация (ResolutionRequestTask.Send): ##100[Ошибка сервера Диадок]code:409, HTTP error: Документ передан на подпись. С другого рабочего места все отправилось, на всех документах так. Для примера можно взять вот этот документ https://diadoc.kontur.ru/54d0b467-aade-47d6-8136-a2bbe2eeb67d/Document/Show?letterId=5bf2abde-dd21-4962-9000-dbeca5148185&documentId=63bd26eb-e454-412b-8ea0-c342295da1cc. В чем может быть причина?

**Comment by aeremina88** [comment]
Добрый день!
Убедитесь, что не отправляете повторно на подпись документ, который уже передан на подпись.
Ошибка говорит именно о такой ситуации.
