### ISSUE TITLE
GetPrintForm() показывает xml...

### ISSUE THREAD

**Issue by ShibaevAnton** [diadoc/diadocsdk-1c-docs#355]
Добрый день. В веб интерфейсе форм сф отображается корректно, а при вызове процедуре выводится xml... 

Что то пошло не так... Это ошибка? Или?

![BE77F73D-4ABE-41D3-B42E-79D71D5888BD](https://user-images.githubusercontent.com/24582236/64423624-a786e300-d0af-11e9-9ac4-0b8ff35ccb83.png)
![69EF8596-9565-466D-99F5-F6F07CC35EA9](https://user-images.githubusercontent.com/24582236/64423625-a81f7980-d0af-11e9-99bd-8b066c006a84.png)

**Comment by aeremina88** [comment]
Добрый день!
В ядре Диадока еще не реализован метод скачивание печатной формы для УПД 820.
Сейчас задача в активной работе. Ориентируемся на начало октября
