### ISSUE TITLE
Отсутствие ф-и GetAddressString() в адресных данных объектов, получаемых через GetDynamicContent()

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#356]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ **5.28.3.491**.

При работе с данными, возвращаемыми **GetDynamicContent()**, заметили одну вещь, которую хотелось бы прояснить.

При работе с обычным контентом, получаемым через **GetContent()** в данных **Seller**'a, **Buyer**'a и других есть их адресные данные. И для объекта адресных данных есть специальная функция **GetAddressString()**:

![image](https://user-images.githubusercontent.com/33707226/64500266-d1cedf80-d2ff-11e9-8231-09feccf3df7c.png)

Обнаружилось, что в данных **Seller**'a, **Buyer**'a и других, получаемых через **GetDynamicContent()**, также есть их адресные данные. Они заданы в ином формате, чем возвращаемые через **GetContent()**. 

**И при этом для них не работает функция GetAddressString()!** 

Возвращается исключение об отсутствии такой функции:
![image](https://user-images.githubusercontent.com/33707226/64500422-72250400-d300-11e9-9c4d-8e85644ee33a.png)

**Вопрос:**
Это какая-то недоработка и это будет исправлено? Функция появиться?

Просто это очень удобная штука для **получения представления адреса именно в том варианте, каким видит его ваша сторона обмена**, и исчезновение возможности получения такого представления адреса кажется нам неправильным...

Может быть вы подумаете над тем, чтобы вернуть этот функционал и для адресных данных объектов, получаемых через **GetDynamicContent()**?

Или же ее более никогда не будет?

Спасибо.

**Comment by aeremina88** [comment]
Добрый день!
Это особенность динамического контента. Сложно понять, как интерпретировать полученный объект, поэтому метод GetAddressString() для него не реализован.

Опишите, пожалуйста, подробно сценарий использования представления адреса?

**Comment by JohnSergeev** [comment]
Добрый день.

А зачем самим собирать строку адреса, если:
1. Уже есть готовая правильно собранная строка
2. Которая представляет адрес так, как он написан на печатной форме
3. Которая с точки зрения Диадок (и по идее любых контрольных органов!) собрана правильно

Плюс при сборе строки адреса можно в чем-нибудь ошибиться или что-нибудь не учесть, а тут строка уже готовая и без ошибок.

Т.е. сценарий простой - зачем уродоваться с шансом ошибиться, когда можно взять готовую и без ошибок - это просто проще и удобнее!

Мы правильно понимаем, что этот функционал уже не вернется и нам теперь все-таки нужно будет собирать адресную строку самостоятельно?

Спасибо.

**Comment by aeremina88** [comment]
Добрый день!
Прошу прощения за задержку ответа.
Метод GetAddressString возвращает один из возможных вариантов представления адреса в строку, а именно:

- "$Индекс$, $наименование_региона$, $район$, $город$, $населенный_ пункт$, дом № $номер_дома$, корпус $номер_корпуса$, кв $номер_квартиры$", для адресов РФ
- "$наименование_страны$, $строка_адреса$, для адреса в произвольной форме

На примере формата 820 приказа, 1-ый вариант - это [АдрРФ ](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=265660), 2-ой вариант - [АдрИнф ](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=265662).
АдрРФ - это представление адреса по КЛАДРу. Часто бывают случаи, когда адрес не укладывается в КЛАДР. Например, вместо квартиры нужно указать офис, вместо корпуса, строение. Либо есть дополнительные адресные элементы, для которых нет полей: литера, этаж и т.п. В таком случае GetAddressString вернет неточный либо неполный адрес. Поэтому нельзя с уверенностью сказать, что строка адреса собрана правильно. 

Исходя из этого, приняли решение для динамического контента метод получения адресной строки не поддерживать.
