### ISSUE TITLE
Путаница в типе и значениях полей булевых типов при использовании GetDynamicContent()

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#357]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ **5.28.3.491**.

При работе с данными, возвращаемыми **GetDynamicContent()**, наткнулись на странную вещь, которую хотели бы у вас уточнить.

В объекте документа (да и во многих других объектах) есть поля типа "Булево". Например, **IsDeleted**, **IsTest** или **Revised**. Подобные поля есть и у других объектов - например, поле **CanEncrypt** у объекта Certificate. 

Все эти поля в этих объектах при работе с АПИ получаются именно как объекты типа "Булево" и имеют значения _Истина_ или _Ложь_:

![image](https://user-images.githubusercontent.com/33707226/64501362-62a7ba00-d304-11e9-903e-1a6311c7506b.png)

![image](https://user-images.githubusercontent.com/33707226/64501342-4efc5380-d304-11e9-9f38-bcbb6f46c89a.png)

Однако, при получении объекта грузоотправителя (**Shipper**) с использованием данных, полученных через **GetDynamicContent()**, мы увидели нечто странное:

![image](https://user-images.githubusercontent.com/33707226/64501402-8c60e100-d304-11e9-8e0d-e040f71d4957.png)

Поле **SameAsSeller** - это, по сути, также поле булевого типа.

**Однако, вместо типа "Булево" возвращается строка представления булевого значения, да еще и на английском языке!**

**Вопрос:**
Будет ли это как-то исправлено, чтобы в полях, которые по смыслу являются полями булевого типа, возвращались бы именно данные булевого типа, а не какие-то "сырые", не до конца обработанные данные?

Спасибо.

**Comment by azhipaigor** [comment]
Мы долго думали на счет представления значений динамических объектов. В итоге пришли к тому, что лучше использовать строки в исходном [XSD-представлении](https://www.w3.org/TR/xmlschema-2/#built-in-datatypes) значений. Такой подход позволяет исключить искажение представлений значений при проецировании в систему типов целевой системы (компонента используется не только в 1С и есть сложности с разными поддерживаемыми типами в разных системах). Ну и отсутствие сложного мэппинга упрощает архитектуру динамического контента и уменьшает риски багов. Существенных минусов в таком подходе мы не нашли, в любом случае интеграционному решению нужно работать с типами и XSD-представление значений является наиболее унифицированным и безопасным.
