### ISSUE TITLE
Расхождение в информации XSD, выгружаемой через SaveUserDataXSD, и данными Контур.Норматив

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#358]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ 5.28.3.491.

При выполнении работ по реализации поддержки 820 приказа ФНС было обнаружено небольшое разночтение в описаниях полей схемы документа между данными на сайте:
https://normativ.kontur.ru/document?moduleId=1&documentId=328588

И данными, возвращаемыми вызовом:
_Документ.Organization.**SaveUserDataXSD**("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01", "Seller", <имя_файла>)_

На сайте:
![image](https://user-images.githubusercontent.com/33707226/64676215-6d0ab500-d4b8-11e9-9807-476595dcb9c3.png)

В возвращаемой XSD:
![image](https://user-images.githubusercontent.com/33707226/64676268-86abfc80-d4b8-11e9-840a-be31ec6c296b.png)

т.к. в этом поле располагаются данные документа, являющегося **основанием** для уступки, то получается, что вариант на сайте верен, а вариант в XSD схеме описан неправильно и немного вводит в заблуждение.

Быть может, это стоит поправить.

**Comment by OlgaPetushina** [comment]
Добрый день @JohnSergeev 
Поправили в новой версии. Подробности тут https://www.diadoc.ru/blog/7883
