### ISSUE TITLE
Представление УПД

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#359]
После перехода на версию компоненты 5.28.2.481 представление УПД (pdf), получаемое через Document.SaveAllContent(КаталогВыгрузкиФайлов, Истина) стало странным. Вместо документа установленного образца выводится xml-файл.
Подскажите, с чем это связано?

**Comment by NataliaShumikhina** [comment]
Добрый день! Печатные формы pdf для 820 формата еще не реализованы, поэтому в pdf сейчас выгружается содержимое xml-файла. Ожидаем появление печатных форм pdf в октябре

**Comment by prog22** [comment]
Спасибо.
