### ISSUE TITLE
Отправка приглашения к партнерству с вложением не асинхронным методом

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#36]
Добрый день, уважаемые разработчики.
Верните, пожалуйста, в компоненту (COM-компонента для 64х для сервера, на локальных машинах 32 бита), возможность отправки приглашения к партнерству с вложением не асинхронным методом:
(в обработке для типовых конфигураций была найдена функция, которая в текущей версии компоненты возвращает ошибку "Ошибка при вызове метода контекста (CreateSendTaskFromFile): Произошла исключительная ситуация (Box.CreateSendTaskFromFile): Неверный тип контента. Допустимыми являются следующие значения: InvoiceContent, InvoiceCorrectionContent, XmlTorg12Content, XmlAcceptanceCertificateContent, ...")
TrustConnectionRequest=Organization.CreateSendTaskFromFile(ИмяФайла, "TrustConnectionRequest");
TrustConnectionRequest.Comment=				Комментарий;
TrustConnectionRequest.CounterAgentid	=	CounteragentId;
TrustConnectionRequest.Send();

**Comment by proger1c** [comment]
Спасибо большое за информацию. В ближайшее время поправим проблему.

**Comment by jakeqwert** [comment]
Спасибо очень ждем. Очень часто отправляем одному контрагенту (не массово) приглашение с вложением, особенно новеньким.  И в текущей нашей реализации не удобно использовать асинхронный метод.

**Comment by proger1c** [comment]
На сайте выложена новая версия компоненты 5.9.0.154. Для объекта AcquireCounteragentTask добавлен метод Send. 
http://diadocsdk-1c.readthedocs.io/ru/latest/Send-(AcquireCounteragentTask).html

Ошибка в типовом модуле будет поправлена в ближайших релизах.

**Comment by jakeqwert** [comment]
Метод Send(), если отправляем с файлом вложением должен возвращать Document, чтобы определить id отправленного доп соглашения к приглашению

**Comment by jakeqwert** [comment]
А на текущий момент он ничего не возвращает, а как же узнать тогда вообще отправлено ли приглашении или нет и что оно подписано было покупателем
