### ISSUE TITLE
Не подписывается УПД в форме приказа 820 со стороны Покупателя

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#360]
При подписании документа в форме 820 приказа Покупателем:

https://diadoc.kontur.ru/7f648ced-4718-4958-884e-02dac0220d4a/Document/Show?letterId=6dcb01af-a7b1-4ee1-ac8a-47d2bd2aa132&documentId=0111dc33-fa57-4acd-b4c2-4a8f4d8649d1

![Pic 1](https://user-images.githubusercontent.com/22831210/64862535-cf43f100-d643-11e9-8469-74df45039cd5.jpg)
![Pic 2](https://user-images.githubusercontent.com/22831210/64862780-6b6df800-d644-11e9-9b5b-e1bc9c8ec8ba.jpg)

Возникает ошибка:

Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalTransferDocumentBuyerTitle/Signers/SignerReference: @Inn is required
/UniversalTransferDocumentBuyerTitle/Signers/SignerReference: SignerDetails not found for boxId=7f648ced-4718-4958-884e-02dac0220d4a, thumbprint=A5657837F9A0B8CEB65BCACC6B3D72F57BF2DC95, d

Я так понимаю, это связано с областью полномочий пользователя?
Ранее похожее было с подписанием документа в форме приказа 552.
Настраивал программно:

SetExtendedSignerDetailsTask = Organization.CreateSetExtendedSignerDetailsTask(ПараметрыСоединения.ОтпечатокСертификата);
					
SetExtendedSignerDetailsTask.IsSeller = Ложь;
SetExtendedSignerDetailsTask.ForCorrection = Истина;
SetExtendedSignerDetailsTask.DocumentTitleType = "AccCert552Buyer";
					
ДанныеПодписанта = SetExtendedSignerDetailsTask.ExtendedSignerDetailsToPost;
ДанныеПодписанта.SignerType = ?(Выборка.Покупатель.Статус = Перечисления.СтатусКонтрагента.ЮрЛицо, "LegalEntity", "IndividualEntity");
ДанныеПодписанта.Powers = "MadeAndSignOperation";
					
SetExtendedSignerDetailsTask.Send();

Про 820 приказ в хелпе ничего не нашел.
Подскажите как быть.

**Comment by azhipaigor** [comment]
Действительно в документации не было. Добавил. Все точно так-же, как для 552, только тип [Utd820Buyer](http://1c-docs.diadoc.ru/ru/latest/ComObjects/SetExtendedSignerDetailsTask.html#setextendedsignerdetailstask-titletype).
