### ISSUE TITLE
Из 1С (AddIn) при Document.SaveAllContentZip(Путь) ошибка: Произошла исключительная ситуация (DocumentBase.SaveAllContentZip): Ошибка открытия файла

### ISSUE THREAD

**Issue by BPivo** [diadoc/diadocsdk-1c-docs#361]
Из 1С пытаюсь сохранить архив, содержащий все файлы, относящиеся к документу. Возникает ошибка: "Ошибка открытия файла".
Если выполняю Document.SaveAllContent(Путь), то сохраняются файлы в указанный каталог без ошибок.
Почему возникает ошибка?
Работаю в 1С через AddIn

**Comment by BPivo** [comment]
Разобрался. 
Оказывается нужно в параметре SaveAllContentZip() прописать полный путь к уже имеющемуся zip-файлу (например, "c:\test\alldoc.zip"). Т.е. файл alldoc.zip уже должен быть по указанному пути к моменту вызова SaveAllContentZip().

**Comment by azhipaigor** [comment]
Да, верно, для SaveAllContentZip нужно указывать полный путь до файла. Но файл по этому пути может и не существовать, тогда он будет создан.

**Comment by BPivo** [comment]
Первоначально я так и делал: в качестве параметра указывал полный путь до файла (как и в методе "SaveAllContent()". Появлялась ошибка открытия файла. Файл zip не хотел создаваться.

Но когда я _создал_ пустой zip файл и указал его в параметре, тогда все прошло успешно.

**Comment by azhipaigor** [comment]
Проверил на 5.28.6.502 - не воспроизводится. Скорее всего какая-то путаница в путях. Для SaveAllContent нужно указывать путь до директории в которую будут сохранены файлы, имена файлов компонента генерирует сама. Для SaveAllContentZip полный путь до файла.

**Comment by BPivo** [comment]
у Вас 5.28.6.502 32-х или 64-х? Не знаю насчет путаницы... переменную, которую использую в качестве пути, использую одну. К переменной добавляется имя файла. Или не добавляется. Выдает вышеописанную ошибку. 1.5 дня мучился, искал причину. Но как только руками создал zip-файл, все получилось, 
Могу Вам выслать пример моей обработки, Вы скажете где ошибка. Только скажите адрес.

**Comment by GilimkhanovDenis** [comment]
Описанное вами поведение было в одном из предыдущих релизов. Проверьте, что у вас не осталась где-то зарегистрированна старая компонента

Разрегистрировать компоненту можно командой командной строки regsvr32.
После её выполнения в реестре не должно остаться зарегистрированных веток реестра с именами объектов компоненты.

**Comment by BPivo** [comment]
Я работаю через AddIn. Вот код 1С:
ИмяФайла = "E:\WRK\Diadoc_5_28_6_502_x64.dll";
ЗагрузитьВнешнююКомпоненту(ИмяФайла);
DiadocApi_ = Новый("AddIn.DiadocInvoiceAPI");
DiadocApi  = DiadocApi_.CreateObject();
...
DiadocConnection = DiadocApi.CreateConnectionByLogin(Логин, Пароль);

**Comment by kulakovskaya** [comment]
Добрый день! Рекомендуем обратиться в техподдержку для перерегистрации компоненты. 
Телефон техподдержки: 8 800 500-10-18

**Comment by BPivo** [comment]
В каком смысле "для перерегистрации компоненты"? Получается, что проблема в dll-ке?

**Comment by kulakovskaya** [comment]
Как говорилось выше, описанное вами поведение было в одном из предыдущих релизов компоненты. Возможно, что у вас осталась где-то зарегистрированная старая версия компоненты. Необходимо проверить данное предположение и далее предлагать варианты решения.

**Comment by Dilise** [comment]
Боремся с подобной проблемой уже некоторое время.
Проблема скорее всего в том, что винда не поддерживает файлы с полным путем более 260 символов. Если сохранение происходит в папку темп, а она где нибудь закопана не в корне диска, то данная ошибка имеет место быть. Хотелось бы обратиться с просьбой об устранении данной проблемы к разработчикам компоненты. Версия компоненты 5.28.8.523

**Comment by GilimkhanovDenis** [comment]
Windows API поддерживает работу с путями с длиной больше 260 символов (см. https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation)
Компонента использует длинные пути

**Comment by Dilise** [comment]
Если я правильно понял, нужно в SaveAllContent передать путь начинающийся с "\\?\" и длинные пути на будут критовать. Спасибо, попробую завтра.
