### ISSUE TITLE
utd820_05_01_01_hyphen

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#362]
Добрый день.
По адресу http://api-docs.diadoc.ru/ru/latest/docflows/AttachmentVersion.html определены возможные версии документов. В частности - utd820_05_01_01 для УПД.
А у меня Version документа a53a3269-b987-4348-b09c-88e5a1ba5158a0ac0b73-4d89-44dc-b975-b35ed04c094a возвращает utd820_05_01_01_hyphen. Что это?

**Comment by NataliaShumikhina** [comment]
Добрый день! Для документов в 820 формате была добавлена новая версия utd820_05_01_01. Подробнее можно прочитать в новости на нашем сайте https://www.diadoc.ru/blog/7883

**Comment by prog22** [comment]
В новости написано: "Если при отправке документа в формате 820 не указать версию, то документ будет отправлен в новой версии utd820_05_01_01_hyphen".

Я создаю задание на отправку так: 
DocumentToSend1 = SendTask.AddDocument("UniversalTransferDocument", ФункцияДокумента, "utd820_05_01_01") и получаю Version = utd820_05_01_01_hyphen.

Нужно в AddDocument передавать utd820_05_01_01_hyphen?

**Comment by GilimkhanovDenis** [comment]
Исправлено в релизе 5.28.7
