### ISSUE TITLE
Иные сведения

### ISSUE THREAD

**Issue by veraItplatforma** [diadoc/diadocsdk-1c-docs#363]
Добрый день.
Какое свойство или метод использовать для получения поля - Иные сведения. В печатной форме УПД (Товар (груз) передал / услуги, результаты работ, права сдал) оно также выводится.

Планируем его в документ записывать.

**Comment by IrinaShmonina** [comment]
Добрый день.
1. Я правильно понимаю, что речь про исходящие документы?
2. С каким форматом вы работаете? 155 или 820?

**Comment by veraItplatforma** [comment]
Добрый день.
Версия модуля UF.5.35.08.184, Версия платформы 1С 8.3.13.1513
1. Входящие документы. Получаем их от контрагента. Хотели бы обращаться к этому полю и записывать его в свое поле.
2. Где посмотреть формат?

**Comment by aeremina88** [comment]
Добрый день!
В компоненте это [AdditionalInfoId](http://1c-docs.diadoc.ru/ru/latest/ComObjects/AdditionalInfoId.html)
Рекомендуем использовать [подключаемый модуль](https://wiki.diadoc.ru/pages/viewpage.action?pageId=7668852), чтобы не вносить доработки в основной модуль. Для обработки входящего документа можно использовать событие _ПослеЗаполненияНовогоДокументаПоступления_ .
