### ISSUE TITLE
В два с лишним раза более медленное получение данных с помощью "нового" GetDynamicContent() по сравнению со "старым" GetContent()

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#364]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ 5.28.6.502.

При реализации работы с "новым" **GetDynamicContent()** показалось, что он как-то очень уж медленно работает. Но оказалось - не показалось!

Специально были написаны небольшие тесты с помощью которых были проведены затраты времени на получение контента отправителя "старым" **GetContent()** и "новым" **GetDynamicContent()**.

**Замерялось "чистое" время только на вызов соответствующих функций для одного и того же списка документов.**

Результаты прогона тестов:

**Прогон 1**
Получение данных: Контент отправителя
Чистое время: 210,0770 сек.
Обработано документов: 500 шт. Документов в секунду: **2,3801** шт.

Получение данных: Контент отправителя (**динамический**)
Чистое время: 609,1280 сек.
Обработано документов: 500 шт. Документов в секунду: **0,8208** шт.

**Прогон 2**
Получение данных: Контент отправителя
Чистое время: 201,4030 сек.
Обработано документов: 500 шт. Документов в секунду: **2,4826** шт.

Получение данных: Контент отправителя (**динамический**)
Чистое время: 492,7910 сек.
Обработано документов: 500 шт. Документов в секунду: **1,0146** шт.

**Прогон 3**
Получение данных: Контент отправителя
Чистое время: 207,3960 сек.
Обработано документов: 500 шт. Документов в секунду: **2,4108** шт.

Получение данных: Контент отправителя (**динамический**)
Чистое время: 499,1590 сек.
Обработано документов: 500 шт. Документов в секунду: **1,0017** шт.

**Прогон 4 (документов в 3 раза больше)**
Получение данных: Контент отправителя
Чистое время: 633,4970 сек.
Обработано документов: 1500 шт. Документов в секунду: **2,3678** шт.

Получение данных: Контент отправителя (**динамический**)
Чистое время: 1448,7070 сек.
Обработано документов: 1500 шт. Документов в секунду: **1,0354** шт.

Понятно, что это усредненные данные полученные с некой долей погрешности.
Но тем не менее, отчетливо видно, что "старый" метод, который получает правильно типизированные данные (в которых дата - это дата, число - это число и т.п.) по сравнению с "новым" методом (который получает все типы данных в виде строк) работает **БОЛЕЕ ЧЕМ В ДВА РАЗА БЫСТРЕЕ!!!**

Или, скажем по другому:
### "Новый" **GetDynamicContent()** получает данные **в ~2.3 раза МЕДЛЕННЕЕ** чем "старый" **GetContent()**

Такое обновление АПИ выглядит очень странным. Новая версия, по сути, работает намного медленнее (хуже) старой!

Это, скажем так, информация для размышления. Вдруг вы как-то не заметили, что новый функционал в два с лишним раза медленнее...

**Вопросы:**
1. А с чем связано такое замедление? Может у вас там какие-то ошибки или недоработки, приводящие к такому существенному замедлению в получении данных?
3. Будет ли это как-то исправляться/оптимизироваться? Стоит ли надеяться на улучшение ситуации со скоростью получения данные через **GetDynamicContent()**? 

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Проверьте работу метода на версии компоненты 5.28.8

**Comment by JohnSergeev** [comment]
Добрый день.

Проверил "по-быстрому".

Стало намного лучше! Теперь даже быстрее, чем старый вариант. Примерно на 20%.

Прогон №1

Получение данных: Контент отправителя
Полное время: 315,9230 сек.
Чистое время: 211,4860 сек.
Обработано документов: 500 шт. Документов в секунду: **2,3642** шт.

Получение данных: Контент отправителя (**динамический**)
Полное время: 268,9170 сек.
Чистое время: 175,6110 сек.
Обработано документов: 500 шт. Документов в секунду: **2,8472** шт.

Прогон №2

Получение данных: Контент отправителя
Полное время: 556,0860 сек.
Чистое время: 386,0470 сек.
Обработано документов: 1000 шт. Документов в секунду: **2,5904** шт.

Получение данных: Контент отправителя (**динамический**)
Полное время: 482,5920 сек.
Чистое время: 314,7550 сек.
Обработано документов: 1000 шт. Документов в секунду: **3,1771** шт.
