### ISSUE TITLE
Изменения в связи с переходом на формат по 820 приказу

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#365]
Добрый день! Планируются ли новые версии компоненты в связи с обязательным форматом УПД по 820 приказу ФНС с 1 января?

**Comment by IrinaShmonina** [comment]
Добрый день,
компонента уже поддержала работу с 820 форматом с версии 5.27.0. Рекомендуем обновляться на последнюю версию.

**Comment by GuninaY** [comment]
Мы уже на 5.28. Подскажите, а методы оставить прежние? Отправляем мы УПД и УКД, через PackageSendTask = Organization.CreatePackageSendTask();
Далее добавляем документ DocumentToSend = PackageSendTask.AddDocument("UniversalTransferDocument") либо DocumentToSend = PackageSendTask.AddDocument("UniversalCorrectionDocument");

**Comment by IrinaShmonina** [comment]
Для отправки 820 формата нужно использовать [PackageSendTask2](http://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html#packagesendtask2).
Пример использования можно посмотреть в [инструкции](http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html)

**Comment by GuninaY** [comment]
Спасибо!
