### ISSUE TITLE
Подписание входящего документа

### ISSUE THREAD

**Issue by regfor1c** [diadoc/diadocsdk-1c-docs#366]
Всем привет,
подскажите, как правильно заполнить ответ. 
Читаю документацию и пытаюсь подписать документ но понятий много, а опыта работать с API мало.
Прочитал что надо использовать 
Document.CreateReplySendTask2("AcceptDocument");

Далее получаю 
ContentItem = ReplySendTask.ContentItems.GetItem(ц);
Далее надо заполнить 
ContentItem.Content.UniversalTransferDocumentBuyerTitle
Как это сделать? Может есть пример?
В документации написано, что надо использовать DinamicComtent, так и не понял что это.
Задача состоит в том, чтобы сформировать правильный ответ и подписать документ.
Но пока не получается.

**Comment by IrinaShmonina** [comment]
Здравствуйте,
Есть пример в документации. [Как выполнить ответные действия по документам](http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_reply_document.html)

**Comment by regfor1c** [comment]
Ирина, спасибо за ответ, это я видел. Только там написано вот так
            // Предполагаем, что есть функции заполнения контента второго титула формализованных документов
            Заполнить_DynamicContent(ContentItem.Content);
У меня нет этой функции и сложность вызвало у меня  раз создание этой функции. Как заполнить структуры, например Signer? Структура, в ней еще структура .....

**Comment by kulakovskaya** [comment]
Работа с DynamicContent не отличается от работы с другими COM-объектами. 
Описание полей, которые необходимо заполнить для Signer можно получить из XSD, получаемой методами Organization.SaveUserDataXSD(), Organization.GetBase64UserDataXSD(), или, используя объект Reflector.
http://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html

**Comment by regfor1c** [comment]
А как надо вызывать Organization.SaveUserDataXSD()?
Я делаю и у меня ошибка
{(1)}: Ошибка при вызове метода контекста (SaveUserDataXSD)

Пробовал использовать Reflector, но опять же не работает, скорее всего я что то не так делаю.
беру вот этот пример и делаю по аналогии
http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_reflect_object.html

Делаю вызов
//Создание Reflector'а
	ReflectorObj = Новый ComОбъект("Diadoc.DiadocClient.Reflector");


Получаю вот такую ошибку
-2147221005(0x800401F3): Недопустимая строка с указанием класса 
{ВнешняяОбработка.ЗапускКомпоненты.Форма.Форма.Форма(47)}:	ReflectorObj = Новый ComОбъект("Diadoc.DiadocClient.Reflector");
{ВнешняяОбработка.ЗапускКомпоненты.Форма.Форма.Форма(37)}:	Команда3НаСервере();

по причине:
-2147221005(0x800401F3): Недопустимая строка с указанием класса

**Comment by GilimkhanovDenis** [comment]
В примере имя объекта рефлектора "AddIn.Diadoc.Reflector", а не "Diadoc.DiadocClient.Reflector". В COM варианте "Diadoc.Reflector"
а у метода SaveUserDataXSD интерфейс другой. см. [документацию](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.SaveUserDataXSD)

**Comment by regfor1c** [comment]
Спасибо за ответ, но не срабатывает
1.	//ReflectorObj = Новый ComОбъект("Diadoc.Reflector");

2.	ReflectorObj = Новый ComОбъект("Diadoc.DiadocClient");

1 вариант выдает ошибку
-2147221005(0x800401F3): Недопустимая строка с указанием класса 

2. Находит и создает COM объект

Что я не так делаю?

**Comment by GilimkhanovDenis** [comment]
Проверьте, что компонента зарегистрировалась и это компонента последней версии (см. [GetVersion()](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html#diadocapi-getversion))

Попробуйте перерегистрировать компоненту (при разрегистрации в реестре не должно остаться веток с именами содержащими "Diadoc")

**Comment by regfor1c** [comment]
Поставил последнюю версию компоненты, рефлектор сработал, только что он показывает и как им плодотворно пользоваться узнаю позже. Сейчас интересует следующий момент.
Выполняю следующий код, который заполняет поля, которые требуются.
Если Document.Version = "utd820_05_01_01_hyphen" Тогда
	ReplySendTask = Document.CreateReplySendTask2("AcceptDocument");			
	ContentItems = ReplySendTask.ContentItems;				
	Для Каждого Item Из ContentItems Цикл
		Content	= Item.Content;
		Если Content.HasProperty("UniversalTransferDocumentBuyerTitle") Тогда
			Content.UniversalTransferDocumentBuyerTitle.DocumentCreator =Organization.Name;
			Content.UniversalTransferDocumentBuyerTitle.OperationContent = "Товары принял без претензий";
		Signers = Content.UniversalTransferDocumentBuyerTitle.Signers;				
		NewSigner = Signers.AddItems();
		SignerDetails = NewSigner.SignerDetails;
		SignerDetails.FirstName = "Иван";
		SignerDetails.LastName = "Иванов";
		SignerDetails.SignerType = "1";
		SignerDetails.SignerPowers = "1";
		SignerDetails.SignerStatus ="4";
		SignerDetails.Inn = Organization.INN;
		SignerDetails.SignerPowersBase = Organization.Certificate.JobTitle;
        КонецЦикла;
КонецЕсли;
ReplySendTask.Send(); //Пытаюсь отправить подтверждение и получаю вот такую ошибку.

Validation errors: Location: Line: 14, Position: 30, /Файл[1]/ИнфПок[1]/Подписант[1]/ЮЛ[1]/@Должн, Message: The 'Должн' attribute is invalid - The value '' is invalid according to its datatype 'String' - The actual length is less than the MinLength value.
Не удалось выполнить операцию утверждения / отклонения!

Не могу понять где этот "Должн", что за поле, по описанию в схеме его нет. Это поле не заполнено у контрагента получается?

**Comment by GilimkhanovDenis** [comment]
Заполните SignerDetails.Position
