### ISSUE TITLE
Помогите заполнить  TaxRate

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#369]
Добрый день! Отправляю УПД с помощью:
 DocumentToSend = PackageSendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01_hyphen");			
Content = DocumentToSend.content.UniversalTransferDocumentWithHyphens; 
Item = Content.Table.AddItem();
Пытаюсь заполнить Item.TaxRate, ничего не выходит, ругается на несоответствие типов Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 4, Position: 148, /UniversalTransferDocumentWithHyphens[1]/Table[1]/Item[1]/@TaxRate: The 'TaxRate' attribute is invalid - The value 'Percent_20' is invalid according to its datatype 'TaxRateWithTwentyPercentAndTaxedByAgent' - The Enumeration constraint failed.
Подскажите, как верно?

**Comment by GilimkhanovDenis** [comment]
По XSD тип "TaxRateWithTwentyPercentAndTaxedByAgent" - одно из значений списка

`<xs:simpleType name="TaxRateWithTwentyPercentAndTaxedByAgent">
    <xs:restriction base="xs:string">
      <xs:enumeration value="без НДС" />
      <xs:enumeration value="0%" />
      <xs:enumeration value="10%" />
      <xs:enumeration value="18%" />
      <xs:enumeration value="20%" />
      <xs:enumeration value="10/110" />
      <xs:enumeration value="18/118" />
      <xs:enumeration value="20/120" />
      <xs:enumeration value="НДС исчисляется налоговым агентом" />
    </xs:restriction>
  </xs:simpleType>`

То есть ставку в 20% надо писать как "20%"

**Comment by GuninaY** [comment]
Спасибо, а где можно посмотреть эту схему? а то у меня какая то другая https://www.diadoc.ru/blog/7883

**Comment by GilimkhanovDenis** [comment]
Схему можно получить методом [Organization.SaveUserDataXSD(....)](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.SaveUserDataXSD)
В вашем случае вызов метода выглядит так:
`dd_Organization.SaveUserDataXSD("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01_hyphen", "Seller", "ПолноеИмяФайлаВКоторыйСохранитьСхему.xml");`

**Comment by GilimkhanovDenis** [comment]
В блоге, похоже, та же XSD лежит

В XSD написано следующее:
**Cтрока 543**: `<xs:attribute name="TaxRate" type="TaxRateWithTwentyPercentAndTaxedByAgent" use="required">
`
Обязательное поле TaxRate. тип - "TaxRateWithTwentyPercentAndTaxedByAgent"

Описание типа "TaxRateWithTwentyPercentAndTaxedByAgent" находится в **строке 1253**
