### ISSUE TITLE
Не всегда находится контрагент через метод GetCounteragentListByInnKpp

### ISSUE THREAD

**Issue by AdrianBerk** [diadoc/diadocsdk-1c-docs#37]
Добрый день!
Довольно часто сталкиваемся с  тем что метод получения контрагента по инн кпп не всегда получает нужного контрагента, хотя на сайте самом он отображается.
Пробовали получать как  с  заполненным КПП, так и   без.
Данные получаем через API, версия библиотеки 5.7.3.135

Как в  данном случае нам пригласить этого контрагента к  сотрудничеству, используя API?

![2016-11-08_13-12-10](https://cloud.githubusercontent.com/assets/7655854/20133321/297ab8b0-a678-11e6-9e4d-c64897ebceba.png)
![2016-11-08_13-10-56](https://cloud.githubusercontent.com/assets/7655854/20133322/297cffbc-a678-11e6-92ed-33e2e42943c1.png)

**Comment by volodkindv** [comment]
Добрый день!
Данного контрагента действительно нет в Диадоке.
Информация на приложенном скриншоте берется из другого сервиса - "Контур.Фокус" (https://focus.kontur.ru/)

**Comment by AdrianBerk** [comment]
У пользователей возникает некоторый диссонанс... Спрашивают: "Ну как же так, с  сайта мы такого пользователя можем заранее пригласить к  обмену документами, а  программно нет?". Интересно, а  если такого пользователя приглашают с  сайта, то потом как только он регистрируется в  Диадок - он получает приглашение, отправленное ранее?

**Comment by denver069** [comment]
Пригласить контрагента которого нет в Диадоке возможно. Для этого в [задании для отправки приглашения](http://diadocsdk-1c.readthedocs.io/ru/latest/AcquireCounteragentTask.html) вместо CounteragentBoxId необходимо заполнить поле Inn. В таком случае ящик контрагента будет создан автоматически и в нем будут копится приглашения к обмену.
