### ISSUE TITLE
Обязатеьно ли заполнять Carrier?

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#370]
Добрый день! Переделываю на 820 формат УПД. У меня почему то не хочет оправляться без указания перевозчика, хотя он вроде бы необязательный. Если заполняю все данные по перевозчику, то отправляется.  Ругается: произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 45, Position: 25, /UniversalTransferDocumentWithHyphens[1]/TransferInfo[1]/Carrier[1]/OrganizationDetails[1]/@OrgType: The 'OrgType' attribute is invalid - The value '' is invalid according to its datatype 'OrganizationType' - The Enumeration constraint failed.
Как нужно заполнять, чтоб обойтись без него?

**Comment by volodkindv** [comment]
Добрый день.
Покажите, пожалуйста, ваш код для заполнения TransferInfo.
Возможно, вы добавили Carrier, но не до конца заполнили его. Правильнее будет вообще не добавлять Carrier.

**Comment by GuninaY** [comment]
Content.TransferInfo.OperationInfo = "Результаты работ переданы (услуги оказаны)"; 			
Content.TransferInfo.TransferDate  = Формат( ТекущаяДата(),"ДФ=dd.MM.yyyy");

TransferBasesItem = Content.TransferInfo.TransferBases.AddTransferBase();
TransferBasesItem.BaseDocumentName = "Договор";
TransferBasesItem.BaseDocumentNumber =  реализация.ДоговорКонтрагента.Номер;			
TransferBasesItem.BaseDocumentDate  =реализация.ДоговорКонтрагента.Дата;			
TransferBasesItem.BaseDocumentInfo  = "Срок оплаты ";	
					
Content.TransferInfo.TransferTextInfo  ="Доверенность № ";

**Comment by GuninaY** [comment]
также ругается если на заполняю Factor = Content.FactorInfo.OrganizationDetails

**Comment by GilimkhanovDenis** [comment]
Попробуйте отправить через компоненту 5.28.8

**Comment by GuninaY** [comment]
А не подскажите где? Качаю отсюда https://diadoc-api.kontur.ru/1c-addin/Diadoc_latest.zip. Там вроде еще 5.28.7

**Comment by kulakovskaya** [comment]
По данной ссылке скачивается актуальная версия компоненты 5.28.8

**Comment by GuninaY** [comment]
Ошибка сохраняется Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 18, Position: 25, /UniversalTransferDocumentWithHyphens[1]/TransferInfo[1]/Carrier[1]/OrganizationDetails[1]/@OrgType: The 'OrgType' attribute is invalid - The value '' is invalid according to its datatype 'OrganizationType' - The Enumeration constraint failed.
Версия 5.28.7.513

**Comment by GuninaY** [comment]
Может быть не обновили версию компоненты?
