### ISSUE TITLE
Работа с шаблонами

### ISSUE THREAD

**Issue by OdintsovSergey** [diadoc/diadocsdk-1c-docs#371]
Добрый день.

Просьба сообщить появилась ли возможность получать информацию о входящих шаблонах через события или еще как-то узнать, что поступили новые шаблоны.
Если такой функционал не реализован, то просьба сообщить когда он будет реализован.

**Comment by IrinaShmonina** [comment]
Добрый день,
компонента не умеет работать с входящими шаблонами.

Можете оставить пожелание техподдержке. На сайте Диадока есть 3 способа связаться с нашей технической поддержкой. https://www.diadoc.ru/support

Либо обратиться к менеджеру, с которым вы работаете.
