### ISSUE TITLE
Получение даты подписи документа

### ISSUE THREAD

**Issue by derxyz** [diadoc/diadocsdk-1c-docs#372]
Добрый день!
 
Ситуация такая: используется COM-компонента версии 5_28_8_523, взял уже последнюю.
 
Документ получен с помощью функции GetDocumentById()
 
Статус документа OutboundWithRecipientSignature - Подписан контрагентом
 
При вызове doc.GetRecipientSignature() возвращается Неопределено
 
Хотя при вызове doc.GetSenderSignature() возвращается нормальное представление подписи с полями Certificate, SignDate, SignatureAuthenticityDate
 
Как получить дату подписи со стороны контрагента?

**Comment by volodkindv** [comment]
Добрый день.
Дайте ссылку на документ или укажите boxId и documentId.

**Comment by derxyz** [comment]
Добрый день! 4c736bbc-e218-45de-a0e8-a4368a021b8d6cae67c1-42a1-4fa1-81a5-f52d230e815b -- С уважением,Кочнев Александр   23.10.2019, 13:04, "Данила Володькин" <notifications@github.com>:Добрый день.Дайте ссылку на документ или укажите boxId и documentId.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by volodkindv** [comment]
Нужен еще boxid, без него мы не сможем ничего понять.

**Comment by derxyz** [comment]
Подскажите, пожалуйста, что за boxid? Это id организации? -- С уважением,Кочнев Александр   23.10.2019, 13:26, "Данила Володькин" <notifications@github.com>:Нужен еще boxid, без него мы не сможем ничего понять.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by volodkindv** [comment]
Да, это ID организации.
Или можете просто приложить ссылку на сам документ в вебе Диадока, там в URL присутствует boxId и documentId.

**Comment by derxyz** [comment]
https://diadoc.kontur.ru/81f373b7-848f-4c68-a07c-95e739b1852a/Document/Show?letterId=4c736bbc-e218-45de-a0e8-a4368a021b8d&documentId=6cae67c1-42a1-4fa1-81a5-f52d230e815b -- С уважением,Кочнев Александр   23.10.2019, 13:55, "Данила Володькин" <notifications@github.com>:Да, это ID организации.Или можете просто приложить ссылку на сам документ в вебе Диадока, там в URL присутствует boxId и documentId.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by derxyz** [comment]
Добрый день!
Есть ли какая-нибудь информация по данной проблеме?

**Comment by kulakovskaya** [comment]
Добрый день! Рекомендуем перерегистрировать компоненту.
При возникновении вопрос обратитесь в техподдержку по телефону 8 800 500-10-18.
