### ISSUE TITLE
Ошибка при заполнении Seller.OrganizationReference.OrgType, COM 64 бит 5.28.8.523

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#373]
Seller = Content.Sellers.AddSeller();
	Seller.OrganizationReference.BoxId = Организация_boxId;

	//1 - Сведения о юридическом лице, состоящем на учете в налоговых органах // СвЮЛУч
	//2 - Сведения об индивидуальном предпринимателе// СвИП
	//3 - Сведения об иностранном лице, не состоящем на учете в налоговых органах // СвЮлНеУч, СвИнНеУч
	//4 - Сведения о физическом лице // СвФл
	Seller.OrganizationReference.OrgType = "1";

Ошибка:
Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 25, Position: 27, /UniversalTransferDocumentWithHyphens[1]/Buyers[1]/Buyer[1]/OrganizationReference[1]/@OrgType: The 'OrgType' attribute is invalid - The value '' is invalid according to its datatype 'OrganizationType' - The Enumeration constraint failed.
Line:

По факту заполняю значением типа строка = "1", но выходит ошибка. Прошу указать, моя ли ошибка или компоненты COM 64 бит 5.28.8.523

**Comment by GilimkhanovDenis** [comment]
Добрый день.
В ошибке речь идёт о Buyer'е, а не Seller'е - проверьте заполнение Buyer'а

**Comment by geron4** [comment]
Действительно, это моя не внимательность, спасибо за помощь.
