### ISSUE TITLE
Вопрос по оформлению шапки формализованного акта // PackageSendTask2

### ISSUE THREAD

**Issue by Fibba** [diadoc/diadocsdk-1c-docs#374]
Добрый день. Пытаемся переучить наше интеграционное решение на PackageSendTask2 и нам необходимо, чтоб в шапке формализованных актов был наш текст.

При использовании старого SendTask для объекта типа XmlAcceptanceCertificate мы использовали реквизит контента Title, для объекта типа XmlAcceptanceCertificate552 - OperationTitle.

Сейчас мы добавляем документ в пакет вот таким образом:
PackageSendTask2 = Organization.CreatePackageSendTask2();
DocumentToSend=		PackageSendTask2.AddDocument("XmlAcceptanceCertificate","default","utd_05_02_01");

и заполняем полученный DocumentToSend.Content.UniversalTransferDocument

В какой из реквизитов DocumentToSend нам записать наш текст, чтоб он визуализировался в шапке акта вот тут?
![image](https://user-images.githubusercontent.com/42743750/68376407-9e6ecc80-0159-11ea-8f74-ca33b5e44bed.png)

**Comment by kulakovskaya** [comment]
Добрый день!
При использовании  SendTask Вы работали с объектом типа XmlAcceptanceCertificate552 - Акт в формате приказа ММВ-7-10/552@, в котором предусмотрено заполнение поля OperationTitle.
Для документа типа PackageSendTask2.AddDocument("XmlAcceptanceCertificate","default","utd_05_02_01") согласно формату приказа ФНС от 24.03.2016 № ММВ-7-15/155@ это поле отсутствует.

**Comment by Fibba** [comment]
Хорошо, я для документа, соответствующего 820 приказу такое поле имеется? (ещё им не занимались, хотелось бы заранее знать)

**Comment by kulakovskaya** [comment]
Для документа в формате 820 приказа тоже нельзя разместить произвольный текст в шапке. 
Если Вам требуется определенное заполнение, Вы можете обратиться к Вашему менеджеру или в техподдержку https://www.diadoc.ru/support для подключения персонализированной кастомной печатной формы.

**Comment by Fibba** [comment]
Спасибо за ответ.
