### ISSUE TITLE
Входящий документ PDF не попадает в DocumentsTask

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#376]
Отбираю документы DocumentsTask.Category = "Any.InboundNotFinished"; почему то документ https://diadoc.kontur.ru/54d0b467-aade-47d6-8136-a2bbe2eeb67d/Document/Show?letterId=20813a5d-d351-417d-98ab-aea2bbd46fda&documentId=7309b4ef-c8e7-48d4-a784-79ac559ec068 не попадает в этот список. Подскажите в чем дело?

**Comment by GuninaY** [comment]
Title ведь у этого документа должен быть Накладная 5547 от 30.10.2019 ?

**Comment by GilimkhanovDenis** [comment]
Добрый вечер.

поле Title у этого документа "**Накладная 5547 от 30.10.2019 .pdf**". Обратите внимание, что перед ".pdf" стоит пробел

**Comment by GuninaY** [comment]
ага, ну поиск по Title  я не использую, это я просто смотрела всю таблицу, которую мне возвращает DocumentsTask.  Данный документ должен попадать в категорию Any.InboundNotFinished?

**Comment by GilimkhanovDenis** [comment]
Кроме категории, другие параметры поиска задаёте? если да, то какие?

Другие Nonformalized документы с незавершённым документооборотом в коллекции возвращаются?

Проверил работу метода только с установкой категории Any.InboundNotFinished без каких-либо других параметров и такие документы были в коллекции

**Comment by GuninaY** [comment]
Есть еще отбор по датам DocumentsTask.FromDocumentDate  = НачПериода;
	DocumentsTask.ToDocumentDate = КонПериода; С границами все в порядке. Неформализованные тоже попадают, например
https://diadoc.kontur.ru/54d0b467-aade-47d6-8136-a2bbe2eeb67d/Document/Show?letterId=edf5e74d-d446-4db7-8d01-b3276410df4a&documentId=016d1f3c-ed82-4414-9df4-8c642156bd9e

**Comment by GilimkhanovDenis** [comment]
Так как документ передан как Nonformalized, то у него просто нет даты документа. Поэтому в фильтр не попадает
альтернативой дате документа могут выступать поля FromSendDate, ToSendDate - дата отправки документа

**Comment by GuninaY** [comment]
Спасибо, так все вы получилось!
