### ISSUE TITLE
Исправительная счет-фактура

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#377]
Добрый день! Бухгалтерия хочет в некоторых случаях отправлять Исправительный счет-фактуру на УПД. Есть ли такая возможность или можно только создать Исправительный УПД? Если возможно, то с помощью какого метода мне это сделать? Пробую так:
PackageSendTask = Organization.CreatePackageSendTask2();
DocumentToSend = PackageSendTask.AddDocument("InvoiceRevision","КСЧФ","invoice_05_01_03");
не ясно как заполнять версию и работает ли вообще CreatePackageSendTask2() для такого вида документа?

**Comment by volodkindv** [comment]
Добрый день.
Чтобы понять, какие параметры передавать в CreatePackageSendTask2(), вызовите Organization.[GetDocumentTypes](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetDocumentTypes)().

Дальше смотрите, какие параметры для Function и Version доступны:
![image](https://user-images.githubusercontent.com/12305552/69226156-8491a880-0ba1-11ea-9f58-7e5dd75c19b3.png)

**Comment by GuninaY** [comment]
Спасибо!
