### ISSUE TITLE
Пример работы с динамическим контентом

### ISSUE THREAD

**Issue by sergeb72** [diadoc/diadocsdk-1c-docs#378]
Здравствуйте.
Установлена COM компонента v5.29.1.530 для произвольных систем.

Решили попробовать работу с динамическим контентом, скопировали с примера на странице https://diadocsdk-1c.readthedocs.io/ru/latest/ComObjects/DynamicContent.html первые 4 строки кода.
При попытке обращения к DynamicContent.UniversalTransferDocument возникает ошибка (Excel VBA):
> "Object doesn't support this property or  method"

или (Delphi):
> Project DiadocTest.exe raised exception class EOleSysError with message 'Член группы не найден'.

Вот, например, попытка в макросе Excel:
```
Sub qq()
    Set DiadocAPI = CreateObject("Diadoc.DiadocClient")
    DiadocAPI.ApiClientId = "..."
    DiadocAPI.ServerUrl = "https://diadoc-api.kontur.ru"
    Set DiadocConnection = DiadocAPI.CreateConnectionByLogin("...", "...")
    Set Organization = DiadocConnection.GetOrganizationById("...")

    Set SendTask = Organization.CreatePackageSendTask2()
    Set DocumentToSend = SendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01")
    Set DynamicContent = DocumentToSend.Content
    Set Utd820_SellerContent = DynamicContent.UniversalTransferDocument
End Sub
```
В чём наша ошибка?

**Comment by GilimkhanovDenis** [comment]
Добрый день
Какую версию Delphi используете? Borland Delphi 7 ?

**Comment by sergeb72** [comment]
Delphi XE2

**Comment by sergeb72** [comment]
Собственно, у нас задача перейти на динамический контент именно в Delphi.
Получив ошибку, решили попробовать код в Excel VBA, там тоже пример из документации не выполнился.

**Comment by GilimkhanovDenis** [comment]
В понедельник будет релиз с фиксом

**Comment by sergeb72** [comment]
Кстати, попутно про PackageSendtTask2.Send():

> "Если отправка пакета с заполненным OperationId завершилась успехом, то все остальные попытки отправки с тем же идентификатором не будут приводить к отправке нового пакета, а в результате выполнения метода вернется ранее отправленный пакет"

Если OperationId совсем не заполнять, то всё равно возвращается ранее отправленный пакет.
То есть, похоже на то, что пустое значение считаются "тем же идентификатором".

У PackageSendtTask такого поведения нет.

**Comment by GilimkhanovDenis** [comment]
Выпустили версию [5.29.2](http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_29_2.html). Проверьте работу с динамическим контентом на ней

**Comment by sergeb72** [comment]
Установили, проверили.
Динамический контент создаётся, атрибуты его уровня заполняются, но попытка добавления элемента любой коллекции приводит к падению.

**Comment by GilimkhanovDenis** [comment]
Выложили версию [5.29.3](http://1c-docs.diadoc.ru/ru/latest/Downloads.html). Должно починиться.

Проверял на коде

```
var
  dd_RootObject, dd_Connection, dd_Organization,
  dd_SendTask, dd_DocumentToSend, dd_DynamicContent,
  dd_Utd_820SellerContent, dd_ValueCollection, dd_Sellers, dd_NewSeller: Variant;
  dd_hasProperty : boolean;

begin
  dd_RootObject := CreateOleObject('Diadoc.DiadocClient');
  dd_RootObject.ApiClientId := 'MyApiKey';
  dd_RootObject.ServerUrl := 'https://diadoc-api.kontur.ru:443';
  dd_Connection := dd_RootObject.CreateConnectionByCertificate('MyCertificateThumbprint');
  dd_Organization := dd_Connection.GetOrganizationById('MyBoxId');

  dd_SendTask := dd_Organization.CreatePackageSendTask2;
  dd_DocumentToSend := dd_SendTask.AddDocument('UniversalTransferDocument', 'СЧФДОП', 'utd820_05_01_01');

  dd_DynamicContent := dd_DocumentToSend.Content;
  dd_hasProperty := dd_DynamicContent.HasProperty('UniversalTransferDocument');
  dd_Utd_820SellerContent := dd_DynamicContent.UniversalTransferDocument;
  dd_Sellers := dd_Utd_820SellerContent.Sellers;
  dd_Sellers.AddSeller;

  dd_hasProperty := dd_NewSeller.HasProperty('OrganizationReference');

end;

end.
```

**Comment by sergeb72** [comment]
На этом этапе починилось. Наткнулись на следующие моменты:

1. В XSD схеме, обновлённой на всякий случай сегодня, указаны следующие типы перечислений:
Signer.SignerDetails.SignerType - перечисление типа string от "1" до "3",
Signer.SignerDetails.SignerPowers - перечисление типа integer от 0 до 6.

Каким образом присваивать им значения, если ошибка
`raised exception class EOleSysError with message 'Неверный тип переменной'`
возникает в момент присвоения значений на любых комбинациях:
```
  Signer.SignerDetails.SignerType := '1';
  Signer.SignerDetails.SignerType := 1;
  Signer.SignerDetails.SignerPowers := 1;
  Signer.SignerDetails.SignerPowers := '1';

```

2. У переменной, созданной с помощью Reflector.Describe, начал падать метод GetPropertiesNames, остальные 3 метода работают штатно.

**Comment by GilimkhanovDenis** [comment]
Заполняйте все поля DynamicContent'а строками - другие типы он не принимает.  Например так:

```
Signer.SignerDetails.SignerType := '1';
Signer.SignerDetails.SignerPowers := '1';
Signer.SignerDetails.Inn := '0000000000';
Signer.SignerDetails.SignerStatus := '1';
Signer.SignerDetails.LastName := 'LastName';
Signer.SignerDetails.FirstName := 'FirstName';
```


Про Reflector лучше отдельный тикет сделать, чтобы не мешать всё в одну кучу

**Comment by sergeb72** [comment]
Так мы и пробуем заполнять строками в том числе, но ошибка 'Неверный тип переменной' происходит сразу после попытки присвоения.

**Comment by GilimkhanovDenis** [comment]
Можете приложить сюда свой код?
у меня не воспроизводится
![image](https://user-images.githubusercontent.com/34439383/70117414-46a78080-1687-11ea-9431-cbd220cd8533.png)

воспроизвожу на
Embarcadero® Delphi 10.3 Version 26.0.36039.7899
![image](https://user-images.githubusercontent.com/34439383/70117440-545d0600-1687-11ea-8663-02145f376b52.png)

**Comment by sergeb72** [comment]
![image](https://user-images.githubusercontent.com/30636239/70122058-f4fbf780-1680-11ea-9fba-50e6d9e45027.png)

Код:
```
var
  API, Connection, Org: OleVariant;
  PackageSendTask, DocInPackage, DynamicContent, UtdSellerContent: OleVariant;
  Signer: OleVariant;
  Version: string;
begin
  API := CreateOLEObject(DIADOC_COM_NAME);
  Version := API.GetVersion; // возвращает '5.29.3.536'
  API.ApiClientId := API_CLIENT_ID;
  API.ServerUrl := SERVER_URL;
  Connection := API.CreateConnectionByLogin(F_USER_LOGIN, F_USER_PASSWORD);
  Org := Connection.GetOrganizationById(F_ORG_ID);

  PackageSendTask := Org.CreatePackageSendTask2;
  PackageSendTask.IsDraft := True;
  DocInPackage := PackageSendTask.AddDocument('UniversalTransferDocument', 'СЧФДОП', 'utd820_05_01_01');

  DynamicContent := DocInPackage.Content;
  UtdSellerContent := DynamicContent.UniversalTransferDocument;

  Signer := UtdSellerContent.Signers.AddItems;
  Signer.SignerDetails.SignerType := '1';

end;
```

**Comment by GilimkhanovDenis** [comment]
Проверил на Вашем коде - тоже без ошибки.

Проект собираете как x86 или x64 ?

**Comment by sergeb72** [comment]
Оба варианта, x86 и x64. Попробуем пока сами поэкспериментировать с мистикой.

Два коротких вопроса по изменениям:

1. В "статические" документы в качестве BoxId продавца и покупателя  передавалось значение ExtendedOrganizationInfo.BoxId (то есть в формате "0540926453394dc7aa362625f812119e@diadoc.ru"). В приложенном Вами коде вижу, что в документ динамического контента передаётся BoxId в формате GUID. Предполагается самостоятельная конвертация, или есть/будет готовый атрибут контрагента в формате GUID?

2. Повторю вопрос про PackageSendtTask2.Send():
> "Если отправка пакета с заполненным OperationId завершилась успехом, то все остальные попытки отправки с тем же идентификатором не будут приводить к отправке нового пакета, а в результате выполнения метода вернется ранее отправленный пакет"

Если OperationId совсем не заполнять, то всё равно возвращается ранее отправленный пакет.
То есть, похоже на то, что пустые значение считаются "тем же идентификатором".
Закладываться на такое поведение, или оно будет приведено в соответствие с описанием метода?

**Comment by volodkindv** [comment]
Добрый день.
1. Готового атрибута контрагента в формате GUID не планируется. Сконвертировать boxId в guid - задача интегратора.
2. Про OperationId пока не готовы ответить, надо будет разбираться. Если вам важно отправлять каждый раз новый пакет, то указывайте пока OperationId в явном виде.

**Comment by sergeb72** [comment]
Спасибо.
Для истории: ошибка "Неверный тип переменной" возникает из-за неявной конвертации строк, подходящих по формату под целочисленное значение. Помогает явное указание строкового типа на этапе присвоения:
`Signer.SignerDetails.SignerType := VarAsType('1', VT_BSTR);`
