### ISSUE TITLE
Ошибка при подписи документа

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#380]
Добрый день! Документ https://diadoc.kontur.ru/54d0b467-aade-47d6-8136-a2bbe2eeb67d/Document/Show?letterId=53af3319-b69c-4047-a2e9-d6e534ca2f8b&documentId=b89fe246-5992-487b-aff9-dd8e305c3bd6 не подписался через модуль  - получили ошибку Произошла исключительная ситуация (ReplySendTask2.Send): ##300[Ошибка CryptoPro]Ошибка при подписывании данных [2148073488:Отказано в доступе.] Через веб интерфейс подписался нормально. В чем может быть причина?

**Comment by volodkindv** [comment]
Добрый день!
Что-то с КриптоПро. Возможные причины тут: https://ca.kontur.ru/faq/teh/oshibka-ecp
Попробуйте пройтись по ним для начала.

**Comment by GuninaY** [comment]
Спасибо, вы правы
