### ISSUE TITLE
Передача на подписание

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#381]
Добрый день. Есть ящик контаргента c22dcaccc2854b60bd2649356a920d9a@diadoc.ru.
В нем часть документов передается на подписание через diadoc api (например, https://diadoc.kontur.ru/c22dcacc-c285-4b60-bd26-49356a920d9a/Document/Show?letterId=ada9c3e9-54aa-4097-81c5-a7b8dcd99907&documentId=9f1df6e5-a8da-426a-9395-c19af3bde973), а часть нет (например, https://diadoc.kontur.ru/c22dcacc-c285-4b60-bd26-49356a920d9a/Document/Show?letterId=f6f1cc14-db83-41ec-8353-9e0f596e9a77&documentId=3a75e0de-df61-4acf-8403-d1241d0001c9). При этом выдает ошибку, что в ящике не найден документ с идентификатором f6f1cc14-db83-41ec-8353-9e0f596e9a773a75e0de-df61-4acf-8403-d1241d0001c9. Хотя это идентификатор документа из примера. Подскажите, с чем это может быть связано, т.к. документ не единичный.

**Comment by kulakovskaya** [comment]
Добрый день! Какой метод используете для передачи на подпись? Можете приложить код запроса?

**Comment by prog22** [comment]
Дело в том, что часть документов передается на подпись, а часть нет. При этом все они одного типа.
Код:
Процедура ОбработчикПередачиНаСогласованиеВходящихДокументов(ДиадокСоединение, Organization, Document, ПараметрыСогласования, Type = "SignatureRequest", Отказ) Экспорт
	
	DocumentPackage = Document.GetDocumentPackage();
		
	ResolutionRequestTask = DocumentPackage.CreateResolutionRequestTask();
	ResolutionRequestTask.ResolutionRequestType = Type;
	ResolutionRequestTask.Comment 				= ПараметрыСогласования.Комментарий;
    ResolutionRequestTask.TargetUserId 			= ПараметрыСогласования.ИдентификаторПользователя;
	
	ResolutionRequestTask.Send();
	
КонецПроцедуры

**Comment by IrinaShmonina** [comment]
Здравствуйте,
у вас закончилась подписка на API Диадока. Нужно обратиться к своему менеджеру или в техподдержку Диадока.

**Comment by prog22** [comment]
Добрый день. Подскажите, аналогичная ситуация:
ящик контрагента: 1b501aa4dbb94351ad3207d12aebd3e2@diadoc.ru
Документы то передаются на подписание, то нет.
Пример:
передался: 1abac1f3-4ecc-4720-b436-df5ca6077ed5ffe5e6e5-4ac4-4623-ab6a-47a56918f040
не передались:
65ad2704-8ca1-4968-9361-f92dcd743e454479b893-5cfe-4a51-9440-9ff9c9bba22d
c0c23df4-c580-4670-8d10-04cfb82117fcafa2e7d4-6a27-4cea-9275-c69a95c1ba10

**Comment by prog22** [comment]
Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ResolutionRequestTask.Send): ##100[Ошибка сервера Диадок]code:409, HTTP error: Текущее состояние документа не позволяет его подписать

**Comment by IrinaShmonina** [comment]
Здравствуйте,
у вас нет оплаты API, поэтому возвращается ошибка.
Обратитесь к вашему менеджеру или в нашу техническую поддержку https://www.diadoc.ru/support

**Comment by prog22** [comment]
Подскажите, пожалуйста, а есть возможность возвращать корректную ошибку - "нет оплаты API"?
Чтобы не тратить время на разбор и дергать Вас.

**Comment by volodkindv** [comment]
Добрый день.
Нам не удается воспроизвести ситуацию на своей стороне.
Должна возвращаться ошибка 402 с текстом "Доступ запрещён. Необходима оплата тарифа АПИ".
Проверьте на своей стороне, не перепутаны ли у вас местами boxid отправителя и получателя?
Исходящий документ, который уже подписан и отправлен контрагенту, действительно нельзя передать на подписание. Возможно, эта проверка отрабатывает раньше, чем проверка оплаты.

**Comment by prog22** [comment]
Мы передаем на подписание документ со стороны Покупателя.
Ситуацию, когда Покупатель подписал документ, а после этого его пытаются передать на подпись - обрабатываем.
Исходящий документ подписываем сразу при отправке. Тариф АПИ состороны Поставщика оплачен. Вопрос с оплатой тарифа у Покупателя.
Ну и возвращаясь к основному вопросу - частично документы были переданы на подпись со стороны Покупателя. Примеры id ящиков и документов выше.

**Comment by volodkindv** [comment]
Оплата API в ящике c22dcaccc2854b60bd2649356a920d9a@diadoc.ru действовала до даты 16.11.2019 11:21 МСК.

[Первый документ](https://diadoc.kontur.ru/c22dcacc-c285-4b60-bd26-49356a920d9a/Document/Show?letterId=ada9c3e9-54aa-4097-81c5-a7b8dcd99907&documentId=9f1df6e5-a8da-426a-9395-c19af3bde973) передан на согласование 2019-11-15 01:26:40Z. Это было до того, как закончилась подписка API.

[Второй документ](https://diadoc.kontur.ru/c22dcacc-c285-4b60-bd26-49356a920d9a/Document/Show?letterId=f6f1cc14-db83-41ec-8353-9e0f596e9a77&documentId=3a75e0de-df61-4acf-8403-d1241d0001c9) отправлен 2019-11-23, т.е. уже после окончания подписки API.

Это объясняет происходящее.

**Comment by prog22** [comment]
Подскажите, как понять, что оплата тарифа у Покупателя закончилась? По возвращаемым ошибкам это понять невозможно. Например, покупатель с id  1b501aa4dbb94351ad3207d12aebd3e2@diadoc.ru (указан выше), утверждает, что все оплатил в августе, действует ли подписка - непонятно.

**Comment by i82** [comment]
Для 1b501aa4dbb94351ad3207d12aebd3e2 нет купленной подписки на API.
По большинству методов мы отправляем явную ошибку про отсутствие оплаты. Чтобы точно ответить, почему в вашем случае Диадок вернул что-то другое нам нужен метод, текст полученной ошибки и примерное время вызова
