### ISSUE TITLE
PackageSendTask2.AddDocument(TitleName, Function, Version) - актуальные версии

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#382]
Переходим с PackageSendTask на PackageSendTask2.
Метод PackageSendTask2.AddDocument(TitleName, Function, Version) - требует другие параметры.
Точнее непонятно про параметр Version, например, для УПД он может принимать значения: 

utd_05_01_01
utd_05_01_02
utd_05_01_04
utd_05_01_05
utd_05_02_01

Метод GetDocumentTypes нужной информации не дает, т.к. там перечисляются те же версии.

Например мне нужно передать документ УПД по 155 Приказу, какую версию нужно выбирать, где посмотреть информацию для всех документов?

**Comment by volodkindv** [comment]
Добрый день.
Список форматов документов можно посмотреть [здесь](http://api-docs.diadoc.ru/ru/latest/docflows/AttachmentVersion.html).
Для УПД 155 стоит использовать последнюю версию utd_05, т.е. "utd_05_02_01".
Формат 155 приказа действует до конца этого года. С 1 января 2020 года рекомендуем использовать формат 820 приказа: например, utd820_05_01_01.

**Comment by geron4** [comment]
Для 820 лучше использовать "utd820_05_01_01_hyphen", "utd820_05_01_01" больше не будет поддерживаться
