### ISSUE TITLE
Ошибка при вызове метода TypeDesc.GetPropertiesNames

### ISSUE THREAD

**Issue by sergeb72** [diadoc/diadocsdk-1c-docs#383]
Вынесено из issue #378

COM компонента v5.29.3.536 для произвольных систем, Delphi XE2.

У переменной, созданной с помощью Reflector.Describe, начал падать метод GetPropertiesNames, остальные 3 метода работают штатно.

**Comment by GilimkhanovDenis** [comment]
Исправлено в версии [5.29.4.539](http://1c-docs.diadoc.ru/ru/latest/Downloads.html)
