### ISSUE TITLE
Ошибка при получении реквизитов "своей" организации

### ISSUE THREAD

**Issue by DmVKonst** [diadoc/diadocsdk-1c-docs#384]
COM компонента v5.29.3.536 x86 для произвольных систем перестала возвращать реквизиты организации в таком алгоритме:
OrganizationList = Connection.GetOrganizationList() # не пустой, Count()=1
Organization = OrganizationList.GetItem(0)
id = Organization.Id # пусто, все остальные свойства тоже
Вернулся на v5.28.4.493: все нормально

**Comment by GilimkhanovDenis** [comment]
Исправлено в версии [5.29.4.539](http://1c-docs.diadoc.ru/ru/latest/Downloads.html)
