### ISSUE TITLE
Согласован с разногласиями

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#386]
Добрый день! Подскажите, пожалуйста, как отобрать во входящих документах те, которые отправлены на подпись, но согласованы с разногласиями? И соответственно подписать их нужно тоже с разногласиями. Сейчас я просто все выбираю DocumentsTask.Category ="Any.InboundWaitingForResolution";

**Comment by kulakovskaya** [comment]
Добрый день! Правильно ли понимаем, что под такими документами вы имели ввиду входящие документы, которые нужно подписать с разногласиями, и по ним получен отказ в согласовании?

**Comment by GuninaY** [comment]
Да

**Comment by kulakovskaya** [comment]
1. Для того чтобы отфильтровать список входящих документов, по которым получен отказ в согласовании, нужно использовать статус Disapproved.
2. Нет возможности отфильтровать документы, по которым получили отказ в согласовании, а потом передали на подпись.
