### ISSUE TITLE
Свойство CustomData объекта Document

### ISSUE THREAD

**Issue by Dilise** [diadoc/diadocsdk-1c-docs#387]
Добрый день!

Есть потребность отправки служебных данных между организациями.
В описании объекта Document увидел свойство CustomData.
Если правильно понял, то данное свойство как раз для этих нужд и создано.

Однако не нашел как это свойство заполнить при отправке пакета документов.
Предполагаю, в CustomDocumentToSend в коллекцию Metadata необходимо добавить объект MetaDataItem, где ключ (Key) будет строка "CustomData", а значение (Value) будет необходимая служебная информация.

На стороне получателя, просто у объекта Document читаем свойство CustomData и выполняем нужные действия.

Вопросы:
1. Корректно использовать свойство CustomData для передачи служебной информации?
2. Влияет ли свойство CustomData на визуализацию формализованного документа при просмотре документа через веб интерфейс? Вообще это свойство где-нибудь в веб интерфейсе отображается?
3. Правильно ли я понимаю алгоритм заполнения / чтения данного свойства?

**Comment by kulakovskaya** [comment]
Добрый день! 

1. Корректно использовать свойство CustomData для передачи служебной информации? - **Да**
2. Правильно ли я понимаю алгоритм заполнения / чтения данного свойства? - **Нет**
CustomData заполняется с помощью объекта CustomDataPatchTask для уже отправленного документа (объект Document). То есть заполнение CustomData невозможно при отправке документа.

**Comment by Dilise** [comment]
С использованием в теории разобрался.
Про визуализацию что-нибудь подскажете?

**Comment by IrinaShmonina** [comment]
В веб версии Диадока добавление CustomData отображается в истории по документу. Также можно посмотреть CustomData по кнопке "Редактировать теги". На печатную форму CustomData не влияет.

**Comment by i82** [comment]
Дополню ответ Ирины. Редактирование тегов может быть вам недоступно - это платная функциональность и в первую очередь она предназначена для редактирования тегов в веб интерфейсе, а не для просмотра.

**Comment by Dilise** [comment]
Спасибо за ответы, будем пробовать.

**Comment by Dilise** [comment]
Вдруг кому пригодится - оставлю ссылку на пример использования: https://github.com/diadoc/diadocsdk-1c-docs/issues/304
