### ISSUE TITLE
Не отправляется неформализованный документ COM 64 вер.5.28.8.523

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#388]
Не отправляется неформализованный документ, Диадок API COM 64 вер.5.28.8.523
В качестве документа - обычный файл PDF.

SendTaskFromFile = PackageSendTask2.AddDocumentFromFile("Nonformalized", "default", "v1", ПутьКФайлу);
SendTaskFromFile.NeedRecipientSignature = True;

Ошибка:
Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:500, HTTP error: The server encountered an internal error or misconfiguration and was unable to complete your request

Прошу указать в чем ошибка.

![2019-12-06_11-11-15](https://user-images.githubusercontent.com/20473774/70300540-97e77980-1819-11ea-89cc-9f6c7e3b256e.png)

**Comment by GilimkhanovDenis** [comment]
Попробуйте на версии компоненты 5.29.5.540
Если воспроизводится, то сообщите время (часовым поясом) во сколько произошла ошибка

**Comment by geron4** [comment]
Попробовал на 5.29.5.540, тоже самое, инфо по отправке ниже, обратите внимание, что отправлено как "ЧЕРНОВИК", в пакете 2 документа, один из них неформализованный, на нем и ошибка

Пакет отправлен как черновик (Время ЕКБ, МСК+2): 09.12.2019 9:20:45, OrganizationDiadoc.Id = 4a15383adbb94a5ebb01a68f20132765@diadoc.ru, PackageSendTask.OperationId = 0a8146e6-dbc6-45cd-b59a-69a58a8a14ed, PackageSendTask.CounteragentId = d64a17ceabc64022be61bdab30279d54@diadoc.ru

ошибка та же,
Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:500, HTTP error: The server encountered an internal error or misconfiguration and was unable to complete your request

**Comment by geron4** [comment]
см.предыдущее сообщение,
еще как вариант, дайте пример кода по отправке неформализованных документов (может я что-то делаю неправильно)

**Comment by GilimkhanovDenis** [comment]
Здравствуйте
Пример кода есть [здесь](http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html)

На первый взгляд ошибки у Вас не вижу. у себя пока тоже не смог воспроизвести - УПД820_hyphen + Неформализованный с запросом подписи без ошибки попадают в черновик.

Если отправлять отдельно Неформализованный документ в черновики, то ошибка воспроизводится?
Если отдельно УПД820_hyphen ?

**Comment by geron4** [comment]
На той же компоненте заработало с таким кодом:

SendTaskFromFile = PackageSendTask.AddDocumentFromFile("Nonformalized", "default", "v1", ПутьКФайлу);
SendTaskFromFile.NeedRecipientSignature = ТребоватьОбратнуюПодпись;	
	
MetaData = SendTaskFromFile.AddMetadata();
MetaData.Key   = "FileName";
MetaData.Value = ИмяФайла;

Вероятно без MetaData не работало.
