### ISSUE TITLE
Ошибка DiadocCom_5.29.4.539 - GetOrganizationList()

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#389]
OrganizationList = ДиадокСоединение.GetOrganizationList();
Выдает 11 элементов (в моем случае)

Organization = OrganizationList.GetItem(0);
Выдает "кривой" com-объект, содержащий какие-то непонятные данные.
Ошибка была замечена после обновления компоненты на указанную версию.

Прошу проверить.

**Comment by GilimkhanovDenis** [comment]
Исправлено в 5.29.5.540

**Comment by geron4** [comment]
В 5.29.5.540 работает
