### ISSUE TITLE
Ошибка при подписании неформализованного документа (COM-компонента 64х)

### ISSUE THREAD

**Issue by maxstarkov** [diadoc/diadocsdk-1c-docs#39]
При попытке подписания неформализованного документа через метод Accept() получаю исключение:

`Произошла исключительная ситуация (0x800405e8)`

Контекст такой:

```
ДиадокАПИ = ПолучитьОбъектАПИ();
ДиадокСоединение = ПолучитьОбъектСоединения(ДиадокАПИ);
ТекущаяОрганизация = ДиадокСоединение.GetOrganizationById(СокрЛП(ИдентификаторОрганизации));
ТекущийДокумент = ТекущаяОрганизация.GetDocumentById(ИдентификаторДокумента);
ТекущийДокумент.Accept();
```

Версия компоненты 5.8.0.138.

Картинка текущей организации:

![default](https://cloud.githubusercontent.com/assets/9978984/20138348/b4147be0-a6a1-11e6-9c59-6fbd1afd61bb.PNG)

Картинка текущего документа:

![default](https://cloud.githubusercontent.com/assets/9978984/20138355/be777e02-a6a1-11e6-82e0-d467881c9a27.PNG)

Документ с типом Nonformalized, подпись для него требуется, но при выполнении Accept() - исключение.

**Comment by v-r-n** [comment]
Проблема действительно имеет место быть в версии 5.8.0.138. Причем в 32-битной версии компоненты такая проблема не наблюдается. Вопрос передан нашим разработчикам компоненты. Как только проблема будет решена - сообщим.

**Comment by maxstarkov** [comment]
В новой версии компоненты ошибок нет. Все работает.
