### ISSUE TITLE
Не отправляется УПД

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#390]
Добрый день, подскажите по следующей ситуации: Одному из контрагентов не отправляется УПД. Получаем ошибку Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid generated title:
Metadata errors: Невозможно получить данные по ключу: /Файл/СвУчДокОбор/@ИдПол
Validation errors: 

Я так поняла ругается на идентификатор участника ЭДО. Если его не заполнить. берет организацию из Buyers. Там все заполнено также как и у других. Его  идентификатор ЭДО 2BE2b9c65f66a5b4cb4a93a81665f1e1c91

**Comment by GuninaY** [comment]
Выяснилось: контрагент поменял оператора и нам нужно снова делать с ним настройку

**Comment by GilimkhanovDenis** [comment]
Здравствуйте. Покажите, пожалуйста как заполняете коллекцию Buyers

**Comment by GuninaY** [comment]
Решилось непосредственным указанием ИдПол у покупателя
