### ISSUE TITLE
ВНИМАНИЕ!!! ОШИБКА в данных, получаемых через GetDynamicContent("Seller")

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#391]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. 

Сегодня попробовали перейти на последнюю версию АПИ 5.29.5.540 и сразу же поймали ошибку.

**После чтения динамического контента "Seller" для документов УПД с любой версией XSD при обращении к любому полю, содержащему в себе другие поля (в отладчике 1С - с "плюсиком"), например, "Shipper" или "Table" и т.п. - происходит вылет 1С!**

Причем это происходит как при выполнении кода 1С, так и при остановке в отладчике и попытке развернуть данное поле - происходит вылет 1С!

Что-то с доступом к COM объекту не работает!

Причем сами данные есть и видны в отладке:
![image](https://user-images.githubusercontent.com/33707226/70408974-d721fe80-1a95-11ea-88da-d7cac9c5fce0.png)

Но, если теперь, например, щелкнуть мышкой по любому "плюсику", например, по "AdditionalInfoId", то 1С думает примерно полсекунды-секунду - и вылетает!

Такой же вылет происходит и при при обращении к таким полям (их содержимому) просто кодом 1С!

В версиях 5.28.xx.xxx такой проблемы не было!

Огромная просьба починить! Работать же невозможно, совершенно!!!

**Comment by JohnSergeev** [comment]
Дополнительно: Еще в версии 5.29.1.530 эта ошибка не появлялась!

**Comment by JohnSergeev** [comment]
Дополнительно: 
Версия 1С, на которой возникает проблема: 8.3 (8.3.10.2375)

**Comment by GilimkhanovDenis** [comment]
Исправлено в 5.29.6.541

**Comment by JohnSergeev** [comment]
Проверено. Всё работает. Спасибо!
