### ISSUE TITLE
ВНИМАНИЕ!!! ОШИБКА в данных подписанта при отказе в подписании документа

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#392]
Добрый день.
Работаем через внешние x32/x64 com компоненты для 1С. Своя реализация работы с вашим АПИ. Сейчас используем версию АПИ 5.28.6.502.

Обнаружили странную ошибку при попытке выполнения отказа от подписания документов с использованием нового, рекомендуемого функционала АПИ - через вызов **CreateReplySendTask2("RejectDocument")**. 

Предполагаем, что ошибка возникает при попытке отказа от подписания любых документов (как минимум воспроизводилась на УПД и неформализованных).

ВАЖНО!!! Эта ошибка воспроизводится и в последней версии АПИ 5.29.5.540.

Для отказа от подписания нужно заполнить данные Signer. И вот тут возникает очень забавная штука! 

Смотрим ЧТО именно лежит в Signer, предлагаемом для заполнения:
![image](https://user-images.githubusercontent.com/33707226/70409482-a04ce800-1a97-11ea-9e0a-4c4d2734b13e.png)

**Очевидно, что это неправильные данные для заполнения!**
Т.к. поля называются так, как они были названы в старой версии АПИ при использовании старой функции CreateReplySendTask!

А в новой версии CreateReplySendTask2 поля подписанта это:
![image](https://user-images.githubusercontent.com/33707226/70409564-e73add80-1a97-11ea-87a0-a80b314e4e37.png)

Обратите внимание на названия полей для Должности (старая - "JobTitle", новая - "Position").

Поэтому отказ от подписания не срабатывает. 

Что интересно, в сообщении об ошибке как раз и говорится о том, что должны быть заполнены именно НОВЫЕ поля:

 _##100[Ошибка сервера Диадок]code:400, HTTP error: LastName is required
FirstName is required
**Position** is required_

(еще раз обратите внимание на "Position"!)

Получается, что выполнить отказ от подписания невозможно, т.к. CreateReplySendTask2("RejectDocument") возвращает для заполнения данных подписанта "старый" объект, но затем где-то "у себя внутри" использует незаполненный "новый" объект и затем бодро рапортует об ошибке т.к. не заполнены новые поля!

Огромная просьба починить! Работать же невозможно!

**Comment by JohnSergeev** [comment]
**Дополнительно:**
Точно такая же проблема возникает и с данными Signer для операции запроса уточнения документа CreateReplySendTask2("CorrectionRequest")!

**Comment by volodkindv** [comment]
Добрый день.
Приложите идентификаторы документа, о котором идет речь. Или URL в вебе, он тоже содержит идентификаторы.

Пока предположение такое, что речь идет об однотитульном документе. Например, неформализованном документе, или счете на оплату. УПД - двухтитульный, и для него в ReplySendTask2 должен вернуться DynamicContent. А для однотитульных документов возвращается "старый" Content. Это отражено в [документации](http://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageContentItem.html).

**Comment by JohnSergeev** [comment]
Добрый день. Проверю. Отпишусь. Но вы не увидели двух вещей в моем сообщении:
1. И для УПД та же самая проблема - об этом написано в самом начале
2. Может быть и должно в некоторых случаях возвращать "старый" контент... Вот только в появляющемся сообщении об ошибке говорится о проблеме того, что незаполненными остались поля "нового" контента!

**Comment by volodkindv** [comment]
2. Ошибку выдает ядро Диадок. Названия полей в тексте ошибки в этом случае могут не совпадать с реальными названиями полей. Компонента просто транслирует этот текст в 1С.
Для дальнейшего разбора ситуации нам понадобятся идентификаторы документов, на которых у вас воспроизводится ошибка.

**Comment by JohnSergeev** [comment]
Добрый день.

Извиняюсь за задержку - пришлось отвлечься на другую ошибку в вашей компоненте (утечки памяти).

Сейчас проверяю ранее описанное поведение на новой версии 5.29.7.549. 
Все воспроизводится.

Итак, Тестовый ящик. берем документ **УПД**. Он, как вы пишите - "двухтитульный".

Документ.Type = "UniversalTransferDocument" 
Документ.Version = "utd820_05_01_01_hyphen"
Документ.Status = "InboundWaitingForRecipientSignature"
Документ.DocumentId = "0465c492-db29-4f84-aeb3-4fab026c67adf4117600-49ea-4ada-a2f2-504d6b6c780f"
Документ.PathURL = "/8015d19a-35ef-421f-84d1-2fbc7258c309/Document/Show?letterId=0465c492-db29-4f84-aeb3-4fab026c67ad&documentId=f4117600-49ea-4ada-a2f2-504d6b6c780f"

Выполняем попытку отказа в подписании.

Для этого вызываем CreateReplySendTask2("RejectDocument"). Получаем задание. А далее просто смотрим в отладчике 1С, что же лежит внутри:
![image](https://user-images.githubusercontent.com/33707226/71233204-969d6d00-2340-11ea-8e62-4541a1afa009.png)

Ну и видим, что для заполнения подана структура подписанта в СТАРОМ формате!
Хотя, по идее, должна быть в НОВОМ, где, например, поле должности подписанта называется не "JobTitle", а "Position".

**Разве это не ошибка?!**

Объясните, пожалуйста.

И, еще раз напомню, что точно такая же ситуация возникает для операции запроса уточнения документа через использование CreateReplySendTask2("CorrectionRequest")!

**Очень похоже, что CreateReplySendTask2 всегда тупо возвращает структуру подписанта в старом виде.**

**Comment by volodkindv** [comment]
Нет, это не ошибка. Это поведение [задокументировано](http://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageContentItem.html). Цитата:

> Если PackageContentItem запрашивается из ReplySendTask2 с типом **AcceptDocument** для двухтитульного документа, то Content будет объектом DynamicContent. В противном случае Content будет объектом, производным от BaseContent.

Иными словами:
CreateReplySendTask2("AcceptDocument") для формализованных двухтитульных документов даст динамический контент.
CreateReplySendTask2("AcceptDocument") для однотитульных и/или неформализованных документов даст "старый" контент.
CreateReplySendTask2("CorrectionRequest") даст "старый" контент для любых документов.
CreateReplySendTask2("RejectDocument") даст "старый" контент для любых документов.

**Comment by JohnSergeev** [comment]
Ок. Понятно. Спасибо.

Хотя и очень путано сделано, зачем теперь надо работать и со старой версией, и с новой - решительно непонятно...

В любом случае спасибо. Будем править код на эту схему.
