### ISSUE TITLE
Сквозной пример для перехода от CreateReplySendTask() к CreateReplySendTask2() 

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#393]
В связи с грядущим переходом (к 1 января 2020г.) на 820 формат УПД был изменён метод для подписания ЭД: возникла потребность в интеграционном решении перейти от CreateReplySendTask() к CreateReplySendTask2().

После прочтения документации не сформировал чёткого понимания, как должен заполняться титул подписания, как должен заполняться контент подписания ( примера заполнения DynamicContent не увидел).

Некоторые контрагенты отправляют УПД в 820 формате, подписывать методом CreateReplySendTask не удаётся.

В связи с этим прошу предоставить сквозной пример подписания ЭД в формате 820, с подробным заполнением свойства DynamicContent .

**Comment by IrinaShmonina** [comment]
Здравствуйте.
Пример [Как выполнить ответные действия по документам](http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_reply_document.html)

**Comment by MikeFilimonov** [comment]
> 
> 
> Здравствуйте.
> Пример [Как выполнить ответные действия по документам](http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_reply_document.html)

Мне и коллегам нужен пример заполнения динамического контента. Из материалов по ссылке неясно, как его заполнять и какова логика заполнения WorkflowId со стороны отправителя.

**Comment by IrinaShmonina** [comment]
Работа с DynamicContent не отличается от работы с другими COM-объектами.
Описание полей, которые необходимо заполнить можно получить из XSD, получаемой методами Organization.SaveUserDataXSD(), Organization.GetBase64UserDataXSD(), или, используя объект Reflector.
http://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html

Разные документы могут отправляться с разным Workflow. Посмотреть доступные Workflow можно в [DocumentWorkflow](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentWorkflow.html). Чтобы узнать доступные Workflow для документа, можно использовать метод [GetDocumentTypes](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetDocumentTypes)

**Comment by MikeFilimonov** [comment]
> 
> 
> Работа с DynamicContent не отличается от работы с другими COM-объектами.
> Описание полей, которые необходимо заполнить можно получить из XSD, получаемой методами Organization.SaveUserDataXSD(), Organization.GetBase64UserDataXSD(), или, используя объект Reflector.
> http://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html
> 
> Разные документы могут отправляться с разным Workflow. Посмотреть доступные Workflow можно в [DocumentWorkflow](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentWorkflow.html). Чтобы узнать доступные Workflow для документа, можно использовать метод [GetDocumentTypes](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetDocumentTypes)

Зачем это нужно, если у формализованных документов набор свойств регламентирован?

**Comment by volodkindv** [comment]
Такой подойдет?
```
Процедура ПодписатьВходящийДокумент820(ВходящийДокумент)	
	
	ReplySendTask2 = ВходящийДокумент.CreateReplySendTask2("AcceptDocument");
	ReplyContentItem = ReplySendTask2.ContentItems.GetItem(0);
	
	boxid = ВходящийДокумент.OrganizationId;
	thumbprint = ВходящийДокумент.Organization.Certificate.thumbprint;
	
	ЗаполнитьКонтентОтвета820(ReplyContentItem.content.UniversalTransferDocumentBuyerTitle, boxid, thumbprint);
	ReplySendTask2.Send();

КонецПроцедуры

Процедура ЗаполнитьКонтентОтвета820(Content, boxid, thumbprint)
	
	// xsd-схему титула, на основании которой строится UniversalTransferDocumentBuyerTitle, можно посмотреть по адресу:
	// http://api-docs.diadoc.ru/ru/latest/howto/utd820.html
	
	Content.AcceptanceDate = Формат(ТекущаяДата(), "ДФ=dd.MM.yyyy");
	Content.DocumentCreator = "ООО Рога и Копыта";
	Content.OperationContent = "Товары приняты";
	
	Signer = Content.Signers.AddItems();
	
	Signer.SignerReference.BoxId = boxid;
	Signer.SignerReference.CertificateThumbprint = thumbprint;
	
КонецПроцедуры	
```

**Comment by Aleksey2W** [comment]
> 
> 
> В связи с грядущим переходом (к 1 января 2020г.) на 820 формат УПД был изменён метод для подписания ЭД: возникла потребность в интеграционном решении перейти от CreateReplySendTask() к CreateReplySendTask2().
> 
> После прочтения документации не сформировал чёткого понимания, как должен заполняться титул подписания, как должен заполняться контент подписания ( примера заполнения DynamicContent не увидел).
> 
> Некоторые контрагенты отправляют УПД в 820 формате, подписывать методом CreateReplySendTask не удаётся.
> 
> В связи с этим прошу предоставить сквозной пример подписания ЭД в формате 820, с подробным заполнением свойства DynamicContent .

Тоже ничего не поняли, что же там есть и как каждый раз понимать, что там может быть...

Для формализованных документов решили проще - создаем xml по формату ФНС, а потом с помощью метода AddDocumentFromFile.

SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01", ИмяФайлаВоВременномХранилище);

Весь контекст заполняется автоматом.

**Comment by MikeFilimonov** [comment]
> > В связи с грядущим переходом (к 1 января 2020г.) на 820 формат УПД был изменён метод для подписания ЭД: возникла потребность в интеграционном решении перейти от CreateReplySendTask() к CreateReplySendTask2().
> > После прочтения документации не сформировал чёткого понимания, как должен заполняться титул подписания, как должен заполняться контент подписания ( примера заполнения DynamicContent не увидел).
> > Некоторые контрагенты отправляют УПД в 820 формате, подписывать методом CreateReplySendTask не удаётся.
> > В связи с этим прошу предоставить сквозной пример подписания ЭД в формате 820, с подробным заполнением свойства DynamicContent .
> 
> Тоже ничего не поняли, что же там есть и как каждый раз понимать, что там может быть...
> 
> Для формализованных документов решили проще - создаем xml по формату ФНС, а потом с помощью метода AddDocumentFromFile.
> 
> SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01", ИмяФайлаВоВременномХранилище);
> 
> Весь контекст заполняется автоматом.

Алексей,  что в переменной ИмяФайлаВоВременномХранилище ? Я формирую титул подписания для ответа на входящий документ

**Comment by MikeFilimonov** [comment]
> Такой подойдет?
> 
> ```
> Процедура ПодписатьВходящийДокумент820(ВходящийДокумент)	
> 	
> 	ReplySendTask2 = ВходящийДокумент.CreateReplySendTask2("AcceptDocument");
> 	ReplyContentItem = ReplySendTask2.ContentItems.GetItem(0);
> 	
> 	boxid = ВходящийДокумент.OrganizationId;
> 	thumbprint = ВходящийДокумент.Organization.Certificate.thumbprint;
> 	
> 	ЗаполнитьКонтентОтвета820(ReplyContentItem.content.UniversalTransferDocumentBuyerTitle, boxid, thumbprint);
> 	ReplySendTask2.Send();
> 
> КонецПроцедуры
> 
> Процедура ЗаполнитьКонтентОтвета820(Content, boxid, thumbprint)
> 	
> 	// xsd-схему титула, на основании которой строится UniversalTransferDocumentBuyerTitle, можно посмотреть по адресу:
> 	// http://api-docs.diadoc.ru/ru/latest/howto/utd820.html
> 	
> 	Content.AcceptanceDate = Формат(ТекущаяДата(), "ДФ=dd.MM.yyyy");
> 	Content.DocumentCreator = "ООО Рога и Копыта";
> 	Content.OperationContent = "Товары приняты";
> 	
> 	Signer = Content.Signers.AddItems();
> 	
> 	Signer.SignerReference.BoxId = boxid;
> 	Signer.SignerReference.CertificateThumbprint = thumbprint;
> 	
> КонецПроцедуры	
> ```

Думаю, да. На момент создания issue, если не ошибаюсь была проблема на стороне API по работе с Reflector. Думаю теперь этим объектом можно получать информацию о наборе свойств объекта дин. контекста. 

Про xsd поставщика:
Изначально непонятна мысль, почему у каждого поставщика ожидается своя xsd для формализованных документов?

**Comment by volodkindv** [comment]
> Изначально непонятна мысль, почему у каждого поставщика ожидается своя xsd для формализованных документов?

Из чего вы сделали такой вывод?

Предыстория GetDocumentTypes следующая.
В Диадоке можно отправлять разные типы документов. УПД и счета-фактуры разных версий - это только часть большого множества возможных типов.

Например, ООО "Ромашка" отправляет УПД и собственный формализованный тип документа "Акт передачи ОС". ИП Иванов отправляет УПД и собственный неформализованный тип документа "Агентский договор". УПД у них будут одинаковыми, с одинаковым набором workflow и versions. Но при этом "Акт передачи ОС" должен видеть только ООО Ромашка и его контрагенты. 

Поэтому есть метод GetDocumentTypes, который рассказывает, какие типы документов доступны в конкретном boxId.

**Comment by MikeFilimonov** [comment]
> > Изначально непонятна мысль, почему у каждого поставщика ожидается своя xsd для формализованных документов?
> 
> Из чего вы сделали такой вывод?
> 
> Предыстория GetDocumentTypes следующая.
> В Диадоке можно отправлять разные типы документов. УПД и счета-фактуры разных версий - это только часть большого множества возможных типов.
> 
> Например, ООО "Ромашка" отправляет УПД и собственный формализованный тип документа "Акт передачи ОС". ИП Иванов отправляет УПД и собственный неформализованный тип документа "Агентский договор". УПД у них будут одинаковыми, с одинаковым набором workflow и versions. Но при этом "Акт передачи ОС" должен видеть только ООО Ромашка и его контрагенты.
> 
> Поэтому есть метод GetDocumentTypes, который рассказывает, какие типы документов доступны в конкретном boxId.

Данила, про различные типы документов мне известно. 
Можете пояснить, как собственный документ может быть формализованным. Насколько знаю, собственные не являются формализованными.
Моё недоумение относится к DynamicContent. Обусловлено единообразием именно формализованных документов.

Возможно, я что - то упустил, и как раз наличие формализованных собственных документов многое может объяснить.

**Comment by MikeFilimonov** [comment]
> Возможно, я что - то упустил, и как раз наличие формализованных собственных документов многое может объяснить.

Данила, прошу уточнить критерий формализованного документа для внесения ясности в диалог.

**Comment by volodkindv** [comment]
> Данила, прошу уточнить критерий формализованного документа для внесения ясности в диалог.

Да, похоже, мы с вами разные смыслы вкладываем в понятие "формализованный документ".
Мы под формализованным документом понимаем документ, файл которого имеет определенную структуру. Как правило, это формат xml. Это может быть счет-фактура/накладная/УПД. А может быть какой-нибудь "КС-2", который тоже передается в XML определенной структуры. Или "Показания счетчиков электроэнергии" - тоже имеет структуру, но встречается не у всех контрагентов.

Документы, которые не имеют структуры и передаются просто как двоичные данные (PDF, Excel, Word, JPEG) мы называем неформализованными.
