### ISSUE TITLE
RSS 

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#394]
При переходе из документации https://buildmedia.readthedocs.org/media/pdf/diadocsdk-1c/latest/diadocsdk-1c.pdf на страницу "Новости RSS" открывается содержимое XML файла.
![изображение](https://user-images.githubusercontent.com/3480769/70436081-8a402700-1a99-11ea-82c4-c1722a05dccd.png)

![изображение](https://user-images.githubusercontent.com/3480769/70436123-a0e67e00-1a99-11ea-9a8d-edae7f09ab0e.png)

**Comment by GilimkhanovDenis** [comment]
rss является xml-файлом. Поставьте какой-нибудь плагин для визуализации RSS
