### ISSUE TITLE
Некорректное именование метода

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#395]
![изображение](https://user-images.githubusercontent.com/3480769/70448554-946e1f80-1ab1-11ea-928c-b192832e4d7b.png)
http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentTitle.html#documenttitle
Если титул в ед. ч., тогда уместнее назвать метод hasUserDataXSD

**Comment by volodkindv** [comment]
Спасибо за замечание. Существующие методы мы менять уже не станем, т.к. ими много кто пользуется. В будущих постараемся учесть.
