### ISSUE TITLE
Формирование и отправка документов в соответствии с Приказом ФНС № 820

### ISSUE THREAD

**Issue by plandoff** [diadoc/diadocsdk-1c-docs#396]
Добрый день!
Мы самостоятельно интегрировались с использованием COM Diadoc API (версия используемой компоненты 5.24.1.382). В описании к API не нашел явных инструкций, какие объекты и методы следует использовать, чтобы соответствовать новому стандарту. Сейчас мы отправляем 3 типа документов: УПД, УКД и Торг-12. Отправку производим объектом SendTask (метод CreateSendTask() у организации). Описание содержимого объекта содержится в разделе http://1c-docs.diadoc.ru/ru/latest/ComObjects/SendTask.html#sendtask-contenttype. Используем тип контента UtdSellerContent, UcdSellerContent и XmlTorg12Content (последний тип контента отсутствует среди доступных в описании объекта, насколько я понимаю, в новой версии компоненты он не поддерживается или переименован). Можем ли мы с 1 января 2020 года продолжать отправку формализованных документов указанными выше способами? Будет ли это соответствовать новому приказу? Или мы вынуждены перейти на использование других конструкций (если да, то каких)?

**Comment by IrinaShmonina** [comment]
Добрый день,
Для того чтобы работать с 820 форматом, нужно использовать объект [PackageSendTask2](http://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html). Пример использования объекта [Как отправить документы](http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html)

**Comment by plandoff** [comment]
Спасибо за оперативный ответ! Я правильно понимаю, что объект PackageSendTask2 можно начинать использовать прям сейчас, не дожидаясь вступления в силу нового приказа? Документы, созданные с его помощью, также соответствуют текущему стандарту?

**Comment by plandoff** [comment]
Еще момент: т.е. все документы, созданные с помощью объекта PackageSendTask2, по умолчанию соответствуют новому стандарту? С учетом, что все обязательные поля заполнены

**Comment by GilimkhanovDenis** [comment]
Можно начинать использовать сейчас. PackageSendTask2 поддерживает отправку всех формализованных документов, что доступны в ящике организации в Диадок

**Comment by plandoff** [comment]
"То есть, можно и в 155 формате УПД через него отправить и в 820" - можете прокомментировать данное утверждение? При создании и отправке я как то явно указываю формат?

**Comment by GilimkhanovDenis** [comment]
Всё верно. при отправке вы явно указываете формат в параметре Version:
utd_05_01_05 - УПД 155
utd820_05_01_01 - УПД 820

Доступные для отправки типы, версии, функции документа можно получть методом http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetDocumentTypes

**Comment by plandoff** [comment]
Спасибо! Еще вопрос, возможно не совсем по адресу: если сейчас начать отправлять документы в новом формате (820), это не будет являться ошибкой для ФНС? Или мы должны до 01.01.2020 отправлять строго в старом, а далее строго в новом?

**Comment by volodkindv** [comment]
Нет, это не будет ошибкой. Главное, чтобы ваши получатели уже умели работать с 820 форматом.

**Comment by plandoff** [comment]
Спасибо!
