### ISSUE TITLE
rss является xml-файлом. Поставьте какой-нибудь плагин для визуализации RSS

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#397]
rss является xml-файлом. Поставьте какой-нибудь плагин для визуализации RSS

_Originally posted by @GilimkhanovDenis in https://github.com/diadoc/diadocsdk-1c-docs/issues/394#issuecomment-563883993_

Сделайте новости в более удобном формате

**Comment by volodkindv** [comment]
Новости в удобном формате расположены тут: http://1c-docs.diadoc.ru/ru/latest/History/History.html.

RSS предназначены для почтовых клиентов. Вы можете подключить RSS в Outlook или другой почтовый клиент.
