### ISSUE TITLE
Получение статуса аннуляции документов,  не требующих подписи.

### ISSUE THREAD

**Issue by Fibba** [diadoc/diadocsdk-1c-docs#398]
Добрый день. Ситуация такая:

Мы закачиваем себе в учетную систему все события происходящие с документами с помощью метода GetDocumentEventList() и пытаемся понять, какой был аннулирован/отклонён, чтоб давать возможность пользователям работать с ними в нашей системе.

Вопрос по документам, не имеющих тип события "Reject", конкретно по УПД с функцией СЧФ. Вроде как прослеживается, что их аннуляция происходит с типом события "MetaModify", но бывают исключения, связанные с какими либо действиями пользователей (например, отправка извещения о получении).

Документ 0a62ec55-d6e6-4e75-9078-a48b5bab19275ff81c5b-4cdd-4463-9d32-f49ea4066a0c
имеет события:
![image](https://user-images.githubusercontent.com/42743750/70608852-e62dbb80-1c11-11ea-9be1-ba0d4642185d.png)
В личном кабинете "Аннулирован".

Документ 2f345b52-2779-4f1f-86da-fc47f48b59a9132b81ee-2882-41c9-a6dc-f4e6297c6479
имеет события:
![image](https://user-images.githubusercontent.com/42743750/70609786-74ef0800-1c13-11ea-92af-7396d17eef13.png)
В личном кабинете "Документооборот завершен".

Как понимать при обработке событий, кто из документов аннулирован? На что ещё обращать внимание?

**Comment by kulakovskaya** [comment]
Добрый день!
Подскажите, пожалуйста, какую версию компоненты используете? А также пришлите boxId организации.

**Comment by Fibba** [comment]
Компонента - DiadocCom_5_28_5_501_x64
boxId - 0fe70ae3e8cd40b197817b256ebbeb6a@diadoc.ru

**Comment by kulakovskaya** [comment]
Для УПД с функцией СЧФ метод  GetDocumentEventList() возвращает событие "Reject".
1. Рекомендуем Вам выполнить запрос снова, начиная с события 4275a199-7bf3-4a13-82b6-66a3eda638ca.
2. Обратите внимание на то, как Вы получаете событие Reject - нет ли фильтрации?

**Comment by Fibba** [comment]
Кто бы мог подумать, что "MetaModify" и "Reject" для таких УПД имеют одинаковый "EventId". А была полная уверенность, что он для каждого события уникально. 
![image](https://user-images.githubusercontent.com/42743750/71076693-33240b80-2197-11ea-992a-5c2f5ee02fd8.png)

Фильтраций не было. 

Разобрались, спасибо.
