### ISSUE TITLE
ЧУДОВИЩНОЕ ПОТРЕБЛЕНИЕ ПАМЯТИ при работе с новой версией АПИ.

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#399]
Добрый день.
Работаем через внешние x32/x64 **com** компоненты для 1С. Своя реализация работы с вашим АПИ. Сегодня перешли на версию АПИ 5.29.6.541.

**И тут же обнаружили совершенно невообразимое потребление памяти!** 

У нас операции ЭДО работают на отдельном сервере кластера 1С **на котором кроме них вообще больше ничего не работает**. После запуска у нас выполнялось в основном две операции - получение документов и получение Zip-архива файлов документов. 

В текущей реализации для получения документов и их данных мы используем новые методы АПИ - работу с динамическими контентами через вызовы GetDynamicContent(). А для получения архива файлов - SaveAllContentZipAsync().

За примерно 1 час работы произошло следующее:
![image](https://user-images.githubusercontent.com/33707226/70683368-e3a09400-1ced-11ea-8521-6f16bf9f9c54.png)

![image](https://user-images.githubusercontent.com/33707226/70683445-219db800-1cee-11ea-9cf3-ecf94c1ced9f.png)

Т.е. мы включили фоновые примерно в 12-00, и работа с использованием нового АПИ "выжрала" всю память на сервере буквально за час!

**Очень похоже, что у вас какая-то утечка памяти в com-компоненте (или полученная память в каких-то случаях не освобождается).**

**ВАЖНО!!!**
Ранее мы работали с версией АПИ 5.28.3.491.
Там тоже был подобный постоянный "расход" памяти, но, гораздо более медленный - свободная память на сервере "потихоньку" уменьшалась примерно в течение дня, а часто и на больше хватало. Вот типичный пример (свободная память постепенно утекает примерно за полтора дня):
![image](https://user-images.githubusercontent.com/33707226/70683643-d89a3380-1cee-11ea-8edb-3d90c132a2aa.png)

А, т.к. у нас почти каждое утро происходит плановый перезапуск серверов, то это особо не напрягало.

**Но то, что получилось сейчас, явно уже очень и очень напрягает! 
Явно что-то не то с выделением и освобождением памяти при работе с новым АПИ и использованием GetDynamicContent()!**

Кстати, т.к. в новом варианте получение архива файлов выполняется точно так же, как и в старом варианте - с использованием SaveAllContentZipAsync(), то очень похоже, что дело именно где-то в реализации работы с динамическими контентами. А может, конечно, и еще в чем-то... Это уже вам виднее. Вы разработчики, у вас исходники.

Пожалуйста, рассмотрите эту проблему как можно скорее - в текущем варианте использование компоненты очень... неудобно, скажем так.

Спасибо.

**Дополнение:**
За примерно 1 час на сервере была "выжрана" вся память (16 Гб), он какое-то время еще поработал, но в конце концов все фоновые ЭДО прекратили работу. После удаления rphost и запуска фоновых ЭДО свободная память на сервере стала уменьшаться со скоростью примерно 5-7 Мб в секунду!

На графике это выглядит так:
![image](https://user-images.githubusercontent.com/33707226/70690531-911da280-1d02-11ea-832a-dffb0ad4c342.png)

Фоновые ЭДО были запущены в 16-55 и за 15 минут rphost "съел" около 7 Гб памяти!
![image](https://user-images.githubusercontent.com/33707226/70690587-b27e8e80-1d02-11ea-9ed3-2d44772b9b8a.png)

Еще раз уточняю, что это отдельный сервер в кластере 1С на котором выполняется ТОЛЬКО код по работе с ЭДО и ничего более!

Пожалуйста, сделайте с этим что-нибудь!
**С таким чудовищным потреблением памяти совершенно же невозможно работать!**

Прошло еще немного времени... И:
![image](https://user-images.githubusercontent.com/33707226/70693216-c3320300-1d08-11ea-903f-977520b116ba.png)

Вся память на сервере "сожрана" за 1 час - с 16-55 по 17-55. 15 Гб "зависли" в пользовании у rphost:
![image](https://user-images.githubusercontent.com/33707226/70693292-e957a300-1d08-11ea-9f59-49585b346c2e.png)

Разберитесь, пожалуйста, с таким поведением com-компоненты!

Кстати, что-то еще и с загрузкой процессора странное:
![image](https://user-images.githubusercontent.com/33707226/70714858-c347f800-1d34-11ea-862c-cce340ba4cc1.png)

Четко видна граница потребления - до 12 часов работала версия компоненты 5.28.3.491, а с 12 - новая 5.29.6.541. И потребление ресурсов процессора стало существенно большим и каким-то хаотичным, что ли. "Дырка" в потреблении чуть после 16 часов - это когда выжралась вся память и перезапускали сервер. А так прямо видно, что новая версия, кроме того, что сжирает всю память, так еще и процессор нагружает гораздо сильнее!

Разберитесь, пожалуйста, что там вообще происходит!

Спасибо.

**Дополнение №2:**
Провели своими силами небольшой анализ того, в каких условиях утекает память. Обнаружили следующее очень интересное поведение:

1. Если мы получаем объект документа через GetDocumentByID(), затем получаем динамические контенты через GetDynamicContent("Seller") и GetDynamicContent("Buyer") и БОЛЕЕ НИЧЕГО НЕ ДЕЛАЕМ (вообще ничего - т.е. просто получили, но ничего "изнутри" не читаем, ни к каким полям этих объектов никак не обращаемся) - **память НЕ утекает**.

2. Если мы сделали все из п.1 и затем обращаемся к свойствам объекта документа полученного через GetDocumentByID(), но НЕ обращаемся к свойствам объектов дин. контентов, полученных через GetDynamicContent() - **память НЕ утекает**.

3. Если мы сделали все из п.1 и п.2 и затем ОБРАЩАЕМСЯ к свойствам объектов дин.контентов, полученных через GetDynamicContent() - **вот тут-то память уже УТЕКАЕТ!**

**Возможно, это важно:**
К свойствам этих объектов мы обращаемся не напрямую "через точку":
_Переменная1С = ОбъектДинКонтента.<ИмяПоля>;_

, а с помощью относительного доступа (через "скобки"). И присваиваем значение полю структуры 1С. А именно так:
_Структура1С.ПолеСтруктуры = ОбъектДинКонтента[<Строка_ИмяПоля>];_

**Пока что такое ощущение, что, возможно, что-то не так либо в самих объектах дин. контентов, возвращаемых GetDynamicContent(), либо какая-то проблема при получении данных из них, при использовании относительного доступа через [] по строковым именам полей.**

Надеемся, эта информация будет полезной.

**Comment by GilimkhanovDenis** [comment]
Попробуйте на [5.29.7.549](http://1c-docs.diadoc.ru/ru/latest/Downloads.html)
[release_notes](http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_29_7.html)

**Comment by JohnSergeev** [comment]
Добрый день.

Спасибо!!!

Пробуем. Пока (предварительно) все хорошо, «выжора» памяти нет.

Точно по итогам тестирования отпишусь на гитхабе завтра.

С уважением,
Сергеев Евгений.

**Comment by JohnSergeev** [comment]
Добрый день.

Более детально все "покрутили".
Утечек памяти нет!

Стало даже намного лучше чем в "старых" версиях 5.28.ххх - там тоже, похоже, были утечки, просто не такие "мощные" - вся память (16 Гб) сжиралась примерно за 1-1.5 дней.

Сейчас же ситуация на рабочем сервере выглядит так:
![image](https://user-images.githubusercontent.com/33707226/71227003-8ded6c80-2329-11ea-8bd8-bc23ee885ce1.png)
Т.е. в плане утечек все починено просто прекрасно!
Огромное спасибо!

Однако, все-таки хотелось бы поднять еще и вопрос по загрузке процессора - может быть у вас там тоже есть какие-то проблемы? Просто (я показывал выше на графиках) в новой версии такое ощущение, что загрузка процессора при работе с ЭДО выше в 2-2.5 раза, чем в версиях, в которых не работали через GetDynamicContent().

**Посмотрите, пожалуйста, может в этом тоже виновата какая-то ошибка/недоработка.**

Еще раз огромное спасибо за решение проблем с утечками памяти.

**Comment by volodkindv** [comment]
Здравствуйте.
Про загрузку процессора сделайте, пожалуйста, отдельный тикет. Иначе не разберем потом, что к чему относится.
Память починили, так что этот тикет закрываю.
