### ISSUE TITLE
Подключаемый модуль

### ISSUE THREAD

**Issue by ikolegov** [diadoc/diadocsdk-1c-docs#40]
Вопрос по созданию подключаемого модуля.
Создал внешнюю обработку 1.epf. В ней в модуле объекта создаю пустышку

Функция ОбработатьСобытиеДиадок(ИмяСобытия, Параметры, СтандартнаяОбработкаДиадок = Истина) Экспорт
               Сообщить("Выполнение обработки");
КонецФункции

Далее пытаюсь его подключить – не удалось инициализировать подключаемый модуль.
Что я делаю не так?

**Comment by volodkindv** [comment]
К какому именно модулю вы пытаетесь его подключить? (версия для обычных или управляемых форм)?
Обратите внимание на код инициализации (где у вас, скорее всего, возникает ошибка):

`Функция ИнициализироватьВнешнийПодключаемыйМодуль()
...
							ВнешнийМодуль = ВнешниеОбработки.Создать(ИмяФайла, Ложь);
														
							ВнешнийМодуль.Инициализировать(ЭтотОбъект);
...
`

Т.е. в подключаемом модуле должна находиться экспортная функция "Инициализировать(парам)"
Готовый подключаемый модуль с типовыми примерами кода можете получить таким образом:
![image](https://cloud.githubusercontent.com/assets/12305552/20164904/84419c0c-a72a-11e6-8814-9ac88d34df96.png)

**Comment by ikolegov** [comment]
Спасибо. Мне нужно заполнить при отправке колонку "Доп. сведения". Для агентского договора заменить поставщика (с собственного на комитента). Как это сделать? И как отлаживать?

**Comment by ikolegov** [comment]
Управляемое приложение

**Comment by volodkindv** [comment]
Вам надо корректно заполнить контент документа, который вы собираетесь отправлять.
Предполагаю, что речь идет о контенте счета-фактуры или ТОРГ-12.
Подробное описание полей данных контентов находится в документации:
http://1c-docs.diadoc.ru/ru/latest/InvoiceContent.html
http://1c-docs.diadoc.ru/ru/latest/Torg12SellerContent.html
Вопрос про отладку сложно понять. Речь про F9 или что-то другое?

**Comment by ikolegov** [comment]
Переопределять процедуры заполнения мне в модуле формы? И там же я могу поставить точку останова?

**Comment by denver069** [comment]
Смотрите примеры в модуле обработки.
