### ISSUE TITLE
Игнорирование pin кода ЭЦП

### ISSUE THREAD

**Issue by Avgurin** [diadoc/diadocsdk-1c-docs#400]
На компьютере хранится ЭЦП в реестре с установленным pin кодом. При работе с ЭЦП через браузер, через обработку 1С pin код запрашивается.
При вызове в коде 1С метода DiadocAPI.CreateConnectionByCertificate(Thumbprint[, Pin ]) с пустым параметром pin происходит успешный вход в Diadoc и отправка документа. 
Если указать pin (правильный или неправильный), метод вызывается с ошибкой, что pin неверный.

Пароли при вводе pin не сохранялись, в CryptoPro сохраненные пароли были удалены. СОМ компонент DiadocCom_5_29_1_530.dll

**Comment by kulakovskaya** [comment]
Добрый день. Рекомендуем обновить компоненту до версии DiadocCom_5_29_6.
Если ошибка сохранится, пришлите скриншот или подробный текст ошибки.

**Comment by GilimkhanovDenis** [comment]
Если ошибка сохраняется, то
1) пройдите [диагностику](https://help.kontur.ru/diadoc) с того компьютера, где хранится сертификат
2) сообщите в тикете номер пройденной диагностики
3) напишите какое значение указываете в параметре Thumbprint метода DiadocAPI.CreateConnectionByCertificate
4) "через обработку 1С pin код запрашивается" - имеется ввиду [модуль Диадок 1С](https://www.diadoc.ru/1c) ?
