### ISSUE TITLE
Реестр сертификатов и Торг12.. Как загрузить из файлов?

### ISSUE THREAD

**Issue by via-ekb** [diadoc/diadocsdk-1c-docs#401]
Перешли на новую версию DiadocCom_5_29_6_541_x64.dll
Стали загружать УПД и УКД в новом формате (приказ 820)
UtdToSend = PackageSendTask2.AddDocumentFromFile("UniversalTransferDocument","СЧФ","utd820_05_01_01",ФайлПолноеИмя);
UtdToSend = PackageSendTask2.AddDocumentFromFile("UniversalTransferDocument","СЧФДОП","utd820_05_01_01",ФайлПолноеИмя);

Но перестали отправляться Торг12 и Реестр сертификатов.. Не понятно их загружать (из файлов).. которые клиент требует в пакет совать вместе с УПД.

Я уж и так и сяк пробовал. 
Torg12ToSend = PackageSendTask2.AddDocumentFromFile("XmlTorg12","ДОП","utd820_05_01_01",ФайлПолноеИмя);
CertificateRegistryToSend = PackageSendTask2.AddDocumentFromFile("CertificateRegistry","default","v1",ФайлПолноеИмя);

В момент отправки ругается.. 
на реестр сертификатов "Невозможно получить данные по ключу: FileName"
на Торг12 "Документ не может быть отправлен в указанном формате"

В старой версии загружались спокойно
Torg12ToSend = PackageSendTask.AddDocumentFromFile("UtdTorg12",ФайлПолноеИмя);
CertificateRegistryToSend = PackageSendTask.AddDocumentFromFile("CertificateRegistry",ФайлПолноеИмя);

[PackageSendTask.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/3967707/PackageSendTask.zip)

**Comment by kulakovskaya** [comment]
Добрый день!
1. Для исправления этой ошибки необходимо заполнить мету - http://1c-docs.diadoc.ru/ru/latest/ComObjects/CustomDocumentToSend.html.
`на реестр сертификатов "Невозможно получить данные по ключу: FileName"`
2.  XmlTorg12 нельзя отправить с функцией "ДОП".
`на Торг12 "Документ не может быть отправлен в указанном формате"`

**Comment by via-ekb** [comment]
На Торг12 помогло вместо "ДОП" указать "default" 
PackageSendTask2.AddDocumentFromFile("XmlTorg12","default","utd820_05_01_01",ФайлПолноеИмя);


Про реестр сертификатов помогли дополнительные три строчки кода (CertificateRegistryToSendMetaData):
CertificateRegistryToSend = PackageSendTask.AddDocumentFromFile("CertificateRegistry","default","v1",ФайлПолноеИмя);
				CertificateRegistryToSend.Comment = "Реестр сертификатов";
				CertificateRegistryToSendMetaData = CertificateRegistryToSend.AddMetadata();
				CertificateRegistryToSendMetaData.Key   = "FileName";
				CertificateRegistryToSendMetaData.Value = Файл.Имя;

P.S. ВНИМАНИЕ писать MetaData как примерах нельзя (слово MetaData зарезервировано)
    MetaData = Third_DocumentToSend.AddMetadata();
    MetaData.Key   = "FileName";
    MetaData.Value = "Имя Файла Для Передачи.xml";
