### ISSUE TITLE
Заполнение контента неформализованных документов

### ISSUE THREAD

**Issue by Aleksey2W** [diadoc/diadocsdk-1c-docs#403]
При добавлении через веб неформализованного документа типа "Ценовой лист" можно указать дополнительные сведения, такие как "вступает в силу", "номер" и пр.

![изображение](https://user-images.githubusercontent.com/49516183/71159820-76de4a00-2257-11ea-9c76-93c4c13da359.png)

Через COM компоненту v5.29.7.549 x64 произвольных систем создаю документ, но контент у него пустой:

```
SendTask = КонтекстОрганизации.CreatePackageSendTask2();
SendTask.OperationId = Строка(ИсходящийДокумент.УникальныйИдентификатор());
SendTask.CounteragentId = ИсходящийДокумент.ИдПолучателя;

ДокументОтправки = SendTask.AddDocumentFromFile("PriceList", "default", "v1", 	ИмяФайлаВоВременномХранилище);
```

![изображение](https://user-images.githubusercontent.com/49516183/71160031-db010e00-2257-11ea-8828-516855e2a2e8.png)

Как указать эти доп. данные ?

**Comment by GilimkhanovDenis** [comment]
Добрый день. Эти данные заполняются аналогично заполнению FileName для Nonformalized документа из [примера](http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html) - данные заполняются через коллекцию Metadata.
Названия ключей для Metadata можно получить в ответе метода [GetDocumentTypes](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetDocumentTypes)

**Comment by Aleksey2W** [comment]
> 
> 
> Добрый день.
> Эти данные заполняются аналогично заполнению FileName для Nonformalized документа из [примера](http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html) - данные заполняются через коллекцию Metadata.
> Названия ключей для Metadata можно получить в ответе метода [GetDocumentTypes](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetDocumentTypes)

т.е. заполнять надо не контент, а Metadata? 
Это касается только неформализованных документов?

В элементах DocumentTypeDescription есть поле RequiresFnsRegistration - это можно считать признаком формализованного документа?

**Comment by Aleksey2W** [comment]
> 
> 
> Добрый день.
> Эти данные заполняются аналогично заполнению FileName для Nonformalized документа из [примера](http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html) - данные заполняются через коллекцию Metadata.
> Названия ключей для Metadata можно получить в ответе метода [GetDocumentTypes](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetDocumentTypes)

 доступные поля для MetadataItem искать в версии? Как узнать какая из них последняя и актуальная?

**Comment by GilimkhanovDenis** [comment]
Я бы собветовал использовать признак [IsFormal](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentTitle.html)
В иерархии он здесь:
[DocumentTypeDescription](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentTypeDescription.html).[DocumentFunction](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentFunction.html).[DocumentVersion](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentVersion.html).[DocumentTitle](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentTitle.html)

**Comment by Aleksey2W** [comment]
> 
> 
> Я бы собветовал использовать признак [IsFormal](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentTitle.html)
> В иерархии он здесь:
> [DocumentTypeDescription](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentTypeDescription.html).[DocumentFunction](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentFunction.html).[DocumentVersion](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentVersion.html).[DocumentTitle](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentTitle.html)

Нууу, счет (ProformaInvoice) вроде не является формализованным, но признак стоит Истина:
![изображение](https://user-images.githubusercontent.com/49516183/71238754-f3cff900-2315-11ea-9842-e1e00183df5a.png)

**Comment by GilimkhanovDenis** [comment]
У ProformaInvoice есть две версии. одна из них формализованная (proformainvoice_01_01), другая (v1), соответственно, - нет

**Comment by Aleksey2W** [comment]
> У ProformaInvoice есть две версии:
> proformainvoice_01_01 - формализованная
> v1 - неформализованная

Актуальными являются обе получается?

> **или разработанному участниками ЭДО для собственного удобства**

т.е. этот всеми участниками документаоборота? Или только внутри Диадока?


И последний вопрос - как определить актуальна версия или нет? У счет-фактуры версий куча, ен совсем понимаем, какую из них надо использовать (все значения брали из DocumentTypeDescription).
![изображение](https://user-images.githubusercontent.com/49516183/71241519-de120200-231c-11ea-816d-1c4fb0e8f543.png)

**Comment by Aleksey2W** [comment]
> 
> 
> У ProformaInvoice есть две версии:
> proformainvoice_01_01 - формализованная
> v1 - неформализованная
> 
> [Чем отличаются формализованные документы от неформализованных в Диадоке?](https://www.diadoc.ru/docs/faq/faq-127): "Формализованный электронный документ — это документ в виде файла с расширением xml, созданного по формату, утвержденному или рекомендованному ФНС **или разработанному участниками ЭДО для собственного удобства**"

в моем понимании "Формализованный" - утвержденный ФНС.
С таким определением поле RequiresFnsRegistration - будет являться таким признаком?

Если ProformaInvoice  можно передать в формате xml - это хорошо, но, я так понимаю, это не факт что его поймут получатели (если он формализован в рамках оператора к примеру а передаю через роуминг)

**Comment by IrinaShmonina** [comment]
@Aleksey2W , подскажите, что вы хотите отправить?

**Comment by Aleksey2W** [comment]
Неформализованный документ в виде PDF, с типом документа "Счет" (ProformaInvoice) укзав при этом дополнительные данные как сумма, номер, дата и пр.
Как это сделать я уже понял, через MetaData, а доступные ключи можно найти в версии.

Вопроса у меня сейчас два:
- какие версии надо выбирать, по какому принципу, или как понять что эта версия последняя из актуальных.
- по какому свойству можно определить, что это формализованный документ (в моем понимании "Формализованный" - утвержденный ФНС; к примеру счет с версией proformainvoice_01_01  который можно передать в формате xml и по версии Диадока - формализованный для меня таковым не является)

**Comment by volodkindv** [comment]
Про формализованные документы можно почитать в [этом комментарии](https://github.com/diadoc/diadocsdk-1c-docs/issues/393#issuecomment-567351864).

**Comment by IrinaShmonina** [comment]
Для того, чтобы отправить неформализованный документ в виде PDF, с типом документа "Счет" (ProformaInvoice), нужно использовать ProformaInvoice и версию v1 - неформализованная

**Comment by Aleksey2W** [comment]
> 
> 
> Про формализованные документы можно почитать в [этом комментарии](https://github.com/diadoc/diadocsdk-1c-docs/issues/393#issuecomment-567351864).

Про формализованные документы я понял и писал выше, что в моем понимании "Формализованный" - утвержденный ФНС. Мое понимание видимо не правильное, но понять для кого он "формализованный" тоже не ясно - для Диадока или для всех операторов.

**Comment by Aleksey2W** [comment]
> 
> 
> Для того, чтобы отправить неформализованный документ в виде PDF, с типом документа "Счет" (ProformaInvoice), нужно использовать ProformaInvoice и версию v1 - неформализованная

Да, я это уже выяснил, собсно как и написал в сообщении выше.
