### ISSUE TITLE
ВНИМАНИЕ! ОШИБКА!!! При получении данных КСФ через GetDynamicContent() часть полей документа пустая!

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#404]
Добрый день.
Работаем через внешние x32/x64 com-компоненты для 1С. Своя реализация работы с вашим АПИ. Работаем на версии АПИ 5.29.7.549.

**Обнаружена ошибка:**
При получении данных КСФ через GetDynamicContent() в составе документа КСФ не заполнены значения сумм НДС к уменьшению и увеличению по строкам состава.

Собственно, все прекрасно видно на картинке из отладчика 1С:
![image](https://user-images.githubusercontent.com/33707226/71227514-36500080-232b-11ea-86f0-beb3fd6542dd.png)

При получении содержимого документа через "старый" GetContent() в составе состава указана сумма уменьшения НДС, а при получении этого же содержимого через "новый" GetDynamicContent() - сумма уменьшения НДС пуста!

Очень хотелось бы, чтобы ошибка была исправлена, т.к. по техническим соображениям важно иметь возможность перечитывать содержимое и уже "устаревших" форматов документов. И хотелось бы получать правильные данные! А тут такая напасть...

Спасибо.

**Comment by IrinaShmonina** [comment]
Здравствуйте,
данная ошибка воспроизводится на документах в устаревшем формате → [93 формат](https://normativ.kontur.ru/document?moduleId=1&documentId=334617&rangeId=295290). Актуальный формат сейчас → [189](https://normativ.kontur.ru/document?moduleId=1&documentId=339567#h1). 
Документы в 93 формате не принимаются налоговой. Лучше использовать документы в действующем формате.

Мы зафиксировали ошибку. На исправление нам понадобится время. По срокам сориентировать не могу. Пока для документов в старом формате можно использовать старую версию метода GetContent()

**Comment by JohnSergeev** [comment]
Добрый день.

**Да мы прекрасно понимаем, что это устаревший формат.**

Просто есть СТАРЫЕ документы из ПРОШЛОГО. И в силу разных причин ИНОГДА всплывает необходимость получить их заново. Естественно, средствами АПИ. И это очень плохо, что новая версия, использование которой рекомендует документация, получает данные некоторых документов с ошибкой!

Надеемся, что это будет исправлено и рекомендуемый GetDynamicContent() начнет работать без ошибок с любыми форматами документов...

**Comment by kulakovskaya** [comment]
Добрый день. Ошибку исправили. Теперь для документов в старом формате можно использовать метод GetDynamicContent().
