### ISSUE TITLE
Полная документация по AddInDiadocAPI.dll

### ISSUE THREAD

**Issue by KrykovLev** [diadoc/diadocsdk-1c-docs#405]
1. Как получить полную документацию по AddInDiadocAPI.dll ? Без использования Reflector
2. Если берем AddInDiadocAPI.dll и настраиваем свою систему работы (без использования модуля для 1с) - нужно ли будет платить за использование АПИ?

**Comment by IrinaShmonina** [comment]
Здравствуйте
1. [Документация](http://1c-docs.diadoc.ru/ru/latest/)
2. Да, использование апи платное. Чтобы узнать цену обратитесь к менеджеру или в тех. поддержку

**Comment by KrykovLev** [comment]
1. В указанном месте, так же как и в (https://readthedocs.org/projects/diadocsdk-1c/downloads/pdf/latest/ ) нет полной информации. Предлагается получать описание объектов через Reflector

**Comment by IrinaShmonina** [comment]
Подскажите, пожалуйста, какой информации вам не хватает?

**Comment by KrykovLev** [comment]
Описание и спецификация всех свойств и коллекций УПД 820 с особенностями заполнения (табл часть, покупатель\продавец,....). Так же и по др. документам

**Comment by volodkindv** [comment]
Здравствуйте.
Документацией по содержимому документов теперь является xsd-схема, получаемая методом [SaveUserDataXSD](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.SaveUserDataXSD).
Для 820-го формата схема также [продублирована](https://api-docs.diadoc.ru/ru/latest/howto/utd820.html#userdataxml) в документации ядра Диадок.
Рекомендую также ознакомиться с тикетами #340 и #339: там вы найдете ответы на часть вопросов, которые у вас появятся.

**Comment by KrykovLev** [comment]
Спасибо!
