### ISSUE TITLE
ВОПРОС! А что это за документы с типом "UnknownDocumentType" и версией "powerofattorney_01_01"?!

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#406]
Добрый день.
Работаем через внешние x32/x64 com-компоненты для 1С. Своя реализация работы с вашим АПИ. Работаем на версии АПИ 5.29.7.549.

Недавно заметили, что в списках обрабатываемых документов "проскакивают" документы у которых Type = "UnknownDocumentType", а Version =  "powerofattorney_01_01".

Если мы правильно поняли, то это доверенность, которую можно отправить через редактор документов на сайте Диадока, при выборе типизации для неформализованных документов.

Но вопрос не в этом. А вот в чем:

**А почему один из поддерживаемых Диадоком типов документов лишь как-то ЧАСТИЧНО поддерживается АПИ для 1С?!**

Тип у него - неизвестный. 
При этом новые функции получения метаданных (через GetDocumentTypes() и далее через Functions и т.д.) возвращают метаданные для этого типа документа. А вот в схемах XSD, возвращаемых через GetDocumentTypes() и далее SaveUserDataXSD() - этого документа уже нет!

Ну и, самое главное, - **его же можно отправить и обработать при работе на сайте Диадок!** 

**Почему тогда с ним нормально не работает АПИ?**

Можете дать какие-то разъяснения по этому поводу?

Спасибо.

**Comment by volodkindv** [comment]
Добрый день.

Мы можем дать "разъяснения" на вопросы "почему", написанные жирным шрифтом и заглавными буквами. Но помогут ли они вам? Предположу, что вам интереснее, как работать с такими документами.

Поле [Type](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html?highlight=Type) имеет свой список значений, который нереально переложить на многообразие документов в ядре Диадок. К тому же поддержка новых типов документов в компоненте требовала её перекомпиляции. Поэтому сейчас альтернативой полю Type в объекте Document является тройка полей: [TypeNamedId](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html?highlight=TypeNamedId), DocumentFunction и Version.

Если вы хотите обрабатывать все возможные документы, то вам лучше переложить логику на эти 3 поля.
