### ISSUE TITLE
Метод GetCounteragentListByInnList 

### ISSUE THREAD

**Issue by nnsidorov22** [diadoc/diadocsdk-1c-docs#407]
Добрый день.
Используем версию модуля Диадок 5.38.01.444 совместно с 1С УТ 11.1
Столкнулись с проблемой при поиске контрагентов в Диадок по кнопке "Найти контрагентов в Диадоке". Запускается форма "Форма поиска и приглашения контрагента" и выполняется поиск и сопоставление контрагентов в Диадок и в нашей учетной системе 1С УТ 11.1. В какой-то момент процедура зависает. В результате анализа процедуры выяснил причину. У нас в справочнике "Контрагенты" по мимо контрагента (юр.лица) заводят так же грузополучателей этого же контрагента. К примеру на 1 юл. лицо "Леруа Мерлен" заведено порядка 50 грузополучателей (это магазины Леруа Мерлен), где ИНН один тот же, а КПП разные. В модуле список контрагентов получаются методом GetCounteragentListByInnList, т.е. только по ИНН. Что в нашем случае приводит к зацикливанию в геометрической прогрессии. Возможно ли этот метод заменить на GetCounteragentListByInnKpp? И как это лучше сделать?

**Comment by IrinaShmonina** [comment]
@nnsidorov22 , здравствуйте
Пожалуйста, обратитесь с данными вопросом к менеджеру или в нашу техническую поддержку
