### ISSUE TITLE
описание ключей AddMetadata() для различных видов документов

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#408]
COM компонента v5.29.7.549 для произвольных систем
1)При отправке СЧЕТ НА ОПЛАТУ новой версией API, как задать сумму НДС счета? Например Key = "TotalSum" добавил сумму по счету, а НДС как??
2)А так же где посмотреть описание ключей AddMetadata() для различных видов документов?
В документации нет описания. 
Пример ниже. Пробовал Vat, VatTotal не выводит НДС.
Из документации "Не имеет фиксированного набора свойств. Описание полей можно понять или из XSD, получаемой методами Organization.SaveUserDataXSD(), 
или, используя объект Reflector. Каждое поле объекта является или строкой, или коллекцией, или DynamicContent’ом"
Функция SaveUserDataXSD() не возвращает XSD например для "ProformaInvoice", "default", "v1".
А объект Reflector не дает описание ключей AddMetadata().
 
Параметры брал из .GetDocumentTypes()
Пробовал разные типы документа, чтобы получить XSD , ошибка Неверный тип документа. Если вместо "v1", использовать «proformainvoice_01_01», то XSD дает, но оно для xml, а нужно файл отправить и чтобы в карточке документа НДС отражалось, а сейчас написано БЕЗ НДС и сумма
//Organization.SaveUserDataXSD(TitleName, Function, Version, DocflowSide, FilePath 
//Organization.SaveUserDataXSD("NonformilizedDocumentContent", "default", "v1", "Seller", "C:\SaveUserDataXSD\ProformaInvoice.xml"); ");  //Неверный тип документа
//Organization.SaveUserDataXSD("ProformaInvoice", "default", "v1", "Seller", "C:\SaveUserDataXSD\ProformaInvoice.xml");  //Неверный тип документа
//Organization.SaveUserDataXSD("ProformaInvoiceContent", "default", "v1", "Seller", "C:\SaveUserDataXSD\ProformaInvoice.xml");  //Неверный тип документа
//Organization.SaveUserDataXSD("NonformilizedDocumentContent", "default", "v1", "Seller", "C:\SaveUserDataXSD\ProformaInvoice.xml"); //Неверный тип документа
 
Документацию смотрел тут
https://diadocsdk-1c.readthedocs.io/ru/dev/ComObjects/CustomDocumentToSend.html
https://diadocsdk-1c.readthedocs.io/ru/dev/ComObjects/MetadataItem.html
https://diadocsdk-1c.readthedocs.io/ru/dev/ComObjects/PackageSendTask2.html#packagesendttask2-adddocumentfromfile
 
https://api-docs.diadoc.ru/ru/latest/proto/CustomDataItem.html
https://api-docs.diadoc.ru/ru/latest/proto/ContractAttachment.html
https://api-docs.diadoc.ru/ru/latest/API_Documents.html
 
Пример
DocumentToSend = PackageSendTask.AddDocumentFromFile("ProformaInvoice", "default", "v1", Pathdoc);                              
Metdata = DocumentToSend.AddMetadata();
Metdata.Key   = "DocumentDate";
Metdata.Value = Date;
                                               
Metdata = DocumentToSend.AddMetadata();
Metdata.Key   = "DocumentNumber";
Metdata.Value = DocNumber;
                                               
Metdata = DocumentToSend.AddMetadata();
Metdata.Key   = "TotalSum";
Metdata.Value = Sum;
                
//Вот туту хочу НДС передать                                 
//Metdata = DocumentToSend.AddMetadata();
//Metdata.Key = "Vat"; //VatTotal
//Metdata.Value = SummNDS;                                  
 
Metdata = DocumentToSend.AddMetadata();
Metdata.Key   = "FileName";
Metdata.Value = СтрТЗКомплект.пИмяФайла;

**Comment by volodkindv** [comment]
Добрый день.
Описания полей Metadata для каждого типа документа лежат в ответе метода GetDocumentTypes, рядом с XsdUrl: [DocumentMetadataItems](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentMetadataItem.html).

**Comment by jakeqwert** [comment]
Разобрался, а вот как понять  для чего используется этот ключ AddMetadata, например, Grounds для ProformaInvoice.

**Comment by jakeqwert** [comment]
Grounds может быть туда указывать основание для счета, например договор указать?

**Comment by volodkindv** [comment]
Grounds - да, для оснований. Договор, заказ, счет, доп.соглашение, ...
Вот метаданные этого типа документа в отладчике:

![image](https://user-images.githubusercontent.com/12305552/72129272-71c47480-3397-11ea-8955-6fc56b20f996.png)

Поле для суммы НДС называется "TotalVat". Следующий код работает:

```
Процедура ТестPST2_Metadata() Экспорт
	
// ...
	Doc = PackageSendTask2.AddDocumentFromFile("ProformaInvoice", "default", "v1", ИмяФайла);
	
	ДобавитьМетаданныеDocumentToSend(Doc, "FileName",		"Счет.xml");
	ДобавитьМетаданныеDocumentToSend(Doc, "TotalSum",		"1234.56");
	ДобавитьМетаданныеDocumentToSend(Doc, "TotalVat",		"789.10");
	
	ДобавитьМетаданныеDocumentToSend(Doc, "DocumentNumber",	"СЧ_123");
	ДобавитьМетаданныеDocumentToSend(Doc, "DocumentDate",	ТекущаяДата());
	
	ДобавитьМетаданныеDocumentToSend(Doc, "Grounds",		"Текст про основания");
	
	// 3. Отправляем.
	РезультатОтправки = PackageSendTask2.Send();
	
	// 4. Покажем url отправленного документа.
	ОтправленныйДокумент = РезультатОтправки.Documents.GetItem(0);
	Сообщить("https://diadoc.kontur.ru" + ОтправленныйДокумент.PathURL);
	
КонецПроцедуры

Процедура ДобавитьМетаданныеDocumentToSend(DocumentToSend, Key, Value)
	
	MetadataItem = DocumentToSend.AddMetadata();
	MetadataItem.Key = Key;
	MetadataItem.Value = Value;
	
КонецПроцедуры	

```

**Comment by volodkindv** [comment]
> Разобрался, а вот как понять для чего используется этот ключ AddMetadata, например, Grounds для ProformaInvoice

Исчерпывающей документации по метаданным всех типов документов сейчас нет.
