### ISSUE TITLE
отправка в 820 формате

### ISSUE THREAD

**Issue by 2michael** [diadoc/diadocsdk-1c-docs#409]
Добрый день. Пользуемся модулем диадок pro 3.2.28.205 
В поддержке сказали, что он работает с 820 форматом, только на получение, а отправлять надо через  подключаемый выполнив доработку? это так? 
в двух словах можете подсказать, что надо доработать, какое событие обрабатывать?

**Comment by IrinaShmonina** [comment]
Добрый день,
Если у вас в ПМ-е нет доработок на сбор контента, то:

1. В ПолучитьТаблицуИспользуемыхВидовДокументов нужно поменять “utd” → “utd820”
![image](https://user-images.githubusercontent.com/19413034/72070756-17320680-330c-11ea-980c-bae910d712f7.png)

2. В ПодготовитьЭлектронныйДокумент добавить условие ВРЕГ(ТипКонтента_XDTO) = ВРЕГ("Utd820SellerContent")
![image](https://user-images.githubusercontent.com/19413034/72070797-2dd85d80-330c-11ea-9345-fec6c520c0f9.png)

3. Изменить в пользовательском режиме: В настройках → Сервисные функции → Сопоставление видов пакетов и документов → Обновить типы документов API → Сопоставить виды документов
![image](https://user-images.githubusercontent.com/19413034/72071032-b48d3a80-330c-11ea-93b1-b80d460457f5.png)

**Comment by 2michael** [comment]
Спасибо большое, все ок
