### ISSUE TITLE
Подвисание при обращении к полю Total объекта Document (COM-компонента 64х)

### ISSUE THREAD

**Issue by 7923655** [diadoc/diadocsdk-1c-docs#41]
Добрый день! Можете помочь, проблема появилась после обновления на версию 5.8.0.138
После получения документа при попытки открыть comОбъект происходит кратковременное провисание на секунд 5-6. А самая проблема встаёт когда пытаемся получить реквизит Total. Время на получение данного реквизита не обоснованно велико. 
![Uploading IMG_14112016_162740.png…]()

![Uploading 111.jpg…]()

**Comment by volodkindv** [comment]
Добрый день!
1) На какой версии компоненты все было хорошо?
2) Воспроизводится ли проблема на компоненте 5.9.0.154?
3) Скриншоты не приложились, перевыложите, пожалуйста. И если речь идет о каком-то уже существующем документе, укажите его boxId и documentId.

**Comment by 7923655** [comment]
Добрый день! На новой компоненте  5.9.0.154 проблема не воспроизводиться.  Но в поле Total странная запись http://prntscr.com/ddhbey

**Comment by denver069** [comment]
Попробуйте новую версию внешней компоненты 5.14.0.176
http://1c-docs.diadoc.ru/ru/latest/Downloads.html
