### ISSUE TITLE
Отправка счетов-фактур в 820 формате

### ISSUE THREAD

**Issue by alexr1983** [diadoc/diadocsdk-1c-docs#410]
Добрый день!
Используем компоненту Diadoc_5_29_7_549.dll.

Получаю объект PackageSendTask2
При попытке вызова метода AddDocument("Invoice", "СЧФ", "utd820_05_01_01") - получаю ошибку "Неверная версия вложения".
При этом с УПД проблем нет:
PackageSendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01") - так работает.

С уважением, Александр.

**Comment by IrinaShmonina** [comment]
Добрый день,
У Invoice нет версии "СЧФ". Нужно вместо "СЧФ" указывать "default"

**Comment by alexr1983** [comment]
А какую функцию контента необходимо указывать?
Если так:
Content.Function = "default"
, то выдает ошибку:
##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 2, Position: 28, /UniversalTransferDocument[1]/@Function: The 'Function' attribute is invalid - The value 'default' is invalid according to its datatype 'String' - The Enumeration constraint failed.

**Comment by NataliaShumikhina** [comment]
Небольшое уточнение. СЧФ - это не версия, а функция. Вот как раз функция должна быть default, а версия должна быть указана utd820_05_01_01, Попробуйте такой вызов для СФ AddDocument("Invoice", "default", "utd820_05_01_01").
Судя по ошибке, вы пытаетесь отправить УПД, для УПД действительно нет функции default, а есть функции СЧФ, СЧФДОП, ДОП. И для УПД вы использовали правильный вызов метода PackageSendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01")

**Comment by GilimkhanovDenis** [comment]
Добавление Счёта-фактуры в задание на отправку:
dd_DocumentToSend = PackageSendTask2.AddDocument("Invoice", "default", "utd820_05_01_01")
Значения берутся из метода [Organization.GetDocumentTypes](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#organization-getdocumenttypes)

В контенте: 
Content.Function = "СЧФ"
Возможные значения берутся из UserDataXSD (можно получить методом [Organization.SaveUserDataXSD](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#organization-saveuserdataxsd), передав в него те же параметры, что и PackageSendTask2.AddDocument)

**Comment by alexr1983** [comment]
Так и делаю:
Set DocumentToSend = PackageSendTask.AddDocument("Invoice", "default", "utd820_05_01_01")
а далее
Content = DocumentToSend.Content.UniversalTransferDocument
Content.Function = "СЧФ"

Но при отправке:
##100[Ошибка сервера Диадок]code:500, HTTP error: The server encountered an internal error or misconfiguration and was unable to complete your request

**Comment by alexr1983** [comment]
В составе пакета был неформализованный документ. Если его исключить, счф отправляет нормально.
После добавления к неформализованному документу
MetaData = SendTaskFromFile.AddMetadata();
MetaData.Key = "FileName";
MetaData.Value = ИмяФайла;
отправилось нормально.

Спасибо за помощь.
