### ISSUE TITLE
Ошибка при работе с API Диадока - метод GetDynamicContent()

### ISSUE THREAD

**Issue by MERCurY84** [diadoc/diadocsdk-1c-docs#411]
Добрый день,
При работе с API Диадока в 1С, в связи со сменой формата УПД (850 приказ), перестал работать метод GetContent(), согласно инструкции необходимо использовать метод GetDynamicContent() (http://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html#Document.GetDynamicContent ).
Однако при вызове его, API возвращает не данные сообщения, не даже неопределено, как указано в инструкции, а цифру 0.  Как нам получить данные сообщения, в чем ошибка?
Ниже скрин с полученным COM объектом (ЭДОбъект) и используемым методом.
Заранее спасибо.
![API](https://user-images.githubusercontent.com/59817250/72235495-7b421c80-35e3-11ea-9678-a219616dee3c.jpg)

**Comment by GilimkhanovDenis** [comment]
Добрый день.
Укажите, пожалуйста, версию используемой компоненты (можно получить методом [DiadocApi.GetFullVersion|http://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html#diadocapi-getfullversion])

**Comment by MERCurY84** [comment]
Версия 5.28.5.501

**Comment by GilimkhanovDenis** [comment]
Ошибка [была исправлена](http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_28_6.html) в 5.28.6

обновите компоненту до актуальной версии

**Comment by MERCurY84** [comment]
Спасибо, попробую
