### ISSUE TITLE
The 'Должн' attribute is invalid

### ISSUE THREAD

**Issue by Sergafan10** [diadoc/diadocsdk-1c-docs#412]
Здравствуйте! Версия AddIn x64 5.29.7.549 при попытке подписания документа получаю ошибку 
**Validation errors: Location: Line: 14, Position: 30, /Файл[1]/ИнфПок[1]/Подписант[1]/ЮЛ[1]/@Должн, Message: The 'Должн' attribute is invalid - The value '' is invalid according to its datatype 'String' - The actual length is less than the MinLength value.**
В SignerDetails запихиваю следующую инфу:

>  ДанныеПодписанта = Новый Структура;	
> ДанныеПодписанта.Вставить("LastName", МассивФИО[0]);
> ДанныеПодписанта.Вставить("FirstName", МассивФИО[1]);
> ДанныеПодписанта.Вставить("Inn", Документ.Organization.Inn);
> ДанныеПодписанта.Вставить("SignerOrganizationName", Документ.Organization.Name);
> ДанныеПодписанта.Вставить("SignerPowers",	"1"); 
> ДанныеПодписанта.Вставить("SignerType",	"1");     
> ДанныеПодписанта.Вставить("SignerStatus", "5");

Нигде нет ничего подобного на "Должн". Откуда он его берёт?

**Comment by IrinaShmonina** [comment]
Здравствуйте,
Согласно 820 приказу поле Должность является обязательным. [Ссылка на приказ](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=306528)

**Comment by Sergafan10** [comment]
Только сейчас порешал. С этим переходом на 820 формат столько головняка вылезло... В итоге смотрел вашу обработку и не придумал ничего лучше, как передрать методы оттуда.
`&НаКлиенте
Процедура ПодписатьИОтправить(Документ)
	
	Структура = Новый Структура;
	Структура.Вставить("OperationContent", "Товары и услуги получены, работы приняты");
	Структура.Вставить("DocumentCreator", Документ.Organization.Name);
	Структура.Вставить("AcceptanceDate", Документ.DocumentDate);
	
	МассивФИО = СтроковыеФункцииКлиентСервер.РазложитьСтрокуВМассивПодстрок(Документ.Organization.Certificate.Name, " ");
	
	ДанныеПодписанта = Новый Структура;	
	ДанныеПодписанта.Вставить("Surname", МассивФИО[0]);
	ДанныеПодписанта.Вставить("FirstName", МассивФИО[1]);
	ДанныеПодписанта.Вставить("Inn", Документ.Organization.Inn);
	ДанныеПодписанта.Вставить("OrganizationName", Документ.Organization.Name);
	ДанныеПодписанта.Вставить("OrganizationPowersBase", "");
	ДанныеПодписанта.Вставить("Patronymic",  МассивФИО[2]);
	ДанныеПодписанта.Вставить("Powers",	"PersonMadeOperation"); 
	ДанныеПодписанта.Вставить("PowersBase", "Должностные обязанности");
	ДанныеПодписанта.Вставить("RegistrationCertificate", "");
	ДанныеПодписанта.Вставить("SignerInfo", "");
	ДанныеПодписанта.Вставить("JobTitle", "Сотрудник");
	ДанныеПодписанта.Вставить("SignerType",	"LegalEntity");     
	ДанныеПодписанта.Вставить("Status", "BuyerEmployee");
	
	Структура.Вставить("Signers", Новый Массив);
	Структура.Signers.Добавить(Новый Структура("SignerDetails", ДанныеПодписанта));
	
	ОтветнаяЗадача = Документ.CreateReplySendTask2("AcceptDocument");

	ОтветныйТитул = СформироватьОтветныйТитулДокумента(Документ, Структура);

	ContentItem = ОтветнаяЗадача.ContentItems.GetItem(0);
	ContentItem.LoadContentFromBase64(Base64СтрокаИзДвоичныхДанных(ОтветныйТитул));
	
	ОтветнаяЗадача.Send();
	
КонецПроцедуры

&НаКлиенте
Функция СформироватьОтветныйТитулДокумента(Document, ПротоКонтент)
	
	ТипКонтента = "Utd820BuyerContent";	
	
	СтрокаBase64 = Document.GetBase64Content("Seller");
	ФайлТитулаПродавца	 = Base64Значение(СтрокаBase64);
	
	СтрокаBase64 = Document.GetBase64Signature("Seller");
	ФайлПодписиПродавца	 = Base64Значение(СтрокаBase64);
	
	Результат = СформироватьОтветныйТитулДокументаНаСервере(ТипКонтента, ПротоКонтент, ФайлТитулаПродавца, ФайлПодписиПродавца);
	
	Возврат Результат;
	
КонецФункции

&НаСервере
Функция СформироватьОтветныйТитулДокументаНаСервере(ТипКонтента, ПротоКонтент, ФайлТитулаПродавца, ФайлПодписиПродавца)
	
	Если НЕ ЗначениеЗаполнено(Обработка) Тогда
		Об = РеквизитФормыВЗначение("Объект");
		ДвоичныеДанные = Об.ПолучитьМакет("ГенерацияXML");
		АдресОбработки = ПоместитьВоВременноеХранилище(ДвоичныеДанные);
		ИмяОбработки   = ВнешниеОбработки.Подключить(АдресОбработки, "", Ложь);
		Обработка	   = ВнешниеОбработки.Создать(ИмяОбработки, Ложь);
	КонецЕсли;
	
	ПротоКонтентXDTO			 = Обработка.ПротоКонтент_В_ПротоКонтентXDTO(ПротоКонтент, ТипКонтента);
	ПараметрыФормированияФайла	 = Обработка.XML_ПараметрыФормированияФайла();  	
	ОбъектXDTO = Обработка.XML_ОтветныйТитул_УПД_820(ПротоКонтентXDTO, ФайлТитулаПродавца, ФайлПодписиПродавца, ПараметрыФормированияФайла);	
	Результат = Обработка.ОбъектXDTO_В_ДвоичныеДанные(ОбъектXDTO);
	
	Возврат Результат;
	
КонецФункции

&НаКлиенте
Функция Base64СтрокаИзДвоичныхДанных(ДвоичныеДанные)
	
	Результат = Base64Строка(ДвоичныеДанные);
	Результат = СтрЗаменить(Результат, Символы.ВК, "");
	Результат = СтрЗаменить(Результат, Символы.ПС, "");
	
	Возврат Результат;
	
КонецФункции
`

**Comment by vbperesadin** [comment]
Добрый день!
Точно такая же ошибка возникает, при таких же условиях. Но у меня нет вашего коннектора. Можете сказать в какой из тегов нужно поставить Должность? 
Ошибка возникает если заполняю SignerDetails  и оставляю пустым SignerReference
Если же заполняю SignerReference

Signer = Content.Signers.AddItems();
Signer.SignerReference.BoxId = BoxID;
Signer.SignerReference.CertificateThumbprint = thumbprint;

то выходит ошибка @Inn
