### ISSUE TITLE
ВОПРОСЫ по работе с Reflector

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#413]
Добрый день.
Работаем через внешние x32/x64 COM-компоненты для 1С. Своя реализация работы с вашим АПИ. Работаем на версии АПИ 5.29.7.549.

Не так давно (в версии 5.28.7), скажем так, с нашей подачи, хотя и несколько неожиданно, был добавлен новый объект – **Reflector**.

Наконец-то нашлось время попробовать с ним поработать. По результатам этой работы хотелось бы задать несколько вопросов.

Напомню, что всё, что в итоге привело к появлению в вашем АПИ данного объекта, началось с выдвинутой нами идеи о том, что было бы здорово иметь возможность получать все данные документов, получаемые через **GetDynamicContent()**, как бы «сами по себе» – без ориентации на XSD-схемы, возвращаемые **SaveUserDataXSD()**, т.к. по умолчанию 1С как-то не особо хочет с ними «дружить».

В итоге получилось даже лучше. Reflector позволяет делать даже больше. Еще раз спасибо за такой полезный объект!

Но при экспериментах с получением данных документов с использованием Reflector’a появилось несколько вопросов:

### ВОПРОС №1
Когда мы получаем поле составного типа (т.е., некое поле, содержащее в себе другие поля – например, Counteragent, у которого «внутри» есть свои поля - INN, KPP и т.д.):
![image](https://user-images.githubusercontent.com/33707226/72321989-f9401980-36f0-11ea-8993-aa68fc79d02e.png)

То возникает первая «странность»:

Если мы через Reflector получаем подобные поля для объекта документа, то тип таких составных полей будет «**VT_PTR**».

Но, если мы получаем подобное же поле для объекта динамического контента (например, для какого-то поля из контента Document.GetDynamicContent(«Seller») – например, TransferInfo), то тип такого поля будет уже почему-то «**VT_DISPATCH**».

В принципе это не составляет особой проблемы, но все-таки хочется задать

### Вопрос:
Понятно, что _«Оно исторически так сложилось…»_ И «_Это на самом деле разные данные…»_. Но может быть как-то возможно привести их к единому типу? Это же абсолютно одинаковые по своей структуре составные поля, которые просто содержат в себе еще какие-то другие поля, а не просто какие-то конкретные значения!

### ВОПРОС №2
Когда мы с помощью Reflector’а получаем поле, содержащее в себе коллекцию каких-то данных, например, данные состава документа:
![image](https://user-images.githubusercontent.com/33707226/72322137-51771b80-36f1-11ea-9f2c-28cc54a52af2.png)

То возникает вторая «странность» (куда более серьёзная!):

Для коллекции, возвращаемый Reflector’ом тип данных (например, для Документ.GetDynamicContent("Seller").UniversalTransferDocumentWithHyphens.Table.Item с картинки выше) **ВООБЩЕ НИКАК не указывает на то, что это коллекция!**

У поля коллекции документа будет такой же тип «**VT_PTR**», как для составных полей документа. У поля коллекции динамического контента будет такой же тип «**VT_DISPATCH**», как для составных полей динамического контента.

И поэтому для понимания того, что это у нас именно коллекция, а не поле составного типа приходится использовать крайне странный подход – если это поле с типом «**VT_DISPATCH**» (или «**VT_PTR**») и список включенных в него полей, получаемый через GetPropertiesNames(), состоит из одного поля с названием «Count» – тогда считаем, что это не поле составного типа, а поле коллекции. Другого пути мы не нашли!

Это какая-то весьма «зыбкая фигня», т.к. работать она будет ровно до того момента, пока не найдется поле составного типа, в котором реально будет только одно вложенное поле, и оно будет называться «Count»! В этом случае отличить коллекцию от составного типа с помощью объекта, который вроде как для этого и предназначен, станет совершенно невозможным!

В связи с этим возникает

### Вопрос:
А можно как-то сделать, чтобы по данным типизации можно было бы отличить поле составного типа от поля, содержащего коллекцию?

А то как-то странно выходит – при использовании объекта, показывающего «внутреннюю структуру» других объектов почему-то не хватает данных типизации и приходится пользоваться весьма странными костылями для того, чтобы понять, что перед тобой – составное поле, содержащее в себе другие поля или поле, содержащее в себе коллекцию!

Ждем ваши комментарии!

Большое спасибо.

**Comment by volodkindv** [comment]
Добрый день.

Можем реализовать примерно в таком виде:
```
//имеем content - это динамический контент utd820_05_01_01

reflector = Новый COMОбъект("AddIn.Diadoc.Reflector");
item_desc = reflector.Describe(content.UniversalTransferDocument.Table.Item) //Item - IValueCollection

Если item_desc.GetInterfaceName() = "IValueCollection" Тогда
//...
КонецЕсли;
```

Такой вариант подойдет?

**Comment by GilimkhanovDenis** [comment]
Пример обхода элементов DynamicContent'а есть в http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_reflect_object.html

В том числе и обход коллекций
