### ISSUE TITLE
ПРЕДЛОЖЕНИЕ по расширению функционала Reflector'a

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#414]
Добрый день.
Работаем через внешние x32/x64 COM-компоненты для 1С. Своя реализация работы с вашим АПИ. Работаем на версии АПИ 5.29.7.549.

Не так давно (в версии 5.28.7), скажем так, с нашей подачи, хотя и несколько неожиданно, был добавлен новый объект – **Reflector**.

Наконец-то нашлось время попробовать с ним поработать. 

**По результатам этой работы хотелось бы выдвинуть одно предложение, реализация которого, как нам кажется, может здорово помочь как непосредственно в использовании Reflector’а, так и в том, что им станут чаще и охотнее пользоваться.**

**А также вообще может здорово облегчить работу с любыми предоставляемыми через АПИ данными.**

Напомню, что всё, что в итоге привело к появлению в вашем АПИ данного объекта, началось с выдвинутой нами идеи о том, что было бы здорово иметь возможность получать все данные документов, получаемые через **GetDynamicContent()**, как бы «сами по себе» – без ориентации на XSD-схемы, возвращаемые **SaveUserDataXSD()**, т.к. по умолчанию 1С как-то не особо хочет с ними «дружить».

В итоге получилось даже лучше. Reflector позволяет делать даже больше. Еще раз спасибо за такой полезный объект!

При попытке получения структуры документа с использованием Reflector’a, мы пришли к следующему коду (Пример тестовый, т.к. данные по Seller’у и Buyer’у в нем получаются «пыром» через попытку. Но в остальном - рабочий):

Основная вызываемая ф-я получения структуры объекта документа:
![image](https://user-images.githubusercontent.com/33707226/72325701-66f04380-36f9-11ea-9b2b-80400d514132.png)

Промежуточная ф-я получения данных структуры заданного контента:
![image](https://user-images.githubusercontent.com/33707226/72325714-72436f00-36f9-11ea-80ad-0b0d002ae3ff.png)

И ф-я получения полей и их значений (с учетом всех «костылей» для обхода текущих «странностей» Reflector'a – если бы их не было, то она была бы в два раза короче):
![image](https://user-images.githubusercontent.com/33707226/72325747-85563f00-36f9-11ea-9211-2413b2c70f60.png)

Эти три небольших функции получают все поля и данные в них по документам любого типа и возвращают их в виде структуры 1С. В которой составные поля – это также структуры:
![image](https://user-images.githubusercontent.com/33707226/72325901-d6fec980-36f9-11ea-9697-a00092424ea2.png)

А коллекции – массивы, содержащие структуры:
![image](https://user-images.githubusercontent.com/33707226/72325921-debe6e00-36f9-11ea-942d-cbd59a8d3660.png)

![image](https://user-images.githubusercontent.com/33707226/72325933-e54ce580-36f9-11ea-9eb7-b7530a48e88a.png)

И так далее вниз по иерархии структуры объекта.

**Т.е. вышеуказанные функции с помощью Reflector’a транслируют данные COM-объекта АПИ в «обычную» структуру 1С.** 

В ней, во-первых, оказываются все данные документа «в терминах АПИ» как бы «сами по себе», без какого-либо предварительного знания о структуре конкретного обрабатываемого объекта. И, во-вторых, это уже простая структура – обычный объект 1С, гораздо более удобный для дальнейшей обработки, чем COM-объект АПИ. С ним можно работать всеми стандартными средствами 1С (например, можно изменить набор полей структуры или записать её в какой-либо регистр 1С и т.п.).

Вернёмся к реализации функции получения данных:
![image](https://user-images.githubusercontent.com/33707226/72325966-f564c500-36f9-11ea-825b-bc944c97214c.png)

Обратите, пожалуйста, внимание на выделенный код:
![image](https://user-images.githubusercontent.com/33707226/72325981-fd246980-36f9-11ea-80cd-be882432ac40.png)

Это просто получение значения из текущего COM-объекта АПИ. А его особенность вот в чем. Сделаем замер производительности (по большому количеству документов (341 шт.) для усреднения результатов) и увидим:
![image](https://user-images.githubusercontent.com/33707226/72326148-568c9880-36fa-11ea-85ea-fcef5e372b0d.png)

Т.е. операция получения данных занимает около 60% от всего времени обработки документов!

А, если к этому добавить еще время операций получения данных и контентов через АПИ:
![image](https://user-images.githubusercontent.com/33707226/72326014-10cfd000-36fa-11ea-8beb-06d5ab54c5ab.png)
, то получится, что они займут **более 98% времени обработки данных**.

И, вот после взгляда на все это у нас сформировалось

### Предложение по расширению функционала Reflector’a:

---
Было бы здорово, если бы вы добавили в рефлектор еще одну функцию – что-то типа **GetFullObjectStructure()**, которая (быстро, на С++) просто тупо делала бы всё тоже самое, что делает сейчас (медленно, на 1С) показанный ранее комплект функций!
---

Т.е. она бы просто брала поданный на вход объект АПИ и возвращала все его содержимое со всеми вложенными полями и коллекциями, собранное в структуру 1С, как это делает показанный комплект функций 1С.

Чтобы вместо вышеуказанных функций можно было бы, например, получить структуру документа так:
![image](https://user-images.githubusercontent.com/33707226/72326295-abc8aa00-36fa-11ea-8fb5-b4c0c891f2a7.png)

И чтобы она работала именно как показано выше. Т.е., если, например, на вход подано «Неопределено» (когда, например, у документа нет контента «Seller»), то не будет никакого вылета по ошибке, а просто в структуру сткСодержимое запишется поле «Seller» со значением «Неопределено».

**Внутренняя реализация подобного получения данных была бы намного быстрее их формирования кодом 1С, что позволило бы обрабатывать документы (и не только их! – вообще любые объекты, получаемые через АПИ) гораздо быстрее и проще.**

Очень надеемся, что вы рассмотрите наше предложение!

Ждем ваши комментарии.

Спасибо!

**Comment by volodkindv** [comment]
Добрый день.
Мы провели замеры на своей стороне, на произвольном наборе документов. Смотрели время выполнения кода:
`КонтентНиже = Контент[ИмяПоля]`

| Где | Обращений | Общее время | Скорость |
| У нас | 111 000 | 6,38 с | **0,057** / 1000 |
| У вас | 266 000 | 377 с | **1,417** / 1000 |

Т.е. в ваших тестах обращение к полям выполняется в 25 раз медленнее, чем в наших тестах.
В чем причина такого поведения - не ясно. Какая у вас версия платформы 1С?

Можете попробовать провести замеры на одном единственном документе? Возможно, дело в специфике конкретного документа. Если так, то нам нужен пример этого документа (прямо XML), чтобы погонять его на своей стороне.

**Comment by volodkindv** [comment]
Предложение насчет GetFullObjectStructure() реализовать сейчас не готовы.
Это будет слишком специфичная для 1С8 вещь. Компонентой пользуются также в 1С77 и в других системах: нам встречались клиенты с Python, Delphi, C++, C#, даже MS SQL.
Поэтому можем только в сторону ускорения текущих методов подумать.

**Comment by JohnSergeev** [comment]
Добрый день.
Спасибо за информацию.

По поводу **GetFullObjectStructure()** понятно. 

По поводу скорости КонтентНиже = Контент[ИмяПоля] - извиняюсь за задержку, сегодня-завтра попробуем еще погонять этот код и скинуть вам результаты.

Работаем на следующей платформе 1С: 1С:Предприятие **8.3 (8.3.10.2375)**.

Разница **в 25 раз** кажется совершенно дикой!

А не может она быть как-то связана с тем, что мы во Владивостоке, а вы к себе немного поближе (;-)) и 1С как-то странно в замерах учла то, что мы, возможно, просто дольше получаем документы по сети? (хотя эти операции вроде в замере отдельно стоят...)

Не совсем понятен ваш вопрос про документ - показанные результаты замера производительности сделаны **по комплекту из 341 разных документов**. Т.е. не делали много раз одно и то же по какому-то одному документу, а запустили на пачке из 341 уникального документа, упавшими нам в тот день с утра.

Или вы предполагаете, что был какой-то особенный документ в этой пачке, который и устроил нам все проблемы с производительностью?

**Comment by JohnSergeev** [comment]
А вы прямо вот тот же код у себя повторили, что я на скрине показал?

У нас, кстати, изначально появилось ощущение, что вариант косвенного обращения Объект["ИмяПоля"] сам по себе работает почему-то медленнее прямого обращения Объект.ИмяПоля.

Но потом подумали, что наверное все-таки показалось.

**Comment by volodkindv** [comment]
> 1С как-то странно в замерах учла то, что мы, возможно, просто дольше получаем документы по сети? (хотя эти операции вроде в замере отдельно стоят...)

Получение контента действительно стоит отдельно. Т.е. в сеть компонента ходит в методе GetDynamicContent(). 

> Или вы предполагаете, что был какой-то особенный документ в этой пачке, который и устроил нам все проблемы с производительностью?

Да, это один из возможных вариантов. 
Мы тоже прогоняли замеры на пачке разнородных документов. Для чистоты эксперимента хорошо бы сделать это на одинаковом наборе данных. 341 разный документ мы смоделировать не сможем. Поэтому давайте сделаем так.
Вы у себя проведите замеры на 2-3 выборках меньших размеров. И на 1 документе циклом.
Если скорость обращения Объект["ИмяПоля"] будет примерно одинакова во всех случаях и близка к нашей, то, скорей всего, среди тех 341 документа есть какой-то особенный. Его можно вычислить постепенным делением выборки пополам.

Если скорость будет по-прежнему сильно отличаться от нашей, то вам достаточно выбрать один документ и отправить нам (прямо Xml). Мы сможем смоделировать поведение компоненты на таком же документе и той же версии платформы. После этого станет более понятно, куда копать.

**Comment by volodkindv** [comment]
> А вы прямо вот тот же код у себя повторили, что я на скрине показал?
Не совсем, но смысл тот же самый.
На всякий случай приложите сюда листинг текстом.

**Comment by JohnSergeev** [comment]
Ок. Все понятно. Сегодня начну, завтра доделаю и отпишусь (у нас уже поздновато).

**Comment by JohnSergeev** [comment]
В принципе, я еще дополнительно скину списки ID документов, на которых буду проверять. Тогда вы у себя как раз и сможете полностью вплоть до документов повторить то, что происходило в меня.

**Comment by volodkindv** [comment]
> В принципе, я еще дополнительно скину списки ID документов, на которых буду проверять. Тогда вы у себя как раз и сможете полностью вплоть до документов повторить то, что происходило в меня.

У нас нет доступа к содержимому ваших документов. Поэтому и прошу предоставить именно xml файлы, из которых мы потом создадим свои документы для тестов. Если там что-то конфиденциальное внутри, предварительно отредактируйте их.

**Comment by JohnSergeev** [comment]
Добрый день.

Провели дополнительный анализ, и выявилась очень интересная ... эээ... фигня. Почему-то в рамках этого тестирования замер производительности 1С показывает очень странные результаты, слабо совпадающие с реальным замером времени! 

**Первое.**
Нам нужна отправная точка, о чем мы с вами ранее забыли. Т.к. непонятно на чем запускали код мы, на чем вы - как мы сравниваем время - загадка! Итак, у меня все запускалось на следующей системе:

Win7 Pro
![image](https://user-images.githubusercontent.com/33707226/72956332-12308500-3deb-11ea-9327-ec4e47b4963a.png)
1С:Предприятие 8.3 (8.3.10.2375)
АПИ ЭДО: COM x86 5.29.7.549

**Второе.**
Делаем запуск кода с замером производительности и замером реального времени с использованием ТекущаяУниверсальнаяДатаВМиллисекундах().

Делаем запуск кода с таким обращением поля (как было ранее):
**КонтентНиже = Контент[ИмяПоля]**

Получаем результаты по 126 документам УПД и УКД от 19.01.2020:
![image](https://user-images.githubusercontent.com/33707226/72956402-5d4a9800-3deb-11ea-9386-5bc2ef2585e0.png)
Опять дикое время на выполнение КонтентНиже = Контент[ИмяПоля].

Смотрим, сколько затрат времени вообще показывает замер:
![image](https://user-images.githubusercontent.com/33707226/72956466-8ec36380-3deb-11ea-9c69-df57466e2478.png)
И сколько намерили засекая реальное время:
![image](https://user-images.githubusercontent.com/33707226/72956487-9b47bc00-3deb-11ea-9c9c-39b7a0f65c48.png)
Есть небольшая погрешность, но сейчас она не существенна.

А вот теперь делаем запуск версии в которой косвенное обращение:

**КонтентНиже = Контент[ИмяПоля]**

заменено на прямое, "через точку". В нашем случае выполняем такой код:

**КонтентНиже = Неопределено;**
**Выполнить("КонтентНиже = Контент." + ИмяПоля);**

Получаем результаты по тем же 126 документам УПД и УКД от 19.01.2020:
![image](https://user-images.githubusercontent.com/33707226/72956570-e82b9280-3deb-11ea-875a-f26f6ece7cee.png)

Фантастика! 50% превратились в 3%! Вместо 177 секунд - 6.6! Замер показывает, что затрачено намного меньше времени:
![image](https://user-images.githubusercontent.com/33707226/72956601-11e4b980-3dec-11ea-85d6-f09440d341be.png)

Ура! Мы победили! Проблема в самом косвенном обращении через []!

НО! Вот сюрприз... А сколько же времени намерили по секундомеру?
![image](https://user-images.githubusercontent.com/33707226/72956622-2759e380-3dec-11ea-80b3-7ba6403a1b30.png)

**Тааддам! Даже больше!** Вот это поворот ;-)

Реально затраченное время даже рядом не лежало с тем, что показывает замер производительности!

Пока единственное предположение, что подобная ерунда как-то связана с "Выполнить". Но по факту получается, что замер выдает одни данные, а в реальности затраты совершенно другие.

Может, конечно, проблема в адресации через [] все-таки есть... Но это уже, похоже, сможете проверить только вы.

**Третье.**
Произвели поиск "плохого" документа на котором предположительно падает скорость. К сожалению, таких документов нет - проблемы со скоростью постоянны.
Выложил на [Яндекс.Диск](https://yadi.sk/i/IwsczgJ9LTaDtQ) файл Excel с замерами времени по 3 дням с 18 по 20 января 2020 года.

Там видно, что никаких всплесков по времени нет и, если брать медианы затрат по каждому дню, то они все оказываются в районе 2-2.1 сек. (а максимум не выскакивает за 8.3 сек - и то на больших документах с объемным составом УПД).

Т.е., получается, что это у нас просто скорость такая. И, если у вас на сопоставимом железе она **в 25 раз больше,** то это вообще непонятно что - может быть какая-то несовместимость с версией платформы, какая-то ошибка именно в COM x32 компоненте или еще чего... Было бы здорово найти. 

**Мы бы не отказались от 20-кратного увеличения скорости обращения к полям документов!**

Прилагаю свой код, который тестировали. Файл на [Яндекс.Диск.](https://yadi.sk/d/IM_ZT0XkHOS7Zw)

Думаю, для проверки скорости работы доступа к полям документов с вашей стороны доступ именно к нашим документам не требуется, т.к. мы не нашли проблемные документы, на которых все "тупит" - у нас в среднем так медленно. Поэтому сравнить можно с любым другим набором документов. Только напомню, что проверялось на УПД и УКД.

Но, если все-таки действительно и в этом случае нужны наши файлы, то пишите - попробуем как-то организовать выгрузку XML (сами-то файлы выгрузить не проблема, но если бухгалтерия упреться, то, во-первых, замаемся удалять оттуда "секретную" инфу, а , во-вторых, в итоге это будут все равно не именно наши файлы, и даже не такие же, а просто частично похожие. И какой тогда в этом смысл - не очень ясно).

Спасибо.

**Comment by volodkindv** [comment]
Спасибо за исследования и за код.
Кажется, что причина лежала на поверхности, прямо в первом скриншоте. Просто не хватило внимания.

```
Функция ПолучитьДанныеЧерезReflector(пДокументId)
	...
	

	// Следующая строка приводит к чтению данных объекта Document, а не DynamicContent.
	// Здесь скорость получения полей может плавать, т.к. некоторые из них вычисляются "лениво" - только при обращении к ним, и запрос идет через HTTP
	// Resolutions вроде бы и еще какие-то поля, точно сейчас не вспомню.
	сткСодержимое.Вставить("Document", ПолучитьДанныеКонтента(Документ));
	
	Попытка
		// А здесь мы уже действительно обращаемся именно к динамическому контенту
		// К этому моменту он уже загружен через HTTP и лежит в оперативной памяти, поэтому скорость работы с ним высокая.
		сткСодержимое.Вставить("Seller", ПолучитьДанныеКонтента(Документ.GetDynamicContent("Seller")));
	Исключение
	КонецПопытки;
	
	Попытка
		сткСодержимое.Вставить("Buyer", ПолучитьДанныеКонтента(Документ.GetDynamicContent("Buyer")));
	Исключение
	КонецПопытки;
	
	Возврат сткСодержимое;
КонецФункции

```

Попробуйте устроить замеры без строки с `ПолучитьДанныеКонтента(Документ)`. Так скорость должна стать ближе к цифрам с нашей стороны.

**Comment by JohnSergeev** [comment]
Добрый день.

Провел сравнение с предложенным вами вариантом (без получения данных самого документа).

Похоже, дело действительно в указанной вами причине.

Все включено:
![image](https://user-images.githubusercontent.com/33707226/73146545-06043a80-40ff-11ea-8ff2-281d02071b8b.png)
Все время обработки комплекта документов = ~ 346 сек.

Убрано получение данных для самого документа:
![image](https://user-images.githubusercontent.com/33707226/73146588-2cc27100-40ff-11ea-8400-725575b2bfdc.png)
Все время обработки комплекта документов = ~ 201 сек.

Если брать полное время на обработку комплекта, то выходит, что разница в скорости будет где-то в районе 1.5 раз.

Если рассматривать разницу в скорости обработки самой операции:
**КонтентНиже = Контент[ИмяПоля];**,

то с учетом разницы в количестве выполняемых операций получается:
![image](https://user-images.githubusercontent.com/33707226/73146682-a22e4180-40ff-11ea-8322-dfc58c222c89.png)

Т.е., когда мы не получаем данные самого документа скорость выполнения **КонтентНиже = Контент[ИмяПоля];** больше примерно в 10 раз! Правда, никак не дотягивает до заявленных вами 25 раз.

Тут сразу появляются три вопроса:
1. А вы можете привести список полей документа, которые вот так вот медленно отложенным обращением получаются (чтобы не искать их "методом тыка")?
2. А в чем может быть дело, что у меня получилась разница в 10 раз, а у вас в 25 раз? Даже, если вы не учли уменьшившееся количество операций во втором случае, то там все равно не будет такого разрыва... В чем может быть дело?
3. А как-то можно сделать, чтобы и поля документа можно было бы получать быстро? Эти данные в общем-то нужны... И какая разница где они лежат, если при обращении к ним все настолько замедляется?

Спасибо за информацию.
Ждем ваши комментарии!

**Comment by volodkindv** [comment]
Добрый день.

> 1. А вы можете привести список полей документа, которые вот так вот медленно отложенным обращением получаются (чтобы не искать их "методом тыка")?

Сейчас нет. Надо глубоко копать код. 

> 2. А в чем может быть дело, что у меня получилась разница в 10 раз, а у вас в 25 раз? Даже, если вы не учли уменьшившееся количество операций во втором случае, то там все равно не будет такого разрыва... В чем может быть дело?

Здесь уже может играть роль разница в железе, ОС, наборе документов или еще чем угодно. 

> 3. А как-то можно сделать, чтобы и поля документа можно было бы получать быстро? Эти данные в общем-то нужны... И какая разница где они лежат, если при обращении к ним все настолько замедляется?

Как минимум был момент с Author в http://1c-docs.diadoc.ru/ru/latest/ComObjects/ResolutionStatus.html. В [HTTP API](https://api-docs.diadoc.ru/ru/latest/proto/ResolutionStatus.html) о нем нет подробной информации, только ID. Чтобы получить ФИО, приходится делать дополнительный HTTP запрос. Это сделано "лениво", т.е. http запрос происходит только тогда, когда вы обращаетесь к этому полю в компоненте. Здесь можно продумать какой-нибудь механизм кэширования, но это отдельная задача.

**Comment by Dilise** [comment]
Коллеги, добрый день!
Очень интересны ваши замеры производительности, но возникает один вопрос:
Почему, если необходим полный перечень всех полей контента, не используете все же метод получения XSD схемы? Сам не замерял, но думаю, что там будет все на порядок быстрее.

**Comment by Dilise** [comment]
Хотя, наши программисты тоже выбрали рефлектор вместо XSD схемы, но на производительность никто не смотрел, ввиду среднего времени работы рег.задания по получению документов ~ 2 - 3 мин каждые 20 мин.

**Comment by volodkindv** [comment]
Кажется, что исходный вопрос исчерпан. Если будут новые, то их лучше оформлять отдельным тикетом. Если надо что-то еще уточнить в рамках исходного вопроса, переоткройте тикет.
