### ISSUE TITLE
неверная версия вложения при вызове AddDocument

### ISSUE THREAD

**Issue by ejig** [diadoc/diadocsdk-1c-docs#415]
Добрый день
Использую COM компонент v5.29.8.554 x86 для произвольных систем
При вызове PackageSendTask2.AddDocument('Invoice', 'СЧФ', 'utd820_05_01_01')
и PackageSendTask2.AddDocument('XmlTorg12', 'ДОП', 'utd820_05_01_01_hyphen')
выходит ошибка "неверная версия вложения"
Подскажите в чем ошибка

**Comment by kulakovskaya** [comment]
Нельзя отправить XmlTorg12 с функцией "ДОП" и Invoice с функцией СЧФ. Вместо данных функций нужно указать "default".
Также рекомендуем Вам проверять с помощью метода GetDocumentTypes https://api-docs.diadoc.ru/ru/latest/http/GetDocumentTypes.html#getdocumenttypes какие типы документов доступны для ящика и какие функции используются для нужного типа документа.
