### ISSUE TITLE
SignerDetails not found for boxId

### ISSUE THREAD

**Issue by evilless63** [diadoc/diadocsdk-1c-docs#416]
При попытке формирования СЧФДОП по 820 приказу, раньше я указывал boxId вида
"45dd214c6c5f4517a39c90xxxx5dxxxx@diadoc.ru", документы отправлялись. Документы с нового года не отправляются, сообщает об ошибке SignerDetails not found for boxId.
Каким форматом должен быть boxId, чтобы все успешно отправлялось ?

Пробовал отправлять в формате GUID, "45dd214c-6c5f-4517-a39c-90xxxx5dxxxx", в таком же, как и у получателя.
так же не находит ящик.

**Comment by volodkindv** [comment]
Дело не в формате ящика, а в том. что SignerDetails от 155 приказа не подходят к 820 приказу. Вам необходимо заново указать SignerDetails для данного сертификата в ящике через
http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.CreateSetExtendedSignerDetailsTask.

**Comment by evilless63** [comment]
Спасибо, заработало !
