### ISSUE TITLE
Проблема с отправкой УПД

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#417]
Добрый день.
Ящик организации 2ba16b1e6df1488fa5f5f13ba8696f78@diadoc.ru.
При попытке отправки документов (14.01.2020 16:00 - 16.01.2020 11:00) он либо отправляется, либо возвращается ошибка: "**##100[Ошибка сервера Диадок]code:402, HTTP error: Пакет документов исчерпан. Отправка документов контрагентам недоступна.**". Подскажите, с чем это может быть связано, т.к. менеджер по сопровождению клиентов Диадок говорит, что с пакетом проблем нет. Нужно отправить большое количество документов, а из-за возникающей ошибки процесс стоит на месте, т.к. возникает она часто.

**Comment by volodkindv** [comment]
Добрый день.
Вашей проблемой уже занимаются. Номер обращения - 24424343.

**Comment by prog22** [comment]
Спасибо. Вопрос решен.

**Comment by Uerpec** [comment]
> Спасибо. Вопрос решен.

В чем проблема была, подскажите пожалуйста?
