### ISSUE TITLE
При подписании через COM-API набор свойств подписанта не соответсвует API

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#418]
Текущая версия API : DiadocCom_5_28_1_479.dll
При попытке формирования контента подписания покупателя нижеприведённым кодом
![image](https://user-images.githubusercontent.com/3480769/72544089-c7b58280-3897-11ea-8c36-8cadf8b00aa3.png) получаю ошибку 
"Поле объекта не обнаружено (Powers) ВызватьИсключение ОписаниеОшибки();"

Смотрю структуру свойств объекта SignerDetails, вижу следующую структуру
![image](https://user-images.githubusercontent.com/3480769/72544217-faf81180-3897-11ea-8b7f-69c064bde183.png)

В документации для 1с такие свойства не объявлены 
http://1c-docs.diadoc.ru/ru/latest/ComObjects/ExtendedSignerDetails.html
https://buildmedia.readthedocs.org/media/pdf/diadocsdk-1c/latest/diadocsdk-1c.pdf

Зато эти свойства есть в документации на HTTP-API:
https://api-docs.diadoc.ru/ru/latest/proto/utd/ExtendedSigner.html

Доступ к API получен на ежегодной платной основе, требую оперативно исправть баг, а именно привести в соответствие документацию и набор свойств объектов

**Comment by kulakovskaya** [comment]
Добрый день. Вы заполняете DynamicContent http://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html:
При использовании динамического контента ориентироваться на описание старых версий контента (например, UtdSellerContent) нельзя - отличается как набор полей, так и допустимые для них значения. Всё описание теперь находится в соответвующей XSD схеме.

**Comment by volodkindv** [comment]
Более подробно можно почитать обсуждение в этом [тикете](https://github.com/diadoc/diadocsdk-1c-docs/issues/366).
Пример кода есть в [комментарии]https://github.com/diadoc/diadocsdk-1c-docs/issues/366#issuecomment-539041927) (только там надо еще добавить заполнение SignerDetails.Position).

**Comment by MikeFilimonov** [comment]
> Более подробно можно почитать обсуждение в этом [тикете](https://github.com/diadoc/diadocsdk-1c-docs/issues/366).
> Пример кода есть в [комментарии][#366 (comment)](https://github.com/diadoc/diadocsdk-1c-docs/issues/366#issuecomment-539041927)) (только там надо еще добавить заполнение SignerDetails.Position).

Спасибо, Денис, но в документации это нужно отражать
