### ISSUE TITLE
Добрый день. Вы заполняете DynamicContent http://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html:

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#419]
Добрый день. Вы заполняете DynamicContent http://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html:
При использовании динамического контента ориентироваться на описание старых версий контента (например, UtdSellerContent) нельзя - отличается как набор полей, так и допустимые для них значения. Всё описание теперь находится в соответвующей XSD схеме.

_Originally posted by @kulakovskaya in https://github.com/diadoc/diadocsdk-1c-docs/issues/418#issuecomment-575481015_

Почему в документации эти поля в SignerDetails не помечены как устаревшие?

**Comment by MikeFilimonov** [comment]
SignerDetails не отмечен как устаревший, это вводит в заблуждение, ввиду отсутствия сквозного примера

**Comment by IrinaShmonina** [comment]
Добрый день,
В документацию http://1c-docs.diadoc.ru/ru/latest/ComObjects/ExtendedSigner.html  добавили информацию про устаревшие поля
