### ISSUE TITLE
Как восстановить (узнать) OperationId?

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#42]
Документ был отправлен, Id по какой-то причине были потеряны, документ можно найти например через "GetDocumentsTask" и восстановить DocumentId, а как при этом узнать какой был OperationId (он точно был)?

**Comment by volodkindv** [comment]
Сейчас никак. Максимум, что можно сделать, по LetterId и DocumentId попробовать в логах поискать. Если вам важно найти какой-то OperationId конкретного документа, пришлите идентификаторы (boxId, letterId, documentId).

**Comment by geron4** [comment]
Острой потребности нет, предлагаю включить в следующие версии ПО.

**Comment by volodkindv** [comment]
Предложение зафиксировано.
