### ISSUE TITLE
Пример заполнения титула покупателя с описанием списков допустимых значений полей с пояснениями

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#420]
"Более подробно можно почитать обсуждение в этом [тикете](https://github.com/diadoc/diadocsdk-1c-docs/issues/366).
Пример кода есть в [комментарии]https://github.com/diadoc/diadocsdk-1c-docs/issues/366#issuecomment-539041927) (только там надо еще добавить заполнение SignerDetails.Position).

_Originally posted by @volodkindv in https://github.com/diadoc/diadocsdk-1c-docs/issues/418#issuecomment-575484058_"

Возникла сложность с заполнением  полей титула покупателя через COM -API
Из https://github.com/diadoc/diadocsdk-1c-docs/issues/418 и https://github.com/diadoc/diadocsdk-1c-docs/issues/366 понятно, как определить набор 
 свойств титула покупателя, но не могу понять, где перечень ограничений на значения заполнения и пояснения к этим значениям.

Прошу предоставить информацию о перечне допустимых значениях полей титула покупателя с пояснениями, чему соответствуют эти значения. В документации этой информации не нашёл

**Comment by MikeFilimonov** [comment]
Могу руководствоваться документацией на HTTP -API для работы с COM-API

**Comment by volodkindv** [comment]
Ограничения полей указаны в xsd-схемах типов документов.

Схемы для 820 формата можно посмотреть в [документации](https://api-docs.diadoc.ru/ru/latest/howto/utd820.html#userdataxml) http-api. Там есть пример "упрощенной" XSD, на основании которой как раз строятся поля в объектах компоненты. И пример оригинальной XSD от ФНС.

Пояснений нет в оригинальной XSD от ФНС. Их можно найти в [полной версии приказа 820](https://normativ.kontur.ru/document?moduleId=1&documentId=328588).

**Comment by MikeFilimonov** [comment]
Спасибо за https://api-docs.diadoc.ru/ru/latest/howto/utd820.html#userdataxml

Когда документация по COM-API будет приведена в актуальное состояние?
Могу на этот период при работе с COM-API руководствоваться документацией на HTTP -API ?

**Comment by volodkindv** [comment]
> Когда документация по COM-API будет приведена в актуальное состояние?

У нас нет планов транслировать XSD в документацию по компоненте для 1С. На то есть несколько причин.

> Могу на этот период при работе с COM-API руководствоваться документацией на HTTP -API ?
Да. Если точнее, то вам надо руководствоваться XSD схемой нужного титула.

**Comment by MikeFilimonov** [comment]
> У нас нет планов транслировать XSD в документацию по компоненте для 1С. На то есть несколько причин.

Есть ли у Вас в планах отметить обязательные для заполнения поля?



> Да. Если точнее, то вам надо руководствоваться XSD схемой нужного титула.
Предположу, что дело  не в XSD, а в несоответствии набора свойств  класса ExtendedSignerDetails в https://buildmedia.readthedocs.org/media/pdf/diadocsdk-1c/latest/diadocsdk-1c.pdf и набора  свойств объекта, полученного через API. Разве свойста ExtendedSignerDetails  тоже определены XSD, а не документацией?
Если это так, почему в документации поля не помечены устаревшими для новых версий компоненты?
В чем причина различия?

**Comment by volodkindv** [comment]
Класс [ExtendedSignerDetails](http://1c-docs.diadoc.ru/ru/latest/ComObjects/ExtendedSignerDetails.html) был реализован во внешней компоненте как обертка над интерфейсом метода [ExtendedSignerDetails](https://api-docs.diadoc.ru/ru/latest/http/utd/ExtendedSignerDetails.html) в HTTP API. Все его атрибуты были жесто прописаны в коде. Как и все объекты COM-интерфейса.
Он и сейчас таков.
К XSD схемам документов он не имеет никакого отношения.

У нас нет планов отмечать обязательные для заполнения поля. Одна из причин в том, что список этих полей зашит в XSD схеме, которой владеет команда разработки HTTP API. Эта схема периодически меняется (например, поля для дефисов осенью добавились). При таком подходе ни одна документация не будет поспевать за изменениями. Тем более что XSD - это и есть документация, просто в непривычном формате.

**Comment by MikeFilimonov** [comment]
> Одна из причин в том, что список этих полей зашит в XSD схеме, которой владеет команда разработки HTTP API.

@volodkindv, с чем связана ошибка
"Line: 5, Position: 164, /UniversalTransferDocumentBuyerTitle[1]/Signers[1]/SignerDetails[1]/@SignerType: The 'SignerType' attribute is invalid - The value 'LegalEntity' is invalid according to its datatype 'String' - The Enumeration constraint failed.
Line: 5, Positi"
https://api-docs.diadoc.ru/ru/latest/proto/utd/ExtendedSignerDetailsToPost.html
Неужели Вы int обернули в String и обрезали длину поля до 1 символа?

**Comment by volodkindv** [comment]
Приведите, пожалуйста, пример кода, приводящего к ошибке. Из описания не ясно, что именно Вы вызываете.
Возможно, перепутаны ExtendedSignerDetailsToPost и заполнение контента документов.

**Comment by MikeFilimonov** [comment]
> Возможно, перепутаны ExtendedSignerDetailsToPost и заполнение контента документов.

Точно нет.


> пример кода, приводящего к ошибке
![image](https://user-images.githubusercontent.com/3480769/73157821-4e1d6000-40f3-11ea-9d66-61165fb871f3.png)
Вводил строковые литералы, которые сейчас указаны в комментариях

**Comment by MikeFilimonov** [comment]
Так в чём дело?

**Comment by volodkindv** [comment]
В каком формате пришел документ, который вы подписываете на скриншоте?
Похоже, это 155 формат, и в МассивСвойствЗадания лежит [UtdBuyerContent](http://1c-docs.diadoc.ru/ru/latest/ComObjects/UtdBuyerContent.html), а не [DynamicContent](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html).

Кроме того, достаточно заполнить либо boxId/certificateThumbprint подписанта, либо все остальные поля (SignerType и т.д.).
В первом случае параметры подписанта возьмутся из полномочий, установленных через ExtendedSignerDetails. Во втором - непосредственно те, которые вы указали.

**Comment by MikeFilimonov** [comment]
> В каком формате пришел документ
820

**Comment by MikeFilimonov** [comment]
> Кроме того, достаточно заполнить либо boxId/certificateThumbprint подписанта, либо все остальные поля (SignerType и т.д.).

Они заполнены, при этом автоматически параметры подписанта не заполняются.  В результате при вызове Send() получаю ошибку о незаполнении полей

**Comment by volodkindv** [comment]
Что лежит в переменной МассивСвойствЗадания ? Как она инициализируется? Через CreateReplySendTask() или CreateReplySendTask2()?
Будет проще если приведете весь значимый код, от самого начала подписания. Желательно текстом.

**Comment by MikeFilimonov** [comment]
> Через CreateReplySendTask() или CreateReplySendTask2()?

CreateReplySendTask2()

> Будет проще если приведете весь значимый код, от самого начала подписания. Желательно текстом.
В публичном доступе не хочу выкладывать весь значимый код. Куда могу выслать его лично Вам?

**Comment by volodkindv** [comment]
> Куда могу выслать его лично Вам?

Написал вам в почту вашего профиля.

**Comment by MikeFilimonov** [comment]
> Написал вам в почту вашего профиля.

@volodkindv, спасибо! Отправил

**Comment by olleksa** [comment]
Подскажите, пожалуйста, какое значение в SignerPowers надо указать, когда требуется проставить подпись покупателя по строке 15 УПД (блок СодФХЖ4)? И вообще правильно ли я создаю подписанта в таком случае?
Signer = ContentItem.content.UniversalTransferDocumentBuyerTitle.Signers.AddItems()
Signer.SignerDetails.SignerType = "1"; //Представитель юридического лица
Signer.SignerDetails.SignerPowers = ?
Signer.SignerDetails.SignerStatus ="5"; //BuyerEmployee = 5;  Работник организации - покупателя (для документов в формате приказа №820);

**Comment by MikeFilimonov** [comment]
> Подскажите, пожалуйста, какое значение в SignerPowers надо указать, когда требуется проставить подпись покупателя по строке 15 УПД (блок СодФХЖ4)? И вообще правильно ли я создаю подписанта в таком случае?
> Signer = ContentItem.content.UniversalTransferDocumentBuyerTitle.Signers.AddItems()
> Signer.SignerDetails.SignerType = "1"; //Представитель юридического лица
> Signer.SignerDetails.SignerPowers = ?
> Signer.SignerDetails.SignerStatus ="5"; //BuyerEmployee = 5; Работник организации - покупателя (для документов в формате приказа №820);

Заполняю так:
СвойстваПодписанта.SignerPowers = "3";//"PersonDocumentedOperation"


Ориентировался вот на эти источники 
https://api-docs.diadoc.ru/ru/latest/proto/utd/UniversalTransferDocumentBuyerTitleInfo.html
https://api-docs.diadoc.ru/ru/latest/proto/utd/ExtendedSigner.html

**Comment by olleksa** [comment]
Спасибо, @MikeFilimonov 
Попробовала по Вашему совету, поставила SignerPowers = "3":
Signer = ContentItem.content.UniversalTransferDocumentBuyerTitle.Signers.AddItems()
Signer.SignerDetails.SignerType = "1"; //Представитель юридического лица
Signer.SignerDetails.SignerPowers = "3";//"PersonDocumentedOperation"
Signer.SignerDetails.SignerStatus ="5"; //BuyerEmployee = 5; 

Результат тот же, в 18 строке подпись добавляется, в 15 ничего не попадает. И, кстати, непонятно, откуда в 18 строке берется еще одна подпись - т.е. я создаю Signer (заполняю ФИО, должность) - и эта подпись встает второй подписью в 18.

![изображение](https://user-images.githubusercontent.com/41576111/79998062-e775cb80-84c2-11ea-8d7c-914cb8a71d7b.png)

**Comment by volodkindv** [comment]
@olleksa попробуйте заполнять поля Employee или OtherIssuer.

**Comment by olleksa** [comment]
@volodkindv Спасибо, заполнение Employee принесло ожидаемый эффект.
