### ISSUE TITLE
code:409, HTTP error: Текущее состояние документа не позволяет его подписать

### ISSUE THREAD

**Issue by evilless63** [diadoc/diadocsdk-1c-docs#421]
При попытки подписи входящего документа возникает ошибка code:409, HTTP error: Текущее состояние документа не позволяет его подписать

Получаем документ по его идентификатору (который записался в реквизит в момент получения документа в 1с)
Document = Organization.GetDocumentById(Документ.va_ИдентификаторДокументаЭДО);
Далее
ReplySendTask =  Document.CreateReplySendTask2("AcceptDocument");
					UTD = ReplySendTask.ContentItems.getItem(0).Content.UniversalTransferDocumentBuyerTitle;
					UTD.DocumentCreator = Document.Organization.Name;
					UTD.OperationContent = "Утверждение документа";
					Signers = UTD.Signers;
					NewSigner = Signers.AddItems();
					NewSigner.SignerReference.BoxId = Organization.Id;
					NewSigner.SignerReference.certificateThumbprint = Organization.Certificate.thumbprint;
					ReplySendTask.Send();

Прошу помочь с решением

**Comment by evilless63** [comment]
Документы уже подписали в системе вручную...

**Comment by evilless63** [comment]
Проблема сохранилась. Прошу помочь с решением.

**Comment by IrinaShmonina** [comment]
@evilless63 здравствуйте
Можете предоставить 
- ссылку на документ, на котором воспроизводится ошибка
- BoxId
- значение переменной ИдентификаторДокументаЭДО

**Comment by evilless63** [comment]
Например,

BoxId организации: 45dd214c-6c5f-4517-a39c-90ceee5da717
Идентификатор документа: 9b66f5e5-643e-48e9-b85e-7f1c75deabc375b74d6d-807f-41dc-965f-e7778d91b3ba
Вх номер документа: ТМ101-00402

Ссылка:https://diadoc.kontur.ru/45dd214c-6c5f-4517-a39c-90ceee5da717/Document/Show?letterId=b3a163d3-f42c-4f8f-b6eb-f91f860921f9&documentId=fa37f500-30d3-4afa-a917-2e2c5801b572

**Comment by IrinaShmonina** [comment]
Можете подсказать еще версию компоненты?

**Comment by evilless63** [comment]
DiadocCom_5_29_8_554

**Comment by IrinaShmonina** [comment]
@evilless63 здравствуйте,
Документ с идентификатором 9b66f5e5-643e-48e9-b85e-7f1c75deabc375b74d6d-807f-41dc-965f-e7778d91b3ba уже подписан, поэтому на него может возвращаться ошибка при попытке подписать документ.

Документ https://diadoc.kontur.ru/45dd214c-6c5f-4517-a39c-90ceee5da717/Document/Show?letterId=b3a163d3-f42c-4f8f-b6eb-f91f860921f9&documentId=fa37f500-30d3-4afa-a917-2e2c5801b572 не подписан. И в логах не вижу, чтобы возвращалась ошибка.

Проверьте идентификаторы документов, которые вы хотите подписать

**Comment by evilless63** [comment]
То есть, это разные документы ?

**Comment by volodkindv** [comment]
Да, разные. Здесь вы указали 2 разных документа.

> BoxId организации: 45dd214c-6c5f-4517-a39c-90ceee5da717
> Идентификатор документа: 9b66f5e5-643e-48e9-b85e-7f1c75deabc375b74d6d-807f-41dc-965f-e7778d91b3ba
> Вх номер документа: ТМ101-00402
> 
> Ссылка:https://diadoc.kontur.ru/45dd214c-6c5f-4517-a39c-90ceee5da717/Document/Show?letterId=b3a163d3-f42c-4f8f-b6eb-f91f860921f9&documentId=fa37f500-30d3-4afa-a917-2e2c5801b572
> 

Первый: https://diadoc.kontur.ru/45dd214c-6c5f-4517-a39c-90ceee5da717/Document/Show?letterId=9b66f5e5-643e-48e9-b85e-7f1c75deabc3&documentId=75b74d6d-807f-41dc-965f-e7778d91b3ba

Второй: https://diadoc.kontur.ru/45dd214c-6c5f-4517-a39c-90ceee5da717/Document/Show?letterId=b3a163d3-f42c-4f8f-b6eb-f91f860921f9&documentId=fa37f500-30d3-4afa-a917-2e2c5801b572
