### ISSUE TITLE
Пример SaveContent

### ISSUE THREAD

**Issue by PaulStogov** [diadoc/diadocsdk-1c-docs#422]
Здравствуйте!
Кто-нибудь может привести рабочий пример Document.SaveContent() для PackageSendTask2.DocumentsToSend ? Что не пытаюсь сделать - в ответ тишина и отсутствие каких-либо результатов. Мне всего-то нужно сохранить сформированную xml'ку УПД перед отправкой на сервер Диадока.

**Comment by MikeFilimonov** [comment]
@PaulStogov, у Вас COM-API или HTTP-API? 
Далее исхожу из документации на COM-API: https://buildmedia.readthedocs.org/media/pdf/diadocsdk-1c/latest/diadocsdk-1c.pdf
![image](https://user-images.githubusercontent.com/3480769/72870450-4deb2200-3cf9-11ea-8ac5-1b124e2f787c.png)
@PaulStogov, допустим, мы создали  PackageSendTask2.
Далее добавляем документы, и, думаю, после добавления можем сохранить документ в xml.
![image](https://user-images.githubusercontent.com/3480769/72870674-e08bc100-3cf9-11ea-8e96-3b35bc4561f5.png)

После добавления документа, при попытке его сохранения, у Вас возникает ошибка?

**Comment by volodkindv** [comment]
Добрый день.
Метод SaveContent() не реализован в [CustomDocumentToSend](http://1c-docs.diadoc.ru/ru/latest/ComObjects/CustomDocumentToSend.html), являющемся производным от PackageSendTask2.
У нас есть такая задача. Когда будет готово, напишем в новостях.

**Comment by PaulStogov** [comment]
> У нас есть такая задача. Когда будет готово, напишем в новостях.

Спасибо за отклик!

**Comment by GilimkhanovDenis** [comment]
Функциональность добавлена в версии [5.29.9](http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_29_9.html)
