### ISSUE TITLE
Упд 820 Сведения о товаре, подлежащем прослеживаемости

### ISSUE THREAD

**Issue by sc0rp10n87** [diadoc/diadocsdk-1c-docs#423]
Добрый день. 
Мы являемся участником системы меркурий. 
В формате 820 были предусмотрены теги для товаров с отслеживанием, тег СведПрослеж. 
При заполнении этого тега и отправки документов через внешнюю компоненту  "Diadoc_5_29_7_549.dll" подключенную к 1с. 
Выходит следующая ошибка 
PackageSendTask2.Send: ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: { Location = /Файл/@ИдФайл, Message = Значение атрибута @ИдФайл имеет неверный формат: ON
NSCHFDOPPR_91******70-91******01_61******63-23******01_20200121_1F4046B7-82E0-4189-9AB3-49DD0110D50A (@ИдОтпр=61******63-23******01, @ИдПол=91******70-91******01), для прослеживаемых товаров СведПрослеж=
Отправка происходит с использованием метода PackageSendTask2.AddDocumentFromFile("UniversalTransferDocument", "ДОП", "utd820_05_01_01",ПутьИмяФайла);
В качестве файла с данными передается xml документ.
Подскажите по какой причине может выходить данная ошибка?

**Comment by GilimkhanovDenis** [comment]
ИдПол и ИдОтпр - идентификаторы участника ЭДО (свойство FnsParticipantId объекта [ExtendedOrganizationInfo](http://1c-docs.diadoc.ru/ru/latest/ComObjects/ExtendedOrganizationInfo.html#extendedorganizationinfo))
Они же используются в наименовании файла (это требование формата).
В вашем случае в названии файла указаны
@ИдОтпр=6163-2301, @ИдПол=9170-9101
Это НЕ идентификаторы ЭДО
