### ISSUE TITLE
Как скоро будет готова печатная форма для УПД 820?

### ISSUE THREAD

**Issue by MikeFilimonov** [diadoc/diadocsdk-1c-docs#425]
Ориентировочный срок появления печатных форм УПД 820 - конец лета

_Originally posted by @GilimkhanovDenis in https://github.com/diadoc/diadocsdk-1c-docs/issues/320#issuecomment-510344770_

С 17 января проблемы при формировании пф 
"При попытке сохранить печатную форму через  API получаю ошибку Ошибка при вызове метода контекста (GetPrintForm): Произошла исключительная ситуация (DocumentBase.GetPrintForm): За указанный промежуток времени не удалось сгенирировать печатную форму"

**Comment by IrinaShmonina** [comment]
@MikeFilimonov , добрый день
Диадок поддержал печатные формы для УПД 820 формата. Новость об этом на сайте Диадока → https://www.diadoc.ru/blog/7887

Попробуйте еще рез получить печатную форму документа. Если ошибка воспроизводится, то можете приложить ссылку на документ?

**Comment by MikeFilimonov** [comment]
> Попробуйте еще рез получить печатную форму документа. Если ошибка воспроизводится, то можете приложить ссылку на документ?

Пробовал около 5 раз

Ссылок много :
/19bb544b-6a04-4874-b639-2637a1c10f0a/Document/Show?letterId=23a7732d-da89-460a-ae60-93ba664ce66f&documentId=21da2d77-d0ea-42a6-982b-2ea52eb7ad65
/19bb544b-6a04-4874-b639-2637a1c10f0a/Document/Show?letterId=f03137a7-1143-4a7f-aa83-2457f2620b7b&documentId=f7db30fd-1a38-4dc1-8b2c-67ac5e32d3ba
/19bb544b-6a04-4874-b639-2637a1c10f0a/Document/Show?letterId=c97690ce-20e2-4b9e-a0fd-c20b70656fba&documentId=fa1255b5-7fa7-4b74-b8e4-2449cafa0278
/19bb544b-6a04-4874-b639-2637a1c10f0a/Document/Show?letterId=4f153ee2-0209-4d49-a630-7bb39800173d&documentId=bbe1d79f-cd3a-4564-90d6-fd90c63a05ea
/19bb544b-6a04-4874-b639-2637a1c10f0a/Document/Show?letterId=fbb53c0f-8b01-414e-bb27-b5e201aa0426&documentId=42ca57bf-dcb8-4b28-b21c-87285ece345f

**Comment by MikeFilimonov** [comment]
Сегодня ошибка не проявилась.
