### ISSUE TITLE
Список отправленных документов

### ISSUE THREAD

**Issue by PaulStogov** [diadoc/diadocsdk-1c-docs#426]
И снова здравствуйте!
COM-API
Хочу получить список отправленных в Диадок документов из нашей 1С Предприятие 7.7.
Лезу в документацию http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetSentDocuments

> Organization.GetSentDocuments(OneSId, AsDiadocDocumentId=False)
> Возвращает коллекцию строк - идентификаторов отправленных документов для запрашиваемых идентификаторов OneSId.
> Не рекомендуется, начиная с версии 5.5.0: Используйте Organization.GetData()

Иду по ссылке http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetData
> Organization.GetData(Key)
> Key: строка уникальный ключ в хранилище
> Возвращает значение, соответствующее ключу

Что за хранилище? Что за ключи? Где копать?

**Comment by kuiv** [comment]
Добрый день, рекомендация ,не использовать GetSentDocuments(), сделана потому, что этот метод готовится к "выпиливанию".   Т.к. использует недокументированные возможности diadoc-api.  Ему на смену приходят методы GetData/SetData. Эти методы "родные" для diadoc-api и документированы.

Логика работы такая:
- при отправке документа в Диадок, сразу после отправки получаем DocumentID из Диадок  и сопоставляем ему пару OneSDocumentID (который генерируем самостоятельно) . И обратную пару.
Organization.SetData( OneSDocumentID, DocumentID )
Organization.SetData( DocumentID, OneSDocumentID ) // обратная пара
- если нам нужно узнать был ли отправлен документ 1С в Диадок исполняем
DocumentID  = Organization.GetData(OneSDocumentID) , если DocumentID  не пустой , то это идентификатор документа в Диадоке, иначе документ не отравлялся.
- чтобы "отвязать" документ1с от документа Диадок, исполняем Organization.SetData( OneSDocumentID, "" )
- чтобы узнать к какому документу 1с привязан документ Диадок, исполняем
OneSDocumentID  = Organization.GetData(DocumentID) . срабатывает обратная пара

Метод GetSentDocuments будет "выпилен" , когда модуль 7.7 стандарт перйдет на GetData/SetData.

**Comment by PaulStogov** [comment]
> Ему на смену приходят методы GetData/SetData. Эти методы "родные" для diadoc-api и документированы.

А кто поделится ссылкой на то место где они "документированы"?

**Comment by kuiv** [comment]
Упс. Поправка. Используются НЕДОКУМЕНТИРОВАННЫЕ методы api-diadoc. Методы используются только компонентой COM Diadoc API

**Comment by IrinaShmonina** [comment]
[GetData](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetData)
[SetData](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.SetData)

**Comment by PaulStogov** [comment]
> [GetData](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetData)
> [SetData](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.SetData)

Спасибо, конечно, но именно из-за этого я и обратился за помощью неделю назад. Документации нет, примеров нет. В исходниках компоненты GetData вызывается для формирования таблицы маршрутизации и всё. Такого наплевательского отношения я давно не встречал =(

**Comment by PaulStogov** [comment]
Пытаюсь воспользоваться свежедобавленным  Organization.CreateDataTask(), 
DataTask.SetData() и DataTask.GetData(), по ощущениям, не делают ничего.
`DataTask = дд_Организация.CreateDataTask();DataTask.GetData();
ПараИдентификаторов = DataTask.AddKey(ПолучитьИД(Документ1С.ТекущийДокумент()), Пакет.Documents.GetItem(0).DocumentId);
			ПараИдентификаторов = DataTask.AddKey(Пакет.Documents.GetItem(0).DocumentId, ПолучитьИД(Документ1С.ТекущийДокумент()));
			Сообщить(ПараИдентификаторов.Key + " " + ПараИдентификаторов.Value);
			DataTask.SetData();			
			//Смотрим, что у нас в хранилище
			DataTask.GetData();
			Сообщить("В хранилище (" + DataTask.KeyValues.Count + "):");
			Для KeyValuesCounter = 0 По DataTask.KeyValues.Count-1 Цикл							
				Сообщить(KeyValuesCounter + ": ");
				Сообщить(DataTask.KeyValues.GetItem(KeyValuesCounter).Key + " " + DataTask.KeyValues.GetItem(KeyValuesCounter).Value);
			КонецЦикла;
`

**Comment by GilimkhanovDenis** [comment]
Поведение должно быть такое:
```
DataTask = дд_Организация.CreateDataTask();
DataTask.GetData();
```
Коллекция ключей-значений пустая, поэтому смысла в этом вызове нет

```
ПараИдентификаторов = DataTask.AddKey(ПолучитьИД(Документ1С.ТекущийДокумент()), Пакет.Documents.GetItem(0).DocumentId);
ПараИдентификаторов = DataTask.AddKey(Пакет.Documents.GetItem(0).DocumentId, ПолучитьИД(Документ1С.ТекущийДокумент()));
DataTask.SetData();
DataTask.GetData();
```

В коллекции 2 элемента у которых есть ключ и значение


Если поведение отличается, то проиллюстрируйте, пожалуйста, скриншотами (или другим способом) что было в коллекции до вызова SetData и что стало после вызова GetData

**Comment by PaulStogov** [comment]
Почему смысла нет? А как же те значения, которые я добавлял в коллекцию в предыдущий вызов DataTask.SetData() в прошлый, скажем, вторник?

> Am 13.02.2020 um 09:36 schrieb GilimkhanovDenis <notifications@github.com>:
> 
> ﻿
> Поведение должно быть такое:
> 
> DataTask = дд_Организация.CreateDataTask();
> DataTask.GetData();
> Коллекция ключей-значений пустая, поэтому смысла в этом вызове нет

**Comment by GilimkhanovDenis** [comment]
Потому что только что создали новый объект и, если судить по коду,  ключей в него не добавили.
Если нужны данные по ключам, которые заполняли во вторник, то заполните коллекцию ключами, которые устанавливали во вторник и вызовите GetData()
