### ISSUE TITLE
Как связать отправляемый в диадок пакет документов созданный методом CreatePackageSendTask2 с нужным документом

### ISSUE THREAD

**Issue by Avtomir-AMK** [diadoc/diadocsdk-1c-docs#427]
Добрый день!
Ранее для объекта DocumentToSend, созданного методом CreatePackageSendTask, существовал метод DocumentToSend.AddInitialDocument(DocumentID) для связи отправляемого пакета с уже отправленным документом.
Приведите пожалуйста пример как теперь через объект CustomDocumentToSend, созданный методом CreatePackageSendTask2 связать отправляемый пакет с уже отправленным документом.

С уважением, Алексей

**Comment by IrinaShmonina** [comment]
Добрый день,
[CustomDocumentToSend](http://1c-docs.diadoc.ru/ru/latest/ComObjects/CustomDocumentToSend.html)является производным от DocumentToSend. У него есть набор методов по созданию связей: AddInitialDocument, AddSubordinateDocument, AddInitialDocumentFromPackage, AddSubordinateDocumentFromPackag

**Comment by Avtomir-AMK** [comment]
Ирина, добрый день!
Спасибо большое за помощь. Разобрались. Вопрос снимается.
