### ISSUE TITLE
Метод "GetDocflows".  Код ошибки 400 Can't deserialize request body into type: GetDocflowBatchRequest

### ISSUE THREAD

**Issue by YSSergey** [diadoc/diadocsdk-1c-docs#429]
`Добрый` день. Подскажите, что я делаю не так?
Пытаюсь получить по DocumentId статусы документов, для этого использую метод GetDocflows, (недоступный во внешней компоненте для 1С).
Почему метод не принимает мой json? 

КодСостояния : 400.
Ошибка: Can't deserialize request body into type: GetDocflowBatchRequest

{
 "Requests": [
  {
   "LastEventId": 2,
   "DocumentId": {
    "EntityId": "e4233cf3-fe71-4d67-a7e0-cf8ad327981622",
    "MessageId": "f2b5b444-ef15-4f00-a285-e8bf588a180722"
   }
  },
  {
   "LastEventId": 2,
   "DocumentId": {
    "EntityId": "e4233cf3-fe71-4d67-a7e0-cf8ad327981622",
    "MessageId": "f2b5b444-ef15-4f00-a285-e8bf588a180722"
   }
  }
 ]
}

**Comment by kulakovskaya** [comment]
Добрый день!
Ошибка говорит о том, что данные в запросе имеют неверный формат. 
В необязательном параметре LastEventId необходимо указать **идентификатор** последнего события.

**Comment by YSSergey** [comment]
> Добрый день!
> Ошибка говорит о том, что данные в запросе имеют неверный формат.
> В необязательном параметре LastEventId необходимо указать **идентификатор** последнего события.

Пробовал и с обязательными параметрами и без..
Дело оказалось в другом, Именно 1C некорректный json отправляет, т.к. попробовал в API testere (расширение хрома) выполнить этот запрос со всеми параметрами из 1С - все получилось. 
Почему не работает в 1С - загадка =(

**Comment by volodkindv** [comment]
Возможно, разница в том, как вы собираете JSON.
На свежих платформах у нас работает так:
```
Функция СтруктураВJSON(Структура) Экспорт
	
	Запись = Вычислить("Новый ЗаписьJSON");
	Запись.УстановитьСтроку();
	
	ЗаписатьJSON(Запись, Структура);
	
	Результат = Запись.Закрыть();
	
	Возврат Результат;
	
КонецФункции

...
ТелоЗапроса = СтруктураВJSON(Структура);
HTTPЗапрос.УстановитьТелоИзСтроки(ТелоЗапроса, КодировкаТекста.UTF8, ИспользованиеByteOrderMark.НеИспользовать);

```
Здесь важно убирать BOM.

**Comment by YSSergey** [comment]
> Возможно, разница в том, как вы собираете JSON.
> На свежих платформах у нас работает так:
> 
> ```
> Функция СтруктураВJSON(Структура) Экспорт
> 	
> 	Запись = Вычислить("Новый ЗаписьJSON");
> 	Запись.УстановитьСтроку();
> 	
> 	ЗаписатьJSON(Запись, Структура);
> 	
> 	Результат = Запись.Закрыть();
> 	
> 	Возврат Результат;
> 	
> КонецФункции
> 
> ...
> ТелоЗапроса = СтруктураВJSON(Структура);
> HTTPЗапрос.УстановитьТелоИзСтроки(ТелоЗапроса, КодировкаТекста.UTF8, ИспользованиеByteOrderMark.НеИспользовать);
> ```
> 
> Здесь важно убирать BOM.

Спасибо за совет! Но к сожалению не помогло..:
![Анализ JSON](https://user-images.githubusercontent.com/60465849/73544552-76d28c00-444a-11ea-9ef9-07b39959d0f7.png)


Вот как собираю структуру:

``Функция СобратьСтруктуруТела(messageId, entityId)
	
	DocumentId1 = Новый Структура;
	DocumentId1.Вставить("MessageId", messageId);
	DocumentId1.Вставить("EntityId", entityId);
	
	ПервыйДокументМассив = Новый Массив;
	ПервыйДокументМассив.Добавить(DocumentId1);
	
	ПервыйДокумент = Новый Структура;
	ПервыйДокумент.Вставить("DocumentId",DocumentId1);
	ПервыйДокумент.Вставить("LastEventId", "46da120e-d398-11e8-8077-030000000000");
	
	
	СписокЗапросов = Новый Массив;
	СписокЗапросов.Добавить(ПервыйДокумент);
	
	Requests  = Новый Структура;
	Requests.Вставить("Requests", СписокЗапросов);
	
	Возврат  Requests;

КонецФункции


`Процедура GetDocFlowsНаСервере()
	
	СтруктураТела = СобратьСтруктуруТела(messageId, entityId);
	
	Заголовки = Новый Соответствие;
	Заголовки.Вставить("Content-Type", "application/x-www-form-urlencoded");
	Заголовки.Вставить("Authorization","DiadocAuth ddauth_api_client_id="+КлючРазработчика+",ddauth_token="+token);
	Заголовки.Вставить("Accept",		"application/json");  // без этого вернется двоичнй протобуфер
	
	HTTPЗапрос = Новый HTTPЗапрос("/V2/GetDocflows?boxid="+boxid, Заголовки);

	ТелоЗапроса = СтруктураВJSON(СтруктураТела);
	HTTPЗапрос.УстановитьТелоИзСтроки(ТелоЗапроса, КодировкаТекста.UTF8, ИспользованиеByteOrderMark.НеИспользовать);
	
	HTTPОтвет = HTTPСоединение.ОтправитьДляОбработки(HTTPЗапрос);
	
	ЧтениеJSON = Новый ЧтениеJSON;
	СтрокаЧтения = HTTPОтвет.ПолучитьТелоКакСтроку();
	ЧтениеJSON.УстановитьСтроку(СтрокаЧтения) ;
	
	
	Сообщить (HTTPОтвет.ПолучитьТелоКакСтроку());
	Сообщить(HTTPОтвет.КодСостояния);	
		
		                                                                                                                     
	ДанныеGetDocflows = ПрочитатьJSON(ЧтениеJSON, Ложь);
	Сообщить("Документов в массиве:" +ДанныеGetDocflows.Documents.Количество());
	                        

	
КонецПроцедуры
`

**Comment by YSSergey** [comment]
Всем спасибо! Вопрос снимается! Разобрался. Нужно было вместо Заголовки.Вставить("Content-Type", "application/x-www-form-urlencoded"); использовать Заголовки.Вставить("Content-Type", "application/json");
