### ISSUE TITLE
Отправка Contract документ типа “договор” 

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#43]
Отправляю вот так:
SendTask = Organization.CreateSendTaskFromFile(СтрТЗКомплект.ПутьФ,"Contract");
SendTask.Content.ContractType = "Дополнительное соглашение";
SendTask.Content.Date 	= ?(ТипЗнч(стДокумент) = Тип("СправочникСсылка.Документооборот"), стДокумент.ДатаРегистрации, стДокумент.Дата);
SendTask.Content.Number = СокрЛП(стДокумент.Договор.Наименование);   
SendTask.Filename 		= СтрТЗКомплект.пИмяФайла;

При отправке ругается что не существует такого вида документа Contract для CreateSendTaskFromFile, можно использовать только другие из списка, в котором нет "Contract". Как отправить такой вид произвольного документа?

**Comment by denver069** [comment]
Какую версию компоненты используете?

**Comment by jakeqwert** [comment]
5.9.0.154, до этого такая же проблема была 5.5.4.83. Просто не знал что сюда можно писать.

**Comment by jakeqwert** [comment]
Ошибка при вызове метода контекста (CreateSendTaskFromFile): Произошла исключительная 
ситуация (Box.CreateSendTaskFromFile): Неверный тип контента. Допустимыми являются следующие значения: InvoiceContent, UniversalTransferDocument, ......

**Comment by denver069** [comment]
Указанную вами ошибку воспроизвести не удалось, тестировал на всех вариантах исполнения компоненты версии 5.9.0.154.
Попробуйте переустановить компоненту.
