### ISSUE TITLE
RSS: битая ссылка

### ISSUE THREAD

**Issue by volodkindv** [diadoc/diadocsdk-1c-docs#430]
![1](https://user-images.githubusercontent.com/12305552/73518060-1da13300-441f-11ea-9139-7460c70c25c3.jpg)
![2](https://user-images.githubusercontent.com/12305552/73518061-1da13300-441f-11ea-8989-e82132c40b5f.jpg)

**Comment by GilimkhanovDenis** [comment]
Исправлено
