### ISSUE TITLE
Установка FromDepartmentId при отправке документа

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#431]
Компонента 1С версии AddIn x86 5.29.8.554.
В веб-интерфейсе контрагентам установлены подразделения нашей организации, к которому они относятся. При отправке документа через CreatePackageSendTask2 надо установить FromDepartmentId, соответствующее контрагенту. Как можно получить связку контрагент-подразделение?

**Comment by volodkindv** [comment]
Добрый день.
Такой возможности сейчас нет. Она доступна только в веб-интерфейсе Диадок и не вынесена в [HTTP API](https://api-docs.diadoc.ru/ru/latest/), поэтому и в компоненте 1С ее не может быть.
