### ISSUE TITLE
Выборка документов типа "Nonformalized" методом DocumentsTask.GetDocuments()

### ISSUE THREAD

**Issue by DurkinVA** [diadoc/diadocsdk-1c-docs#432]
Здравствуйте!
  Подскажите,  почему из выборки убрали документы вышеуказанного типа и как их получить теперь? Платформа 1с 7.7, AddInDiadocAPI.dll версия  5.29.1.530.  

Спасибо.

**Comment by IrinaShmonina** [comment]
Здравствуйте,
мы не изменяли логику работы в DocumentsTask.GetDocuments(). Можете поподробнее рассказать про вашу проблему?

**Comment by DurkinVA** [comment]
DocumentsTask = НашаФирма.GetDocumentsTask();
	DocumentsTask.FromDocumentDate = ВыбНачПериода;
	DocumentsTask.toDocumentDate = ВыбКонПериода;
	DocumentsTask.Category = "Any.Outbound";
	
		
	Если ПустоеЗначение(ИДКлиента)=0 Тогда
		
		DocumentsTask.CounteragentId =Строка(ИДКлиента);
	Иначе
		DocumentsTask.CounteragentId ="";
	КонецЕсли;
		
		DocumentList = DocumentsTask.GetDocuments();
		
		Ц = 0;
		Пока ц < DocumentList.Count Цикл
			Document = DocumentList.GetItem(Ц);
		//	Сообщить(Document.DocumentNumber); 
			Поз = 0;
		//	Если т.НайтиЗначение(СокрЛП(Document.DocumentNumber), Поз, "НомерДок") = 0 Тогда
				
				т.НоваяСтрока();
				т.Вид   = Document.Type;       
				т.НомерДок = СокрЛП(Document.DocumentNumber);
				т.ДатаДок  = Document.DocumentDate;
				
				т.АннулированСтатус = СокрЛП(Document.RevocationStatus);     
				т.ИД = СокрЛП(Document.DocumentID);  
				т.ИмяФайла = Document.FileName;
				//		КонецЕсли;                             
				
				
				Если СокрЛП(Document.Type) ="XmlAcceptanceCertificate"  Тогда
					//ОбъектПокупателя = Document.GetBuyerContent();
					//
					//попытка
					//	
					//	т.ДатаПолучения =  ОбъектПокупателя.SignatureDate;        
					//	
					//Исключение
					//	//					т.ДатаПолучения =  ОбъектПокупателя.SignatureDate;
					//	
					//	
						
						Signature = Document.GetRecipientSignature();
						
						
						Если ПустоеЗначение(Signature)=0 Тогда
							т.ДатаПолучения = Signature.SignDate;     
						КонецЕсли; 
						
						
						
				//	КонецПопытки;
					
					т.СтатусАкта   = СокрЛП(Document.Status); 
					
				ИначеЕсли СокрЛП(Document.Type) ="Invoice" Тогда 
					
				    Signature = Document.GetRecipientSignature();
					
					
					Если ПустоеЗначение(Signature)=0 Тогда
					 	т.ДатаПодписи = Signature.SignDate;     
					КонецЕсли; 
					
					
				
					
					
					т.Статус   = СокрЛП(Document.Status);  
					
				ИначеЕсли (СокрЛП(Document.Type) ="Nonformalized") или (СокрЛП(Document.Type) ="NonformalizedProforma") или (Найти(врег(т.ИмяФайла),"СЧЁТ")>0) или (Найти(Врег(т.ИмяФайла),"СЧЕТ")>0) Тогда 
					
					т.СтатусСчёта   = СокрЛП(Document.Status); 	
					
				КонецЕсли; 
			 
		        т.СтатусДокумента = СокрЛП(Document.Status);
			
			
			
			//	Сообщить(СокрЛП(Document.Type));
			
			Ц = Ц + 1;
		КонецЦикла;   
		  
		Сообщить("Конец запроса к Диадок по документам");

**Comment by DurkinVA** [comment]
Вот кусок кода. Раньше он позволял выбирать и неформализованные документы. Сейчас, почему-то перестал.  В выборке только акт  и счет-фактура. Пакет отправлялся с счетом также.

**Comment by DurkinVA** [comment]
Счет = Пакет.AddDocumentFromFile("Nonformalized","default", "v1", КаталогСохранения +"\"+ глИмяФайла);              
			                
			MetaDataItem = Счет.AddMetadata();
			MetaDataItem.Key   = "FileName";
			MetaDataItem.Value = глИмяФайла;
Так отправляю.

**Comment by GilimkhanovDenis** [comment]
Ситуация аналогична тикетам: https://github.com/diadoc/diadocsdk-1c-docs/issues/120 и https://github.com/diadoc/diadocsdk-1c-docs/issues/376 - у Nonformalized документов нет свойства DocumentDate, поэтому в выборку они не попадают.
Используйте фильтр по дате отправки (FromSendDate, ToSendDate) вместо даты документа (FromDocumentDate, ToDocumentDate)

**Comment by DurkinVA** [comment]
Спасибо. Хотя странно, раньше выбиралось. Буду разбираться.
