### ISSUE TITLE
Ошибка при отправке УПД  Invalid data UserContractData

### ISSUE THREAD

**Issue by IrinaZ86** [diadoc/diadocsdk-1c-docs#433]
Добрый день
Использую COM-компоненту для встраивания в произвольные системы версии DiadocCom_5_29_7_549

При по пытке отправить УПД через API - получаем ошибку:

PackageSendTask2.Send: ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:

'', hexadecimal value 0x11, is an invalid character. Line 200, position 46.

Помогите, пожалуйста, разобраться из-за чего может быть эта ошибка?

**Comment by kulakovskaya** [comment]
Добрый день! Какой из методов используйте для отправки документа: AddDocument, AddDocumentFromFile или AddDocumentFromBase64?

**Comment by IrinaZ86** [comment]
AddDocument

**Comment by IrinaZ86** [comment]
Package.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01_hyphen")

**Comment by kulakovskaya** [comment]
Приложите, пожалуйста,  файл полученный с помощью DocumentToSend.SaveContent.

**Comment by IrinaZ86** [comment]
При попытке сохранить файл с помощью данного метода - такая же ошибка:
![diadoc_Error](https://user-images.githubusercontent.com/41632692/73912560-dbb43900-48c5-11ea-935a-7dd75b3a629b.PNG)

**Comment by kulakovskaya** [comment]
Для решения вопроса необходимо залогировать запрос и предоставить нам собранные логи.
Также рекомендуем проверить поля в документе на наличие спецсимволов.

**Comment by IrinaZ86** [comment]
Нашли спецсимвол в описание товара, проблема решена. Спасибо
