### ISSUE TITLE
Добавление элементов через подключаемый модуль

### ISSUE THREAD

**Issue by snapsik** [diadoc/diadocsdk-1c-docs#434]
Добрый день! 
Необходима ваша помощь по вопросу:
 Как поправить подключаемый модуль, чтобы на основную форму обработки Контур.Диадок добавить новую кнопку программно и назначить процедуру при нажатии (без редактирования типовой обработки Контур.Диадок)? Через какую процедуру это можно сделать?

**Comment by kulakovskaya** [comment]
Добрый день! На основную форму обработки новую кнопку можно добавить в раздел "Действия" с помощью функции **ЗаполнитьСписокДополнительныхКнопок** и **НажатиеДополнительнойКнопки.** Подробнее в документации http://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Dobavleniye_Knopok.html

**Comment by snapsik** [comment]
Документацию читал, но не понятно куда эти процедуры вставить. В модуль объекта "подключаемого модуля"? Вызов ОсновнойМодуль - это откуда (не определен)? 
В самой обработке Диадок не отображается кнопка Действия. Отладка эти процедуры новые не отрабатывает. Есть примеры использования этих процедур в подключаемом модуле? Документация от Диадок примитивна.
Написал такие процедуры,.. но ничего не работает.

Процедура ЗаполнитьСписокДополнительныхКнопок(Параметры) Экспорт //++08022020
	РежимОтображенияДокументов = Параметры.РежимОтображенияДокументов;
	ТаблицаКнопок = Параметры.ТаблицаКнопок;
	
	Если РежимОтображенияДокументов = "ОтправленныеДокументы" Тогда
		
		НовСтрока = ТаблицаКнопок.Добавить();
		НовСтрока.Имя       = "СопоставитьОтправленныйДокумент";
		НовСтрока.Заголовок = "Сопоставить документ";
		
	КонецЕсли;
	
КонецПроцедуры


Процедура НажатиеДополнительнойКнопки(Параметры) Экспорт //++08022020
	РежимОтображенияДокументов = Параметры.РежимОтображенияДокументов;
	ВыделенныеСтроки = Параметры.ВыделенныеСтроки;
	ИмяКнопки = Параметры.ИмяКнопки;
	
	Если РежимОтображенияДокументов = "ОтправленныеДокументы" И ИмяКнопки = "СопоставитьОтправленныйДокумент" Тогда
		
		Для Каждого ВыбраннаяСтрока Из ВыделенныеСтроки Цикл
			Если ЗначениеЗаполнено(ВыбраннаяСтрока.ДокументЭДО) Тогда
				
				//РезультатФункции = ОсновнойМодуль.НайтиИСопоставитьДокументДД(ВыбраннаяСтрока.ДокументЭДО, ВыбраннаяСтрока.Пакет);
				////ОсновнойМодуль.ОбработатьРезультатФункции(РезультатФункции);
				
			КонецЕсли;
		КонецЦикла;
		
	КонецЕсли;
КонецПроцедуры

**Comment by snapsik** [comment]
Подскажите, где вызывать процедуру ЗаполнитьСписокДополнительныхКнопок(Параметры) ?
Кто-нибудь имел дело с этой процедурой? Вопрос очень важен.

**Comment by snapsik** [comment]
> Добрый день! На основную форму обработки новую кнопку можно добавить в раздел "Действия" с помощью функции **ЗаполнитьСписокДополнительныхКнопок** и **НажатиеДополнительнойКнопки.** Подробнее в документации http://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Dobavleniye_Knopok.html

Подскажите, где вызывать процедуру ЗаполнитьСписокДополнительныхКнопок(Параметры) ? Выше правильно процедуры написал? Они в модуле объекта подключаемого модуля должны быть?

**Comment by IrinaShmonina** [comment]
Здравствуйте,
Можно воспользоваться генерацией шаблона кода ПМ. 
Для этого зайдите в Диадок.ПРО → Настройки → Настройки → Подключаемый модуль → Генерировать пример подключаемого модуля → В разделе "Прочие события" можно найти процедуру ЗаполнитьСписокДополнительныхКнопок

**Comment by ChelUsr** [comment]
> 
> 
> Здравствуйте,
> Можно воспользоваться генерацией шаблона кода ПМ.
> Для этого зайдите в Диадок.ПРО → Настройки → Настройки → Подключаемый модуль → Генерировать пример подключаемого модуля → В разделе "Прочие события" можно найти процедуру ЗаполнитьСписокДополнительныхКнопок

Добрый день! Такого раздела нет в модуле Диадок. Я так понимаю, что у меня простая версия модуля. Можете подсказать как обратится к этим процедурам/функциям?

**Comment by IrinaShmonina** [comment]
@ChelUsr , добрый день
подскажите какая у вас версия модуля

**Comment by ChelUsr** [comment]
> 
> 
> @ChelUsr , добрый день
> подскажите какая у вас версия модуля

5.34.03.228

**Comment by volodkindv** [comment]
Скорее всего, у вас конфигурация на обычных формах.

В модуле зайдите в  раздел "Настройки", "Подключаемый модуль", "Сохранить шаблон подключаемого модуля на диск".
Откройте шаблон в конфигураторе.
Вам нужны следующие методы:

```
Функция ОбработатьСобытиеДиадок(ИмяСобытия, Параметры, СтандартнаяОбработкаДиадок = Истина) Экспорт
	
	//...

	ИначеЕсли ИмяСобытия = "ПриОткрытииФормы" Тогда
		
		ОбработатьСобытие_ПриОткрытииФормы(Параметры);
		
	ИначеЕсли ИмяСобытия = "ПодключаемаяКоманда" Тогда
		
		ОбработатьСобытие_ПодключаемаяКоманда(Параметры);
		
	КонецЕсли;
	
КонецФункции


// Процедура вызывается после при открытии в формы обработки (пока только основной).
//
// Параметры
//	Параметры - <Структура> - Содержит коллекцию, переданных параметров
//
// Состав структуры:
// 	Форма	 - <Форма>	- Основная форма обработки.
// 	ИмяФормы - <Строка> - Имя формы, как оно задано в конфигураторе в списке форм обработки.
//
Процедура ОбработатьСобытие_ПриОткрытииФормы(Параметры)
	
	#Если ТолстыйКлиентОбычноеПриложение Тогда
	
	Форма= 	  Параметры.Форма;
	ИмяФормы= Параметры.ИмяФормы;
	
	Если ИмяФормы = "Форма_Основная" Тогда
		
		// Пример добавления кнопки с разделителем на командную панель:
		Форма.ЭлементыФормы.КоманднаяПанельСФОтправленные.Кнопки.Добавить(,ТипКнопкиКоманднойПанели.Разделитель);
		
		// Обработка действия кнопки выполняется в процедуре ОбработатьСобытие_ПодключаемаяКоманда()
		Форма.ЭлементыФормы.КоманднаяПанельСФОтправленные.Кнопки.Добавить("ДополнительнаяКнопка",ТипКнопкиКоманднойПанели.Действие, "Дополнительная кнопка", Новый Действие("ПодключаемаяКоманда"));
		
	КонецЕсли;
	
	#КонецЕсли
	
КонецПроцедуры

// Процедура вызывается из метода формы ПодключаемаяКоманда().
// ПодключаемаяКоманда() используется в качестве метода действия при создании дополнительных кнопок основной формы.
//
// Параметры
//	Параметры - <Структура> - Содержит коллекцию, переданных параметров
//
// Состав структуры:
// 	Форма  	 - <Форма>  - Основная форма обработки.
// 	ИмяФормы - <Строка> - Имя формы, как оно задано в конфигураторе списке форм обработки.
// 	Кнопка 	 - <Кнопка> - Табличная часть в которой выполнено обновление.
//
Процедура ОбработатьСобытие_ПодключаемаяКоманда(Параметры)
	
	Форма=	  Параметры.Форма;
	ИмяФормы= Параметры.ИмяФормы;
	Кнопка=   Параметры.Кнопка;
	
	Если ИмяФормы = "Форма_Основная" Тогда
		
		Если Кнопка.Имя = "ДополнительнаяКнопка" Тогда
			Сообщить("Действие дополнительной кнопки");
		КонецЕсли;
		
	КонецЕсли;
	
КонецПроцедуры



```

**Comment by ChelUsr** [comment]
Спасибо.
