### ISSUE TITLE
Получить шаблоны документов на принимающей стороне.

### ISSUE THREAD

**Issue by Avtomir-AMK** [diadoc/diadocsdk-1c-docs#435]
Добрый День!

Почитал ссылку как работать с шаблонами документов - http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_template.html
В Диадок есть метод Organization.GetTemplate(TemplateId).
Нам присылают шаблоны документов. Мы не знаем идентификаторы данных шаблонов TemplateId. Подскажите пожалуйста каким методом можно получить отправленные нам шаблоны документов?

С уважением,
Алексей

**Comment by GilimkhanovDenis** [comment]
Добрый день.
Аналогичный вопрос был в https://github.com/diadoc/diadocsdk-1c-docs/issues/371.
Ответ пока тот же: компонента не умеет получать входящие шаблоны. Если данная функциональность необходима, просьба обратиться к менеджеру, ведущему ваше организацию

**Comment by Avtomir-AMK** [comment]
Понял. Спасибо!
