### ISSUE TITLE
Ошибка SaveAllContent

### ISSUE THREAD

**Issue by Dilise** [diadoc/diadocsdk-1c-docs#436]
Добрый день!

При сохранении файлов документа методом SaveAllContent происходит ошибка:
`Ошибка при вызове метода контекста (SaveAllContent): Произошла исключительная ситуация (DocumentBase.SaveAllContent): Ошибка открытия файла`
Версия компоненты: **COM** компонента 5.29.8.554 x64
Параметры метода: DirectoryPath(94 символа) = "C:\Users\svc-1CTest-server\AppData\Local\Temp\v8_5E53_68.tmp\Приложение к акту за август 2019"
WithProtocol = True
Имя файла в документе для скачивания: "Приложение к акту за август 2019 внутр..pdf" !!! Имеет две точки !!!
Другие файлы сохраняются без проблем данным методом
При использовании **AddIn** компоненты той же версии и разрядности проблемы нет.

PS: Сам документ: [https://diadoc.kontur.ru/17770a8b-8394-4af4-b302-74bd71e1dbbc/Document/Show?letterId=09e85846-26c3-4533-8d54-c310eb92636b&documentId=2246369d-79ac-4d91-9649-dd90fa10df17](url)

**Comment by Dilise** [comment]
После нескольких повторений, методвсе же отработал и файл скачался. В чем может быть причина?

**Comment by Dilise** [comment]
Воспроизвел ситуацию еще раз. Файл загрузился с четвертого раза, спустя 8 минут.

**Comment by Dilise** [comment]
Еще раз воспроизвел проблему. С использованием компоненты AddIn файл загрузился без ошибок с первого раза, как и описано в топике.

**Comment by GilimkhanovDenis** [comment]
Проверьте, что у пользователя, под которым выполняется обработка, достаточно прав на запись в  указанную папку

**Comment by Dilise** [comment]
Прав достаточно, т.к. в этом же сеансе другие документы загружаются корректно.

> Воспроизвел ситуацию еще раз. Файл загрузился с четвертого раза, спустя 8 минут.

Да и на четвертую попытку права точно никто не менял.

**Comment by Dilise** [comment]
Хотя различие между COM и AddIn имеется.
COM зарегистрирована на сервере приложений и выполняется под доменной учеткой сервера приложений.
AddIn регистрируется на клиенте и выполняется под пользователем домена.

**Comment by denver069** [comment]
Можно посмотреть код, которым вы скачиваете эти файлы?
Есть ли различия в серверной части кода и клиентской?

**Comment by Dilise** [comment]
Код всей функции во вложении. [СкачатьФайлыОбъектаДиадок.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/4190059/default.txt)
Различие клиентской и серверной части кода только в инициализации компоненты:
`		#Если Клиент Тогда
			//Загрузка внешней компоненты
			ИмяФайла = ПолучитьИмяВременногоФайла("dll");
			ЭтотОбъект.ПолучитьМакет("ФайлКомпоненты_x86").записать(ИмяФайла);
			ЗагрузитьВнешнююКомпоненту(ИмяФайла);
			//Создание объекта DiadocInvoiceAPI
			DiadocInvoiceAPI_ = Новый("AddIn.DiadocInvoiceAPI");
			DiadocInvoiceAPI  = DiadocInvoiceAPI_.CreateObject();
			Reflector = Новый ComОбъект("AddIn.Diadoc.Reflector");
			КонтекстВыполнения = НСтр("ru='клиенте'");
		#Иначе                
			//создаем корневой элемент COM-объекта
			DiadocInvoiceAPI = Новый COMОбъект("Diadoc.DiadocClient");
			Reflector = Новый ComОбъект("Diadoc.Reflector");
			КонтекстВыполнения = НСтр("ru='сервере'");
		#КонецЕсли
		ВерсияКомпоненты = DiadocInvoiceAPI.GetVersion();
		ТекстПодключения = НСтр("ru='DiadocAPI подключен на '") + КонтекстВыполнения
			+ НСтр("ru='
			|Версия компоненты: '") + ВерсияКомпоненты
		;
		ЗаписатьИнформациюВ_ЖР(ТекстПодключения, Истина);
`

**Comment by Dilise** [comment]
ОФФТОП: Если вдруг у Вас имеется решение проблемы максимального количества символов пути в windows при сохранении файлов пакета документов тем же методом (SaveAllContent), было бы неплохо о нем узнать. Пока мы искусственно анализируем длину пути темп каталога и вычитаем максимально возможную длину файла пакета Диадок, полученную опытным путем.

**Comment by GilimkhanovDenis** [comment]
Про оффтоп: создайте отдельный issue. В целом сохранение файлов по длинному пути (>260 символов) в компоненте работает. Притом имя файла или папки в пути не может превышать 255 символов, а общая длина пути не может превышать 32,767 символов. Подробнее [здесь](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file)

**Comment by Dilise** [comment]
> Про оффтоп:
Про обратный слэш в курсе, но как то пытался передать путь с обратным слэшем платформе 1С 8.2 - результат отрицательный (подробностей не помню) - видимо до компоненты не дошло управление. Как соберусь со временем и тестами - оформлю отдельно - спасибо.

**Comment by GilimkhanovDenis** [comment]
оффтоп: Компонента сама добавляет слэши в начало пути
изначальную ошибку стабильно удаётся воспроизвести только, если сохранять во временную папку с недостаточными правами (что на addin, что на com). Сервер и клиент это разные машины? Если да, то вероятно, папка для временнных файлов создаётся на сервере и на неё может не быть прав. Код внутри Addin и Com в этом месте один и тот же вызывается

**Comment by Dilise** [comment]
**Сервер и клиент это разные машины?**
- Да.
**вероятно, папка для временнных файлов создаётся на сервере и на неё может не быть прав**
- Думаю это не так, т.к. идет цикл по загрузке всех полученных документов, и N десятков документов загружаются корректно в той же сессии, в смежные папки в Temp того же пользователя, и только приведенный в ошибке файл выдает ошибку, причем только несколько итераций, после чего загружается этими же строками кода.
Есть предположение, что, возможно, сам файл физически не успел передаться от отправителя до получателя на сервере (т.к. это pdf объемом 431 КБ), и поэтому, загрузка удается с N-го раза, а в компоненте просто не предусмотрен перехват исключения, но это всего лишь догадки. Такое возможно?

**Comment by GilimkhanovDenis** [comment]
Такое не возможно. Ошибка "Ошибка открытия файла" возникает при попытке создания файла (handle'а) в файловой системе до записи каких-либо данных в него.
Сами данные к этому моменту уже все получены

Ошибка записи данных имеет текст ошибки "Ошибка записи в файл"

**Comment by Dilise** [comment]
Спасибо за потраченное время, попробую подключить сисадминов к решению проблемы.

**Comment by Dilise** [comment]
Коллеги, прошу проверить еще одну версию:
Будет ли ошибка, если в конце пути будет пробел, например:
"C:\Users\svc-1CTest-server\AppData\Local\Temp\v8_7303_78.tmp\Приложение к акту за август 2019 "
Есть подозрения, что недопустимые символы заменились пробелами, таким образом в имени каталога для сохранения на конце оказался пробел вместо той второй точки.
Предполагаю, что компонента добавив к каталогу слэш и имя файла получила разделенный пробелом путь.
ps: Права проверили - пользователь - владелец папки с полным доступом.

**Comment by GilimkhanovDenis** [comment]
Похоже предположение верное. С таким сценарием воспроизводится

**Comment by Dilise** [comment]
Мне нужно обращение зарегистрировать на устранение?
Или поправите без обращения в будущих версиях?

**Comment by GilimkhanovDenis** [comment]
Добавим более информативную ошибку в следующей версии компоненты
