### ISSUE TITLE
УПД 820

### ISSUE THREAD

**Issue by lanrootdiadoc** [diadoc/diadocsdk-1c-docs#438]
День добрый! Подскажите, пожалуйста, по подключаемому модулю диадок. Постоянно требуется его править. 
например при заполнении макета УПД
1. Как заполнить уступочную надпись? (Должна быть в шапке в самом верху)
2. Протоконтент.TransferInfo.Employee - подписант с нашей стороны.
Как заполнить поле "Иные сведения" ?
Ранее не использовал подключаемый модуль, а разбирал макеты и хранил на диске.
Сейчас хочу сделать по фэншую.
Спасибо.

**Comment by volodkindv** [comment]
Добрый день!
1. Вам надо заполнить добавить Key-Value в Content.AdditionalInfoId.StructedAdditionalInfos. Значение поля Key надо узнать у получателя документа. Value - сам текст надписи.
2. Попробуйте заполнить Протоконтент.TransferInfo.Employee.EmployeeInfo.

**Comment by lanrootdiadoc** [comment]
1. Уступочная надпись должна выводиться в шапке договора (самая верхняя строка печатной формы). У получателя нет специального ключа для этого.

**Comment by volodkindv** [comment]
1. StructedAdditionalInfos надо заполнить примерно так:
![image](https://user-images.githubusercontent.com/12305552/75336522-231e5b80-58ad-11ea-846c-9c994698a74a.png)

Печатная форма в модуле будет такой:
![image](https://user-images.githubusercontent.com/12305552/75336562-2fa2b400-58ad-11ea-8fc9-5f6ddbb20870.png)

Печатная форма в веб-интерфейсе:
![image](https://user-images.githubusercontent.com/12305552/75336646-52cd6380-58ad-11ea-9681-d4c6800084f9.png)

**Comment by lanrootdiadoc** [comment]
Уступочная надпись попала в  доп.сведения, а нужно сверху.
//Уступочная надпись
     Если ТипЗнч(ссылкаНаДокумент)=Тип("ДокументСсылка.РеализацияТоваровУслуг") тогда
         Если СОКРЛП(СсылкаНаДокумент.договор.ШапкаУПД)<>"" тогда           
             ДополнитьМассивKeyValue(Протоконтент.AdditionalInfoId.StructedAdditionalInfos,"Уступочная надпись","<head>"+СсылкаНаДокумент.договор.ШапкаУПД+"</head>");     
         КонецЕсли;  
     иначе
        Если СОКРЛП(СсылкаНаДокумент.ДокументОснование.договор.ШапкаУПД)<>"" тогда           
             ДополнитьМассивKeyValue(Протоконтент.AdditionalInfoId.StructedAdditionalInfos,"Уступочная надпись","<head>"+СсылкаНаДокумент.ДокументОснование.договор.ШапкаУПД+"</head>");     
         КонецЕсли;  
     КонецЕсли;
 
 
 
С уважением,
ведущий программист
ООО "Эй энд Ди Ди Компани",
Ларин Сергей.

Моб.тел.: (926) 376-09-55.
Раб.тел.: (495) 988-46-85 (доб. 257)
e-mail:  sergey.larin@addc.ru

**Comment by volodkindv** [comment]
Нужна точная версия вашего модуля и скриншот шапки документа.

**Comment by lanrootdiadoc** [comment]
5.37.01.375
 
 
 
С уважением,
ведущий программист
ООО "Эй энд Ди Ди Компани",
Ларин Сергей.

Моб.тел.: (926) 376-09-55.
Раб.тел.: (495) 988-46-85 (доб. 257)
e-mail:  sergey.larin@addc.ru

**Comment by lanrootdiadoc** [comment]
![image](https://user-images.githubusercontent.com/61452897/75341985-91abeb00-58a6-11ea-8137-995a172d8257.png)

**Comment by lanrootdiadoc** [comment]
![image](https://user-images.githubusercontent.com/61452897/75342219-03843480-58a7-11ea-9e25-c918920c77f0.png)

**Comment by volodkindv** [comment]
Попробуйте обновить модуль до последнего 5.38.19. Должно заработать.

**Comment by lanrootdiadoc** [comment]
огонь, работает, спасибо

**Comment by AlexProgz** [comment]
Добрый день, уважаемые коллеги.
У меня такая же проблема с отображением уступочной надписи.
Версия модуля 1С 5_47_01  и на 5_48_01 пробовал.
Поэтому вопрос остается открытым
Как заполнить уступочную надпись? (Должна быть в шапке в самом верху).
Вот пример кода в подключаемом модуле:
///////////////////////////////////////////////////////////////////////////////
**ТекстШапки** = "Требование по оплате данной поставки уступлено обществу с ограниченной ответственностью «РБ Факторинг». Любое решение относительно прекращения, изменения или исполнения Требования подлежит согласованию с названным фактором. Все платежи на основании настоящего документа должны перечисляться Вашей компанией на: получатель ООО «РБ Факторинг», ИНН  7706677277,КПП 770801001, Банк  получателя: ПАО РОСБАНК, г. Москва, ИНН 7730060164 КПП 997950001,  БИК 044525256,  к/сч 30101810000000000256,  р/сч 40702810500000061566.";
ДополнитьМассивKeyValue(**Протоконтент.AdditionalInfoId.StructedAdditionalInfos**, "Внимание", "<head>"+ТекстШапки+"</head>");

///////////////////////////////////////////////////////////////////////////////

**Comment by AlexProgz** [comment]
Теперь скриншоты с проблемой:
![Версия модуля Диадок](https://user-images.githubusercontent.com/54399625/159478450-7359bf4c-6b1d-4988-9f07-860a6590ef0b.jpg)

**Comment by AlexProgz** [comment]
![Документ УПД в Контур Диадок при загрузке сохраненного на диск xml файла_верх](https://user-images.githubusercontent.com/54399625/159478586-1988864a-6e69-4747-acd9-8caff0d57ce7.jpg)
![Документ УПД в Контур Диадок при загрузке сохраненного на диск xml файла_низ](https://user-images.githubusercontent.com/54399625/159478596-29ba9012-5a99-48c7-b505-d3a63fe7ed43.jpg)

**Comment by AlexProgz** [comment]
Также вот как выглядит этот документ в веб версии СБИС
![Пример документа УПД с факторингом из системы СБИС](https://user-images.githubusercontent.com/54399625/159479017-1907afaf-b7b4-4801-a617-366b24efae4b.jpg)

Здесь отображется нормально в шапке

**Comment by AlexProgz** [comment]
Как я понимаю Печатная форма именно в веб-интерфейсе не понимает тег head.

**Comment by ilzag** [comment]
> Как я понимаю Печатная форма именно в веб-интерфейсе не понимает тег head.

Добрый день.
Печатная форма в вебинтерфейсе не учитывает наличие тега `<head>...</head>`.
Для того, чтобы настроить печатную форму, существует отдельная услуга "Кастомная печатная форма" (КПФ). За подробностями рекомендуем обратиться к вашему менеджеру по Диадоку.
