### ISSUE TITLE
Архив Диадок

### ISSUE THREAD

**Issue by YSSergey** [diadoc/diadocsdk-1c-docs#439]
Добрый день.

Подскажите пожалуйста, стоит задача хранить файлы документооборота Диадок в 1С (печатные формы, подписи и тд).
Каким методом лучше пользоваться, если нужно получать информацию не за период, а по идентификаторам  (желательно массив на вход) ?
"GenerateDocumentZip" как я понимаю работает только для одного документа.

**Comment by volodkindv** [comment]
Добрый день.
В компоненте 1С нет метода GenerateDocumentZip. 
Есть метод [GenerateDocumentZip](https://api-docs.diadoc.ru/ru/latest/http/GenerateDocumentZip.html#generatedocumentzip) в HTTP API. И есть метод [SaveAllContentZipAsync](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html#document-saveallcontentzipasync) во внешней компоненте.

В вашем случае надо воспользоваться одним из них, циклом по ID нужных документов.

**Comment by YSSergey** [comment]
Благодарю за пояснение!

> Добрый день.
> В компоненте 1С нет метода GenerateDocumentZip.
> Есть метод [GenerateDocumentZip](https://api-docs.diadoc.ru/ru/latest/http/GenerateDocumentZip.html#generatedocumentzip) в HTTP API. И есть метод [SaveAllContentZipAsync](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html#document-saveallcontentzipasync) во внешней компоненте.
> 
> В вашем случае надо воспользоваться одним из них, циклом по ID нужных документов.
