### ISSUE TITLE
Ошибка при вызове метода контекста (GetCounteragentById)

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#44]
С 16.11.2016 16:35:06 началась такая ошибка:
"Ошибка при вызове метода контекста (GetCounteragentById): Произошла исключительная ситуация (Box.GetCounteragentById): ##100[Ошибка сервера Диадок]code:404, HTTP error: Trust relationship between organizations 93e15610-48db-4162-90d1-8f6d380ed19e and f70eaa1b-5cc3-4c0a-a52b-c74467735729 not found"
До этого ничего не меняли и все работало достаточно стабильно.

**Comment by jakeqwert** [comment]
Процедура ОбработатьEvent(Event, Organization)
	Событие = Event;	
	Counteragent = Organization.GetCounteragentById(Событие.CounteragentId);
Ошибка в этой строке.

**Comment by jakeqwert** [comment]
Могу предположить, что какой-то контрагент заблокировал нас и соответственно не можем теперь ленту событий корректно отработать, контрагента нельзя получить.

**Comment by jakeqwert** [comment]
В общем документ отправили ошибочно "https://diadoc.kontur.ru/3bfb9c4d-0203-4610-83c8-e15ba95fd8d2/Document/Show?letterId=436aec69-3c55-4e65-8844-9954323e9b47&documentId=3bd0863f-ac93-4990-bbed-2d62e54baecb"
А потом после прокачки статуса не получается получить контрагента, т.к. мы с ним не партнеры. А документ доставлен.

**Comment by jakeqwert** [comment]
Просто пропустил в ленте событий это события начал со следующего и все заработало.

**Comment by volodkindv** [comment]
Контрагент с данным ID не является партнером вашей организации. Вам необходимо отправить ему приглашение (или получить приглашение от него), после этого можно будет начинать обмен электронными документами. Метод GetCounteragentById после этого тоже должен отрабатывать корректно.
Пропуск события - тоже вариант решения проблемы.
