### ISSUE TITLE
Подпись сертификатом отказа

### ISSUE THREAD

**Issue by Edoexpetek** [diadoc/diadocsdk-1c-docs#441]
При выполнение ответных действий по документу пользуюсь методом CreateReplySendTask2. Метод возвращает 2 типа объектов DynamicContent (ReplyType="AcceptDocument") и BaseContent . С первым объектом все понятно. А вот со вторым есть затруднение. Не могу найти метод, которым можно подписать Content отпечатком Сертификата. Подскажите чем пользоваться для подписания объектов BaseContent Отпечатком Сертификата КриптоПро? Или сейчас такие объекты можно подписать только Signer.Surname = "Фамилия"; Signer.FirstName = "Имя"; Signer.Patronymic = "Отчество"; Signer.JobTitle = "Должность"; Signer.Inn = "966785367420"; таким образом?

**Comment by volodkindv** [comment]
Вопрос непонятен.
Какой вид документа вы хотите подписать? 
Ответный титул подписывается сертификатом, под которым авторизовался пользователь. При выполнении метода Send().
Вы хотите заполнить ответный титул для УПД 155 формата?

**Comment by Edoexpetek** [comment]
Я хочу по документу utd820_05_01_01_hyphen отказать в подписи документа либо подтвердить ануляцию документа.

**Comment by volodkindv** [comment]
ReplySendTask2 = Document.CreateReplySendTask2("RejectDocument");

Content = ReplySendTask2.ContentItems.GetItem(0);
... (при необходимости заполнить поля в Content)

ReplySendTask2.Send(); // происходит подписание ответа текущим сертификатом

Пример работы с ReplySendTask2 в режиме AcceptDocument есть тут:
https://github.com/diadoc/diadocsdk-1c-docs/issues/393#issuecomment-564523227

**Comment by Edoexpetek** [comment]
Но при этом все равно надо заполнять поля подписи
vSigner = vContent.Signer.
         vSigner.Surname
         vSigner.FirstName
         vSigner.Patronymic
         vSigner.JobTitle
         vSigner.Inn
или все же можно просто указать где-то отпечаток сертификата?

**Comment by IrinaShmonina** [comment]
Принятие запроса на аннулирование - это "AcceptRevocation"

COM-Объект будет [AcceptanceContent](http://1c-docs.diadoc.ru/ru/latest/ComObjects/AcceptanceContent.html) - для него заполнять ExtendedSigner'а не нужно.
На уровне прото заполняется структура [DocumentSignature](https://api-docs.diadoc.ru/ru/latest/proto/DocumentSignature.html) - данные о подписи содержатся в поле Signature.
Подписание/отказ аннулирования происходит авторизованным пользователем

**Comment by Edoexpetek** [comment]
Да для подписания аннуляции не нужно заполнять данные подписи, а для отказа RejectDocument
есть возможность не заполнять данные подписи а подписать отпечатком?

**Comment by kulakovskaya** [comment]
Добрый день. Для отказа логика такая же, как для принятия запроса на аннулирование. Действие выполняется с тем сертификатом, по которому авторизовались.
