### ISSUE TITLE
Получение комментариев для документа

### ISSUE THREAD

**Issue by sergeb72** [diadoc/diadocsdk-1c-docs#442]
Здравствуйте.
Установлены COM компоненты v5.29.10.566 для произвольных систем.

В документации по ссылке
http://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html#Document.GetAnyComment
описано 4 варианта получения комментариев.

Для документа
https://diadoc.kontur.ru/05409264-5339-4dc7-aa36-2625f812119e/Document/Show?letterId=a39c5a16-00b1-4137-a3b1-a85339c3201e&documentId=17dc6426-4ea5-4231-88fc-07df17a52b3c
все 4 доступных варианта возвращают пустую строку, однако на портале видно, что документ имеет комментарий в событии "подписал и отправил соглашение об аннулировании".

Каким образом получить этот существующий комментарий?

**Comment by volodkindv** [comment]
Добрый день.
Вам надо обойти коллекцию Resolutions в объекте Document: http://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html?highlight=Resolutions

**Comment by sergeb72** [comment]
Спасибо.
