### ISSUE TITLE
Ошибка при отправке УПД в форме приказа 820

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#443]
Добрый день. При отправке УПД возникла ошибка:

_Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid generated title:
Metadata errors: 
Validation errors: Location: Line: 58, Position: 31, /Файл[1]/Документ[1]/ТаблСчФакт[1]/СведТов[1]/СвТД[1]/@НомерТД, Message: The 'НомерТД' attribute is invalid - The value '10126110/280610/0008906/012/01' is invalid according to its datatype 'String' - The actual length is greater than the MaxLength value._

Но ведь тип поля string1000? Подскажите, в чем проблема?

**Comment by volodkindv** [comment]
Предполагаю, что речь идет про 820 формат.

По формату ФНС номер ГТД имеет максимальную длину 29 символов:
```
  <xs:attribute name="НомерТД" use="optional">
	<xs:annotation>
	  <xs:documentation>Регистрационный номер таможенной декларации (номер декларации на товары; графа 11 счета-фактуры)</xs:documentation>
	</xs:annotation>
	<xs:simpleType>
	  <xs:restriction base="xs:string">
		<xs:maxLength value="29" />
		<xs:minLength value="1" />
	  </xs:restriction>
	</xs:simpleType>
  </xs:attribute>
```
String1000 - это внутреннее представление Диадока для совместимости между разными форматами.

**Comment by prog22** [comment]
Да, 820 формат. Спасибо за помощь.
