### ISSUE TITLE
АВР в формате приказа 552

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#444]
Добрый день.
Исполнитель отправляет XmlAcceptanceCertificate в формате приказа 552. Поле TaxRate является не обязательным и Исполнитель его не заполняет. Заказчик загружает документ через diadoccomapi.dll x64 для произвольных систем. При чтении TaxRate возвращается "18", что некорректно.
Пример ID документа в системе Диадок: _55f76ce7-3b42-439a-8bdb-26943d07ede7125ce2b8-e7c9-4bd3-9e16-62a8a949a8cc_.

**Comment by volodkindv** [comment]
Добрый день.
Для анализа нужны:
- сам файл документа
- точная версия компоненты
- boxid организации (видимо, получателя)
- пример кода, которым вы читаете TaxRate. Если точнее, то надо понять, вы работаете через DynamicContent или через старую объектную модель документа (http://1c-docs.diadoc.ru/ru/latest/ComObjects/Act552SellerContent.html).

**Comment by prog22** [comment]
Файл: [DP_REZRUISP.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/4338120/DP_REZRUISP.zip)

Версия: 5.29.7.549 x64 для произвольных систем
boxid: 98fb1fe3f2d84e9f9a3d55517ff8574b@diadoc.ru

Работаю через старую объектную модель: UtdSellerContent = Document.GetContent();

**Comment by kulakovskaya** [comment]
Данная логика заполнения TaxRate является техническим ограничением для старой объектной модели UtdSellerContent = Document.GetContent();.
Рекомендуем перейти на использование DynamicContent  http://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html, тогда в документе ставка будет отсутствовать. 
Либо в логике своей программы считать, что ставка 18% аналогична значению "ставка не заполнена", но для старых документов такая логика не подойдёт.

**Comment by prog22** [comment]
Спасибо.
