### ISSUE TITLE
отправка документа Nonformalized

### ISSUE THREAD

**Issue by Edoexpetek** [diadoc/diadocsdk-1c-docs#445]
Подскажите, можно ли документ Nonformalized добавлять vSendTask.AddDocument("Nonformalized", "default", "v1")  вот таким образом или такие документы можно только загружать из файла методом AddDocumentFromFile?

**Comment by GilimkhanovDenis** [comment]
Здравствуйте.
Для добавления документов, у которых нет упрощённой схемы контента (см. [DocumentTitle.HaveUserDataXSD|http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentTitle.html]), в задание на отправку можно использовать методы
[PackageSendTask2.AddDocumentFromFile|http://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocumentFromFile]
[PackageSendTask2.AddDocumentFromBase64|http://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocumentFromBase64]

метод [PackageSendTask2.AddDocument|http://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocument] для таких документов вернёт ошибку "Неверная версия вложения"
