### ISSUE TITLE
Заполнение Товар (груз) передал / услуги, результаты работ, права сдал

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#446]
Добрый день! Подскажите, каким способом заполнить при подписании исходящего документа (УПД) данное поле? Документ был ранее отправлен на подпись с помощью CreateResolutionRequestTask(), сотрудником у которого нет  эцп. Далее сотрудник с эцп подписывает его с помощью CreateOutDocumentSignTask(). Там заполняется только Signer.SignerDetails. Влияет ли Signer.SignerDetails.Powers на заполнение "Товар (груз) передал / услуги, результаты работ, права сдал" или это нужно сделать другим способом?

**Comment by GuninaY** [comment]
Также интересует этот вопрос касаемо входящих УПД (820 формат)

**Comment by kulakovskaya** [comment]
Добрый день! Signer.SignerDetails.Powers не влияет на заполнение "Товар (груз) передал / услуги, результаты работ, права сдал". В структуре xml за эти данные отвечает тег <СвПродПер>. Заполнить эти сведения необходимо уже на этапе отправки документа на согласование.

**Comment by GuninaY** [comment]
Спасибо!
