### ISSUE TITLE
Отправка документов с помощью PackageSendTask2

### ISSUE THREAD

**Issue by AntonP-star** [diadoc/diadocsdk-1c-docs#447]
Добрый День!

Оправляем документы УПД с помощью PackageSendTask2 по 820 приказу. Документ добавляем с помощью метода AddDocument(TitleName, Function, Version), где TitleName = UniversalTransferDocument, Function = СЧФ или СЧФДОП, Version = utd820_05_01_01.
Вопрос: Можно ли и каким образом отправить Счет фактуру и Накладную в виде НЕ УПД а в стандартном их виде? По 155 приказу я так понимаю это было возможно. Какие получается параметры мне необходимо установить ?
Спасибо.

**Comment by volodkindv** [comment]
Добрый день!
В вашем случае будет примерно так:

```
 AddDocument("Invoice", "Default", "utd820_05_01_01")
 AddDocument("XmlTorg12", "Default", "utd820_05_01_01")
```
Точные значения TitleName, Function, Version лучше посмотреть в результате метода GetDocumentTypes().

Version = utd820_05_01_01 сейчас не развивается, там есть более новая с текстом hyphen

**Comment by AntonP-star** [comment]
Спасибо, попробую и отпишусь.

**Comment by AntonP-star** [comment]
Попробовал, выдает ошибку ""Произошла исключительная ситуация (PackageSendTask2.AddDocument): Неверная версия вложения"" 
в результате метода GetDocumentTypes() те же данные, что и Вы мне указали. В чем может быть проблема ?

**Comment by AntonP-star** [comment]
Причем, если меняю на любую другую версию - та же ошибка

**Comment by kulakovskaya** [comment]
Какую используете версию компоненты?

**Comment by GilimkhanovDenis** [comment]
В GetDocumentTypes функция указана "default", а не "Default"

**Comment by AntonP-star** [comment]
На момент написания вопроса версия была 5.28.7, вчера поставил 5.29.11 и сегодня еще раз попробовал с функцией default (не "Default"), в итоге, к моему счастью удалось получить документ, причем как для версии utd820_05_01_01, так и для utd820_05_01_01hyphen. 
Всем спасибо за помощь) Сейчас буду заполнять документы и отправлять.
