### ISSUE TITLE
Оправляем Счет Фактуру и накладную с помощью PackageSendTask2 по 820 Приказу

### ISSUE THREAD

**Issue by AntonP-star** [diadoc/diadocsdk-1c-docs#448]
Добрый день!
Оправляем документы Счет Фактуру и накладнуюс помощью PackageSendTask2 по 820 приказу. Документ добавляем с помощью метода 
AddDocument("Invoice", "default", "utd820_05_01_01")
 AddDocument("XmlTorg12", "default", "utd820_05_01_01"), 
документ добавляется, контент я заполняю и с помощью метода Send() отправляю документы. В ответ получаю ошибку:
100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 2, Position: 28, /UniversalTransferDocument[1]/@Function: The 'Function' attribute is invalid - **The value 'default' is invalid according to its datatype 'String'** - The Enumeration constraint failed.
Что не так с функцией ? Ведь в результате метода GetDocumentTypes() функция как раз "Строка"? Что необходимо поправить?
Версия компоненты 5.29.11 
Заранее спасибо)

**Comment by GilimkhanovDenis** [comment]
В контенте фукнции должны быть "СЧФ" и "ДОП"

**Comment by AntonP-star** [comment]
А посмотрите этот тикет "Отправка документов с помощью PackageSendTask2 #447", мне там ответили, что в моем случае, для оправки счф и накладной нужны следующие параметры:
 AddDocument("Invoice", "Default", "utd820_05_01_01")
 AddDocument("XmlTorg12", "Default", "utd820_05_01_01")

**Comment by AntonP-star** [comment]
> 
> 
> В контенте фукнции должны быть "СЧФ" и "ДОП"

Все дошло) Сейчас попробую ...
