### ISSUE TITLE
Изменение поведение метода GetDocuments()

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#449]
Имеем в 1С код:
	Документы						= Организация.GetDocumentsTask();
	Документы.Category				= Категория;
	Документы.RequireOneSDocumentId	= 1;
	КоллекцияДокументов	= Документы.GetDocuments();
Код прекрасно работал несколько лет. Вчера обновили вашу компоненту до последней версии 5.29.11 и этот код стал выдавать ошибку:
SearchDocumentTask.GetDocuments: ##100[Ошибка сервера Диадок]code:400, HTTP error: Number of keys in request to KeyValueStorageGet exceeds allowed 100 items per query
Интуиция и гугл-переводчик подсказывают, что превышено допустимое количество элементов в выборке, но молчат по поводу методов исправления ситуации.
Может быть вы подскажите? С чего вдруг изменилось поведение метода и как можно получить список документов порциями?

**Comment by GilimkhanovDenis** [comment]
Испрвлено в 5.29.12

**Comment by dorexpro** [comment]
Забавное какое исправление. Ошибку теперь не выдает, но возвращает только первые сто документов. Вопрос о получении документов порциями все еще актуален.

**Comment by GilimkhanovDenis** [comment]
Укажите, пожалуйста boxId организации, в которой выполняете запрос и как заполнен объект SearchDocumentTask

**Comment by dorexpro** [comment]
Все заполняется точно так же, как для компоненты версии 5.29.8. Если поведение этого метода изменено с этой версии, то скажите где об этом почитать и как теперь получать полный список документов.
BoxId = e65822e9be3449cc8dd6a256fcfae77b@diadoc.ru
Свойства объекта SearchDocumentTask:
FromSendDate = 01.01.18
ToSendDate =   .  .
FromDocumentDate =   .  .
ToDocumentDate =   .  .
Category	 = Any.Outbound
counteragentId = 
DepartmentId = 
requireOneSDocumentId = 1
ExcludeSubdepartments = 0
Top100 = 0
FromDepartmentId =  
ToDepartmentId =

**Comment by dorexpro** [comment]
Уточнение. Список документов возвращается нормального размера, но поле OneSDocumentId заполнено только у первой сотни.

**Comment by GilimkhanovDenis** [comment]
Проверьте на версии 5.29.13
[release info](http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_29_13.html)
[download](http://1c-docs.diadoc.ru/ru/latest/Downloads.html)

**Comment by dorexpro** [comment]
Вроде нормально теперь. Спасибо.
