### ISSUE TITLE
Помогите разобраться с партнерством контрагента, не отправляются документы.

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#45]
Добрый день.
На портале Диадока видно, что контрагент 1 декабря подписал наше приглашение к ЭДО с файлом вложения, см. рис.:
![img-2016-12-04-10-47-09](https://cloud.githubusercontent.com/assets/20082460/20864836/f77dc824-ba0f-11e6-898e-33b42205ee56.png)
![img-2016-12-04-10-48-44](https://cloud.githubusercontent.com/assets/20082460/20864837/fc3dca6c-ba0f-11e6-8296-74c68c2979f5.png)
Но при этом документы не можем отправить контрагенту, потому что 17 ноября он нас заблокировал, как такое возможно? Соглашение на ЭДО подписано, но мы не партнеры и поэтому не можем отправить:
![img-2016-12-04-10-45-59](https://cloud.githubusercontent.com/assets/20082460/20864847/425752f2-ba10-11e6-955f-95f6bd548ac6.png)

**Comment by jakeqwert** [comment]
Получается, что 17.11.2016 16:01:15 мы отправили приглашение к ЭДО, контрагент 17 ноября нас же заблокировал, но потом передумал и 1 декабря подписал, но отправить мы не можем, как быть?

**Comment by denver069** [comment]
Отправьте приглашение контрагенту повторно.
