### ISSUE TITLE
Поле иные сведения в упд

### ISSUE THREAD

**Issue by lanrootdiadoc** [diadoc/diadocsdk-1c-docs#450]
В подключаемом модуле мы заполняем «Иные сведения» в упд:
ДополнитьМассивKeyValue(Протоконтент.AdditionalInfoId.StructedAdditionalInfos,TKey,TValue);
После этого мы видим в макете:      « Иные сведения:    Tkey : TValue   » 
Клиент хочет, чтобы в поле записывался только наименование города доставки, без двоеточий, дефисов и пр. 
Что указывать в Tkey, чтобы отображался только TValue без двоеточия?
Спасибо.

**Comment by volodkindv** [comment]
Добрый день, такой возможности нет. Поля Key и Value обязательны к заполнению.
