### ISSUE TITLE
Передача доработанных счетов-фактур из 1с на сторону Диадока

### ISSUE THREAD

**Issue by MaximF2020** [diadoc/diadocsdk-1c-docs#451]
Добрый день.

Подскажите пожалуйста, в каком модуле/процедуре/функции
происходит формирование данных для отправления
из 1С на сторону Диадока счетов-фактур.

Хотим передавать клиенту сгруппированные счета-фактуры
(несколько однотипных строк схлопывать в одну,
т.е. в 1С в акте выполненных работ остается несколько 
однотипных строк,  а клиенту уходит СЧФ с одной)
и дополнять наименование услуги, взятое из документа в 1С.

**Comment by kulakovskaya** [comment]
Добрый день. Подскажите, пожалуйста, какое из интеграционных решений используете для обмена электронными документами через Диадок?


Правильно понимаем, что вы еще не используете никаких интеграционных решений для обмена электронными документами через Диадок?

**Comment by MaximF2020** [comment]
Контур.Диадок v 5.38.19.465

**Comment by kulakovskaya** [comment]
Уточните, версию конфигурации 1С и ответьте, пожалуйста на вопросы:
1. Что подразумевается под понятием "однотипные строки"?
2. Зачем требуется передавать контрагенту документ с одной "схлопнутой позицей"?
3. Что значит "дополнять наименование услуги, взятое из документа в 1С"?

**Comment by MaximF2020** [comment]
1С ERP 2.4

   **1 Что подразумевается под понятием "однотипные строки"?**
   Строки, которые можно сгруппировать.

   Услуга1  Количество 1  Цена 100  Сумма  100
   Услуга1  Количество 1  Цена 100  Сумма  100
   Услуга1  Количество 1  Цена 100  Сумма  100

   Услуга1  Количество 3  Цена 100  Сумма  300

   **2 Зачем требуется передавать контрагенту документ с одной "схлопнутой позицей"?**
   В документах бывает много строк, клиент просит делать группировку для уменьшения
   общего количества строк

   **3 Что значит "дополнять наименование услуги, взятое из документа в 1С"?**
   К наименованию услуги добавлять комментарий из дополнительного реквизита

**Comment by kulakovskaya** [comment]
Реализация данного сценария потребует кастомизации основного модуля, поэтому рекомендуем вам доработки подключаемого модуля с использованием события ОбработатьСобытиеПослеЗаполненияКонтента. 
За более подробной консультацией обратитесь к вашему менеджеру.

**Comment by dmcural** [comment]
Здравствуйте. Дабы не плодить темы, тк проблема подобная. 
Обработка 5.38.19.46,
1с КА 2.4.11.91
После последнего обновления, 1с при печати счета-фактуры выданная решила брать номер на печать не из реквизита номер документа а из реквизита представление номера.
Данный реквизит мы активно начали использовать, для своей нумерации. 
Диадок берет данные для формирования счета фактуры по старому. В каком модуле формы я могу доработать функционал присвоения номера на печать счет фактуры?

**Comment by kulakovskaya** [comment]
Добрый день. В модуле заполнение номера на печать планируется исправить в модуле версии 5.42. В исправлении учтем реквизит "Представление номера". 
Рекомендуем следить за историей обновления модуля.
