### ISSUE TITLE
PackageSendTask2. SignerDetails заполнение полей с типом VT_BSTR. Неверный тип переменной.

### ISSUE THREAD

**Issue by SlashSep** [diadoc/diadocsdk-1c-docs#452]
Здравствуйте.
Установлена COM компонента v5.29.11.567 для произвольных систем.
Работаем через MSSQL: Microsoft SQL Server 2008 (SP4) - 10.0.6000.29 (X64) 
При попытке заполнить SignerDetails для полей с типом VT_BSTR возникает ошибка: Неверный тип переменной.

Для примера:
EXECUTE @rc = sp_OACreate 'Diadoc.DiadocClient', @DiadocAPI OUTPUT
<...>
EXECUTE @rc = sp_OASetProperty @SignerDetails, 'SignerType', '1'

Перебрал все типы sql - все равно ошибка.
Похожая проблема была в теме #378, реализация в Delphi
Побороли так: Signer.SignerDetails.SignerType := VarAsType('1', VT_BSTR);
В MSSQL нет возможности привести к типу VT_BSTR.

Странно то, что при заполнении в @DocumentToSend (получен AddDocument) поля comment такой ошибки не возникает, хотя поле так же имеет тип VT_BSTR
EXECUTE @rc = sp_OAMethod @PackageSendTask2, 'AddDocument("XmlAcceptanceCertificate", "default", "utd820_05_01_01")', @DocumentToSend output
EXECUTE @rc = sp_OASetProperty @DocumentToSend, 'Comment', 'Комментарий'

С уважением, Алексей

**Comment by GilimkhanovDenis** [comment]
Добрый день
Проверьте на версии 5.29.13
[release info](http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_29_13.html)
[download](http://1c-docs.diadoc.ru/ru/latest/Downloads.html)

**Comment by SlashSep** [comment]
Добрый день!
Проверил на версии 5.29.13 - Все работает! Спасибо!
С уважением, Алексей
