### ISSUE TITLE
Как получить объект Document из таблицы входящих документов в модуле Диадок (версия 5.34.03.228)?

### ISSUE THREAD

**Issue by ChelUsr** [diadoc/diadocsdk-1c-docs#453]
Добрый день. Есть ли возможность как то получить объект Document из таблицы входящих документов? Нужно для получения печатной формы электронного документа. Например: Вывели список документов, использовав определенные отборы на форме, далее обходим в цикле полученный список, при удовлетворении какого-либо условия получаем нужный документ и сохраняем его печатную форму.

**Comment by kulakovskaya** [comment]
Добрый день! В подключаемом модуле можно использовать событие_ПослеОбновленияСпискаДокументов.

**Comment by ChelUsr** [comment]
Не могли бы вы показать простой пример получения печатной формы из списка документов пожалуйста?

**Comment by ChelUsr** [comment]
> 
> 
> Добрый день! В подключаемом модуле можно использовать событие_ПослеОбновленияСпискаДокументов.

Есть ли хоть какой-то пример?

**Comment by kulakovskaya** [comment]
Вот пример использования метода getPrintForm:
`Если Направление = "Inbound" Тогда
    
    Счетчик = 0;
    
    Для каждого ЭлементТаблицы из ТекущаяТаблица Цикл
      
      Счетчик = Счетчик + 1;
      
      Box = ОсновнойМодуль.Модуль_РаботаССерверомДиадок.ПолучитьЯщикДиадокДляОрганизации(ЭлементТаблицы.Организация);
      
      Document = Box.GetDocumentById(ЭлементТаблицы.DocumentId);
      
      Файл = Новый Файл("c:\ПФ" + Счетчик + ".pdf");
      
      Document.GetPrintForm(Файл.ПолноеИмя, 30);
      
    КонецЦикла;
    
  КонецЕсли;`

**Comment by ChelUsr** [comment]
Спасибо большое! Получилось! Здоровья Вам.
