### ISSUE TITLE
Не обнаружено поле UniversalTransferDocumentWithHyphens

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#454]
Подскажите, пожалуйста в API что то поменялось? нет поля UniversalTransferDocumentWithHyphens в content. Документ отправляю так

 PackageSendTask = Organization.CreatePackageSendTask2();
 DocumentToSend = PackageSendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01_hyphen");
Content = DocumentToSend.content.UniversalTransferDocumentWithHyphens;

**Comment by GuninaY** [comment]
В модуле ничего не меняли, с сегодняшнего дня ни один документ не уходит

**Comment by GuninaY** [comment]
![image](https://user-images.githubusercontent.com/49683051/79557881-03850180-80ac-11ea-94ff-fbaaf468a0b3.png)

**Comment by GilimkhanovDenis** [comment]
Добрый день
Чиним

**Comment by GuninaY** [comment]
Спасибо огромное!

**Comment by GilimkhanovDenis** [comment]
Проверьте, пожалуйста, сейчас

**Comment by GuninaY** [comment]
Спасибо, все работает
