### ISSUE TITLE
Не обнаружено поле UniversalTransferDocument

### ISSUE THREAD

**Issue by Avtomir-AMK** [diadoc/diadocsdk-1c-docs#455]
Добрый день!

Сегодня с 12:00 по москве поломалась отправка документов методом AddDocument.
Отправляем документы так.
PackageSendTask = Organization.CreatePackageSendTask2();
DocumentToSend = PackageSendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01"); 
DynamicContent = DocumentToSend.Content;
Utd820Content = DynamicContent.UniversalTransferDocument;

Компоненту после ошибки обновили до последнего релиза DiadocCom_5_29_13_573_x64.dll.
Просьба помочь в решении проблемы.

![ОшибкаКонтента](https://user-images.githubusercontent.com/56300441/79559891-911a1e80-80b7-11ea-9313-772aa63e0567.jpg)

**Comment by prog22** [comment]
Аналогично, передайте хотя бы первой линии техподдержки, что имеет быть проблема с передачей через Диадок АПИ. Бухгалтера звонят, их просят ключ разработчика/код запроса/диагностику.

**Comment by GilimkhanovDenis** [comment]
Проблема та же, что #454 
Решаем

**Comment by Avtomir-AMK** [comment]
Проблема решена диадоком. Ждем до понедельника, если проблем не будет закроем обращение.

**Comment by Avtomir-AMK** [comment]
Проблема решена. Спасибо за помощь!
