### ISSUE TITLE
Подскажите, как понять, что оплата тарифа у Покупателя закончилась? По возвращаемым ошибкам это понять невозможно. Например, покупатель с id  1b501aa4dbb94351ad3207d12aebd3e2@diadoc.ru (указан выше), утверждает, что все оплатил в августе, действует ли подписка - непонятно.

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#456]
Подскажите, как понять, что оплата тарифа у Покупателя закончилась? По возвращаемым ошибкам это понять невозможно. Например, покупатель с id  1b501aa4dbb94351ad3207d12aebd3e2@diadoc.ru (указан выше), утверждает, что все оплатил в августе, действует ли подписка - непонятно.

_Originally posted by @prog22 in https://github.com/diadoc/diadocsdk-1c-docs/issues/381#issuecomment-618336598_

**Comment by volodkindv** [comment]
Если Покупатель - это вы, то при вызове большинства методов внешней компоненты вы будете получать ошибку 402 с текстом вроде "необходима оплата тарифа API".
Подписка у указанного ящика помечена как "неактивная". 
Проверить оплату в рамках этого обсуждения невозможно, этот вопрос можно решить через обращение в техподдержку или напрямую к своему менеджеру.

**Comment by prog22** [comment]
Я Поставщик. Покупатель обращается ко мне. Невозможно передать документ на подписание. На процессе отправки подписанного документа - передачи на подписание со стороны Покупателя и подписание Покупателем построен документооборот между взаимодействующими организациями. Ошибки со стороны Покупателя указаны выше. Если бы ошибка была вида "Необходима оплата тарифа", вопроса бы не было. Мне, как Поставщику, недоступна информация об оплате тарифа. Техподдержка Диадок данную информацию о Покупателе не предоставляет.
