### ISSUE TITLE
Оплата тарифа и техподдержка Диадок

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#457]
Я Поставщик. Покупатель обращается ко мне. Невозможно передать документ на подписание. На процессе отправки подписанного документа - передачи на подписание со стороны Покупателя и подписание Покупателем построен документооборот между взаимодействующими организациями. Ошибки со стороны Покупателя указаны выше. Если бы ошибка была вида "Необходима оплата тарифа", вопроса бы не было. Мне, как Поставщику, недоступна информация об оплате тарифа. Техподдержка Диадок данную информацию о Покупателе не предоставляет.

_Originally posted by @prog22 in https://github.com/diadoc/diadocsdk-1c-docs/issues/456#issuecomment-618920206_

**Comment by prog22** [comment]
Вопрос об ошибке про оплату тарифа со стороны покупателя. Ошибки про передачу на подписание - разные, указаны в оригинальном посте, но не про оплату тарифа.
Вопрос не праздный, очень много обращений к нам, Поставщику, со стороны Покупателей, а ответа нет.

**Comment by volodkindv** [comment]
Информация об оплате тарифа у Покупателя у вас будет только в том случае, если у вас будет доступ к ящику Покупателя.

При отсутствии оплаты сервис Диадок возвращает ошибку 402.

В оригинальном посте указано несколько примеров документов. По некоторым из них мы провели "расследование" и рассказали о результатах.

Сформулируйте более точно свой вопрос, чтобы на него можно было ответить.

**Comment by prog22** [comment]
У нас нет доступа к информации об оплате тарифа у Покупателя.
Предоставить ее техподдержка Диадок со стороны Поставщика не может.

Ошибка 402 не возвращается.

Посмотрите исходное обращение: https://github.com/diadoc/diadocsdk-1c-docs/issues/381

Возвращается:

1) Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ResolutionRequestTask.Send): ##100[Ошибка сервера Диадок]code:409, HTTP error: Текущее состояние документа не позволяет его подписать

2) Добрый день. Есть ящик контаргента c22dcaccc2854b60bd2649356a920d9a@diadoc.ru.
В нем часть документов передается на подписание через diadoc api (например, https://diadoc.kontur.ru/c22dcacc-c285-4b60-bd26-49356a920d9a/Document/Show?letterId=ada9c3e9-54aa-4097-81c5-a7b8dcd99907&documentId=9f1df6e5-a8da-426a-9395-c19af3bde973), а часть нет (например, https://diadoc.kontur.ru/c22dcacc-c285-4b60-bd26-49356a920d9a/Document/Show?letterId=f6f1cc14-db83-41ec-8353-9e0f596e9a77&documentId=3a75e0de-df61-4acf-8403-d1241d0001c9). При этом выдает ошибку, что в ящике не найден документ с идентификатором f6f1cc14-db83-41ec-8353-9e0f596e9a773a75e0de-df61-4acf-8403-d1241d0001c9. Хотя это идентификатор документа из примера. Подскажите, с чем это может быть связано, т.к. документ не единичный.

При этом отвечают, что данная ошибка связана с оплатой тарифа.

**Comment by alogicman** [comment]
Документ, который не получается передать на подписание, уже подписан, поэтому его текущее состояние не позволяет выполнить это действие

**Comment by prog22** [comment]
> Документ, который не получается передать на подписание, уже подписан, поэтому его текущее состояние не позволяет выполнить это действие

Да, на данный момент ситуация уже поменялась.

Сейчас основной вопрос в том, что я как Поставщик не имею доступ в ящик Покупателя.
При попытке передачи на подписание часть документов передается, часть нет. Выяснили, что это связано с оплатой тарифа API. Но при попытке передачи на подписание со стороны Покупателя возвращаются ошибки, не связанные с оплатой тарифа. Техподдержка Диадок не выдает информацию об оплате тарифа Покупателя.
Покупатель обращается к нам (Поставщику) с тем, что документы не передаются на подпись.

Можно возвращать ошибку об оплате тарифа API Покупателю при попытке передачи на подписание?

**Comment by OlgaPetushina** [comment]
Добрый день. Такая ошибка должна возвращаться. Если этого не происходит нужно разбираться предметно, нужны идентификаторы документа, который пытаются подписать, дата запроса, тело запроса и код ответа. В идеале, чтобы с проблемой обратился сам Покупатель.

**Comment by prog22** [comment]
Документ пытаются передать на подписание. Подключение по логину-паролю, а не сертификату. При попытке подписания при подключению по сертификату м.б. и вернулась бы ошибка про оплату API, но это не наш случай. Выше писали, почему часть документов передается на подписание, а часть - нет.

**Comment by GilimkhanovDenis** [comment]
Должна возвращаться ошибка про оплату. Если этого не происходит, то, как писали ранее, нужны идентификаторы документа, который пытаются подписать, дата запроса, тело запроса и код ответа. В идеале, чтобы с проблемой обратился сам Покупатель
