### ISSUE TITLE
Добавление тегов по пакету документов диадок

### ISSUE THREAD

**Issue by Avtomir-AMK** [diadoc/diadocsdk-1c-docs#458]
Добрый день!

Подскажите пожалуйста предусматривает ли компонента api добавление тегов по пакету документов сформированного методом CreatePackageSendTask2().
Инструкция добавления тегов во вложении.
![AddTeg](https://user-images.githubusercontent.com/56300441/80568522-3910df80-8a08-11ea-969a-7e5d2e8120ba.jpg)

**Comment by volodkindv** [comment]
Добрый день.
Теги можно добавить к уже отправленным документам через [Document.CreateCustomDataPatchTask](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html#Document.CreateCustomDataPatchTask).

**Comment by Avtomir-AMK** [comment]
Спасибо за подсказку. Кодом добавили пользовательские данные.
Подскажите, пожалуйста, дело в том, что в WEB-интерфейсе Диадок у нас нет ссылки «Добавить теги».
Хотелось бы понять, это дополнительный функционал, которого может не быть у большинства пользователей Диадок, или именно мы просто что-то делаем не так? Скрин как у нас на сайте и какую инструкцию нам прислал контрагент ниже.
![Tegi](https://user-images.githubusercontent.com/56300441/80669671-0d4c3300-8ab6-11ea-93ea-2bb4186c6384.jpg)

**Comment by OlgaPetushina** [comment]
В веб-интерфейсе это доп.функциональность доступна за отдельную плату.
