### ISSUE TITLE
Отправка внутренних документов через PackageSendTask2 

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#459]
При отправке внутреннего документа необходимо обязательно указывать поле FromDepartmentId, иначе возвращается ошибка при отправке: "##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.FromDepartmentId is required field.". Но в организации одно подразделение - головное. При этом если смотреть Organization.Departments.Count = 0. Получается, я не могу указать FromDepartmentId, т.к. id подразделения нет. Как быть?

**Comment by volodkindv** [comment]
Внутренние документы предназначены для передачи между подразделениями организации.
Вам необходимо создать несколько подразделений.
Если хотите отправлять документы в/из головного подразделения, то указывайте для него "нулевой" гуид: 00000-0000-...

**Comment by prog22** [comment]
Указываю "нулевой" гуид, получаю ту же ошибку: ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.ToDepartmentId is required field.
![image](https://user-images.githubusercontent.com/22831210/81286802-b248ac00-9072-11ea-8dff-80d528399f45.png)

**Comment by prog22** [comment]
Т.е. если у меня одно подразделение (головное), я всегда обязан добавлять еще одно "фиктивное" подразделение?
Так как если указывать "нулевой" гуид и для SendTask.FromDepartmentId и для SendTask.ToDepartmentId, то возвращается ошибка: ##100[Ошибка сервера Диадок]code:400, HTTP error: Подразделение получатель совпадает с отправителем

**Comment by prog22** [comment]
С чем связано такое ограничение, ведь через броузер такого ограничения нет. Просто указываешь в качестве поля Подразделение "Головное подразделение" и документ отправляется.

**Comment by prog22** [comment]
Вопрос связан с тем, что для организации не требуется вести список подразделений и через броузер внутренние документы отправлять можно (не ведя список подразделений), а автоматизировать процесс передачи через внутреннюю компоненту, получается, невозможно (без ведения списка подразделений)?

**Comment by volodkindv** [comment]
В браузере такое ограничение тоже присутствует:

![image](https://user-images.githubusercontent.com/12305552/81289134-50db0a00-907f-11ea-88af-da8e0ad56762.png)

Оно заложено изначальной логикой: внутренние документы должны передаваться между разными подразделениями одной организации.

Если вы такого ограничения не видите, значит, у вас настроены подразделения.

Если подразделений нет и ограничения вы не видите, то напишите адрес ящика, на котором проверяли.

**Comment by prog22** [comment]
Извините, в тестовой организации удалил тестовое подразделение и получил ограничение как у Вас, поэтому скорректировал комментарий про возможность отправлять из браузера.
Подскажите, а какой смысл, имея два подразделения при отправке через браузер указывать "Головное подразделение"? В браузере же указывается одно подразделения, а не отправитель и получатель.

**Comment by volodkindv** [comment]
Подразделение-отправитель в браузере определяется по текущему сотруднику. Например, если сотрудник относится к "Головному подразделению", и отправляет тоже в "Головное подразделение", то браузер не даст отправить внутренний документ, как и API.

**Comment by prog22** [comment]
Спасибо за помощь, действительно, сотрудник головного подразделения не может передать документы в головное подразделение через браузер.
