### ISSUE TITLE
Отправка формализованных УПД и УКД

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#46]
Добрый день.
Подскажите, пожалуйста, COM-компонента для встраивания в произвольные системы-версия 5.10.0.161 (COM-компонента для встраивания в произвольные системы, для 64-х битных приложений - версия 5.10.0.161) уже поддерживают документы УПД и УКД? 
В описании http://1c-docs.diadoc.ru/ нашел типы документа UniversalTransferDocument и UniversalTransferDocumentRevision, а корректировочного документа не нашел?
Подскажите, пожалуйста, уже можно отправлять и подписывать UniversalTransferDocument,  UniversalTransferDocumentRevision и как отправить корректировочный документ?

**Comment by denver069** [comment]
Добрый день! Во внешней компоненте версии 5.10.0.161 реализован только UniversalTransferDocument, соответственно его можно отправлять и принимать. UniversalTransferDocumentRevision и UniversalTransferDocumentCorrection будут реализованы в следующих версиях компоненты.

**Comment by jakeqwert** [comment]
А можете, подсказать плановый срок реализации UniversalTransferDocumentCorrection, просто если сейчас запущу использование UniversalTransferDocument, а числа 4 января нужно будет отправить много  UniversalTransferDocumentCorrection, т.к. конец года. Нужно оценить целесообразность перехода

**Comment by LyubovZykova** [comment]
Добрый день! UniversalTransferDocumentCorrection в компоненте будет реализован ориентировочно в конце января-феврале 2017 года. Поэтому если вам нужно использовать сразу и УПД, и корректировки УПД, то лучше немного подождать.

**Comment by jakeqwert** [comment]
Добрый день, подскажите, пожалуйста. 
В COM-компоненте для встраивания в произвольные системы версия 5.14.0.176, появилась возможность отправлять UniversalTransferDocumentRevision и UniversalTransferDocumentCorrection ?

**Comment by denver069** [comment]
В 5.14.0.176 этих документов нет.
Возможность отправки UniversalTransferDocumentRevision и UniversalTransferDocumentCorrection будет реализована в следующей версии компоненты.
