### ISSUE TITLE
Как создать документ с марками?

### ISSUE THREAD

**Issue by KrykovLev** [diadoc/diadocsdk-1c-docs#460]
Здравствуйте!
Используем модуль для 1с 7.7 (версия 2.10.01)
Как втолкнуть в документ марки для Честного Знака (проект по маркировке)?
Какие поля и как заполнять? Есть ли методичка какая-то?
Пытаюсь затолкнуть их по аналогии с ГТД:
УЗВКПр("Table.Item[" + ТабЗапроса1.НомерСтроки + ].CustomsDeclarations[1].CustomsDeclaration.DeclarationNumber", лев(сокрлп(ТабЗапроса1.GTD),29)); 
УЗВКПр("Table.Item[" + НомСтр + "].ItemIdentificationNumbers[1].ItemIdentificationNumber.Unit", сокрлп(ТабЗапросаМарки.CIS)); 
Ничего не получается. 
Еще и в названии файла должен изменится префикс на ON_NSCHFDOPPRMARK

**Comment by kuiv** [comment]
Исправлено в 2.11.21. 
Для наполнения документа КИЗами в модуле ОбработкаПросмотраУПД.ert найти строку "// маркировка, КИЗы " и раскомментировать нужные строки. Изменить  "нужное значение" на нужное значение )))
