### ISSUE TITLE
Подскажите как по документу Укд найти документ УПД?

### ISSUE THREAD

**Issue by darujo** [diadoc/diadocsdk-1c-docs#461]
Подскажите как по документу Укд найти документ УПД? Метод GetDocumentPackage возращает один документ укд.

**Comment by kulakovskaya** [comment]
Добрый день! Метод GetDocumentPackage возвращает только те документы, которые были отправлены одним Message. 
Выполнить поиск УПД можно по InitialDocumentId, который можно указать при отправке УКД для его связки с УПД. Если данный параметр был указан, то можно воспользоваться методом Organization.GetDocumentById и получить УПД.
