### ISSUE TITLE
Как в титуле покупателя по упд заполнить код содержания оперции.

### ISSUE THREAD

**Issue by goleaff** [diadoc/diadocsdk-1c-docs#462]
Нету свойств у титула код содержания операции или не задокументированно.

**Comment by darujo** [comment]
vContentItems = iReplyTask:ContentItems.
 do vi = 1 to vContentItems:count:
      vContentItem = vContentItems:GetItem(vi - 1 ):Content.
      vBuyerTitle = vContentItem:UniversalTransferDocumentBuyerTitle.

**Comment by goleaff** [comment]
поля код содержания операции нету  смотрите внимательно.

**Comment by kulakovskaya** [comment]
Добрый день! Код содержания операции появился только в УПД формата 820@ приказа. Для работы с документами данного формата нужно смотреть XSD-схему и заполнять DynamicContent - http://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html?highlight=DynamicContent

**Comment by goleaff** [comment]
я так и делаю только не вижу названия этого поля, как оно именутся?

**Comment by goleaff** [comment]
Для работы с документами данного формата нужно смотреть XSD-схему где ее посмотреть?

**Comment by goleaff** [comment]
мне нужно наименование поля в динамическом контенте код содержимого операции, чтобы я мог к нему обратится, и наименования полей в динамическом контенте уже у кода вида операции, чтобы обратится к его свойствам.

**Comment by kulakovskaya** [comment]
Наименование поля Код содержания операции - это TotalCode.

**Comment by darujo** [comment]
vContentOperCode:TotalCode = vOperationContent. /* КодИтога  Принимает значение:
1 – товары (работы, услуги, права) приняты без расхождений (претензий)   |
2 – товары (работы, услуги, права) приняты с расхождениями (претензией)   |
3 – товары (работы, услуги, права) не приняты

**Comment by goleaff** [comment]
отлично.Спасибо.
