### ISSUE TITLE
Обрезается наименование у покупателя ИП

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#463]
Добрый день! Подскажите в чем причина, того что в УПД отражается в покупателе только Иванов Иван Иванович, хотя в структуру  Buyer = Content.Buyers.AddBuyer() передается полное - Индивидуальный предприниматель Иванов Иван Иванович

**Comment by GuninaY** [comment]
Для примера УПД https://diadoc.kontur.ru/54d0b467-aade-47d6-8136-a2bbe2eeb67d/Document/Show?letterId=f2d2b558-32b6-4afa-bbe7-5a21188a0e09&documentId=772bc647-20d8-4334-8135-73549bc49472

**Comment by kulakovskaya** [comment]
Добрый день! В соответствии с приказами ФНС, регламентирующими форматы электронных документов, в сведениях о физических лицах должны указываться только ИНН физического лица и его ФИО. Это значит, что указание формы собственности (приставки «ИП») у индивидуального предпринимателя не требуется.

**Comment by GuninaY** [comment]
Спасибо, поняла
