### ISSUE TITLE
PackageSendtTask2.Send() - не удается получить ранее отправленный пакет

### ISSUE THREAD

**Issue by IrinaZ86** [diadoc/diadocsdk-1c-docs#465]
Добрый день
Использую COM-компоненту для встраивания в произвольные системы версии DiadocCom_5_29_7_549

При отправке пакета первоначально запоминаем OperationId

Но почему-то при отправке пакета с таким OperationId через PackageSendtTask2.Send()  повторно получаем ошибку:
PackageSendTask2.Send: ##100[Ошибка сервера Диадок]code:400, 
HTTP error: Could not parse boxId in boxId query param:  

Пробовала и с последней версией компоненты DiadocCom_5_29_14_577 - тоже самое

**Comment by GilimkhanovDenis** [comment]
Здравствуйте.
Можете показать как заполнен объект PackageSendtTask2 ?

**Comment by IrinaZ86** [comment]
Добрый день

Set packDocs = Organization.CreatePackageSendTask2()
packDocs.OperationId = opID
Set objDocs = packDocs_send.Documents()		

opID было получено при отправке пакета в первый раз с использованием DiadocPackage.OperationId

**Comment by IrinaZ86** [comment]
Извините, строчку пропустила - как раз в которой ошибка

Set packDocs = Organization.CreatePackageSendTask2()
packDocs.OperationId = opID
Set packDocs_send = packDocs.send ()		
Set objDocs = packDocs_send.Documents()

**Comment by GilimkhanovDenis** [comment]
Добрый день
Попробуйте на релизе 5.30.0

[release info](http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_30_0.html)
[download page](http://1c-docs.diadoc.ru/ru/latest/Downloads.html)

**Comment by IrinaZ86** [comment]
На данном релизе работает, спасибо
