### ISSUE TITLE
Не обнаружена процедура CreatePackageSendTask2

### ISSUE THREAD

**Issue by mishgan75** [diadoc/diadocsdk-1c-docs#468]
ДиадокАпи.GetVersion() | "5.3.0.55" | Строка
SendTask = Organization.CreatePackageSendTask2();
РаботаССерверомДиадок.Модуль(2036)}: Метод объекта не обнаружен (CreatePackageSendTask2)

**Comment by volodkindv** [comment]
Версия 5.3.0.55 выпущена в 2015 году: http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_3_0.html
Попробуйте обновиться на версию 5.30.0. Скорее всего, остальные 2 ваших тикета связаны с этим же. #467, #469

**Comment by mishgan75** [comment]
Я скачивал последнюю https://sdk-new.readthedocs.io/en/latest/Downloads.html,
что это за сайт, почему он как две капли воды похож на Ваш и при этом
содержит не актуальную информацию
пт, 29 мая 2020 г. в 12:30, Данила Володькин <notifications@github.com>:

**Comment by mishgan75** [comment]
Я скачивал последнюю https://sdk-new.readthedocs.io/en/latest/Downloads.html, что это за сайт, почему он как две капли воды похож на Ваш и при этом содержит не актуальную информацию

**Comment by IrinaShmonina** [comment]
@mishgan75 откуда вы взяли ссылку на этот ресурс? 
Актуальная документация находится здесь - http://1c-docs.diadoc.ru/ru/latest/Downloads.html

**Comment by mishgan75** [comment]
В поисковике набрал


пт, 29 мая 2020 г. в 15:09, IrinaShmonina <notifications@github.com>:
