### ISSUE TITLE
Интеграция. Первые шаги.

### ISSUE THREAD

**Issue by ShibaevAnton** [diadoc/diadocsdk-1c-docs#47]
Добрый день. 

На этом сайте первый раз так что куда писать, непонятно. Было бы проще пообщаться по почте (a_shibaev@a4m.ru).

Есть задача по интеграции с 1С. По ряду причин решили использовать для этого API. Ознакомились с документацией. Так как в каждой религии свои боги то возникает некоторое непонимание как это устроено. При попытке получить ответы на наши вопросы у нашего менеджера мы били посланы к вам, а точнее на этот ресурс.

В настоящее время получили ключ разработчика.

Вопросы следующие:
1) Какой функцией можно получит текущий статус документа по идентификатору 1С.
2) Какой функцией можно получить печатную форму документа по идентификатору 1С.
3) Можно ли получить только измененные документы. В настоящее время стоит задача по отображению статуса в 1С. Для этого нам нужно хранить статус в базе, что сразу же приводит к актуализации статусов. Поэтому и возник вопрос как обновлять статус в 1С? Самое правильное было бы получить все изменения, но непонятно, у вас это вообще под капотом есть?
 
Хотелось бы эту таблицу обновлять. Как это лучше сделать?

С уважением Шибаев А.И.

**Comment by denver069** [comment]
> По ряду причин решили использовать для этого API

Правильно ли я понял? Вы планируете работать напрямую с API Диадока без использования [внешней компоненты для 1С](http://1c-docs.diadoc.ru/ru/latest/description.html)?

**Comment by ShibaevAnton** [comment]
Сложно сказать.

Наверное с использованием. 

Я планировал. Взять за основу уже разработанную вами обработку. Там вроде используется.

Да и в инструкции по api тоже используется компонента...
http://1c-docs.diadoc.ru/ru/latest/index.html

С уважением Шибаев А.И.

**Comment by ShibaevAnton** [comment]
Основной вопрос сейчас как корректор обновлять статус документа.

Нам по задаче необходимо реализовать вывод статуса ЭДО в формы документов 1С.

Исходя из задачи необходимо статусы хранить в 1С. И пока планиру сделать таблицу [Документ1ССсылка|СтатусЭДО]

Эту таблицу нужно обновлять. И возникают вопросы как от вас это получать. Есть ли у вас некий буфер "только обновленные". Если есть то все просто: выполнили функцию - получили резульат - 3 объекта - обновили таблицу. Если нет такого буфера, то задача становиться сложнее, надо организовывать вечный цикл в котором по Ссылке 1С получать статус и если он отличается то перезаписывать запись в таблице.

Пока непонятно как делать, может вы, зная как у вас все под капотом работает, посоветуете что то полезное полезное, как нам лучше организовать работу с таблицей...

**Comment by denver069** [comment]
Понял вас.
Идентификатор 1С не хранится в базе Диадока, поэтому хранить нужно наоборот идентификатор Диадока в базе 1С. В нашем модуле для этого используется механизм дополнительных свойств. Что касается изменения статусов, если хотите получать только изменения то читайте ленту событий. Читать ленту событий во внешней компоненте можно методом [GetDocumentEventList](http://diadocsdk-1c.readthedocs.io/ru/latest/GetDocumentEventList.html?highlight=Event)

**Comment by ShibaevAnton** [comment]
Прочитал... GetDocumentEventList(<EventId>)

Я правильно понял, что для корректной работы мне нужно хранить EventId. И постоянно его презаписывать при получении нового пакета?

Вопрос 2: Каким методом получить статус документа имея его айди?
Вопрос 3: Открытие печатной формы с подписями. Я видел метод позволяющий получить PDF версию документа. Этот PDF - печатная форма документа? Как в вашей обработке 1С? Если макет документа изменен под стандарты компании, какая форма вернется в PDF? Унифицированная или измененая?
