### ISSUE TITLE
как получить ссылки на документ для получателя (для рассылки по е-mail)

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#471]
как получить ссылки на документ:
1) ссылка из кабинета получателя (для рассылки по е-mail)
2) ссылка из кабинета получателя в роуминге. (Тензора и др. операторы)
Известен идентификатор документа из кабинета отправителя и идентификатор получателя.

**Comment by IrinaShmonina** [comment]
@jakeqwert Здравствуйте,
уточните, пожалуйста, сценарий. На какие документы нужна ссылка? Для чего?

**Comment by jakeqwert** [comment]
Я отправил документ контрагенту и нужно ему в письме скинуть ссылку на документ

**Comment by kulakovskaya** [comment]
Добрый день. Данную информацию получить невозможно.
