### ISSUE TITLE
Как я могу установить тип данных в реквизитах DynamicContent.UniversalTransferDocument?

### ISSUE THREAD

**Issue by mishgan75** [diadoc/diadocsdk-1c-docs#472]
Здравствуйте.
Установлена COM компонента v5.30.0.580 для произвольных систем.
Добавляю документ в пакет:
SendTask = Organization.CreatePackageSendTask2();
DocumentToSend = SendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01");
DocumentToSend.Comment = "Это УПД с заполнением контента средствами компоненты";
DynamicContent = DocumentToSend.Content;
Utd820_SellerContent = DynamicContent.UniversalTransferDocument;

Utd820_SellerContent все типы строковые.
При выполнении команды SendTask.Send() вылетает список ошибок связанных с неверным типом данных:
Line: 2, Position: 46, /UniversalTransferDocument[1]/@DocumentDate: The 'DocumentDate' attribute is invalid - The value '29.05.2020 12:00:21' is invalid according to its datatype 'date' - The Pattern constraint failed.
Line: 3, Position: 39, /UniversalTransferDocument[1]/Table[1]/@Vat: The 'Vat' attribute is invalid - The value '66018,6' is invalid according to its datatype 'Decimal' - The string '66018,6' is not a valid Decimal value.
Line: 3, Position: 53, /UniversalTransferDocument[1]/Table[1]/@Total: The 'Total' attribute is invalid - The value '396111,6' is invalid according to its datatype 'Decimal' - The string '396111,6' is not a valid Decimal value.
Line: 4, Position: 449, /UniversalTransferDocument[1]/Table[1]/Item[1]/@TaxRate: The 'TaxRate' attribute is invalid - The value '20' is invalid according to its datatype 'TaxRateWithTwentyPercentAndTaxedByAgent' - The Enumeration constraint failed.
Line: 4, Position: 494, /UniversalTransferDocument[1]/Table[1]/Item[1]/@Vat: The 'Vat' attribute is invalid - The value '9122,4' is invalid according to its datatype 'Decimal' - The string '9122,4' is not a valid Decimal value.
Line: 4, Position: 507, /UniversalTransferDocument[1]/Table[1]/Item[1]/@Subtotal: The 'Subtotal' attribute is invalid - The value '54734,4' is invalid according to its datatype 'Decimal' - The string '54734,4' is not a valid Decimal value.
Line: 4, Position: 526, /UniversalTransferDocument[1]/Table[1]/Item[1]/@ItemMark: The 'ItemMark' attribute is invalid - The value 'Property' is invalid according to its datatype 'Integer' - The string 'Property' is not a valid Integer value.
Line: 5, Position: 385, /UniversalTransferDocument[1]/Table[1]/Item[2]/@TaxRate: The 'TaxRate' attribute is invalid - The value '20' is invalid according to its datatype 'TaxRateWithTwentyPercentAndTaxedByAgent' - The Enumeration constraint failed.
Line: 5, Position: 430, /UniversalTransferDocument[1]/Table[1]/Item[2]/@Vat: The 'Vat' attribute is invalid - The value '17140,2' is invalid according to its datatype 'Decimal' - The string '17140,2' is not a valid Decimal value.
Line: 5, Position: 444, /UniversalTransferDocument[1]/Table[1]/Item[2]/@Subtotal: The 'Subtotal' attribute is invalid - The value '102841,2' is invalid according to its datatype 'Decimal' - The string '102841,2' is not a valid Decimal value.
Line: 5, Position: 464, /UniversalTransferDocument[1]/Table[1]/Item[2]/@ItemMark: The 'ItemMark' attribute is invalid - The value 'Property' is invalid according to its datatype 'Integer' - The string 'Property' is not a valid Integer value.
Line: 6, Position: 385, /UniversalTransferDocument[1]/Table[1]/Item[3]/@TaxRate: The 'TaxRate' attribute is invalid - The value '20' is invalid according to its datatype 'TaxRateWithTwentyPercentAndTaxedByAgent' - The Enumeration constraint failed.
Line: 6, Position: 430, /UniversalTransferDocument[1]/Table[1]/Item[3]/@Vat: The 'Vat' attribute is invalid - The value '12821,4' is invalid according to its datatype 'Decimal' - The string '12821,4' is not a valid Decimal value.
Line: 6, Position: 444, /UniversalTransferDocument[1]/Table[1]/Item[3]/@Subtotal: The 'Subtotal' attribute is invalid - The value '76928,4' is invalid according to its datatype 'Decimal' - The string '76928,4' is not a valid Decimal value.
Line: 6, Position: 463, /UniversalTransferDocument[1]/Table[1]/Item[3]/@ItemMark: The 'ItemMark' attribute is invalid - The value 'Property' is invalid according to its datatype 'Integer' - The string 'Property' is not a valid Integer value.
Line: 7, Position: 386, /UniversalTransferDocument[1]/Table[1]/Item[4]/@TaxRate: The 'TaxRate' attribute is invalid - The value '20' is invalid according to its datatype 'TaxRateWithTwentyPercentAndTaxedByAgent' - The Enumeration constraint failed.
Line: 7, Position: 432, /UniversalTransferDocument[1]/Table[1]/Item[4]/@Vat: The 'Vat' attribute is invalid - The value '26934,6' is invalid according to its datatype 'Decimal' - The string '26934,6' is not a valid Decimal value.
Line: 7, Position: 446, /UniversalTransferDocument[1]/Table[1]/Item[4]/@Subtotal: The 'Subtotal' attribute is invalid - The value '161607,6' is invalid according to its datatype 'Decimal' - The string '161607,6' is not a valid Decimal value.
Line: 7, Position: 466, /UniversalTransferDocument[1]/Table[1]/Item[4]/@ItemMark: The 'ItemMark' attribute is invalid - The value 'Property' is invalid according to its datatype 'Integer' - The string 'Property' is not a valid Integer value.
Line: 16, Position: 25, /UniversalTransferDocument[1]/Sellers[1]/Seller[1]/OrganizationDetails[1]/@OrgType: The 'OrgType' attribute is invalid - The value 'LegalEntity' is invalid according to its datatype 'OrganizationType' - The Enumeration constraint failed.
Line: 25, Position: 25, /UniversalTransferDocument[1]/Buyers[1]/Buyer[1]/OrganizationDetails[1]/@OrgType: The 'OrgType' attribute is invalid - The value 'LegalEntity' is invalid according to its datatype 'OrganizationType' - The Enumeration constraint failed.
Line: 34, Position: 25, /UniversalTransferDocument[1]/Shippers[1]/Shipper[1]/OrganizationDetails[1]/@OrgType: The 'OrgType' attribute is invalid - The value 'LegalEntity' is invalid according to its datatype 'OrganizationType' - The Enumeration constraint failed.
Line: 43, Position: 25, /UniversalTransferDocument[1]/Consignees[1]/Consignee[1]/OrganizationDetails[1]/@OrgType: The 'OrgType' attribute is invalid - The value 'LegalEntity' is invalid according to its datatype 'OrganizationType' - The Enumeration constraint failed.
Line: 51, Position: 96, /UniversalTransferDocument[1]/Signers[1]/SignerDetails[1]/@SignerType: The 'SignerType' attribute is invalid - The value 'LegalEntity' is invalid according to its datatype 'String' - The Enumeration constraint failed.
Line: 51, Position: 174, /UniversalTransferDocument[1]/Signers[1]/SignerDetails[1]/@SignerStatus: The 'SignerStatus' attribute is invalid - The value 'SellerEmployee' is invalid according to its datatype 'Integer' - The string 'SellerEmployee' is not a valid Integer value.
Line: 51, Position: 204, /UniversalTransferDocument[1]/Signers[1]/SignerDetails[1]/@SignerPowers: The 'SignerPowers' attribute is invalid - The value '' is invalid according to its datatype 'Integer' - The string '' is not a valid Integer value.
Как я могу установить тип данных в реквизитах DynamicContent.UniversalTransferDocument?

**Comment by mishgan75** [comment]
![Kontent](https://user-images.githubusercontent.com/30045276/83538224-3f5e1400-a4fe-11ea-8fe7-6ce66e11f9d7.jpg)

**Comment by azhipaigor** [comment]
Здравствуйте. Динамический контент является проекцией схемы user data xsd АПИ Диадок (https://api-docs.diadoc.ru/ru/latest/http/GenerateTitleXml.html), из нее следуют все ограничения типов данных. user data xsd можно сохранить на диск с помощью метода компоненты [Organization.SaveUserDataXSD](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html?highlight=SaveUserDataXSD#organization-saveuserdataxsd).

В вашем случае валидация не проходит тк нарушены следующие ограничения: 
- тип "date" должен быть "Дата в формате ДД.ММ.ГГГГ (01.01.1800 - 31.12.2099)";
- тип "decimal" должен иметь разделитель ".", а не ",";
- свойство "TaxRate" имеет тип "TaxRateWithTwentyPercentAndTaxedByAgent" и принимает значения: "без НДС",  "0%", "10%", "18%", "20%", "10/110", "18/118", "20/120", "НДС исчисляется налоговым агентом";
- свойство "ItemMark" имеет тип "integer"
- свойство "OrgType", имеет тип "OrganizationType" и принимает значения от 1 до 4: "1" (Сведения о юридическом лице, состоящем на учете в налоговых органах // СвЮЛУч), "2" (Сведения об индивидуальном предпринимателе// СвИП), "3" (Сведения об иностранном лице, не состоящем на учете в налоговых органах // СвЮлНеУч, СвИнНеУч) или "4" (Сведения о физическом лице // СвФл);
- свойство "SignerType" принадлежащее типу "ExtendedSignerDetailsBase" принимает значения от 1 до 3: "1" (Представитель юридического лица (ЮЛ)), "2" (Индивидуальный предприниматель (ИП)), "3" (Физическое лицо (ФЛ));
- свойство "SignerStatus" принадлежащее типу "ExtendedSignerDetails" принимает значения от 1 до 4: "1" (работник организации продавца товаров (работ, услуг, имущественных прав) ИЛИ работник организации покупателя), "2" ( работник организации - составителя информации продавца ИЛИ работник организации – составителя информации покупателя), "3" (работник иной уполномоченной организации), "4" (уполномоченное физическое лицо, в том числе индивидуальный предприниматель);
- свойство "SignerPowers" принадлежащее типу "ExtendedSignerDetails_SellerTitle" принимает значения от 0 до 6: "0" (лицо, ответственное за подписание счетов-фактур), "1" (лицо, совершившее сделку, операцию), "2" (лицо, совершившее сделку, операцию и ответственное за ее оформление), "3" (лицо, ответственное за оформление свершившегося события), "4" (лицо, совершившее сделку, операцию и ответственное за подписание счетов-фактур), "5" (лицо, совершившее сделку, операцию и ответственное за её оформление и за подписание счетов-фактур), "6" (лицо, ответственное за оформление свершившегося события и за подписание счетов-фактур).

**Comment by mishgan75** [comment]
Вы может не видели картинку. Поясняю Com объект был создан по примеру описанном в документации и атрибуты DocumentDate, 'Total','Vat','TaxRate' ,'Subtotal'  и др имею формат строковый, и несмотря на то что я передаю Дату или число Content преобразует значение в строку. Как мне создать content c Правильными типами? Как например в не рекомендованных CreateSendTask
![контент2](https://user-images.githubusercontent.com/30045276/83621768-c7dcc300-a597-11ea-8db8-8ef4930be5cc.jpg)

**Comment by azhipaigor** [comment]
Динамический контент действительно не имеет такой типизации как старые SendTask и PackageSendTask и работает только со строковыми типами. Конвертация типов в строки происходит не на уровне компоненты, а на уровне 1С. Поэтому если попробовать задать значения из не строковых 1С-типов, будут получены строки в формате по-умолчанию для 1С.  Что-бы создать контент с "правильными типами" нужно со стороны 1С задавать не типизированные объекты, а строки в ожидаемых динамическим контентом форматах. На данный момент только такой путь, возможно в будущем появится типизация с автоматической конвертацией.

**Comment by mishgan75** [comment]
Про типы понятно, решаемо, но почему в документации нет никаких указаний когда использовать текст, а когда цифры, наткнулся на тот факт что в объекте SignerDetails для документа SignerStatus = 1,2,3 или 4, а в SignTask = это строка типа "LegalEntity" и тд
Кстати, а можно сделать метод HasProperty не чувствительным к Регистру, просто в одном объекте Есть INN а в другом Inn и приходится 2 раза проверять

**Comment by azhipaigor** [comment]
Старый вариант и PackageSendTask2 основаны на разных концепциях со стороны Диадок АПИ, эти различия сложно в удобном виде отразить в документации. При работе с динамическом контентом наиболее точная документация user data xsd. Ваше пожелание учтем.

HasProperty сделаем.
