### ISSUE TITLE
/UniversalTransferDocument/Signers/SignerDetails: Invalid @Inn=5835042666 for @SignerType=LegalEntity

### ISSUE THREAD

**Issue by mishgan75** [diadoc/diadocsdk-1c-docs#473]
Здравствуйте.
Установлена COM компонента v5.30.0.580 для произвольных систем.
Добавляю документ в пакет:
SendTask = Организация.CreatePackageSendTask2();
DocumentToSend = SendTask.AddDocument ("UniversalTransferDocument", "СЧФДОП", "UTD820_05_01_01");
DocumentToSend.Comment = "Это УПД с заполнением контента средствами компоненты";
DynamicContent = DocumentToSend.Содержание;
Utd820_SellerContent = DynamicContent.UniversalTransferDocument;
При выполнении команды SendTask.Send() вылетает ошибка:
/UniversalTransferDocument/Signers/SignerDetails: Invalid @Inn=5835042666 for @SignerType=LegalEntity
Требуется ли заполнять Этот реквизит и если требуется 
то какой из трех выбрать для ответственного лица организации?
LegalEntity -представитель юридического лица
IndividualEntity - индивидуальный предприниматель
PhysicalPerson - физическое лицо

**Comment by azhipaigor** [comment]
В динамическом контенте для "UniversalTransferDocument", "СЧФДОП", "UTD820_05_01_01" SignerType принимает значения от 1 до 3, соответственно: "1" (Представитель юридического лица (ЮЛ)), "2" (Индивидуальный предприниматель (ИП)), "3" (Физическое лицо (ФЛ)). О причинах такого поведения отвечал здесь https://github.com/diadoc/diadocsdk-1c-docs/issues/472.
