### ISSUE TITLE
Ошибка добавления документов в коллекцию DocumentsToSend методом PackageSendTask2.AddDocument - Protobuf parse error: required fields missing: (cannot determine missing fields for lite message)

### ISSUE THREAD

**Issue by Avtomir-AMK** [diadoc/diadocsdk-1c-docs#474]
Добрый день!

Сегодня с 14:56 ошибки добавления документов в отправляемый пакет.
Описание ошибки ниже.
Подскажите пожалуйста в чем причина ошибки и когда она будет устранена?

ЗаданиеОтправкиПакетаДокументов = ОрганизацияДиадок.CreatePackageSendTask2();

Ошибка при вызове метода контекста (AddDocument)
DocumentToSend = ЗаданиеОтправкиПакетаДокументов.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01"); //"СЧФДОП"  utd820_05_01_01_Hyphen utd820_05_01_01
по причине:
Произошла исключительная ситуация (PackageSendTask2.AddDocument): Protobuf parse error: required fields missing: (cannot determine missing fields for lite message)

С уважением, Алексей

**Comment by azhipaigor** [comment]
Поправили, теперь все должно работать.

**Comment by Avtomir-AMK** [comment]
Добрый день!

Проверили. Все в порядке.
Спасибо за помощь.

С уважением, Алексей.

**Comment by Avtomir-AMK** [comment]
Устранено.

**Comment by Avtomir-AMK** [comment]
Добрый день.

Данная ошибка вернулась.
Подскажите, пожалуйста, в чем причина? Будет ли устранена?
Спасибо.

С уважением, Максим.

**Comment by GilimkhanovDenis** [comment]
Добрый день. Укажите Guid организации для которойвозникает ошибка и версию используемой компоненты

**Comment by Avtomir-AMK** [comment]
GUID - 58b86c0ccc8c4dd1bdf7c8c2afa36207@diadoc.ru
Версия компоненты - DiadocCom_5_33_4_674_x64

**Comment by GilimkhanovDenis** [comment]
Добрый день.
Не нашли в логах каких-либо запросов, отправленных из компоненты 5.33.4.674 - видим только запросы от компоненты 5.29.13.573
Ошибку воспроизвести тоже не получилось, метод PackageSendTask2.AddDocument()  отрабатывает без ошибки

Проверьте что у вас действительно подключена указанная версия компоненты и что ошибка возникает именно на методе PackageSendTask2.AddDocument()
