### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by darujo** [diadoc/diadocsdk-1c-docs#475]
Подскажите какой метод авторизации используется при подключение через Proxy сервер и можно ли его как-то задать?

**Comment by kulakovskaya** [comment]
Добрый день! В документации описано про авторизацию через прокси-сервер http://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html.

**Comment by darujo** [comment]
Это я видел, но там не описано какой тип авторизации используется на прокси сервер.
.
