### ISSUE TITLE
Подскажите с чем может быть связана ошибка куда ей нужен доступ?

### ISSUE THREAD

**Issue by darujo** [diadoc/diadocsdk-1c-docs#476]
![image](https://user-images.githubusercontent.com/65738957/83771956-83caea80-a68b-11ea-873c-9c3e4c2a28ad.png)

**Comment by volodkindv** [comment]
Добрый день.
Опишите подробно сценарий воспроизведения ошибки. И контекст: используемая система, версия компоненты.

**Comment by volodkindv** [comment]
Пока можно предположить, что внешняя компонента регистрировалась из dll, расположенном на диске, который зашифрован BitLocker. Точнее по этому скрину сказать что-либо сложно.

**Comment by darujo** [comment]
Добрый день.
Бибилиотека находится не на зашифрованном диске. Так как с помощью библиотеки документы у нас получаются

create "Diadoc.DiadocClient":U mDiadocApi.

   /*Задаем параметры подлючения к серверу*/
   /*Получение списка сертификатов*/

   vCertificates = mDiadocApi:GetPersonalCertificates(true).
   if vCertificates:count = 1 then do:
     v-rid-list = vCertificate:GetItem(0):SerialNumber .
     apply "GO" to FRAME {&frame-name} .
   end.
   else do:  
   do vi = 1 to  vCertificates:count:
      vCertificate = vCertificates:GetItem(vi - 1).

      create tt-sertif .
      tt-sertif.Name_ = vCertificate:name .
      tt-sertif.BeginDate = vCertificate:begindate .
      tt-sertif.EndDate = vCertificate:enddate .
      tt-sertif.OrganizationName = vCertificate:OrganizationName .
      tt-sertif.SerialNumber = vCertificate:SerialNumber . 
      tt-sertif.Thumbprint  = vCertificate:Thumbprint .
   end.
   end.

**Comment by volodkindv** [comment]
Зашифрованный диск в системе присутствует?
На какой строке кода возникает ошибка?
Возможно, на зашифрованном диске лежит контейнер ключа сертификата.

**Comment by darujo** [comment]
К сожалению, сказать не могу стенд клиент перенес на не зашифрованную машину
