### ISSUE TITLE
Как отличить документ в одном пакете.

### ISSUE THREAD

**Issue by darujo** [diadoc/diadocsdk-1c-docs#477]
Добрый день.
Подскажите, как отличить документы присланные в одном пакете от измененных документов.
Сейчас определяем измененный УПД по PackageId но видимо это не правильно.

**Comment by kulakovskaya** [comment]
Добрый день! Подскажите, пожалуйста, что вкладывается в понятие "измененный документ"?

**Comment by darujo** [comment]
ИУПД

**Comment by volodkindv** [comment]
Пока не ясно, что именно вам требуется.
Опишите, пожалуйста, сценарий в виде:
"Я отправляю документ ___. Потом отправляю документ(ы) ___, связывая их с ___. Теперь на стороне отправителя/получателя мне надо найти документ, который ___".

**Comment by darujo** [comment]
В ящике отправителя добавляем несколько файлов с УПД в отправку. В ящике получателя получаем эти документы у них у все проставлен одинаковый PackageId и не пустой. Как понять что эти документы не связаны друг с другом, а просто набор документов?

**Comment by volodkindv** [comment]
Все еще не ясно, почему эти документы не связаны друг с другом, если их отправляли вместе с УПД?

**Comment by volodkindv** [comment]
Если их отправляли в одно и то же время (то есть одним PackageSendTask, или "одним сообщением"), то у документов будет совпадать половина DocumentId. Если в разное время, то DocumentId будут различаться полностью. Возможно, вы об это спрашиваете.

**Comment by darujo** [comment]
Это разные документы УПД на разные товары. Потом присылают ИУКД на один из этих документов как можно понять на какой из эти документов пришел  ИУКД у них у всех же один PackageId?

**Comment by volodkindv** [comment]
1. Проверить InitialDocumentIds / SubordinateDocumentIds в ИУКД.
2. Если их нет, то смотреть на OriginalInvoices в контенте ИУКД. И определять исходный УПД по номеру/дате.
