### ISSUE TITLE
Отсутствует доступ к ящику организации

### ISSUE THREAD

**Issue by mishgan75** [diadoc/diadocsdk-1c-docs#478]
Здравствуйте при попытке отправить документ вышла ошибка
Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (SendTask.Send): Отсутствует доступ к ящику организации

**Comment by IrinaShmonina** [comment]
Здравствуйте,
по данному вопросу лучше обратиться в тех.поддержку - https://www.diadoc.ru/support

**Comment by mishgan75** [comment]
да но когда отправлю Торг 12 такой ошибки не возникает

**Comment by kulakovskaya** [comment]
Здравствуйте! В методе SendTask.Send присутствует логика по проверке на доступ в ящик. Но нет проверки на то, какой тип документа отправляется - ошибка либо будет, либо не будет на всех типах документов.

Рекомендуем перейти на метод PackageSendTask2 и DataTask, если нужно что-то сохранять в хранилище - http://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html?highlight=PackageSendTask2
