### ISSUE TITLE
Ошибка подписания COM компонента v5.30.0.580 x86 для произвольных систем

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#479]
Ошибка подписания COM компонента v5.30.0.580 x86 для произвольных систем

```
(ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid 
data UserContractData:
Line: 5, Position: 310, /AcceptanceCertificate552BuyerTitle[1]/Signers[1]/SignerDetails[1]/@SignerStatus: The 
'SignerStatus' attribute is invalid - The value '5' is invalid according to its datatype 'Integer' - The Enumeration constraint 
failed.
/AcceptanceCertificate552BuyerTitle/Signers/SignerReference: @Inn is required
/AcceptanceCertificate552BuyerTitle/Signers/SignerReference: SignerDetails not found for boxId=xxxxxx-xxxxxx-xxxx-xxxxx-xxxxxxxxxxx, thumbprint=XXXXXXXXXXXXXXXXXX
documentTitleType=7
```
тип подписываемого документа: Document.type = "XmlAcceptanceCertificate"
1)ContentAccepCert552BuyerT = ContentItem.Content.AcceptanceCertificate552BuyerTitle;
Signer_ = ContentAccepCert552BuyerT.Signers.AddItems();
поле Signer_.SignerDetails.SignerStatus является строкой, а судя из описания ошибки должно быть числом.
2)Signer_.SignerReference.Inn поле отсутствует, соответственно нет возможности передать через COM

**Comment by kulakovskaya** [comment]
Добрый день!
1. Согласно приказу 552 в документах данного формата статус Подписанта не может принимать значение "5" - https://normativ.kontur.ru/document?moduleId=1&documentId=339635&rangeId=357462.
2. Не указаны полномочия подписанта:
* Для получения настроек подписанта использовать GetExtendedSignerDetails2.
* Для отправки настроек подписанта использовать объект SetExtendedSignerDetailsTask.

**Comment by jakeqwert** [comment]
> * GetExtendedSignerDetails
1. Для подписанта со стороны покупателя не один из статусов не подходит, т.к. перечень для продавца/поставщика. И ссылка на старый приказ, сейчас Приказ от 19.12.2018 № ММВ-7-15/820
2.Полномочия подписанта указаны ExtendedSignerDetails.SignerPowers = 3; 
// 3 - лицо, ответственное за оформление свершившегося события
ExtendedSignerDetails.SignerPowersBase = "Доверенность №ххххх от 01.01.2020";

**Comment by kulakovskaya** [comment]
Добрый день. Приложите, пожалуйста, ссылку на документ, который нужно подписать.

**Comment by jakeqwert** [comment]
> Добрый день. Приложите, пожалуйста, ссылку на документ, который нужно подписать.

https://diadoc.kontur.ru/3bfb9c4d-0203-4610-83c8-e15ba95fd8d2/Document/Show?letterId=6fe30ef4-464f-4367-b8b7-7313377d57f3&documentId=61140cef-5660-4d3a-8961-be5dd004a89d
Пришлось для срочности его через web подписать, но через COM компонента v5.30.0.580 x86 для произвольных систем он не подписывался, хотя при подписании на сайте заполнял руками поля такими же значениями как и поля COM  объекта

**Comment by kulakovskaya** [comment]
Данный документ в формате 552 приказа.
Полномочия подписанта указаны верно:
ExtendedSignerDetails.SignerPowers = 3;
// 3 - лицо, ответственное за оформление свершившегося события
ExtendedSignerDetails.SignerPowersBase = "Доверенность №ххххх от 01.01.2020";

Рекомендуем в следующий раз заполнить только SignerReference и НЕ заполнять SignerDetails - тогда всё подтянется из Диадока.

**Comment by jakeqwert** [comment]
> Рекомендуем в следующий раз заполнить только SignerReference и НЕ заполнять SignerDetails - тогда всё подтянется из Диадока.
SignerDetails нужен, чтобы указать доверенность, должность, ФИО и пр. т. к. удобнее эти данные передавать из местной системы и номер доверенность зависит от категории документа, который можно проверить/взять из местной информационной системы.

**Comment by GilimkhanovDenis** [comment]
В таком случае указывайте только SignerDetails и не указывайте SignerReference. Эти два поля взаимозаменяемые и не могут быть указаны одновременно

**Comment by jakeqwert** [comment]
> не указывайте SignerReference

тогда ругается что не заполнено SignerReference.BoxId, SignerReference.CertificateThumbprint, SignerReference.Inn поля которого там нет

**Comment by GilimkhanovDenis** [comment]
> тогда ругается что не заполнено SignerReference.BoxId, SignerReference.CertificateThumbprint, SignerReference.Inn поля которого там нет

Можете показать как этом случае заполнена коллекция подписантов, дословный текст ошибки и TypeNameId+ Function+version этого документа?

**Comment by jakeqwert** [comment]
> > тогда ругается что не заполнено SignerReference.BoxId, SignerReference.CertificateThumbprint, SignerReference.Inn поля которого там нет
> 
> Можете показать как в этом случае заполнена коллекция подписантов, дословный текст ошибки и ссылку на тот документ, на котором воспроизводится (предыдущая ссылка ведёт на уже подписанный документ)?

(ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 4, Position: 310, /AcceptanceCertificate552BuyerTitle[1]/Signers[1]/SignerDetails[1]/@SignerStatus: The 
'SignerStatus' attribute is invalid - The value '5' is invalid according to its datatype 'Integer' - The Enumeration constraint 
failed.
![img-2020-07-08-15-27-43](https://user-images.githubusercontent.com/20082460/86913396-ab501f80-c12f-11ea-823f-637684aa7585.png)

В компоненте тип поля не 'Integer', а строка.

**Comment by GilimkhanovDenis** [comment]
Как уже писалось [выше](https://github.com/diadoc/diadocsdk-1c-docs/issues/479#issuecomment-644107274), статус 5 не может быть использован для этого титула. Информация есть в UserDataXSD
![image](https://user-images.githubusercontent.com/34439383/86915867-23244700-c13c-11ea-84ce-0252308afa81.png)


Так же отмечу, что каждый элемент SignerReference и каждый элемент SignerDetails будут превращены в отдельного подписанта, если данные заполнены. Это также следует из UserDataXSD
![image](https://user-images.githubusercontent.com/34439383/86916138-8dd58280-c13c-11ea-84f1-c56a05623453.png)

**Comment by GilimkhanovDenis** [comment]
Про типизацию полей обсуждалось [здесь](https://github.com/diadoc/diadocsdk-1c-docs/issues/472#issuecomment-638137314). В целом ответ такой, что все данные в Динамическом контенте имеют строковый тип; числа записываются строковым представлением (см. https://www.w3schools.com/xml/schema_dtypes_numeric.asp)
