### ISSUE TITLE
Интеграция с 1С. Шаг номер 2

### ISSUE THREAD

**Issue by ShibaevAnton** [diadoc/diadocsdk-1c-docs#48]
Добрый день. Подскажите пожалуйста как провести тестирование. В настоящее время есть ключ разработчика и 2 тестовые базы в которых пробовали обмен документами с помощью вашей обработки. Сейчас читаю инструкцию к API, http://1c-docs.diadoc.ru/ru/latest/How-auth.html - Как авторизоваться в системе Диадок. Возник вопрос могу ли я для тестирования использовать подключение CreateConnectionByLogin вместо CreateConnectionByCertificate, и подключиться к тестовым базам? Или ключ разработчика привязан к конкретной организации и не даст возможности это сделать?

**Comment by jakeqwert** [comment]
Можете. Не привязан к организации.
ДиадокАпи = Новый ComОбъект("Diadoc.DiadocClient");	
//Задаем параметры подлючения к серверу
КлючРазработчика = "XXXXXXX-XXXXXXXXXXXXX";
ДиадокАпи.ApiClientId = КлючРазработчика;
ДиадокАпи.ServerUrl   = "https://diadoc-api.kontur.ru:443";

//соединение и авторизоваться

//Получение списка сертификатов
//Certificates = ДиадокАПИ.GetPersonalCertificates();
//создание соединения, здесь в явном виде указан отпечаток сертификата
//в рабочем варианте его надо получить из коллекции Certificates
//Например так PersonalCertificate = Certificates.GetItem(0).Thumbprint;
//ДиадокСоединение = ДиадокАПИ.CreateConnectionByCertificate("3E859FA8FB718FB691A793AE1206C5EE85574AFD");

//по паролю
//Иванов М.
Login = "XXXXXXX@mail.ru";
Password = "XXXXXXX";	
ДиадокСоединение = ДиадокАПИ.CreateConnectionByLogin(Login,Password);

//Проверить подключение
//DiadocInvoiceAPI.TestConnection()
	
//контекст работы с организацией
//OrgId: XXXXX-48db-4162-90d1-jkhkjhghg
//BoxId: XXXXX-0203-4610-83c8-jhfgghgg
OrganizationId = "3bfb9c4d02jhgjhg1083c8e15ba95fd8d2@diadoc.ru";
ДиадокКонтекстОрганизации = ДиадокСоединение.GetOrganizationById(OrganizationId);
//Получив массив всех объектов Organization всех доступных ящиков. Пример:	
//OrganizationList = ДиадокСоединение.GetOrganizationList();
//  Ц = 0;
//  Пока Ц < OrganizationList.Count() Цикл
//    Organization = OrganizationList.GetItem(ц);
//    Сообщить(Organization.Name);
//  Ц = Ц + 1;
//  КонецЦикла;

**Comment by denver069** [comment]
@jakeqwert спасибо за ответ с примером!
