### ISSUE TITLE
Отправка счет-фактуры через COM-компоненту

### ISSUE THREAD

**Issue by BaevaSvetlana** [diadoc/diadocsdk-1c-docs#480]
Добрый день.
Отправляю счет-фактуру через COM Diadoc API - 5_30_0_580_x64
Задание на создание формилизованного документа создаю методом
SendTask = Organization.CreateSendTask("UtdInvoice");
Документ отправляется без ошибок, но в личном кабинете для документа указано предупреждение "Документ в устаревшем формате ". 
Также пробовала создание документа через метод CreateSendTask("InvoiceContent")  - ситуация аналогичная. 
Каким образом можно отправить счет-фактура в новом формате через 
COM-компоненту?

**Comment by GilimkhanovDenis** [comment]
Добрый день.

Объект [SendTask](http://1c-docs.diadoc.ru/ru/latest/ComObjects/SendTask.html) устаревший и больше не развивается. В том числе, он не поддерживает отправку документов в формате 820 приказа. Вместо [SendTask](http://1c-docs.diadoc.ru/ru/latest/ComObjects/SendTask.html)'а используйте [PackageSendTask2](http://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html)
Добавить счёт-фактуру можно вызовом 
[PackageSendTask2.AddDocument](http://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocument)("UniversalTransferDocument", "СЧФ", "utd820_05_01_01_hyphen"); (печатная форма УПД)
или 
[PackageSendTask2.AddDocument](http://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocument)("Invoice", "default", "utd820_05_01_01_hyphen"); (печатная форма счёта-фактуры)

Общая информация об доступна [здесь](http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html)
