### ISSUE TITLE
Можно ли создать черновик используя внешнюю компоненту 1С?

### ISSUE THREAD

**Issue by VDK1C** [diadoc/diadocsdk-1c-docs#482]
Добрый день.
Создаём и отправляем УПД используя внешнюю компоненту Diadoc_5_29_14_577.dll, документ сразу подписывается и уходит в Диадок.
Существует ли способ отправить неподписанный документ, как черновик, что бы в дальнейшем его можно было подписать через веб-интерфейс?

**Comment by volodkindv** [comment]
Добрый день. 
Используйте флаг IsDraft или DelaySend в [PackageSendTask2](http://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html). Лучше DelaySend - это не черновик, а "отложенная отправка".

**Comment by VDK1C** [comment]
Спасибо.
