### ISSUE TITLE
Как подписывать документы кроме UniversalTransferDocument

### ISSUE THREAD

**Issue by mpei0504** [diadoc/diadocsdk-1c-docs#483]
Добрый день.
Может что-то упустил, но при создании контента для подписи документа получаю возможность для подписания только для документов типа UniversalTransferDocument(УПД).Для всех остальных типов документов контент возвращается в виде строки DocumentSignature

Получаю контент так:
ReplySendTask = Document.CreateReplySendTask2("AcceptDocument");
UTD = ReplySendTask.ContentItems.getItem(0).Content;

Подскажите, как подписывать документы других типов(не УПД)?
Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день.
Про какие конкретно документы речь?

Не все документы являются двухтитульными, как UniversalTransferDocument, - некоторым достаточно только подписи и дополнительно заполнять ничего не нужно (см. [DocumentTypeDescription](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentTypeDescription.html).[Functions](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentFunction.html).[Versions](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentVersion.html).[Workflows](http://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentWorkflow.html) в ответе метода [Organization.GetDocumentTypes](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetDocumentTypes))

**Comment by mpei0504** [comment]
Речь идет о неформализованных документах(счет, акт-сверки, акт), они не имеют контента.

Для подписания таких документов нужно заполнять metadata?

**Comment by mpei0504** [comment]
Есть ли примеры согласования однотитульных документов?

**Comment by GilimkhanovDenis** [comment]
У неформализованных документов (TypeName = "Nonformalized", function = "default", version = "v1") нет второго титула, никаких данных для подпиания заполнять не нужно. Подписание произойдёт тем сертификатом, по которому авторизовались

**Comment by GilimkhanovDenis** [comment]
Для согласования есть метод [Document.Approve](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html#Document.Approve)

**Comment by mpei0504** [comment]
При попытке метод Document.Approve возникает ошибка:

Произошла исключительная ситуация (DocumentBase.Approve): ##100[Ошибка сервера Диадок]code:409, HTTP error: Текущее состояние документа не позволяет его согласовать
параметры документа:

**Comment by mpei0504** [comment]
NonformalizedAcceptanceCertificate
InboundWaitingForRecipientSignature
workflowid  = 1

**Comment by mpei0504** [comment]
Извините, самое главное не написал

TypeName  = AcceptanceCertificate

**Comment by mpei0504** [comment]
Вопрос закрыт.Денис спасибо.
