### ISSUE TITLE
Регистрация компоненты на сервере

### ISSUE THREAD

**Issue by biv2020** [diadoc/diadocsdk-1c-docs#485]
Добрый день!

При попытке создать объект получаю ошибку создания объекта. 
Что сделать?

До этого на сервере не было библиотеки, т.е запись файла, его регистрацию алгоритм выполнил успешно.
	флРезультатПодключенияВК = ПодключитьВнешнююКомпоненту(текProgID);

Собрал вот такой протокол, компоненту 32 вер для полноты под адм правами зарегистрировал вручную.

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = D:\temp\AddInDiadocAPI_5_29_13_573_x86_64.dll
	AssemblyDirectory = D:\temp\
	Application Config File = 
-----------------
INFO: Parsing Manifest File D:\temp\AddInDiadocAPI_5_29_13_573_x86_64.dll.
	INFO: Manifest Definition Identity is (null).
	INFO: Reference: AddInDiadocAPI,type="win32",version="1.0.0.0"
INFO: Resolving reference AddInDiadocAPI,type="win32",version="1.0.0.0".
	INFO: Resolving reference for ProcessorArchitecture AddInDiadocAPI,type="win32",version="1.0.0.0".
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at D:\temp\AddInDiadocAPI.DLL.
				INFO: Attempt to probe manifest at D:\temp\AddInDiadocAPI.MANIFEST.
				INFO: Attempt to probe manifest at D:\temp\AddInDiadocAPI\AddInDiadocAPI.DLL.
				INFO: Attempt to probe manifest at D:\temp\AddInDiadocAPI\AddInDiadocAPI.MANIFEST.
				INFO: Did not find manifest for culture Neutral.
			INFO: End assembly probing.
	ERROR: Cannot resolve reference AddInDiadocAPI,type="win32",version="1.0.0.0".
ERROR: Activation Context generation failed.
End Activation Context Generation.

**Comment by GilimkhanovDenis** [comment]
Добрый день
Если зарегистрировали x86 компоненту, то прежде чем подключать x64 версию нужно разрегистрировать x86
Сейчас похоже, что осталась зарегистрирована x86, а 1С пытается подключить её как x64
