### ISSUE TITLE
500 при попытке отправить СЧФДОП

### ISSUE THREAD

**Issue by SIMBaIrk** [diadoc/diadocsdk-1c-docs#486]
Здравствуйте.
Версия com библиотеки 5.30.1.584
Авторизация по сертификату (hash взял по которому авторизуемся в diadoc).
API_key test-*
 
`SendTask = DiadocOrganization.CreatePackageSendTask2();
SendTask.CounterAgentId = Client.Id;
SendTask.isDraft = 1; // пробовал комментировать, не влияет
Second_DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01", ПолноеИмяФайла); 
 
РезультатОтправки = SendTask.Send(); // прилетает 500, см скрин`

PackageSendTask2.Send: ##100[Ошибка сервера Диадок]code:500, HTTP error: The server encountered an internal error or misconfiguration and was unable to complete your request

![500](https://user-images.githubusercontent.com/1243523/87131218-aec9df00-c2c6-11ea-8441-b6d0a753e78e.png)
[ЭДОНакл__2020710_3370353.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/4901816/__2020710_3370353.zip)

**Comment by IrinaShmonina** [comment]
@SIMBaIrk , здравствуйте
У вас есть ошибки в xml. Например, отсутствует поле ИдФайл в теге Файл.
Корректность составленной xml можно проверить на сайте Диадока - https://www.diadoc.ru/docs/forms/validation-xml

**Comment by SIMBaIrk** [comment]
Спасибо, так и подумал что-то с файлом.

**Comment by SIMBaIrk** [comment]
Дозаполнил необходимыми полями ушло.
