### ISSUE TITLE
Добавление колонки в список полученных.

### ISSUE THREAD

**Issue by varyag42** [diadoc/diadocsdk-1c-docs#487]
Добрый день. Разбираюсь и дорабатываю модуль диадок для 1С.
В документации подключаемого модуля нашел про добавление колонок в список документов: 
[https://diadoc1cpro-docs.readthedocs.io/ru/latest/proc/pm/Dorabotka_Spiska_Dokumentov.html#](url)

По факту указанных в документации функций нет в подключаемом модуле. Подскажите как добавить колонки правильно? может я не правильно понял документацию и не там ищу?

**Comment by Chebotareva-Vika** [comment]
Добрый день!
Можете приложить ПМ?
Какая у вас версия модуля диадок?

**Comment by varyag42** [comment]
Версия модуля: 5.37.17.375
Подключаемый модуль: https://yadi.sk/d/jCHa9kAj_BPZJQ

**Comment by Chebotareva-Vika** [comment]
Данная настройка предназначена для модуля Про. В модуле УФ (как у вас) возможности добавления колонок нет.

Если требуются доп.колонки, то нужно обратиться во Внедрение модуля Диадок. Коллеги проконсультируют по модулю Про.
