### ISSUE TITLE
Версии документов.

### ISSUE THREAD

**Issue by darujo** [diadoc/diadocsdk-1c-docs#488]
Подскажите есть ли где-нибудь описание, что вот такими версиями рекомендовано пользоваться, а вот такими не рекомендовано? Интересуют версии документов UniversalTransferDocument.
Сейчас от поставщиков приходят в основном версии документов:
Version VT_BSTR utd820_05_01_01_hyphen
но один поставщик присылает документ с версией:
Version VT_BSTR utd820_05_01_01
И не понятно имеет смысл поддерживать версию   utd820_05_01_01  или может быть надо поддеживать какие-то другие версии?

**Comment by IrinaShmonina** [comment]
@darujo, здравствуйте
utd820_05_01_01_hyphen и utd820_05_01_01 - это 2 версии 820 формата. На данный момент 820 формат является актуальным.

Про отличие этих версий можно прочитать на сайте Диадока - https://www.diadoc.ru/blog/7883
