### ISSUE TITLE
Обязательность поля BaseDocumentDate объекта UniversalTransferDocumentWithHyphens...TransferBase

### ISSUE THREAD

**Issue by CatAnd0** [diadoc/diadocsdk-1c-docs#489]
Версия компоненты: COM x86 5.30.2.593
Заполняю основание УПД через динамический контент UniversalTransferDocumentWithHyphens.
В описании схемы поле TransferInfo.TransferBases.TransferBase.BaseDocumentDate (дата документа основания) указано как необязательное. Так же необязательность этого поля отмечена в описании УПД здесь https://www.diadoc.ru/docs/forms/upd/structure/8 

Соответственно, дату не указываю. Но при отправке пакета получаю ошибку: `Метод 'Send' в COM-объекте класса 'IPackageSendTask2' возвратил код ошибки 0x800405E8 (<unknown>), который означает: ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData: /UniversalTransferDocumentWithHyphens/TransferInfo/TransferBases/TransferBase: @BaseDocumentDate is required.`

Проверьте, пожалуйста.

**Comment by IrinaShmonina** [comment]
@CatAnd0 , здравствуйте
Дата документа основания является обязательным полем, если поле наименование документа основания отличается от "Без документа-основания".
Подробнее про это можно посмотреть в [приказе](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=375673)

**Comment by CatAnd0** [comment]
Не доглядел, спасибо за быстрый ответ.
