### ISSUE TITLE
Можно не закрывать сообщения без согласия? 

### ISSUE THREAD

**Issue by ShibaevAnton** [diadoc/diadocsdk-1c-docs#49]
Добрый день. 

Ранее было написано обращение, которое мало того, что было закрыто по непонятной кому воле, так еще отработано некорректно!

Цитата из переписки: "Идентификатор 1С не хранится в базе Диадока, поэтому хранить нужно наоборот идентификатор Диадока в базе 1С." - ответ вашего специалиста. 

http://1c-docs.diadoc.ru/ru/latest/Document.html - свойство объекта Документа - OneSDocumentId (строка, чтение) - идентификатор документа в 1С. Как трактовать ответ вашего специалиста? Как ответ не компетентного сотрудника? Или ошибки в документации?

И просьба не закрывайте обращение. Потому что у меня возникли вопросы по ответу от вашего специалиста, а он почему то посчитал что можно закрыть обращение... 

А как я, уже сейчас понимаю, в закрытых обращениях писать бесполезно, никто по ним не отрабатывает...

**Comment by volodkindv** [comment]
Добрый день.
Приложите ссылку на исходный тикет.

**Comment by denver069** [comment]
Ответа от клиента нет, тикет закрываю.
