### ISSUE TITLE
Статус контрагента

### ISSUE THREAD

**Issue by asdjjklm** [diadoc/diadocsdk-1c-docs#490]
Здравствуйте, мне нужно получить список всех контрагентов, с которыми у меня установлены партнерские отношения из Диадок в 1С. Для этого я использую Organization.GetCounteragentListByStatus(IsMyCounteragent) в модуле Диадок. Но при обновлении Диадок, мой код будет затерт и каждый раз держать мысль в голове, что при обновлении Диадок нужно заново дописывать свой код не очень хочется. Скажите пожалуйста, можно ли как-то дополнить типовую обработку Диадок своим расширением?  
Существует подключаемый модуль, в который можно вносить изменения и при обновлении диадок он не затрется, но в нем не работает данный метод "GetCounteragentListByStatus". Можно ли как-то получить данные с сервера диадок в подключаемом модуле?

**Comment by IrinaShmonina** [comment]
@asdjjklm, здравствуйте
подскажите, пожалуйста, полную версию модуля

**Comment by asdjjklm** [comment]
5.33.09.168

**Comment by asdjjklm** [comment]
Спасибо, проблема решена. В подключаемом модуле при инициализации.

DiadocConnectionDefault = ОбработкаДиадок.Модуль_РаботаССерверомДиадок.DiadocConnectionDefault;
Organization = DiadocConnectionDefault.GetOrganizationList();
Organization = Organization.GetItem(0); //Выбираем нужную организацию
СписокКонтрагентов = Organization.GetCounteragentListByStatus("IsMyCounteragent");

**Comment by AleksandrSergeevich77** [comment]
Здравствуйте. 
Подскажите, как получить список всех контрагентов, с которыми у меня установлены партнерские отношения в подключаемом модуле diadoc standart (версия 5.49.13.958) ?
