### ISSUE TITLE
Доработка ПМ

### ISSUE THREAD

**Issue by DevSPT** [diadoc/diadocsdk-1c-docs#491]
Добрый день. Дорабатываю модуль диадок для 1С (Diadoc1C_UF_5_42_01).
В документации подключаемого модуля нашел:

"
Код содержит в себе некоторые процедуры и функции. 

Также в коде есть подсказки в виде комментариев и пример использования функции, которая “обрезает” нули в номере счета-фактуры. Находится она в функции «ОбработатьСобытиеПослеЗаполненияКонтента».
"

По факту указанной в документации функции нет в подключаемом модуле. 
Где искать, куда копать?

**Comment by IrinaShmonina** [comment]
Добрый день,
Можете подсказать, про какую документацию речь?

Модуль по умолчанию отправляет электронные документы с такими же номерами, как и в типовых печатных формах. Как правило из номера сф удаляются префиксы и лидирующие нули.

**Comment by DevSPT** [comment]
https://wiki.diadoc.ru/pages/viewpage.action?pageId=7669858
"
 Находится она в функции «ОбработатьСобытиеПослеЗаполненияКонтента».
"
По факту указанной в документации функции нет в подключаемом модуле.
там пример содержащий как подключить и настроить вызов функций из ПМ.
А вообще нам надо  настроить передачу поля "Комментарий" документа УПД из 1с83 УТ11 в подвале документа через Контур.Диадок.

**Comment by IrinaShmonina** [comment]
@DevSPT я правильно вас поняла, что вы не можете найти обработку события «ОбработатьСобытиеПослеЗаполненияКонтента»?

**Comment by DevSPT** [comment]
Так точно. У нас версия модуля диадок - стандарт, как мне сказали в чате техподдержки.

**Comment by IrinaShmonina** [comment]
В модуле зайдите в "Настройки"-"Подключаемый модуль"-"Сохранить шаблон подключаемого модуля на диск".
Также нужно будет потом подключить ПМ - https://wiki.diadoc.ru/pages/viewpage.action?pageId=7669847

Откройте сохраненный документ в конфигураторе.
Там можно найти пример обработки функции "ОбработатьСобытиеПослеЗаполненияКонтента".
Также нужно будет включить обработку события в "ОбработкаСобытияПодключаемогоМодуля". Для этого достаточно раскомментировать строку с нужным событием

**Comment by DevSPT** [comment]
Спасибо, попробую и отпишусь о результате, но, видимо, уже в пнд. 27.07.20.

**Comment by YuriiGurkunov** [comment]
Здравствуйте, по ссылке на ваш wiki https://wiki.diadoc.ru/plugins/servlet/mobile?contentId=7669858#content/view/7669858 информация устарела. модуль ПМ сейчас выглядит совсем не так и ТипыКонтента свосем другие. Мне надо изменить формирование СчетФактуры как мне идентифицировать это событие в "ОбработатьСобытиеПослеЗаполненияКонтента"

**Comment by volodkindv** [comment]
> Здравствуйте, по ссылке на ваш wiki https://wiki.diadoc.ru/plugins/servlet/mobile?contentId=7669858#content/view/7669858 информация устарела. модуль ПМ сейчас выглядит совсем не так и ТипыКонтента свосем другие. Мне надо изменить формирование СчетФактуры как мне идентифицировать это событие в "ОбработатьСобытиеПослеЗаполненияКонтента"

Здравствуйте. Новый вопрос лучше задавать в отдельном тикете. Ссылка, которую вы приложили, действительно устарела.
