### ISSUE TITLE
Ошибка при отправке УПД

### ISSUE THREAD

**Issue by MGPr1C** [diadoc/diadocsdk-1c-docs#492]
Модуль интеграции с 1С 7.7.
При отправке УПД клиенту возникает ошибка: "PackageSendTask2.Send: ##100[Ошибка сервера Диадок]code:400, HTTP
error: Invalid data UserContractData:
' ', hexadecimal value 0x1D, is an invalid character. Line 14, position 42."

При попытке сохранить сформированный УПД в XML файл перед отправкой, чтобы посмотреть, что содержится в "Line 14, position 42." выдается та же ошибка.

Другие документы отправляются из того же модуля корректно. 

Прошу помочь с решением проблемы.

**Comment by volodkindv** [comment]
Предоставленной информации слишком мало.
Скорей всего, какое-то из текстовых полей в контенте содержит спецсимвол 0x1D. Попробуйте его найти.

**Comment by MGPr1C** [comment]
Спасибо за оперативный ответ!

Можно ли каким-то образом получить файл, передаваемый через
компоненту, чтобы понять, какая именно информация содержится в "Line
14, position 42" ? Визуальный анализ содержимого документа был
произведен в первую очередь, он результатов не дал.

"Предоставленной информации слишком мало." - я готов предоставить
любую необходимую информацию для детального анализа, укажите, какую
именно?

22.07.2020, Данила Володькин<notifications@github.com> написал(а):

**Comment by volodkindv** [comment]
> Спасибо за оперативный ответ! Можно ли каким-то образом получить файл, передаваемый через компоненту, чтобы понять, какая именно информация содержится в "Line 14, position 42" ? Визуальный анализ содержимого документа был произведен в первую очередь, он результатов не дал. "Предоставленной информации слишком мало." - я готов предоставить любую необходимую информацию для детального анализа, укажите, какую именно? 22.07.2020, Данила Володькин<notifications@github.com> написал(а):
> […](#)
> Предоставленной информации слишком мало. Скорей всего, какое-то из текстовых полей в контенте содержит спецсимвол 0x1D. Попробуйте его найти. -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#492 (comment)](https://github.com/diadoc/diadocsdk-1c-docs/issues/492#issuecomment-662305024)

Получить файл, передаваемый через компоненту, сейчас невозможно. Мы планируем добавить такую возможность в ближайшем релизе. Следите за историей изменений.

**Comment by MGPr1C** [comment]
То есть проблема с технической точки зрения со стороны api Диадок
решения не имеет, я вас верно понимаю?

Со своей стороны могу сказать, что ошибка нами найдена. В сканируемых
марках сигарет, которые в составе УПД передаются в Диадок, в некоторых
сканерах содержащийся коде маркировки спецсимвол с кодом 0x1D не
пропускается, это и было причиной ошибки. Как только добавили
программную замену этого символа в составе передаваемых в УПД марок -
ошибка исчезла.

22.07.2020, Данила Володькин<notifications@github.com> написал(а):

**Comment by volodkindv** [comment]
> То есть проблема с технической точки зрения со стороны api Диадок
решения не имеет, я вас верно понимаю?

Верно, сейчас технического решения нет. Оно будет в следующем релизе компоненты: в объекте CustomDocumentToSend появится метод SaveUserData().

**Comment by GilimkhanovDenis** [comment]
Метод сохранения упрощенного контента добавлен в [5.31.0](http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_31_0.html)
