### ISSUE TITLE
Изменение поля Товар при передаче в ДиаДок

### ISSUE THREAD

**Issue by bond1cka** [diadoc/diadocsdk-1c-docs#493]
Добрый день, подскажите пожалуйста как нам изменить передачу информации о номенклатуре в диадок. 
У нас сейчас в актах в табличной части документа отправляется просто наименование товара, а нам нужно чтобы было наименование и дата документа.
В подключаемом модуле я написал так:

```
Процедура ОбработатьСобытиеПослеЗаполненияКонтента(Параметры)
	
	ТипыКонтента = ТипыКонтента();
	
	СсылкаНаДокумент			 = Параметры.ДокументСсылка;
	Протоконтент				 = Параметры.Content;
	ТипКонтента					 = Параметры.ТипКонтента;
	ПараметрыФормированияФайла	 = Параметры.ПараметрыФормированияФайла;
	
	Если ТипКонтента = ТипыКонтента.Utd820SellerContent Тогда
		
		//ПримерОбработкиУПД820(СсылкаНаДокумент, Протоконтент);
		
	ИначеЕсли ТипКонтента = ТипыКонтента.UtdSellerContent Тогда
		
		//ПримерОбработкиУПД155(СсылкаНаДокумент, Протоконтент);
		
	ИначеЕсли ТипКонтента = ТипыКонтента.Torg12SellerContent Тогда
		
		//ПримерОбработкиНакладной172(СсылкаНаДокумент, Протоконтент);
		
	ИначеЕсли ТипКонтента = ТипыКонтента.AcceptanceCertificateSellerContent Тогда
		
		//ПримерОбработкиАкта172(СсылкаНаДокумент, Протоконтент);
		
		Данные = Параметры.Данные;
		
		сч = 0;
		Для Каждого Стр Из Протоконтент.Items Цикл
			СтрокаДанных = Данные.ТаблицаТоваров[сч];
			Стр.Product = СтрокаДанных.НоменклатураСсылка.Наименование + ", за период с " + Формат(НачалоМесяца(СсылкаНаДокумент.Дата), "ДФ=dd.MM.yyyy") + "г. по " + Формат(КонецМесяца(СсылкаНаДокумент.Дата), "ДФ=dd.MM.yyyy") + "г.";
			сч = сч +1;	
		КонецЦикла;
		
		
	КонецЕсли;
	
КонецПроцедуры // ОбработатьСобытиеПослеЗаполненияКонтента()
```

эффекта 0. 

Подскажите плз что я делаю не так?

**Comment by Chebotareva-Vika** [comment]
Добрый день!
Убедитесь, что:
1. Вызов процедуры ОбработатьСобытиеПослеЗаполненияКонтента раскомментирован
![image](https://user-images.githubusercontent.com/68367093/88253608-f63f6a80-cccb-11ea-829a-2f686e2eb104.png)

2. Акт отправляется в формате приказа 172@, т.к. приведенный код обрабатывает именно этот формат (см. условие "ИначеЕсли ТипКонтента = ТипыКонтента.AcceptanceCertificateSellerContent Тогда"))

**Comment by bond1cka** [comment]
Спасибо за информацию. Есть тут еще одна проблема. Когда я обращаюсь к Протоконтент.Items система выдает ошибку. Говорит что нет в структуре Items. Я этот пример брал с официальной документации
https://wiki.diadoc.ru/pages/viewpage.action?pageId=7669858
Я так понимаю что это устарело.
Где можно посмотреть как сейчас нужно обращаться к табличной части Протоконтента?

**Comment by bond1cka** [comment]
Если обратиться к документации
http://1c-docs.diadoc.ru/ru/latest/ComObjects/InvoiceItem.html
там предлагают использовать InvoiceItem
Его тоже нет в протоконтенте.

**Comment by volodkindv** [comment]
> Где можно посмотреть как сейчас нужно обращаться к табличной части Протоконтента?
Это зависит от того, какой документ вы отправляете, в каком формате и в какой версии модуля.

Если документ отправляется в формате УПД, то `КоллекцияСтрок = Протоконтент.Table.Items;`

Посмотрите шаблон ПМ, входящий в состав модуля. Там достаточно примеров. Имя переменной - коллекции строк легко понять, заглянув в отладчик в момент выполнения.

**Comment by bond1cka** [comment]
Спасибо.
