### ISSUE TITLE
Как изменить строки табличной части Счета на оплату?

### ISSUE THREAD

**Issue by bond1cka** [diadoc/diadocsdk-1c-docs#495]
Строки табличных частей (например Наименование номенклатуры) можно изменять в ПМ. Там есть УПД, акт и др. Но не нашел где там можно изменить табличную часть Счета на оплату.

**Comment by kulakovskaya** [comment]
Добрый день! Подскажите какой используете интеграционный модуль?

**Comment by bond1cka** [comment]
А какие бывают?

**Comment by kulakovskaya** [comment]
Тут описаны все интеграционные модули - https://www.diadoc.ru/integrations/1c.
Подскажите, пожалуйста, какую используете конфигурацию и версию модуля Диадок 1С.

**Comment by bond1cka** [comment]
Платформа 1С 8.3 (управляемое приложение) для Бухгалтерия предприятия, ред. 3.0

**Comment by Chebotareva-Vika** [comment]
Добрый день!
Событие ПМ "ПослеЗаполненияКонтента" используется только для формализованных типов документов. Счет на оплату не является формализованным типом. Поэтому там изменить нельзя. 
Можно попробовать следующие варианты: 
- использовать ВПФ;
- переопределить функцию печати счета в конфигурации (в БП 3.0 это функция ПечатьСчетаНаОплату общего модуля ПечатьТорговыхДокументов).

**Comment by bond1cka** [comment]
Понял. Спасибо.
