### ISSUE TITLE
Invoice.GetContent

### ISSUE THREAD

**Issue by Ant377** [diadoc/diadocsdk-1c-docs#496]
Добрый день.  Пытаюсь получить доступ к InvoiceItem.
Через список документов, нашёл счёт-фактуру Invoice. 
Но Invoice.GetContent - пустой.

**Comment by GilimkhanovDenis** [comment]
Добрый день
Такое поведение [метода](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Invoice.html?highlight=GetContent#Invoice.GetContent) означает, у Счёта-фактуры версия, которая не поддерживается этим методом. Используйте метод [Document.GetDynamicContent()](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html#Document.GetDynamicContent)

**Comment by Ant377** [comment]
спасибо.
