### ISSUE TITLE
CreateConnectionByCertificate(ОтпечатокСертификата) ошибка

### ISSUE THREAD

**Issue by MolostovDS** [diadoc/diadocsdk-1c-docs#497]
Возникла необходимость подписывать документы через фоновые задания. 
	Функция АвторизацияПоСертификату(ОтпечатокСертификата) Экспорт
	
	//создаем корневой элемент COM-объекта
	DiadocApi = Новый ComОбъект("Diadoc.DiadocClient");
	
	DiadocApi.ApiClientId = КлючРазработчика();
	DiadocApi.ServerURL   = "https://diadoc-api.kontur.ru:443";	
	
	DiadocConnection = DiadocApi.CreateConnectionByCertificate(ОтпечатокСертификата);
	
	Возврат  DiadocConnection;
	
КонецФункции

При попытке авторизоваться через сертификат на сервере выходит ошибка:
##300[Ошибка CryptoPro]Ошибка при расшифровке данных [2148073494:Набор ключей не существует]

Ключ установлен на локальном компьютере.
Подскажите пожалуйста где может быть ошибка.
Заранее спасибо!

**Comment by volodkindv** [comment]
Фоновые задания выполняются на сервере. Ключи у вас установлены на клиенте. Если это разные машины, то CryptoPro совершенно справедливо говорит: на сервере ключей нет.
