### ISSUE TITLE
Регистрация 32x компоненты на Win 7x64.

### ISSUE THREAD

**Issue by Ant377** [diadoc/diadocsdk-1c-docs#498]
Добрый день.

Как правильно регистрировать 32x dll в 64х разрядной Windows?

У пользователей с Windows 7 x32 проблем с установкой нет, а в Win64 пишет "Не удалось загрузить модуль Diadoc...dll"
regsvr32 запускался через bat "от имени администратора".

**Comment by kulakovskaya** [comment]
Добрый день! Рекомендуем Вам обратиться в службу технической поддержки https://www.diadoc.ru/support для регистрации компоненты.

**Comment by darujo** [comment]
Если вы на win 64 используете 32 разрядное приложение то вам необходимо использовать 32 разрядную библиотеку, если у вас приложение 64 разрядное то надо использовать 64 разрядную библиотеку.

**Comment by Ant377** [comment]
Проблема в регистрации. Оказалось DLL хоть и 32х разрядную, надо класть в SysWOW64, а не в  System32.
