### ISSUE TITLE
Метод getStatus() - проблема

### ISSUE THREAD

**Issue by cableru** [diadoc/diadocsdk-1c-docs#499]
После обновления компоненты диадок для 1с(v5.31.0.604 x86) https://diadoc-api.kontur.ru/1c-addin/DiadocCom_latest.zip при получении статуса контрагентов методом getStatus() возвращается пустая строка и разрывается партнерство с этим контрагентом.

Пример:

РезультатЗапроса = Organization.GetCounteragentListByStatus();
Для н = 0 По РезультатЗапроса.Count - 1 Цикл
    
    Counteragent = РезультатЗапроса.GetItem(н);
    Если Counteragent <> Неопределено Тогда
        Статус = СокрЛП(Counteragent.getStatus());
    КонецЕсли;
    
КонецЦикла;

При смене версии компоненты отличаются свойства контрагента 
v5.29.6.541
![v5 29 6 541](https://user-images.githubusercontent.com/46784876/89649223-1294f700-d8c9-11ea-9d17-fd48cc83cfc2.png)

v5.31.0.604 x86
![v5 31 0 604 x86](https://user-images.githubusercontent.com/46784876/89649234-1759ab00-d8c9-11ea-9032-1736a545449e.png)

Версия компоненты: v5.31.0.604 x86
Версия 1с: 1С:Предприятие 8.3 (8.3.16.1063)

**Comment by cableru** [comment]
Вот скриншот, моделирующий ситуацию.
Единственная строка исключает контрагента из работы.
![Снимок экрана 2020-08-07 в 16 26 15](https://user-images.githubusercontent.com/46784876/89650358-f8f4af00-d8ca-11ea-92cc-960999c9e29e.png)

**Comment by GilimkhanovDenis** [comment]
Добрый день.
Скорее всего что-то с регистрацией компоненты. На это указывает странное поведение объектов в вашей интеграции
1) В методе GetStatus() нет обращения к api Диадока, поэтому разрыва дружбы происходить не может
2) Значение статуса у вас попадает в поле GUID
3) Поля Guid и OrganizationGuid появились только в 5.31.0, но у вас на скриншоте они есть и в версии v5.29.6.541
4) Поле LastEventTimestampTicks у вас конвертируется в начало дня, но должно быть время с точностью до секунды в вашем часовом поясе

Разрегистрируйте компоненты.
Проверьте, через реестр, что не осталось никаких зарегистрированных объектов от любой из ранее зарегистрированных компонент.
Подключите свежую компоненту

**Comment by cableru** [comment]
Хорошо, мы допускаем, что компонента могла не корректно зарегистрироваться, хотя перед обновлением явно снимали регистрацию старой и регистрировали новую.
Но даже при таком конфликте старой и новой компоненты, каким образом при запросе метода GetStatus() происходит разрыв отношений.
В сообщении выше мы смогли воспроизвести это на контрагенте с кем были снова установлены отношения методом GetStatus().

**Comment by cableru** [comment]
из-за данной "проблемы" мы разорвали отношения с 4327 контрагентами и не совсем понимаем как такой метод мог сработать таким непредсказуемым образом.

**Comment by GilimkhanovDenis** [comment]
Предполагаем, что:
1) раз вы используете COM-версию, то интеграция работает на сервере
2) так как работаете на сервере, то сеанс 1С после регистрации компоненты не перезапускали
3) Так как перезапуска не было, то 1С использует закэшированные объекты
4) В новой компоненте появились новые поля в объект, по несчастливой случайности их интерфейс по размерам параметров совпал с объявлением методов в старой компоненте. Смещение согласуется с тем, как ведёт себя компонента в вашей интеграции
5) По логам все разрывы дружбы отправлялись из компоненты 5.29.6, что так же говорит в пользу предположения, что сеанс 1С не перезапускался

**Comment by cableru** [comment]
>http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_31_1.html
>Метод Counteragent.GetStatus() помечен устаревшим

Как я понимаю ошибка все таки была на Вашей стороне...

ну хорошо хоть исправили, плохо что сразу не признали... Выводы мы сделали...

**Comment by cableru** [comment]
мы никаким из доступных нам способом не смогли зарегистрировать "правильно" новую компоненту...
а изменения которые произошли в новой версии - как раз говорят об исправлении данных ошибок
