### ISSUE TITLE
Формат для колонки количество в печатной форме счет-фактуры

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#5]
Заполняю из 1C Content для объекта Organization.CreateSendTask("InvoiceContent").
Как сделать формат колонки количество? Т.е. нужно чтобы всегда после запятой было 3 знака, либо после запятой 3 нуля, если целое? См. скрин, такого я добился загрузим xml руками добавим в файл нули.
![img-2016-07-05-13-01-42](https://cloud.githubusercontent.com/assets/20082460/16581185/d45c41bc-42b0-11e6-8f8b-83f7feb541dd.png)

**Comment by vasbur** [comment]
заполняйте текстом, а не числом

**Comment by jakeqwert** [comment]
А не подскажите как можно перебить итог. См скрин ниже. Временно в xml поправил и загрузил, хотелось бы тоже самое делать через заполнение Content полученный через CreateSendTask("InvoiceCorrectionContent")
После заполнения Items, COM Объект TotalsDec и TotalsInc автоматически инициализируются итоговыми значениями, получается развернутый итог, 
А нам нужен свернутый итог, поэтому мы хотим присвоить свои значения свернутого итога, но происходит ошибка: 
«Не удается инициализировать реквизит TotalWithVatExcluded для объекта InvoiceCorrectionContent.TotalsDec по причине: Поле объекта недоступно для записи (TotalWithVatExcluded)»
![img-2016-07-04-14-20-31](https://cloud.githubusercontent.com/assets/20082460/16583522/ba1a8062-42be-11e6-8c97-5966a3033298.png)

**Comment by vasbur** [comment]
Это же неправильно
Строки называются "Сумма строк В" и "Сумма строк Г" - компонента ровно так и считает.
То, как вы хотите сделать - противоречит логике формы и, видимо, законодательству
