### ISSUE TITLE
Изменение данных в БД 1С?

### ISSUE THREAD

**Issue by ShibaevAnton** [diadoc/diadocsdk-1c-docs#50]
Я правильно понимаю, что в какой то момент при использовании вашей обработки создаются дополнительные свойства для объектов? 

А где нибудь об этом можно прочитать?

**Comment by volodkindv** [comment]
Да, правильно понимаете.
Обработка создает при первоначальном запуске:
1) Несколько элементов "ПланыВидовХарактеристик.НастройкиПользователей"
2) Несколько элементов "ПланыВидовХарактеристик.ЗначенияСвойствОбъектов"
Для этого достаточно один раз запустить обработку под пользователем с полными правами.
При повседневной работе она активно работает с регистрами сведений "НастройкиПользователей" и "ЗначенияСвойствОбъектов".
Полный перечень всех создаваемых объектов можно увидеть, запустив обработку под полными правами на копии базы и посмотрев в журнал регистрации.

**Comment by ShibaevAnton** [comment]
ок. спс
