### ISSUE TITLE
##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: Документ не может быть отправлен в указанном формате

### ISSUE THREAD

**Issue by chedek** [diadoc/diadocsdk-1c-docs#500]
Добрый день! Работаю через DiadocComApi.dll.  Выполняю такой код:

SendTask := Organization.CreatePackageSendTask2;
SendTask.CounterAgentId := Counteragent.Id;
DocumentToSend := SendTask.AddDocumentFromFile('UniversalTransferDocument', 'СЧФДОП', 'utd820_05_01_01',C:\1.xml').
SendTask.Send;

xml-файл содержит УПД по 820 приказу в кодировке utf-8. Заголовок такой:

<?xml version="1.0" encoding="utf-8"?>
<Файл ИдФайл="ON_NSCHFDOPPR_2BM-2312135215-231201001-201604011214213372005_2BM-231105834105--2016042607052561120930000000_20200810_494B73F5-139F-4FF2-B6D9-9C32F54699AD" ВерсФорм="5.01" ВерсПрог="Diadoc 1.0">
<СвУчДокОбор ИдОтпр="2BM-231105834105--2016042607052561120930000000" ИдПол="2BM-2312135215-231201001-201604011214213372005">
  <СвОЭДОтпр ИННЮЛ="6663003127" ИдЭДО="2BM" НаимОрг="АО &quot;ПФ &quot;СКБ Контур&quot;" />
</СвУчДокОбор>
<Документ КНД="1115131" ......

На последней команде падает с ошибкой. Отправка неформализованного документа таким же методом работает. При этом, если данный файл загружаю вручную через web-интерфейс, он не содержит ошибок и отправляется без проблем.
Что не так?

**Comment by chedek** [comment]
В дополнение, заполнил тот же самый документ через DynamicContent вместо загрузки из файла. Ошибка при отправке та же.

**Comment by IrinaShmonina** [comment]
@chedek здравствуйте
В строчке DocumentToSend := SendTask.AddDocumentFromFile('UniversalTransferDocument', 'СЧФДОП', 'utd820_05_01_01',C:\1.xml') не хватает кавычки

Возможно, файл сформирован в utf8. Файл должен быть в cp1251 по формату

**Comment by chedek** [comment]
Где именно не хватает кавычки? Здесь все на месте. Файл выгружал и в формате utf8 и в cp1251.  Заработало, когда перешел к заполнению DynamicContent. К сожалению, сообщение не очень информативное и совершенно не говорящее не о чем. Приходится просто методом тыка пробовать все варианты.

**Comment by kulakovskaya** [comment]
Добрый день!
Кавычки не хватает в последнем аргументе DocumentToSend := SendTask.AddDocumentFromFile('UniversalTransferDocument', 'СЧФДОП', 'utd820_05_01_01',**'C:\1.xml'**).

Вам удалось разобраться с проблемой? Требуется ли еще наша помощь?

**Comment by chedek** [comment]
Добрый день, там кавычки все на месте.  Это в 1С, а в Delphi, там апостроф это аналог кавычки

Проблема решилась переходом к DynamicContent

**Comment by tomkad70** [comment]
Добрый день. Подскажите в чём ошибка:
делаю post запрос
`{
 "FromBoxId": "...@diadoc.ru",
 "ToBoxId": "...@diadoc.ru",
 "DocumentAttachments": [
        {
            "SignedContent":
            {
                "Content": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0id2luZG93cy0xMjUxIj8+CjzQpNCw0LnQuyDQmNC00KTQsNC50Ls9Ik9OX05TQ0hGRE9QUFJfMkJNLTcwMTcxNzU3Nzk3MC0yMDIxMTEyMTAyNTEwODg0NTIzNDcwMDAwMDAwMF8ySUo3NDM3NUQ3NUI1MzM0NDMxQTA5MzBFQkZCNTE4RDgwOV8yMDIyMDgyOV9CRjRFQkU3NC02NjI2LTQ5NDUtQTc1Mi02Q0Y5NUY4MTczRDUiINCS0LXRgNGB0KTQvtGA0Lw9IjUuMDEiPgogIDzQodCy0KPRh9CU0L7QutCe0LHQvtGAINCY0LTQntGC0L/RgD0iMklKNzQzNzVENzVCNTMzNDQzMUEwOTMwRUJGQjUxOEQ4MDkiINCY0LTQn9C+0Ls9IjJCTS03MDE3MTc1Nzc5NzAtMjAyMTExMjEwMjUxMDg4NDUyMzQ3MDAwMDAwMDAiPgogICAgPNCh0LLQntCt0JTQntGC0L/RgCDQndCw0LjQvNCe0YDQsz0i0J7QntCeICZxdW90O9Ct0JTQmNCh0J7QpNCiJnF1b3Q7IiDQmNCd0J3QrtCbPSI3ODAxNDcxMDgyIiDQmNC00K3QlNCePSIySUoiLz4KICA8L9Ch0LLQo9GH0JTQvtC60J7QsdC+0YA+CiAgPNCU0L7QutGD0LzQtdC90YIg0JrQndCUPSIxMTE1MTI1IiDQpNGD0L3QutGG0LjRjz0i0KHQp9Ck0JTQntCfIiDQlNCw0YLQsNCY0L3RhNCf0YA9IjI5LjA4LjIwMjIiINCS0YDQtdC80JjQvdGE0J/RgD0iMDkuMTMuMzgiINCd0LDQuNC80K3QutC+0L3QodGD0LHQodC+0YHRgj0iINCe0YLQutGA0YvRgtC+0LUg0LDQutGG0LjQvtC90LXRgNC90L7QtSDQvtCx0YnQtdGB0YLQstC+ICZxdW90O9Ci0J7QnNCh0JrQntCVINCf0JjQktCeJnF1b3Q7Ij4KICAgIDzQodCy0KHRh9Ck0LDQutGCINCd0L7QvNC10YDQodGH0KQ9ItCh0KQyMi04MjI4NCIg0JTQsNGC0LDQodGH0KQ9IjI0LjA4LjIwMjIiINCa0L7QtNCe0JrQkj0iNjQzIj4KICAgICAgPNCh0LLQn9GA0L7QtD4KICAgICAgICA80JjQtNCh0LI+CiAgICAgICAgICA80KHQstCu0JvQo9GHINCd0LDQuNC80J7RgNCzPSIg0J7RgtC60YDRi9GC0L7QtSDQsNC60YbQuNC+0L3QtdGA0L3QvtC1INC+0LHRidC10YHRgtCy0L4gJnF1b3Q70KLQntCc0KHQmtCe0JUg0J/QmNCS0J4mcXVvdDsiINCY0J3QndCu0Js9IjcwMTgwMTEwNDUiLz4KICAgICAgICA8L9CY0LTQodCyPgogICAgICAgIDzQkNC00YDQtdGBPgogICAgICAgICAgPNCQ0LTRgNCg0KQg0JjQvdC00LXQutGBPSI2MzQwMjgiINCa0L7QtNCg0LXQs9C40L7QvT0iNzAiINCT0L7RgNC+0LQ9ItCi0L7QvNGB0LoiINCj0LvQuNGG0LA9ItCc0L7RgdC60L7QstGB0LrQuNC5INGC0YDQsNC60YIiINCU0L7QvD0iNDYiLz4KICAgICAgICA8L9CQ0LTRgNC10YE+CiAgICAgIDwv0KHQstCf0YDQvtC0PgogICAgICA80JPRgNGD0LfQntGCPgogICAgICAgIDzQntC90JbQtT7QvtC9INC20LU8L9Ce0L3QltC1PgogICAgICA8L9CT0YDRg9C30J7Rgj4KICAgICAgPNCT0YDRg9C30J/QvtC70YPRhz4KICAgICAgICA80JjQtNCh0LI+CiAgICAgICAgICA80KHQstCY0J8g0JjQndCd0KTQmz0iNzAxNzE3NTc3OTcwIj4KICAgICAgICAgICAgPNCk0JjQniDQpNCw0LzQuNC70LjRjz0i0KHQntCa0J7Qm9Ce0JIiINCY0LzRjz0i0JjQktCQ0J0iINCe0YLRh9C10YHRgtCy0L49ItCY0JLQkNCd0J7QktCY0KciLz4KICAgICAgICAgIDwv0KHQstCY0J8+CiAgICAgICAgPC/QmNC00KHQsj4KICAgICAgICA80JDQtNGA0LXRgT4KICAgICAgICAgIDzQkNC00YDQoNCkINCa0L7QtNCg0LXQs9C40L7QvT0iNzAiLz4KICAgICAgICA8L9CQ0LTRgNC10YE+CiAgICAgIDwv0JPRgNGD0LfQn9C+0LvRg9GHPgogICAgICA80KHQstCf0L7QutGD0L8+CiAgICAgICAgPNCY0LTQodCyPgogICAgICAgICAgPNCh0LLQmNCfINCY0J3QndCk0Js9IjcwMTcxNzU3Nzk3MCI+CiAgICAgICAgICAgIDzQpNCY0J4g0KTQsNC80LjQu9C40Y89ItCh0J7QmtCe0JvQntCSIiDQmNC80Y89ItCY0JLQkNCdIiDQntGC0YfQtdGB0YLQstC+PSLQmNCS0JDQndCe0JLQmNCnIi8+CiAgICAgICAgICA8L9Ch0LLQmNCfPgogICAgICAgIDwv0JjQtNCh0LI+CiAgICAgICAgPNCQ0LTRgNC10YE+CiAgICAgICAgICA80JDQtNGA0KDQpCDQmtC+0LTQoNC10LPQuNC+0L09IjcwIiDQk9C+0YDQvtC0PSLQotC+0LzRgdC6INCzIiDQo9C70LjRhtCwPSLQntCx0YDRg9GH0LXQstCwINGD0LsiINCU0L7QvD0iMzAiINCa0LLQsNGA0YI9IjUxIi8+CiAgICAgICAgPC/QkNC00YDQtdGBPgogICAgICA8L9Ch0LLQn9C+0LrRg9C/PgogICAgPC/QodCy0KHRh9Ck0LDQutGCPgogICAgPNCi0LDQsdC70KHRh9Ck0LDQutGCPgogICAgICA80KHQstC10LTQotC+0LIg0J3QvtC80KHRgtGAPSIiINCd0LDQuNC80KLQvtCyPSLQktC+0LTQsCDQvNC40L3QtdGA0LDQu9GM0L3QsNGPICZxdW90O9Cn0LDQttC10LzRgtC+JnF1b3Q7INC/0YDQuNGA0L7QtNC90LDRjyDQv9C40YLRjNC10LLQsNGPINC70LXRh9C10LHQvdC+LdGB0YLQvtC70L7QstCw0Y8g0LPQuNC00YDQvtC60LDRgNCx0L7QvdCw0YLQvdC+LdGF0LvQvtGA0LjQtNC90LDRjyDQvdCw0YLRgNC40LXQstCw0Y8g0LPQsNC30LjRgNC+0LLQsNC90L3QsNGPLiAo0J/QrdCiIDAuNSkiINCa0L7Qu9Ci0L7Qsj0iMTIuMDAwIiDQptC10L3QsNCi0L7Qsj0iMTcuNDgiINCh0YLQotC+0LLQkdC10LfQndCU0KE9IjIwOS44MCIg0J3QsNC70KHRgj0iMjAlIiDQodGC0KLQvtCy0KPRh9Cd0LDQuz0iMjUxLjc2IiDQntCa0JXQmF/QotC+0LI9Ijg2OCI+CiAgICAgICAgPNCQ0LrRhtC40Lc+CiAgICAgICAgICA80JHQtdC30JDQutGG0LjQtz7QsdC10Lcg0LDQutGG0LjQt9CwPC/QkdC10LfQkNC60YbQuNC3PgogICAgICAgIDwv0JDQutGG0LjQtz4KICAgICAgICA80KHRg9C80J3QsNC7PgogICAgICAgICAgPNCh0YPQvNCd0LDQuz40MS45Njwv0KHRg9C80J3QsNC7PgogICAgICAgIDwv0KHRg9C80J3QsNC7PgogICAgICAgIDzQlNC+0L/QodCy0LXQtNCi0L7Qsj4KICAgICAgICAgIDzQndC+0LzQodGA0LXQtNCY0LTQtdC90YLQotC+0LI+CiAgICAgICAgICAgIDzQndC+0LzQo9C/0LDQuj4wMjA0NjA3MDIyNzQxODk2MzcxMjwv0J3QvtC80KPQv9Cw0Lo+CiAgICAgICAgICA8L9Cd0L7QvNCh0YDQtdC00JjQtNC10L3RgtCi0L7Qsj4KICAgICAgICA8L9CU0L7Qv9Ch0LLQtdC00KLQvtCyPgogICAgICA8L9Ch0LLQtdC00KLQvtCyPgogICAgICA80KHQstC10LTQotC+0LIg0J3QvtC80KHRgtGAPSIiINCd0LDQuNC80KLQvtCyPSLQktC+0LTQsCDQvNC40L3QtdGA0LDQu9GM0L3QsNGPINC/0YDQuNGA0L7QtNC90LDRjyDQv9C40YLRjNC10LLQsNGPINGB0YLQvtC70L7QstCw0Y8gJnF1b3Q70JLQuNCy0LDQu9GMJnF1b3Q7ICgmcXVvdDtWaXZhbCZxdW90Oykg0L3QtdCz0LDQt9C40YDQvtCy0LDQvdC90LDRjy4gMC410LsuIiDQmtC+0LvQotC+0LI9IjEyLjAwMCIg0KbQtdC90LDQotC+0LI9IjIxLjc3IiDQodGC0KLQvtCy0JHQtdC30J3QlNChPSIyNjEuMjAiINCd0LDQu9Ch0YI9IjIwJSIg0KHRgtCi0L7QstCj0YfQndCw0Ls9IjMxMy40NCIg0J7QmtCV0Jhf0KLQvtCyPSI4NjgiPgogICAgICAgIDzQkNC60YbQuNC3PgogICAgICAgICAgPNCR0LXQt9CQ0LrRhtC40Lc+0LHQtdC3INCw0LrRhtC40LfQsDwv0JHQtdC30JDQutGG0LjQtz4KICAgICAgICA8L9CQ0LrRhtC40Lc+CiAgICAgICAgPNCh0YPQvNCd0LDQuz4KICAgICAgICAgIDzQodGD0LzQndCw0Ls+NTIuMjQ8L9Ch0YPQvNCd0LDQuz4KICAgICAgICA8L9Ch0YPQvNCd0LDQuz4KICAgICAgICA80JTQvtC/0KHQstC10LTQotC+0LI+CiAgICAgICAgICA80J3QvtC80KHRgNC10LTQmNC00LXQvdGC0KLQvtCyPgogICAgICAgICAgICA80J3QvtC80KPQv9Cw0Lo+MDIwNDYwNzAyMjc0Mjk5MjM3MTI8L9Cd0L7QvNCj0L/QsNC6PgogICAgICAgICAgPC/QndC+0LzQodGA0LXQtNCY0LTQtdC90YLQotC+0LI+CiAgICAgICAgPC/QlNC+0L/QodCy0LXQtNCi0L7Qsj4KICAgICAgPC/QodCy0LXQtNCi0L7Qsj4KICAgICAgPNCh0LLQtdC00KLQvtCyINCd0L7QvNCh0YLRgD0iIiDQndCw0LjQvNCi0L7Qsj0i0J/QuNCy0L4gJnF1b3Q70J3QtdC80LXRhtC60L7QtSZxdW90OyDRgdCy0LXRgtC70L7QtSDRhNC40LvRjNGC0YDQvtCy0LDQvdC90L7QtSDQv9Cw0YHRgtC10YDQuNC30L7QstCw0L3QvdC+0LUgKNCx0YPRgi4pIiDQmtC+0LvQotC+0LI9IjEyLjAwMCIg0KbQtdC90LDQotC+0LI9IjQ1LjM5IiDQodGC0KLQvtCy0JHQtdC30J3QlNChPSI1NDQuNzAiINCd0LDQu9Ch0YI9IjIwJSIg0KHRgtCi0L7QstCj0YfQndCw0Ls9IjY1My42NCIg0J7QmtCV0Jhf0KLQvtCyPSI4NjgiPgogICAgICAgIDzQkNC60YbQuNC3PgogICAgICAgICAgPNCh0YPQvNCQ0LrRhtC40Lc+MTQ0LjAwPC/QodGD0LzQkNC60YbQuNC3PgogICAgICAgIDwv0JDQutGG0LjQtz4KICAgICAgICA80KHRg9C80J3QsNC7PgogICAgICAgICAgPNCh0YPQvNCd0LDQuz4xMDguOTQ8L9Ch0YPQvNCd0LDQuz4KICAgICAgICA8L9Ch0YPQvNCd0LDQuz4KICAgICAgICA80JTQvtC/0KHQstC10LTQotC+0LIvPgogICAgICA8L9Ch0LLQtdC00KLQvtCyPgogICAgICA80JLRgdC10LPQvtCe0L/QuyDQodGC0KLQvtCy0JHQtdC30J3QlNCh0JLRgdC10LPQvj0iMTAxNS43MCIg0KHRgtCi0L7QstCj0YfQndCw0LvQktGB0LXQs9C+PSIxMjE4Ljg0Ij4KICAgICAgICA80KHRg9C80J3QsNC70JLRgdC10LPQvj4KICAgICAgICAgIDzQodGD0LzQndCw0Ls+MjAzLjE0PC/QodGD0LzQndCw0Ls+CiAgICAgICAgPC/QodGD0LzQndCw0LvQktGB0LXQs9C+PgogICAgICA8L9CS0YHQtdCz0L7QntC/0Ls+CiAgICA8L9Ci0LDQsdC70KHRh9Ck0LDQutGCPgogICAgPNCh0LLQn9GA0L7QtNCf0LXRgD4KICAgICAgPNCh0LLQn9C10YAg0KHQvtC00J7Qv9C10YA9ItCi0L7QstCw0YDRiyDQv9C10YDQtdC00LDQvdGLIiDQlNCw0YLQsNCf0LXRgD0iMjQuMDguMjAyMiI+CiAgICAgICAgPNCe0YHQvdCf0LXRgCDQndCw0LjQvNCe0YHQvT0i0JTQvtCz0L7QstC+0YAiINCd0L7QvNCe0YHQvT0iMjIvMjA4NzQiINCU0LDRgtCw0J7RgdC9PSIxNi4xMi4yMDIwIi8+CiAgICAgIDwv0KHQstCf0LXRgD4KICAgIDwv0KHQstCf0YDQvtC00J/QtdGAPgogICAgPNCf0L7QtNC/0LjRgdCw0L3RgiDQntCx0LvQn9C+0LvQvT0iNSIg0KHRgtCw0YLRg9GBPSIxIiDQntGB0L3Qn9C+0LvQvT0i0JTQvtC70LbQvdC+0YHRgtC90YvQtSDQvtCx0Y/Qt9Cw0L3QvdC+0YHRgtC4Ij4KICAgICAgPNCu0Jsg0JjQndCd0K7Qmz0iNzAxODAxMTA0NSIg0J3QsNC40LzQntGA0LM9IiDQntGC0LrRgNGL0YLQvtC1INCw0LrRhtC40L7QvdC10YDQvdC+0LUg0L7QsdGJ0LXRgdGC0LLQviAmcXVvdDvQotCe0JzQodCa0J7QlSDQn9CY0JLQniZxdW90OyIg0JTQvtC70LbQvT0i0JPQtdC90LXRgNCw0LvRjNC90YvQuSDQtNC40YDQtdC60YLQvtGAIj4KICAgICAgICA80KTQmNCeINCk0LDQvNC40LvQuNGPPSLQmtCb0K/QmdCdIiDQmNC80Y89ItCT0JDQm9CY0J3QkCIg0J7RgtGH0LXRgdGC0LLQvj0i0JjQktCQ0J3QntCS0J3QkCIvPgogICAgICA8L9Cu0Js+CiAgICA8L9Cf0L7QtNC/0LjRgdCw0L3Rgj4KICA8L9CU0L7QutGD0LzQtdC90YI+Cjwv0KTQsNC50Ls+Cg=="                
            },
            "TypeNamedId": "UniversalTransferDocument",
            "Function": "СЧФДОП",
            "Version": "utd820_05_01_02"
        }
    ]
}`

ошибка  MessageToPost.DocumentAttachments[0]: Документ не может быть отправлен в указанном формате

**Comment by GilimkhanovDenis** [comment]
@tomkad70 Вопрос точно имеет отношение к COM компоненте?

кажется, вы сами формируете запрос. Возможно, вам нужно [сюда](https://github.com/diadoc/diadocapi-docs)
