### ISSUE TITLE
СЧФ вместо УТД 

### ISSUE THREAD

**Issue by Ant377** [diadoc/diadocsdk-1c-docs#501]
Добрый день.
Создаётся УПД. Позволяет в web-интерфейсе поменять на "СЧФ", а хочется сразу Счёт-фактуру.

  SendTask := Organization.CreatePackageSendTask2;
  SendTask.CounterAgentId     := aContrAgents.id;
  SendTask.IsDraft                    := True;
  SendTask.StrictDraftValidation      := True;
   DocToSend1 := SendTask.AddDocument('UniversalTransferDocument', 'СЧФ', 'utd820_05_01_01');    
   DocToSend1.Comment         := ' Test Создание Счёт-фактуры Тест ';
   UTD := DocToSend1.content.UniversalTransferDocument;
   UTD.Function        := 'СЧФ';
   UTD.DocumentNumber  :=  'Test СЧФ API 4';
   UTD.DocumentDate    :=   '10.08.2020'; 
   UTD.Currency        := '643';
   UTD.DocumentCreator := 'Общество с ограниченной ответственностью'
      SetSeller( UTD.Sellers.AddSeller );
      SetBuyer( UTD.Buyers.AddBuyer );
      SetSigner( UTD.Signers.Additems );
      FillTable( UTD.Table );
    SendTask.Send;

**Comment by IrinaShmonina** [comment]
@Ant377 здравствуйте
Замените строку 
DocToSend1 := SendTask.AddDocument('UniversalTransferDocument', 'СЧФ', 'utd820_05_01_01');
На
DocToSend1 := SendTask.AddDocument('Invoice', 'СЧФ', 'utd820_05_01_01');

**Comment by Ant377** [comment]
Здравствуйте, спасибо помогло.
А что писать для акта? 
SendTask.AddDocument('Act', 'default', 'utd820_05_01_01')  - выдаёт ошибку.
Почему в документации не раскрыты возможные значения аргументов?

**Comment by kulakovskaya** [comment]
Добрый день!
Для акта необходимо указать следующее:
SendTask.AddDocument('XmlAcceptanceCertificate', 'default', 'utd820_05_01_01').
С помощью метода [Organization.GetDocumentTypes()](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html?highlight=GetDocumentTypes#Organization.GetDocumentTypes) можно получить коллекцию типов документов, доступных для организации. Для каждого типа документа будет информация о значениях аргументов.

**Comment by Ant377** [comment]
Добрый день, спасибо.
Ещё вопрос по акту.
Какое свойство/объект отвечает за "Основания передачи (сдачи)" ?

**Comment by kulakovskaya** [comment]
"Основание передачи (сдачи)" необходимо заполнить в контенте документа.

**Comment by Ant377** [comment]
Это понятно, что контенте. Как узнать в каком свойстве?

**Comment by kulakovskaya** [comment]
Добрый день!
Нужно заполнить TransferBase, который находится в TransferInfo. 
Описание всех свойств есть в UserDataXSD, получить которую можно методом [SaveUserDataXSD](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html?highlight=SaveUserDataXSD#Organization.SaveUserDataXSD).

**Comment by Ant377** [comment]
Спасибо.
