### ISSUE TITLE
DocumentsTask.GetDocuments()

### ISSUE THREAD

**Issue by VladAleshin** [diadoc/diadocsdk-1c-docs#503]
В документации есть описание того, как получить список документов по организации из 1С: 
 
// Создаем объект DocumentsTask
DocumentsTask = Organization.GetDocumentsTask();
 
// Заполняем параметры отбора документов

DocumentsTask.FromSendDate = НачалоГода(ТекущаяДата());
DocumentsTask.ToSendDate   = КонецГода(ТекущаяДата());
DocumentsTask.Category     = "XmlTorg12.InboundWaitingForRecipientSignature";
 
// Получаем коллекцию документов
DocumentList = DocumentsTask.GetDocuments();
 
Данный код работает, но переменная DocumentList всегда пустая, независимо от периода или категории, которые выставлены в отборе.
 
Просьба уточнить, каким образом можно поучить список документов, которые мы выставили контрагентам за определенный период, используя данное API?

**Comment by IrinaShmonina** [comment]
@VladAleshin, здравствуйте
1. Какую версию компоненты вы используете?
2. Есть ли у вас в ящике торг-12, которые ожидают подписи КА за тот период, который вы указываете?

**Comment by GilimkhanovDenis** [comment]
Вы пытаетесь получить документы, которые выставили контрагентам? Тогда фильтр неправильный - сейчас вы запрашиваете входящие документы
XmlTorg12.**Inbound**WaitingForRecipientSignature
