### ISSUE TITLE
The 'Должн' attribute is invalid

### ISSUE THREAD

**Issue by vbperesadin** [diadoc/diadocsdk-1c-docs#505]
Здравствуйте! Компонента DiadocCom_5_30_1_584_x64 при попытке подписания входящего документа получаю ошибку
Validation errors: Location: Line: 14, Position: 30, /Файл[1]/ИнфПок[1]/Подписант[1]/ЮЛ[1]/@Должн, Message: The 'Должн' attribute is invalid - The value '' is invalid according to its datatype 'String' - The actual length is less than the MinLength value.

заполняю данные так

        _Content.AcceptanceDate = Формат(ТекущаяДата(),  "ДФ=dd.MM.yyyy");
	Content.DocumentCreator = "Какая организация приняла";
	Content.OperationContent = "Приняли и отправили подпись назад";
	
	Signer = Content.Signers.AddItems();
	//Signer.SignerReference.BoxId = BoxID;
	//Signer.SignerReference.CertificateThumbprint = thumbprint;
	
	Signer.SignerDetails.LastName = "Получатель";
	Signer.SignerDetails.FirstName = ДанныеПодписи.Имя;
	Signer.SignerDetails.MiddleName = ДанныеПодписи.Отчество;
	Signer.SignerDetails.SignerPowers = "1";//5;    	// лицо, совершившее сделку, операцию и ответственное за её оформление и за подписание счетов
	Signer.SignerDetails.SignerPowersBase = "Должностные обязанности";
	Signer.SignerDetails.SignerStatus = "5";   // Работник организации - покупателя (для документов в формате приказа №820);

	Signer.SignerDetails.SignerType = "1";// юрлицо
	Signer.SignerDetails.INN = прКонтекст.ДиадокОрганизация.Inn;
	Signer.SignerDetails.SignerOrgPowersBase  = "Пусть будет доверенность №1";
	Signer.SignerDetails.SignerOrganizationName = "Тестовая организация";

Если же я заполняю SignerReference, а не SignerDetails тогда {ВнешняяОбработка.ПодписаниеИОтправкаВДиадок.Форма.Форма.Форма(384)}: Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalTransferDocumentBuyerTitle/Signers/SignerReference: @Inn is required
/UniversalTransferDocumentBuyerTitle/Signers/SignerReference: SignerDetails not found for boxId=1102d5f2-e2fd-466a-b53d-15a068e4fe44, thumbprint=69B46E0278E8B97833E5B5A5E3F54CE58981AB87, documentTitleType=8

**Comment by volodkindv** [comment]
Добрый день!
В Signer.SignerDetails не хватает поля Position, которое отвечает за должность подписанта в организации.
Список всех возможных полей можно увидеть в XSD [здесь](https://diadoc-sdk.readthedocs.io/ru/latest/howto/utd820.html#userdataxml), или в отладчике 1С.

**Comment by vbperesadin** [comment]
Большое спасибо, Данила!  Так получилось. Скажите, а есть ли где актуальная документация, что-где-в каких случаях нужно заполнять!? Потому что http://1c-docs.diadoc.ru/_/downloads/ru/dev/pdf/ как-то совсем ничего нет

**Comment by volodkindv** [comment]
Отдельной документации по заполнению полей документов 820 формата сейчас нет. Описание полей есть в xsd-схеме, которую можно скачать через [GetDocumentTypes ](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetDocumentTypes) -> [SaveUserDataXsd](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.SaveUserDataXSD) 
Или [тут](https://diadoc-sdk.readthedocs.io/ru/latest/howto/utd820.html#userdataxml) (ссылка "XSD-схема упрощенного xml (UserDataXsd) для титула продавца").

Документация по ссылке http://1c-docs.diadoc.ru/_/downloads/ru/dev/pdf/ - это просто версия для печати. Можно пользоваться общей ссылкой http://1c-docs.diadoc.ru/ru/latest/ и смотреть уже нужные разделы.

**Comment by vbperesadin** [comment]
Спасибо!
