### ISSUE TITLE
Заполнение структуры Address в Протоконтенте подключаемого модуля

### ISSUE THREAD

**Issue by ElkinPalkin** [diadoc/diadocsdk-1c-docs#506]
Я пытаюсь в Грузополучателе УПД вывести адрес из другого источника по согласованию с контрагентом. Для этого использую подключаемый модуль для обработки Диадок 5.42.01.665 (версия Windows х64), функция ОбработкаСобытияПодключаемогоМодуля() с именем события "ПослеЗаполненияКонтента".
Дело в том, что нужный адрес для вывода у меня представлен в виде строкового представления с запятыми, а заполнять надо Протоконтент, где есть поле Address, с кучей полей. Есть ли какая-то функция в модуле Диадок, на вход которой я могу подать строку с моим адресом, а она разложит по полям мой переданный адрес?

**Comment by volodkindv** [comment]
В модуле Диадок такой функции нет. Но вы можете не раскладывать адрес по полям, а записать одной строкой. Формат такое допускает.
```
		AddressInfo.IsForeign	 = Истина;
		AddressInfo.CountryCode	 = "643";
		AddressInfo.AddressText	 = "620100, Свердловская обл, г. Екатеринбург, ул. Юридическая, д.1";
```

**Comment by ElkinPalkin** [comment]
Спасибо! Жаль.
Но где-то ведь должно быть это раскладывание, т.к. в типовом поведении там уже значения какие-то есть (я выяснил это ДО внесения мной каких-либо изменений), значит типовой код умеет раскладывать?

**Comment by volodkindv** [comment]
Типовой код использует общие модули типовых конфигураций, где реализована такая раскладка. Попробуйте посмотреть модули с именами вроде "УправлениеКонтактнойИнформацией".

**Comment by ElkinPalkin** [comment]
Эти общие модули "УправлениеКонтактнойИнформацией" я уже облазил.
Мне-то интересно заполнение "Address", чтобы оценить в какой момент времени там появляются заполненные поля.

**Comment by volodkindv** [comment]
Посмотрите процедуры ЗаполнитьСтруктуруАдреса(), СведенияОбАдресе(), Заполнить_AddressInfo().

**Comment by ElkinPalkin** [comment]
Спасибо! Это гляну.
