### ISSUE TITLE
Неверный идентификатор получателя в УПД

### ISSUE THREAD

**Issue by codexa727** [diadoc/diadocsdk-1c-docs#507]
Добрый день!
Отправляю УПД через API (AddIn x86 5.29.7.549)
Использую метод GetCounteragentById(), который возвращает контрагента по идентификатору почтового ящика.  
Устанавливаю свойство CounterAgentId в задании на отправку:
PackageSendTask= Organization.CreatePackageSendTask2();
PackageSendTask.CounterAgentId = Counteragent.Id;
В задании кроме свойства CounterAgentId я больше никаких идентификаторов не устанавливаю.
 
После отправки в личном кабинете в исходящем документе появляется следующее сообщение:
"Документ не соответствует установленному формату.
Обнаружены следующие нарушения:
Идентификатор получателя "2BM-..........-.........-201504010559542939230" в документе не соответствует идентификатору в карточке."

Проверяю идентификатор участника ЭДО в файле контрагентов и в сообщении об ошибке - идентификаторы разные.
И судя по идентификатору, который мне сообщает система в ошибке - это идентификатор прямого ящика Диадок.
А контрагент работает через роуминг.
Из всех контрагентов такая ошибка появилась у 2-х. Причем у одного проблема решилась переходом на прямой ящик Диадока.
 
Подскажите, пожалуйста, почему в системе Диадок в документе идентификатор получателя отличается от идентификатора из файла контрагентов? Откуда он там берется? Он заполняется в момент загрузки документа? Я при выгрузке его нигде не указываю.
Тогда получается, что в момент загрузки в систему Диадок получатель заполняется первым попавшимся значением?
А я могу как-то повлиять на эту ситуацию?

**Comment by kulakovskaya** [comment]
Добрый день!
Если Вы указали BoxId контрагента, то OrgName, Inn, Kpp, Address, FnsParticipantId уже не нужно указывать в контенте.
Тогда ИдПол заполнится корректно.

**Comment by codexa727** [comment]
Если можно, чуть подробнее - вообще не добавлять сведения о покупателе? 
Я добавляла вот таким образом:
Utd820_SellerContent = DocumentToSend.Content.UniversalTransferDocument;
Buyer = Utd820_SellerContent.Buyers.AddBuyer();
Buyer.OrganizationDetails.OrgName = КонтрагентНаименованиеПолное;
Buyer.OrganizationDetails.Inn	= КонтрагентИНН;
Buyer.OrganizationDetails.Kpp = КонтрагентКПП;
Если я вообще не указываю сведений о покупателе, то получаю ошибку " The element 'UniversalTransferDocument' has incomplete content. List of possible elements expected: 'Buyers'."

**Comment by kulakovskaya** [comment]
Добрый день! Вместо перечисленных реквизитов выше вам необходимо заполнить Buyer.OrganizationReference.BoxId или Buyer.OrganizationDetails.FnsParticipantId.

**Comment by codexa727** [comment]
Ок, делаю так:
Buyer = Utd820_SellerContent.Buyers.AddBuyer();
Buyer.OrganizationReference.BoxId = BoxID;

 ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalTransferDocument/Buyers/Buyer/OrganizationReference: Address is required

**Comment by codexa727** [comment]
Добрый день!
При отправке документа сегодня получила интересную ошибку:
 ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid generated title:
Metadata errors: 
Validation errors: Location: Line: 39, Position: 90, /Файл[1]/Документ[1]/СвСчФакт[1]/СвПокуп[1]/Адрес[1]/АдрРФ[1]/@Кварт, Message: The 'Кварт' attribute is invalid - The value 'Помещение VIII Ком. 2 Этаж 1' is invalid according to its datatype 'String' - The actual length is greater than the MaxLength value.

То есть я больше не передаю никаких адресов, но если на стороне Диадока адрес у контрагента заполнен с ошибками - документ не выгружается.
На стороне Диадока не контролируется выполнение условий по длине полей? И что с этим делать?

**Comment by NataliaShumikhina** [comment]
Добрый день! Проблема нам известная. Дело в том, что в Диадоке используются разные форматы и разные документы с разными требованиями к длине полей, а адрес у организации один. Из-за этого могут возникать конфликты, что адрес, указанный в Диадоке "не влазит" в какое-то поле формата. Сроков решения этой проблемы на стороне Диадока нет.
Если решать проблему системно на стороне интеграционного решения, то при получении такой ошибки можно заполнять адрес в xml вручную.
Если хочется исправить проблему только для текущего случая, то напишите boxid ящика, для которого была получена ошибка, мы попробуем скорректировать адрес

**Comment by codexa727** [comment]
a4aefe6a-9494-4f27-893d-34a66c54b255

**Comment by codexa727** [comment]
А когда примерно вы попробуете?

**Comment by YudinaM** [comment]
Добрый день!
Мы попросили техподдержку связаться с вашим контрагентом и вместе с ним сменить адрес в его настройках. Со своей стороны вы также можете связаться с контрагентом, чтобы ускорить решение вопроса.

**Comment by YudinaM** [comment]
Адрес вашего контрагента изменен, можете повторить отправку.

**Comment by codexa727** [comment]
Добрый день!
Теперь возникла следующая проблема - у всех контрагентов, являющихся ИП и работающих в роуминге, в адресе покупателя в документе указан только город, больше никаких данных нет. Каким образом можно решить эту проблему?
