### ISSUE TITLE
iDocument:GetDynamicContent("Seller")

### ISSUE THREAD

**Issue by darujo** [diadoc/diadocsdk-1c-docs#508]
Добрый день.
На тестовом стенде перестал возвращаться объект при получении вот таким способом iDocument:GetDynamicContent("Seller"). Что-то изменилось или это проблема на стороне diadoc?

**Comment by GilimkhanovDenis** [comment]
Добрый день
Можете дать boxId и идентификатор документа ?

**Comment by darujo** [comment]
OrganizationId VT_BSTR 66720198c9d84bb2afd6a1aba8b47b12@diadoc.ru
DocumentId VT_BSTR 38124c26-f9c2-4497-a67d-a05259bce3c4fb5cd5cc-8837-464a-b443-a29bdf557581

**Comment by GilimkhanovDenis** [comment]
У нас не возникает никакой ошибке при запросе контента для подобных документов

Какая у вас ошибка происходит в момент вызова метода?
И можете ещё указать версию компоненты и битность

**Comment by darujo** [comment]
Error occurred while accessing component property/method: GetDynamicContent.
Protobuf parse error: required fields missing: (cannot determine missing fields for lite message)
Error code: 0x80020009 CheckLoad c:\work15_0\utl\proc-diadoc.p (5890)
DiadocCom_5_29_13_573.dll 32битная

**Comment by GilimkhanovDenis** [comment]
Ошибка связана с тем, что в ответе сервиса появились новые значения перечисления, о которых компонента 5.29.13 не знает, и как следствие не может десериализовать ответ.

Решение: Обновить компоненту до актуальной

**Comment by darujo** [comment]
А как часто надо обновлять компоненту? И как это может сказаться на уже написанных обращениях к методам и проперти? Например  OrganizationId: в Document  не актуально и надо использовать OrganizationGuid, но я не нашел методов работающих с OrganizationGuid. Или метод  например Connection.GetOrganizationById(BoxID) работает как OrganizationId так и с OrganizationGuid?

**Comment by volodkindv** [comment]
@darujo Об изменениях в составе свойств или в методах мы пишем в [истории обновлений](http://1c-docs.diadoc.ru/ru/latest/History/History.html). Для удобства можно подписаться на [RSS](http://diadocsdk-1c.readthedocs.io/ru/latest/index.rss).
Об устаревших свойствах/методах также предупреждаем заранее. Например, [так](http://1c-docs.diadoc.ru/ru/latest/History/release_info/5_31_0.html?highlight=%D1%83%D1%81%D1%82%D0%B0%D1%80%D0%B5%D0%B2%D1%88%D0%B8%D0%BC#id1).

Как часто обновлять компоненту, должен решать интегратор. Например, если клиент работает только с неформализованными документами, то бОльшая часть изменений в компоненте на него не повлияет.
