### ISSUE TITLE
API. GetDocuments(). Как обратится к табличной части документа из списка?

### ISSUE THREAD

**Issue by komissarovev** [diadoc/diadocsdk-1c-docs#509]
Добрый день, Использую метод GetDocuments() Category = "UniversalTransferDocument.Inbound";
Получаю структуру документа с различными свойствами:
Document.DocumentNumber;
Document.Total;
Но не могу найти где хранится количество и цена?

**Comment by IrinaShmonina** [comment]
@komissarovev добрый день,
Необходимо получить контент электронного документа. 
См. методы "GetDynamicContent" ([для получения динамического представления контента](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html)) и "GetBase64Content"/"GetBase64ContentAsync" объекта [Document](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html) для получения XML-файла. 
Файл можно распарсить самостоятельно.

**Comment by komissarovev** [comment]
Подсткажите Document1 это объект документ? Как можно получить объект Document1?
DocumentList = DocumentsTask.GetDocuments();
Ц = 0;
Пока ц < DocumentList.Count Цикл
Document1 = DocumentList.GetItem(Ц);
dc= Document1.GetDynamicContent();

**Comment by kulakovskaya** [comment]
Добрый день!
1. Document1 - это объект документ?
_Да_
2. Как можно получить объект Document?
_Не совсем понятен вопрос. Расскажите, пожалуйста, подробнее с какой проблемой столкнулись._

**Comment by komissarovev** [comment]
Вот этот код у меня вызывает ошибку:
Произошла исключительная ситуация (DocumentBase.GetDynamicContent): Неверное значение перечисления

Пока ц < DocumentList.Count Цикл
Document1 = DocumentList.GetItem(Ц);
dc= Document1.GetDynamicContent();

**Comment by komissarovev** [comment]
Можете привести пример использования GetDynamicContent?

**Comment by acharushkin** [comment]
См. документацию к методу [Document.GetDynamicContent](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html?highlight=GetDynamicContent#Document.GetDynamicContent)
У вас не указано значение параметра DocFlowSide ("Seller" или "Buyer").
Должно быть так:
`Док = Document.GetDynamicContent("Seller");`

Более подробные примеры работы с динамическим контентом приведены в документации к объекту [DynamicContent](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html)

**Comment by komissarovev** [comment]
Спасибо.
