### ISSUE TITLE
Ошибка при работе с компонентой "5.9.0.154"

### ISSUE THREAD

**Issue by 7923655** [diadoc/diadocsdk-1c-docs#51]
При работе с компонентой периодически возникают дампы на сервере с падением рпхостов.
ошибка в мониторинге выглядит примерно так:
dumpLastModified = 20161205003738
excpModule = winhttp!WinHttpConnect+0x1e5 94680625 dumpName = rphost.exe.27196.dmp dumpSize = 2016879417 processName = rphost callStack = winhttp!WinHttpConnect+0x1e5
DiadocComApi1+0x20d738
DiadocComApi1+0x1c784d
DiadocComApi1+0x19d501
DiadocComApi1+0x2e0f9b
DiadocComApi1+0x2e234c
DiadocComApi1+0x2e1cfb
DiadocComApi1+0x2eacd1
DiadocComApi1+0x275e19
DiadocComApi1!DllUnregist...
PID = 27196

**Comment by denver069** [comment]
попробуйте обновить внешнюю компоненту до текущей версии 5.10.4.168
