### ISSUE TITLE
Выгрузка подписанных документов из системы diadoc на локальный компьютер

### ISSUE THREAD

**Issue by snapsik** [diadoc/diadocsdk-1c-docs#510]
Добрый день! 
Задача состоит в следующем: выгружать по расписанию подписанные документы из системы diadoc в папку на локальном компьютере. Выгрузка будет реализована средствами 1с. Есть ли возможность это делать через API ? Какие методы для этого использовать? 
В модуле диадок для 1с можно руками выгружать документы через кнопку Сохранить на диск. Но необходимо исключить выгрузку руками, вызывать процедуру, которая будет автоматически выгружать подписанные документы на диск.

**Comment by snapsik** [comment]
Этот метод- GenerateDocumentZip ? Есть знатоки? Тут живые чаты, кто знает?

**Comment by kulakovskaya** [comment]
Добрый день! Уточните, пожалуйста, конфигурацию и версию модуля Диадок 1С.

**Comment by snapsik** [comment]
> Добрый день! Уточните, пожалуйста, конфигурацию и версию модуля Диадок 1С.

Управление производственным предприятием, редакция 1.3 (1.3.36.1) 
Версия модуля Диадок 1с - 5.36.05.281

**Comment by snapsik** [comment]
> Добрый день! Уточните, пожалуйста, конфигурацию и версию модуля Диадок 1С.

Написал конфигурацию и версию модуля Диадок 1с. Это поможет решить вопрос? 
Типовой модуль Диадок имеет отдельные процедуры выгрузки документов на диск? Насколько я знаю, там в режиме диалога только можно выгрузить документы через кнопку -Сохранить на диск. Как вариант, переписывать процедуры модуля Диадок 1с... либо использовать API.  Сталкивались с необходимостью автоматической выгрузкой без всплывающих диалоговых окон и (выбора вручную документов, места сохранения и т.д.)?

**Comment by kulakovskaya** [comment]
Добрый день! Для выгрузки документов можно использовать методы компоненты, например SaveAllContent. Подробнее в [документации](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html?highlight=SaveAllContent#Document.SaveAllContent).
