### ISSUE TITLE
Получение данных о подписанте в неформализованных документах.

### ISSUE THREAD

**Issue by anat3446134** [diadoc/diadocsdk-1c-docs#511]
Здравтсвуйте.
  При использование метода GetSenderSignature() по неформализованному  документу данные отсутствуют.
 Подскажите возможно еще есть варианты получение данных о подписанте?

Работаем через ComОбъект( "Diadoc.DiadocClient") из 1с83.

**Comment by GilimkhanovDenis** [comment]
Добрый день.
Какую версию компоненты используете?
Дайте, пожалуйста, ссылку на документ, на котором воспроизводится

**Comment by anat3446134** [comment]
Проблема решилась.
Обновили версию компоненты до последней.
Спасибо.

  09.09.2020, 08:06, GilimkhanovDenis <notifications@github.com>

  Добрый день.
  Какую версию компоненты используете?
  Дайте, пожалуйста, ссылку на документ, на котором воспроизводится
