### ISSUE TITLE
Убрать нижнюю часть при выгрузке Формализованного Акта

### ISSUE THREAD

**Issue by JGhjfhgjkdh5486t** [diadoc/diadocsdk-1c-docs#512]
Добрый день. Версия 1С 7.7. Библиотека ДиаДок 5.29.13.573.
Возможно ли при отправке формализованного Акта (XmlAcceptanceCertificate552) и какими командами отключить появление / видимость строки Всего табличной части?
Аналогичный вопрос ниже по подписям - Всего оказано услуг на сумму... в том числе Ндс - возможно ли это убрать / заменить на свои строки / сумму ?

**Comment by volodkindv** [comment]
Добрый день.
Этот вопрос относится к работе модуля, а не внешней компоненты.
С вопросами по модулю вам лучше обратиться в техподдержку.
