### ISSUE TITLE
Выгрузка формализованного Акта 820 приказа 1С 7.7

### ISSUE THREAD

**Issue by JGhjfhgjkdh5486t** [diadoc/diadocsdk-1c-docs#513]
Добрый день. Версия 1С 7.7. Библиотека ДиаДок 5.29.13.573.
В документации к 1С http://1c-docs.diadoc.ru/ не нашел информации о заполнении / выгрузке документов по 820 приказу.
Конкретно нужна выгрузка формализованного Акта. Прошу, пожалуйста, направить.
В документации по sdk  есть информация, как работать с документами https://diadoc-sdk.readthedocs.io/ru/latest/howto/utd820.html.
Нам нужен формализованный Акт, и из 1С 7.7 стандартными средствами мы не выгружаем xml.
Прошу подсказки, и структуру, как это сделать. Либо может как в формализованном акте есть стандартная команда для выгрузки, как XmlAcceptanceCertificate552

**Comment by kulakovskaya** [comment]
Добрый день! В [документации](http://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html) есть пример, как сформировать и отправить документ.
