### ISSUE TITLE
Неверно подготавливается табличная часть УПД 820

### ISSUE THREAD

**Issue by Mazart** [diadoc/diadocsdk-1c-docs#514]
В модуле "Ядро" есть функция "ДополнитьСлужебнойИнформациейItem820", в которой таблица Items820 дополняется доп. свойствами (характеристика, серия, служебная информация и так далее). Проблема состоит в том, что там происходит соединение двух таблиц через отбор по номенклатуре и сумме, но по первой строке из результата отбора.
Ситуация, когда в документе есть несколько строк одинаковых позиций по номенклатуре, но отличающиеся этими доп. свойствами, приводят к тому, что они становятся абсолютна одинаковыми, а значит их дальнейшая обработка становится бесполезной, как и сама операция соединения. 
Итоговая xml от этого не страдает, но обработать результат в ПМ уже не получится. В нашем случае требуется для определённых контрагентов дополнить УПД доп. данными в разрезе номенклатур, для чего мною был откорректирован запрос формирования таблицы документа. Полученные данные были добавлены в "СлужебнаяИнформация" для обработки в ПМ, но из-за вышеописанной проблемы этого не получается сделать. 
Обидно, что запросы нельзя переопределить в ПМ, помнится в Диадок.EDI запросы вынесены в макеты и их можно было легко подредактировать при внедрении модуля в очень изменённые конфигурации, тут такого нет, хотя на память она (обработка) похожа на Диадок.Про
upd: 
Бухгалтерия предприятия, редакция 3.0 (3.0.77.106) 
Диадок.Про 4.1.0.476

**Comment by volodkindv** [comment]
Это поведение модуля исправляли в версии 4.1.16.
