### ISSUE TITLE
Работа с маркировкой

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#515]
Добрый день! Вводим маркировку товара. Раньше для отправки УПД использовали PackageSendTask2.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01_hyphen"); Теперь в документе должен вставать префикс ON_NSCHFDOPPRMARK. Как этого добиться?

**Comment by GuninaY** [comment]
И еще вопрос по таблице марок ItemIdentificationNumbers - там нет количества. Получается на каждую шт своя марка?

**Comment by kulakovskaya** [comment]
Добрый день! Если в контенте документа заполнены сведения по кодам маркировки, тогда в наименование автоматически встает префикс ON_NSCHFDOPPRMARK.

**Comment by kulakovskaya** [comment]
_И еще вопрос по таблице марок ItemIdentificationNumbers - там нет количества. Получается на каждую шт своя марка?_

Да, все верно. Количество кодов маркировки соответствует количеству товара по каждой позиции в документе.

**Comment by GuninaY** [comment]
Спасибо, все поняла
