### ISSUE TITLE
Отсутствует адрес покупателя у контрагентов ИП, работающих в роуминге.

### ISSUE THREAD

**Issue by codexa727** [diadoc/diadocsdk-1c-docs#517]
Добрый день!
По проблеме "Неверный идентификатор получателя в УПД #507" есть продолжение, но открыть ту задачу я больше не могу, поэтому напишу отдельно.
У всех контрагентов, являющихся ИП и работающих в роуминге, в адресе покупателя в документе указан только город, больше никаких данных нет. Каким образом можно решить эту проблему?

**Comment by IrinaShmonina** [comment]
@codexa727, добрый день,
подскажите, пожалуйста, boxid вашей организации

**Comment by codexa727** [comment]
BoxId: 86efecb9-3ada-4954-8b49-05f5cbf54962

**Comment by aeremina88** [comment]
Добрый день!
Вам нужно уточнить полный адрес у контрагента и указывать при формировании УПД.

**Comment by codexa727** [comment]
Ну приехали... 
Вы точно предыдущую тему читали??
Ответ Вашей коллеги:

kulakovskaya commented on 24 Aug
Добрый день!
Если Вы указали BoxId контрагента, то OrgName, Inn, Kpp, Address, FnsParticipantId уже не нужно указывать в контенте.
Тогда ИдПол заполнится корректно.

**Comment by aeremina88** [comment]
Всё верно. Если указать BoxId, то подтянутся данные, которые по контрагенту в Диадоке. Но в случае роумингового контрагента у нас может не быть полной информации (не все поля адреса заполнены). В таком случае надежнее заполнить поля OrgName, Inn, Kpp, Address, FnsParticipantId вручную, а BoxId при этом не указывать. 

Со своей стороны попробуем актуализировать информацию об адресе ваших роуминговых контрагентах, сделаем запрос к операторам. Но это займет время, поэтому рекомендую пока заполнять вручную.

**Comment by codexa727** [comment]
"kulakovskaya commented on 25 Aug
Добрый день! Вместо перечисленных реквизитов выше вам необходимо заполнить Buyer.OrganizationReference.BoxId или Buyer.OrganizationDetails.FnsParticipantId."
Если я правильно помню, когда указывается FnsParticipantId, то адрес не заполняется вручную и не передается, как и в случае с BoxID.   
BoxID единственный, по-моему, способ идентифицировать получателя, когда у него несколько роуминговых подключений. В этом случае заполнять OrgName, Inn, Kpp, Address вручную совсем не вариант.

**Comment by NataliaShumikhina** [comment]
Добрый день. Мы сделали запрос роуминговым операторам, чтобы уточнить адреса ваших контрагентов. Операторы не смогли предоставить нам данные по всем контрагентам. Поэтому такие ситуации вам придется учесть в вашем интеграционном решении. Если у нас в системе есть адрес роумингового контрагента, то мы его, конечно, подтянем по boxid. Если адреса нет, то вам придется заполнить его вручную.

**Comment by codexa727** [comment]
Добрый день. Судя по тому, что я вижу в списке контрагентов, ни по каким контрагентам операторы не смогли предоставить данные. Давайте уж будем говорить как есть.

Ок, если мне нужно будет заполнять адрес контрагента вручную, то тогда поясните, пожалуйста, как это делать таким образом, чтобы не получать ошибку, описанную вот здесь https://github.com/diadoc/diadocsdk-1c-docs/issues/507
Итог разбора той ошибки  - нельзя заполнять BoxId и адрес контрагента одновременно.
А то получается, что при заполнении адреса вручную одна ошибка, а при незаполнении - другая.

**Comment by aeremina88** [comment]
Добрый день!
Ранее Вы писали: 

> Если я правильно помню, когда указывается FnsParticipantId, то адрес не заполняется вручную и не передается, как и в случае с BoxID. BoxID единственный, по-моему, способ идентифицировать получателя, когда у него несколько роуминговых подключений.

Это не так. По FnsParticipantId получатель с несколькими роуминговыми подключениями определится однозначно. 
Если заполните FnsParticipantId, то нужно будет вручную заполнить OrgName, Inn, Kpp, Address.

**Comment by codexa727** [comment]
А с помощью какого метода можно получить контрагента по FnsParticipantId?

**Comment by volodkindv** [comment]
В компоненте 1С нет возможности получить контрагента по FnsParticipantId.
Но если у вас уже есть на руках BoxId, то можно получить это значение из [Counteragent](http://1c-docs.diadoc.ru/ru/latest/ComObjects/Counteragent.html?highlight=FnsParticipantId)

**Comment by codexa727** [comment]
Добрый день!
Заполняю FnsParticipantId, OrgName, Inn, Kpp, Address. Документы выгружаются, всё отлично.
Сейчас пришел запрос от контрагента на уточнение документа со следующей причиной "Неверно указана утверждающая организация". Контрагент работает в роуминге. 
И вот вопрос, куда собственно копать? Это проблема оператора контрагента? Или есть какое-то поле типа ИдПол, которое заполняется неявно и сейчас заполняется неверно?

**Comment by volodkindv** [comment]
Добрый день.
Надо связаться с контрагентом. Спросить, какие именно поля в документе он считает неправильно указанными.
