### ISSUE TITLE
Ошибка при подписании докуметов.

### ISSUE THREAD

**Issue by ElenaBurnasheva** [diadoc/diadocsdk-1c-docs#518]
Здравствуйте! 
Есть следующий код: Document=Organization.GetDocumentById(ДокИд); //выполняется для ДокИд =3700b79e-dca8-4fd1-a042-1fbd07901c5b6cd62610-a593-4653-b3db-f3dc59e83306
//проверяю статус Document.Status= InboundNotFinished
SendTask = Document.CreateReplySendTask2("AcceptDocument");
//проверяю количество SendTask.ContentItems.Count= 0
После этого захожу на сайт и нахожу искомый документ 
![image](https://user-images.githubusercontent.com/72372519/95049963-708c6200-06f3-11eb-8cc4-92a78c10b443.png)
Выполняю код еще раз и SendTask.ContentItems.Count>0, все отрабатывает и документ подписывается.
![image](https://user-images.githubusercontent.com/72372519/95050266-eb557d00-06f3-11eb-9e9a-c4302ac23520.png)

Почему в первый запуск SendTask.ContentItems.Count= 0? И как этого избежать в дальнейшем?

**Comment by volodkindv** [comment]
Добрый день!
Вот список возможных статусов документов: http://1c-docs.diadoc.ru/ru/latest/ComObjects/Enums/UTDStatus.html?highlight=InboundNotFinished#utdstatus

Статус "InboundNotFinished" обычно относится к счетам-фактурам и означает, что по данному документу не сформировано извещение о получении. Подпись счета-фактуры не требуется, поэтому в ReplySendTask2 и не добавляется ContentItem.

На приложенном вами скриншоте - Накладная. У накладных без подписи покупателя будет статус "InboundWaitingForRecipientSignature", и для них в ReplySendTask2 должен добавиться титул покупателя.

Проверьте: возможно, вы смотрите разные документы.
