### ISSUE TITLE
Как получить черновики?

### ISSUE THREAD

**Issue by ktibo** [diadoc/diadocsdk-1c-docs#519]
Добрый день! Есть ли какой-то инструмент для получения списка документов-черновиков по какому-либо отбору? Использовал Organization.GetDocumentsTask().GetDocuments() с разными параметрами, но черновики не возвращаются. По id конкретный документ-черновик получить можно.
Использую внешнюю компоненту Diadoc_5_31_2_611 (x32).

**Comment by kulakovskaya** [comment]
Добрый день! Во внешней компоненте нет метода для получения списка черновиков. Получить черновик можно только по идентификатору. Также, если черновик отправлялся с помощью PackageSendTask2, можно получить объект черновика.

**Comment by ktibo** [comment]
Спасибо
