### ISSUE TITLE
ошибка при вызове ДиадокАПИ.CreateConnectionByCertificate

### ISSUE THREAD

**Issue by vgrichuk** [diadoc/diadocsdk-1c-docs#52]
Здравствуйте,
при выполнении кода:
```
	ДиадокАпи = Новый ComОбъект("Diadoc.DiadocClient");

	//Задаем параметры подлючения к серверу
	ДиадокАпи.ApiClientId = "vgrichuk-дальше_цифирьки_буковки";
	ДиадокАпи.ServerUrl   = "https://diadoc-api.kontur.ru:443";

  	//Получение списка сертификатов
  	Certificates = ДиадокАПИ.GetPersonalCertificates();
  	Если Certificates.Count() > 0 Тогда

    	Thumbprint = Certificates.GetItem(0).Thumbprint;
    	ДиадокСоединение = ДиадокАПИ.CreateConnectionByCertificate(Thumbprint);

```
получаю ошибку: 
{ВнешняяОбработка.РаботаСДиаДок.Форма.Форма.Форма(23)}: Ошибка при вызове метода контекста (CreateConnectionByCertificate)
    ДиадокСоединение = ДиадокАПИ.CreateConnectionByCertificate(Thumbprint);
по причине:
Произошла исключительная ситуация (DiadocApiInvoiceApi.CreateConnectionByCertificate): ##100[Ошибка сервера Диадок]code:401, HTTP error: Invalid API client id

Предполагаю, что у меня не привязаны сертификаты организаций. Если это так, то каков процесс их формирования пока идет разработка?

**Comment by denver069** [comment]
Ошибка "Invalid API client id" - значит что вы указываете не корректный ключ разработчика в поле ДиадокАпи.ApiClientId.

**Comment by vgrichuk** [comment]
ключ разработчика получен вчера из СКБ Контур по запросу 11577605

**Comment by LyubovZykova** [comment]
Добрый день! Проблема была в некорректно сформировавшемся ключе разработчика, вам в почту будет выслан новый ключ.
