### ISSUE TITLE
Ошибка ##300 при подписывании документов по api

### ISSUE THREAD

**Issue by mpei0504** [diadoc/diadocsdk-1c-docs#520]
Добрый день.

При попытке подписать акт по апи из 1с возникает ошибка: Произошла исключительная ситуация (ReplySendTask2.Send): ##300[Ошибка CryptoPro]Ошибка при подписывании данных [1627:Ошибка исполнения функции.]

Код:
SignerReference =ReplySendTask.ContentItems.getItem(0).Content.UniversalTransferDocumentBuyerTitle.Signers.AddItems().SignerReference
UTD = ReplySendTask.ContentItems.getItem(0).Content.UniversalTransferDocumentBuyerTitle;
SignerReference.BoxId = Organization.Id;
SignerReference.CertificateThumbprint = Thumbprint;
UTD.DocumentCreator = "DiadocCreator";
UTD.OperationContent = "OperationContent";
ReplySendTask.Send();

В чем может быть причина?

**Comment by kulakovskaya** [comment]
Добрый день! Ошибка связана с КриптоПро. Попробуйте воспользоваться рекомендациями из https://ca.kontur.ru/faq/teh/oshibka-ecp.
