### ISSUE TITLE
Метод GetDocumentEventList

### ISSUE THREAD

**Issue by KimAnton1984** [diadoc/diadocsdk-1c-docs#521]
Доброго дня, для интеграции используем внешнюю компоненту AddInDiadocAPI.DLL
Читаем ленту событий ЛК через метод GetDocumentEventList объекта Оrganization. Что бы получать текущие события приходится читать ленту со дня образования ЛК. Вопрос можно каким то образом получить актуальный параметр EventId что бы не вычитывать ленту событий за прошлые периоды. Спасибо

**Comment by kulakovskaya** [comment]
Добрый день! На текущий момент в компоненте нет метода, который бы возвращал актуальный EventId. На уровне HTTP API Диадока есть возможность получить последнее событие в ящике. Подробнее в [документации](https://api-docs.diadoc.ru/ru/latest/http/GetLastEvent.html).
