### ISSUE TITLE
1c-com-Diadoc DataTask Help

### ISSUE THREAD

**Issue by Sergey279** [diadoc/diadocsdk-1c-docs#522]
Добрый вечер. 
Столкнулся с объектом **DataTask** 
Первоначально записываю в связки:

GUID_1C=ID_Diadoc
ID_Diadoc=GUID_1C   //обратную пару. 

и т.к. в 1с документов больше 1шт может быть, а обратная пара всегда 1 пара 
то и GUID по ID я всегда получу в единственном числе. 

**Вопрос:** как извлечь полный массив Key-Value из хранилища , не используя перебора ?

**Comment by kulakovskaya** [comment]
Здравствуйте! В компоненте нет возможности получить все Key-Value из хранилища, которые есть в ящике организации.

**Comment by Sergey279** [comment]
Добрый день. 
Реализовал через локальное внешнее хранилище. Чтоб две базы с одинаковыми GUID документами. могли статусы документов наблюдать. Например в БП базе видны статусы, хотя работа с Диадок производилась в УТ.
DataTask - очень затратный по времени получился. с оптимизировать не удалось.

В общем, я локально выкрутился, а в копилку Инфостар_сообщества из-за использования левых SQL баз выложить нечего =(
