### ISSUE TITLE
Как отправить документ и потребовать, чтобы контрагент его подписал?

### ISSUE THREAD

**Issue by averyanovalex** [diadoc/diadocsdk-1c-docs#523]
Добрый день!
Хотим отправить неформализованный документ и потребовать, чтобы контрагент его обязательно подписал. 
Делаем вот так:

    // Добавление неформализованного документа
    Third_DocumentToSend = SendTask.AddDocumentFromFile("Nonformalized", "default", "v1", "С:\\Документ.pdf");
    Third_DocumentToSend.Comment = "Это неформализованный документ";
    MetaDataItem = Third_DocumentToSend.AddMetadata();
    MetaDataItem.Key   = "FileName";
    MetaDataItem.Value = "Имя Файла Для Передачи.xml";

    ОтправленныеДокументы = SendTask.Send();

Но документ в Диадок получает статус "Документооборот завершен". И не подразумевает обязательной подписи.

В документации нашли объект ResolutionRequestTask и пример:

    Document = Organization.GetDocumentById(ИдентификаторДокумента)
    ResolutionRequestTask = Document.CreateResolutionRequestTask();

    // ResolutionRequestType определяет будет ли это запрос на согласование или передача на подпись
    // В данном случае - передача на подпись
    ResolutionRequestTask.ResolutionRequestType = "SignatureRequest";
    ResolutionRequestTask.TargetDepartmentId    = ИдентификаторПодразделения;

    ResolutionRequestTask.Send();

Но, учитывая, что здесь есть только атрибуты TargetDepartmentId    и  TargetUserId и нет ничего про контрагента, это используются для подписи на нашей стороне.

А как нам потребовать обязательную подпись со стороны контрагента?

**Comment by volodkindv** [comment]
Добрый день!
При отправке надо установить флаг [NeedRecipientSignature](https://1c-docs.diadoc.ru/ru/latest/ComObjects/CustomDocumentToSend.html?highlight=needrecipientsignature).

```
Third_DocumentToSend = SendTask.AddDocumentFromFile("Nonformalized", "default", "v1", "С:\\Документ.pdf");
Third_DocumentToSend.Comment = "Это неформализованный документ";
Third_DocumentToSend.NeedRecipientSignature= Истина;
```

**Comment by averyanovalex** [comment]
Как все просто. Спасибо!
