### ISSUE TITLE
Свойство объекта BoxEvent DocumentDirection

### ISSUE THREAD

**Issue by NatalyaNoskova** [diadoc/diadocsdk-1c-docs#524]
Добрый день!
Использую COM (32) библиотеку DiadocCom_5_31_2_611.
Снимая события, хочу обрабатывать информацию только об исходящих от нас документах. 
Скажите, свойство BoxEvent'a DocumentDirection как-то согласовано со свойством Direction самого документа, получаемого по GetDocument() из этого самого бокса? А то по DocumentDirection  у меня идет сплошной "Inbound", а по Direction из документа и "Inbound" и "Outbound". Рассматривается 2 контрагента, один нам прислал, другому мы отправляли. Не хотелось бы лезть в сами документы, думала отсечь на уровне события.

**Comment by GilimkhanovDenis** [comment]
Это баг. исправим в ближайшем релизе

**Comment by GilimkhanovDenis** [comment]
Выпустили компоненту 5.32.0 - обновитесь до неё
