### ISSUE TITLE
Выгрузка из 1с ут 10.3

### ISSUE THREAD

**Issue by 010Bit** [diadoc/diadocsdk-1c-docs#525]
Доброго времени суток, есть очень старая версия 1с ут 10.3, в ней удалось через правки обработки организовать работу Вашего модуля. Теперь есть необходимость, заполнять поля(как документа так и табличной части) торг12 при отправке к Вам на сайт отличными от типовых данными. В каком модуле это можно сделать?

**Comment by 010Bit** [comment]
Как найти boxld не знаю) наш инн 231 1180215

**Comment by volodkindv** [comment]
Здравствуйте.
О каком именно модуле идет речь? (нужна точная версия).

**Comment by volodkindv** [comment]
boxid пока не нужен, но вообще его можно посмотреть в браузере:

![image](https://user-images.githubusercontent.com/12305552/96695176-ca9f4f80-13a2-11eb-815f-987444b012d1.png)

**Comment by 010Bit** [comment]
![image](https://user-images.githubusercontent.com/73169242/96702275-4517a180-139a-11eb-9160-86e3372f082d.png)
123e1301-a911-4d57-ba2d-6c328012f28b

**Comment by volodkindv** [comment]
Попробуйте настроить подключаемый модуль (ПМ). [Здесь](https://wiki.diadoc.ru/pages/viewpage.action?pageId=7668190) описано, что это такое.
Можно получить шаблон ПМ так: в обработке зайдите в раздел "Настройки" - "Подключаемый модуль" - "Сохранить шаблон подключаемого модуля на диск". Откройте шаблон ПМ и посмотрите пример кода в событии "ПослеЗаполненияКонтента".

**Comment by 010Bit** [comment]
Спасибо, посмотрю, отпишусь

**Comment by 010Bit** [comment]
Спасибо, вроде то, что нужно

**Comment by 010Bit** [comment]
Доброго времени суток, всё же не всё (
Изменения адреса грузоотправителя сделал, но при выгрузке на сайт(личный кабинет) виден старый адрес, а не новый. Код ниже:
			Грузоотправитель.Address.CountryCode=643;
			Грузоотправитель.Address.IsForeign = истина;
			Грузоотправитель.Address.AddressText = Выборка.ЮридическийАдрес

и ещё вопрос, эта настройка("использовать подключаемый модуль") у всех пользователей сохранится? работа ведётся через rdp с 1с

**Comment by volodkindv** [comment]
Настройка "Использовать подключаемый модуль" и адрес ПМ сохранится у всех пользователей.
Но стоит обратить внимание, что указанный файл должен быть доступен у всех пользователей базы. В идеале - общедоступный сетевой путь, или загрузить ПМ в справочник "Внешние обработки", чтобы уж точно. Расположение ПМ на диске обычно используется для отладки.

Про адрес в рамках этого обсуждения сложно что-либо сказать: нужен пример документа, код из ПМ и отладка на вашей базе. С этим лучше обратиться в техподдержку.
