### ISSUE TITLE
Вопрос про EventType

### ISSUE THREAD

**Issue by IlyaGlyzin** [diadoc/diadocsdk-1c-docs#526]
Confirmation - Извещение о получении документа
New - новый документооборот

Почему  для Inbound UniversalTransferDocument нет события New но оно есть для NonformalizedProforma и других?
В чем отличие Confirmation и New тогда не пойму?

**Comment by IlyaGlyzin** [comment]
уточню что список событий я получаю через AddIn DiaDoc API

**Comment by GilimkhanovDenis** [comment]
Для данного документа список событий выглядит так
![image](https://user-images.githubusercontent.com/34439383/96707089-dc87ef00-13b0-11eb-80d9-67e677d712cb.png)

1 New + 5 Confirmation

New - для поступления документа
Confirmation - для различных извещений о получении (см. [Документооборот УПД](https://api-docs.diadoc.ru/ru/latest/docflows/UtdDocflow.html#id5))

Если у вас нет события New, то укажите, пожалуйста,
1) EventId, начиная с которого вы вычитываете блок событий и не получаете событие New
2) Версию компоненты и её вбитность

**Comment by IlyaGlyzin** [comment]
все разобрался , по вашему скрину  у них EventID один и тот же, как же так? у меня затирает последний

**Comment by IlyaGlyzin** [comment]
и время одинаковое и как мне их различать тогда

**Comment by IlyaGlyzin** [comment]
спасибо за информацию

**Comment by GilimkhanovDenis** [comment]
Да. в ленте событий компоненты с одним идентификатором может быть несколько событий. Из хорошего - события с одним идентификатором идут друг за другом.

Насколько я понял, вопрос решён

**Comment by IlyaGlyzin** [comment]
да
