### ISSUE TITLE
Возникла проблема с получением токена авторизации при подключении по HTTP из 1С 8.1 и 8.3.

### ISSUE THREAD

**Issue by Sullawsw** [diadoc/diadocsdk-1c-docs#527]
После выполнения метода /V3/Authenticate?type=certificate  получаю зашифрованный ответ и согласно API  мне необходимо его расшифровать тем же сертификатом , затем преобразовать в  Base64 и полученную строку использовать в качестве ddauth_token при авторизации для любых последующих действий.

Попытка
                               Соединение =  Новый HTTPСоединение("https://diadoc-api.kontur.ru",,,,,,Новый ЗащищенноеСоединениеOpenSSL(),Ложь);
                Исключение
                               Сообщить("Не удалось установить соединение с сервером онлайн-проверки:" 
                               + Символы.ПС + ИнформацияОбОшибке().Описание, СтатусСообщения.Важное);
                               Возврат;
                КонецПопытки;
                
                //Тело POST-запроса
                имяФайлаСертификата = "d:/xxxxxxxxxxxxxxxxxxxx/yyyyyyyyyy.cer";
                
                ВремКаталог = "c:\Users\...\AppData\Local\Temp\66ac670b-f9b9-11ea-9441-00155d27324d";
                ИмяФайлаВыходЗапросаВыгрузкиДок = ВремКаталог + "\UploadDocResult83.txt";

                ТекстЗапросаФайл = Новый ТекстовыйДокумент;
                ТекстЗапросаФайл.Прочитать(имяФайлаСертификата, "windows-1251");
                ТелоPOSTЗапроса = ТекстЗапросаФайл.ПолучитьТекст();
                
                ФайлСертификата = Новый ДвоичныеДанные(имяФайлаСертификата);
                СодержимоеФайла = XMLСтрока(ФайлСертификата);

                Заголовки = Новый Соответствие();    
                Заголовки.Вставить("Authorization", "DiadocAuth ddauth_api_client_id=test-diadoc-api-ххххххххххххххххххххххххххх");
                Заголовки.Вставить("Content-Type", "application/octet-stream"); //
                Заголовки.Вставить("Content-Length", Формат(СтрДлина(СодержимоеФайла),"ЧЦ=; ЧГ=")); //
                
                HTTPЗапрос = Новый HTTPЗапрос("/V3/Authenticate?type=certificate", Заголовки);
                HTTPЗапрос.УстановитьТелоИзСтроки(СодержимоеФайла, "windows-1251", ИспользованиеByteOrderMark.НеИспользовать);
                
                Результат  = Соединение.ОтправитьДляОбработки(HTTPЗапрос, ИмяФайлаВыходЗапросаВыгрузкиДок );
                

                МенеджерКриптографии  = НОвый МенеджерКриптографии("Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider", "", 80);
                МенеджерКриптографии.ПарольДоступаКЗакрытомуКлючу = "1";
                ФайлТокенаДляРасшифровки = Новый ДвоичныеДанные(ИмяФайлаВыходЗапросаВыгрузкиДок);
                ТокенРасшифрован = МенеджерКриптографии.Расшифровать(ИмяФайлаВыходЗапросаВыгрузкиДок);
                Сообщить("ТокенРасшифрован: " + ТокенРасшифрован);
                Токен = УбратьСимволы1013(ПолучитьBase64СтрокуИзДвоичныхДанных(ТокенРасшифрован)); 
                Сообщить("Токен: " + Токен);
                ЗаголовокHTTP = Новый Соответствие();
                ЗаголовокHTTP.Вставить("Authorization", "DiadocAuth ddauth_api_client_id=test-diadoc-api-xxxxxxxxxxxxxxxxxxxxxxxx, ddauth_token=" + Токен);

                ИмяФайлВыходАутентификация = ВремКаталог + "\" + "AuthResult83.txt";

                HTTPЗапрос = Новый HTTPЗапрос("/GetMyOrganizations?autoRegister=false", ЗаголовокHTTP);
                Результат  = Соединение.Получить(HTTPЗапрос,ИмяФайлВыходАутентификация);
                
                Сообщить("Код состояния " + Результат.КодСостояния + ".");

И ответы с промежуточными значениями после запроса /GetMyOrganizations?autoRegister=false:

ТокенРасшифрован: F2 A2 C1 A0 E4 9A 55 6C 3C 70 3F BD F0 E9 24 EA FE 96 5F 08 5B 33 BB C1 F6 06 5C 13 98 DA 99 68 4A AA 2A CE 6D C6 07 66 FC 40 31 BF F1 F8 C1 CC FC D7 FF 50 65 C6 B1 EC A0 C0 9A 96 1D 97 BF DE 9F A7 9D 63 84 C7 D4 09 66 97 F1 3A 3F BC 45 B8 28 A4 50 17 E2 AF 61 B5 F1 1A A9 9B C8 D4 58 49 F7 64 EF 50 9C FE 34 DB FD C3 F3 F2 35 FE 07 59 F7 E2 28 66 A8 95 6D 41 86 FC 8A E0 A4 62 89 70 3A 1E F6 94 D9 2F DF CE CB 6D 65 62 D9 C3 EC 34 6A 90 5E 25 ED BE 63 02 27 6E 2D D0 55 34 F0 19 04 5E 86 51 F1 4A 36 E7 DC 42 F2 C9 13 9B 3C 83 D5 7F 8F D3 57 A1 A5 4B C8 31 D6 D1 6B 7A A3 0B EB FE 06 E7 EC E6 D7 9D 59 1C BA 85 C9 FE BD 5B 6B C0 40 05 41 70 62 59 26 0A 0B F9 36 7D 37 5D 3E 96 80 0F F3 B6 CA ED 59 CA 1E 99 37 E0 68 93 BE EB 0D A6 FE F5 97 BB 77 58 CB 19 8D 28 80 73
Токен: 8qLBoOSaVWw8cD+98Okk6v6WXwhbM7vB9gZcE5jamWhKqirObcYHZvxAMb/x+MHM/Nf/UGXGseygwJqWHZe/3p+nnWOEx9QJZpfxOj+8RbgopFAX4q9htfEaqZvI1FhJ92TvUJz+NNv9w/PyNf4HWffiKGaolW1BhvyK4KRiiXA6HvaU2S/fzsttZWLZw+w0apBeJe2+YwInbi3QVTTwGQRehlHxSjbn3ELyyRObPIPVf4/TV6GlS8gx1tFreqML6/4G5+zm151ZHLqFyf69W2vAQAVBcGJZJgoL+TZ9N10+loAP87bK7VnKHpk34GiTvusNpv71l7t3WMsZjSiAcw==

Код состояния 401. Invalid auth token

Подскажите, в чем ошибка расшифровки/кодирования?  Возможно я использую не те методы или где то не указываю нужные форматы...

**Comment by volodkindv** [comment]
Добрый день.
Возможно, что-то ломается в этих функциях:
УбратьСимволы1013
ПолучитьBase64СтрокуИзДвоичныхДанных

Мы делаем примерно так:
```
            
            ФайлСертификата = Новый ДвоичныеДанные(имяФайлаСертификата);
            СодержимоеФайла = XMLСтрока(ФайлСертификата);

            Заголовки = Новый Соответствие();    
            Заголовки.Вставить("Authorization", "DiadocAuth ddauth_api_client_id=test-diadoc-api-ххххххххххххххххххххххххххх");
//            Заголовки.Вставить("Content-Type", "application/octet-stream");
            Заголовки.Вставить("Content-Type", "application/json;charset=utf-8");  // обычно работаем в JSON, UTF-8
            Заголовки.Вставить("Accept", "application/json");   // и обратно тоже ждем JSON
//            Заголовки.Вставить("Content-Length", Формат(СтрДлина(СодержимоеФайла),"ЧЦ=; ЧГ=")); // это не нужно
            
            HTTPЗапрос = Новый HTTPЗапрос("/V3/Authenticate?type=certificate", Заголовки);
//            HTTPЗапрос.УстановитьТелоИзСтроки(СодержимоеФайла, "windows-1251", ИспользованиеByteOrderMark.НеИспользовать); 
            HTTPЗапрос.УстановитьТелоИзДвоичныхДанных(ФайлСертификата);   // вместо строки сразу гоняем ДвоичныеДанные

            Результат  = Соединение.ОтправитьДляОбработки(HTTPЗапрос, ИмяФайлаВыходЗапросаВыгрузкиДок );

.........
            ТокенРасшифрован = МенеджерКриптографии.Расшифровать(ИмяФайлаВыходЗапросаВыгрузкиДок);
            Сообщить("ТокенРасшифрован: " + ТокенРасшифрован);


//            Токен = УбратьСимволы1013(ПолучитьBase64СтрокуИзДвоичныхДанных(ТокенРасшифрован)); 
            Токен = Base64Строка(Токен );
            Токен = СтрЗаменить(Токен , Символы.ВК, "");
            Токен = СтрЗаменить(Токен , Символы.ПС, "");

            Сообщить("Токен: " + Токен);
```

**Comment by Sullawsw** [comment]
> Добрый день.
> Возможно, что-то ломается в этих функциях:
> УбратьСимволы1013
> ПолучитьBase64СтрокуИзДвоичныхДанных
> 
> Мы делаем примерно так:
> 
> ```
>             
>             ФайлСертификата = Новый ДвоичныеДанные(имяФайлаСертификата);
>             СодержимоеФайла = XMLСтрока(ФайлСертификата);
> 
>             Заголовки = Новый Соответствие();    
>             Заголовки.Вставить("Authorization", "DiadocAuth ddauth_api_client_id=test-diadoc-api-ххххххххххххххххххххххххххх");
> //            Заголовки.Вставить("Content-Type", "application/octet-stream");
>             Заголовки.Вставить("Content-Type", "application/json;charset=utf-8");  // обычно работаем в JSON, UTF-8
>             Заголовки.Вставить("Accept", "application/json");   // и обратно тоже ждем JSON
> //            Заголовки.Вставить("Content-Length", Формат(СтрДлина(СодержимоеФайла),"ЧЦ=; ЧГ=")); // это не нужно
>             
>             HTTPЗапрос = Новый HTTPЗапрос("/V3/Authenticate?type=certificate", Заголовки);
> //            HTTPЗапрос.УстановитьТелоИзСтроки(СодержимоеФайла, "windows-1251", ИспользованиеByteOrderMark.НеИспользовать); 
>             HTTPЗапрос.УстановитьТелоИзДвоичныхДанных(ФайлСертификата);   // вместо строки сразу гоняем ДвоичныеДанные
> 
>             Результат  = Соединение.ОтправитьДляОбработки(HTTPЗапрос, ИмяФайлаВыходЗапросаВыгрузкиДок );
> 
> .........
>             ТокенРасшифрован = МенеджерКриптографии.Расшифровать(ИмяФайлаВыходЗапросаВыгрузкиДок);
>             Сообщить("ТокенРасшифрован: " + ТокенРасшифрован);
> 
> 
> //            Токен = УбратьСимволы1013(ПолучитьBase64СтрокуИзДвоичныхДанных(ТокенРасшифрован)); 
>             Токен = Base64Строка(Токен );
>             Токен = СтрЗаменить(Токен , Символы.ВК, "");
>             Токен = СтрЗаменить(Токен , Символы.ПС, "");
> 
>             Сообщить("Токен: " + Токен);
> ```

Спасибо за ответ, но к сожалению не помогло.
Без строки 
Заголовки.Вставить("Content-Type", "application/octet-stream"); // 
вообще не работает,  возвращает не правильный вид запроса.

Результат расшифровки и преобразования по Вашему методу дал визуально схожий с моим результат, в прочем он так же не прошел дальше.

**Comment by volodkindv** [comment]
Тут сложно что-либо сказать.
В 8.1 это почти наверняка работать не будет. В 8.3 - должно.
Странно, что у вас не проходит 
`            Заголовки.Вставить("Content-Type", "application/octet-stream");`
вместо
`            Заголовки.Вставить("Content-Type", "application/json;charset=utf-8");`
Какая точная версия платформы и режим совместимости?

**Comment by Sullawsw** [comment]
Проблема решилась до безобразия просто - "/V3/Authenticate?type=certificate"  использовать нельзя. Нужно использовать -"/Authenticate?type=certificate". 
Вот такой вот финт ушами от разработчиков.

**Comment by GilimkhanovDenis** [comment]
> Проблема решилась до безобразия просто - "/V3/Authenticate?type=certificate" использовать нельзя. Нужно использовать -"/Authenticate?type=certificate".
> Вот такой вот финт ушами от разработчиков.

Кажется, в варианте с V3/Authenticate Вы не вызывали метод [AuthenticateConfirm](https://api-docs.diadoc.ru/ru/latest/http/AuthenticateConfirm.html) после расшифровки токена

**Comment by Sullawsw** [comment]
> > Проблема решилась до безобразия просто - "/V3/Authenticate?type=certificate" использовать нельзя. Нужно использовать -"/Authenticate?type=certificate".
> > Вот такой вот финт ушами от разработчиков.
> 
> Кажется, в варианте с V3/Authenticate Вы не вызывали метод [AuthenticateConfirm](https://api-docs.diadoc.ru/ru/latest/http/AuthenticateConfirm.html) после расшифровки токена

Я пробовал вызывать метод AuthenticateConfirm и в v3  и во всех иных вариантах, типа V3/AuthenticateConfirm или  V2/AuthenticateConfirm или  /AuthenticateConfir,  он всегда возвращает ошибку то 400 то 501. 
Но в формате "/Authenticate?type=certificate" полученный и расшифрованный токен подошел для метода GetMyOrganizations и вернул верный ответ в формате JSON.
Надеюсь и для других методов подойдет. 
А AuthenticateConfirm  так и не работает ни в каком варианте.
