### ISSUE TITLE
Статус маркировки в API для 1с

### ISSUE THREAD

**Issue by KrykovLev** [diadoc/diadocsdk-1c-docs#529]
Добрый день
как можно получить статус маркировки в ГИС МТ в API для 1с ?

![image](https://user-images.githubusercontent.com/59161074/96882728-4626fc80-1488-11eb-9761-52300cdaabb4.png)

**Comment by IrinaShmonina** [comment]
@KrykovLev, добрый день.
В компоненте статусы маркировки добавлены в версии [5.32.0](https://1c-docs.diadoc.ru/ru/latest/History/release_info/5_32_0.html). Добавлен объект для работы со статусами - [ExternalStatus](https://1c-docs.diadoc.ru/ru/latest/ComObjects/ExternalStatus.html#externalstatus)

**Comment by KrykovLev** [comment]
Не пойму - как им пользоваться?

**Comment by KrykovLev** [comment]
Нашел Document.GetExternalStatuses(), спасибо!
