### ISSUE TITLE
Ошибка при вызове метода "CreateReplySendTask"

### ISSUE THREAD

**Issue by Alex463** [diadoc/diadocsdk-1c-docs#53]
Добрый вечер!
Версия компоненты 5_7_3_137. Клиент x64.
При вызове метода CreateReplySendTask объекта Document возникает следующая ошибка - "Ошибка при вызове метода контекста (CreateReplySendTask): Произошла исключительная ситуация (DocumentBase.CreateReplySendTask): Нет документов, для которых возможно формирование ответного задания выбранного типа."
Скриншот объекта Document.
![default](https://cloud.githubusercontent.com/assets/24681242/21358132/322024f2-c6f1-11e6-8237-a9158abc2873.png)

код получения объекта:
ЭД = DiadocConnection.GetOrganizationById(ИДОрганизации).GetDocumentById(ИДДокумента);
				
А в личном кабинете эта функция доступна (подпись документа)
Вопрос: Как подписать данный документ через 1с?

**Comment by volodkindv** [comment]
Добрый день!
Обратите внимание на поле "ЭД.status": он не предполагает ответной подписи.
Для неформализованных документов требование ответной подписи устанавливается в момент отправки. Т.е. вы можете отправить один за другим 2 неформализованных документа, в одном запросить ответную подпись, в другом - не запрашивать.
Похоже, что конкретный документ, приведенный на скриншоте, подписи не требует.

**Comment by Alex463** [comment]
Добрый день! по статусу согласен (поле ЭД.status). Но пользователь в ЛК(личном кабинете) видит, что он может подписать этот документ (есть кнопочка "подписать"). Поэтому решил уточнить этот вопрос. Хорошо, скажу тогда, что это ошибка в личном кабинете, по факту документ не требует подписи.
