### ISSUE TITLE
Свойство объекта Document   TypeNamedId

### ISSUE THREAD

**Issue by NatalyaNoskova** [diadoc/diadocsdk-1c-docs#530]
Уважаемые разработчики!
Имеется исходящий документ (акт), отправленный в pdf c xml составляющей из стандартной web формы Диадока.
Свойства документа по GetDocumentById("blalblabla", false):
    Type = "NonformalizedAcceptanceCertificate"
    TypeNamedId = "AcceptanceCertificate"
    DocumentFunction = "default"
    Version= "v1"
  этот же документ из BoxEvent.DocumentType = "NonformalizedAcceptanceCertificate"

Из https://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html следует, что свойство Type использовать нежелательно.
Как мне не используя Type на основании рекомендуемых TypeNamedId, DocumentFunction и Version понять что документ представляет из себя печатную форму с xml составляющей (неформальный документ), т. е. то, что верно написано в Type?
Используется DiadocCom_5_32_0_627.dll.

**Comment by kulakovskaya** [comment]
Здравствуйте! TypeNamedId = "AcceptanceCertificate" - это и есть [неформализованный акт](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Enums/DocumentToSend.html?highlight=AcceptanceCertificate#documenttosend).
Если необходимо узнать является ли документ формализованным, можно воспользоваться методом [GetDocumentTypes](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html?highlight=GetDocumentTypes%20#Organization.GetDocumentTypes) и в ответе метода найти свойство [Is Formal](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentTitle.html).
