### ISSUE TITLE
Нет связных документов для УКД Ксчф Дис

### ISSUE THREAD

**Issue by Namelesssssss** [diadoc/diadocsdk-1c-docs#531]
Для входящего документа УКД Ксчф Дис нет связных документов (ЭДОбъект.InitialDocumentIds.Count = 0).
Номер документа основания указан верно (номер соответствует номеру УПД), в руководстве пользователя было указано, что Диадок автоматически связывает УПД и УКД.

**Comment by kulakovskaya** [comment]
Здравствуйте! При отправке УКД необходимо указать параметр InitialDocumentId, только тогда документы свяжутся. 
Подскажите, пожалуйста, где именно в руководстве пользователя сказано о том, что Диадок автоматически связывает УПД и УКД?

**Comment by Namelesssssss** [comment]
Руководство пользователя сервиса Диадок (https://wiki.diadoc.ru/pages/viewpage.action?pageId=720902)
"Диадок автоматически связывает корректировочный документ (с функцией КСФ
или КСФДИС) с ранее отправленным универсальным передаточным документом
(УПД с функцией СЧФ или СЧФДОП). Все связанные документы возможно
посмотреть на странице просмотра УПД"

Контрагент отправляет документы через модуль для 1С, в нём как-то реализована возможность указать связный документ или только через доработки?

**Comment by kulakovskaya** [comment]
Здравствуйте! Можете указать версию модуля Диадок 1С, из которого контрагент отправляет документы?

**Comment by Namelesssssss** [comment]
5.38.01.444

**Comment by kulakovskaya** [comment]
В [модуле УФ](https://wiki.diadoc.ru/pages/viewpage.action?pageId=7668802) не реализована возможность связывать УПД и УКД. Зарегистрировано пожелание.
