### ISSUE TITLE
Ошибка при отклонении входящего документа, COM x86 5.30.0.580 для произвольных систем

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#532]
Ошибка при вызове метода контекста (Send): 
Произошла исключительная ситуация (ReplySendTask2.Send): 
##100[Ошибка сервера Диадок]code:400, HTTP error: 
MessagePatchToPost should contain at least one entity.

//тип отклоняемого документа: 
Document.type = "UniversalTransferDocument"
DocumentFunction = "СЧФ"
Version = "utd820_05_01_01_hyphen"

```
//Отклонение
ReplySendTask = Document.CreateReplySendTask2("RejectDocument");
ContentItems = ReplySendTask.ContentItems;
КоличествоКонтентов = ContentItems.Count();
Для ц = 0 По КоличествоКонтентов - 1 Цикл
   ContentItem = ContentItems.GetItem(ц);
   ContentItem.Content.comment = "Комментарий";  
   Signer = ContentItem.Content.Signer;
   Signer.Surname = "Фамилия;
   Signer.FirstName = "Имя"";
   Signer.Patronymic = "Отчество";
   Signer.JobTitle = "Должность";   
   Signer.INN = "ИНН";  
   Signer.IsSoleProprietor = ложь;								
КонецЦикла; 
ReplySendTask.Send();
```

**Comment by kulakovskaya** [comment]
Добрый день! Попробуйте обновить компоненту до актуальной версии [5.32.0](https://1c-docs.diadoc.ru/ru/latest/History/History.html).

**Comment by jakeqwert** [comment]
Обновили компоненту до версии 5.32.0, не помогает, выходит такая же ошибка.

**Comment by kulakovskaya** [comment]
Добрый день! Документы с DocumentFunction = "СЧФ" нельзя подписать или отказать в подписи по ним.
