### ISSUE TITLE
Диадок не отдает количество сертификатов

### ISSUE THREAD

**Issue by Alexsis-it** [diadoc/diadocsdk-1c-docs#533]
Попытка
		ДиадокАпи = Новый ComОбъект("Diadoc.DiadocClient");
	Исключение
		Сообщить("Ошибка загрузки COM объекта <Diadoc.DiadocClient>: " + ОписаниеОшибки());
		Возврат Неопределено;
	КонецПопытки;
	
	// Задаем параметры подлючения к серверу
	
	ДиадокАпи.ApiClientId = КлючРазработчика;
	ДиадокАпи.ServerUrl   = "https://diadoc-api.kontur.ru:443";
	
	Certificates		 = ДиадокАПИ.GetPersonalCertificates();
	CertificatesCount    = Certificates.Count();
	Возвраащает CertificatesCount = 0 

Подскажите куда копать?

**Comment by kulakovskaya** [comment]
Добрый день! Подскажите какую используете версию компоненты?
Установлены ли сертификаты в хранилище Личное? Подробнее в [документации](GetPersonalCertificates).

**Comment by Alexsis-it** [comment]
версия компоненты последний релиз COM-соединения.
Сертификаты установлены, Контур.диагностика показывает все ОК.

**Comment by kulakovskaya** [comment]
Приложите, пожалуйста, номер диагностики.

**Comment by Alexsis-it** [comment]
18169161

**Comment by kulakovskaya** [comment]
По результатам диагностики видно, что при установке сертификатов в хранилище Личное возникли ошибки:
![image](https://user-images.githubusercontent.com/54439404/98631062-5e2ec500-233e-11eb-9d41-1b7d70bfc5dc.png)

Рекомендуем переустановить сертификаты с помощью инструкции 
[ustanovka_sertifikata.pdf](https://github.com/diadoc/diadocsdk-1c-docs/files/5514985/ustanovka_sertifikata.pdf)

**Comment by Alexsis-it** [comment]
![image](https://user-images.githubusercontent.com/74223681/98633105-5a596d80-2353-11eb-9399-94a107b1c852.png)

**Comment by Alexsis-it** [comment]
сделал второй раз все по инструкции. выдает то же самое.

**Comment by kulakovskaya** [comment]
Приложите скрин с вкладки "Путь сертификации".

**Comment by Alexsis-it** [comment]
![image](https://user-images.githubusercontent.com/74223681/98634071-4151bc00-2355-11eb-8160-488c163c62df.png)

**Comment by kulakovskaya** [comment]
По последнему скриншоту видно, что проблема с корневым сертификатом.
Какие действия можно предпринять:
1. Нажать на корневой сертификат двойным кликом мыши.
2. Нажать на кнопку "Установить сертификат".
3. Запустится мастер установки сертификатов.
4. Нужно выбрать "Текущий пользователь" - "Установить в хранилище" выбрать хранилище "Доверенные корневые центры сертификации" и нажать "Далее". 
5. Появится окно с предупреждением, необходимо нажать "Да".

Корневой сертификат будет установлен. Если возникнут сложности, обратитесь в техподдержку любым удобным способом - https://www.diadoc.ru/support.

**Comment by Alexsis-it** [comment]
Спасибо, теперь сертификат виден. Но ничего не поменялось. Все равно диадок возвращает количество сертификатов 0.
Поддержка ничего сказать не может. Отписывается стандартными шаблонами.

**Comment by Alexsis-it** [comment]
![image](https://user-images.githubusercontent.com/74223681/98650343-58030d80-236b-11eb-98e2-eb991b23238b.png)
ключ АПИ в личном кабинете.

**Comment by kulakovskaya** [comment]
Пройдите еще раз диагностику, пожалуйста. И отправьте номер актуальной диагностики.

**Comment by Alexsis-it** [comment]
Прошел 18176088

**Comment by Alexsis-it** [comment]
![image](https://user-images.githubusercontent.com/74223681/98650472-8680e880-236b-11eb-90fb-3b78ba4e6b25.png)

**Comment by kulakovskaya** [comment]
Подскажите, пожалуйста, где выполняется запрос на сервере или на локальном компьютере пользователя? А также куда был установлен сертификат - на сервер или на компьютер пользователя?

**Comment by Alexsis-it** [comment]
Сертификаты установлены на сервер и оттуда отправляем

**Comment by kulakovskaya** [comment]
Можем еще предположить, что 1С  работает под одним пользователем, а сертификат пытаетесь получить от другого пользователя.

**Comment by Alexsis-it** [comment]
нет. Думаю это не та проблема.
Подскажите что делает команда библиотеки GetPersonalCertificates(). Она запрашивает на сервере диадока сертификат? 
т.е. идет по адресу "https://diadoc-api.kontur.ru:443" и получает по ключу ApiClientId список сертификатов, так?

**Comment by azhipaigor** [comment]
Нет. В этот момент никаких запросов на сервер не будет. GetPersonalCertificates() запрашивает список сертификатов из хранилища сертификатов Windows. Конкретнее, если вызов без аргументов или с аргументом TRUE, то это будут сертификаты из хранилища текущего пользователя (CERT_SYSTEM_STORE_CURRENT_USER), "Личное"("MY"). С аргументом FALSE - сертификаты компьютера (CERT_SYSTEM_STORE_LOCAL_MACHINE), "Личное"("MY").

**Comment by Alexsis-it** [comment]
Добрый день! Все получилось. Сертификаты установили. Теперь ошибка в ключе API. Ранее нам передавали такой ключ "api-8fecfb97-3176-4e62-a054-3ac191dda788", но при попытке отправить возникает следующая ошибка 
Ошибка ДИАДОК: 
{ОбщийМодуль.Сервер.Модуль(1075)}: Ошибка при вызове метода контекста (CreateConnectionByCertificate): Произошла исключительная ситуация (DiadocCom.CreateConnectionByCertificate): ##100[Ошибка сервера Диадок]code:401, HTTP error: Invalid API client id

Можете подсказать где взять правильный ключ API?

**Comment by IrinaShmonina** [comment]
@Alexsis-it здравствуйте,
обратитесь с этим вопросом к вашему менеджеру или в нашу [техническую поддержку](https://www.diadoc.ru/support)

**Comment by Alexsis-it** [comment]
Здравствуйте! Можете подсказать, у com объекта Organization отсутствует метод 
Organization.GetExtendedSignerDetails2(Organization.Certificate.Thumbprint, "UtdSeller")	{(1)}: Ошибка при вызове метода контекста (GetExtendedSignerDetails2)	
Где можно посмотреть какие методы используются?

**Comment by Alexsis-it** [comment]
![image](https://user-images.githubusercontent.com/74223681/99205640-b9076700-27eb-11eb-83e2-5e52e011f238.png)
COM объект создан и отпечаток есть.

**Comment by Alexsis-it** [comment]
хотя метод Organization.CreateSetExtendedSignerDetailsTask(Organization.Certificate.Thumbprint) видит и возвращает

**Comment by Alexsis-it** [comment]
версия COM компонента v5.32.0.627 x64 для произвольных систем

**Comment by Alexsis-it** [comment]
некоторые методы не работают на этой версии. К кому обращаться?

**Comment by azhipaigor** [comment]
> 
> 
> Здравствуйте! Можете подсказать, у com объекта Organization отсутствует метод
> Organization.GetExtendedSignerDetails2(Organization.Certificate.Thumbprint, "UtdSeller") {(1)}: Ошибка при вызове метода контекста (GetExtendedSignerDetails2)
> Где можно посмотреть какие методы используются у com объекта ?

Здравствуйте!

Методы не менялись. Все как описано в [документации](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html).
Скорее всего у вас некорректно зарегистрирована компонента. Нужно перерегистрировать:
1. regsvr32 /i:user /u "Путь до компоненты" (с правами администратора)
2. regsvr32 /i:user /n "Путь до компоненты"

**Comment by Alexsis-it** [comment]
Здравствуйте! 
Получаю входящий документ, а у него нету перечня товаров и услуг, т.е. нету реквизита Table. Как их можно получить? 
А в полученной печатной форме pdf табличная часть есть. 

		// Создаем объект DocumentsTask
		DocumentsTask = Organization.GetDocumentsTask();
		
		// Заполняем параметры отбора документов
		DocumentsTask.FromSendDate = НачалоГода(ТекущаяДата());
		DocumentsTask.ToSendDate   = КонецГода(ТекущаяДата());
		DocumentsTask.Category     = "UniversalTransferDocument.InboundWaitingForRecipientSignature";

**Comment by GilimkhanovDenis** [comment]
Добрый день. Возможно, вам подойдёт решение из https://github.com/diadoc/diadocsdk-1c-docs/issues/509

Рекомендую новые вопросы, не связанные с первоначальной проблемой оформлять отдельным тикетом
