### ISSUE TITLE
Ошибка при получении отпечатка

### ISSUE THREAD

**Issue by kvazymoda** [diadoc/diadocsdk-1c-docs#536]
Добрый день.

При попытке выполнить:
ПодключитьВнешнююКомпоненту("AddIn.DiadocInvoiceAPI");

DiadocApi_ = Новый("AddIn.DiadocInvoiceAPI");
DiadocApi  = DiadocApi_.CreateObject();

//DiadocApi.ApiClientId  = КлючРазработчика; // Тестовый ключ получен на 21 день
DiadocApi.ServerUrl   = "https://diadoc-api.kontur.ru:443";

//Получение списка сертификатов
Certificates = DiadocApi.GetPersonalCertificates();

//Создание соединения
ОтпечатокСертификата = Certificates.GetItem(0).Thumbprint;
DiadocConnection = DiadocApi.CreateConnectionByCertificate(ОтпечатокСертификата);
_________________________________________

Вопрос 1: На локальной машине, ноуте, Certificates.Count =1, находит отпечаток.
На сервере рабочем, на котором ключи КЭП и криптопро установлены, пытаюсь запустить тот же код и ключ разработчика: Certificates.Count =0, 
       то есть не находит сертификат и далее не возможно Certificates.GetItem(0), тк нет объектов в выборке.
     Что я не так сделал? Где и что посмотреть?

Вопрос 2: DiadocApi.CreateConnectionByCertificate, корректно отработает если под этим пользователем, установлены сертификаты и крипто про?  Поэтому имеет смысл запускать только на рабочей машине? Или на локальной(без КЭП) тоже должно отработать? 
Спасибо

**Comment by azhipaigor** [comment]
Добрый день!

Метод GetPersonalCertificates() при вызове без аргументов возвращает сертификаты из хранилища сертификатов Windows текущего пользователя (CERT_SYSTEM_STORE_CURRENT_USER), "MY". Возможно на сервере сертификаты установлены в хранилище компьютера? Тогда их можно получить вызовом GetPersonalCertificates(false).

Если сертификат зарегистрирован в Диадок (КЭП), то CreateConnectionByCertificate сможет авторизоватся.

**Comment by kvazymoda** [comment]
Добрый день.

В1: Да, верно. выяснилось что на тестовой машине не было сертификатов установленных в Windows.  После переноса их, от реального пользователя, к тестовому (с помощью инструкции от Контура), код отработал как следует. 

В2: Предлагаю Вам,  оф. справку доработать и вставить вышеприведенный текст: "...Метод GetPersonalCertificates() при вызове без аргументов возвращает сертификаты из хранилища сертификатов Windows текущего пользователя (CERT_SYSTEM_STORE_CURRENT_USER)..." Иначе не понятна суть метода GetPersonalCertificates.

Спасибо.

**Comment by azhipaigor** [comment]
Здравствуйте!

В документации напишем более очевидно. Спасибо за обратную связь!
