### ISSUE TITLE
Объект Document возвращает пустой статус

### ISSUE THREAD

**Issue by CatAnd0** [diadoc/diadocsdk-1c-docs#537]
Версия компоненты COM x86 5.32.0.627

Документ отправляется внутри компании между подразделениями. При получении статуса у такого документа возвращается пустая строка. При этом в личном кабинете на сайте статус отображается.

Создание документа происходит так:
`this.parmPackageSendTask2().AddDocumentFromFile("Torg13", "default", "v1", _metaData.parmFileName());`

Возможно, статус не возвращается, потому что нет производного объекта от Document для Torg13.

Подскажите, что можно сделать для получения статусов по таким документам?

**Comment by volodkindv** [comment]
Причина может быть и в типе документа (ТОРГ-13), и в том, что документ внутренний.

Попробуйте посмотреть значения в полях "RevocationStatus", "SenderSignatureStatus" и другим подобных: https://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html?highlight=status

**Comment by CatAnd0** [comment]
Другие статусы возвращают значения отличные от возможных значений Document.Status(). То есть невозможно в таком случае получить унифицированную систему. 

Если сделать прямой запрос HTTP API /V3/GetDocument по документу, то там есть структура **Torg13Metadata** и в поле **DocumentStatus** возвращается нужный статус:
`"Torg13Metadata": "DocumentStatus":"InternalWaitingForRecipientSignature","Total":"115674.85","Vat":"","Grounds":"","ReceiptStatus":"ReceiptStatusNone","RevisionDate":"","RevisionNumber":""}`

Получается, что статус приходит в компоненту, но она его не отдает.

**Comment by ButurlakinSemyon** [comment]
Структура Torg13Metadata считается устаревшей. Мы не советуем ее использовать, так как в будущем эта структура может быть удалена. Статус нужно формировать самостоятельно по RecipientReceiptMetadata, ConfirmationMetadata, AmendmentRequestMetadata, RecipientResponseStatus, SenderSignatureStatus.

**Comment by CatAnd0** [comment]
Спасибо за консультацию. Сделаем составной статус по предложенным статусам.
