### ISSUE TITLE
Ошибка при расшифровке данных: Нет доступа к карте. Введен неправильный PIN-код.

### ISSUE THREAD

**Issue by averyanovalex** [diadoc/diadocsdk-1c-docs#539]
Не получается авторизоваться по сертификату. Хотя сертификат установили на компьютере. Получаем ошибку

Ошибка при вызове метода контекста (CreateConnectionByCertificate): Произошла исключительная ситуация (DiadocCom.CreateConnectionByCertificate): ##300[Ошибка CryptoPro]Ошибка при расшифровке данных [2148532331:Нет доступа к карте. Введен неправильный PIN-код.]

Авторизуемся вот так:

ДиадокСоединение = ДиадокAPI.CreateConnectionByCertificate(<Строка отпечаток сертификата>);

В чем может быть проблема?

**Comment by volodkindv** [comment]
Закрытый ключ ЭЦП защищен пин-кодом. При вызове метода [CreateConnectionByCertificate](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html?highlight=CreateConnectionByCertificate#DiadocAPI.CreateConnectionByCertificate) КриптоПро должен выдать окно с запросом пин-кода, и его надо ввести прравильно. Попробуйте для начала авторизоваться в веб-интерфейсе с этим сертификатом, там должно тоже всплыть окно с запросом пинкода.

Если не хотите его каждый раз вводить, то можно передать пинкод вторым параметром в  [CreateConnectionByCertificate](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html?highlight=CreateConnectionByCertificate#DiadocAPI.CreateConnectionByCertificate)

**Comment by averyanovalex** [comment]
понял, спасибо
