### ISSUE TITLE
Печатные формы дорабатывать или нет?

### ISSUE THREAD

**Issue by ShibaevAnton** [diadoc/diadocsdk-1c-docs#54]
Добрый день.

Сегодня появился вопрос о печатных формах документов. 

Если мы правильно поняли то печатная форма открывается стандартная. 

У нас формы немного отличаются от стандартных.

Хотел уточнить в электронном документообороте это играет какую-то роль?

Нашим клиентам при ЭДО нужна наша измененная форма? Или ему без ризница? С законодальной стороны могут быть вопросы? 

Мне кажется такие вопросы возникали уже. Что можете сказать по данному вопросу?

С уважением Шибаев А.И.

**Comment by volodkindv** [comment]
Добрый день.
С законодательной стороны клиент должен получить файл, подписанный ЭЦП. Если речь идет о формализованных документах (ТОРГ-12, счет-фактура и т.д.), то файл должен быть в формате XML и соответствовать XSD-схемам, которые были разработаны ФНС.
Печатные формы в этом случае не имеют никакого значения: это просто способ более привычного для человека отображения содержимого xml-файла.
Если ваши печатные формы содержат какие-то расширенные сведения (например, штрихкод товара в ТОРГ12), то можете передавать их в дополнительных полях: StructedAdditionalInfos или AdditionalInfo, они описаны в документации.
