### ISSUE TITLE
Какие события меняют статус документа ?

### ISSUE THREAD

**Issue by IlyaGlyzin** [diadoc/diadocsdk-1c-docs#540]
я получаю события методом GetDocumentEventList

там есть событие Confirmation , статус документа при этом может изменится?
т.е. мне бы хотелось знать для каких событий произошла смена статуса.

**Comment by ButurlakinSemyon** [comment]
Добрый день!

Зависит от того, что вы подразумеваете под статусом.
Если про поле Document.Status, то оно не всегда будет меняться. Но вполне может влиять на содержание коллекций RecipientReceiptMetadata и остальных, по которым можно собрать статус документа.
А если про документооборот в общем виде, то всё, кроме MetaModify, меняет статус в каком-то виде.

**Comment by IlyaGlyzin** [comment]
Спасибо
