### ISSUE TITLE
Ошибка при получении динамического контекста

### ISSUE THREAD

**Issue by IlyaGlyzin** [diadoc/diadocsdk-1c-docs#541]
GetDynamicContent

выдает 

Произошла исключительная ситуация (DocumentBase.GetDynamicContent): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid content to parse for document type=[typeNamedId=ProformaInvoice, function=default, version=proformainvoice_01_01, titleIndex=0]

DocumentID = 9b181af3-45a3-48fe-8957-c7267a915996abd05139-9ec9-4a74-95c3-e37ba4a309e4
BoxID = 6aafd32f478e4aa6b0fa1cd4ea60c793@diadoc.ru

**Comment by IlyaGlyzin** [comment]
UP

**Comment by kulakovskaya** [comment]
Добрый день! В Диадоке не предусмотрен парсинг для typeNamedId=ProformaInvoice. Расскажите подробнее о том, что требуется сделать с документом и зачем нужен парсинг?

**Comment by IlyaGlyzin** [comment]
да мне собственно не нужен , просто выдает ошибку , хотел знать почему. Если не предусмотрен тогда я не буду обрабатывать тоже такие ситуации.
