### ISSUE TITLE
После обновления библиотек до v5.32.0.627 перестали отправляться документы (УПД)

### ISSUE THREAD

**Issue by NickVStepin** [diadoc/diadocsdk-1c-docs#542]
PackageSendTask2.Send возвращает ошибку: В отправляемом документе заполнены взаимоисключающие элементы: SignerReference,  SignerDetails

до обновления библиотек работало исправно.

авторизация делается по логину/паролю, в SignerReference передается отпечаток сертификата.

BoxId: 858f928aed7d4c04ac5b0169b30de77a@diadoc.ru
CertificateThumbprint: b53bf262f0dafc749656da728afcee11969c68c8
FirstName: Николай
Inn: 9610509099
LastName: Степин
MiddleName: Вячеславович
Position: директор информационной службы
SignerType: 1
SignerPowers: 5
SignerStatus: 1

**Comment by NickVStepin** [comment]
потестировал, проблема начинается с версии 5.29.9 (в 5.29.8) все работает.
с 5.29.9 для отправки УПД обязательно требует ввода по сертификату

**Comment by NickVStepin** [comment]
с 5.29.9 PackageSendTask2.Send: Для подписания и отправки юридически значимого документа необходимо выполнить вход по сертификату

**Comment by volodkindv** [comment]
Все верно, для отправки юридически значимого документа нужна ЭЦП. Ее можно сформировать только в том случае, если вход выполнен под сертификатом.

По поводу изначального сообщения - дело в том, как заполняется динамический контент документа. В поле ExtendedSigner можно заполнить, на выбор:
- либо BoxId + CertificateThumbprint
- либо все остальные поля (FirstName, Inn, Position, ..).

Описание ошибки указывает на то, что вы заполняете оба поля одновременно.
