### ISSUE TITLE
Ошибка отправки УКД

### ISSUE THREAD

**Issue by svetik-alekseevna** [diadoc/diadocsdk-1c-docs#543]
Добрый день!
При отправке УКД из 1С выходит ошибка:
"Ошибка HTTP запроса
Код ошибки: 400
MessageToPost.DocumentAttachments[0]: Документ не может быть отправлен в указанном формате"

"Content-Type"  -  "application/json;charset=utf-8"
Параметры запроса во вложении
[параметры запроса УКД.xlsx](https://github.com/diadoc/diadocsdk-1c-docs/files/5582775/default.xlsx)

В чем причина ошибки?

**Comment by kulakovskaya** [comment]
Добрый день!
Используете ли Вы модуль Диадок 1С? Если да, то какой версии?

Как формируется xml-файл для УКД?

**Comment by kulakovskaya** [comment]
В Content и Signature присутствуют символы переноса строки:
`\r\n`

Из-за этого происходит ошибка отправки документа.

**Comment by svetik-alekseevna** [comment]
> Добрый день!
> Используете ли Вы модуль Диадок 1С? Если да, то какой версии?
> 
> Как формируется xml-файл для УКД?

у нДиадокас модуль устаревший  -сильно переписанная УПП. так что обновляем по мере необходимости по частям, версию не скажу

**Comment by svetik-alekseevna** [comment]
> В Content и Signature присутствуют символы переноса строки:
> `\r\n`
> 
> Из-за этого происходит ошибка отправки документа.

спасибо огромное! никогда бы не заметила. Как удастся проверить, отпишусь

**Comment by svetik-alekseevna** [comment]
А не могли бы Вы прислать пример http-запроса пот отправке УКД для сравнения?

**Comment by volodkindv** [comment]
Добрый день. Возможно, причина в том, что не указаны Function и AttachmentVersion.
![image](https://user-images.githubusercontent.com/12305552/100201170-89f6a100-2f21-11eb-8cb0-561fd80587ca.png)

**Comment by svetik-alekseevna** [comment]
> Добрый день. Возможно, причина в том, что не указаны Function и AttachmentVersion.
> ![изображение](https://user-images.githubusercontent.com/12305552/100201170-89f6a100-2f21-11eb-8cb0-561fd80587ca.png)

Спасибо за совет! Но, увы, не помогло. По коду эти поля подставляются, если документ зашифрован. Если указываю, что он зашифрован, то приходит ответ с ошибкой, что организация не может отправлять зашифрованные доки. А если просто их заполняю, то ошибка как и прежде - Код ошибки: 400
MessageToPost.DocumentAttachments[0]: Документ не может быть отправлен в указанном формате"

**Comment by kulakovskaya** [comment]
Добрый день! Есть возможность приложить xml документа?

**Comment by svetik-alekseevna** [comment]
> Добрый день! Есть возможность приложить xml документа?

Добрый! Приложила

[ON_KORSCHFDOPPR_2BM-9661294606-966101000-201710120213295936911_2BM-9682790475-968201000-201805150903281095037_20201203_73fbcbe3-91fe-4b01-aae9-67ae...zip](https://github.com/diadoc/diadocsdk-1c-docs/files/5652882/ON_KORSCHFDOPPR_2BM-9661294606-966101000-201710120213295936911_2BM-9682790475-968201000-201805150903281095037_20201203_73fbcbe3-91fe-4b01-aae9-67ae.zip)

**Comment by kulakovskaya** [comment]
Файл проходит [проверку](https://www.diadoc.ru/docs/forms/validation-xml) по xsd схеме:
![image](https://user-images.githubusercontent.com/54439404/101364768-be287500-38c4-11eb-803e-9989d14484ce.png)

Проверьте, пожалуйста, результат перекодировки в base64.
Попробовали перевести, вот что получилось:
[Результат перекодировки.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/5653364/default.txt)

**Comment by svetik-alekseevna** [comment]
[сравнение перекодировки 1С и ЛК Диадока.docx](https://github.com/diadoc/diadocsdk-1c-docs/files/5654584/1.docx)
[результат перекодировки в base64 из 1с.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/5654586/base64.1.txt)
Сравнила. Есть разница, но пока не поняла, в чем причина. Попробовала заменить при отправке на содержимое,которое Вы прислали, ошибка прежняя(

**Comment by kulakovskaya** [comment]
Добрый день! В xml документа содержатся реквизиты исправительного документа:
![image](https://user-images.githubusercontent.com/54439404/101448085-47cd5680-3948-11eb-8535-3b8234c66e1a.png)
В таком случае в TypeNamedId нужно указать "UniversalCorrectionDocumentRevision".

**Comment by svetik-alekseevna** [comment]
> Добрый день! В xml документа содержатся реквизиты исправительного документа:
> ![изображение](https://user-images.githubusercontent.com/54439404/101448085-47cd5680-3948-11eb-8535-3b8234c66e1a.png)
> В таком случае в TypeNamedId нужно указать "UniversalCorrectionDocumentRevision".

Благодарю Вас!! Проблема оказалась действительно в этом. Вопрос решен!
