### ISSUE TITLE
Не отрабатывает метод SendAsync() отправки черновика УПД

### ISSUE THREAD

**Issue by klishev** [diadoc/diadocsdk-1c-docs#544]
DiadocApi.ServerUrl   = "https://diadoc-api-test.kontur.ru:443";
Организация----------
Guid 9f197cbd-ac80-4659-9780-428af6209dd9
AuthenticateType Login
IsTest 0
IsPilot 0
IsLiquidated 0
EncryptedDocumentsAllowed 0

выполняю следующий код:
SendDraftTask = Organization.CreateSendDraftTask("9e0ede25-3f43-4bd2-8d58-876314ecde61");
AsyncResult = SendDraftTask.SendAsync();

у объекта AsyncResult :
AsyncResult.IsCompleted = 1
AsyncResult.Result = Ошибка в выражении!
т.е. свойства "Result " якобы нет, но при этом:
Reflector.Describe(AsyncResult).GetPropertiesNames().GetItem(1) = "Result"

**Comment by klishev** [comment]
Черновики УПД созданы автоматически после отправки INVOIC по API EDI.
Событие EDI ящика "DraftOfDocumentPackagePostedIntoDiadoc" возвращает:
MessageId = eb4f8347-298d-11eb-9d58-4d117bdc6b09
UniversalTransferDocumentId = 9e0ede25-3f43-4bd2-8d58-876314ecde61

**Comment by IrinaShmonina** [comment]
@klishev , здравствуйте
у вас в Result должна лежать ошибка с причиной не отправки черновика. Вам нужно посмотреть поле Result через конфигуратор. Нужно в try ... catch ... обернуть получение результата и посмотреть на ошибку

**Comment by klishev** [comment]
Дополнил код, теперь он стал следующим:
	SendDraftTask = Organization.CreateSendDraftTask("9e0ede25-3f43-4bd2-8d58-876314ecde61");
	ExtendedSigner = SendDraftTask.AddExtendedSigner();
	ExtendedSigner.BoxId = Organization.Guid;
	ExtendedSigner.CertificateThumbprint = гОтпечаток;
	Result = AsyncResult.Result;
	сообщить(СокрЛП(Result));
	сообщить(Result.Count);
Result теперь содержит значение "IValueCollection", но в нём 0 строк.
Пробовал с другим UniversalTransferDocumentId, тоже Result.Count = 0.

Получается что не находится черновик по идентификатору или как эту ситуацию понимать?

**Comment by klishev** [comment]
У документов в Диадок ИД длиной 72 символа.
EDI сайт возвращает мне ИД черновиков Диадока длиной 36 символа.
Может быть причина в том, что мне для работы с черновиками в Диадоке нужно ИД длиной 72 символа, но тогда где взять  недостающие символы?

**Comment by GilimkhanovDenis** [comment]
1) В Organization.CreateSendDraftTask() нужно передать MesageId

2) в ящике 9f197cbd-ac80-4659-9780-428af6209dd9 нет черновиков ни с идентификaтором eb4f8347-298d-11eb-9d58-4d117bdc6b09 (то, что названо MessageId), ни с идентификатором 9e0ede25-3f43-4bd2-8d58-876314ecde61 (то, что названо UniversalTransferDocumentId)

3) Про идентификатор в 72 символа: DocumentId = MessageId + EntityId

4) Про ValueCollection с Count = 0 в результате. Теоретически такое возможно, но сценарий воспроизведения пока не понятен. Буквально это значит, что никакого исключения при вызове метода не произошло, но и никакие черновики не отправились - очень странная ситуация

5) Вы пишете, что 

> AuthenticateType Login

Но пытаетесь подписать черновики. Для подписания нужно быть авторизованным по сертификату

Предлагаю начать с того, чтобы найти черновик в ящике.
Проверить, что черновик с используемыми идентификаторами есть в ящике можно, например,  используя метод [GetDocumentById](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#organization-getdocumentbyid)

И авторизоваться по сертификату, чтобы была возможность подписывать документы

**Comment by klishev** [comment]
Денис, большое спасибо за ответ. 
2. Можете назвать хотя бы 1 MesageId у черновика, находящегося в ящике
Guid 9f197cbd-ac80-4659-9780-428af6209dd9 ?
3. Когда я получаю события "DraftOfDocumentPackagePostedIntoDiadoc" из ящика EDI там нет свойства с именем "EntityId".
4. Для отправки черновиков я авторизовался по сертификату, ValueCollection с Count = 0  получается можно интерпретировать, что нет черновика с указанным идентификатором.
5. Попробовал метод GetDocumentById  с моими 36 разрядными идентификаторами, возвращает ошибку "Could not parse entityId query param". Получается необходим идентификатор 72 символа, где взять EntityId ??

**Comment by GilimkhanovDenis** [comment]
2. Идентификаторы черновиков:
MessageId=6a075616-a0c7-43c1-9cc2-2c9ebc1ca543 ; EntityId=22a150d2-ef02-4b0b-b643-00bff9d312d2
MessageId=5a3d7884-8abe-4966-afda-a28ac8f960ff ; EntityId=9e0ede25-3f43-4bd2-8d58-876314ecde61

На примере первого черновика корректными будут вызовы
```
dd_SendDraftTask = Organization.CreateSendDraftTask("6a075616-a0c7-43c1-9cc2-2c9ebc1ca543"); // опустим пока заполнение подписантов и подписание черновика
dd_Document = Organization.GetDocumentById("6a075616-a0c7-43c1-9cc2-2c9ebc1ca54322a150d2-ef02-4b0b-b643-00bff9d312d2");
```

3. Подозреваю, что это тот идентификатор, которы в одном из сообщений выше указан как UniversalTransferDocumentId, но лучше это уточнить у специалистов по API EDI

4. Кажется, корректным должен быть возврат ошибки, что черновика нет. На своей стороне проверим поведение компоненты

5. Ответ в пункте 3

**Comment by klishev** [comment]
Денис, спасибо за оперативный ответ! Завтра попробую отправку черновиков и отпишусь.

**Comment by klishev** [comment]
Денис, спасибо!
Получилось отправить черновики после авторизации по сертификату:
	SendDraftTask = Organization.CreateSendDraftTask("5a3d7884-8abe-4966-afda-a28ac8f960ff");
	ExtendedSigner = SendDraftTask.AddExtendedSigner();
	ExtendedSigner.BoxId = Organization.Guid;
	ExtendedSigner.CertificateThumbprint = гОтпечаток;
	AsyncResult = SendDraftTask.SendAsync();
Но при этом: AsyncResult.Result.Count = 0

**Comment by klishev** [comment]
Использовал компоненту версии 5.31.0.604

**Comment by klishev** [comment]
Хотел ещё проконсультироваться.
После того как я отправил черновик методом:
SendDraftTask.SendAsync().

Этот черновик перешел в "Исходящие" из "Черновиков".
По старому идентификатору (который был у черновика) методом GetDocumentById() получаю документ со статусом "OutboundWaitingForSenderSignature".
У документа, который в "Исходящих"  - другой идентификатор и статус "OutboundWaitingForInvoiceReceiptAndRecipientSignature".

Как по идентификатору черновика можно выйти на новый идентификатор документа?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Попробовал сейчас воспроизвести на последней версии компоненты. Результат отправки черновика есть и в результат попадает отправленный документ с новым идентификатором

![image](https://user-images.githubusercontent.com/34439383/102178267-f3395680-3ec6-11eb-935b-c6f1e49d0814.png)

**Comment by klishev** [comment]
Добрый день.
Попробовал отправку с последней версией компоненты: 5.32.2.632.
Я использую 1С 7.7 и 32 битную версию компоненты.
После выполнения :
AsyncResult = SendDraftTask.SendAsync()

AsyncResult.IsCompleted = 0
AsyncResult.Result.Count = 0

но при этом:
1) черновик пропадает из ящика, у него взводится флаг IsDeleted = 1;
2) создаётся подписанный и отправленный документ в Исходящих

**Comment by GilimkhanovDenis** [comment]
Проверил на 1C 7.7
![image](https://user-images.githubusercontent.com/34439383/102747496-32155380-4382-11eb-8b66-dbac35fc9b05.png)

Созданные из черновиков документы возвращаются в результат.

Из того, что вы пишите:

> AsyncResult.IsCompleted = 0
> AsyncResult.Result.Count = 0

Предположу, что не дожидаетесь завершения асинхронного вызова прежде, чем посмотреть результат.

**Comment by klishev** [comment]
Разобрался, такая ситуация:
AsyncResult.IsCompleted = 0
AsyncResult.Result.Count = 0
возникала, когда я передавал неверный отпечаток сертификата.

Успешно получил отправленный документ в результатах отправки.
