### ISSUE TITLE
Добрый день! Ошибка при подписании UTD

### ISSUE THREAD

**Issue by Alexsis-it** [diadoc/diadocsdk-1c-docs#545]
Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 2, Position: 38, /UniversalTransferDocumentBuyerTitle[1]/@DocumentCreator: The 'DocumentCreator' attribute is invalid - The value '' is invalid according to its datatype 'string1000' - The actual length is less than the MinLength value.
Line: 2, Position: 2, /UniversalTransferDocumentBuyerTitle[1]: The element 'UniversalTransferDocumentBuyerTitle' has incomplete content. List of possible elements expected: 'Signers'.
/UniversalTransferDocumentBuyerTitle: One of the fields must be present: @OperationContent, ContentOperCode
{ОбщийМодуль.МодульОбработчикаСообщений.Модуль(454)}:	ReplyTask.Send();

Вот код выполнения. Как по инструкции. 
	
	Organization = Сервер.АвторизоватьсяВДиадок(Организация.ApiClientId,Организация.ИНН,Организация.КПП); 
	DocumentToSend = Organization.GetDocumentById(СтруктураJSON.Document.id);
	ReplyTask = DocumentToSend.CreateReplySendTask2("AcceptDocument");
        ReplyTask.Send();

Подскажите что не так заполнено?

**Comment by ButurlakinSemyon** [comment]
Добрый день!

Ниже пример заполнения:

Процедура ПодписатьВходящийДокумент820(ВходящийДокумент)	
	
	ReplySendTask2 = ВходящийДокумент.CreateReplySendTask2("AcceptDocument");
	ReplyContentItem = ReplySendTask2.ContentItems.GetItem(0);
	
	boxid = ВходящийДокумент.OrganizationId;
	thumbprint = ВходящийДокумент.Organization.Certificate.thumbprint;
	
	ЗаполнитьКонтентОтвета820(ReplyContentItem.content.UniversalTransferDocumentBuyerTitle, boxid, thumbprint);
	ReplySendTask2.Send();

КонецПроцедуры

Процедура ЗаполнитьКонтентОтвета820(Content, boxid, thumbprint)
	
	// xsd-схему титула, на основании которой строится UniversalTransferDocumentBuyerTitle, можно посмотреть по адресу:
	// http://api-docs.diadoc.ru/ru/latest/howto/utd820.html
	
	Content.AcceptanceDate = Формат(ТекущаяДата(), "ДФ=dd.MM.yyyy");
	Content.DocumentCreator = "ООО Рога и Копыта";
	Content.OperationContent = "Товары приняты";
	
	Signer = Content.Signers.AddItems();
	
	Signer.SignerReference.BoxId = boxid;
	Signer.SignerReference.CertificateThumbprint = thumbprint;
	
КонецПроцедуры

**Comment by Alexsis-it** [comment]
с подписями разобрался. Теперь такая ошибка 
Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 2, Position: 38, /UniversalTransferDocumentBuyerTitle[1]/@DocumentCreator: The 'DocumentCreator' attribute is invalid - The value '' is invalid according to its datatype 'string1000' - The actual length is less than the MinLength value.
/UniversalTransferDocumentBuyerTitle: One of the fields must be present: @OperationContent, ContentOperCode
{ОбщийМодуль.МодульОбработчикаСообщений.Модуль(452)}:	ReplyTask.Send();

**Comment by Alexsis-it** [comment]
поля ContentOperCode нету в описании к АПИ.

**Comment by ButurlakinSemyon** [comment]
Описание поля ContentOperCode:
https://1c-pro-docs.diadoc.ru/ru/latest/objects/ContentOperCode.html

**Comment by Alexsis-it** [comment]
Вопрос закрыт
