### ISSUE TITLE
The 'SignerPowers' attribute is invalid - The value '5' is invalid according to its datatype 'Integer' 

### ISSUE THREAD

**Issue by WoockY1** [diadoc/diadocsdk-1c-docs#547]
Добрый день,

Используем com-компоненту для 1С х86. Пытаемся отправить Титул Покупателя. Заполняем через 

```
ДокументДиадок = Organization.GetDocumentById(Ссылка.ИдентификаторПлатформы);
ЗадачаНаОтвет = ДокументДиадок.CreateReplySendTask2("AcceptDocument");
```
Заполнение напрямую:

Детали = ОбъектПодписи.SignerDetails;
		Детали.FirstName = ЭЦП_ПолучитьПолеСертификата(лСертификат, "Имя", Ссылка);
		Детали.LastName = ЭЦП_ПолучитьПолеСертификата(лСертификат, "Фамилия", Ссылка);
		Детали.MiddleName = ЭЦП_ПолучитьПолеСертификата(лСертификат, "Отчество", Ссылка);
		Детали.Position = ЭЦП_ПолучитьПолеСертификата(лСертификат, "Должность", Ссылка);
		Детали.SignerType = "1";
		**Детали.SignerStatus = 1;
		Детали.SignerPowers = "5";**
		Детали.SignerPowersBase = "Должностные обязанности";
		Детали.Inn = СокрЛП(ПРО(Ссылка.Организация,"ИНН",Ссылка.Дата));
		Детали.SignerOrganizationName = СокрЛП(ПРО(Ссылка.Организация,"Наименование",Ссылка.Дата));

При попытке отправки валится:
_Ошибка отправки: {Обработка.ИнтеграцияЕДИ.МодульОбъекта(10529)}: Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 5, Position: 234, /UniversalTransferDocumentBuyerTitle[1]/Signers[1]/SignerDetails[1]/@SignerPowers: The 'SignerPowers' attribute is invalid - **The value '5' is invalid according to its datatype 'Integer' - The Enumeration constraint failed.**
Line: 5, Position: 251, /UniversalTransferDocumentBuyerTitle[1]/Signers[1]/SignerDetails[1]/@SignerStatus: **The 'SignerStatus' attribute is invalid - The value '1' is invalid according to its datatype 'Integer' - The Enumeration constraint failed.**_

Хотелось бы узнать с чем это может быть связано. Заметьте, я пытаюсь как строку передать, так и напрямую число. Результат один и тот же.

**Comment by IrinaShmonina** [comment]
@WoockY1, добрый день
Подскажите какой документ вы пытаетесь подписать? УПД? Какая версия документа?

**Comment by WoockY1** [comment]
Пытаемся подписать УПД последней версии, Титул Покупателя:

![image](https://user-images.githubusercontent.com/75391935/101017743-8e533780-357b-11eb-9286-925c70531290.png)

**Comment by kulakovskaya** [comment]
Добрый день! Вы заполняете титул покупателя, согласно xsd схеме SignerStatus и SignerPowers могут принимать следующие значения:
![image](https://user-images.githubusercontent.com/54439404/101325226-396e3480-388d-11eb-8a70-2fb50ae93a63.png)
