### ISSUE TITLE
Новые версии компоненты com-1С функцией GetDocumentEventList возвращают неверный DocumentDirection

### ISSUE THREAD

**Issue by WoockY1** [diadoc/diadocsdk-1c-docs#548]
Добрый день,
Использовали com-компоненту для 1С версии х86. Решили обновить. Скачали последнюю, оказалось, что новая компонента возвращает список событий и в document direction у ВСЕХ событий Inbound, несмотря на реальное направление документа. Последняя компонента, которая работает. как ожидаемо - от 09.07.2020. Возможно какая-то логика поменялась?
![image](https://user-images.githubusercontent.com/75391935/100932632-370e8200-34fd-11eb-85eb-9c86e0c6a356.png)

Тот же кусок на старой версии компоненты:
![image](https://user-images.githubusercontent.com/75391935/100934886-6f638f80-3500-11eb-8dcb-8cdd83ae6af2.png)

**Comment by GilimkhanovDenis** [comment]
Добрый день.
Какую конкретно версию компоненты вы используете?
можно узнать методом [GetFullVersion()](DiadocAPI.GetFullVersion())

**Comment by WoockY1** [comment]
Сейчас используем "COM x86 5.30.2.593", все более поздние версии, которые мы использовали, возвращают описанный выше результат!

**Comment by GilimkhanovDenis** [comment]
По логам вижу вчерашние запросы только от 5.31.2 версии
в версии 5.32.0 эта ошибка исправлялась и воспроизвести у себя с этой версией не получается

**Comment by WoockY1** [comment]
Да, спасибо, перепроверил на последней версии. Все отработало как надо. Спасибо за помощь.
