### ISSUE TITLE
CreateConnectionByLogin в DiadocCom_5_32_0_627.dll 32bit дает ошибку,  DiadocCom_5_31_2_611.dll  32bit работает нормально

### ISSUE THREAD

**Issue by VMescheryakov** [diadoc/diadocsdk-1c-docs#549]
CreateConnectionByLogin в DiadocCom_5_32_0_627.dll (32 bit) дает ошибку "Неверное значение перечисления"
DiadocCom_5_31_2_611.dll работает нормально

**Comment by ButurlakinSemyon** [comment]
Добрый день.

Предполагаю, что сервер 1С использует закэшированные объекты от старой версии компоненты.
Попробуйте выключить полностью приложение. Перерегистрировать компоненту и включить приложение.
Важно, чтобы не осталось никаких зарегистрированных объектов от любой из ранее зарегистрированных компонент.

**Comment by VMescheryakov** [comment]
Гарантированно нет. На двух компьютерах проверяли. Всегда закрывали приложение, что использует компоненту, потом разрегистрировали и регистрировали новую. Проверяли в системном реестре имя новой dll
Откатываем на старую версию все норм, на новой странная ошибка про перечисления.

**Comment by GilimkhanovDenis** [comment]
Подскажите, в каком приложении используете компоненту

**Comment by VMescheryakov** [comment]
В приложении Дела&Финансы. Разработано на Delphi
В проекте используется импортированная из dll библиотека типов DiadocComApiLib_TLB.pas
Если используется библиотека от версии DiadocCom_5_31_2_611.dll или более ранней то такая ошибка
Если импортировать DiadocCom_5_32_0_627.dll то она не компилируется в Delphi - выдает ошибку
 
на функции

function TEnumVariant.Next(celt: LongWord; const rgvar: OleVariant; out pceltFetched: LongWord): HResult;
begin
  Result := DefaultInterface.Next(celt, rgvar, pceltFetched);
end;

что const не может быть передана внутрь как var. Очевидно что проблема с параметром rgvar

 IEnumVARIANT = interface(IUnknown)
    ['{00020404-0000-0000-C000-000000000046}']
    function Next(celt: LongWord; **var rgvar : OleVariant;**
      out pceltFetched: LongWord): HResult; stdcall;
    function Skip(celt: LongWord): HResult; stdcall;
    function Reset: HResult; stdcall;
    function Clone(out Enum: IEnumVARIANT): HResult; stdcall;
  end;

**Comment by azhipaigor** [comment]
Воспроизводится. Нужно перегенерировать обертки. Попробовал на Delphi 10.4, при импорте DiadocCom_5_32_0_627.dll ошибок компиляции не возникает. Какая у вас версия Delphi?

**Comment by VMescheryakov** [comment]
Delphi XE5
генерирует обертку как я привел выше
var в одном параметре function Next(celt: LongWord; var rgvar : OleVariant; и const  в TEnumVariant.Next(

**Comment by VMescheryakov** [comment]
Проверил на 10.3
Если ставить галку "Generate component Wrappers" при импорте библиотеки (создания DiadocComApiLib_TLB.pas) то такая же ошибка как у меня в XE5 и я всегда импортирую компоненты с такой галкой, удобнее работать с такими компонентами

**Comment by azhipaigor** [comment]
Воспроизвел. С флагом "Generate component Wrappers" действительно генерируется некомпилируемая обертка, причем как для DiadocCom_5_32_0_627.dll, так и для DiadocCom_5_31_2_611.dll. 

Проблемный метод Next относится к системному интерфейсу IEnumVARIANT, который имеет объявление
```
[
  odl,
  uuid(00020404-0000-0000-C000-000000000046),
  hidden
]
interface IEnumVARIANT : IUnknown {
    HRESULT _stdcall Next(
                    [in] unsigned long celt, 
                    [in] VARIANT* rgvar, 
                    [out] unsigned long* pceltFetched);
    HRESULT _stdcall Skip([in] unsigned long celt);
    HRESULT _stdcall Reset();
    HRESULT _stdcall Clone([out] IEnumVARIANT** ppenum);
};
```
Это баг в генераторе оберток Delphi. `[in] VARIANT* rgvar` почему-то стал `const rgvar: OleVariant;` в
```
function TEnumVariant.Next(celt: LongWord; const rgvar: OleVariant; out pceltFetched: LongWord): HResult;
```
Из наличия аттрибута [in] не следует константность параметра (https://docs.microsoft.com/en-us/windows/win32/midl/in).

Со своей стороны спрячем coclass EnumVariant из библиотеки типов, что-бы для него не генерировались обертки.

**Comment by VMescheryakov** [comment]
>Со своей стороны спрячем coclass EnumVariant из библиотеки типов, что-бы для него не генерировались обертки.
Проблема осталась в версии 5_32_4_635
