### ISSUE TITLE
Отправка в Диадок УПД. Ошибка Info.DocumentCreator is required

### ISSUE THREAD

**Issue by Sergguha** [diadoc/diadocsdk-1c-docs#55]
Добрый день,
Компонента 5.10.4.168, x32
При отправке универсального передаточного документа (метод Send() объекта SendTask с типом "UniversalTransferDocument") возникает ошибка Info.DocumentCreator is required. [Поиск данного поля](http://1c-docs.diadoc.ru/ru/latest/search.html?q=DocumentCreator&check_keywords=yes&area=default) в документации результата не дал.
Подскажите, где заполнить этот обязательный реквизит?
![2016-12-22_14-32-26](https://cloud.githubusercontent.com/assets/24603503/21424850/65a52046-c856-11e6-85d0-bbab66e613d1.png)

**Comment by denver069** [comment]
**DocumentCreator** соответствует полю **Creator** в объекта [UtdSellerContent](http://1c-docs.diadoc.ru/ru/latest/UtdSellerContent.html)
