### ISSUE TITLE
Вероятная ошибка в компоненте ЭДО (версия 5.32.0.627) при работе с данными документов

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#550]
Добрый день.

**Возникшая проблема**
На этой неделе стали возникать серьезные проблемы в работе ЭДО, которые мы не сразу смогли идентифицировать.
Разбор проблемы показал, что в некоторых ситуациях, при получении данных документов ЭДО, происходит вылет из 1С в пользовательском режиме (или из конфигуратора при отладке) и уничтожение сеансов фоновых заданий на сервере 1С.
Было замечено, что проблема возникает, как при получении данных новых документов ЭДО, так и при обновлении данных ранее принятых документов.
Дальнейшее изучение проблемы привело нас к мнению о том, что практически со 100% вероятностью в используемой нами версии компоненты для 1С (5.32.0.627) есть ошибка!

**Общая информация для упрощения «разбора полётов»:**
Организация:		«ДНС Ритейл»
ИНН:			2540167061
КПП:			254301001
КПП2:			783450001

Текущая используемая версия компоненты: COM x64 **5.32.0.627**.

**Суть проблемы**
Разбор показал, что для некоторых документов при обращении к какому-то из полей из следующего списка:

Resolutions, 
ResolutionRequests
ResolutionRequestDenials 

Возникает «что-то не то» – **и это полностью «убивает» текущий сеанс 1С (1С аварийно завершает работу).**

Если это пользовательский сеанс – 1С закрывается.
Если это конфигуратор в режиме отладки, остановленной по точке останова, и в нём выполнить следующую команду 1С, которая обращается к одному из этих полей – и конфигуратор, и пользовательский сеанс закрываются.
Если это конфигуратор в режиме отладки, остановленной по точке останова и поместить в окно для показа значений переменных обращение к одному из этих полей – и конфигуратор, и пользовательский сеанс закрываются. 

Во всех этих случаях визуально происходит какой-то ступор на какое-то время (от 2 до 20 секунд) и затем 1С аварийно завершает работу. Вообще говоря, это очень похоже на эффект, возникающий, когда какая-то рекурсия начинает проваливаться куда-то до бесконечности в глубину без выхода наружу и в итоге сжирает весь стек и заставляет приложение вылететь по ошибке.

Сеансы фоновых заданий на сервере 1С при выполнении такого кода также уничтожаются. Процессы на сервере просто падают с дампом.

**В общем в любом случае происходит аварийное прекращение работы 1С. Никакие «Попытка – Исключение – КонецПопытки» никак не помогают и никак не срабатывают.**
Это происходит и при прямых обращениях к полям (типа Документ.Resolutions), и при косвенных (типа Документ["Resolutions"]).

Учитывая информацию об изменениях в последней версии компоненты:
![изображение](https://user-images.githubusercontent.com/33707226/101127210-c5434f00-3648-11eb-8f4e-c19adcb80ec6.png)

мы подозреваем, что, **исправив какие-то найденные ошибки в работе с этими коллекциями, вы внесли туда какие-то новые ошибки, проявляющиеся, если эти коллекции не пусты** (или содержат что-то «специфическое»).
Именно поэтому ошибки при обращении к вышеуказанным полям возникают не со всеми документами, а только с некоторыми, в которых, похоже, в этих полях есть какие-то данные. Какие – по вышеописанным причинам, понятно, что мы со своей стороны посмотреть никак не можем.

**Информация для проверки**
У нас на текущий момент (04.12.2020) вылеты 1С стабильно воспроизводятся на следующих входящих документах (Id входящих документов в ящике ДНС Ритейл):

839d05ac-54ef-47de-9b7b-3e97e5eb8fa5c4e9963b-686a-4d6d-9f57-115883884539
4ab8116a-c5ff-44b0-af95-2453b48447f00aeba503-4877-445a-8457-01bf149d7dde
16af5ff3-bcff-4983-b153-4bc9b7695a2a9a418661-fadc-4290-952d-b69638dfbb07
213f7894-013c-465c-8ef8-7d68d0347bc8b7d4ff6e-ec1d-4631-bc0b-39dc820ae7b3
2711a150-6fb1-4f8f-9093-21fcccdc11781757f15f-b5b9-4043-8dd5-ffcccc22f21f
ff7b43d1-0668-44c6-9781-d89bf9904190af71116d-3de5-4cf4-bdb8-f650bb3a7e81
5209d610-29b0-4709-a02b-1d192c1e7b1aeb6d4de5-874d-4b1c-8a17-cee3b6557491
884e864e-e851-4882-b87d-79a43ac663d9eea26ceb-9695-4e80-bea8-f06255a08ce1
f1539025-ad7c-4f54-b7c4-c4d9838b0f3c42a34c77-0edc-4f44-9f9a-b9b8973f7f7a

Документы разного типа и от разных контрагентов. Т.е. дело точно не в каком-от одном типе документов и не в проблемах какого-то одного контрагента.
Это наверняка не весь набор документов с проблемами, просто, когда ошибки стали проявляться и на документах, которые мы ранее уже успешно обрабатывали, мы переключились не на поиск документов с проблемами вообще, а на поиск деталей того, что именно вызывает аварийное завершение работы 1С при обработке документов. И в этом поиске и вышли в итоге на поля Resolutions, ResolutionRequests и ResolutionRequestDenials. А на то, что именно они перечислены в истории изменений, с удивлением обратили внимание уже позже.
Также было замечено, что проблема касается именно всех трех вышеуказанных полей. Перебирая варианты того, какие поля читать, а какие нет, было замечено, что один документ не ломает 1С, если не читать поле Resolutions, и читать два остальных, но при этом другой документ – всё равно ломает. И так с любым из полей – один документ всё ломает при обращении к одному полю, а другой – при обращении к другому полю. Скорее всего проблема есть по всем этим полям, просто не все поля в каждом из документов заполнены.  
Очень похоже, что ошибка носит какой-то единый обобщающий характер. И, скорее всего, была внесена в рамках внесения указанных в истории изменений исправлений.

Очень надеемся на исправление проблемы. 
Надеемся, что предоставленная информация поможет в ее подтверждении, выявлении и исправлении.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Спасибо!
Информации для решения достаточно. Исправим в ближайшем релизе

**Comment by GilimkhanovDenis** [comment]
Исправлено в [5.32.1](https://1c-docs.diadoc.ru/ru/dev/History/release_info/5_32_1.html)
[Ссылки для скачивания](https://1c-docs.diadoc.ru/ru/dev/Downloads.html)
