### ISSUE TITLE
Статус

### ISSUE THREAD

**Issue by ZhSergey** [diadoc/diadocsdk-1c-docs#551]
Здравствуйте.

Скажите пожалуйста, можно ли узнать состояние документа, не открывая 
обработку Диадок или не заходя в личный кабинет?

То есть, контрагент в своем Диадоке подписывает документ, это информация 
где то на сервере у вас. А я могу как то получить информацию по нему?

**Comment by kulakovskaya** [comment]
Здравствуйте! Расскажите, пожалуйста, подробнее о своём сценарии работы.

**Comment by ZhSergey** [comment]
1 в 1с делается регистр сведений, например измерение это реализация, ресурс статус аналог статуса в диадоке
2 в 1с далется регламентное задание, которое отправляет запрос в диадок/контур по указанной реализации
3 получает отклик и в зависимости от него, меняет статус в регистре

при этом пользователь, не имеющий сертификата, доступ к обработке диадока 
формирует отчет и видит статус документа.

вот проблема в п2, можно ли это сделать? хранятся где то статусы документа?

**Comment by ButurlakinSemyon** [comment]
Добрый день!
В модуле Про есть возможность использовать [регламентное задание](https://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Reglamentnoye_Zadaniye.html), которое будет вычитывать ленту событий под служебной учетной записью.
Затем через ПМ, если статус документа изменился, записывать его в регистр в событии [ПослеУстановкиСтатусаДокумента](https://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Dopolnitel'nyye_Vozmozhnosti.html#id3).

**Comment by ZhSergey** [comment]
А что за модуль Про?

**Comment by ButurlakinSemyon** [comment]
Модуль Про, для взаимодействия с Апи Диадока, использует 1C.Plugin. Он предоставляет методы для асинхронной работы с криптографией, Web API и прочее. 
Про работает и на обычных, и на управляемых формах. Предназначен для клиентов, которым не подходит стандартное решение.
Также ознакомиться с информацией можно здесь:
https://www.diadoc.ru/blog/7795

**Comment by ZhSergey** [comment]
А как узнать, у нас про или Стандарт?

**Comment by ButurlakinSemyon** [comment]
1. Открыть модуль диадок в 1С. 
2. Ищем ссылку "Техподдержка" (в зависимости от модуля и версии, она может находится в разных местах, но скорее всего будет в левом нижнем углу).
3. В открывшемся окне ,переходим в "Техническую информацию". Здесь будет отображаться версия модуля и другая тех. информация.

Актуальные версии модулей:
Стандарт ОФ - 5.38.01
Стандарт УФ - 5.54.01
Про - 4.2.0

**Comment by ZhSergey** [comment]
![image](https://user-images.githubusercontent.com/75615762/101461623-38500c80-394c-11eb-89da-c243eb89c9f1.png)

**Comment by ZhSergey** [comment]
![image](https://user-images.githubusercontent.com/75615762/101461703-53bb1780-394c-11eb-8b97-67b15bf535c3.png)

**Comment by ButurlakinSemyon** [comment]
У вас модуль стандарт для управляемых форм, версия 5.44.01.762

**Comment by ZhSergey** [comment]
То есть для получение того, что хотелось бы, нужен модуль ПРО.
Цена вопроса?

**Comment by ButurlakinSemyon** [comment]
По данному вопросу можете обратиться к своему менеджеру. Если не знаете своего менеджера, обратитесь в [тех поддержку](https://www.diadoc.ru/support).

**Comment by ZhSergey** [comment]
А перейдя на про, надо что то встраивать в нашу конфигурацию? 
Регистр?

**Comment by ButurlakinSemyon** [comment]
При установке модуля Про возможны два варианта:
1. Использовать типовые объекты 1С
2. С добавлением [объектов](https://wiki.diadoc.ru/pages/viewpage.action?pageId=7669128) Диадок.

**Comment by ZhSergey** [comment]
И как это все работает?

есть задание, котороая счиитывает статус документов и хранит их например в реестре?
есть отчет показывающий документ и его статус ?

**Comment by ButurlakinSemyon** [comment]
Работа регламентного задания описана здесь - https://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Reglamentnoye_Zadaniye.html
Новые события (например, изменение статуса) записываются в справочник.
Далее при помощи функции "ПослеУстановкиСтатусаДокумента" можно записать значение нужного статуса в регистр или сам документ.

Отчета нет, статус отображается в списке документов при открытии модуля.

**Comment by ZhSergey** [comment]
Это все работает ииеннно в ПРО. В стандарт  я ниак не получу эти статусы?

Это не смогу у себя написать
// ОБРАБОТКА СОБЫТИЙ ЛЕНТЫ, В Т.Ч. ЗАГРУЗКА НОВЫХ ДОКУМЕНТОВ

КоличествоПорцийСобытий = 10; // Кол-во вычитываемых порций событий (каждая порция содержит не более 100 событий)
Для Каждого СтрокаОрганизации Из ОсновнойМодуль.ЭДО_Модуль_ТаблицаОрганизацийПользователя() Цикл
    ОсталосьСобытийВЛенте = ОсновнойМодуль.ЭДО_Модуль_ОбработатьНовыеСобытияДокументов(СтрокаОрганизации, КоличествоПорцийСобытий);
КонецЦикла;



???

**Comment by ZhSergey** [comment]
И цена переходя сна про какова?

**Comment by ButurlakinSemyon** [comment]
К сожалению, по цене сориентировать не могу. По данному вопросу можете обратиться к своему менеджеру. Если не знаете своего менеджера, обратитесь в [тех поддержку](https://www.diadoc.ru/support).

**Comment by ZhSergey** [comment]
Это все работает ииеннно в ПРО. В стандарт я ниак не получу эти статусы?

Это не смогу у себя написать
// ОБРАБОТКА СОБЫТИЙ ЛЕНТЫ, В Т.Ч. ЗАГРУЗКА НОВЫХ ДОКУМЕНТОВ

КоличествоПорцийСобытий = 10; // Кол-во вычитываемых порций событий (каждая порция содержит не более 100 событий)
Для Каждого СтрокаОрганизации Из ОсновнойМодуль.ЭДО_Модуль_ТаблицаОрганизацийПользователя() Цикл
ОсталосьСобытийВЛенте = ОсновнойМодуль.ЭДО_Модуль_ОбработатьНовыеСобытияДокументов(СтрокаОрганизации, КоличествоПорцийСобытий);
КонецЦикла;

???

**Comment by ZhSergey** [comment]
В телефонном звонке никто не может ничего объяснить!
Ответ не получен!

**Comment by volodkindv** [comment]
Подскажите номер обращения в техподдержку.

**Comment by ZhSergey** [comment]
Номер заявки 29170754.

Может долго переписывались. Попробую упростить вопрос.
1 при открытии обработки диадока отображается допустим реализация номер 1 от такого то и ее статус
2 у менеджера есть только список реализаций
3 в этом списке отображается реализация номер 1 от такого то и есть колокнка статус
4 на форме списка есть кнопка "Проверить статус"

Вопрос - могу ли я по кнопке вызвать метод какой то или функцию передав в нее эту реализацию и получить статус?

**Comment by volodkindv** [comment]
В модуле Стандарт нет простого способа получить статусы.
Есть сложный:
- подключить внешнюю компоненту
- авторизоваться
- прочитать ID документа в Диадок, связанного с Реализацией, из регистра "ЗначенияСвойствОбъектов / ДополнительныеРеквизиты" 
- конвертировать их в пару GUID (в регистре строка перекодирована в base32)
- во внешней компоненте получить объект Organization, оттуда - Document, из него  - уже Status.

**Comment by ZhSergey** [comment]
Ну хорошо, пусть сложный.. Но получается можно..

Это понятно, под пользователем которого есть доступ
подключить внешнюю компоненту
авторизоваться

прочитать ID документа в Диадок - а как мне узнать этот ид? я же заню толкьо сам докмент в 1с

**Comment by ZhSergey** [comment]
Если я сделал обработку с одной кнопкой, на форме поместил реквизит типа "реализация товаров и услуг",
то при нажатии надо
подключить внешнюю компоненту
авторизоваться

есть где то описание? какая компонента?

**Comment by volodkindv** [comment]
Этот репозиторий содержит как раз документацию к внешней компоненте: https://1c-docs.diadoc.ru/ru/latest/

**Comment by volodkindv** [comment]
Остальные вопросы требуют много времени на подготовку ответов и не относятся к багам / пожеланиям по внешней компоненте. Вы можете заказать внедрение или консультации по использованию компоненты, обратившись к своему менеджеру.

**Comment by ZhSergey** [comment]
По документации понятно, вроде как то что надо.
Пример
//Загрузка внешней компоненты
ИмяФайла = "C:\Temp\AddInDiadocAPI.dll";
ЗагрузитьВнешнююКомпоненту(ИмяФайла);


AddInDiadocAPI.dll - где ее взять?

**Comment by volodkindv** [comment]
https://1c-docs.diadoc.ru/ru/latest/Downloads.html здесь

**Comment by ZhSergey** [comment]
скачал.. в серверном варианте ее надо поместить на сервер же? или куда, что бы каждый пользователь моге ее увидеть?
рабоатет в терминальном режиме

**Comment by volodkindv** [comment]
Это зависит от того, какую архитектуру решения вы настроите. Будет она встроена в конфигурацию или лежать в справочнике, на общей сетевой папке или на сервере приложений 1С. Обычные формы или управляемые.

**Comment by ZhSergey** [comment]
управляемые формы.

хочу сделать регламентноре задание по получению статусов по документам.

**Comment by ZhSergey** [comment]
![image](https://user-images.githubusercontent.com/75615762/103076644-42763a00-45df-11eb-9c61-8f75b9aa76cd.png)
это обрабокта

**Comment by volodkindv** [comment]
Ваш вопрос выходит за рамки консультаций, которые мы готовы дать здесь.
Если у вас есть сложности с самостоятельной реализацией регламентного задания, вы можете заказать это решение у нас. Для этого надо обратиться к вашему менеджеру.

**Comment by ZhSergey** [comment]
Хорошо, скачал длл куда ее поместить?

**Comment by ZhSergey** [comment]
в документации не сказано..

**Comment by ZhSergey** [comment]
Загрузка AddIn компоненты

//Загрузка внешней компоненты
ИмяФайла = "C:\Temp\AddInDiadocAPI.dll";
ЗагрузитьВнешнююКомпоненту(ИмяФайла);

//Создание объекта DiadocInvoiceAPI
DiadocApi_ = Новый("AddIn.DiadocInvoiceAPI");
DiadocApi  = DiadocApi_.CreateObject();

//Задаем параметры подлючения к серверу
DiadocApi.ApiClientId = КлючРазработчика;
DiadocApi.ServerUrl   = "https://diadoc-api.kontur.ru:443";




а что такое КлючРазработчика? 
где брать?

**Comment by volodkindv** [comment]
Если вы хотите интегрироваться самостоятельно через API, вам надо приобрести ApiClientId (ключ разработчика).

**Comment by ZhSergey** [comment]
надо приобрести ApiClientId (ключ разработчика). - это тоже платно?

**Comment by volodkindv** [comment]
Да, это платно.

**Comment by volodkindv** [comment]
Этот тикет закрываю, т.к. он давно вышел за рамки изначального обсуждения.
