### ISSUE TITLE
Извлечь файл при получении

### ISSUE THREAD

**Issue by kvazymoda** [diadoc/diadocsdk-1c-docs#553]
Добрый день.
Подскажите, как правильно извлечь(сохранить на диск) произвольный файл из полученного документа?
  Полученный документ пытаюсь взять через: DocumentsTask.GetDocuments();
Сама Отправка, контрагентом, такого файла осуществлялась:  SendTask.AddDocumentFromFile("Nonformalized", "default", "v1", ПутькФайлуXML)
Спасибо.

**Comment by kulakovskaya** [comment]
Добрый день!
Правильно понимаю, что Вы уже каким-то образом пытались сохранить файл, но столкнулись с проблемой?
Для сохранения неформализованного документа можно применить, например, метод [Document.SaveAllContent](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html#Document.SaveAllContent).

**Comment by kvazymoda** [comment]
Добрый день. 
Нет, на тот момент я не мог понять, какой командой это делать.
Прощу уточнить, если я отправил несколько файлов, то команда  Document.SaveAllContent
сохранит их все?
 
  
>Среда, 9 декабря 2020, 16:34 +03:00 от kulakovskaya <notifications@github.com>:
> 
> 
>Добрый день!
>Правильно понимаю, что Вы уже каким-то образом пытались сохранить файл, но столкнулись с проблемой?
>Для сохранения неформализованного документа можно применить, например, метод  Document.SaveAllContent .
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
С Уважением,
Андрей Ямкин

**Comment by ButurlakinSemyon** [comment]
Добрый день!

Команда Document.SaveAllContent - сохраняет все файлы, относящиеся к документу (в т.ч. электронные подписи), в указанную директорию.

**Comment by kvazymoda** [comment]
Добрый день.
Благодарю!
  
>Пятница, 11 декабря 2020, 9:28 +03:00 от ButurlakinSemyon <notifications@github.com>:
> 
> 
>Добрый день!
>Команда Document.SaveAllContent - сохраняет все файлы, относящиеся к документу (в т.ч. электронные подписи), в указанную директорию.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
С Уважением,
Андрей Ямкин
