### ISSUE TITLE
Не удается отправить УКД (UniversalCorrectionDocument)

### ISSUE THREAD

**Issue by Alekseevda** [diadoc/diadocsdk-1c-docs#554]
Добрый день.
Использую com компоненту v5.32.0.627
Сам код отправки ниже:

	SendTask = ОрганизацияДляОбмена.CreatePackageSendTask2();
	SendTask.CounterAgentId = КонтрагентДиадок.Id;
	
	DocumentToSend = SendTask.AddDocument("UniversalCorrectionDocument", "КСЧФДИС", "ucd_05_02_01"); 
	DynamicContent = DocumentToSend.Content;
	
	UCD820_SellerContent = DynamicContent.UniversalCorrectionDocument;
	
	UCD820_SellerContent.DocumentNumber	 = НомерДокумента;
	UCD820_SellerContent.DocumentDate	 	= ДатаДокумента;
	UCD820_SellerContent.Currency 			= "643";
	UCD820_SellerContent.Function 			= "КСЧФДИС";
	UCD820_SellerContent.DocumentCreator 	= НаименованиеОрганизации + " ИНН/КПП:" + ИНН + "/" + КПП;	

	UCD820_SellerContent.CorrectionRevisionNumber = "1";	
	UCD820_SellerContent.CorrectionRevisionDate      = ДатаКорректируемогоДокумента;
	
	//Продавец
	UCD820_SellerContent.Seller.OrganizationReference.BoxId 	= ОрганизацияДляОбмена.Guid;	//BoxId 
	UCD820_SellerContent.Seller.OrganizationReference.OrgType	= "1";
	
	//Покупатель
	UCD820_SellerContent.Buyer.OrganizationReference.BoxId = КонтрагентДиадок.Guid;	//BoxId
	UCD820_SellerContent.Buyer.OrganizationReference.OrgType	= "1";
		
	//Подписант
	Signers = UCD820_SellerContent.Signers;
	NewSigner = Signers.AddItems();
	NewSigner.SignerDetails.SignerPowersBase = "Должностные обязанности";	//ОснПолн
	NewSigner.SignerDetails.SignerPowers = "0";	
	NewSigner.SignerDetails.SignerStatus = "1";	
	
	NewSigner.SignerDetails.SignerType = "1";		//ЮЛ
	NewSigner.SignerDetails.Inn = ИНН;	//ИННЮЛ
	NewSigner.SignerDetails.Position = ОрганизацияДляОбмена.Certificate.JobTitle;	//Должн
	NewSigner.SignerDetails.SignerOrganizationName = ОрганизацияДляОбмена.Name;	//НаимОрг
	
	NewSigner.SignerDetails.LastName   = Фамилия;
	NewSigner.SignerDetails.FirstName  = Имя;
	NewSigner.SignerDetails.MiddleName = Отчество;	
	//Подписант	
	
	//СодФХЖ3 (факт хозяйственной жизни)
	UCD820_SellerContent.EventContent.TransferDocDetails 	= "УПД № " + Строка(OriginalDocumentNumber) + " от " + ДатаУПД;	
	UCD820_SellerContent.EventContent.OperationContent		= "Изменение стоимости товаров и услуг";	//СодОпер
	UCD820_SellerContent.EventContent.NotificationDate		= Формат(ТекущаяДата(), "ДЛФ=ДФ");	        //ДатаНапр

	//Основание корректировки (ОснКорр)
	NewCorrectionBase = UCD820_SellerContent.EventContent.AddCorrectionBase();
        NewCorrectionBase.BaseDocumentName = "Договор";
	NewCorrectionBase.BaseDocumentNumber = ДоговорНомер;
	NewCorrectionBase.BaseDocumentDate = ДоговорДата;

        //TotalsDec (Итого к уменьшению)
	UCD820_SellerContent.Table.TotalsDec.Total = Сумма;
	UCD820_SellerContent.Table.TotalsDec.TotalWithVatExcluded = СуммаБезНДС;
	UCD820_SellerContent.Table.TotalsDec.Vat = СуммаНДС;

	NewItem = UCD820_SellerContent.Table.Items.AddItem();
	NewItem.Product = Наименование; 	//НаимТов

	NewItem.OriginalValues.Unit 		= Код;	
	NewItem.OriginalValues.Quantity     = КоличествоДо;
	NewItem.OriginalValues.Price           = ЦенаДо;
	NewItem.OriginalValues.TaxRate 	= "20%";
	NewItem.OriginalValues.SubtotalWithVatExcluded = СуммаБезНДСДо;
	NewItem.OriginalValues.Subtotal		= СуммаДо;
	NewItem.OriginalValues.Vat			= СуммаНДСДо;
		
	//значения после корректировки
	NewItem.CorrectedValues.Unit		= Код;   
	NewItem.CorrectedValues.Quantity    = КоличествоПосле;
	NewItem.CorrectedValues.Price       = ЦенаПосле;
	NewItem.CorrectedValues.TaxRate 	= "20%";
	NewItem.CorrectedValues.SubtotalWithVatExcluded = СуммаБезНДСПосле;
	NewItem.CorrectedValues.Subtotal	= СуммаПосле;
	NewItem.CorrectedValues.Vat		= СуммаНДСПосле;
		
	//Значения самой корректировки
	NewItem.AmountsDec.Subtotal		= СуммаКорректировки;
	NewItem.AmountsDec.SubtotalWithVatExcluded = СуммаКорректировкиБезНДС; 
	NewItem.AmountsDec.Vat			= СуммаНДСКорректировки;

	//Счет-фактура (invoice)
	Invoice = UCD820_SellerContent.Invoices.AddInvoice();
	Invoice.Date	   = ДатаСФ;
	Invoice.Number   = НомерСФ;
	
	ОтправленныйПакет = SendTask.Send();

Текст ошибки:
"Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: Документ не может быть отправлен в указанном формате"

Пробовал менять версию на "ucd_05_01_02" - но тогда ошибка поля "TaxRate" - "20%"

Что я делаю не так?

**Comment by ButurlakinSemyon** [comment]
Добрый день!
Пытаетесь отправить УКД или исправительную УКД?

**Comment by Alekseevda** [comment]
исправительную УКД

**Comment by ButurlakinSemyon** [comment]
Тогда нужно использовать тип "UniversalCorrectionDocumentRevision"

**Comment by Alekseevda** [comment]
Да, с типом "UniversalCorrectionDocumentRevision" документ ушел.

**Comment by Alekseevda** [comment]
Подскажите, как правильно отправлять просто УКД? Что бы окончательно все прояснилось. Спасибо.

**Comment by ButurlakinSemyon** [comment]
Документ, который вы прислали имеет версию ucd_05_01_03. Попробуйте использовать ее.

**Comment by Alekseevda** [comment]
Для документа с версией "ucd_05_01_03"
DocumentToSend = SendTask.AddDocument("UniversalCorrectionDocument", "КСЧФДИС", "ucd_05_01_03");

Опять возвращает ошибку:
"Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: Документ не может быть отправлен в указанном формате"

**Comment by kulakovskaya** [comment]
Добрый день! Проверьте, пожалуйста, что отправляете именно корректировочный документ, а не исправление к нему.

**Comment by Alekseevda** [comment]
Спасибо, понял свою ошибку. Теги "CorrectionRevisionNumber" и "CorrectionRevisionDate" надо заполнять только для документа "UniversalCorrectionDocumentRevision".
