### ISSUE TITLE
Ошибка отправки PackageSendTask2.Send при DelaySend = true

### ISSUE THREAD

**Issue by Andy28ts** [diadoc/diadocsdk-1c-docs#555]
Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:403, HTTP error: У вас нет доступа к документу

Делаю из 1С отложенную отправку
посмотрел в отладчике. стандартная обработка  Diadoc1C_UF_5_45_01.epf работает, а если копирую методы (все под одним и тем же пользователем) в свой код - получаю эту ошибку доступа.

В чем причина?

**Comment by kulakovskaya** [comment]
Добрый день! 
Какой код Вы скопировали? Как в результате заполнили PackageSendTask2? В какой момент возникает ошибка?
Также можете приложить BoxId организации, от которой отправляете документ.
