### ISSUE TITLE
Ошибка подключения по сертификату: CreateConnectionByCertificate 

### ISSUE THREAD

**Issue by kvazymoda** [diadoc/diadocsdk-1c-docs#556]
Добрый день коллеги.
Спасибо что быстро отвечаете, ценим 8-)

Вопрос такой, на клиенте пробовали все работает ок. Решили перейти на серверный вариант,  код такой :
(библиотеку для ком-сборки зарегистрировали )

DiadocApi = Новый COMОбъект("Diadoc.DiadocClient"); // тут ОК
DiadocApi.ApiClientId = ВернутьКонстанту("КлючРазработчика");  // тут ОК
DiadocApi.ServerUrl   = ВернутьКонстанту("АдресСайта"); // "https://diadoc-api.kontur.ru:443";   , тут тоже ОК
	
Certificates = DiadocApi.GetPersonalCertificates();                      // Ок
ОтпечатокСертификата = Certificates.GetItem(0).Thumbprint;   // Ок
DiadocConnection = DiadocApi.CreateConnectionByCertificate(ОтпечатокСертификата);     // Ошибка!
________________________________________________________________
сообщение об ошибке:
{ОбщийМодуль.ОбменСДиадок.Модуль(33)}: Ошибка при вызове метода контекста (CreateConnectionByCertificate)
по причине:
Произошла исключительная ситуация (DiadocCom.CreateConnectionByCertificate): ##100[Ошибка сервера Диадок]code:400, HTTP error: <html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>

**Comment by kulakovskaya** [comment]
Добрый день! Можем предположить, что используется прозрачный прокси или еще какой-то посредник между компонентой и сервером ДД АПИ.

**Comment by kvazymoda** [comment]
Судя по Вашему ответу, хочу уточнить следующее:
1 Правильно ли мы поняли, что входящий к Вам трафик не проходит от нас, и проблема на нашей стороне?
2 Дело в том, что и клиентский и серверный вариант мы тестируем на одной и той же машине, под одним и тем же пользователем. На ней же установлены обе DLL. При этом, клиентский вариант работает, серверный нет.

**Comment by kvazymoda** [comment]
Коллеги, добрый день.
Есть ли комментарий? Стоит подождать?

**Comment by volodkindv** [comment]
Добрый день. Вводные такие:
1. Описанную ошибку мы на своей стороне в логах не видим: 400 The plain HTTP request was sent to HTTPS port
2. Исходный код в Addin и COM версиях компоненты идентичен.

Наиболее вероятно, что что-то происходит внутри вашей сети.

Укажите точную версию и разрядность компоненты.

Тестирование "клиентского" и "серверного" варианта проходит в рамках одного сеанса? Для чистоты эксперимента лучше завершать сеанс после каждого тестирования.

**Comment by kvazymoda** [comment]
1 Возможно прокси-сервер есть, выясняю сейчас. В таком случае, каков код(листинг) для подключения соединения с использованием прокси-сервера?
2 ок.
Подключаемые компоненты: 
DiadocCom_5_32_2_632_x64.dll   - для серверного варианта
Diadoc_5_32_0_627_x64.dll  -  для клиентского варианта
Да, в рамках одного сеанса происходит тестирование

**Comment by volodkindv** [comment]
1. 
```
DiadocApi.ProxySettings.Url = "url";
DiadocApi.ProxySettings.Login = "admin";
DiadocApi.ProxySettings.Password = "********";
```

https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html?highlight=ProxySettings.

**Comment by kvazymoda** [comment]
Добрый день.
Разобрался. Моя ошибка.
В клиентском варианте был правильный URL на ваш сайт. В серверном варианте забыл указать: https
 
Спасибо. Можно закрыть.
  
>Среда, 16 декабря 2020, 11:19 +03:00 от Данила Володькин <notifications@github.com>:
> 
> 
>Добрый день. Вводные такие:
>*  Описанную ошибку мы на своей стороне в логах не видим: 400 The plain HTTP request was sent to HTTPS port
>*  Исходный код в Addin и COM версиях компоненты идентичен.
>Наиболее вероятно, что что-то происходит внутри вашей сети.
>Укажите точную версию и разрядность компоненты.
>Тестирование "клиентского" и "серверного" варианта проходит в рамках одного сеанса? Для чистоты эксперимента лучше завершать сеанс после каждого тестирования.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
С Уважением,
Андрей Ямкин
