### ISSUE TITLE
Ошибка при отправке неформализованного документа-файла

### ISSUE THREAD

**Issue by kvazymoda** [diadoc/diadocsdk-1c-docs#559]
Добрый день, коллеги.
Имеем ошибку при выполнении кода, она возникает не всегда, но часто.
В чем может быть дело? Что мы не так сделали?
__________
ПутькФайлуXML = "E:\Users\A.Popov\AppData\Local\Temp\v8_B390_7.xml";
Third_DocumentToSend = SendTask.AddDocumentFromFile("Nonformalized", "default", "v1", ПутькФайлуXML);

Ошибка: 
   Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, 
         HTTP error: MessageToPost.DocumentAttachments[0]: Имя файла не должно содержать символы < > : “ / \ | ? * или 
          заканчиваться точкой, пробелом.

**Comment by volodkindv** [comment]
Добрый день.
Попробуйте так:
```
ПутькФайлуXML = "E:\Users\A.Popov\AppData\Local\Temp\v8_B390_7.xml";
Third_DocumentToSend = SendTask.AddDocumentFromFile("Nonformalized", "default", "v1", ПутькФайлуXML);

		Item = Third_DocumentToSend.AddMetadata();
		Item.Key	 = "FileName";
		Item.Value	 = "имя_файла_для_клиента";

```

**Comment by kvazymoda** [comment]
Добрый день. 
Заработало, спасибо. 



Отправлено из мобильной Почты Mail.ru


среда, 23 декабря 2020 г., 12:10 +0300 от notifications@github.com  <notifications@github.com>:
