### ISSUE TITLE
Объект  Resolution не Свойство ResolutionType неправильно описано в инструкции

### ISSUE THREAD

**Issue by ShibaevAnton** [diadoc/diadocsdk-1c-docs#56]
Добрый день.

Документация: http://1c-docs.diadoc.ru/ru/latest/Resolution.html

Свойство ResolutionType принимает одно из следующих значений:

“SignatureRequest” - запрос на подпись документа
“SignatureApprove” - подписать документ
“SignatureDisapprove” - отказать в подписи документа
“ResolutionRequest” - запрос на огласование документа
“ResolutionApprove” - согласовать документ
“ResolutionDisapprove” - отказать в согласовании документа
“RevocationApprove” - согласовать аннулирование документа
“RevocationDisapprove” - отказать в аннулировании документа
“RevocationRequest” - запрос на аннулирование документа
“FormalizedSignatureDisapprove” - формализованный отказ в подписи
“InvoiceCorrectionRequest” - уведомление об уточнении счета-фактуры

Они изменились?

**Comment by ShibaevAnton** [comment]
У документа это ResolutionType = SignatureRequested... опечатка в инструкции?

**Comment by denver069** [comment]
Антон вы правы в http://1c-docs.diadoc.ru/ru/latest/Resolution.html очепятка, обязательно исправим. Правильное значение SignatureRequested.

**Comment by denver069** [comment]
Антон, я некорректно ответил на ваш вопрос!

На самом деле в документации действительно была ошибка, но совсем иного свойства.
В поле [Document.ResolutionStatus](http://diadocsdk-1c.readthedocs.io/ru/latest/Document.html) был не корректно указан объект, там на самом деле используется [ResolutionStatus](http://diadocsdk-1c.readthedocs.io/ru/latest/ResolutionStatus.html) и как раз в нем поле Type = **SignatureRequested**
А вот в коллекции Document.Resolutions элементы коллекции [Resolution](http://diadocsdk-1c.readthedocs.io/ru/latest/Resolution.html) и в них поле ResolutionType = **SignatureRequest**.

Спасибо за участие!
