### ISSUE TITLE
Как освободить Com-object DiadocComApi при серверном вызове

### ISSUE THREAD

**Issue by NickVStepin** [diadoc/diadocsdk-1c-docs#560]
Платформа 1С 8.1, работу с Диадок выполняем на стороне сервера. Соответственно для подключения используем
ДиадокАпи = Новый ComObject("Diadoc.DiadocClient");
Когда обращение к Диадок больше не нужно, то все переменные, включая ДиадокАпи = Неопределено.
Но серверный процесс все равно держит библиотеку DiadocComApi.dll. В итоге невозможно обновить библиотеки Диадок без перезагрузки серверного процесса 1с, что крайне не удобно, ибо работаем 24х7

**Comment by volodkindv** [comment]
Добрый день.
Увы, платформа 1С не предоставляет механизма для освобождения COM-объектов. Есть ПодключитьВнешнююКомпоненту(), а ОтключитьВнешнююКомпоненту() нет.

**Comment by NickVStepin** [comment]
Ну на сервере даже ПодключитьВнешнююКомпоненту недоступно, поэтому только Новый ComObject...

**Comment by volodkindv** [comment]
Единственное решение, которое приходит в голову, - переход на 8.3 и вынос регламентных заданий в отдельный процесс.
