### ISSUE TITLE
Редактирование макета формализованного документа

### ISSUE THREAD

**Issue by lanrootdiadoc** [diadoc/diadocsdk-1c-docs#561]
День добрый. Хочу в документе "СчетНаОплату" добавить перед табличной частью вывод комментария (требование Вымпелком).. 
Добавил в макет в обработке область, но не могу понять как вывести её и заполнить параметр. В старой версии так делал. Тех поддержка написала, что можно через подключаемый модуль.
Подключил модуль, настроил отладку вложенных обработок. 
1. Можно ли отключить кэширование подключаемого модуля? Не работают точки остановки, только можно тестировать в самом модуле основной обработки и туда переносить (процедура ОбработкаСобытияПодключаемогоМодуля)
2. При открытии документа "СчетНаОплату" программа не заходит в покдлючаемый модуль, она заходит туда только при выводе списка документов "СчетНаОплату". Как добавить в макет еще одну область и заполнить её? Где это ловить?
Использую КА 2.4.6.200 + Модуль УФ 5.38.19.465
С уважением, Ларин Сергей 
8-926-376-09-55

**Comment by volodkindv** [comment]
Добрый день.
Этот репозиторий относится к внешней компоненте 1С. С вопросами по модулю УФ следует обращаться в техподдержку.

**Comment by lanrootdiadoc** [comment]
День добрый. Они меня сюда отправили.

**Comment by lanrootdiadoc** [comment]
Цитирую: Вы можете задать любой вопрос по поводу примеров кода, ошибок при написании интеграционного решения на https://github.com/diadoc/diadocsdk-1c-docs, в верхней части интерфейса будет закладка Issues.  
 
Номер вашего обращения - 29184930.

**Comment by acharushkin** [comment]
@lanrootdiadoc , а зачем для отладки печатной формы запускать модуль Диадок.Стандарт? Отлаживайте её как обычную ВПФ, затем просто укажите её в настройках отправки.
