### ISSUE TITLE
Как отправить документ в Диадок с помощью компоненты AddIn?

### ISSUE THREAD

**Issue by metod1c** [diadoc/diadocsdk-1c-docs#562]
Здравствуйте.

Имеется нетиповая конфигурация 1С. Необходимо отправить документ в Диадок.

В документации
https://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html#
не понятно, что из себя представляет параметр Counteragent и как его получить?
Что из себя представляется процедура ЗаполнитьДинамическийКонтентДокумента() в первом варианте отправки?
Как получить файл xml во втором варианте отправки?

**Comment by IrinaShmonina** [comment]
@metod1c , здравствуйте
Про контрагента можно узнать в разделе [Counteragent](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Counteragent.html?highlight=Counteragent#counteragent)

Про динамический контент можно узнать в разделе [DynamicContent](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html)

Второй вариант, это когда у вас уже есть где-то готовая xml и вам нужно ее отправить. Вам нужно указать что это за документ и путь до него
Second_DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01", "С:\\Moй УПД.xml");

Подробнее про PackageSendTask2 можно посмотреть в разделе [PackageSendTask2](https://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html)

**Comment by metod1c** [comment]
@IrinaShmonina 
Спасибо. Про контрагента разобрался.
Не могу разобраться, как заполнить документ, где указать товары и их маркировку?

**Comment by IrinaShmonina** [comment]
@metod1c, описание полей документа можно узнать из XSD, получаемой методами [Organization.SaveUserDataXSD()](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#organization-saveuserdataxsd), [Organization.GetBase64UserDataXSD()](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetBase64UserDataXSD), или, используя объект [Reflector](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Reflector.html).

Есть статья [как получить описание полей через Reflector](https://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_reflect_object.html)

**Comment by metod1c** [comment]
@IrinaShmonina
Может у вас есть пример заполнения УПД через компоненту? Это бы сильно упростило понимание механизма.

**Comment by volodkindv** [comment]
Готового кода для выкладки сюда нет. Тот, что есть, не будет полезен.
Товары находятся в InvoiceTable, наполнять так:
```
	InvoiceTableItem = InvoiceTable.AddItem();
	Заполнить_DynamicInvoiceTableItem(InvoiceTableItem);
```
Данные о маркировке лежит внутри InvoiceTable.Item в коллекции ItemIdentificationNumbers. Заполняется так:

```
	InvoiceTableItem.ItemIdentificationNumbers.AddPackageId("_PackageId_");  // для упаковок
	InvoiceTableItem.ItemIdentificationNumbers.AddUnit("_Unit_");  // для единиц
```
