### ISSUE TITLE
Подписать документ при использовании:  SendTask.AddDocumentFromFile()

### ISSUE THREAD

**Issue by kvazymoda** [diadoc/diadocsdk-1c-docs#563]
Добрый день, Коллеги.

Использую конструкцию:
Third_DocumentToSend = SendTask.AddDocumentFromFile("XmlAcceptanceCertificate", "default", "rezru_05_02_01",ПутькФайлуXML);    // работает

// далее
   SendTask.AddEncryptCertificate(мПараметры.Сертификат);    // Метод объекта не обнаружен (AddEncryptCertificate)
Похоже этот метод устарел, так написано в документации.

Как правильно подписать/зашифровать отправляемые документ? Дадите код?

**Comment by ButurlakinSemyon** [comment]
Добрый день!
Используйте задание [PackageSendTask2](https://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html).
Примеры отправки документов есть [здесь](https://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html).
За шифрование документа отвечает свойство "[IsEncrypted](https://1c-docs.diadoc.ru/ru/latest/ComObjects/CustomDocumentToSend.html?highlight=isencrypted)".

**Comment by kvazymoda** [comment]
Добрый день.
В том и дело, мы используем ровно то, что вы перечислили.
Но к контрагенту-получателю, документ приходит, он его печатает, из вебинтерфейс-диадок, и на нем нет синей подписи, с указанием : кто отправил и когда отправил. Поэтому у нас возник вопрос, что документ не подписан, и  как правильно подписать/зашифровать документ? И что мы сделали не так? Привожу, наш, полный код, он полностью рабочий, но нет синей подписи у получателя на полученном от нас документе:
_____________________________________________________
имяКомпоненты = "AddIn.DiadocInvoiceAPI";   
ПодключитьВнешнююКомпоненту("AddIn.DiadocInvoiceAPI");  
DiadocApi_ = Новый("AddIn.DiadocInvoiceAPI");
DiadocApi  = DiadocApi_.CreateObject();
//Задаем параметры подлючения к серверу
DiadocApi.ApiClientId  = КлючРазработчика;
DiadocApi.ServerUrl      = "https://diadoc-api.kontur.ru:443";
//Получение списка сертификатов
Certificates = DiadocApi.GetPersonalCertificates();
мОснованяОрг = ОбменСДиадок.ВернутьКонстанту("ОсновнаяОрганизация");
ИННОрганизации = ПолучитьРеквизитОбъектаНаСервере(мОснованяОрг,"ИНН");
СтруктураСертификата = ПолучитьОтпечатокСертификата(Certificates, ИННОрганизации); // Отпечаток, Сертификат
 
DiadocConnection = DiadocApi.CreateConnectionByCertificate(ОтпечатокСертификата);
// Получение списка организаций
OrganizationList = DiadocConnection.GetOrganizationList();
Ц = 0;
Пока Ц < OrganizationList.Count() Цикл       // Орг
        // Получение конкретной организации
        Organization = OrganizationList.GetItem(ц);
        Сообщить("Определена основная организация:" + Organization.Name);
        Ц = Ц + 1;
КонецЦикла;
СтрокаИНН = Сокрлп(ЭтаФорма.Элементы.КонтрагентИНН.ТекстРедактирования);
CounteragentList = Organization.GetCounteragentListByInnList(СтрокаИНН); 
        
Если CounteragentList.IsCompleted Тогда           // Контрагенты
           РезультатЗапроса = CounteragentList.Result;
        Item = РезультатЗапроса.GetItem(0);
        Counteragent = Item.Counteragent;                   
КонецЕсли;
SendTask = Organization.CreatePackageSendTask2();   // ок
 
SendTask.CounterAgentId = Counteragent.Id;   
МассДокКОтправке = ПолучитьВыборкуДокументовДляОтправки(мОрганизация,мКонтрагент);  // ок
 Для каждого элем Из МассДокКОтправке Цикл
       ПутькФайлуXML = СформироватьВременныйФайл(элем.Файл);  // ок
       Third_DocumentToSend = SendTask.AddDocumentFromFile("XmlAcceptanceCertificate", "default", "rezru_05_02_01",ПутькФайлуXML);   // ок,    Загрузили «Акт о выполненных работах»
       Third_DocumentToSend.Comment = "Это тест!!";
       ОтправленныеДокументы = SendTask.Send();    // ок
КонецЦикла;
________________________________________________
Что не так сделали?
 
Спасибо.
  
>Пятница, 25 декабря 2020, 14:03 +03:00 от ButurlakinSemyon <notifications@github.com>:
> 
> 
>Добрый день!
>Используйте задание  PackageSendTask2 .
>Примеры отправки документов есть  здесь .
>За шифрование документа отвечает свойство " IsEncrypted ".
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
С Уважением,
Андрей Ямкин

**Comment by ButurlakinSemyon** [comment]
Можете прислать ссылку на документ?

**Comment by kvazymoda** [comment]
вот сам файл, ссылка:
 
https://cloud.mail.ru/public/NHdT/iYQrzKqmc
  
>Пятница, 25 декабря 2020, 15:52 +03:00 от ButurlakinSemyon <notifications@github.com>:
> 
> 
>Можете прислать ссылку на документ?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
С Уважением,
Андрей Ямкин

**Comment by ButurlakinSemyon** [comment]
Я имел ввиду ссылку на документ в диадоке)

**Comment by kvazymoda** [comment]
вот ссылка:
https://diadoc.kontur.ru/27262ac5-c910-41ef-b437-4d9fd0efce59/Document/Show?letterId=8fb5503b-b538-47b2-9e76-d25086f98e84&documentId=c47d53b6-2290-487c-b5ca-b2f014e0a81f
 
Отправляем от Организации: ВоркХаус
  
>Пятница, 25 декабря 2020, 16:32 +03:00 от ButurlakinSemyon <notifications@github.com>:
> 
> 
>Я имел ввиду ссылку на документ в диадоке)
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
С Уважением,
Андрей Ямкин

**Comment by ButurlakinSemyon** [comment]
![F83BF807-10C7-4548-ACDA-8151401D5075](https://user-images.githubusercontent.com/74642650/103139460-2fa65700-46fe-11eb-9a9e-6fca16e2770e.jpeg)
В вебе при выводе на печать документа подпись есть. Также что документ подписан видно сверху на форме документа, там где отображается история действий.

**Comment by kvazymoda** [comment]
Спасибо, коллеги. Разбираемся.
Прошу картинку с печатью, удалить из ветки, комм. информация.

**Comment by kvazymoda** [comment]
Спасибо, разобрались.
Закроем.
