### ISSUE TITLE
Вероятная ошибка в компоненте ЭДО (версия 5.32.3.633) при работе с УКД

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#564]
Добрый день.

**Общая информация для упрощения «разбора полётов»:**
Организация:		«ДНС Ритейл»
ИНН:			2540167061
КПП:			254301001
КПП2:			783450001
ID организации:	c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru		
ID участника ЭДО:	2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: COM x64 5.32.3.633.

**Возникшая проблема**
Тестируя отправку исходящих УКД (**ucd_05_01_03**), натолкнулись на странное поведение в обработке данных состава УКД.
Мы почти на 100% уверены, что это какая-то ошибка.

**Суть:**
При попытке отправки УКД (**ucd_05_01_03**), в которых происходит уменьшение сумм по строке состава, была замечена проблема:

Рассмотрим на примере тестового документа со следующим составом:
![изображение](https://user-images.githubusercontent.com/33707226/103267747-f7549080-49fd-11eb-984e-46f80853533c.png)

Т.е. в строке №1 товар после корректировки полностью исчезает, в строке №2 - появляется новый товар, в строке №2 цена на товар уменьшается и в строке №4 цена увеличивается.
По группам "Суммы к увеличению" и "Суммы к уменьшению" видно, что изменения касаются всех трех сумм - Суммы без НДС, суммы НДС и полной суммы с НДС.

Попробуем отправить такой документ и посмотрим, что будет в данных задачи на отправку перед отправкой и какой документ будет сформирован и отправлен.

Формируем данные на отправку с использованием **PackageSendTask2**.

Общие данные документа (отладчик 1С):
![изображение](https://user-images.githubusercontent.com/33707226/103267761-020f2580-49fe-11eb-88a2-74a386eba106.png)
Итоговые значения по изменению сумм заполнены.

**Данные строк состава:**

№1
![изображение](https://user-images.githubusercontent.com/33707226/103267805-1fdc8a80-49fe-11eb-8514-925fd5375c30.png)

№2
![изображение](https://user-images.githubusercontent.com/33707226/103267819-2539d500-49fe-11eb-87d3-d509fb1de3da.png)

№3
![изображение](https://user-images.githubusercontent.com/33707226/103267827-2a971f80-49fe-11eb-8273-a6ac0b2e9bdd.png)

№4
![изображение](https://user-images.githubusercontent.com/33707226/103267833-2f5bd380-49fe-11eb-804a-87789046254b.png)
Видно, что в строках состава присутствуют данные по всем трем суммам - без НДС, НДС и с НДС.

Отправляем документ с использованием **SendAsync()**.

Смотрим данные отправленного исходящего документа (отладчик 1С):
![изображение](https://user-images.githubusercontent.com/33707226/103267991-72b64200-49fe-11eb-8725-07fe466555bc.png)
Данные по общему изменению полной суммы и суммы НДС есть.

**Смотрим данные состава документа:**

Данные итогов документа:
![изображение](https://user-images.githubusercontent.com/33707226/103268018-7b0e7d00-49fe-11eb-9062-397c419b997e.png)
Также есть все данные по всем суммам.

По отдельным строкам состава:

№1
![изображение](https://user-images.githubusercontent.com/33707226/103268031-82ce2180-49fe-11eb-8cfa-9df3c3b5b890.png)

### Ошибка!!! Пропала сумма уменьшения НДС!

№2
![изображение](https://user-images.githubusercontent.com/33707226/103268044-8a8dc600-49fe-11eb-9944-43c40495d013.png)
Суммы увеличения без ошибок.

№3
![изображение](https://user-images.githubusercontent.com/33707226/103268060-92e60100-49fe-11eb-920b-4f065162cc4a.png)

### Ошибка!!! Пропала сумма уменьшения НДС!

№4
![изображение](https://user-images.githubusercontent.com/33707226/103268078-9a0d0f00-49fe-11eb-9174-db4a219cd5c4.png)
Суммы увеличения без ошибок.

**В итоге документ изменяется так:**

Что отправляли:
![изображение](https://user-images.githubusercontent.com/33707226/103268087-a002f000-49fe-11eb-94c4-f0d51209d90a.png)

Что реально отправилось:
![изображение](https://user-images.githubusercontent.com/33707226/103268099-a5f8d100-49fe-11eb-8280-c0f18f7d1aa4.png)

### По итогу получаем, что у нас пропадает сумма НДС в блоке уменьшения сумм по строке корректировки!

Эта же "кривая" информация по суммам формируется и в печатной форме документа:
![изображение](https://user-images.githubusercontent.com/33707226/103268635-84e4b000-49ff-11eb-826e-70d638233e3a.png)

**Показанная ситуация повторяется на любых отправляемых УКД.**

Собственно, хотелось бы узнать - это какое-то особенное поведение компоненты и так и должно быть (тогда почему?!)
или же это ошибка. Если ошибка, то большая просьба исправить поведение компоненты.

Спасибо.

**Comment by volodkindv** [comment]
Здравствуйте.
Приложите, пожалуйста, ссылку на документ, отправленный в таком виде, и сам xml файл, полученный при отправке.

**Comment by JohnSergeev** [comment]
Добрый день. извиняюсь за задержку с ответом - попали как раз на праздники.
С новым годом!

Документы передавались в тестовом контуре из одного тестового ящика в другой.

Документ:
Id = 22dd99f2-d2cd-4887-aac2-7edd34a713063b0f7ed5-2dd4-45d5-b446-4bf2386dab65

**Отправлено из:**
Тестовая организация №2918743
0d7430bf4a9d4acca06e3ba0720e3e91@diadoc.ru
ИНН 9629187430 КПП 962901000

Path = /0d7430bf-4a9d-4acc-a06e-3ba0720e3e91/Document/Show?letterId=22dd99f2-d2cd-4887-aac2-7edd34a71306&documentId=3b0f7ed5-2dd4-45d5-b446-4bf2386dab65

Архив отправленного документа: [Исходящий.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/5794022/default.zip)

**Получено в:**
Тестовая организация №9683568
8015d19a35ef421f84d12fbc7258c309@diadoc.ru
ИНН 9696835687 КПП 969601000

Path = /8015d19a-35ef-421f-84d1-2fbc7258c309/Document/Show?letterId=22dd99f2-d2cd-4887-aac2-7edd34a71306&documentId=3b0f7ed5-2dd4-45d5-b446-4bf2386dab65

Архив полученного документа: [Входящий.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/5794021/default.zip)

Спасибо.

**Comment by volodkindv** [comment]
С праздниками вас!
Мы поразбирались. В вашем примере "Строка 1", "ТоварНеСтало". Вы заполняете одновременно и AmountsInc, и AmountsDec. В полях секции AmountsInc вы ставите нули. Но с точки зрения ядра Диадок, нули - это не пустые значения. Дальше при построении XML по формату ФНС срабатывает логика: если заполнена секция AmounstInc, то пишем в XML СумУвел, а СумУм не заполняем. В вашем случае AmounstInc считается заполненной.
Решение простое: по строке 1 не заполнять нулями поля секции AmounstInc. Там останутся пустые строки, и XML файл будет построен корректно.
С остальными строками смысл такой же.

**Comment by JohnSergeev** [comment]
Ясно. Спасибо. Очень не явное поведение.

Попробуем у себя переделать на пустые строки в таких ситуациях. Посмотрим, что выйдет.

**Comment by volodkindv** [comment]
Мы пока разбираемся, можно ли тут добавить очевидности и в каком виде.

**Comment by JohnSergeev** [comment]
Ну, например, можно про эту особенность заполнения полей просто указать в документации!

**Comment by JohnSergeev** [comment]
Добрый день. Переделали у себя для заполнения AmountsDiff чтобы вместо "0" для нулевых значений в DynamicContent писалось бы "" (пустая строка). После этого все отработало как надо.

Спасибо за разъяснение. Тему по идее можно закрывать.

**Comment by i82** [comment]
Мы планируем внести комментарий в xsd, поменять поведение, к сожалению, не получится.
В новом формате корректировки, который становится обязательным с 1 октября сразу учтём эту проблему

**Comment by JohnSergeev** [comment]
Да это и не проблема в общем-то.
Просто описать такое поведение в документации было бы вполне достаточно. 
И кроме XSD неплохо бы это отметить в документации здесь: https://diadocsdk-1c.readthedocs.io/ru/latest/index.html

Спасибо.
