### ISSUE TITLE
Документ не может быть отправлен в указанном формате

### ISSUE THREAD

**Issue by alexandra582** [diadoc/diadocsdk-1c-docs#565]
Сделали доработку модуля.
Цель: отправка одновременно 3-ех форматов документов - ТОРГ12, СФ, УПД (типовые настройки этого не позволяют)

Для этого для каждого документа СФ добавили аналогичную строку, перезаполнили 

СтрокаНовая.DocumentType = "UniversalTransferDocument";
СтрокаНовая.ТипДокумента = "УПД Счф Доп";
СтрокаНовая.ФорматОтправки.ИмяТипа = "UniversalTransferDocument";
СтрокаНовая.ФорматОтправки.ФункцияДокумента = "СЧФДОП";
СтрокаНовая.ФункцияУПД = "СЧФДОП";

Сделала также, чтоб документы находились в одном пакете.

При просмотре списка все хорошо, документы формируются.
Но при отправке документов Накладная, СФ (флаги без УПД) выходит ошибка Документ не может быть отправлен в указанном формате 

(code 400. HTTP error MessagetoPost.DocumentAttachment[1]: Документ не может быть отправлен в указанном формате)

Хотелось бы узнать, в чем может быть причина?

**Comment by volodkindv** [comment]
Добрый день.
Укажите точную версию модуля. В каком именно месте вносили правки?

**Comment by alexandra582** [comment]
Добрый день!Тех. информация модуля:  Интеграция:Версия модуля: 5.37.02.297Версия компоненты: 5.32.3.633Модуль интеграции: Модуль_ИнтеграцияУПП13Модуль типовой: НетПодключаемый модуль: В справочникеПуть к подключаемому модулю: Справочник: Внешние обработкиЭлемент: Диадок подключаемый модульUserID: 71ac42cf-d607-4301-af22-338bcde27f89Отпечаток сертификата:  не найден  Настройки:Отладка вложенных обработок: ЗапрещенаРежим совместимости форматов: Да  Программное обеспечение:Версия ОС: version 10.0  (Build 17763)Версия платформы: 8.3.15.1869Тип платформы: Windows x86Вид клиента: Толстый клиент обычное приложениеКонфигурация: Управление производственным предприятием, редакция 1.3 (1.3.146.2) Вносила измененияДобавленные строки в коде выделены жирным шрифтом. 1. Добавила в список УПД ФормаВыгрузкиПроцедура ОбновитьСписокСтраницыОтправкиВДиадок()    СписокДокументовДляВыгрузки.Очистить();        ОтборОрганизация = ПолучитьЗначениеОрганизации();    ОтборКонтрагент     = ПолучитьЗначениеКонтрагента();        Если ОтборОрганизация = Неопределено Тогда        ОтборОрганизация = ПолучитьМодульПрог("Модуль_РаботаССерверомДиадок").ПолучитьОрганизацииНезаблокированныеПоAPI();    КонецЕсли;        ТаблицаДокументовДляОтправки = Модуль_Интеграция.ПолучитьТаблицуЗначенийДокументовДляОтправкиДиадок(    ДатаНачала, ДатаОкончания, ТипыДокументов, ОтборОрганизация, ОтборКонтрагент);        КэшБелыйЛистДоговоров = Новый Соответствие;        Для каждого СтрокаТаблицы из ТаблицаДокументовДляОтправки Цикл                Если СтрокаТаблицы.ТипДокумента = "Счет-фактура" Тогда                        СтрокаНовая = ТаблицаДокументовДляОтправки.Добавить();            ЗаполнитьЗначенияСвойств(СтрокаНовая, СтрокаТаблицы);                        СтрокаНовая.DocumentType = "UniversalTransferDocument";            СтрокаНовая.ТипДокумента = "УПД Счф Доп";            СтрокаНовая.ФорматОтправки.ИмяТипа = "UniversalTransferDocument";            СтрокаНовая.ФорматОтправки.ФункцияДокумента = "СЧФДОП";            СтрокаНовая.ФункцияУПД = "СЧФДОП";                                КонецЕсли;            КонецЦикла;        Для Каждого СтрокаТаблицы Из ТаблицаДокументовДляОтправки Цикл                Если СписокДокументовДляВыгрузки_ПроверитьБелыйЛистДоговоров(СтрокаТаблицы, КэшБелыйЛистДоговоров) = Ложь Тогда            Продолжить;        КонецЕсли;                СтрокаТЧ = СписокДокументовДляВыгрузки.Добавить();                ЗаполнитьЗначенияСвойств(СтрокаТЧ, СтрокаТаблицы, ,"ФорматОтправки"); и тд процедура без изменений 2. Объединила в один пакет УПД и ТОРГ-12 ФормаВыгрузкиПроцедура СписокДокументовДляВыгрузки_СформироватьПакеты() ИначеЕсли СтрокаТЧ.DocumentType = "Invoice"               ИЛИ СтрокаТЧ.DocumentType = "InvoiceRevision"               ИЛИ СтрокаТЧ.DocumentType = "InvoiceCorrectionRevision"               ИЛИ СтрокаТЧ.DocumentType = "UniversalTransferDocument" И СтрокаТЧ.ФункцияУПД = "СЧФ"               ИЛИ СтрокаТЧ.DocumentType = "UniversalTransferDocument" И СтрокаТЧ.ФункцияУПД = "СЧФДОП"               ИЛИ СтрокаТЧ.DocumentType = "UniversalCorrectionDocument" И СтрокаТЧ.ФункцияУПД = "КСЧФ" Тогда                        СчетФактуруВПакет(СтрокаТЧ); 3. отключила взаимовыбор документов ФормаПечатногоДокументаПроцедура ТаблицаДокументовПриОкончанииРедактирования(Элемент, НоваяСтрока, ОтменаРедактирования) В самом начале дописала Возврат;т.к. некоторым контрагентам нужно отпралять пакет СФ+Торг-12, некоторым УПД, также есть внешние печатные формы, которые также прикреплены к реализации и флаги устанавливаются некорректно.30.12.2020, 15:22, "Данила Володькин" <notifications@github.com>:
Добрый день.
Укажите точную версию модуля. В каком именно месте вносили правки?

**Comment by alexandra582** [comment]
Добрый день!
Тех. информация модуля:
 
 Интеграция:
Версия модуля: 5.37.02.297
Версия компоненты: 5.32.3.633
Модуль интеграции: Модуль_ИнтеграцияУПП13
Модуль типовой: Нет
Подключаемый модуль: В справочнике
Путь к подключаемому модулю: Справочник: Внешние обработки
Элемент: Диадок подключаемый модуль
UserID: 71ac42cf-d607-4301-af22-338bcde27f89
Отпечаток сертификата:  не найден
 
 Настройки:
Отладка вложенных обработок: Запрещена
Режим совместимости форматов: Да
 
 Программное обеспечение:
Версия ОС: version 10.0  (Build 17763)
Версия платформы: 8.3.15.1869
Тип платформы: Windows x86
Вид клиента: Толстый клиент обычное приложение
Конфигурация: Управление производственным предприятием, редакция 1.3 (1.3.146.2)
 
Вносила изменения
Добавленные строки в коде выделены жирным шрифтом.
 
1. Добавила в список УПД
 
ФормаВыгрузки
Процедура ОбновитьСписокСтраницыОтправкиВДиадок()
    СписокДокументовДляВыгрузки.Очистить();
    
    ОтборОрганизация = ПолучитьЗначениеОрганизации();
    ОтборКонтрагент     = ПолучитьЗначениеКонтрагента();
    
    Если ОтборОрганизация = Неопределено Тогда
        ОтборОрганизация = ПолучитьМодульПрог("Модуль_РаботаССерверомДиадок").ПолучитьОрганизацииНезаблокированныеПоAPI();
    КонецЕсли;
    
    ТаблицаДокументовДляОтправки = Модуль_Интеграция.ПолучитьТаблицуЗначенийДокументовДляОтправкиДиадок(
    ДатаНачала, ДатаОкончания, ТипыДокументов, ОтборОрганизация, ОтборКонтрагент);
    
    КэшБелыйЛистДоговоров = Новый Соответствие;
    
/////добавленный цикл
    **Для каждого СтрокаТаблицы из ТаблицаДокументовДляОтправки Цикл
        
        Если СтрокаТаблицы.ТипДокумента = "Счет-фактура" Тогда
            
            СтрокаНовая = ТаблицаДокументовДляОтправки.Добавить();
            ЗаполнитьЗначенияСвойств(СтрокаНовая, СтрокаТаблицы);
            
            СтрокаНовая.DocumentType = "UniversalTransferDocument";
            СтрокаНовая.ТипДокумента = "УПД Счф Доп";
            СтрокаНовая.ФорматОтправки.ИмяТипа = "UniversalTransferDocument";
            СтрокаНовая.ФорматОтправки.ФункцияДокумента = "СЧФДОП";
            СтрокаНовая.ФункцияУПД = "СЧФДОП";
                        
        КонецЕсли;
        
    КонецЦикла;**
 ////////конец добавленного цикла
   
    Для Каждого СтрокаТаблицы Из ТаблицаДокументовДляОтправки Цикл
        
        Если СписокДокументовДляВыгрузки_ПроверитьБелыйЛистДоговоров(СтрокаТаблицы, КэшБелыйЛистДоговоров) = Ложь Тогда
            Продолжить;
        КонецЕсли;
        
        СтрокаТЧ = СписокДокументовДляВыгрузки.Добавить();
        
        ЗаполнитьЗначенияСвойств(СтрокаТЧ, СтрокаТаблицы, ,"ФорматОтправки");
 
и тд процедура без изменений
 
2. Объединила в один пакет УПД и ТОРГ-12
 
ФормаВыгрузки
Процедура СписокДокументовДляВыгрузки_СформироватьПакеты()
 
ИначеЕсли СтрокаТЧ.DocumentType = "Invoice" 
              ИЛИ СтрокаТЧ.DocumentType = "InvoiceRevision" 
              ИЛИ СтрокаТЧ.DocumentType = "InvoiceCorrectionRevision" 
              ИЛИ СтрокаТЧ.DocumentType = "UniversalTransferDocument" И СтрокаТЧ.ФункцияУПД = "СЧФ"
 ////добавленный код
              **ИЛИ СтрокаТЧ.DocumentType = "UniversalTransferDocument" И СтрокаТЧ.ФункцияУПД = "СЧФДОП"**
 ////конец добавленного кода
              ИЛИ СтрокаТЧ.DocumentType = "UniversalCorrectionDocument" И СтрокаТЧ.ФункцияУПД = "КСЧФ" Тогда
            
            СчетФактуруВПакет(СтрокаТЧ);
 
3. отключила взаимовыбор документов
 
ФормаПечатногоДокумента
Процедура ТаблицаДокументовПриОкончанииРедактирования(Элемент, НоваяСтрока, ОтменаРедактирования)
 
В самом начале дописала Возврат;
т.к. некоторым контрагентам нужно отпралять пакет СФ+Торг-12, некоторым УПД, также есть внешние печатные формы, которые также прикреплены к реализации и флаги устанавливаются некорректно.

**Comment by alexandra582** [comment]
Разобрались, вопрос закрыт.
Спасибо!

**Comment by alexandra582** [comment]
.
