### ISSUE TITLE
Не получается отправить подписанный документ с помощью CreatePackageSendTask2

### ISSUE THREAD

**Issue by klishev** [diadoc/diadocsdk-1c-docs#566]
Использую следующий код:
ПакетДокКонтур = пАвторизацияКонтур.CreatePackageSendTask2();
ПакетДокКонтур.CounterAgentId = тзЭДО.ИдКлКонтур;
ПакетДокКонтур.DelaySend = 1;// с этим флагом всё отправляется успешно
// для УПД-1
 ДокКонтур = ПакетДокКонтур.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01_hyphen", пИмяФайла);
// для УКД
ДокКонтур = ПакетДокКонтур.AddDocumentFromFile("UniversalCorrectionDocument", "КСЧФДИС", "ucd_05_02_01", пИмяФайла);
ДокКонтур.Comment = "выгружен из 1С";
ПакетДокКонтурОтпр = ПакетДокКонтур.Send();

Без установленного флага (ПакетДокКонтур.DelaySend = 1) отправка вызывает ошибку:
// для УПД-1
PackageSendTask2.Send: ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: { Location = /Файл/@ИдФайл, Message = Значение атрибута @ИдФайл имеет неверный формат: ON_NSCHFDOPPR_20210112_c2f964f3-39e3-40fa-990e-7ddeb24a301b (@ИдОтпр=9f197cbd-ac80-4659-9780-428af6209dd9, @ИдПол=17ec9597-a94b-43fc-9048-e7f8bb772668)
При отстутствии /Файл/Документ/ТаблСчФакт/СведТов/ДопСведТов/НомСредИдентТов и /Файл/Документ/ТаблСчФакт/СведТов/ДопСведТов/СведПрослеж значение @ИдФайл должно начинаться с ON_NSCHFDOPPR_, ON_NSCHFDOPPRMARK_ или ON_NSCHFDOPPRPROS }
// для УКД
PackageSendTask2.Send: ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: { Location = /Файл/@ИдФайл, Message = Значение атрибута @ИдФайл имеет неверный формат: ON_KORSCHFDOPPR_20210112_f78933d2-b5cb-4441-8f77-fa09027fe74f (@ИдОтпр=9f197cbd-ac80-4659-9780-428af6209dd9, @ИдПол=17ec9597-a94b-43fc-9048-e7f8bb772668) }

**Comment by ButurlakinSemyon** [comment]
Добрый день!
Ошибка указывает на неправильный порядок значений в ИдФайл.
После префикса ON_SCHFDOPPR должен идти "ИдПол", затем "ИдОтпр" (у вас идет дата файла "20210112").

Имя файла должно иметь следующий вид:

R_T_A_O_GGGGMMDD_N, где:

R_T - префикс, принимающий значение ON_NSCHFDOPPR в общем случае
A - идентификатор получателя файла обмена
O - идентификатор отправителя файла обмена
GGGG - год формирования передаваемого файла обмена, 
MM - месяц, 
DD - день;
N - 36-символьный глобально уникальный идентификатор GUID

**Comment by klishev** [comment]
Всё получилось, спасибо.
