### ISSUE TITLE
Подписание формализованного акта

### ISSUE THREAD

**Issue by alkrot** [diadoc/diadocsdk-1c-docs#567]
Взял пример из другого #366
![image](https://user-images.githubusercontent.com/26366975/104320746-c7c08080-54f3-11eb-84c5-1dc298dfab58.png)

Но в итоге при попытки присвоение св-в
![image](https://user-images.githubusercontent.com/26366975/104322110-934dc400-54f5-11eb-87bd-5aea9e3b54b9.png)

В чем может быть проблема?

Также Content.HasProperty("UniversalTransferDocumentBuyerTitle")

Возвращает всегда False хотя если обратиться к этому св-ву, то ошибок по сути нет

**Comment by GilimkhanovDenis** [comment]
Добрый день!

Можете дать ссылку на документ (можно или из веб-интерфейса или из поля [pyDoc.PathUrl](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html?highlight=PathUrl)) ?

И подскажите какой язык, компилятор используете

**Comment by alkrot** [comment]
> pyDoc.PathUrl

/a41d989f-d47d-46d9-81a5-92b683892137/Document/Show?letterId=7a306818-7643-4051-b4d5-d259c6050792&documentId=211eb8b5-84bb-4b75-9152-639cf83cdfa8

ISBL программа  в который применяется данный язык, написана на Delphi

**Comment by GilimkhanovDenis** [comment]
Боюсь, без дампа памяти в момент ошибки разобраться не получится

Можете его собрать ( с помощью WinDbg или любым другим доступным способом)?

**Comment by alkrot** [comment]
@GilimkhanovDenis 
https://drive.google.com/file/d/1a1nSvyfUw74vVsR4VtMpDRbEMa0chfr2/view?usp=sharing

**Comment by GilimkhanovDenis** [comment]
Добрый день. Посмотрели дампы. Боюсь, в них никакой информации об исключении, которое получаете у себя в программе - только информация о срабатывании системного прерывания int 3

```
EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 0000000000000000
   ExceptionCode: 80000003 (Break instruction exception)
  ExceptionFlags: 00000000
NumberParameters: 0
```

Подозреваю, что дамп был создан не в момент возникновения исключения, а после того, как появилось окно "Access violation..."

Возможно, проще будет собрать дамп с помощью [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) с ключами
`procdump -e -ma -w <process_name>`

**Comment by alkrot** [comment]
@GilimkhanovDenis 

ProcDump v10.0 - Sysinternals process dump utility
Copyright (C) 2009-2020 Mark Russinovich and Andrew Richards
Sysinternals - www.sysinternals.com

Process:               SBRte.exe (4184)
Process image:         C:\PROGRA~2\DIRECT~1\DIRECT~1.7\sbrte.exe
CPU threshold:         n/a
Performance counter:   n/a
Commit threshold:      n/a
Threshold seconds:     n/a
Hung window check:     Disabled
Log debug strings:     Disabled
Exception monitor:     Unhandled
Exception filter:      [Includes]
                       *
                       [Excludes]
Terminate monitor:     Disabled
Cloning type:          Disabled
Concurrent limit:      n/a
Avoid outage:          n/a
Number of dumps:       1
Dump folder:           D:\DiadocApi\Procdump\
Dump filename/mask:    PROCESSNAME_YYMMDD_HHMMSS
Queue to WER:          Disabled
Kill after dump:       Disabled


Press Ctrl-C to end monitoring without terminating the process.

[16:19:24] Exception: C0000005.ACCESS_VIOLATION
[16:19:24] Exception: 0EEDFADE
[16:19:24] Exception: 0EEDFADE
[16:19:24] Exception: 0EEDFADE
[16:19:24] Exception: 0EEDFADE
[16:19:24] Exception: 0EEDFADE
[16:19:24] Exception: 0EEDFADE

**Comment by GilimkhanovDenis** [comment]
@alkrot
У вас в папке
`Dump folder:           D:\DiadocApi\Procdump\`
должен был создаться файл с дампом. Можете его прислать?
имя файла соответсвует маске
`Dump filename/mask:    PROCESSNAME_YYMMDD_HHMMSS`

**Comment by GilimkhanovDenis** [comment]
@alkrot
Проблема ещё актуальна?
Если да, то пришлите, пожалуйста дамп, сформированный ProcDump'ом
