### ISSUE TITLE
Получение ИдентификаторДокументаВДиадок для 1C

### ISSUE THREAD

**Issue by mavDev** [diadoc/diadocsdk-1c-docs#568]
Наша биллинговая система формирует счета для клиентов и они в последствии импортируются в 1С. Если эти счета и УПД отправлять через API Диадока, а не через модуль Диадока 1С, то в 1С модуле Диадока отображается ошибка, "документ отсутствует в 1С", хотя документ с таким номером существует. 
Мы выяснили, что при отправке через модуль 1С заполняются дополнительные поля - ИдентификаторЯщикДокументаВДиадок и ИдентификаторДокументаВДиадок (ИдентификаторДокументаВДиадокСч)
Если с ящиком все понятно, то где можно узнать о том, как получить ИдентификаторДокументаВДиадок ?

![image 1](https://user-images.githubusercontent.com/4738113/104311027-b40e1d80-54e5-11eb-87b4-bfea37cbc14d.png)
![image 5](https://user-images.githubusercontent.com/4738113/104311029-b53f4a80-54e5-11eb-9130-f23746c57232.png)

**Comment by volodkindv** [comment]
Подобное обсуждали в #208, вот тут: https://github.com/diadoc/diadocsdk-1c-docs/issues/208#issuecomment-365936786
