### ISSUE TITLE
Подключить компоненту Диадок

### ISSUE THREAD

**Issue by komissarovev** [diadoc/diadocsdk-1c-docs#569]
Хочу подключить компоненту Диадок на сервере. (Сервер 64.)
Пробую двумя способами
1
ИмяФайла = КаталогВременныхФайлов()+"AddInDiadocAPI.dll";
Файл = Новый Файл (ИмяФайла);
Если Не Файл.Существует() Тогда
    МакетСДанными = ПолучитьМакет1();
    МакетСДанными.Записать(ИмяФайла);
КонецЕсли;
ЗагрузитьВнешнююКомпоненту(ИмяФайла);

Выдает:
{ВнешняяОбработка.ДиадокТест.Форма.Форма.Форма(478)}: Ошибка при вызове метода контекста (ЗагрузитьВнешнююКомпоненту): Ошибка при загрузке внешней компоненты

2
ЗарегистрироватьВнешнююКомпоненту(ИмяФайла);
КомпонентаПодключена = ПодключитьВнешнююКомпоненту(ИмяФайла, "AddInDiadocAPI", ТипВнешнейКомпоненты.Native);

Выдает:
{ВнешняяОбработка.ДиадокТест.Форма.Форма.Форма(467)}: Не удалось подключить внешнюю компоненту

**Comment by volodkindv** [comment]
Вам нужна документация по компоненте для 1С, а не C# SDK. Про подключение написано [тут](https://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_auth.html).
