### ISSUE TITLE
Отправка приглашений к партнерству (повторно)

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#57]
Добрый день.
Подскажите как правильно сделать. В начале года массово рассылали приглашение к партнерству с файлом вложения доп соглашение работа через ЭДО.
Написали самостоятельно обработку для 1С для рассылки.
Теперь необходимо заново, всем кто не перешел на ЭДО выложить соглашение на ЭДО и приглашение к партнерству, чтобы мы у них в списке приглашений были сверху (если вдруг контрагент начал работать в ЭДО, нас увидел и подпишет приглашение, все таки уже прошло много времени, некоторые считают может оно не актуально).
Вообщем как правильно поступить? 
- Перед отправкой приглашения проверять статус, если отправлено приглашения, удалять это приглашение и файл доп соглашения и отправлять сразу новое приглашение с файлом вложения? 
- Или можно просто отправить приглашение с вложением повторно, но система не позволяет это делать.
- Или есть какой-то метод в COM-компоненте для встраивания в произвольные системы, который обновит приглашение к ЭДО (допустим в нашем случае файл вложения тот же, просто поднять нас в списке приглашений выше, как будто мы сейчас только его отправили)

**Comment by denver069** [comment]
Сначала отменяем приглашение с помощью метода [BreakWithCounteragent](http://1c-docs.diadoc.ru/ru/latest/BreakWithCounteragent.html), затем посылаем новое приглашение методом [CreateAcquireCounteragentTask](http://1c-docs.diadoc.ru/ru/latest/CreateAcquireCounteragentTask.html)
