### ISSUE TITLE
Подключить компоненту Диадок

### ISSUE THREAD

**Issue by komissarovev** [diadoc/diadocsdk-1c-docs#570]
Хочу подключить компоненту Диадок на сервере. (Сервер 64.)
Пробую двумя способами
1
ИмяФайла = КаталогВременныхФайлов()+"AddInDiadocAPI.dll";
Файл = Новый Файл (ИмяФайла);
Если Не Файл.Существует() Тогда
МакетСДанными = ПолучитьМакет1();
МакетСДанными.Записать(ИмяФайла);
КонецЕсли;
ЗагрузитьВнешнююКомпоненту(ИмяФайла);

Выдает:
{ВнешняяОбработка.ДиадокТест.Форма.Форма.Форма(478)}: Ошибка при вызове метода контекста (ЗагрузитьВнешнююКомпоненту): Ошибка при загрузке внешней компоненты

2
ЗарегистрироватьВнешнююКомпоненту(ИмяФайла);
КомпонентаПодключена = ПодключитьВнешнююКомпоненту(ИмяФайла, "AddInDiadocAPI", ТипВнешнейКомпоненты.Native);

Выдает:
{ВнешняяОбработка.ДиадокТест.Форма.Форма.Форма(467)}: Не удалось подключить внешнюю компоненту

**Comment by komissarovev** [comment]
ИмяФайла = КаталогВременныхФайлов()+"AddInDiadocAPI.dll";
Файл = Новый Файл (ИмяФайла);
Если Не Файл.Существует() Тогда
	МакетСДанными = ПолучитьМакет1();
	МакетСДанными.Записать(ИмяФайла);
КонецЕсли;
ЗагрузитьВнешнююКомпоненту(ИмяФайла);

**Comment by volodkindv** [comment]
Посмотрите [тут](https://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_auth.html)

**Comment by komissarovev** [comment]
Делаю как сказано 
//Загрузка внешней компоненты
ИмяФайла = "C:\Temp\AddInDiadocAPI.dll";
ЗагрузитьВнешнююКомпоненту(ИмяФайла);
Выдает:
{ВнешняяОбработка.ДиадокТест.Форма.Форма.Форма(478)}: Ошибка при вызове метода контекста (ЗагрузитьВнешнююКомпоненту): Ошибка при загрузке внешней компоненты

**Comment by volodkindv** [comment]
Попробуйте отловить текст ошибки.
Наиболее вероятные причины:
- не хватает прав для загрузки внешних компонент
- не настроены профили безопасности
- загружается компонента неправильной битности (64 вместо 32)
- ОС отличается от Windows
- ...

**Comment by komissarovev** [comment]
ОС windows
Если у меня платформа 1с 32, а сервер 64
и я хочу подключиться к диадок с сервера, то dll64 нужна?

**Comment by volodkindv** [comment]
если с сервера, то нужна 64, сборка COM
