### ISSUE TITLE
Подскажите как для исходящего УПД  через com  ( динамаческий контекст ) узнать название поля 10 в дереве контекста

### ISSUE THREAD

**Issue by amore1302** [diadoc/diadocsdk-1c-docs#571]
Подскажите как для исходящего УПД  через com  ( динамаческий контекст ) узнать название поля 10 в дереве контекста
Покупатель просит заполнить поле 10 в УПД (времени катострофически не хватает )
Как до него добраться через  DynamicContent.UniversalTransferDocumentWithHyphens
какие  поля дальше

заранее спасибо

**Comment by volodkindv** [comment]
Посмотрите в блоке TransferInfo.Employee или TransferInfo.OtherIssuer.

**Comment by amore1302** [comment]
спасибо
это Employee

OtherIssuer это когда лицо сторонней организации


а comment надо закрывать или не обязательно ?

**Comment by amore1302** [comment]
спасибо все получилось - уже выгрузили в реальный УПД ( для некоторых покупателей )
