### ISSUE TITLE
Расшифровки статусов UTD

### ISSUE THREAD

**Issue by SIMBaIrk** [diadoc/diadocsdk-1c-docs#572]
https://1c-docs.diadoc.ru/ru/latest/ComObjects/Enums/UTDStatus.html
Через event.GetDocument().status получаю статус исходящего документа.
Необходимо отработать событие успешное подписание УПД.
Пытаюсь разобраться  встатусах, но есть неуверенность в их интерпретации
УПД состоит из двух частей: Передаточного документа и СФ. Передаточный документ либо подписывается либо нет. СФ проходит по спец протоколу извещений.
Соответственно статусы состоят из двух частей, той что отвечате за ПД, и той что за СФ.

Правильно ли я понял идентификатор и описание:
OutboundWaitingForSenderSignature - всё понятно, мы сами ещё не подписали
OutboundWaitingForInvoiceReceiptAndRecipientSignature - Подпись нет, Извещение нет.
OutboundWaitingForInvoiceReceipt - Подпись есть, Извещение нет (возможно что через интеграцию подписали, которая не умеет генерировать извещения)
OutboundWaitingForRecipientSignature - Подпись нет, Извещение есть
OutboundWithRecipientSignature - Не понятный статус, ни по описанию ни по идентификатору.
OutboundFinished - есть и подпись, и извещение.

**Comment by ButurlakinSemyon** [comment]
Добрый день!

Все верно, кроме:
OutboundWithRecipientSignature - есть и подпись, и извещение
OutboundFinished - есть извещение, ответная подпись не требуется (СФ, неформализованные документы)

**Comment by SIMBaIrk** [comment]
Спасибо, теперь встало на свои места. Если есть возможность может быть доку подправить? Понятно что те кто её писал прекрасно понимают с чем имеют дело, но всё же.

**Comment by ButurlakinSemyon** [comment]
Данная страница транслирует описание статусов в документации по [апи диадока](https://api-docs.diadoc.ru/ru/latest/proto/utd/UniversalDocumentMetadata.html?highlight=UniversalTransferDocumentStatus). Вы можете оставить пожелание по руководству [здесь](https://github.com/diadoc/diadocsdk-csharp/issues).

**Comment by SIMBaIrk** [comment]
Спасибо
