### ISSUE TITLE
Подключаемый модуль, заполнение реквизита Протоконтент.Table.Items[0].VAT 

### ISSUE THREAD

**Issue by achumak** [diadoc/diadocsdk-1c-docs#573]
Модуль интеграции Diadoc1C_UF_5_38_19.epf 
для с/ф, торг12 УПД820 (ТипыКонтента.Utd820SellerContent, Function "Invoice", "Basic" )

Для варианта Протоконтент.Table.Items[0].TaxRate = "ИсчНалАг" (налог исчисляемый налоговым агентом) необходимо заполнить реквизит Item.VAT таким значением, чтобы в форме документа в колонке Сумма НДС стоял "-" (сумма налога предъявляемая покупателю). 

Значения Item.VAT = "ДефНДС" и Item.VAT = "-" не дают нужного эффекта, в колонке Сумма НДС отображается "без НДС". 

Реквизит HyphenVat в нынешней объектной модели отсутствует. Помогите решить проблему.

**Comment by volodkindv** [comment]
попробуйте так
```
Item.HyphenVat = Истина;
или
Item.Vat = Неопределено;
```
при этом в Item.WithoutVat должно быть Ложь или Неопределено

**Comment by achumak** [comment]
Большое спасибо, проблема решена!
