### ISSUE TITLE
Требует поле при отправке:  FromDepartmentId 

### ISSUE THREAD

**Issue by kvazymoda** [diadoc/diadocsdk-1c-docs#574]
Добрый день, Коллеги.

Все хорошо было, соединялось, отправлялось и вот после нового года, а может просто по другому контрагенту,
по которому есть партнерские отношения(с нашей организацией), у контрагента есть ID, который мы знаем.
Как будто поле "FromDepartmentId " обязательным стало.
Что мы сделали неверно?
Код:
__________________________________________________________________________
ПутькФайлуXML = СформироватьВременныйФайл(элем.Файл)
 Third_DocumentToSend = SendTask.AddDocumentFromFile("XmlAcceptanceCertificate", "default", "rezru_05_02_01",ПутькФайлуXML);   
 Third_DocumentToSend.Comment = "Это тест!! не принимать документ к учету!! НФД";
    
 ОтправленныеДокументы = SendTask.Send(); // ошибка

// Сообщение при отправке
//Ошибка при вызове метода контекста (Send)
//		   ОтправленныеДокументы = SendTask.Send();
//по причине:
//Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: //MessageToPost.FromDepartmentId is required field.

**Comment by kvazymoda** [comment]
Коллеги, 
есть ли мысли по этому поводу?

**Comment by volodkindv** [comment]
Добрый день.
Укажите точную версию компоненты, сборку (COM/Addin) и разрядность.
И код, который создает объект SendTask.

**Comment by kvazymoda** [comment]
regsvr32.exe C:\Файлы\Diadoc_5_32_0_627_x64.dll
// или  regsvr32.exe C:\Файлы\DiadocCom_5_32_2_632_x64.dll
// 64 разряда
_____________________________________________________________________
ПодключитьВнешнююКомпоненту("AddIn.DiadocInvoiceAPI");  
//Создание объекта DiadocInvoiceAPI
DiadocApi_ = Новый("AddIn.DiadocInvoiceAPI");
DiadocApi  = DiadocApi_.CreateObject();

//Задаем параметры подлючения к серверу
//DiadocApi.ApiClientId  = КлючРазработчика;
DiadocApi.ApiClientId  = "*****";
DiadocApi.ServerUrl   = "https://diadoc-api.kontur.ru:443";

//Получение списка сертификатов
Certificates = DiadocApi.GetPersonalCertificates();

//Создание соединения
мОснованяОрг = ОбменСДиадок.ВернутьКонстанту("ОсновнаяОрганизация");
ИННОрганизации = ПолучитьРеквизитОбъектаНаСервере(мОснованяОрг,"ИНН");

СтруктураСертификата = ПолучитьОтпечатокСертификата(Certificates, ИННОрганизации); // Отпечаток, Сертификат
ОтпечатокСертификата = СтруктураСертификата.Отпечаток; 
DiadocConnection = DiadocApi.CreateConnectionByCertificate(ОтпечатокСертификата);

ИНН = Прав(Certificates.GetItem(0).Inn,10);
КПП = Certificates.GetItem(0).kpp;

СтруктураКонтрагентов = ОбменСДиадок.ПолучитьСтрокуДоступныхИННКонтрагентов();  
СтрокаИНН   = СтруктураКонтрагентов.СтрокаИНН;     
МассивКонтрагентов = СтруктураКонтрагентов.МассивКонтрагентов;
мКонтрагент = МассивКонтрагентов[0];	

// Получение списка организаций
OrganizationList = DiadocConnection.GetOrganizationList();
Ц = 0;
	Пока Ц < OrganizationList.Count() Цикл       
		Organization = OrganizationList.GetItem(ц);
		мОрг = ПолучитьЭлементСправочникаПоЗначению(Organization.INN,"ИНН","Организации"); 
		Ц = Ц + 1;
	КонецЦикла;
	
SendTask = Organization.CreatePackageSendTask2();
МассДокКОтправке = ПолучитьВыборкуДокументовДляОтправки(мОрганизация,мКонтрагент);
   Для каждого элем Из МассДокКОтправке Цикл
	   ПутькФайлуXML = СформироватьВременныйФайл(элем.Файл);
	   Third_DocumentToSend = SendTask.AddDocumentFromFile("XmlAcceptanceCertificate", "default", "rezru_05_02_01",ПутькФайлуXML);  
	   
	   ПредставлениеФайла = СформироватьИмяФайлаПоПредставлению(элем.Представление);
	   Third_DocumentToSend.Comment = ПредставлениеФайла;
	   ОтправленныеДокументы = SendTask.Send();
КонецЦикла;

**Comment by volodkindv** [comment]
Поля FromDepartmentId и ToDepartmentId становятся обязательными, если не задан CounteragentBoxId. В вашем коде как раз не задается CounteragentBoxId. Скорее всего, причина именно в этом.

**Comment by kvazymoda** [comment]
1 Просим пояснить, для отправки файла контрагенту, как должно заполняться свойство CounteragentBoxId и в какой момент?
2 В справочной информации нашел его только для отправки приглашения  к сотрудничеству:
[https://1c-docs.diadoc.ru/ru/latest/ComObjects/AcquireCounteragentTask.html](url)
3 Какова природа этого свойства, от куда его брать? У нас среди свойств контрагента есть только ID и GUID
![ДИадок_Контрагент_внутри](https://user-images.githubusercontent.com/74547718/105244416-8d08b900-5b81-11eb-9156-458ebcfc4bff.jpg)

**Comment by volodkindv** [comment]
Пример отправки документа можно найти [тут](https://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html).
```
    SendTask = Organization.CreatePackageSendTask2();
    SendTask.CounterAgentId = Counteragent.Id;
```
Полное описание PackageSendTask [тут](https://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html).

**Comment by kvazymoda** [comment]
Добрый день.
 
Разобрались. Дело было в некорректных данных. По ошибке, мы в ручную, в 1С установили ID для контрагента,
точно такой какой, у своей Организации. Тк для отправки, наш механизм берет данные из базы 1С, в том числе ID,
то получилось, что отправитель и получатель имеют одинаковый ID. Метод SendTask, это расценивает как отправку внутри организации, поэтому требовал указать подразделение.
 
Спасибо.
  
>Четверг, 21 января 2021, 8:04 +03:00 от Данила Володькин <notifications@github.com>:
> 
> 
>Пример отправки документа можно найти  тут .
>    SendTask = Organization.CreatePackageSendTask2();
>
>    SendTask.CounterAgentId = Counteragent.Id;
>
>
>Полное описание PackageSendTask  тут .
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
С Уважением,
Андрей Ямкин
