### ISSUE TITLE
Проблемы с получением списка контрагентов

### ISSUE THREAD

**Issue by kvazymoda** [diadoc/diadocsdk-1c-docs#575]
Добрый день, Коллеги.

Приведу код, он ниже.
Выяснилась странная особенность, код2 отрабатывает корректно только во время режима **отладки** 1С.
В обычном режиме исполнения- в режиме работы пользователя, не работает и в цикл не заходит, и как следствие ошибка : {ВнешняяОбработка.ПодключениеДиадок.Форма.Форма.Форма(211)}: Значение не является значением объектного типа (Count)
	Пока Ц < CounteragentList.Result.Count Цикл  ....
        КонецЦикла;

Мы в начале подумали - ошибка платформы 1С, но похожий кусок - Код1 и Код3 отрабатывает всегда корректно .
Просим помочь разобраться! Как устранить такой недостаток?

Спасибо.
_____________________________________________________________

//  regsvr32.exe C:\Файлы\Diadoc_5_32_0_627_x64.dll     // Используем компоненту
// Платформа 1С:Предприятие 8.3 (8.3.13.1865)            // Используем платформу

// Подключение
ПодключитьВнешнююКомпоненту("AddIn.DiadocInvoiceAPI");  
//Создание объекта DiadocInvoiceAPI
DiadocApi_ = Новый("AddIn.DiadocInvoiceAPI");
DiadocApi  = DiadocApi_.CreateObject();

//Задаем параметры подлючения к серверу
//DiadocApi.ApiClientId  = КлючРазработчика;
DiadocApi.ApiClientId  = "*****";
DiadocApi.ServerUrl   = "https://diadoc-api.kontur.ru:443";

//Получение списка сертификатов
Certificates = DiadocApi.GetPersonalCertificates();

//Создание соединения
мОснованяОрг = ОбменСДиадок.ВернутьКонстанту("ОсновнаяОрганизация");
ИННОрганизации = ПолучитьРеквизитОбъектаНаСервере(мОснованяОрг,"ИНН");

СтруктураСертификата = ПолучитьОтпечатокСертификата(Certificates, ИННОрганизации); // Отпечаток, Сертификат
ОтпечатокСертификата = СтруктураСертификата.Отпечаток; 
DiadocConnection = DiadocApi.CreateConnectionByCertificate(ОтпечатокСертификата);

ИНН = Прав(Certificates.GetItem(0).Inn,10);
КПП = Certificates.GetItem(0).kpp;

СтруктураКонтрагентов = ОбменСДиадок.ПолучитьСтрокуДоступныхИННКонтрагентов();  
СтрокаИНН   = СтруктураКонтрагентов.СтрокаИНН;     
МассивКонтрагентов = СтруктураКонтрагентов.МассивКонтрагентов;
мКонтрагент = МассивКонтрагентов[0];	

// Получение списка организаций

/// Код1, начало 
OrganizationList = DiadocConnection.GetOrganizationList();
Ц = 0;
	Пока Ц < OrganizationList.Count() Цикл       
		Organization = OrganizationList.GetItem(ц);
		мОрг = ПолучитьЭлементСправочникаПоЗначению(Organization.INN,"ИНН","Организации"); 
		Ц = Ц + 1;
	КонецЦикла;
/// Код1, окончание 

/// Код2, начало
CounteragentList = Organization.GetCounteragentListByInnList(СтрокаИНН);    
	Ц = 0;
	Пока Ц < CounteragentList.Result.Count Цикл  		
		Counteragent = CounteragentList.Result.GetItem(Ц).Counteragent;
		Сообщить("Контр ДИадок: "+ Counteragent.ID);
		// Counteragent = Item.Counteragent;
		мКонтр = ПолучитьЭлементСправочникаПоЗначению(Counteragent.INN,"ИНН");
		Если ЗначениеЗаполнено(мКонтр) Тогда
			ИД = ПолучитьРеквизитОбъектаНаСервере(мКонтр,"ИД");
			Если НЕ ЗначениеЗаполнено(ИД) Тогда
				СоздатьЭлементСправочникаПоСтруктуре("Контрагенты",Новый Структура("Ссылка,ИД",мКонтр,Counteragent.ID)); 			
			КонецЕсли;
		Иначе	
			мКонтр = "";
			.....
		КонецЕсли;  
		Ц = Ц + 1;
	КонецЦикла;		
//// Код 2, окончание

// Получаем коллекцию документов
// Код3, начало
DocumentsTask = Organization.GetDocumentsTask();
DocumentList = DocumentsTask.GetDocuments();	
	СтрокаИНН = мПараметры.СтрокаИНН;
	Ц = 0;
	Пока ц < DocumentList.Count Цикл
		Document = DocumentList.GetItem(Ц);	
       .....
        КонецЦикла;
/// Код3, окончание

**Comment by volodkindv** [comment]
Добрый день.
Обратите внимание, что метод [GetCounteragentListByInnList](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html?highlight=GetCounteragentListByInnList#Organization.GetCounteragentListByInnList) - асинхронный. Когда вы смотрите его результат в отладке, он уже успел отработать, т.к. какое-то время выполнение стояло в точке останова.  Когда метод выполняется программно, его результат еще не успел вернуться.
Вам надо дождаться, пока IsCompleted вернет Истина, и уже после этого обращаться к Result.Count.

**Comment by kvazymoda** [comment]
Да, спасибо. 
Получилось Поставил задержку в коде для этих целей.
