### ISSUE TITLE
Отправка подписанного документа с помощью CreateOleObject('Diadoc.DiadocClient')

### ISSUE THREAD

**Issue by SanekPro** [diadoc/diadocsdk-1c-docs#576]
В документации в том числе в последней ее версии я не нашел метода как добавить документ с отсоединенной подписью, может кто нибудь направить в нужную. сторону ?

Документ без подписей - нет проблем, а очень надо с подписью.

**Comment by kulakovskaya** [comment]
Добрый день! 
Опишите, пожалуйста, подробнее сценарий, который требуется реализовать. 
Правильно понимаем, что речь про [документацию](https://1c-docs.diadoc.ru/ru/latest/) для COM-компоненты?

**Comment by SanekPro** [comment]
Да именно так, есть различные документы, как не формализованные так и формализованные АВР/ СФ по 820 приказу, они уже подписаны нужно переложить их диадок и переслать контрагенту, на текущий момент уже смогли это сделать с помощью Http Api, но думаю подобный вопрос касательно COM компоненты возник не только у нас

**Comment by kulakovskaya** [comment]
COM-компонента сама формирует подпись. Сценарий работы с подписью, сформирвоанной где-то извне в компоненте не поддерживается.

**Comment by SanekPro** [comment]
ну на том спасибо подтвердили наши догадки а по HTTP Api можно вас помучать ?
то есть прикрепить документ с подписью очень надо поэтому копаем в сторону HTTP Api не формализованный документ добавляется без проблем а вот АВР по 820 приказу принимать не хочет уже все перерыли, если пример запроса пришлю сможете подсказать ?

**Comment by kulakovskaya** [comment]
По вопросам HTTP-API рекомендуем обратиться в https://github.com/diadoc/diadocapi-docs.
