### ISSUE TITLE
Получить УПД в PDF

### ISSUE THREAD

**Issue by komissarovev** [diadoc/diadocsdk-1c-docs#577]
Добрый день, Можете подсказать где хранятся двоичные данные файла pdf с формой УПД? Чтобы ее можно было сохранить на диск.
Тая я получаю документ:
Пока ц1 < DocumentList.Count цикл
	    Document = DocumentList.GetItem(ц1);
КонецЦикла

**Comment by GilimkhanovDenis** [comment]
Добрый день
У документа есть метод [Document.GetPrintForm(FilePath, Timeout=30)](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Document.html#Document.GetPrintForm)
