### ISSUE TITLE
Если  в Delphi XE5 импортировать DiadocCom_5_32_4_635.dll c параметром Generate component Wrappers то она не компилируется - выдает ошибку

### ISSUE THREAD

**Issue by VMescheryakov** [diadoc/diadocsdk-1c-docs#578]
Если импортировать DiadocCom_5_32_4_635.dll то она не компилируется в Delphi - выдает ошибку

на функции

function TEnumVariant.Next(celt: LongWord; **const rgvar**: OleVariant; out pceltFetched: LongWord): HResult;
begin
Result := DefaultInterface.Next(celt, rgvar, pceltFetched);
end;

что const не может быть передана внутрь как var. Очевидно что проблема с параметром rgvar

IEnumVARIANT = interface(IUnknown)
['{00020404-0000-0000-C000-000000000046}']
function Next(celt: LongWord; **var rgvar** : OleVariant;
out pceltFetched: LongWord): HResult; stdcall;
function Skip(celt: LongWord): HResult; stdcall;
function Reset: HResult; stdcall;
function Clone(out Enum: IEnumVARIANT): HResult; stdcall;
end;

Вот тут https://github.com/diadoc/diadocsdk-1c-docs/issues/549 писали что исправили 14.12.2020 но не исправлено в  в версии от 14.01.2021

**Comment by azhipaigor** [comment]
Улучшение пока не вошло в релиз. Планируем выпустить в следующем релизе. Следите за историей изменений компоненты https://1c-docs.diadoc.ru/ru/latest/History/History.html, там обязательно будет комментарий.
