### ISSUE TITLE
ошибка при вызове  MarkAsRead()

### ISSUE THREAD

**Issue by vgrichuk** [diadoc/diadocsdk-1c-docs#58]
Добрый день,
версия COM-компоненты 5.10.4.168, 32-бит
при попытке пометить документ с типом XmlTorg12.InboundWaitingForRecipientSignature как прочтенный:
`Если НЕ Document.isRead Тогда Document.MarkAsRead(); КонецЕсли;`
возникает ошибка `Произошла исключительная ситуация (DocumentBase.MarkAsRead): WIN32[0x00002EE7]WinHttpSendRequest`

**Comment by denver069** [comment]
Судя по коду ошибки [WinHTTP (12007)](https://msdn.microsoft.com/ru-ru/library/windows/desktop/aa383770(v=vs.85).aspx) - это ошибка разрешения имени сервера. Скорее всего это связано с ошибками в сети.
