### ISSUE TITLE
Как отредактировать строку 10 при отправки УПД

### ISSUE THREAD

**Issue by Airat116** [diadoc/diadocsdk-1c-docs#580]
Здравствуйте, подскажите пожалуйста
Я скачал обработку "Подключаемый модуль Диадок Стандарт (СКБ Контур)"
Пытаюсь отредактировать строку 10, но не могу найти ее параметров в конфигураторе
![77](https://user-images.githubusercontent.com/78408705/106571584-63b83780-6548-11eb-8974-aba276c6b81f.png)

**Comment by ButurlakinSemyon** [comment]
Добрый день!

Данные заполняются в макете "ПечатныеФормы". Чтобы посмотреть параметры заполнения, необходимо:
1. Открыть файл модуля в конфигураторе.
2. Выгрузить из макета ПечатныеФормы библиотеку, с расширением epf.
3. Открыть в конфигураторе выгруженный файл и зайти в модуль объекта.

Нас интересует процедура ПФ_УПД_ПодвалДокумента, в которой:

Работник = РаботникИлиИноеЛицо(Content.TransferInfo);
	Если Работник <> Неопределено Тогда
		Область.Параметры.ПродавецРаботник			= СтрокаФИО(Работник);
		Область.Параметры.ПродавецРаботникДолжность = Работник.EmployeePosition``

**Comment by Airat116** [comment]
Не совсем понял пункт 2 
Я не правильно захожу?
![Screenshot_9](https://user-images.githubusercontent.com/78408705/106597021-df28e180-6566-11eb-8a7d-0b4ca7093a0f.png)

**Comment by Airat116** [comment]
Получилось найти)
Значит я могу добавить изменения? а потом загружаю данный макет обратно?

**Comment by ButurlakinSemyon** [comment]
Да, все верно.

**Comment by Airat116** [comment]
Подскажите последнюю вещь, для того чтоб мне поставить там не работника 
А директора организации и должность, мне нужно поменять это - Content.TransferInfo?

**Comment by ButurlakinSemyon** [comment]
да

**Comment by Airat116** [comment]
Спасибо
