### ISSUE TITLE
Управление областью полномочий при отправке документа строгой отчетности

### ISSUE THREAD

**Issue by NickVStepin** [diadoc/diadocsdk-1c-docs#581]
формирую документ к отправке через CreatePackageSendTask2.
При этом для документа УПД мне надо указать область полномочий подписанта 5, а для УКД - 6.
Т.к. это документы для фнс, то у подписанта заполняю SignerReference.BoxId и SignerReference.CertificateThumbprint (авторизуюсь по сертификату). Но область полномочий можно указать только в SignerDetails.SignerPowers. А одновременно их заполнять нельзя. Как быть?

**Comment by GilimkhanovDenis** [comment]
Добрый день
SignerReference используется, если нужно использовать параметры подписанта, запомненные для данного типа документа для указанного сертификата в указанном ящике в Диадоке (см. [SetExtendedSignerDetailsTask](https://1c-docs.diadoc.ru/ru/latest/ComObjects/SetExtendedSignerDetailsTask.html))
SignerDetails используется, если есть хотите указать параметры подписанта явно

Одновременно использовать запомненные параметры подписанта из базы Диадок и заданные явно невозможно.
Подписание всегда происходит тем сертификатом, по которому авторизовались

**Comment by NickVStepin** [comment]
Спасибо за ответ. А как тогда управлять областью полномочий, ибо в рамках одного и того же пользователя мне надо УПД подписывать с областью 5, а УКД - с областью 6.

**Comment by GilimkhanovDenis** [comment]
Если хотите использовать SignerReference при отправке УПД, то сохранить параметры для титула `UtdSeller`
Если хотите использовать SignerReference при отправке УКД, то сохранить параметры для титула `UcdSeller`

Или используйте SignerDetails для того титула, для которого параметры подписанта не запомнены

**Comment by NickVStepin** [comment]
видимо мы о разном или я не допонял сейчас.

Я создаю задание через CreatePackageSendTask2. В него добавляю документ через AddDocument, указывая DocumetType как  UniversalTransferDocument или UniversalCorrectionDocument для УПД и УКД соответственно.
Далее заполняю документ данными и привязываю к нему подпись через Signers.AddItem, соответственно заполняя SignerReference,BoxId и SignerRefernce.CertificateThumbprint.  При этом диадок сам подставляет область полномочий из настроек пользователя. Но для УПД мне надо 5, а для УКД - 6 для одного и того же пользователя.

Как вариант, я могу две подписи к документу добавить, одну через SignerReference, а вторую - через SignerDetails. Или для УПД и УКД этот вариант не пройдет из-за требований подписывать документ сертификатом?

**Comment by GilimkhanovDenis** [comment]
Параметры подписанта  настраиваются отдельно на каждый тип титула (тип документа + титул продавца/титул покупателя)

Соответственно, вы можете указать одни параметры для титула УПД(с полномочиями 5) и другие для титула УКД (с полномочиями 6).

**Comment by NickVStepin** [comment]
Это в вэб-версии Диадок? Или через АПИ? Носом не ткнете, где посмотреть?

**Comment by GilimkhanovDenis** [comment]
Как минимум в API.
Как уже говорил, для сохранения данных подписанта используется объект [SetExtendedSignerDetailsTask](https://1c-docs.diadoc.ru/ru/latest/ComObjects/SetExtendedSignerDetailsTask.html) (создать можно методом [Organization.CreateSetExtendedSignerDetailsTask(Thumbprint)](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#organization-createsetextendedsignerdetailstask))

Посмотреть сохранённые параметры подписанта можно методом [Organization.GetExtendedSignerDetails2(Thumbprint, TitleType)](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#organization-getextendedsignerdetails2)

В вебе, не для всех титулов можно настроить параметры подписанта и разделить УПД и УКД, кажется, нельзя

**Comment by NickVStepin** [comment]
я правильно понимаю, что для моих настроек надо сделать два задания  SetExtendedSignerDetailsTask, сначала для УПД, а потом для УКД и последовательно их отправить?

**Comment by GilimkhanovDenis** [comment]
Правильно
