### ISSUE TITLE
Компонента COM x64 5.29.13.573: для некоторых документов не крашится метод Document.GetRecipientSignature()

### ISSUE THREAD

**Issue by vlad3190** [diadoc/diadocsdk-1c-docs#582]
Коллеги, добрый день! 
Компонента COM x64 5.29.13.573
Подскажите пожалуйста, почему для некоторых документов метод **Document.GetRecipientSignature()** крашится?
В документации написано, что объект Document является базовым объектом для всех типов документов . Обладает базовым набором свойств и методов, которые также работают для всех производных типов документов.
При этом статус у документа может быть 
![error](https://user-images.githubusercontent.com/34089439/106576042-c829c580-654d-11eb-996f-93dd438c6ecd.PNG)
"OutboundWithRecipientSignature".

**Comment by GilimkhanovDenis** [comment]
Ошибка исправлялась в [5.29.14](https://1c-docs.diadoc.ru/ru/latest/History/release_info/5_29_14.html)

Обновите компоненту до актуальной
