### ISSUE TITLE
AddIn-компонента и COM-компонента. 

### ISSUE THREAD

**Issue by vlad3190** [diadoc/diadocsdk-1c-docs#583]
Коллеги, добрый день!
1. Я правильно понимаю, что AddIn-компонента выполнена по технологии Native API и не требует регистрации в реестре Windows (regsvr32)? Или же и AddIn-компонента и COM-компонента требуют регистрации в реестре Windows?
2. Каким образом можно подключить AddIn-компоненту на Тонком клиенте? В инструкции приведен пример:
//Загрузка внешней компоненты
ИмяФайла = "C:\Temp\AddInDiadocAPI.dll";
ЗагрузитьВнешнююКомпоненту(ИмяФайла);

//Создание объекта DiadocInvoiceAPI
DiadocApi_ = Новый("AddIn.DiadocInvoiceAPI");
DiadocApi  = DiadocApi_.CreateObject();

Но метод "ЗагрузитьВнешнююКомпоненту()" работает только в Толстом клиенте. В Тонком клиенте и на Сервере он недоступен. Если можно приведите пожалуйста рабочий пример подключения AddIn -компоненты?

**Comment by volodkindv** [comment]
Добрый день.
Addin-компонента выполнена по технологии COM. В зависимости от версии платформы и клиент/сервера, вам могут понадобиться разные способы обращения к компоненте. В тонком клиенте это будет `ПодключитьВнешнююКомпоненту()`. На сервере может понадобиться предварительное выполнение `regsvr32`.

**Comment by vlad3190** [comment]
А можно поподробнее узнать, по каким именам идентификаторов обращаться к компоненте при вызова метода Новы("...")?
Метод Новый("AddIn.DiadocInvoiceAPI"); валится с ошибкой.

**Comment by vlad3190** [comment]
Компонента AddInDiadoc.dll зарегистрирована вручную, командой regsvr32.

**Comment by volodkindv** [comment]
Дайте больше информации в вашем вопросе.
- версия платформы и ее битность
- тонкий/толстый клиент, сервер или нет
- какая именно ошибка возникает при вызове `Новый("AddIn.DiadocInvoiceAPI")`

**Comment by volodkindv** [comment]
Самая частая проблема - это когда для 32-битной 1С регистрируют 64-битную компоненту, или наоборот.

**Comment by vlad3190** [comment]
Версия платформы: 8.3.17.1851 x64
Контекст: Тонкий клиент, сервер
Описание ошибки: "Тип не определен" при попытке вызвать Новый("AddIn.DiadocInvoiceAPI")
Версия компоненты: Diadoc_5_32_4_635_x64.dll (AddIn-компонента), библиотека зарегистрированна на сервере, сервер перезапущен.

**Comment by vlad3190** [comment]
Может неверный идентификатор классов или идентификатор объекта компоненты?

**Comment by ButurlakinSemyon** [comment]
Попробуйте для AddIn сделать так:

res = ПодключитьВнешнююКомпоненту(АдресДоФайлаВК, "Test", ТипВнешнейКомпоненты.COM);
DiadocInvoiceApi = Новый("AddIn.Test.DiadocInvoiceAPI");
DiadocApi = DiadocInvoiceApi.CreateObject();

Если используется в тонком клиенте то: "Для режимов запуска "Тонкий клиент" и "Веб-клиент", компонент должен быть предварительно установлен методом УстановитьВнешнююКомпоненту."

**Comment by vlad3190** [comment]
Коллеги, добрый день! А компонента AddIn предназначена для работы в Тонком клиенте?
Делаю так:

&НаКлиенте
Процедура Команда(Команда)
    Подключить(Истина);
КонецПроцедуры

&НаКлиенте 
Процедура Подключить(УстановитьЕслиНеПодключено) Экспорт
    НачатьПодключениеВнешнейКомпоненты(
        Новый ОписаниеОповещения(
            "ПослеПодключения",
            ЭтотОбъект,
            УстановитьЕслиНеПодключено),
        "Обработка.ТЕСТ_.Макет.AddInDiadocAPI",
        "Test");
КонецПроцедуры

&НаКлиенте
Процедура ПослеПодключения(Подключено, УстановитьЕслиНеПодключено) Экспорт
    Если Подключено Тогда
        // Внешняя компонента подключена
        DiadocInvoiceApi = Новый("AddIn.Test.DiadocInvoiceAPI");
		DiadocApi = DiadocInvoiceApi.CreateObject();
    ИначеЕсли УстановитьЕслиНеПодключено Тогда
        НачатьУстановкуВнешнейКомпоненты(
            Новый ОписаниеОповещения(
                "Подключить",
                ЭтотОбъект,
                Ложь),
           "Обработка.ТЕСТ_.Макет.AddInDiadocAPI");
    Иначе
        // Не удалось установить или подключить

        // внешнюю компоненту

    КонецЕсли;

Получаю ошибку:
![Error](https://user-images.githubusercontent.com/34089439/107205704-35869c00-6a0f-11eb-8097-9b9c50ad424e.PNG)

**Comment by vlad3190** [comment]
В макете zip-архив:
[AddInDiadoc.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/5942884/AddInDiadoc.zip)

**Comment by volodkindv** [comment]
Да, компонента рассчитана на работу в тонком клиенте. Попробуйте следующий код:
```
ПодключитьВнешнююКомпоненту("Обработка.ТЕСТ_.Макет.AddInDiadocAPI", "DiadocAPI", ТипВнешнейКомпоненты.COM);
```

**Comment by volodkindv** [comment]
Тикет пока закрою. Если будут новые вводные, откроем.
