### ISSUE TITLE
Почему при отправки документа на согласование, выходит разный результат

### ISSUE THREAD

**Issue by Airat116** [diadoc/diadocsdk-1c-docs#584]
Здравствуйте, подскажите пожалуйста почему при отправки на согласование выходит разный результат в макете УПД?
![Screenshot_2](https://user-images.githubusercontent.com/78408705/106709366-73e21c80-6605-11eb-9323-d86cbe49b5a4.png)
![Screenshot_1](https://user-images.githubusercontent.com/78408705/106709368-75134980-6605-11eb-8f55-ae0f1126907c.png)

При просмотре пакетов документа  выходит ФИО и должность, а при отправки на согласования пустое поле.
Это получается разные макеты?

**Comment by Airat116** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/78408705/106718746-8151d380-6612-11eb-8bf5-7d6475fb62ff.png)

Выгрузил макет "Генерация XML (СКБ Контур)"
И там нашел такие процедуры, можете пожалуйста подсказать в какой именно процедуре заполняется 10 строка?

**Comment by volodkindv** [comment]
Добрый день.
Вам нужно поле Content.TransferInfo.
#571 #580

**Comment by Airat116** [comment]
Правильно ли я смотрю?
![Screenshot_2](https://user-images.githubusercontent.com/78408705/106740342-532cbd80-662b-11eb-88b3-f18eca7c65e5.png)
![Screenshot_1](https://user-images.githubusercontent.com/78408705/106740348-5627ae00-662b-11eb-93dd-bc7c1928eb35.png)

**Comment by volodkindv** [comment]
Да. TransferInfo.Employee или TransferInfo.OtherIssuer

**Comment by Airat116** [comment]
Понял, сейчас попробую поменять значение

**Comment by Airat116** [comment]
Почему то не получается подправить строку 10 =(
Отправляю документ исходящий УПД, всё равно должность не заполняется

![Screenshot_4](https://user-images.githubusercontent.com/78408705/106862956-e7a12980-66d8-11eb-8f33-b47514b5d098.png)

**Comment by volodkindv** [comment]
ФИО заполнили?

**Comment by volodkindv** [comment]
Тикет пока закрою. Если будут новые вводные, откроем.
