### ISSUE TITLE
Как получить статус документа после использования Send() или SendAsync()?

### ISSUE THREAD

**Issue by mikecool-mc** [diadoc/diadocsdk-1c-docs#585]
Добрый день. При использовании Send() или SendAsync() объекта ReplySendTask можно ли как то получить статус документа или требуется отдельный запрос?

**Comment by volodkindv** [comment]
Добрый день. Лучше выполнить отдельный запрос GetDocument

**Comment by mikecool-mc** [comment]
Правильно ли я понимаю, что SendAsync()  возвращает результат своего выполнения? т.е. он выполняется асинхронно, но возвращает результат? 
Вернее вопрос такой - после какого из методов  Send() или SendAsync()  я могу выполнить GetDocument и гарантированно получить статус документа?

**Comment by volodkindv** [comment]
Все асинхронные методы компоненты возвращают объект [AsyncResult](urlhttps://1c-docs.diadoc.ru/ru/latest/ComObjects/AsyncResult.html). Надо дождаться, пока AsyncResult.IsCompleted будет Истина. После этого можно будет обращаться к AsyncResult.Result. Если при выполнении операции произошла ошибка, то в 1С она возникнет при обращении к AsyncResult.Result.
