### ISSUE TITLE
При заполнении содержимого исходящего УПД не могу заполнить TransferInfo.Employee.EmployeePosition

### ISSUE THREAD

**Issue by NickVStepin** [diadoc/diadocsdk-1c-docs#586]
Создал задание на отправку через CreatePackageSendTask2.
Получил содержимое документа для заполнения через AddDocument("UniversalTransferDocument","СЧФДОП", Данные)

Заполняю содержимое:

СодержимоеДокумента.TransferInfo.Employee.EmployeePosition			= ДанныеДляОтправки.TransferInfo.Employee.EmployeePosition;
			СодержимоеДокумента.TransferInfo.Employee.Surname					= ДанныеДляОтправки.TransferInfo.Employee.Surname;
			СодержимоеДокумента.TransferInfo.Employee.FirstName					= ДанныеДляОтправки.TransferInfo.Employee.FirstName;
			СодержимоеДокумента.TransferInfo.Employee.Patronymic
			
и получаю ошибку "Поле объекта не обнаружено (EmployeePosition)", т.е. в структуре содержимого документа в TransferInfo.Employee нет EmployeePosition.

Вопрос, как заполнить TransferInfo.Employee (нужно чтобы поле 10 в УПД заполнилось)

**Comment by GilimkhanovDenis** [comment]
Добрый день

В динамическом контенте у Employee нет поля EmployeePosition - есть поле Position
