### ISSUE TITLE
Добавить документы в пакет через API

### ISSUE THREAD

**Issue by Alekseevda** [diadoc/diadocsdk-1c-docs#589]
Добрый день.
Есть задача, что бы при отправке УКД или исправления, документы объединять в пакет.
Вот пример того как это выглядит в веб версии:
https://diadoc.kontur.ru/87a6ba56-08de-478f-8f97-9d8287c38fa0/Document/Show?letterId=3a82dcf9-f6a8-4e5f-96e1-43e02a8f998f&documentId=f7bd8542-b610-4c02-8131-d7d7da0c49f6
Использую com компоненту v5.32.0.627
Спасибо.

**Comment by volodkindv** [comment]
Добрый день.
Примерно так:
```
CustomDocumentToSend = PackageSendTask2.AddDocument(...);
CustomDocumentToSend.AddInitialDocument(Sent_document_utd.DocumentId);
```
