### ISSUE TITLE
метод SetOneSDocumentId

### ISSUE THREAD

**Issue by vgrichuk** [diadoc/diadocsdk-1c-docs#59]
надо ли производить какие-либо действия с документом для сохранения сведений в базу ДиаДок после вызова метода Document.SetOneSDocumentId(<УникальныйИдентификатор>) ?

**Comment by Sergguha** [comment]
Добрый день, сам недавно задавался этим вопросом: ничего дополнительного делать не нужно, только для получения установленного идентификатора из базы Диадок при получении документа методом [GetDocumentById()](http://diadocsdk-1c.readthedocs.io/ru/latest/GetDocumentById.html) объекта Organization устанавливать для параметра RequireOneSDocumentId значение Истина.

**Comment by vgrichuk** [comment]
Спасибо, Sergguha, направление оказалось верным. Только не у Организации, а у GetDocumentsTask это свойство ставится.

**Comment by Sergguha** [comment]
И у организации в том числе, ссылка в моем сообщении ведет на метод объекта Organization.
