### ISSUE TITLE
Расхождение данных подразделений входящих документов на сайте и в данных, получаемых через АПИ для 1С

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#590]
Добрый день.

Случайно заметили странность в данных подразделений входящих документов.
А именно несоответствие информации о текущем подразделении и подразделении, в которое наш отправитель изначально отправил нам свой документ, который мы получили, и который теперь лежит у нас во входящих.

Либо это какая-то ошибка, либо, если это так и должно быть, хотелось бы получить от вас какое-то разъяснение по логике такого назначения значений реквизитов.

**Общая информация для упрощения «разбора полётов»:**
Организация:		«ДНС Ритейл»
ИНН:			2540167061
КПП:			254301001
КПП2:			783450001
ID организации:	c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru		
ID участника ЭДО:	2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.32.4.635**.

### Суть проблемы на примере конкретного документа:

Данные документа:
**ID**
67eb1388-32e9-4e0a-9f72-5f2e966af907a5c6e84f-746b-4649-8413-9353261a17fd

**FileName** 
ON_NSCHFDOPPR_2BM-2540167061-254001001-201312151140099321090_2BM-7814364151-781401001-201612151129107992264_20210217_1a2e80ad-0c80-45a0-b004-0d6a2fc3d273.xml

**PathURL**
/c4390c58-315b-4323-a9b4-b5d87d6e868b/Document/Show?letterId=67eb1388-32e9-4e0a-9f72-5f2e966af907&documentId=a5c6e84f-746b-4649-8413-9353261a17fd

Из данных документации:
![изображение](https://user-images.githubusercontent.com/33707226/108289028-64ec9400-71d9-11eb-889d-a9a0a749b83d.png)

видно, что 
**Department** - это то наше подразделение, в котором входящий документ находится сейчас.
**ToDepartment** - это то наше подразделение, в которое отправитель изначально отправил нам документ.

Если посмотреть на данные вышеуказанного документа на сайте то видно:
![изображение](https://user-images.githubusercontent.com/33707226/108289195-bc8aff80-71d9-11eb-8417-fd051a9d4bd1.png)

что документ получен в головное подразделение.
**И нет никакой истории перемещения документа между подразделениями.** 

Т.е. получается, что документ нам отправили в головное подразделение.
И в головном же подразделении его приняли, и сейчас он там "лежит".

Однако, если получить данные этого же документа через АПИ для 1С, то видна такая картина (данные из отладчика 1С):
![изображение](https://user-images.githubusercontent.com/33707226/108289477-3622ed80-71da-11eb-9411-a3edc384ca25.png)

Т.е., согласно данным, возвращаемым АПИ, 
### документ был отправлен нам не в головное подразделение, а в подразделение "Входящие документы поставщиков". Но сейчас находится в головном подразделении.

И вот тут нам стало непонятно.

**Получается, что:**
1. Или на сайте не отразились данные о истории перемещения документа из подразделения "Входящие документы поставщиков" в головное подразделение после его приема. _Ошибка на сайте?_
2. Или в АПИ для 1С в каких-то случаях неверно возвращаются данные в реквизите ToDepartment, и на самом деле в этом реквизите в обсуждаемом случае должно было быть указано головное подразделение. _Ошибка в АПИ?_
3. Или мы просто как-то неверно интерпретируем данные в реквизитах Department, ToDepartment и FromDepartment. _А как тогда их правильно понимать?_

Вот хотелось бы обратить ваше внимание на эту ситуацию и получить по ней какое-то разъяснение, если мы что-то неверно понимаем в сути вышеуказанных реквизитов. Ну а, если это реально какая-то ошибка, то показать ее и далее надеяться на то, что вы ее исправите.

Спасибо.

**Comment by ButurlakinSemyon** [comment]
Добрый день!

Документ действительно был отправлен в подразделение "Входящие документы поставщиков". Но у получателя стоит настройка, согласно которой отправитель может отправлять документы только в "Головное подразделение" (у контрагента стоит группа "По умолчанию"). Поэтому документ автоматически пришел в головное подразделение. 
Фактически документ не перемещали из одного подразделения в другой, поэтому и истории перемещения нет. 

На скриншоте из веба подразделение соответствует полю Department. Поэтому правильно смотреть на поле Department, а не ToDepartment.

**Comment by JohnSergeev** [comment]
Ясно. Мы просто думали, что подобные "перескоки" документа должны отражаться в истории перемещений (типа, "Ну изначально же его ВОТ ТУДА отправили").

Спасибо за разъяснение.

Тему можно закрывать.
