### ISSUE TITLE
Не получается отправить УПД

### ISSUE THREAD

**Issue by kvazymoda** [diadoc/diadocsdk-1c-docs#591]
Добрый день, коллеги.

Пытаемся отправить файл, он выгружен из 1С:Бухгалтерия 8, формат УПД, приказ 820, не получается.
Привожу полный код, он ниже, с описанием используемых методов и компонентов. Описание ошибки, после кода.
Прошу помочь. 
Приложил выгружаемый файл (имена изменены/обезличены) :
[https://cloud.mail.ru/public/fnwm%2FjdJpKec47](url)

PS: Нужно отметить - Акты продавца отправляются успешно, код аналогичный, но конструкция при этом такая:
//Third_DocumentToSend = SendTask.AddDocumentFromFile("XmlAcceptanceCertificate", "default", "rezru_05_02_01",ПутькФайлуXML)
______________________________
regsvr32.exe C:\Файлы\Diadoc_5_32_0_627_x64.dll
// или regsvr32.exe C:\Файлы\DiadocCom_5_32_2_632_x64.dll
// 64 разряда

ПодключитьВнешнююКомпоненту("AddIn.DiadocInvoiceAPI");
//Создание объекта DiadocInvoiceAPI
DiadocApi_ = Новый("AddIn.DiadocInvoiceAPI");
DiadocApi = DiadocApi_.CreateObject();

//Задаем параметры подлючения к серверу
//DiadocApi.ApiClientId = КлючРазработчика;
DiadocApi.ApiClientId = "*****";
DiadocApi.ServerUrl = "https://diadoc-api.kontur.ru:443";

//Получение списка сертификатов
Certificates = DiadocApi.GetPersonalCertificates();

//Создание соединения
мОснованяОрг = ОбменСДиадок.ВернутьКонстанту("ОсновнаяОрганизация");
ИННОрганизации = ПолучитьРеквизитОбъектаНаСервере(мОснованяОрг,"ИНН");

СтруктураСертификата = ПолучитьОтпечатокСертификата(Certificates, ИННОрганизации); // Отпечаток, Сертификат
ОтпечатокСертификата = СтруктураСертификата.Отпечаток;
DiadocConnection = DiadocApi.CreateConnectionByCertificate(ОтпечатокСертификата);

ИНН = Прав(Certificates.GetItem(0).Inn,10);
КПП = Certificates.GetItem(0).kpp;

СтруктураКонтрагентов = ОбменСДиадок.ПолучитьСтрокуДоступныхИННКонтрагентов();
СтрокаИНН = СтруктураКонтрагентов.СтрокаИНН;
МассивКонтрагентов = СтруктураКонтрагентов.МассивКонтрагентов;
мКонтрагент = МассивКонтрагентов[0];

// Получение списка организаций
OrganizationList = DiadocConnection.GetOrganizationList();
Ц = 0;
Пока Ц < OrganizationList.Count() Цикл
Organization = OrganizationList.GetItem(ц);
мОрг = ПолучитьЭлементСправочникаПоЗначению(Organization.INN,"ИНН","Организации");
Ц = Ц + 1;
КонецЦикла;

SendTask = Organization.CreatePackageSendTask2();
МассДокКОтправке = ПолучитьВыборкуДокументовДляОтправки(мОрганизация,мКонтрагент);
Для каждого элем Из МассДокКОтправке Цикл
ПутькФайлуXML = СформироватьВременныйФайл(элем.Файл);

Third_DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01",ПутькФайлуXML);   // Ок, принимает параметры
  /// Пробовали: "СЧФДОП", "СЧФ", "ДОП" результат одинаков

   ПредставлениеФайла = СформироватьИмяФайлаПоПредставлению(элем.Представление);
   Third_DocumentToSend.Comment = ПредставлениеФайла;
   
   ОтправленныеДокументы = SendTask.Send();  // !!Ошибка!!
   
КонецЦикла;
___________________________________________
// Описание ошибки:
//Ошибка при вызове метода контекста (Send)
		   ОтправленныеДокументы = SendTask.Send();
по причине:
Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, 
       HTTP error: MessageToPost.DocumentAttachments[0]: Документ не может быть отправлен в указанном формате

**Comment by ButurlakinSemyon** [comment]
Добрый день!
ИдФайл в документе, который вы прислали содержит префикс "ON_SCHFDOPPR", что соответствует 155@ формату документа.
820@ формат должен содержать префикс "ON_NSCHFDOPPR".

**Comment by kvazymoda** [comment]
Добрый день, коллеги!
Да, исправили. Отправить получилось. 
Но документ, у получателя, принялся с сообщением об ошибке:
«ФИО подписанта в документе не совпадает с ФИО владельца эл. подписи»
подскажите что не так?
приложил сам файл, фото из интерфейса Диадок.
Нужна ли ссылка на сам документ в системе Диадок?
 
PS: Приложенные файлы, просьба не публиковать в открытом доступе.
 
Спасибо.
 
Ямкин Андрей.

  
>Среда, 24 февраля 2021, 7:26 +03:00 от ButurlakinSemyon <notifications@github.com>:
> 
> 
>Добрый день!
>ИдФайл в документе, который вы прислали содержит префикс "ON_SCHFDOPPR", что соответствует 155@ формату документа.
>820@ формат должен содержать префикс "ON_NSCHFDOPPR".
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
С Уважением,
Андрей Ямкин

**Comment by ButurlakinSemyon** [comment]
Согласно порядку обмена счетами-фактурами, Приказ Минфина от 10.11.2015 N174н п. 1.2, ФИО подписанта в счете-фактуре должны совпадать с ФИО владельца сертификата КЭП. В вашем случае они разные. Если открыть документ в вебе, то можно увидеть разницу.
Например, ФИО владельца эл. подписи:
![image](https://user-images.githubusercontent.com/74642650/109146678-f2a22380-7785-11eb-8cb0-de3509706ebc.png)

А ФИО подписанта в документе:
![image](https://user-images.githubusercontent.com/74642650/109146770-0cdc0180-7786-11eb-8528-75da8e1a3341.png)

**Comment by GilimkhanovDenis** [comment]
Первоначальный вопрос решён. Тикет закрываю.
Новые вопросы предлагаю оформлять отдельным issue.

**Comment by kvazymoda** [comment]
Добрый день.
Да, все верно.
Спасибо.
 
Ямкин Андрей.
  
>Пятница, 26 февраля 2021, 14:22 +03:00 от Гилимханов Денис <notifications@github.com>:
> 
> 
>Первоначальный вопрос решён. Тикет закрываю.
>Новые вопросы предлагаю оформлять отдельным issue.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
С Уважением,
Андрей Ямкин
