### ISSUE TITLE
Ошибка при соединении через DLL

### ISSUE THREAD

**Issue by t1975453** [diadoc/diadocsdk-1c-docs#592]
Добрый день! Номер диагностики 20148741
![1](https://user-images.githubusercontent.com/26548420/108950554-3c0c4900-7688-11eb-8321-8ba1bc029829.png)
![2](https://user-images.githubusercontent.com/26548420/108950556-3d3d7600-7688-11eb-8c8d-0f4533df5650.png)
![3](https://user-images.githubusercontent.com/26548420/108950618-53e3cd00-7688-11eb-8723-71af6f9a52c5.png)

Что не так? Компонента зарегистрирована и загружена. 
Функция TestConnection2() вызывает ошибку, представленную на скриншотах

**Comment by ButurlakinSemyon** [comment]
Добрый день!
WinHttpSendRequest 0x2ee2 (12002) - это таймаут соединения.

https://docs.microsoft.com/en-us/windows/win32/winhttp/error-messages :
```
ERROR_WINHTTP_TIMEOUT
12002
The request has timed out.
This error can be returned as a result of TCP/IP time-out behavior, regardless of time-out values set in Windows HTTP Services.
```

Почему запросы уходят в time-out, нужно разбираться на вашей стороне. 
По диагностике видно, что у вас есть прокси. Возможно у вас так настроен прокси.
Второй вариант: в компоненте что-то указано не до конца.

**Comment by t1975453** [comment]
Для версии 2.0 использовалось AddIn компонента v5.32.4.635 x64. В ней все нормально работает. Проблем с прокси нет. В версии 3.0 данная компонента не загружается. Для этого была использована COM компонента v5.32.4.635 x64. Но она не проходит тест соединения. Соответственно, не выполняются и другие функции компоненты

------------------
Второй вариант: в компоненте что-то указано не до конца.
------------------
Конкретно что именно? Она скачана с вашего сайта https://1c-docs.diadoc.ru/ru/latest/Downloads.html и что там не так, я не могу понять

**Comment by volodkindv** [comment]
Покажите настройки прокси в Internet Explorer.
Приложите сюда вывод команды `tracert diadoc-api.kontur.ru`

**Comment by t1975453** [comment]
![image](https://user-images.githubusercontent.com/26548420/110574338-c2dc1e00-817e-11eb-9fac-21b5b65ba426.png)

Результат трассировки. Внешний айпи скрыл

![image](https://user-images.githubusercontent.com/26548420/110574478-fc148e00-817e-11eb-91f6-1f43e43fa521.png)

Прокси нет

**Comment by volodkindv** [comment]
Попробуйте в ProxyMode указать "UseDefaultProxy".
У загруженной компоненты вызовите GetVersion(), чтобы убедиться, что не загрузилась более старая версия. 
Можете ли проверить подключение на Addin компоненте той же версии с теми же настройками proxy?
У них одна кодовая база. 

> В версии 3.0 данная компонента не загружается

Что такое версия 3.0, и почему компонента не загружается?

**Comment by t1975453** [comment]
![image](https://user-images.githubusercontent.com/26548420/112813822-1237af00-9098-11eb-99b0-832947042493.png)
Загружается верная версия
![image](https://user-images.githubusercontent.com/26548420/112813958-37c4b880-9098-11eb-98f1-20c634750e1e.png)

`
Что такое версия 3.0, и почему компонента не загружается?
`

Конфигурация Бухгалтерия предприятия 3.0 не загружает компоненту AddIn

**Comment by t1975453** [comment]
В AddIn в БП 3.0 следующая ошибка:
![image](https://user-images.githubusercontent.com/26548420/112817329-bf5ff680-909b-11eb-8350-7192f3559988.png)

В БП 2.0 такой ошибки нет. Код идентичен, библиотека та же

**Comment by IrinaShmonina** [comment]
@t1975453 Здравствуйте,
1. Какая версия платформы? 
2. Для БП 2.0 и БП 3.0 вероятно разные версии платформы? 
3. Менялась ли битность платформы?

**Comment by t1975453** [comment]
1) версия платформы используется одна для двух версий конфигураций: на текущий момент 8.3.17.1851
2) нет, обе конфигурации находятся на одном сервере
3) битность сервера 64, платформы тоже
