### ISSUE TITLE
Привязать приглашенного контрагента к группе через АПИ

### ISSUE THREAD

**Issue by NickVStepin** [diadoc/diadocsdk-1c-docs#593]
Подскажите, можно ли через АПИ привязать (или указать в приглашении) контрагента к существующей группе?

**Comment by volodkindv** [comment]
Если речь про группы в веб-версии Диадок, то через API к ним доступа нет.
![image](https://user-images.githubusercontent.com/12305552/109117459-da211180-7763-11eb-979f-b15e4465fee5.png)
