### ISSUE TITLE
CreateSendTaskFromFile с типом "NonformilizedDocumentContent"

### ISSUE THREAD

**Issue by Sergguha** [diadoc/diadocsdk-1c-docs#594]
Добрый день!
Для отправки произвольных двоичных данных в Диадок использовался метод Диадок-компоненты `Organization.CreateSendTaskFromFile(<Path>, <Type>)` с Type = "NonformilizedDocumentContent".
Сейчас вызов этого метода возвращает исключение "Неверная версия вложения".
Как теперь следует отправлять такие данные в Диадок?

**Comment by volodkindv** [comment]
Добрый день.
Сейчас следует пользоваться методом [createpackagesendtask2](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#organization-createpackagesendtask2). Добавлять документы в исходящий Package методом AddDocumentFromFile(). Параметры метода AddDocumentFromFile() можно узнать, вызвав Organization.GetDocumentTypes().
Метод CreateSendTaskFromFile не поддерживается с 2016 года: https://1c-docs.diadoc.ru/ru/latest/History/release_info/5_5_0.html

**Comment by Sergguha** [comment]
Благодарю, так и сделаем.

**Comment by Sergguha** [comment]
Используем CreatePackageSendTask2(), добавляем документ AddDocumentFromFile("Nonformalized", "default", "v1", ПолноеИмяФайла), как можно указать Номер и Дату этого неформализованного документа? Если попытаться из передать в метаданных
```
MetaDataItem = DocumentContent.AddMetadata();
MetaDataItem.Key = "number";
MetaDataItem.Value = НомерДокумента;			
MetaDataItem = DocumentContent.AddMetadata();
MetaDataItem.Key = "date";
MetaDataItem.Value = ДатаДокумента;
```
Ругается "Provided odd metadata items. Keys: number, date".

Подскажите, как можно передать Дату и Номер неформализованного документа?

**Comment by Sergguha** [comment]
Сам написал, сам ответил: следует использовать поля метаданных DocumentNumber и DocumentDate (имена полей регистрозависимые)
