### ISSUE TITLE
Непонятное поведение GetDynamicContent("Buyer") на некоторых документах (ошибка?)

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#595]
Добрый день.

При попытке получения данных некоторых "старых" ранее полученных тестовых документов обнаружили, что стали получать ошибку выполнения при обращении к **GetDynamicContent("Buyer")** на некоторых документах.

**Общая информация для упрощения «разбора полётов»:**
Организация:		Тестовая организация №2918743
ИНН:			9629187430
КПП:			962901000
ID организации:	0d7430bf4a9d4acca06e3ba0720e3e91@diadoc.ru

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.32.4.635**.

Для некоторых уже подписанных с обеих сторон тестовых документов при попытке получения контента получателя с помощью вызова **GetDynamicContent("Buyer")** для документа объекта возникает исключение и ошибки вида:

_Ошибка при вызове метода контекста (GetDynamicContent): Произошла исключительная ситуация (DocumentBase.GetDynamicContent): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid content to parse for document type=[typeNamedId=XmlAcceptanceCertificate, function=default, version=utd_05_01_01, titleIndex=1]_

Документы подписаны с обеих сторон. Т.е. у них точно есть и контент отправителя, и контент получателя. Ранее такой проблемы не было и данные контента получателя для этих документов возвращались без ошибок (об этом просто есть информация в БД, ранее полученная именно по этим документам).
Точно сказать с какой версии АПИ началась проблема мы не можем, т.к. долгое время к этим документам не обращались (это тестовые документы конца 2019 года).

Список ID документов на которых была замечена проблема (это, скорее всего не все, а только то, что мы заметили):
b67880b2-6a4e-49c7-9fce-7ecdeb475933f1d74360-a22d-480e-984f-90344e49c55e
b075bcf9-587a-42d3-9e3e-2e40f3c8b944f7b990a7-f172-40fc-b3e0-c8555c545ee7
4a0f9f2d-e8f2-4380-aeaf-d342bdbc094cd3c704a3-1dbc-4612-b695-0380e333e6a7
3ff01593-c624-4b45-ac32-3de9d466d5618142cb71-031c-4722-80e5-743700293a0f
3f4cec97-6beb-480e-b033-5d5dd238ff762ba6b9ec-c04c-4683-8107-bf98c03c36d9
3da95a81-acf2-43bd-af84-8fb4a8c5d25c5606dc03-837a-418b-82fc-400a48c2803c
321c49fb-46c2-4993-9e49-dff96fc50516806b36ba-7731-4f40-bc20-fcc9f4e8f314
2cb1c870-924f-4e15-b54f-ef3ef0f99a982aa29e02-2f0f-42c4-bf80-cbbe0de79182
1bfea64a-5993-4ba2-8825-2a5d556e821b665b3043-3288-474b-9f47-5cfccc7a1f73
01126d6a-2fe4-4df6-8434-ab6951b87221216cb261-07b2-4224-bbb1-a18d91127d5c
b943ea49-db46-4f41-a9d2-a6596ac86a2c3950986e-a14a-4450-8f7f-5dfde3429062
bbafd2af-751a-46c5-9799-858b05b2a9bfc449c301-3a48-4015-8b76-f7f6d825423e
a544922c-3527-41b2-b4f3-c147ced0806ade1fda05-2942-47b4-9fb2-9828f5c2296c
a280ed33-fbae-4e7c-aa18-ff546d0b4750a8cb25f1-84d0-4997-86bd-bed92e0074aa
9b78e722-413f-4d2c-b82a-26675cf648a52a2ab756-e8a1-49e6-b25e-8741648bfb7c
9098d752-4b5a-412d-bc8f-c1726d7d091db2f068a8-1b90-4171-b3cb-1ee12db7b720
8f7eceab-e5e1-42f1-bca1-2419f2a747841686d183-7bc1-4335-a7f7-c74ccfd7b8ec
7911655f-3fa7-4946-97b0-6a4408db67eae34e4603-3ef2-4bd5-8614-f12c9b7cd478
78588b4f-533b-4752-b183-76bf061ba0b2596ac4cc-aad2-47a0-bc24-84630e198746
77b86b61-ccaf-4191-9602-383ae7b3ccdfe990ca74-a3cd-4fe0-8933-2045884cbc62
7735b0c2-bbf8-470a-aee7-98b253d1b118812f2c81-eb8d-492a-9bab-656091882381
716415c5-b935-492e-9ed8-9c48bea8f7e1bbf35f86-0c67-4379-83e3-f67dd5ec6730
6f6c87c9-be9e-46ca-a5f9-d4e86e85c68439f9c51e-d4f1-4f34-a258-4a66e0a555b7
6b42ad88-7978-4ed2-8d4f-890fcb8f8d925fb22e5f-f161-4492-8bc7-c5473e5e576a
6ad18ac4-94a8-47b9-9840-5ca858180ee1aae27e25-95cf-42a6-84d2-c4cb4f987670
666894a2-7c99-4cba-a7b0-5fdc6183bcbacdf6f74f-f96f-42a9-aa60-37c1b5518d56
6050fef5-9760-45d1-8e8a-4b122fe38a78c0de86b2-b26d-4938-8b39-62486c260ab7
bc469862-7db8-451b-8e9e-31d98e317f59635beb8c-9d95-4fd4-88ae-ad7852f4f1d6
c0f976ff-02e9-4e4c-8761-a462b4e6c58ebe08513d-7b84-4fc2-89e0-8f2d498b492e
caa970f9-bb37-4ec7-8742-d2d94b79470fcf822148-4e6c-409d-a36e-9f8b3704e2bd
d57558db-4be1-4c84-907b-838473dcb231de0107ba-a763-464d-85e4-b69d69454d7e
e565475a-d48a-4331-b074-0439f611432268f45919-cd42-46ec-8aaa-d9f56db1323b
e597bc7d-c411-47d6-82ed-3ac534314b64a741136c-d4df-4315-81b9-bcb269529486
f5d5052e-06d9-4f9b-b5b4-3782585fb89f106340e3-61df-4397-b514-72609f078e34
f9e121dd-f0c6-4d9f-ad0f-c246f19d33049195ca7e-de72-48e5-91ed-1d7371e4e6ed

Что характерно, у всех этих документов версия XSD = utd_05_01_01, а функция = "ДОП".

Большая просьба ответить, в чем заключается проблема и почему попытка получения динамического контента получателя для данных документов завершается с ошибкой.

Спасибо.

**Comment by i82** [comment]
Добрый день. Прошу прощения за долгий ответ. Мы продолжаем исследовать проблему, но решения пока нет.

**Comment by GilimkhanovDenis** [comment]
В https://github.com/diadoc/diadocsdk-1c-docs/issues/711 та же ситуация, этот тикет закрою
