### ISSUE TITLE
Перечитать коллекцию Подразделений

### ISSUE THREAD

**Issue by soldatof** [diadoc/diadocsdk-1c-docs#596]
Здравствуйте!

Можно ли как-то перечитать коллекцию Department в объекте Organization?
Например, если было создано новое подразделение через веб-сайт или api через http запрос.

Сейчас коллекция не обновляется, и если документ был отправлен в новое подразделение, то в списке документов новое подразделение отображается только после повторной авторизации.

Работа через 1С, версия модуля 5.46.01.851

**Comment by volodkindv** [comment]
Здравствуйте. Можно, для этого надо заново авторизоваться в компоненте.

**Comment by soldatof** [comment]
> Здравствуйте. Можно, для этого надо заново авторизоваться в компоненте.

Больше никаких способов нет? Может какой-то метод есть, что бы перечитать коллекцию?

**Comment by volodkindv** [comment]
Других способов нет.
