### ISSUE TITLE
Метод Organization.GetDocumentEventList возвращает данные не с первого раза

### ISSUE THREAD

**Issue by nikolayuy** [diadoc/diadocsdk-1c-docs#598]
Используем Com-компоненту (5.29.11.567) для пометки в 1С документов, которые были подписаны контрагентами в ЭДО.
Первоначально, получили все события с момента начала работы компании с ЭДО с помощью метода GetDocumentEventList без указания идентификатора сообщения. В дальнейшем запоминаем идентификатор последнего обработанного сообщения и в следующий раз вызываем GetDocumentEventList с этим идентификатором.
При попытке повторно получить старые события, столкнулись со следующей ситуацией.
При передаче в метод GetDocumentEventList идентификатора события, после которого совершенно точно есть более новые события, метод возвращает пустую коллекцию.
Если метод вызвать с этим же идентификатором через некоторое время, то данные будут возвращены.
Прокомментируйте, пожалуйста, данное поведение метода.
Есть ограничения на количество и время вызова метода? Или неправильно его используем? Можно ли как-то понять, что более новые события после события с переданным идентификатором есть, но не возвращены по каким либо причинам?

> 
	События = Организация.GetDocumentEventList(EventId);
	lastEventId = "";
	СтопОбработка = Ложь;
	Пока События.Count > 0 Цикл
		Для Инд = 0 По События.Count - 1 Цикл
			Событие = События.getitem(Инд);
			Если Событие.EventId = СтопEventId Тогда
				СтопОбработка = Истина;
				Прервать;
			КонецЕсли;
			ТипСобытия = ВернутьСтатусСобытияПоИмени(Событие.EventType);
			Если ТипСобытия = Перечисления.ТМ_СтатусыСобытийДокументовВЭДО.Accept Тогда
				ОбработатьПодписание(Событие);
			КонецЕсли;
			lastEventId = Событие.EventId;
		КонецЦикла;
		Если СтопОбработка Тогда 
			Прервать;
		КонецЕсли;
		События = Организация.GetDocumentEventList(lastEventId);
	КонецЦикла;

**Comment by volodkindv** [comment]
У вас довольно старый релиз компоненты. В первую очередь проверьте, будет ли описанное поведение повторяться на последней версии (на текущий момент это 5.33.4).

Если будет повторяться, то нам для проверки понадобятся boxid организации и id события, с которого вы начинаете чтение ленты.

**Comment by nikolayuy** [comment]
В истории изменений последнее упоминание GetDocumentEventList есть в описании версии 5.26.3 (Выпущено 2019-03-29). У нас более новая версия.
До последнего времени (начало этого года) такое поведение не встречалось и в нашей версии: код, в котором происходит остановка из-за возврата данных, работал в 2019 году и начале 2020.
Были какие-то изменения в работе с событиями на стороне сервера?

**Comment by volodkindv** [comment]
Для диагностики укажите следующие данные:
- boxid и id события, с которого вы начинаете чтение ленты
- даты (хотя бы приблизительно), когда возникала пустая коллекция в GetDocumentEventList
- ключ разработчика (ApiKey) - публичная часть, без GUID на конце.
- желательно еще логин/отпечаток сертификата пользователя, под которым была авторизация.

**Comment by nikolayuy** [comment]
Последнюю версию компоненты ещё не поставили на тестовый сервер, поэтому пока её поведение не проверили.

1. boxid 0f48482606fa445593051ae136e4fb8e@diadoc.ru
2. id события, с которым вызывали метод: 04c24fa9-7733-441e-a138-fd4b56d5c10a
3. Примеры проверок.
Начало проверки 17.03.2021 18:14:26, остановка 17.03.2021 18:16:27 (где-то после обработки события 91b24791-adfe-47f0-ac9e-2827f9908bc4)
Раньше такого не замечал, но для комментария снова запустил получение данных с того же идентификатора, и получение остановилось после того же события, что и вчера:
17.03.2021 18:24:41 - 17.03.2021 18:28:23 (последнее обработанное событие о подписании e2959fbf-e8a1-4ed0-9f03-da0c6f2d6254)
18.03.2021 10:00:40 - 18.03.2021 10:06:04 (последнее обработанное событие о подписании e2959fbf-e8a1-4ed0-9f03-da0c6f2d6254)

4. API ключ используем от модуля Диадок, за который платим, но не используем (наш менеджер сказал, что так можно делать) 1C-DDPro-v3-0
5. Login = "o.miasova@tmtr.ru"

**Comment by nikolayuy** [comment]
Версия компоненты 5.33.4.674.
id события, с которым вызывали метод: 04c24fa9-7733-441e-a138-fd4b56d5c10a
18.03.2021 12:00:52 - 18.03.2021 12:03:37 (последнее обработанное событие о подписание документа cba372ba-017d-4b8f-abb5-6db49d074468, которое идёт раньше события e2959fbf-e8a1-4ed0-9f03-da0c6f2d6254, на котором остановилось при проверке в 18.03.2021 10:00:40)

**Comment by ButurlakinSemyon** [comment]
Добрый день!

Описанная вами ситуация не воспроизводится на последней версии компоненты.
Попробуйте обновить компоненты до последней версии. Если ситуация повториться, то необходимо прислать новые логи, но с расшифрованным траффиком. 
Просим собирать логи через Fiddler - он расшифровывает траффик. Wireshark по умолчанию этого не делает (это можно настроить, инструкцию нужно поискать в интернете).

**Comment by nikolayuy** [comment]
Подскажи, пожалуйста, как правильно настроить подключение через прокси?
Прокси сервер Fiddler запущен на порту 8866

```
 	Попытка
 	 	ДиадокКлиент = Новый COMОбъект("Diadoc.DiadocClient"); 
 	Исключение
 		Сообщить(ОписаниеОшибки());
 		Возврат;
 	КонецПопытки;
 	ДиадокКлиент.ApiClientId = СокрЛП(ApiClientId);
 	ДиадокКлиент.ServerUrl   = СокрЛП(ДиадокServerUrl);
 	ДиадокКлиент.ProxyMode 	 = "UseProxy";
 	ДиадокКлиент.ProxySettings.Url = "127.0.0.1:8866";
 	Попытка
 		Подключение = ДиадокКлиент.CreateConnectionByLogin(Login, Password);
 	Исключение
 		Сообщить(ОписаниеОшибки());
 		Возврат;
 	КонецПопытки;

``` 

Ошибка при вызове метода контекста (CreateConnectionByLogin): Произошла исключительная ситуация (DiadocCom.CreateConnectionByLogin): WIN32[0x00002F8F]WinHttpSendRequest

**Comment by GilimkhanovDenis** [comment]
Добрый день

Укажите
`ДиадокКлиент.VerifySslCertificate = Ложь;`

**Comment by nikolayuy** [comment]
Благодарю!

**Comment by GilimkhanovDenis** [comment]
Добрый день!

Проверьте, пожалуйста работу метода сейчас - должно исправиться.

Также прошу обратить внимание, что использовать в собственных интеграциях ключ, встроенный в наши типовые решения не рекомендуется.
Причины:
- Ключи от неподдерживаемых типовых решений постепенно блокируются и интеграция на вашей стороне в определённый момент не сможет авторизоваться
- Ошибка из данного обращения связана с тем, что у этого ключа есть особы права и ограничения в сервисе

Поэтому, лучше получить свой собственный ключ API (через менеджера или [оставив заявку](https://www.diadoc.ru/integrations/api#order-form-integration))

**Comment by nikolayuy** [comment]
Больше ситуация не повторяется ни на старой версии компоненты, ни на новой, ни с ключом от модуля, ни с собственным.
API ключ получили - будем использовать его.
Благодарю за помощь!
