### ISSUE TITLE
Подписание неформализованных документов

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#599]
Здравствуйте. Подниму старую тему, как все-таки можно подписать неформализованный документ с помощью метода ReplySendTask2.send(). В документации сказано, что использовать ReplySendTask не рекомендуется, нужно использовать ReplySendTask2. Ну хорошо, как подписать например УПД в документации подробно описано и всё работает. Но как подписать неформализованный документ конкретного примера нет. 
Например для подписи УПД получаем объект последовательно методами: Document.CreateReplySendTask2("AcceptDocument").ContentItems.GetItem(0).Content.UniversalTransferDocumentBuyerTitle и с этим объектом работаем. Для неформализованного документа есть только один вариант: Document.CreateReplySendTask2("AcceptDocument").ContentItems.GetItem(0).Content у полученного объекта BaseContent есть только свойство Type и что дальше делать??? Подскажите реально рабочий вариант.

**Comment by volodkindv** [comment]
Здравствуйте.
В контексте электронного документооборота, формализованные документы - это xml с четкой структурой. Неформализованные документы - это просто произвольные файлы.
Контент - это объектное представление структуры xml файла. Он имеет смысл только для формализованных документов.
Поэтому для неформализованных документов нет смысла обращаться к Content. Можно проще:
```
Reply = Document.CreateReplySendTask2("AcceptDocument");
Reply.Send();
```

**Comment by evgen421** [comment]
Здравствуйте Данила. Этот вариант я уже пробовал, ничего не происходит, статус документа не меняется.

**Comment by IrinaShmonina** [comment]
@evgen421 , можете дать ссылку на документ?

**Comment by evgen421** [comment]
Подскажите как дать ссылку

**Comment by evgen421** [comment]
Проверил, подписывается документ, всем спасибо!
