### ISSUE TITLE
Ошибка при загрузки печатной формы документа

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#6]
Ошибка при загрузки печатной формы документа.
Ссылка на документ: https://diadoc.kontur.ru/3bfb9c4d-0203-4610-83c8-e15ba95fd8d2/Document/Show?letterId=cd61cd55-eedd-4489-a8c4-41cd9ad2bcce&documentId=a43f2165-4f2f-4dc7-a1ff-b62b7751b455
Из 1С необходимо получить печатную форму, используем метод
(DocumentBase.GetPrintForm): ##100[Ошибка сервера Диадок]code:409, HTTP error: Generating print form for this type of document is not supported. Can not render nonformalized to pdf.
Если по ссылке перехожу на сайт и жму скачать форму то ошибка "Не удалось распечатать документ."
![img-2016-07-06-14-19-20](https://cloud.githubusercontent.com/assets/20082460/16616264/b8ecfb4a-4384-11e6-97e6-27c01cfe1f5a.png)

**Comment by vasbur** [comment]
попробуйте сейчас повторить действие

**Comment by jakeqwert** [comment]
Да через минут 15 после ошибки форма стала загружаться. Но неудобно хотелось бы сразу, чтобы работало.

**Comment by vasbur** [comment]
к сожалению, у нас иногда возникают проблемы с функционированием сервиса, который генерирует печатные формы в формате pdf
