### ISSUE TITLE
Не запрашивать подписание НЕформализованных документов

### ISSUE THREAD

**Issue by JGhjfhgjkdh5486t** [diadoc/diadocsdk-1c-docs#600]
Добрый день.
Некоторым контрагентам при отправке НЕформализованных документов (NonformilizedDocumentContent) (Счета и/или других) требуется НЕ запрашивать подписание с их стороны, т.к. это неформализованный документ.
Возможно ли такое настроить и каким образом?
Выгрузка идет через внешнюю компоненту AddIn по API из 1С 7.7, версия 5.29.13.573

**Comment by IrinaShmonina** [comment]
@JGhjfhgjkdh5486t , добрый день

У NonformilizedDocumentContent есть поле NeedRecipientSignature - оно за запрос подписи отвечает.
Некоторые документы никогда не отправляются с запросом подписи (Счета, например, - [workflow 6](https://api-docs.diadoc.ru/ru/latest/proto/DocumentWorkflow.html)).

А вообще, мы рекомендуем перейти на PackageSendTask2
