### ISSUE TITLE
через API скачать документооборот целиком 

### ISSUE THREAD

**Issue by komissarovev** [diadoc/diadocsdk-1c-docs#601]
Добрый день, 
Я через API получаю печатную форму Document.GetPrintForm(ИмяФайлаПДФ,30);
Подскажите, как через через API скачать документооборот целиком включая технологические документы?

**Comment by GilimkhanovDenis** [comment]
В разделе "Методы" объекта [DocumentBase](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentBase.html) во второй колонке есть интересующие вас методы
