### ISSUE TITLE
Подключаемый модуль.

### ISSUE THREAD

**Issue by Verba77** [diadoc/diadocsdk-1c-docs#603]
Можно ли реализовать через подключаемый модуль след задачу. При открытии формы "ГрупповоеСопоставлениеНоменклатуры" для отдельного контрагента номенклатура искалась по нашим определенным правилам и заполняла соотв. колонку на форме.

**Comment by ButurlakinSemyon** [comment]
Добрый день!

Уточните пожалуйста сценарий:
1. "Для отдельного контрагента" - это означает, что только для одного нужно изменить логику поиска номенклатуры, остальные контрагенты должны отрабатывать по типовой? Или Для разных контрагентов, разная логика?
2. У вас где-то в 1С хранится связь номенклатуры контрагента с вашей номенклатурой и вы хотите, чтобы модуль искал связь там? Это регистр или справочник?

**Comment by Verba77** [comment]
1. нужно для одного отдельно взятого контрагента изменить логику сопоставления, остальные типовым способом.
2. Для данного контрагента нужно сопоставить номенклатуру по части наименования: берем наименование зашедшее из Диадока, берем часть его символов - это артикул, по артикулу ищем ном-ру, если не находим, то автоматически ее создаем и подставляем на форму.

-

**Comment by kulakovskaya** [comment]
Добрый день! Уточните, пожалуйста, версию модуля Диадок.

**Comment by Verba77** [comment]
> Добрый день! Уточните, пожалуйста, версию модуля Диадок.

Добрый. 
Стандарт 
5.47.01.85

**Comment by IrinaShmonina** [comment]
@Verba77 , добрый день
попробуйте использовать событие  событие ПолучитьНоменклатуру1С
