### ISSUE TITLE
выгрузка акта через обработку

### ISSUE THREAD

**Issue by TolochkovYu** [diadoc/diadocsdk-1c-docs#604]
Добрый день! При отправке акта по приказу 820 формируется заголовок в ЛК в отправленных как УПД, как сделать по умолчанию, чтоб при отправке вставал заголовок акта.  В файле xml стоит функция ДОП

**Comment by ButurlakinSemyon** [comment]
Добрый день!
Уточните, пожалуйста, что вы подразумеваете под сокращением "ЛК"?
Можете прислать ссылку на документ, который отправляете?

**Comment by TolochkovYu** [comment]
ЛК-Личный кабинет...могу прислать файл xml и скрин с личного кабинета.

**Comment by ButurlakinSemyon** [comment]
Жду файл и скрин.
Через какое интеграционное решение отправляли документ?
Возможно причина в DocumentTypeId. Ваш документ был отправлен как "UniversalTransferDocument", поэтому в заголовке и отображается УПД.
Для того, чтобы отправить акт, необходимо использовать "XmlAcceptanceCertificate"

**Comment by TolochkovYu** [comment]
Пробовал писать в строчке 
DocumentToSend = SendTask.AddDocumentFromFile("XmlAcceptanceCertificate", "ДОП", "utd820_05_01_01", ВременныйФайл)

была ошибка {ВнешняяОбработка.ОбработкаЭДО.МодульОбъекта(226)}: Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: Документ не может быть отправлен в указанном формате

Изменил на UniversalTransferDocument - результат док-т ушел...но заголовок УПД


![image (14)](https://user-images.githubusercontent.com/81348285/112440632-ffee0600-8d63-11eb-90eb-5b8a47220ea3.png)
[ON_NSCHFDOPPR_2BM-631918224361-20130709015155533678600000000_2BM-4415007811-441501001-201608191011012398919_20210323_4b4f475a-7844-11eb-ab55-ac1f6bbabf41.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/6203061/ON_NSCHFDOPPR_2BM-631918224361-20130709015155533678600000000_2BM-4415007811-441501001-201608191011012398919_20210323_4b4f475a-7844-11eb-ab55-ac1f6bbabf41.txt)

**Comment by GilimkhanovDenis** [comment]
У актов не бывает функции "ДОП" в описании типа документа. Правильная функция - "default"

Аналогичные вопросы:
https://github.com/diadoc/diadocsdk-1c-docs/issues/415
https://github.com/diadoc/diadocsdk-1c-docs/issues/448
https://github.com/diadoc/diadocsdk-1c-docs/issues/480
https://github.com/diadoc/diadocsdk-1c-docs/issues/501
https://github.com/diadoc/diadocsdk-1c-docs/issues/516

**Comment by TolochkovYu** [comment]
можно пример ?

**Comment by GilimkhanovDenis** [comment]
`DocumentToSend = SendTask.AddDocumentFromFile("XmlAcceptanceCertificate", "default", "utd820_05_01_01", ВременныйФайл);`

**Comment by TolochkovYu** [comment]
в формировании xml ничего не менять? он будет выгружаться как акт?

**Comment by GilimkhanovDenis** [comment]
В XML ничего не менять - в нём тэг 
> Функция="ДОП"
указан правильно

**Comment by TolochkovYu** [comment]
ок, спасибо, пробую

**Comment by TolochkovYu** [comment]
по результату, отпишу

**Comment by TolochkovYu** [comment]
тему закрываю! все отлично! спс ребята!)
