### ISSUE TITLE
Не подписывается входящий УКД

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#605]
Здравствуйте. Пытаюсь подписывать входящий УКД, ошибок не выдает, но и не подписывает.

ReplySendTask = Document.CreateReplySendTask2("AcceptDocument");
RST = ReplySendTask.ContentItems.GetItem(0).Content.UniversalCorrectionDocumentBuyerTitle;
RST.AcceptanceDate	= ДатаПолучения;
RST.DocumentCreator = Продавец;
RST.OperationContent = "С изменением стоимости согласен";
RST.DocumentCreatorBase = ДокументОснование;
Signer=RST.Signers.AddItems();
Signer.SignerDetails.LastName	= "Иванов"; 
Signer.SignerDetails.FirstName	= "Иван"; 
Signer.SignerDetails.MiddleName = "Иванович"; 
Signer.SignerDetails.INN = "1234567890"; 
Signer.SignerDetails.Position = "Директор"; 
Signer.SignerDetails.SignerPowers = "3"; 
Signer.SignerDetails.SignerStatus = "5"; 
Signer.SignerDetails.SignerPowersBase = "Должностные обязанности"; 
Signer.SignerDetails.SignerType = "1"; 
ReplySendTask.Send();

Подскажите, где ошибка.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Укажите, пожалуйста:

- какую версию компоненты используете ([DiadocApi.GetFullVersion()](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html#diadocapi-getfullversion))
- ссылку на документ ([Document](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentBase.html).PathUrl)
- начало используемого ключа API (префикс без гуида)

Бросается в глаза:
```
Signer=RST.Signers.AddItems();
Signer=RST.Signers.AddItems();
```
Добавили двух подписантов, но заполнили только одного

**Comment by evgen421** [comment]
Это я здесь по ошибке задублировал, в реальном запросе без дубляжа

**Comment by GilimkhanovDenis** [comment]
Ошибка в
`Signer.SignerDetails.SignerStatus = "5";`

Указанный документ отправлен с версией `ucd_05_01_03` - для неё невозможно указать SignerStatus = 5. Возможные значения 1-4 

```
<xs:complexType name="ExtendedSignerDetails">
    <xs:complexContent mixed="false">
      <xs:extension base="ExtendedSignerDetailsBase">
        <xs:attribute name="SignerStatus" use="required">
          <xs:annotation>
            <xs:documentation>Статус</xs:documentation>
            <xs:documentation>
							1 - работник организации продавца товаров (работ, услуг, имущественных прав) ИЛИ работник организации покупателя;
							2 - работник организации - составителя информации продавца ИЛИ работник организации – составителя информации покупателя;
							3 - работник иной уполномоченной организации;
							4 - уполномоченное физическое лицо, в том числе индивидуальный предприниматель.
						</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:enumeration value="1" />
              <xs:enumeration value="2" />
              <xs:enumeration value="3" />
              <xs:enumeration value="4" />
            </xs:restriction>
```
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

**Comment by evgen421** [comment]
Спасибо! Исправил, получилось подписать.
