### ISSUE TITLE
Вопрос по связыванию документов в пакеты

### ISSUE THREAD

**Issue by BorisRubin** [diadoc/diadocsdk-1c-docs#606]
Подскажите в каком месте обработки для 1С Бухгалтерии предприятия находится определение (инициализация) параметров SubordinateDocumentId / InitialDocumentId ?
И достаточно ли нам просто очистить эти параметры чтобы 2 Счета-фактуры связанные с 1-м Отчетом комитенту НЕ связывались в 1 Пакет на стороне получателя пакета?
Если можете указать место где лучше всего подменить эти параметры также будем признательны

**Comment by kulakovskaya** [comment]
Добрый день! 
Подскажите, пожалуйста, версию модуля Диадок.
Почему не нужно связывать счета-фактуры с документом "Отчёт комитенту"?

**Comment by BorisRubin** [comment]
1. версия 5.45.01.823
2. По отчету комитента выставляется 2 СФ, одна на услугу, которая перевыставляется клиенту от поставщика, а вторая на агентское вознаграждение. По требованию принимающей стороны (клиент в данном случае) информация по этим 2-м счетам-фактурам должна попасть в разные комплекты, а они попадают в один и по информации от коллег из Диадока происходит это именно из-за этого параметра связывания

**Comment by kulakovskaya** [comment]
какая у Вас конфигурация 1С?

**Comment by BorisRubin** [comment]
1C бухглатерия предприятия КОРП 3.0.88.22

**Comment by IrinaShmonina** [comment]
@BorisRubin, добрый день
Попробуйте через ПМ сделать. В событии ПослеПолученияТаблицыДокументовДляОтправки через ТаблицаСвязей попробуйте удалить записи со связью.

**Comment by BorisRubin** [comment]
Спасибо, нашли уже в отладчике и очищаем для одного из документов связи, вроде сработало.
