### ISSUE TITLE
Как получить полную историю с момента отправки документа?

### ISSUE THREAD

**Issue by anat3446134** [diadoc/diadocsdk-1c-docs#608]
Здравствуйте.

   Использую метод Document.Resolutions.GetItem(к) в цикле получаю данные об авторах события, но там нету параметра status.
Статус документа могу получить только текущий, как получить историю изменения статуса (status) с момента отправки документа и до его подписания?

**Comment by GilimkhanovDenis** [comment]
Только самостоятельно интерпретировать тип Resolution'а в какой-то статус
Другого способа в компоненте нет
