### ISSUE TITLE
Можно ли получать масив документов по которым прозошли события, без учета интервала?

### ISSUE THREAD

**Issue by anat3446134** [diadoc/diadocsdk-1c-docs#609]
Здравствуйте.

   Используя метеод DocumentsTask.GetDocuments() ,  я могу получать документы только за период по дате отправления (TimeStamp) или по дате документа (DocumentDate). 
   Можно ли получать все документы по которым происходили изменения, без учета даты?

**Comment by GilimkhanovDenis** [comment]
Возможно, вам подойдёт метод [Organization.GetDocumentEventList](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html?highlight=GetDocumentEventList#Organization.GetDocumentEventList)
