### ISSUE TITLE
Подпись документа

### ISSUE THREAD

**Issue by ShibaevAnton** [diadoc/diadocsdk-1c-docs#61]
Подскажите пожалуйста как правильно подписать документ.

В вашей обработке 1С если оправлен на согласование или на подпись его подписать можно только через сайт. Подскажите почему так было сделано? Есть какая то особенность?

Если нет то какой функцией API можно подписать документ по ссылке?

**Comment by denver069** [comment]
Для подписания черновика используйте метод [CreateOutDocumentSignTask()](http://1c-docs.diadoc.ru/ru/latest/CreateOutDocumentSignTask-(Document).html).
