### ISSUE TITLE
Не заполнены ИНН и КПП в УПД

### ISSUE THREAD

**Issue by borisovcpr** [diadoc/diadocsdk-1c-docs#610]
Здравствуйте.

Пытаюсь отправить подготовленный xml УПД через компоненту
DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01_hyphen", ИмяФайла);

В файле ИНН и КПП организации заполнены 
<ИдСв><СвЮЛУч НаимОрг="Общество с ограниченной ответственностью &quot;НашеООО&quot;" ИННЮЛ="7100000000" КПП="710000000"/></ИдСв>

Но в вебе в личном кабинете ни у отправителя, ни у получателя ИНН/КПП не заполнен
![image](https://user-images.githubusercontent.com/36307480/113011388-6c14a380-9182-11eb-9221-ec6ddb66c213.png)

**Comment by IrinaShmonina** [comment]
@borisovcpr , проверьте, что заполнено по следующему формату
`<СвПрод КраткНазв="название">
        <ИдСв>
          <СвЮЛУч НаимОрг="название" ИННЮЛ="инн" КПП="кпп" />
        </ИдСв>
      </СвПрод>
      <СвПокуп КраткНазв="название">
        <ИдСв>
          <СвЮЛУч НаимОрг="название" ИННЮЛ="инн" КПП="кпп" />
        </ИдСв>
      </СвПокуп>`
Также можно проверить xml в сервисе - https://www.diadoc.ru/docs

Еще рекомендуем " заменять на "&quot";

**Comment by borisovcpr** [comment]
Валидация xml в сервисе проходит. Правда, ИНН и КПП указаны в формате, как необязательные. Кавычки в файле заменены, это я неверно скопировал

![image](https://user-images.githubusercontent.com/36307480/113120210-0542c900-921a-11eb-8116-0131998d55a6.png)

Читал в старых задачах, что некоторая информация о продавце может тянуться не из xml, а из ящика, с которого отравляется файл. Такое может быть в данном вопросе?

**Comment by GilimkhanovDenis** [comment]
Пришлите, пожалуйста ссылку на документ (DocumentBase.PathUrl или адрес страницы из веб-интерфейса)

**Comment by borisovcpr** [comment]
https://diadoc.kontur.ru/260c689e-a95b-454f-ad63-2cebd5524e50/Document/Show?letterId=d695bab0-db7b-4157-b80a-585d8fca83d5&documentId=997c1875-54a0-4ace-b340-e9c1c745da4b

**Comment by IrinaShmonina** [comment]
@borisovcpr, здравствуйте
У вас настроена кастомная печатная форма, поэтому может не отображаться инн/кпп. Вам следует обратиться к вашему менеджеру, либо в техническую поддержку - https://www.diadoc.ru/support
