### ISSUE TITLE
Заполнение иных сведений в УПД перестал работать. Нужна возмездная помощь.

### ISSUE THREAD

**Issue by rom-kat** [diadoc/diadocsdk-1c-docs#612]
Уважаемые коллеги, перестал работать код.  

Функция ОбработатьСобытиеПослеЗаполненияКонтента(Параметры)
	
	DocumentType 	= Параметры.DocumentType;
	Content 		= Параметры.Content;
	ДокументСсылка 	= Параметры.ДокументСсылка;
	
	Если DocumentType = "XmlTorg12" Тогда
		
		Content.Number= ДокументСсылка.Номер;
		
		Товары=   ДокументСсылка.Товары;
		ВГраница= Content.Items.ВГраница();
		
		Для ИндексЦикла=0 ПО ВГраница Цикл
			
			Item=  Content.Items[ИндексЦикла];
			СтрокаТовары= Товары[ИндексЦикла];
			
			Item.Product=  СтрокаТовары.Номенклатура.Наименование+". "+СокрЛП(СтрокаТовары.Номенклатура.Производитель);
			
		КонецЦикла;
		
		Возврат Content;
	ИначеЕсли DocumentType = "XmlUTD" Тогда
		
		Если Content.Function = "Invoice" Тогда
		ИначеЕсли Content.Function = "Basic" Тогда
		ИначеЕсли Content.Function = "InvoiceAndBasic" Тогда
			Попытка				
				ДополнитьМассивKeyValue(Content.AdditionalInfoId.StructedAdditionalInfos, "инвойс", СокрЛП(ДокументСсылка.ДокументОснование.СчетНаОплатуПокупателю.ТД)); // заполнение иных сведений 
			Исключение
					Сообщить("Проверьте правильность заполнения поля ДТ");
			КонецПопытки;
	КонецЕсли;
		Возврат Content;
	КонецЕсли;	
КонецФункции // ОбработатьСобытиеПослеЗаполненияКонтента()

Вот этот кусок ДополнитьМассивKeyValue(Content.AdditionalInfoId.StructedAdditionalInfos, "инвойс", СокрЛП(ДокументСсылка.ДокументОснование.СчетНаОплатуПокупателю.ТД)); // заполнение иных сведений   Не работает.

Перестал работать после того как я обернул в условие 
Если ЗначениеЗаполнено(ДокументСсылка.ДокументОснование.СчетНаОплатуПокупателю) Тогда

Попытка				
				ДополнитьМассивKeyValue(Content.AdditionalInfoId.StructedAdditionalInfos, "инвойс", СокрЛП(ДокументСсылка.ДокументОснование.СчетНаОплатуПокупателю.ТД)); // заполнение иных сведений 
			Исключение
					Сообщить("Проверьте правильность заполнения поля ДТ");
			КонецПопытки;
КонецЕсли;

Затем убрал условие перезагрузил модуль, но не заработало.

Помощь нужна срочно. ГЛБух премии лишает.

**Comment by ButurlakinSemyon** [comment]
Добрый день! 
Уточните верси. модуля, на которой работаете.
Можете описать сценарий, что хотите заполнить?

**Comment by rom-kat** [comment]
Версия модуля: 5.47.01.875
Модуль типовой: Да
Версия компоненты: 5.33.4.674
Конфигурация: Бухгалтерия предприятия, редакция 3.0 (3.0.90.45)


В УПД в иные сведения должна попадать информация из реквизита счета. Все работало до того момента как для одного клиента не сделали реализацию не на основании счета. Без счета не отправлялся УПД. После разбирательств пришли к решению отключать ПМ перед отправкой УПД этому клиенту. И соответственно включать для остальных. 

Конечно же хотелось добиться корректной работы ПМ без его отключения. Поэтому стал разбираться. Нашел поиском этот код, обернул его условием  и после этого перестала выводиться информация совсем. 

Не могу настроить отладку. В основной модуль получается зайти, но вот в ПМ никак. Сейчас буду пробовать на сервере и подключу ПМ с диска.

**Comment by kulakovskaya** [comment]
Добрый день. Удалось ли разобраться с отладкой подключаемого модуля?
Если у Вас клиент-серверная база то в разделе "Настройки" - "Подключаемый модуль" должен быть указан серверный путь.

**Comment by rom-kat** [comment]
Добрый день. 
Отладку подключаемого модуля запустил. 
На форме отправки я кликаю на УПД  - в  отладчике в функция ОбработкаСобытияПодключаемогоМодуля ИмяСобытия = "ПослеЗаполненияКонтента" запускает процедуру  ОбработатьСобытиеПослеЗаполненияКонтента(ПараметрыСобытия)


А в ОбработатьСобытиеПослеЗаполненияКонтента ПараметрыСобытия.DocumentType = Неопределено. 


А должен выполняться вот этот код

	ИначеЕсли DocumentType = "Utd" Тогда
		
		Попытка				
					ДополнитьМассивKeyValue(Content.AdditionalInfoId.StructedAdditionalInfos, "инвойс", СокрЛП(ДокументСсылка.ДокументОснование.СчетНаОплатуПокупателю.ТД)); // заполнение иных сведений 
				Исключение
						Сообщить("Проверьте правильность заполнения поля ДТ");
				КонецПопытки;
				
			
		Возврат Content;

**Comment by kulakovskaya** [comment]
Добрый день. Можете ли Вы приложить файл подключаемого модуля?

**Comment by rom-kat** [comment]
Добрый день. Да, конечно.
[ПМ_Профиль-евро_010421.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/6262429/_.-._010421.zip)

**Comment by kulakovskaya** [comment]
В событии ПослеЗаполненияКонтента лучше использовать параметр **ТипКонтента**.
Возможные типы контентов можно посмотреть в функции **ТипыКонтента** модуля основной обработки.

**Comment by rom-kat** [comment]
Получилось. Спасибо.
