### ISSUE TITLE
МХ-1

### ISSUE THREAD

**Issue by Alekseevda** [diadoc/diadocsdk-1c-docs#613]
Добрый день.
Выполнил загрузку акта МХ-1, при просмотре в веб-версии документ выглядит как xml
https://diadoc.kontur.ru/87a6ba56-08de-478f-8f97-9d8287c38fa0/Document/Show?letterId=b19a9056-057a-4429-b066-5ce6cae61ef9&documentId=00caf5f4-84ea-4591-b913-de929f9fd27f

Сам код выгрузки:
SendTask = ОрганизацияДляОбмена.CreatePackageSendTask2();
SendTask.CounterAgentId = КонтрагентДиадок.Id;
		
DocumentToSend = SendTask.AddDocument("StorageInventoryAcceptanceCertificate", "default", "utd820_05_01_01");
DocumentToSend.comment = "Сформирован автоматически";
DynamicContent = DocumentToSend.Content;
Utd820_SellerContent = DynamicContent.UniversalTransferDocument;
		
Utd820_SellerContent.DocumentNumber	= НомерДокумента;
Utd820_SellerContent.DocumentDate	 	= ДатаДокумента;
Utd820_SellerContent.Currency 			= "643";
Utd820_SellerContent.Function 			= "ДОП";
Utd820_SellerContent.DocumentCreator 	= "ИнформацияОбОрганизации";

далее заполняю аналогично УПД
Подскажите, что я сделал не так, в документации про МХ-1 буквально два слова.

Спасибо.

**Comment by kulakovskaya** [comment]
Добрый день. В Диадоке не предусмотрена типовая печатная форма для документа МХ-1.

**Comment by Alekseevda** [comment]
Скажите пожалуйста, с МХ-3 аналогичная ситуация?

**Comment by kulakovskaya** [comment]
Добрый день. Да, для МХ-3 также нет типовой печатной формы.
