### ISSUE TITLE
1С, Выгрузка счета на оплату покупателю

### ISSUE THREAD

**Issue by kvazymoda** [diadoc/diadocsdk-1c-docs#614]
Добрый день, коллеги.
Выгрузили из 1С Счет на оплату, как файл xml. Выгружаем с помощью кода, он ниже.  Передаем чере Диадок, успешно.
При этом получатель, принимает файл и видит его, не как печатную форму счета, а как файл-xml. Не понимает что с этим делать.
Впорос, какие настройки(код) нужно применить, чтобы Счет на оплату, получил получатель, такой как в Вашем примере по ссылке:
https://www.diadoc.ru/docs/forms/notype

[текст_Счет_6a117010-3c67-4ff8-a336-5eba7b7fc4a8.txt](https://github.c
[текст_Счет_6a117010-3c67-4ff8-a336-5eba7b7fc4a8.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/6255698/_._6a117010-3c67-4ff8-a336-5eba7b7fc4a8.txt)
om/diadoc/diadocsdk-1c-docs/files/6255696/_._6a117010-3c67-4ff8-a336-5eba7b7fc4a8.txt)
И подпись была, если возможно.
Сам выгруженный файл, приложил.

// Текущий код по выгрузке счета_______________________________________
ПодключитьВнешнююКомпоненту("AddIn.DiadocInvoiceAPI");
//Создание объекта DiadocInvoiceAPI
DiadocApi_ = Новый("AddIn.DiadocInvoiceAPI");
DiadocApi = DiadocApi_.CreateObject();

//Задаем параметры подлючения к серверу
//DiadocApi.ApiClientId = КлючРазработчика;
DiadocApi.ApiClientId = "*****";
DiadocApi.ServerUrl = "https://diadoc-api.kontur.ru:443";

//Получение списка сертификатов
Certificates = DiadocApi.GetPersonalCertificates();

//Создание соединения
мОснованяОрг = ОбменСДиадок.ВернутьКонстанту("ОсновнаяОрганизация");
ИННОрганизации = ПолучитьРеквизитОбъектаНаСервере(мОснованяОрг,"ИНН");

СтруктураСертификата = ПолучитьОтпечатокСертификата(Certificates, ИННОрганизации); // Отпечаток, Сертификат
ОтпечатокСертификата = СтруктураСертификата.Отпечаток;
DiadocConnection = DiadocApi.CreateConnectionByCertificate(ОтпечатокСертификата);

ИНН = Прав(Certificates.GetItem(0).Inn,10);
КПП = Certificates.GetItem(0).kpp;

СтруктураКонтрагентов = ОбменСДиадок.ПолучитьСтрокуДоступныхИННКонтрагентов();
СтрокаИНН = СтруктураКонтрагентов.СтрокаИНН;
МассивКонтрагентов = СтруктураКонтрагентов.МассивКонтрагентов;
мКонтрагент = МассивКонтрагентов[0];

// Получение списка организаций
OrganizationList = DiadocConnection.GetOrganizationList();
Ц = 0;
Пока Ц < OrganizationList.Count() Цикл
Organization = OrganizationList.GetItem(ц);
мОрг = ПолучитьЭлементСправочникаПоЗначению(Organization.INN,"ИНН","Организации");
Ц = Ц + 1;
КонецЦикла;

SendTask = Organization.CreatePackageSendTask2();
МассДокКОтправке = ПолучитьВыборкуДокументовДляОтправки(мОрганизация,мКонтрагент);
Для каждого элем Из МассДокКОтправке Цикл
ПутькФайлуXML = СформироватьВременныйФайл(элем.Файл);

 Third_DocumentToSend = SendTask.AddDocumentFromFile("ProformaInvoice", "default", "v1",ПутькФайлуXML); 
ОтправленныеДокументы = SendTask.Send(); // Отправка счета из внешнего файла
_______________________________________________
Спасибо

**Comment by kulakovskaya** [comment]
Добрый день!
Типовой печатной формы для счета на оплату нет в Диадоке.
Если нужно отправлять счет в формате xml и при этом корректно визуализировать его, нужно приобрести кастомную печатную форму, для этого можете обратиться к вашему менеджеру.
Второй вариант - отправлять счет в любом другом формате, например, в pdf.
