### ISSUE TITLE
Передача маркированного товара

### ISSUE THREAD

**Issue by Xolto** [diadoc/diadocsdk-1c-docs#616]
Как указать в УПД что маркированный товар передается для собственного использования

**Comment by kulakovskaya** [comment]
Здравствуйте!
Согласно[ методическим рекомендациям от ГИС МТ](https://xn--80ajghhoc2aj1c8b.xn--p1ai/upload/%D0%9C%D0%A0_%D0%9E%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%AE%D0%97_%D0%AD%D0%94%D0%9E_%D0%BF%D1%80%D0%B8_%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87.pdf) в случае	приобретения или	безвозмездной передачи маркированного товара юридическими лицами и индивидуальными предпринимателями в целях использования, не связанных с его последующей реализацией (продажей), в документе о передаче (приемке) данных товаров в форме УПД  необходимо заполнить поле «СвВыбытияМАРК» с указанием вида оборота.

Данные сведения можно указать в УПД ДОП в теге ИнфПолФХЖ1:
- Идентификатор: ВидОборотаМАРК
- Значение: 9 – Перемещение товаров, не связанное с реализацией.

Пример:
![image](https://user-images.githubusercontent.com/54439404/114697103-eb83a480-9d36-11eb-99e6-c16e240df9ba.png)

**Comment by Xolto** [comment]
еще хотел заметить, (ознакомился с   методическим рекомендациям от ГИС МТ) наверное лучше использовать идентификатор: СвВыбытияМАРК Значение 1 - покупка товаров Юр лицами и ИП в целях использования "для собственных нужд", нежели ВидОборотаМАРК - это скорее связано спередачей в рамках договоров комиссии и агентских дог.

**Comment by kulakovskaya** [comment]
Да, вы правы. Спасибо за уточнение.
