### ISSUE TITLE
как установить дату произвольную дату получения при ответном действии?

### ISSUE THREAD

**Issue by vlad3190** [diadoc/diadocsdk-1c-docs#618]
Коллеги, добрый день!
Подскажите пожалуйста как установить дату произвольную дату получения при ответном действии?
ReplySendTask2 = Document.CreateReplySendTask2("AcceptDocument");   //CreateReplySendTask2
ContentItems = ReplySendTask2.ContentItems;
Как дальше установить произвольную дату получения товара? Приведите пожалуйста пример кода?

**Comment by GilimkhanovDenis** [comment]
Добрый день.

Если речь про подписание УПД формата [820 приказа](https://normativ.kontur.ru/document?moduleId=1&documentId=328588) и тэг `ДатаПрин` , то заполняется он в

`ContentItems[0].Content.UniversalTransferDocumentBuyerTitle.AcceptanceDate`

**Comment by vlad3190** [comment]
Спасибо!
