### ISSUE TITLE
Как изменить номер договора в счете фактуре

### ISSUE THREAD

**Issue by LowDzu** [diadoc/diadocsdk-1c-docs#619]
Мне необходимо убрать префикс в шаблоне "Договор №".
Через подключаемый модуль я убрал слово договор, но символ "№" и пробел остались, мне нужно убрать все что до слова Оферта.
Моя строчка в модуле: Протоконтент.TransferInfo.TransferBases[0].DocumentName = "";

Результат " № Оферта ОФ-1П от 10.02.2020"

**Comment by kulakovskaya** [comment]
Здравствуйте!
Подскажите, пожалуйста, версию модуля Диадок.

**Comment by LowDzu** [comment]
> Здравствуйте!
> Подскажите, пожалуйста, версию модуля Диадок.

5.47.01

**Comment by kulakovskaya** [comment]
Здравствуйте!
Модуль в печатной форме визуализирует символ "№", если нужно заполнить Протоконтент.TransferInfo.TransferBases[0].DocumentNumber.

Какая логика в заполнении DocumentNumber в подключаемом модуле?

**Comment by LowDzu** [comment]
> Здравствуйте!
> Модуль в печатной форме визуализирует символ "№", если нужно заполнить Протоконтент.TransferInfo.TransferBases[0].DocumentNumber.
> 
> Какая логика в заполнении DocumentNumber в подключаемом модуле?

Я уже решил свою задачу ранее, заменой текста "Договор" на нужный мне номер, а номера на "", тогда и система не подставляет "№", задача выполнена, но не очень корректно, думал существует макет который можно просто отредактировать.
