### ISSUE TITLE
Организация.CreatePackageSendTask() Метод объекта не обнаружен

### ISSUE THREAD

**Issue by PanyushkinN** [diadoc/diadocsdk-1c-docs#62]
Попробовал устанавливать поочередно все компоненты с ресурса http://1c-docs.diadoc.ru/ru/latest/Downloads.html.  

подключение следующим кодом (пример с компонентой AddInDiadocAPI2.dll):

ИмяФайла = "C:\NIK\1C\ExtForms\УТ\ЭДО\ДИАДОК\AddInDiadocAPI2.dll";
	
	
	Попытка 
		ЗагрузитьВнешнююКомпоненту(ИмяФайла);	
	Исключение 
		ЭтотОбъект.ПолучитьМакет("ФайлКомпоненты").записать(ИмяФайла);
		Попытка
			ЗагрузитьВнешнююКомпоненту(ИмяФайла);	
		Исключение
			СообщенияПользователям_ПоказатьСообщениеОбОшибке("ОшибкаЗагрузкиВнешнейКомпоненты", ОписаниеОшибки(), ИмяФайла);
			Возврат;
		КонецПопытки;
	КонецПопытки;
		
	DiadocInvoiceAPI_ = Новый("AddIn.DiadocInvoiceAPI");
	DiadocInvoiceAPI = DiadocInvoiceAPI_.CreateObject();
	
	DiadocInvoiceAPI.ApiClientId= "1SBox-5-0-817fcc7d-336f-4819-b522-c069be6c114f";
	DiadocInvoiceAPI.ServerUrl=   "https://diadoc-api.kontur.ru:443";
	DiadocInvoiceAPI.ProxyMode=	  "UseProxy";
	//DiadocInvoiceAPI.ProxySettings.Url=			СтруктураНастроек.Адрес;
	//DiadocInvoiceAPI.ProxySettings.Login=		СтруктураНастроек.Логин;
	//DiadocInvoiceAPI.ProxySettings.Password=	СтруктураНастроек.Пароль;
	
	Если НЕ DiadocInvoiceAPI.TestConnection() Тогда
		ВызватьИсключение("##200 Текущие настройки не позволяют подключиться к серверу " );
	КонецЕсли;

*************************
Организация распознается как com объект со всеми свойствами.
Но при попытке вызвать метод Организация.CreatePackageSendTask() Выдается ошибка "Метод объекта не обнаружен". Вопрос - что я делаю не так ?

**Comment by volodkindv** [comment]
Проверьте в отладчике результат функции:
DiadocInvoiceAPI.GetVersion()
http://1c-docs.diadoc.ru/ru/latest/GetVersion.html
Вероятно, у вас подключена какая-то старая версия компоненты (первая цифра версии будет меньше 5).
Если так, то попробуйте 2 вещи:
1) Перезапустить клиентский сеанс 1С. К сожалению, разработчики платформы не снабдили нас методом ОтключитьВнешнююКомпоненту(), поэтому до завершения сеанса в нем висит та версия компоненты, которую запустили первой.
2) Если это не сработает, то попробуйте зарегистрировать компоненту через regsvr32.

**Comment by PanyushkinN** [comment]
к сожалению не помогло. на компоненте 5.1.6.38
 та же ошибка

**Comment by volodkindv** [comment]
Возможность отправлять документы пакетами появилась в версии 5.5:
http://1c-docs.diadoc.ru/ru/latest/History.html#v5-5-08-04-2016
Возьмите последний релиз компоненты.

**Comment by PanyushkinN** [comment]
Большое спасибо за консультацию! Вы очень помогли.
