### ISSUE TITLE
Почему метод GetDocumentEventList("") возвращает ответ порциями по 100-150 событий?

### ISSUE THREAD

**Issue by vlad3190** [diadoc/diadocsdk-1c-docs#620]
Коллеги, добрый день! Подскажите, почему метод GetDocumentEventList("") или GetDocumentEventList("EvetID") возвращает результат порциями по 100-150 строк? При количество строк в ответе не фиксированно, может быть 120, 140, 146 итд.?

**Comment by vlad3190** [comment]
Версия компоненты Diadoc (5.33.4.674).

**Comment by GilimkhanovDenis** [comment]
Если вернулось 0 строк, то на данный момент события вычитаны до конца. Верхней границы размера коллекции в ответе нет
