### ISSUE TITLE
Ошибка при работе через прокси компоненты 5.33.6.682 . ErrorText = WIN32[0x00002EE2]WinHttpSendRequest

### ISSUE THREAD

**Issue by ptizaezhik** [diadoc/diadocsdk-1c-docs#621]
Интернет в нашей организации работает через прокси,
Сейчас используем компоненту версии 5.29.7.549 - проблем нет.
Решил проверить новую 5.33.6.682 - не работает 
TestConnection2 выдает ErrorText = WIN32[0x00002EE2]WinHttpSendRequest

Как только включаем прямой доступ к diadoc-api.kontur.ru - работает.
Ошибка в компоненте?

**Comment by GilimkhanovDenis** [comment]
Скорее нет, чем да

0x2ee2 - таймаут соединения. Почему он возникает, сложно сказать без знания настроек компа, настроек прокси-сервера, настроек подключения компоненты

Вероятнее, что неправильно указаны настройки прокси в компоненте

**Comment by ptizaezhik** [comment]
> 
> 
> Скорее нет, чем да
> 
> 0x2ee2 - таймаут соединения. Почему он возникает, сложно сказать без знания настроек компа, настроек прокси-сервера, настроек подключения компоненты
> 
> Вероятнее, что неправильно указаны настройки прокси в компоненте

А там есть возможность настроек прокси? Как?

**Comment by GilimkhanovDenis** [comment]
У [корневого объекта](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html) есть поля:

- ProxyMode
- ProxySettings
- AutoLogonPolicy

**Comment by ptizaezhik** [comment]
> 
> 
> У [корневого объекта](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html) есть поля:
> 
>     * ProxyMode
> 
>     * ProxySettings
> 
>     * AutoLogonPolicy

Спасибо. По-умолчанию стояло "UseDefaultProxy".
Поменял на "UseProxy" и указал адрес для нашей сети "proxy.local:8080" (без авторизации) - только тогда заработало.

Остаётся вопрос: почему при "UseDefaultProxy" не работает

**Comment by GilimkhanovDenis** [comment]
Для ответа на вопрос нам понадобятся:

- Лог WinHttp ([как собрать](https://docs.microsoft.com/en-us/windows/win32/wsdapi/capturing-winhttp-logs]), когда настройка в компоненте выставлена в UseDefaultProxy
- Номер [диагностики](https://help.kontur.ru/diadoc)

**Comment by ptizaezhik** [comment]
> 
> 
> Для ответа на вопрос нам понадобятся:
> 
>     * Лог WinHttp ([как собрать](https://docs.microsoft.com/en-us/windows/win32/wsdapi/capturing-winhttp-logs)), когда настройка в компоненте выставлена в UseDefaultProxy
> 
>     * Номер [диагностики](https://help.kontur.ru/diadoc)

Номер диагностики - 21505708

А с логами WinHttp проблема на Win 10.
Инструкция по указанной ссылке приводит к такому результату
"Используйте команду netsh trace start scenario=InternetClient"

Гугл не очень помог.
После netsh trace start scenario=InternetClient  формируется etl страшного размера.
Пробовал открывать через Microsoft Network Monitor  - не нашел сходу логов WinHttp.

Подскажете, как на Win10 собрать логи WinHttp ?

**Comment by GilimkhanovDenis** [comment]
Попробуем без логов исправить. Спасибо
