### ISSUE TITLE
Тип не определен (AddIn.DiadocInvoiceAPI)

### ISSUE THREAD

**Issue by komissarovev** [diadoc/diadocsdk-1c-docs#622]
Добрый день, 
Подключаюсь к апи выдает Тип не определен (AddIn.DiadocInvoiceAPI). Раньше работало. В чем может быть проблема?

ИмяФайла = "C:\Users\user\AppData\Local\Temp\212\AddInDiadocAPI_5_33_4_674_x86\AddInDiadocAPI.dll"
КомпонентаПодключена = ПодключитьВнешнююКомпоненту(ИмяФайла, ИмяКомпоненты, ТипВнешнейКомпоненты.Native);
КомпонентаПодключена = ПодключитьВнешнююКомпоненту("AddIn.DiadocInvoiceAPI");
ДиадокАПИ_ = Новый("AddIn.DiadocInvoiceAPI");

**Comment by IrinaShmonina** [comment]
@komissarovev , здравствуйте,
Попробуйте перерегистрировать компоненту. Если возникнут трудности, то можно обратиться в нашу техническую поддержку - https://www.diadoc.ru/support

**Comment by komissarovev** [comment]
Модуль диадок работает нормально. Не могу подключиться к API

**Comment by komissarovev** [comment]
ПодключитьВнешнююКомпоненту("AddIn.DiadocInvoiceAPI") возвращает ложь

**Comment by IrinaShmonina** [comment]
@komissarovev , обратитесь в нашу техническую поддержку - https://www.diadoc.ru/support
