### ISSUE TITLE
При работе с компонентой версии 5.33.6.682 вылетает 1С 7.7 "Аварийное закрытие".

### ISSUE THREAD

**Issue by klishev** [diadoc/diadocsdk-1c-docs#623]
Пытался выполнить подписание и отправку черновика УПД  с компонентой версии 5.33.6.682 (авторизация по сертификату).
Код следующий:

```
ДокКонтурДД = пАвторизацияКонтурЭДО.GetDocumentById(пИдДокКонтур);
	Если ДокКонтурДД.IsDeleted = 0 Тогда
		SendDraftTask  = пАвторизацияКонтурЭДО.CreateSendDraftTask(Лев(пИдДокКонтур,36));
		ExtendedSigner = SendDraftTask.AddExtendedSigner();
		ExtendedSigner.BoxId = пАвторизацияКонтурЭДО.Guid;
		ExtendedSigner.CertificateThumbprint = пОтпечатокСерт;
		AsyncResult = SendDraftTask.SendAsync();
		Если AsyncResult.IsCompleted = 1 Тогда
			флОбнДокЭДО = 1;
			СпрДокЭДО.идДокКонтур    = AsyncResult.Result.GetItem(0).DocumentId;
			СпрДокЭДО.СтатусЭДИ      = статЭДИКон;
			СпрДокЭДО.СтатусПередачи = 1;// "выгружен" из глПолучитьСписокСтатусовЭДО()
		КонецЕсли;
	КонецЕсли;
```

После получения AsyncResult 1С 7.7 вскоре "аварийно закрывается системой Win 10" (успевал прочитать, что AsyncResult.IsCompleted = 0).

Перед этим выполнял этот код с компонентой версии 5.32.2.632, результат был следующий:
AsyncResult.IsCompleted = 1, но у AsyncResult не было поля Result, поэтому скачал свежую версию компоненты.

Черновик УПД, над которым я пытался выполнить подписание и отправку по прежнему находится в черновиках.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Можете подсказать что за документ пытаетесь отправить из черновиков? Достаточно будет значения
`ДокКонтурДД.PathURL`

Также проверка `Если AsyncResult.IsCompleted = 1 Тогда` не совсем корректна:
`SendDraftTask.SendAsync()` - длительная операция и нет гарантии, что код из ветки `Если AsyncResult.IsCompleted = 1 Тогда`  выполнится.

Стоит давать время на исполнение метода. Например, периодически опрашивать AsyncResult на завершённость и только после того как операция завершится, смотреть в поле `AsyncResult.Result`

Рекомендация справедлива для любого AsyncResult'а

**Comment by klishev** [comment]
Спасибо за комментарий. Вопрос подписания и отправки документа на компоненте версии 5.32.2.632 удалось решить. С более новыми компонентами работать не будем (пробовал работать с компонентой 5.33.4, на ней тоже наша 1С 7.7 аварийно вылетает).

Для пользователя с сертификатом установил на сайте Диадок в разделе "Полномочия для подписания документов" реквизиты; после этого подписание с отправкой заработало.

**Comment by klishev** [comment]
В нашей реализации не критично, если код из ветки "Если AsyncResult.IsCompleted = 1 Тогда" не выполнится, так как потом мы перед любым действием обрабатываем все новые события ящика; которые будут содержать изменение состояния документа.
