### ISSUE TITLE
Документ не может быть отправлен в указанном формате.

### ISSUE THREAD

**Issue by spartandog** [diadoc/diadocsdk-1c-docs#624]
Добрый день. 
Подскажите, пожалуйста, XML файл какого формата передается в AddDocumentFromFile? 
Туда нельзя передавать подготовленный к ручной загрузке xml файл?
Собственно использую код из примера https://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html 
Second_DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01", _ФайлХМЛ); 
В_ФайлХМЛ ссылка на xml файл с УПД, этот файл без ошибок загружается руками, через веб интерфейс Диадок.
Через API я получаю ошибку: “MessageToPost.DocumentAttachments[0]: Документ не может быть отправлен в указанном формате”.
В УПД есть маркируемый товар, если это важно. 
Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

> Подскажите, пожалуйста, XML файл какого формата передается в AddDocumentFromFile?

Формат файла определён законодательством. Для "UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01" формат описан [здесь](https://normativ.kontur.ru/document?moduleId=1&documentId=328588)

> Туда нельзя передавать подготовленный к ручной загрузке xml файл?

Можно и нужно

> В_ФайлХМЛ ссылка на xml файл с УПД, этот файл без ошибок загружается руками, через веб интерфейс Диадок.

Некоторые ошибки в xml-файле веб-интерфейс исправляются автоматически. Причину ошибки `MessageToPost.DocumentAttachments[0]: Документ не может быть отправлен в указанном формате` можно будет понять, если предоставите контент передаваемого файла. 

Если в файле есть конфиденциальная информация, то предлагаю этот файл передать нам через техподдержку (почта ТП: diadoc@skbkontur.ru)

**Comment by spartandog** [comment]
Добрый день. 
Спасибо за ответ. 
Файл xml можно  загрузить по ссылке. 
https://drive.google.com/file/d/1z9Nij_EpBGpTxEhW_J8C6_5VrmSz-kli/view?usp=sharing
Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

В документе функция указана "ДОП", а в методе добавления файла на отправку вы его обозначили как "СЧФДОП".

Попробуйте изменить функцию или в контенте документа, или в методе добавления документа

**Comment by spartandog** [comment]
Все получилось, спасибо большое!
