### ISSUE TITLE
Проблема с получением печатных форм некоторых неформализованных документов начиная с 4 мая

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#625]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
КПП2: 783450001
ID организации: c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.32.4.635.**

У вас 04.05.2021 вышло обновление АПИ для 1С.
Возможно, это просто совпадение, но начиная с 4 числа у нас по некоторым не формализованным документам при попытке получения печатной формы документа с использованием GetPrintForm стали появляться ошибки подобного вида:

_Ошибка при вызове метода контекста (GetPrintForm): Произошла исключительная ситуация (DocumentBase.GetPrintForm): ##100[Ошибка сервера Диадок]code:409, HTTP error: Unknown error. Custom printer error
Text1: Error in expression: Документ.Номер_

Все документы не формализованные. С XML вложением внутри. 

**Документы по которым регулярно воспроизводится эта ошибка (ID документов):**
6c4bad75-9269-4b9c-809f-ce354393324d8f757dd9-9094-455a-b9a3-8b7ef08df4e0
6c4bad75-9269-4b9c-809f-ce354393324dc81a1cd2-113d-45c2-abdd-acb207002273
6c4bad75-9269-4b9c-809f-ce354393324dd93c9487-ede2-4a00-b09e-ed71393cb54d
f2072d6a-943a-42e3-ba72-c31ad2988fd155eeacae-6b10-4cbb-af97-7630af64d0d6
8f21d3d2-9388-4d56-9260-bac7a94b73a3bfe2342a-0777-4f75-bfef-a3f5ebc639d8
8f21d3d2-9388-4d56-9260-bac7a94b73a3349a3640-22a5-4ac0-866b-bed5482aa528
8f21d3d2-9388-4d56-9260-bac7a94b73a36c6509ff-939a-4955-8a79-fedd663f4950
03e9b775-a29f-4084-92ff-703a11be98cecc504d2b-745a-46d7-a9aa-9a20cb485208
d1eb9e9d-9d14-4e7d-bcc5-d5509bb49148fa9c8c40-e4dc-473f-8d95-07f9d27e8680
737c840d-0a32-4583-abd3-f858427240cddd6cec85-a8d2-4afa-bc82-379d50e70c4c
be3e86db-5c55-4e47-97c6-2ed9b39b61bf9c35c399-5e11-43d3-953e-8f5c040ec4d1
af196592-f3f6-4d12-bcc5-2dc4bd63c003f5cbf514-b029-4ca6-ba3b-6d9a29233f67

Возможно, это просто совпадение. 
Но может быть вам стоит проверить - не появилось ли каких-то ошибок в ваших механизмах формирования печатных форм.

**Comment by ButurlakinSemyon** [comment]
Добрый день!
Ошибка не связана с компонентой. Скорее всего проблема с настройкой кастомной печатной формы. Вам лучше обратится с этой проблемой в тех поддержку, Они посмотрят в чем конкретно ошибка.
