### ISSUE TITLE
Проблема с получением списка неформализованных документов

### ISSUE THREAD

**Issue by plandoff** [diadoc/diadocsdk-1c-docs#628]
Добрый день!
ООО "ГК ЮНИКОМ"
ИНН 2543107078, КПП 254301001
 
Работаем с вашим сервисом посредством AddIn Diadoc API. 
Для получения документов (в рамках задачи по обновлению статусов в своей системе) используем метод GetDocuments. Работа метода с примером есть в описании к API по ссылке https://sdk-new.readthedocs.io/en/latest/DocumentsTask.html. 
Проблема в том, что часть документов данный метод не возвращает. Речь идет о неформализованных документах.
 
К примеру, при попытке получить данные за 26.06.2019 я не вижу документ https://diadoc.kontur.ru/f92a4a6a-01eb-4bcc-a0c4-8bd85b1b9217/Document/Show?letterId=1fb9e689-acc0-44e4-a6a6-dd20ab306025&documentId=48b86545-da34-44f2-bd40-b3fce17fce08 
Но документ https://diadoc.kontur.ru/f92a4a6a-01eb-4bcc-a0c4-8bd85b1b9217/Document/Show?letterId=d5370f9e-7550-4141-b107-5f5c0c32dd0b&documentId=d4935d56-a5d5-4a1e-a276-0c1dd8a121e5 в выдаче присутствует. Это не единичный пример. 
 
Метод используем ровно так же, как в описании. Получаем все входящие либо исходящие документы (фильтр Category), например:
 
    DocumentsTask = Organization.GetDocumentsTask();
    DocumentsTask.FromSendDate = НачалоГода(ТекущаяДата());
    DocumentsTask.ToSendDate = КонецГода(ТекущаяДата());
    DocumentsTask.Category = "Any.Outbound;
 
    DocumentList = DocumentsTask.GetDocuments();
    ц = 0;
    Пока ц < DocumentList.Count цикл
        Document = DocumentList.GetItem(ц);
        ………..
    КонецЦикла;
 
 
 
Вот, к примеру, исходящий от нас документ https://diadoc.kontur.ru/f92a4a6a-01eb-4bcc-a0c4-8bd85b1b9217/Document/Show?letterId=788d914a-f1cd-4fe5-93dc-f5b8c8a27e5f&documentId=38ef8748-bc90-47bd-8747-a642a35308da. Я не могу также его получить данным способом.
В чем может быть причина? Могу ли я каким то другим способом обновлять статусы по документам? В описании к API не нашел ничего другого, кроме данного метода

**Comment by GilimkhanovDenis** [comment]
Добрый день

1) 
Документы
https://diadoc.kontur.ru/f92a4a6a-01eb-4bcc-a0c4-8bd85b1b9217/Document/Show?letterId=1fb9e689-acc0-44e4-a6a6-dd20ab306025&documentId=48b86545-da34-44f2-bd40-b3fce17fce08
и
https://diadoc.kontur.ru/f92a4a6a-01eb-4bcc-a0c4-8bd85b1b9217/Document/Show?letterId=788d914a-f1cd-4fe5-93dc-f5b8c8a27e5f&documentId=38ef8748-bc90-47bd-8747-a642a35308da

удалены

2) Уверены, что при запросе исходящих документов получаете документ https://diadoc.kontur.ru/f92a4a6a-01eb-4bcc-a0c4-8bd85b1b9217/Document/Show?letterId=d5370f9e-7550-4141-b107-5f5c0c32dd0b&documentId=d4935d56-a5d5-4a1e-a276-0c1dd8a121e5 а не связанный с ним в пакет https://diadoc.kontur.ru/f92a4a6a-01eb-4bcc-a0c4-8bd85b1b9217/Document/Show?letterId=42be2ed6-d276-4cae-823c-affa76ed7402&documentId=a0bc0f70-7bf6-490c-83b1-ccf087ff802a ?

**Comment by plandoff** [comment]
Добрый день! Спасибо за оперативный ответ!

1) Т.е. даный метод не возвращает удаленные документы?

2) Да, уверен

![image](https://user-images.githubusercontent.com/23355882/118438052-0dea5280-b727-11eb-8a8b-6f9c88a7e8d3.png)

**Comment by GilimkhanovDenis** [comment]
1. Удалённые документы не возвращаются - их можно запросить по идентификатору
2. На последней версии компоненты ситуацию воспроизвести не получилось.
Фильтр документов за 2019 год и категории  "Any.Outbound" возвращается 21099 документов, среди которых нет входящих

**Comment by plandoff** [comment]
1. Если не сложно, подскажите, каким методом я могу по идентификатору получить документ в контексте организации? В описании не нашел.
2. Это входящий документ, т.е. я его ищу как "Any.Inbound". Ну и версия компоненты у меня не последняя

**Comment by GilimkhanovDenis** [comment]
1. [Organization.GetDocumentById](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html?highlight=GetDocumentById#Organization.GetDocumentById)
2. Тогда логично, что указанный документ есть в фильтре. В изначальном вопросе у вас фильтр указан "Any.Outbound"

**Comment by plandoff** [comment]
Большое спасибо за помощь!
