### ISSUE TITLE
Возникновение ошибки "Неизвестная ошибка" при вызове различных методов

### ISSUE THREAD

**Issue by Avtomir-AMK** [diadoc/diadocsdk-1c-docs#629]
Добрый день.

С 14.05.2021 7:05:05 начала возникать ошибка: «Неизвестная ошибка» при вызове различных методов:
События = ТекущаяОрганизация.GetDocumentEventList(ПоследнееЗагруженноеСобытие)
ТекущаяОрганизация = СписокОрганизаций.GetItem(Индекс)
ТекСвязанныйДокументДиадок = ТекОрганизация.GetDocumentById(IDСвязанногоДокумента)
DocumentList = DocumentsTask.GetDocuments()

Версия компоненты: DiadocCom_5_33_7_685_x64.dll 
Например для GUID:
                606d53b1fa1f4f3b92eb43b3983a31f5@diadoc.ru
                ca94d31ff1e44365a7605381c3824934@diadoc.ru

Обновились до версии 5.34.0.964, ошибка сохранилась.

Подскажите, пожалуйста, в связи с чем возникают данные ошибки?
Спасибо.

**Comment by kulakovskaya** [comment]
Здравствуйте. Рекомендуем перерегистрировать компоненту.

**Comment by Avtomir-AMK** [comment]
Добрый день.
После перерегистрации компоненты ничего не изменилось, ошибки остаются.

**Comment by IrinaShmonina** [comment]
@Avtomir-AMK , здраствуйте.
1. Перезапускали ли вы сеанс 1С при регистрации компоненты? 1С могло что-то закэшить у себя и ходить по старым адресам и вызывать не то, что надо.

2. Если ошибка будет сохранятся, то пожалуйста обратитесь в нашу техническую поддержку любым для вас удобным способом - https://www.diadoc.ru/support
Для дальнейшей работы нам нужно будет собрать дамп и http-логи
