### ISSUE TITLE
Отправка неформализованного документа, требующего подпись

### ISSUE THREAD

**Issue by plandoff** [diadoc/diadocsdk-1c-docs#630]
Добрый день!
ООО "ГК ЮНИКОМ"
ИНН 2543107078, КПП 254301001

Вопрос в следующем: отправляю клиенту неформализованный документ (договор покупки). Стоит задача, чтобы клиент его обязательно подписал (будем осуществлять контроль по статусу документа). Но документ сразу отображается как "Документооборот завершен". Есть получить его через API, то у него Status в значении OutboundNoRecipientSignatureRequest. Т.е. судя по статусу я отправил документ без запроса ответной подписи. Вопрос в том, как отправить документ с запросом ответной подписи?
Вот ссылка на него - https://diadoc.kontur.ru/f92a4a6a-01eb-4bcc-a0c4-8bd85b1b9217/Document/Show?letterId=bad4af8d-efdc-4f72-80cd-0a1a49541f59&documentId=e4adb475-cf19-4935-b544-1d8234c7dc98

Вот как осуществляем отправку (возможно, нами выбран неподходящий вариант для нашего кейса):

SendTask = Organization.CreatePackageSendTask2();
DocumentToSend  = SendTask.AddDocumentFromFile("Nonformalized", "default", "v1", ПутьКФайлу);
DocumentToSend.Comment = "Договор";		
MetaDataItem = DocumentToSend.AddMetadata();
MetaDataItem.Key   = "FileName";
MetaDataItem.Value = "Договор";

Заранее спасибо за помощь!

**Comment by GilimkhanovDenis** [comment]
Добрый день.

[PackageSendTask2.AddDocumentFromFile(...)](https://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocumentFromFile) возвращает [CustomDocumentToSend](https://1c-docs.diadoc.ru/ru/latest/ComObjects/CustomDocumentToSend.html). [CustomDocumentToSend](https://1c-docs.diadoc.ru/ru/latest/ComObjects/CustomDocumentToSend.html) наследует интерфейс [DocumentToSend](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentToSend.html). Настройка есть в этом интерфейсе - NeedRecipientSignature
