### ISSUE TITLE
Ошибка в CreateReplySendTask2: "Необходимо подписать все документы в пакете"

### ISSUE THREAD

**Issue by ptizaezhik** [diadoc/diadocsdk-1c-docs#631]
Всем добрый день!

Столкнулся с ошибкой при вызове метода Send() объекта CreateReplySendTask2:
"Необходимо подписать все документы в пакете"

Судя по описанию ошибки, надо подписывать не отдельные документы в пакете, а весь пакет целиком, так?

Созданию ReplySendTask для пакета:
 ReplySendTask = ПакетДиадок.CreateReplySendTask2("AcceptDocument")

Делаю перебор коллекции ReplySendTask.ContentItems

Внутри каждого Item есть пара объектов:
 Content - у него свойство Type со значением типа строка "DocumentSignature"
 Document - ссылка на документ пакета

Если ничего не заполнять и сразу делать ReplySendTask.Send(), то, конечно, получаю ошибку:

Invalid data UserContractData:
Line: 2, Position: 38, /UniversalTransferDocumentBuyerTitle[1]/@DocumentCreator: The 'DocumentCreator' attribute is invalid - The value '' is invalid according to its datatype 'string1000' - The actual length is less than the MinLength value.
Line: 2, Position: 2, /UniversalTransferDocumentBuyerTitle[1]: The element 'UniversalTransferDocumentBuyerTitle' has incomplete content. List of possible elements expected: 'Signers'.
/UniversalTransferDocumentBuyerTitle: One of the fields must be present: @OperationContent, ContentOperCode

Но я не пойму. в каком объекте надо заполнить данные для подписи? 
Как выйти на объект, в котором можно прописать DocumentCreator и Signers ?

**Comment by GilimkhanovDenis** [comment]
Добрый день
Как минимум один из контентов ReplySendTask2.ContentItems.GetItem(...).Content  должен быть [DynamicContent](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html)'ом. Данные заполняются в нём

Если такого контента нет, среди ReplySendTask2.ContentItems , то нужна ссылка на какой-нибудь из документов пакета

**Comment by ptizaezhik** [comment]
>  ссылка на какой-нибудь из документов пакета
На конкретный документ?
Вот.
https://diadoc.kontur.ru/819b7633-95ab-4644-95a3-d2a59a38b331/Document/Show?letterId=cd39541b-3a78-4fb0-a501-2c08c1369b58&documentId=f8ee456c-9312-4741-b970-55a1e95ec93c

**Comment by GilimkhanovDenis** [comment]
В ReplySendTask2.ContentItems находится два элемента. Один из них такой:
![image](https://user-images.githubusercontent.com/34439383/119105702-07b1ea00-ba37-11eb-903d-c23d49ec5ad0.png)

**Comment by ptizaezhik** [comment]
> 
> 
> В ReplySendTask2.ContentItems находится два элемента. Один из них такой:
> ![image](https://user-images.githubusercontent.com/34439383/119105702-07b1ea00-ba37-11eb-903d-c23d49ec5ad0.png)
> 
> Его и нужно заполнить

У вас какая версия компоненты?

**Comment by GilimkhanovDenis** [comment]
5.34.0

**Comment by ptizaezhik** [comment]
Разрази меня гром! Вижу!
Не было этого полчаса назад, там было только свойство Type со значением типа строка "DocumentSignature" ! Надо было скринить.
(компонента 5.33.6.682)

**Comment by ptizaezhik** [comment]
> 
> 
> В ReplySendTask2.ContentItems находится два элемента. Один из них такой:
> ![image](https://user-images.githubusercontent.com/34439383/119105702-07b1ea00-ba37-11eb-903d-c23d49ec5ad0.png)
> 
> Его и нужно заполнить

Получислось.
Меня смутило то, что два элемента было в ContentItems - думал, что это два документа и их надо оба подписать, т.к. в личном кабинете именно два документа из пакета неподписанными светились А первый элемент, оказывается, надо было проигнорировать.

Спасибо большое!
