### ISSUE TITLE
Задваиваются документы по АПИ

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#633]
Добрый день! Со вчерашнего дня отправка УКД и УПД в некоторых случаях дает от 1 до 3 документов 
 в личном кабинете, механизм отправки давно не менялся:
                       DocumentPackage = PackageSendTask.Send();
			//отправим на подпись
			Если не Черновик тогда 					
				ResolutionRequestTask = DocumentPackage.Documents.GetItem(0).CreateResolutionRequestTask();
				ResolutionRequestTask.ResolutionRequestType = "SignatureRequest";
				ResolutionRequestTask.TargetDepartmentId = "00000000-0000-0000-0000-000000000000";
				ResolutionRequestTask.Send();
			Конецесли;

Не подскажите, что такое могло произойти? Для примера два одинаковых документа:
https://diadoc.kontur.ru/8c4381c2-96ba-4f0f-8bbe-c9563f974922/Document/Show?letterId=07bc49f2-0612-4c42-a23d-6b09d957376b&documentId=5299cd3a-29da-47fe-b4f7-746fd8a39399
https://diadoc.kontur.ru/8c4381c2-96ba-4f0f-8bbe-c9563f974922/Document/Show?letterId=734531a1-7c43-4c2f-bfb7-1170d90273c9&documentId=999759d8-0893-4b4c-87e4-b7a0bc3dfcfa

**Comment by volodkindv** [comment]
Добрый день!
Указанные вами документы отправлены с разницей в 10 секунд. Надо проверять на вашей стороне. Возможно, подключился второй пользователь или был запущен второй экземпляр фонового задания. Или где-то есть цикл, который не проверяет успешность отправки.
Чтобы избежать подобных ситуаций, можно воспользоваться свойством [OperationId](https://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html?highlight=OperationId). Если имеются 2 объекта PackageSendTask2 с одинаковым OperationId, то отправка второго задания также завершится успешно, но в ответ вернутся ссылки на документы, отправленные первым заданием. Т.е. дублирования не произойдет.
