### ISSUE TITLE
Ошибка при отправке документов

### ISSUE THREAD

**Issue by dimok22prog** [diadoc/diadocsdk-1c-docs#634]
Здравствуйте.
При отправке документов от организации e2d8838958a8452397d55059473f1be5@diadoc.ru возникает ошибка (примерно с 18.00 29.05.2021):

Ошибка при вызове метода контекста (CreateReplySendTask2): Произошла исключительная ситуация (DocumentPackage.CreateReplySendTask2): Protobuf parse error: required fields missing: (cannot determine missing fields for lite message)

Кроме того, при попытке получения информации о документе, так же возникает ошибка:

Ошибка при вызове метода контекста (GetDynamicContent): Произошла исключительная ситуация (DocumentBase.GetDynamicContent): Protobuf parse error: required fields missing: (cannot determine missing fields for lite message).

С другими организациями такой проблемы нет.
Подскажите как быть.

**Comment by dimok22prog** [comment]
Ошибка отправки возникает на:

SendTask = КонтекстОрганизации.CreatePackageSendTask2();
DocumentToSend1 = SendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01");

**Comment by GilimkhanovDenis** [comment]
Добрый день
Какую версию компоненты используете?

**Comment by dimok22prog** [comment]
5.29.7.549. Дело в том, что проблема только с указанным ящиком, по другим ящикам с этой же версией документы загружаются и отправляются.

**Comment by GilimkhanovDenis** [comment]
Для ящика e2d8838958a8452397d55059473f1be5@diadoc.ru  подключены дополнительные типы документов. Старая компонента не может разобрать часть информации об этих типах документов

Решение:
Обновить компоненту до актуальной

**Comment by dimok22prog** [comment]
А можете указать, что за дополнительные типы?

**Comment by GilimkhanovDenis** [comment]
Транспортная накладная (TypeNamedId = Waybill)

**Comment by dimok22prog** [comment]
Подскажите, а временно ее как-то можно отключить, чтобы старая версия компоненты работала (через веб-интерфейс или через обращение на техподдержку Диадок)?

**Comment by GilimkhanovDenis** [comment]
Извиняюсь, ошибся.
Проблема не с транспортной накладной, а с Торг-2

Отключить не получится

**Comment by dimok22prog** [comment]
Подскажите, каким образом к ящику e2d8838958a8452397d55059473f1be5@diadoc.ru были “подключены дополнительные типы документов“ и почему только к нему (от других организаций информация пока не поступала, документы отправляются в штатном режиме).

**Comment by volodkindv** [comment]
> Подскажите, каким образом к ящику [e2d8838958a8452397d55059473f1be5@diadoc.ru](mailto:e2d8838958a8452397d55059473f1be5@diadoc.ru) были “подключены дополнительные типы документов“ и почему только к нему (от других организаций информация пока не поступала, документы отправляются в штатном режиме). Или это автоматически и с другими организациями стоит ожидать подобной ошибки?

Эту информацию вы можете уточнить у вашего менеджера.
