### ISSUE TITLE
Прослеживаемый товар в УПД

### ISSUE THREAD

**Issue by plandoff** [diadoc/diadocsdk-1c-docs#636]
Добрый день!
ООО "ГК ЮНИКОМ"
ИНН 2543107078, КПП 254301001

Используем версию COM компоненты 5.33.4.674

В связи с изменениями в УПД с 01.07.2021, связанными с прослеживаемым товаром, возник вопрос об отправке документов с такими товарами. Не смог найти информации о поддержке этих изменений в API. Подскажите, пожалуйста, эти изменения уже поддерживаются? Какая версия компоненты нужна и какие методы использовать?

Заранее большое спасибо!

**Comment by GilimkhanovDenis** [comment]
В API  никаких изменений не будет - все необходимые поля уже есть в контенте УПД

**Comment by plandoff** [comment]
Я правильно понимаю, если товар подлежит прослеживанию, то его РНПТ надо передавать как номер ГТД в поле DeclarationNumber или какая то другая логика? Буду благодарен, если дадите пример заполнения

**Comment by plandoff** [comment]
Здравствуйте!
По моему вопросу еще нет информации?

**Comment by plandoff** [comment]
> В API никаких изменений не будет - все необходимые поля уже есть в контенте УПД

Денис, добрый день! Можно получить пример по использованию API для УПД прослеживаемого товара?

**Comment by kulakovskaya** [comment]
Добрый день! 
Приложила скриншот с примером заполнения сведений о прослеживаемости товара:
<img width="844" alt="Сведения о прослеживаемости" src="https://user-images.githubusercontent.com/54439404/122732423-b2673380-d295-11eb-8418-8adc39a4f411.png">

**Comment by plandoff** [comment]
> Добрый день!
> Скриншот с примером заполнения сведений о прослеживаемости товара:
> <img alt="Сведения о прослеживаемости" width="844" src="https://user-images.githubusercontent.com/54439404/122732423-b2673380-d295-11eb-8418-8adc39a4f411.png">

Большое спасибо за ответ! Можете подсказать еще, где в описании API найти заполнение этой информации? По ключевым словам ничего не находит

**Comment by kulakovskaya** [comment]
Добрый день!
Наименования полей и правила их заполнения можно посмотреть в UserData.xsd. Скачать UserData можно получить с помощью метода [Organization.SaveUserDataXSD](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.SaveUserDataXSD).

**Comment by plandoff** [comment]
Спасибо!
