### ISSUE TITLE
Возможная ошибка в обработке данных CorrectionBase и TransferDocDetails в новых УКД ucd736_05_01_01 в версии АПИ 5.34.2.707

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#638]
Добрый день.

При переходе с версии 5.32.4.635 на версию 5.34.2.707 было замечено два странных момента. 
Один больше похож просто на рассогласованность между реальным функционалом АПИ и описанием изменений по его обновлению в истории изменений. А вот второй больше всего похож на ошибку в данных УКД нового формата ucd736_05_01_01.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
КПП2: 783450001
ID организации: c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: COM x64 5.34.2.707.

### Первое.
В версии АПИ 5.34.2.707 для любых документов обращение к полю **.Type** документа всегда возвращает пустую строку. В версии АПИ 5.34.1.698 в этом поле еще возвращалась строка с типом документа.

В этом изменении смущают два момента:
1. В истории изменений для версии АПИ 5.34.2.707 не указано, что более не заполняется поле **.Type**.
2. В описании документа хоть и указано, что **.Type** устарел и надо пользоваться **.TypeNamedId**, но при этом не указано, что **.Type** уже не работает.

Поэтому немного непонятно - то ли это просто забыли указать в документации, то ли действительно ошиблись, и поле **.Type** пока что еще должно заполняться (и это тогда, по идее, надо поправить).

Хотелось бы увидеть от вас какое-то разъяснение по этому вопросу.

### Второе.
Очень похоже, что есть ошибка в новых УКД со схемой XSD ucd736_05_01_01.

Формируем исходящий УКД.

Заполняем в нём основания корректировки (EventContent - CorrectionBase):
![изображение](https://user-images.githubusercontent.com/33707226/123014271-34c43480-d409-11eb-9113-2eb0650c54f1.png)

и реквизиты передаточных документов (EventContent - TransferDocDetails):
![изображение](https://user-images.githubusercontent.com/33707226/123014204-0a727700-d409-11eb-8e97-b697e2912ab5.png)

Отправляем документ.

При отправке у нас такие данные (информация из отладчика 1С):

CorrectionBase:
![изображение](https://user-images.githubusercontent.com/33707226/123014591-ebc0b000-d409-11eb-86e3-5bfb1298b787.png)

TransferDocDetails:
![изображение](https://user-images.githubusercontent.com/33707226/123014633-01ce7080-d40a-11eb-9154-f0aa1478b1ae.png)

Документ нормально отправляется. 

**А далее мы получаем очень странную штуку!**

Смотрим данные отправленного исходящего документа:
CorrectionBase:
![изображение](https://user-images.githubusercontent.com/33707226/123014865-75707d80-d40a-11eb-935c-638d1b5d97f8.png)

TransferDocDetails:
![изображение](https://user-images.githubusercontent.com/33707226/123014823-65589e00-d40a-11eb-879c-bcd6db9a629d.png)

Эта же информация видна и в отладчике 1С:
![изображение](https://user-images.githubusercontent.com/33707226/123015060-e2841300-d40a-11eb-86f4-6eaf5470beb1.png)

![изображение](https://user-images.githubusercontent.com/33707226/123015098-faf42d80-d40a-11eb-8a3f-f3e6e280aea6.png)

![изображение](https://user-images.githubusercontent.com/33707226/123015952-e5800300-d40c-11eb-8257-4a5fe755e1ef.png)

Если посмотреть полученный входящий документ по этой отправке УКД (мы отправляли такие УКД сами себе, используя тестовые ящики), то во входящих документах эти данные CorrectionBase и TransferDocDetails точно такие же, собранные "в одну кучку" из этих двух таблиц!

**Получается, что при отправке и передаче УКД происходит какое-то "слияние" данных из таблиц CorrectionBase и TransferDocDetails  между собой. Причем они просто совмещают свои данные и всё - даже дубли остаются. И после этого вот такая слитая воедино информация видна как в исходящем, так и во входящем документе.**

Это ОЧЕНЬ похоже на какую-то ошибку в обработке этих данных!

Хотелось бы получить от вас разъяснение - это действительно ошибка, и вы её поправите? 
Или это специально задуманное поведение - это правильно, так и должно быть, и так и останется в дальнейшем?

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день
DocumentBase.Type исправили в 5.34.3

Получение CorrectionBase и TransferDocDetails  - в 5.34.4

**Comment by JohnSergeev** [comment]
Спасибо. Сможем протестировать у себя 2 числа или позже
