### ISSUE TITLE
Макет Серверный модуль

### ISSUE THREAD

**Issue by Dima101973** [diadoc/diadocsdk-1c-docs#639]
Как отладить серверный модуль? Поставить точки останова, он только выгрузить и загрузить.

**Comment by ButurlakinSemyon** [comment]
Добрый день!

Можете прислать техническую информацию из модуля?
Расскажите, пожалуйста, подробнее что хотите отладить?

**Comment by Dima101973** [comment]
Позвоните, пожалуйста, тел. 8 968 100-00-34
Спасибо за ответ
  
>Четверг, 24 июня 2021, 9:27 +03:00 от ButurlakinSemyon ***@***.***>:
> 
> 
>Добрый день!
>Можете прислать техническую информацию из модуля?
>Расскажите, пожалуйста, подробнее что хотите отладить?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
Дмитрий Леонидов

**Comment by ButurlakinSemyon** [comment]
К сожалению, у меня нет возможности связаться с вами по телефону. Можете описать ситуацию здесь?
