### ISSUE TITLE
Возможная проблема с расхождением итоговой информации по состоянию обработки маркировки в ЧЗ между сайтом и результатом, возвращающимся через АПИ 1С во внешних статусах документа

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#640]
Добрый день.

Недавно мы столкнулись со странной проблемой в обработке маркировки по одному из наших входящих документов. А точнее – с проблемами интерпретации информации об итоговом состоянии результата обработки маркировки по данному документу.

Общая информация для упрощения «разбора полётов»:
Организация:		«ДНС Ритейл»
ИНН: 			2540167061
КПП: 			254301001
КПП2: 			783450001
ID организации: 	c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru
ID участника ЭДО:	2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С:
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: COM x64 5.34.2.707.

### Данные документа:
УПД №9000079857 от 09.06.2021
**ID:**
f8c319fa-c0ab-4107-afad-b80c49445bf018827094-e612-4c79-aa86-fa507c512b80
**URL:**
/c4390c58-315b-4323-a9b4-b5d87d6e868b/Document/Show?letterId=f8c319fa-c0ab-4107-afad-b80c49445bf0&documentId=18827094-e612-4c79-aa86-fa507c512b80
**Контрагент:**
ООО "ФУДЖИФИЛЬМ РУС" (ИНН 7714391842, КПП 771401001)

### Суть проблемы:
Если посмотреть на состояние документа на сайте Диадок, то можно увидеть следующее:
![изображение](https://user-images.githubusercontent.com/33707226/123207943-89e37180-d501-11eb-9af2-edb85069f7c6.png)
 
Т.е. на сайте в списке документов показано, что документ **обработан** в системе ЧЗ.
 
Если посмотреть детально на сам документ, то там видно следующее:
![изображение](https://user-images.githubusercontent.com/33707226/123207856-64566800-d501-11eb-8c35-db9947e000e6.png)

Тут уже смущают два момента:
1.	Если посмотреть расположение событий по маркировке по аналогии с событиями получения и подписания документа – сверху вниз – то возникает ощущение, что **сперва** документ был обработан в системе ЧЗ, а уже **потом** вдруг перешел в состояние «Обрабатывается в ЧЗ».
2.	Дополнительно путаницу вносит то, что время этих двух событий («обрабатывается» и «обработан») указано одно и то же (по крайней мере так выглядит).

Теперь, если посмотреть на данные, которые возвращает по данному документу ваше АПИ для 1С, то получается следующее (данные из отладчика 1С при непосредственном получении документа средствами АПИ):

Текущее состояние внешнего статуса обработки маркировки по документу:
![изображение](https://user-images.githubusercontent.com/33707226/123208045-bd260080-d501-11eb-87ef-f18120797021.png)

История статусов обработки маркировки по документу (через вызов GetExternalStatuses):
![изображение](https://user-images.githubusercontent.com/33707226/123208064-c44d0e80-d501-11eb-977d-d5c4a6390e13.png)
 
Такую информацию по внешним статусам данного документа возвращает ваше АПИ для 1С как минимум следующих версий:
1.	5.32.4.635
2.	5.34.1.698
3.	5.34.2.707 (последняя на 24.06.2021)

При этом, согласно вашей документации (https://api-docs.diadoc.ru/ru/latest/proto/OuterDocflowInfo.html):
![изображение](https://user-images.githubusercontent.com/33707226/123208123-dcbd2900-d501-11eb-964a-e1781cad25f2.png)
 
Type = «Normal» отражает **промежуточное, не до конца завершенное** состояние обработки маркировки в ЧЗ. О чем, кстати, прямо указано в описании данного состояния – "Документ **обрабатывается** в ГИС МТ "Честный ЗНАК".

В результате получается, что ваше АПИ для 1С возвращает информацию о том, что по документу было два состояния обработки маркировки в ЧЗ – «Обрабатывается» и «Обработан» – как и отображается у вас на сайте (напомню еще раз):
![изображение](https://user-images.githubusercontent.com/33707226/123207122-36245880-d500-11eb-9a72-091bf25cfbc6.png)
 
Однако при этом **ТЕКУЩЕЕ** состояние обработки маркировки в ЧЗ ваше АПИ возвращает в значении «Normal» – «**Обрабатывается** в ЧЗ».

Да и в истории если смотреть по порядку списка статусов видно, что сперва был статус «обработан», а уже потом появился – статус «обрабатывается» (О такой же последовательности статусов обработки документа косвенно свидетельствует и их порядок отображения у вас на сайте, о чем я ранее уже упоминал).

Явно видно расхождение в формировании и интерпретации итогов обработки маркировки в ЧЗ по данному документу. И сайт, и АПИ для 1С в истории статусов одинаково отображают и «Обработан», и «Обрабатывается». При этом сайт считает (и показывает!), что в итоге маркировка по документу была **обработана** в ЧЗ. А АПИ для 1С считает (и показывает!), что в итоге маркировка по документу только **обрабатывается**! Возможно, подобная «путаница» как-то связана с одной и той же датой фиксации событий обработки в ЧЗ.

**С нашей точки зрения не должно быть такого, что одна и та же информация интерпретируется совершенно по-разному на сайте и в АПИ для 1С.** 

А это означает, что-то из двух вариантов:
1.	**В вашей системе ЭДО (в целом) есть какая-то ошибка или недоработка** – либо неверно итоговое состояние обработки маркировки в ЧЗ отображает ваш сайт, либо неверно итоговую информацию по текущему статусу обработки КМ формирует и возвращает ваше АПИ для 1С.
2.	Как-то по-другому нужно интерпретировать данные, возвращаемые АПИ – не обращать внимание не текущее состояние внешнего статуса ЧЗ, возвращаемого в данных LastExternalStatuses
![изображение](https://user-images.githubusercontent.com/33707226/123207155-489e9200-d500-11eb-8b7d-f7793c03791a.png)
 
А всегда смотреть в данные, возвращаемые через GetExternalStatuses():
![изображение](https://user-images.githubusercontent.com/33707226/123207171-505e3680-d500-11eb-81d4-5e78fef0061a.png)

И считать, что неважно, что возвращается в текущих данных по статусам в LastExternalStatuses, а важно, что в истории статусов, возвращаемой через GetExternalStatuses(), хотя бы раз встречалось упоминание о том, что маркировка была обработана (хоть раз встретился «Success»). 

Такой вариант кажется нам **совершенно странным (и даже нелепым)**, т.к. тогда совершенно непонятно зачем вообще нужны данные LastExternalStatuses, если они отображают **ложную** информацию и в общем-то тогда они вообще не нужны, т.к. предлагается не обращать на них внимание!

Поэтому мы пока что предварительно считаем, что речь всё-таки идет о какой-то ошибке или недоработке в вашей системе ЭДО, приводящей к различной интерпретации итогового состояния обработки маркировки в ЧЗ в разных местах системы – одним образом у вас на сайте, и другим образом – в вашем АПИ для 1С. 

### Дополнительно:
Было бы здорово (и намного понятнее при обработке данных), если бы в данные, возвращаемые через GetExternalStatuses(), была бы добавлена колонка с отметкой времени, когда было зафиксировано то или иное состояние обработки маркировки в ЧЗ. Так было бы намного понятнее какое из состояний было зафиксировано раньше, а какое позже.

Ждем ваши комментарии по данной проблеме. 

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день
Время создания статуса ГИС МТ добавим в ближайшем релизе

Проблему с порядком статусов пока ещё решаем

**Comment by GilimkhanovDenis** [comment]
Добрый день.
В релизе [5.35.0](https://1c-docs.diadoc.ru/ru/latest/History/release_info/5_35_0.html) добавили информацию о времени поступления внешнего статуса
