### ISSUE TITLE
Получение отправленных приглашений через компоненту 1с

### ISSUE THREAD

**Issue by Salinarius** [diadoc/diadocsdk-1c-docs#642]
Добрый день,
Есть ли возможность просмотра для получения отправленных мною приглашений? Нашел только просмотр текущего статуса с контрагентами Organization.GetCounteragentListByStatus

**Comment by GilimkhanovDenis** [comment]
Если необходимо найти кто присылал приглашения, то можно искать по [статусу](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Enums/CounteragentStatus.html) через [Organization.GetCounteragentListByStatus](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html?highlight=GetCounteragentListByStatus#Organization.GetCounteragentListByStatus)

Если нужно найти вложение приглашения, то нужно использовать  [DocumentsTask](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentsTask.html).

Если нужно найти текстовое сообщение приглашения, то у [контрагента](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Counteragent.html) есть поля MessageFromCounteragent и MessageToCounteragent.
