### ISSUE TITLE
Несоответствие между документацией и данными типа ReceiptError в АПИ версии 5.34.2.707

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#643]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
КПП2: 783450001
ID организации: c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С:
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: COM x64 5.34.2.707.

Совершенно случайно наткнулся на несоответствие документации по объекту ReceiptError, получаемому через вызов GetReceiptGenerationProcess(), и тем, что реально хранится в объекте:

Согласно документации:
![изображение](https://user-images.githubusercontent.com/33707226/123375028-6f75ca80-d5cb-11eb-8b9c-151d98b1087c.png)

Однако, отладчик 1С показывает следующее:
![изображение](https://user-images.githubusercontent.com/33707226/123375123-99c78800-d5cb-11eb-98f1-52ce8b417220.png)

Т.е. поле реально называется не **Error**, как указано в документации, а **ErrorText**.

Наверное, стоит или переименовать поле согласно документации или, что проще, поправить описание ReceiptError в документации. 

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Исправили имя поля  в документации
