### ISSUE TITLE
При формировании УПД в новом модуле пропало заполнение второй колонки "Код"

### ISSUE THREAD

**Issue by lanrootdiadoc** [diadoc/diadocsdk-1c-docs#644]
День добрый, подскажите при формировании УПД в новом модуле пропало заполнение второй колонки "Код" . На старом модуле работает.

В подключаемом модуле в процедура ПримерОбработкиУПД820 добавлено:

КоллекцияСтрок = Протоконтент.Table.Items;
Для Каждого Элемент Из КоллекцияСтрок Цикл
	СлужебнаяИнформация = Элемент.СлужебнаяИнформация;			
	ItemVendorCode = осаСервер.ПолучитьШтрихкод();
	ДополнитьМассивKeyValue(Элемент.StructedAdditionalInfos, "КодТов", ItemVendorCode);//ИдентификаторТовара);
        //Добавил по рекомендации "КодВидТов" - не помогло
	ДополнитьМассивKeyValue(Элемент.StructedAdditionalInfos, "КодВидТов", ItemVendorCode);//ИдентификаторТовара);  
	Элемент.ItemVendorCode = ItemVendorCode;

Помогите пожалуйста решить проблему.

![image](https://user-images.githubusercontent.com/61452897/123612359-21e7a080-d80b-11eb-981a-d3c24277b21a.png)

**Comment by happydeadman** [comment]
Добрый день!

Подскажите, пожалуйста ИНН-КПП вашей организации, либо BoxID.

**Comment by lanrootdiadoc** [comment]
7710714394-772201001
ООО "Эй энд Ди Ди Компани"

**Comment by happydeadman** [comment]
Авторизуйтесь в модуле повторно и проверьте заполнение ПФ.

**Comment by lanrootdiadoc** [comment]
Спасибо, проблема ушла

**Comment by lanrootdiadoc** [comment]
День добрый!
Можно повторить для ООО "Рево Чардж Рус", ИНН 7719451213, КПП 771401001
Та же проблема.
Спасибо.
