### ISSUE TITLE
Пустое значение в поле ДокументДиадок.type

### ISSUE THREAD

**Issue by ptizaezhik** [diadoc/diadocsdk-1c-docs#647]
По одному контрагенту из нескольких сотен наблюдаю пустое значение в поле ДокументДиадок.type

Из отладчика:
![DiadocType](https://user-images.githubusercontent.com/82872143/124095033-fad6dc00-da61-11eb-8594-8a04b47be402.jpg)

ДокументДиадок.type	- ""
ДокументДиадок.TypeNamedId	- "XmlTorg12"
ДокументДиадок.DocumentId	- "1d9f725c-1c64-4f5b-8399-44e058884f06d259e8c0-3d7c-4f28-a059-a18e9a9bfe96"
ДокументДиадок.PackageId	- "d3626661-f1d1-49cc-8900-faf2ddfa8303"

Почему может быть пустое значение в поле ДокументДиадок.type ?

Версия компоненты 5.34.2.707. Но ошибка, похоже, была и на более ранних,

**Comment by GilimkhanovDenis** [comment]
DocumentBase.Type пустое всегда в версии компоненты 5.34.2.707
Исправлено в 5.34.3.710

Рекомендуем отказаться от использования данного поля в пользу поля DocumentBase.TypeNamedId
