### ISSUE TITLE
Пусто значение Content.DocumentShimpents

### ISSUE THREAD

**Issue by evil21** [diadoc/diadocsdk-1c-docs#648]
Добрый день, при работе с подключаемым модулем Диадок 1С в формате 820, в обработчике ОбработатьСобытиеПослеЗаполненияКонтента массив DocumentShipment(реквизиты документа, подтверждающего отгрузку товаров (работ, услуг, имущественных прав) [ДокПодтвОтгр]) пустой. Подскажите пожалуйста в чем может быть проблема, обработка Диадок стандарт последней версии

**Comment by volodkindv** [comment]
Добрый день.
Обсуждение будет в https://github.com/diadoc/diadoc1cpro-docs/issues/52.
Этот тикет закрываю как дублирующий.
