### ISSUE TITLE
Не могу подписать входящий УПД

### ISSUE THREAD

**Issue by LevKrykov** [diadoc/diadocsdk-1c-docs#649]
Пытаюсь подписать входящий УПД

					ReplySendTask = DD_Doc.CreateReplySendTask2("AcceptDocument"); 
					RST_Cont = ReplySendTask.ContentItems.GetItem(0).Content.UniversalTransferDocumentBuyerTitle; 
ругается:
 RST_Cont = ReplySendTask.ContentItems.GetItem(0).Content.UniversalTransferDocumentBuyerTitle; 
{\\MAJOR7\SUPPORT\DIADOCTABL\ДИАДОК_ДЛЯ_1С_77.ERT(9714)}: ValueCollection.GetItem: Индекс выходит за диапазон коллекции

версия AddInDiadocAPI 5.34.4.713, пробовал и на более ранних - тоже самое
Прошу помощи

**Comment by GuninaY** [comment]
У меня тоже самое

**Comment by GilimkhanovDenis** [comment]
Добрый день
Нужна ссылка на документ (поле DD_Doc.PathURL) для которого воспроизводится

**Comment by GuninaY** [comment]
вот мой для примера /8c4381c2-96ba-4f0f-8bbe-c9563f974922/Document/Show?letterId=4bc1d695-e22a-49ca-b24d-35cb58498d1b&documentId=d55a7fac-be9a-44fb-bd50-bf86e5d816dc

**Comment by GilimkhanovDenis** [comment]
Не воспроизводится
Проверьте, что используется последняя версия компоненты ([DiadocAPI.GetFullVersion()](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html#DiadocAPI.GetFullVersion))

На старых компонентах такое поведение возможно.
В пользу того, что используется старая компонента говорит ещё и то, что при отсутствии в ReplySendTask2.ContentItems каких-либо элементов должна возвращаться ошибка
`"Нет документов, для которых возможно формирование ответного задания выбранного типа"`

**Comment by LevKrykov** [comment]
версия компоненты 5.34.4.713
пример документа https://diadoc.kontur.ru/4307f099-7560-4925-964e-bdf7a0c85514/Document/Show?letterId=9ac5183d-8495-41b2-b11c-025d4f8c9c39&documentId=57ad167c-b21a-4474-9bb4-c5a89f41df1a

**Comment by GilimkhanovDenis** [comment]
Аналогично - не воспроизводится
![image](https://user-images.githubusercontent.com/34439383/124241506-3bebf080-db35-11eb-9ea1-48e31d82ff2c.png)

**Comment by LevKrykov** [comment]
Что делать?

**Comment by GilimkhanovDenis** [comment]
Убедитесь что у вас подключена самая новая компонента. Пока поведение аналогично поведению старых компонент.

Насколько понимаю, используете модуль для 1С 7.7 . В папке с модулем лежит файл компоненты

1) Завершите сеанс 1С
2) разрегистрируйте компоненту (в реестре не должно остаться веток, которые связаны с компонентой. Обычно достаточно поиска по строке "Diadoc")
3) скачайте последнюю компоненту с сайта с документацией
4) замените файл компоненты в папке с модулем
5) Зарегистрируйте самую последнюю компоненту
6) при запуске интеграции убедитесь, что подключена та компонента, которую регистрировали ([DiadocAPI.GetFullVersion()](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html#DiadocAPI.GetFullVersion))
7) Воспроизведите ещё раз

**Comment by Aleksey2W** [comment]
/2c0263d0-258c-443c-a358-e8866d3c1a65/Document/Show?letterId=9baeb0ba-239f-47c0-b3ac-412cdf0fd3d9&documentId=bdea9c1a-1048-43bb-b23a-91c0779bb2b5

такая же ситуация, ЗадачаОтвета.ContentItems.Count = 0

**Comment by GilimkhanovDenis** [comment]
@Aleksey2W рекомендация та же - обновить компоненту с 5.32.4 до последней или хотя бы 5.34.2

**Comment by Romantiktak** [comment]
Такая же ошибка была. База клиент-серверная. Я Зарегал последнюю компоненту диадока на компе клиента( т.к. я её вызываю с машины пользователя).  Поменял режим запуска на толстый клиент и вуаля - заработало. причем потом можно поменять на тонкий клиент после первого успешного запуска компоненты. Похоже реально дело в кеше.
В тонком клиенте - кеш хранится на сервере, а в толстом на клиентской машине.
