### ISSUE TITLE
Вопрос по счетам фактурам

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#65]
Использую версию компоненты 5.10.4.168, 64-х разрядная на сервере приложений 1С.
Для обработки извещений СФ использую объект ReceiptGenerationProcess.
Непонятно, когда завершится данный процесс. В какой момент произойдет перевод статуса в "OutboundFinished"/"InboundFinished".
Например:
1) https://diadoc.kontur.ru/5cc59872-767d-471d-8f28-f125aabfaf8a/Document/Show?letterId=220d076d-d761-46a9-b8d7-bc677d29fd0f&documentId=ee9dd559-f80e-4a63-b4d0-48cc59e6dc1b - сменил статус относительно быстро;
2) https://diadoc.kontur.ru/5cc59872-767d-471d-8f28-f125aabfaf8a/Document/Show?letterId=562abba4-7fc3-4ebf-9817-b7b712ff94af&documentId=658153bb-2ec4-422d-8f8a-b8f90750712c - в "ожидается извещение о получении". При этом неоднократно выполняю ReceiptGenerationProcess.

Можно ли как-то влиять на данный процесс обмена извещениями?

**Comment by prog22** [comment]
До сих пор вторая СФ не изменила состояния. Повторно несколько раз выполнял  ReceiptGenerationProcess.

**Comment by denver069** [comment]
Процесс генерации извещений можно выполнять явным образом методом [Invoice.SendReceiptsAsync()](http://1c-docs.diadoc.ru/ru/latest/SendReceiptsAsync.html).
