### ISSUE TITLE
Ошибка подписи документа.

### ISSUE THREAD

**Issue by darujo** [diadoc/diadocsdk-1c-docs#651]
Добрый день. 
Подписываем документ:
```
vReplyTask = Document:CreateReplySendTask2("AcceptDocument").
vContentItems = vReplyTask:ContentItems.
do vi = 1 to vContentItems:count:
         vContentItem = vContentItems:GetItem(vi - 1 ):Content.
         vBuyerTitle = vContentItem:UniversalTransferDocumentBuyerTitle no-error.
            vEmployee = vBuyerTitle:Employee.
               vEmployee:position        = user-account.position    . /* должность работника */
               vEmployee:FirstName       = user-account.first-name  . /* фамилия */
               vEmployee:LastName        = user-account.last-name   . /* имя */
               vEmployee:MiddleName      = user-account.second-name . /* отчество */
               vEmployee:EmployeeBase     = "Должностные обязанности". /* основание полномочий представителя */ 
            end.
   
            
            vContentOperCode = vBuyerTitle:ContentOperCode. /* КодСодОпер */
            vContentOperCode:DateDiscrepDocument = string(today,"99.99.9999"). /* ДатаДокРасх */
            vContentOperCode:NumberDiscrepDocument = "NumberDiscrepDocument". /* НомДокРасх */
            vContentOperCode:TypeDiscrepDocument = "3".                       /* ВидДокРасх Принимает значение: 
            */
            vContentOperCode:NameDiscrepDocument = "NameDiscrepDocument". /* НаимДокРасх */ */
            vContentOperCode:TotalCode = 1. /* КодИтога  */
            vBuyerTitle:OperationCode   = "". /*"вид операции".*/
       
  end. 
         vBuyerTitle:DocumentCreator = vDocumentCreator . /*"составитель файла обмена счета-фактуры (информации покупателя)".*/
         vBuyerTitle:DocumentCreatorBase     = vDocumentCreatorBase. /*"основание, по которому экономический субъект является составителем файла обмена счета-фактуры".*/
         
         vBuyerTitle:OperationContent =  "Принято без разногласий". /* "содержание операции".*/
         vBuyerTitle:AcceptanceDate   = vdate. /*"Дата, чтение/запись - дата принятия товаров (результатов выполненных работ) или имущественных прав (подтверждения факта оказания услуг)" */
         
         vSigner = vBuyerTitle:Signers:additems().
         vSigner:SignerReference:CertificateThumbprint = mDiadocConnection:Certificate:Thumbprint.
         vSigner:SignerReference:boxid = iOrganizationId.
        
end.
   
end.
vReplyTask:Send().
```
при этом стала возникать ошибка
![image](https://user-images.githubusercontent.com/65738957/124247535-a77c9080-db2a-11eb-8d4e-9d7c5f717644.png)
на последней версии библиотеки ошибка меняется на другую
![image](https://user-images.githubusercontent.com/65738957/124247687-c7ac4f80-db2a-11eb-981d-b3eb967c15e0.png)
Подскажите в чем может быть проблема?

**Comment by GilimkhanovDenis** [comment]
Добрый день. 
Последняя ошибка по данному документу в логах такая:


```
Invalid data UserContractData:
Line: 2, Position: 38, /UniversalTransferDocumentBuyerTitle[1]/@DocumentCreator: The 'DocumentCreator' attribute is invalid - The value '' is invalid according to its datatype 'string1000' - The actual length is less than the MinLength value.
Line: 2, Position: 2, /UniversalTransferDocumentBuyerTitle[1]: The element 'UniversalTransferDocumentBuyerTitle' has incomplete content. List of possible elements expected: 'Signers'.
/UniversalTransferDocumentBuyerTitle: One of the fields must be present: @OperationContent, ContentOperCode, ApiClientMessage: , UserMessage: Invalid data UserContractData:
Line: 2, Position: 38, /UniversalTransferDocumentBuyerTitle[1]/@DocumentCreator: The 'DocumentCreator' attribute is invalid - The value '' is invalid according to its datatype 'string1000' - The actual length is less than the MinLength value.
Line: 2, Position: 2, /UniversalTransferDocumentBuyerTitle[1]: The element 'UniversalTransferDocumentBuyerTitle' has incomplete content. List of possible elements expected: 'Signers'.
```

Не полностью заполнен контент

**Comment by darujo** [comment]
Это я понимаю что не заполнено для новой библиотеки. Код не менялся в этой части в описаниях изменений тоже вроди ничего нет. Все работало до вчерашнего дня со старой библиотекой, а вчера перестало работать по всей стране.

**Comment by GilimkhanovDenis** [comment]
Если раньше документ подписывался без указания этого тэга, то это было ошибочное поведение. Узел DocumentCreator обязательный и его необходимо указывать

**Comment by darujo** [comment]
Это поле как и раньше заполнялось вот так
vOrganization = mDiadocConnection:GetOrganizationById(iOrganizationId) no-error.
vDocumentCreator = substitute("&1, ИНН~/КПП &2~/&3", vOrganization:name , vOrganization:inn , vOrganization:kpp).
vBuyerTitle:DocumentCreator = vDocumentCreator

**Comment by GilimkhanovDenis** [comment]
А можете залогировать HTTP трафик (расшифрованный) в момент отправки ответа (vReplyTask:Send())?
например через Fiddler или WireShark

Лог лучше через техподдержку отправить, чтобы не оставлять здесь приватную информацию (в запросах будет ваш ключ апи и контент второго титула)

**Comment by darujo** [comment]
Боюсь залогировать нам не дадут по безопасности. подскажите DiadocConnection:GetOrganizationById работает с ID организации в последней версии библиотеки?

**Comment by azhipaigor** [comment]
[GetOrganizationById](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Connection.html?highlight=GetOrganizationById#Connection.GetOrganizationById) работает только с идентификатором ящика организации (BoxId)

**Comment by GilimkhanovDenis** [comment]
Дополню, что BoxId может быть как в виде GUID (deadbeef-dead-beef-dead-beefdeadbeefdead), так и в виде "...@diadoc.ru"(deadbeefdeadbeefdeadbeefdeadbeefdead@diadoc.ru)

**Comment by GilimkhanovDenis** [comment]
После выполнения
`vBuyerTitle:DocumentCreator = vDocumentCreator`
в поле
`vBuyerTitle:DocumentCreator` действительно что-то записывается? можете это проверить, например, вызвав геттер этого поля?

**Comment by GilimkhanovDenis** [comment]
@darujo вижу документы в тестовом ящике, которые подписаны из компоненты

Насколько понимаю, Вам удалось разобраться с ошибкой. Это так?
