### ISSUE TITLE
в версии  5.34.4.713 поломался Получить список входящих документов

### ISSUE THREAD

**Issue by amore1302** [diadoc/diadocsdk-1c-docs#652]
Пишет Вам  клиент сервиса Диадок (АО Металлоторг инн  7118018781   кпп 997350001 )
Используем библилиотеку AddInDiadocAPI.dll  ( 32 разряда )
для интеграции Диадока и нашей учетной программе на 1с 7.7
на версии библиотеки AddInDiadocAPI_5_29_6_541.dll все работало 
вчера поменял библиотеку 
на версии 5.34.4.713 не работает ( переход на нов библиотеку из-за новых  УПД )

Не работает получить список входящих документов за один день по одному поставщику.

вот скрипт  на 1cv77

// это поставщик  инн = 7707310955   кпп = 773101001
Клиент_Id = "e35c34d671be4eedb95ef317be4c3b3e@diadoc.ru";

DocumentsTask = ТекущаяОрганизация.GetDocumentsTask();
DocumentsTask.FromSendDate = '28.06.2021';
DocumentsTask.ToSendDate = '28.06.2021';

DocumentsTask.Category = "Any.Inbound";
DocumentsTask.CounteragentId = Клиент_Id;

DocumentList = DocumentsTask.GetDocuments();
	
КолвоДокументов  = DocumentList.Count ;
Сообщить("КолвоДокументов = " + КолвоДокументов); 
и здесь печать колво документов = 0
на самом деле их 51

Помогите понять что не так
скорее всего надо Даты как-то по другому задавать дата м время  через строку.
Помогите - что надо поменять или пример как задать дату в виде строки

**Comment by GilimkhanovDenis** [comment]
Добрый день
FromSendDate и ToSendDate задают дату и время отправки документа. В текущем варианте они совпадают, поэтому документы, отправленные не в этот указанный момент времени не попадут в выборку

Для получения документов за день необходимо в FromSendDate поместить начало дня (вместе со временем 0:00:00), а в ToSendDate - конец дня (вместе со временем 23:59:59)

**Comment by amore1302** [comment]
как это сделать т.е как задать эти параметры Даты ( DocumentsTask.ToSendDate )  через строку в 1сv 77. 
у меня сейчас нет  1cv8 как там этот пример проверить

**Comment by amore1302** [comment]
(GilimkhanovDenis) Вы можете привести пример в котором задатется и дата и время .
текстовых представлений даты очень много.

**Comment by amore1302** [comment]
Почему точно такой же фильтр по дате документа ( когда интервал из одной даты ) правильно отрабатывает на новой библиотеке.
а когда берем интервал один день по дате выставления документа то сейчас не работает ???

**Comment by GilimkhanovDenis** [comment]
любой формат, который приводится к типу DATE.  Например, вы можете использовать что-то такое:
`КонецДня(ТекущаяДата()) `

**Comment by GilimkhanovDenis** [comment]
> Почему точно такой же фильтр по дате документа ( когда интервал из одной даты ) правильно отрабатывает на новой библиотеке.
> а когда берем интервал один день по дате выставления документа то сейчас не работает ???

Поле `ToDocumentDate` автоматически приводится к концу дня, начиная с версии 5.32.1

**Comment by amore1302** [comment]
>>>>любой формат, который приводится к типу DATE. Например, вы можете использовать что-то такое:
>>>КонецДня(ТекущаяДата())
Это Вы пишете на языке 1с V8
в 1с v7  такого нет и под рукой у меня нет восьмерки чтобы посмотреть.

**Comment by amore1302** [comment]
Прочел в документации
для DocumentsTask

ToSendDate: Дата и время, чтение/запись - конечная дата интервала отправки/получения документа
ToDocumentDate:	Дата и время, чтение/запись - дата документа, конечная дата интервала. Дата приводится к концу дня

ну согласитесь нелогично.  
Выборка что по дате документа , что по дате создания, аналогичные выборки а ведут себя по разному если ДатаОкончания только дата. ( причем раньше было другое поведение - раньше все дополнялось до окончания дня)
Хорошо хоть в документации прописано.

**Comment by amore1302** [comment]
Ну и как пожелание можно ли сделать чтобы
ToSendDate: Дата тоже если не задано явно врмя автоматически приводилось к концу дня.

Если надо то могу написать такое пожелание на линию консультаций.

**Comment by GilimkhanovDenis** [comment]
> > > > > любой формат, который приводится к типу DATE. Например, вы можете использовать что-то такое:
> > > > > КонецДня(ТекущаяДата())
> > > > > Это Вы пишете на языке 1с V8
> > > > > в 1с v7  такого нет и под рукой у меня нет восьмерки чтобы посмотреть.

В модуле 7.7 для подобной выборки:

- в поле FromSendDate указывается текущая дата
- в поле ToSendDate указывается дата следующего дня
