### ISSUE TITLE
Жутко тормозит обращение к Resolutions и HasCustomPrintForm

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#653]
Обращение к Resolutions и HasCustomPrintForm объекта типа Document занимает 70% и 20% времени соответственно относительно обращения ко всем остальным свойствам этого объекта.
Компонента последней версии - 5.34.4.713.

**Comment by GilimkhanovDenis** [comment]
Всё так.
И в том, и в другом случае при обращении к полю DocumentBase происходит вызывается метод HTTP API

Именно поэтому поле Resolutions скрыто и вместо него нужно использовать метод GetResolutions (с версии 5.34.0)

В той же версии у объекта DocumentsTask появился флаг DetectCustomPrintForm. Если его установить в истину, то в дальнейшем поле DocumentBase.HasCustomPrintForm будет вычислять не для каждого документа в отдельности, а пачками

**Comment by dorexpro** [comment]
Понятно. Спасибо.

**Comment by GilimkhanovDenis** [comment]
Замечу, что скорость обращения к полю Resolutions и получение списка резолюций через метод GetResolutions не отличается - исполняется один и тот же код. Но скрытие поля Resolutions из интерфейса объекта DocumentBase позволяет не вычислять эти данные при отладке
