### ISSUE TITLE
Перестала работать лента событий

### ISSUE THREAD

**Issue by vlad3190** [diadoc/diadocsdk-1c-docs#654]
Коллеги, добрый день!  Перестала работать лента событий. Последнее событие в ленте зарегистрированно в 14:03, дальше ничего не возвращает, хотя события точно были! Это связано с перебоями в работе сервиса? Когда будет исправлено?

**Comment by vlad3190** [comment]
ID организации - 55cb15b1-a79b-4bca-9f6f-1fde3c26f17d
ID последнего события - dc613766-d1ef-4377-8d35-4ba02c3577d8

**Comment by happydeadman** [comment]
Добрый день!

Такое поведение действительно могло наблюдаться из-за временных перебоев в работе сервиса. 
Сейчас работоспособность восстановлена. 
Уточните, актуален ли вопрос? 

Если да, то предоставьте:
- ключ разработчика
- запрос, вызывающий ошибку;
- полный текст ответа на запрос с ошибкой;
- точное время возникновения ошибки, с указанием часового пояса;

**Comment by vlad3190** [comment]
Добрый день! Сейчас, вроде, заработало...
