### ISSUE TITLE
dll 5.34.4.713  - Вызов метода валит приложение.

### ISSUE THREAD

**Issue by LevKrykov** [diadoc/diadocsdk-1c-docs#655]
dll 5.34.4.713  - Вызов метода валит приложение.
SendTask = дд_Организация.CreatePackageSendTask()
и SendTask = дд_Организация.CreatePackageSendTask2()
Прошу помощи

**Comment by GilimkhanovDenis** [comment]
Добрый день

Нужен дамп в момент падения приложения. Можно использовать, например [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) 
`procdump -e -ma -w <process_name>`

**Comment by LevKrykov** [comment]
[дампы.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/6777271/default.zip)
дампы...

**Comment by LevKrykov** [comment]
Добрый день

Дампы. 

Папки по названию методов на которых валится приложение

**Comment by JohnSergeev** [comment]
Странно - у нас на этой же версии все норм с вызовом CreatePackageSendTask2.

У вас native или com версия? У нас без проблем на com х32 и х64.

**Comment by LevKrykov** [comment]
Перезагрузил сервер – заработало

Спасибо!
