### ISSUE TITLE
Перестали подписываться в 1С с нашей стороны входящие документы

### ISSUE THREAD

**Issue by AlexDevToDeath** [diadoc/diadocsdk-1c-docs#657]
Возникла следующая проблема. 
Перестали подписываться в 1С с нашей стороны входящие документы.
Т.е. мы пытаемся подписать входящий документ (ПТУ)

Метод Document.CreateReplySendTask2("AcceptDocument") не возвращает контекст, т.е. ReplySendTask2.ContentItems.Count = 0 , при этом отправляются документы и подписываются нормально. Последние удачно подписанные входящие документы по компании - 23.06.2021

Например, не можем подписать документ с гуидом a9830ffa-75f6-40b1-b961-408d695e6b739df03df5-8bae-4d8f-b9d7-819e83b4a9c7
Что именно поменялось за этот период в диадок?

**Comment by GilimkhanovDenis** [comment]
Добрый день
Без BoxId не получится точно ответить на ваш вопрос.

Скорее всего, используется компонента ниже версии [5.34.2](https://1c-docs.diadoc.ru/ru/latest/History/release_info/5_34_2.html)

С 1 июля изменилась схема документооборота по умолчанию для документов, требующих ИоП. Компоненты старше указанной выше версии про новые схемы документооборота не распознают и потому не предлагают сформировать для них ответные титулы или подписи
