### ISSUE TITLE
Перестали подписываться документы из-за отсутсвия контента у документов

### ISSUE THREAD

**Issue by AndreevNikolay** [diadoc/diadocsdk-1c-docs#658]
Ошибка при вызове метода контекста (GetItem): Произошла исключительная ситуация (ValueCollection.GetItem): Индекс выходит за диапазон коллекции. Метод CreateReplySendTask2().  ContentItems.GetItem(0) возвращет пустую коллекцию. Например ИНН организации документ которой пытаемся подписать 7743856281. Интеграционное решение написано на основе COM компоненты. Её версия 5.34.4. Не нашел в документации к API решения своей проблемы
ДокументКПодписанию содержит класс Document.
![image](https://user-images.githubusercontent.com/87376941/125475145-3da62bd4-bbd3-4c26-a05a-44ce1d948b78.png)

**Comment by IrinaShmonina** [comment]
@AndreevNikolay , здравствуйте,
попробуйте перезапустить 1С. 
Сохраняется ли ошибка после перезапуска 1С?

**Comment by AndreevNikolay** [comment]
> @AndreevNikolay , здравствуйте,
> попробуйте перезапустить 1С.
> Сохраняется ли ошибка после перезапуска 1С?
Добрый день! Да, ошибка сохраняется и после запуска. Пользователь пробовал перезапускать 1с

**Comment by GilimkhanovDenis** [comment]
Нужен идентификатор докумнета на котором воспроизводится
и проверьте, что действительно подключилась компонента 5.34.4 ([DiadocApi.GetFullVersion](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html?highlight=GetFullVersion#diadocapi-getfullversion))

**Comment by AndreevNikolay** [comment]
Подключилась компонета версии 5.28.1.479. Не понятно, почему эта версия. Скачивал компоненту [тут](https://1c-docs.diadoc.ru/ru/latest/Downloads.html). Идентификатор документа d19056ea-9c7c-4a02-a795-94b2bbd5e618e439fd08-1687-433c-b5ab-816716df3c70

**Comment by AndreevNikolay** [comment]
По [инструкции ](https://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_update.html)снимали с регистрации старую версию и ставили новую.

**Comment by GilimkhanovDenis** [comment]
Компоненты старше 5.34.2  не умеют обрабатывать документы с новыми документооборотами, которые появились 1 июля.

Обычно 1С кэширует компоненту, которую подключила. Попробуйте сделать следующее:

- завершить сеанс 1С (если инициализация компоненты производилась на сервере, то придётся завершить сеанс сервера)
- разрегистрировать старую компоненту (в реестре не должно остаться веток с именами, соответствующим именам объектов компоненты. Обычно хватает поиска по строке "Diadoc")
- Зарегистрировать новую компоненту
- Повторить попытку подписания

Если нужна помощь в перерегистрации компоненты, то рекомендуем обратиться в техподдержку

**Comment by AndreevNikolay** [comment]
> Компоненты старше 5.34.2 не умеют обрабатывать документы с новыми документооборотами, которые появились 1 июля.
> 
> Обычно 1С кэширует компоненту, которую подключила. Попробуйте сделать следующее:
> 
> * завершить сеанс 1С (если инициализация компоненты производилась на сервере, то придётся завершить сеанс сервера)
> * разрегистрировать старую компоненту (в реестре не должно остаться веток с именами, соответствующим именам объектов компоненты. Обычно хватает поиска по строке "Diadoc")
> * Зарегистрировать новую компоненту
> * Повторить попытку подписания
> 
> Если нужна помощь в перерегистрации компоненты, то рекомендуем обратиться в техподдержку

Перерегистрировали компоненту, GetFullVersion возвращает COM x64 5.34.4.713. Ошибка по прежнему осталась. Идентификатор документа 5dd73ce-7d54-4c71-aae6-bf0bdbb5d4f011333456-7721-449c-ae04-6cfe811f0c92 на

**Comment by GilimkhanovDenis** [comment]
> Перерегистрировали компоненту, GetFullVersion возвращает COM x64 5.34.4.713. Ошибка по прежнему осталась. Идентификатор документа 5dd73ce-7d54-4c71-aae6-bf0bdbb5d4f011333456-7721-449c-ae04-6cfe811f0c92 на

это какой-то неправильный идентификатор - в начале должно быть 8 символов, а здесь 7

**Comment by GilimkhanovDenis** [comment]
Попробовал подобрать первый символ в идентификаторе - в ящике с ИНН 7743856281 не нашлось документа с таким идентификатором

**Comment by AndreevNikolay** [comment]
> это какой-то неправильный идентификатор - в начале должно быть 8 символов, а здесь 7

Прошу прощения, не скопировал 1 символ d5dd73ce-7d54-4c71-aae6-bf0bdbb5d4f06c4d7b6e-e3bf-44b3-b20d-0ebc39633756 . Это другой поставщик с аналогичной проблемой

**Comment by AndreevNikolay** [comment]
> в ящике с ИНН 7743856281

По этому постащику вот пример f285a3c7-5999-4607-b57d-d3cf1a741c7ed2152906-5ee5-4205-ba53-a4f4600ccd46

**Comment by GilimkhanovDenis** [comment]
Так это же исходящий документ, который уже отправлен. Для отправленного документа ReplySendTask2 не должен создаваться- будет ошибка
`(DocumentBase.CreateReplySendTask2): Нет документов, для которых возможно формирование ответного задания выбранного типа`


На  стороне получателя ReplySendTask2 создаётся
![image](https://user-images.githubusercontent.com/34439383/125947038-9203d682-8396-4c3d-9ee4-23c46508e19a.png)

**Comment by AndreevNikolay** [comment]
На данный момент нет других примеров, так как подписали в ЛК Диадок

**Comment by AndreevNikolay** [comment]
> Нет документов, для которых возможно формирование ответного задания выбранного типа
Ошибкb на создание ReplySendTask2() нету, у меня ContentItems.GetItem(0) возвращет пустую коллекцию

**Comment by GilimkhanovDenis** [comment]
ReplySendTask2 не может возвращать пустую коллекцию - если коллекция пустая, то будет указанная выше ошибка.

Скорее всего что-то осталось в 1С закэшировано от старой компоненты
