### ISSUE TITLE
Как в 5.34.4 у неформализованного документа проставить дату и номер документа ?

### ISSUE THREAD

**Issue by amore1302** [diadoc/diadocsdk-1c-docs#659]
В предыдущей версии создавал неформализованный документ из pdf файла так
и при этом задавал дату и номер документа в Диадоке так :

ДиадокЧтоСоздаем = "NonformilizedDocumentContent";
SendTask =   ТекущиаяОрганизация.CreateSendTaskFromFile( Путь_к_файлу, ДиадокЧтоСоздаем);

Un_Content = SendTask.Content;

Un_Content.Date    = ТекДок.ДатаДок;
Un_Content.Number    = ТекДок.НомерДок;

В версии библиотеки 5.34.4 у неформализованного документа теперь нет

Т.е пишем
    ДиадокЧтоСоздаем = "NonformilizedDocumentContent";
    Paket = ТекущиаяОрганизация.CreatePackageSendTask2();
    Путь_к_файлу = "d:\3\1.txt";
    Док_Отправляем  =  Paket.AddDocumentFromFile( ДиадокЧтоСоздаем, "default", "v1", Путь_к_файлу );

Как у документа теперь проставить дату и номер ????

**Comment by amore1302** [comment]
В версии библиотеки 5.34.4 у неформализованного документа теперь нет Content , точнее он пустой.
помогите не можем работать с целым направлением по внутренним документам.

**Comment by IrinaShmonina** [comment]
@amore1302 , здравствуйте,
Для добавления номера и даты нужно заполнить мета данные. Для этого нужно вызвать метод AddMetadata(). [Пример использования метода](https://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html)
Имя меты (поле Key) можно в GetDocumentTypes узнать

**Comment by amore1302** [comment]
можно поговорить по телефону.
так много писать и будет все равно непонятно.

  
>Четверг, 15 июля 2021, 11:31 +03:00 от IrinaShmonina ***@***.***>:
> 
> 
***@***.*** , здравствуйте,
