### ISSUE TITLE
Ввод пароля на закрытый ключ в КриптоПро

### ISSUE THREAD

**Issue by Alex463** [diadoc/diadocsdk-1c-docs#66]
Добрый день! 
Версия компоненты 5.10.4.168
Версия КриптоПро - 3.9.8227
Программа 1с - ERP 2.1
Разрядность клиента 1с - x64
Если на сертификат установлен пароль, то при попытки подключится по сертификату в систему, его запрашивает 3 раза. Ключевой носитель - смарт-карта.
пример кода:
ДиадокAPI.CreateConnectionByCertificate(ОтпечатокСертификата)
Пользователей это не совсем устраивает и запоминать пароль на ключ в криптопро не хотят. В чем может быть проблема?

**Comment by Alex463** [comment]
Можете дать какой-нибудь комментарий по этому поводу? Аналогичный повторный запрос пароля есть и в вашей обработке интеграции с 1с.

**Comment by volodkindv** [comment]
Добрый день!
Задача пока в очереди.

**Comment by denver069** [comment]
Передайте пинкод вторым параметром в [CreateConnectionByCertificate](http://1c-docs.diadoc.ru/ru/latest/CreateConnectionByCertificate.html): ДиадокAPI.CreateConnectionByCertificate(ОтпечатокСертификата, Пинкод)
