### ISSUE TITLE
УКД, не заполнить поля 10,10а,11(страна происхождения, ГТД)

### ISSUE THREAD

**Issue by Alekseevda** [diadoc/diadocsdk-1c-docs#660]
Добрый день!
Вот примерный код заполнения УКД:

DocumentToSend = SendTask.AddDocument("UniversalCorrectionDocument", "КСЧФДИС", "ucd_05_01_03"); 
DocumentToSend.AddInitialDocument(ИдРеализацияТоваров);	//Пробуем добавить в пакет	
DynamicContent = DocumentToSend.Content;
UCD820_SellerContent = DynamicContent.UniversalCorrectionDocument;

NewItem = UCD820_SellerContent.Table.Items.AddItem();

далее заполняю суммы до и после корректировки, но как заполнить поля 10,10а,11(страна происхождения, ГТД)?
Что я делаю не так?

**Comment by YudinaM** [comment]
Добрый день!
Формат УКД не предполагает заполнения страны происхождения и ГТД.

**Comment by JohnSergeev** [comment]
Дополню. 
Если речь идет о данных РНПТ (документарная прослеживаемость), то в формате ucd_05_01_03 эти данные отсутствуют. Для работы с РНПТ нужно использовать УКД форматов ucd736_05_01_01 и ucd736_05_01_02.
