### ISSUE TITLE
При формировании УПД в новом модуле пропало заполнение второй колонки "Код"

### ISSUE THREAD

**Issue by lanrootdiadoc** [diadoc/diadocsdk-1c-docs#662]
День добрый!

Прошу повторить заявку 644 для  ООО "Рево Чардж Рус", ИНН 7719451213, КПП 771401001

Та же проблема.

Спасибо.

**Comment by BlackC1over** [comment]
Добрый день!

Повторно пройдите авторизацию в модуле и проверьте, работу.

**Comment by lanrootdiadoc** [comment]
Спасибо, вроде как проставилось.

**Comment by BlackC1over** [comment]
Пожалуйста, закрою два ваших вопроса, до востребования.
