### ISSUE TITLE
Подписание документа

### ISSUE THREAD

**Issue by rvp1s** [diadoc/diadocsdk-1c-docs#663]
Добрый день
У нас самостоятельная интеграция в 1С 8.3.
До 1го июля подписывали документы корректно. После появилась версия документа utd820_05_01_02_hyphen и на моменте создания ReplySendTask = ДокументДиаДок.CreateReplySendTask2("AcceptDocument"); где ДокументДиаДок - Полный путь к ХМЛ файлу, начало выдавать ошибку: "Ошибка при вызове метода контекста (CreateReplySendTask2)". 

Установили последнюю версию Кома 5.34.4 - не помогло.
Файл пример во вложении
[ON_NSCHFDOPPR_2BM-6164102531-616401001-201510190753478238737_2BK-7703599366-1067746785204_20210712_AFCFD967-80F2-488B-8608-60297FC7788A.zip](https://github.com/diadoc/diadoccom-1c-docs/files/6841284/ON_NSCHFDOPPR_2BM-6164102531-616401001-201510190753478238737_2BK-7703599366-1067746785204_20210712_AFCFD967-80F2-488B-8608-60297FC7788A.zip)

Заранее спасибо за ответ

**Comment by GilimkhanovDenis** [comment]
Добрый день
Текст `"Ошибка при вызове метода контекста (CreateReplySendTask2)"`, возникает при попытке вычислить выражение `ДокументДиаДок.CreateReplySendTask2("AcceptDocument")` в отладчике. К сожалению, в этом тексте нет самой возникшей ошибки
Поймайте её, например, с помощью
```
Попытка
ReplySendTask = ДокументДиаДок.CreateReplySendTask2("AcceptDocument")
Исключение
Сообщить(ОписаниеОшибки());
КонецПопытки
```

**Comment by rvp1s** [comment]
Добрый день
Полной текст ошибки:
Обработка.СинхронизацияДанных_Диадок.МодульОбъекта(709)}: Ошибка при вызове метода контекста (CreateReplySendTask2): Произошла исключительная ситуация (DocumentBase.CreateReplySendTask2): Нет документов, для которых возможно формирование ответного задания выбранного типа

**Comment by rvp1s** [comment]
Я так понимаю нужно использовать другой метод для ответа?

**Comment by GilimkhanovDenis** [comment]
Документ из архива уже [подписан](https://diadoc.kontur.ru/7dd0c282-d364-41bb-9a1a-605d16ec6862/Document/Show?letterId=e4b9df84-ed29-4a52-847c-1f161259e129&documentId=bc27be8f-4e3e-480c-bcde-3531f2572d05). Создание задания на подписание для него с ошибкой закономерно.

Если воспроизводится для каких-то неподписанных документов, то нужен пример (можно ссылкой на документ, поле DocumentBase.PathUrl)

**Comment by rvp1s** [comment]
Вот документ за 19.07.21 не подписан нами - DocumentBase.PathUrl: /7dd0c282-d364-41bb-9a1a-605d16ec6862/Document/Show?letterId=2499f449-c8e4-46b2-8f06-ac22baacd7ce&documentId=43717a5f-2a7c-407a-aba9-d35484adafa0

**Comment by GilimkhanovDenis** [comment]
Не воспроизводится
![image](https://user-images.githubusercontent.com/34439383/126485475-8272d006-02b3-4f99-aaf2-89bbdb57c673.png)

Скорее всего ситуация такая же, как в https://github.com/diadoc/diadocsdk-1c-docs/issues/658, https://github.com/diadoc/diadocsdk-1c-docs/issues/649,  - 1С закэшировала старую компоненту.

Рекомендации те же:
- завершить сеанс 1С (если инициализация компоненты производилась на сервере, то придётся завершить сеанс сервера)
- разрегистрировать старую компоненту (в реестре не должно остаться веток с именами, соответствующим именам объектов компоненты. Обычно хватает поиска по строке "Diadoc")
- Зарегистрировать новую компоненту
- Повторить попытку подписания
