### ISSUE TITLE
Модификация xml в подключаемом модуле.

### ISSUE THREAD

**Issue by kropachev** [diadoc/diadocsdk-1c-docs#664]
При генерации xml выполняется проверка заполнения полей HyphenSubtotal и Subtotal, на основании чего присваивается значение ДефСтТовУчНал. Необходимо чтобы значение "0" не преобразовывалось в "-". Каким образом реализовать эти изменения в подключаемом модуле? Событий вызываемых после генерации xml найти не удалось.

Обработка Diadoc1C_UF_5_49_02.epf
Используется подключаемый модуль.
Номер обращения 32592172.

**Comment by volodkindv** [comment]
В подключаемом модуле нет такого события.

**Comment by Well3n** [comment]
Так же для ДефСтТовУчНал значение "-" является значением по умолчанию, заданное форматом приказа @[820](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=2792428) 
Т.е. по формату в этом элементе должен быть прочерк.
