### ISSUE TITLE
Ошибка в функции CreateConnectionByCertificate

### ISSUE THREAD

**Issue by t1975453** [diadoc/diadocsdk-1c-docs#665]
Функцией DiadocAPI.GetPersonalCertificates(false) (поиск сертификата в хранилище компьютера) выдал список используемых сертификатов, и использованием true список не находит.
Далее получаю отпечаток сертификата.
ОтпечатокСертификата = Certificates.GetItem(н).Thumbprint; 
отпечаток сертификата получен. В системе он есть, установлен в хранилище "Личное" и в хранилище компьютера.
Проверили отпечаток функцией 
ПроверкаСертификата = DiadocAPI.VerifyThatUserHasAccessToAnyBox(ОтпечатокСертификата). Вернул true.

Но при попытке соединения по сертификату получаем ошибку:
ДиадокСоединение = DiadocAPI.CreateConnectionByCertificate(ОтпечатокСертификата);

![image](https://user-images.githubusercontent.com/26548420/126746217-dcb0ca97-38d7-4f35-bbe2-1890c7fef426.png)

Можете сообщить, как функция считывает сертификат? Или есть альтернативное решение?

В крипто про сертификат и закрытый ключ установлен

**Comment by GilimkhanovDenis** [comment]
Добрый день

Скорее всего нет связи между открытой части ключа и закрытой частью ключа.
DiadocAPI.GetPersonalCertificates(false) вернёт все установленные сертификаты даже без закрытой части

Предлагаю обратиться в техподдержку

**Comment by t1975453** [comment]
Спасибо! Данная ветка уже не актуальна. В управляемых формах сертификат нужно устанавливать пользователю, от имени которого и запускается служба 1С
