### ISSUE TITLE
Как отловить событие подписания InvoiceCorrection?

### ISSUE THREAD

**Issue by ptizaezhik** [diadoc/diadocsdk-1c-docs#666]
Отправляем покупателю корректировочный счет-фактуру в 9:02.
На скрине из ЛК видно, что он подписан в 10:42

![КСФ confirmation](https://user-images.githubusercontent.com/82872143/126782576-e47aad82-5320-46a8-99df-16546526bd1b.jpg)

GetDocumentEventList() выдаёт 2 одинаковых события Confirmation: в 9:02 и в 10:42
При этом в поле ConfirmationDate стоит 9:02  (почему не 10:42) ?

![КСФ confirmation 2](https://user-images.githubusercontent.com/82872143/126782572-a247efa2-4a0c-4d37-bc4b-0910e49bfa80.jpg)

Как понять, что документ подписан клиентом не в 9:02, а в 10:42 ?
Как отличить эти 2 события Confirmation?

Версия компоненты: 5.34.2.707

**Comment by GilimkhanovDenis** [comment]
Добрый день

`ДокументДиадок.ConfirmationDate` - время получения подтверждения оператора. 9:02:02

`ДокументДиадок.GetResolutions().GetItem(0).CreationDate` - время появления подписи отправителя (тип резолюции SignatureApprove). 9:02:02

`Событие.Timestamp` - время появления события. В данном случае Confirmation (Извещение о получении), присланного получателем документа. Подписи под Счетом-фактурой со стороны получателя не будет - документооброт этого не предусматривает. В ДокументДиадок соответсвует полю `ДокументДиадок.RecipientReceiptMetadata.ConfirmationMetadata.DateTimeTicks`

**Comment by ptizaezhik** [comment]
Действительно, там есть эта дата. Спасибо.
