### ISSUE TITLE
Заполнение УПД

### ISSUE THREAD

**Issue by pariytv** [diadoc/diadocsdk-1c-docs#667]
Добрый день! В какой форме и какой процедуре внешней обработки Диадока происходит заполнение реквизитов УПД при выгрузка из 1С УНФ? Конкретно интересует поле "Документ об отгрузке (5а)"

**Comment by kulakovskaya** [comment]
Добрый день! Подскажите, пожалуйста, какую версию модуля Диадок используете?

**Comment by pariytv** [comment]
Версия = "5.49.14";

**Comment by Timmer555** [comment]
Этот метод отвечает за добавление документа отгрузки AddDocumentShipment(), поиск поможет определить его местоположение в обработке.

**Comment by pariytv** [comment]
Поиск не смог обнаружить данный метод

**Comment by volodkindv** [comment]
Данный репозиторий не предназначен для решения вопросов по модулю Диадок. Репозиторий относится к компоненте, а не к модулям.
Вопросы по модулям вы можете адресовать в техподдержку.
