### ISSUE TITLE
Заполнение счет-фактуры (строка 5а)

### ISSUE THREAD

**Issue by TTG1234** [diadoc/diadocsdk-1c-docs#668]
Добрый день. Подскажите, пожалуйста, какое свой-во InvoiceContent отвечает за заполнение строки 5а из печатной формы счет-фактуры? Возможно есть какой-то другой способ заполнить данные?

**Comment by hotdog75rus** [comment]
Приветствую, у меня вот так работает.

DocToSend         = SendTask.AddDocument("UniversalTransferDocument","СЧФДОП","utd820_05_01_01"); 
......
....
....
....
DynamicContent = DocToSend.Content; 
UTD            = DynamicContent.UniversalTransferDocument;
DocumentShipmentList = UTD.DocumentShipments;
DocementShipmentElement = DocumentShipmentList.AddDocumentShipment();
DocementShipmentElement.Name ="";
DocementShipmentElement.Number =НомерДок;
DocementShipmentElement.Date = ДатаДок;

**Comment by TTG1234** [comment]
hotdog75rus, спасибо. Данные о заполнении п-п можно взять из механизма 1С формирования печатной формы с-ф. Подскажите, пожалуйста, а где Вы прописываете указанный код в дополнительном подключаемом модуле Диадока? Сделала поиск, у меня только определяет в процедуре ОбработатьСобытиеНайтиДокумент1С(ДанныеСтроки) доп. модуля.

**Comment by hotdog75rus** [comment]
Здравствуйте! Где взять данные я понимаю, сложность возникает при их добавлении элементу коллекции  DocumentShipmentList как в моем примере, подозреваю, что это еще не реализовано. У меня полностью самописный модуль под 1C 7.7 поэтому место расположение тут не поможет. Нужны версии используемого модуля и библиотеки. Использование InvoiceContent не рекомендуется использовать, начиная с версии 5.27.0: Используйте DynamicContent.

**Comment by volodkindv** [comment]
Данный репозиторий не предназначен для решения вопросов по модулю Диадок. Репозиторий относится к компоненте, а не к модулям.
Вопросы по модулям вы можете адресовать в техподдержку.
