### ISSUE TITLE
401, HTTP error: Invalid API client id

### ISSUE THREAD

**Issue by DmitriyVolohov** [diadoc/diadocsdk-1c-docs#669]
Добрый день. Вчера перестала работать компонента. Подключение происходит через сертификат.
Список сертификатов получается верный, но при вызове функции CreateConnectionByCertificate() с параметром «Отпечаток сертификата» (в котором есть нужные данные) происходит исключение: 401, HTTP error: Invalid API client id

**Comment by AndreyPermikin** [comment]
Ошибка сообщает о том что указан некорректный ключ разработчика. Проверьте что указан верный ключ разработчика и в нем не содержится лишних символов или пробелов.
