### ISSUE TITLE
XML УПД. Отличается печатная форма pdf от отображения на сайте.

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#67]
XML УПД. Отличается печатная форма pdf скачанная по кнопке (скачать документооборот целиком) от отображения на сайте.
См. пример на картинках.
Сайт
![img-2017-01-23-13-10-41](https://cloud.githubusercontent.com/assets/20082460/22199902/f54b044c-e16d-11e6-8a6d-0983aba5f2f1.png)
Печатная форма pdf
![img-2017-01-23-13-11-29](https://cloud.githubusercontent.com/assets/20082460/22199916/00f14d92-e16e-11e6-88cd-b2e58ab441c8.png)
Необходимо убрать из печатной формы pdf поля Контактные данные, которых нет в формате. В  колонке "Условное обозначение" 2а предсталение изменить как на сайте.

**Comment by denver069** [comment]
Обратитесь в [техподдержку](http://www.diadoc.ru/support)
