### ISSUE TITLE
В каком свойстве дата получения (приемки)?

### ISSUE THREAD

**Issue by svsevolod** [diadoc/diadocsdk-1c-docs#670]
Добрый день!
Мне нужно найти свойство в котором содержится дата приемки товара.
 
Эта дата указывается в  поле УПД Дата получения (приемки).
Я предполагаю, что эта дата хранится в свойстве ConfirmationMetadata, в DateTimeTicks, верно?

**Comment by happydeadman** [comment]
Добрый день!

Данная информация хранится в титуле покупателя "AcceptanceDate".
Получить можно через [DynamicContent](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html)
