### ISSUE TITLE
Ошибка при создании УПД с КИЗ

### ISSUE THREAD

**Issue by Aleksey2W** [diadoc/diadocsdk-1c-docs#671]
`ПакетДиадок = Диадок_КонтекстОрганизации.CreatePackageSendTask2();`
`***`
`ПакетДиадок.AddDocumentFromFile("UniversalTransferDocument", "ДОП", "utd820_05_01_01_hyphen", ПутьКФайлуXML)`
`***`
`МассивЗадач.Добавить(Новый Структура("Документ,Задача", СсылкаНаДокумент, ПакетДиадок.SendAsync()));`

Ошибка:

Произошла исключительная ситуация (AsyncResult.Result): ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: { Location = /Файл/@ИдФайл, Message = Значение атрибута @ИдФайл имеет неверный формат: ON_NSCHFDOPPR_2BM-7715631511-2013010901274169611920000000000_2BM-5008042442-770601001-201411210919150217360_20210724_74c05be2-f37f-11eb-b806-00505683be8d (@ИдОтпр=2BM-5008042442-770601001-201411210919150217360, @ИдПол=2BM-7715631511-2013010901274169611920000000000), для маркированных товаров НомСредИдентТов=
						010461003244594421iGsPvOf9Egd3I }

ИД_Формируется по правилу:

R_T_A_O_GGGGMMDD_N, где:

R_T - префикс, принимающий значение ON_NSCHFDOPPR в общем случае
A - идентификатор получателя файла обмена
O - идентификатор отправителя файла обмена
GGGG - год формирования передаваемого файла обмена,
MM - месяц,
DD - день;
N - 36-символьный глобально уникальный идентификатор GUID

**Comment by Aleksey2W** [comment]
если этот же файл загрузить через веб-версию - проблем не возникает.
Приложил на всякий файл в архиве (просто xml не поддерживает).

[ON_NSCHFDOPPR_2BM-7715631511-2013010901274169611920000000000_2BM-5008042442-770601001-201411210919150217360_20210724_74c05be2-f37f-11eb-b806-00505683be8d.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/6923784/ON_NSCHFDOPPR_2BM-7715631511-2013010901274169611920000000000_2BM-5008042442-770601001-201411210919150217360_20210724_74c05be2-f37f-11eb-b806-00505683be8d.zip)

**Comment by YudinaM** [comment]
Добрый день!
Если в документе передаются КИЗ, то префикс должен быть не ON_NSCHFDOPPR, а ON_NSCHFDOPPRMARK.

**Comment by Aleksey2W** [comment]
помогло, спасибо
