### ISSUE TITLE
Как получить комментарий в неформализованном документе?

### ISSUE THREAD

**Issue by komissarovev** [diadoc/diadocsdk-1c-docs#672]
Добрый день?
Если я сайта скачиваю документооборот целиком, то получаю файл с комментарием
![QIP Shot - Screen 408](https://user-images.githubusercontent.com/36499475/128013791-0a3e7740-275e-44ea-8242-5fa10e9e25b7.png)
а если использую метод SaveAllContent, то не получаю его
![QIP Shot - Screen 407](https://user-images.githubusercontent.com/36499475/128014099-973b5928-0ed3-44a6-be07-053d73582b63.png)

Можете подсказать комментарий в неформализованном документе хранится только в файле? И почему я не получаю этот файл методом  SaveAllContent?

**Comment by kab1k** [comment]
Добрый день.

SaveAllContent не скачивает файл с комментарием, вам необходимо воспользоваться методом SaveAllContentZip.
