### ISSUE TITLE
Ошибка при отправке УПД с прослеживаемым товаром

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#673]
Здравствуйте.

Для взаимодействия 1С 7.7 с Диадок использую вашу внешнюю компоненту.

При отправке УПД, в табличной части информацию о стране происхождения и ГТД заполняю следующим образом:

Content=Document.Content.UniversalTransferDocumentWithHyphens;
Item=Content.Table.AddItem();
CustomsDeclaration=Item.CustomsDeclarations.AddCustomsDeclaration();
CustomsDeclaration.Country=КодСтраны;
CustomsDeclaration.DeclarationNumber=НомерГТД;

Всё корректно отправляется.

Если в табличной части есть прослеживаемый товар, то насколько я понимаю, заполняется только код страны, а дальше заполняется информация о прослеживаемости:

Content=Document.Content.UniversalTransferDocumentWithHyphens;
Item=Content.Table.AddItem();
CustomsDeclaration=Item.CustomsDeclarations.AddCustomsDeclaration();
CustomsDeclaration.Country=КодСтраны;
TracingInfo=Item.ItemTracingInfos.AddItemTracingInfo();
TracingInfo.RegNumberUnit=НомерРНПТ;
TracingInfo.Unit=КодЕдиницыИзмерения;
TracingInfo.Quantity=Количество;

Но при таком варианте при отправке возникает ошибка:

error: Invalid generated title:
Metadata errors: 
Validation errors: Location: Line: 282, Position: 31, /Файл[1]/Документ[1]/ТаблСчФакт[1]/СведТов[27]/СвТД[1]/@НомерТД, Message: The НомерТД attribute is invalid

Пробовал подставлять пустую строку:

CustomsDeclaration.DeclarationNumber="";

Всё равно выдает ошибку, что неправильно делаю?

**Comment by DarkTrin** [comment]
Эти *****, по другому их не назовешь, не могут нормально обслуживать клиентов. эту жу информацию я из техподдержки выбивал неделю.
Если идут РНПТ номера, то надо в ГТД добавить вот так:
CustomsDeclaration.DeclarationNumber="Прослеж";

**Comment by DarkTrin** [comment]
Отвратительный сервис у них!
Самое главное, с управляемых формах  у них не работает ПМ, все надо допиливать внутри... 
А самое главное, они говорят, что ответственности за допиляный диадок они не берут, а в моем ПМ ошибки(притом, что я внутри диадока прописую подключение и все отлично). Вообще удоты еще те там сидят!

**Comment by IrinaShmonina** [comment]
@evgen421 , здравствуйте.
[По 820 формату](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=2834527) в номерТД в отношении товаров, подлежащих прослеживаемости, указывается "Прослеж", поэтому в CustomsDeclaration.DeclarationNumber="Прослеж";

**Comment by evgen421** [comment]
**DarkTrin** большое спасибо за подсказку.
**IrinaShmonina** вам конечно тоже спасибо, но ждать неделю простого ответа на простой вопрос это многовато.
