### ISSUE TITLE
Ошибка при создании массива

### ISSUE THREAD

**Issue by ejig** [diadoc/diadocsdk-1c-docs#674]
Добрый день

// Добавление неформализованного документа
    Third_DocumentToSend = SendTask.AddDocumentFromFile("Nonformalized", "default", "v1", "С:\\Документ.pdf");
    Third_DocumentToSend.Comment = "Это неформализованный документ";
    MetaDataItem = Third_DocumentToSend.AddMetadata();

До текущего момента работали на dll версии 5.29.8.554, проблем не было
перешли на  5.34.4 появилась ошибка

 Access violation at address 00000000. Write of address 00000000

Подскажите были изменения?

**Comment by ejig** [comment]
> 
> 
> Добрый день
> 
> // Добавление неформализованного документа
> Third_DocumentToSend = SendTask.AddDocumentFromFile("Nonformalized", "default", "v1", "С:\Документ.pdf");
> Third_DocumentToSend.Comment = "Это неформализованный документ";
> MetaDataItem = Third_DocumentToSend.AddMetadata();
> 
> До текущего момента работали на dll версии 5.29.8.554, проблем не было
> перешли на 5.34.4 появилась ошибка
> 
> Access violation at address 00000000. Write of address 00000000
> 
> Подскажите были изменения?

**Comment by happydeadman** [comment]
Добрый день!

Можете, пожалуйста, подсказать размер файла, который пытаетесь передать?

**Comment by ejig** [comment]
Файл 300  КБ 
Ошибка на строке:
MetaDataItem = Third_DocumentToSend.AddMetadata();
