### ISSUE TITLE
Необходимо в электронном УПД заполнять колонку Код товара, работ,услуг.

### ISSUE THREAD

**Issue by pogarskiy** [diadoc/diadocsdk-1c-docs#675]
Необходимо в электронном  УПД заполнять колонку Код товара, работ,услуг. 

В подключаемом модуле я заполняю: 
УстановитьЗначениеXDTO(Контент, "ItemVendorCode", Формат(СтрокаТабличнойЧасти.ТоварКод, "ЧГ=0")); Но в печатную форму на экран выводится "-".

В обработке Диадок Про в макете "Печатные формы_epf" в модуле объекта в процедуре ПФ_УПД_820_СтрокиТаблицы(Таб, Параметры) есть код:
Область.Параметры.Код = ПредставлениеКодТов_736_820(Item, Параметры.ВыводитьНаименованиеТовараСКодами);				

Функция ПредставлениеКодТов_736_820(Item, ВыводитьНаименованиеТовараСКодами)
	
	Результат = "";
	
	Если ВыводитьНаименованиеТовараСКодами Тогда
		Результат = СтрокаИлиДефис(Item.ItemVendorCode);
	Иначе
		
		Если ЗначениеЗаполнено(Item.Product) ИЛИ ЗначениеЗаполнено(Item.ItemCharact)
			ИЛИ ЗначениеЗаполнено(Item.ItemArticle) Тогда
			
			Результат = СтрокаДефис();
			
		КонецЕсли;
		
		Если Результат = "" Тогда 
			Результат = СтрокаИлиДефис(Item.ItemVendorCode);
		КонецЕсли;
	
	КонецЕсли;
	
	Возврат Результат;
	
КонецФункции

ВОПРОС: Где устанавливается параметр "ВыводитьНаименованиеТовараСКодами"?

**Comment by kab1k** [comment]
Добрый день.
Если в XML  документа заполнен тег "КодТов" но в модуле он не визуализируется, то вам необходимо обратиться в техническую поддержку для включения визуализации тега "КодТов" в документах.
Обратиться в техническую поддержку можно любым удобным способом по ссылке https://www.diadoc.ru/support .
