### ISSUE TITLE
Дата отгрузки в 11 строке УПД

### ISSUE THREAD

**Issue by EVVeselova** [diadoc/diadocsdk-1c-docs#676]
Добрый день.

Подскажите, какой датой заполняется 11 строка УПД? Эта дата отгрузки. Она не должна совпадать с датой документа.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Уточните, пожалуйста, ваш вопрос.
Какую дату укажете при заполнении в соответствующем поле [контента](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html) , такая и будет в передана
