### ISSUE TITLE
Дата получения 16 строка УПД

### ISSUE THREAD

**Issue by MaGeron66** [diadoc/diadocsdk-1c-docs#677]
Добрый день.
Реализуем доп. обработку через подключаемый модуль в Диадок стандарт, дату учета можем забрать, а эту дату не получается, подскажите пожалуйста, куда смотреть, куда копать, каким образом можно эту дату забрать\получить?

**Comment by kulakovskaya** [comment]
Здравствуйте!
1. Подскажите, пожалуйста, версию модуля Диадок или приложите всю техническую информацию.
2. Для понимания проблемы и принятия решений опишите Ваш сценарий более подробно.

**Comment by MaGeron66** [comment]
Добрый день!

1. Версия модуля: 5.49.13.958
Модуль типовой: Неизвестно
Версия компоненты: 5.35.3.731
Модуль интеграции: Модуль_ИнтеграцияУТ11
UserId: 60ceeee9-6d10-4ea3-8e25-8a9566fc157c
Сертификат: 3416a6d4d1044138ac09a88d5a043d17e6b87570
Режим совместимости форматов: Нет
Подключаемый модуль: В конфигурации
Путь к подключаемому модулю: Обработка: ДиадокПодключаемыйМодульСтандарт
Отладка вложенных обработок: Нет
Использовать форму ввода накладной: Нет
Использовать метрики: Да
Использовать сервис "Контур.Маркировка": Нет

Версия ОС: Microsoft Windows 8.1 version 6.3  (Build 9600)
Тип платформы: Windows x86-64
Версия платформы: 8.3.18.1483
Вид клиента: Тонкий клиент
Строка соединения: Srvr="srv1c";Ref="ut_tdka";
Конфигурация: 1С:Комплексная автоматизация 2 (2.4.13.243)

2.  В подключаемом модуле Диадок, при обработке события "ПриОбновленииСпискаДокументов", хотелось бы чтобы была возможность получать "RecipientSignature = Document.GetRecipientSignature();", такой метод есть на стороне "Клиента" в основной обработке или получать полностью данные электронного документа по идентификатору "Document = ЭлектронныйДокументПоИдентификатору(ТекущиеДанные.BoxID, ТекущиеДанные.DocumentID);"

**Comment by kulakovskaya** [comment]
Подскажите, пожалуйста, какой сценарий в Вашей работе закрыла бы данная возможность? Для чего необходимо получать RecipientSignature или полные данные по документу?

**Comment by MaGeron66** [comment]
Нам необходимо отслеживать, когда контрагент подписал документ (в первую очередь для аналитики и расчета более корректной дебеторки), и было бы удобно эту информацию получать массово, а то сейчас ее возможно получить только провалившись в печатную форму документа в диадоке.

**Comment by ButurlakinSemyon** [comment]
@MaGeron66, добрый день.

К сожалению, в стандартном модуле УФ реализовать такой кейс без кастомизации корневого модуля не получится. Такой подход приведет к серьезной деградации производительности. 

Мы можем порекомендовать вам переход на модуль ПРО, т.к. там используется лента событий (т.е. чтобы узнать о подписании документа не нужно вычитывать данные по всем документам). В модуле ПРО можно переопределить чтение ленты событий и даже реализовать чтение ленты через регламентное задание.
