### ISSUE TITLE
Ошибка при отправке УКД по 736 приказу со ставками Без НДС и НДС 0%

### ISSUE THREAD

**Issue by DmitryBir** [diadoc/diadocsdk-1c-docs#679]
Добрый день.
Пытаюсь отправить УКД (**статус 2: ДИС**) по 736 приказу через АПИ (в отправляемом документе есть строки  как со ставкой НДС 10% и 20%, так и строки со ставкой НДС 0% и Без НДС):

DocumentToSend = PackageSendTask2.AddDocument("UniversalCorrectionDocument", "ДИС", "ucd736_05_01_01");

Когда ставка НДС 20% или НДС10% - отправка происходит без ошибок

Если заполняю ком-объект  для строк со ставкой НДС 0% или Без НДС  (тэги не заполнены) :
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/BIRYUK~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/BIRYUK~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/BIRYUK~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=RU style='tab-interval:35.4pt'>

Свойство | Значение | Тип
-- | -- | --
Item | COMОбъект | COMОбъект
AdditionalInfos | COMОбъект | COMОбъект
CorrectedItemIdentificationNumbers | COMОбъект | COMОбъект
Excise | COMОбъект | COMОбъект
ItemArticle | "" | Строка
ItemCharact | "" | Строка
ItemKind | "" | Строка
ItemTracingInfos | COMОбъект | COMОбъект
ItemTypeCode | "" | Строка
ItemVendorCode | "" | Строка
OriginalItemIdentificationNumbers | COMОбъект | COMОбъект
OriginalNumber | "" | Строка
Price | COMОбъект | COMОбъект
CorrectedValue | "" | Строка
OriginalValue | "626.00" | Строка
Product | "Возврат услуги" | Строка
Quantity | COMОбъект | COMОбъект
Subtotal | COMОбъект | COMОбъект
AmountsDec | "626.00" | Строка
AmountsInc | "" | Строка
CorrectedValue | "0.00" | Строка
OriginalValue | "626.00" | Строка
SubtotalWithVatExcluded | COMОбъект | COMОбъект
AmountsDec | "626.00" | Строка
AmountsInc | "" | Строка
CorrectedValue | "0.00" | Строка
OriginalValue | "626.00" | Строка
TaxRate | COMОбъект | COMОбъект
CorrectedValue | "без НДС" | Строка
OriginalValue | "без НДС" | Строка
Unit | COMОбъект | COMОбъект
UnitName | COMОбъект | COMОбъект
Vat | COMОбъект | COMОбъект
AmountsDec | "" | Строка
AmountsInc | "" | Строка
CorrectedValue | "" | Строка
OriginalValue | "" | Строка
WithoutVat | COMОбъект | COMОбъект
CorrectedValue | "без НДС" | Строка
OriginalValue | "без НДС" | Строка

</body>

</html>

тогда возникает вот такая ошибка:

Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalCorrectionDocument/Table/Items/Item[1]/Vat/AmountsInc: Vat/AmountsInc or Vat/AmountsDec is required, when TaxRate/@OriginalValue != 'НДС исчисляется налоговым агентом'

Когда заполняю ком-объект для строк со ставкой НДС 0% или Без НДС  (тэги заполняю 0)

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/BIRYUK~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/BIRYUK~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/BIRYUK~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=RU style='tab-interval:35.4pt'>

Свойство | Значение | Тип
-- | -- | --
Item | COMОбъект | COMОбъект
AdditionalInfos | COMОбъект | COMОбъект
CorrectedItemIdentificationNumbers | COMОбъект | COMОбъект
Excise | COMОбъект | COMОбъект
ItemArticle | "" | Строка
ItemCharact | "" | Строка
ItemKind | "" | Строка
ItemTracingInfos | COMОбъект | COMОбъект
ItemTypeCode | "" | Строка
ItemVendorCode | "" | Строка
OriginalItemIdentificationNumbers | COMОбъект | COMОбъект
OriginalNumber | "" | Строка
Price | COMОбъект | COMОбъект
CorrectedValue | "" | Строка
OriginalValue | "626.00" | Строка
Product | "Возврат услуги" | Строка
Quantity | COMОбъект | COMОбъект
Subtotal | COMОбъект | COMОбъект
AmountsDec | "626.00" | Строка
AmountsInc | "" | Строка
CorrectedValue | "0.00" | Строка
OriginalValue | "626.00" | Строка
SubtotalWithVatExcluded | COMОбъект | COMОбъект
AmountsDec | "626.00" | Строка
AmountsInc | "" | Строка
CorrectedValue | "0.00" | Строка
OriginalValue | "626.00" | Строка
TaxRate | COMОбъект | COMОбъект
CorrectedValue | "без НДС" | Строка
OriginalValue | "без НДС" | Строка
Unit | COMОбъект | COMОбъект
UnitName | COMОбъект | COMОбъект
Vat | COMОбъект | COMОбъект
AmountsDec | "0.00" | Строка
AmountsInc | "0.00" | Строка
CorrectedValue | "0.00" | Строка
OriginalValue | "0.00" | Строка
WithoutVat | COMОбъект | COMОбъект
CorrectedValue | "без НДС" | Строка
OriginalValue | "без НДС" | Строка

</body>

</html>

тогда возникает вот такая ошибка:

Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalCorrectionDocument/Table/Items/Item[1]/Vat/AmountsInc: AmountsInc must be > 0
/UniversalCorrectionDocument/Table/Items/Item[1]/Vat/AmountsDec: AmountsDec must be > 0

Что не так?
Спасибо

**Comment by ichechulina** [comment]
Добрый день, по требованиям нового формата, в документе должны оставаться только строки с корректировками. Поэтому необходимо убрать позиции без изменения суммы и налога. В вашем случае со ставкой НДС 0% или Без НДС сумма налога не изменилась, соответственно нельзя отправить документ с такими позициями. Подробнее: https://www.diadoc.ru/blog/7957

**Comment by DmitryBir** [comment]
Добрый день.
Тогда подскажите пожалуйста, каким образом мне выставить УКД со статусом 2 по позициям, по которым не меняется сумма налога (т.к. его нет), а меняется только сумма позиции, т.е. пример:
Было -  Сумма =100 руб ставка "без НДС"
Стало Сумма= 5 руб       ставка  "без НДС"

**Comment by ichechulina** [comment]
В случае, если не изменились сумма и НДС, можно сформировать не корректировку, а исправление

**Comment by DmitryBir** [comment]
Согласно договору  с клиентом - должна быть  корректировка

**Comment by GilimkhanovDenis** [comment]
Ответ будет дан в рамках обращения в техподдержку 33150271
