### ISSUE TITLE
Данные сертификата для отклонения документов

### ISSUE THREAD

**Issue by Lacertus** [diadoc/diadocsdk-1c-docs#680]
Не могу разобраться, как происходит подпись отклоняемых документов.
В API можно было использовать свойство Signature структуры данных SignedContent, отправляя документы на подпись или отказывая в подписи. В дальнейшем эта информация верно отражалась в файле Протокол в разделе "Получатель отказал в подписи документа"

Пытаюсь выполнить те же действия через компоненту, через ReplySendTask2. Соединение выполняется по отпечатку того же сертификата, которым подписывал в API. Через DiadocAPI.GetPersonalCertificates() я успешно получаю данные сертификата с верными значениями подписанта, сроков действия и т.д. Но при подписи документа через ReplySendTask2 в результате в протоколе отображаются данные другой подписи. Как определяется подпись, через которую принимаются\отклоняются документы при работе с ReplySendTask2 (в частности неформализованные)?

**Comment by GilimkhanovDenis** [comment]
Используется тот сертификат, по которому произошла авторизация.

Если документ тестовый, то подписание производится тестовым сертификатом, находящимся на сервере Диадок, а не тот, по которому авторизовались
