### ISSUE TITLE
Ошибка при подписании документа.

### ISSUE THREAD

**Issue by ElenaBurnasheva** [diadoc/diadocsdk-1c-docs#681]
Здравствуйте! 
Интеграционное решение написано на основе COM компоненты.
С июля перестали подписываться УПД между 2 организациями. Организация1 пописывает документ и отправляет Организации2.  Организация2 не может подписать документ. Возникает ошибка: Ошибка при вызове метода контекста `(GetItem): Произошла исключительная ситуация (ValueCollection.GetItem): Индекс выходит за диапазон коллекции`. 
Выполняется следующий код:
```
SendTask = Document.CreateReplySendTask2("AcceptDocument");
NewSigner = SendTask.ContentItems.getitem(0).Content.UniversalTransferDocumentBuyerTitle.Signers.AddItems()
```
Идентификатор документа ef90d04e-4535-46fe-adec-b92b182193648fb23368-0724-4367-979b-ad48045b3744.
А документ 6a730837-05f1-4d2b-8c94-cd91c3289004e9e10753-47f7-4996-8c94-4464719e0f5a, который выставлен другой организации подписан. Код выполняется тот же.

**Comment by GilimkhanovDenis** [comment]
Добрый день.
Скорее всего история та же, что в https://github.com/diadoc/diadocsdk-1c-docs/issues/658 - нужно обновить компоненту до актуального релиза

**Comment by ElenaBurnasheva** [comment]
После обновления компоненты ошибка ушла.
