### ISSUE TITLE
Ошибка при открытии формы ОбработкаПросмотраУПД.ert

### ISSUE THREAD

**Issue by galiurust** [diadoc/diadocsdk-1c-docs#682]
[
![ОшибкаПриОткрытииФормы](https://user-images.githubusercontent.com/90258078/132343555-8ba7f98f-9810-42a6-b202-557bc3184269.jpg)
](url)
Пытаюсь адаптировать обработки ДиаДок версии 2_16_24 под нетиповую конфигурацию 1С на платформе 7.7
При открытии формы ОбработкаПросмотраУПД.ert выдает сообщение:
функция УПД не передана
SendDoc=SendTask.AddDocument("UniversalTransferDocument"); 
{I:\1C BASE\RUSTAM\ПЕТРОСЕРВИС2\EXTFORMS\DIADOC_77_V_2_16_24\ОБРАБОТКАПРОСМОТРАУПД.ERT(9365)}: Неверное число параметров
Как найти ошибку?

**Comment by GilimkhanovDenis** [comment]
Скорее всего SendTask - это PackageSendTask2
Можете проверить это или найдя метод, с помощью которого был создан SendTask или использую [Reflector](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Reflector.html)

Если так, то  у AddDocument три параметра.
[документация](https://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html#packagesendttask2-adddocument)

**Comment by galiurust** [comment]
Я чистый 1С-ник. То что Вы написали мне не совсем понятно. Напишите пж-ста
текст модуля, который я смогу вставить в обработку

**Comment by GilimkhanovDenis** [comment]
Пример вызова метода есть в [документации](https://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html):
`First_DocumentToSend = SendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01");`
