### ISSUE TITLE
Получить список контрагентов в подключаемом модуле diadoc

### ISSUE THREAD

**Issue by AleksandrSergeevich77** [diadoc/diadocsdk-1c-docs#683]
Здравствуйте.
Подскажите, как получить список всех контрагентов, с которыми у меня установлены партнерские отношения в подключаемом модуле diadoc standart (версия 5.49.13.958) ?

**Comment by Well3n** [comment]
Добрый день! 
Вам может помочь в этом метод https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetCounteragentListByStatusAsync
