### ISSUE TITLE
Действия с приглашениями к партнерству.

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#685]
Здравствуйте. Существует ли возможность отозвать отправленное контрагенту приглашение к партнерству и отклонить входящее приглашение от контрагента. В документации нашел только Counteragent.BreakWithCounteragent() отказ от партнерства, видимо уже установленного.

**Comment by azhipaigor** [comment]
Для отзыва отправленного приглашения и отклонения входящего так же используется метод [Counteragent.BreakWithCounteragent()](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Counteragent.html?highlight=BreakWithCounteragent#counteragent-breakwithcounteragent)

**Comment by evgen421** [comment]
Я так и предполагал, спасибо.
