### ISSUE TITLE
Ошибка начение атрибута @ИдФайл имеет неверный формат при АПИ и допсведения при загрузке через интерфейс Диадок

### ISSUE THREAD

**Issue by AlexDevToDeath** [diadoc/diadocsdk-1c-docs#686]
[ON_NSCHFDOPPR_5047085094_504701001_7701368645_772801001_20210917_3f01c61d-593a-47bf-bbe4-3aa8d06910b0.xml.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/7195805/ON_NSCHFDOPPR_5047085094_504701001_7701368645_772801001_20210917_3f01c61d-593a-47bf-bbe4-3aa8d06910b0.xml.zip)

Выгружаем Файл (во вложении) из 1С Бухгалерия как через АПИ, так и штатными средствами 1С. 
1С Бухгалтерия типовая, версия Бухгалтерия предприятия, редакция 3.0 (3.0.96.35) 
Если файл выгружаем через АПИ 
SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01",ПутькФайлуXML)

Получаем ошибку:

[Uploading ON_NSCHFDOPPR_5047085094_504701001_7701368645_772801001_20210917_3f01c61d-593a-47bf-bbe4-3aa8d06910b0.txt…]()

Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: { Location = /Файл/@ИдФайл, Message = Значение атрибута @ИдФайл имеет неверный формат: ON_NSCHFDOPPR_5031081930_503101001_7701368645_772801001_20210917_ae83c34b-94a0-43e7-aedb-4b70de6321c9 (@ИдОтпр=7701368645_772801001, @ИдПол=5031081930_503101001)
				При отстутствии /Файл/Документ/ТаблСчФакт/СведТов/ДопСведТов/НомСредИдентТов и /Файл/Документ/ТаблСчФакт/СведТов/ДопСведТов/СведПрослеж значение @ИдФайл[ON_NSCHFDOPPR_5047085094_504701001_7701368645_772801001_20210917_3f01c61d-593a-47bf-bbe4-3aa8d06910b0.xml.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/7195804/ON_NSCHFDOPPR_5047085094_504701001_7701368645_772801001_20210917_3f01c61d-593a-47bf-bbe4-3aa8d06910b0.xml.zip)должно начинаться с ON_NSCHFDOPPR_, ON_NSCHFDOPPRMARK_ или ON_NSCHFDOPPRPROS };{ Location = /Файл/СвУчДокОбор/СвОЭДОтпр, Message = Поле СвОЭДОтпр должно присутствовать }

Если же этот же файл пытаемся отправить через интерфейс диадок, то получаем следубщие ошибки (хотя все поля и парсятся):

![image](https://user-images.githubusercontent.com/87308729/134003639-349026a9-aafd-43ff-a9a8-9961d1541ab8.png)
![image](https://user-images.githubusercontent.com/87308729/134003695-87f39e17-4b1e-41f7-90d5-85af2646b6be.png)
![image](https://user-images.githubusercontent.com/87308729/134003744-aa89eabb-5097-4d37-b72c-1eea992b398b.png)

Отсюда вопрос: Что именно не так в файле, почему все сведения через интрефес диадок парсятся но все допсведения помечены красненьким крестом? 
Какая минимальная версия 1С БУхгалтерия совместима с текущим АПИ Диадок?

**Comment by GilimkhanovDenis** [comment]
Добрый день

В файле неправильный контент:
Согласно [формату](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=2882282) в ИдФайл должны быть указаны идентификаторы участников ЭДО (см [Organization](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html).FnsParticipantId и [Counteragent](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Counteragent.html).FnsParticipantId), а не ИНН_КПП
[Поле СвОЭДОтпр должно присутствовать](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=2882283)

Про версию конфигурации не сможем подсказать.

**Comment by GilimkhanovDenis** [comment]
1. Если мы пользуемся стандартным рабочим кабинетом Диадок (бухгалтер руками выгрузил файл из 1С и руками в личном кабинете через интернет браузер его загружает) - откуда в файле возьмутся ИД из Организации и Контрагента из диадок?

А как здесь используется компонента?..
Если вопрос в том, что из веба файл отправляется, то это потому, что веб перегенерирует контент документа после загрузки и некоторые ошибки может исправить

2. Продолжение вопроса 1 (вариант выгрузки руками и загрузки файла через интернет браузер) - почему на скриншотах выше диадок ругается не на контрагента или организацию, а на допинформацию?

Если речь про красные крестики, то это кнопка для удаления строки. О каких ошибках на скриншоте речь?

3. Вопрос уже не про ручную выгрузку, а про вариант загрузки через апи. В настоящий момент файлы, выгруженные из более ранеей версии 1С, где тоже указаны ИНН и КПП как в текущем файле, через апи отправляются. При этом при отправке через АПИ в актуальной документации указано, что контрагент и организация указываются примерно следующим образом:
SendTask = мПараметры.Organization.CreatePackageSendTask2();
SendTask.CounterAgentId = элем.КонтрагентИД;
т.е. они явно указываются не в файле, в самом методе SendTask2. Этот подход поменялся ? Теперь надо указывать в файле? вместе со старым кодом или вместо?

```
SendTask = мПараметры.Organization.CreatePackageSendTask2();
SendTask.CounterAgentId = элем.КонтрагентИД;
```
Так задаётся ящик в который будет отправлен документ. Контент документа будет ровно тот, который загружаете методом
`SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01",ПутькФайлуXML)`

В общем случае эSendTask.CounterAgentId может относиться к организации, отличной от той, которая указана в участниках докуентооборота в контенте документа.

Что касается "раньше отправлялось" - вероятно, раньше использовался PackageSendTask , а не PackageSendTask2. В нём метод с аналогичным названием сначала разбирал контент документа в объектную модель, а потом перегенерировал. Т.е. отправлялся не тот же контент, который был загружен

**Comment by AlexDevToDeath** [comment]
> 1. Если мы пользуемся стандартным рабочим кабинетом Диадок (бухгалтер руками выгрузил файл из 1С и руками в личном кабинете через интернет браузер его загружает) - откуда в файле возьмутся ИД из Организации и Контрагента из диадок?
> 
> А как здесь используется компонента?..
> Если вопрос в том, что из веба файл отправляется, то это потому, что веб перегенерирует контент документа после загрузки и некоторые ошибки может исправить
> 
> 1. Продолжение вопроса 1 (вариант выгрузки руками и загрузки файла через интернет браузер) - почему на скриншотах выше диадок ругается не на контрагента или организацию, а на допинформацию?
> 
> Если речь про красные крестики, то это кнопка для удаления строки. О каких ошибках на скриншоте речь?
> 
> 1. Вопрос уже не про ручную выгрузку, а про вариант загрузки через апи. В настоящий момент файлы, выгруженные из более ранеей версии 1С, где тоже указаны ИНН и КПП как в текущем файле, через апи отправляются. При этом при отправке через АПИ в актуальной документации указано, что контрагент и организация указываются примерно следующим образом:
>    SendTask = мПараметры.Organization.CreatePackageSendTask2();
>    SendTask.CounterAgentId = элем.КонтрагентИД;
>    т.е. они явно указываются не в файле, в самом методе SendTask2. Этот подход поменялся ? Теперь надо указывать в файле? вместе со старым кодом или вместо?
> 
> ```
> SendTask = мПараметры.Organization.CreatePackageSendTask2();
> SendTask.CounterAgentId = элем.КонтрагентИД;
> ```
> 
> Так задаётся ящик в который будет отправлен документ. Контент документа будет ровно тот, который загружаете методом
> `SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01",ПутькФайлуXML)`
> 
> В общем случае эSendTask.CounterAgentId может относиться к организации, отличной от той, которая указана в участниках докуентооборота в контенте документа.
> 
> Что касается "раньше отправлялось" - вероятно, раньше использовался PackageSendTask , а не PackageSendTask2. В нём метод с аналогичным названием сначала разбирал контент документа в объектную модель, а потом перегенерировал. Т.е. отправлялся не тот же контент, который был загружен

2. Приложенный файл веб интерфейс Диадок (ручная отправка через браузер) не принимает. Пишет только, что есть ошибки.  Если удалить всю доп информацию, то файл принимается. Почему? 
![image](https://user-images.githubusercontent.com/87308729/134033576-6e3947c0-3eae-4ce6-85a8-c47a061dd509.png)

3. Нет, данный программный код не менялся последние два квартала. Использовали сразу PackageSendTask2. Более того, если я сейчас (только что проверил) пихаю в него хмл, сделанную до 01.07, то документ уходит и диадок принимает.

**Comment by AlexDevToDeath** [comment]
> 1. Приложенный файл веб интерфейс Диадок (ручная отправка через браузер) не принимает. Пишет только, что есть ошибки. Если удалить всю доп информацию, то файл принимается. Почему?
> 
> С данным вопросом обратитесь в техподдержку
> 
> 1. Можно пример XML, который подобным образом отправляется?

Давайте пойдем от противного.
Во вложении файл.
Исправили его так, как вы сказали

Но ошибка при отправке через АПИ (код отправки тот же) не поменялась за исключением того, что пропала последняя ее часть, а именно, исчезло "Message = Поле СвОЭДОтпр должно присутствовать": .

**Код отправки:** SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01",ПутькФайлуXML)

**Текст ошибки:**

ОтправленныеДокументы = SendTask.Send();
по причине:
Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: { Location = /Файл/@ИдФайл, Message = Значение атрибута @ИдФайл имеет неверный формат: ON_NSCHFDOPPR_7701368645_772801001_9715326381_771501001_20210915_6544a794-8544-4012-b307-b5e0fd210c1c (@ИдОтпр=dc74b700-f93c-11e8-80da-0cc47a31ea11, @ИдПол=5b506d04-a26f-11eb-8db3-ac1f6bc56bbd)
				При отстутствии /Файл/Документ/ТаблСчФакт/СведТов/ДопСведТов/НомСредИдентТов и /Файл/Документ/ТаблСчФакт/СведТов/ДопСведТов/СведПрослеж значение @ИдФайл должно начинаться с ON_NSCHFDOPPR_, ON_NSCHFDO

[ДляДиадок.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/7197733/default.txt)

**Comment by GilimkhanovDenis** [comment]
[fixe.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/7200469/fixe.txt)
Попробуйте такой
