### ISSUE TITLE
Добавление xml файла через API

### ISSUE THREAD

**Issue by JGhjfhgjkdh5486t** [diadoc/diadocsdk-1c-docs#687]
Добрый день.
Каким образом из 1С добавить файл xml через API, уже подготовленный для загрузки ?
Аналогично как вручную - добавляем новый документ
![image](https://user-images.githubusercontent.com/71314160/134128333-ef016062-9b27-4d27-b298-89676619b1e4.png)

И его отображение преобразуется в Счет-фактуру.
Имя файла: ON_NSCHFDOPPR_2BE9E283AB9A78D40F3951415B92D5787F2_2AE309584F4-CB30-4A16-A300-42C1D3BB0772_20210909_70ceb6c5-2e5f-4f3b-ad57-5d0de5b0dc65.xml
Внутри вижу: Функция="СЧФ"
То есть, предполагаю, что нужно отправлять как формализованный документ с этой функцией.
И каким-то образом прикладывать только этот файл, ничего не заполняя ?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Используйте [PackageSendTask2.AddDocumentFromFile("UniversalTransferDocument", "СЧФ", "utd820_05_01_02", FilePath)](https://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocumentFromFile)

пример использования метода [здесь](https://1c-docs.diadoc.ru/ru/latest/HowTo/HowTo_post_document.html)

**Comment by JGhjfhgjkdh5486t** [comment]
Благодарю за ответ.
с utd820_05_01_02 - есть ошибка:
PackageSendTask2.AddDocumentFromFile: Неверный тип документа
Отправляется успешно с помощью: utd820_05_01_01 или utd820_05_01_01_hyphen, но выходит в Черновиках как УПД, а не как счет-фактура.

**Comment by kab1k** [comment]
Получите необходимый тип с помощью GetDocumentTypes. Метод возвращает описание типов документов, доступных в ящике.
https://diadoc-sdk.readthedocs.io/ru/latest/http/GetDocumentTypes.html
