### ISSUE TITLE
Проверка подписки для своего ящика

### ISSUE THREAD

**Issue by Lacertus** [diadoc/diadocsdk-1c-docs#688]
Добрый день! Не нашел методов для проверки остатка подписки для предупреждения пользователей.
В курсе, что при завершении подписки появится ошибка 402, но в этот момент уже поздно. Хотелось бы предупреждать пользователя о скором завершении. Есть такая возможность, или обязательно нужно заходить в веб интерфейс?

**Comment by aeremina88** [comment]
Добрый день!
Сейчас нет таких методов и в ближайшее время не планируется.
