### ISSUE TITLE
Документ не может быть отправлен в таком формате

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#689]
Добрый день! Для перехода на новый формат УКД обновила версию с 32 на 35. Перестали отправляться документы УКД Произошла исключительная ситуация (PackageSendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: Документ не может быть отправлен в указанном формате.
У меня PackageSendTask = Organization.CreatePackageSendTask();
Подскажите, что то перестали поддерживать в новой версии?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Объект PackageSendTask не поддерживает отправку УКД по 736 приказу - только 189. Сам объект тоже считается устаревшим и в ближайшее время может быть удалён из компоненты (см. [Предупреждение](https://1c-docs.diadoc.ru/ru/latest/Downloads.html))
Для отправки УКД в новом формате используйте PackageSendTask2.
`dd_DocumentToSend = PackageSendTask2.AddDocument("UniversalCorrectionDocument", "КСЧФДИС", "ucd736_05_01_02");`
Второй параметр должен совпадать с полем "Функция"/"Function" в контенте документа

**Comment by GuninaY** [comment]
Это я понимаю, но отправка по прежнему у нас идет в 189 формате. Обновила только библиотеку пока

**Comment by GilimkhanovDenis** [comment]
Можете уточнить, контент документа формируете самостоятельно или используете представление контента из компоненты (каким методом добавляете документ на отправку в PackageSendTask)?

Какую функцию указываете в контенте ?

**Comment by GuninaY** [comment]
Формируем самостоятельно:
PackageSendTask = Organization.CreatePackageSendTask();	
DocumentToSend = PackageSendTask.AddDocument("UniversalCorrectionDocument");
Content = DocumentToSend.Content;
Content.Function = "InvoiceAndBasic";  и т.д. его заполняем 
Далее отправляем
DocumentPackage = PackageSendTask.Send();

**Comment by GilimkhanovDenis** [comment]
Да, в версии 5.33.0 изменилось поведение PackageSendTask'а - стало невозможно отправить УПД и УКД с фактурными частями

Что можно сделать сейчас.
Должен сработать такой код:
        ```
        СоответствиеФункцийУКД = Новый Соответствие;
	СоответствиеФункцийУКД.Вставить("InvoiсеAndBasic", "КСЧФДИС");
	СоответствиеФункцийУКД.Вставить("Basic",                   "ДИС");
	СоответствиеФункцийУКД.Вставить("Invoiсе",               "КСЧФ");
	
	PackageSendTask = Organization.CreatePackageSendTask();
	DocumentToSend = PackageSendTask.AddDocument("ucd_05_01_03");
	ФункцияУКД = "InvoiceAndBasic";
	DocumentToSend.Function = СоответствиеФункцийУКД[ФункцияУКД];
	Content = DocumentToSend.Content;
	Content.Function = ФункцияУКД;
	//
	//...
	//
	DocumentPackage = PackageSendTask.Send();
```

**Comment by GuninaY** [comment]
К сожалению ошибка сохраняется
