### ISSUE TITLE
Ошибка. УПД XML обработка статусов подписанных документов

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#69]
Контрагент подписал УПД документ:
![img-2017-02-14-15-00-53](https://cloud.githubusercontent.com/assets/20082460/22928396/56da9d3e-f2c7-11e6-962a-cf73a45cb395.png)

Анализирую ленту событий:
массивEvent = Organization.GetDocumentEventList(ПоследнийЗагруженныйEventID);
получил события, но у текущего события, подписания документа УПД не определен тип, EventType пусто
![img-2017-02-14-14-53-28](https://cloud.githubusercontent.com/assets/20082460/22928475/b5a43208-f2c7-11e6-8599-92cf11df9274.png)
и не понятно, что отражает оно для данного документа.

Если открыть сам документ на сайте, то внутри видно, что он подписан, а в списке документов видна вот такая надпись:
![img-2017-02-14-15-05-48](https://cloud.githubusercontent.com/assets/20082460/22928553/245d286c-f2c8-11e6-9a4c-e049b15cc102.png)

Подскажите, что это значит и как правильно определить что документ подписан и соответственно документооборот завершился успешно (в этом случае документу в программе ставлю статус возвращен и закачиваю к документу приложение новый zip контейнер по документу с сайта)

**Comment by jakeqwert** [comment]
По теме статусы стали возвращаться для обычных УПД (не исправительных в исправительных такая же сейчас проблема) и вопрос остается по последней картинке из 1 поста.

**Comment by azhipaigor** [comment]
Добрый день! Расширил статусы для УПД/УКД в GetDocumentEventList. Выйдет в ближайшем релизе 5.16.0.
