### ISSUE TITLE
Подписание неформализованных документов

### ISSUE THREAD

**Issue by crashsip** [diadoc/diadocsdk-1c-docs#690]
Добрый день.
Нужна помощь.
Используем библиотеку Diadoc_5_34_4_713_x64.dll, подключается как внешняя компонента по технологии 1С (AddIn).
```
ЗагрузитьВнешнююКомпоненту(ИмяФайла);
DiadocApi_ = Новый("AddIn.DiadocInvoiceAPI");
```
При создании и отправке неформализованного документа (акт сверки) не могу понять, как сделать так, чтобы документ контрагенту приходил с требованием подписания. Т.е. на данный момент документ из 1С уходит в ДИАДОК корректно, до контрагента доходит, но статус у него "Документооборот завершен". Нам же необходимо чтобы документ отправлялся и приходил к контрагенту со статусом "Требуется подпись".

по https://1c-docs.diadoc.ru/ru/latest/index.html не нашел необходимой информации (может не правильно искал)

код отправки используется такой (часть кода, выполняется в цикле):
```
SendTask = КонтекстОрганизации.CreatePackageSendTask2();
SendTask.CounterAgentId = КонтрагентВСопоставлении;
DocumentToSend = SendTask.AddDocumentFromFile("Nonformalized", "default", "v1", ТекущийДокумент);
DocumentToSend.Comment = КомментКДокументу;
MetaDataItem = DocumentToSend.AddMetadata();
MetaDataItem.Key   = "FileName";
MetaDataItem.Value = ИмяДокумента;
РезультатОтправки = SendTask.Send();
```

Через WEB-интерфейс неформализованный документ с требованием подписи отправить можно.

**Comment by GilimkhanovDenis** [comment]
Добрый день.

[PackageSendTask2.AddDocumentFromFile(...)](https://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocumentFromFile) возвращает [CustomDocumentToSend](https://1c-docs.diadoc.ru/ru/latest/ComObjects/CustomDocumentToSend.html). [CustomDocumentToSend](https://1c-docs.diadoc.ru/ru/latest/ComObjects/CustomDocumentToSend.html) наследует интерфейс [DocumentToSend](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentToSend.html). Настройка есть в этом интерфейсе - NeedRecipientSignature


аналогичные запросы:
https://github.com/diadoc/diadocsdk-1c-docs/issues/630
https://github.com/diadoc/diadocsdk-1c-docs/issues/523

**Comment by crashsip** [comment]
спасибо! первый раз на гитхабе по сути... не увидел что 640 уже закрытых постов есть.... ))
