### ISSUE TITLE
Заполнение марок в УКД

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#691]
Доброе утро! Пытаюсь в новом 736 формате заполнить информацию о марках: 
добавляю так 
Item = Content.Table.Items.AddItem();
ЭлИнфПолФХЖ2  = Item.AdditionalInfos.AdditionalInfo()
Получаю COMобъект без полей id и  cis 
![Снимок](https://user-images.githubusercontent.com/49683051/134460405-8a99ee77-39cc-4582-89c6-8e05f511631c.JPG)
Подскажите, что я делаю не так?

**Comment by GilimkhanovDenis** [comment]
Добрый день

`Item.AdditionalInfos.AdditionalInfo()` вернул вам коллекцию (IValueCollection)
Владелец коллекции - `Item.AdditionalInfos`
Для добавления элемента в коллекцию сделайте вызов
`Item.AdditionalInfos.AddAdditionalInfo()`

**Comment by GilimkhanovDenis** [comment]
Отмечу также, что в УКД 736 есть отдельная коллекция для заполнения информации о прослеживаемости - `Item.ItemTracingInfos`

**Comment by GuninaY** [comment]
Спасибо!
