### ISSUE TITLE
Изменения с 01.10.2021 в формате отправки

### ISSUE THREAD

**Issue by GerdoSergey** [diadoc/diadocsdk-1c-docs#693]
Добрый день!
С 01.10.2021 УКД нужно отправлять в новом формате. 
**Вопрос по формированию УПД и обычных счетов-фактур, будет ли после 01.10 работать конструкция?** 
SendTask = Organization.CreatePackageSendTask2();
...
DocumentToSend = SendTask.AddDocument (ТипДокумента, ФункцияДокумента, "utd820_05_01_01_hyphen");

**Comment by azhipaigor** [comment]
С 01.10.2021 нельзя будет отправить только УКД в формате приказа 189. УПД и счетов-фактур в формате приказа 820 изменения не касаются - конструкция будет работать.
