### ISSUE TITLE
@CurrencyName: The 'CurrencyName' attribute is invalid

### ISSUE THREAD

**Issue by nikolayuy** [diadoc/diadocsdk-1c-docs#694]
При отправка УКД возникает ошибка:
@CurrencyName: The 'CurrencyName' attribute is invalid

При подготовке к переходу на отправку УКД по приказу 736 столкнулись с проблемой заполнения валюты.

Ранее при создании документа УКД (UniversalCorrectionDocument, "КСЧФДИС", "ucd_05_01_03") заполняли только свойство Currency (код валюты [КодОКВ]) и проблем не было.

При создании документа UniversalCorrectionDocument, "КСЧФДИС", "ucd736_05_01_01" или "ucd736_05_01_02" возникает указанная ошибка. Заполнение свойства CurrencyName проблему не решает.

Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 2, Position: 173, /UniversalCorrectionDocument[1]/@CurrencyName: The 'CurrencyName' attribute is invalid - The value '' is invalid according to its datatype 'String' - The Enumeration constraint failed.

Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 2, Position: 173, /UniversalCorrectionDocument[1]/@CurrencyName: The 'CurrencyName' attribute is invalid - The value 'RUB' is invalid according to its datatype 'String' - The Enumeration constraint failed.

Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 2, Position: 173, /UniversalCorrectionDocument[1]/@CurrencyName: The 'CurrencyName' attribute is invalid - The value 'Российский рубль' is invalid according to its datatype 'String' - The Enumeration constraint failed.

**Comment by nikolayuy** [comment]
Ошибка повторяется на COM компонента  x64 для произвольных систем версий 5.35.3.731 и 5.35.4.736.

**Comment by azhipaigor** [comment]
UserData XSD определяет СurrencyName так:
НАимОКВ - наименование валюты
Для формирования НаимОКВ по коду валюты принимает значение - 1
Если формировать НаимОКВ не нужно - принимает значение 0

Получить UserData XSD для документа можно с помощью метода [Organization.SaveUserDataXSD](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html?highlight=Organization#organization-saveuserdataxsd).
