### ISSUE TITLE
Ошибка при подписании и отправке документа

### ISSUE THREAD

**Issue by galiurust** [diadoc/diadocsdk-1c-docs#697]
Добрый день! Типовая бухгалтерия ред. 7.70.650
Версия обработок 2.16.24
Ошибка при нажатии кнопки "Подписать и отправить":
Отправляем пакет 1. Ошибка. PackageSendTask2.Send: ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalTransferDocumentWithHyphens/Signers/SignerReference: @Inn is required
/UniversalTransferDocumentWithHyphens/Signers/SignerReference: SignerDetails not found for b

**Comment by happydeadman** [comment]
Добрый день!

Необходимо настроить область полномочий подписанта.
Для того вам нужно в веб-интерфейсе https://diadoc.kontur.ru/ перейти в раздел "Настройки " - "Сотрудники" - выбрать сотрудника, сертификат которого используется при подписании - перейти в вкладку "Данные по сертификатам" - "Область полномочий" и указать нужные полномочия. 
Рекомендации по их заполнению: http://wiki.diadoc.ru/pages/viewpage.action?pageId=8355842.

Как правило, полномочия прописаны в доверенности или в учетной политике компании.
