### ISSUE TITLE
Ошибка после обновления КриптоПро на версию 5.0.12000

### ISSUE THREAD

**Issue by galiurust** [diadoc/diadocsdk-1c-docs#699]
Типовая бухгалтерия. Редакция 4.5 (7.70.650)
При переходе на закладку "Отправленные" выдает сообщение:
Документы.СостояниеДокументооборота = Док.DocflowStatus.PrimaryStatus.Text; 
{I:\1C BASE\TB_UGT\EXTFORMS\DIADOC_77_V_2_16_24\ДИАДОК_ДЛЯ_1С_77.ERT(7849)}: Поле агрегатного объекта не обнаружено (DocflowStatus)

**Comment by kab1k** [comment]
Добрый день. 

Вам необходимо обратиться в техническую поддержку за версией модуля со всеми исправлениями.
Также потребуется обновить и зарегистрировать компоненту.
