### ISSUE TITLE
Существует ли возможность в API Диадок для 1С связать уже отправленные документы ?

### ISSUE THREAD

**Issue by ivankhrulev** [diadoc/diadocsdk-1c-docs#7]
Существует ли возможность в API Диадок для 1С связать уже отправленные документы ?

**Comment by denver069** [comment]
Список отправленных из вашего ящика документов можно получить через объект [DocumentsTask](http://1c-docs.diadoc.ru/ru/latest/GetDocumentsTask.html). Создать объект можно методом [Organization.GetDocumentsTask()](http://1c-docs.diadoc.ru/ru/latest/GetDocumentsTask.html) В объекте [DocumentsTask](http://1c-docs.diadoc.ru/ru/latest/GetDocumentsTask.html) доступны фильтры и возможность разделить процесс получения данных на порции по 100 документов. Далее вы можете найти по номеру и дате документов их аналоги в базе и сохранить соответствие ссылки в 1С идентификатору в Диадок.

**Comment by ivankhrulev** [comment]
Немного уточню, речь не о сопоставлении ОбъектовЭД с документом 1С. 
Возможно ли связать документы Диадок друг с другом(в частности отправленные)? (аналогично СФ и Документу основанию). 

Цель: обозначить пакет документов. НО пакет должен быть отправлен не единовременно, а по факту заведения документов. Обрабатываться на принимающей стороне будет по факту получения. Связать документы необходимо для обработок и дальнейшего анализа.

т.е. отправили неформализованный документ, затем через неделю еще один (например приложение), затем нужно обозначить и зафиксировать, что это один пакет документов. Т.к. при необходимости получения пакета, можно было подтянуть все докумаенты.

**Comment by denver069** [comment]
**Документ №1** - Ранее отправленный документ через [Диадок](https://diadoc.kontur.ru).
**Документ №2** - Новый документ.

При отправке документа №2, выполнить связку можно методом [**AddInitialDocument()**](http://1c-docs.diadoc.ru/ru/latest/search.html?q=AddInitialDocument&check_keywords=yes&area=default) со значением [DocumentId](http://1c-docs.diadoc.ru/ru/latest/Document.html) документа №1.

В результате на сайте [diadoc.kontur.ru](https://diadoc.kontur.ru) документ №1 и документ №2 будут отображены в одном пакете. Кроме этого, документ №2 будет содержать [DocumentId](http://1c-docs.diadoc.ru/ru/latest/Document.html) документа №1 в коллекции [InitialDocumentIds](http://1c-docs.diadoc.ru/ru/latest/Document.html), а документ №1 будет содержать [DocumentId](http://1c-docs.diadoc.ru/ru/latest/Document.html) документа №2 в коллекции [SubordinateDocumentIds](http://1c-docs.diadoc.ru/ru/latest/Document.html).
