### ISSUE TITLE
Помогите разобраться с  GetDocumentById

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#701]
Доброе утро! Помогите, пожалуйста, разобраться с получением по id документа. Выполняю Organization.GetDocumentById("453b8053-5d58-4762-8c0d-7a91c6806b85f591d4ff-2cd0-4a69-8bee-1a1bd9a77d63"). Возвращает документ у которого Document.Corrected = Ложь и  Document.IsDeleted = истина. Получается, что это другой документ (дубль), по нему был отказ подписи - https://diadoc.kontur.ru/8c4381c2-96ba-4f0f-8bbe-c9563f974922/Document/Show?letterId=c5dd7b03-07d7-403b-be32-21d453c5a499&documentId=fa4eb18e-6b6f-4291-8dba-a9bae46c254c. Но как видим здесь другой id.  Я же пытаюсь получить вот этот https://diadoc.kontur.ru/8c4381c2-96ba-4f0f-8bbe-c9563f974922/Document/Show?letterId=b07cc37f-117a-4d05-b301-b1174dce73f6&documentId=f591d4ff-2cd0-4a69-8bee-1a1bd9a77d63. Верны ли мои предположения?

**Comment by GilimkhanovDenis** [comment]
Добрый день

1. По идентификтаору `453b8053-5d58-4762-8c0d-7a91c6806b85f591d4ff-2cd0-4a69-8bee-1a1bd9a77d63` вы получаете информацию о черновике
2. Из этого черновика был создан [документ](https://diadoc.kontur.ru/8c4381c2-96ba-4f0f-8bbe-c9563f974922/Document/Show?letterId=b07cc37f-117a-4d05-b301-b1174dce73f6&documentId=f591d4ff-2cd0-4a69-8bee-1a1bd9a77d63), который вы и хотите получить. Идентификатор у этого документа - `b07cc37f-117a-4d05-b301-b1174dce73f6&documentId=f591d4ff-2cd0-4a69-8bee-1a1bd9a77d63`
3. [Документ с отказом в подписи](https://diadoc.kontur.ru/8c4381c2-96ba-4f0f-8bbe-c9563f974922/Document/Show?letterId=c5dd7b03-07d7-403b-be32-21d453c5a499&documentId=fa4eb18e-6b6f-4291-8dba-a9bae46c254c) был отправлен без использования черновика. Привязан к пакету документов через указание идентификатора этого документа как InitialDocumentId у [УКД|https://diadoc.kontur.ru/8c4381c2-96ba-4f0f-8bbe-c9563f974922/Document/Show?letterId=219327fa-9cea-420e-a4c1-c4691b3aaf4f&documentId=17160194-b7e4-491b-98e5-2ee28d7388ac] наравне с идентификатором документа из пункта 2
