### ISSUE TITLE
Проблема при отправке УКД

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#702]
Подскажите, пожалуйста, по УКД при ситуации пересортицы. Мы пытаемся отправить УКД с количеством до изменения = 0, т.е. мы добавляем новую позицию, которой не было в УПД. Система ругается что OriginalValue для количества должно быть больше нуля. Раньше у нас получалось отправлять УКД в таком случае, теперь нельзя?

**Comment by GuninaY** [comment]
DocumentToSend = PackageSendTask2.AddDocument("UniversalCorrectionDocument", "КСЧФДИС", "ucd736_05_01_02");
Content = DocumentToSend.Content.UniversalCorrectionDocument;
Item = Content.Table.Items.AddItem();
Item.Quantity.OriginalValue = XMLСтрока(стр.КоличествоДоИзменения);
Item.Quantity.CorrectedValue = XMLСтрока(стр.Количество);

Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalCorrectionDocument/Table/Items/Item[2]/Quantity/@OriginalValue: Quantity/@OriginalValue must be > 0

**Comment by GuninaY** [comment]
понятно, спасибо, в вэб интерфейсе у меня получилось сделать документ)

**Comment by GilimkhanovDenis** [comment]
Попробуйте в интеграции вообще не заполнять `Item.Quantity.OriginalValue` - оставьте его пустым

**Comment by GuninaY** [comment]
Вы знаете, помогло
