### ISSUE TITLE
Проблема при подписании документа.

### ISSUE THREAD

**Issue by darujo** [diadoc/diadocsdk-1c-docs#705]
Добрый день.
При подписании документа УПД заполняем данные
-----------------------------------------
Employee
property
MiddleName VT_BSTR Александрович
FirstName VT_BSTR Роман
LastName VT_BSTR Таганов
EmployeeBase VT_BSTR Должностные обязанности
EmployeeInfo VT_BSTR 
Position VT_BSTR 
------------------------------------------
UniversalTransferDocumentBuyerTitle
property
AcceptanceDate VT_BSTR 19.10.2021
OperationContent VT_BSTR Принято с разногласиями
OperationCode VT_BSTR 2
DocumentCreatorBase VT_BSTR 
DocumentCreator VT_BSTR Тестовая организация №8199767, ИНН/КПП 9681997678/968101000
------------------------------------------
SignerReference
property
CertificateThumbprint VT_BSTR d8d11fc06141e0563e753a464e0d468dc5bbb17a
CertificateBytes VT_BSTR 
BoxId VT_BSTR 8283c62dadea494ba8830b9a0cea5634@diadoc.ru
------------------------------------------
при отправке подписи по документу получаем ошибку
![image](https://user-images.githubusercontent.com/65738957/137820647-0afb7d08-0955-401c-b0df-12d1ec199221.png)
подскажите чего не хватает?

**Comment by GilimkhanovDenis** [comment]
Добрый день

В логах вижу ошибку

```
Invalid generated title:
Metadata errors: 
Validation errors: Location: Line: 14, Position: 22, /Файл[1]/ИнфПок[1]/СодФХЖ4[1]/СвПрин[1]/СвЛицПрин[1]/РабОргПок[1]/@Должность, Message: The 'Должность' attribute is invalid - The value '' is invalid according to its datatype 'String' - The actual length is less than the MinLength value.
```

1) Заполните поле Employee.Position .
2) Ошибки от Диадока бывают многострочные, как, например, в этом случае. Компонента их текст никак не преобразовывает и отдаёт так же многострочными. Попробуйте ловить их полностью, а не до конца строки. Так у вас будет больше контекста возникновения ошибки

**Comment by GilimkhanovDenis** [comment]
Задачу про какой-то альтернативный способ возврата ошибок добавили к себе в бэклог

Это обращение закрываю
