### ISSUE TITLE
Изменения в выпуске сертификатов с 01.01.2022

### ISSUE THREAD

**Issue by dimok22prog** [diadoc/diadocsdk-1c-docs#708]
Здравствуйте.
Насколько я понял, с 01.01.2022 выпуск сертификатов будет возможен ТОЛЬКО через ФНС или их доверенных лиц (список еще в процессе утверждения до конца года).

Однако меня больше всего волнует следующая новость. Сертификаты, выпущенные с 01.01.2022 через ФНС или доверенных лиц будут НЕэкспортируемыми, НЕкопируемыми и записываться в одном экземпляре на токен, приобретаемый отдельно.

Сейчас мы устанавливаем сертификаты в реестр сервера, с которого осуществляется отправка и подписание документов, где работает связка COM компонента Диадок для произвольных систем - Крипто ПРО.

Вопрос:
В случае использования только НЕэкспортируемых и НЕкопируемых сертификатов с помощью COM компоненты Диадок для произвольных систем в связке с Крипто ПРО, как обеспечить доступность таких сертификатов для компоненты Диадок **без физического варианта размещения токена** на сервере?

**Comment by JohnSergeev** [comment]
Присоединяюсь к вопросу! 

Очень интересно услышать ответ и хоть какое-то объяснение, что делать с, например, 30 ЭЦП, если их нельзя скопировать в реестр выделенного сервера для работы с ЭДО?

**Comment by IrinaShmonina** [comment]
Здравствуйте,
10.11 будет вебинар по работе с новыми сертификатами и машиночитаемыми доверенностями. 
На вебинаре расскажем, где нужно будет получать КЭП, когда изменения вступят в силу и что поменяется для пользователей ЭДО в ближайшем будущем.
Программа:
- Изменения в работе с сертификатами электронной подписи руководителей.
- Подпись сотрудника и машиночитаемая доверенность.
- Сроки действия сертификатов электронной подписи.
- Ответы на вопросы.
Дата: 10 ноября, с 12:00 до 14:00 Мск.
Регистрация и подробная программа: [на сайте мероприятия](http://school.kontur.ru/video/10713?utm_source=sale&utm_medium=letter&utm_campaign=webinar&utm_content=63fz&utm_term=registration).
**Участие бесплатное**.

**Comment by JohnSergeev** [comment]
На семинаре побывали. Легче, если честно, не стало. Т.к. пока видна только одна технически возможная схема работы:
1. Получаем ЭЦП на директора на токене
2. Получаем ЭЦП физ.лиц на тех, кто раньше получал ЭЦП на себя в организации
3. Ею подписываем МЧД для физ. лиц на право использования их ЭЦП для подписания документов организации
3. Эти ЭЦП физ.лиц впихаваем в реестр на сервер ЭДО 
4. И там теперь все, как и раньше автоматически работает

Вот только где взять ненормальных, которые свою, теперь уже именно персональную ЭЦП физ.лица отдадут для использования по такой схеме? А что будет, если такая ЭЦП с сервера попадет не в те руки? 

А, как можно по-другому?

Может можно получать ЭЦП физ. лиц, как-то ограниченную в правах использования? 
Типа, чтобы документы компании, которая выписала МЧД на эту ЭЦП подписывать ею было можно, а, например, дарственную на свою квартиру - нет?

Иначе какая-то полная ерунда получается.

**Comment by kulakovskaya** [comment]
Здравствуйте,
к сожалению, текущая нормативная база не предусматривает иных вариантов. Мы ожидаем, что будет переходный период, в который, в том числе получится найти безопасное решение и для той схемы, которую вы описываете. Сейчас мы можем рекомендовать выпустить сертификат на руководителя до конца года. Такой сертификат будет действовать до конца своего срока, что даст больше времени на внедрение и освоение новых процессов.

**Comment by dimok22prog1** [comment]
Добрый вечер. Прочитал о добавлении в последней версии компоненты возможности работы с МЧД.
Но, насколько понял, можно использовать МЧД уже зарегистрированные через сервис Контур или Прочие.
Подскажите, а кто и как их выпускает и как передает в сервис Контур или Прочие?

**Comment by happydeadman** [comment]
Добрый день.

Прямо сейчас сформировать МЧД (для ЭДО с контрагентами или взаимодействия с гос. органами) можно на портале [m4d.nalog.ru ](https://m4d.nalog.ru/). Чтобы начать использовать такую МЧД, её необходимо подписать с помощью электронной подписи. Сделать это можно, например, через сервис Контур.Крипто или КриптоАРМ.
Также сформировать МЧД можно в сервисе Контур.Доверенность. Сервис доступен по адресу: https://m4d.kontur.ru/ . С инструкцией по работе в данном сервисе вы можете ознакомиться здесь: https://support.kontur.ru/pages/viewpage.action?pageId=83873849.

XmlContent - это контент самой МЧД.  
XmlSignature - это контент файла подписи (*.sig, *.sgn и т.п.), который был сформирован при выпуске МЧД.

**Comment by GilimkhanovDenis** [comment]
Ответ на первоначальный вопрос [дан](https://github.com/diadoc/diadocsdk-1c-docs/issues/708#issuecomment-977744802). Тикет закрываю
