### ISSUE TITLE
Пожелания по доработке АПИ

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#709]
Добрый день.

Денис, как и договаривались, выкладываю отдельно блок предложений по доработке АПИ.

По большому счету, все далее описанные моменты касаются общей идеи, которую мы хотели бы реализовать в своей учетной системе в плане работы с ЭДО Диадок – чтобы как можно больше доступного функционала по работе с ЭДО мы могли бы выполнять в рамках работы в самой учетной системе. Без необходимости выполнения каких-то специальных действий напрямую и только на сайте Диадок. В идеале хотелось бы добиться того, чтобы из учетной системы можно было бы сделать вообще всё.

Далее перечислены как раз моменты, отсутствие которых в АПИ, как раз и заставляет работать с ЭДО вне учетной системы. Т.к. в АПИ для 1С просто не поддерживается данный функционал, присутствующий в Диадок.

### 1.	Информация об операторах роуминга контрагентов
Сейчас при работе в Диадок на сайте для контрагентов ЭДО отображается не только то, что он работает в роуминге, но и оператор ЭДО, через которого работает этот контрагент. Пример:
![изображение](https://user-images.githubusercontent.com/33707226/139798477-dba33f48-4575-4d85-ae0e-2c8831981028.png)

Т.е. по факту в Диадок **есть** информация и о том, через роуминг работает контрагент или нет и, если через роуминг, то **есть информация через какого оператора ЭДО**.

Однако, в АПИ для 1С никак нельзя получить информацию о том, через какого оператора работает контрагент в роуминге. Т.е. понять в роуминге контрагент или нет – возможно. У контрагента (объекта АПИ Counteragent) есть свойство IsRoaming (булево), показывающее в роуминге контрагент или нет. Но вот получить информацию об операторе роуминга для контрагента нельзя никак.

Сейчас это приходится делать самостоятельно, без какой-либо привязки информации по операторам к данным самого Диадока (мы, например, определяем оператора контрагента по префиксу в ID участника ЭДО).

Т.к. на текущий момент у разных операторов разные особенности работы в ЭДО и разные возможности роуминга с Диадок, бывает очень важно знать через какого именно оператора с нами работает тот или иной контрагент в роуминге.

**Предложение:**
Добавить в АПИ для 1С либо какую-то функцию получения информации об операторе ЭДО для объекта контрагента. Или добавить поле с данными оператора ЭДО контрагента в данные контрагента. 

По идее по оператору хотелось бы знать как минимум:
1.	Наименование оператора
2.	Префикс участника ЭДО (3 символа)

А в идеале еще возможности оператора типа:
1.	Работает ли с данным оператором функционал аннулирования в роуминге
2.	Что-то что вы лучше знаете в плане того, что одни операторы поддерживают, а другие нет.

Получение информации по операторам контрагентов в роуминге непосредственно от Диадок было бы более правильным тем более, что в Диадок эта информация явно есть (вы же на сайте её показываете).

### 2.	Просмотр удаленных документов
Сейчас с помощью АПИ для 1С можно удалить документ – переместить его в папку «Удаленные». Можно, з**ная ID документа**, восстановить его из удаленных. Но вот посмотреть, что сейчас по организации лежит в папке «Удаленные» – т.е. узнать какие документы сейчас в организации точно удалены… с помощью АПИ для 1С нельзя.

Поэтому, если мы документ удалили и его  ID где-то сохранили, то всё более-менее нормально. Т.е., если мы захотим, то, получив документ по этому сохраненному ID, мы сможем его с помощью АПИ восстановить. НО! Если у нас по какой-то причине нет ID удаленного документа, то с помощью АПИ мы до него вообще никак «добраться» не сможем. Т.е. мы в рамках АПИ просто вообще никак не знаем, что этот документ у нас вообще есть!

Если честно, совершенно непонятно почему и для чего существует это ограничение.

Сейчас приходится сохранять ID всех удаленных документов для возможности их восстановления в нужный момент. Но на наших объемах часто не хватает именно возможности оперативно посмотреть содержимое папки «Удаленные» как она есть – именно как она точно заполнена в Диадоке, а не то, какой список удаленных документов собран у нас в нашей учетной системе по их сохраненным ID.

**Предложение:**
Хотелось бы, чтобы все-таки была возможность получения списка удаленных документов. Либо с помощью какого-то отдельного метода, либо через добавление функционала отбора удаленных в **DocumentsTask** через задание какой-то специальной категории отбора для свойства **Category**.

### 3.	Права пользователя и доступность подразделений
**Важность: высокая**

Сейчас с помощью АПИ можно получить информацию по правам пользователя в рамках его подключения по ЭЦП в плане доступа к функционалу ЭДО – заблокирован ли он, может ли создавать документы, подписывать документы, удалять и восстанавливать их и т.п. Также можно получить информацию по тому, в каком подразделении пользователь состоит и к документам каких подразделений имеет доступ.

Это крайне важная и полезная информация. 

В работе с ЭДО мы сейчас используем несколько организаций, у некоторых из них довольно-таки много подразделений. Но, главное, у нас используется много ЭЦП. Которые, имеют свойство заканчивать свой срок действия. Далее на сотрудника получают новую ЭЦП и начинают использовать её. И вот тут мы часто сталкиваемся с ошибками в первоначальных настройках доступа для новых ЭЦП. В небольшой части в плане прав пользователя на те или иные действия, но в основном – в плане доступа пользователя к тем или иным подразделениям (документам в подразделениях).

И мы постоянно находимся в странной ситуации, когда мы в учетной системе замечаем ошибку, связанную с неправильно настроенным доступом в подразделения организации. Далее мы в учетной системе можем увидеть права данного пользователя вошедшего под данной ЭЦП и можем понять в чем именно ошибка с правами доступа и… всё! Далее в самой учетной системе, точно зная, что нужно поменять в настройках доступа пользователя по конкретному ЭЦП, мы ничего сделать не можем.

Т.к. на текущий момент возможность ПРОЧИТАТЬ информацию по правам доступа в АПИ есть. А вот возможности ИЗМЕНИТЬ эту информацию в АПИ нет.

И, увидев в учетной системе ошибку, и в этой же системе разобравшись с тем почему она возникает и как её исправить, мы вынуждены все изменения в правах пользователя делать не в учетной системе, а заходя на сайт Диадок и изменяя доступ пользователя к тем или иным подразделениям только и именно на сайте Диадок. 

**Предложение:**
Дополнительно к функционалу по ЧТЕНИЮ настроек прав пользователя, добавить в АПИ функционал по ИЗМЕНЕНИЮ настроек прав пользователя.

**Хотя бы в части настроек текущего подразделения пользователя и настроек доступных для данного пользователя подразделений.**

Это позволило бы ответственным сотрудникам при обнаружении проблемы с правами доступа к подразделениям при работе в учетной системе, в этой же учетной системе эти проблемы и исправлять. А не «лазить» за исправлением проблем напрямую в ящики организаций на сайт Диадок. Тем более, что прямой доступ туда есть у гораздо меньшего числа людей, чем тех, кто мог бы исправить обнаруженную проблему. И для исправления приходиться не просто выполнять какие-то действия вне учетной системы, но на самом деле еще и просить других людей, имеющих доступ к организации на сайте, выполнить вручную необходимые действия. 

А в рамках учетной системы мы могли бы самостоятельно гибко настроить доступ к соответствующему функционалу настроек прав доступа к подразделениям и выполняли бы все требуемые настройки более просто и понятно.

### 4.	Странности и ограничения в возможностях работы с п пользователями и правами пользователей

**Первое. Определение текущего пользователя**

Как понять под каким пользователем мы подключились к той или иной организации?

Сперва мы выбираем ЭЦП из списка доступных и подключаемся по нему в Диадок. Далее получаем список доступных по ЭЦП организаций. Далее для нужной организации мы можем вызвать метод **GetUsers()** и получить список сотрудников этой организации. Далее, если перебрать всех сотрудников в цикле и проверить у каждого свойство **IsCurrentUser**, то можно найти текущего пользователя, под которым произошла авторизация.

**Предложение:**
Может быть было бы удобнее и логичнее для объекта организации завести функцию типа **GetCurrentUser()**, сразу возвращающую ссылку на текущего пользователя (объект типа **OrganizationUser**))? 

Понятно, что можно и циклом по списку пользователей «поездить», но почему нельзя сразу предоставить доступ к текущему пользователю, а вместо этого предлагается получать список всех пользователей и затем ещё их всех перебирать, чтобы понять под каким пользователем из этого списка произошло подключение?

**Второе. Некая непонятность с должностями пользователей**

У пользователя есть свойство **Position** – Должность пользователя:
![изображение](https://user-images.githubusercontent.com/33707226/139799195-140699c8-c85f-4b0a-aeb1-d459b55f7152.png)
 
При этом в данных прав пользователя в организации (**Permissions**) есть поле **JobTitle** –  должность сотрудника:
![изображение](https://user-images.githubusercontent.com/33707226/139799211-62df214b-191b-4ccc-a9b3-bd5367df4458.png)
 
Тут возникают вопросы:
1.	Если Position пользователя и JobTitle в его правах – это одно и то же, то зачем вообще нужен и заведён JobTitle?
2.	Если это разные данные, то, в чем между ними разница?
3.	Что вообще делает JobTitle в данных прав пользователя? Он там явно выбивается из общей сути данных. Все поля UserPermissions так или иначе говорят о возможностях и ограничениях пользователя по работе в организации. И только JobTitle… просто содержит какую-то информацию, которая никак к правам пользователя не относится. По идее, он если и нужен, то должен быть свойством самого пользователя, а не его прав. Разве нет?

Тут просто хотелось бы увидеть какое-то пояснение по поводу JobTitle. А, если окажется, что он в данных прав действительно лишний, то может его стоит вообще убрать, чтобы «не смущал»? Хотя мы вполне допускаем, что он тут остался из соображений какой-то совместимости с прежними версиями АПИ. 

**Третье. Ограничение возможностей по работе с пользователями**

В АПИ на текущий момент в плане работы с пользователями отсутствует:
1.	Получение информации по доступным и текущим сертификатам ЭЦП
2.	Получение информации по полномочиям подписания УПД и УКД
3.	Получение информации по эл. Почте пользователя и настройкам уведомлений на почту

Т.е. эта информация доступна при работе в Диадок на сайте и отсутствует в АПИ даже по чтению.

Тем более нет никакого функционала для изменения этих настроек с помощью АПИ.

**Предложение:**
Добавить в АПИ хотя бы возможность читать всю доступную информацию по пользователям. 
А в идеале – и возможность изменять эти данные с помощью АПИ.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev Добрый день

1. Не могли бы вы пояснить пункт про "2. Получение информации по полномочиям подписания УПД и УКД". Есть метод [Organization.GetExtendedSignerDetails2(Thumbprint, TitleType)](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetExtendedSignerDetails2) - он как раз  предназначен для получения полномочий подписанта. Есть какой-то сценарий для которого этот метод вам не подходит? Предполагаю, что может быть связано с невозможностью получения информации о привязке сертификатов к сотрудникам ящика и невозможности администрировать сотрудников


2. И про просмотр удалённых документов. Можете рассказать сценарий как используется папка документов  "Удалённые" у вас. Почему приходится восстанавливать документы? Как документы попадают в удалённые?

3. По остальным пунктам пока понятно

**Comment by JohnSergeev** [comment]
Добрый день. Вопросы увидел и понял. Отвечу обязательно.
Если не успею сегодня, то уже после праздников.

**Comment by JohnSergeev** [comment]
Добрый день.

Извиняюсь за задержку.
Ответы на вопросы:

**Вопрос №1**

Не могли бы вы пояснить пункт про "2. Получение информации по полномочиям подписания УПД и УКД". Есть метод Organization.GetExtendedSignerDetails2(Thumbprint, TitleType) - он как раз предназначен для получения полномочий подписанта. Есть какой-то сценарий для которого этот метод вам не подходит? Предполагаю, что может быть связано с невозможностью получения информации о привязке сертификатов к сотрудникам ящика и невозможности администрировать сотрудников

**Ответ:**
АПИ на текущий момент устроено несколько странно и одна, по сути, информация указывается в каких-то странных привязках.
На сайте Диадока информацию по полномочиям вроде как задаются для пользователей:
![изображение](https://user-images.githubusercontent.com/33707226/141258604-8f9cfad9-27c1-44de-8a0b-0e90fe6632e6.png)

По крайней мере такое ощущение складывается.
А данные, возвращаемые **Organization.GetExtendedSignerDetails2(Thumbprint, TitleType)** привязаны к  ЭЦП. Она возвращает параметры подписанта:
![изображение](https://user-images.githubusercontent.com/33707226/141258637-20e75cff-fcdc-4664-9dd2-4605b87430ad.png)

Понятно, что речь по факту идет об одном и том же.
Просто сейчас нет явной связи между информацией, возвращаемой АПИ по привязке к ЭЦП и информацией на сайте, явно выглядящей, как настройки в привязке к пользователям.

Т.е. тут скорее проблема не в том, что этой информации нет, а то, что:
1.	Непонятно, как информация о полномочиях по ЭЦП связана с информацией о полномочиях по пользователям. Оно вроде одно и то же. Но как связано – не понятно. По крайней мере явным образом. Или же это всё-таки не одно и тоже?
2.	Непонятно, как будет обновлена через вызов CreateSetExtendedSignerDetailsTask() информация о полномочиях, т.к. она тоже вызывается по привязке к ЭЦП. А как это с пользователями соотносится?
Скорее всего, по этому пункту ничего менять и дорабатывать не надо. Но вот как-то более понятно объяснить связь пользователей и ЭЦП было бы здорово. 

Плюс на сайте вроде есть механизмы по настройке привязки пользователей и ЭЦП. А вот в АПИ этого нет!

Ну и еще раз, уже в отрыве от основного ответа, напомню, что сильнее всего в этом блоке нам мешает отсутствие редактирования прав на доступ пользователей к подразделениям организаций через АПИ. Прочитать можем, проблему увидеть можем, а из учетной системы ее исправить - нет. Приходится лезть на сайт Диадока и там "ручками" все менять.

**Вопрос №2**
И про просмотр удалённых документов. Можете рассказать сценарий как используется папка документов "Удалённые" у вас. Почему приходится восстанавливать документы? Как документы попадают в удалённые?

**Ответ:**
_Как документы попадают в «Удаленные»?_ 
В основном это не принимаемые документы от контрагентов в роуминге, которые работают через операторов ЭДО, не поддерживающих аннулирование. Такие документы с обеих сторон (мы и отправитель документа) удаляются.

_Почему приходится восстанавливать документы?_
Просто на наших объемах чисто статистически бывают ошибки, когда, например, удаление выполнено ошибочно. Поэтому у нас пользователям (с определенными правами) предоставлена как возможность удаления документа, так и возможность восстановления его из удаленных.

_Можете рассказать сценарий как используется папка документов "Удалённые" у вас?_
Вот пока используется в указанных выше случаях. Тут, скорее, вопрос в том, что чтобы «поглазеть» на документы в папке «Удаленные» на сайте – можно в эту папку зайти. А через АПИ – никак. Поэтому есть потенциальная проблема – если мы как-то потеряли ID удаленного документа, то у нас, пользуясь АПИ, нет вообще никакой возможности даже понять, что такой документ вообще когда-то был. Его же нигде и никак через АПИ не видно! Можно только по ID его получить и в свойствах увидеть, что он удален. А если ID нет – то всё, приехали!

Т.е. отсутствие возможности заглянуть через АПИ в папку удаленных не мешает реальной работе – мы документы и их ID сохраняем в учетной системе. Поэтому доступ к удаленным документам у нас в общем-то есть. Но, скажем так, напрягает, что потенциально есть возможность при каком-то сбое потерять данные так, что потом через АПИ их вообще никак не вытащить! Вот хотелось бы чтобы была возможность их все-таки как-то достать – например, получив возможность видеть документы в папке «Удаленные». Плюс, доступ к этой папке потенциально облегчил бы администрирование ЭДО, позволив находить и видеть все документы из нашей учетной системы. А не только их часть, как сейчас.

**Comment by NinaKrivopusk** [comment]
Добрый день. Прошу дополнительно рассмотреть возможность доработки метода Апи по получению группы контрагентов, которую пользователи могут назначить в веб-версии Диадок. 
Потребность возникает при определении связки контрагентов Диадок и учетной системы.

![image](https://user-images.githubusercontent.com/97938487/149884944-9004f4dc-3572-4e95-a9bb-0c8b671463f4.png)

В документации описания методов, либо описания структуры Контрагента данные по группам не нашла.
Хоть по описанию что то похоже на структуру Department, но на данном примере контрагента, и эта структура пустая.
![image](https://user-images.githubusercontent.com/97938487/149885166-6390ebe0-e51b-4882-96ed-fe595c583849.png)
![image](https://user-images.githubusercontent.com/97938487/149885314-05432fea-5df9-47dd-85d0-84e8a1e08538.png)

**Comment by GilimkhanovDenis** [comment]
@NinaKrivopusk Добрый день

Сразу отвечу, что появление такой функциональности маловероятно, т.к. доработки нужны не только в компоненте. Можете данное пожелание на доработку через менеджера занести.

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev 
Разбил обращение на отдельные темы:
https://github.com/diadoc/diadocsdk-1c-docs/issues/828
https://github.com/diadoc/diadocsdk-1c-docs/issues/829
https://github.com/diadoc/diadocsdk-1c-docs/issues/830
https://github.com/diadoc/diadocsdk-1c-docs/issues/831
https://github.com/diadoc/diadocsdk-1c-docs/issues/832
