### ISSUE TITLE
Ошибки при обработке регламентного документооборота по СФ

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#710]
Добрый день.

Обнаружили, что у нас по 35 документам одного контрагента возникают ошибки в подписании извещений о получении счетов-фактур.

Сыпятся ошибки при работе регламентного документооборота по СФ, запускаемого через **GetReceiptGenerationProcess**.

**Все документы находятся в ящике организации:**
Организация:		«ДНС Ритейл»
ИНН:			2540167061
ID организации:	c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru                

**Контрагент:**
ООО "Компания БОНАНЗА", ИНН 7714659095, КПП 770101001.

**Документы с ошибками:**
Все - Исправления УПД (UniversalTransferDocumentRevision) со схемой utd820_05_01_02_hyphen.

**Список ID документов:**
afd2f835-5d13-4cfc-8ab7-d1d09a60d7fa877d8d83-9282-4cae-8a3a-3e460b28c023
2c1a9ea3-9db7-4768-81dd-24d8525c77f00e558df9-cbec-40a8-8f96-63fde789ce5d
d1ab8d93-e409-46de-a65e-e99b844a8ec660be7563-e912-4966-a815-f9ed9b2107c4
ee383f64-9ed3-4edf-838a-91ef661a7ad5e231be0a-2fbc-45ba-8804-ef4ee0b0c1b5
eb03f7f4-646b-417d-a2ae-e99fc6cc81455bd57d38-94ba-467c-b38e-5e0bc95fc36e
e1cba83f-928a-4289-a27d-3e2b9e4fd99210748f2f-fd5e-499d-a906-25fea68778ad
8f2ceb48-9b3c-4d02-afdb-ac801420ec014397d5f4-4efe-41c3-a20d-8c845ca49161
478d64df-da1a-40cf-975e-e94cadbfb7d66f76150f-90b3-4493-b49e-13bf8599bf63
9ad86e08-fa6a-4ff8-a90c-9cdde41fbdc0abcbd8cd-d8c1-4b2e-a5fb-b47d2c961154
4bcac4c3-16a9-46ed-8a72-5bbfa0301208fe266f8a-3580-4710-bdc8-81ab626fe9f3
ea3ca2a0-96ae-481d-bed7-6c2e3373f3da13d4a9eb-3e5f-4c15-8a4d-69802040cda7
0177f1b6-8793-49a2-8517-0a002354a0f91089ef73-2313-4383-bbef-3bdb748073b7
3bcc1422-f0cf-4d22-a1b2-b5b8eb1ff9bb7a1b0630-0d12-48af-988d-409af3016385
7f6d64ef-8c72-43bd-ba0f-433b43ef749ac111dd81-ea80-4860-8547-c6af53140880
f7e88e21-5fbc-4fc2-be73-8af03518bb1932bc5de8-c60a-440b-9170-900fb86abe5c
f27b4751-ea06-4050-a178-5cb3519aa98c04281f8f-3d4b-4574-8c45-e3e76c16cce9
7bc55350-d8ec-480f-afe5-1ae14c43691f3d38baba-e4c1-4710-b26c-7da5492a9c22
8af969dc-8086-4a4f-a282-0b9ccea8aa8d28971e02-35d1-4566-835f-31586653cd25
1a91e79b-5c32-472e-a131-f810dd8672bc7c596e38-7af9-4865-bd76-04dafce5d0e5
e4e664ef-6807-4e01-9c9d-90bc881a973d7fff46fb-304d-4823-9f24-477ef14d0589
55270812-6e17-4efd-9181-ae67332da1a75eb52ba3-49b3-4783-88d0-51f010e3d781
140dd69a-5d9c-41cb-97f3-f6b9295a01a826c3cedd-01ef-4ffc-85b7-bb67c5d0d48c
9c2ab019-ec1a-4da9-a198-574fa5b4e8562a040ec1-8160-4b8f-ac7a-6f359b04660b
51d837c1-7a19-442d-89ba-c5d11c54bcb968615958-a0fa-4439-9393-b45fdf29a883
6c2bafec-1b1d-49cd-a0db-181dc03fd3fb02eb0b1b-8a75-4a41-a8ff-dd3baf625e2d
1b106dc0-c222-4e53-b50c-e06b7084951109860f3a-d9bc-415e-b738-4fbcf834602b
3401b8ce-489e-4202-a97c-ee9c5e7d7f7775aabccf-92e5-4893-9799-8e0a22672c88
1b106dc0-c222-4e53-b50c-e06b7084951109860f3a-d9bc-415e-b738-4fbcf834602b
a15b1cea-2625-44ff-9b27-881aeaa2820ef11ce1a0-cd45-4e09-8a8b-ac477b83068a
224dea71-b585-4ec6-9275-bdb0ca7ec8b4086864ec-4b99-43f9-a536-9f6c24d89bb0
5acc227f-78ee-44f2-8690-3d3093694990fbb4f067-fca9-4378-8dd3-5ce913f7ce54
b788e303-955e-4e9a-b7e2-2bd0abf6985a22772e02-29c3-475f-8081-3db41164d0b8
01d0c542-66ba-4b47-9942-618ba67ad9644340a734-95b5-4e0d-b495-06f75e015db1
fde14bc6-768c-4f33-8088-e1e0980ef2a90c12476b-7ce5-46ab-8717-2ca499c400cc
4645165a-e0b9-41a4-b9a7-a52c3ae3652b4625cdb0-4b10-42d5-99b6-0d576aee4459

**Возникающие ошибки:**
По всем документам возникает одинаковая ошибка, указывающая на проблему в формате номера исправления. 

Примеры:

1
_HTTP error: Invalid generated title:
Metadata errors: 
Validation errors: Location: Line: 10, Position: 206, /Файл[1]/Документ[1]/СвИзвПолуч[1]/СведПолФайл[1]/ДанПолучДок[1]/@НомИспрСФ, Message: The 'НомИспрСФ' attribute is invalid - The value '33           ' is invalid according to its datatype 'String' - The actual length is greater than the MaxLength value._

2
_HTTP error: Invalid generated title:
Metadata errors: 
Validation errors: Location: Line: 10, Position: 206, /Файл[1]/Документ[1]/СвИзвПолуч[1]/СведПолФайл[1]/ДанПолучДок[1]/@НомИспрСФ, Message: The 'НомИспрСФ' attribute is invalid - The value '4           ' is invalid according to its datatype 'String' - The actual length is greater than the MaxLength value._

Маркдаун похоже срезает лишние пробелы, покажу то же самое картинкой:
![изображение](https://user-images.githubusercontent.com/33707226/140011177-d8ccff28-e3e6-410a-93f7-77dd591a2bdc.png)

Т.е. поставщик задал номера исправлений длиной в 10 символов с пробелами на конце строки номера. И так по всем этим документам.

**Вопросы:**
1.	В чем именно проблема – это поставщик реально неправильно оформил документы или же у вас в механизмах ДО СФ есть какая-то недоработка, показывающая ошибку там, в ситуации, когда проблемы на самом деле нет?

2.	Если это ошибка поставщика в формировании данных документов, то, что теперь с ними делать? Поставщику нужно аннулировать эти документы и отправить нам взамен исправленные версии? Или что?

**Дополнительно:**
A.	Если это ошибка в документе и поставщик его реально оформил, с ошибками, то почему вы такие документы передаете получателю, даете ему с ними работать, **даже даете ему эти документы нормально подписать**... и выдаете ошибку только при попытке подписания извещения? Это, кстати, больше всего удивляет - что подписать такой документ можно, а извещение о его получении - нет! Так точно должно быть?

B.	Если это реально ошибка в документе и такие документы никак и никаким образом всё равно в ЭДО Диадок нормально обработаны не будут (не получится подписать извещение о получении СФ), то имеем ли мы право сразу же при получении таких документов подавать их поставщику на аннулирование с формулировкой типа «Неверно задан номер исправления УПД»?

C.	А можно как-то чуть-чуть доработать сообщение об ошибке, чтобы вместо строки _«The actual length is greater than the MaxLength value»_ в ней было бы написано _«The actual length is greater than the MaxLength (<максимальное значение длины для данного поля/типа>) value»_? 

Т.е. чтобы в итоге получалось, например, так: _«The actual length is greater than the MaxLength (10) value»_.

Это было бы намного информативнее и не пришлось бы копаться в форматах XSD-схем документов на предмет выяснения – насколько именно было превышение - на 1 символ или сразу на 20.

3.	Если же это ваша ошибка в проверках ДО СФ, то тогда нужно просто подождать какого-то исправления ситуации с вашей стороны? Если так, то (хотя бы приблизительно) в какие сроки может быть исправлена проблема?

Спасибо.

**Comment by JohnSergeev** [comment]
Добрый день.
А можете хоть что-то ответить по заданным вопросам?

Проблема есть, а что с ней делать - непонятно.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev  Добрый день
Пока ждём решения со стороны сервиса

**Comment by JohnSergeev** [comment]
Добрый день.

А сейчас есть какая-то информация - это скорее что-то у вас внутри "не так" или это скорее поставщик просто неверно документы оформляет?

Хотя в любом случае странно почему часть действий над таким документом фиксирует ошибку в данных, а часть считает, что всё хорошо.

**Comment by DmitryModin** [comment]
Добрый день!

В рамках тикете https://jira.diadoc.ru/browse/DDSUPPORT-40545 поправили генерацию ИоП.
Документы с статусом требуется подписать извещение - отсутствуют

**Comment by DmitryModin** [comment]
> Добрый день!
> 
> Поправили генерацию ИоП. Документы с статусом требуется подписать извещение - отсутствуют

**Comment by DmitryModin** [comment]
Добрый день!

Поправили генерацию ИоП.
Документы с статусом требуется подписать извещение - отсутствуют

**Comment by JohnSergeev** [comment]
Добрый день.
Подтверждаю, на тек. момент по всем указанным в заявке документам проблема снята.

Спасибо.
