### ISSUE TITLE
Ошибка! 1С вылетает в исключение при обращении к GetDynamicContent("Buyer") для некоторых УКД

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#711]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: Тестовая организация №2918743
ИНН: 9629187430
КПП: 962901000
ID организации: 0d7430bf4a9d4acca06e3ba0720e3e91@diadoc.ru

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: COM x64 5.35.4.736.

При попытке получения данных некоторых ранее уже успешно получаемых рабочих документов мы обнаружили, что более не можем получить все данные этих документов.

### Все документы - исходящие УКД.

**Список ID найденных документов:**
971666a8-251b-49c2-b491-dc7534d2a1d159eca725-f90e-4de1-94be-24e0eb8b3b35
bc8b3a2e-9c81-464f-9b5d-0772810032e4fc2b595e-7c3e-472c-8a51-e25082d9f04a
28bec836-2c39-4a81-a3c3-133e3ce365ef4f5dcf7b-20fd-4a7a-9486-48c986c4c2a3
e77c4842-1e4e-4a24-b7cf-7a1fad150ea7ae3d06de-fc19-4dc9-830a-deb145348031
530bb425-94cb-4fbb-b751-1a404aa42e3eec4a688b-4a6b-4354-b560-e652dad10251
71e5bee7-c4a5-42d6-a3d1-c0a0b65097ae8e72653a-2b73-4671-b911-1789879205fd
acb31401-2dfc-4a4a-9196-35dc309b0f07ad2ff473-60bd-4136-aabd-acfaa1bcb3ea
e86199ee-8928-4f51-a361-0a8b5322e99f407c2736-97d4-4dcb-80a1-1012d8ef3c2d

**Документы относительно свежие:**
![изображение](https://user-images.githubusercontent.com/33707226/140683120-fe85f785-a70b-40ee-b28c-426d5b4d4810.png)

До какого-то момента документы нормально по АПИ получались. А именно - до момента их подписания получателями. Как только у этих документов появились данные подписи получателя (Buyer), то _"что-то пошло не так"_ и 1С стало при обращении к **GetDynamicContent("Buyer")** вылетать в исключение и возвращать ошибку вида:

_Ошибка при вызове метода контекста (GetDynamicContent): Произошла исключительная ситуация (DocumentBase.GetDynamicContent): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid content to parse for document type=[typeNamedId=UniversalCorrectionDocument, function=КСЧФДИС, version=ucd_05_01_03, titleIndex=1]_

Т.е. по этим документам стабильно не выполняется **GetDynamicContent("Buyer")**. 
При этом **GetDocumentByID()** и **GetDynamicContent("Seller")** выполняются без ошибок.

Странно то, что в 2021 у нас есть и другие исходящие УКД, КСЧФДИС, ucd_05_01_03 - И более ранние по сравнению с указанными, и более поздние. И с ними всё нормально! Никаких проблем при вызове **GetDynamicContent("Buyer")** не возникает. Пример: 0afaeeaf-90e4-4b1d-965e-c9cc8cdadef939c9bdbd-76d3-4394-8a31-79158aaeff0a.

Ранее (5 марта 2021 года, обращение #595) мы уже писали вам о подобной проблеме. Но тогда она касалась документов в **тестовых** ящиках. А в данном случае проблема касается **реальных рабочих документов**. То обращение по-прежнему висит, помеченное, как "Bug". Как мы понимаем, проблема до сих пор не определена и не решена.

### Большая просьба обратить внимание на проблему! И, если это возможно, исправить её.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

На данных документах причина ошибки стала более очевидной. В #595 она же. В ближайшем релизе починим

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev Добрый день
Попробуйте на [5.36.4](https://1c-docs.diadoc.ru/ru/latest/History/release_info/5_36_4.html)
Скачать компоненту можно [здесь](https://1c-docs.diadoc.ru/ru/latest/Downloads.html)

**Comment by JohnSergeev** [comment]
Спасибо!
Проверить сможем в ближайшие дни. Обязательно отпишусь.

**Comment by JohnSergeev** [comment]
Добрый день.
Проверили на версии x64 5.36.4.756.

Теперь по этим документам ошибка не возникает.

Спасибо!
