### ISSUE TITLE
Вопрос по "странной" ошибке при вызове GetOrganizationList() - "Too many registrations today. There were 3 attempts, but max allowed per day is 3"

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#712]
Добрый день.

**Общая информация для упрощения «разбора полётов»:**
Организация:		«ДНС Ритейл»
ИНН:			2540167061
КПП:			254301001
ID организации:	c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru		
ID участника ЭДО:	2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.35.4.736**.

Возник вопрос - периодически мы при обновлении в учетной системе данных по ЭЦП, организациям ЭДО и связанных с ними контрагентах получаем такую ошибку:

_Ошибка при вызове метода контекста (GetOrganizationList): Произошла исключительная ситуация (DiadocConnection.GetOrganizationList): ##100[Ошибка сервера Диадок]code:409, HTTP error: **Too many registrations today. There were 3 attempts, but max allowed per day is 3**_

Т.е. мы подключаемся к ЭДО по ЭЦП и, после установления соединения, пробуем получить список организаций по данному ЭЦП. И получаем такую ошибку. Причем по одному и тому же ЭЦП мы ее то получаем, то нет. Т.е. она какая-то случайная.

Также из текста ошибки вообще непонятно о какой регистрации идет речь и что это за ограничение в 3 попытки в день?

Как сделать так, чтобы эта ошибка не возникала и не мешала в работе?

Может ли это быть как-то связано с какими-то особенностями ЭЦП или особенностями настройки его использования на сайте Диадок? Если да, то в чем проблема и как ее можно исправить?

Спасибо.

**Comment by JohnSergeev** [comment]
Добрый день.

А вот оно у вас "в работе". А можно хотя бы какое-то пояснение, что это вообще за ошибка такая, почему она появляется и о чем сигнализирует?

А то совершенно непонятно какое отношение какое-то ограничение по количеству регистраций (?!) имеет к операции GetOrganizationList.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev Добрый день

Внутри GetOrganizationList вызывается [этот метод](https://api-docs.diadoc.ru/ru/latest/http/GetMyOrganizations.html) из HTTP API. у него есть параметр, отвечающий за регистрацию. компонента его никогда не передаёт и **при необходимости** должна срабатывать авторегистрация пользователя

Но для пользователя, у которого возникала ошибка, авторегистрация почему-то срабатывала и в той ситуации, когда, кажется, не должна.

Ошибка возникала, когда у пользователя был запрос на доступ в ящик организации (ID организации: c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru) (причина такого поведения пока не понятна - ждём ответа смежной команды)

В целом есть мысль отказаться от авторегистрации в этом методе и сделать отдельный метод для регистрации (администрирование пользователей примерно из той же области)

**Comment by NickZubashevskiy** [comment]
Добрый день!
Ошибка была исправлена в последнем [релизе](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_53_1.html)
