### ISSUE TITLE
Ошибка! ValueCollection.GetItem: Индекс выходит за диапазон коллекции

### ISSUE THREAD

**Issue by galiurust** [diadoc/diadocsdk-1c-docs#713]
Нетиповая конфигурация 1С7.7, близкая к бухгалтерии.
Адаптирую обработки версии 2.17.01
При двойном нажатии на документ счет-фактура в таблице значений главной обработки возникает ошибка:
ДД_Продавец     = дд_Документ.Sellers.Seller.getItem(0).OrganizationDetails; 
{\\SQL1C\1C_BASE\UGT_SQL\EXTFORMS\DIADOC_77_V_2_17_01\ОБРАБОТКАПРОСМОТРАУПД.ERT(10830)}: ValueCollection.GetItem: Индекс выходит за диапазон коллекции
Подскажите как устранить ошибку. Заранее спасибо.

**Comment by kuiv** [comment]
Для ответа на вопрос нужна конфигурация (1cv7.md) и "адаптированный" модуль.

Иначе получится "лечение по фотогарфии"

**Comment by galiurust** [comment]
> Для ответа на вопрос нужна конфигурация (1cv7.md) и "адаптированный" модуль.
> 
> Иначе получится "лечение по фотогарфии"
Набор измененных обработок
[https://drive.google.com/file/d/137an7eZ7OlXyiPoLt6ox6Tol357qQU8F/view?usp=sharing](url)
1cv7.MD
[https://drive.google.com/file/d/1y3o4kP6Ek_W7q9fVgfP1-cL9-s9cRM5u/view?usp=sharing](url)

**Comment by galiurust** [comment]
> Для ответа на вопрос нужна конфигурация (1cv7.md) и "адаптированный" модуль.
> 
> Иначе получится "лечение по фотогарфии"

Объясните мне простому 1с-нику эту выражение:
ДД_Продавец = дд_Документ.Sellers.Seller.getItem(0).OrganizationDetails;

Можно ли по-другому обратиться к продавцу?

**Comment by galiurust** [comment]
> Для ответа на вопрос нужна конфигурация (1cv7.md) и "адаптированный" модуль.
> 
> Иначе получится "лечение по фотогарфии"


Сколько по времени ждать ответа? Заранее спасибо

**Comment by kuiv** [comment]
Добрый день доступа по ссылке на MD нет. На доработанном вами модуле и типовой бухгалтерии ошибка не воспроизводится. Жду MD

**Comment by galiurust** [comment]
> Добрый день доступа по ссылке на MD нет. На доработанном вами модуле и типовой бухгалтерии ошибка не воспроизводится. Жду MD


Открыл доступ к MD

**Comment by kuiv** [comment]
Ваша конфигурация сильно отличается от типовых. Работа модуля на нетиповых конфигурациях не гарантирована. Доработку модуля под нетиповые конфигурации ведет отдел внедрения. За подробностями обратитесь в техподдержку 8 800 500 10 18

**Comment by galiurust** [comment]
Ответ получен. Спасибо
