### ISSUE TITLE
Отправка счета на оплату с использованием вн. компоненты

### ISSUE THREAD

**Issue by EvilRadiator** [diadoc/diadocsdk-1c-docs#714]
Использую последнюю версию ком компоненты.
Пытаюсь отправить двумя способами:
1) С помощью свойства объекта [DocumentToSend  ](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentToSend.html)- Content
 
До заполнения таблицы товаров не дошел, спотыкаюсь на таком сообщении: The element 'ProformaInvoiceSenderTitle' has incomplete content. List of possible elements expected: 'PersonalAccountInfo, ProformaInvoiceTable'.
 
Прошу дать описание обязательных реквизитов и коллекций свойства Content для документа вида "Счет на оплату покупателю"
Создаю документ из объекта SendTask следующим методом:  SendTask.AddDocument("ProformaInvoice", "default", "proformainvoice_01_01");
 
2) С помощью метода AddDocumentFromFile объекта DocumentToSend
.AddDocumentFromFile("ProformaInvoice", "default", "proformainvoice_01_01", [путь к файлу xml]) - система возвращает ошибку про неверный формат файла.
Xml файл сформирован по примеру с Вашего сайта - [ссылка на пример](https://www.diadoc.ru/Files/Modules/ElectronicDocument/3__xml.xml?t=1488556261)
 
Прошу дать корректную xml схему или пример для формирования файла.

**Comment by ButurlakinSemyon** [comment]
@EvilRadiator, добрый день!
Судя по ошибке у вас не заполнен элемент ProformaInvoiceSenderTitle.ProformaInvoiceTable и коллекция ProformaInvoiceSenderTitle.PersonalAccountInfo пустая.
Актуальную схему можно получить методом [Organization.SaveUserDataXSD](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#organization-saveuserdataxsd).

**Comment by EvilRadiator** [comment]
> @EvilRadiator, добрый день! Судя по ошибке у вас не заполнен элемент ProformaInvoiceSenderTitle.ProformaInvoiceTable и коллекция ProformaInvoiceSenderTitle.PersonalAccountInfo пустая. Актуальную схему можно получить методом [Organization.SaveUserDataXSD](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#organization-saveuserdataxsd).

Добрый день. 
С PersonalAccountInfo из схемы и из раскопок объекта вижу, что это коллекция объектов с двумя полями.
Но сущность объектов коллекции мне не ясна. Подскажите пожалуйста, где брать поля id и value для данной коллекции?

**Comment by ButurlakinSemyon** [comment]
@EvilRadiator, Это необязательная коллекция элементов ЛицСчетИнф (PersonalAccountInfo), в которых есть атрибуты Идентиф(Id) и Значен(Value).
Элемент PersonalAccountInfo в UserDataXsd является не обязательным, поэтому его можно не заполнять.

**Comment by EvilRadiator** [comment]
Добрый день.
Выше у Вас написано, что т.к. эта коллекция пустая выскакивает ошибка. В тексте ошибки также упоминается данная коллекция. Игнорировать это и не заполнять?

**Comment by ButurlakinSemyon** [comment]
@EvilRadiator, в ошибке перечислены поля, которые у вас не были заполнены - ProformaInvoiceTable и PersonalAccountInfo. Но PersonalAccountInfo является не обязательным. Поэтому в вашем случае можно:

- Заполнить оба элемента
- Заполнить только ProformaInvoiceTable.

**Comment by EvilRadiator** [comment]
> @EvilRadiator, в ошибке перечислены поля, которые у вас не были заполнены - ProformaInvoiceTable и PersonalAccountInfo. Но PersonalAccountInfo является не обязательным. Поэтому в вашем случае можно:
> 
> * Заполнить оба элемента
> * Заполнить только ProformaInvoiceTable.

Пробовал рефлектором посмотреть методы ProformaInvoiceTable, на предмет метода добавления элемента в коллекцию - обнаружил, что GetMethodsNames() возвращает коллекцию свойств объекта, а не методов.
Подскажите имя метода для добавления элемента типа ProformaInvoiceItem в коллекцию ProformaInvoiceTable

**Comment by ButurlakinSemyon** [comment]
@EvilRadiator, эта ошибка лечилась в 5.36.4.
