### ISSUE TITLE
Неверное формирование поля FileName при отправке UPD

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#715]
Не знаю чья конкретно проблема, компоненты или сервера Diadoc, но на всякий случай пишу и тут, параллельно с обращением в чат службы поддержки.
Есть контрагент, который подключен к Диадок, а так же к другому провайдеры ЭДО. Мы подключены к Диадоку. Документы идут от нашего ящика в Диадоке на ящик клиента у другого провайдера (настроен роуминг).
Работа в нашей системе идет в 1С 7.7 через вашу компоненту. Отправляем документы УПД.
Проблема в неверном формировании поля FileName.
Если отправить документ с установленным флагом IsDraft, а потом из папки "Черновики" через web-интерфейс подписать и отправить документ, то все уходит нормально.
Если без установки этого флага попробовать сразу отправить документ, то при формировании поля FileName используется ID ящика клиента в Диадоке. Это приводит к ошибки со стороны другого провайдера.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Похоже, у вас та же ситуация, что в https://github.com/diadoc/diadocsdk-1c-docs/issues/717  - нужно более однозначно указать продавца

**Comment by dorexpro** [comment]
Да, проблема та же самая. Ошибка именно в том, что берется из списка контрагентов по ИНН-КПП первый попавшийся для формирования имени файла, а поле Buyer.OrganizationDetails.FnsParticipantId игнорируется. Хотя внутри файла id контрагента устанавливается правильно.
Ранее Калуга Астрал не контролировала корректность имени файла, хотя в формате обмена ФНС четко прописывает этот момент.
Прошу исправить как можно скорей. Документы зависли.

**Comment by GilimkhanovDenis** [comment]
Можете указать какие именно поля заполняются в Buyer ?

**Comment by dorexpro** [comment]
Вот код заполнения:

```
	Задача = Организация.CreatePackageSendTask2();
	Задача.CounterAgentId	= ИдКонтрагента;
...
	Buyer = СодержаниеСчетаФактуры.Buyers.AddBuyer();
	Если КомпанияЭДО.Контрагент.ФормаСобственности.ЭтоИП = 1 Тогда
		Buyer.OrganizationDetails.OrgType = "2";
	Иначе
		Buyer.OrganizationDetails.OrgType = "1";
	КонецЕсли;
	Buyer.OrganizationDetails.OrgName	= СокрЛП(сзДанные.Получить("Покупатель"));
	Buyer.OrganizationDetails.INN		= СокрЛП(сзДанные.Получить("ИННКПППокупателя_ИНН"));
	Buyer.OrganizationDetails.KPP		= СокрЛП(сзДанные.Получить("ИННКПППокупателя_КПП"));
	Buyer.OrganizationDetails.LegalEntityId	= "LegalEntity";
	
	Buyer.OrganizationDetails.FnsParticipantId = ИдКонтрагента;
	
	BuyerForeignAddress = Buyer.OrganizationDetails.Address.ForeignAddress;
	
	BuyerForeignAddress.Country	= "643";
	BuyerForeignAddress.Address	= сзДанные.Получить("АдресПокупателя");

```
Или нужны именно значения, которыми заполняются поля?

**Comment by GilimkhanovDenis** [comment]
Вижу здесь немного странный код:

```
Задача.CounterAgentId	= ИдКонтрагента;
....
Buyer.OrganizationDetails.FnsParticipantId = ИдКонтрагента;
```

`Задача.CounterAgentId` - сюда должно записаться значение идентификтаора ящика. Это либо строка формата GUID, либо строка вида "ГуидБездефисов@diadoc.ru" (зависит от того, используете Counteragent.Guid или Counteragent.Id)

`Buyer.OrganizationDetails.FnsParticipantId`, а сюда должен попадать не идентификатор ящика, а идентификатор участника ЭДО - строка, начинающаяся на "2BM" или для Калуги Астрал "2ae" (поле Counteragent.FnsParticipantId)

То есть это разные идентификаторы. В приведённом коде используется один и тот же идентификатор

**Comment by dorexpro** [comment]
Понятно. Это я ошибся с заполнением FnsParticipantId, а сервер на это не отреагировал, просто взял значение на основе ИНН. Сейчас попробую переделать на верное значение.

**Comment by dorexpro** [comment]
Прошел документ. Спасибо. Сейчас все остальные отправлю.
