### ISSUE TITLE
Вопрос по связке 1С и Диадок

### ISSUE THREAD

**Issue by sbrros** [diadoc/diadocsdk-1c-docs#716]
В документации ДИАДОК, примеры на C# в самом низу указанных страниц
 
http://api-docs.diadoc.ru/ru/latest/howto/example_authorization.html
http://api-docs.diadoc.ru/ru/latest/howto/example_send_invoice.html
 
показано как имея файл «.cer» можно произвести авторизацию в самом Диадок, а в дальнейшем и подписывать документы (в случае необходимости).
 
Есть какой-то аналогичный вариант работы из среды 1С? В модуле для 1С на странице авторизации появляются только те сертификаты, которые установлены на локальной машине, в нашем же случае хотелось бы реализовать несколько иной алгоритм.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Компонента использует для авторизации те сертификаты, которые установлены в хранилище "Личные". Какого-то низкоуровневого интерфейса для работы с сертификатами компонента не предоставляет и подобных планов у нас не было.
Подписание будет тем сертификатом, по которому авторизовались, кроме случая отправки тестовых документов - там будет использован специальный тестовый сертификат сервера Диадок.

Какой сценарий вы хотите реализовать?

**Comment by sbrros** [comment]
У нас сертификаты пользователей хранятся в одном месте, т.к. в связи с текучкой кадров так проще контролировать. Далее в 1С хотелось бы сделать привязку пользователя 1С с его сертификатом и в зависимости от пользователя подписывать документы его сертификатом.

**Comment by GilimkhanovDenis** [comment]
Под единым местом хранения что подразумевается?

в каком виде хранятся сертификаты ?

**Comment by sbrros** [comment]
Мы сейчас так раз думаем как их хранить, в зависимости от возможностей работы с сертификатами. На данный момент есть файлы ".cer" в каталоге. Закрытая часть ключа на флешке, но думаем куда-то их разместить в единое хранилище тоже, либо в реестр (но все в одном месте) либо еще каким-то образом хранить и далее пользователь акцептует операцию в 1С, программа подписывает документ от имени пользователя.

**Comment by GilimkhanovDenis** [comment]
Пока не очень понятно чем хранение контейнеров в реестре/на флешке/на рутокене противоречит тому, что сертификаты (.cer) будут установлены в хранилище "Личные". Если не хочется под каждого пользователя устанавливать сертификаты, то можно установить в "Личные" компьютера

**Comment by sbrros** [comment]
Денис, такой вопрос, если нам нужно чтобы из 1С (программно) мы могли обращаться к любому из этих сертификатов, то сертификаты должны быть установлены на сервере приложений 1С? или как 1С до них будет достукиваться?

**Comment by GilimkhanovDenis** [comment]
Если компонента инициализируется @НаСервере, то сертификаты должны быть доступны серверу приложений. Если @НаКлиенте - клиенту

Т.е. сертификаты должны быть установлены там, где будут исполняться вызовы компоненты.

**Comment by sbrros** [comment]
Спасибо, будем пробовать. По результатам отпишусь.

**Comment by sbrros** [comment]
Денис, добрый день.
Воспользовались Вашим советом (спасибо), сертификаты на сервере получаем, переписываем обработку для работы с серверной ЭЦП (из реестра), столкнулись со следующей проблемой:
Вызов GetDocumentsAsync , а в последствии попробовали его заменить на GetDocuments (и результат примерно одинаковый) достаточно часто приводит к прекращению работы службы "Агент сервера 1С предприятия", просто теряется связь всех клиентов с сервером, службу нельзя ни остановить, ни перестартовать, помогает только перезагрузка сервера.
При этом иногда методы отрабатывают без проблем и удается получать список документов.  С чем может быть проблема?

**Comment by sbrros** [comment]
AsyncTask=	DocumentsTask.GetDocumentsAsync();    
AsyncTask=	DocumentsTask.GetDocuments();
Вот эти строки вызывают проблему

**Comment by GilimkhanovDenis** [comment]
Добрый день
Предлагаю новый вопрос оформить в отдельным issue
Если вызов метода вызывает APPCRASH, то нужен будет дамп процесса в момент возникновения ошибки. Это можно сделать, например, с помощью [procdump -e -ma -w <process_name>](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump)

**Comment by sbrros** [comment]
Создал новый Issue https://github.com/diadoc/diadocsdk-1c-docs/issues/736.
