### ISSUE TITLE
Ошибка доставки документа через роуминг

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#717]
Здравствуйте.
Возникла проблема с несколькими исходящими УПД в адрес контрагентов, которые работают с оператором Калуга Астрал. Для работы с Диадоком используем AddIn компоненту v5.36.3.747 x86 для 1С. Для отправки документов стандартный вариант:

SendTask = Organization.CreatePackageSendTask2();
SendTask.CounterAgentId = Counteragent.Guid;

Далее всё стандартно заполняется и успешно отправляется в Диадок. В вэб интерфейсе Диадока документ появляется, но со статусом "Ошибка доставки документа через роуминг". До недавнего времени всё работало. Что произошло, совершенно не понятно.

Идентификатор документа с ошибкой: ON_NSCHFDOPPR_2BM-040300004925--2014103011465505567290000000_2BM-2223034582-2012052808121872222630000000000_20211110_dca368bf-b7d4-45b4-b35b-58e371b68a79

Помогите решить проблему!!!

**Comment by GilimkhanovDenis** [comment]
Добрый день

`SendTask.CounterAgentId = Counteragent.Guid;`
задаёт только ящик получателя документа и никак не влияет на контент документа. Информация о получателе для данного типа документа будет взята из первого элемента коллекции покупателей. Проверьте информацию, указанную там. Если задаёте только ИНН-КПП, то при наличии нероумингового ящика контрагента информация будет взята из него

**Comment by evgen421** [comment]
Здравствуйте GilimkhanovDenis.
Я использую следующий алгоритм:

API=СоздатьОбъект("AddIn.DiadocInvoiceAPI");
DiadocApi = API.CreateObject();	
DiadocApi.ApiClientId = "API-Kitezh-d540c719-baf1-4751-a7fc-6603ed65ceae";
DiadocApi.ServerUrl = "https://diadoc-api.kontur.ru:443";
	Organization=DiadocApi.CreateConnectionByCertificate("1dfefa7b31a027b473da3d5467235ceeeeb62a57").GetOrganizationById("f9f8b47e-bc55-4960-9ca2-8b6908bfe9df");

У контрагента, которому необходимо отправить документ, два ящика, один Диадок, другой Калуга Астрал, на который нам необходимо отправить документ.
Далее пытаюсь получить данные о ящиках контрагента:

CounteragentList=Organization.GetCounteragentListByInnKpp(040300004925);
Для К=0 По CounteragentList.count-1 Цикл
    Guid=CounteragentList.GetItem(К).Guid;
    FnsParticipantId=CounteragentList.GetItem(К).FnsParticipantId;
КонецЦикла;

Для первого ящика получаем
Guid=3e44dbc8-d2e8-47fb-aefa-8cf596f3d2d3
FnsParticipantId=2AECE313D3A-00F7-4AFC-AB68-17FA24B763BA

Для второго ящика:
Guid=e92b49fa-e540-42e2-92cb-c682b30f6198
FnsParticipantId=2BM-040300004925--2014103011465505567290000000

Видим, что у первого ящика в FnsParticipantId первые три символа 2AE, значит это Калуга Астрал  и 3e44dbc8-d2e8-47fb-aefa-8cf596f3d2d3 является идентификатором роумингового ящика контрагента.

Тогда:
SendTask = Organization.CreatePackageSendTask2();
SendTask.CounterAgentId = 3e44dbc8-d2e8-47fb-aefa-8cf596f3d2d3;

Диадок успешно принимает документ от нас, но контрагенту не отправляет. Самое странное, что до этого всё работало.

**Comment by GilimkhanovDenis** [comment]
Повторюсь.
Вам нужно смотреть как заполняется покупатель (Buyer) в контенте отправляемого документа. В смежном https://github.com/diadoc/diadocsdk-1c-docs/issues/715 сценарий похож на ваш

**Comment by evgen421** [comment]
Исправил, заработало. Большое спасибо!

**Comment by PFight** [comment]
@GilimkhanovDenis добрый день, подскажите, пожалуйста, к чему приводит ошибка и как исправляет ее Ваша рекомендация на уровне протокола обмена с Диадок? Это проблема в самом xml-документе, или в сообщении? Какие именно поля неправильно заполнены? Столкнулись с похоже ошибкой в другой системе....

**Comment by GilimkhanovDenis** [comment]
@PFight  Которая именно ошибка? Если  `Ошибка доставки документа через роуминг`, то она означает. что документ не доставлен до контрагента, который работает не в Диадок, а у другого оператора ЭДО

Конкретно в этом обращении проблема была с тем, что в XML неправильно заполнялся тэг ИдПол. Есть более [свежее обращение](https://github.com/diadoc/diadocsdk-1c-docs/issues/826), с другой ошибкой, но теми же корнями, что в данном - там ИдПол совсем не заполнялся и документ не был принят ещё на этапе загрузки в Диадок

**Comment by PFight** [comment]
@GilimkhanovDenis благодарю, попробуем покопать в эту сторону.

**Comment by PFight** [comment]
Через техподдержку Калуга Астрал выяснил, что "Ошибка заключается в том, что в имени документа, в строке получатель указан идентификатор оператора Контур Диадок, а документ вы направляете клиенту оператора Калуга Астрал."
