### ISSUE TITLE
Не могу найти документ по id

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#718]
Добрый день! После отправки документа в Диадок в 1с зафиксировался следующий id de2cb38a-68d8-4495-8e48-debad1e87fba8b6b5d46-c243-47b9-86a5-f93ea9b940c3   но в Диадоке не могу найти такой. Если возможно, подскажите откуда он?  Вот еще один 15be126c-ee3d-44e5-82f8-848feb35459dd955df83-1de8-4869-8177-fa920a255293

**Comment by GuninaY** [comment]
Нашла его через Organization.GetDocumentById, он числится удален. Такие нельзя посмотреть через в личном кабинете?

**Comment by happydeadman** [comment]
Добрый день!

Если речь про веб-интерфейс по ссылке https://diadoc.kontur.ru/, то удаленные документы находятся на соответствующей вкладке 
![image](https://user-images.githubusercontent.com/59083178/143229829-666dfdfc-01b2-4635-82e7-127dd21f573a.png)
