### ISSUE TITLE
Отправка УПД через API без подписания

### ISSUE THREAD

**Issue by Barmolei3** [diadoc/diadocsdk-1c-docs#719]
Здравствуйте! 
В документации 1С Diadoc приведён пример отправки документа УПД с контентом, взятым из файла. Всё отлично работает документ уходит и автоматически подписывается. К сожалению не нашёл в документации описания такого же процесса, но без подписания. Подскажите, пжл, метод или ссылку на документацию. Ниже используемый код.

SendTask = Organization.CreatePackageSendTask2();
Second_DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01", "D:\temp\68afe640-4217-11ec-91e4-003048f2575e.xml");
Second_DocumentToSend.Comment = "Это УПД с контентом, загруженным из файла";
ОтправленныеДокументы = SendTask.Send();

**Comment by dorexpro** [comment]
Если установить SendTask.IsDraft = 1, то документ отправится в папку "Черновики" без отправки контрагенту и без подписания. Это случаем не то, что требуется или "ой!"?

**Comment by Barmolei3** [comment]
Спасибо)
