### ISSUE TITLE
Ошибка при вызове метода CreateSendTaskFromFile

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#72]
Ошибка при вызове метода контекста (CreateSendTaskFromFile): Произошла исключительная ситуация (Box.CreateSendTaskFromFile): Message has no attachments
DocumentType = "ReconciliationAct" и  "NonformilizedDocumentContent", файлы в формате *.pdf. Пробовали метод CreateSendTaskFromFileRaw - та же ошибка.

**Comment by volodkindv** [comment]
Ошибка еще актуальна?
Если да, то укажите, пожалуйста, версию компоненты и приложите пример кода.
Там легко ошибиться в порядке следования параметров.
И проверьте, доступен ли файл на той машине, откуда вызывается метод (это актуально для 1С на управляемых формах - иногда файл формируется на сервере, а отправка происходит с клиента).

**Comment by jakeqwert** [comment]
На новой версии компоненты все прошло

**Comment by jakeqwert** [comment]
Формы обычные, толстый клиент был
