### ISSUE TITLE
Передача подписанного документа

### ISSUE THREAD

**Issue by Daria78456** [diadoc/diadocsdk-1c-docs#721]
Подскажите  - есть такая задача. Мы хотим подписывать документы у себя в 1С сертификатами непосредственного установленными из 1С, типовыми средствами программы, я затем передавать эти данные в Диадок нашему контрагенту для подписания. Нужно чтобы при передачи ему уходили наши подписи из 1С. Какими методами это возможно реализовать?

**Comment by GilimkhanovDenis** [comment]
Добрый день.

Через компоненту такой возможности нет и не планируется - компонента сама подпишет документ тем сертификатом, по которому авторизовались.
Для вашего сценария рекомендую обратиться к возможностям [HTTP API - метод PostMessage](https://api-docs.diadoc.ru/ru/latest/http/PostMessage.html)
