### ISSUE TITLE
Процедура ДополнитьКонтентСтрокиДокументаСлужебнойИнформацией(Item, СтрокаДанных)

### ISSUE THREAD

**Issue by JuliaShapir** [diadoc/diadocsdk-1c-docs#723]
Мне нужно в УКД вывести ГТД - вот в этой прцедуре видно, что в служебную информацию ГТД попала, но на печати ее нет.

**Comment by JuliaShapir** [comment]
СлужебнаяИнформация = Новый Структура;
			СлужебнаяИнформация.Вставить("Номенклатура");
			СлужебнаяИнформация.Вставить("Характеристика");
			СлужебнаяИнформация.Вставить("Серия");
			СлужебнаяИнформация.Вставить("НомерГТД");
			СлужебнаяИнформация.Вставить("ЕдиницаИзмерения");
			СлужебнаяИнформация.Вставить("ЕдиницаИзмеренияДоИзменения");
			СлужебнаяИнформация.Вставить("СтранаПроисхождения");
			СлужебнаяИнформация.Вставить("ДанныеПрослеживаемости");
			СлужебнаяИнформация.Вставить("ПрослеживаемыйТовар");
			СлужебнаяИнформация.Вставить("ДокументОтгрузки");
			
			ЗаполнитьЗначенияСвойств(СлужебнаяИнформация, СтрокаДанных);

**Comment by happydeadman** [comment]
Добрый день!

Заполнение ГТД у УКД не предусмотрено нормативно, поэтому заполнить эту информацию нет возможности.

Вашему клиенту нужно напомнить, что печатная форма электронного документа согласно письму [Письмо ФНС РФ от 21.10.2013 N ММВ-20-3/96@](https://normativ.kontur.ru/document?moduleId=8&documentId=220334) "носит рекомендательный характер. Неприменение данной формы для оформления фактов хозяйственной жизни не может быть основанием для отказа в учете этих фактов хозяйственной жизни в целях налогообложения."
