### ISSUE TITLE
Проблема перехода на более свежую компоненту

### ISSUE THREAD

**Issue by darujo** [diadoc/diadocsdk-1c-docs#725]
Добрый день.
Подскажите пожалуйста столкнулись с проблемой подключения к серверу.
Подключение производим вот  как
DiadocApi:ApiClientId = ..
mDiadocApi:ServerUrl =..
DiadocAPI:CreateConnectionByLogin(login,pwd)
на библиотеке v5.29 x86 v5.31 x86 все работает
а на библиотеке v5.34 x86 v5.35 x86 v5.36 x86 возникает ошибка
Error occurred while accessing component property/method: CreateConnectionByLogin.
WIN32[0x00002F8F]WinHttpSendRequest
Error code: 0x80020009 ConectByLogin c:\th\td15\rc\utl\proc-diadoc.r (5890)
данная проблема проблема возникает не везде.  С чем может быть связана данная проблема?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Ошибка ERROR_WINHTTP_SECURE_FAILURE (0x00002F8F) означает, что соединение не защищено (например, кто-то расшифровывает трафик). 

Если уверены, что это запланировано, то можете отключить проверку SSL сертификатов [DiadocAPI](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html).VerifySslCertificate
