### ISSUE TITLE
Ошибка при попытке залогиниться по сертификату

### ISSUE THREAD

**Issue by Igora0** [diadoc/diadocsdk-1c-docs#726]
Здравствуйте. Такой код, выполняется на сервере:

        DiadocApi 				= Новый COMОбъект("Diadoc.Api.InvoiceApi"); // тут ОК
	DiadocApi.ApiClientId 	= "******"; // тут ОК
	DiadocApi.ServerUrl 	= "https://diadoc-api.kontur.ru:443"; 
	Certificates = DiadocApi.GetPersonalCertificates(); // Ок
	ОтпечатокСертификата = Certificates.GetItem(0).Thumbprint; 
	DiadocConnection = DiadocApi.CreateConnectionByCertificate(ОтпечатокСертификата);

Получаю ошибку:
"Произошла исключительная ситуация (DiadocApiInvoiceApi.CreateConnectionByCertificate): ##300[Ошибка CryptoPro]Ошибка при расшифровке данных [2148073506:Поставщику не удалось выполнить действие, так как запрошено выполнение в автоматическом контексте.]"

Что не так, подскажите.

**Comment by volodkindv** [comment]
Здравствуйте. Вероятнее всего, недоступен контейнер закрытого ключа или на него установлен пин-код.
http://www.cryptopro.ru/forum2/default.aspx?g=posts&t=17368
Ошибку можно исследовать средствами КриптоПро.
