### ISSUE TITLE
Отправить файл сформированный в 1С в Контур

### ISSUE THREAD

**Issue by asvlasov** [diadoc/diadocsdk-1c-docs#727]
Здравствуйте.

Работаю с 1С. Сформировал файл в формате XML. Надо отправить его в контур.
В API есть функция, которая отправляет файл. Я ей воспользовался. Но она одновременно подписывает.
Как отправить файл в контур без подписи, чтобы другой сотрудник просмотрел его и мог подписать?
 
		Third_DocumentToSend = SendTask.AddDocumentFromFile("Nonformalized", "default", "v1", ИмяФайла);
	    Third_DocumentToSend.Comment = "Это неформализованный документ";
	    MetaDataItem = Third_DocumentToSend.AddMetadata();
	    MetaDataItem.Key   = "FileName";
	    MetaDataItem.Value = "Имя Файла Для Передачи.xml";	
		Иначе
		//Second_DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01", "E:\Андрей\Moй УПД.xml");
			Если ФайлПередачи = Неопределено Тогда
			Second_DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01", ИмяФайла);
			Иначе
			Second_DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01", ФайлПередачи);
			КонецЕсли;
		Second_DocumentToSend.Comment = "Это УПД с контентом, загруженным из файла";	
		КонецЕсли;

**Comment by GilimkhanovDenis** [comment]
Добрый день
у [PackageSendTask2 ](https://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html) есть два флага, которые могут влияет на способ отправки:
IsDraft и DelaySend - первый отправит документ в черновики, второй - в исходящие без отправки.

Предположу, что вас интересует второй из флагов

**Comment by asvlasov** [comment]
Здравствуйте.
 
Спасибо.
А как передать данный флаг? Можете привести пример?
 
С уважением Власов А.С.
  
>Понедельник, 24 января 2022, 16:53 +03:00 от Гилимханов Денис ***@***.***>:
> 
> 
>Добрый день
>у  PackageSendTask2  есть два флага, которые могут влияет на способ отправки:
>IsDraft и DelaySend - первый отправит документ в черновики, второй - в исходящие без отправки.
>Предположу, что вас интересует второй из флагов
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/727/1020123618 @ github . com> 
 
 
--
Андрей Власов

**Comment by GilimkhanovDenis** [comment]
> Здравствуйте.   Спасибо. А как передать данный флаг? Можете привести пример?   С уважением Власов А.С.  
> Понедельник, 24 января 2022, 16:53 +03:00 от Гилимханов Денис ***@***.***>:     Добрый день у PackageSendTask2 есть два флага, которые могут влияет на способ отправки: IsDraft и DelaySend - первый отправит документ в черновики, второй - в исходящие без отправки. Предположу, что вас интересует второй из флагов — Reply to this email directly, view it on GitHub , or unsubscribe . Triage notifications on the go with GitHub Mobile for iOS or Android . You are receiving this because you authored the thread. Message ID: <diadoc/diadocsdk-1c-docs/issues/727/1020123618 @ github . com>
>     -- Андрей Власов

Не понял ваш вопрос. Поля задаются точно так же как и в других объектах

**Comment by asvlasov** [comment]
Здравствуйте.
 
В описании нашёл пример, который использовал. Можете как то применительно к данному примеру 
подсказать как будет выглядеть синтаксис, чтобы передать флаг «IsDraft»?
 

  
>Вторник, 25 января 2022, 20:19 +03:00 от Гилимханов Денис ***@***.***>:
> 
> 
>Здравствуйте.   Спасибо. А как передать данный флаг? Можете привести пример?   С уважением Власов А.С.  
>Понедельник, 24 января 2022, 16:53 +03:00 от Гилимханов Денис  @ .***>:     Добрый день у PackageSendTask2 есть два флага, которые могут влияет на способ отправки: IsDraft и DelaySend - первый отправит документ в черновики, второй - в исходящие без отправки. Предположу, что вас интересует второй из флагов — Reply to this email directly, view it on GitHub , or unsubscribe . Triage notifications on the go with GitHub Mobile for iOS or Android . You are receiving this because you authored the thread. Message ID: < /issues/727 /1020123618 @ github . com>
>    -- Андрей Власов
Не понял ваш вопрос. Поля задаются точно так же как и в других объектах
—
Reply to this email directly,  view it on GitHub , or  unsubscribe .
Triage notifications on the go with GitHub Mobile for  iOS or  Android .
You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/727/1021425056 @ github . com>  
 
--
Андрей Власов

**Comment by GilimkhanovDenis** [comment]
Добрый день

Например, так:

```
...
dd_SendTask = dd_Organization.CreatePackageSendTask2();
dd_SendTask.IsDraft = True;
dd_DocumentToSend = dd_SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_02_hyphen", ИмяФайла);
...
```

**Comment by asvlasov** [comment]
Спасибо большое.
 
С уважением Власов А.С.
  
>Понедельник, 31 января 2022, 12:57 +03:00 от Гилимханов Денис ***@***.***>:
> 
> 
>Добрый день
>Например, так:
>...
>
>dd_SendTask = dd_Organization.CreatePackageSendTask2();
>
>dd_SendTask.IsDraft = True;
>
>dd_DocumentToSend = dd_SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_02_hyphen", ИмяФайла);
>
>...
>
>
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/727/1025558753 @ github . com> 
 
 
--
Андрей Власов

**Comment by asvlasov** [comment]
Здравствуйте.
 
Ещё раз спасибо.
 
А можете подсказать по процедуре передачи на согласование или на подпись?
Мне не понятна ситуация, что передаётся на согласование или подпись уже существующий в Диадок документ.
Я то полагал, что источником должен быть XML файл, но тогда как создать документ в Диадоке,
чтобы он был не подписан и при этом можно было бы получить его идентификатор?
 
Вот  вырезка из описания этого метода
Как работать с согласованием и передачей   на   подпись
Как запрашивать согласование и передавать   на   подпись   документ
Для отправки документа   на   подпись   или согласование пред на з на чен объект   ResolutionRequestTask , который можно создать методами   Document.CreateResolutionRequestTask()   и   DocumentPackage.CreateResolutionRequestTask()
Процедура ОтправитьДокументНаПодписьВПодразделение(ИдентификаторДокумента, ИдентификаторПодразделения)

    Document = Organization.GetDocumentById(ИдентификаторДокумента)

    ResolutionRequestTask = Document.CreateResolutionRequestTask();

    // ResolutionRequestType определяет будет ли это запрос на согласование или передача на подпись
    // В данном случае - передача на подпись
    ResolutionRequestTask.ResolutionRequestType = "SignatureRequest";
    ResolutionRequestTask.TargetDepartmentId    = ИдентификаторПодразделения;

    ResolutionRequestTask.Send();

КонецПроцедуры 
>Понедельник, 31 января 2022, 12:57 +03:00 от Гилимханов Денис ***@***.***>:
> 
> 
>Добрый день
>Например, так:
>...
>
>dd_SendTask = dd_Organization.CreatePackageSendTask2();
>
>dd_SendTask.IsDraft = True;
>
>dd_DocumentToSend = dd_SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_02_hyphen", ИмяФайла);
>
>...
>
>
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/727/1025558753 @ github . com>
 
 
--
Андрей Власов

**Comment by GilimkhanovDenis** [comment]
Добрый день

Документ(ы) и его(их) идентификатор(ы) можно получить как результат метода [PackageSendTask2.Send()](https://1c-docs.diadoc.ru/ru/latest/ComObjects/PackageSendTask2.html#PackageSendtTask2.Send) или [DocumentsTask.GetDocuments](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentsTask.html#DocumentsTask.GetDocuments) или многих других методов, возвращающих DocumentBase или коллекцию DocumentBase

**Comment by GilimkhanovDenis** [comment]
Для отправки документа в исходящие без подписи укажите флаг DelaySend в PackageSendTask2

**Comment by asvlasov** [comment]
Спасибо большое.
А можно ещё вопрос?
Я использую сертификат для подключения к API библиотеке. 
Синтаксис следующий:
DiadocConnection = MyDiadocApi.CreateConnectionByCertificate(ТекСертификат);
А возможно подключение к API библиотеке по логину и паролю?
 
С уважением Власов А.С.  
>Вторник, 1 февраля 2022, 11:43 +03:00 от Гилимханов Денис ***@***.***>:
> 
> 
>Для отправки документа в исходящие без подписи укажите флаг DelaySend в PackageSendTask2
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/727/1026598629 @ github . com> 
 
 
--
Андрей Власов

**Comment by kulakovskaya** [comment]
Добрый день! Для авторизации можно использовать логин и пароль. Подробнее в [документации](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Connection.html).

**Comment by asvlasov** [comment]
Спасибо.

  
>Пятница, 4 марта 2022, 11:50 +03:00 от kulakovskaya ***@***.***>:
> 
> 
>Добрый день! Для авторизации можно использовать логин и пароль. Подробнее в  документации .
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/727/1058962166 @ github . com> 
 
 
--
Андрей Власов

**Comment by asvlasov** [comment]
Спасибо. Я разобрался.

  
>Пятница, 4 марта 2022, 11:50 +03:00 от kulakovskaya ***@***.***>:
> 
> 
>Добрый день! Для авторизации можно использовать логин и пароль. Подробнее в  документации .
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/727/1058962166 @ github . com> 
 
 
--
Андрей Власов

**Comment by asvlasov** [comment]
Здравствуйте.
 
Отправляю УПД методом
Second_DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01", ФайлПередачи);
 
И когда я делаю это в цикле по списку документов, то они собираются в один пакет.
При чём по нарастающей.
А как отключить передачу пакетного режима?
 
С уважением Власов А.С.
  
>Пятница, 4 марта 2022, 11:50 +03:00 от kulakovskaya ***@***.***>:
> 
> 
>Добрый день! Для авторизации можно использовать логин и пароль. Подробнее в  документации .
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/727/1058962166 @ github . com> 
 
 
--
Андрей Власов

**Comment by asvlasov** [comment]
Здравствуйте.
В документации есть припер отправки УПД, а мне нужно отправить УКД. Можете показать пример?
 // Добавление документа УПД с контентом, взятым из файла
    Second_DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_02_hyphen", "С:\\Moй УПД.xml");
