### ISSUE TITLE
Ошибка при отправке документов

### ISSUE THREAD

**Issue by MGPr1C** [diadoc/diadocsdk-1c-docs#728]
При отправке документов из модуля для 1С 7.7 стала возникать ошибка:
SendDoc = SendTask.AddDocument("UniversalTransferDocument", ФункУПД, "utd820_05_01_01_hyphen"); 
{B:\DIONIS\EXTFORMS\МАРКИРОВКА\ОБРАБОТКАПРОСМОТРАУПД.ERT(8939)}: PackageSendTask2.AddDocument: Protobuf parse error: required fields missing: (cannot determine missing fields for lite message)
PackageSendTask2.Send: ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost should contain at least one attachment.

Версия компоненты последняя - 5.34.2.709

Подскажите, как можно оперативно решить проблему?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Попробуйте обновить компоненту

Если обновление не поможет, то нужен идентфикиатор ящика, из которого пытаетесь отправить документ

**Comment by MGPr1C** [comment]
Компоненту обновили в первую очередь. На оф. сайте у вас выложена компонента 5.34.2.709, поддержка прислала компоненту 5.35.4.736. Обновили, но это не помогло.

Идентификатор ящика это guid 2BM-5837072592-583701001-201805181005241251835 ?

**Comment by GilimkhanovDenis** [comment]
Последняя версия компоненты [5.36.3.747](https://1c-docs.diadoc.ru/ru/latest/Downloads.html)

**Comment by MGPr1C** [comment]
Обновили компоненту до версии 5.36.3.747. Ошибка, к сожалению, не исчезла.

**Comment by GilimkhanovDenis** [comment]
Проверьте, что у вас действительно загрузилась последняя версия компоненты - метод  [DiadocApi.GetFullVersion()](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html?highlight=GetFullVersion#DiadocAPI.GetFullVersion)

**Comment by GilimkhanovDenis** [comment]
И рекомендую проверить, что старая компонента полностью разрегистрировалась - после разрегистрации не должно остаться никаких веток реестра с именами объектов  компоненты (можно искать по подстроке "Diadoc")

**Comment by MGPr1C** [comment]
Большое спасибо за оперативный и точный совет, после перерегистрации компоненты все заработало!
