### ISSUE TITLE
Маркированный товар по API

### ISSUE THREAD

**Issue by orbazandar** [diadoc/diadocsdk-1c-docs#729]
В какой объект нужно записывать данные о маркировке товара, для передачи в "Честный знак" ?
Например номера ГТД записываются в объект "CustomsDeclarations" : CD = Item.CustomsDeclarations.AddCustomsDeclaration()
Как называется объект для маркировки товара ?

**Comment by Timmer555** [comment]
Если речь идет о УПД так:

DynamicContent = DocToSend.Content; 
UTD            = DynamicContent.UniversalTransferDocument;
..
..
..
Item = UTD.Table.AddItem();
..
..
..
ItemIdentificationNumbers = Item.ItemIdentificationNumbers;
NewItemIdentificationNumber = ItemIdentificationNumbers.AddItemIdentificationNumber();
NewItemIdentificationNumber.AddUnit(<КОД МАРКИРОВКИ>);

**Comment by happydeadman** [comment]
Добрый день!

Все верно, заполнять нужно в "ItemIdentificationNumbers".
Пример можно найти в [документации](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html?highlight=ItemIdentificationNumbers%20#dynamiccontent).

**Comment by petrgavrilko** [comment]
Добрый день, есть строка следующего вида:

СтрокаКМ = ТоварыСтрока.ItemIdentificationNumbers.AddItemIdentificationNumber();

в ней есть такая коллекция:
СтрокаКМ.items

Какой вызвать метод для добавления в эту коллекцию нового элемента и присвоить атрибуту Unit нужный код маркировки?

ранее для добаления кода маркировки был следующий вызов:
СтрокаКМ = ТоварыСтрока.ItemIdentificationNumbers.AddItemIdentificationNumber();
СтрокаКМ.AddUnit(КодМаркировки);

Поскольку мы передаем документ в формате 970 сейчас выдает ошибку: Ошибка при формировании упрощенного документа¶{RM_572930_АдаптацияНовыйФорматУПД Обработка.ЗагрузкаУПД.МодульОбъекта(335)}: Метод объекта не обнаружен (AddUnit)

Прошу дать примеры.
