### ISSUE TITLE
Заполнение полей объекта DocumentShipments

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#730]
Имеем в 1С такой вот код:
```
		ДокументОтгрузки = СодержаниеСчетаФактуры.DocumentShipments.AddDocumentShipment();
		ДокументОтгрузки.Date	= СодержаниеСчетаФактуры.DocumentDate;
		ДокументОтгрузки.Number = СодержаниеСчетаФактуры.DocumentNumber;
		ДокументОтгрузки.Name	= "№ п/п " + стрПП;
```
стрПП содержит номера строк накладной. При просмотре документа на сервера Диадока в поле (5а) выводятся Date и Number, поле Name игнорируется и ничего там не выводится. Контрагенты требуют, чтобы это поле было заполнено, как описано у ФНС.
Что делать?

**Comment by Well3n** [comment]
Добрый день! 
В ПФ мы визуализируем только дату и номер документа. Наименование не отображаем, несмотря на то, что по формату это обязательный элемент. Обязательность распространяется именно на содержимое xml, а не отображение в ПФ.

**Comment by dorexpro** [comment]
Служба поддержки прислала подробный ответ, что это несогласованность печатной формы УПД (утверждается правительством) и формата электронного обмена (утверждается ФНС). Компонента тут абсолютно не при чем.
Большое спасибо.
