### ISSUE TITLE
Неверный статус у аннулированного документа

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#731]
Здравствуйте.   Контрагенту  был  отправлен  запрос  на  аннулирование
документа, выгруженного с ошибкой. Получатель подтвердил аннулирование
и сообщает, что у него документ в статусе "Аннулирован". У нас данный
документ до сих пор в статусе ожидания аннулирования.

Идентификатор документа:
ON_NSCHFDOPPRMARK_2BM-040900001443--2014103011465694612850000000_2BM-2223034582-2012052808121872222630000000000_20211111_862fe0d1-4a95-4aa1-8a8d-ffd356455525

**Comment by happydeadman** [comment]
Добрый день!

Получатель подписал документ и завершил документооборот, вместо того, чтобы подтвердить аннулирование.
Можете связаться с вашим контрагентом и попросить аннулировать документ по [инструкции](https://wiki.diadoc.ru/pages/viewpage.action?pageId=1147041).

Если у контрагента возникнут сложности, то рекомендуйте обратиться в техническую поддержку Диадок.

**Comment by evgen421** [comment]
Здравствуйте. Дело в том, что в честном знаке данный документ в статусе "аннулирован", то есть получатель действительно его аннулировал, иначе как объяснить данный статус в честном знаке.

**Comment by happydeadman** [comment]
Причина такого статуса в том, что вами отправлено два предложения об аннулировании с интервалом в час. 
Контрагент в роуминге подписал первое, но не второе. 

Для решения вопроса контрагенту необходимо обратиться к своему оператору, чтобы тот помог подписать второе предложение об аннулировании. Для помощи в его поиске передайте контрагенту:
- транспортный пакет - 671cdb584f754026b45465669df78f7c;
- логическое сообщение - 76bb1276370649afbdf628476c71461f;
