### ISSUE TITLE
Очень похоже на ошибку в формируемых печатных формах Исправления УПД с док. прослеживаемостью

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#733]
Добрый день.

**Общая информация для упрощения «разбора полётов»:**
Организация:		«ДНС Ритейл»
ИНН:			2540167061
КПП:			254301001
ID организации:	c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru		
ID участника ЭДО:	2BM-2540167061-254001001-201312151140099321090

Совершенно случайно на одном из Исправлений УПД на ПФ увидели такое:

Шапка
![изображение](https://user-images.githubusercontent.com/33707226/143535186-d0c5f9c2-abf0-4b87-b8f2-7c2849a3112f.png)

Смотрим на условное обозначение единиц измерения в составе и в данных документарной прослеживаемости (РНПТ)

В составе отображается:
![изображение](https://user-images.githubusercontent.com/33707226/143535322-102ff2d3-caa2-4c32-8743-761b3472f1b0.png)

Т.е. для кода 796 из состава показывается правильное обозначение - "шт."
Но для такого же кода 796 из данных док. прослеживаемости почему-то вместо обозначения "шт." показывается тот же код единицы измерения - 796.

### А это точно правильно?

**Для информации:**
ID документа по которому получена ПФ из Диадок:
b04f631b-18e0-4d44-8e91-e9aab4e55bd98462a4ed-4f6b-4517-a050-48ddbfb88ae0

Спасибо.

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev, добрый день.

В печатной форме в столбцах `12` и `12а` отображаются те данные, которые заполнены в контенте. Скорее всего в контенте указано `ЕдИзмПрослеж="796" НаимЕдИзмПрослеж="796"`

**Comment by JohnSergeev** [comment]
Добрый день. 

Проверили. Вы правы.

Получается, что когда документ формируется напрямую через подачу XML, а не средствами объектной модели АПИ, то в XML может быть указана любая не проверяемая ерунда, которая в таком виде будет и передана, и отображена на ПФ.

Получается, что ошибки нет, а просто поставщик криво заполняет данные в XML.
Спасибо. Тему можно закрывать.
