### ISSUE TITLE
Document.Countragent не заполнен

### ISSUE THREAD

**Issue by olleksa** [diadoc/diadocsdk-1c-docs#735]
Добрый день.

В объекте Document, полученном в Organization.GetDocumentsTask(), не приходит Countragent.

Мы работаем с Диадок с использованием компонент АПИ для 1С
Установлена последняя версия - v5.36.4.756 x64 для произвольных систем.
f58ad829225940ad8f9b5d75aa4ddd36@diadoc.ru

![изображение](https://user-images.githubusercontent.com/41576111/143691950-197cf81c-17ed-46f3-b0a2-3047367d20c9.png)

**Comment by GilimkhanovDenis** [comment]
Добрый день
Для ответа на вопрос понадобится ссылка на документ или DocumentId

**Comment by olleksa** [comment]
> Добрый день Для ответа на вопрос понадобится ссылка на документ или DocumentId

DocumentId = "ad5f1738-51cb-4aa3-b7d3-358a1ce1548b1f15617e-49ec-4418-93d6-516e97f49066"

**Comment by GilimkhanovDenis** [comment]
Исправим в ближайшем релизе

**Comment by GilimkhanovDenis** [comment]
@olleksa , Добрый день

Попробуйте версию [5.36.5.760](https://1c-docs.diadoc.ru/ru/latest/Downloads.html)

**Comment by olleksa** [comment]
> @olleksa , Добрый день
> 
> Попробуйте версию [5.36.5.760](https://1c-docs.diadoc.ru/ru/latest/Downloads.html)

Спасибо, в ближайшее время попробуем
