### ISSUE TITLE
Зависание службы Агент сервера 1С при вызове метода GetDocuments или GetDocumentsAsync

### ISSUE THREAD

**Issue by sbrros** [diadoc/diadocsdk-1c-docs#736]
Переписываем обработку на работу с ЭЦП на сервере. При вызове методов GetDocumentsAsync или GetDocuments происходит зависание службы Агент сервера 1С Предприятия, все работающие клиенты зависают. Саму службу не получается остановить, помогает только полная перезагрузка сервера. При этом иногда методы отрабатывают без проблем.

**Comment by sbrros** [comment]
Попробовали procdump -e -ma -w ragent.exe   запустили обработку, первый раз GetDocumentsAsync отрабатывает без ошибок, а вот при повторном запросе, служба зависает.  Но никакого дампа не создалось..., но похоже ситуация происходит стабильно после первого успешного получения списка документов.

**Comment by GilimkhanovDenis** [comment]
ключ `-e` задаёт для создания дампа при возникновении необработанного исключения
если процесс зависает, то попробуйте ключ `-h`

`-h | Write dump if process has a hung window (does not respond to window messages for at least 5 seconds)`


Я правильно понял, что зависает примерно такой код:

```
dd_MyOrganization = dd_Connection.GetOrganizationById(...);
dd_GDT = dd_MyOrganization.GetDocumentsTask();
dd_AsyncResult1 = dd_GDT.GetDocumentsAsync(); // AsyncResult создался
dd_AsyncResult2 = dd_GDT.GetDocumentsAsync(); // AsyncResult не создался
```

**Comment by sbrros** [comment]
Код который вызывает проблему ниже. 
Мы не дважды вызываем метод, а дважды вызываем весь блок кода ниже, т.е. первый раз он отрабатывает, а при повторной попытке чтения происходит зависание службы.

Box=	 			ПолучитьОрганизациюПоBoxID(ТекПредставление,ТекBoxId);
DocumentsTask=	Box.getDocumentsTask();
			
Если ТекОтбиратьПоДатеДокумента Тогда
	DocumentsTask.FromDocumentDate=			ТекДатаНачала;
	Если НЕ ПараметрыВыборки.Направление = "OutboundWaitingForSenderSignature" Тогда
		DocumentsTask.ToDocumentDate=		КонецДня(ТекДатаокончания);
	КонецЕсли;
Иначе
	DocumentsTask.FromSendDate=			ТекДатаНачала;
	Если НЕ ПараметрыВыборки.Направление = "OutboundWaitingForSenderSignature" Тогда
		DocumentsTask.ToSendDate=		КонецДня(ТекДатаокончания);
	КонецЕсли;
КонецЕсли;
DocumentsTask.Category=					ФильтрАпи.ТипДокумента + "." + ФильтрАпи.Фильтр;
DocumentsTask.counterAgentId=			ТекcounterAgentBoxId;
DocumentsTask.DepartmentId=				depId.DepartmentId;
DocumentsTask.ExcludeSubdepartments=	НЕ depId.вклДочерниеПодразделения;
		
AsyncTask=	DocumentsTask.GetDocumentsAsync();    //  ПРОБЛЕМА В ЭТОЙ СТРОКЕ ПРИ ПОВТОРНОМ ЧТЕНИИ

**Comment by GilimkhanovDenis** [comment]
Нужен дамп зависшего процесса

**Comment by GilimkhanovDenis** [comment]
@sbrros ? Добрый день

Попробуйте версию [5.36.5.760](https://1c-docs.diadoc.ru/ru/latest/Downloads.html)

Если зависание продолжается, то нужен дамп зависшего процесса

**Comment by sbrros** [comment]
Добрый вечер.
С данной версией стало заметно лучше! Понаблюдаем за работой еще завтра, но по крайней мере прошлые "сбойные" моменты прошли.
Спасибо!
