### ISSUE TITLE
Интеграция 1С - Диадок (маркированный товар)

### ISSUE THREAD

**Issue by gerz85** [diadoc/diadocsdk-1c-docs#737]
Добрый день! Пишем интеграцию 1С - Диадок - с целью автоматизировать работу с маркированным товаром. Появились несколько вопросов: 

Есть ли возможность при получении списка документов отфильтровать только по документам, в составе которых имеется маркированный товар, чтобы не перебирать все документы?

**Comment by GilimkhanovDenis** [comment]
Добрый день

> Есть ли возможность при получении списка документов отфильтровать только по документам, в составе которых имеется маркированный товар, чтобы не перебирать все документы?

Такого фильтра нет ни в компоненте, ни в [публичном API Диадока](https://api-docs.diadoc.ru/ru/latest/http/GetDocuments.html)

> может быть есть отдельные методы для работы именно с маркированным товаром, встроенные в компоненту?

Каких-то специализированных методов связанных с маркировкой товаров нет. Информация о маркированном товаре содержится в контенте документов. Всю логику, связанную с обработкой марок/штрихкодов Диадок выполняет на своей стороне и компонента никак в этом не участвует.

Единственный метод, который может вас заинтересовать - [DocumentBase.GetExternalStatuses()](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentBase.html?highlight=GetExternalStatuses#DocumentBase.GetExternalStatuses)

**Comment by gerz85** [comment]
Спасибо.
