### ISSUE TITLE
Как указать в поле № 5 (к расчетно-платежному документу) несколько документов

### ISSUE THREAD

**Issue by galiurust** [diadoc/diadocsdk-1c-docs#738]
Добрый день, Уважаемая поддержка!
Типовая конфигурация "Бухгалтерский учет (ред.4.5)" (для платформы 1с7.7)
Как ее подправить и как изменить соответствующий модуль Диадок, чтобы
в поле № 5 (к расчетно-платежному документу) УПД было указано несколько документов.
Наша организация ООО "УГТ". ИНН\КПП 1821012720\182101001
Огромная просьба помочь оперативно! Мы на платной поддержке!

**Comment by galiurust** [comment]
Какие сроки ответа? Очень жду

**Comment by volodkindv** [comment]
Добрый день.
В контенте документа надо заполнить массив TransferInfo.TransferBases.

**Comment by volodkindv** [comment]
Надо заполнить коллекцию DocumentShipments в контенте. Поля элемента коллекции: Name, Number, Date.
