### ISSUE TITLE
Разные возвращаемые значения метода GetDocumentById

### ISSUE THREAD

**Issue by EugeneMSoul** [diadoc/diadocsdk-1c-docs#739]
Добрый день.

Столкнулись с проблемой при работе с методом GetDocumentById. 

Суть проблемы
Внедряем Диадок API собственными силами. Обкатываем все на тестовом ящике 9ef604cc701c4a768a94c53bf009800e@diadoc.ru.
На этот ящик отправляем пакеты документов. В каждом пакете УПД (передаточный документ) и Счет-фактура, отправили два пакета. При получении документа счет-фактуры (из каждого пакета) с помощью метода GetDocumentById, возвращаемое значение немного отличается составом. В одном случае коллекция InitialDocumentIds заполнена, в другом пустая.
Вот это документ 35b302e7-6519-4bce-9ee5-00588c1e1d3351e61236-5dcd-4ec8-9163-c1f557dda53a с заполненной колекцией, а вот этот b6fb96ea-1ac7-4ece-aa63-6121f700bc7346229491-c1ed-4597-87a1-2d478da7fe01 с пустой. 
Хотелось бы понять в чем причина такого поведения API, является это ошибкой?
Есть подозрения, что важную роль играет порядок документов в пакете, с пустой коллекцией счет-фактура шла по порядку раньше УПД.

**Comment by volodkindv** [comment]
Добрый день.
Оба пакета отправлены из веб-интерфейса.
Возможно, документы добавляли в пакет в разном порядке. Проверьте также коллекцию SubordinateDocumentIds.
