### ISSUE TITLE
UnsupportedEventType - событие ГИС МТ

### ISSUE THREAD

**Issue by ptizaezhik** [diadoc/diadocsdk-1c-docs#741]
Добрый день!

Получаю события через GetDocumentEventList()
Документ - УПД с маркированными биодобавками, утвержденный и прошедший через ГИС МТ
В обоих событиях ("обрабатывается в ГИС МТ" и "обработан в ГИС МТ") светится UnsupportedEventType

![изображение](https://user-images.githubusercontent.com/82872143/144371211-7c534e4b-18a8-4dfe-8970-bd66fb1f4620.png)

Можно ли поменять UnsupportedEventType на что-то более информативное?
Например, GismtProcessingNormal и GismtProcessedSuccess для данного случая.
Маркировки будет всё больше, никуда не денемся.

**Comment by volodkindv** [comment]
#706

**Comment by GilimkhanovDenis** [comment]
Учтём это пожелание, когда будем переделывать ленту событий https://github.com/diadoc/diadocsdk-1c-docs/issues/706
