### ISSUE TITLE
Заполнение параметра "Основания"  в Акте сдачи-приемке в Диадок

### ISSUE THREAD

**Issue by 999ilya999** [diadoc/diadocsdk-1c-docs#742]
Добрый день. Нужно, чтобы параметр "Основания" заполнялся как наименование договора. Сейчас параметр заполняется вот так:
Результат = Результат + Разделитель + TransferBase.DocumentName 
		+ ?(ЗначениеЗаполнено(TransferBase.DocumentNumber), " № "  + TransferBase.DocumentNumber, "")
		+ ?(ЗначениеЗаполнено(TransferBase.DocumentDate)  , " от " + ДатаСтрокой(TransferBase.DocumentDate), "")
		+ ?(ЗначениеЗаполнено(TransferBase.DocumentInfo)  , ", "   + TransferBase.DocumentInfo, "");
Где TransferBase.DocumentName - это значение по умолчанию "Договор". 
Далее номер и дата договора
Мне нужно в структуру TransferBase добавить наименование договора
Прошу подсказать в каком модуле формируется данная структура

**Comment by volodkindv** [comment]
Добрый день.
В этом репозитории идет обсуждение вопросов по внешней компоненте.
Вопросы по модулям правильнее направлять в техподдержку.
