### ISSUE TITLE
Вопросы по роумингу

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#743]
Здравствуйте.
1.Почему до сих пор отсутствует автороуминг с оператором Тензор, вроде бы такой крупный оператор, неужели нет технической возможности?
2.Возможно ли послать заявку на роуминг через API или COM объект, а то приходится переходить из учетной системы в вэб интерфейс Диадока. Если нет такой возможности, то очень хотелось бы ее иметь в учетной системе. Я думаю многим понадобилась бы такая возможность.

**Comment by YudinaM** [comment]
Добрый день!
1. Сейчас и мы, и коллеги из Тензор работаем над устранением технических ограничений с обоих сторон, чтобы запустить автороуминг в таком виде, в котором будет комфортно работать пользователям. С целью снижения вероятных технических сложностей  с 15.06.2021 по  22.06.2021 запускали пилотное тестирование.
Автороуминг планируется, но сроки запуска на сегодняшний день мы обозначить  не можем
2. Такой возможности нет, но мы активно развиваем автороуминг, так что бы можно было обмениваться приглашениями, а не составлять заявки

**Comment by evgen421** [comment]
Спасибо за ответы.
