### ISSUE TITLE
Protobuf parse error: required fields missing: (cannot determine missing fields for lite message)

### ISSUE THREAD

**Issue by yellowit** [diadoc/diadocsdk-1c-docs#745]
Перестали отправляться УПД  для которых в пакет кидает дополнительные документы. Ошибка добавления документов в коллекцию DocumentsToSend методом PackageSendTask2.AddDocument - Protobuf parse error: required fields missing: (cannot determine missing fields for lite message).
Документы отправляются из стороннего модуля через Диадок.Стандарт 5.52.01

**Comment by volodkindv** [comment]
Уточните:
1. Версию компоненты.
2. Сценарий оспроизведения.

**Comment by yellowit** [comment]
Разобрались. Была старая компонента. Спасибо.
