### ISSUE TITLE
Подписание документа с комментарием COM x86 5.35.4.736 для произвольных систем

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#746]
Добрый день! Подскажите, есть ли возможность подписания входящих документов с указанием нашего комментария при подписании? Если есть, с помощью каких методов реализуется?

**Comment by GilimkhanovDenis** [comment]
Добрый день!
При подписании документа нет возможности указывать комментарий.

**Comment by jakeqwert** [comment]
Спасибо!
