### ISSUE TITLE
Выгрузка документов разным филиалам - формирование универсального ключа для каждого филиала ?

### ISSUE THREAD

**Issue by JGhjfhgjkdh5486t** [diadoc/diadocsdk-1c-docs#747]
Добрый день. Клиент написал и задает вопрос.
У них несколько филиалов, а сам контрагент один в ДиаДок.
От нас, соответственно, выгружаются документы на этого контрагента.
Пишут нам: их тех поддержка сообщила, что при формировании с нашей стороны универсального ключа комплекты смогут сразу попадать на соответствующих ответственных лиц со стороны Общества. Просьба уточнить – есть ли возможность с нашей стороны ЭДО формирования универсального ключа для каждого Филиала?

Разъясните, пожалуйста, эти моменты. Как это происходит? Где почитать?
В контрагентах я вижу только одного клиента с этим Наименованиеим / Инн и Кпп.
Как я могу увидеть / узнать их подразделения, куда, какие команды / ключи им формировать при выгрузке документов?

Работаем через Api из 1С 7.7.

**Comment by GilimkhanovDenis** [comment]
Добрый день!
Не очень понятно про какие уникальные ключи идёт речь

На уровне догадки:
возможно, вам нужно использовать объект [CustomDataPatchTask](https://1c-docs.diadoc.ru/ru/latest/ComObjects/CustomDataPatchTask.html), созадаваемый методом [DocumentBase.CreateCustomDataPatchTask()](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentBase.html#DocumentBase.CreateResolutionRequestTask)

**Comment by JGhjfhgjkdh5486t** [comment]
Добрый день.
В продолжение вопроса:
" При получении документа от внешнего контрагента, если в XML в структуре <ИнфПолФХЖ1> указан идентификатор <ТекстИнф Идентиф="UNIVERSAL_KEY" и Значен="любое_произвольное_значение", необходимо на портале СЭД определять шаблонную цепочку по указанному универсальному ключу.


Таким образом, как я понял, нам как Контрагенту, который отправляет документы, нужно создать Идентификаторы для каждого филиала Покупателя?
Где искать эти поля?
Какие могут быть идентификаторы / уникальные ключи? Просто любое текстовое+числовое значение ? Какие ограничения?

**Comment by JGhjfhgjkdh5486t** [comment]
Нашел следующую структуру:
AdditionalInfo = Utd820_SellerContent.AdditionalInfoId.addAdditionalInfo();
AdditionalInfo.Id = "1"; // Id - string50 - required - Идентиф - идентификатор (наименование)
AdditionalInfo.Value = ...; // Value - string2000 - required - Значен - значение

Смотрю, на экране отображаются в дополнительных сведениях, через запятую.
Возможно ли НЕ показывать, или показывать с  новой строки?
