### ISSUE TITLE
Ошибка при повторной загрузке компоненты

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#750]
1С:Предприятие 7.7. Используется версия компоненты: 5.36.3.747.
Если повторно выполнить загрузку компоненты с помощью метода ЗагрузитьВнешнююКомпоненту(), то при создании объекта "AddIn.Diadoc.Reflector" выдает следующую ошибку:
```
Неудачная попытка создания объекта
Reflector = СоздатьОбъект("AddIn.Diadoc.Reflector");
```
При одиночной загрузке все отрабатывает нормаль. Проблема именно при второй загрузке компоненты.
При этом ранее все работало нормально много лет.

**Comment by GilimkhanovDenis** [comment]
Добрый день
Попробовал на версии x86 5.36.9.786
Поведение не воспроизводится

```
Функция ПодключитьКомпоненту(ПутьДоКомпоненты, НомерПопытки)
	Попытка
		Сообщить("Попытка: " + Строка(НомерПопытки));
		ЗагрузитьВнешнююКомпоненту(ПутьДоКомпоненты);
		dd_AddInObject = создатьОбъект("AddIn.DiadocInvoiceAPI");		
		dd_Api = dd_AddInObject.CreateObject();
		Сообщить("Подключена компонента: " + dd_Api.GetFullVersion());

		Сообщить("Создаю Рефлектор");
		Reflector = создатьОбъект("AddIn.Diadoc.Reflector");
		Сообщить("Успех");
		Возврат dd_Api;
	Исключение
		Сообщить(ОписаниеОшибки());
	КонецПопытки;
КонецФункции
```
![image](https://user-images.githubusercontent.com/34439383/150797043-b7ebbe14-6981-4452-9d0a-c45f747a154d.png)


Скорее всего что-то с регистрацией. Попробуйте полностью разрегистрировать и зарегистрировать заново
