### ISSUE TITLE
Входящий УПД ContentItems.Count()=0

### ISSUE THREAD

**Issue by MariaAmpilova** [diadoc/diadocsdk-1c-docs#751]
Здравствуйте.
Подписываем входящий документ УПД с функцией УПДСЧФ согласно инструкции:

    ReplyTask = DocumentPackage.CreateReplySendTask2(ТипОтвета);
    ContentItems = ReplyTask.ContentItems;
    
    КоличествоКонтентов = ContentItems.Count();

    Для ц = 0 По КоличествоКонтентов - 1 Цикл
        ContentItem = ContentItems.GetItem(ц);
        Если НуженВторойТитул(ContentItem.Document.WorkflowId) Тогда
            // Предполагаем, что есть функции заполнения контента второго титула формализованных документов
            Заполнить_DynamicContent(ContentItem.Content);
        КонецЕсли;
    КонецЦикла;

В строке  КоличествоКонтентов = ContentItems.Count(); получаем 0. По какой причине это может быть? И что в таком случае делать?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Скорее всего, используется старая компонента

Аналогичные запросы:
https://github.com/diadoc/diadocsdk-1c-docs/issues/649
https://github.com/diadoc/diadocsdk-1c-docs/issues/657
https://github.com/diadoc/diadocsdk-1c-docs/issues/658
