### ISSUE TITLE
Подпись договора через api в 1с

### ISSUE THREAD

**Issue by irina48l** [diadoc/diadocsdk-1c-docs#752]
Добрый день! 
ИНН 1655258235 КПП 161501001 Университет Иннополис

У меня вопрос о возможности подписания входящего документа с типом Contract через API (делаю доработку в 1с).
Пришел документ Договор, статус "Требуется подпись". 
Формализованные документы, например, Акт, успешно подписываю следующим образом:

		Document = Organization.GetDocumentById(DocumentID);
		ReplySendTask = Document.CreateReplySendTask2("AcceptDocument");
		Reflector = Новый ComОбъект("AddIn.Diadoc.Reflector");
		МассивItem = ReplySendTask.ContentItems;
		    Для каждого Item Из МассивItem Цикл
		        
		        Content = Item.Content;
		        
		        TypeDesc = Reflector.Describe(Content);
		        
		        МассивСвойств = TypeDesc.GetPropertiesNames();
		        ИмяСвойства = МассивСвойств.GetItem(0);
		        
		        Doc = Content[ИмяСвойства];
		        Doc.DocumentCreator = Organization.Name;
		        Doc.OperationContent = "Реализация";

		        Signers = Doc.Signers;
		        NewSigner = Signers.AddItems();
			SignerReference = NewSigner.SignerReference;
			SignerReference.BoxId = Organization.Guid;
			SignerReference.CertificateThumbprint = Organization.Certificate.Thumbprint;
		     КонецЦикла;
	
		ReplySendTask.Send();

Для акта в Content есть свойство UniversalTransferDocumentBuyerTitle (COM-объект), у которого есть свойства, в том числе Signers, которые я заполняю для подписания.

А для Договора в Content есть только свойство Type типа строка со значением "DocumentSignature", и нет Signers.
И я не пойму, как подписать этот документ

**Comment by GilimkhanovDenis** [comment]
Добрый день
Дополнительно ничего указывать не нужно, так как нет необходимости формировать второй титул и указывать полномочия подписанта - ставится только подпись. Подпись сформируется с тем сертификатом, по которому авторизовались.
