### ISSUE TITLE
Ошибка в записи значения свойства IsQualifiedElectronicSignature и INN

### ISSUE THREAD

**Issue by UserAlex90** [diadoc/diadocsdk-1c-docs#755]
**Первая проблема:** Периодически, при получении сертификатов пользователей с помощью метода GetPersonalCertificates(),
в информации сертификатов признак IsQualifiedElectronicSignature устанавливается false. 
В одной базе все отображается корректно, а в другой с ошибками.

**Вторая проблема:**  в поле ИНН вместо ИНН организации, выводится ИНН физлица.

Через какое-то время метод снова работает корректно, во всех сертификатах выводится ИНН организации, и IsQualifiedElectronicSignature устанавливается Истина.
Потом снова проблема возвращается.

Просьба помочь максимально оперативно! Возможно, уже с таким обращались.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Не воспроизводится.
Возможно, что-то с регистрацией компоненты. Флаг зависит только только от состава открытого ключа сертификата

как и ИНН
