### ISSUE TITLE
Не получается аннулировать документ

### ISSUE THREAD

**Issue by AlexanderShiryaev** [diadoc/diadocsdk-1c-docs#757]
При попытке аннулирования документа через API возвращается ошибка 409: текущее состояние документа не позволяет создать запрос на аннулирование или выполнить отзыв. Статусы документов в ЛК и у нас совпадают - ожидание подписи контрагента
GUID: 173627de-c4c9-480b-8cfd-d0664091a592140c7057-4332-4e9b-95ef-cfe919ee1d43

**Comment by GilimkhanovDenis** [comment]
Добрый день

по [документ](https://diadoc.kontur.ru/1b6b3083-c50f-4620-b419-81055ef9b948/Document/Show?letterId=173627de-c4c9-480b-8cfd-d0664091a592&documentId=140c7057-4332-4e9b-95ef-cfe919ee1d43) был получен отказ в подписи 4 февраля. Ошибка `Текущее состояние документа не позволяет создать запрос на аннулирование или выполнить отзыв` была после этого.
Аннулирование недоступно, так как не было принятия документа c `workflow=3` обеими сторонами
