### ISSUE TITLE
Работа с отказом от партнёрства

### ISSUE THREAD

**Issue by BitMounter** [diadoc/diadocsdk-1c-docs#759]
Добрый день!

Для отказа от партнёрства документация предлагает использовать метод `BreakWithCounteragent(Сообщение)`. Это если мы хотим разорвать отношения. Если же контрагент решил разорвать с нами отношения и отправил отказ этим методом, как нам узнать об этом? Где получить текст сообщения, которое контрагент отправил при отказе?
В документации нашёл только возможность получить список контрагентов по статусу `RejectsMe`, но из такого списка сообщение, отправленное контрагентом уже не достать.

**Comment by GilimkhanovDenis** [comment]
Добрый день

В списке контрагентов у каждого контрагента есть поле `MessageFromCounteragent` - в нём будет комментарий, отправленный контрагентом

см. [Organization.GetCounteragentListByStatus](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html#Organization.GetCounteragentListByStatus) + [Counteragent](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Counteragent.html)
