### ISSUE TITLE
Вопрос по внедрению модуля Диадок 1С УПД

### ISSUE THREAD

**Issue by ckyrun** [diadoc/diadocsdk-1c-docs#76]
Внедряю отправку УПД на нетиповую конфу. Для примера использую Diadoc1C_5_13_11.

В какие поля COMОбъекта помещать данные из выделенных красным полей печатной формы для того, что бы они отправились получателю?
[](url)
![image](https://cloud.githubusercontent.com/assets/26325897/23795273/b76b7902-05a5-11e7-9436-e376b3ccad2d.png)

**Comment by volodkindv** [comment]
http://1c-docs.diadoc.ru/ru/latest/UtdSellerContent.html
"Иные сведения" расположены в AdditionalInfoId
"Основание" - в TransferInfo.TransferBases (http://1c-docs.diadoc.ru/ru/latest/TransferBase.html)
P.S. Конфигурация написана с нуля или сделана на базе одной из типовых, которые поддерживаются модулем?

**Comment by ckyrun** [comment]
Спасибо за ответ. Конфигурация так давно и сильно переработана, что даже их программисты 1С не могут сказать, что было основой. Буду пробовать помещать нужные мне данные в указанные контейнеры.

**Comment by volodkindv** [comment]
У нас есть модуль для работы с самописками-нетленками. Если интересно, пишите на volodkindv@skbkontur.ru.
