### ISSUE TITLE
документы "требующие обработки"

### ISSUE THREAD

**Issue by Xolto** [diadoc/diadocsdk-1c-docs#760]
Здравствуйте.
Ситация такая: документ полученный головным подразделением отправили на согласование в "другое" подразделение. И Пользователь "другого" подразделения  в "WEB-диадоке" видит в разделе "требующие обработки" этот документ, при этом во входящих его нет. Вопрос: какими методами получить доступ к этому документу в 1С (через getdocuments не получается или я чего не знаю)
спасибо

**Comment by GilimkhanovDenis** [comment]
Добрый день

В API нет фильтра "Требующие обработки", список нужно собирать из документов разных статусов и фильтровать по переданным этому сотруднику или в его подразделение.

**Comment by Xolto** [comment]
метод getDocuments не возвращает документы пользователю дочернего подразделения которые были отправлены  клиентом в головное подразделение и далее пользователем головного подразделения отправлены на согласование пользователю дочернего подразделения.

**Comment by GilimkhanovDenis** [comment]
Добрый день.

Для подобного сценария API Диадока требует, чтобы у пользователя, который фильтрует подобные документы был доступ ко всем подразделениям. Со стороны компоненты повлиять на ситуацию не сможем
