### ISSUE TITLE
Не удаётся добавить грузоотправителя. 

### ISSUE THREAD

**Issue by VitShvets** [diadoc/diadocsdk-1c-docs#761]
Пытаюсь отправить УПД:
1. Использую компоненту DiadocCom_5_36_9_786_x64.dll
2. Создаю SendTask = Org.CreatePackageSendTask2();
3. Добавляю УПД  = SendTask.AddDocument("UniversalTransferDocument", "ДОП", "utd820_05_01_02_hyphen");
4. Получаю InvoiceContent = УПД.Content.UniversalTransferDocumentWithHyphens;
5. Добавляю продавца SellerInfo = InvoiceContent.Sellers.AddSeller();
6. Заполняю у продавца реквизиты в SellerInfo.OrganizationDetails.OrgName, Inn и т.д.
7. Добавляю грузоотправителя  ShipperInfo = InvoiceContent.Shippers.AddShipper();

Но в ShipperInfo нет ни OrganizationDetails ни OrganizationReference. Только свойство "SameAsSeller" и какая-то коллекция "Items". 

Подскажите  пожалуйста как правильно заполнить грузоотправителя и грузополучателя.

![image](https://user-images.githubusercontent.com/100152883/155002034-5db6028b-7975-4c0c-9b92-22fe49b5a3c8.png)

**Comment by GilimkhanovDenis** [comment]
Добрый день

Коллекция внутри ShipperInfo называется `items`. Соответственно, нужно вызвать метод `ShipperInfo.Additems()`

Подробнее [здесь](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html)
