### ISSUE TITLE
Аннулирование в роуминге

### ISSUE THREAD

**Issue by NickVStepin** [diadoc/diadocsdk-1c-docs#763]
При попытке запросить аннулирование документа через CreateReplySendTask2("RevocationRequest") получаю:
Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: MessagePatchToPost.RevocationRequests[0]: Version 1.01 of revocation request is not supported by roaming operator 2ae. Supported versions: revocation_request_02

возможно ли как-то поменять версию или аннулировать только руками через веб-интерфейс?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Обновите компоненту. Новая версия аннулирования была поддержана в [5.36.0](https://1c-docs.diadoc.ru/ru/latest/History/release_info/5_36_0.html)

**Comment by NickVStepin** [comment]
я правильно понимаю, что сам вызов при этом не меняется, т.е. мне надо только обновить компоненту?

**Comment by GilimkhanovDenis** [comment]
Всё верно. вызов не меняется
