### ISSUE TITLE
Вопрос по формированию наименования ИП при отправке исходящих УПД (внутреннее не отключаемое преобразование наименования ИП)

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#764]
Добрый день.

**Общая информация для упрощения «разбора полётов»:**
Организация:		«ДНС Ритейл»
ИНН:			2540167061
КПП:			254301001
КПП2:			783450001
ID организации:	c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru		
ID участника ЭДО:	2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.36.5.760**.

Как-то не обращали внимания, но бухгалтерия начала транслировать нам недовольство от некоторых контрагентов, мы провели небольшое исследование и, скажем так, несколько удивились текущему подходу в формировании вами исходящих УПД, в которых покупатель и/или грузополучатель - это ИП (индивидуальный предприниматель).

**Оказалось, что при формировании и отправке исходящих документов у вас существует внутреннее преобразование наименования организации, если указано, что контрагент - это ИП.**

**Обнаружено следующее:**
Если для покупателя или грузополучателя указано, что это ИП - т.е. у него ИНН длиной 12 цифр + нет КПП + указан тип ИП (Buyer.OrgType = 2), то перед формированием и отправкой исходящего документа происходит контроль наименования ИП в поле Buyer.OrgName и **это наименование перед отправкой меняется по вполне определенным правилам**. 

А именно (на примере):
1. Было "Рябоконь Ирина Ивановна" - Стало "Рябоконь Ирина Ивановна".
2. Было "ИП Рябоконь Ирина Ивановна" - Стало "Рябоконь Ирина Ивановна".
3. Было "Индивидуальный предприниматель Рябоконь Ирина Ивановна" - Стало "Рябоконь Ирина Ивановна".
4. Было "ИндЕвидуальный предприниматель Рябоконь Ирина Ивановна" - Стало "ИндЕвидуальный предприниматель Рябоконь Ирина ИвановнаРябоконь Ирина Ивановна".

Т.е. из наименования организации, если это ИП, явным образом исключается "ИП " или "Индивидуальный предприниматель " в начале наименования. И в исходящем документе будет уже измененное наименование без этих элементов. Во входящем, у получателя этого документа - соответственно, будет также.

Результатом этого является то, что в печатных формах УПД никак не отображается, что это ИП! 
![изображение](https://user-images.githubusercontent.com/33707226/155084913-5d236759-5ddd-42f3-9926-9c7ece9971db.png)
Просто потому, что в наименованиях в документе этих данных уже и нет!
И, главное, у нас нет никакой возможности на это повлиять!

При этом в самом электронном документе явно указано, что покупатель или грузополучатель - это ИП. Есть соответствующим образом заполненное поле в XML. Но на печатной форме отображается только ФИО, т.к. была выполнена безусловная коррекция передаваемого в документ наименования. 

При этом многие из наших контрагентов выражают недовольство этим - т.е. они хотели бы видеть на печатных формах для ИП именно явное указание на то, что это ИП - т.е. они хотят видеть, что покупатель это не просто "Иванов А.А.", а именно "ИП Иванов А.А.".

**Вопросы:**
1. А зачем так сделано?

По идее, нам, как пользователю АПИ, хотелось бы, чтобы было ровно наоборот! 
Т.е., если я не указал для ИП "приставку" "ИП " в наименовании, то чтобы она автоматически добавлялась и была видна на печатной форме.

А еще лучше - чтобы нам оставили возможность самим решать, как именно отображать данные по ИП - т.е. чтобы просто не было никакой внутренней переделки наименования. Захотели, чтобы было без "ИП" - указали имя без "ИП". Захотели, чтобы с ИП (например, по настойчивому требованию конкретного контрагента) - указали с "ИП ".

2. Возможно ли отключить это безусловное неявное преобразование наименования ИП и дать нам самим решать, как именно формировать наименования для контрагентов, являющихся ИП?

Спасибо.

**Comment by TugovDenis** [comment]
Добрый день.
1. В соответствии с приказами ФНС, регламентирующими форматы электронных документов, в сведениях об индивидуальном предпринимателе должны указываться только ИНН физического лица и его ФИО. Организационно-правовая форма (приставка «ИП») указываться не должна, поэтому ее и нет.
С приказами можно ознакомиться на сайте https://www.diadoc.ru/docs/laws .
2. К сожалению, возможности отключить преобразование нет. Можно настроить определенный внешний вид печатной формы документа в веб-версии Диадока с помощью дополнительной услуги - кастомная печатная форма (КПФ). Услуга является платной, за подробностями рекомендуем обратиться к вашему менеджеру по Диадоку.

**Comment by Milady2024** [comment]
> Добрый день.
> 
> 1. В соответствии с приказами ФНС, регламентирующими форматы электронных документов, в сведениях об индивидуальном предпринимателе должны указываться только ИНН физического лица и его ФИО. Организационно-правовая форма (приставка «ИП») указываться не должна, поэтому ее и нет.
>    С приказами можно ознакомиться на сайте https://www.diadoc.ru/docs/laws .
> 2. К сожалению, возможности отключить преобразование нет. Можно настроить определенный внешний вид печатной формы документа в веб-версии Диадока с помощью дополнительной услуги - кастомная печатная форма (КПФ). Услуга является платной, за подробностями рекомендуем обратиться к вашему менеджеру по Диадоку.

Доброго дня!

Вы указали ссылку на большой перечень документов, но ни в одном из этих документов я не нашла указание на то, что наименование продавца ИП должно состоять только из его ФИО, без указания "ИП" или "Индивидуальный предприниматель". Укажите, пожалуйста конкретный документ и пункт в этом документе. Это очень важный вопрос, т.к. выставление документов без указания, что поставщик ИП, приводит к массовым конфликтам с покупателями, особенно с теми, кто на ОСН и берет к вычету НДС, выделяемый в документах продавца ИПшника.
