### ISSUE TITLE
Ошибка "Too many movements. Max allowed movements count is 15"

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#765]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
КПП2: 783450001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: COM x64 5.36.5.760.

Заметили, что по некоторым попыткам перемещения документов между подразделениями стали приходить ошибки вида:

_Ошибка при вызове метода контекста (Move): Произошла исключительная ситуация (DocumentBase.Move): ##100[Ошибка сервера Диадок]code:409, HTTP error: Too many movements. Max allowed movements count is 15_

Суть ошибки понятна из ее описания.
Но вот сам факт такого ограничения... чем он объясняется? Почему 15? А не 26, например?

Понятно, что когда ты вручную перемещаешь документы между подразделениями, то 15-ти попыток хватит тебе "до конца жизни". Но, если организовывать какую-то автоматику распределения и, например, допустить при этом какую-то ошибку, то эти 15 попыток очень легко использовать полностью очень и очень быстро. 

Что, собственно, у нас, похоже, и произошло. Как минимум с частью документов. 
И теперь не очень понятно - а что с этим можно сделать?

Поэтому хотелось бы уточнить несколько моментов:
1. Если так получилось и по документу достигли этого лимита в 15 перемещений - то документ больше вообще никак и никогда нельзя будет никуда переместить? И он навечно останется в последнем подразделении, куда он попал?
2. Или это ограничение сбросится через какое-то время и можно будет переместить документ снова? Если да, то через какое?
3. Или автоматически это ограничение не сбрасывается, но его всё равно можно как-то отменить? Если да, то как?
4. Можно ли как-то поменять предел с 15 на большее количество перемещений?
5. Что можно сделать с последствиями ошибок в перемещениях, когда документ в итоге оказался не в том подразделении, где он должен быть, а лимит перемещений исчерпан?

Очень ждем ваши ответы!

Спасибо.

**Comment by ButurlakinSemyon** [comment]
@JohnSergeev добрый день!
1. Если лимит исчерпан, то документ больше нельзя никуда перемещать.
2. Данный лимит не сбрасывается.
3. Отменить его к сожалению нельзя.
4. Данное ограничение установлено на стороне апи.  В моменте внести изменения не получится. Можете подробнее рассказать про сценарий, который привел к этой ситуации? Вы писали про ошибку, которую допустили. Можете рассказать с чем была связана ошибка?
5. Если лимит исчерпан, документ останется в том подразделении, в которое был перемещен. С документом ничего не получится сделать.
