### ISSUE TITLE
Ошибка выгрузки УПД

### ISSUE THREAD

**Issue by VitShvets** [diadoc/diadocsdk-1c-docs#768]
Пытаюсь отправить УПД:
1. Использую компоненту DiadocCom_5_36_9_786_x64.dll
2. Создаю SendTask = Org.CreatePackageSendTask2();
3. Устанавливаю идентификатор контрагента SendTask.CounterAgentId = НужныйCounteragentId;
4. Добавляю УПД = SendTask.AddDocument("UniversalTransferDocument", "ДОП", "utd820_05_01_02_hyphen");
5. Заполняю остальные поля.
6. Отправляю SendTask.Send()
7. Получаю ошибку:

2012111407001544014440000000000_2BM-7723823400-2013041212283238278290000000000_20220225_35c4fa4c-c46e-4299-83ed-80b775c0e270.xml содержит ошибки и не может быть доставлен. Не совпадают идентификаторы отправителя-получателя в документе и описании к документу. Обратитесь к разработчику вашего ПО для исправления (3.04.09.003)

Подскажите пожалуйста, какое поле и где нужно дополнительно заполнить? Контрагент роуминговый, но также по ИНН 5002087060 находится и в Диадок.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Получателя необходимо однозначно задать в контенте документа.

Аналогичные вопросы и примеры заполнения можно подсмотреть, например, здесь:
https://github.com/diadoc/diadocsdk-1c-docs/issues/717
https://github.com/diadoc/diadocsdk-1c-docs/issues/715

**Comment by VitShvets** [comment]
Добрый день! Помог ответ @GilimkhanovDenis в #715
Кроме SendTask.CounterAgentId нужно заполнять Buyer.OrganizationDetails.FnsParticipantId.
Так работает корректно:
"НужныйCounteragent" получаю из GetCounteragentListByInnKpp
SendTask.CounterAgentId = НужныйCounteragent.Id;
...
Buyer.OrganizationDetails.FnsParticipantId    = НужныйCounteragent.FnsParticipantId;

Спасибо!
