### ISSUE TITLE
Ошибка при принятии входящего аннулирования

### ISSUE THREAD

**Issue by SlashSep** [diadoc/diadocsdk-1c-docs#769]
Здравствуйте.
Установлена COM компонента v5_36_9_786_x64 для произвольных систем.
Работаем через MSSQL: Microsoft SQL Server 2008 (SP4) - 10.0.6000.29 (X64)

Получаем документ по которому пришел входящий запрос об аннулировании:
select @MethodStr = 'GetDocumentById('+@DocGUID+')'
EXECUTE @rc = sp_OAMethod @Organization, @MethodStr, @Document output

При попытке вызвать метот CreateReplySendTask2 с типом принятия аннулированя получаем ошибку:

EXECUTE @rc = sp_OAMethod @Document, 'CreateReplySendTask2(AcceptRevocation)', @ReplySendTask output
ODSOLE Extended Procedure. Исключение при выполнении кода:  EXCEPTION_ACCESS_VIOLATION

В чем может быть проблема?
С уважением, Алексей.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Можете указать ссылку на документ, который пытаетесь аннулировать или `Organization.Guid` и значение в `@DocGUID` ?

**Comment by SlashSep** [comment]
Добрый день!
Пример:
Organization.Guid = a704aeeeaea141f09d04b187a857394c@diadoc.ru
DocGUID = b8214435-fb93-45a5-a87d-2c022f274e5bab68fee7-5b1e-432f-8152-5d7bc14eea95

С уважением, Алексей.

**Comment by SlashSep** [comment]
Добрый день!
GetFullVersion возвращает: COM x64 5.36.9.786
Только что пробовал принять аннулирование:
rc = -1073741819
DocGUID = 474c6fca-06c9-4297-a162-255f82a22718a1bcad3a-f33c-4a29-8c67-af598142d4c4
Organization = 02cd8398df764ead9e1d966d85512641@diadoc.ru

Ошибка: ODSOLE Extended Procedure. Исключение при выполнении кода:  EXCEPTION_ACCESS_VIOLATION

С уважением, Алексей.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Попробуйте с версией компоненты 5.37.2.823

**Comment by SlashSep** [comment]
Добрый день!
После обновления компоненты до версии 5.37.2.823 - все заработало!
Большое спасибо!

С уважением, Алексей.
