### ISSUE TITLE
ВАЖНО! ПРОБЛЕМА! Ошибка в работе компонент АПИ 5.36.9.786 через регламентные задания - постоянно вылетает и перезапускается rphost.exe

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#770]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
КПП2: 783450001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: COM x64 5.36.5.760.

### При попытке перехода на версию COM x64 5.36.9.786 столкнулись с очень серьезной проблемой!

У нас работа с ЭДО происходит на отдельном сервере в кластере серверов основной БД 1С. 
Вся работа с ЭДО происходит через работу регламентных (фоновых) заданий, запускаемых на этом сервере.

С версиями компонент АПИ до 5.36.5.760 включительно никаких проблем не было.

При попытке работы с версией компонент АПИ 5.36.9.786 (DiadocCom_5_36_9_786.dll, DiadocCom_5_36_9_786_x64.dll) наблюдается и воспроизводится следующая проблема:

**На сервере ЭДО запускается rphost.exe, работает примерно от 40 до 90 секунд и после этого вылетает. Затем запускается снова, работает те же 40-90 секунд - и вылетает. Т.е. происходит постоянное прерывание в работе фоновых ЭДО.** 

При этом, пока фоновые работают и rphost ещё не вылетел, происходит подключение по АПИ к Диадок, иногда даже что-то успевает выполнится... и далее следует вылет и начинается всё сначала. То, что подключение происходит видно по логам. 

**Пример лога №1:**
_01.03.2022 12:19:53 - АПИ Диадок. Версия: [5.36.9.786]
01.03.2022 12:19:53 - Установлено соединение по сертификату: [ID000037, Ярошенко Игорь Евгеньевич]
01.03.2022 12:19:53 - Выполнено подключение к организации: [ООО "ДНС РИТЕЙЛ"]
01.03.2022 12:19:53 - глЭДО_Обертки_Organization_CreatePackageSendTask2. Организация = [ООО "ДНС РИТЕЙЛ"], ID = [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru]_

здесь подключился и что-то даже начал делать.

**Пример лога №2:**
_01.03.2022 12:20:46 - АПИ Диадок. Версия: [5.36.9.786]
01.03.2022 12:20:47 - Установлено соединение по сертификату: [ID000026, Попов Алексей Геннадьевич]_

здесь успел только подключиться.

**Пример лога с предыдущей работающей версии:**
_01.03.2022 0:01:11 - АПИ Диадок. Версия: [5.36.5.760]
01.03.2022 0:01:11 - Установлено соединение по сертификату: [ID000026, Попов Алексей Геннадьевич]
01.03.2022 0:01:17 - Выборка [1] - Выбрано cобытий: 44 шт.
01.03.2022 0:01:17 - Выборка [2] - Выбрано cобытий: 0 шт.
01.03.2022 0:01:17 - Формирование операций по сертификату [ID000026]
01.03.2022 0:01:17 - Для организации [ООО "ДНС РИТЕЙЛ"] по ID = [bb46b9a8-a757-43e5-bf0f-5dc17c306b9e] сделано выборок событий [1]. Найдено и обработано [44] новых событий. Создано [28] новых операций.
01.03.2022 0:01:17 - ### Регламентный Документооборот по СФ:
01.03.2022 0:01:17 - Запущен регламентный ДО СФ для организации [ООО "ДНС РИТЕЙЛ"]
01.03.2022 0:02:18 - Остановлен регламентный ДО СФ для организации [ООО "ДНС РИТЕЙЛ"]
01.03.2022 0:02:18 - Начало: 00:01:11, Окончание: 00:02:18, Затрачено: 00:01:07. Обработано событий: 44, Создано операций: 28._

здесь всё выполнилось + видна точная фиксация окончания выполненного подключения.

### Важно!
Ситуация на 100% воспроизводима.
При откате на версию 5.36.5.760 всё работает без каких-либо проблем. При переходе на версию 5.36.9.786 сразу же начинаются вышеуказанные проблемы.

При этом локальное использование версии 5.36.9.786 без запуска через фоновые задания, через ручной поштучный запуск тех или иных действий - например, получения списка документов, получение данных документа или его печатной формы и т.д. - происходят без каких-либо проблем.

Проблема возникает именно при работе в фоновом режиме на сервере. 
При этом, еще раз напомню, что с версией 5.36.5.760 при такой фоновой работе на сервере нет вообще никаких проблем!

### Огромная просьба

Пожалуйста, рассмотрите данную проблему как можно быстрее. Очень хотелось бы разобраться в причинах и сделать так, чтобы всё работало так же, как сейчас работает для версии 5.36.5.760 (и тех, что были раньше).

В ближайшие дни со своей стороны постараемся сделать версию нашего функционала для возможности запуска и проверки поведения для версии 5.37.0. Обязательно оповестим вас о результатах.

**Очень ждем ваши ответы и комментарии по данной проблеме!**

Спасибо.

**Comment by JohnSergeev** [comment]
**Дополнительно:**
Если для разбора проблемы будет полезно, чтобы мы проверили поведение компоненты АПИ промежуточных версий 5.36.6, 5.36.7, 5.36.8, чтобы определить начиная с какой версии воспроизводится проблема - напишите, пожалуйста, мы выделим время и ресурсы и всё проверим.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Для решения проблемы нужен дамп в момент падения

**Comment by JohnSergeev** [comment]
Добрый день. Оно падает с интервалом 40-90 секунд (это я про rphost).

Можете точно объяснить - каким инструментом и как снять дамп, и куда и в каком виде его передать?

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Можно использовать, например, [procdump -e -ma -w <process_name>](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump)  или настроить в 1С [сбор технологического журнала](https://programmist1s.ru/nastroyka-tehnologicheskogo-zhurnala-1s/)

**Comment by JohnSergeev** [comment]
Спасибо.

Сбор тех. журнала скорее всего не получится - он у нас в реалтайме уже собирает кучу разных метрик и перенастраивать его на сбор дампа скорее всего не станут. Попробуем procdump'ом именно на сервере ЭДО.

Единственное - это потребует синхронизации с командой администрирования + сейчас у нас уже подкрадывается время, когда запад просыпается и начинает массово сыпать документы. Поэтому мы попробуем подготовится и всё "поломать" на время завтра утром, когда на западе ночь и нагрузка по ЭДО минимальная.

Куда результаты скидывать? 

И повторю вопрос - может попробовать поведение промежуточных версий 5.36.6, 5.36.7, 5.36.8, чтобы более точно понять с какого момента проявляется проблема?

**Comment by GilimkhanovDenis** [comment]
Дамп можно загрузить на гугл-диск и сюда написать его ссылку. Или, если есть какие-то опасения, то ссылку отправить через техподдержку [diadoc@skbkontur.ru](mailto:diadoc@skbkontur.ru), а здесь указать номер обращения, который Вам там дадут

Если проверить другие версии не сложно, то можно попробовать. Можно ещё попробовать версию 5.37.0 - вдруг мы случайно исправили то место, которое вызывает падение

**Comment by JohnSergeev** [comment]
Дампы попробуем собрать сегодня. Уже начали работу.
Как отправить разберемся когда будут дампы.

Версии промежуточные попробуем после.

Версию 5.37.0 хотим попробовать. Но там, к сожалению, слишком мажорные изменения - нам сперва нужно будет несколько мест переписать у себя, чтобы вообще с ней запуститься. Поэтому с ней получится скорее всего ближе к концу недели.

**Comment by GilimkhanovDenis** [comment]
Да, понимаю. Там действительно много ключевых изменений

Будем ждать дамп

**Comment by JohnSergeev** [comment]
Важная информация. Проверили поведение версии DiadocCom_5_36_8_783 - с ней проблем нет, фоновые работают нормально.

Так что проблема получается происходит только в версии DiadocCom_5_36_9_786.

Сейчас попробуем с нее дампы поснимать.

**Comment by JohnSergeev** [comment]
На DiadocCom_5_36_9_786 проблема еще раз воспроизвелась.

Админы поснимали дампы rphost в течение какого-то времени, пока он работал, падал и начинал работать снова.
Дампы они снимали с помощью Windows Error Reporting. Сказали, что в этих дампах только стека потоков, хипа там нет.

Мы не можем на 100% гарантировать, что в эти дампы попала информация на момент падения rphost'ов. Но надаемся, что это так и дампы помогут.

Ссылка на архив дампов: https://disk.yandex.ru/d/NE2eXs62XUuZBA

Денис, у нас тут немножко замудрили с секретностью - архив под паролем. Укажите, пожалуйста, почту или еще что, куда я могу выслать пароль на архив дампов, не засвечивая его здесь. Спасибо.

**Comment by GilimkhanovDenis** [comment]
Напишите, пожалуйста в [техподдержку](mailto:diadoc@skbkontur.ru)

**Comment by JohnSergeev** [comment]
### Важное дополнение !

Админы посмотрели дампы через WinDbg и нашли там такое - очень похоже, что это и есть искомая проблема:

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 000007fed9446bd9 (DiadocCom_5_36_9_786_x64+0x0000000000286bd9)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: ffffffffffffffff
Attempt to read from address ffffffffffffffff

DEFAULT_BUCKET_ID:  INVALID_POINTER_READ

PROCESS_NAME:  rphost.exe

FOLLOWUP_IP: 
DiadocCom_5_36_9_786_x64+286bd9
000007fe`d9446bd9 8b4208          mov     eax,dword ptr [rdx+8]

READ_ADDRESS:  ffffffffffffffff 

ERROR_CODE: (NTSTATUS) 0xc0000005 - <Unable to get error code text>

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - <Unable to get error code text>

EXCEPTION_CODE_STR:  c0000005

Надеемся, это поможет.

**Comment by JohnSergeev** [comment]
по теххподдержке - ок, понял. Сейчас сделаю.

**Comment by JohnSergeev** [comment]
Письмо в поддержу отправил. Только что-то от них никакого номера тикета не было пока

**Comment by JohnSergeev** [comment]
Добрый день!
 
Информацию сотрудникам поддержки GitHub передали, вопрос в работе.
 
Номер вашего обращения - 44844801.

**Comment by JohnSergeev** [comment]
Денис, напишите, пожалуйста, как всё получите и успешно распакуете - чтобы мы знали, что всё не застопорилось где-то посредине. Спасибо.

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev 
Письмо получил. смотрю дамп

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev ,  добрый день

Должно полечиться на версии 5.37.2.823

**Comment by JohnSergeev** [comment]
Ясно. Спасибо. 

Сейчас готовим изменения для возможности запуска 5.37.xx версий - как сделаем, так проверим и отпишемся в обязательном порядке. Скорее всего уже после праздников.

**Comment by JohnSergeev** [comment]
Добрый день.
Проверили на версии **Com_5_37_3_825**.

Ошибка не воспроизводится, фоновые работают без проблем уже более 4 часов.

Спасибо!
