### ISSUE TITLE
Вопрос по работе с МЧД в версии 5.37.xx - можно ли использовать эту версию компоненты, если пока еще с МЧД не работаем? Как использовать МЧД при работе в тестовых ящиках?

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#771]
Добрый день.

Появилось несколько вопросов по версии 5.37.:

### №1
А вот в этой новой версии АПИ можно теперь работать ТОЛЬКО с использованием МЧД? И по другому никак?
Или можно работать и с использованием МЧД, и без использования МЧД (типа, как сейчас, "по-старому")?

Это важно, т.к. непонятно - можно ли вообще переходить на эту версию АПИ, если пока в работе МЧД еще не используются?

### №2
А вот у вас есть тестовые организации (ящики) - очень удобная штука для тестирования.

Как при тестировании и работе с тестовыми организациями использовать МЧД? Где их брать? Какие они могут быть?

Может быть есть тестовые МЧД, которые можно использовать при работе с тестовыми организациями? Или, может быть планируется их появление? Если что-то такое есть, то как такие МЧД для тестирования можно получить?

Или для работы в тестовых организациях нужно каким-то образом получать и использовать реальные МЧД?
Как это можно сделать?

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Отвечу на первый вопрос:
Можно работать и по-старому. В тасках появилось новое поле `PowerOfAttorneyToAttach` - если его не заполнять, тогда МЧД использоваться не будет, то есть будет старое поведение. В этом месте компоненты обратно совместимы

Но обратите внимание, что были удалены методы объекта [DocumentBase](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentBase.html), в которых происходило подписание каких-либо сущностей (кроме подписания ИоП). Если эти методы использовались, то нужно перейти на [CreateReplySendTask2](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentBase.html#DocumentBase.CreateReplySendTask2)

**Comment by kulakovskaya** [comment]
Добрый день!
На текущий момент реализовать схему тестирования работы с машиночитаемыми доверенностями нельзя. В [документации](https://support.kontur.ru/pages/viewpage.action?pageId=83873849) для сервиса Контур.Доверенности подробно описана схема работы. Рекомендуем следить за обновлениями сервиса.

**Comment by JohnSergeev** [comment]
За ссылку на документацию спасибо.

Но, всё-таки не понятно - как можно на текущем этапе начать внедрение работы с МЧД? Только сразу без всякого тестирования, что называется "без права на ошибку, сразу по-белому"? Или как?

Можно где-то увидеть, скажем так, схему работы с МЧД в смысле - как организуется процесс с нуля? 
Как можно работать с АПИ на начальном тестовом этапе, с учетом того, что вы говорите, что работать с МЧД в тестовых организациях сейчас нельзя?

Невозможность использования МЧД при тестировании - это будет всегда или это просто не реализовано на текущий момент и в дальнейшем появиться? Если да, то когда - хотя бы ориентировочно?

Спасибо.

**Comment by kulakovskaya** [comment]
Добрый день! На текущий момент такой схемы нет. Действительно, тестировать можно только с реальными доверенностями. Такое поведение обусловлено различными ограничениями со стороны блокчейна ФНС. 
Скажите, пожалуйста, когда ваша компания планирует переходить на схему обработки документов с МЧД?

**Comment by dimok22prog1** [comment]
Коллеги, в продакшен неудобно выкладываать такое. Есть варианты?

**Comment by JohnSergeev** [comment]
Мы пока малость прифигели от такого подхода. 

Ну и получается, что Диадок тут не вставляет нам, пользователям, палки в колёса, а сам тоже, скорее, жертва обстоятельств... 

Сейчас мы прорабатываем вариант с "тестовой" отправкой **реально значимых** документов от одного юр. лица к другому с последующим аннулированием этих документов. Другие варианты пока вообще в голову не приходят. Нам тут несколько проще, т.к. у нас есть несколько своих юр. лиц и поэтому "шалить" в таком ключе нам... ну, типа, менее страшно.

Если у кого-то есть, какие-то другие варианты тестирования работы с МЧД, то, пожалуйста, напишите в эту ветку, какой вы видите реализацию тестирования работы с МЧД при указанных ранее ограничениях?

Спасибо.

**Comment by IrinaShmonina** [comment]
@JohnSergeev @dimok22prog1 , добрый день.
Актуально ли для вас тестирование работы с МЧД? 
Если да, то можно обратиться к вашим менеджерам с запросом на тестирование МЧД
