### ISSUE TITLE
Работа с МЧД

### ISSUE THREAD

**Issue by dimok22prog1** [diadoc/diadocsdk-1c-docs#772]
Добрый вечер. Прочитал о добавлении в последней версии компоненты возможности работы с МЧД.
Но, насколько понял, можно использовать МЧД уже выпущенные, зарегистрировав с помощью Organization.RegisterPowerOfAttorneyByContent(XmlContent, XmlSignature).
Подскажите, а кто и как их выпускает? Как получить XmlContent? Как получить XmlSignature (это же подпись ГД на токене)?

_Originally posted by @dimok22prog1 in https://github.com/diadoc/diadocsdk-1c-docs/issues/708#issuecomment-1055437386_

**Comment by dimok22prog1** [comment]
Если я правильно понял, то 
XmlContent это xml-файл установленного формата, который может формировать кто угодно, преобразованный в виде base64 строки?
XmlSignature:	это отпечаток сертификата генерального директора на токене в виде base64 строки?

А операцию Organization.RegisterPowerOfAttorneyByContent(XmlContent, XmlSignature) выполнять при подключении по сертификату генерального директора.

**Comment by GilimkhanovDenis** [comment]
Добрый день

XmlSignature это контент файла подписи (*.sig, *.sgn и т.п.), который был сформирован при выпуске МЧД

Выпустить МЧД можно, например, через [Контур.Доверенности](https://m4d.kontur.ru/poa)
[справка](https://support.kontur.ru/pages/viewpage.action?pageId=83873849)

**Comment by dimok22prog1** [comment]
То есть МЧД может быть выпущена только через сторонний сервис, при выпуске будет сформирован контент файла подписи (XmlSignature) и xml-файл установленного формата (XmlContent )?

**Comment by GilimkhanovDenis** [comment]
Да

**Comment by dimok22prog1** [comment]
Получается, что если МЧД была выпущена через сервис Контур.Доверенности, все равно нужно ее единоразово регистрировать через [Organization.RegisterPowerOfAttorneyByContent()] для использования в Диадок? Или после выпуска через Контур.Доверенности она сразу будет доступна к использованию через [MyEmployee.GetPowersOfAttorney()]?

**Comment by dimok22prog1** [comment]
Подскажите, не планируется ли доработок компоненты для автоматизации выпуска МЧД. Т.е., мы готовим xml установленного формата и и передаем его при подключении по сертификату генерального директора вместе с отпечатком его сертификата (по аналогии с подписанием документов)?

**Comment by GilimkhanovDenis** [comment]
Да, вызвать метод необходимо (по крайней мере пока). Если МЧД уже зарегистрирована, то вернётся соответствующий ответ.


В ближайших планах такой задачи нет

Если такая функциональность необходима, то предлагаю эту задачу озвучить менеджеру, чтобы он её защищал/продвигал среди прочих задач
