### ISSUE TITLE
Вопрос по новой функции АПИ 5.37.хх - PersonalCertificate.SetPin()

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#774]
Добрый день.

Хотелось бы получить более детальную информацию по новой функции:
![изображение](https://user-images.githubusercontent.com/33707226/156872854-fbccf794-c174-45ee-aeee-da936914d01d.png)

Правильно ли мы понимаем, что этот функционал предназначен для того, чтобы можно было сделать что-то подобное:
1. При установке или копировании ЭЦП с флешки в реестр компьютера в КриптоПро мы устанавливаем для копии ЭЦП в реесте какой-то новый пароль - например "12345".
2. В дальнейшем при подключении к ЭДО по этой ЭЦП - у нас КриптоПро постоянно запрашивает пароль. 
3. Поэтому мы с помощью PersonalCertificate.SetPin("12345") для данного ЭЦП "запоминаем" пароль. 
4. И при последующих подключениях у нас пароль уже не запрашивается, т.к. компонента теперь его сама подставляет в ответ на запрос КриптоПро.
5. И мы получаем, что и "лишний раз мучатся с постоянным вводом пароля" не надо. И при этом сами скопированные ЭЦП более защищены, т.к. на них задан пароль и их без него уже не используешь.

Или это не просто "запоминание" установленного пароля для ЭЦП для удобства подключения, а именно сама установка пароля на ЭЦП? Т.е. если для ЭЦП в реестре вызвать PersonalCertificate.SetPin("12345"), то на него будет установлен пароль "12345" и сама ЭЦП в реестре теперь будет под этим паролем - безотносительно с Диадоком или еще как её теперь будут пытаться использовать?
Если это так - то пароль при каждом подключении будет запрашиваться? Или будет подставляться автоматически?

Или мы вообще неверно понимаем суть и предназначение данного метода?
Тогда что именно он делает и для чего предназначен?

**Дополнительно:**
Если это сохранение пароля для последующей автоматической его передачи в КриптоПро при подключении по запароленной ЭЦП, то сразу возникает вопрос:
А введенный пин - он где храниться? На локальной машине где он введен? Или он куда-то в ваш сервис по сети "уезжает" и при попытке подключения мы получаем его по сети обратно? А локально у нас на компьютере (и вообще нигде) его нет?

Другими словами - как и насколько полно организована безопасность хранения введенных таким образом пинов?

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Данная функциональность предназначена только для того, чтобы компонента попыталась автоматически ввести пинкод/пароль для контейнера, если КриптоПро его запросит. Не изменяет установленный  на контейнер пароль

Запоминается пинкод/пароль только на время жизни объекта [PersonalCertificate](https://1c-docs.diadoc.ru/ru/latest/ComObjects/PersonalCertificate.html).

Если не использовать метод [PersonalCertificate.SetPin(Pin)](https://1c-docs.diadoc.ru/ru/latest/ComObjects/PersonalCertificate.html#PersonalCertificate.SetPin), но пинкод на контейнер установлен, то КриптоПро попытается показать своё стандартное окно для ввода пинкода.
Иногда показ такого окна невозможен. В частности при выполнении регламентного задания 1С устанавливает тихий режим и блокирует показ соответсвующего окна, что приводит к ошибке.

Аналогичное поведение было и раньше, но выполнялось неявно - в методе [DiadocApi.CreateConnectionByCertificate](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html#DiadocAPI.CreateConnectionByCertificate) за ввод пинкода отвечал второй параметр

С появлением новых методов (в частности методов в [AdminTools](https://1c-docs.diadoc.ru/ru/latest/ComObjects/AdminTools.html)) хотелось оставить возможность использовать любой объект `PersonalCertificate`, но не переусложнять интерфейсы всех методов, где нужен сертификат дополнительным параметром.


Небольшое пояснение на примере метода [DiadocApi.CreateConnectionByCertificate2](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html#DiadocAPI.CreateConnectionByCertificate2) как альтернативы [DiadocApi.CreateConnectionByCertificate](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html#DiadocAPI.CreateConnectionByCertificate)
Один из возможных сценариев:

1. запрашивается список сертификатов, установленных в хранилище "Личные"  [DiadocApi.GetPersonalCertificate](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html#DiadocAPI.GetPersonalCertificate) 
2. пользователь выбирает нужный ему сертификат
3. интеграция запрашивает у выбранного сертификата поле Thumbprint и передаёт в метод авторизации [DiadocApi.CreateConnectionByCertificate](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html#DiadocAPI.CreateConnectionByCertificate)

Обращение к хранилищу происходили на 1 и на 3 шаге

В новом варианте информация о сертификате уже приходит в метод авторизации и обращаться к хранилищу дополнительно не приходится.

Аналогичная ситуация для всех новых методов, принимающих [PersonalCertificate](https://1c-docs.diadoc.ru/ru/latest/ComObjects/PersonalCertificate.html) в качестве параметра
