### ISSUE TITLE
Ошибка DocumentBase.Resolutions

### ISSUE THREAD

**Issue by blender5** [diadoc/diadocsdk-1c-docs#775]
Добрый день! При обращении к DocumentBase.Resolutions или GetResolutions() получаю ошибку.  (DocumentBase.Resolutions): invalid map<K, T> key.
из 22 тысяч документов с такой проблемой столкнулся в 60.

версия компоненты 5_36_9_786_x64

**Comment by blender5** [comment]
версия компоненты 5_36_9_786_x64

**Comment by GilimkhanovDenis** [comment]
Добрый день

обновите компоненту до последнего релиза

**Comment by GilimkhanovDenis** [comment]
К слову, лучше использовать метод GetResolutions - функциональность та же самая, а поле помечено устаревшим

**Comment by blender5** [comment]
Спасибо, проверю.

Мне показалось, что GetResolutions() работает медленней.

но уже использую его.
