### ISSUE TITLE
ОШИБКА! Неправильная работа методов GetCounteragentListByStatus() и GetCounteragentListByStatusAsync() - неверная обработка входящих параметов + в результете возвращаются не все контрагенты с запрашиваемым статусом, а только какая-то их часть, искусственно ограниченная в количестве

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#776]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.37.3.825**.

### Обнаружили большую и очень критичную проблему!

На текущий момент неправильно работают методы АПИ:
1. Organization.GetCounteragentListByStatus()
2. Organization.GetCounteragentListByStatusAsync()

Причем они неправильно работают, скажем так, в нескольких "типах" неправильности!

### Ошибка типа №1. Неправильная обработка параметров функций
Это заметили еще в январе, но сумели обойти замеченную проблему, переделав свой код, и поэтому не обращались к вам.
Но, теперь, с учетом обнаружения ошибок типа №2 (см. далее), решили и на этот момент обратить ваше внимание.

Суть:
**Описание параметров этих методов у вас в документации не соответствует действительности!**

Смотрим описание методов в документации:
![изображение](https://user-images.githubusercontent.com/33707226/157820618-ed7158e7-71e2-4694-9d26-159856d3eb0e.png)

Ссылка "Возможные значения" ведет к:
![изображение](https://user-images.githubusercontent.com/33707226/157820114-6ebab6ec-f345-475b-a7cd-7b58ce7976c8.png)

Однако, при попытке вызова этих методов с вышеуказанными параметрами, получаем:

**UnknownCounteragentStatus**
ОШИБКА!
_"MyBox.GetCounteragentListByStatus): ##100[Ошибка сервера Диадок]code:400, HTTP error: counteragentStatus: Could not parse query param: UnknownCounteragentStatus"_

**IsMyCounteragent**
ОК. Работает.

**InvitesMe**
ОК. Работает.

**IsInvitedByMe**
ОК. Работает.

**RejectsMe**
ОШИБКА!
_"MyBox.GetCounteragentListByStatus): ##100[Ошибка сервера Диадок]code:400, HTTP error: counteragentStatus: Could not parse query param: RejectsMe"_

**IsRejectedByMe**
ОШИБКА!
_"MyBox.GetCounteragentListByStatus): ##100[Ошибка сервера Диадок]code:400, HTTP error: counteragentStatus: Could not parse query param: IsRejectedByMe"_

**NotInCounteragentList**
ОШИБКА!
_"MyBox.GetCounteragentListByStatus): ##100[Ошибка сервера Диадок]code:400, HTTP error: counteragentStatus: Could not parse query param: NotInCounteragentList"_

**Т.е. из 7 указанных в документации параметров правильно работают только 3!**

При этом, что довольно забавно, работает еще один параметр, вообще не указанный в документации!

Мы на то, что он работает нарвались случайно, т.к. в каких-то "древних" версиях что-то типа от 2018 года он был в документации упомянут. И, нарвавшись на вышеуказанные ошибки, совершенно случайно, методом "тыка", попробовали и его. И оказалось, что он прекрасно продолжает работать!

Это параметр **"Rejected"**.

По нему получаются контрагенты со статусами "RejectsMe" и "IsRejectedByMe" - и те, и другие сразу "одной кучей".

Подобное поведение стабильно воспроизводится на всех версиях АПИ, как минимум начиная с 5_36_5_760 и заканчивая 5_37_3_825.

**Резюме по ошибкам типа №1:**
Налицо полное несоответствие документации и реальной работы методов получения списка контрагентов организаций по статусу контрагента.

**Хотелось бы, чтобы поведение функций было бы приведено в соответствие с документацией.**

Теперь переходим к гораздо более серьезной ошибке:

### Ошибка типа №2. Неправильные результаты функций - возвращаются не все данные по контрагентам

Сроки возникновения этой ошибки, к сожалению, очень не точные, т.к. мы заметили проблему явно не сразу после её возникновения, а, скорее, по реакции пользователей на некоторые "странности" в учете работы контрагентов учетной системы в ЭДО. Плюс мы сперва подумали, что проблема заключается в коде на нашей стороне и поэтому не спешили с обращениями к вам. Но 11.03.2022 окончательно поняли, что это явно проблема на вашей стороне.

Поэтому - очень приблизительно - возникла эта проблема где-то в начале февраля. Скорее всего.

Суть:
Вызов методов GetCounteragentListByStatus() и GetCounteragentListByStatusAsync() с ЛЮБЫМИ параметрами или без оных возвращает в результате своей работы какой-то список контрагентов. Всё, как указано в документации... 

**вот только это ДАЛЕКО НЕ ВСЕ наши контрагенты, с указанным в параметрах статусом!**

У нас сейчас примерно 92 тысячи контрагентов только по "ДНС Ритейл". И ранее вызов вышеуказанных методов возвращал полные списки контрагентов.

**Однако, разбор проблемы показал, что сейчас это не так!**
Такое ощущение, что на текущий момент действует какое-то недокументированное ограничение в ~10 тысяч контрагентов.
И с любыми параметрами или без оных возвращается всегда какой-то список размером не более чем примерно 10.000 записей.

При этом очень похоже, что дело не в какой-то ошибке в АПИ, а в изменении поведения самой функции с какого-то момента. Как мы понимаем, вызов данных методов через АПИ для 1С ведет к дальнейшему вызову какого-то вашего уже внутреннего функционала по получению списка контрагентов. И вот, очень похоже, что где-то на этом "глубоком" уровне что-то поменяли или "оптимизировали". 

Почему мы так думаем - мы проверили поведение этих функций на нескольких "старых" версиях АПИ, докатившись в истории вплоть до версии 5_31_2_611 - и сейчас на всех версиях от нее и до текущей 5_37_3_825 поведение этих методов одинаковое - возвращается каждый раз не более 10.000 контрагентов.

Например, конкретно по "ДНС Ритейл" вызов этих функций без параметров возвращает всегда 9997 контрагентов в списке.

А еще в начале года они возвращали всех контрагентов организации без каких-либо ограничений.

Пример:
Вызываем функцию GetCounteragentListByInnKpp() с указанием ИНН 4703119938. И получаем список из двух наших контрагентов:
![изображение](https://user-images.githubusercontent.com/33707226/158086110-83295be3-74f3-42cb-a264-1c163adc69f1.png)
В данном случае нас интересует контрагент №2 из списка (выделен цветом).

Если теперь мы вызовем GetCounteragentListByStatus() и GetCounteragentListByStatusAsync() без параметров для получения списка всех наших контрагентов вообще, то мы получаем списки из 9997 контрагентов. И в этих списках контрагент №1 будет присутствовать. А контрагент №2 - нет.

А если мы затем вызовем GetCounteragentListByStatus() и GetCounteragentListByStatusAsync() с параметром "IsMyCounteragent" для получения списка наших контрагентов, с которыми установлены отношения, то мы получаем списки... опять из 9997 контрагентов! Хотя при предыдущем вызове без параметров в результирующем списке из 9997 контрагентов были контрагенты с разными статусами, а не только со статусом "IsMyCounteragent". Уже одно это показывает, что возвращаются не все имеющиеся данные!
И снова - в этих полученных списках контрагент №1 будет присутствовать. А контрагент №2 - нет.

Мы даже сперва подумали, что проблема заключается в отсечении всех контрагентов в роуминге. Но проверка показала, что дело не в этом. Просто возвращается список, по какой-то причине искусственно ограниченный в размере.

Т.е. ф-я получения списка контрагентов по ИНН и КПП отрабатывает верно - показывает всех наших контрагентов с заданным ИНН. А вот функции получения списка контрагентов по статусу возвращают только какую-то часть нашего списка контрагентов.

**Очень сильное ощущение, что просто действует какое-то внутренне ограничение на размер списка. Причем еще в начале года такого ограничения не было и списки контрагентов возвращались полностью.**

Самая большая проблема сейчас в том, что **вообще не осталось способа получения полного списка своих контрагентов в ЭДО!**

Не перебирать же нам всех наших контрагентов (из нашей учетной системы) по ИНН и КПП обращениями к АПИ через GetCounteragentListByInnKpp() в попытке проверить - а нет ли его среди наших контрагентов в ЭДО...

**Резюме по ошибкам типа №2:**
На текущий момент функции GetCounteragentListByStatus() и GetCounteragentListByStatusAsync() явно работают... ну, как минимум, крайне странно. А в общем-то - просто неправильно.

Огромная просьба исправить работу функций GetCounteragentListByStatus() и GetCounteragentListByStatusAsync() так, чтобы они соответствовали документации и возвращали данные по всем контрагентам организации в ЭДО с заданным в параметрах вызова статусом, а не только по какой-то их искусственно ограниченной части.

Если же это (крайне странное!) ограничение на количество возвращаемых данных по какой-то причине вы убирать не собираетесь, то, пожалуйста, укажите это явным образом:
1. В данной переписке (и было бы очень здорово увидеть хоть какую-то аргументацию для такого решения). Чтобы нам было понятно, что возврата к нормальному поведению уже не будет и мы начали что-то придумывать для обхода проблемы с учетом и контролем наших контрагентов ЭДО на своей стороне.
2. В документации к методам GetCounteragentListByStatus() и GetCounteragentListByStatusAsync(). Чтобы было понятно, что на возвращаемые данные есть ограничение, и чтобы было понятно в чём именно это ограничение выражается.

Очень надеемся на скорое исправление замеченных проблем.
Особенно критична текущая невозможность получения полного списка своих контрагентов!

Спасибо.

**Comment by JohnSergeev** [comment]
Добрый день!

Хотелось бы получить хоть какую-то вашу реакцию на описанную проблему.

Сейчас всё очень плохо еще и потому, что мы не только не контролируем состояние отношений с теми контрагентами ЭДО, которые уже внесены в нашу учетную систему - это полбеды.

Но мы вообще не видим тех контрагентов, которые "новые", т.е. установившие с нами отношения уже после появления вышеописанной проблемы. Т.к. по АПИ в обрезанном списке контрагентов их нет, то мы даже не знаем, что кто-то с нами устанавливает отношения и уже работает по ЭДО.

**Comment by GilimkhanovDenis** [comment]
Добрый день

ограничение в 10000 контрагентов исправим в ближайшее время (предположительно без обновления компоненты)

поиск контрагентов по статусам исправим в ближайшем фиксе

**Comment by GilimkhanovDenis** [comment]
Добрый день

ограничение в 10000 контрагентов снято

**Comment by JohnSergeev** [comment]
Добрый день.

Подтверждаем, работает:
![изображение](https://user-images.githubusercontent.com/33707226/158521930-2e0ee8de-8ce5-4843-a7cb-2b32443ab726.png)

Огромное спасибо!

Теперь осталось дождаться исправления обработки параметров и вообще хорошо будет.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Доработали возможные параметры метода в [5.37.4](https://1c-docs.diadoc.ru/ru/latest/History/release_info/5_37_4.html)
