### ISSUE TITLE
Некорретное отображение уступочной надписи в веб-версии Диадок

### ISSUE THREAD

**Issue by AlexProgz** [diadoc/diadocsdk-1c-docs#778]
Добрый день, уважаемые коллеги.
У меня такая же проблема с отображением уступочной надписи.
Ситуация аналогичная той, которая описана в https://github.com/diadoc/diadocsdk-1c-docs/issues/438
Версия модуля 1С 5_47_01 и на 5_48_01 пробовал.

**Как заполнить уступочную надпись в модуле 1С, чтобы в веб-версии Диакдок надпись была в шапке в самом верху?**

Вот пример кода в подключаемом модуле:
///////////////////////////////////////////////////////////////////////////////
ТекстШапки = "Требование по оплате данной поставки уступлено обществу с ограниченной ответственностью «РБ Факторинг». Любое решение относительно прекращения, изменения или исполнения Требования подлежит согласованию с названным фактором. Все платежи на основании настоящего документа должны перечисляться Вашей компанией на: получатель ООО «РБ Факторинг», ИНН 7706677277,КПП 770801001, Банк получателя: ПАО РОСБАНК, г. Москва, ИНН 7730060164 КПП 997950001, БИК 044525256, к/сч 30101810000000000256, р/сч 40702810500000061566.";
ДополнитьМассивKeyValue(Протоконтент.AdditionalInfoId.StructedAdditionalInfos, "Внимание", ""+ТекстШапки+"");

///////////////////////////////////////////////////////////////////////////////

**Comment by AlexProgz** [comment]
Теперь скриншоты с проблемой:
![Версия модуля Диадок](https://user-images.githubusercontent.com/54399625/159483344-6ab5b398-31ee-4d97-a9ac-9535d39f1386.jpg)

**Comment by AlexProgz** [comment]
Вот как в веб-версии отображается надпись с т
![Документ УПД в Контур Диадок при загрузке сохраненного на диск xml файла_верх](https://user-images.githubusercontent.com/54399625/159483491-8f2fdcd6-2dea-4725-8a59-2715d0b762ba.jpg)
![Документ УПД в Контур Диадок при загрузке сохраненного на диск xml файла_низ](https://user-images.githubusercontent.com/54399625/159483496-af8d6069-e8ea-470a-90f3-0aaef8a3dd5b.jpg)
егом <head>

**Comment by AlexProgz** [comment]
в 1С надпись отображается корректно в шапке:
![Рисунок1](https://user-images.githubusercontent.com/54399625/159486102-4e1f94d1-2213-44e1-bac8-ca765d004c24.png)

**Comment by AlexProgz** [comment]
Вопрос перенаправил и создал в отдельной ветке https://github.com/diadoc/diadocsdk-1c-docs/issues/778

**Comment by ilzag** [comment]
Добрый день.
Печатная форма в вебинтерфейсе не учитывает наличие тега `<head>...</head>`.
Для того, чтобы настроить печатную форму, существует отдельная услуга "Кастомная печатная форма" (КПФ). За подробностями рекомендуем обратиться к вашему менеджеру по Диадоку.
