### ISSUE TITLE
Функции в UniversalTransferDocumentRevision

### ISSUE THREAD

**Issue by ElenaBurnasheva** [diadoc/diadocsdk-1c-docs#780]
Здравствуйте. 
При попытке отправить UniversalTransferDocumentRevision с функцией СЧФДОП возникла следующая ошибка:
Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: Невозможно отправить документ с функцией ДОП/СЧФДОП/СвРК/СвЗК. Измените функцию документа или выберите другой тип документа.

В описании форматов документов написано, что для UniversalTransferDocumentRevision возможно использование функции СЧФДОП.
 Как отправить с функцией СЧФДОП?

**Comment by GilimkhanovDenis** [comment]
Закрываю как дубль 
https://github.com/diadoc/diadocsdk-1c-docs/issues/787
