### ISSUE TITLE
Критическая ошибка компоненты версии 5.37.4.831

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#781]
1С:Предприятие 7.7 (27-й релиз), компонента версии 5.37.4.831.
При вызове метода Organization.GetCounteragentListByStatus() без передачи параметра 1С молча закрывается. В событиях Windows сообщения о краше не формируется.
До этого стояла 5.36.3.747. Все отрабатывало нормально.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Если падение происходит с любым значением параметра, скорее всего что-то с регистрацией компоненты. Попробуйте перерегистрировать компоненту

Если падение продолжается, то нужен будет дамп процесса. Можно собрать, например, с помощью https://docs.microsoft.com/en-us/sysinternals/downloads/procdump

`procdump -e -ma -w <process_name>`

**Comment by dorexpro** [comment]
У нас работа с компонентой обернута в класс 1С++. Собственно работа с классом ведется из модуля вынесенного во внешнюю обработку и запускаемого с помощью объекта ВыполняемыйМодуль. Падение замечено только в такой вот связке и только в этом методе. Если вынести вызов метода в обычную внешнюю обработку, то он выполняется нормально.
Дамп в какой момент предлагается собрать, если приложение просто закрывается без следов?

**Comment by GilimkhanovDenis** [comment]
В момент падения
флаг `-e` в команде
Write a dump when the process encounters an unhandled exception. Include the 1 to create dump on first chance exceptions
