### ISSUE TITLE
Ошибка при подключении по логину

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#782]
ДиадокСоединение = ДиадокАПИ.CreateConnectionByLogin("***","***");
по причине:
Произошла исключительная ситуация (DiadocApiInvoiceApi.CreateConnectionByLogin): WIN32[0x00002F8F]WinHttpSendRequest
One or more errors were found in the Secure Sockets Layer (SSL) certificate sent by the server:
- The function is unfamiliar with the Certificate Authority that generated the server's certificate
- SSL certificate common name (host name field) is incorrect
Подскажите, в чем может быть проблема?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Что-то произошло с SSL сертификатами, которые используются для установки соединения. Попробуйте пройти [диагностику](https://help.kontur.ru/diadoc) и выполните рекомендуемые действия.

Есть ещё вариант, что траффик идёт через прокси, которые расшифровывает траффик
Если это запланировано, то можно отключить проверку SSL сертификатов, установив поле VerifySslCertificate в [корневом объекте](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DiadocAPI.html) в Ложь

**Comment by GuninaY** [comment]
Дело было в установленном крипто про, сертификата у меня нет. Удалила, все заработало
