### ISSUE TITLE
Не полная поставка, информирование поставщика, что не доставлено

### ISSUE THREAD

**Issue by sbrros** [diadoc/diadocsdk-1c-docs#784]
Добрый день.
Подскажите, есть ли в типовом функционале  возможность отправить поставщику уведомление  с перечислением конкретных позиций, которые не были доставлены, условно 
Ариткул : 202
Наименование: Помидоры
Количество заказано: 10 кг
Доставлено: 9 кг

или есть только текстовые уведомления о расхождениях?

**Comment by sbrros** [comment]
В текстовом виде нашли возможность, но неужели нет никакой возможности передать в виде табличной части с кодами недопоставленного?

**Comment by kulakovskaya** [comment]
1. Для вышеописанного сценария подошел бы вариант с оформлением формализованного [акта о расхождениях Торг-2 в формате @423 приказа](https://normativ.kontur.ru/document?moduleId=1&documentId=348230). Но в типовом модуле данная функциональность не реализована, можно выполнить доработки в подключаемом модуле:
* [Как добавить Торг-2 в модуле](https://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Sozdanie_TORG-2.html)
* [Структура документа Торг-2](https://1c-pro-docs.diadoc.ru/ru/latest/TORG-2.html)

2. Также текст и структуру для запроса об уточнении тоже можно доработать в подключаемом модуле.
