### ISSUE TITLE
Вопрос по обработке для 1с (Модуль Диадок 1С Стандарт)

### ISSUE THREAD

**Issue by byunyar** [diadoc/diadocsdk-1c-docs#785]
Добрый день, мы пользуемся стандартной обработкой Диадок для 1с, конфигурация у нас бухгалтерия, сейчас нам нужно поменять алгоритм формирования наименования товара при отправке электронных УПД, подскажите куда копать в обработке или где про это узнать можно.

**Comment by DKneta** [comment]
Диадок берет для отправки упд наименование товара из номенклатуры документа (реализация товара) э если в накладной в колонке нет аименование  в поле прописано наименование + артикул от туда и берет. При обратной реализации (возврат от поставщика) может попасть наименование уже не ваше, там немного сложнее, нужно делать сопоставление

**Comment by byunyar** [comment]
У нас в реализации в товарах добавлен строковой реквизит "Подробно", в него записано нужное нам наименование, в каком модуле обработке нужно поправить, чтобы наименование бралось которое нужно там?
Просто у вас модули обработок для интеграции со стандартными конфигурациями запиханы в макеты, и поиском не найти:(

**Comment by volodkindv** [comment]
В данном репозитории обсуждаются вопросы, связанные с работой внешней компоненты для 1С.
В модуле есть режим отладки, при котором вложенные обработки выгружаются в каталог как обычные epf.
