### ISSUE TITLE
 Вопрос по печатной форме УПД, формируемой при открытии документа через обработку Диадок.

### ISSUE THREAD

**Issue by DmitryOLOLO2** [diadoc/diadocsdk-1c-docs#786]
Вопрос по печатной форме УПД, формируемой при открытии документа через обработку Диадок.
  Верно ли мы понимаем что печатная форма УПД формируется на сервере Диадок и передается нам на клиент как табличное поле? Дело в том что нам нужно изменить алгоритм получения номера ГТД (РНПТ). У нас структура данных немного отличается от стандартной структуры данных в УТ 10.
  В прошлой версии обработки мы нашли модуль, который отвечает за формирование печатной формы и там подправили в запросе чтобы ГТД подтягивалась и выводилась корректно. В новой версии, судя по коду, данные получаются из ядра обработки.
  Если табличное поле формируется на сервере Диадок то получается что нам нужно как-то по другому передавать поле ГТД при загрузке документа в Диадок, верно?

**Comment by volodkindv** [comment]
> Верно ли мы понимаем что печатная форма УПД формируется на сервере Диадок и передается нам на клиент как табличное поле?

Нет, не верно. 
Непонятно, о каком именно модуле вы пишете, но возможно, вам поможет эта [инструкция по отладке](https://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Kak_otlajivat'_vlojennye_obrabotki.html).
