### ISSUE TITLE
Ошибка при передачи UniversalTransferDocumentRevision!!!

### ISSUE THREAD

**Issue by ElenaBurnasheva** [diadoc/diadocsdk-1c-docs#787]
Здравствуйте.
При попытке отправить UniversalTransferDocumentRevision с функцией СЧФДОП возникла следующая ошибка:
`Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): #100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[0]: Невозможно отправить документ с функцией ДОП/СЧФДОП/СвРК/СвЗК. Измените функцию документа или выберите другой тип документа.`

В описании форматов документов написано, что для UniversalTransferDocumentRevision возможно использование функции СЧФДОП.
Как отправить с функцией СЧФДОП?

**Comment by GilimkhanovDenis** [comment]
Скорее всего при вызове метода PackageSendTask2.AddDocument(...) указали значение версии, которое не соответствует функции, указанной в контенте документа

Если ошибка остаётся, необходимы:

1. Идентифкатор организации, из которой пытаетесь отправить документ
2. Параметры функции, которой добавляете документ на отправку в явном виде
3. информация о том как заполнен контент. Если загружаете из файла, то нужен этот файл. Если заполняете [динамический контент](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DynamicContent.html), то каким данными идёт заполнение (Можно вызвать метод [CustomDocumentToSend.SaveUserData()](https://1c-docs.diadoc.ru/ru/latest/ComObjects/CustomDocumentToSend.html#CustomDocumentToSend.SaveUserData) и предоставить его)

**Comment by ElenaBurnasheva** [comment]
Проблема решилась обновлением компоненты до версии 5.37.4.
