### ISSUE TITLE
Вопрос по транспортной накладной

### ISSUE THREAD

**Issue by dimok22prog1** [diadoc/diadocsdk-1c-docs#788]
Добрый день. На данный момент через компоненту возможна работа с неформализованным документом с видом "Транспортная накладная". Но скоро данный документ будет формализованным. Когда предполагается поддержка компонентой указанного вида формализованного документа?

**Comment by volodkindv** [comment]
Добрый день.
Поддержка формализованной транспортной накладной в компоненте появится автоматически тогда, когда будет реализация в HTTP API. Объектная модель содержимого документа реализована через [DymanicContent](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html), поэтому обновление самой компоненты при изменении форматов документов не требуется.
Исключение - если вместе с форматом документа добавится какая-то еще функциональность. Например, новые основания полномочий. Но об этом можно будет говорить только после утверждения нормативки.
