### ISSUE TITLE
Получить ТЧ документа из контента документа

### ISSUE THREAD

**Issue by AndreyEfimoff** [diadoc/diadocsdk-1c-docs#789]
Добрый день.
Хочу в подключаемом модуле из контента документа получить ТЧ Товары, чтобы перезаполнить уже существующий документ.
Сам документ предварительно приходит в базу 1С другими обработками.
Прошу пример кода по получению ТЧ с сопоставленной номенклатурой.

**Comment by Solar-Valkyrie** [comment]
Добрый день!

Документация работы со входящими документами доступна по ссылке: https://developer.kontur.ru/Docs/Diadoc_UM/proc/pm/Obrabotka_Vkhodyashchikh_Paketov.html 
Сопоставление номенклатуры: https://developer.kontur.ru/Docs/Diadoc_UM/func/pm/Sopostavit%27_Nomenklaturu_Postavshchika.html
