### ISSUE TITLE
Вопрос по отправке TransferBase и StructedAdditionalInfo

### ISSUE THREAD

**Issue by ckyrun** [diadoc/diadocsdk-1c-docs#79]
Получил уже ответ, как отправлять Основание и Иные сведения. Сделал отправку, но результат вызвал вопросы.
![default](https://cloud.githubusercontent.com/assets/26325897/24090643/2bfb18ea-0d53-11e7-8913-59c4551027f8.jpg)
В подчеркнутых местах отражаются ненужные данные.
Заполнение TransferBase:
DocumentName - "Договор"
DocumentNumber - "КомГаз"
DocumentDate  -  дата
DocumentInfo - ""
Почему дополняется "Отсутствует"?
Заполнение StructedAdditionalInfo:
Key - GUID в виде строки
Value - строка данных
Пробовал в Key отправлять "", ругается. А так отражает и GUID, и данные.

**Comment by volodkindv** [comment]
По поводу заполнения StructedAdditionalInfo:
это массив пар Ключ-Значение, который в конечном итоге сериализуется в XML-файл, формат которого определен ФНС.
В формате оба поля (и ключ, и значение) являются обязательными для заполнения.
Т.е. в вашем случае можно заполнять, например, так:
Key = "Цена_с_учетом_коэффициента"
Value = "123.45678"

Насчет TransferBase - проверьте, сколько элементов у вас в этой коллекции. Возможно, что больше одного, а заполнен только один.

**Comment by ckyrun** [comment]
В моем случае нельзя. У них только одна строка в допсведениях. А избежать : между значениями никак. А то можно на две части разбить.
По второму уверен дело в этом, самому что то в голову не пришло.

**Comment by ckyrun** [comment]
Можно закрывать. Отправку доп. инфы перенесли в табличную часть.
