### ISSUE TITLE
Как получить табличную часть документа Torg12

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#791]
Здравствуйте. 
Один из наших контрагентов присылает нам документы, у которых свойство DocumentType=Torg12, но в печатной форме при этом выводится УПД.

Если например приходит документ со значением свойства DocumentType=UniversalTransferDocument, то для  получения ТЧ УПД получаем контент документа:
Document=Organization.GetDocumentById(DocumentId)
DynamicContent=Document.GetDynamicContent("Seller") 
Content=DynamicContent.UniversalTransferDocument
а далее циклом по объекту Content.Table.Item.Count получаем значения полей табличной части документа на основании описания полученного из метода Organization.SaveUserDataXSD(TitleName, Function, Version, DocflowSide, FilePath)

При работе с документом Torg12 возникает две проблемы:

1.Как получить контент документа Torg12 ?

2.Не удается получить описание содержимого контента Torg12.
Для получения описание содержимого контента использую метод Organization.GetDocumentTypes() и получаю значения
TitleName=Torg12
Function=default
Version=v1
DocflowSide=Seller
Далее использую метод Organization.SaveUserDataXSD("Torg12", "default", "v1", "Seller", ИмяФайла) и получаю ошибку MyBox.SaveUserDataXSD: Неверный тип документа

Для работы с документами используется 1С AddIn x86 5.37.4.831.

**Comment by GilimkhanovDenis** [comment]
Добрый день

[Torg12; default; v1] - неформализованный Торг-12. упрощённого представления контента для этого типа нет (GetDynamicContent(...) будет возвращать `Неопределено`). Всё что можно сделать с контентом - получить его как он есть - [GetBase64Content(...)](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentBase.html#DocumentBase.GetBase64Content), [SaveContent(...)](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentBase.html#DocumentBase.SaveContent)

Формализованный Торг12 имеет `TitleName == "XmlTorg12"`. Представление контента зависит от версии

**Comment by evgen421** [comment]
Здравствуйте Денис. Спасибо за ответ.
Использовал метод SaveContent(...), но я не понял, в каком формате полученный файл?

**Comment by GilimkhanovDenis** [comment]
Сохраняется просто бинарное содержимое документа, который вам прислали

У [DocumentBase](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentBase.html) есть поле FileName. Если при отправке контрагент указал расширение у файла, то здесь его можно увидеть

**Comment by evgen421** [comment]
Здравствуйте Денис. Указал расширение файла и действительно формат файла соответствует расширению, то есть это не формализованный документ. Спасибо, вопрос закрыт.
