### ISSUE TITLE
Ошибка при вызове метода DocumentsTask.GetDocuments();

### ISSUE THREAD

**Issue by Litv123** [diadoc/diadocsdk-1c-docs#792]
при отборе документов в ящиках организаций -возникает следующая ошибка, на определенных периодах
(SearchDocumentTask.GetDocuments): Ошибка синтаксического анализа Protobuf: отсутствуют обязательные поля: (не удается определить отсутствующие поля для облегченного сообщения) в методе DocumentList = DocumentsTask.GetDocuments();

Пока к < OrganizationList.Count() Цикл
	// Получение конкретной организации
	Organization = OrganizationList.GetItem(к);
	//Список документов можно получить только в контексте организации.
	// Создаем объект DocumentsTask
	DocumentsTask = Organization.GetDocumentsTask();
	// Заполняем параметры отбора документов
	DocumentsTask.FromDocumentDate = НачалоДня(ПараметрыЗапроса.НачалоПериода);
	DocumentsTask.ToDocumentDate   = КонецДня(ПараметрыЗапроса.КонецПериода);
	//DocumentsTask.FromSendDate = НачалоДня(ПараметрыЗапроса.НачалоПериода);
	//DocumentsTask.ToSendDate   = КонецДня(ПараметрыЗапроса.КонецПериода);
	Для каждого элементаМассива из Мас цикл
	DocumentsTask.Category=элементаМассива;
	//DocumentsTask.Category     = "AnyBilateralDocumentType.Outbound";
	DocumentList = DocumentsTask.GetDocuments();

**Comment by GilimkhanovDenis** [comment]
Добрый день
Нужны идентификатор ящика (поле Guid объекта Organization), в котором возникает ошибка и параметры DocumentsTask, которые задаёте. Также укажите версию используемой компоненты
