### ISSUE TITLE
Модуль 1С v 5.49.22.958 :Длина максимальная для DocumentID

### ISSUE THREAD

**Issue by Alfiyaaaaa** [diadoc/diadocsdk-1c-docs#793]
Добрый день.
Спрашивала у техподдержки какая длина для DocumentID - сказали 36.
У нас он явно больше раза в 2. Техподдержка сказала что это другое поле.
Мне надо понять как заполняется это поле во вкладке Отправленные.
нашла:
МетодКлиента("Модуль_РаботаССерверомДиадок", "ПолучитьДокументДиадок"
		, ИдентификаторОрганизации
		, СоставнойИдентификаторДокумента)
В СоставнойИдентификаторДокумента я как раз помещаю наш длинный ГУИД и документ из Диадока подтягивается.
Можете подсказать где тогда DocumentID ?

**Comment by GilimkhanovDenis** [comment]
Отвечу про то, что касается компоненты и длины DocumentID:

Идентификатор DocumentId [документа](https://1c-docs.diadoc.ru/ru/latest/ComObjects/DocumentBase.html) является конкатенацией MessageId/LetterId и EntityId из [HTTP-API](http://api-docs.diadoc.ru/ru/latest/index.html), которые являются GUID’ами (каждый 36-символов)

Про модуль Стандарт

**Comment by Alfiyaaaaa** [comment]
спасибо

**Comment by GilimkhanovDenis** [comment]
Какая-то ещё информация про DocumentID нужна или можно закрыть этот issue ?

**Comment by Alfiyaaaaa** [comment]
это максимальный предел?

**Comment by Alfiyaaaaa** [comment]
Техподдержка говорила что могут быть разной длины

**Comment by GilimkhanovDenis** [comment]
Валидный идентификатор DocumentID - 72 символа

В некоторые методы компоненты нужно передавать только первую половину этого идентификатора (например, в методе [Organization.CreateSendDraftTask(MessageId)](https://1c-docs.diadoc.ru/ru/latest/ComObjects/Organization.html?highlight=CreateSendDraftTask#Organization.CreateSendDraftTask))

А большей длины компоненте не нужно

Увы, про ограничения длины поля в модуле Стандарт подсказать не смогу - это репозиторий компоненты и про устройство модуля мы ничего не знаем . Консультации по доработкам модуля можно обсудить с вашим менеджером

**Comment by Alfiyaaaaa** [comment]
хорошо. спасибо. Можно закрыть
