### ISSUE TITLE
Помогите заполнить CircumFormatInvoice

### ISSUE THREAD

**Issue by GuninaY** [diadoc/diadocsdk-1c-docs#794]
Передаю его как Content.CircumFormatInvoice = XMLСтрока("4");  Тип строка, но все равно ругается что,/UniversalTransferDocumentWithHyphens[1]/@CircumFormatInvoice: The 'CircumFormatInvoice' attribute is invalid - The value '4' is invalid according to its datatype 'String' - The Enumeration constraint failed.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Проверьте, что в качестве версии документа указываете `utd820_05_01_02_hyphen`, а не `utd820_05_01_01_hyphen`

Если изменение версии не поможет, то укажите идиентификатор организации, которая выполняет отправку и параметры метода PackageSendTask2.AddDocument(...), которые указываете

**Comment by GuninaY** [comment]
Спасибо, помогло utd820_05_01_02_hyphen!
