### ISSUE TITLE
проблемы с GetCounteragentListByStatus

### ISSUE THREAD

**Issue by NatalyaNoskova** [diadoc/diadocsdk-1c-docs#795]
Добрый день!
В Стандартных модулях Диадока к 1С (к УПП и Комплексной, последние версии) а также при работе с СОМ объектом 32 (и последняя версия тоже) наблюдается при считывании списка с условием "IsMyCounteragent" (ну или Партнерские отношения ) рандомное дублирование этих самых контрагентов. В Веб-форме считывается правильно. Если пишет что у вас N контрагентов то и считывает N контрагентов, оригинальных  по ГУИДу, ИД и т.п. Модули 1С и запрос GetCounteragentListByStatus считывают так же N контрагентов , но штуками, в списке оказываются полные дубли , за счет которых не попадают в список "оригиналы" других контрагентов. 
Я считывала контрагентов в нескольких организациях, поняла только, что такое дублирование идет в организациях, в которых контрагентам в веб-форме назначены Группы с привязкой к Подразделениям. Так же у дублирующихся контрагентов наблюдаются разные адреса (смотрела по Улица). Я не берусь утверждать, что именно это влияет на дублирование но другой зависимости я не нашла.
Я уже отправляла этот вопрос через представителя Диадок в СПб, но ответа пока не получила. Прошу разобраться.

**Comment by happydeadman** [comment]
Добрый день!
Теперь контрагенты должны отображаться корректно. Проверьте, пожалуйста, работу.

**Comment by NatalyaNoskova** [comment]
Проверила. Дуплит. Не сотнями конечно, но десятками. (сегодня 15 дублей)

**Comment by NatalyaNoskova** [comment]
Проверила. Дублит. Меньше, но все же

  
>Среда, 18 мая 2022, 11:22 +03:00 от AndrewPleshko ***@***.***>:
> 
> 
>Добрый день!
>Теперь контрагенты должны отображаться корректно. Проверьте, пожалуйста, работу.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/795/1129716498 @ github . com> 
 
 
--
Natalya Noskova
Отправлено из Почты  Mail.ru

**Comment by Solar-Valkyrie** [comment]
Добрый день!

Уточните, пожалуйста, актуален ли вопрос?
Если актуален, то укажите, пожалуйста:

BoxID
Используемый метод и запрос.
Точное время запроса.

**Comment by NatalyaNoskova** [comment]
Организация 2BM-7825352662-784001001-201407080849181670655
Запрос из VBA в экселе
        Set CountList = OrgBox.GetCounteragentListByStatus("IsMyCounteragent")  
от считывания всех контрагентов с пустым параметром результат не меняется (в смысле дублируемость)
CountList.Count тащит правильный (сужу по веб клиенту)
 а среди 
     Set pCount = CountList.GetItem(j)
имеют место быть полные дубли (по ГУИД, айди и что там еще).
количество дублей рандомное (120+ вчера), из-за них не попадают "оригиналы"

Стандартный модуль 1С тоже дублирует при правильном количестве клиентов. Гуиды не видны, но то, что модуль дает сопоставить единственную запись контрагента в 1С с 2 притащенными из Диадока дает мне резон так думать.

В то же время, по организации 2BM-7810089105-780601001-201504081120284145477 таких явлений не наблюдалось никогда. Вся разница между организациями в том, что в первой имеет место быть разнесение контрагентов по группам в веб-форме. Другой разницы я не вижу.

Сегодня дублей нет (смотрела в 11 и в обед) ни в модулях всех версий, ни в библиотеках тоже всех версий. Я не думаю, что это вообще зависит от релиза. Не знаю, что там происходит и уверенности что это не сломается опять у меня нет, поэтому не закрывайте тикет неделю

**Comment by NatalyaNoskova** [comment]
Здравствуйте! Это снова я, опять дуплит
![image](https://user-images.githubusercontent.com/72979060/172882584-363ed82a-0318-49cf-a0b8-7f782f63421f.png)

**Comment by kab1k** [comment]
Добрый день, нужна техническая информация модуля.
Скопировать можно по кнопке "Техподдержка" в левом нижнем углу.
