### ISSUE TITLE
проблема GetCountrlistByStatus () не решилась

### ISSUE THREAD

**Issue by NatalyaNoskova** [diadoc/diadocsdk-1c-docs#797]
https://github.com/diadoc/diadocsdk-1c-docs/issues/795#issue-1235084480
Сегодня наблюдаются дубли

**Comment by kab1k** [comment]
Попробуйте разрегистрировать старую компоненту, чтобы модуль подтянул новую. Либо зарегистрировать новую вручную. Скачать компоненту можно на сайте https://diadoc-api.kontur.ru/1c-addin/ .

Если проблема останется актуальной - предоставьте, пожалуйста, полную техническую информацию о модуле. Так же используется ли ПМ или является ли модуль кастомным.

**Comment by kab1k** [comment]
Последняя версия компоненты Diadoc_5_37_4_832 от 14.04.2022

**Comment by kab1k** [comment]
Предоставьте, пожалуйста, полную техническую информацию о модуле. Так же используется ли ПМ или является ли модуль кастомным.
Скачать компоненту можно на сайте https://diadoc-api.kontur.ru/1c-addin/ .
В модуле актуальная компонента - 5_37_4_832
Скачать нерелизную версию модуля с фиксами можно по ссылке https://disk.skbkontur.ru/index.php/s/BWNoFYNScKq4PZt

**Comment by NatalyaNoskova** [comment]
1. Сегодня на 11:04 дублей нет. Не знаю, что там сделали но прошу зафиксировать это состояние. Дублей нет ни в модулях любой свежести 1С (v5.48.01.529 и 5.48.13.529) ни при работе в библиотеками dll. (тоже любой свежести). Новый модуль 1С по ссылке на всякий случай поставили.
2. Прошу ссылку на 5_37_4_832 СОМ86 или положите вот сюда
![image](https://user-images.githubusercontent.com/72979060/170224136-3cfe4f4c-a19b-4f78-a7a6-30bae32b9d7d.png)
С этой библиотекой я работаю из экселя на предмет снятия событий, расфасовкой документов по подразделениям и наблюдением за контрагентами. Модуль Стандарт использую штатно без всяких доработок. Что такое ПМ не знаю.
3. Не закрывайте тикет неделю пожалуйста.

**Comment by kab1k** [comment]
[Diadoc_5_37_4_832_x64.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/8770033/Diadoc_5_37_4_832_x64.zip)
ПМ - подключаемый модуль для основного модуля, подключается в настройках

**Comment by NatalyaNoskova** [comment]
мне не 64, мне 32

**Comment by GilimkhanovDenis** [comment]
@NatalyaNoskova  на сайте документации выложен последний официальный релиз
5.37.4.832 - версия, о которой говорит @kab1k, предназначена специально для модуля 1С (в ней кастомная логика и она только варианте 1C Addin)

Если у вас собственная интеграция, то эта версия вам не нужна

Насколько понял, сейчас проблемы нет, поэтому закрываю.
Если возникнет повторно, то нужен будет идентификатор ящика, в котором воспроизводится (Organization.Guid) и параметры метода, с которыми вызываете метод GetCounteragentListByStatus

**Comment by NatalyaNoskova** [comment]
Закройте через неделю пожалуйста, а то в прошлый раз через 2 дня все сломалось
