### ISSUE TITLE
Перестали получаться события через Organization.GetDocumentEventList([AfterEventId])

### ISSUE THREAD

**Issue by Lacertus** [diadoc/diadocsdk-1c-docs#798]
Добрый день!
Организация: ООО «ХАРЛИ-ДЭВИДСОН РУС»
ИНН: 7709864349
КПП: 770901001
ID участника ЭДО: 2BM-7709864349-770901001-201508240537314140774

При обращении к методу получения событий организации получаются события только до конца марта, хотя в web-версии присутствуют и другие документы. ID последнего получаемого события dcf6b9bd-855d-49dd-850f-f5d3a083905a, хотя 1 апреля пришел документ в событии c6db514b-9919-448e-854b-e41338737301.

Почему могут не получаться дальнейшие события?

**Comment by Lacertus** [comment]
Ведется ли какая-то работа над этим вопросом?

**Comment by Solar-Valkyrie** [comment]
Добрый день!

Покажите, пожалуйста, метод и текст запроса. Также укажите, пожалуйста, точное время запроса.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Поведение не воспроизводится. Organization.GetDocumentEventList("dcf6b9bd-855d-49dd-850f-f5d3a083905a") возвращает 109 событий. В том числе и события, случившиеся 1 апреля

Что у Вас является результатом выполнения метода?
