### ISSUE TITLE
Повторная отправка приглашений, COM x86 5.35.4.736 для произвольных систем

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#799]
Добрый день!
Раз в квартал мы осуществляем массовую отправку приглашений к партнерству с файлом вложения Соглашения на ЭДО.
Если контрагенту ранее уже было направлено приглашение, то мы сначала отменяем его с помощью метода BreakWithCounteragent, затем посылаем новое приглашение методом CreateAcquireCounteragentTask.
С некоторого времени метод BreakWithCounteragent перестал отрабатывать, контрагент остается в статусе IsInvitedByMe, новое приглашение не уходит. 
Как реализовать повторную отправку приглашений?

Примеры приглашений, отправленных ранее. По этим контрагентам не удалось отправить новый документ.

https://diadoc.kontur.ru/3bfb9c4d-0203-4610-83c8-e15ba95fd8d2/Document/Show?letterId=f0341df9-8d2f-4b9c-b154-cf7a1a600d80&documentId=7d9e6c5b-6257-4d63-bfd7-e4f49d4e6086

https://diadoc.kontur.ru/3bfb9c4d-0203-4610-83c8-e15ba95fd8d2/Document/Show?letterId=a81c6547-7107-4921-a5bb-419c3775adaf&documentId=18a56a1e-aeab-4a83-be0d-f98b2c37f044

**Comment by GilimkhanovDenis** [comment]
Добрый день

Попробовал на своих организациях. Отправил запрос с вложением с запрошенной подписью и разорвал дружбу
```
Процедура test(CounteragentGUID, FilePath)
    Counteragent = Organization.GetCounteragentById(CounteragentGUID);
    Сообщить("Статус перед тестом: " + Counteragent.Status);

    ACTast = Organization.CreateAcquireCounteragentTask();
    ACTast.CounteragentBoxId = CounteragentGUID;
    ACTast.Message = "https://github.com/diadoc/diadocsdk-1c-docs/issues/799";
    ACTast.FileName = FilePath;
    ACTast.SignatureRequested = True;

    ACTast.send();

    Counteragent = Organization.GetCounteragentById(CounteragentGUID);
    Сообщить("Статус после отправки приглашения: " + Counteragent.Status);

    Counteragent.BreakWithCounteragent();
    Сообщить("Статус после разрыва дружбы (emplace): " + Counteragent.Status);

    UpdatedCounteragent = Organization.GetCounteragentById(CounteragentGUID);
    Сообщить("Статус после разрыва дружбы (new instance): " + UpdatedCounteragent.Status);
КонецПроцедуры
```
Получил такой вывод:

```
Статус перед тестом: IsRejectedByMe
Статус после отправки приглашения: IsInvitedByMe
Статус после разрыва дружбы (emplace): IsRejectedByMe
Статус после разрыва дружбы (new instance): IsRejectedByMe
```

Насколько вижу, у вас используется старая компонента (v5.35.4). Попробуйте её обновить до актуальной (v[5.37.4](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_37_4.html))

**Comment by jakeqwert** [comment]
Спасибо, попробуем!

**Comment by jakeqwert** [comment]
Добрый день! Попробовали на новой компоненте, та же самая ошибка: "##100[Ошибка сервера Диадок]code:409, HTTP error: Invalid relation state". Статус контрагента перед попыткой разрыва отношений - IsInvitedByMe.

**Comment by ButurlakinSemyon** [comment]
@jakeqwert Добрый день.

На стороне апи Диадока произошли изменения. Теперь, прежде чем отозвать приглашение с вложением, необходимо аннулировать само вложение. 
Для формирования соглашения об аннулировании необходимо с помощью [DocumentsTask](https://developer.kontur.ru/Docs/Diadoc/Com/ComObjects/DocumentsTask.html) найти приглашение. Затем для него создать ReplySendTask2 методом [DocumentBase.CreateReplySendTask2](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html#DocumentBase.CreateReplySendTask2) с типом "RevocationRequest", заполнить необходимые данные и отправить созданное аннулирование.

Для того, чтобы не останавливать процесс работы сейчас, можно отозвать приглашения через веб-версию Диадока. 
Если вы не пользуетесь веб-версией или вам необходимо отозвать большое количество приглашений с вложениями, можем предложить отозвать приглашения силами разработки. В таком случае нам потребуется BoxId вашей организации и BoxId контрагентов, чтобы понять какие приглашения отозвать. Информацию о BoxId можете прислать через тех поддержку или менеджера.

**Comment by jakeqwert** [comment]
Большое спасибо! С помощью этого механизма получилось отозвать приглашения.
