### ISSUE TITLE
Колонка "Сумма налога" была равна "без НДС"

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#8]
Подскажите пожалуйста при программном заполнении данных для отправки электронного акта выполненных работ(АВР), что требуется заполнить в реквизите "vat" табличной части, чтобы в самом документе колонка "Сумма налога" была равна "без НДС" (не путать с "0"), пример на скриншоте:

![image](https://cloud.githubusercontent.com/assets/20473774/16869243/612c1af4-4a95-11e6-92bf-0d6f1d74be29.png)

Последовательность действий:
1. SendTask = Organization.CreateSendTask("XmlAcceptanceCertificateContent"); - создаем задание для отправки АВР на сервер.
2. Item = InvoiceContent.AddItem(); - добавляет сведения в коллекцию строк акта. 
3. Item.vat - интересует данный реквизит, как его требуется заполнять, если ставка НДС = "без НДС". 

	Заполняем эту структуру
http://diadocsdk-1c.readthedocs.io/ru/latest/AcceptanceCertificateItem.html

**Comment by denver069** [comment]
В таком случае не инициализируйте поле **Vat** объекта [AcceptanceCertificateItem](http://diadocsdk-1c.readthedocs.io/ru/latest/AcceptanceCertificateItem.html) (Не записывайте туда значение вообще).
