### ISSUE TITLE
Как добавить поля доп. сведений в УПД ?

### ISSUE THREAD

**Issue by Himik1** [diadoc/diadocsdk-1c-docs#802]
Как добавить поля доп. сведений (ИнфПолФХЖ2, ИнфПолФХЖ3) в УПД. А так же Дополнительные сведения к документу ?

**Comment by Solar-Valkyrie** [comment]
Добрый день!

Можно с помощью StructedAdditionalInfo: 
https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/StructedAdditionalInfo.html
