### ISSUE TITLE
Работа с МЧД

### ISSUE THREAD

**Issue by dimok22prog1** [diadoc/diadocsdk-1c-docs#803]
Ранее на вопрос по работе с МЧД через компоненту получил утвердительный  ответ на вопрос:

То есть МЧД может быть выпущена только через сторонний сервис, при выпуске будет сформирован контент файла подписи (XmlSignature) и xml-файл установленного формата (XmlContent )?

_Originally posted by @dimok22prog1 in https://github.com/diadoc/diadocsdk-1c-docs/issues/772#issuecomment-1074824189_

Подключились к сервису Контур.Доверенности.
Получил следующий ответ от ответственного:

1) Скачать из Контур.Доверенности на данный момент ни в каком формате доверенность нельзя;
2) Такого пункта меню даже нет.
Менеджер Контур подтвердила, что на данный момент в сервисе еще не реализована функция скачивания доверенности.

Я правильно понимаю, что: 
1) использовать возможность подписания с МЧД через компоненту Диадок для произвольных систем на данный момент нельзя?
2) нет возможности получить XmlSignature и XmlContent на данный момент каким либо способом?

**Comment by Max-Redhead** [comment]
Добрый день!
1. Работа с МЧД возможна. 
Если доверенность уже выпущена в сервисе Контур.Доверенность, её нужно только добавить к сотруднику в Диадоке. Для этого можно воспользоваться методами -
Organization.RegisterPowerOfAttorneyById и MyEmployee.AddPowerOfAttorney.

2. Возможность получения XmlSignature и XmlContent необходимо уточнять в сервисе, где вы выпускали МЧД.
