### ISSUE TITLE
При отправке УКД ошибка <##100[Ошибка сервера Диадок]code:400, HTTP error: Info.InvoiceCorrectionTable.TotalsDec.TotalWithVatExcluded is required>

### ISSUE THREAD

**Issue by VMescheryakov** [diadoc/diadocsdk-1c-docs#804]
DiadocCom_5_37_5_836.dll  (COM x86)

Среда разработки Delphi XE5
Формирую UniversalCorrectionDocument
Присваиваю свойства в коде:

ADocument.Content.InvoiceCorrectionTable.TotalsInc.TotalWithVatExcluded := FormatFloat('0.###', 0);
ADocument.Content.InvoiceCorrectionTable.TotalsDec.TotalWithVatExcluded :=FormatFloat('0.###', 0);

но ADocument.Content.InvoiceCorrectionTable.TotalsDec.TotalWithVatExcluded = UnAssigned как до оператора присвоения так и после него, в то время как ADocument.Content.InvoiceCorrectionTable.TotalsInc.TotalWithVatExcluded = 0 перед присвоением так и после него. Такое ощущение что Set или Get не работает у этого свойства 

![image](https://user-images.githubusercontent.com/3495337/171604407-775d2698-3460-4b10-b6e8-c1b92401c729.png)

точно такая же проблема с DiadocCom_5_37_4_831.dll

**Comment by GilimkhanovDenis** [comment]
Добрый день

Другие свойства подобным образом устанавливаются?

И можете ещё указать какие  TypeNamedId, DocumentFunction, DocumentVersionиспользуете в методе [PackageSendTask2.AddDocument(TypeNamedId, DocumentFunction, DocumentVersion)](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocument)

**Comment by VMescheryakov** [comment]
Такая ошибка возникает при попытке работать через PackageSendTask
PackageSendTask.AddDocument('UniversalCorrectionDocument')

**Comment by VMescheryakov** [comment]
>Другие свойства подобным образом устанавливаются?

да  ADocument.Content.InvoiceCorrectionTable.TotalsInc.TotalWithVatExcluded - работает норм

**Comment by GilimkhanovDenis** [comment]
Если я правильно понял из постановки, то изначально имеем
```
ADocument.Content.InvoiceCorrectionTable.TotalsInc.TotalWithVatExcluded = 0
ADocument.Content.InvoiceCorrectionTable.TotalsDec.TotalWithVatExcluded = UnAssigned 
```

потом выполняем код
```
ADocument.Content.InvoiceCorrectionTable.TotalsInc.TotalWithVatExcluded := FormatFloat('0.###', 0);
ADocument.Content.InvoiceCorrectionTable.TotalsDec.TotalWithVatExcluded :=FormatFloat('0.###', 0);
```

и изначальные значения не меняются
```
ADocument.Content.InvoiceCorrectionTable.TotalsInc.TotalWithVatExcluded = 0
ADocument.Content.InvoiceCorrectionTable.TotalsDec.TotalWithVatExcluded = UnAssigned 
```

Но последний Ваш комментарий говорит, что я не правильно понял и для
`ADocument.Content.InvoiceCorrectionTable.TotalsInc.TotalWithVatExcluded` всё работает.

Поправьте тот момент, в котором я ошибся


В целом PackageSendTask и его представление контентов документов использовать не рекомендуется - в нём не поддерживаются новые форматы документов. В том числе и [УКД 736 формата](https://normativ.kontur.ru/document?moduleId=1&documentId=375857) - используйте [PackageSendTask2](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html) и [DynamicContent](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html)

**Comment by VMescheryakov** [comment]
После присвоения
ADocument.Content.InvoiceCorrectionTable.TotalsDec.TotalWithVatExcluded :=FormatFloat('0.###', 0);
остается
ADocument.Content.InvoiceCorrectionTable.TotalsDec.TotalWithVatExcluded = UnAssigned 

TotalsInc.TotalWithVatExcluded  работает норм

**Comment by GilimkhanovDenis** [comment]
TotalsDec и TotalsInc - один и тот же объект [InvoiceTotalsDiff](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/InvoiceTotalsDiff.html)

Если работает для одного инстанса и не работает для другого, то скорее всего, дело в регистрации компоненты. Попробуйте разрегистрировать компоненту и зарегистрировать снова.
Если генерируете какие-то статические обёртки над COM-объектом, то их лучше перегенерировать

**Comment by VMescheryakov** [comment]
>TotalsDec и TotalsInc - один и тот же объект [InvoiceTotalsDiff]
Да, это видно в коде обертке 
>компоненту и зарегистрировать снова.
да же компьютер перегружаю между этим

>Если генерируете какие-то статические обёртки над COM-объектом, то их лучше перегенерировать
Всегда генерирую обертку (TLB файл), иначе все ломается 

Могу простой код на delphi написать для проверки

**Comment by GilimkhanovDenis** [comment]
Если не сложно, то присылайте, посмотрю

// если в листинге будут какие-то приватные данные (ключ разработчика например), то можно прислать через техподдержку

**Comment by GilimkhanovDenis** [comment]
В https://github.com/diadoc/diadocsdk-1c-docs/issues/805 вижу, что переезжаете на динамический контент. Тогда этот тикет закрываю
