### ISSUE TITLE
Где можно найти пример кода формирования и отправки современного УКД?

### ISSUE THREAD

**Issue by VMescheryakov** [diadoc/diadocsdk-1c-docs#805]
Добрый день

Где можно найти пример кода формирования и отправки современного УКД?
От начала до конца.

**Comment by VMescheryakov** [comment]
>Как отправить документ 
Это шутка? Там:

1. УПД а не УКД
2. вся тайна спрятана в ЗаполнитьДинамическийКонтентДокумента. Где посмотреть какие свойства присваивать?


>SDK: https://github.com/diadoc/diadocsdk-1c-docs
Вот так показывает по ссылке

![image](https://user-images.githubusercontent.com/3495337/172143919-2a0c8962-696a-4e58-bab1-81d3290542fd.png)

**Comment by GilimkhanovDenis** [comment]
COM-объект [DynamicContent](https://developer.kontur.ru/Docs/Diadoc/Com/ComObjects/DynamicContent.html) строится полностью в runtime на основе UserDataXSD, которую можно получить методом [Organization.SaveUserDataXSD()](https://developer.kontur.ru/Docs/Diadoc/Com/ComObjects/Organization.html#Organization.SaveUserDataXSD)

Правила по которым строится это представление контента описаны на странице [DynamicContent](https://developer.kontur.ru/Docs/Diadoc/Com/ComObjects/DynamicContent.html)

Также можно использовать [Reflector](https://developer.kontur.ru/Docs/Diadoc/Com/ComObjects/Reflector.html), чтобы понять какие поля и методы есть у конкретного инстанса [DynamicContent](https://developer.kontur.ru/Docs/Diadoc/Com/ComObjects/DynamicContent.html)


Готового примера нет

**Comment by GilimkhanovDenis** [comment]
Добавить УКД 736 на отправку можно, так
```
DocumentFunction := "ДИС"; // только для примера. Полный список возможных функций можно получить методом Organization.GetDocumentTypes()
PackageSendTask2.AddDocument("UniversalCorrectionDocument", DocumentFunction , "ucd736_05_01_02" );
```

**Comment by VMescheryakov** [comment]
Где можно посмотреть готовый пример заполнения всех свойств документа для отправки УКД  на любом языке программирования? Не набор свойств объектов а пример кода.

**Comment by Solar-Valkyrie** [comment]
К сожалению, примера готового кода нет.
Вы можете обратиться в техническую поддержку и приобрести консультацию отдела внедрения.
Контакты технической поддержки: https://www.diadoc.ru/support
