### ISSUE TITLE
Ошибка при попытке отправить УКД в котором не изменяется сумма без НДС а меняется только сумма НДС 

### ISSUE THREAD

**Issue by VMescheryakov** [diadoc/diadocsdk-1c-docs#806]
DiadocCom_5_37_5_836.dll (x86)
Если в строке УКД не изменяется сумма без НДС (Item.SubtotalWithVatExcluded)  то УПД не формируется так как требует что бы было указано увеличение Item.SubtotalWithVatExcluded.AmountsInc или уменьшение Item.SubtotalWithVatExcluded.AmountsDec
Попытка указать в любое из них 0 так же выводит ошибку - требует что бы значение было больше 0

Вот такая ошибка если не передавать:
 
EOleException
##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalCorrectionDocument/Table/Items/Item/SubtotalWithVatExcluded/AmountsInc: Function=КСЧФ AmountsInc or AmountsDec is required
/UniversalCorrectionDocument/Table/Items/Item/SubtotalWithVatExcluded/AmountsDec: Function=КСЧФ AmountsInc or AmountsDec is required

Такая если присвоить Item.SubtotalWithVatExcluded.AmountsDec := 0

EOleException
##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalCorrectionDocument/Table/Items/Item/SubtotalWithVatExcluded/AmountsDec: AmountsDec must be > 0

Как отправить УКД в котором изменяется только ставка НДС и сумма с НДС?

**Comment by Solar-Valkyrie** [comment]
Добрый день!

Согласно законодательству, заполнение тэгов СумУвел или СумУм является обязательным: https://normativ.kontur.ru/document?moduleId=1&documentId=375857&rangeId=6093837
Значение должно быть больше нуля. Т.е. необходимо заполнить или увелические, или уменьшение. И нельзя указать значение "0". 
Отправить УКД, в котором не указывается увеличение либо уменьшение, к сожалению, нельзя. 
Полезная документация по теме: 
https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/InvoiceForCorrectionInfo.html
