### ISSUE TITLE
Как найти документ по его Номеру ?

### ISSUE THREAD

**Issue by m-e-arutyunyan** [diadoc/diadocsdk-1c-docs#808]
В методе Organization.GetDocumentsTask() в DocumentsTask для поиска я вижу только Дату документа, Дату Отправки и т.д.
Но Номера Нет.
Как найти документ по его Номеру ? (не по ИД)

**Comment by Max-Redhead** [comment]
Добрый день!
Такой возможности нет. Если отсутствие функционала для вас критично, рекомендую обратиться к менеджеру.
