### ISSUE TITLE
Проблемы с формированием выгрузки из 1С. COM-соединение.

### ISSUE THREAD

**Issue by DevianTools** [diadoc/diadocsdk-1c-docs#809]
Добрый день!
При формировании выгрузки документа «Дополнительное соглашение» из 1С в Диадок возникает исключительная ситуация, с формализованными документами(УПД, УКД..)  таких проблем нет.
Проблема именно с документом «SupplementaryAgreement», если не заполнять даты и номера документов выгрузка происходит успешно и вложение выгружается.
При заполнение контента DocumentDate, DocumentNumber, ContractNumber, ContractDate вызывается исключение.
![изображение](https://user-images.githubusercontent.com/107174490/172805835-985e063a-0b26-47c0-b570-1a133951d2fe.png)

![изображение](https://user-images.githubusercontent.com/107174490/172807195-4bb70756-7b6e-40ed-8ef3-f257f2f7ce64.png)

Предполагаю что content для документа SupplementaryAgreement необходимо заполнять несколько другим образом.
![изображение](https://user-images.githubusercontent.com/107174490/172808253-525f5913-7254-4b6b-a167-504a936a2552.png)

Подскажите может кто нибудь сталкивался с такой проблемой?

**Comment by kab1k** [comment]
Добрый день.
Content заполняется только для формализованных документов. Неформализованные документы состоят из файла и метаданных.
"№ документа" и "к договору №" - это метаданные документа доп. соглашение (supplementaryagreement).
https://developer.kontur.ru/Docs/Diadoc_UM/proc/pm/Podgotovka_Paketa_Dlya_Otpravki.html
Самоинтеграторам с заполнением и отправкой документов необходимо ознакомится в документации. Либо обратиться в СКБ Контур за приобретением консультаций по разработке.
