### ISSUE TITLE
Метод GetDocumentEventList() возвращает ограниченное число значений

### ISSUE THREAD

**Issue by LyudmilaCh** [diadoc/diadocsdk-1c-docs#812]
Добрый день. 
	Функция ПолучитьСписокСобытий()
		EventId="";
		СписокСобытий = ОрганизацияДД_.GetDocumentEventList(EventId);
		сч = 0;
		Сообщить(""+СписокСобытий.Count);
		Для Инд = 0 По СписокСобытий.Count - 1 Цикл
			DocEvent = СписокСобытий.getitem(Инд);
			EventId = DocEvent.EventId;
			Сообщить(EventId + " " + DocEvent.Timestamp);
		КонецЦикла;
		Возврат 0;
	КонецФункции

Результат 115 событий. Хотя на самом деле их гораздо больше. 
В чем может быть проблема?

**Comment by JohnSergeev** [comment]
Добрый день.
В **старой** документации же об этом прямо сказано - метод GetDocumentEventList начиная с заданного Ид события возвращает не все последующие события, а некую порцию.

![изображение](https://user-images.githubusercontent.com/33707226/177663487-17dc8526-b940-4621-987f-0102a8044271.png)

На практике размер порции всегда где-то в районе 100 шт. (причем там реально плавает - он может 80 вернуть, а может 120). 

В новой документации на сайте это почему-то из описания убрали.
### Было бы здорово, если бы вернули на сайт это расширенное описание из старой документации. 

И для получения оставшихся событий надо просто еще раз вызывать GetDocumentEventList с последним ИД из полученного списка событий. И так продолжать, пока метод не "выгребет" все и не начнет возвращать пустой список.

**Comment by JohnSergeev** [comment]
И дополнительно посмотрите сверху по ссылке
![изображение](https://user-images.githubusercontent.com/33707226/177681553-6b6d0c3f-4936-45d7-8f37-cf3e5df9bbb0.png)

Там в том числе и о том, что бы в текущей ленте событий поменять.

**Comment by azhipaigor** [comment]
@JohnSergeev, спасибо за развернутый комментарий. В документацию добавим.

@LyudmilaCh, метод работает именно так - возвращает наборы событий пачками. Что-бы вычитать полную ленту нужно в начале вызвать метод передав пустую строку и дальше вызывать с идентификатором последнего события в пачке.

**Comment by GilimkhanovDenis** [comment]
[Описание метода](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Organization.html?highlight=getdocumenteventlist#Organization.GetDocumentEventList) обновлено
