### ISSUE TITLE
Отсутствие печатных форм для документов "Акт МХ-1" и "Акт МХ-3". Отсутствие значения в поле "Status" для этих документов

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#813]
Добрый день.

**Общая информация для упрощения «разбора полётов»:**
Организация:		«ДНС Ритейл»
ИНН:			2540167061
КПП:			254301001
КПП2:			783450001
ID организации:	c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru		
ID участника ЭДО:	2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.37.4.831**.

Недавно мы добавили у себя работу с документами форматов:
1. "Акт МХ-1" (StorageInventoryAcceptanceCertificate) 
2. "Акт МХ-3" (ReturnInventoryAcceptanceCertificate)

Сама работа с документами происходит нормально за исключением 2 моментов:

## 1. Для этих документов в данных АПИ в поле "Status" всегда указано значение "" (пустая строка).

Мы знаем, что согласно документации это поле устарело и в настоящий момент ведем работы по отказу от него. Однако, непонятно, почему, например, для всех "старых" документов - УПД, УКД, СФ и так далее - статус документа в этом поле АПИ показывает, а для "новых" Акт МХ-1 и Акт МХ-3 - нет.

**Вопросы:**
1. Почему для документов "Акт МХ-1" и "Акт МХ-3" в АПИ не передается статус документа в поле "Status"?
2. Будет ли для этих документов  добавлено значение статуса в поле статус, чтобы в этом плане они не отличалась от, например, УПД и УКД (до момента полного отказа от поля Status)?

## 2. Для этих документов в Диадок отсутствуют печатные формы

При получении печатных форм документов "Акт МХ-1" и "Акт МХ-3" с использованием метода GetPrintForm() или архива документа с вложенной печатной формой с использованием методов SaveAllContentZip() или SaveAllContentZipAsync() печатная форма (или архив файлов с ней) без ошибок возвращается... **вот только внутри этой печатной формы (файла PDF) находится "картинка" с текстом XML-файла документа**.

То же самое происходит и у вас на сайте Диадок:

Акт МХ-1
![изображение](https://user-images.githubusercontent.com/33707226/177227379-36879c85-7b00-4b24-bdbd-bace1a74adb0.png)

Акт МХ-3
![изображение](https://user-images.githubusercontent.com/33707226/177227417-d28a30ff-9169-463a-8e3b-7f2540cd892e.png)

И вот это уже большая проблема, т.к. мы полностью полагаемся на формируемые Диадок печатные формы и очень не хотели бы устраивать какую-то мутную логику, когда по части документов (например УПД) печатная форма предоставляется Диадок, а по части документов - по какой-то причине не предоставляется.

**Вопросы:**
1. Это какая-то ошибка с формированием печатных форм?
2. Будет ли она исправлена и добавите ли вы нормальные печатные формы для этих документов в Диадок?
3. Если да, то когда это можно ожидать? Если нет, то по какой причине у документов не будет печатных форм и что с этим делать?

Спасибо.

**Comment by s-kuzmin** [comment]
1. Уточните подробнее о каком статусе говориться? В [DocflowStatus ](https://developer.kontur.ru/Docs/diadoc-api/proto/DocflowStatusV3.html)статус возвращается.
2. Печатной формы у таких типов документов нет, и на юридическую значимость это не влияет, однако, если требуется, наши специалисты выполнят разработку печатной формы, которая будет подключена к вашим документам МХ-1/МХ-3, входящим/исходящим. С этим вопросом стоит обратиться к вашему менеджеру по Диадоку.

**Comment by GilimkhanovDenis** [comment]
Отвечу про поле `DocumentBase.Status`

Поле `DocumentBase.Status` компонента не вычисляет самостоятельно, а берёт из ответа сервиса. При этом для каждого типа документов это поле в ответе своё уникальное и появлялись эти поля до того как в Диадок стало много типов документов.
Для всех документов, появившихся в сервисе относительно недавно, полей со статусом не появлялось - документы стали другими и для каждого нового типа добавлять в контракты API отдельное поле стало нецелесообразно - контракты бы обновлялись очень часто

Вместо этого есть поле `DocflowStatus.PrimaryStatus` + `DocflowStatus.SecondaryStatus`, в котором есть представление статуса документа "как в web" - его можно показывать пользователю. Полного списка статусов здесь нет и не планируется, а само представление статуса, теоретически, может меняться
В интеграционном решении для реализации логики следует использовать поля с частичными статусами: `SenderSignatureStatus`, `RecipientResponseStatus`, `ProxySignatureStatus`, `RoamingNotificationStatus`, `RevocationStatus`, `ResolutionStatus`, `RecipientReceiptMetadata`, `ConfirmationMetadata`, `AmendmentRequestMetadata`

Планов по доработкам поля Status нет
