### ISSUE TITLE
Не удается получить описание контента документа Акт сверки

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#814]
Здравствуйте.

TitleName=ReconciliationAct
Function=default
Version=v1
DocflowSide=Seller
Organization.SaveUserDataXSD(TitleName, Function, Version, DocflowSide, FilePath);

Выдает ошибку:  MyBox.SaveUserDataXSD: Неверный тип документа
В чем ошибка?

**Comment by GilimkhanovDenis** [comment]
Добрый день

тип документа `[ReconciliationAct; default; v1]` не имеет UserDataXSD для первого титула. Это можно увидеть в ответе [GetDocumentTypes](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Organization.html#Organization.GetDocumentTypes)

![image](https://user-images.githubusercontent.com/34439383/183824731-ac580c60-8b29-4bd5-bfe1-dbc9a9a6c1a9.png)

**Comment by evgen421** [comment]
Здравствуйте Денис, спасибо за ответ, но для второго титула тоже нет схемы, тогда как заполнять?! Где взять схему заполнения?

**Comment by GilimkhanovDenis** [comment]
Для `[ReconciliationAct; default; v1]` вообще нет второго титула. Первый титул может быть в любом формате. Подписание входящего будет выглядеть так же как подписание обычного неформализованного (`[Nonformalized; default; v1]`):

`DocumentBase.CreateReplySendTask2().Send();`

**Comment by evgen421** [comment]
Всё понятно, спасибо.
