### ISSUE TITLE
Отсутствие возможности работать с документами "Акт на взаимозачет" в тестовых ящиках

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#815]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
КПП2: 783450001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: COM x64 5.37.4.831.

Мы обнаружили, что набор поддерживаемых типов документов, возвращаемый с использованием GetDocumentTypes() в наших рабочих ящиках (в частности - вышеуказанном ящике для "ДНС Ритейл"), не совпадает с набором поддерживаемых типов документов, которая эта же функция GetDocumentTypes() возвращает в наших тестовых ящиках! 
В частности в ящиках: 
1. Тестовая организация №2918743
2. Тестовая организация №9683568

Особенно нас заинтересовал момент с документом "Акт на взаимозачет".

В ящике "ДНС Ритейл" (и рабочих ящиках других наших реальных юр. лиц) функция GetDocumentTypes() возвращает информацию о документе "Акт на взаимозачет":

| Поле | Значение |
| - | - |
| Title | "Акт на взаимозачет" |
| Name | ActOfsetting |
| Docflow | Seller |
| Functions.Name | default |
| Functions.Version | aktnavz_01_01 |

Для данного документа в этих ящиках успешно выгружается  его XSD схема (с использованием функции SaveUserDataXSD()).
Документ такого типа успешно добавляется в пакет на отправку (с использованием Organization.CreatePackageSendTask2() и последующим добавлением документа в задание на отправку через AddDocument()).

**Однако, в наших тестовых ящиках в данных, возвращаемых GetDocumentTypes() такого типа документа вообще нет!
А попытка добавить его в пакет на отправку приводит к ошибке.**

Т.е. выполнение кода:
### SendTask.AddDocument("ActOfsetting", "default", "aktnavz_01_01")

в **рабочих** ящиках успешно добавляет документ данного типа в пакет.

А выполнение этого же кода в **тестовых** ящиках приводит к ошибке:
**_Произошла исключительная ситуация (PackageSendTask2.AddDocument): Неверный тип документа_**

### Вопросы:
Чем объясняется, что тип документа "Акт на взаимозачет" поддерживается в рабочих ящиках, но отсутствует в тестовых?

Если документ полноценно поддерживается в ЭДО Диадок, то просьба сделать так, чтобы и в тестовых ящиках с ним можно было работать.

Если же с документом какие-то проблемы с реализацией и именно поэтому он отсутствует в тестовых ящиках, то, пожалуйста, сообщите в чем именно проблемы и когда планируется реализовать полноценную работу с данным документом как в рабочих, так и в тестовых ящиках.

Спасибо.

**Comment by kab1k** [comment]
Добрый день.

В Диадок возможно подключить свои типы документов, которые на текущий момент не используются в существующем виде в Диадоке. Тип документа может быть создан на базе любого формата (ФНС, созданного клиентом, разработанного нами).

ActOfsetting - это тип документа, который на текущий момент не используется в существующем виде в Диадоке. Поэтому GetDocumentTypes() возвращает разные списки доступных документов между рабочим ящиком и тестовым.

Свои типы документов настраиваются индивидуально для каждого ящика. Если вам необходимо подключить дополнительные типы на тестовый ящик, то необходимо обратиться к менеджеру в сервисный центр.

**Comment by GilimkhanovDenis** [comment]
Обращение закрываю - развёрнутый ответ дан выше.
В Диадок есть типы документов, доступные всем и доступные только в определённых ящиках, поэтому GeDocumentTypes может давать разные ответы в разных ящиках
