### ISSUE TITLE
Проблемы в работе с ТТН - не получается добавить документы в пакет на отправку исходящих

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#816]
Добрый день.

**Общая информация для упрощения «разбора полётов»:**
Организация:		«ДНС Ритейл»
ИНН:			2540167061
КПП:			254301001
КПП2:			783450001
ID организации:	c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru		
ID участника ЭДО:	2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.37.4.831**.

При попытке разобраться в работе с ТТН в Диадок мы обнаружили следующие проблемы:

# №1
Аналогично проблеме, описанной в https://github.com/diadoc/diadocsdk-1c-docs/issues/815 с документами ТТН также есть момент, что в рабочих ящиках у нас один набор доступных типов ТТН, а в тестовых ящиках - другой.

Список ТТН, доступных в ящике "ДНС Ритейл":
![изображение](https://user-images.githubusercontent.com/33707226/178416414-07c8c416-7c3c-42e2-af50-b31802fede34.png)

Список ТТН, доступных в тестовом ящике "Тестовая организация №2918743":
![изображение](https://user-images.githubusercontent.com/33707226/178416504-e0c817c6-84b9-4784-b4b7-70eeba329c81.png)

**Вопросы:**
1. С чем связано то, что в рабочих и тестовых ящиках поддерживаются разные наборы типов документов?
2. Можно ли сделать так, чтобы в тестовых и рабочих ящиках поддерживались одинаковые типы документов?
3. Если нет, то по какой причине?

# №2. Важно
Нам было непонятно с какими именно ТТН из вышеуказанных возвращаемых АПИ типов нужно и можно работать. 

Мы обратились к менеджеру Контура Черказьянову Д.В., и он нам в ответном письме указал, что рабочими типами документов для ТТН являются только эти:
![изображение](https://user-images.githubusercontent.com/33707226/178417380-d13ca252-8e0b-4dbd-8c95-0ef80c1d3249.png)

А все остальные - устарели и не должны использоваться.

**Вопросы №1:** 
А это действительно так?

А далее мы столкнулись со странной проблемой:
## Ни один из указанных типов ТТН в АПИ не поддерживается в принципе!

Суть:
Мы, как обычно для других типов документов попробовали организовать отправку документов ТТН, используя стандартные методы АПИ:
![изображение](https://user-images.githubusercontent.com/33707226/178417799-b393273c-5c3a-432a-9d31-ffea2d7348e5.png)

Однако, оказалось, что при подключении что к рабочему ящику "ДНС Ритейл", что при подключении к тестовому ящику "Тестовая организация №2918743" мы получаем один и тот же результат:

### У нас не получается добавить документ заданного типа ТТН в пакет документов!

Возможные значения параметров мы получаем через
![изображение](https://user-images.githubusercontent.com/33707226/178418331-31908f46-1252-4084-aaf0-ce1a4d087122.png)

При любом варианте передаваемых параметров возникает ошибка:

// Титул транспортной накладной

Пакет.AddDocument("LogisticsWaybill", "delivery", "kl_trn_mt_05_01")
**Результат:** Произошла исключительная ситуация (PackageSendTask2.AddDocument): Неверный тип документа

Пакет.AddDocument("LogisticsWaybill", "reception", "kl_trn_mt_05_01")
**Результат:** Произошла исключительная ситуация (PackageSendTask2.AddDocument): Неверный тип документа

// Транспортная накладная о приеме груза

Пакет.AddDocument("LogisticsWaybillReception", "default", "kl_trn_mt_01")
**Результат:** Произошла исключительная ситуация (PackageSendTask2.AddDocument): Неверный тип документа

Пакет.AddDocument("LogisticsWaybillReception", "default", "kl_trn_x5_01")
**Результат:** Произошла исключительная ситуация (PackageSendTask2.AddDocument): Неверный тип документа

// Транспортная накладная о сдаче груза

Пакет.AddDocument("LogisticsWaybillDelivery", "default", "kl_trn_mt_01")
**Результат:** Произошла исключительная ситуация (PackageSendTask2.AddDocument): Неверный тип документа

Пакет.AddDocument("LogisticsWaybillDelivery", "default", "kl_trn_pol_01_01")
**Результат:** Произошла исключительная ситуация (PackageSendTask2.AddDocument): В схеме не найден тип элемента

Пакет.AddDocument("LogisticsWaybillDelivery", "default", "kl_trn_x5_01")
**Результат:** Произошла исключительная ситуация (PackageSendTask2.AddDocument): Неверный тип документа

И получается, что мы ни один из указанных видов ТТН не можем добавить в пакет на отправку!

При этом Черказьянов Д.В. сообщил нам, что типы ТТН 
![изображение](https://user-images.githubusercontent.com/33707226/178417380-d13ca252-8e0b-4dbd-8c95-0ef80c1d3249.png)

точно поддерживаются в Диадок, являются актуальными и должны работать.

**Вопросы №2:**
1. Почему не удается добавить никакую ТТН в пакет документов на отправку? АПИ возвращает, что в ящике они доступны, а добавить не получается.
2. Мы указываем какие-то неверные параметры или же что-то неправильно работает в компоненте? Что тогда нужно указать, чтобы добавлять ТТН в пакет на отправку?
3. Можно ли сделать что-то, чтобы мы могли отправлять и получать ТТН? Если есть какая-то проблема в настройке ящиков или в работе компоненты Диадок, из-за чего не удаётся добавить и отправить ТТН, то можно ли это как-то починить?

Спасибо.

**Comment by dimok22prog1** [comment]
Столкнулся с теми же вопросами. Основной вопрос по поводу поддержки типов электронных документов, связанных с ТТН в тестовых ящиках. Будет ли поддержка или как с МЧД тестирование в рабочем окружении?
По поводу работы с формализованной ТТН через компоненту Диадок: хотелось бы немного разъяснений или дополнения раздела "Примеры использования".

**Comment by GilimkhanovDenis** [comment]
### Доступность типов документов в ящиках

Резюмирую https://github.com/diadoc/diadocsdk-1c-docs/issues/815

Есть общедоступные документы, есть документы доступныее только в определённых ящиках. Если необходимо добавить типы документов в какие-то ящики, то обратитесь, пожалуйста, к менеджеру



### Про ошибку `Неверный тип документа`

AddDocument с 3 параметрами можно вызвать для тех типов документов, у которых для первого титула есть упрощённое представление контента (для них можем построить DynamicContent). В противном случае будет ошибка `Неверный тип документа`

Такие титулы нужно загружать уже готовыми ([PackageSendTask2.AddDocumentFromFile](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocumentFromFile), [PackageSendTask2.AddDocumentFromBase64](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocumentFromBase64))

На примере `[LogisticsWaybill, delivery, kl_trn_mt_05_01]`
![image](https://user-images.githubusercontent.com/34439383/183848109-c127b82a-166e-45f8-84c9-6e0bd9c7dc01.png)

В PackageSendTask2  не сможем добавить титул, заполняемый через DynamicContent (первая строка/первый титул не имеет упрощённой схемы)
Но сформировать второй титул (в ReplySendTask2) - сможем


### Ошибка `В схеме не найден тип элемента`
В работе

**Comment by dimok22prog1** [comment]
Я правильно понял, что зафиксированная ошибка (в схеме не найден тип элемента), взятая в работу - это добавление для первого титула упрощенной схемы, для работы с ним через DynamicContent?

**Comment by GilimkhanovDenis** [comment]
@dimok22prog1
В UserDataXSD `[LogisticsWaybillDelivery, default, kl_trn_pol_01_01]` используется описание тэгов, из которого пока не умеем строить DynamicContent.

Доработаем построение DynamicContent'а - можно будет заполнить контент первого титула `[LogisticsWaybillDelivery, default, kl_trn_pol_01_01]`  и всех остальных титулов, где используется (будет использоваться) аналогичное описание тэгов

**Comment by GilimkhanovDenis** [comment]
Ошибка

> Пакет.AddDocument("LogisticsWaybillDelivery", "default", "kl_trn_pol_01_01")
> Результат: Произошла исключительная ситуация (PackageSendTask2.AddDocument): В схеме не найден тип элемента

Исправлена в релизе [5.38.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_38_0.html) - для данного типа документа можно заполнить контент
