### ISSUE TITLE
Метод GetPersonalCertificates() получает сертификат, который уже удален из хранилища

### ISSUE THREAD

**Issue by greenpist** [diadoc/diadocsdk-1c-docs#817]
Использую Diadoc_5_37_5_836_x64.dll

Фрагмент кода:
DiadocApi = Новый ComОбъект("Diadoc.Api.InvoiceApi");

DiadocApi.ApiClientId = [Мой_ключ];
try DiadocApi.ServerUrl   = "https://diadoc-api.kontur.ru:443";
except Message(ОписаниеОшибки());
return Undefined;
endtry;

try TestResult = DiadocApi.TestConnection2();
Message("ConnectionSuccess: "+TestResult.ConnectionSuccess);
except Message("ErrorText: "+TestResult.ErrorText);
return Undefined;
endtry;	        
//все проходит без ошибок

Certificates = DiadocApi.GetPersonalCertificates();
if Certificates.Count = 0 then 
Message("Ни одного сертификата не найдено!");
return Undefined;
endif;
	
//перебор доступных сертификатов
сертификат_найден = ложь;
ТекущийСертификат = Неопределено;
Для нц = 0 по Certificates.Count -1 Цикл
   ТекущийСертификат = Certificates.GetItem(нц); // - здесь получаю один единственный сертификат, просроченный на данный момент, которого нет ни в "Личное" ни на машине.  В службе поддержки Диадок попросили протестировать систему (номер проверки № 33458295 - "компьютер готов к работе"). Через ЛК Диадок актуальный сертификат, прописанный в "Личное" виден, работать с ним получаться. Штатная обработка Диадок также работает без проблем.
Скажите пожалуйста, в чем может быть дело ?

**Comment by Max-Redhead** [comment]
Вижу, вы обратились с техническую поддержку с данным вопроса, удобно продолжить решение вопроса через техническую поддержку ? Ваш вопрос в работе.

**Comment by greenpist** [comment]
Hello Natasha,

В тех поддержку обратился, заявка 47155608.
 
Если вы из этой же структуры, то не надо два раза один вопрос решать. 
Если у вас конечно нет решения сразу.

Tuesday, July 26, 2022, 11:19:36 AM, you wrote:

> Вижу, вы обратились с техническую поддержку с данным вопроса, удобно продолжить решение вопроса через техническую поддержку ? Ваш вопрос в работе.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

-- 
Best regards,
ด้วยความเคารพ
 อันเดร                         ***@***.***

**Comment by Max-Redhead** [comment]
Хорошо, можете обратиться в тех поддержку для уточнения и предоставления информации необходимой для решения или дождаться обратную связь. Вопрос будет решаться в рамках обращения.

**Comment by GilimkhanovDenis** [comment]
Вопрос будет решаться через техподдержку. Это обращение закрываю
