### ISSUE TITLE
Получение полного имени контрагента

### ISSUE THREAD

**Issue by AlexanderShiryaev** [diadoc/diadocsdk-1c-docs#820]
Получаю контрагентов методом GetCounteragentListByInnKpp / GetCounteragentById, но не могу понять, где получить полное имя контрагента. Как я могу его получить?

**Comment by GilimkhanovDenis** [comment]
Если речь про поле [Counteragent](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Counteragent.html).Name, то в нём будет краткое наименование ящика в диадок, если оно заполнено, иначе полное.

Получить полное наименование, если заполнено краткое через компоненту сейчас невозможно
