### ISSUE TITLE
Проблема с получением комментария к уточнению для клиента в роуминге

### ISSUE THREAD

**Issue by SlashSep** [diadoc/diadocsdk-1c-docs#822]
Добрый день!
Используем компоненту 5_37_5_836_x64 для произвольных систем.
Обнаружили проблему, при вызове метода GetAnyComment(AmendmentComment) получаем пустой комментарий, хотя комметарий точно указан. При этом клиент находится в роуминге (возможно это как то связано с проблемой).

С уважением, Алексей.

**Comment by GilimkhanovDenis** [comment]
Добрый день

нужна ссылка на документ

**Comment by SlashSep** [comment]
https://diadoc.kontur.ru/2969e5d4-1da4-43a7-bf74-aca283c24d2f/Document/Show?letterId=553b8bc3-5f3d-485f-b6f0-be6df2fc8612&documentId=59885d5c-3e06-4b8d-8d7c-1064aecf85d2

**Comment by SlashSep** [comment]
Добрый день
Еще раз предоставляю ссылку:
https://diadoc.kontur.ru/2969e5d4-1da4-43a7-bf74-aca283c24d2f/Document/Show?letterId=553b8bc3-5f3d-485f-b6f0-be6df2fc8612&documentId=59885d5c-3e06-4b8d-8d7c-1064aecf85d2

Убедительная просьба ответить как можно скорее.
С уважением, Алексей.

**Comment by GilimkhanovDenis** [comment]
Исправлено в [5.38.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_38_0.html)
