### ISSUE TITLE
Обработка Diadoc1C_UF_5_51_05

### ISSUE THREAD

**Issue by sbrros** [diadoc/diadocsdk-1c-docs#823]
Пришло сообщение что обработка Diadoc1C_UF_5_51_05 перестает работать с 13.09.2022 г.
Данная обработка использовала Dll, методы из самого DLL продолжат выполняться? Новая версия обработки построена на работе через https запросы к web серверу, при этом для работы через сертификат требуется некий плагин, где его можно найти, куда его необходимо установить для работы с ЭЦП хранящимися на сервере приложений 1С.

**Comment by GilimkhanovDenis** [comment]
Добрый день

DLL продолжит работать, если используете собственный ключ API, а не скопированный из модуля

Плагин вшит в универсальный модуль. По его API не консультируем.

Вопросы по универсальному модулю можно задать [здесь](https://github.com/diadoc/diadoc1cpro-docs)

Документация к универсальному модулю находится [здесь](https://developer.kontur.ru/Docs/Diadoc_UM/index.html)
