### ISSUE TITLE
Неверный тип документа при отправке Счет-фактуры

### ISSUE THREAD

**Issue by chuprakova-la** [diadoc/diadocsdk-1c-docs#824]
Здравствуйте! Делаю выгрузку формализованного Счет-фактуры из 1С по API. Версия компоненты 5.37.5.836.
Добавляю документ следующим образом:
TypeNamedId		 = "Invoice";	 //Строка - название типа документа: 
DocumentFunction 	= "СЧФ";		 //Строка - функция документа 
DocumentVersion	 = "utd820_05_01_02_hyphen";	 //Строка - версия документа  
FilePath		 = ИмяФайла;		 //Строка - путь до файла документа
Second_DocumentToSend = SendTask.AddDocumentFromFile(TypeNamedId, DocumentFunction, DocumentVersion, FilePath); 

Файл проверку проходит.
При выполнении метод AddDocumentFromFile выдает ошибку 
«Произошла исключительная ситуация (PackageSendTask2.AddDocumentFromFile): Неверный тип документа»
Подскажите, где ошибка?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Для типа "Invoice" не существует функции "СЧФ" - есть только "default". Убедиться можно, вызвав метод [GetDocumentTypes](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Organization.html?highlight=getdocumenttypes#Organization.GetDocumentTypes)
