### ISSUE TITLE
Проверка статуса документа

### ISSUE THREAD

**Issue by TsysarAndrew** [diadoc/diadocsdk-1c-docs#825]
Добрый день. Используем COM-компоненту DiadocCom_5_37_5_836_x64.dll. Пытаемся проверить статус документа. Нужную информацию нашли в объекте Document, возвращаемому из Organization.GetDocumentById(). Проблема в том, что в 1С не нашли данные, которые можно передать в качестве параметра методу GetDocumentById. У нас есть доп. свойство ИдентификаторДокументаВДиадок. После изучения информации в сети пришли к выводу, что в этом свойстве хранятся необходимые данные, но в зашифрованном виде.  Расшифровать не получилось. 
В сети (и где-то на этом ресурсе) встречали примеры кода с упоминанием функции КонвертироватьЧисло64вГуид, макета КонвертацияBase64. Но в имеющейся у нас обработке Diadoc1C_UF_5_55_05 ничего из этого не нашли.

Вопрос: как можно узнать статус документа при помощи Com-компоненты, имея в наличии значение доп. свойства ИдентификаторДокументаВДиадок? В крайнем случае как получить это значение (ИдентификаторДокументаВДиадок) из свойств Document.DocumentId или Document.PathURL?

**Comment by TsysarAndrew** [comment]
Коллеги, нам бы какую-нибудь обратную связь получить по этому вопросу.

**Comment by ButurlakinSemyon** [comment]
@TsysarAndrew добрый день!
В свойстве "ИдентификаторДокументаВДиадок" хранится строка DocumentId (LetterId+EntityId) в закодированном виде. Функции кодирования и декодирования расположены в модуле объекта самой обработки: КонвертироватьГуидВЧисло64 и КонвертироватьЧисло64вГуид.
 
Статус документа можно посмотреть в [DocflowStatus](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html#:~:text=%D0%BF%D1%80%D0%BE%D1%87%D0%B8%D1%82%D0%B0%D0%BD%20%D1%81%D0%BE%D1%82%D1%80%D1%83%D0%B4%D0%BD%D0%B8%D0%BA%D0%BE%D0%BC%20%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8-,DocflowStatus,-DocflowStatus%20%2C%20%D1%87%D1%82%D0%B5%D0%BD%D0%B8%D0%B5%20%2D%20%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%BE%D0%B2%D0%BE%D0%B5), который возвращается в ответе Organization.GetDocumentById. Для того, чтобы воспользоваться этим методом, нужно указать идентификатор документа DocumentId. Который, в свою очередь, можно получить из "ИдентификаторДокументаВДиадок" при помощи функции декодирования.
