### ISSUE TITLE
Metadata errors: Невозможно получить данные по ключу: /Файл/СвУчДокОбор/@ИдПол

### ISSUE THREAD

**Issue by dimok22prog1** [diadoc/diadocsdk-1c-docs#826]
Здравствуйте.
При отправке документов на одного из Покупателей (64bedcbd51bd469c8fbfa4242997961f@diadoc.ru) выходит ошибка:

Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid generated title:
Metadata errors: Невозможно получить данные по ключу: /Файл/СвУчДокОбор/@ИдПол
Validation errors: 

SendTask.CounteragentId заполняем указанным идентификатором.
Документ добавляем: DocumentToSend1 = SendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01");

Подскажите, пожалуйста, в чем может быть дело, куда посмотреть? С остальными Покупателями таких проблем не было и нет.

**Comment by kulakovskaya** [comment]
Здравствуйте. Приложите техническую информацию из модуля.

**Comment by GilimkhanovDenis** [comment]
Добрый день
SendTask.CounteragentId не влияет на заполнение контента.

Проверьте как заполнили поле
`Content.UniversalTransferDocumentWithHyphens.RecipientFnsParticipantId`
и коллекцию
`Content.UniversalTransferDocumentWithHyphens.Buyers`

**Comment by GilimkhanovDenis** [comment]
Добрый день

В данном сценарии Диадок не смог однозначно определить получателя документа, поэтому в контенте тэг `/Файл/СвУчДокОбор/@ИдПол` остался незаполненным - по данным ИНН-КПП нашлось **два** роуминговых ящика.

Чтобы избегать подобных ситуаций рекомендую перейти на версию `utd820_05_01_02_hyphen` - в них можно в явном виде указать идентификатор получателя (`Content.UniversalTransferDocumentWithHyphens.RecipientFnsParticipantId`)
