### ISSUE TITLE
Просмотр УПД с функцией СзВК

### ISSUE THREAD

**Issue by cnor22** [diadoc/diadocsdk-1c-docs#833]
При попытке посмотреть УПД с функцией СзВК (загружено через файл xml)
Функция="СвЗК" ПоФактХЖ="Документ, включающий в себя сведения о факте закупки комиссионером (агентом, действующим от собственного имени) товаров для комитента (принципала)"

Получаем 

Просмотр документа недоступен.
Скачайте документ, чтобы посмотреть его содержимое.

Это еще не реализовано, или какая-то ошибка в xml файле. При загрузке файла ошибок не возникло...

**Comment by ylmanchik** [comment]
@cnor22 Добрый день!
Подскажите, каким методом вы пользуетесь для просмотра и какая версия компоненты у вас сейчас установлена.

**Comment by cnor22** [comment]
XML файл формируется самостоятельно из 1С . Без использования компоненты. А просмотр в веб интерфейсе
 Результат загрузки с компьютера. Вроде без ошибок…
При попытке просмотра.

 "Просмотр документа недоступен.
Скачайте документ, чтобы посмотреть его содержимое."

скрины и загружаемый файл отправил почтой

**Comment by ylmanchik** [comment]
Прошу прощения, а на какую почту? 
Т.е. у вас сформированный файл из 1С (без использования API Диадока и модуля Диадок) не открывается для предпросмотра в веб?

**Comment by cnor22** [comment]
На почту ответом на письмо…

Да сформированный файл без использования API и модуля Диадок. Прошедший валидацию при загрузке не открывается в веб. Вернее он открывается, но не показывает содержимое. 

Результат загрузки файла
![изображение2](https://user-images.githubusercontent.com/108237374/188902161-98277cb1-c342-437c-abce-c3fee550b241.png)

Результат попытки просмотра

![изображение3](https://user-images.githubusercontent.com/108237374/188902245-a093d163-3d44-4310-a9a4-4043c4fcbe35.png)



Тот же файл просматривается в системе
 СБИС ( https://sbis.ru/formats/report?section=ROSSTAT). Кнопка "Открыть мой документ". Там содержимое файла показывается правильно.
Прилагаю файл. Так как в github нельзя закачать файлы xml - изменил расширение на txt. Для использования измените расширение на xml.

[ON_NSCHFDOPPR_2BM-7810896123-2013041210303216390830000000000_2BM-7810896123-2013041210303216390830000000000_20220901_324cb60e-1d49-4a7c-8e14-d76b328f9d2d.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/9506938/ON_NSCHFDOPPR_2BM-7810896123-2013041210303216390830000000000_2BM-7810896123-2013041210303216390830000000000_20220901_324cb60e-1d49-4a7c-8e14-d76b328f9d2d.txt)

**Comment by ylmanchik** [comment]
Добрый день! Да, печатная форма для СзВК ещё не реализована.

**Comment by cnor22** [comment]
Возможно сориентировать по времени, когда будет реализация? Пользоваться сторонними ресурсами не очень удобно....

**Comment by cnor22** [comment]
XML файл формируется самостоятельно из 1С . Без использования компоненты. А просмотр в веб интерфейсе
 
 
Результат загрузки с компьютера
 
 
Вроде без ошибок…
При попытке просмотра.
 

Загружаемый файл прикрепляю.
 
  
>Вторник, 6 сентября 2022, 8:45 +03:00 от ylmanchik ***@***.***>:
> 
> 
***@***.*** Добрый день!
>Подскажите, каким методом вы пользуетесь для просмотра и какая версия компоненты у вас сейчас установлена.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you were mentioned. Message ID:  <diadoc/diadocsdk-1c-docs/issues/833/1237684179 @ github . com> 
 
 
--
За сим и подписуюсь, Михаил Иванов

**Comment by GilimkhanovDenis** [comment]
Из последнего комментария делаю вывод, что вопрос к компоненте не относится

сроки реализации функциональности в веб интерфейсе предлагаю узнавать у теподдежрки
