### ISSUE TITLE
Доступность типов документов в ящиках (ТТН)

### ISSUE THREAD

**Issue by dimok22prog1** [diadoc/diadocsdk-1c-docs#835]
Здравствйуте. Подскажите пожалуйста, в случае добавления документа  LogisticsWaybill для тестового ящика, можно ли через компоненту сформировать и отправить первый титул (убедиться, что сформировали корректно и отправляется) или обязательно потребуется подключение данного ящика к сервису Контур.Логистика?
_________________________
### Доступность типов документов в ящиках

Резюмирую https://github.com/diadoc/diadocsdk-1c-docs/issues/815

Есть общедоступные документы, есть документы доступныее только в определённых ящиках. Если необходимо добавить типы документов в какие-то ящики, то обратитесь, пожалуйста, к менеджеру

### Про ошибку `Неверный тип документа`

AddDocument с 3 параметрами можно вызвать для тех типов документов, у которых для первого титула есть упрощённое представление контента (для них можем построить DynamicContent). В противном случае будет ошибка `Неверный тип документа`

Такие титулы нужно загружать уже готовыми ([PackageSendTask2.AddDocumentFromFile](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocumentFromFile), [PackageSendTask2.AddDocumentFromBase64](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html#PackageSendTask2.AddDocumentFromBase64))

На примере `[LogisticsWaybill, delivery, kl_trn_mt_05_01]`
![image](https://user-images.githubusercontent.com/34439383/183848109-c127b82a-166e-45f8-84c9-6e0bd9c7dc01.png)

В PackageSendTask2  не сможем добавить титул, заполняемый через DynamicContent (первая строка/первый титул не имеет упрощённой схемы)

_Originally posted by @GilimkhanovDenis in https://github.com/diadoc/diadocsdk-1c-docs/issues/816#issuecomment-1210332386_

**Comment by GilimkhanovDenis** [comment]
Попробую ответить

1. Если в ящике подключён тип LogisticsWaybill, то компонента позволит его отправить, получить и выполнить полный документооборот каким бы он ни был. Подключение типа в ящике необходимо обсуждать с менеджером
2. Если для указанных `Типа + Функции + Версии + Номер титула` документа Диадок предоставляет упрощённую схему, то компонента предоставит DynamicContent для заполнения
3. Нужно ли подключать Контур.Логистика? На этот вопрос у команды, разрабатывающей COM Диадок, нет ответа. Всё зависит от того какие бизнес процессы закрываются в Контур.Логистика. Если эти процессы реализуемы через API Диадок, то их можно решить с помощью компоненты (Если какая-то часть из них в компоненте не реализована, но API Диадок в принципе позволяет закрыть эти процессы, то можно оставить пожелание здесь, через техподдержку или через менеджера). Думаю, вопрос о необходимости подключения Контур.Логистика следует решать с вашим менеджером
