### ISSUE TITLE
Метод GetOrganizationById() выдает ошибку "Отсутствует доступ к ящику организации"

### ISSUE THREAD

**Issue by SlashSep** [diadoc/diadocsdk-1c-docs#836]
Добрый день!
Используем компоненту 5_38_1_846 для произвольных систем.
Ранее работали не версии 5_37_5_836. После перехода на новую версию возникла проблема:
Подключаемся как обычно по отпечатку сертификата
select @MethodStr = 'CreateConnectionByCertificate("'+@Thumbprint+'")'
EXECUTE @rc = sp_OAMethod @DiadocAPI, @MethodStr, @DiadocConnect output
Тут без ошибок.
Далее получаем организацию
select @MethodStr = 'GetOrganizationById('+@Organizationid+')'
EXECUTE @rc = sp_OAMethod @DiadocConnect, @MethodStr, @Organization output
А вот тут получаем ответ: "Отсутствует доступ к ящику организации"
Для примера организация: 02cd8398df764ead9e1d966d85512641@diadoc.ru

В чем может быть дело?
С уважением, Алексей.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Вызов GetOrganizationById,приводящий к ошибке - это первый вызов метода в сеансе?

**Comment by SlashSep** [comment]
Добрый день!
Данного метода - да.
Последовательность такая:
EXECUTE @rc = sp_OACreate 'Diadoc.DiadocClient', @DiadocAPI OUTPUT
<ServerUrl, ApiClientId>

select @MethodStr = 'CreateConnectionByCertificate("'+@Thumbprint+'")'
EXECUTE @rc = sp_OAMethod @DiadocAPI, @MethodStr, @DiadocConnect output

select @MethodStr = 'GetOrganizationById('+@Organizationid+')'
EXECUTE @rc = sp_OAMethod @DiadocConnect, @MethodStr, @Organization output

Вот что странно, для организации 88ce1a3e398043738665a9bef3b4d714@diadoc.ru такой ошибки не происходит.

С уважением, Алексей

**Comment by GilimkhanovDenis** [comment]
А в `@organizationId` случайно нет пробелов в начале или конце?

И можете ещё сказать по какому отпечатку авторизовываетесь (`@thumbprint`)?

**Comment by SlashSep** [comment]
Пробелов нет.
Thumbprint = c80ef3053529e01a0b518bb2bea501ea3f7a2c89

**Comment by GilimkhanovDenis** [comment]
Я правильно понял:
авторизуетесь по сертификату `c80ef3053529e01a0b518bb2bea501ea3f7a2c89` и в ящик [88ce1a3e398043738665a9bef3b4d714@diadoc.ru](mailto:88ce1a3e398043738665a9bef3b4d714@diadoc.ru) попасть можете, а в [02cd8398df764ead9e1d966d85512641@diadoc.ru](mailto:02cd8398df764ead9e1d966d85512641@diadoc.ru) - нет?

Не наоборот?

**Comment by SlashSep** [comment]
Нет, не так. У нас множество ЮЛ и на каждое ЮЛ свой сертификат.
Не могу попасть, ошибка:
Organizationid = 02cd8398df764ead9e1d966d85512641@diadoc.ru
CFns = 2BM-5404376181-2012052808381752102630000000000
Thumbprint = c80ef3053529e01a0b518bb2bea501ea3f7a2c89

Без ошибок:
Organizationid = 88ce1a3e398043738665a9bef3b4d714@diadoc.ru
CFns = 2BM-5406225935-2012052808271851462630000000000
Thumbprint = 88f4fb418cd92e00f752f8917be8fa79e20247de

**Comment by SlashSep** [comment]
Пока откатились на пред версию 5_37_5_836 - там все работает.

**Comment by GilimkhanovDenis** [comment]
Попробуйте, пожалуйста, на [5.38.2](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_38_2.html)

**Comment by SlashSep** [comment]
Версия: COM x64 5.38.2.852
ОШИБКА: DiadocCom.CreateConnectionByCertificate. WIN32[0x00000057]WinHttpOpen The parameter is incorrect.

**Comment by GilimkhanovDenis** [comment]
Сделайте, пожалуйста для новой ошибки новый тикет

Эта ошибка была и в 5.38.0 и в 5.38.1. занимаюсь ей

**Comment by SlashSep** [comment]
Ок
