### ISSUE TITLE
Ошибка в методе CreateConnectionByCertificate

### ISSUE THREAD

**Issue by SlashSep** [diadoc/diadocsdk-1c-docs#838]
Версия: COM x64 5.38.2.852
ОШИБКА: DiadocCom.CreateConnectionByCertificate. WIN32[0x00000057]WinHttpOpen The parameter is incorrect.

С уважением, Алексей

**Comment by GilimkhanovDenis** [comment]
Временное решение - указать [DiadocAPI](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DiadocAPI.html).ProxyMode отличный от `UseDefaultProxy`

**Comment by GilimkhanovDenis** [comment]
Исправлено в [5.38.3](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_38_3.html)
