### ISSUE TITLE
Получение содержимого таблицы документа

### ISSUE THREAD

**Issue by Potapovdn** [diadoc/diadocsdk-1c-docs#839]
Здравствуйте!
Подскажите, как получить товары/услуги из табличной части документа? Они необходимы для сопоставления товаров/услуг, занесённых в 1С, при этом сам документ в 1С ещё не отражен. 
Есть вариант получения, не скачивая xml-файл?
Что из структуры документа для этого можно использовать?

![image](https://user-images.githubusercontent.com/112869285/188592680-66310a00-2a0b-4fcc-b59c-a1b5973e5e0d.png)
![image](https://user-images.githubusercontent.com/112869285/188593004-2643fe3a-ca80-48bf-9c2b-976feb675142.png)
![image](https://user-images.githubusercontent.com/112869285/188594751-d5e8cd94-4054-44d1-a04d-21278e3941c9.png)

**Comment by GilimkhanovDenis** [comment]
Получение контента документа осуществляется с помощью метода [GetDynamicContent](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html#DocumentBase.GetDynamicContent)

Дальше нужно смотреть на структуру контента

Аналогичный вопрос: https://github.com/diadoc/diadocsdk-1c-docs/issues/509

**Comment by Potapovdn** [comment]
> Добрый день! Уточните, пожалуйста, откуда вы берете эти данные, в какой момент и как получаете? Хочется понять, где вы планируете это использовать и как?

Добрый день. Эта структура входящего документа в Диадоке. Мне необходимо получить список входящих УПД от к/а, но только с определенным видом услуг, который указывается в табличной части

**Comment by AleksandrSurin** [comment]
Добрый день!
Если я вас правильно понял, вы хотите сразу получить список только нужных документов, согласно вашего фильтра, то не получится. В любом случае придется получить какой-то пул документов и по ним пробежаться.

**Comment by Potapovdn** [comment]
> Добрый день! Если я вас правильно понял, вы хотите сразу получить список только нужных документов, согласно вашего фильтра, то не получится. В любом случае придется получить какой-то пул документов и по ним пробежаться.

Все верно. Я получаю весь пулл документов и среди них нужно выбрать с определенным видом услуг, при этом, желательно, не скачивать xml на каждый документ. Вот и интересует, возможно ли это

**Comment by AleksandrSurin** [comment]
Вы можете воспользоваться предложенным выше (@GilimkhanovDenis) методом
