### ISSUE TITLE
В представлении УПД поле название контаргента нет "ИП"

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#84]
Подскажите, пожалуйста, как сделать чтобы в представление УПД в поле название контрагента выходило ИП, например
![img-2017-03-30-13-11-09](https://cloud.githubusercontent.com/assets/20082460/24499615/fa6e326c-154a-11e7-91bd-fa64e1dab2e3.png)
Вот так заполнен xml
![img-2017-03-30-13-09-16](https://cloud.githubusercontent.com/assets/20082460/24499627/02f436d4-154b-11e7-96bb-d3f9053ff472.png)
![img-2017-03-30-13-10-04](https://cloud.githubusercontent.com/assets/20082460/24499639/0a3d513c-154b-11e7-837f-6ae62184fc38.png)

**Comment by LyubovZykova** [comment]
Форма визуализации в вебе Диадока унифицированная, более того, слово "ИП" или фраза "Индивидуальный предприниматель" автоматически обрезается из ФИО, т.к. нет у ИП такой фамилии "ИП Иванов", есть просто Иванов, а ИП - это форма собственности.
Но если вам очень нужно и ваш контрагент и/или налоговая не проверяют правильность заполнения тега Фамилия в блоке контрагента, то можно указать "ИП_Иванов".
