### ISSUE TITLE
Описание API по выгрузки данный по ОСУ в 1с7.7

### ISSUE THREAD

**Issue by UnT0xA** [diadoc/diadocsdk-1c-docs#840]
Добрый день.
Необходимо отправить в Контур.Диадок сведения об объемно сортовом учете, но в описании API не нашел ничего как передавать эти данные.
В документации нашел описание как передать сведения о товаре 
https://developer.kontur.ru/Docs/diadoc-api/proto/utd/UniversalTransferDocumentSellerTitleInfo.html?highlight=extendedinvoiceitem
но в нем нет ничего чтоб касалось ОСУ.
Подскажите как осуществить передачу сведений по ОСУ ?

**Comment by Max-Redhead** [comment]
Документ нужно заполнять, используя документацию: https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_post_document.html или генерировать через dynamicContent (https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html)
