### ISSUE TITLE
Выгружаются не все входящие документы через AddIn в 1с

### ISSUE THREAD

**Issue by bBubbleGum** [diadoc/diadocsdk-1c-docs#841]
Здравствуйте. В выборку попадают не все входящие документы. В ходе тестирования выяснили, что не попали документы со статусом **`Подписан всеми получателями`**. 
`PathURL `не попавшего в выгрузку:

`/aa8fa5a5-33b7-4bf4-a549-ce7f42737049/Document/Show?letterId=2c0afaa0-2221-4811-831e-f83a6f9d7e5c&documentId=35dc2538-6f16-415c-a494-806ed0eed2a1`

Код для получения документов по дате получения:

```
DiadocConnection = DiadocApi.CreateConnectionByLogin(Логин, Пароль);  
Organization = DiadocConnection.GetOrganizationById(BoxId);
SearchDocumentTask = Organization.GetDocumentsTask();
НачалоПериода = НачалоДня('20220829');
КонецПериода = КонецДня('20220829');
SearchDocumentTask.FromSendDate = НачалоПериода;
SearchDocumentTask.ToSendDate   = КонецПериода;
	
//Входящие
SearchDocumentTask.Category = "Any.Inbound"; 
DocumentList = SearchDocumentTask.GetDocuments();
```

**Comment by GilimkhanovDenis** [comment]
Это дубль https://github.com/diadoc/diadocsdk-1c-docs/issues/837
