### ISSUE TITLE
ВНИМАНИЕ! Проблемы с сайтом документации и компонент ЭДО (https://diadocsdk-1c.readthedocs.io)

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#844]
Добрый день.

При попытке зайти по адресам:
https://diadocsdk-1c.readthedocs.io
https://diadocsdk-1c.readthedocs.io/ru/
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html

появляется ошибка, что такой страницы нет:
![изображение](https://user-images.githubusercontent.com/33707226/191657386-f1cd382a-ffcd-4bc7-a2d8-e5a4aa40ba3a.png)

В итоге - нельзя документацию посмотреть, нельзя компоненты АПИ скачать.

Это как-то будет чиниться?
Уже несколько дней такое.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Пока исправляю можно пользоваться ссылкой
https://1c-docs.diadoc.ru/ru/latest/
или
https://developer.kontur.ru/Docs/Diadoc/COM/index.html

**Comment by GilimkhanovDenis** [comment]
Вернул доступ по ссылкам
https://diadocsdk-1c.readthedocs.io/
https://diadocsdk-1c.readthedocs.io/ru/
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
