### ISSUE TITLE
Подписание УПД через CreateReplySendTask2. Подписывает не той подписью, которая указан в SignerReference.CertificateThumbprint

### ISSUE THREAD

**Issue by ptizaezhik** [diadoc/diadocsdk-1c-docs#848]
До сих пор мы работали с одной ЭЦП директора и проблем не было.
Сейчас хотим использоваться разные ЭЦП,

Отпечаток подписи передаю так (использую CreateReplySendTask2()):

ReplySendTask = ДокументДиадок.CreateReplySendTask2("AcceptDocument");
....
Signers = Doc.Signers;
Signers.AddItems();

SignerReference = Signers.items.GetItem(0).SignerReference;
SignerReference.BoxId = ОрганизацияДиадок.Id;
**SignerReference.CertificateThumbprint = ОтпечатокHEX**;

ReplySendTask.Send()

Проверяю, что отпечаток корректный:
![Диадок подпись](https://user-images.githubusercontent.com/82872143/194049563-fc930569-a848-48c1-9e4b-a6a25cd37726.jpg)

Но документ в итоге подписывается сертификатом директора (отпечаток в "синеньком pdf"другой).
Сотрудник с нужным сертификатом в Личном кабинете заведен.
Причем, сначала новый сертификат "по-умолчанию" (и полномочия для УПД) не указали в ЛК - лезла ошибка, т.к. Диадок пытался найти сертификат:
Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalTransferDocumentBuyerTitle/Signers/SignerReference: @Inn is required
/UniversalTransferDocumentBuyerTitle/Signers/SignerReference: SignerDetails not found for boxId=819b7633-95ab-4644-95a3-d2a59a38b331, thumbprint=85D5DCCBF753987C02C4EEE4B6849EA675643913, documentTitleType=8

Когда его указали - подписание идет, но сертификатом директора.
Как подписать нужным сертификатом?

Ссылка на документ для примера
https://diadoc.kontur.ru/819b7633-95ab-4644-95a3-d2a59a38b331/Document/Show?letterId=e8c89996-b505-4071-9084-6b52cb74b14c&documentId=38cf5dfa-f7e1-42d8-a9fa-9b4f67040a04

**Comment by ptizaezhik** [comment]
Примечание:

Само соединение с Диадок устанавливаю через CreateConnectionByCertificate. И там указывают отпечаток директора. В этом может быть дело? Тогда непонятно, что чего вообще указывать SignerReference.CertificateThumbprint  ?

**Comment by ptizaezhik** [comment]
Сейчас сделал и CreateConnectionByCertificate - по нужному сертификату. Так сработало!
Но всё равно странно: для чего нужен CertificateThumbprint , если всё указано в соединении ?

**Comment by GilimkhanovDenis** [comment]
SignerReference используется для формирования блока Подписант в XML. Обычно там указываются ФИО, должность, Полномочия и прочее (см. https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/ExtendedSignerDetailsToPost.html)

Подписание любого контента идёт тем сертификатом, по которому авторизовались.

Это две независимые друг от друга истории
