### ISSUE TITLE
Не верное наименование покупателя при передаче в BoxId

### ISSUE THREAD

**Issue by Alekseevda** [diadoc/diadocsdk-1c-docs#849]
Добрый день.
Работаем через com-компоненту.
Передаем покупателя через BoxId:
	Buyer = Utd820_SellerContent.Buyers.AddBuyer();
	Buyer.OrganizationReference.BoxId = Guid;
	Buyer.OrganizationReference.OrgType = "1";

В результате в УПД не верное наименование покупателя, в самой карточке ошибок нет
Guid = "cfc4c18042b74d99bb51c0c18e012b12@diadoc.ru"
Ссылка на УПД:
https://diadoc.kontur.ru/87a6ba56-08de-478f-8f97-9d8287c38fa0/Document/Show?letterId=75110dbc-2e84-4312-adf5-dac69e7a448c&documentId=3e20754f-5008-489c-ae32-05b9db5f4dad

**Comment by GilimkhanovDenis** [comment]
Название ящика в Диадок исправлено. Титул должен генерироваться с правильным названием контрагента
