### ISSUE TITLE
Вопрос по отправке данных Грузополучателя. Очень срочно. Отправка в первой декаде апреля.

### ISSUE THREAD

**Issue by ckyrun** [diadoc/diadocsdk-1c-docs#85]
Организация работает с региональными потребителями, поэтому покупатель, это головная организация в Москве, а грузополучатель в регионе. Грузополучатель списывает НДС, поэтому в УПД должен быть указан ИНН/КПП филиала-грузополучателя. В своей базе они добавляют эти данные в строку адреса грузополучателя, опираясь на письмо ФНС. Как в рамках Диадока можно разместить ИНН\КПП грузополучателя? Поле Иные сведения предлагал, их не устраивает.

**Comment by LyubovZykova** [comment]
Например, так <ГрузПолуч>
        <ИдСв>
          <СвЮЛУч НаимОрг="ООО Авто (тестовая)" ИННЮЛ="2012600006" КПП="222222222" />
        </ИдСв>
        <Адрес>
          <АдрРФ КодРегион="22" Город="1" />
        </Адрес>
      </ГрузПолуч>
В формате УПД унифицирован блок сведений об организациии наименование и ИНН являются обязательной информацией для юрлица независимо от того, кем оно является - грузоотправителем, грузополучателем, продавцом или покупателем.

**Comment by ckyrun** [comment]
Укажите, пожалуйста, куда поместить в COM-объект. В COM-объекте в данных грузополучателя заполнены ИНН и КПП, но в вебформе УПД этих данных я не вижу.

**Comment by ckyrun** [comment]
В xml эти данные отражены:
-<ГрузПолуч ИнфДляУчаст="тест111111111111111111111111111111">
-<ИдСв>
<СвЮЛУч **ИННЮЛ="9636244023"** НаимОрг="Филиал организация №3624402" **КПП="963601000"**/>
</ИдСв>
-<Адрес>
<АдрРФ Дом="135" Улица="Аустрина ул" Город="Пенза г" КодРегион="58" Индекс="442250"/>
</Адрес>
</ГрузПолуч>
но в вебформе и pdf: "Филиал организация №3624402, 442250, Пензенская область, Пенза г, Аустрина ул, 135" нет ИНН и КПП. Почему!?

**Comment by ckyrun** [comment]
Нужно признак какой нибудь заполнить в COM-объекте?

**Comment by ckyrun** [comment]
Ссылка на обсуждаемый документ https://diadoc.kontur.ru/48ad04b4-af63-4a72-901c-f19b698c31cc/Document/Show?letterId=99452e45-58c4-40f1-bfd0-4ea5207675b0&documentId=a3a2a3fc-33ee-49e0-ad22-f8794034a738

**Comment by LyubovZykova** [comment]
Все данные вы передаете правильно, просто было непонятно, что говорите о печатной форме документа в веб-интерфейсе Диадока. 
Ваш контрагент может данные ИНН/КПП грузополучателя проверять в своей учетной системе и на их основании дальше маршрутизировать документ.
Если маршрутизацию контрагент будет делать вручную, то, т.к. общая печатная форма УПД для всех унифицирована, то вам нужно обратиться к своему менеджеру или специалисту по внедрению и попросить настройку кастомной печатной формы УПД.
Такой запрос также можно сделать через техподдержку  http://www.diadoc.ru/support
