### ISSUE TITLE
Как получить GUID организации по FnsParticipantId идентификатор организации-участника документооборота

### ISSUE THREAD

**Issue by darujo** [diadoc/diadocsdk-1c-docs#850]
Добрый день.
Подскажите пожалуйста  как получить GUID организации или объект организации по FnsParticipantId (идентификатор организации-участника документооборота)?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Можете рассказать о сценарии, в котором нужно узнавать идентификатор ящика по идентификатору участника ЭДО ?

**Comment by darujo** [comment]
Добрый день. У нас интеграция через ком библиотеку. Для отправки документа нужно получить доступ к организации своей или контр агента. В личном кабинете можно только увидеть FnsParticipantId. А для отправки документа  контр агенту нужен Guid. Такую информацию можно взять из входящих документов, но не понятно как ее получить если таких документов нет.

**Comment by GilimkhanovDenis** [comment]
Сейчас таких методов в библиотеке нет

Получить свою организацию можно, используя метод Connection.GetOrganizationList() и далее выбирая необходимую организацию. 

А поиск контрагентов можно делать по статусу контрагента, по ИНН-КПП и т.д.:
[GetCounteragentById()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Organization.html#Organization.GetCounteragentById)

[GetCounteragentByOrgId()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Organization.html#Organization.GetCounteragentByOrgId)

[GetCounteragentListByStatus()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Organization.html#Organization.GetCounteragentListByStatus)

[GetCounteragentListByStatusAsync()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Organization.html#Organization.GetCounteragentListByStatusAsync)

[GetCounteragentListByInnKpp()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Organization.html#Organization.GetCounteragentListByInnKpp)

[GetCounteragentListByInnKppAsync()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Organization.html#Organization.GetCounteragentListByInnKppAsync)

[GetCounteragentListByInnList()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Organization.html#Organization.GetCounteragentListByInnList)


В полученных объектах будет информацию о FnsParticipantId

**Comment by GilimkhanovDenis** [comment]
Добавил возможность получения контрагента по идентификатору участнка ЭДО в [5.39.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_39_0.html)
