### ISSUE TITLE
Метод GetDocumentEventList() не возвращает событие подписания для одного исходящего документа 

### ISSUE THREAD

**Issue by ptizaezhik** [diadoc/diadocsdk-1c-docs#852]
Добрый день!
Помогите с проблемой, пожалуйста. Сквозь глухую оборону обычной техподдержки больше недели пробиться не можем.

Метод GetDocumentEventList() не возвращает событие подписания для одного исходящего документа.

Документ https://diadoc.kontur.ru/819b7633-95ab-4644-95a3-d2a59a38b331/Document/Show?letterId=d2aa0483-eb9b-4239-a8ca-20618d821dcc&documentId=99157f7b-f430-4c3f-82b7-f4825475631f

Подписан покупателем 03.10.2022 в 7:59 (судя по данным ЛК)

![7-59](https://user-images.githubusercontent.com/82872143/196873620-8a2b193b-ac7c-41cb-ae5d-50500011a76d.jpg)

Но метод GetDocumentEventList() не возвращает событий в этом диапзоне (см. вложение – список событий за этот период, в 7-58 и 7-59 нет ни одного события, возможно и другие документы пропущены).
[GetDocumentEventList.xls](https://github.com/diadoc/diadocsdk-1c-docs/files/9826934/GetDocumentEventList.xls)

Проверялось на версиях компоненты 5_38_3_853 и 5_36_5_760.

Почему нет события подписания в GetDocumentEventList()?

**Comment by ptizaezhik** [comment]
Разбираемся с техподдержкой, отпишусь о результатах.

**Comment by GilimkhanovDenis** [comment]
Закрою

Если понадобится, техподдержка сама эскалирует запрос на нас
