### ISSUE TITLE
Как получить секунды из DocumentBase.Timestamp

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#853]
Здравствуйте. В документации к Диадок COM/1C Addin SDK  для поля Timestamp объекта DocumentBase написано, что поле содержит дату и время отправки документа, но в 1С 7.7 при обращении к этому полю возвращается только дата без времени. Как получить время? Знаю, что у объекта DocumentBase есть поле TimestampSeconds, но данное поле помечено как устаревшее и видимо в будущем будет отключено.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Можете рассказать как эти данные планируется использовать?

Вообще, поле Timestamp  возвращает OLE DATE, которое содержит и дату, и время.

В 1С этот тип превращается в тип Дата.
А в 1С 7.7, насколько понимаю, тип Дата не содержит в себе данных о часах/минутах/секундах и в этом вся проблема

**Comment by evgen421** [comment]
Здравствуйте Денис. Спасибо за отклик. Планируется использовать при записи в 1С информации о событиях в ящике  диадока, чтобы работала сортировка по дате и времени. В данное время для работы с диадоком используется одновременно и API и компонента. В компоненте, насколько я понял, еще не реализована стабильная работа с лентой событий, поэтому пока используется API для получения ленты событий и там без проблем можно получить дату и время из поля CreationDateTime. Хотелось бы использовать только компоненту для получения событий, но обнаружилась вышеуказанная проблема и как её решить в рамках компоненты я не знаю! Может кто нибудь подскажет?

**Comment by GilimkhanovDenis** [comment]
Можете подсказать из какого контракта API поле CreationDateTime используете ?
И в каком виде записываете это значение в 1С. То есть хочется понять какие типы вы используете в сортировке по Дате и Времени

У документа поле Timestamp и TimestampSeconds не обновляются при получении новых событий после доставки документа до контрагента и в этом случае не очень понятен сценария в контексте его использования для сохранения ленты событий.

Что касается ленты. Она есть и в ней события в хронологическом порядке идут, но она очень старая, поэтому хотим её обновить, если поймём, что в ней есть большая потребность у интеграторов

**Comment by evgen421** [comment]
Здравствуйте Денис.

Не совсем понял, что такое контракт API.

Значение записывается в том виде, в котором его возвращает компонента, а возвращает компонента всегда дату без времени. Вообще это глобальная проблема внешних компонент в 1С 7.7. При получении данных формата DateTime или Timestamp компоненты всегда возвращает только дату. Решается проблема только если удается задать в запросе возвращать данные в строковом формате. Даже если не нужно сортировать документы по времени, то все равно необходимо знать не только дату выгрузки документа в ЭДО, но и время.

Сценарий простой, необходимо записать в базу данных сведения из ленты событий. Поступил новый документ, нужно записать его идентификатор, дату и время выгрузки в ЭДО и т.д., а в дальнейшем обновляются только статусы документа.

А что касается ленты, просто хотелось бы использовать во всех сценариях только внешнюю компоненту и не использовать запросы к API. Сейчас приходится комбинировать использование компоненты и API.

**Comment by GilimkhanovDenis** [comment]
Задача на добавление какого-нибудь типа данных, который бы позволил работать с DateTime в 1С 7.7 добавлена в бэклог. сроков нет

Если это крайне необходимая фича, то предлагаю обратиться к менеджеру, чтобы он продвигал эту задачу в очереди на разработку

**Comment by evgen421** [comment]
Спасибо.
