### ISSUE TITLE
Ошибка в адресе контрагента при попытке отправить документ PackageSendTask2.Send

### ISSUE THREAD

**Issue by AllianceAvia** [diadoc/diadocsdk-1c-docs#854]
Добрый день!

Используем Com-компоненту x64.
Заполняем BoxId покупателя (т.е. в этом случае адрес покупателя не указываем, адрес берется из Диадок):
          
`Buyer.OrganizationReference.BoxId = 48952d26b0874a5288abad19db42f45a@diadoc.ru`

При попытке отправить комплект документов получаем ошибку в адресе (в регионе):

```
Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalTransferDocumentWithHyphens/Buyers/Buyer/OrganizationReference: Could not recognize Address/RussianAddress/@Region= 
```

Ошибку получаем именно для ящика 48952d26b0874a5288abad19db42f45a@diadoc.ru, с остальными контрагентами такой ошибки нет. В поддержке нам сказали, что адрес у этого контрагента в Диадоке заполнен. 

В чем тогда может быть проблема?

PS. Контрагент роуминговый

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Проверьте сейчас

**Comment by AllianceAvia** [comment]
Спасибо. Работает.
