### ISSUE TITLE
Типы и версии документов для функции AddDocument

### ISSUE THREAD

**Issue by WoockY1** [diadoc/diadocsdk-1c-docs#857]
Добрый день, 
SendTask = Organization.CreatePackageSendTask2();
DocumentToSend = SendTask.AddDocument(**"UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01"**);

А где можно посмотреть список всех возможных типов и версий документов для функции?
Например УКД последней версии в формате СЧФДОП: какие аргументы в функции AddDocument передавать?

**Comment by OsnND** [comment]
Добрый день.
Тип, функция и версия документа вы можете получить из ответа Organization.GetDocumentTypes(). 
Ссылка в документации: https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Organization.html#Organization.GetDocumentTypes

**Comment by WoockY1** [comment]
Спасибо, то, что требуется!
