### ISSUE TITLE
Не возвращаются входящие документы на запрос

### ISSUE THREAD

**Issue by Gin1980** [diadoc/diadocsdk-1c-docs#860]
При запросе документов с отбором
DocumentsTask.Category		= "Any.Inbound"
Получаем список документов, но он не содержит УПД NSCHFDOPPRMARK
В чем причина?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Какую компоненту используете?
В каком ящике работаете?
Как заполнен DocumentsTask помимо поля Category ?

**Comment by Gin1980** [comment]
32,  последняя с сайта
Вот весь код
Модуль подключения
	DiadocApi					= Новый ComОбъект("Diadoc.DiadocClient");
	sidДиадок					= "Фирма.Sid;
	DiadocApi.ApiClientId			=   sidДиадок;
	DiadocApi.ServerUrl			= "https://diadoc-api.kontur.ru:443";
	ОтпечатокСертификата			= СертификатОтпечаток();
	DiadocConnection				= DiadocApi.CreateConnectionByCertificate(ОтпечатокСертификата);
	OrganizationList				= DiadocConnection.GetOrganizationList();
	Organization					= OrganizationList.GetItem(0);

Модуль запроса документа:
        DocumentsTask					= Organization.GetDocumentsTask();
 	DocumentsTask.FromDocumentDate 	= НачалоГода(ТекущаяДата());
	DocumentsTask.ToDocumentDate 		= КонецГода(ТекущаяДата());
        DocumentsTask.Category		        = "Any.Inbound";
        DocumentList					        = DocumentsTask.GetDocuments();

Итог возвращает документы без УПД

**Comment by GilimkhanovDenis** [comment]
В каком ящике вы работаете?
Поле `Organization.Guid`

**Comment by Gin1980** [comment]
ff9a379ec7c74639a1055914963eb9c0@diadoc.ru

**Comment by GilimkhanovDenis** [comment]
Это из устаревшего поля Id? а поле Guid есть в объекте?

**Comment by Gin1980** [comment]
Да из поля ID

**Comment by GilimkhanovDenis** [comment]
Это поле вы в конфигураторе видите?
А поле Guid ?

**Comment by Gin1980** [comment]
> Это из оставшегося поля Id? на поле Руководство есть в объекте?

**Comment by Gin1980** [comment]
![Безымянный](https://user-images.githubusercontent.com/118940739/203710228-c570b164-8c77-45f0-8dcf-ca2aaedf6305.png)

**Comment by GilimkhanovDenis** [comment]
Почему спрашиваю: нашёл ваше обращение в техподдежрку. и там сказано, что использовали версию [5.3.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.3.0). Эта версия была выпущена до того как появился УПД. В ней же у объекта Organization нет поля Guid. но есть поле Id.

Если видите Id, но не видите Guid, то значит у вас подключилась старая компонента

На последней версии с заданными параметрами поиска возвращается 17 документов и УПД среди них есть

**Comment by GilimkhanovDenis** [comment]
![image](https://user-images.githubusercontent.com/34439383/203710608-f2f1734a-53cf-4e0e-bcf4-756de5cce761.png)

Вот так объект Organization выглядит на последней версии

**Comment by GilimkhanovDenis** [comment]
Итого пока получаем, что подключилась старая версия, которая не знает про тип документа УПД, поэтому в списке документов не может превратить информацию о них в объект

Обновите до последнего релиза и проверьте, что подключился именно он. Проверить версию подключённой компоненты можно методом [DiadocApi.GetFullVersion()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DiadocAPI.html#DiadocAPI.GetFullVersion)

**Comment by Gin1980** [comment]
Эммм... скачивалась с ссылок с описанием "Текущие версии внешней компоненты"
Можете предоставить ссылку на актуальные версии

**Comment by Gin1980** [comment]
Скиньте пжл ссылку на актуальную версию. Спс

**Comment by GilimkhanovDenis** [comment]
https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html
М
Можете скинуть ссылку, которой воспользовались вы, для получения своей версии

**Comment by Gin1980** [comment]
https://sdk-new.readthedocs.io/en/latest/Downloads.html#id2

**Comment by GilimkhanovDenis** [comment]
Понятно. Это чей-то форк  старой документации

**Comment by Gin1980** [comment]
Спс...а то я тут бьюсь какой день
