### ISSUE TITLE
Клиенты в роуминге

### ISSUE THREAD

**Issue by Gin1980** [diadoc/diadocsdk-1c-docs#862]
Добрый день!
Отправляем УПД клиенту через API, ИД правильный. Клиент роуминговый. В справочниках присутствует. НО при загрузке подхватывается контрагент вообще с другим ИД (не роуминговый с тем же ИНН,КПП)

**Comment by GilimkhanovDenis** [comment]
Добрый день

Из описания не понятно какие объекты и как заполняете

Возможно, в решении помогут:
- https://github.com/diadoc/diadocsdk-1c-docs/issues/717
- https://github.com/diadoc/diadocsdk-1c-docs/issues/715

и аналогичные
