### ISSUE TITLE
При авторизации автоматически создает сотрудника

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#865]
В компании сменился Генеральный Директор. Соответственно, сертификат старого гендира отвязали от всех сотрудников и при попытки авторизоваться в веб-интерфейсе выдается ошибка . Что-то типа "сертификат не привязан ни к одному сотруднику". И дается отлуп.
А вот при авторизации по старому сертификату через компоненту 1C v 7.7 неожиданно был автоматически создан сотрудник, к которому привязался этот старый сертификат и установлены полные права.
Это чего такое?

**Comment by ylmanchik** [comment]
Добрый день!
Обратитесь, пожалуйста, в техническую поддержку Диадок. Здесь потребуется детальная проверка по организации и пользователям.

**Comment by dorexpro** [comment]
А нам это зачем? Это в вашей системе дырень в безопасности. Со своей стороны мы этот глюк учли.

**Comment by VladdPush** [comment]
Добрый день! К сожалению, без информации о конкретном сценарии с вашей стороны и сбора полноценной информации, нет возможности дать пояснение по ситуации и указать на точную причину.
