### ISSUE TITLE
Ошибка DocumentBase.CreateReplySendTask2

### ISSUE THREAD

**Issue by AlexanderZhukovXX** [diadoc/diadocsdk-1c-docs#866]
Добрый день. У нас своя разработка по обмену документами ЭДО. Используется Диадок COM 5.34.4. Сегодня перестали подписываться документы с ошибкой "Нет документов, для которых возможно формирование ответного задания выбранного типа". Что-то случилось/изменилось?

Пример документа d9361e1f-b578-433d-a8b5-ec046c527bf6d50e1c25-d541-4955-932d-540373e08ab6

**Comment by vlad3190** [comment]
У нас такая же ошибка сегодня появилась! Версия компоненты 5.37.4.831. Вчера все работало!
Пример документа: https://diadoc.kontur.ru/55cb15b1-a79b-4bca-9f6f-1fde3c26f17d/Document/Show?letterId=0a7045ef-dbaa-4ea8-929a-5ee3219c852e&documentId=03c82cc6-e99d-44f3-a128-765dbb1d35d4

**Comment by tigr182** [comment]
У нас такая же ошибка сегодня появилась! Версия компоненты 5.34.2.707. Вчерашние документы успешно подписываются.

**Comment by darujo** [comment]
У нас таже проблема

**Comment by OsnND** [comment]
Ошибка связана с изменениями https://www.diadoc.ru/blog/31211-v_diadoce_dopolnenie_podtverzhdeniyami_o_dostavke
Необходимо обновить компоненту на актуальную. Скачать её можно по ссылке: https://diadoc-api.kontur.ru/1c-addin/

**Comment by Decabtry** [comment]
Такая же проблема. В блоге ничего не сказано что перестанут работать методы.

**Comment by vlad3190** [comment]
Коллеги, подскажите что означает данная ошибка? 
"Произошла исключительная ситуация (DiadocApiInvoiceApi.CreateConnectionByCertificate2): LIBHTTP[0x0000001F] base address must be absolute"

Версия компоненты: 5.39.0.861

**Comment by GilimkhanovDenis** [comment]
@vlad3190 по этой ошибке создайте отдельное обращение

И проверьте как заполняете DiadocApiInvoiceApi, включая настройки прокси

> Коллеги, подскажите что означает данная ошибка? "Произошла исключительная ситуация (DiadocApiInvoiceApi.CreateConnectionByCertificate2): LIBHTTP[0x0000001F] base address must be absolute"
> 
> Версия компоненты: 5.39.0.861
