### ISSUE TITLE
Произошла исключительная ситуация (DiadocApiInvoiceApi.CreateConnectionByCertificate2): LIBHTTP[0x0000001F] base address must be absolute

### ISSUE THREAD

**Issue by vlad3190** [diadoc/diadocsdk-1c-docs#867]
Коллеги, добрый день!
Подскажите, что означает данная ошибка: **_**"Произошла исключительная ситуация (DiadocApiInvoiceApi.CreateConnectionByCertificate2): LIBHTTP[0x0000001F] base address must be absolute"**_**?
Версия компоненты: Diadoc_5_39_0_861_x64

Вызов:
//Получение списка сертификатов
Certificates = DiadocApi.GetPersonalCertificates();

//Создание соединения
ОтпечатокСертификата = Certificates.GetItem(0);
DiadocConnection = DiadocApi.CreateConnectionByCertificate2(ОтпечатокСертификата);

**Comment by GilimkhanovDenis** [comment]
Добрый день

ошибка означает, что не задан адрес подключения (DiadocApi.ServerUrl)
