### ISSUE TITLE
Как понять для ответного действия по документу требуется титул или нет кроме как  DocumentWorkflow.id?

### ISSUE THREAD

**Issue by darujo** [diadoc/diadocsdk-1c-docs#868]
Добрый день.

Подскажите, пожалуйста.  Как понять для ответного действия по документу требуется титул или нет кроме как  [DocumentWorkflow](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentWorkflow.html#documentworkflow).id? 
Чтобы при добавление очередного вида документов не приходилось дорабатывать систему.

**Comment by GilimkhanovDenis** [comment]
Добрый день, вариант без использования WorkflowId написан [здесь](https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_reply_document.html) - через  Reflector
