### ISSUE TITLE
Ошибки работы компонент 5.37.4.831 и 5.39.0.861

### ISSUE THREAD

**Issue by MaximGlazunov** [diadoc/diadocsdk-1c-docs#869]
Добрый день!

Сегодня мы устанавливали более свежие компоненты Диадок (до этого была версия 5.36.3.747), а именно 5.37.4.831 и 5.39.0.861, и у обеих компонент была обнаружена следующая ошибка: неверно отрабатывают методы (были проверены GetFullVersion(), TestConnection() и TestConnection2()).
Метод GetFullVersion() возвращает вместо строки COM-объект с полями ConnectionSuccess и ErrorText (то, что должен возвращать TestConnection2()), а TestConnection2() выдает ошибку, что недостаточно параметров.
При установке текущей компоненты эти ошибки пропадают.

**Comment by GilimkhanovDenis** [comment]
Добрый день

такое поведение означает, что неправильно подключена компонента. Интеграция могла закэшировать виртуальную таблицу методов одной компоненты и использовать её при подключении другой. В итоге идёт обращение по неправильным адресам и соответсвенно вызов не тех методов, которые ожидаете
