### ISSUE TITLE
Ошибка при получении документа типа Исправительная УПД

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#87]
Используем "COM-компонента для встраивания в произвольные системы- версия 5.15.0.179" 
Получаем ленту событий (в ней отправленные новые документы типа Исправительные УПД, цель прокачать в базу статусы документа "доставлено") 
массивEvent = Organization.GetDocumentEventList(ПоследнийЗагруженныйEventID);
В ленте вот так отображается событие (новый исправительные УПД):
![img-2017-04-03-15-53-05](https://cloud.githubusercontent.com/assets/20082460/24740239/c68b3a18-1aa8-11e7-82be-cdf4d86a594c.png)
Видно что документ исходящий, но не определен тип.
Далее, если сделать команду Event.GetDocument(),
Для ц = 0 по массивEvent.Count-1 цикл 
				Event = массивEvent.GetItem(ц);
				Document = Event.GetDocument();
КонецЦикла;	
то выпадает ошибка при вызове метода контекста (GetDocument): Произошла исключительная ситуация (BoxEvent.GetDocument): Данный тип документа не поддерживается. Допустимыми являются следующие значения: NonformalizedAcceptanceCertificate, Invoice, InvoiceCorrection, InvoiceCorrectionRevision, InvoiceRevision, Nonformalized, NonformalizedProforma, NonformalizedTorg12, TrustConnectionRequest, XmlAcceptanceCertificate, XmlTorg12

**Comment by jakeqwert** [comment]
Отправляем испр. УПД так же как и обычные УПД 
SendTask = Organization.CreateSendTask("UniversalTransferDocument");
Заполняем только поля номер и дата исправления, на сайте все отображается хорошо, в скачанном архиве "документооборот целиком" тоже все замечательно. Вот только при работе через "COM-компонента для встраивания в произвольные системы- версия 5.15.0.179" не возвращаются статусы таких документов, очень не удобно, просим исправить, а так же при отправке методом  SendTask.Send() для такого типа документов не возращается Document

**Comment by azhipaigor** [comment]
Большое спасибо за обратную связь! Действительно, в текущем релизе 5.15.0 COM-компоненты не прокинут тип документа иУПД в GetDocumentEventList и SendTask.Send. Пофиксил. Выпустим в 5.16.0.
