### ISSUE TITLE
Ошибки метода CreateReplySendTask2()

### ISSUE THREAD

**Issue by MaximGlazunov** [diadoc/diadocsdk-1c-docs#870]
Добрый день!

Уже второй день при подписании документов в диадок падает ошибка при вызове метода CreateReplySendTask2().
Описание ошибки: Нет документов, для которых возможно формирование ответного задания выбранного типа.
Как правило, эта ошибка возникает, если документ уже подписан в диадок, но все проверенные документы были в ожидании подписи (за редким исключением).
В понедельник, 19.12.2022, все работало, во вторник уже нет. На тот момент стояла компонента 5.36.3.747, сегодня установили 5.39.0.861, но ничего не изменилось.
Между 19.12.2022 и 20.12.2022 никаких изменений в работу своих систем мы не вносили.

**Comment by ptizaezhik** [comment]
Сегодня на версии 5_39_0_861 тоже была такая ошибка на некоторых документах, например: https://diadoc.kontur.ru/819b7633-95ab-4644-95a3-d2a59a38b331/Document/Show?letterId=bbe4c31c-6385-46f5-bfb0-56b39c1d7644&documentId=d39cd8f3-bbf1-4d1e-845d-99fbabfcfb63

Подписали через ЛК

**Comment by guzhakovskiy** [comment]
Проверьте версию dll, через которую у вас происходит отправка. У нас та же ошибка была 20.12.2022., пришлось завершить все процессы 1с, почистить папку Temp.

**Comment by MaximGlazunov** [comment]
Серверный кэш почистили, Temp почистили, сервер перезагрузили - не помогло.
Ошибка "Нет документов, для которых возможно формирование ответного задания выбранного типа" пока не появляется, но падает "Неизвестная ошибка", причем то на одном методе, то на другом.

**Comment by MaximGlazunov** [comment]
Поиграли с настройками компоненты - все работает. Всем спасибо.

**Comment by ptizaezhik** [comment]
> Поиграли с настройками компоненты - все работает. Всем спасибо.

Какие настройки? Можно подробнее?

**Comment by MaximGlazunov** [comment]
В свойствах компоненты, вкладка "Activation", поменяли с "Server application" на "Library application"

**Comment by ptizaezhik** [comment]
> В свойствах компоненты, вкладка "Activation", поменяли с "Server application" на "Library application"

Погодите. Мы говорит про dll и её работу из 1С. Какие там вкладки?

**Comment by MaximGlazunov** [comment]
С dll все в порядке было.
У нас на сервере, в приложении Component Servises установлена компонента Диадок. По ней ПКМ, свойства. Дальше то, что я уже описал.

**Comment by ylmanchik** [comment]
@ptizaezhik Добрый день! Ошибка ещё воспроизводится?
