### ISSUE TITLE
ReplySendTask2.Send: DocumentService.NotAllowedForLockedPacket (Http.Conflict)

### ISSUE THREAD

**Issue by tigr182** [diadoc/diadocsdk-1c-docs#872]
Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask2.Send): #https://github.com/diadoc/diadocapi-docs/issues/100[Ошибка сервера Диадок]code:409, HTTP error: ErrorCode: DocumentService.NotAllowedForLockedPacket (Http.Conflict)

**Comment by tigr182** [comment]
Подписываются входящие документы в формате (Накладные), а (УПД) выходит данная ошибка

**Comment by andersonru** [comment]
Аналогичная ошибка. Возникла при обновлении на DiadocCom_5_39_0_861.dll. 
Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:409, HTTP error: ErrorCode: DocumentService.NotAllowedForLockedPacket (Http.Conflict)

Закрытый пакет от поставщика, в котором есть 3 документа: 2 требуют подписи, 1 не требует. Соответственно подписать отдельные документы нельзя.
При этом стало давать подписать по одному документу (в закрытом пакете) если требует подписи только 1 документ, а другой не требует

**Comment by tigr182** [comment]
Каким образом подписывать документы, которые только требуют подписи?

**Comment by andersonru** [comment]
Вызывать CreateReplySendTask2("AcceptDocument") не у DocumentPackage, а у DocumentBase.

Например пакет состоит из УПД (требует подписи) +Реестр сертификатов (не требует подписи). Подписывать только УПД.
А вот когда в пакете УПД (требует подписи) + Протокол согласования цен (требует подписи) + Реестр сертификатов (не требует подписи) уже не получается

**Comment by tigr182** [comment]
Ну у меня как во втором варианте, в пакете УПД 3 документа.

**Comment by andersonru** [comment]
Значит баг не обойти, а только ждать исправления

**Comment by tigr182** [comment]
Уже прошла целая неделя после обновления, документов очень много приходится пока через ЛК подписывать.

**Comment by andersonru** [comment]
Долго сидели на старой версии dll. Вчера обновили - теперь подписывать вручную. Повезло, что только 1 поставщик присылает такие закрытые пакеты

**Comment by GilimkhanovDenis** [comment]
Добрый день

Попробуйте на версии [5.39.1](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.39.1)

**Comment by andersonru** [comment]
Спасибо. Подписывает!

**Comment by tigr182** [comment]
> Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask2.Send): #[https://github.com/diadoc/diadocapi-docs/issues/100[Ошибка](https://github.com/diadoc/diadocapi-docs/issues/100%5B%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B0) сервера Диадок]code:409, HTTP error: ErrorCode: DocumentService.NotAllowedForLockedPacket (Http.Conflict)
