### ISSUE TITLE
Код ошибки 409 "ErrorCode: DocumentService.InvalidDocumentState (Http.Conflict)

### ISSUE THREAD

**Issue by tigr182** [diadoc/diadocsdk-1c-docs#873]
Вчера выполнили обновление компоненты до версии 5_39_0_861. От 2 поставщиков документы в формате (Накладные) нормально подписываются, а от 1 документы в формате (УПД) выходит данная ошибка (Код ошибки 409 "ErrorCode: DocumentService.InvalidDocumentState (Http.Conflict)")

**Comment by GilimkhanovDenis** [comment]
Добрый день
Если правильно понимаю, то в https://github.com/diadoc/diadocsdk-1c-docs/issues/872 речь про тот же пакет документов

Нужна ссылка на любой из документов этого пакета. И опишите что пытаетесь сделать, создаёте ReplySendTask2 для каждого отдельного документа или для всего пакета - то есть нужен сценарий воспроизведения ошибки. чем подробнее, тем лучше

**Comment by tigr182** [comment]
![Uploading 2.JPG…]()
Я не силен во всем вот данные которые получаю. ReplySendTask2 для всего пакета

**Comment by tigr182** [comment]
Кто-нибудь сталкивался? пока что приходится через сайт подписывать.

**Comment by JohnSergeev** [comment]
Добрый день. 

Странно. С 23.12.2023 (включительно) на АПИ COM x64 5.39.0.861 успешно подписано более 6100 входящих документов. Ни одной ошибки.

**Comment by GilimkhanovDenis** [comment]
Здесь закрытость пакета может влиять. Сегодня буду разбираться

**Comment by GilimkhanovDenis** [comment]
Добрый день

Попробуйте на версии [5.39.1](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.39.1)
