### ISSUE TITLE
Здравствуйте, при подписании документа возникает ошибка Invalid data UserContractData

### ISSUE THREAD

**Issue by vladimir4385** [diadoc/diadocsdk-1c-docs#874]
Подробное описание ошибки:Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 2, Position: 38, /UniversalTransferDocumentBuyerTitle[1]/@DocumentCreator: The 'DocumentCreator' attribute is invalid - The value '' is invalid according to its datatype 'string1000' - The actual length is less than the MinLength value.
Line: 2, Position: 2, /UniversalTransferDocumentBuyerTitle[1]: The element 'UniversalTransferDocumentBuyerTitle' has incomplete content. List of possible elements expected: 'Signers'.
/UniversalTransferDocumentBuyerTitle: One of the fields must be present: @OperationContent, ContentOperCode

**Comment by GilimkhanovDenis** [comment]
Добрый день

В диадоке появлись WorkflowId 18 и 19. Ответ на них формируется точно так же как для 16 и 3, соответственно. Проверьте, что в интеграции учтены новые WorkflowId

В целом можно отказаться от анализа WorkflowId документа и смотреть на тип интерфейса, вернувшегося из компоненты - тогда появление новых типов документооборота вас не заденет. Сделать это можно с помощью Reflector. [Пример](https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_reply_document.html)

**Comment by vladimir4385** [comment]
Добрый день ! Но там возвращается object
--
Отправлено из Mail.ru для Android пятница, 23 декабря 2022г., 14:22 +03:00 от Гилимханов Денис  ***@***.*** :

**Comment by GilimkhanovDenis** [comment]
Значит, это DynamicContent и его нужно заполнить. Ошибка говорит о том, что не заполнены обязательные элементы

**Comment by vladimir4385** [comment]
Доброго времени суток всем.
Искренне надеюсь, что не отвлекаю. Я изо всех сил пытаюсь показать всем своим знакомым эту новость - https://t.me/s/mpt_slava/post/31
Слава - это мой пл стахович ем сапрыкин яш


С уважением,
Владимир Теслинов
***@***.***
