### ISSUE TITLE
Оправка в пакете документа типа Waybill

### ISSUE THREAD

**Issue by ElenaBurnasheva** [diadoc/diadocsdk-1c-docs#875]
Здравствуйте. Возникла необходимость отправлять в пакете документов вместе с УПД Транспортную накладную (файл pdf). 
Для добавления в пакет  выполняется следующий код:
SendTask = Organization.CreatePackageSendTask2();
НовДок=SendTask.AddDocumentFromFile("Waybill","default","nonformalizedwaybill_01_01",ПутьКФайлу); 
MetaDataItem =НовДок.AddMetadata(); 
MetaDataItem.Key   = "FileName";
MetaDataItem.Value = ИмяФайла; 
//таким же образом в метаданные добавлется номер и дата документа
При  отправке документа вылезает ошибка: Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: MessageToPost.DocumentAttachments[1]: TwoSided workflow is not supported for Waybill

Как отправить транспортную накладную в виде сканированного изображения в пакете?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Документооброт этого типа документа предполагает, что можно отправить только через промежуточного получателя. Укажите `SendTask.ProxyBoxId`

**Comment by ElenaBurnasheva** [comment]
А какой идентификатор мне туда записать, если нет промежуточного получателя? Себя же? Или идентификатор получателя?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Ядро диадок не позволяет использовать отправителя или получателя в качестве промежуточного получателя. Возможно, для вашего бизнес процесса нужно использовать другой тип документа ( TypenamedId, DocumentFuction, DocumentVersion)

Если подходящий вам тип документа в ящике не подключен, то обратитесь к менеджеру
