### ISSUE TITLE
Изменение подразделения в исходящем документе

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#876]
Подскажите, пожалуйста, как переместить отправленный документ в другое подразделение?

**Comment by GilimkhanovDenis** [comment]
[DocumentBase.Move](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html?highlight=move#DocumentBase.Move)

**Comment by dorexpro** [comment]
Спасибо.
