### ISSUE TITLE
Странное поведение метода GetEmployees() (очень похоже на ОШИБКУ)

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#877]
Добрый день.

При попытке перейти с использования объявленного устаревшим метода **GetUsers()** на его «заменитель» **GetEmployees()**:
![изображение](https://user-images.githubusercontent.com/33707226/209292302-5128139a-35e5-41f9-b73e-edbbbdacbe7e.png)

мы столкнулись с несколько непонятным для нас поведением этого метода.

Либо мы что-то не понимаем в его работе (а в документации никаких пояснений нет!):
![изображение](https://user-images.githubusercontent.com/33707226/209292338-b9c1fa33-aa93-4c97-9ba9-656189b0a2b6.png)
 
### Либо в работе метода есть какая-то ошибка.

**Общая информация для упрощения «разбора полётов»:**

Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
КПП2: 783450001
ID организации: c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru                
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.39.0.861**.

**Детали:**

# 1
Подключаемся к организации по ЭЦП №1 (Кравченко О. В.):
![изображение](https://user-images.githubusercontent.com/33707226/209292537-0badd451-aaed-42e1-a6b0-54b1306bc41b.png)
 
ЭЦП Кравченко О. В. привязан к пользователю Кравченко О.В., не являющемуся администратором.

Выполняем «старый» метод GetUsers(). Получаем список из 90 (девяноста) пользователей организации.
![изображение](https://user-images.githubusercontent.com/33707226/209292586-f9390b2f-e7f0-4fb5-8bfd-3f7e98a55b1c.png)
 
Выполняем «новый» метод GetEmployees(). Получаем список из 90 (девяноста) пользователей организации. В новом формате данных.
![изображение](https://user-images.githubusercontent.com/33707226/209292628-c14ce4f2-98af-4a8a-aae1-c503b5b5fdb3.png)

Заходим под этим пользователем на сайт Диадок:
![изображение](https://user-images.githubusercontent.com/33707226/209294997-0722db5b-755c-401a-bfb3-0fb5e6215b30.png)

Т.к. это не администратор, то доступа к пользователям на сайте мы не имеем.

# 2
Повторим всё то же самое, используя ЭЦП №2 (Кучинская И. Е.):
![изображение](https://user-images.githubusercontent.com/33707226/209295178-8e018d6f-8187-4ed5-94ff-e0c343ab2830.png)
![изображение](https://user-images.githubusercontent.com/33707226/209293537-6bd300b9-c476-4e33-83fe-2fc7ded4c0de.png)
   
ЭЦП Кучинской И.Е. привязан к пользователю Копылов Н.А., являющемуся администратором.

Выполняем «старый» метод GetUsers(). Получаем список из 90 (девяноста) пользователей организации.
![изображение](https://user-images.githubusercontent.com/33707226/209292900-ca9cc184-5643-419e-a475-db345bad33c1.png)

Выполняем «новый» метод GetEmployees(). Получаем список из **50 (пятидесяти)** пользователей организации. В новом формате данных.
![изображение](https://user-images.githubusercontent.com/33707226/209292926-8d3ece19-e138-4c68-8b17-4067394418ac.png)
 
Заходим под этим пользователем на сайт Диадок. Т.к. ЭЦП привязан к пользователю Копылов Н.А., то вход на сайт будет выполнен под ним. Т.к. он администратор, то мы можем перейти к списку пользователей:
![изображение](https://user-images.githubusercontent.com/33707226/209293683-3253b303-11a5-4f74-88de-232403c919b8.png)
![изображение](https://user-images.githubusercontent.com/33707226/209293913-32867712-8c84-4950-adfe-f6241bd9b988.png)

И на сайте мы видим, что **по организации заведено именно 90 (девяносто) сотрудников. А не 50.**

### Вопросы:
1.	Почему «новый» метод GetEmployees() возвращает разное количество пользователей по организации? Иногда верное (90), а иногда – нет (в нашем последнем примере – 50). При этом «старый» метод GetUsers() всегда возвращает верное количество пользователей в организации?

2.	Это какая-то ошибка в работе GetEmployees()? Или это какая-то недокументированная особенность её поведения? 
Если второе, то можно получить разъяснение – почему и в каких ситуациях GetEmployees() возвращает меньшее количество сотрудников и по какому принципу происходит их включение и не включение в итоговый список? А также можно ли, чтобы эта информация была добавлена в документацию в описание метода?

Надеемся на скорейшее получение информации по данному вопросу.
И на исправление ошибки, если это ошибка.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Попробуйте на версии [5.39.1](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.39.1)

**Comment by JohnSergeev** [comment]
Спасибо! Постараемся сегодня-завтра посмотреть.

**Comment by JohnSergeev** [comment]
Проверил. Всё работает.
Спасибо!
