### ISSUE TITLE
Неверное (регистрозависимое) поведение новой функции GetCounteragentByFNSParticipantId()

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#878]
Добрый день.

При попытке реализации работы с новой функцией  GetCounteragentByFNSParticipantId() мы были, скажем так, несколько удивлены её поведением.

### С нашей точки зрения – это ошибка в работе функции.

**Общая информация для упрощения «разбора полётов»:**

Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
КПП2: 783450001
ID организации: c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru                
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.39.0.861**.

 ## Детали:
Рассмотрим результаты поиска тех или иных контрагентов «старым» поиском GetCounteragentById() и «новым» поиском GetCounteragentByFNSParticipantId().

### Пример №1

Контрагент: "КОМИТЕТ ИМУЩЕСТВЕННЫХ И ЗЕМЕЛЬНЫХ ОТНОШЕНИЙ"
ИД: [8f37d9cfb5ff477a95281807570c7954@diadoc.ru](mailto:8f37d9cfb5ff477a95281807570c7954@diadoc.ru)
GUID: 8f37d9cf-b5ff-477a-9528-1807570c7954
ИД ФНС: 2bef48269083f82494e93ef70d03f8d3b38
Оператор ЭДО: Тензор

Поиск по ИД / GUID  + поиск по ИД ФНС
![изображение](https://user-images.githubusercontent.com/33707226/209504714-dc4c7567-2bfc-43dc-9543-116ba46ddc3e.png)

Поиск по ИД (детали)
![изображение](https://user-images.githubusercontent.com/33707226/209503975-53fa2e19-b8f6-4410-b861-38711b373ad3.png)

Поиск по ИД ФНС (детали)
![изображение](https://user-images.githubusercontent.com/33707226/209504003-356b32d4-ec37-4b57-b7e9-4900c4817bbf.png)

**Результат:**
Поиск по ИД методом GetCounteragentById() работает **независимо** от регистра поданной на поиск строки ИД / GUID. 
Поиск по ИД ФНС методом GetCounteragentByFNSParticipantId() **явно зависим от регистра подаваемой строки поиска** и выдает верный результат только, если ему «нравиться» регистр поданной строки (т.е. он, похоже, находит контрагента, только если регистр строки поиска совпадает с регистром ИД ФНС где-то у вас в системе, где происходит поиск).

### Пример №2

Контрагент: МБУ "КДК"
ИД: [e04e093ecbe2408392874cd823d2605d@diadoc.ru](mailto:e04e093ecbe2408392874cd823d2605d@diadoc.ru)
GUID: e04e093e-cbe2-4083-9287-4cd823d2605d
ИД ФНС: 2BM-3338006625-333801001-201902051250251182466
Оператор ЭДО: Диадок

Поиск по ИД / GUID + поиск по ИД ФНС
![изображение](https://user-images.githubusercontent.com/33707226/209505116-00f03e9d-8869-4bc8-b7a5-14b1bbd490a1.png)

Поиск по ИД (детали)
![изображение](https://user-images.githubusercontent.com/33707226/209505219-910077a2-32db-48c1-a132-23c6d713135e.png)

Поиск по ИД ФНС (детали)
![изображение](https://user-images.githubusercontent.com/33707226/209505261-b7aea424-165e-43aa-a669-eaf68a136c48.png)

**Результат:**
Поиск по ИД методом GetCounteragentById() работает **независимо** от регистра поданной на поиск строки ИД / GUID. 
Поиск по ИД ФНС методом GetCounteragentByFNSParticipantId() **явно зависим от регистра подаваемой строки поиска** и выдает верный результат только, если ему «нравиться» регистр поданной строки (т.е. он, похоже, находит контрагента, только если регистр строки поиска совпадает с регистром ИД ФНС где-то у вас в системе, где происходит поиск).

### Пример №3

Контрагент: ООО "ПРОГРЕСС ТЕХНОЛОДЖИ"
ИД: [056659ef1dde420cb72a08a81b513fd0@diadoc.ru](mailto:056659ef1dde420cb72a08a81b513fd0@diadoc.ru) 
GUID: 056659ef-1dde-420c-b72a-08a81b513fd0
ИН ФНС: 2AE450D5387-F6F5-4FC8-8CF9-6114C3B9A82E
Оператор ЭДО: Калуга Астрал

Поиск по ИД / GUID  + поиск по ИД ФНС
![изображение](https://user-images.githubusercontent.com/33707226/209505620-391f9451-3817-4258-8c6f-4dd5f8e4e132.png)

Поиск по ИД (детали)
![изображение](https://user-images.githubusercontent.com/33707226/209505696-ca3db4b5-8e5c-474a-ae43-2963355b7796.png)

Поиск по ИД ФНС (детали)
![изображение](https://user-images.githubusercontent.com/33707226/209505744-bf15bbb1-b517-401f-a216-a77039e94c78.png)

**Результат:**
Поиск по ИД методом GetCounteragentById() работает **независимо** от регистра поданной на поиск строки ИД / GUID. 
Поиск по ИД ФНС методом GetCounteragentByFNSParticipantId() **явно зависим от регистра подаваемой строки поиска** и выдает верный результат только, если ему «нравиться» регистр поданной строки (т.е. он, похоже, находит контрагента, только если регистр строки поиска совпадает с регистром ИД ФНС где-то у вас в системе, где происходит поиск).

## Выводы:
1.	Поиск по ИД / GUID методом GetCounteragentById() работает **ОЖИДАЕМО**. 
Его результат не зависит от регистра поданной на вход строки. Что совершенно верно, т.к. мы в общем случае не знаем и знать не можем в каком регистре в ИД / GUID того или иного контрагента записаны отдельные буквенные символы.

2.	Поиск по ИД ФНС методом GetCounteragentByFNSParticipantId() работает **НЕ ОЖИДАЕМО**. 
На текущий момент он **регистрозависим**.

### С нашей точки зрения он работает неправильно.

А, т.к. мы в общем случае не знаем и знать не можем в каком регистре в ИД ФНС того или иного контрагента записаны отдельные буквенные символы, то данный метод на текущий момент для правильных результатов поиска можно использовать только одним образом – выполняя поиск по одному ID множество раз, в попытках «угадать» верный регистр символов искомой строки ИД ФНС. 

Т.е. только перебрав с отрицательным результатом все возможные комбинации ИД ФНС, заменяя регистр букв в ИД, и получив для всех вариантов отрицательный результат мы можем утверждать, что контрагента с "таким" ИД ФНС в Контур.Диадок нет. Насколько мы понимаем, для этого нужно перебрать 2 в степени N вариантов, где N - количество буквенных символов в ИД ФНС. Например, для ИД ФНС из примера №1 это будет 2 в степени 11 - 2048 проверок!

Пока что предварительно мы в своих механизмах поиска контрагентов вызываем этот метод дважды – один раз по строке ИД ФНС в нижнем регистре, и один раз по строке ИД ФНС в ВЕРХНЕМ регистре. 

Но это не дает нам полной гарантии, т.к. мы не уверены на 100%, что не может быть ИД ФНС в котором будут встречаться и «маленькие», и «большие» символы. А такие ИД ФНС в текущей реализации поиска найти… ну практически невозможно – разве, что случайно повезет угадать регистр всех буквенных символов в ИД ФНС!

### Вопросы и предложения:
Мы считаем, что текущая реализация GetCounteragentByFNSParticipantId() ошибочна. 
И требуется доработка этой функции так, чтобы она была регистронезависима к передаваемым параметрам поиска (ИД ФНС).

**Просим вас исправить поведение функции GetCounteragentByFNSParticipantId() и привести её к регистронезависимому**
**поведению, каковым, например, обладает поиск функцией GetCounteragentById().**

При невозможности (?!) подобной доработки просим вас дать разъяснения по поводу причин этого, а также объяснение каким образом тогда пользоваться этой функцией, если для поиска контрагента в Контур.Диадок мы, как правило, используем ИД ФНС, получаемые от контрагентов, и у нас нет никакой гарантии, что они будут переданы нам в нужном регистре символов.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Попробуйте на версии [5.39.1](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.39.1)

**Comment by JohnSergeev** [comment]
Спасибо! Постараемся сегодня-завтра посмотреть.

**Comment by JohnSergeev** [comment]
Проверил. Всё работает как надо.
Спасибо!
