### ISSUE TITLE
ExtendedOrganizationInfo - BoxId

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#88]
В ExtendedOrganizationInfo
BoxId (строка, чтение/запись) - идентификатор ящика организации в Диадок.

Если контрагент роуминговый, в этом случае тоже работает автоматическое заполнение?

**Comment by denver069** [comment]
Насколько я понимаю вы имеете ввиду структуру API Диадока http://api-docs.diadoc.ru/ru/latest/proto/utd/ExtendedOrganizationInfo.html, если это так то поля OrgName, Inn, Kpp, Address, FnsParticipantId
буду автоматически заполнены данными указанного BoxID ящика в Диадоке.
