### ISSUE TITLE
Пожелание. Автоматическое определения подразделения контрагента

### ISSUE THREAD

**Issue by SlashSep** [diadoc/diadocsdk-1c-docs#880]
Добрый день!
Есть ситуации, когда у контрагента создано множество внутренних подразделений. При отправки формализованного документа все хорошо, документ падает на нужное подразделения. Я предполагаю, что определение подразделения происходит по КПП которое мы указываем в OrganizationDetails. Но если мы отправляем неформализованный документ, то он уходит на главное подразделение. Мы можем конечно явно указать ToDepartmentId в PackageSendTask2, но для этого нам надо будет сначала подучить список всех подразделений контрагента, определить нужное по КПП и подставить в ToDepartmentId.
Почему бы не упростить эту схему. Например, можно добавить КПП в PackageSendTask2 или в метаданные для документа и по нему автоматически определять подразделение контрагента.

С уважением, Алексей.

**Comment by DmitryModin** [comment]
Добрый день, Алексей!
Ваше пожелание было зафиксировано. Спасибо за подробно описанный пример!
