### ISSUE TITLE
Ошибка в адресе контрагента при попытке отправить документ PackageSendTask2.Send

### ISSUE THREAD

**Issue by AllianceAvia** [diadoc/diadocsdk-1c-docs#881]
Добрый день!

Точно такая же проблема, как здесь https://github.com/diadoc/diadocsdk-1c-docs/issues/854

Используем Com-компоненту x64.
Заполняем BoxId покупателя (т.е. в этом случае адрес покупателя не указываем, адрес берется из Диадок):
          
При попытке отправить комплект документов получаем ошибку в адресе (в регионе):

```
Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalTransferDocumentWithHyphens/Buyers/Buyer/OrganizationReference: Could not recognize Address/RussianAddress/@Region= 
```

Ошибку получаем для ID 2BE199802884b1b11e3b127005056917125, с остальными контрагентами такой ошибки нет. 

PS. Контрагент роуминговый

Спасибо.

**Comment by OsnND** [comment]
Добрый день

Проверьте сейчас

**Comment by AllianceAvia** [comment]
Спасибо, работает
