### ISSUE TITLE
Подписание внутренних документов

### ISSUE THREAD

**Issue by dimok22prog1** [diadoc/diadocsdk-1c-docs#884]
Здравствуйте.
Используем компоненту 5.39.1.865 x64 для произвольных систем (перешли на нее в декабре 2022).
Обнаружили, что перестали подписываться **внутренние** документы.
При вызове `ReplySendTask = Document.CreateReplySendTask2("AcceptDocument")` возникает ошибка:

- Ошибка при вызове метода контекста (CreateReplySendTask2): Произошла исключительная ситуация (Document.CreateReplySendTask): Нет документов, для которых возможно формирование ответного задания выбранного типа

Пример документа:

ИдентификаторДокумента = "d694228c-f5f4-475d-941d-098f80559afa1df83889-fd88-41b4-9282-6f4c8d9f546c".

Данные документа:
![Данные документа](https://user-images.githubusercontent.com/100696615/214509681-aa6b8b58-ce9f-480e-b025-3da624142ef9.png)

**Comment by GilimkhanovDenis** [comment]
Добрый день

Исправлено в [5.40.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.40.0)
