### ISSUE TITLE
Ошибка подписи документов 1С при вызове CreateReplySendTask2

### ISSUE THREAD

**Issue by EugeneMSoul** [diadoc/diadocsdk-1c-docs#887]
Добрый день. 
Возникла ошибка подписания документов в Диадок посредством COM компоненты. Ошибка следующего содержания:
`Ошибка при вызове метода контекста (CreateReplySendTask2): Произошла исключительная ситуация (DocumentBase.CreateReplySendTask2): Нет документов, для которых возможно формирование ответного задания выбранного типа`.
Судя по обращениям такая ошибка обычно устраняется переустановкой компоненты и перезапуском 1С, т.к. компонента кэшируется. 
Но в нашем случае в одной сессии 1С часть документов подписывается, а часть нет.
Вот пример 2х документов, один подписался, другой нет:
[https://diadoc.kontur.ru/c72bf514-0d97-4e57-8548-88903d1c3dcc/Document/Show?letterId=0b3115f5-85e5-4710-9ad3-8d0c3e706584&documentId=a1171d63-a777-4448-9416-15b48542a27c](url)
[https://diadoc.kontur.ru/c72bf514-0d97-4e57-8548-88903d1c3dcc/Document/Show?letterId=e31a87ca-c214-4566-a7aa-8d0ec234a237&documentId=1b203064-09de-4baa-8707-e638f13ff945](url)
В чем может быть проблема?

**Comment by OsnND** [comment]
Добрый день.
Уточните, пожалуйста, версию компоненты которую используете? Правильно понимаю, что переустанавливать её не пробовали, т.к. часть документов подписывается?

**Comment by crashsip** [comment]
Подскажите, решилась проблема как-то?

**Comment by crashsip** [comment]
> Добрый день. Возникла ошибка подписания документов в Диадок посредством COM компоненты. Ошибка следующего содержания: `Ошибка при вызове метода контекста (CreateReplySendTask2): Произошла исключительная ситуация (DocumentBase.CreateReplySendTask2): Нет документов, для которых возможно формирование ответного задания выбранного типа`. Судя по обращениям такая ошибка обычно устраняется переустановкой компоненты и перезапуском 1С, т.к. компонента кэшируется. Но в нашем случае в одной сессии 1С часть документов подписывается, а часть нет. Вот пример 2х документов, один подписался, другой нет: [https://diadoc.kontur.ru/c72bf514-0d97-4e57-8548-88903d1c3dcc/Document/Show?letterId=0b3115f5-85e5-4710-9ad3-8d0c3e706584&documentId=a1171d63-a777-4448-9416-15b48542a27c](url) [https://diadoc.kontur.ru/c72bf514-0d97-4e57-8548-88903d1c3dcc/Document/Show?letterId=e31a87ca-c214-4566-a7aa-8d0ec234a237&documentId=1b203064-09de-4baa-8707-e638f13ff945](url) В чем может быть проблема?

Подскажите, решилась проблема как-то?

**Comment by GilimkhanovDenis** [comment]
У одного из документов новый workflowid. про который старая компонента ничего не знает, поэтому не может создать ответное действие

подписанный документ подписывался компонентой 5.34.4.713
