### ISSUE TITLE
Поддержка метода SendRevocationRequest в новых версиях

### ISSUE THREAD

**Issue by AlekseyNakonechniy** [diadoc/diadocsdk-1c-docs#888]
Добрый день!
В 1С используется dll Диадок, всё хорошо, но перестал работать метод аннулирования "SendRevocationRequest", возвращает исключение с описанием :"##100[Ошибка сервера Диадок]code:400, HTTP error: MessagePatchToPost.RevocationRequests[0]: Version 1.01 of revocation request is not supported by roaming operator 2be. Supported versions: revocation_request_02".
![2](https://user-images.githubusercontent.com/124274597/216348354-89127b6a-4137-465c-bb6d-8ef77eb9ebe5.png)
Судя по историям изменений в версии 5.37.0 от 25 февраля 2022 его удалили. 
![1](https://user-images.githubusercontent.com/124274597/216348383-5c7779b0-ae15-4364-814b-1658f8fb0e83.png)
Подскажите пожалуйста, так ли это, если да какой метод вызывать для аннулирования документов?

**Comment by ylmanchik** [comment]
Добрый день! 
Если вопрос для вас ещё актуален - вы можете использовать ReplySendTask2. Можете узнать больше по ссылке https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_reply_document.html

**Comment by AlekseyNakonechniy** [comment]
Добрый день!
Спасибо за ответ, сделал как в примере, всё заполнил, при попытке вызвать метод Send() у созданного объекта CreateReplySendTask2("RevocationRequest"); Возвращается та же ошибка.

Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: MessagePatchToPost.RevocationRequests[0]: Version 1.01 of revocation request is not supported by roaming operator 2be. Supported versions: revocation_request_02

**Comment by GilimkhanovDenis** [comment]
За последние пару суток такая ошибка была только от компонент верси 5.29.9, 5.34.0 и 5.35.4

Отправка же новой версии запроса появлиась в [5.36.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_36_0.html)

Проверьте, что подключается последняя версия компоненты
