### ISSUE TITLE
Вопросы по идентификатору машиночитаемой доверенности (МЧД)

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#889]
Добрый день.

Данные идентификатора МЧД:

![изображение](https://user-images.githubusercontent.com/33707226/217725043-1c490d98-8274-4b76-902c-695c7a12cfb0.png)

Данные доверителя МЧД:
![изображение](https://user-images.githubusercontent.com/33707226/217725173-0299d8f7-71a7-462a-afbf-152659e1a264.png)

![изображение](https://user-images.githubusercontent.com/33707226/217725213-2291d259-07fa-456f-9ec4-e0e112ce0fd7.png)

![изображение](https://user-images.githubusercontent.com/33707226/217725235-d561c52f-532e-4b88-abe9-1855ec567f74.png)

![изображение](https://user-images.githubusercontent.com/33707226/217725254-bf21567a-d193-4618-afbd-12e48d910b4b.png)

## Вопросы:

1. А почему идентификатор МЧД представлен в виде регистрационного номера МЧД и ИНН доверителя?
Может быть так, что регистрационный номер один и тот же для разных МЧД, но при этом разные ИНН доверителя (т.е. сами доверители)? 
Идентификатор МЧД уникален уже по своему регистрационному номеру? Или только по комбинации "регистрационный номер" + "ИНН доверителя"? Если уникален уже по регистрационному номеру, то зачем в данных идентификатора указан еще и ИНН доверителя?

2. А чем ИНН доверителя из данных идентификатора МЧД отличается от ИНН доверителя в данных доверителя? Зачем это поле (ИНН доверителя) присутствует дважды - один раз в данных идентификатора МЧД и второй - в данных Доверителя?

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

По регистрационному номеру и ИНН доверителя МЧД идентифицируется в блокчейне ФНС. Так же он и в API Диадок прокинут

ИНН доверителя в идентификаторе МЧД не отличается от ИНН доверителя в данных о доверителе. В доверителя ИНН прокинут, чтобы информация о доверителя была собрана в одном месте
