### ISSUE TITLE
Падает клиент 1С при отправке документа.

### ISSUE THREAD

**Issue by ckyrun** [diadoc/diadocsdk-1c-docs#89]
Модуль Диадок был внедрен на самописную конфигурацию и отправляет без проблем СФ и ТОРГ-12. Добавил логику отправки УПД и новую внешнюю компоненту. Для отправки продолжаю использовать: AsyncTask =  SendTask.SendAsync(), рандомно после исполнения указанного метода крашится клиент 1С.
Внешняя компонента: "5.14.1.177"
База клиент-серверная. Конфигурация самописная, обычные формы. Платформа 8.3.9.2170. Клиент 32-битный.

**Comment by geron4** [comment]
Я не разработчик Диадок, но я думаю надо попробовать последнюю версию компоненты "5.16.1.191". Как вариант отказаться от асинхронных методов в пользу синхронных.

**Comment by denver069** [comment]
Возможно проблема в слишком большом количестве параллельно запущенных SendTask.
Попробуйте ограничить их количество до 10.
