### ISSUE TITLE
При выполнении метода GetDocumentsAsync() не происходит завершение выполнения

### ISSUE THREAD

**Issue by AnnaNLeonova** [diadoc/diadocsdk-1c-docs#892]
Здравствуйте, используемм модуль 5.48.01.529 (обычные формы). При выполнении метода GetDocumentsAsync() не происходит завершение выполнения (IsCompleted  Ложь) и происходит зацикливание при получении документов (не всегда, иногда получение происходит корректно).
(Функция ПолучитьМассивДокументов модуля  Модуль_РаботаССерверомДиадок)

**Comment by BlackRaser** [comment]
Добрый день!

Уточните, возникают ли ошибки при выполнении метода GetDocumentsAsync()? Можете уточнить примерную дату и время возникновения проблем с зацикливанием метода, указав часовой пояс

**Comment by AnnaNLeonova** [comment]
Здравствуйте, ошибки не возникает, происходит зависание программы с последующим закрытием, нагрузка процессора под 100%. 
Примерная дата и время: 27.02.2023 в 12:10 Мск

**Comment by GilimkhanovDenis** [comment]
Предлагаю пойти по порядку

1. Какая версия компоненты используется ([DiadocApi.GetFullVersion()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DiadocAPI.html#DiadocAPI.GetFullVersion))?
2. В каком ящике происходит поиск документов ([Box](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html).Guid) ?
3. С какими параметрами происходит поиск документов (поля объекта [SearchDocumentTask](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/SearchDocumentTask.html))?
4. Есть ли при зависании какая-то сетевая активность от компоненты? Есть есть, то хотелось бы получить HTTP лог (расшифрованный) (можно, например, использовать Fiddler или Wireshark - что удобнее, лишь бы траффик был расшифрован). Можно передать его через техподдержку, если опасаетесь за данные в этом логе
5. Если вылетает, то нужен дамп процесса в момент падения (может помочь [ProcDump](https://learn.microsoft.com/en-us/sysinternals/downloads/procdump)или обычно достаточно дампа, созданного средствами 1С)

**Comment by AnnaNLeonova** [comment]
Перешли на новую версию обработки

**Comment by AnnaNLeonova** [comment]
Обращение закрываю
