### ISSUE TITLE
AddDocumentFromFile("ProformaInvoice") создает объект без специфичных для этого типа реквизитов

### ISSUE THREAD

**Issue by EvgenySavotin** [diadoc/diadocsdk-1c-docs#893]
AddDocumentFromFile("ProformaInvoice") стал создавать объект без специфичных для этого типа реквизитов - "DocumentNumber", "DocumentDate" и проч.
Зарегистрировал свежую dll-ку - не помогло.
Ранее все работало корректно.
В чем может быть проблема?
![2023-03-16_15-22-53](https://user-images.githubusercontent.com/128049484/225616576-025ec176-fa10-4688-a3eb-bc412ef6917a.png)

**Comment by GilimkhanovDenis** [comment]
`AddDocumentFromFile("ProformaInvoice")` - это вызов для [PackageSendTask](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DEPRECATED/PackageSendTask.html), а не [PackageSendTask2](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html)

PackageSendTask2 всегда создаёт [CustomDocumentToSend](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/CustomDocumentToSend.html)

Специфичные для типа документа поля заполняются через Metadata, как показано в [примере](https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_post_document.html) для неформализованного документа

**Comment by EvgenySavotin** [comment]
К сожалению, скрин вводит в заблуждение, но создается именно PackageSendTask2, просто переменная называется
PackageSendTask

**Comment by GilimkhanovDenis** [comment]
То, что создаётся PackageSendTask2 видно по вызываемому методу с 4 параметрами. И про него же я и написал, что он создаёт CustomDocumentToSend и нужно заполнять Metadata
