### ISSUE TITLE
получить информацию об операторе ЭДО контрагента

### ISSUE THREAD

**Issue by EkaterinaRed** [diadoc/diadocsdk-1c-docs#894]
можно ли как-то вытащить оператора через которого работаем с контрагентом? Получая контрагента через, например, GetCounteragentById не вижу такого свойства у него

**Comment by JohnSergeev** [comment]
![изображение](https://user-images.githubusercontent.com/33707226/226497224-3b7fc41e-77b0-437a-af2f-91bda9402b1d.png)

**Comment by JohnSergeev** [comment]
Если документ передан через роуминг, то в этих полях будет соответствующая информация.

Справка:
https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/OperatorEdoInfo.html
