### ISSUE TITLE
Отправка документов от подразделения(не головного)

### ISSUE THREAD

**Issue by afila** [diadoc/diadocsdk-1c-docs#895]
Добрый день!
Не получается отправить документы в черновики(`IsDraft=true`) с помощью метода объекта `PackageSendTask2.Send` от **НЕГОЛОВНОГО подразделения** нашей организации. Свойство `FromDepartmentId` перед отправкой заполнено корректным идентификатором подразделения. 
Затем, после того как документ будет "подписан и отправлен" пользователем в вебе,  метод `GetDocuments` возвращает эти же документы с идентификатором **00000000-0000-0000-0000-000000000000** в качестве подразделения отправителя(`FromDepartmentId`).

Как я понимаю, проверить код подразделения у  документов в папке _Черновики_ не получится, т.к. нет [реализации.](https://github.com/diadoc/diadocapi-docs/issues/560)

**Comment by GilimkhanovDenis** [comment]
Добрый день

Черновики в Диадоке не лежат ни в каком подразделении, поэтому указание `FromDepartmentId` при постинге черновика (`IsDraft=true`) не имеет большого смысла

Получитьданные о подразделении черновика можно, например посмотрев на результат создания черновика ([PackageSendTask2.Send()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html#PackageSendTask2.Send)) или запросив его по идентификатору ([Box.GetDocumentById(...)](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.GetDocumentById)) - там Диадок возвращает информацию, что черновик как бы лежит в головном подразделении

Вместо черновика вы можете использовать отложенную отправку (`DelaySend=True; `IsDraft=False``)
