### ISSUE TITLE
Ошибка 409 Recipient allows to receive messages only from counteragents

### ISSUE THREAD

**Issue by EvgeniyAganin** [diadoc/diadocsdk-1c-docs#896]
Добрый день.
Подскажите пожалуйста, установлен модуль Диадока, при отправке документов выдается сообщение "code:409, HTTP error: Recipient allows to receive messages only from counteragents".
С чем это может быть связано?

**Comment by VladdPush** [comment]
Добрый день! Данное сообщение означает, что у получателя установлен запрет на получение документов не от контрагентов. Т.е. контрагент обязательно должен быть у вас в списке "Ваши контрагенты" в Диадок.

**Comment by EvgeniyAganin** [comment]
Спасибо.
