### ISSUE TITLE
DiadocAPI.CreateConnectionByCertificate2(Certificate) возвращает ошибку применения пароля закрытого ключа. 

### ISSUE THREAD

**Issue by Ruslan511** [diadoc/diadocsdk-1c-docs#897]
При вызове метода DiadocAPI.CreateConnectionByCertificate2 возвращается ошибка: 
`##300[Ошибка CryptoPro]Ошибка при расшифровке данных [2148532331:The card cannot be accessed because the wrong PIN was presented.]`
При этом в явном виде пароль закрытого ключа в метод не передается. 
Пример вызова: 

```
	Thumbprint = "******";
	DiadocApi = Новый ComОбъект("Diadoc.Api.InvoiceApi");
	DiadocApi.ApiClientId = "FKP-85d07277-d29c-4dbe-8a04-f6e3725a3617";
	DiadocApi.ServerUrl   = СтрШаблон("https://%1:%2", "diadoc-api.kontur.ru", "443");
	Certificate = DiadocAPI.GetPersonalCertificate(Thumbprint);
	Connection = DiadocAPI.CreateConnectionByCertificate2(Certificate);
```

Что я делаю не так?

**Comment by Ruslan511** [comment]
Нашел метод 	Certificate.SetPin(""), вызов перед CreateConnectionByCertificate2 с данными ключа вроде позволил получить com-объект, но возник вопрос: как работает механизм в части случаев без вызова SetPin? Как в конечном счете верно?

**Comment by GilimkhanovDenis** [comment]
@Ruslan511  `Certificate.SetPin(...)` нужен для того, чтобы задать пароль, который будет использоваться при обращении к закрытому ключу сертификата. Если  пароль на контейнер не установлен или запомнен в СКЗИ, то метод можно не вызывать

**Comment by Ruslan511** [comment]
Сделали так - вроде ничего не сломалось. 
Спасибо!
