### ISSUE TITLE
Ошибка при вызове метода CreateConnectionByLogin

### ISSUE THREAD

**Issue by axchemezov** [diadoc/diadocsdk-1c-docs#898]
Здравствуйте. При вызове метода CreateConnectionByLogin(лонин, пароль) начала появляться ошибка:

invalid API client id. 

Если заходить по паролю логину через браузер, всё работает, а через компоненту, ошибка. Как можно это исправить?
Версия dll Diadoc_5_36_5_760

**Comment by Solar-Valkyrie** [comment]
Добрый день. 

Ошибка ссылается на ключ API, который используется. Пожалуйста, предоставьте ключ API и полный запрос.

**Comment by GilimkhanovDenis** [comment]
@axchemezov  Скорее всего, в своей интеграции используете ключ API ([DiadocApi](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DiadocAPI.html).ApiClientId), который используется в одном из наших типовых решений для 1С - эти ключ мы периодически отзываем.
Интегратор необходимо использовать собственные ключи. Получить их можно обратившись к менеджеру или [оставив заявку](https://www.diadoc.ru/integrations/api#order-form-integration)
