### ISSUE TITLE
Получение списка входящих шаблонов

### ISSUE THREAD

**Issue by MaximGlazunov** [diadoc/diadocsdk-1c-docs#899]
Добрый день.

Работаем с диадок через COM-компоненту, версия COM x64 5.39.0.861.
Подскажите, пожалуйста, как можно получить список входящих шаблонов?
Методы GetDocumentsTask() и GetDocumentEventList() возвращают только документы, шаблонов среди них нет.
Спасибо.

**Comment by GilimkhanovDenis** [comment]
@MaximGlazunov Добрый день

В компоненте есть только метод получения шаблона по его идентификатору. Получить его можно при отправке шаблона.

Сценарий получения списка входящих шаблонов не реализован. Если функциональность необходима, можете обратиться к своему менеджеру с запросом о доработках продукта.

Задача в бэклоге есть, но не в ближайших планах
