### ISSUE TITLE
Возникла проблема с сериализатором Json на платформе 1с 8.2.

### ISSUE THREAD

**Issue by bastra** [diadoc/diadocsdk-1c-docs#9]
Возникла проблема с сериализатором Json на платформе 1с 8.2.
[Ответ в xml.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/369063/xml.txt)
[Пример запроса.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/369064/default.txt)

Сформированный файл отправляем в сервис и получаем в ответ xml с поплывшей кодировкой.

Файл запрос и ответ во вложении.

**Comment by EKorenovsky** [comment]
Добрый день. Аналогичная проблема. Платформа 8.3.8, для формирвоания JSON используется ЗаписьJSON. Файл со структурой и файл с результатом в аттаче. 
[Запрос.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/371062/default.txt)
[Ответ.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/371063/default.txt)
Спасибо.

**Comment by volodkindv** [comment]
@bastra @EKorenovsky приведите полностью код, отправляющий http-запрос, а также метод API, к которому обращаетесь.
Возможно, вы не сбросили BOM или не установили кодировку в самом POST-запросе.
Мы отправляли примерно так:
`

			Запрос = Новый HTTPЗапрос(ПолныйАдрес);

			Запрос.УстановитьТелоИзСтроки(ТекстФайла,"UTF-8",ИспользованиеByteOrderMark.НеИспользовать);

			Запрос.Заголовки = Заголовки;

			Соединение.ОтправитьДляОбработки(Запрос,ИмяФайлаОтвета);
`

**Comment by EKorenovsky** [comment]
Добрый день.  Ваш пример не помог.
Реализовано так:

`	Результат = "";
	HTTPСоединение = Новый HTTPСоединение("diadoc-api.kontur.ru",,,,,Истина);
	HTTP_Заголовок = Новый Соответствие;
	HTTP_Заголовок.Вставить("host","diadoc-api.kontur.ru");
	HTTP_Заголовок.Вставить("Connection","Keep-Alive");
	HTTP_Заголовок.Вставить("Content-Type","application/json charset=UTF-8");
	HTTP_Заголовок.Вставить("Accept","application/json");
	ЗаголовокДляАвторизации = "DiadocAuth ddauth_api_client_id="+TokenApi+" ddauth_token="+TokenSession;
	HTTP_Заголовок.Вставить("Authorization",ЗаголовокДляАвторизации);
	ИмяФайла = Директория + "123.txt";
	ИмяРесурса = "GenerateInvoiceXml?invoiceType=Invoice";
	HTTPЗапрос = Новый HTTPЗапрос(ИмяРесурса, HTTP_Заголовок);
	HTTPЗапрос.УстановитьТелоИзСтроки(ФайлJSON,"UTF-8",ИспользованиеByteOrderMark.НеИспользовать);
	СтруктураОтвета = Новый Структура("Код,Результат",-1,"");
	
	Попытка
		HTTPОтвет = HTTPСоединение.ОтправитьДляОбработки(HTTPЗапрос);
		Результат = HTTPОтвет.ПолучитьТелоКакСтроку();
		
		СтруктураОтвета.Вставить("Код",HTTPОтвет.КодСостояния);
		СтруктураОтвета.Вставить("Результат",Результат);
	Исключение
		ИнфОшибка= ИнформацияОбОшибке();		
	КонецПопытки;
	Возврат СтруктураОтвета;	`

**Comment by volodkindv** [comment]
@EKorenovsky Добрый день!
По приведенному коду непонятно, что находится в переменной ФайлJSON. 

` HTTPЗапрос.УстановитьТелоИзСтроки(ФайлJSON,"UTF-8", ИспользованиеByteOrderMark.НеИспользовать);`
   
Попробуйте поменять на 

`HTTPЗапрос.УстановитьИмяФайлаТела(ИмяФайла);`

Тестировал на 8.3.7.2027 с файлом, предоставленным вами. Результат на скриншоте:
![image](https://cloud.githubusercontent.com/assets/12305552/16980795/2f52a83c-4e81-11e6-8083-c8618294d7a2.png)

**Comment by EKorenovsky** [comment]
Добрый день. Эта ошибка на платформе 8.2.19. Стоит задача создания обмена с целью охватить наибольшее количество используемых платформ от 1с, желательно без использования ВК: от 7.7 до 8.3. С платформой 8.3 проблем нет.
Если не получится без ВК, у вас есть на сайте информация по необходимым ВК и методам, которые используются? Или это надо поднимать на основании кода ваших обработок?

**Comment by denver069** [comment]
http://1c-docs.diadoc.ru

**Comment by Macvey** [comment]
@EKorenovsky  Добрый день!   
Попробуйте результат сразу сохранять в файле. Вместо: 
HTTPОтвет = HTTPСоединение.ОтправитьДляОбработки(HTTPЗапрос);
Результат = HTTPОтвет.ПолучитьТелоКакСтроку();

Вот это:
HTTPОтвет = HTTPСоединение.ОтправитьДляОбработки(HTTPЗапрос,ИмяФайла );
			ТД=Новый ТекстовыйДокумент;
			ТД.Прочитать(ИмяФайла,КодировкаТекста.UTF8);
			Результат=ТД.ПолучитьТекст();

**Comment by EKorenovsky** [comment]
Всем огромное спасибо. Будем пытаться победить.

**Comment by Macvey** [comment]
@EKorenovsky В принципе работали напрямую с API и на 7 и на УФ. Для запросов использовали Microsoft.XMLHTTP. Ответ получали методом responseBody. Для расшифровки токена пришлось код завернуть в vbscript. Т.е. в теории возможность отказаться от компоненты есть. И от CAPICOMa тоже. Может здесь найдете что-то полезное для себя: http://wiki.kint.ru/index.php/Использование_средств_шифрования_.Net_из_1С

**Comment by EKorenovsky** [comment]
За ссылку на kint.ru - огромное спасибо!
