### ISSUE TITLE
Ошибка при отправлении "Счет фактуры"

### ISSUE THREAD

**Issue by Alex463** [diadoc/diadocsdk-1c-docs#90]
Добрый день! Версия компоненты: 5.16.1.191 
Помогите пожалуйста решить следующую проблему:
Заполняю СФ по документу основания "ОтчетКомиссионера". 
Создаю SendTask, SendTask = Organization.CreateSendTask("InvoiceContent"); 
заполняю его. 
Результат после заполнения: 
![screenshot_17](https://cloud.githubusercontent.com/assets/24681242/24968778/0b129682-1fb7-11e7-9e44-0d73f6e13880.jpg)

далее пытаюсь его отправить: SendTask.Send() 
выдает ошибку: Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (SendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: InvoiceInfo.InvoiceRevisionDate is required

но у меня не исправление СФ, перерыл документацию, но не нашел как задать этому док-ку тип "Invoice". Такое впечатление, что СФ создается с типом "InvoiceRevision", а мне необходимо отправлять именно СФ с типом "Invoice". Как это сделать? или скажите, что я неправильно заполняю?

**Comment by denver069** [comment]
Данная ошибка может возникать только если в поле SendTask.Content.InvoiceRevisionNumber записать какое либо значение а поле SendTask.Content.InvoiceRevisionDate оставить пустым.
Дело в том что при отправке счета-фактуры отдельного типа InvoiceRevision не существует, API Диадока определяет наличие исправления по полю SendTask.Content.InvoiceRevisionNumber, если оно заполнено то к поле SendTask.Content.InvoiceRevisionDate становится обязательным.
Воспроизвести ошибку с данными как на скриншоте (с пустыми полями InvoiceRevisionNumber и InvoiceRevisionDate) не удалось.

**Comment by denver069** [comment]
Проверьте еще раз отправляемый контент и если SendTask.Content.InvoiceRevisionNumber и SendTask.Content.InvoiceRevisionDate пустые, попробуйте переустановить внешнюю компоненту.

**Comment by Alex463** [comment]
denver069, спасибо, сейчас попробую

**Comment by Alex463** [comment]
denver069, убрал присвоение пустых значений полям SendTask.Content.InvoiceRevisionNumber и SendTask.Content.InvoiceRevisionDate (т.е. было SendTask.Content.InvoiceRevisionNumber = "", SendTask.Content.InvoiceRevisionDate = Дата('00010101'), затем комментировал)  - все заработало.
