### ISSUE TITLE
Подписание документа готовым sig-файлом

### ISSUE THREAD

**Issue by irina48l** [diadoc/diadocsdk-1c-docs#900]
Добрый день. 
Возможно ли реализовать такой кейс:
В 1с используются API-методы для работы с Диадок, вся логика реализована на стороне сервера. 
На клиенте формируется sig-файл подписи для документа, и уже готовый файл передается на сервер. И, соответственно, подписание документа уже в Диадоке происходит готовым sig-файлом без доступа непосредственно к сертификату (в личном кабинете сертификат добавлен).
Если это возможно, то каким методом можно реализовать такое подписание?
(Сейчас используется на клиенте авторизация по сертификату -> CreateReplySendTask2 )
Спасибо!

**Comment by GilimkhanovDenis** [comment]
Добрый день

такой функциональности в компоненте нет. Файлы подписи генерируются самой компонентой с использованием сертификата, по которому произошла авторизация

**Comment by irina48l** [comment]
Понятно, спасибо, Денис. А если использовать http api, там можно такое реализовать? или это надо в другой ветке спросить?
