### ISSUE TITLE
Ошибка при подписании УПД (CreateReplySendTask2)

### ISSUE THREAD

**Issue by crashsip** [diadoc/diadocsdk-1c-docs#902]
При подписании входящих УПД получаем с некоторого времени ошибку:
Произошла исключительная ситуация (DocumentBase.CreateReplySendTask2): Нет документов, для которых возможно формирование ответного задания выбранного типа.

Другие входящие и исходящие документы подписываются без проблем.

Компонента подключается так: 
		
`ЗагрузитьВнешнююКомпоненту(ИмяФайла);`
`DiadocApi_ = Новый("AddIn.DiadocInvoiceAPI");`
`DiadocApi  = DiadocApi_.CreateObject();`

Соединение устанавливается по сертификату.

Версия платформы 1С:Предприятие 8.3 (8.3.21.1644)
Конфигурация Бухгалтерия Предприятия 3.0 (блок ЭДО самописный).
Версии библиотеки: Diadoc_5_37_4_831_x64.dll - на ней появилась ошибка.
Обновил до: Diadoc_5_41_0_871_x64.dll - ошибка так же появляется на УПД.

Просьба подсказать решение проблемы.

**Comment by crashsip** [comment]
> Добрый день!
> 
> Уточните, с какими документами возникла проблема? Приложите ссылки на проблемные документы

УПД для примера (на данный момент ожидают подписи, пока не подписываем)

https://diadoc.kontur.ru/5d3b1c37-1d46-4056-978b-0c192ab7a860/Document/Show?letterId=5002e686-0920-49d8-943f-3266061645dd&documentId=cc3c6d01-ccb5-41ea-9409-d599c9fecdd5 

https://diadoc.kontur.ru/5d3b1c37-1d46-4056-978b-0c192ab7a860/Document/Show?letterId=e59c8194-2964-4989-920a-16c00d350661&documentId=d1f02b96-0c51-4b9b-af20-3390b32ea8e2

**Comment by GilimkhanovDenis** [comment]
Добрый день

Поведение не воспроизводится. Убедитесь, что у вас действительно подключается обновлённая версия компоненты, а не закэшированная 1С

**Comment by crashsip** [comment]
> Добрый день
> 
> Поведение не воспроизводится. Убедитесь, что у вас действительно подключается обновлённая версия компоненты, а не закэшированная 1С

Обновил компоненту до версии 5.42.4 
Появилась другая ошибка

"Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
Line: 2, Position: 38, /UniversalTransferDocumentBuyerTitle[1]/@DocumentCreator: The 'DocumentCreator' attribute is invalid - The value '' is invalid according to its datatype 'string1000' - The actual length is less than the MinLength value.
Line: 2, Position: 2, /UniversalTransferDocumentBuyerTitle[1]: The element 'UniversalTransferDocumentBuyerTitle' has incomplete content. List of possible elements expected: 'Signers'.
/UniversalTransferDocumentBuyerTitle: One of the fields must be present: @OperationContent, ContentOperCode"

Тут уже вроде понятнее, похоже у нас в коде недоработка. Будем разбираться. Этот топик, полагаю, можно закрыть.

**Comment by GilimkhanovDenis** [comment]
@crashsip Если разобраться не получится, то нужен код как заполняете контент второго титула УПД - через динамические контент, через загрузку из файла или через загрузку из Base64
+ ссылка на этот УПД.
