### ISSUE TITLE
Произошла исключительная ситуация (DiadocCom.CreateConnectionByLogin): WIN32[0x00002EE2]WinHttpSendRequest

### ISSUE THREAD

**Issue by KonstantinBIA** [diadoc/diadocsdk-1c-docs#903]
Добрый день, появляется следующая ошибка - Произошла исключительная ситуация (DiadocCom.CreateConnectionByLogin): WIN32[0x00002EE2]WinHttpSendRequest

Версия компоненты 5_41_0_871

**Comment by Solar-Valkyrie** [comment]
Добрый день.

Расскажите, пожалуйста, подробнее. 
Приложите, пожалуйста, полный текст ответа от сервера. И какой вы используете запрос, пришлите его текст.

**Comment by GilimkhanovDenis** [comment]
@KonstantinBIA WinHttp 0x2ee2 - это таймаут соединения. Рекомендуем повторить запроси, если ошибка повторяется, то проверить параметры подключения к серверу Диадок и стабильность соединения
