### ISSUE TITLE
Box.GetDocumentEventList([AfterEventId]) перестала возвращать события, связанные с исходящими документами

### ISSUE THREAD

**Issue by NickVStepin** [diadoc/diadocsdk-1c-docs#905]
Идентификатор ЭДО 2BM-7707609512-2012052808144049502630000000000.

Последнее полученное событие 04db7872-87c0-4848-bf19-e6e98c03cf64 от 29.03.2023 13:16:42 (когда все работало).
С тех пор вызов Box.GetDocumentEventList("04db7872-87c0-4848-bf19-e6e98c03cf64") всегда возвращает COM-объект с 23 событиями, и все эти события связаны только со входящими документами.
Хотя только за апрель месяц, если сделать отбор по вэбморде на наши исходящие документы произошло более 144 событий.

Версии библиотек 5.41.0.871 (64 бит)

**Comment by Solar-Valkyrie** [comment]
Добрый день. 

После получения одной "пачки" событий нужно продолжить запрашивать ленту событий.
