### ISSUE TITLE
ПОЖЕЛАНИЕ: Добавление информации об источнике получения сертификата для метода GetPersonalCertificates()

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#908]
Добрый день.

**Общая информация для упрощения «разбора полётов»:**
Организация:		«ДНС Ритейл»
ИНН:			2540167061
КПП:			254301001
КПП2:			783450001
ID организации:	c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru		
ID участника ЭДО:	2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.39.1.865**.

В преддверии 1 сентября (начало полноценной обязательной работы с МЧД) хотелось бы иметь возможность реализовать для пользователей ограничение на работу с копиями сертификатов в реестре компьютера. Т.е., например, сделать так, чтобы пользователь на своем рабочем месте при подключении к ЭДО не мог воспользоваться сертификатами, скопированными в реестр. И ему бы пришлось использовать свою подпись со своей флешки или токена.

Сейчас нет никакой возможности понять какие из сертификатов, возвращаемых **GetPersonalCertificates()** откуда получены.

Для того, чтобы это можно было понять, было бы здорово, если бы в объекты **CertificateInfo**, возвращаемые методом **GetPersonalCertificates()**, было бы добавлено поле "Откуда получен сертификат" со значениями вида:
а) Из реестра; 
б) С внешнего носителя; 
в) С дополнительного жесткого диска (не диска С).

Наличие такой дополнительной информации было бы очень полезным. 

Просьба:
Если это возможно, добавьте, пожалуйста, данную информацию о месте, из которого получен сертификат, в объекты типа **CertificateInfo**.

Спасибо.

**Comment by NickZubashevskiy** [comment]
Задача была добавлена в бэклог, если данная функциональность необходима в ближайшее время - просьба обратиться к менеджеру, ведущему вашу организацию
