### ISSUE TITLE
ПРОБЛЕМА с получением данных по МЧД некоторых документов (ОШИБКА в АПИ?)

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#909]
Добрый день.

**Общая информация для упрощения «разбора полётов»:**
Организация:		«ДНС Ритейл»
ИНН:			2540167061
КПП:			254301001
КПП2:			783450001
ID организации:	c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru		
ID участника ЭДО:	2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.42.0.873**.

При обработке документов некоторых контрагентов в последние дни стали сталкиваться со странной ошибкой - согласно статусам документа по нему есть состояние проверки МЧД, но при попытке получить данные по этим МЧД с помощью метода GetPowersOfAttorney() происходит ошибка.

**Пример исходящего документа:**
PathURL = /c4390c58-315b-4323-a9b4-b5d87d6e868b/Document/Show?letterId=1081cfcc-0a29-465c-83e2-1ff954735e6b&documentId=033a5dcd-9d19-432b-862f-591d916358e6

От нас документ подписан без использования МЧД.

Контрагент в роуминге:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/dec3ff81-833a-431c-80a9-7505582126c7)

По документу есть сводный статус МЧД без ошибок:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/3e4b4108-510c-4ad9-9b00-a637a9e795fd)

Мы для таких документов пытаемся с помощью GetPowersOfAttorney() получить информацию по доверенностям в документе и получаем в ответ ошибку:

_Произошла исключительная ситуация (DocumentBase.GetPowersOfAttorney): ##100[Ошибка сервера Диадок]code:404, HTTP error: Power of attorney not found"_

Если открыть документ на сайте, то данные по доверенности видны:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/eb2350d9-73ad-45c6-81e2-5309805749b7)

Правда странно, что нет ссылки перехода на просмотр данных по доверенности на сайте ФНС.

**Пример входящего документа:**
PathURL = /c4390c58-315b-4323-a9b4-b5d87d6e868b/Document/Show?letterId=24a14266-a440-4ca9-a1fa-8014e845adf6&documentId=b02f168b-5b94-4b1d-a5ed-1942f20da9b1

Контрагент в роуминге:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/dd61c189-7a3f-44b2-a46d-d07d382db8b7)

По документу есть сводный статус МЧД без ошибок:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/e0992101-b826-44d0-bc36-1c4175aa5a5d)

Мы для таких документов пытаемся с помощью GetPowersOfAttorney() получить информацию по доверенностям в документе и получаем в ответ такую же ошибку:

_Произошла исключительная ситуация (DocumentBase.GetPowersOfAttorney): ##100[Ошибка сервера Диадок]code:404, HTTP error: Power of attorney not found"_

Если открыть документ на сайте, то данные по доверенности видны:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/98c6dd94-b75c-4cb5-b7d5-28064e584ce6)

Т.е. и для входящих, и для исходящих документов проблема одинакова.

## Дополнительно:
Самое странное, что у нас есть документы по которым сперва данных по МЧД не было - и у нас документы обновлялись. А затем (похоже!) откуда-то эти данные по МЧД появились - и начали сыпаться такие ошибки. 
Это (очень ориентировочно!) начало происходить 10.05.2023 после 16 часов по Владивостоку (9 МСК).
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/b4faa7c5-adf0-45ee-9e78-178ad603ecb3)

Вообще, такое ощущение, что это как-то пересекается с информацией от вас о том, что вы начали работать с МЧД в роуминге!
Может быть как раз после этого всплыла какая-то недоработка в АПИ, которая не позволяет получить данные по МЧД, хотя сайт эти данные обрабатывает нормально?

## Вопросы:
1. А почему вообще появляется такая ошибка и как в принципе может быть, что статус доверенности в документе есть, а данных по самой доверенности получить нельзя? **Это, случайно, не какая-то ошибка в АПИ?**
2. Если это не ошибка в АПИ, то почему на сейте данные по МЧД видны, а АПИ их не возвращает?
3. Если это не ошибка в АПИ, то что это вообще означает? Сводное состояние по МЧД есть, а данных по самим МЧД нет - это значить, что ...? Что?
4. Если это не ошибка в АПИ, то как правильно обрабатывать такие документы? Считать, что с ними все хорошо и принимать их к учету? Или считать, что всё плохо, аннулировать их и добиваться документов без таких ошибок?

Очень ждем ваши разъяснения по данной проблеме и исправления в компоненте, если это действительно какая-то ошибка.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

В версии [5.46.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_46_0.html) сделано так, что вызов метода не будет завершаться ошибкой. В информации об МЧД, по которым эта ошибка возникала вернётся только идентификатор доверенности

**Comment by GilimkhanovDenis** [comment]
Ошибка возникает на МЧД, пришедших из роуминга и не зарегистрированных в Контур.Доверенности. Да данный момент нет информации когда поведение изменится
