### ISSUE TITLE
Com компонента

### ISSUE THREAD

**Issue by 7923655** [diadoc/diadocsdk-1c-docs#91]
COM-компонента для встраивания в произвольные системы, для 64-х битных приложений - 5.16.1.191  http://diadocsdk-1c.readthedocs.io/ru/latest/Downloads.html
Компонента поддерживает параллельное использование или она однопоточна?

**Comment by denver069** [comment]
Компонента однопоточная.

**Comment by 7923655** [comment]
Напишите тогда это в описании компоненты.
