### ISSUE TITLE
ВНИМАНИЕ!!! БОЛЬШАЯ ПРОБЛЕМА в работе компонент версий, начиная с 5.40.0.869 и выше

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#910]
Добрый день.

**Общая информация для упрощения «разбора полётов»:**

Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
КПП2: 783450001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.39.1.865**.

# Введение
До недавнего времени мы работали на версии компоненты **5.39.1.865**. 
С ней всё работает стабильно и без ошибок. Хотя и постепенно (но очень медленно) происходит постепенное «выедание» памяти на сервере. О чем я оставлял ранее информацию в топике https://github.com/diadoc/diadocsdk-1c-docs/issues/885

Отреагировав на ваше обновление в версии 5.41.0.871, затрагивающее обработку новых ИОП:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/0a306e08-47fc-4f6b-abf8-c6916995c288)

мы попробовали перейти на более новые версии компоненты. В частности – на последнюю доступную версию **5.42.0.873**.

# И столкнулись с очень, очень серьезными проблемами!

Пытаясь разобраться с этими проблемами, мы, непосредственно на рабочем сервере ЭДО в настоящем «боевом» применении, в течение 2-х дней проверяли работу следующих версий компоненты (**x64 COM**):

- 5.39.1.865
- 5.40.0.869
- 5.40.1.870
- 5.41.0.871
- 5.42.0.873

И пришли к следующим выводам:
1.	Версия компоненты 5.39.1.865 работает без проблем.

2.	Проблемы воспроизводятся со 100% вероятностью во всех версиях компоненты, старше версии 5.39.1.865. Т.е. замеченные проблемы возникают при работе с версиями: 5.40.0.869, 5.40.1.870, 5.41.0.871, 5.42.0.873.

3.	Скорее всего проблемы носят постоянный характер. Но они практически незаметны при, условно,  локальной однопользовательской работе с компонентой, когда нет какой-то большой нагрузки. Однако, проблемы становятся хорошо видны при использовании компоненты на сервере при многопоточной работе с ЭДО.

# Замеченные проблемы

### Проблема №2. Полное прекращение выполнения работы фоновых ЭДО на сервере (зависание фоновых)

С самого начала перехода на версии компоненты старше 5.39.1.865 стало заметно, что rphost стал потреблять значительно больше ресурсов процессора, чем в версии 5.39.1.865.

Это было бы полбеды. Но! Вся проблема в том, что со 100% воспроизводимостью у нас с новыми версиями компоненты на сервере происходит примерно следующее:

1.	Сперва со старта (например, после перезапуска сервера, служб 1С или снятия задачи rphost через диспетчер задач) после старта rphost заново, видно, что потребление ресурсов процессора большое и какое-то «рваное» – происходят частые скачки до 100% загрузки. Большое – в смысле, что явно больше, чем на версии 5.39.1.865.

2.	Затем через какое-то время загрузка процессора (всех ядер) повышается до 100%. При этом по логам операций ЭДО мы видим, что они еще выполняются, но спустя еще какое-то время по этим же логам выполнения операций в ЭДО мы видим, что никакого выполнения операций ЭДО уже не происходит, фоновые на самом деле уже ничего не делают и всё где-то зависло. При этом 100% загрузка процессора остается.

4.	Дополнительно замечено, что вот эти два «пункта» – 100% потребление ресурсов процессора и окончательное зависание, и прекращение выполнения операций ЭДО фоновыми 1С – происходят совершенно непонятно в смысле того, когда именно (с какой дельтой по времени) это произойдет. 

После очередного рестарта сервера, служб 1С или завершения работы rphost через диспетчер задач, повышение загрузки процессоров до 100% у нас происходило и примерно через 2-3 минуты после рестарта, и только через примерно 40 с лишним минут после рестарта. И окончательное зависание фоновых заданий после этого также было когда как – то всё зависало практически сразу после появления 100% загрузки процессора, то еще какое-то время после этого часть фоновых ЭДО работала еще приблизительно 5-15 минут перед тем, как окончательно зависнуть и перестать писать логи.

5.	Так же мы заметили, что при работе на новых версиях компоненты, более новых, чем 5.39.1.865, некоторые из выполняемых нами в ЭДО действий стали падать в процессе выполнения. В частности, это касается тяжелых операций, типа обновления данных справочников контрагентов ЭДО, когда мы по своим организациям получаем данные всех наших контрагентов и обновляем информацию по ним в нашей учетной системе. Но на фоне всего остального это уже мелочи.

Сервер ЭДО у нас – это отдельный сервер в кластере серверов 1С нашей учетной системы. Отведенный только для выполнения фоновых заданий ЭДО. Ничего более на нем не выполняется. Сервер виртуальный. Изначально мы заметили проблему и «проводили опыты» на варианте сервера с 4 ядрами. Далее мы увеличили число ядер до 8 штук. Но это никак не помогло. При возникающей 100% загрузке полностью загружались и 4 ядра в «старом» варианте сервера, и 8 ядер в «новом» варианте конфигурации сервера. И окончательные зависания фоновых заданий происходили в обеих вариантах конфигурации сервера.
Сейчас, после увеличения числа ядер до 8 (4 двухъядерных процессора), сервер «выглядит» так:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/cdaddc0d-2569-4457-8c0e-7207ab131b04)

При тестировании, переключение на использование компоненты 5.39.1.865, после «экспериментов» с версиями 5.40.0.869 и выше, всегда приводило к работе без проблем. Не было никаких зависаний фоновых и повышенной нагрузки на процессор. А также спокойно выполнялись тяжелые операции в ЭДО, которые падали на новых версиях компонент. Повторное переключение на версии 5.40.0.869 и выше снова приводило к вышеописанным проблемам. Мы переключали и по-разному «гоняли» все версии компоненты – 5.40.0.869, 5.40.1.870, 5.41.0.871, 5.42.0.873 + 5.39.1.865 в течение двух дней и всегда было одно и то же.

# Замеченная особенность
Дополнительно к вышеописанным проблемам, мы заметили, что начиная с версии компоненты 5.40.0.869 в ней явно как-то по-другому происходит работа с памятью. **Совсем не так, как это происходит в версии 5.39.1.865!**

Версия компоненты 5.39.1.865, как я писал ранее в топике https://github.com/diadoc/diadocsdk-1c-docs/issues/885, работает с памятью «плавно», потихоньку постепенно забирая её себе все больше и больше. 

А версии компонент, начиная с 5.40.0.869 постоянно агрессивно освобождают память через близкие промежутки времени и затем резко наращивают её потребление. Что на графике потребления памяти отображается в виде некой условно-постоянной «пилы».

Эта пила потребления памяти со временем исчезает и переходит в «ровную линию». Похоже, как раз в момент этого перехода (при 100% загрузке процессора) окончательно зависает выполнение фоновых заданий.

Мы предполагаем, что вы как-то пытались решить проблемы, указанные в топике https://github.com/diadoc/diadocsdk-1c-docs/issues/885. И, возможно, как раз с этими изменениями и связаны все возникающие проблемы.

Мы допускаем, что повышенное потребление ресурсов процессора может быть связано с постоянной работой по освобождению и последующему выделению памяти при работе компоненты. Что в ситуации многопоточной нагрузки становиться заметным. И в итоге и приводит к окончательному зависанию.

# Дополнительные моменты

Также нам очень странным показалось следующее:
Ранее мы уже замечали проблему в работе метода Box.GetEmployees(), писали вам об этом, и проблема была исправлена еще в версии 5.39.1.865:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/4076e46e-27dc-4579-8c25-2e8c83e03851)

К нашему удивлению, уже позже было отмечено аналогичное исправление. Будто бы то, что починили ранее, сломали снова. И снова починили:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/294e6e72-b73e-4ae5-b62f-6fd63d4d856d)

Мы не уверены на 100%, но у нас есть подозрение, что вот это заявленное повторное исправление в версии 5.40.1.870 на самом деле не исправлено до конца! 

**И, возможно, оно сейчас то зависает, то нет.** 
И этим, возможно, тоже объясняются и окончательные зависания, и то, что они происходят с различной дельтой по времени после запуска, и то, что у нас, как я писал выше, среди прочего на новых версиях компоненты перестали выполнятся объемные операции по обновлению данных справочников, некоторые из которых как раз и вызывают метод Box.GetEmployees().

Но, повторюсь, по поводу этого у нас какой-то особой уверенности нет, скорее есть эдакое легкое подозрение, что дело может быть и в этом.

Также есть у нас есть подозрение, что проблемы могут быть в этих изменениях:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/022b8804-cf7d-41fb-aabe-5d6380b3c7a9)

Изначально нам вообще казалось, что проблемы с полным зависанием пропадают, если мы полностью отключаем отправку исходящих документов (т.е. 100% загрузка процессора остается, но все фоновые хотя бы работают, а не виснут полностью). В итоге то, что это 100% связано именно с отправкой исходящих документов не подтвердилось, но тоже осталось подозрение, что дело может быть и в этом изменении тоже.

# Примеры поведения компонент

Полная загрузка процессора + окончательное зависание фоновых (на 5.40.0.869 и выше):
На 4-х ядрах:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/1acc00c8-d8cd-42d2-bf84-25e22708cbc4)

На 8-и ядрах:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/8cf3037f-5a01-4e8e-988b-56b124a88d93)

Полная загрузка процессора, но фоновые пока еще работают… и в конце концов зависают (на 5.40.0.869 и выше):
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/598a06d1-ece7-4c7c-a33a-c36cad43c996)

Работа и загрузка памяти и процессора в версии 5.39.1.865. Плавное повышение расхода памяти, загрузка процессора гораздо ниже, чем на 5.40.0.869 и выше:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/038654ae-ec5a-4bbd-81f5-bc7a31910557)
 
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/93674390-3cfd-4471-8d28-b36681a359e4)

Работает версия 5.39.1.865, потребление памяти плавное. Переключаемся на любую версию выше (на графике - 5.42.0.873) – и сразу пошла пила в потреблении памяти. Хорошо виден момент перехода с плавного потребления памяти на пилу в новой версии:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/a282b1d1-fa26-4626-8739-5a8b6788d55c)

![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/799f30ad-e133-4e89-8e9f-7f6f3d50c5a6)
 
Спустя некоторое время наступает использование процессора на 100%:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/0aadb6d8-0fb8-4378-afcc-97ce6df3cfa2)
 
И еще через некоторое время – окончательное зависание фоновых и выход «пилы» в ровную линию:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/4bf3f776-9809-48a2-807b-e8b14163dd3d)

# Резюме

Надеемся, что смогли более-менее понятно указать на проблему.

Очень ждем ее исправления, т.к. хотелось бы перейти на использование новых версий компоненты, в которых реализована обработка новых ИОП, которая вступает в силу с 23.05.2023. Т.е. через 5 дней.

Спасибо.

**Comment by JohnSergeev** [comment]
Добрый день.

А какая-то реакция будет?!

Совершенно невозможно работать с компонентами версий начиная с 5.40.0.869 и выше.

**Comment by crashsip** [comment]
> Добрый день.
> 
> А какая-то реакция будет?!
> 
> Совершенно невозможно работать с компонентами версий начиная с 5.40.0.869 и выше.

не хочется расстраивать и флуд разводить, конечно, НО...
у вас большая проблема, с огромным описанием. и если подтвердится - нужно будет разработчикам серьезно поработать. 
у меня топик стартовал 11 апреля. три недели назад запрос на уточнение данных пришел. ответ отправил - и тишина. хотя я полагаю, что запрос мой решаем указанием направления решения проблемы, указанием на некорректную настройку (которую мы найти не смогли сами) или что-то в этом духе, без необходимости переписывать компоненту.
Не отрицаю, что косяк скорее всего по нашей проблеме с моей стороны! НО! хотелось бы более активной работы техподдержки, чтоли. Ткнули бы в косяк, помогли решить проблему.
Интересно, сколько будет решаться Ваша проблема.
ожидал лучшего сервиса от компании такого уровня. 
в противовес - Тензор. Техподдержка на наш запрос отреагировала оперативно, едва ли не мгновенно, нашли с ними вместе баг, который они со своей стороны поправили оперативно. Из техподдержки звонят чаще, чем мы у себя успеваем проверить. 
Грусть, печаль, разочарование....

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev 
Добрый день!

Можете предоставить minidump процесса в момент зависания?

**Comment by JohnSergeev** [comment]
Добрый.

Ну, технически, наверное, сможем снять. Но это потребует времени, т.к. нужно будет в прод. накатить "плохую новую" версию и ловить зависания. А они когда как вылазят. На тестировании как-то было, что и 40 минут работало, работало, но потом всё равно сдохло. Но попробуем, конечно.

А можете более детально расписать, что и как отловить надо, чтобы мы че-нить не то не сделали.

Постараемся сделать во вторник или в среду (как ситуация позволит).

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev 
Дамп можно создать через диспетчер задач по ПКМ
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/9ecd67bd-b5c2-455f-9974-07b156a2e389)

**Comment by SergeyNShestakov** [comment]
У нас проблема с теми же версиями. Последняя рабочая версия с которой можно работать 5.39.1.865. С более поздними наблюдается проблема с памятью. Разработка ведется на Delphi 11, раннее связывание через импортируемую библиотеку типов. При вызове Box.GetCounteragentListByInnList(const innList: WideString) (innList содержит порядка трех с половиной тысяч ИНН) во время ожидания ответа (цикл с вызовом системного Sleep) приложение валится с Access violation в момент вызова Sleep где-то в глубинах kernel. Проблема наблюдается как в x86 так и в x64.

**Comment by GilimkhanovDenis** [comment]
@SergeyNShestakov  я так понял, у Вас происходит APPCRASH - нужен дамп с моментом ошибки

**Comment by SergeyNShestakov** [comment]
https://disk.yandex.ru/d/CbQ0JQBLcSCZMw
Из-под отладчика. Если приложение просто запускать, то вылетает мяу не успев сказать.

**Comment by JohnSergeev** [comment]
Добрый день.

Провели дополнительное исследование замеченных проблем, плюс поснимали дампы памяти.

В итоге ситуация оказалась с одной стороны еще более удручающей, а с другой – похоже, что мы смогли более-менее локализовать место возникновения ошибки.

Все проверки и снятие дампов происходили на версии компоненты 5.42.0.873.

Нормальная рабочая версия с которой переходили на тестируемую версию 5.42.0.873 – это версия 5.39.1.865.

# Часть 1. Снятие первого дампа

Начали проверку:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/18664335-7fb5-4b7f-a7fc-00ec30839fb8)

После переключения на работу с версией 5.42.0.873 в 15:40 проходит ~5 минут и все виснет:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/3170d331-fbd5-448c-92ba-342c2d49b360)
 
Мы снимаем первый дамп. Файл - rphost_1.7z (https://disk.yandex.ru/d/TVOX7hvCQp5Vww).

**Тут возникает странный момент, из-за которого мы не уверены на 100%, что снятые дампы корректны!**

У нас сервер ЭДО крутится в кластере серверов и почему-то происходило так, что при снятии дампа само это снятие рапортовало, что все сделано без ошибок, но при этом rphost, дамп которого снимали, убивался и кластер перезапускал новый экземпляр rphost. Поэтому не очень понятно, что в итоге было снято и полностью ли.

![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/b8454637-2f5d-4433-a942-f3975a4574d0)

Т.к. зависший и жравший память rphost был убит при снятии дампа и запущен другой, то нагрузка на процессор временно спала, а фоновые отвисли.

# Часть 2. Замеченная особенности и снятие второго дампа

После перезапуска rphost смогли заметить и зафиксировать еще один вариант «нехорошего» поведения новой компоненты. Оказалось, что бывает так, что иногда происходит постоянная загрузка не всех ядер, а только их части. А в остальном поведение такое же – постоянное повышенное потребление ресурсов процессора с последующим прекращением «пилы» по памяти.

![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/37672539-db78-4edc-a262-79793a92f197)
 
В этот момент мы сняли второй дамп. Файл - rphost_2.7z (https://disk.yandex.ru/d/OMgfZKF4oatiuA).

# Часть 3. Проблемы еще хуже, чем мы думали ранее

Далее мы еще проверяли поведение компонент АПИ и в итоге обратили внимание вот на какой момент – ранее, при первоначальном тестировании (в прошлый раз), нам КАЗАЛОСЬ, что даже, когда все еще не зависло наглухо и фоновые работают и пишут логи, то всё происходит как-то замедленно, не так, как обычно. Типа: _«Ну, вроде работает, но чё-то, такое, прям сильное ощущение, что всё жёстко тормозит»_.

Сегодня мы обратили специальное внимание на это. **И оказалось, что нам НЕ КАЗАЛОСЬ!**

Действительно, даже когда фоновые еще работают и пишут логи, выполнение действий идет как-то еле-еле. Проверка логов различных потоков операций показало проблему.

Пример «правильного» лога, которые пишутся при работе нормальной компоненты версии 5.39.1.865 (или версия 5.42.0.873, после локализации нами проблемы – на скрине именно она):
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/5412415f-1f12-4209-87cf-83b9f798c279)
 
Тут важно то, что выполнение операции или списка поданных на обработку операций всегда завершается штатным сообщением об окончании обработки (выделено цветом).

При работе версии 5.42.0.873 (без локализации проблемы!) происходит следующее – некоторые операции по логам обрабатываются так же, как указано в скрине лога выше. Но! Подавляющее большинство при выполнении пишет такие логи:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/e8ac5350-ff75-4ffa-8769-a315042a5567)

![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/6b3f9671-d863-474a-b90c-8470880749ee)
  
И на этом всё. **Завершение выполнения не фиксируется в логах!** 

И далее появляются новые файлы логов обработки того же блока операций. Это говорит о том, что выполнение действий в ЭДО начинается, но до конца не доходит. При выполнении происходит какое-то постоянное отключение от ЭДО (или что-то еще такого же плана). И в итоге у нас не происходит фиксации выполнения операций, и мы начинаем всё сначала. Снова и снова. И получается, что вроде бы ничего и не зависло, но наш код из-за этих постоянных «отвалов» при работе с ЭДО не фиксирует успешное выполнение действий и начинает всё заново. А пул невыполненных операций постепенно растет.

Более того, было замечено, что у нас по итогам первого тестирования и по итогам сегодняшнего дня даже проявлялось следующее поведение: 
1.	Мы подключаемся, отправляем исходящий документ
2.	Происходит вот такой «отвал» в работе ЭДО и у нас не фиксируется ошибка
3.	Происходит повторная попытка выполнения отправки исходящего документа
4.	Возвращаемся в п.1

НО! При этом иногда «отвалы» происходят так, что для нас операция до конца так и не выполнилась, но у вас в Диадоке исходящий документ уже сформировался! И у нас по факту из-за этого замечены дубли в исходящих документах. Т.е. из-за таких «отвалов» мы отправляем несколько экземпляров полностью идентичных документов, но никак не можем зафиксировать результаты.

**Т.е. проблема еще больше, т.к. кроме того, что «жрется» процессор и почти всегда происходит его 100% загрузка с полным зависанием выполнения фоновых, оказывается, что даже когда ничего еще не выжралось и вроде как работает нормально – на самом деле ничего нормально всё равно не работает, т.к. постоянно происходят какие-то отвалы в работе с ЭДО (то ли соединение падает, то ли еще чего) и у нас почти ничего в итоге не доходит до конца и не фиксируется, как выполненное.**

На всякий случай в таком режиме мы сняли третий дамп. 
При снятии этого дампа rphost НЕ был убит! Файл - rphost_3.7z (https://disk.yandex.ru/d/oivTYju5c9CKHQ).

# Часть 4. Локализация проблемы

В прошлый раз мы хотели попробовать локализовать проблему путем отказа от выполнения каких-то отдельных операций, но толком не успели. В этот раз мы решили это проверить в обязательном порядке. И при этом обратили внимание на замечание от **SergeyNShestakov** (ранее в переписке) по поводу того, что у него падения происходили при попытках работы с контрагентами. Поэтому первым делом мы попробовали на новой версии компоненты 5.42.0.873 запускать варианты обработки операций в ЭДО, из которых бы была исключена работа с контрагентами.

И, оказалось, что первый же выстрел был точно в цель!

![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/f3746477-5cee-4b23-8fc0-0cd8c20eda7f)
 
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/a91d54f4-5fc8-4ea9-aacc-24a7a0f7b090)
 
Проверка показала, что как только мы запускаем версию фоновых в которых отключено выполнение операций АПИ по работе с контрагентами, то происходит следующее:
1.	Нагрузка на процессор становиться «обычной», т.е. такой же, как и в версии 5.39.1.865
2.	Пропадает «пила» по потреблению памяти.
3.	Все операции, судя по логам, выполняются до конца и без «отвалов» от ЭДО. И поэтому фиксируются штатным образом.

**Иными словами, отключение от выполнения операций с контрагентами полностью приводит поведение компоненты версии 5.42.0.873 к нормальному – аналогичному поведению версии 5.39.1.865.**

В наших фоновых были отключено выполнение методов ЭДО  операции GetCounteragentListByStatusAsync(), а также дальнейшее использование получения подразделений и статусов контрагентов. Мы предполагаем в том, что проблема возникает именно при выполнении GetCounteragentListByStatusAsync() (и, скорее всего, других подобных методов).

Надеемся, что эта информация поможет локализовать проблему.

# Часть 5. Дополнительно

Пока я готовил этот материал, я оставил на сервере в работе полную версию фоновых, которая **работает с контрагентами.** По итогу, когда я закончил и посмотрел, что происходит на сервере, то, как и ожидалось, была повышенная нагрузка на процессор, постоянные «отвалы» выполнения операций в ЭДО и почти полная неработоспособность фоновых. В этот раз загрузка процессора была в «эдаком» третьем варианте – не 100%, а «почти 100%»:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/eb60b63e-1323-4d7a-a9a4-335490ffc2da)

В этот момент я снял четвертый дамп. При снятии этого дампа rphost не был убит! Файл - rphost_4.7z. (https://disk.yandex.ru/d/3-n1e2WU_RNNqg)

# Часть 6. Проверка «в долгую»

На период с 19 часов 25.05.2023 до 9-30 26.05.2023 (по Владивостоку) мы оставили на рабочем сервере работу с проблемной компонентой версии 5.42.0.873, но при этом в наших фоновых отключили все операции по работе с контрагентами. Т.е., по сути, мы на достаточно долгом периоде – более 14 часов – проверили наше предположение, высказанное ранее в части 4 о том, что все проблемы в поведении компоненты связаны с какими-то ошибками в методах работы с контрагентами и методах получения списков контрагентов (наподобие методов GetCounteragentListByStatus() и GetCounteragentListByStatusAsync()).

Результат – всё работало прекрасно, не было никаких проблем с загрузкой процессора, никаких «отвалов» при выполнении операций. В общем поведение компоненты было полностью таким же беспроблемным, как и при работе с версией 5.39.1.865.

На основании этого мы практически на 100% уверены, что какие-то ошибки при обновлении компоненты сделаны в методах работы с контрагентами. И, скорее всего, в методах получения списков контрагентов, типа GetCounteragentListByStatus() и ему подобных.
 
Надеемся, что приведенная информация поможет в исправлении проблемы.

Спасибо.

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev Спасибо за подробный анализ
@SergeyNShestakov спасибо за предоставленный дамп

Исправил поведение в версии [5.42.1](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_42_1.html)
[Страница с последними версиями](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)

**Comment by JohnSergeev** [comment]
Добрый день.
Проверили у себя поведение новой компоненты.
**В течение суток полет нормальный, проблема полностью устранена.**

Спасибо!
