### ISSUE TITLE
Ошибка при отправке УКД

### ISSUE THREAD

**Issue by zmeyqq** [diadoc/diadocsdk-1c-docs#912]
Добрый день
Использую COM-объект (COM x64 5.32.4.635), пытаюсь отправить УКД 
делаю `AddDocument("UniversalCorrectionDocument", "КСЧФДИС", "ucd736_05_01_02")`

При формировании получаю ошибки
```
/UniversalCorrectionDocument/Table/Items/Item/Subtotal/AmountsInc: Function=КСЧФДИС AmountsInc or AmountsDec is required, when ../TaxRate[@OriginalValue != 'НДС исчисляется налоговым агентом']
/UniversalCorrectionDocument/Table/Items/Item/SubtotalWithVatExcluded/AmountsInc: Function=КСЧФДИС AmountsInc or AmountsDec is required
/UniversalCorrectionDocument/Table/Items/Item/SubtotalWithVatExcluded/AmountsDec: Function=КСЧФДИС AmountsInc or AmountsDec is required
/UniversalCorrectionDocument/Table/Items/Item/Vat/AmountsInc: Vat/AmountsInc or Vat/AmountsDec is required, when TaxRate/@OriginalValue != 'НДС исчисляется налоговым агентом'
```

Смотрю в рефлекторе Reflector доступные для `UniversalCorrectionDocument/Table/Items/Item/Subtotal` поля, вижу только `OriginalValue` и `CorrectedValue`
При обращении `Item.Subtotal.AmountsDec` получаю `Method 'AmountsDec' not supported by automation object`
Подскажите, где должны находиться находятся AmountsInc/AmountsDec?

**Comment by VladdPush** [comment]
Добрый день! Попробуйте обновить компоненту до актуальной(5.42, компоненты расположены http://1c-docs.diadoc.ru/ru/latest/Downloads.html )  и перезапустить 1с. Описанная ошибка была исправлена в новых версиях с 5.33.

Если это не изменит ситуацию, пришлите пожалуйста пример полного запроса и убедитесь, что в УКД значения ВсегоУвел или ВсегоУм корректно заполнены.

**Comment by zmeyqq** [comment]
Спасибо, обновление помогло
