### ISSUE TITLE
МЧД - данные о полномочиях

### ISSUE THREAD

**Issue by NickVStepin** [diadoc/diadocsdk-1c-docs#913]
Добрый день, всё ближе час повального применения МЧД.
А в DiadocComApi до сих пор GetPowersOfAttorney() не отдает никаких данных, относительно полномочий, прописанных в МЧД.
Или хотя бы саму xml МЧД возвращал бы.

Бегать из 1с для проверки каждой МЧД в сервис ФНС удовольствие еще то.

Вопрос - когда будут данные о полномочиях или хотя бы сама xml доверенности?

**Comment by GilimkhanovDenis** [comment]
Информация о полномочиях в МЧД добавлена в релизе [5.48.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_48_0.html)

[Скачать](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)
