### ISSUE TITLE
Ошибка при отправке УКД Не обнаружен метод Accept()

### ISSUE THREAD

**Issue by tigr182** [diadoc/diadocsdk-1c-docs#914]
Добрый день, примерно с 1 июня выходит данная ошибка (Не обнаружен метод Accept()), ранее все подписывалось нормально.  Обновил версию компоненты до [5.42.1], ничего не изменилось.
![Uploading 1.JPG…]()
![Uploading 2.JPG…]()
![Uploading 3.JPG…]()

**Comment by VladdPush** [comment]
Добрый день! Скриншоты не загрузились, попробуйте приложить заново. Также приложите текст запроса и полный текст ответа с ошибкой. Уточните разрядность системы.

**Comment by tigr182** [comment]
Скриншоты, почему то не загружаются. Вот ссылка на данные скриншоты: https://disk.yandex.ru/d/Av5b2XZzwFhK7g
Разрядность системы х64.

**Comment by tigr182** [comment]
Добрый день! Удалось рассмотреть скриншоты? С чем может быть связана данная ошибка?

**Comment by tigr182** [comment]
метод Accept(), уже не формирует ответную подпись к документу?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Метод удалён в версии компоненты [5.37.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_37_0.html) - используйте [ReplySendTask2](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/ReplySendTask2.html)
