### ISSUE TITLE
И СНОВА ОШИБКА!!! Проблемы с подключением по некоторым сертификатам в версии 5.42.3.899

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#917]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
КПП2: 783450001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.42.1.875**.

Увидели, что вы выпустили новую версию компонент АПИ - 5.42.3.899.
Скачали, установили, протестировали... И в начале показалось, что всё хорошо. Но - поспешили!

## Обнаружилась очень странная проблема, которая воспроизводится со 100% повторяемостью:

На версиях АПИ 5-39-1-865 и 5-42-1-875 проблемы нет.
**На версии АПИ 5-42-3-899 постоянно возникает странная ошибка:**

При подключении по одному из наших сертификатов ЭП мы получаем ошибку:

>Ошибка при вызове метода контекста (CreateConnectionByCertificate): Произошла исключительная ситуация (DiadocCom.CreateConnectionByCertificate): ##300[Ошибка CryptoPro]Ошибка при получении криптопровайдера]

При этом сама ЭП и сертификат абсолютно нормальны - по нему прекрасно происходит подключение в версиях 5-39-1-865 и 5-42-1-875, а также при входе по нему в Диадок на вашем сайте.

Но в версии 5-42-3-899 - любая попытка подключения приводит к указанной ошибке. 

На всякий случай, данные сертификата, возвращаемые АПИ:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/3b33e8a6-1d9b-46a3-b69c-4d35d3373d60)

Важно!
Возможно, что проблемы не только с этим сертификатом! 

Просто выполнение обновления данных по имеющимся у нас ЭП и организациям ЭДО подключается к ЭДО по всем имеющимся у нас сертификатам. И на версиях АПИ 5-39-1-865 и 5-42-1-875 обновление данных происходит спокойно и без ошибок. Все подключения по всем ЭП происходят без проблем. При переходе на версию 5-42-3-899 - фиксируется стабильное попадание в эту ошибку на этом сертификате.

Может дальше еще бы на каких-то сертификатах так же бы упало, но мы этого уже не видим.

## Пожалуйста!
Исправьте данную проблему!

Спасибо.

**Comment by JohnSergeev** [comment]
Дополнительно:
Возможно, что это из-за того, что у нас происходили постоянные попытки подключения по этому сертификату в фоновых с постоянным обломом... Но заметили, что новая версия 5-42-3-899 при своей работе на сервере выжирала память раза в 3 быстрее, чем версия 5-42-1-875.

Возможно, что еще и какие-то утечки памяти есть.

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev  Если правильно понял, то только с с одним сертификатом и только на одной машине так происходит?

Пока не удалось воспроизвести поведение. Если не сложно, можете попробовать на [этой версии](https://disk.skbkontur.ru/index.php/s/RPJTLMTjaaqecm8) - вернул тот код криптографии, который был?

**Comment by JohnSergeev** [comment]
Происходит на нескольких машинах. 
Как минимум проверяли на разработке и на рабочем сервере.

Воспроизводится 100%: переходим на 5-42-3-899 - сразу облом!, возвращаем 5-42-1-875 - работает всё без проблем.
Повторяли такое "туда-сюда" вчера 4 раза. Результат всегда один и тот же.

Видим проблему только по одному сертификату, т.к. на нем происходит сбой нашего стандартного кода.

Возможно, что есть и другие с проблемами, но из-за сбоя они уже не видны.
По всем по отдельности по каждому не проверяли, т.к. надо для этого специальные тесты писать.

Предложенную версию попробуем обязательно.
О результатах отпишусь.

**Comment by JohnSergeev** [comment]
Дополнительно сделали тест и проверили все сертификаты.

На версии 5-42-3-899 указанная проблема возникает по указанному сертификату:
Писанов Виталий Валериевич, ООО "ДНС РИТЕЙЛ" (19.04.2023 - 19.04.2024) - [fcdbc9622913f78205bcf34359a701d6894990a6]

а также еще по трём:
Мертьев Дмитрий Владиславович, ООО "ДНС РИТЕЙЛ" (19.04.2023 - 19.04.2024) - [9f2c598315c73551ff76a100ae94827365fc1461]
Веремеенко Екатерина Алексеевна, ООО "ДНС РИТЕЙЛ" (20.04.2023 - 20.04.2024) - [7debbcebc4613975e37351d65600ddca8b21a867]
Крапивин Захар Александрович, ООО "ДНС РИТЕЙЛ" (21.04.2023 - 21.04.2024) - [4fc06d6cbab747be2c21340d008831669d53f564]

Для всех служебные данные (алгоритмы, удостоверяющий центр) одинаковы (см. картинку ранее).

На версии 5-42-1-875 нет проблем ни с одним из них.

**Comment by JohnSergeev** [comment]
Проверили предложенную версию компоненты.

И в варианте AddIn x64 5.42.3.900
И в варианте COM x64 5.42.3.900

Проблема осталась.

# НО!
**Заметили в процессе проверки один момент, детально с ним поковырялись и полностью разобрались в проблеме!**

### В работе официальной версии 5-42-3-899 с подключением по сертификатам ошибок подключения нет!

Оказалось, что вы с версии 5-42-3-899 поменяли текст сообщения об одной из ошибок, связанной с неверной установкой сертификатов.

До версии 5-42-1-875 (включительно) по неверно установленным сертификатам при попытке подключения возвращалась "детальная" ошибка:
>##300[Ошибка CryptoPro]Ошибка при получении криптопровайдера [2148073494:Набор ключей не существует]

а начиная с версии 5-42-3-899 по этим же сертификатам при попытке подключения стала возвращаться "укороченная" ошибка:
>##300[Ошибка CryptoPro]Ошибка при получении криптопровайдера

И на самом деле проблема не в компоненте. 

Проблема оказалась в нашем коде обработки таких ошибок, т.к. у нас была реализована реакция на сигнатуру _"Набор ключей не существует"_, а в новой версии компоненты по таким же точно ошибкам эта сигнатура перестала появляться и наш код стал для таких ситуация попадать в ветку обработки критических ошибок. И у нас всё падало.

**Возможно, вам стоит и о такого рода изменениях в поведении компоненты указывать в истории версий, т.к. тогда подобное изменение поведения не было бы неожиданностью, как это получилось в этот раз.**

Спасибо за помощь в разборе проблемы.

Тему, по идее, можно закрывать.

**Comment by GilimkhanovDenis** [comment]
Такого изменения не планировалось. Смотрю

**Comment by JohnSergeev** [comment]
Ок. 

**Для информации:**
Мы сделали поправку на сигнатуру ошибки, и сейчас у нас уже в рабочей системе работает новая версия компоненты 5-42-3-899. И проблем с подключениями действительно нет. 

Дело было только в неожиданном изменении описания возвращаемых ошибок.

**Comment by GilimkhanovDenis** [comment]
@JohnSergeev 

Вернул код и текст ошибки в [5.42.4](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)
