### ISSUE TITLE
EventID и DocumentID

### ISSUE THREAD

**Issue by pchelkinp** [diadoc/diadocsdk-1c-docs#918]
Сравниваю результаты GetDocumentEventList() компоненты и V3/GetDocflowEvents api.
В EventId, возвращаемом GetDocumentEventList(), на самом деле находится MessageID. В DocumentID - конкатенация MessageID и EntityID. Это недокументированная особенность?
Таким образом, если с одним документом (MessageId) произошло несколько событий в разные моменты времени, то GetDocumentEventList() вернёт их все с одинаковым EventId.
Какие события вернёт этот метод с параметром AfterEventId? Начиная с первого или последнего события по этому документу?

**Comment by GilimkhanovDenis** [comment]
GetDocumentEventList не использует V3/GetDocflowEvents

`DocumentID` - это действительно конкатенация `MessageID` и `EntityID` из HTTP API

один `MessageId` может быть у нескольких документов. Если события произошли в разное время, то будут разные `EventId`. `EventId` не всегда совпадает с `EntityID` документа. На уровне HTTP API может произойти одно событие, но компонента покажет их как несколько

Может быть так, например (скриншот из https://github.com/diadoc/diadocsdk-1c-docs/issues/696)
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/0ed64fca-1034-43ce-b96e-f2eccb75c40b)

При вызове метода с параметром AfterEventId вернётся пачка событий ПОСЛЕ указанного AfterEventId

**Comment by pchelkinp** [comment]
Т.е. все события с документом в момент его создания имеют EventId=MessageId. 
События, происходящие с этим документом в последующее время получают новый EventId?

**Comment by GilimkhanovDenis** [comment]
В ближайшее время пока нет. Задача в бэклоге есть, но когда реализуем неизвестно
