### ISSUE TITLE
Подписание с статусом WithPartiallyRecipientSignature («Подписан с разногласиями»)

### ISSUE THREAD

**Issue by energo86** [diadoc/diadocsdk-1c-docs#919]
В ДиаДоке было добавлено подписание с статусом «Подписан с разногласиями», в данной библиотеке реализована возможность подписание с таким статусом?
https://www.diadoc.ru/blog/22017-v_diadoke_poyavitsya_novyj_status_podpisaniya

**Comment by GilimkhanovDenis** [comment]
Добрый день

Да. Данный статус указывается путём подписания документа вторым титулом с соответствующим заполнением контента.

Например, для `[UniversalTransferDocument; СЧФДОП; utd820_05_01_02_hyphen]` - это поле ContentOperCode в DynamicContent'е второго титула
