### ISSUE TITLE
COM-компонента для встраивания в произвольные системы, для 64-х битных приложений

### ISSUE THREAD

**Issue by 7923655** [diadoc/diadocsdk-1c-docs#92]
Добрый день! Уважаемые разработчики, передайте пожалуйста информацию ответственным людям которые занимаются поддержкой, что вашу компоненту нельзя использовать параллельно и это приводить к падениям рабочих процессов. Также желательно разместить эту информацию на сайте http://diadocsdk-1c.readthedocs.io/ru/latest/Downloads.html.

**Comment by denver069** [comment]
Мы подготовили новую версию внешней компоненты с возможностью многопоточного использования, в ближайшее будем выпускать релиз.
Для получения информации о выходе новой версии, вы можете подписаться на ленту новостей [RSS](http://diadocsdk-1c.readthedocs.io/ru/latest/index.rss)
