### ISSUE TITLE
ВОПРОС. Странное и непонятное формирование данных документа и его печатной формы для неформализованного счёта на оплату, получаемого в роуминге

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#921]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
КПП2: 783450001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.42.4.901**.

Вместе с одним из наших поставщиков столкнулись с ...эээ..., скажем так, несколько непонятной обработкой документов типа
### "Неформализованный счет на оплату", получаемых нами в роуминге.

Ситуация:

### 1.	Поставщик отправляет нам неформализованный счет на оплату

Тип        = ProformaInvoice
ID           = 25e3b6be-058c-4fc4-9f55-d365d03d7f3dabc140f2-d919-4555-9176-d2c0cde28bb3
URL       = https://diadoc.kontur.ru/c4390c58-315b-4323-a9b4-b5d87d6e868b/Document/Show?letterId=25e3b6be-058c-4fc4-9f55-d365d03d7f3d&documentId=abc140f2-d919-4555-9176-d2c0cde28bb3

### 2.	Поставщик отправляет этот документ в роуминге (Тензор)

![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/8ea73387-fbad-463b-b97e-67b7d7a31a50)

Контрагент Guid = 93e9927f-ec11-4a98-bbf1-97ca07993b05

### 3.	В данных получаемого в Диадок неформализованного счета на оплату мы видим информацию в следующих полях:
 
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/7d21f201-c4fd-49ce-927e-f3617805ca54)

Или, чуть более понятно:

![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/afa3fe06-49d5-447e-8830-db8ef73f7da5)

То же и в документе у вас на сайте:

 ![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/056d8790-f18e-479d-a73d-8cdab1f762e8)

Т.е. и в данных возвращаемых АПИ, и в данных на сайте видно, что в неформализованном счете на оплату передано:
>**Сумма                                                – 210500 руб.**
>**Сумма НДС                                       – 0 (без НДС)**
>**Основание документа                – не заполнено**

### 4.	Однако, если посмотреть на печатную форму документа, то там видно следующее:

![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/7cc032f6-1edb-49ab-b6da-14b2a2bab0f0)

Т.е. есть основание документа. И сумма НДС вовсе не нулевая.

Поначалу кажется, что - "_Ну и что? Это же неформализованный счет. Значит просто такую PDF вложили в документ_".
### 5.	Если получить архив файлов документа, то там будут следующие файлы:

![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/35fe53ae-68fa-4eee-9778-0a6529c00a3c)

**Видно, что в качестве данных передается не PDF файл с «картинкой» счета, а XML файл с данными счета.** 
**И именно по его содержимому (получается!) уже вами (Диадоком) генерируется печатная форма!**

Иначе просто непонятно откуда эта печатная форма берется.

### 6.	При этом в самом передаваемом файле XML есть все данные, которые в итоге и попадают на печатную форму (некоторые места выделены). Сперва "Картинка" файла, а затем весь его текст:

![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/6a1016ef-933e-45a2-85a7-559451243b1c)

Текст XML (вы его и сами можете в архиве документа найти, если что):

<?xml version="1.0" encoding="windows-1251"?>
<Файл Формат="ЭДОСч" ВерсияФормата="3.01" Имя="ON_SCHET___20230606_132652d6-5f46-415d-849b-b3418369ac08" КодФормы="СВИФТ_Рус_Счет">
               <Документ Название="Счет на оплату" Дата="02.06.2023" Время="12.02.18" Номер="3289" Примечание="Поручение экспедитору № ЦЕ6-019381 от 18.05.2023г.">
                               <Валюта КодОКВ="643"/>
                               <Поставщик Название="Общество с ограниченной ответственностью &quot;СВИФТ-РУС&quot;">
                                               <Адрес Тип="Юридический" АдрТекст="117105, Москва г, Новоданиловская наб, дом № 6, корпус 1, этаж 7, офис 711">
                                                              <АдрРФ Индекс="117105" КодРегион="77" Улица="Новоданиловская наб" Дом="6" Корпус="1" Кварт="эт.7,оф.711"/>
                                               </Адрес>
                                               <БанкРекв НаимБанк="Филиал &quot;Центральный&quot; Банка ВТБ (ПАО)" БИК="044525411" КСчет="30101810145250000411" РСчет="40702810710020000800"/>
                                               <Контакт Телефон="7 (495) 646-70-07" EMAIL="[imishina@swiftrus.ru](mailto:imishina@swiftrus.ru)"/>
                                               <СвЮЛ Название="Общество с ограниченной ответственностью &quot;СВИФТ-РУС&quot;" ИНН="9705052741" КПП="772601001" ОКПО="18776818" ОКОПФ="12300" ОКФС="16" ОКВЭД="63.40"/>
                               </Поставщик>
                               <Покупатель Название="ООО &quot;ДНС РИТЕЙЛ&quot;">
                                               <Адрес Тип="Юридический" АдрТекст="690068, Приморский край, г. Владивосток, пр-кт 100-Летия Владивостока, дом 155, КОРПУС 3 ОФИС 5">
                                                               <АдрРФ Индекс="690068" КодРегион="25" Город="Владивосток г." Улица="100-Летия Владивостока пр-кт" Дом="155" Кварт="КОРПУС 3 ОФИС 5"/>
                                               </Адрес>
                                               <БанкРекв НаимБанк="ПАО СКБ ПРИМОРЬЯ &quot;ПРИМСОЦБАНК&quot;" БИК="040507803" КСчет="30101810200000000803" РСчет="40702810600100003410"/>
                                               <Контакт EMAIL="[Migaeva.MG@dns-shop.ru](mailto:Migaeva.MG@dns-shop.ru)"/>
                                               <СвЮЛ Название="ООО &quot;ДНС РИТЕЙЛ&quot;" ИНН="2540167061" КПП="783450001"/>
                               </Покупатель>
                               <Параметр Имя="ДоговорДата" Значение="02.06.2023"/>
                               <Параметр Имя="ДоговорНомер" Значение="3289"/>
                               <Параметр Имя="ИмяВалюты" Значение="руб."/>
                               <Параметр Имя="ВалютаКод" Значение="643"/>
                               <Параметр Имя="ДоговорНаим" Значение="Договор № СВФ-18112020 от 18.11.2020 г., Поручение экспедитору № ЦЕ6-019381 от 18.05.2023г."/>
                               <Параметр Имя="СрокОплаты" Значение="20.06.2023"/>
                               <Параметр Имя="ЦенаСНДС" Значение="1"/>
                               <ТаблДок>
                                               <ИтогТабл Кол_во="1.000" Сумма="210500.00" СуммаБезНал="175416.67">
                                                               <НДС Сумма="35083.33"/>
                                               </ИтогТабл>
                                               <СтрТабл Код="00-00001225" Название="Услуга по организации внутрироссийской перевозки 40 фут. контейнера по маршруту:142440, Московская обл., г.Ногинск, рп.Обухово, тер.Атлант-Парк.,д.28, стр.33 - 680015, г.Хабаровск, ул.Суворова, 82а (дата погрузки 23.05.23г.) (SWFU9902055)" Описание="Услуга по организации внутрироссийской перевозки 40 фут. контейнера по маршруту:142440, Московская обл., г.Ногинск, рп.Обухово, тер.Атлант-Парк.,д.28, стр.33 - 680015, г.Хабаровск, ул.Суворова, 82а (дата погрузки 23.05.23г.)" Кол_во="1.000" ЕдИзм="шт" ОКЕИ="796" Сумма="210500.00" Цена="175416.67" Идентификатор="00-00001225" ПорНомер="1" СуммаБезНал="175416.67">
                                                               <Акциз Сумма="без акциза"/>
                                                               <НДС Сумма="35083.33" Ставка="20" ТипСтавки="процент"/>
                                               </СтрТабл>
                               </ТаблДок>
               </Документ>
</Файл>

##  Итого:
Получается, что на основании переданного XML неформализованного счета на оплату Диадок формирует печатную форму, в которой верно отображаются передаваемые в XML данные – например, сумма НДС и данные основания счета.

Но почему-то в самих данных документа в поля неформализованного счета на оплату попадает только итоговая сумма. 
А информация по основанию документа и по сумме НДС по нему – не передается!

Причем так происходит и при работе через АПИ Диадок для 1С, и на сайте Диадока (см. выше картинки содержимого документа, полученного через АПИ и заголовка документа на сайте).

### Вопросы:
1.	А почему так происходит? Есть какое-то объяснение?
2.	Может так быть, что в обработке данных неформализованного счета на оплату у вас допущена какая-то ошибка, в результате которой на печатной форме данные формируются верно, но в содержимое самого формируемого получаемого счета попадают не все данные, которые должны были туда попасть?
3.	Если проблема в п.2 есть, но она связана с какими-то проблемами и ограничениями в роуминге, тогда почему эти проблемы и ограничения не касаются формирования печатной формы документа? 

Может как-то можно привести поведение формирования реквизитов документа в соответствие с тем, как это обрабатывается при формировании печатной формы?

Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Документ пришёл из роуминга как неформализованный счёт. Согласно технологии РОСЭУ, применяемой в роуминге, в описании логического сообщения (файл description.xml), есть **необязательные** поля "Сумма" и "Сумма НДС". То есть оператор может передавать в них соответствующие значения, и тогда метаданные будут присутствовать в метаинформации документа, или не передавать как в данном случае. В веб интерфейсе эти метаданные отображаются в списке документов и на странице просмотра документа

![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/ac3884f4-8f56-42ae-b4f8-9b61ac7d28a0)

Печатная форма и превью документа в веб строится по контенту документа, в котором информция об НДС есть

Итого, чтобы информация об НДС присутствовала в метаинформации документа, необходимо, чтобы отправитель её указал
