### ISSUE TITLE
Очень странное поведение и трата ресурсов в методах GetDocumentPackage() и GetPackageDocuments() работы с пакетами документов

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#922]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
КПП2: 783450001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.42.4.901**.

# Часть 1

**Небольшая ремарка:**
При получении документа по ЭДО мы, кроме самого документа, также получаем информацию о пакете документов, в который он входит. Причем мы получаем и то, в каком пакете документ был отправлен, и то, в каком пакете документ находится сейчас.

Используем для этого методы АПИ:
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/105cbdc9-9de9-4908-b974-ddf5dc6127ba)

С помощью **GetDocumentPackage()** получаем данные пакета, в котором документ был отправлен.
А с помощью **GetPackageDocuments()** - данные пакета, в котором документ находится сейчас.

Это нужно, как минимум, для того, чтобы как можно оперативнее получить в учетной системе все документы, входящие в один пакет. 

Вчера в рамках одной из важных доработок провели тестирование создания документов, получаемых по ЭДО на наборе документов примерно в 5500 шт. Результаты оказались настолько интересными, что мы их еще раз сегодня перепроверили на примерно 550 шт. документов, кое-что поменяв. Изначально просто проверяли нет ли ошибок в обновленном коде. И только. Просто, что называется, "_глаз невольно зацепился_".

### Первый тест:
В этом тесте в коде получения и разбора данных документов, у нас первым из методов **GetDocumentPackage()** и **GetPackageDocuments()** вызывался метод **GetDocumentPackage()**.

![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/ea307ea6-70fe-476b-80bf-6a8cb0bb90d1)

С очень большим удивлением мы увидели, что:
1. Операция **GetDocumentPackage()** получения пакета документов, в котором был отправлен обрабатываемый документ, занимает в обработке документов больше всего времени. И не просто больше, а **~46% от всего времени обработки**!
2. Операция **GetDocumentPackage()** получения пакета документов, в котором был отправлен обрабатываемый документ, занимает в обработке документов примерно на 35% больше времени (~46%), чем получение самих документов (GetDocumentById - ~29.5%) и всего их содержимого (GetDynamicContent - ~4.5%)!
3. Операция **GetDocumentPackage()** получения пакета документов, в котором был отправлен обрабатываемый документ, занимает в обработке документов **намного больше времени** (~46%), чем операция **GetPackageDocuments()** получения текущего состава пакета документов (~4%) - примерно в 11 раз!

Первые 2 пункта вызвали большое удивление сами по себе. Третий пункт позволил предположить, что проблема может быть в каком-то кешировании данных, т.к. кажется, странным, что два метода, получающие "примерно одно и тоже" могут работать с 11-ти кратной разницей по скорости.

Поэтому мы провели 

### Второй тест:
В этом тесте мы поменяли порядок вызова получения информации по пакетам документов. 
И в коде получения и разбора данных документов, у нас первым из методов **GetDocumentPackage()** и **GetPackageDocuments()** вызывался метод **GetPackageDocuments()**.

![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/b5d186b4-8ce3-4fd7-81c4-af82c26101f9)

В тесте был использовано примерно в 10 раз меньше документов для проверки (~550 против ~5500). Но полученные результаты все равно позволяют сказать, что никакой связи с возможным кешированием данных нет и действительно по какой-то причине  метод **GetDocumentPackage()** работает примерно в 10-11 раз медленнее, чем метод **GetPackageDocuments()**.

## Вопросы:
1. С чем может быть связана такая большая (10-11 раз!) разница в скорости работы методов **GetDocumentPackage()** и **GetPackageDocuments()**?
2. Можно ли как-то ускорить работу метода **GetDocumentPackage()**? Сейчас при его использовании при обработке документа тратится почти столько же времени, сколько на всё остальное!
3. Может ли быть так, что вышеописанные особенности являются следствиями каких-то ошибок и недоработок в реализации метода **GetDocumentPackage()**?

Очень бы хотелось, чтобы вы проверили поведение метода **GetDocumentPackage()**. Т.к., если реально есть какие-то ошибки или недоработки в его работе, и есть шанс сделать его быстрее, то это поможет нам и другим пользователям АПИ существенно ускорить обработку документов.

# Часть 2

Ранее я уже писал об этом. Сейчас еще раз повторю, т.к. очень уж красноречивая статистика нарисовалась.

При получении и обработке документа из ЭДО нам важно знать в какой пакет документов он входит. Для того, чтобы максимально быстро формировать в учетной системе не документы "вообще", а документы, входящие в один пакет, т.к. в них могут находится какие-то связанные данные.

При этом обработка одного документа происходит в транзакции в рамках учетной системы, т.к. мы, кроме получения данных документа из ЭДО, естественно, обработав эти данные, в каком-то виде заносим их в учетную систему. И при каких-то сбоях откатывая транзакцию не нарушаем целостность данных в учетной системе.

Из этого следует вывод, что при обработке одного документа нам не нужны какие-то другие документы. Максимум, что нам может быть нужно - это **какая-то информация о других документах. Но не они сами!**

## Предложение

Было бы очень здорово, если бы в АПИ для методов **GetDocumentPackage()** и **GetPackageDocuments()** были бы их аналоги - методы получения не **документов** отправленного и текущего пакетов, а только **ID этих документов**!

Для учета того, что входит в пакеты текущего обрабатываемого документа этого было бы достаточно. А сама обработка этих документов всё равно происходит по отдельности. А получить нужные **уже именно документы по ID** мы бы совершенно спокойно могли стандартным методом **GetDocumentById()**.

При этом возвращение **только ID документов без их содержимого** дало бы сплошные плюсы и нам, и вам:
1. Мы бы быстрее получали и обрабатывали документы
2. У вас бы нагрузка на системы и сети снизилась, т.к. и получать данных надо было бы меньше, и передавать по сети тоже гораздо меньше.

**Пожалуйста, рассмотрите данное предложение!**

Тем более, что вполне возможно, что где-то у вас в реализации вы сперва получаете как раз ID документов, затем по ID получаете содержимое самих документов и передаете всё это как результат. Так сделайте просто передачу только собранных ID. От этого в выигрыше будем мы - пользователи АПИ - мы быстрее будем получать документы. От этого в выигрыше будете и вы - Диадок - вы быстрее будете отдавать данные, снизите расход ресурсов на получение документов и сетевой трафик.

Спасибо.

**Comment by NickZubashevskiy** [comment]
Добрый день!

После тестов на производительность было выявлено, что разница в производительности проявляется на одиночных документах. Это связано с тем, что GetPackageDocuments имеет оптимизацию - проверяет принадлежность документа к пакету, и если не принадлежит - вызов к ядру не делается. 

У вас в выборке были преимущественно одиночные документы?

**Comment by NickZubashevskiy** [comment]
Добавили подобную оптимизацию для метода GetDocumentPackage, выйдет в версии 5.51

**Comment by NickZubashevskiy** [comment]
Вышла версия 5.51 с оптимизацией по этому тикету
