### ISSUE TITLE
ПРОБЛЕМА! Странное расхождение в поведении аннулирования на сайте и в АПИ

### ISSUE THREAD

**Issue by JohnSergeev** [diadoc/diadocsdk-1c-docs#925]
Добрый день.

Общая информация для упрощения «разбора полётов»:
Организация: «ДНС Ритейл»
ИНН: 2540167061
КПП: 254301001
КПП2: 783450001
ID организации: [c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru](mailto:c4390c58315b4323a9b4b5d87d6e868b@diadoc.ru)
ID участника ЭДО: 2BM-2540167061-254001001-201312151140099321090

Мы работаем с Диадок с использованием компонент АПИ для 1С
https://diadocsdk-1c.readthedocs.io/ru/latest/index.html
Текущая используемая версия: **COM x64 5.42.4.901**.

Столкнулись с двумя "странными" документам, которые никак не получалось аннулировать через АПИ.
При разборе ситуации возникли вопросы, на которые хотелось бы получить ответы. Т.к. замеченная "странность" очень похожа на какую-то недоработку или ошибку.

### Документы:
**№1. Исходящий УПД №ЦЧ4-005586/1136 от 28.06.2023**
ID = 4486c74a-ff10-429d-8ca7-4f25e997fc0eb2d0d860-3e2e-49a0-a159-64a423ae5ee6
URL = /c4390c58-315b-4323-a9b4-b5d87d6e868b/Document/Show?letterId=4486c74a-ff10-429d-8ca7-4f25e997fc0e&documentId=b2d0d860-3e2e-49a0-a159-64a423ae5ee6

**№2. Исходящий УПД №ЦЧ4-005680/1136 от 30.06.2023**
ID = de0b3622-7c15-4cfa-b8e4-422d59b37f6ba2f9e639-d4ab-4c42-8016-3a603485f62e
URL = /c4390c58-315b-4323-a9b4-b5d87d6e868b/Document/Show?letterId=de0b3622-7c15-4cfa-b8e4-422d59b37f6b&documentId=a2f9e639-d4ab-4c42-8016-3a603485f62e

### Ситуация:
Отправили документы контрагенту. Он попросил их аннулировать. Мы (работая через АПИ) попытались их аннулировать и получили следующее:

Документы не аннулировались по причине возникновения ошибки вида:
>Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (ReplySendTask2.Send): ##100[Ошибка >сервера Диадок]code:409, HTTP error: Recipient forbids to receive messages from blocked senders]

Т.е. мы почему-то считались заблокированным отправителем.

Стали разбираться. Оказалось, что (как это часто в Диадок бывает) контрагент, с которым мы работаем присутствует у вас в виде двух контрагентов ЭДО - один в Контуре, а другой - роуминговый.
![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/d710aec4-2cd6-4fd1-b71c-c5d198d0e032)

И мы отправляли документы контрагенту №1 с GUID = e24addf8-8c59-49b3-bc31-3ba826f8964a. Не в роуминг. И контрагент как раз попросил аннулировать эти документы и отправить ему их в роуминг - т.е. контрагенту №2 с GUID = 61292bb9-0c86-42e3-8ec4-2ff5f0ce8147.

Т.е. произошло следующее:
1. Мы еще были в рабочих отношениях с контрагентом №1 (e24addf8-8c59-49b3-bc31-3ba826f8964a) и отправили ему два этих документа.
2. Контрагент (реальный, "физический"!) увидел, что документы отправлены не в роуминг и сделал по ним запрос на удаление с просьбой отправить новые экземпляры документа контрагенту №2 (61292bb9-0c86-42e3-8ec4-2ff5f0ce8147)
3. После этого контрагент (реальный, "физический"!) "от лица" контрагента №1 (e24addf8-8c59-49b3-bc31-3ba826f8964a) разорвал с нами отношения.
4. Мы увидели по документам запросы на аннулирование и подтвердили их.
5. Операции подтверждения аннулирования стали пытаться выполнится, но выполнится не могли и стали выдавать вышеуказанную ошибку о блокировке отправителя и невозможности выполнения операции.

Вроде всё выглядит логично - операция подтверждения аннулирования с документами такого-то контрагента не выполняется и блокируется, т.к. на момент попытки выполнения этих операций у нас уже нет отношений с контрагентом. Ну, просто попали в такую ситуацию.

Но получилось так, что мы захотели посмотреть, какая ошибка нам будет показана на сайте Диадок, если мы попробуем аннулировать один из этих документов непосредственно на сайте.

И мы попробовали аннулировать документ №2 (с ID = de0b3622-7c15-4cfa-b8e4-422d59b37f6ba2f9e639-d4ab-4c42-8016-3a603485f62e).

И, к нашему несказанному удивлению, на сайте, вместо того, чтобы тоже выдать какое-то сообщение о том, что происходит попытка обработать документ контрагента, с которым более нет отношений, и выполнение аннулирования невозможно... документ прекрасно и без проблем аннулировался. Что было видно и на сайте, и через АПИ!

![изображение](https://github.com/diadoc/diadocsdk-1c-docs/assets/33707226/624fc358-045e-409b-9e11-5b26d82ab396)

### Вопросы:
1. А почему различается поведение и возможности у сайта и у АПИ? Почему в такой ситуации на сайте операция выполняется, а АПИ возвращает ошибку блокировки?
2. А как вообще правильно? Т.е. сейчас правильно работает сайт - и надо починить АПИ! Или же правильно работает АПИ - и надо починить сайт!
3. Сделаете ли вы что-то, чтобы поведение сайта и АПИ было бы одинаковым в такой ситуации? То, что сейчас поведение расходится выглядит совершенно ненормальным!

Спасибо.

**Comment by ilzag** [comment]
Добрый день!
Разница в поведении при обмене запросами с помощью API и через веб-интерфейс действительно присутствует.

PostMessagePatch возвращает ошибку на любой патч в сторону заблокированного контрагента сразу.

В веб-интерфейсе нет моментальной проверки отношений между контрагентами, поэтому если после загрузки документа изменился статус отношений с контрагентом, аннулировать документ удастся. На данном этапе от команды разработчиков нет информации, когда это будет решено, поэтому рекомендуем учесть в работе этот момент.

**Comment by GilimkhanovDenis** [comment]
Компонента в данном сценарии исправить поведение не может. Обращение закрываю. Если требуется исправление поведения в вебе или в API, то предлагаю решать задачу через менеджера
