### ISSUE TITLE
Не могу отправить УКД

### ISSUE THREAD

**Issue by ElenaBurnasheva** [diadoc/diadocsdk-1c-docs#926]
Здравствуйте. Не могу отправить УКД через АПИ.
Компонента DiadocCom_5_43_0_904_x64.dll
В УКД 6 строчек, 5 - не меняется, а в одной убирается все количество, соответсвенно суммы после 0. 
Получаются вот такие данные 
<HTML>
<HEAD>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; CHARSET=utf-8"/>
<TITLE></TITLE>
</HEAD>
<BODY STYLE="background: #ffffff; margin: 0; font-family: Arial; font-size: 8pt; font-style: normal; ">

<TABLE style=" overflow: visible;table-layout: fixed; padding: 0; padding-left: 2px; vertical-align:bottom; border-collapse:collapse;font-family: Arial; font-size: 8pt; font-style: normal; " CELLSPACING=0>
<TBODY STYLE="background: #ffffff; margin: 0; font-family: Arial; font-size: 8pt; font-style: normal; ">
<COLGROUP>
<COL WIDTH=208>
<COL WIDTH=279>
<COL WIDTH=189>
</COLGROUP>
<TR STYLE="height: 15px; ">
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; padding-left: 2px; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Table</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">COMОбъект</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">COMОбъект</SPAN></TD>
</TR>
<TR STYLE="height: 15px; ">
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; padding-left: 2px; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Items</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">COMОбъект</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">COMОбъект</SPAN></TD>
</TR>
<TR STYLE="height: 15px; ">
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; padding-left: 2px; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Item</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">COMОбъект</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">COMОбъект</SPAN></TD>
</TR>
<TR STYLE="height: 15px; ">
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; padding-left: 2px; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Count</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">6</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Число</SPAN></TD>
</TR>
<TR STYLE="height: 15px; ">
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; padding-left: 2px; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">TotalsDec</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">COMОбъект</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">COMОбъект</SPAN></TD>
</TR>
<TR STYLE="height: 15px; ">
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; padding-left: 2px; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Total</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">"706406.4"</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Строка</SPAN></TD>
</TR>
<TR STYLE="height: 15px; ">
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; padding-left: 2px; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">TotalWithVatExcluded</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">"588672"</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Строка</SPAN></TD>
</TR>
<TR STYLE="height: 15px; ">
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; padding-left: 2px; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Vat</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">"117734.4"</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Строка</SPAN></TD>
</TR>
<TR STYLE="height: 15px; ">
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; padding-left: 2px; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">WithoutVat</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">""</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Строка</SPAN></TD>
</TR>
<TR STYLE="height: 15px; ">
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; padding-left: 2px; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">TotalsInc</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">COMОбъект</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">COMОбъект</SPAN></TD>
</TR>
<TR STYLE="height: 15px; ">
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; padding-left: 2px; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Total</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">""</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Строка</SPAN></TD>
</TR>
<TR STYLE="height: 15px; ">
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; padding-left: 2px; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">TotalWithVatExcluded</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">""</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Строка</SPAN></TD>
</TR>
<TR STYLE="height: 15px; ">
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; padding-left: 2px; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Vat</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">""</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Строка</SPAN></TD>
</TR>
<TR STYLE="height: 15px; ">
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; padding-left: 2px; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">WithoutVat</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">""</SPAN></TD>
<TD STYLE="font-family: Arial; font-size: 8pt; font-style: normal; color: #000000; background-color: #ffffff; text-align: left; vertical-align: top; border-left: #b3ac86 1px solid; border-top: #b3ac86 1px solid; border-bottom: #b3ac86 1px solid; border-right: #b3ac86 1px solid; "><SPAN STYLE="white-space:nowrap;max-width:0px;">Строка</SPAN></TD>
</TR>
</TBODY>
</TABLE>
</BODY>
</HTML>
﻿
 При отправке вылетает следующая ошибка
Документ <Счет фактура выданный КСФМИ00001 от 30.06.2023 8:00:00> не отправлен. {ОбщийМодуль.Диадок_РаботаССерверомДиадок.Модуль(1261)}: {ОбщийМодуль.Диадок_РаботаССерверомДиадок.Модуль(1245)}: Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:¶/UniversalCorrectionDocument/Table/Items/Item[1]/Vat/AmountsDec: AmountsDec must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[2]/Vat/AmountsDec: AmountsDec must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[3]/Vat/AmountsDec: AmountsDec must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[5]/Vat/AmountsDec: AmountsDec must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[6]/Vat/AmountsDec: AmountsDec must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[1]/Subtotal/AmountsDec: AmountsDec must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[2]/Subtotal/AmountsDec: AmountsDec must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[3]/Subtotal/AmountsDec: AmountsDec must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[5]/Subtotal/AmountsDec: AmountsDec must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[6]/Subtotal/AmountsDec: AmountsDec must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[1]/SubtotalWithVatExcluded/AmountsInc: AmountsInc must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[2]/SubtotalWithVatExcluded/AmountsInc: AmountsInc must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[3]/SubtotalWithVatExcluded/AmountsInc: AmountsInc must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[5]/SubtotalWithVatExcluded/AmountsInc: AmountsInc must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[6]/SubtotalWithVatExcluded/AmountsInc: AmountsInc must be > 0¶/UniversalCorrectionDocument/Table/Items/Item[4]/Subtotal/@CorrectedValue: Function=КСЧФ @CorrectedValue is required, when ../TaxRate[@OriginalValue != 'НДС исчисляется налоговым агентом']¶/UniversalCorrectionDocument/Table/Items/Item[4]/SubtotalWithVatExcluded/@CorrectedValue: Function=КСЧФ @CorrectedValue is required¶/UniversalCorrectionDocument/Table/Items/Item[4]/Vat/@CorrectedValue: Vat/@CorrectedValue or WithoutVat/@CorrectedValue is required, when TaxRate/@OriginalValue != 'НДС исчисляется налоговым агентом'

Как это исправить?

**Comment by Max-Redhead** [comment]
Добрый день!
1. Рекомендуем использовать актуальную версию компоненты. 
2. Согласно Приказу 736@ (https://normativ.kontur.ru/document?moduleId=1&documentId=375857) в корректировочных документах данного формата должны быть только те позиции, по которым произошло изменение стоимости или количества товара и поменялась сумма налога.
То есть, вам необходимо оставить только позицию с изменениями, а остальные удалить

**Comment by ElenaBurnasheva** [comment]
Спасибо. Можно закрывать.
