### ISSUE TITLE
МЧД: HTTP error: Power of attorney not found

### ISSUE THREAD

**Issue by dkamyshn** [diadoc/diadocsdk-1c-docs#927]
Идентификатор участника ЭДО (GUID): 2BM-7743068844-774301001-201502090458113110848
Версия компоненты: DiadocCom_5_43_0_904_x64.dll
PathURL документа: /7454892d-ab5d-4b35-990f-abc3da5a35e9/Document/Show?letterId=b8b853a7-9e09-49a8-8cd7-5c08781b32da&documentId=8db5a627-b497-49a3-bb37-e283c48b29e3

При попытке воспользоваться методом GetPowersOfAttorney() возвращается ошибка:
(DocumentBase.GetPowersOfAttorney): ##100[Ошибка сервера Диадок]code:404, HTTP error: Power of attorney not found

Если открыть документ в вэб сервисе, видно, что у документа есть прикреплённая доверенность.
![7454892d-ab5d-4b35-990f-abc3da5a35e9](https://github.com/diadoc/diadocsdk-1c-docs/assets/29984533/976de4d9-b289-4e01-a57e-96546b8762bf)

Сообщите, пожалуйста, это баг или я что то не так делаю?

**Comment by GilimkhanovDenis** [comment]
Добрый день

В версии [5.46.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_46_0.html) сделано так, что вызов метода не будет завершаться ошибкой. В информации об МЧД, по которым эта ошибка возникала вернётся только идентификатор доверенности
