### ISSUE TITLE
NeedToAttachPowerOfAttorney

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#928]
Здравствуйте. У объекта MyEmployee есть свойство: NeedToAttachPowerOfAttorney Булево, чтение - флаг необходимости использовать МЧД. Я не понял где он изначально устанавливается. Посмотрел в вебинтефейсе настройки сотрудника организации и не нашел ничего похожего.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Он нигде не устанавливается. Он вычисляется компонентой на основе данных сертификата и данных организации - True, если авторизация произошла по сертификату физлица или ИНН владельца сертификата не совпадает с ИНН организации. Носит чисто информационный характер и в логике самой компоненты нигде не учитывается

**Comment by evgen421** [comment]
Понятно, спасибо.
