### ISSUE TITLE
начало работы с DiadicApi в VBA

### ISSUE THREAD

**Issue by BatooHan** [diadoc/diadocsdk-1c-docs#929]
Доброго всем дня.
Зарегистрировал библиотеку .dll в системе. Пытаюсь работать с ней в редакторе VBA, но пока что не могу понять даже как начать использовать её.
Подключил её в свойствах проекта, появились две библиотеки для работы DiadocComApiLib и DiadocCom. Очень мало примеров на VBA, те что я нашёл у меня не работают, на использование любого метода выдаёт ошибку.
Задача - авторизоваться в системе, получить список счетов-фактур, получить тело счетов-фактур (выборочно).
Может кто-нибудь помочь с примерами кода именно в VBA?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Невозможно для каждого языка, в котором можно работать с COM-объектами написать пример кода, поэтому примеры написаны на 1С, так как изначально для него создавалась компонента

Какую ошибку получаете и при каких действиях?

**Comment by BatooHan** [comment]
Ну, например. Вот кусок начала кода(логин и пароль здесь, конечно, вымышленные):
```
    Dim DiadocAPI As DiadocCom
    Dim Dconn As DiadocComApiLib.IDiadocConnection
    
    Dim Login As String
    Dim pass As String
    
    Login = "rr@test.ru"
    pass = "tst|TzTTk8T5yKfVc|ee"
    
    Set Dconn = DiadocAPI.CreateConnectionByLogin(Login, pass)
```
На последней строке я получаю ошибку - **Object variable or With block variable not set**.
Ну, и так при обращении к любому свойству объекта DiadocAPI (имеющего тип DiadocCom).
И непонятно куда двигаться дальше.

**Comment by GilimkhanovDenis** [comment]
А объект `DiadocAPI` вообще создался?

Подозреваю, нужно вызвать [CreateObject(...)](https://learn.microsoft.com/en-us/office/vba/language/reference/user-interface-help/createobject-function):
`Set DiadocAPI = CreateObject("Diadoc.DiadocClient");`

**Comment by BatooHan** [comment]
Да, я тоже так "подозревал", но... на этот вариант создания объекта компилятор отвечает - **ActiveX component can't create object**
Это, думаю, из-за того что компонента **Diadoc** в системе не зарегистрировано. Как я и написал, после регистрации DLL в системе мне стали доступны в редакторе два компонента - **DiadocComApiLib** и **DiadocCom**, при этом судя по всему **DiadocCom** входит в состав **DiadocComApiLib** (**DiadocComApiLib.DiadocCom**) так что не совсем понятно почему два компонента появилось, но это лирическое отступление. Главное - я пока не пойму как работать с этими объектами в среде VBA. 
Кстати я не указал из какой программы я использую VBA, это может иметь значение т.е. набор объектов в разных продуктах Микрософт, использующих VBA различается. Я использую **ACCESS**.

**Comment by energy75** [comment]
Коллега, добрый день. Как успехи ?

Тоже начинал когда-то очень давно с Аксесса. Очень советую изучить возможности Visual Studio по созданию Офисных продуктов, но с выполнением "взрослого кода" на VB.Net /С#  .   VSTO - Visual Studio Tools for Office.  Жизнь заиграет новыми красками, поверьте.

**Comment by BatooHan** [comment]
Добрый день.
Да, сам сейчас активно изучаю Visual Studio и С#. Работа именно в Access продиктована условиями на стороне работодателя.
По API диадока для VBA Access могу сказать, что... он, к сожалению, не пригоден т.к. этот API ориентирован только на работу в 1С, а там своеобразный VBA. К VBA от MS он имеет весьма далёкое отношение.
Поэтому всё что мне нужно реализовал через API Http, который предоставляет диадок. Там достаточно хорошая документация с полным описанием и функций и структур.
Т.е. создаю объект Microsoft.XMLHTTP. Через него отправляю запрос, получаю ответ.
Ну, а разбор полученного уже пилю под свои задачи.

**Comment by GilimkhanovDenis** [comment]
Как и говорил, нужно создать объект с именем `Diadoc.DiadocClient` как и указано в документации.

Можно, например установить поле с адресом API
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/96a3d4a7-4888-4974-ab70-73494062f9ac)

Чтобы убедиться, что это не создание какого-то поля в произвольном объекте, можно попытаться установить значение в несуществующее поле и получить ошибку
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/7d936c1b-cff4-432d-b95c-69d9d5f4ad9b)

**Comment by GilimkhanovDenis** [comment]
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/221ba650-989a-4216-9303-35b52e163c6e)

Привет с попыткой создания подключения (ошибка закономерна - указанного ключа API не существует)

```
Sub Example()
    Dim DiadocAPI As Object
    Set DiadocAPI = CreateObject("Diadoc.DiadocClient")
    
    DiadocAPI.ServerUrl = "https://diadoc-api.kontur.ru:443"
    DiadocAPI.ApiClientId = "COM1C_VBA_Example"
    Dim dd_Connection As Object
    Set dd_Connection = DiadocAPI.CreateConnectionByLogin("foo", "bar")
End Sub
```
