### ISSUE TITLE
Аннулирование и отказ в подписании

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#93]
Добрый день.
Может ли Поставщик:
1) Повторно отправить документ на подпись (АВР/ТОРГ-12), если документ был аннулирован? Если да, как правильно это сделать?
2) Повторно отправить документ на подпись (АВР/ТОРГ-12), если был получен отказ в подписи? Если да, как правильно это сделать?

**Comment by geron4** [comment]
Отправленный документ вы уже не исправите, если он некорректный - его можно аннулировать с обоих Сторон. А потом заново отправить документ с таким же номером с корректными данными.

**Comment by denver069** [comment]
@prog22 вас удовлетворил ответ @geron4 ?

**Comment by prog22** [comment]
Да, спасибо.
