### ISSUE TITLE
Получение списка изменений статусов документов за период

### ISSUE THREAD

**Issue by alteris1508** [diadoc/diadocsdk-1c-docs#930]
коллеги, прошу подсказать метод API, которым можно получить список изменений статусов документов за определенный период дат.
можно ли применить DocumentsTask?
спасибо!

**Comment by MaximGlazunov** [comment]
Добрый день.

Пробовали Organization.GetDocumentEventList(*ПоследнееЗагруженноеСобытие*)?

**Comment by GilimkhanovDenis** [comment]
Всё так как сказал @MaximGlazunov - для получения изменений документов предназначен метод [GetDocumentEventList](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.GetDocumentEventList)

DocumentsTask может получить документы по фильтрам даты отправки или даты документа или конкретным статусам. Для поиска изменений статуса он вряд ли подходит

**Comment by alteris1508** [comment]
Коллеги,

 

Наш вопрос был именно про метод GetDocumentEventList <https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.GetDocumentEventList> :

 



 

 

Как получить EventID на конкретную дату (31.05.2023) для каждой подключенной организации?

 

Мы не хотим загружать события начиная с дня подключения к ДИАДОК.

 

С уважением, 

Пирмухамедов Рустам

 

ООО "Альтер-ИС" 

 <http://www.alter-is.ru/> www.alter-is.ru

**Comment by GilimkhanovDenis** [comment]
Возможно, вам поможет информация из https://github.com/diadoc/diadocsdk-1c-docs/issues/918 - можно попробовать найти документ по дате отправки и использовать его MessageId

В более явном виде никак. Предполагается, что интегратор вычитал уже существующие события и хранит у себя указатель на последнее загруженное событие (EventId)
