### ISSUE TITLE
Подписант по МЧД

### ISSUE THREAD

**Issue by MaximGlazunov** [diadoc/diadocsdk-1c-docs#932]
Добрый день.

Тестируем подпись документов через МЧД (на физ лицо).
Цепляем доверенность в объекте задания на отправку документов (объект, созданный методом CreatePackageSendTask2()).
В самих документах в объекте Signers заполняем только SignerReference.
После отправки в вэб-интерфейсе видим пометку, что в документе использована доверенность, но в xml должность подписанта указана, как "Начальник управления", которым и является доверенное лицо. Текст xml не отличается от того, если бы документ был подписан сертификатом организации.
Подскажите, пожалуйста, откуда подтягивается эта информация? Должно ли так происходить? Как на самом деле должен выглядеть в xml блок "Подписант"?
Сессию запускали и под сертификатом организации, и под сертификатом доверенного лица.
Версия компоненты COM x64 5.39.0.861. ID организации: 52c37243403c4354be3cb578fc056edf@diadoc.ru; ID тестового документа: 439e4676-edeb-4977-a2bb-397f7e5a89d1431d3069-56a3-4882-bc32-d513f43756d4 (сессия под сертификатом доверенного лица).
Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

При указании подписанта через SignerReference будут использоваться данные подписанта, запомненные в сервисе Диадок.  Получить их или изменить можно через объект [MyEmployee](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/MyEmployee.html), используя методы:

- [MyEmployee.GetExtendedSignerDetails](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/MyEmployee.html#MyEmployee.GetExtendedSignerDetails)`("UtdSeller")`
- [MyEmployee.CreateSetExtendedSignerDetailsTask](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/MyEmployee.html#MyEmployee.CreateSetExtendedSignerDetailsTask)`()`

**Comment by MaximGlazunov** [comment]
То есть, если я сейчас "запомню" данные физ лица, а потом мне нужно будет подписывать от лица сотрудника, то мне придется заново "запоминать"?

**Comment by GilimkhanovDenis** [comment]
Да

Либо использовать SignerDetails - там в явном виде можно указать все данные

**Comment by MaximGlazunov** [comment]
Большое спасибо.
