### ISSUE TITLE
Подписать и отправить документ

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#933]
Здравствуйте. Один сотрудник создает документ с помощью PackageSendTask2 с указанием флага DelaySend, чтобы другой сотрудник его подписал и отправил. Насколько я понял, с помощью PackageSendTask2  можно добавить в пакет новый документ, а как подписать и отправить ранее созданный с флагом DelaySend?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Используйте [PatchTask](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PatchTask.html).
Создаётся методом [Box.CreatePatchTask()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.CreatePatchTask)
