### ISSUE TITLE
МЧД и неформализованный документ

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#934]
Был создан неформализованный документ с помощью PackageSendTask2 с указанием флага DelaySend.
Далее пытаюсь добавить МЧД при подписании и отправке:
Document=Box.GetDocumentById(MessageId+EntityId);
PatchTask=Box.CreatePatchTask();
PatchTask.AddToPatch(Document,"Sign");
А вот дальше не совсем понятно.

**Comment by GilimkhanovDenis** [comment]
`PatchTask.AddToPatch(Document,"Sign");` вернул вам какой-то объект - его нужно заполнить и после этого выполнить `PatchTask.Send()`

**Comment by evgen421** [comment]
Это понятно, нужен пример заполнения.

**Comment by GilimkhanovDenis** [comment]
Исходя из того. что говорите об отправке неформализованного документа и предположения, что это не закрытый пакет, вам вернулась коллекция из одного элемента из [PatchItem](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PatchItem.html), у которого в поле PatchContent лежит объект [AcceptanceToSend](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/AcceptanceToSend.html)

И получается, что можно заполнить например так:
```
dd_ValueCollection = PatchTask.AddToPatch(Document,"Sign");
dd_PatchItem = dd_ValueCollection.GetItem(0);
dd_AcceptanceToSend = dd_PatchItem.PatchContent;
dd_POAToAttach = dd_AcceptanceToSend.PowerOfAttorneyToAttach;
dd_POAToAttach.UseDefault = True;
```

Про указание МЧД подробнее написано [здесь](https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_PowerOfAttorney.html)
Пример определения типа ответа можно посмотреть [здесь](https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_reply_document.html)

**Comment by evgen421** [comment]
Спасибо, сейчас попытаюсь реализовать

**Comment by evgen421** [comment]
при выполнении
dd_PatchItem = dd_ValueCollection.GetItem(0);
выдает ошибку:
ValueCollection.GetItem: Индекс выходит за диапазон коллекции

**Comment by GilimkhanovDenis** [comment]
Какой документ пытаетесь добавить в PatchTask ? Нужна ссылка или boxId, documentId

**Comment by evgen421** [comment]
Видимо документ в коллекцию не добавился: dd_PatchItem.count=0
Добавляю неформализованный документ

**Comment by GilimkhanovDenis** [comment]
Нужен  ещё boxId (идентфиикатор ящика)

**Comment by evgen421** [comment]
f9f8b47e-bc55-4960-9ca2-8b6908bfe9df

**Comment by GilimkhanovDenis** [comment]
Этот документ уже отправлен, поэтому для него невозможно сформировать подпись для отправки

насколько вижу, подписан через API

**Comment by evgen421** [comment]
Всё работает, спасибо.
