### ISSUE TITLE
Ошибка ID в СФ созданной по  API

### ISSUE THREAD

**Issue by aklexk** [diadoc/diadocsdk-1c-docs#935]
При создании документа счет фактура
	PackageSendTask = Organization.CreatePackageSendTask2();      
	PackageSendTask.CounterAgentId = Counteragent.Id;
        ...
	DocumentPackage = PackageSendTask.Send();  

При создании документа по контрагенту  роуминга Корус
a7bd134f116e4654ae0f8edd0876058b@diadoc.ru 
ИД: 2BK-5029069967-2286459

В созданном файле в диадоке   ИД ставится диадоковский,а не роуминговый 
т.е. 2BM-5029069967-2012052807491112970000000000000
а должен устанавливаться по ИД  2BK-5029069967-2286459
[Диадок COM/1C Addin SDK]  [5.44.0]

или он изменяется в момент отправки?
просьба пояснить

**Comment by aklexk** [comment]
нет комментариев?

**Comment by GilimkhanovDenis** [comment]
Добрый день

В зависимости от версии документа, в контенте может присутствовать или отсутствовать поле для указания идентификатора участника ЭДО получателя.
Если его нет или оно не заполнено, то он формируется по данным первого покупателя в коллекции покупателей.
Если в нём указаны ИНН-КПП, то по ним найдутся ящики с такими же ИНН-КПП в Диадок. В приоритете выберется ящик оператора Диадок. Если найдёно несколько роуминговых ящиков, то будет ошибка

Таким образом, если необходимо указать в контенте идентификтаоры роумингового ящика, необходимо либо заполнить специально предназначенное для этого поле (если оно есть), либо изменить заполнение покупателя

Похожие запросы: #717, #507

**Comment by aklexk** [comment]
Покупатель только 1 Роуминг Корус

(найдутся ящики с такими же ИНН-КПП ?????)
При создании документа заполняется PackageSendTask.CounterAgentId = Counteragent.Id;  - конкретный ящик

**Comment by GilimkhanovDenis** [comment]
`PackageSendTask.CounterAgentId` задаёт только ящик, куда будет отправлен документ. На контент не влияет

**Comment by GilimkhanovDenis** [comment]
Поиск по ИНН-КПП происходит по всем ящикам, а не только по тем, с кем настроена "дружба" - API позволяет отправлять документы в ящики, с которыми нет "дружбы"

**Comment by aklexk** [comment]
В апи нет функций для задания ИД. Т.о присвоение происходит в момент отправки

**Comment by GilimkhanovDenis** [comment]
ИД - идентификатор участника ЭДО ?
Если да, то всё верно - этот параметр у каждого ящика свой, присваивается каждому ящику в момент создания ящика. Изменять его в системе нельзя.

для версии `utd820_05_01_02_hyphen`  есть поле для указания этого идентификатора:
`UniversalTransferDocumentWithHyphens.RecipientFnsParticipantId = FnsParticipantId`
 или заполнить покупателя, например, с помощью OrganizationReference примерно так:
```
Buyer = UniversalTransferDocumentWithHyphens.Buyers.AddBuyer();
Buyer.OrganizationReference.BoxId = BoxID;
```
