### ISSUE TITLE
Потокобезопасность методов

### ISSUE THREAD

**Issue by RomanTatyanin** [diadoc/diadocsdk-1c-docs#936]
Здравствуйте !
Могу ли я использовать методы компоненты в отдельных потоках например эти:
IDocument.GetBase64Content
IBox.GetDocumentById

**Comment by GilimkhanovDenis** [comment]
Добрый день

Правильно понял, что интересует безопасность вызова, например `IDocument.GetBase64Content` для одного инстанса `IDocument` из разных потоков ?

**Comment by RomanTatyanin** [comment]
Нет, не для одного IDocument в нескольких потоках получить контент. А получить список документов из IBox.GetDocumentsTask как IValueCollection, и подянуть контент документов по этому списку запустив несколько потоков параллельно.

**Comment by GilimkhanovDenis** [comment]
С такими сценариями проблем не вижу

**Comment by RomanTatyanin** [comment]
Благодарю.
