### ISSUE TITLE
Добавление новой МЧД сотруднику администратором системы

### ISSUE THREAD

**Issue by CatAnd0** [diadoc/diadocsdk-1c-docs#937]
Здравствуйте

Версия компоненты: COM x86 5.44.0.907
Задача: Добавить администратором новую МЧД, выпущенную в ФНС, к сотруднику организации.

Для регистрации МЧД есть метод Box.RegisterPowerOfAttorneyById(). Этот метод, видимо, добавляет МЧД, выпущенную сторонним сервисом, в сервис Контур.Доверенность. 

Для добавления МЧД к произвольному сотруднику существует метод AdminTools.AddPowerOfAttorneyToEmployee(Employee, PowerOfAttorney).
Вторым аргументом принимается объект PowerOfAttorney.
Как можно получить данный объект (PowerOfAttorney) после регистрации новой МЧД в организации?

Или есть другие пути добавления новой МЧД сотруднику администратором системы, которые мы не заметили?

Попутный вопрос, как получить список всех доверенностей зарегистрированных в организации, в том числе не привязанных к сотрудникам?

**Comment by GilimkhanovDenis** [comment]
Добрый день

[RegisterPowerOfAttorneyById](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html?highlight=registerpowerofattorneybyid#Box.RegisterPowerOfAttorneyById) возвращает [AsyncResult](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/AsyncResult.html) с [PowerOfAttorneyRegistrationResult](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PowerOfAttorneyRegistrationResult.html) в качестве результата - PowerOfAttorney можно взять из него

В документации описание методов поправил

В целом, вы правильно нашли метод регистрации и привязки МЧД к пользователю. Добавлю лишь, что через [AdminTools](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/AdminTools.html) администратор может настраивать МЧД любых пользователей, а сам пользователь имеет аналогичную возможность, но только в отношении себя через [Box](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html).[MyEmployee](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/MyEmployee.html)

**Comment by CatAnd0** [comment]
Спасибо, будем пробовать
