### ISSUE TITLE
Ошибка при изменении статуса пакета документа (PatchTask).

### ISSUE THREAD

**Issue by tnstestemail** [diadoc/diadocsdk-1c-docs#938]
Доброго времени суток.
Используется DiadocCom компонента версии 5.45.
1. Первоначально отправляю пакет с документами (Invoice, ProformaInvoice, Nonfotmalized) с отложенной отправкой. Документы в Лк отображаются со статусами "Требуется подписать и отправить". 
    **oDocumentPackage = PackageSendTask2.SendAsync()**
3. Затем необходимо подписать.
   2.1 Создаю задание 
        **oPatchTask = box.CreatePatchTask()** 
   2.2 Добавляю пакет в задание и указываю действие = "Sign". 
        **oPatchTask.AddToPatch(oDocumentPackage, "Sign")**
   2.3 Отправляю патч 
        **oPatchTask.SendAsync()**
Ошибка: **один или несколько документов пакета имеют некорректные идентификаторы**.

Идентификаторы проверял в oDocumentPackage.Documents.GetItem(0).DocumentId верные.
Подскажите, куда "копать"? 
До обновления к 5.45 версии использовался метод CreateCustomDataPatchTask. Так вот с помощью этого метода и сейчас работает отправка и подпись неформализованных документов, а вот при отправке и подписи формализованных в составе пакета появляется **400 ошибка "LastName is required; FirstName is required"**. Ошибка возникает при отправке ProformaInvoice документа. Служба поддержки посоветовала использовать PatchTask, но что-то и с ним не получается.
Спасибо.

**Comment by GilimkhanovDenis** [comment]
Добрый день

1. [CreateCustomDataPatchTask](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html?highlight=createcustomdatapatchtask#DocumentBase.CreateCustomDataPatchTask) - создаёт объект, который никак не связан с подписанием. Как вы с помощью него что-то подписывали?

2. `oPatchTask.AddToPatch(oDocumentPackage, "Sign")` вернёт коллекцию из [PatchItem](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PatchItem.html)'ов. У части из них в поле PatchContent будет лежать [DelayedDocumentContentPatchToSend](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DelayedDocumentContentPatchToSend.html) - его нужно заполнить

**Comment by GilimkhanovDenis** [comment]
Судя по логам за последние 2 недели, ни сам Диадок, ни компонента ошибку `один или несколько документов пакета имеют некорректные идентификаторы` не возвращали

Вероятно, это какая-то проверка в самой интеграции

**Comment by tnstestemail** [comment]
Спасибо большое за помощь. Сейчас поищу описание ошибки (был уверен, что ошибка из Диадока) и заполню DelayedDocumentContentPatchToSend).

**Comment by GilimkhanovDenis** [comment]
Небольшое добавление:

В описании [PatchItem](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PatchItem.html) есть варианты что может лежать в поле PatchContent. Определить тип объекта можно с помощью [Reflector](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Reflector.html)'а - пример [здесь](https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_reply_document.html) в `Процедура ОбработатьReplySendTask(dd_ReplySendTask)`

[DelayedDocumentContentPatchToSend](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DelayedDocumentContentPatchToSend.html) нужен чтобы правильно заполнить блок `Подписант` и идентификаторы получателя в XML

**Comment by tnstestemail** [comment]
Создаю  задание
oSendTask = org.CreatePatchTask()
Добавляю все документы пакета в задание
`oPatchItems = oSendTask.AddToPatch(oDocumentPackage, "Sign");`
Для каждого документа в пакете в цикле
`oPatchItem = oPatchItems.GetItem(indItem);`
`oDelayedDocumentContentPatchToSend = oPatchItem.PatchContent;`
Если это **DelayedDocumentContentPatchToSend**, то создаю объект расширенной подписи для заполнения
`oExtendedSigner = oDelayedDocumentContentPatchToSend.AddExtendedSigner();`
Но для типа документа **ProformaInvoice** приходит ответ на вызов AddExtendedSigner(), что "Нет интерфейса".
Увидел в API в описании DelayedDocumentContentPatchToSend указано DraftContentPatchToSend.AddExtendedSigner(), думал это опечатка. Т.е. добавить подпись можно только в DraftContentPatchToSend?

**Comment by GilimkhanovDenis** [comment]
В документации опечатка - конечно, должно быть `DelayedDocumentContentPatchToSend.AddExtendedSigner()` в описании метода [DelayedDocumentContentPatchToSend](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DelayedDocumentContentPatchToSend.html)

Вероятно, ProformaInvoice не поддерживает заполнение подписанта через ExtendedSigner, и подписант заполняется через DelayedDocumentContentPatchToSend.Signer или DelayedDocumentContentPatchToSend.DynamicSigners

**Comment by tnstestemail** [comment]
В описании [AsyncResult](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/AsyncResult.html) в дополнительной информации указано, что если IsCompleted == True, то это ошибка. Так и есть?

**Comment by GilimkhanovDenis** [comment]
В документации написано, что если ошибка, то  `IsCompleted == True`. В обратную сторону если  `IsCompleted == True`, то значит, что операция завершена. завершиться она может ошибкой или успехом

**Comment by GilimkhanovDenis** [comment]
Да, необходимо дождаться завершения операции (если её результат вам важен), периодически проверяя флаг **IsCompleted**

**Comment by tnstestemail** [comment]
Спасибо!
