### ISSUE TITLE
Не получается добавить МЧД для исходящих документов

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#939]
Отправляем документы из 1С 7.7 (собственное интеграционное решение) с помощью вашей компоненты. Переходим сейчас на подпись сертификатом физического лица с МЧД. В настройках пользователя в web-интерфейсе МЧД по умолчанию указана.
Документы отправляются нормально и подписываются нужным сертификатом. Но МЧД к документу не прикладывается.
Попытался директивно указать МЧД с помощью PatchTask, но на методе `PatchTask.AddToPatch(Документ, "Receipts");` выпадает в ошибку:
PatchTask.AddToPatch: Действие не реализовано

Как правильно приложить МЧД к исходящим документам?

**Comment by dorexpro** [comment]
Вроде разобрался, что в методе PatchTask.AddToPatch для исходящих документов надо передавать не "Receipts", а "Sign". Тогда возвращает какую-то коллекцию, если документ в черновиках. Если же передавать пакет документов, возвращенных методом PackageSendTask2.Send(), то возвращается пустая коллекция, т.к. документы уже подписаны и отправлены без МЧД.
Вопрос все тот же: как приложить МЧД до отправки документа?

**Comment by dorexpro** [comment]
Добавил перед отправкой пакета:
`PackageSendTask2.PowerOfAttorneyToAttach.UseDefault = 1;`
Посмотрим как завтра утром документы уйдут в автоматическом режиме.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Если речь про подписание и отправку черновика, то `AddToPatch(Документ, "Sign")` вернёт коллекцию из [PatchItem](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PatchItem.html)'ов. В поле **PatchContent** будет  лежать [DraftContentPatchToSend](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DraftContentPatchToSend.html) или [DraftSignatureToSend](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DraftSignatureToSend.html) - в них и нужно заполнить МЧД, чтобы она прикрепилась при отправке документа, созданного из черновика

**Comment by dorexpro** [comment]
Нет, речь как раз про отправку документов минуя папку черновиков.

**Comment by GilimkhanovDenis** [comment]
Тогда всё верно
`PackageSendTask2.PowerOfAttorneyToAttach.UseDefault = 1;`  прикрепит ко всем отправляемым документам МЧД по умолчанию, заданную у авторизованного пользователя

**Comment by dorexpro** [comment]
А зачем нужен отдельный флаг? Мы тут в отделе так и не поняли его смысл. Если заполнена в документе МЧД, то слать ее. Если не заполнено, то МЧД по умолчанию. Не заполнено по умолчанию, слать без МЧД. Какой такой сценарий может быть, чтобы и МЧД по умолчанию настроена, и документ с подписью этого пользователя надо слать без МЧД?

**Comment by GilimkhanovDenis** [comment]
`PackageSendTask2` не знает ничего про контенты документов. DynamicContent строится в рантайме и где конкретно для каждого типа документа лежат данные об МЧД и как они называются невозможно понять на этапе компиляции. Поэтому не работает `Если заполнена в документе МЧД, то слать ее`

Возможен вариант, когда по-умолчанию настроена не та МЧД, которую хочется использовать в конкретной отправке. Ну и так ближе к [REST API](https://developer.kontur.ru/docs/diadoc-api/proto/PowerOfAttorneyToPost.html)

**Comment by dorexpro** [comment]
Ничего не понял. Как это "невозможно понять на этапе компиляции"? У вас же есть PackageSendTask2.PowerOfAttorneyToAttach, где либо указано, что надо брать по умолчанию, либо заполнены параметры конкретной МЧД. Так зачем нужен отдельный флаг, если в его качестве можно просто брать результат проверки установки параметров конкретной МЧД? У вас же флаг PowerOfAttorneyToAttach.UseDefault где-то проверяется, чтобы добавить МЧД по умолчанию либо ту, которая указана. Почему в этом месте не проверять немного другой критерий?
По-моему, это излишнее усложнение кода, которое ведет к лишним ошибкам и нелогичности схемы в целом.

**Comment by GilimkhanovDenis** [comment]
Если правильно вас понял, то утверждается, что флаг `UseDefault` - лишний. В целом согласен.
Думаю, от флага `UseDefault`  вполне можно будет отказаться после 1 сентября, когда МЧД станет обязательна. Сейчас ещё остались пользователи, у которых МЧД не настроена. Диадок в случае отсутствия МЧД по умолчанию, но переданном флаге про использование дефолтной МЧД ошибку в запросе отдаёт.
