### ISSUE TITLE
Ошибка при отправке УКД (COM-компонента для встраивания в произвольные системы- версия 5.16.1.191)

### ISSUE THREAD

**Issue by geron4** [diadoc/diadocsdk-1c-docs#94]
Ошибка при отправке УКД (COM-компонента для встраивания в произвольные системы- версия 5.16.1.191).

Документ УКД отправляется в пакете, при вызове метода PackageSendTask.Send выходит ошибка:

Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: Info.Invoices is required

Судя по тексту ошибки, вероятно, массив Invoices не заполнен (имеет 0 элементов), но в моем случае он заполнен, имеет 1 элемент и данные этого элемента заполнены. Почему возникает ошибка - непонятно.

Подозреваю, что это ошибка в компоненте, прошу проверить/уточнить.
А также указать описание этой ошибки, что она означает?

**Comment by denver069** [comment]
Ошибку воспроизвести удалось, постараемся в ближайшее время выпустить исправление.
Для получения информации о выходе новой версии внешней компоненты, вы можете подписаться на ленту новостей [RSS](http://diadocsdk-1c.readthedocs.io/ru/latest/index.rss)
