### ISSUE TITLE
DiadocCom.CreateConnectionByCertificate2: WIN32[0x000010DD]WinHttpQueryAuthSchemes The operation identifier is not valid

### ISSUE THREAD

**Issue by ElenaBurnasheva** [diadoc/diadocsdk-1c-docs#941]
Здравствуйте. 
Версия компоненты DiadocCom_5_45_0_912_x64.dll. 
Пытаюсь подключится через CreateConnectionByCertificate2 

	Certificates = ДиадокАпи.GetPersonalCertificates();  //находит 1 сертификат
	СертификатДляПодключения = Certificates.GetItem(0);
	ДиадокСоединение = ДиадокАПИ.CreateConnectionByCertificate2(СертификатДляПодключения);	

Возникает ошибка 	
Ошибка при вызове метода контекста (CreateConnectionByCertificate2): Произошла исключительная ситуация (DiadocCom.CreateConnectionByCertificate2): WIN32[0x000010DD]WinHttpQueryAuthSchemes The operation identifier is not valid.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Как заполнен объект ДиадокАпи ?

**Comment by GilimkhanovDenis** [comment]
Вероятно, что подключение происходит через прокси-сервер. При попытке отправить запрос, прокси-сервер ответил, что пользователь не авторизован и прислал неизвестную [схему авторизации](https://learn.microsoft.com/en-us/windows/win32/api/winhttp/nf-winhttp-winhttpqueryauthschemes)

я бы предложил [собрать логи WinHTTP](https://learn.microsoft.com/en-us/windows/win32/wsdapi/capturing-winhttp-logs). В них могут быть чувствительные данные, поэтому лучше их передать или через техподдержку, или выложить куда-нибудь с защитой паролем, а пароль передать через техподдержку

**Comment by ElenaBurnasheva** [comment]
Да, подключение через прокси сервер, но ДиадокАпи.GetPersonalCertificates() возвращает список сертификатов. 
Получается получить сертификаты он может, а подключится по найденному сертификату нет?

**Comment by GilimkhanovDenis** [comment]
ДиадокАпи.GetPersonalCertificates() не взаимодействует с WinHTTP - он только получает список сертификатов на машине

**Comment by ElenaBurnasheva** [comment]
Администратор пришел с отпуска и все настроил.
