### ISSUE TITLE
Отправка "На подпись" CreateResolutionRequestTask()

### ISSUE THREAD

**Issue by blender5** [diadoc/diadocsdk-1c-docs#942]
НоваяРезолюцияКДокументу = ДокументАпи.CreateResolutionRequestTask();
		
НоваяРезолюцияКДокументу.ResolutionRequestType		= "SignatureRequest";

НоваяРезолюцияКДокументу.TargetDepartmentId	= Неопределено;
НоваяРезолюцияКДокументу.TargetUserId			= Неопределено;

НоваяРезолюцияКДокументу.Send();

Получаю ошибку "Произошла исключительная ситуация (ResolutionRequestTask.Send): ##100[Ошибка сервера Диадок]code:400, HTTP error: MessagePatchToPost.Resolutions[0]: Не задан получатель запроса на согласование"

Подразделение существует только "головное" отправить хочу всем с правом подписи.

При этом если данную операцию осуществляю через веб интерфейс. То в резолюциях при проверке COMобъекта значится
TargetDepartment	= Неопределено
ToEmployee		= Неопределено

версия компоненты COM x64 5.39.0.861

**Comment by GilimkhanovDenis** [comment]
Добрый день

Заполните [идентификатор головного подразделения](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Department.html) - `00000000-0000-0000-0000-000000000000`

**Comment by blender5** [comment]
Работает, спасибо.
Но было не очевидно, где вообще взять код подразделения.
