### ISSUE TITLE
Вопрос по ТТН (Титул 3, Грузополучатель-Грузоперевозчик)

### ISSUE THREAD

**Issue by dimok22prog1** [diadoc/diadocsdk-1c-docs#944]
Здравствуйте.
Используем компоненту для произвольных систем.

Из тестового ящика Грузополучателя (7f648ced47184958884e02dac0220d4a@diadoc.ru) формируем 3 Титул ТТН Грузоперевозчику (572090e7b76148b3b8cdd62989534ddf@diadoc.ru):

1) Программно (пример документа с идентификатором b5ecff8c-bb74-4b22-9686-8b20c2ba3bbe72dca7db-ba45-4a9d-82bc-800ec2bef035):

DocumentToSend = SendTask.AddDocumentFromFile(“LogisticsWaybill”, "delivery", "kl_trn_mt_05_01", [путь к выгруженному файлу третьего титула ТТН установленного формата)]);

2) Вручную из web-интерфейса Контур.Логистика (пример документа с идентификатором ad9d80b1-f975-4659-bb7a-cdaf1c6ad34da8029001-71c7-4455-b94a-12226be13b03).

Различий в атрибутах электронных документов через компоненту не нашли, однако для документа, сформированного вручную в ящике Диадок отображается плашка:
![Pic2](https://github.com/diadoc/diadocsdk-1c-docs/assets/100696615/04de862d-926d-449f-a5e7-f702f479f45f)

Предполагаем, что при формировании Титула 3 что-то не указали (в титуле или атрибутах SendTask), что не позволило связать в Контур.Логистика Титул 1, Титул 2, Титул 3.

Подскажите, пожалуйста, так ли это?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Пока из отличий вижу только то, что в документе, отправленном через Контур.Логистика указана коллекция CustomData.
**ключ**: `kl-id`
**значение**: какой-то guid

Попробуйте указать эту информацию, используя [DocumentBase.CreateCustomDataPatchTask()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html?highlight=CreateCustomDataPatchTask#DocumentBase.CreateCustomDataPatchTask)

**Comment by dimok22prog1** [comment]
Проставили для b5ecff8c-bb74-4b22-9686-8b20c2ba3bbe72dca7db-ba45-4a9d-82bc-800ec2bef035 (Грузополучатель-Грузоперевозчик) CustomData:

- kl-id: 948c4109-6088-4625-a82d-e39f03984419
- mt-id: d98f56c2-cca0-4039-a363-8c9dcd1db452

Плашка [ГИС ЭПД] не появилась.
При этом во всех документах цепочки CustomData одинакова:

-  Грузоотправитель – Грузоперевозчик: 77e0f36f-e722-4ca0-9ed1-40c00be41f599ddec506-2bcc-4516-a515-ac7d557e0f6a
-  Грузоотправитель – Грузополучатель: 2e2446cb-3d82-4335-babf-7210c62a674a3a766505-0352-4735-91b2-a3bcfb5891eb
-  Грузоперевозчик – Грузополучатель: 804db535-9fe2-4714-804d-f5c54e088270afd9e3e9-e39f-4a96-ae1f-4c71c3a90dce

Попробуем адресовать вопрос Контур.Логистике...
