### ISSUE TITLE
Подразделение контрагента

### ISSUE THREAD

**Issue by dorexpro** [diadoc/diadocsdk-1c-docs#945]
В списке контрагентов в веб-интерфейсе назначается группа, к которой относится контрагент. Но в типе Counteragent я не нашел соответствующего поля.
Как узнать с помощью компоненты к какому нашему подразделению отнесен контрагент?

**Comment by GilimkhanovDenis** [comment]
Добрый день

API (ни компоненты, ни REST) не предоставляет возможности работы с группами контрагентов - их просмотр и редактирование доступны только в веб
