### ISSUE TITLE
Как обработать уровень доступа к документам EmployeePermissions.SelectedDepartments

### ISSUE THREAD

**Issue by Xolto** [diadoc/diadocsdk-1c-docs#947]
ЗДравствуйте, в веб версии у пользователя настроен доступ к документам департаментов "головной"  и "бухгалтерия", при обработке через Addin, в коллекции VisibleDepartments, только "бухгалтерия"

**Comment by GilimkhanovDenis** [comment]
Исправлено в [5.47.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_47_0.html)

Для просмотра видимых подразделений, включая головное, нужно будет обращаться к полю VisibleDapartments2
