### ISSUE TITLE
Проблемы с функцией получения GetFileContent, начиная с версии 5.42.2.898 DiadocCom

### ISSUE THREAD

**Issue by WoockY1** [diadoc/diadocsdk-1c-docs#948]
Добрый день,

Мы 2 года не обновляли компоненту, сейчас обновили в связи с использованием МЧД. Поймали следующий момент:
1) Получаем GetDocumentEventList
2) Оттуда событие EventsList.GetItem(i)
3) Имеем событие как com-объект, например такого плана:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/kgdun/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/kgdun/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Событие | COMОбъект
-- | --
CounteragentId | "c19a62eb29d1436793a4afba409263b8@diadoc.ru"
DocumentDirection | "Outbound"
DocumentId | "0f1a07e6-77aa-41a1-9a9e-86114ddf83145a8c7b6a-875c-4742-836b-bd08f7c4a493"
DocumentType | "UniversalTransferDocument"
EventType | "Accept"
Timestamp | 30.08.2023 22:23:37
eventId | "e2f25a1a-5704-43fc-87cb-36f646fb41a2"

</body>

</html>

Это событие возникает при поступлении Титула покупателя на УПД. Соответственно далее мы пытаемся достать файл самого Титула и потом Файл подписи:

ИмяВременногоФайлаТикета = ПолучитьИмяВременногоФайла("") + ".xml"; 
**РеальноеИмяФайлаТикета** = Событие.**GetFileContent**(ИмяВременногоФайлаТикета);
Событие.GetSignatureContent(ПолноеИмяФайлаПодписи)

РеальноИмяФайлаТикета возвращается:
**ON_NSCHFDOPPOK_2BM-7802707397-780201001-202012240915539374093_2BM-7814148471-2012052807203732341080000000000_20230830_0E0B6926-F602-1EDE-91ED-4834E51A87EB.xml**
Это соответствует ожидаемому, а вот содержанием файла является исходный  файл УПД, а не файл Титула Покупателя
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/75391935/c6023c97-5415-4fc0-a2f3-eac0b342ab9f)

И такое поведение для любого типа события:
DP_PDPOL, DP_PDOTPR, ON_NSCHFDOPPOK

Были проверены различные версии компоненты, до версии 5.42.2.898 все работало ожидаемо. Начиная с этой версии, вместо файлов-тикетов внутри  - содержание файла изначальной УПД. Соответственно при проверке подписи пары файл + подпись валится ошибка и весь документооборот ложится.

Логин для доступа используем freshmarket00@bk.ru

С уважением,
Николай

**Comment by GilimkhanovDenis** [comment]
Добрый день.

Исправлено в [5.46.1](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)
