### ISSUE TITLE
Подскажите пожалуйста как подписать документ "ReconciliationAct" через SDK

### ISSUE THREAD

**Issue by MarkRozerford** [diadoc/diadocsdk-1c-docs#950]
После выполнения команды "Document = Organization.GetDocumentById(ИдентификаторДокумента)"
Получаем данные документа, где Document.Version = "reconciliationact405_05_01_01"
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/60421917/daf0a63e-4b37-40c3-84a5-f1c0ac8273ed)

После вызываю команду 
ReplySendTask = Document.CreateReplySendTask2("AcceptDocument");

Однако непонятно, что конкретно требуется заполнить для выполнения утверждения
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/60421917/90e9b096-679b-4ca0-bd8c-be82a58a335c)

В документации по данному виду документа ничего не нашел.
Заранее спасибо!

**Comment by GilimkhanovDenis** [comment]
Добрый день

Пример подписания документа есть [здесь](https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_reply_document.html)

Контент ответного титула заполняется через [DynamicContent](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html) - на странице документации указано какими способами можно понять его структуру (в примере выше из документации есть заполнение контента второго титула УПД)

**Comment by MarkRozerford** [comment]
А поле "SignOfDisagreement" какое значение может содержать?
Оно причем является обязательным, судя по ошибке.

@SignOfDisagreement: The 'SignOfDisagreement' attribute is invalid - The value '' is invalid according to its datatype 'String' - The actual length is not equal to the specified length.

**Comment by GilimkhanovDenis** [comment]
Список возможных значений есть в UserDataXSD
[ReconciliationAct default reconciliationact405_05_01_01 Buyer.txt](https://github.com/diadoc/diadocsdk-1c-docs/files/12575086/ReconciliationAct.default.reconciliationact405_05_01_01.Buyer.txt)
На всякий случай приложу и ссылку на [сам формат](https://normativ.kontur.ru/document?moduleId=1&documentId=425482)

**Comment by MarkRozerford** [comment]
Решилось, спасибо!

**Comment by Vanoha12** [comment]
@GilimkhanovDenis Подскажите пожалуйста, как определить, какой ReconciliationAct подписывается как есть, а на какой нужно создавать Титул получателя?

**Comment by GilimkhanovDenis** [comment]
@Vanoha12 Можно по значению поля [DocumentBase](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html).WorkflowId документа, либо, чтобы не привязываться к конкретным значениям этого поля - по типу ответа [PatchTask.AddToPatch()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PatchTask.html#PatchTask.AddToPatch) (см. https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PatchItem.html и https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_reply_document.html)

**Comment by Vanoha12** [comment]
@GilimkhanovDenis Спасибо
