### ISSUE TITLE
Template и SDK

### ISSUE THREAD

**Issue by dimok22prog1** [diadoc/diadocsdk-1c-docs#952]
Добрый день. Подскажите, пожалуйста, на данный момент существует/планируется возможность работы с входящими шаблонами (получение информации из них, формирование документов по ним и т.п.) через компоненту?
_______________________________________              
Добрый день.
Аналогичный вопрос был в https://github.com/diadoc/diadocsdk-1c-docs/issues/371.
Ответ пока тот же: компонента не умеет получать входящие шаблоны. Если данная функциональность необходима, просьба обратиться к менеджеру, ведущему вашу организацию

_Originally posted by @GilimkhanovDenis in https://github.com/diadoc/diadocsdk-1c-docs/issues/435#issuecomment-584134459_

**Comment by GilimkhanovDenis** [comment]
Добрый день

Функциональность всё ещё не появилась
