### ISSUE TITLE
Документооборот для  Nonformalized

### ISSUE THREAD

**Issue by ElenaBurnasheva** [diadoc/diadocsdk-1c-docs#954]
Здравствуйте.
Отправляю пакет документов в котором один документ упд, а второй - типа Nonformalized. Мне нужно, чтобы для второго документа был запущен двусторонний документооборот.  Насколько я понимаю, мне нужно в поле WorkflowId проставить номер документооборота. Как можно узнать, какие вообще виды документооборота доступны для этого типа документа?
Пыталась получить с помощью Organization.GetWorkflowsSettings() - пишет, что процедура или функция с таким именем не определена.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Под двусторонним имеется ввиду, что получатель обязан подписать документ? Если да, то у [DocumentToSend](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentToSend.html) есть флаг NeedRecipientSignature

Таблица с идентификаторами документооборота есть [здесь](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentWorkflow.html)

Доступные виды докумнетооборота для каждого типа докумнетов указаны в ответе [Organization.GetDocumentTypes()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.GetDocumentTypes)

**Comment by ElenaBurnasheva** [comment]
Спасибо. Все получилось.
