### ISSUE TITLE
Отслеживание статуса отправленного документа.

### ISSUE THREAD

**Issue by crashsip** [diadoc/diadocsdk-1c-docs#956]
Добрый день.
Столкнулись с небольшой проблемой, не нашел в документации, как решить. Может слеп, не исключаю - просьба подопнуть в нужном направлении, если уже обсуждался этот момент или есть в документации.

Подключаем 1С к ДИАДОК через библиотеку "AddIn".
В ДИАДОК документы формируются сначала в черновиках. В момент формирования документов в 1С сохраняется DocumentID (который, насколько я понимаю, является склейкой MessageID и EntityId).
После этого ответственный сотрудник компании заходит в ДИАДОК, проверяет отправляемые документы, при необходимости вносит изменения (добавляет документы), подписывает их ЭЦП и отправляет контрагенту. Документы из черновиков "перемещаются" в Исходящие.
Далее хотим сделать так, чтобы 1С с некоторой периодичностью подключалась к ДИАДОК и проверяла статус документов.
Но, как выяснил, после "перемещения" в Исходящие, у пакета меняется MessageID. 
Соответственно первая половина DocumentID изменяется.

При поиске документа методом Box.GetDocumentById(DocumentId, WithExternalId=False)  мы находим документ, который был изначально помещен в черновик. Но у этого документа свойство IsDeleted = True.
И возникает ситуация, когда мы не понимаем, был ли этот документ просто удален из черновиков, или же был отправлен.

Поиск по части ID (передать EntityId в GetDocumentById) не работает.
Подскажите, как можно следить за статусом документа? Или как зная MessageID и EntityId и еще какие-либо свойства, оптимально находить документ и получать его статус?  Отправка и подписание из черновиков происходят в Web-интерфейсе, 1С про эти события ничего не знает. Получать список всех документов за период (а не подписывают документы месяцами) и перебирать их сравнивая со списком из 1С - так себе затея по производительности, если честно...

**Comment by GilimkhanovDenis** [comment]
Добрый день

Вероятно, вам может помочь [Box.GetDocumentEventList([AfterEventId])](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.GetDocumentEventList) - возвращает события по документам-нечерновикам

Другого способа получить MessageId документа, созданного из черновика, зная черновик, сейчас нет

**Comment by crashsip** [comment]
> Вероятно, вам может помочь [Box.GetDocumentEventList([AfterEventId])]
> 
> Другого способа получить MessageId документа, созданного из черновика, зная черновик, сейчас нет


Понял. Тогда, пожалуй, обращение можно закрывать.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Добавили информацию о созданных и черновика документах в релизе [5.50.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.50.0) ([ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html))

**Comment by crashsip** [comment]
> Добрый день
> 
> Добавили информацию о созданных и черновика документах в релизе [5.50.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.50.0) ([ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html))


Добрый день.
Добрался снова до этого вопроса.
Может быть есть ссылки какие-то на документацию, где и как получить DraftInfo?
или в какой-нибудь ветке здесь может быть разбирали?

Как пример документа в пакете 
https://diadoc.kontur.ru/24071535-0f13-46dc-b228-f6f1ed3df1d5/Document/Show?letterId=260ef80f-2bdc-4f28-9e8a-78d197542929&documentId=2511b9ea-62e6-48f1-8b8a-f854280af0fb
Это уже отправленный.

в черновиках был вот такой адрес:
https://diadoc.kontur.ru/24071535-0f13-46dc-b228-f6f1ed3df1d5/Document/Show?letterId=2e047541-3b71-47a0-8ea8-56222a0459d5&documentId=2511b9ea-62e6-48f1-8b8a-f854280af0fb

т.е. у меня был ID этого документа - 2e047541-3b71-47a0-8ea8-56222a0459d52511b9ea-62e6-48f1-8b8a-f854280af0fb
зная запрашиваю статус, получаю "OutboundWaitingForSenderSignature"
и статус не меняет при подписании и отправке из черновика, ответ от ДИАДОК приходит, хотя в черновиках документа уже нет.
у документа в черновиках свойства DraftInfo нет. Как использовать - не разобрался. Помогите, пожалуйста.
версия dll - Diadoc_5_51_2_962_x64.dll

**Comment by GilimkhanovDenis** [comment]
Добрый день

DraftInfo - это поле в DocumentBase. Для указанного черновика:

![image](https://github.com/user-attachments/assets/4acc7466-5400-4282-a596-4fc616586388)

**Comment by GilimkhanovDenis** [comment]
Если поля нет, то скорее всего подключена старая компонента

**Comment by crashsip** [comment]
> Если поля нет, то скорее всего подключена старая компонента

использовалась Diadoc_5_51_2_962_x64.dll
с ней не видел поля DraftInfo

обновил до Diadoc_5_52_4_989_x64.dll (на клиенте и на сервер. на сервере обязательно после перерегистрации DLL перезапустить процесс rphost!)
после этого поле увидел. Спасибо!
