### ISSUE TITLE
Поддержка многопоточности MTA

### ISSUE THREAD

**Issue by demetrius2003** [diadoc/diadocsdk-1c-docs#957]
Доброго дня!
У Вас начиная с версии 5.17.0 заявлена поддержка многопоточности. Хотелось бы увидеть пример рассылки документов в несколько потоков. Объёмы растут. Отправка уже занимает 9 часов и более!

**Comment by GilimkhanovDenis** [comment]
Добрый день

Уверены, что вас интересует именно MTA, а не асинхронная отправка с помощью [PackageSendTask2.SendAsync()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html#PackageSendTask2.SendAsync) ?

**Comment by demetrius2003** [comment]
Абсолютно без разницы. Главное, чтоб этот вариант дал мне возможность с одного рабочего места отправить очень много документов быстрее, чем за 9 часов!

**Comment by demetrius2003** [comment]
Сейчас используется CreatePackageSendTask2.Send()

**Comment by demetrius2003** [comment]
И чем мне поможет асинхронная выгрузка? Мне нужно выгрузить массив неформализованных документов объёмом несколько гигабайт. В один поток! Какая разница какой он будет?

**Comment by GilimkhanovDenis** [comment]
Если выгружаете несколько гигабайт, то это в любом случае несколько отправок. Если используете синхронный метод, то выглядеть это будет так:
```
CreatePackageSendTask2.Send() // отправляем 1ю пачку документов. Пока не отправится, не можем отправить следующую пачку
CreatePackageSendTask2.Send() // отправляем 2ю пачку документов. Пока не отправится, не можем отправить 
...
CreatePackageSendTask2.Send() // отправляем Nю пачку документов. Пока не отправится, не можем отправить 
```

Если асинхронный вариант, то
```
CreatePackageSendTask2.SendAsync() // отправляем 1ю пачку документов
CreatePackageSendTask2.SendAsync() // отправляем 2ю пачку документов
...
CreatePackageSendTask2.SendAsync() // отправляем Nю пачку документов
```
SendAsync() сам создаст отдельный поток и вызов метода завершится практически сразу. Результат метод AsyncResult нужно куда-то сохранить, чтобы через какое-то время его опросить и получить результат отправки

Так у вас может одновременно отправляться несколько пачек документов

**Comment by GilimkhanovDenis** [comment]
MTA - это про то, что к COM-объектам можно обращаться из многопоточной среды и COM'у не нужно самому синхронизировать наши объекты

**Comment by demetrius2003** [comment]
Проблема при асинхронном варианте может даже усугубиться. При нынешнем варианте рассылки пользователи покорно ждут завершения отправки. А то, что мы асинхронно что-то куда-то вытолкнули чуда не произведёт. Где-то по прежнему будут качаться гигабайты. Для пользователей же будет это казаться как завершение задачи. Они начнут закрывать рабочие места, выключать ноутбуки. У СБИСа такая история. Выдал 1000 заданий плагину. И думаешь что всё ок. Но это не так. И вот мне и нужно сделать разделение массива, скажем 6000 документов, на несколько порций. И иметь возможность эти порции отправить одновременно. В несколько потоков. Сейчас если в 1С это просимулировать и сделать несколько кучек, то нормально будет отправляться только первая, все последующие экземпляры 1с попытавшиеся создать COM соединение и отправляющие туда что-либо ломают вообще всю отправку. Поэтому мне и показалось, что MTA это решение проблемы.

**Comment by GilimkhanovDenis** [comment]
Для вашего сценария как раз и есть асинхронные отправки

Как отобразить пользователю, что все его отправки завершились - задача интеграции (так же как и логика разделения 6000 документов по пакетам).
У AsyncResult'а есть поле **IsCompleted** на которое можете ориентироваться чтобы понять, что отдельная отправка завершилась

Не очень понятно что у вас ломается в отправке. Какая ошибка?

**Comment by demetrius2003** [comment]
Ошибку к сожалению не сохранили. Вы советуете на асинхронку переползти? Или попробовать как-нибудь хитро создать несколько экземпляров ComОбъект("Diadoc.DiadocClient")?

**Comment by GilimkhanovDenis** [comment]
Рекомендую асинхронную отправку

количество экземпляров корневого объекта - как вам удобно.
Если отправку отправляют разные пользователи, то объекты подключения могут быть созданы как из одного корневого объекта (тогда его нужно как-то расшарить между пользователями), так и из созданных индивидуально для каждого пользователя.

Алгоритм для одного пользователя примерно такой:
Пользователь создаёт асинхронные отправки сколько ему нужно. AsyncResult'ы помещаете в какую-то коллекцию.
Как-то понимаете, что пользователь сформировал все отправки, которые ему нужны, и начинаете опрашивать коллекцию с сохранёнными AsyncResult'ами: если асинхронная операция завершилась, удаляете её из коллекции. И так делаете, пока коллекция не опустеет

**Comment by demetrius2003** [comment]
Огромное спасибо!!! Буду пробовать.
