### ISSUE TITLE
Не заполняются ИНН/КПП продавца и покупателя при отправке УПД

### ISSUE THREAD

**Issue by heratei** [diadoc/diadocsdk-1c-docs#958]
Отправка формируется методом CreatePackageSendTask2. Заполнение происходит через заполнение представления контента 

DocumentToSend = SendTask.AddDocument("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01");

Заполнение ИНН/КПП покупателя:
Покупатель	= DocumentToSend.Content.UniversalTransferDocument.Buyers.ADDBuyer();
Покупатель_Детализация	= Покупатель.OrganizationDetails;
Покупатель_Детализация.Inn		= Ссылка.Контрагент.ИНН;
Покупатель_Детализация.Kpp		= Ссылка.Контрагент.КПП;

Заполнение ИНН/КПП продавца:
Продавец	=  DocumentToSend.Content.UniversalTransferDocument.Sellers.ADDSeller();
Продавец_Детализация	= Продавец.OrganizationDetails;
Продавец_Детализация.Inn		= Ссылка.Организация.ИНН;
Продавец_Детализация.Kpp		= Ссылка.Организация.КПП;

В итоге в отправленном документе в веб-интерфейсе пустые ИНН и КПП покупателя и продавца. Подскажите, куда копать?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Кроме ИНН и КПП какие данные заполняете?

**Comment by GilimkhanovDenis** [comment]
И можете ещё пример такого документа дать?

**Comment by heratei** [comment]
![Снимок1](https://github.com/diadoc/diadocsdk-1c-docs/assets/149143951/617888ce-8d61-4f52-8abd-a0fbaad8f37f)

адреса и наименования юрлиц заполняются нормально. Как и табличная часть с подвалом. Проблема только в ИНН/КПП

**Comment by heratei** [comment]
Заполнение адреса отрабатывает нормально:

РусАдрес	= Продавец_Детализация.Address.RussianAddress;
		
		РусАдрес.Apartment	= ЮрАдресОрганизации.Квартира;
		РусАдрес.Block		= ЮрАдресОрганизации.Корпус;
		РусАдрес.Building	= ЮрАдресОрганизации.Дом;
		РусАдрес.City		= ?(ЗначениеЗаполнено(ЮрАдресОрганизации.Город), ЮрАдресОрганизации.Город, ЮрАдресОрганизации.НаселенныйПункт);
		//Locality
		РусАдрес.Region		= ЮрАдресОрганизации.Область;
		Если СтрНайти(ВРег(ЮрАдресОрганизации.Область), "ОБЛАСТЬ") = 0 Тогда
			ПозОбл	= СтрНайти(ВРег(ЮрАдресОрганизации.Область), "ОБЛ");
			Если ПозОбл > 0 Тогда
				РусАдрес.Region		= Лев(ЮрАдресОрганизации.Область, ПозОбл - 1) + "область";
			КонецЕсли;
		КонецЕсли;
		РусАдрес.Street		= ЮрАдресОрганизации.Улица;
		//Territory
		РусАдрес.ZipCode	= ЮрАдресОрганизации.Индекс;

**Comment by GilimkhanovDenis** [comment]
Можете дать ссылку на этот документ?

**Comment by heratei** [comment]
Прикладываю xml, выгруженный с веб-интерфейса
[ON_NSCHFDOPPR_2BM-ИзмененыНаименования.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/13186751/ON_NSCHFDOPPR_2BM-.zip)
![Снимок2](https://github.com/diadoc/diadocsdk-1c-docs/assets/149143951/26992bbb-a937-448a-8dd0-959b9f5a5fd5)

**Comment by GilimkhanovDenis** [comment]
Со ссылкой было бы, конечно, легче.
Видно. что заполняется тэг `СвИнНеУч`
По текущим данным могу только предположения строить.

Предположение такое:
По ИНН-КПП Диадок попытался найти ящик (чтобы проставить идентификаторы получателя/отправителя). Нашёл его. У ящика задан признак, что это иностранная организация. Исходя из этого заполняет тэг [СвИнНеУч](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=6389294) - в нём не может быть ИНН/КПП

**Comment by heratei** [comment]
Ларчик просто открывался. В поле OrgType необходимо передавать значение = "1". Денис, благодарю за наводку
