### ISSUE TITLE
Вопрос по API

### ISSUE THREAD

**Issue by BakinIlya** [diadoc/diadocsdk-1c-docs#96]
Добрый день.

В макете конфигурации, для работы клиентской части,  у нас  загружена компонента AddInDiadocAPI.dll Версия компоненты 5_1_0_16.
При работе данной компоненты периодически возникают ошибки, при исполнении кода:
ДиадокКоннект = Диадок.CreateConnectionByCertificate(ДанныеОрганизации.Thumbprint);

Попробовали заменить данную компоненту с сайта диадок http://diadocsdk-1c.readthedocs.io/ru/latest/Downloads.html?highlight=%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0
из Текущие версии внешней компоненты(версия 5.15.0.179). После загрузки компоненты, ошибка при исполнении кода УстановитьВнешнююКомпоненту(ПутьКМакету):
ПутьКМакету = "ОбщийМакет.КомпонентаДляРаботыСДиадок_5_15_0_179";
Подключено = ПодключитьВнешнююКомпоненту(ПутьКМакету, "DiadocAPI", ТипВнешнейКомпоненты.COM);
                Если Не Подключено Тогда
                               Попытка
                                               УстановитьВнешнююКомпоненту(ПутьКМакету);
                                               Подключено = ПодключитьВнешнююКомпоненту(ПутьКМакету, "DiadocAPI", ТипВнешнейКомпоненты.COM);
                               Исключение
                                               ВызватьИсключение "Ошибка инициализации компоненты работы с ДИадок: " + ОписаниеОшибки();
                               КонецПопытки;
                КонецЕсли;
 

Версия платформы: 1С:Предприятие 8.3 (8.3.9.1850)
Конфигурация: Документооборот 8 КОРП, редакция 1.4 (1.4.3.1) 

Вопрос: какую компоненту нам нужно скачать из списка компонент? По адресу http://diadocsdk-1c.readthedocs.io/ru/latest/Downloads.html?highlight=%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0 Необходимо заменить клиентскую компоненту диадок для 1с.
Достаточно ли компоненту поместить в макет конфигурации или необходимо на сервере приложений создавать com объект с этой компонентой?

Заранее благодарю Вас за ответ!!!

**Comment by denver069** [comment]
Для 32-х битных клиентов, необходимо использовать файл: [Внешняя компонента для 1С](http://1c-docs.diadoc.ru/ru/latest/_downloads/AddInDiadocAPI.dll).
Для 64-х битных клиентов, необходимо использовать файл: [Внешняя компонента для 1С, для 64-х битных приложений](http://1c-docs.diadoc.ru/ru/latest/_downloads/AddInDiadocAPI1.dll).

Если с базой данных работают клиенты любой архитектуры, рекомендую поместить в общий макет конфигурации zip архив с двумя файлами и манифестом.
Пример zip архива внешней компоненты: [5.16.1.191.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/969856/5.16.1.191.zip)

Создавать com объект на сервере приложений не нужно.
