### ISSUE TITLE
 Не подписывается входящий УКД

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#962]
Здравствуйте.

Document=Box.GetDocumentById(DocumentId);
ReplySendTask = Document.CreateReplySendTask2("AcceptDocument"); 
RST = ReplySendTask.ContentItems.GetItem(0).Content.UniversalCorrectionDocumentBuyerTitle;
RST.DocumentCreator	= Box.Name;
RST.AcceptanceDate 	= ДатаПодписания; 
RST.OperationContent= "С изменением стоимости согласен"; 
Signer=RST.Signers.AddItems(); 
Signer.SignerReference.CertificateThumbprint = Box.Certificate.Thumbprint; 
Signer.SignerReference.BoxId = Document.Organization.ID; 
ReplySendTask.PowerOfAttorneyToAttach.UseDefault=Box.MyEmployee.NeedToAttachPowerOfAttorney;
ReplySendTask.Send();

Возникает ошибка:
ReplySendTask2.Send: ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData: /UniversalCorrectionDocumentBuyerTitle/Signers/SignerReference: @Inn is required /UniversalCorrectionDocumentBuyerTitle/Signers/SignerReference: SignerDetails not found for boxId=f9f8b47e-bc55-4960-9ca2-8b6908bfe9df,

Несколько дней назад для подписания использовался сертификат сотрудника организации, подписание работало. Сейчас используется сертификат физического лица, подписание не работает. Как теперь правильно подписывать УКД?

AddIn x86 5.47.0.923

**Comment by GilimkhanovDenis** [comment]
Добрый день

Ошибка означает, что для данного сертификата в данном ящике для данного типа документа не найдены полномочия подписанта

Заполните их с помощью [Box](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html).[MyEmployee](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/MyEmployee.html).[CreateSetExtendedSignerDetailsTask()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/MyEmployee.html#MyEmployee.CreateSetExtendedSignerDetailsTask)

**Comment by evgen421** [comment]
Здравствуйте Денис, спасибо за быстрый ответ. Да, была мысль об этом. 
Я сейчас попытался подписать этот документ в вэбинтерфейсе, при подписании потребовалось ввести полномочия, документ подписался. Далее я стал там же подписывать следущий УКД, полномочия уже были указаны, их не нужно было снова вводить. Далее удачно прошло подписание следующего УКД уже с помощью компоненты, не заполняя полномочия подписанта. То есть получается достаточно было один раз заполнить полномочия подписанта при подписании любого УКД в вэбинтерфейсе и сработает подписание с помощь компоненты. Довольно странно, потому что при добавлении нового сертификата физического лица сотрудника, полномочия подписанта были заполнены у данного сотрудника в личном кабинете Контур Диадока. Я правильно понял?

**Comment by GilimkhanovDenis** [comment]
Всё так

Полномочия уникальны для тройки `[BoxId; CertificateThumbprint; DocumentType]`. Подписание документа в веб с соответствующим типом заполняет соответствующие полномочия. Увы, в веб интерфейсе не совсем точная информация отображается в частности по полномочиям подписания УКД (в будущем планируется улучшить веб-интерфейс, но по про эту задачу ничего не смогу рассказать)
Через компоненту полномочия можно заполнить способом, указанным ранее

**Comment by evgen421** [comment]
Понятно, большое спасибо!
