### ISSUE TITLE
GetDocumentsTask не возвращает WaitingForSenderSignature

### ISSUE THREAD

**Issue by blender5** [diadoc/diadocsdk-1c-docs#965]
Добрый день!

При получении списка документов через GetDocumentsTask()
как для 
Category = "Any.Outbound";
так и для
Category = "Any.OutboundWaitingForSenderSignature";

не возвращает список нужных документов.

при этом через HTTP запрос к апи список документов возвращается.

Может проблема крыться в том что установлены ограничения на FromSendDate и ToSendDate? А у тех документов, что должны быть возвращены, вероятно эти данные отсутствуют вовсе. Т.к. документы сформированы но ещё не были отправлены.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Есть очень похожий вопрос [#837](https://github.com/diadoc/diadocsdk-1c-docs/issues/837).
В целом ответ на ваш вопрос - да, границы `FromSendDate` и `ToSendDate` мешают попаданию в отбор неотправленных документов (дата отправки у них считается Диадоком как "далеко в будущем")

**Comment by blender5** [comment]
тогда может подскажете, у документов с какими статусами дата будет "далеко в будущем"?
очень не хочется чаще раза в день перелопачивать весь ящик на предмет изменений или появления новых документов.

**Comment by blender5** [comment]
Сижу разбираюсь с GetDocumentEventList, вероятно этот метод снимет все вопросы.
