### ISSUE TITLE
Как добавить документ к пакету? 

### ISSUE THREAD

**Issue by Udodov87** [diadoc/diadocsdk-1c-docs#966]
Всем привет, допустим я создал через CreatePackageSendTask2 пакет из 2х документов, имею в Диадоке PackageId своего пакета, как мне положить в этот пакет еще документы? какой процедурой или методом?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Сейчас того метода нет. Добавил задачу в бэклог

**Comment by Udodov87** [comment]
> Добрый день
> 
> Сейчас того метода нет. Добавил задачу в бэклог

Ок, надеюсь в скором времени данная функция появится, уж лчень она необходима.

**Comment by Udodov87** [comment]
> Добрый день
> 
> Сейчас того метода нет. Добавил задачу в бэклог

Денис, где я могу отслеживать новости по своему вопросу? Чтобы быть в курсе когда интересующий меня метод появится в компоненте.  Так понял изменить тег PackageId  в загруженном документе тоже нельзя? Допустим был PackageId ="F". хочу заменить на PackageId ="A"

**Comment by GilimkhanovDenis** [comment]
Чтобы следить за новостями релизов, можете подписаться на [RSS](https://developer.kontur.ru/Docs/Diadoc/COM/index.rss)

Если функциональность нужна в ближайшие сроки, рекомендую обратиться к вашему менеджеру, чтобы он продвигал её среди прочих задач, которые у нас есть

**Comment by GilimkhanovDenis** [comment]
Добавили добавление документов в пакет в [5.54.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.54.0)

**Comment by Udodov87** [comment]
Добрый день, не подскажите на какой ключ API из типового модуля Диадок изменился этот ключ? 

1C-DDPro-4-34-1-11c9176b-194a-4fd3-b137-b088af69ee5d

**Comment by GilimkhanovDenis** [comment]
Добрый день

Чтобы избежать блокировки собственного интеграционного решения используйте [собственный ключ API](https://www.diadoc.ru/integrations/api#order-form-integration), а не ключ универсального модуля.

**Comment by Udodov87** [comment]
У меня ошибка с сегодняшнего дня 

Ошибка при вызове метода контекста (CreateConnectionByLogin): Произошла исключительная ситуация (DiadocCom.CreateConnectionByLogin): ##100[Ошибка сервера Диадок]code:401, HTTP error: Invalid API client id

**Comment by Udodov87** [comment]
Так я в унивирсальном модуле дописывал функцию оповещения сотрудника и там вообще никакие действия не производились, сертификат не использовался.

**Comment by GilimkhanovDenis** [comment]
Могу посоветовать только такие варианты:
- выпустить собственный ключ API
- периодически переносить доработки в новые версии модуля
- предполагаю, что сценарий можно закрыть не через доработки основного модуля, а через ПМ и тогда можно будет безболезненно обновлять основной модуль

В противном случае периодически будет происходить аналогичная ситуация, что сейчас - команда отключает старые модули, блокируя используемый в них ключ API
