### ISSUE TITLE
Как отслеживать изменения состояния документов?

### ISSUE THREAD

**Issue by X-BANZAJ** [diadoc/diadocsdk-1c-docs#968]
Доброго времени суток. Используем Diadoc COM Api (5.46.1.920)

Возникли некоторые вопросы в ходе изучения возможностей библиотеки: 
1) Как лучше всего отслеживать изменение состояния (статус) документа? Например, мы отправили документ и ожидаем его подписания, т.е. свойство **RecipientResponseStatus** должно измениться как мы понимаем..

2) Например, возможно ли определять у каких документов изменилось состояние на определенную дату? 
Попробовали метод **GetDocumentEventList**, вывел информацию не по всем событиям, вернул 134 записи, ограничение? Если да то какое? И заметили что **EventId** совпадает с **MessageId**, что крайне не понятно для нас, особенно учитывая что единственный возможный фильтр/параметр в этом методе как раз идентификатор события..

Также обратили внимание на метод HTTP **GetDocflowEvents**. В теле запроса возможно указать фильтр по дате, попытались таким образом в Postman ограничить выборку и получить результат, но как указать **FromTimestamp** и **ToTimestamp** (не Tick).. 

3) Каким способом лучше всего получать информацию о том, что пришел новый документ в нашу организацию?

**Comment by GilimkhanovDenis** [comment]
Добрый день

другого метода в компоненте на данный момент нет. Ленту можно читать только вперёд, начиная с события после того, чей идентификатор передан в параметр метода

События выводятся пачками. чтобы читать ленту дальше, нужно вызвать метод повторно в идентификатором события, пришедшим последним.

Про EventId и MessageId предлагаю почитать обсуждение https://github.com/diadoc/diadocsdk-1c-docs/issues/918 - там отвечал на подобный же вопрос

Что касается GetDocflowEvents: в Диадок две ленты событий, оперирующих разными абстракциями. Компонента GetDocflowEvents не использует. В бэклоге есть задача на улучшение текущей ленты. [Здесь](https://github.com/diadoc/diadocsdk-1c-docs/discussions/827) собираем пожелания и фиксируем проблемы

**Comment by X-BANZAJ** [comment]
@GilimkhanovDenis, спасибо за ответ. Опять же, если есть необходимость обработать самое последнее событие снова (допустим мы его храним у себя), это сделать не получится, т.к. метод вернет только те что будут после него.. По документу, дате тоже было бы удобно получать события. А можно точно узнать в каких случаях EventId совпадает с MessageId?

**Comment by GilimkhanovDenis** [comment]
`EventId` совпадает с `MessageId` для отправки первого титула документа в Диадок. т.е. только для исходящего документа. Для входящего могут быть отличия.
И, как отмечал, в https://github.com/diadoc/diadocsdk-1c-docs/issues/918 - это нигде не прописанная и не зафиксированная логика Диадока. Завязываться на неё можно только на свой страх и риск

Пожелание про ленту зафиксировал
