### ISSUE TITLE
Ошибка при заполнении SignerReference

### ISSUE THREAD

**Issue by EgorEgorProg** [diadoc/diadocsdk-1c-docs#970]
Не получается отправить через API Диадок документы через ФЛ с МЧД. 
Заполняю структуру:
NewSigner.SignerReference.BoxId = Organization.guid; 
NewSigner.SignerReference.PowerOfAttorney.UseDefault = "false";                                 
NewSigner.SignerReference.CertificateThumbprint = Organization.Certificate.Thumbprint; 
NewSigner.SignerReference.PowerOfAttorney.FullId.IssuerInn = ИНН ЮЛ;
NewSigner.SignerReference.PowerOfAttorney.FullId.RegistrationNumber = Номер доверенности ФЛ.

Ошибка:
Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (PackageSendTask2.Send):
 ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
/UniversalTransferDocument/Signers/SignerReference: @Inn is required
/UniversalTransferDocument/Signers/SignerReference: SignerDetails not found for boxId=Ид организации,
 thumbprint=Отпечаток ЭЦП, documentTitleType=0

Помогите пожалуйста разобраться.

**Comment by EgorEgorProg** [comment]
@INN is required - такое поле только в SignerDetails (но его не надо заполнять, если заполняешь SignerReference) и в Organization.Certificate (там ИНН ФЛ, на которого ЭЦП)

**Comment by GilimkhanovDenis** [comment]
https://github.com/diadoc/diadocsdk-1c-docs/issues/962 здесь уже отвечал на такой же вопрос

нужно заполнить параметры подписанта с помощью [Box](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html).[MyEmployee](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/MyEmployee.html).[CreateSetExtendedSignerDetailsTask()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/MyEmployee.html#MyEmployee.CreateSetExtendedSignerDetailsTask)

**Comment by EgorEgorProg** [comment]
Ошибка возникала из-за ограниченных прав. Решил так:

Ошибка возникает, если не настроен подписант УПД в личном кабинете Диадок.

Чтобы исправить ошибку, в системе Диадок откройте Настройки > Реквизиты организации. Перейдите на вкладку Сотрудники и выберите сотрудника, который будет отвечать за подписание документов. В карточке сотрудника перейдите на вкладку Данные по сертификатам и в группе полей Область полномочий установите полномочия для входящих и исходящих документов. Нажмите на кнопку Сохранить.

**Comment by EgorEgorProg** [comment]
Отправка прошла без ошибок. Но доверенность в штампе так и не подтянулась. В примере в штампе указано "доверенность не приложена при подписании"
[Акт 2111002.pdf](https://github.com/diadoc/diadocsdk-1c-docs/files/13445571/2111002.pdf)

**Comment by GilimkhanovDenis** [comment]
Доверенность указывается в [PackageSendTask2](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html).[PowerOfAttorneyToAttach](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PowerOfAttorneyToAttach.html)

Проверьте как он заполнен при отправке

**Comment by EgorEgorProg** [comment]
Да, круто, спасибо. Всё заработало.

Сделал так:
	// МЧД
	dd_EmployeePowerOfAttorney_Collection = Organization.MyEmployee.GetPowersOfAttorney(Истина);
	МЧД = Неопределено;

	Для Каждого стр из dd_EmployeePowerOfAttorney_Collection цикл
		Если стр.PowerOfAttorney.Id.RegistrationNumber=НомерДоверенности Тогда
			МЧД=стр;
		КонецЕсли;
	КонецЦикла;

	Если Не МЧД = Неопределено Тогда
		dd_PowerOfAttorneyToAttach = PackageSendTask.PowerOfAttorneyToAttach;
		dd_PowerOfAttorney = МЧД.PowerOfAttorney;
		dd_PowerOfAttorneyToAttach.PowerOfAttorney = dd_PowerOfAttorney;
	КонецЕсли;
