### ISSUE TITLE
Диадок. Отправка УПД контрагенту

### ISSUE THREAD

**Issue by PetrovKvazar2016** [diadoc/diadocsdk-1c-docs#971]
Здравствуйте!
Не могу отправить документ контрагенту.
Если устанавливаю значение свойства `oSendTask.IsDraft = True`, то документ попадает в личный кабинет в виде черновика.
Но если свойство `oSendTask.IsDraft = False`, документ исчезает: его нет не в исходящих, не во входящих у контрагента.
Помогите разобраться как отправить контрагенту подписанный УПД.
 
Вот код, который я использую для отправки:
 
```
oContragents = oOrganization.GetCounteragentListByStatus()
oCounterAgent = GetCounterAgentByInn('9677329734', oContragents)
oSendTask = oOrganization.CreatePackageSendTask2()
oSendTask.CounterAgentId = oCounterAgent.ID
oSendTask.OperationId = NewId()
oSendTask.IsDraft = .F.
 
oDocumentToSend = oSendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", ;
        "utd820_05_01_02_hyphen", ;
        "c:\Users\Viktor\Documents\ON_NSCHFDOPPR_....xml")
oDocumentToSend.COMMENT = "Это УПД с контентом, загруженным из файла"
oSendTask.SEND()
```
 
Спасибо!

**Comment by GilimkhanovDenis** [comment]
Добрый день

Метод [Send()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html#PackageSendTask2.Send) возвращает список отправленных документов. В каждом документе будет ссылка на этот документ в веб-интерфейсе

**Comment by PetrovKvazar2016** [comment]
Если
oSendTask.IsDraft = .T. (черновик), то метод send() возвращает докумены.
А если oSendTask.IsDraft = .F. - то нет.
И куда при этом уходит документ неизвестно.

**Comment by GilimkhanovDenis** [comment]
Метод либо возвращает документы, либо возвращает ошибку. Судя по синтаксису, у вас не 1С - возможно, нужно в каком-то явно виде ловить ошибку

Можете указать начало ключа API, который используете - попробую логи найти

**Comment by GilimkhanovDenis** [comment]
Если правильно нашёл отправителя и получателя, то при постинге получаете ошибку:

```
MessageToPost.DocumentAttachments[0]: { Location = /Файл/@ИдФайл, Message = Значение атрибута @ИдФайл имеет неверный формат: ON_NSCHFDOPPR_2BM-9677329734-967701000-201508251208137541585_2BM-7706422198-772301001_20231122_F1D5F87B-5C66-4431-AB6C-632106445844.xml (@ИдОтпр=2BM-7706422198-772301001, @ИдПол=2BM-9677329734-967701000-201508251208137541585)
				При отстутствии /Файл/Документ/ТаблСчФакт/СведТов/ДопСведТов/НомСредИдентТов и /Файл/Документ/ТаблСчФакт/СведТов/ДопСведТов/СведПрослеж значение @ИдФайл должно начинаться с ON_NSCHFDOPPR_ или ON_NSCHFDOPPRMARK_ }
```

по [формату](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=6399066) ИдФайла должен быть
`ON_NSCHFDOPPR_2BM-9677329734-967701000-202311210136311165039_2BM-9671359891-967101000-202111010235323023806_...`
В вашем файле идентификаторы получателя и отправителя указаны неправильно

**Comment by PetrovKvazar2016** [comment]
Здравствуйте! Работаю на VFP9 (Foxpro), но через API 1С.
Вот начало API ключа: Kvazar-03a1b9c7-4183-4856-92f9-
Собственно 1С у меня действительно нет. Но я использую функции API, выдернутые из примеров 1С. 
>Суббота, 25 ноября 2023, 12:02 +03:00 от Гилимханов Денис ***@***.***>:
> 
> 
>Метод либо возвращает документы, либо возвращает ошибку. Судя по синтаксису, у вас не 1С - возможно, нужно в каком-то явно виде ловить ошибку
>Можете указать начало ключа API, который используете - попробую логи найти
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/971/1826259289 @ github . com> 
 
 
_____________________________________
С уважением, Виктор. Квазар.

**Comment by PetrovKvazar2016** [comment]
Здравствуйте!
При использовании следующего кода:
oOrganization = goOrgan        &&THISFORM.GetOrganizationByInn()
oContragents = oOrganization.GetCounteragentListByStatus()
oCounterAgent = THISFORM.GetCounterAgentByInn('9677329734', oContragents)
oSendTask = oOrganization.CreatePackageSendTask2()
oSendTask.CounterAgentId = oCounterAgent.ID
 
oSendTask.OperationId = NewId()
oSendTask.IsDraft = .T.
 
*!*    Добавление документа УПД с контентом, взятым из файла
oDocumentToSend = oSendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", ;
    "utd820_05_01_02_hyphen", ;
    "c:\Users\Viktor\Documents\ON_NSCHFDOPPR_2BM-9677329734-967701000-201508251208137541585_2BM-7706422198-772301001_20231122_F1D5F87B-5C66-4431-AB6C-632106445844.xml")
oDocumentToSend.COMMENT = "Это УПД с контентом, загруженным из файла"
 
oPatchTask = oOrganization.CreatePatchTask()
oPatchTask.AddToPatch(oDocumentToSend, 'Sign')
oPatchTask.send()
 
Документ попадает в черновики личного кабинета. При этом никаких ошибок в файле не обнаружено. Если нажимаю на кнопку «Подписать и отправить», то документ без проблем отправляется контрагенту (отслеживаю по тестовому ящику контрагента). Затем подписываю от имени контрагента, и вижу в своем ящике, что документ подписан.
Проблема возникает лишь тогда, когда я устанавливаю  oSendTask.IsDraft = .F. (не черновик). 
>Суббота, 25 ноября 2023, 12:20 +03:00 от Гилимханов Денис ***@***.***>:
> 
> 
>Если правильно нашёл отправителя и получателя, то при постинге получаете ошибку:
>MessageToPost.DocumentAttachments[0]: { Location = /Файл/@ИдФайл, Message = Значение атрибута @ИдФайл имеет неверный формат: ON_NSCHFDOPPR_2BM-9677329734-967701000-201508251208137541585_2BM-7706422198-772301001_20231122_F1D5F87B-5C66-4431-AB6C-632106445844.xml (@ИдОтпр=2BM-7706422198-772301001, @ИдПол=2BM-9677329734-967701000-201508251208137541585)
>				При отстутствии /Файл/Документ/ТаблСчФакт/СведТов/ДопСведТов/НомСредИдентТов и /Файл/Документ/ТаблСчФакт/СведТов/ДопСведТов/СведПрослеж значение @ИдФайл должно начинаться с ON_NSCHFDOPPR_ или ON_NSCHFDOPPRMARK_ }
>
>по  формату ИдФайла должен быть
>ON_NSCHFDOPPR_2BM-9677329734-967701000-202311210136311165039_2BM-9671359891-967101000-202111010235323023806_...
>В вашем файле идентификаторы получателя и отправителя указаны неправильно
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/971/1826262686 @ github . com> 
 
 
_____________________________________
С уважением, Виктор. Квазар.

**Comment by PetrovKvazar2016** [comment]
Ошибка. Вместо кода
oPatchTask = oOrganization.CreatePatchTask()
oPatchTask.AddToPatch(oDocumentToSend, 'Sign')
oPatchTask.send()

Использую
oDocuments = oSendTask.SEND()

**Comment by GilimkhanovDenis** [comment]
При подписании черновика, его контент патчится - исправляются идентификаторы получателя/отправителя, подписант. Поэтому в черновик можно запостить в чём-то неправильно заполненный документ.
Когда отправляете документ сразу, то никакого патчинга не происходит - отправляет то, что есть. И по логам я вижу ошибку с тэгом  ИдФайл

**Comment by PetrovKvazar2016** [comment]
Я поправил ИдФайл, ИдОтпр, ИдПол и Подписант.
К сожалению, ситуация не изменилась.
В ИдОтпр я подставил значение oOrganization.FnsParticipantId, в ИдПол — oCounterAgent.FnsParticipantId.
Поменял везде ИННы и КПП (где это необходимо).
Правильно ли я указал ВерсПрог="Diadoc 1.0"? Потому что в интернете я увидел ВерсПрог="CorePlat 1.4.1"
  
>Понедельник, 27 ноября 2023, 11:48 +03:00 от Гилимханов Денис ***@***.***>:
> 
> 
>При отправке черновика, контент патчится - исправляются идентфикаторы получателя/отправителя, подписант. Поэтому в черновик можно запостить в чём-то неправильно заполненный документ.
>Когда отправляете документ сразу, то никакого патчинга не происходит - отправляет то, что есть. И по логам я вижу ошибку с n'ujv ИдФайл
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/971/1827383209 @ github . com> 
 
 
_____________________________________
С уважением, Виктор. Квазар.

**Comment by GilimkhanovDenis** [comment]
Последние ошибки всё те же - неправильный ИдФайл. теперь он просто не полный. из идентфикатора файла пропал суффикс - то что в [формате](https://normativ.kontur.ru/document?moduleId=1&documentId=328588&rangeId=6399066) обозначено как `..._GGGGMMDD_N`

предлагаю так же научиться ловить в интеграции ошибки, возвращаемые компонентой. Если, это чем-то поможет, то возвращаем их с помощью [SetErrorInfo](https://learn.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-seterrorinfo)

**Comment by PetrovKvazar2016** [comment]
Добавил суффикс. Но ничего не изменилось!

  
>Понедельник, 27 ноября 2023, 15:46 +03:00 от Гилимханов Денис ***@***.***>:
> 
> 
>Последние ошибки всё те же - неправильный ИдФайл. теперь он просто не полный. из идентфикатора файла пропал суффикс - то что в  формате обозначено как ..._GGGGMMDD_N
>предлагаю так же научиться ловить в интеграции ошибки, возвращаемые компонентой. Если, это чем-то поможет, то возвращаем их с помощью  SetErrorInfo
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/971/1827768853 @ github . com> 
 
 
_____________________________________
С уважением, Виктор. Квазар.

**Comment by GilimkhanovDenis** [comment]
Можете показать XML, который пытаетесь отправить?

**Comment by PetrovKvazar2016** [comment]
>Понедельник, 27 ноября 2023, 16:24 +03:00 от Гилимханов Денис ***@***.***>:
> 
> 
>Можете показать XML, который пытаетесь отправить?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/971/1827827543 @ github . com> 
 
 
_____________________________________
С уважением, Виктор. Квазар.

**Comment by GilimkhanovDenis** [comment]
Предположу, что в последнем Вашем ответе должно быть вложение, но на GitHub его нет

Предлагаю или через сам GitHub приложить файл или выложить файл куда-то и в письме дать ссылку

**Comment by PetrovKvazar2016** [comment]
Файл прикреплен к письму.

  
>Понедельник, 27 ноября 2023, 17:03 +03:00 от Гилимханов Денис ***@***.***>:
> 
> 
>Предположу, что в последнем Вашем ответе должно быть вложение, но на GitHub его нет
>Предлагаю или через сам GitHub приложить файл или выложить файл куда-то и в письме дать ссылку
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/971/1827893369 @ github . com> 
 
 
_____________________________________
С уважением, Виктор. Квазар.

**Comment by PetrovKvazar2016** [comment]
Дублирую файл.
[ON_NSCHFDOPPR-2BM-9677329734-967701000-202311210136311165039-2BM-9671359891-967101000-202111010235323023806-20231127-5019FA16-EDA5-4203-B005-344138221996.zip](https://github.com/diadoc/diadocsdk-1c-docs/files/13476068/ON_NSCHFDOPPR-2BM-9677329734-967701000-202311210136311165039-2BM-9671359891-967101000-202111010235323023806-20231127-5019FA16-EDA5-4203-B005-344138221996.zip)

**Comment by PetrovKvazar2016** [comment]
Здравствуйте!
 
Вроде бы нашел ошибку. В ИдФайл было указано расширение файла «xml».
 
<Файл ИдФайл="ON_NSCHFDOPPR_2BM-9677329734-967701000-201508251208137541585_2BM-7706422198-772301001_20231128_121E1386-EA01-49CA-B176-168712279017 .xml " ВерсФорм="5.01" ВерсПрог="Diadoc 1.0">
Убрал это расширение, и файл попал в исходящие организации и во входящие контрагента.
Но после команды отправки документа использовал аналог функции SetError:
 
oDocuments = oSendTask.SEND()
=AERROR(arrError)   && аналог SetError
 
Дальше всё прошло: подписал документ контрагентом.
Меня смущает ошибка 1429.
 
 
и в полученном массиве ошибки всё равно была ошибка 1429. 
>Понедельник, 27 ноября 2023, 17:03 +03:00 от Гилимханов Денис ***@***.***>:
> 
> 
>Предположу, что в последнем Вашем ответе должно быть вложение, но на GitHub его нет
>Предлагаю или через сам GitHub приложить файл или выложить файл куда-то и в письме дать ссылку
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/971/1827893369 @ github . com> 
 
 
_____________________________________
С уважением, Виктор. Квазар.

**Comment by GilimkhanovDenis** [comment]
@PetrovKvazar2016 Если првильно понимаю то, что написано [здесь](https://help.foxclub.ru/html/cf8d9a30-f8dc-4181-bebd-1181c3554308.htm), то кроме ошибки `1429` в первом элементе `arrError`, можно посмотреть третий элемент, в котором будет текст

там что-то есть?

**Comment by PetrovKvazar2016** [comment]
Не поверите, не могу воспроизвести ошибку. Всё работает без ошибок.
Но из предыдущего журнала ошибок там было "При отстутствии /Файл/Документ/ТаблСчФакт/СведТов/ДопСведТов/НомСредИдентТов и /Файл/Документ/ТаблСчФакт/СведТов/ДопСведТов/СведПрослеж значение @ИдФайл должно начинаться с ON_NSCHFDOPPR_ или ON_NSCHFDOPPRMARK_"

**Comment by GilimkhanovDenis** [comment]
У меня единственное предположение, что информация об ошибке сохраняется, пока её не забрать.

Т.е. в предыдущую отправку ошибка произошла, её никто не забрал.
Далее была успешная отправка
Но ошибку с прошлого раза никто не забрал и её можно получить после успешной отправки

Предлагаю это обращение закрыть. Если проблема с тем, что ошибка есть при успешной отправке остаётся, то лучше в новом issue разобрать ситуацию

**Comment by PetrovKvazar2016** [comment]
Совершенно верно. Пока я полностью не перезагрузил программу, последняя ошибка оставалась актуальной. Но после перезагрузки последняя ошибка ушла.

**Comment by PetrovKvazar2016** [comment]
Спасибо за помощь!
