### ISSUE TITLE
Предотвратить дублирование отправляемых документов

### ISSUE THREAD

**Issue by PetrovKvazar2016** [diadoc/diadocsdk-1c-docs#972]
Здравствуйте!
Подготавливаю документ для отправки методом SendTask = oOrganization.CreatePackageSendTask2()
Затем получаю список уже отправленных документов:
SearchDocuments = oOrganization.GetDocumentsTask()
oSearchDocuments.FromSendDate = '01.11.2023'
oSearchDocuments.ToSendDate   = '30.11.2023'
oSearchDocuments.Category     = "UniversalTransferDocument.Outbound"
oDocumentList = oSearchDocuments.GetDocuments()
И перебираю список полученных документов:
FOR nInd = 0 TO oDocumentList.COUNT - 1
	oDocumentBase = oDocumentList.GetItem(nInd)
...
ENDFOR

Как определить, что отправляемый документ не был отправлен ранее?
Какие свойства SendTask и oDocumentBase использовать для этого?
Или есть какой-то другой способ предотвратить задвоенность?

**Comment by GilimkhanovDenis** [comment]
Добрый день

у PackageSendTask2 есть поле `OperationId` - можно использовать его в качестве идентификатора отправки. Т.е. если указан OpеrаtionId и ранее была отправка с таким `OperationId`, то вернётся результат этой отправки

Одинаковость (задвоенность) документов бывает разной - для кого-то одинаковыми документами считаются  документы с одинаковым номером и датой. Для кого-то важен тип документа (`Торг12 №1 от 01.01.2023`  не то же самое, что `УПД ДОП №1 от 01.01.2023`). Для кого-то важно, чтобы ещё и сумма совпадала и т.д.
Т.е. проверка задвоенности зависит от бизнес процесса

Если хотите как-то понимать, что документ вашей учётной системы уже был отправлен в Диадок, то какой-то признак об этом можно хранить в самой УС, например, хранить `OperationId`, в котором была отправка этого документа или `DocumentId` документа в Диадок

**Comment by PetrovKvazar2016** [comment]
Здравствуйте!
С проблемой задвоенности я разобрался. Но.
Когда я получаю список документов
SearchDocuments = oOrganization.GetDocumentsTask()
oSearchDocuments.FromSendDate = '01.11.2023'
oSearchDocuments.ToSendDate = '30.11.2023'
oSearchDocuments.Category = "UniversalTransferDocument.Outbound"
в список не попадают удаленные документы, хотя в полученном списке есть свойство IsDeleted. 
А мне очень нужны и удаленные тоже. Как мне их получить?

**Comment by GilimkhanovDenis** [comment]
Удалённые документы через GetDocumentsTask никак не получить
Их можно получить по идентификатору (через [Box.GetDocumentById(...)](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.GetDocumentById))

**Comment by PetrovKvazar2016** [comment]
Да, но для этого нужно знать DocumentId.
А список никак не получить?

**Comment by GilimkhanovDenis** [comment]
Нет. никак

API Диадок такое не позволяет сделать

**Comment by PetrovKvazar2016** [comment]
Может быть через HTTP?

**Comment by PetrovKvazar2016** [comment]
Или получить вручную, через личный кабинет. DocumentId где нибудь фигурирует?
Тогда я бы составил список Id вручную

**Comment by GilimkhanovDenis** [comment]
`DocumentId`  - конкатенация строк `LetterId` и `DocumentId` из веб
Допустим, есть
https://diadoc.kontur.ru/f2fc9a7f-bbae-45db-bc01-7c3447ed4c78/Document/Show?letterId=b40b3950-e84e-4992-845c-7730b27d11a5&documentId=3ddf0be4-13a0-46f6-bb67-063894961e44

Тогда `DocumentId` для компоненты - `b40b3950-e84e-4992-845c-7730b27d11a53ddf0be4-13a0-46f6-bb67-063894961e44`
