### ISSUE TITLE
проблема с подписью актов

### ISSUE THREAD

**Issue by AnnaStarod** [diadoc/diadocsdk-1c-docs#973]
Подписываем через COM-объект 
ReplyContentItem.Document.TypeNamedId="XmlAcceptanceCertificate" 
Document.Version="rezru_05_02_01"
с помощью объекта ReplyContentItem.Content.AcceptanceCertificate552BuyerTitle
Signer пробовали заполнять и по отпечатка сертификата и через Signer.SignerDetails, в Signer.SignerDetails.FirstName записываю Фамилию. После подписи документа в Диадоке , подпись отображается как Отчество Фамилия Имя, техподдержка отвечает, что именно по этой причине информация о подписи не доходит до контрагента (эти документа приходят из роуминга Тензор).
Certificate.Name ="Фамилия Имя Отчество". В чем может быть причина и как исправить?

**Comment by GilimkhanovDenis** [comment]
Добрый день

можете дать ссылку на документ, у которого подпись не доходит до роумингового контрагента?
Может быть при отправке ответа получаете какую-то ошибку?

**Comment by AnnaStarod** [comment]
вот этот (он был аннулирован, чтобы подписать новый ,т.к. надо было срочно)
https://diadoc.kontur.ru/184f66df-afda-4192-88de-b14002842176/Document/Show?letterId=fa18cd0b-3194-48c2-a365-c9ea59a71ad1&documentId=319a77e1-f8e5-48b7-8195-b3e198dfc709

и вот этот такой же проблемный
https://diadoc.kontur.ru/184f66df-afda-4192-88de-b14002842176/Document/Show?letterId=037467f6-0da1-4b08-ad88-18dd3a79dd9f&documentId=c915f60e-4285-461a-84b2-4f57a650237f

**Comment by AnnaStarod** [comment]
Здравствуйте, а есть какое-то движение по этому вопросу? А то у нас большие проблемы с такими актами.

**Comment by GilimkhanovDenis** [comment]
Можете показать как именно заполняете подписанта?

**Comment by GilimkhanovDenis** [comment]
FirstName - это Имя
LastName - это Фамилия

**Comment by AnnaStarod** [comment]
boxid = Document.OrganizationId;
					thumbprint = Document.Organization.Certificate.thumbprint;
					Signer.SignerReference.BoxId=boxid;
					Signer.SignerReference.CertificateThumbprint=Thumbprint;
скажите, а версия dll может играть роль? Мы работали на 5_39_1_865, на последней пока не было возможности проверить

**Comment by GilimkhanovDenis** [comment]
Нет, не должно

если заполняете так, то стоит проверить какие данные возвращаются на вызов

`Document.Organization.MyEmployee.GetExtendedSignerDetails("Utd820Buyer")`

**Comment by AnnaStarod** [comment]
![СнимокДиадок](https://github.com/diadoc/diadocsdk-1c-docs/assets/152598813/6aca230b-a073-431b-af76-e39dabe5e914)

**Comment by GilimkhanovDenis** [comment]
Кажется, это данные по другому пользователю (по другому сертификату). Подозреваю, это данные по сертификату с отпечатком `f7c5232de357b116a139c280c52ca645c774e47f`. С ним не вижу проблемных документов

Те документы, с которыми возникли ошибки, подписывались сертификатом с отпечатком `73ba0ee382ab9e86b043024aa3d3f24cc3865286`

К тому же сейчас заметил, что в начале обращения речь идёт об Актах в формате приказа 552, а ссылки на документы даны для УПД 820 приказа.

Насколько вижу, сейчас для сертификата `73ba0ee382ab9e86b043024aa3d3f24cc3865286` в полномочиях правильно указаны ФИО (для 2го титула УПД 820, для остальных титулов параметры подписанта не запомнены)

Есть ли свежие примеры документов, которые подписывались этим сертификатом с использованием `SignerReference`, и в которых неправильно заполнен подписант?

**Comment by AnnaStarod** [comment]
пока других примеров нет

**Comment by GilimkhanovDenis** [comment]
@AnnaStarod появились ли актуальные примеры?

**Comment by AnnaStarod** [comment]
нет, пока нет (не обращались пользователи)

**Comment by GilimkhanovDenis** [comment]
Тогда обращение закрою. Если появятся новые примеры, то переоткрывайте, будем смотреть
