### ISSUE TITLE
Авторизация по сертификату

### ISSUE THREAD

**Issue by PetrovKvazar2016** [diadoc/diadocsdk-1c-docs#974]
Здравствуйте!
Есть действительный сертификат Крипто-ПРО.
Ранее я разрабатывал программу, авторизуясь по логину и паролю. Сейчас необходимо перейти на сертификат.
При попытке авторизоваться по сертификату не могу получить объект DiadocConnection.
DiadocConnection = DiadocApi.CreateConnectionByCertificate2(<отпечаток сертификата>)
Причем система его распознает.
Команда oPrint = DiadocApi.GetPersonalCertificate(<отпечаток сертификата>)  позволяет увидеть все его свойства.
Команда DiadocApi.VerifyThatUserHasAccessToAnyBox(<отпечаток сертификата>) возвращает True.
Но в DiadocConnection вместо объекта попадает False.
Помогите понять проблему.

**Comment by GilimkhanovDenis** [comment]
CreateConnectionByCertificate2 принимает не отпечаток сертификата, а объект

Т.е. должно быть примерно так:
```
oCertificate = DiadocApi.GetPersonalCertificate(<отпечаток сертификата>)
oConnection = DiadocApi.CreateConnectionByCertificate2(oCertificate)
```

**Comment by PetrovKvazar2016** [comment]
Это я уже понял. А как теперь получить токен. Без HTTP запросов.

**Comment by GilimkhanovDenis** [comment]
Не очень понятно зачем он понадобился - по идее дальше при работе с компонентой он не должен понадобиться

но он лежит в `oConnection.SessionInfo.Token`

**Comment by PetrovKvazar2016** [comment]
Извините, туплю. Увидел токен.

**Comment by PetrovKvazar2016** [comment]
Спасибо за помощь. С авторизацией я разобрался.
Вопрос. Если вхожу в систему с помощью сертификата, получаю объект организации Organization.
Но команда
Contragents = Organization.GetCounteragentListByStatus()
или
Contragents = Organization.GetCounteragentListByStatus('IsMyCounteragent')
вместо объекта Contragents, возвращает False.
Когда входил по логину и паролю, это работало.
Как победить?

**Comment by PetrovKvazar2016** [comment]
Спасибо за помощь! С авторизацией я разобрался.
Вопрос. Если вхожу в систему с помощью сертификата, получаю объект организации Organization.
Но команда
Contragents = Organization.GetCounteragentListByStatus()
или
Contragents = Organization.GetCounteragentListByStatus('IsMyCounteragent')
вместо объекта Contragents, возвращает False.
Когда входил по логину и паролю, это работало.
Как победить?

  
>Пятница, 1 декабря 2023, 15:34 +03:00 от Гилимханов Денис ***@***.***>:
> 
> 
>Не очень понятно зачем он понадобился - по идее дальше при работе с компонентой он не должен понадобиться
>но он лежит в oConnection.SessionInfo.Token
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <diadoc/diadocsdk-1c-docs/issues/974/1836047086 @ github . com> 
 
 
_____________________________________
С уважением, Виктор. Квазар.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Предлагаю новую проблему обсудить в новом тикете, если она ещё актуальна.

Вообще работа метода не зависит от способа авторизации.
Предположу, что возникла какая-то ошибка при выполнении запроса. Возможно, начали выполнять метод в другом ящике - в логах вижу ошибку `##100[Ошибка сервера Диадок]code:402, HTTP error: Доступ запрещён. Необходима оплата тарифа АПИ`
