### ISSUE TITLE
Переход с режима отладки на работу по сертификату организации.

### ISSUE THREAD

**Issue by PetrovKvazar2016** [diadoc/diadocsdk-1c-docs#975]
После перехода на боевой режим с использованием сертификата организации. Начались проблемы.

Вопрос. Если вхожу в систему с помощью сертификата, получаю объект организации Organization.
Но команда
Contragents = Organization.GetCounteragentListByStatus()
или
Contragents = Organization.GetCounteragentListByStatus('IsMyCounteragent')
вместо объекта Contragents, возвращает False.
Когда входил по логину и паролю, это работало.
Как победить?

**Comment by PetrovKvazar2016** [comment]
Да, ящик сменился. Был c5aa5513-c09b-4db9-a04f-cd3279ebca1e
Стал: 1e81de5f-da4d-4ff3-b8a2-5d84e5b02b5e
Какие действия мне предпринять, чтобы заработало в новом ящике?

**Comment by GilimkhanovDenis** [comment]
Насколько вижу, в ящике `1e81de5f-da4d-4ff3-b8a2-5d84e5b02b5e` нет оплаченного тарифа на использование API

Необходимо обратиться к менеджеру

PS. Для тестовых организаций (`c5aa5513-c09b-4db9-a04f-cd3279ebca1e`) API не блокируется, поэтому там всё работало

**Comment by PetrovKvazar2016** [comment]
Спасибо!
