### ISSUE TITLE
Подписать входящий УПД

### ISSUE THREAD

**Issue by PetrovKvazar2016** [diadoc/diadocsdk-1c-docs#976]
Здравствуйте!
Есть входящий УПД. Его необходимо подписать. Код взял из примера в документации  Диадок COM/1C Addin SDK.

IF oDocumentBase.RecipientResponseStatus = 'WaitingForRecipientSignature'
	oPatchTask = goOrganization.CreatePatchTask()
	oValueCollection = oPatchTask.AddToPatch(oDocumentBase, 'Sign')

	FOR nInd1 = 0 TO oValueCollection.COUNT - 1
		oPatchItem = oValueCollection.GetItem(nInd1)

начало примера:
		oPatchContent = oPatchItem.PatchContent
		oTypeDesc = goReflector.Describe(oPatchContent)
		oInterfaceName = oTypeDesc.GetInterfaceName()

		oContent = oPatchItem.PatchContent.Content
		oUniversalTransferDocumentBuyerTitle = oContent.UniversalTransferDocumentBuyerTitle
		oUniversalTransferDocumentBuyerTitle.DocumentCreator  = goOrganization.NAME
		oUniversalTransferDocumentBuyerTitle.OperationContent = "Принято без претензий"
		oSignerDetails = oUniversalTransferDocumentBuyerTitle.Signers.AddItems().SignerDetails
		oSignerDetails.LastName         = "Петров"
		oSignerDetails.FirstName        = "Виктор"
		oSignerDetails.MiddleName       = "Петрович"
		oSignerDetails.SignerPowers     = "1"
		oSignerDetails.SignerPowersBase = "Должностные обязанности"
		oSignerDetails.SignerType       = "1"
		oSignerDetails.SignerStatus     = "1"

Указываю с SignerStatus как строку. При этом получаю ошибку:
HTTP error: Invalid data UserContractData:
Line: 5, Position: 169, /UniversalTransferDocumentBuyerTitle[1]/Signers[1]/SignerDetails[1]/@SignerStatus: The 'SignerStatus' attribute is invalid - The value '1' is invalid according to its datatype 'Integer' - The Enumeration constraint failed.

Получается, что в SignerStatus я должен положить 1 как Integer.

Но если я пишу 
		oSignerDetails.SignerStatus       = 1

то получаю ошибку времени выполнения
OLE error code 0x80020008: Bad variable type.

и в любом случае документ не подписывается.

		oSignerDetails.inn              = "9671359891"
	ENDFOR

	oPatchResult = oPatchTask.SEND()
	cError = oPatchResult.GetItem(0).ERROR
ENDIF

**Comment by GilimkhanovDenis** [comment]
Добрый день.
В первом случае положили значение правильно - его нужно класть строкой.
Ошибка Диадок означает, что для этого типа документа нельзя применить само значение `1`. Можете в UserDataXSD посмотреть какие значения допустимы

**Comment by PetrovKvazar2016** [comment]
Спасибо! Разобрался.
