### ISSUE TITLE
Проблема с заданием на подпись документов CreatePatchTask

### ISSUE THREAD

**Issue by heratei** [diadoc/diadocsdk-1c-docs#977]
Добрый день!

При создании задания на подпись документов 1С падает в ошибку:
Метод объекта не обнаружен (CreatePatchTask)
{ОбщийМодуль........Модуль(363)}:		PatchTask	= Organization.CreatePatchTask();

Код ниже:
Organization = DiadocConnection.GetOrganizationById(BoxId);
PatchTask	= Organization.CreatePatchTask();

**Comment by GilimkhanovDenis** [comment]
Добрый день.

Либо в `Organization` лежит `Неопределено` по какой-то причине, либо используете старую компоненту, где этого метода ещё нет

**Comment by heratei** [comment]
Обновление компоненты помогло. Благодарю!
