### ISSUE TITLE
Здравствуйте, можно ли при подписи через COM объект заполнять дополнительные сведения, интересует СвВыбытияМАРК, чтобы партии сразу выбывали в Честном знаке.

### ISSUE THREAD

**Issue by AnnaStarod** [diadoc/diadocsdk-1c-docs#978]
Здравствуйте, можно ли при подписи через COM объект заполнять дополнительные сведения, интересует СвВыбытияМАРК, чтобы партии сразу выбывали в Честном знаке.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Если правильно понимаю, то `СвВыбытияМАРК` - это тэг в XML документа. Если так, то нужно получить UserDataXSD соответствующего типа документа и посмотреть есть ли поле для его заполнения. Подробнее можно посмотреть  [DynamicContent](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html)
