### ISSUE TITLE
Регистровая зависимость ID МЧД

### ISSUE THREAD

**Issue by MaximGlazunov** [diadoc/diadocsdk-1c-docs#979]
Добрый день.

Столкнулись с такой ситуацией.
Метод GetPowersOfAttorney() возвращает данные МЧД, только если МЧД проверена Диадоком.
Если с МЧД что-то не так, то метод возвращает ошибку, а описание можно найти в DocflowStatus.PowerOfAttorneyStatus.
Корреспондент прислал документы подписанные МЧД, и вэб-интерфейс и COM-объект говорят, что доверенность не найдена на сайте ФНС (ID доверенности: f1c290f6-b9df-4402-bdce-6e46ec0af2fe). И правда, сайт ФНС ничего не находит по этому ID.
Однако, если произвести поиск по этому же ID, но в верхнем регистре (F1C290F6-B9DF-4402-BDCE-6E46EC0AF2FE), поиск будет успешным.
Обратная ситуация тоже имеет место быть: по ID в нижнем регистре другие МЧД будут найдены, в верхнем - нет.
Скажите, пожалуйста, будет ли проведена какая-то работа по устранению данной проблемы со стороны Диадок?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Так как регистрозависимый поиск осуществляется на стороне блокчейна ФНС, то считаем, что пожелание о регистронезависимом поиске должно быть отправлено им.

У Диадока задачи на поиск МЧД с идентификаторами в различных регистрах нет
