### ISSUE TITLE
УПД (UtdInvoice)

### ISSUE THREAD

**Issue by prog22** [diadoc/diadocsdk-1c-docs#98]
Использую COM-компоненту для встраивания в произвольные системы, для 64-х битных приложений - 5.16.1.191.
Со стороны Поставщика отправляю счет-фактуру как УПД (UtdInvoice).
В ящике Покупателя получаю Document с Document.type = "Invoice".
Как мне понять, что СФ отправлена в новом электронном формате?

**Comment by prog22** [comment]
И еще вопрос:
Со стороны Покупателя данный "Invoice" находится в состоянии "InboundFinished" (получен после Document.SendReceiptsAsync), а со стороны Поставщика "UtdInvoice" находится в состоянии "OutboundNotFinished" (Документ исходящий, извещение о получении УПД/ИУПД/УКД/ИУКД от покупателя уже есть, но документооборот еще не завершен).
Что нужно сделать для перевода данного "UtdInvoice" в состояние "OutboundFinished".

**Comment by denver069** [comment]
В версии 5.17.0.201 внешней компоненты в объект Document добавлено поле AttachmentVersion.
Если счет-фактура отправлена в формате УПД, значение этого поля будет равно UniversalTransferDocument".

**Comment by prog22** [comment]
Обновил компоненту, получилось. Спасибо.
