### ISSUE TITLE
Как найти документ по draftId после подписания и отправки?

### ISSUE THREAD

**Issue by X-BANZAJ** [diadoc/diadocsdk-1c-docs#980]
Доброго времени суток. Интересует один момент. Если допустим мы размещаем два документа в черновике (закрыт от изменения) в диадоке, на данный момент у нас есть 16-символьный guid идентификаторов документов и идентификатор черновика draftId (как я понимаю после размещения документов в диадоке в черновике то draftId = letterId из pathURL). Как после подписания и отправки (кнопка "Подписать и отправить" из черновика) получить у этих документов letterId через draftId? Т.к. видимо после подписания эти документы перекочуют в исходящие и letterId меняется
Надеюсь понятно объяснил)

**Comment by GilimkhanovDenis** [comment]
Добрый день

Если подписываете через [PatchTask](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PatchTask.html), то созданные документы будут возвращены как результат подписания черновиков

Если подписание было через Веб, то сейчас в компоненте нет никакого способа, кроме чтения ленты [Box.GetDocumentEventList()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.GetDocumentEventList)

**Comment by X-BANZAJ** [comment]
Да через веб подписание происходит.  Хотели как раз обойтись без чтения ленты т.к. она очень не удобна на текущий момент.

**Comment by X-BANZAJ** [comment]
@GilimkhanovDenis, подскажите а как то по другому можно разместить пакет (например из 3 документов) в диадок и получить только одну ссылку, по которой пользователь зайдлет и подпишет весь пакет одной кнопкой? Видел что можно разместить и в исх.одящих но там ссылки у документов разные и приходится по каждому проходить подписывать и отправлять..

**Comment by GilimkhanovDenis** [comment]
Можно отправить с флагом `DelaySend = True`. тогда документ попадёт в исходящие, но не будет подписан. Т.е. он не будет черновиком.
Можно сделать примерно так:

```
КакойТоИдентификатор =  "идентификатор, который запомним в УС";
SendTask = Box.CreatePackageSendTask2();
// добавляем документы на отправку
// ....

SendTask.OperationId = КакойТоИдентификатор ;
SendTask.DelaySend = True;
SendTask.LockMode = "Send"; //чтобы пользователь подписывал весь пакет разом
dd_DocumentPackage = SendTask.Send();
```

далее происходит подписание в веб. На стороне интеграции после этого можно сделать такое:

```
SendTask = Box.CreatePackageSendTask2();
SendTask.OperationId = КакойТоИдентификатор;
dd_DocumentPackage = SendTask.Send();
```

получите пакет документов, которые отправляли ранее.


Либо можно запоминать идентификатор `DocumentId` какого-то документа из пакета и потом делать примерно:

```
dd_Document = Box.GetDocumentById(Запомненный_DocumentId);
dd_DocumentPackage = dd_Document.GetDocumentPackage();
```

**Comment by X-BANZAJ** [comment]
@GilimkhanovDenis, при DelaySend = True общей ссылки не будет же? Подписант должен будет произвести подписание раздельно на каждом документе тогда? Когда в черновиках, там плюс в том что ссылка одна и кнопка на подписание всего пакета одна

**Comment by GilimkhanovDenis** [comment]
При
`SendTask.LockMode = "Send"; //чтобы пользователь подписывал весь пакет разом`

отправитель не сможет подписать документы по раздельности. Если правильно помню поведение веба, то при подписании любого документа пакета будет показано окно с информацией, что подписание произойдёт по всем документамм пакета

**Comment by GilimkhanovDenis** [comment]
Т.е. можно будет дать ссылку на любой документ пакета

**Comment by X-BANZAJ** [comment]
@GilimkhanovDenis, спасибо за ваш ответ. К сожалению есть еще удобство в черновике, это возможность оттуда удалить, если подписант не согласен. Возмжности же удаления из исх. полностью  в диадоке отсутствует как я понимаю

**Comment by GilimkhanovDenis** [comment]
Только переместить в удалённые (потом можно восстановить), черновики же полностью удаляются

**Comment by X-BANZAJ** [comment]
Все понятно, еще раз благодарю.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Добавили информацию о созданных и черновика документах в релизе [5.50.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.50.0) ([ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html))
