### ISSUE TITLE
Отправка подписанного контента

### ISSUE THREAD

**Issue by AlexanderShiryaev** [diadoc/diadocsdk-1c-docs#981]
Коллеги, добрый день!
В компоненте не планируется реализация отправки подписанного контента?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Если речь про то, чтобы отправлять контент с заранее сформированной подписью, то нет не планируется

**Comment by GilimkhanovDenis** [comment]
Расскажите о сценарии, для которого такая функциональность потребовалась

**Comment by AlexanderShiryaev** [comment]
Мы пользуемся компонентой, чтобы отправлять контент, подписываемый сертификатом ген. директора, который хранится на сервере. Сертификаты физ. лиц хранить на сервере не хочется в целях безопасности, поэтому пока мы реализуем отправку подписанного контента с помощью хттп методов, но это влечет за собой больше требований по сопровождению и реализации механизма

**Comment by GilimkhanovDenis** [comment]
Пока не очень понятен сценарий. Сейчас формируете подпись, используя сертификат ген.директора, а хочется, видимо, формировать с помощью сертификатов сотрудников.

Что мешает сейчас авторизовываться по сертификату сотрудника в компоненте и отправлять контент подписанный их сертификатом.
Речь про отправку документов или ответов на входящие?

**Comment by AlexanderShiryaev** [comment]
И отправка новых документов, и ответы на входящие
Если я правильно понимаю, компонента должна быть расположена на той же машине, на которой расположен сертификат, а в случае с использованием сертификатов физ. лиц такой возможности нет. Или я недостаточно хорошо знаю возможности компоненты?

**Comment by AlexanderShiryaev** [comment]
В текущей реализации компонента и сертификат ген. директора на одном сервере

**Comment by GilimkhanovDenis** [comment]
Если дадим способ загрузки готовой подписи (если правильно понял то, о чём просите), то как будет устроен процесс отправки?

**Comment by GilimkhanovDenis** [comment]
Компонента ничего не знает про то, на сервере или нет она работает - ей важен доступ к сертификатам. Как он будет организован - на усмотрение интегратора. Это может быть или сертификат, локально установленный на сервере, или проброс смарт карт через RDP или ещё как-то

Если речь про 1С, то там, насколько знаю, есть инструкции препроцессора `&НаСервере`  и `&НаКлиенте` - никто не запрещает инициализировать компоненту на клиенте и работать в локальном контексте пользователя

**Comment by AlexanderShiryaev** [comment]
Сейчас для отправки новых мы используем CreatePackageSendTask2, в который добавляем необходимые документы и метаданные, а затем делаем для объекта CreatePackageSendTask2 метод Send
Для ответа мы для каждого документа используем CreateReplySendTask2, который по необходимости наполняем и делаем Send
При подписании физ. лицом с отправкой новых больших сложностей нет, но вот с ответными документами - нам необходимо понимать, какой контент подписывать, а это либо генерация xml самостоятельно на основании GenerateTitleXml, либо хранение xsd схем у себя, а затем подбор их в зависимости от типа сущности в Диадоке - получается много "лишних" действий, от которых избавляла компонента

**Comment by AlexanderShiryaev** [comment]
Касательно НаСервере и НаКлиенте - вы правы, но интеграция включает в себя не только 1С, поэтому такой подход не реализуем

**Comment by GilimkhanovDenis** [comment]
Давайте ещё раз. Хотите загружать `подписываемый контент` или `контент + подпись, сформированную где-то вне компоненты` ?
При этом, отправка документов у вас не вызывает проблем - там формируется тот контент, который вам нужен и подписывается тем сертификатом, которым нужно
Вопрос возникает только с ответными действиями, и там не можете реализовать сценарий который хотите?

По сути, механизм отправки документа и ответа не отличаются, поэтому пока не очень понимаю в чём трудность возникла

**Comment by AlexanderShiryaev** [comment]
Контент + Подпись, сформированную вне компоненты, да

В случае отправки нового, мы дополняем xml данными о подписанте, это небольшой блок, который несложно реализовать/поддеражть

Основная проблема в генерации ответного титула, который и требуется подписывать. Слишком много вариантов требуют либо большой кодовой базы, либо более универсального, но более медленного механизма

**Comment by GilimkhanovDenis** [comment]
**Про отправку:**

XML генерируете сами, и потом загружаете в компоненту готовый файл. Подписываете сертификатом ген.директора и подписанта заполняете его же данными?
Здесь проблем не возникает, потому что отправляете очень ограниченный набор документов, условно только УПД СЧФДОП?

**Про ответные действия:**

Приходит много разных по типу документов + нужно ещё уметь аннулировать, запрашивать корректировки и т.д., поэтому приходится в кодовой базе держать логику для заполнения подписанта для титулов разных типов документов и разных ответных действий

Либо использовать GenerateTitleXML, где подписант немного упрощён. Но этот способ медленнее.

Сейчас ответные действия выполняете через HTTP API, а хочется через компоненту

**Вопрос 1**

Сейчас подписант в титулах и ответных действиях заполняется данными ген.директора и подписывается сертификатом ген.директора?
Или в XML подписант заполнен данными сотрудника и сам XML-файл подписан сертификатом сотрудника. После подписания, XML и подпись отправляются на сервер, где с помощью HTTP API отправляются в Диадок?

**Вопрос 2**

Если для ответных действий используются данные сотрудника, то почему? Хочу понять бизнес-сценарий, почему для отправки документов как будто бы не возникает никаких проблем.
Или в отправке тоже хочется загружать готовый контент и подпись

**Вопрос 3**

История с большой кодовой базой и поддежркой разных подписантов, как будто бы отдельная проблема. Как добавление возможности загрузки готового контента и подписи решит проблему с поддержанием заполнения подписантов для разных контентов?

**Comment by AlexanderShiryaev** [comment]
Про отправку - верно

Про ответные - верно

Вопрос 1: у нас работают оба механизма - и отправка ответных через компоненту, и отправка ответных через апи (апи используем только для подписания титулов сертификатами физ. лиц)

Вопрос 2: у нас возникает потребность реализации факта подписания штатными сотрудниками. На этапе отправки, как вы верно заметили, проблем почти нет, потому что список документов ограничен и регламентируется внутри компании, а вот входящие документы могут быть в довольно большом различном количестве форматов, что и вызвало, по сути, создание этого топика) Естественно, вне зависимости от того, отправка нового или ответное подписание - есть потребность использовать исключительно подпись физ. лица в связке с МЧД

Вопрос 3: реализация отправки контента + подписи не решит проблему с поддержкой кодовой базы для реализации ответных титулов, но снимет с нас нагрузку на поддержку периодически меняющихся методов ответной отправки
Естественно, также хотелось бы иметь "конструктор" xml на стороне компоненты, что как раз приведет к уменьшению кодовой базы, но я почему то начал топик не с этого)

**Comment by GilimkhanovDenis** [comment]
В целом понятно

Загрузку готового контента и подписи положу в бэклог, не уверен как быстро возьмём задачу в работу. Если сильно болит, то предлагаю обратиться к вашему менеджеру, чтобы он продвигал задачу среди прочих

Что касается механизма формирования XML - пока это первое пожелание на моей памяти и очень маловероятно что когда-то реализуем. В компоненте есть [DynamicContent](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html), который по сути заполняет UserDataXSD для отправки в метод GenerateTitleXML из HTTP API. Возможно, он частично сможет снять боль с формированием разных XML

**Comment by GilimkhanovDenis** [comment]
Да, ещё такая просьба, можете указать ИНН-КПП вашей компании, чтобы нам проще было понимать, от кого было обращение

**Comment by AlexanderShiryaev** [comment]
Окей, спасибо большое
7707743155-770501001
