### ISSUE TITLE
подпись УПД и выбытие в Честный знак

### ISSUE THREAD

**Issue by AnnaStarod** [diadoc/diadocsdk-1c-docs#982]
Здравствуйте, можно ли при подписи через COM объект заполнять дополнительные сведения, интересует СвВыбытияМАРК, чтобы партии сразу выбывали в Честном знаке. Уже задавала вопрос https://github.com/diadoc/diadocsdk-1c-docs/issues/978. 
 Поясните, пожалуйста как найти это свойство, я получила Url /GetContent?typeNamedId=UniversalTransferDocument&function=ДОП&version=utd820_05_01_01&titleIndex=0&contentType=TitleXsd, дальше как я могу получить схему и определить нужное мне поле? Документации никакой, все методом проб.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Воспользуйтесь методом [Box.SaveTitleDynamicContentXSD(...)](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.SaveTitleDynamicContentXSD) - получите схему упрощённого контента по которой строится [DynamicContent](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DynamicContent.html) в том числе там будет указано какие поля DynamicContent'а за какие тэги XML отвечают. Оттуда же можно понять и вложенность этих полей

**Comment by AnnaStarod** [comment]
Box - это какой объект?

**Comment by GilimkhanovDenis** [comment]
Тот же для которого вызываете [CreatePackageSendTask2()](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/Box.html#Box.CreatePackageSendTask2)

**Comment by AnnaStarod** [comment]
![Снимок](https://github.com/diadoc/diadocsdk-1c-docs/assets/152598813/a6e7aba1-b1e5-4e90-a945-d45083c117f9)
не вызывается

**Comment by AnnaStarod** [comment]
без аргумента - тоже самое

**Comment by AnnaStarod** [comment]
я поняла, что там надо задать больше аргументов, в том числе путь для файла, но это как-то очень странно, чтобы узнать какие поля заполнять, надо написать код, сохраняющий на диск схему. можно как-то ее получить не меняя программу под получение схемы?

**Comment by GilimkhanovDenis** [comment]
схема вам нужна по сути только 1 раз, чтобы понять строение контента и написания логики заполнения контента. В логике самой интеграции схема сама по себе вряд ли понадобится.
Схема - единственный способ понять какое поле контента за что в XML отвечает

**Comment by AnnaStarod** [comment]
в том-то и дело: чтобы 1 раз посмотреть - напиши код

**Comment by AnnaStarod** [comment]
как должен быть заполнен FilePath? "d:\1" дает ошибку 
![Снимок1](https://github.com/diadoc/diadocsdk-1c-docs/assets/152598813/cc8a92ba-43ad-4d33-ba1c-1ad707a93203)

**Comment by AnnaStarod** [comment]
методом проб и ошибок файл со схемой получила, но СвВыбытияМАРК там не нашла, по идее он в доп. сведениях, похожие поля в схеме есть, но описания нет
[Uploading 2222.txt…]()

**Comment by AnnaStarod** [comment]
файл приложила

**Comment by GilimkhanovDenis** [comment]
Увы, файл не приложился
Схему для какиго типа, функции и версии выгружали?

**Comment by GilimkhanovDenis** [comment]
Почитал рекомендации про указание сведений о выбытии. Если правильно понял, то это не тэг в XML, а значение ключа в `ИнфПолФХЖ1` и в схеме для, например,  `[UniversalTransferDocument, ДОП, utd820_05_01_01]`  за эти тэги отвечает

```
<xs:element minOccurs="0" name="AdditionalInfoId" type="AdditionalInfoId">
          <xs:annotation>
            <xs:documentation>ИнфПолФХЖ1 - Информационное поле документа</xs:documentation>
          </xs:annotation>
```

Сам тип полей описан так:
```
<xs:complexType name="AdditionalInfoId">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="AdditionalInfo" type="AdditionalInfo">
        <xs:annotation>
          <xs:documentation>ТекстИнф - текстовая информация</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="InfoFileId" use="optional">
      <xs:annotation>
        <xs:documentation>ИдФайлИнфПол (GUID) - идентификатор файла информационного поля</xs:documentation>
      </xs:annotation>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:length value="36" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
```

Т.е. внутри лежит AdditionalInfo:
```
  <xs:complexType name="AdditionalInfo">
    <xs:attribute name="Id" type="string50" use="required">
      <xs:annotation>
        <xs:documentation>Идентиф - идентификатор (наименование)</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Value" type="string2000" use="required">
      <xs:annotation>
        <xs:documentation>Значен - значение</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
```

Собственно, в AdditionalInfo.Id нужно указать "СвВыбытияМАРК", а в AdditionalInfo.Value указать причину

Таким образом для  `[UniversalTransferDocument, ДОП, utd820_05_01_01]` можно получить такое заполнение
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/91ccaddb-4f28-4991-82ae-89dafce3646f)

// в логе написано обращение по индексу - его можно наменить на  вызов метода GetItem(Index)

**Comment by AnnaStarod** [comment]
Спасибо, получилось, а еще можно уточнить: если мы на все УПД (без анализа есть Честный знак или нет) будем указывать СвВыбытияМАРК, проблем нигде не будет? И УПД попадают в Честный знак после подписи покупателя?

**Comment by GilimkhanovDenis** [comment]
Боюсь, здесь не смогу подсказать - это вопрос не про функциональность компоненты

Рекомендую с этими вопросами обратиться на линию технической поддержки - у них больше информации про сценарии взаимодействия Диадок с Честным знаком
