### ISSUE TITLE
Подпись актов сверки

### ISSUE THREAD

**Issue by ElenaBurnasheva** [diadoc/diadocsdk-1c-docs#983]
Здравствуйте.
Какие поля необходимо заполнить в Content.ReconciliationActRecipientTitle.Signers.Signer при подписи без разногласий и какие при разногласиях?

**Comment by ElenaBurnasheva** [comment]
Есть где то описание как правильно заполнять Content.ReconciliationActRecipientTitle при разногласиях и без них?

**Comment by NickZubashevskiy** [comment]
Добрый день
Наличие разногласий указывается в поле документа ПризнРазн (описание есть в [приказе](https://normativ.kontur.ru/document?moduleId=1&documentId=425482)). В UserDataXSD документа это поле называется SignOfDisagreement, согласно приказу значение 1 - нет разногласий, 2 - есть разногласия.
Информация по заполнению других полей есть в [приказе](https://normativ.kontur.ru/document?moduleId=1&documentId=425482) и UserDataXSD.

**Comment by GilimkhanovDenis** [comment]
Кстати, аналогичный вопрос уже был: https://github.com/diadoc/diadocsdk-1c-docs/issues/950
