### ISSUE TITLE
необходимо авторизоваться по сертификату  ошибка

### ISSUE THREAD

**Issue by girafiik** [diadoc/diadocsdk-1c-docs#984]
при отправке документа возникает ошибка 

> Ошибка при вызове метода контекста (Send)
> {ВнешняяОбработка.ДД_подключаемыйМодуль.Форма.Форма.Форма(36)}:ОтправленныеДокументы = SendTask.Send();
> {ВнешняяОбработка.ДД_подключаемыйМодуль.Форма.Форма.Форма(11)}:ОтправитьУПД(Organization,ЯщикиКонтрагентов[0]);
> 
> [ОшибкаВоВремяВыполненияВстроенногоЯзыка]
> по причине:
> Произошла исключительная ситуация (PackageSendTask2.Send): Для выполнения операции необходимо авторизоваться по сертификату

[ОшибкаИспользованияВстроенногоЯзыка]
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/8110162/2f780065-9525-4869-94a8-68301494cd7b)

```
SendTask = Organization.CreatePackageSendTask2();
SendTask.CounterAgentId = Counteragent.Guid;

Third_DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "ДОП", "utd820_05_01_02_hyphen", "C:\от 15.01.2024.xlsx");   
Third_DocumentToSend.Comment = "Спецификация  " + "35"; 
ОтправленныеДокументы = SendTask.Send();
```

**Comment by GilimkhanovDenis** [comment]
Добрый день

В чём вопрос? В ошибке написано. что нужно авторизоваться по сертификату. Из вашего скриншота видно, что авторизовались по логину

**Comment by girafiik** [comment]
> Добрый день
> 
> В чём вопрос? В ошибке написано. что нужно авторизоваться по сертификату. Из вашего скриншота видно, что авторизовались по логину

а если нету сертификата?  по логину и паролю нельзя отправлять документы?

**Comment by GilimkhanovDenis** [comment]
Можно отправлять тестовые документы (в тестовый ящик или из тестового ящика), отправлять документы в черновики ([PackageSendTask2](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html).IsDraft) или отправлять  документы в исходящие без отправки контрагенту ([PackageSendTask2](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html).DelaySend)

Если нужно отправить юридически значимые документы контрагенту, то их нужно подписывать сертификатом КЭП

**Comment by girafiik** [comment]
> Можно отправлять тестовые документы (в тестовый ящик или из тестового ящика), отправлять документы в черновики ([PackageSendTask2](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html).IsDraft) или отправлять документы в исходящие без отправки контрагенту ([PackageSendTask2](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PackageSendTask2.html).DelaySend)
> 
> Если нужно отправить юридически значимые документы контрагенту, то их нужно подписывать сертификатом КЭП

все спасибо
