### ISSUE TITLE
Статус документа InboundNoRecipientSignatureRequest, а на сайте есть кнопка подписания (COM x86 5.49.1.933)

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#985]
Добрый день.
Используем компоненту COM x86 5.49.1.933 для произвольных систем.
Получили документ с реквизитами

TypeNamedId   Nonformalized
status                InboundNoRecipientSignatureRequest

![скрин1](https://github.com/diadoc/diadocsdk-1c-docs/assets/20082460/f08a2b55-6793-4232-8561-e0c63f341f91)

Мы понимаем, что это неформализованный документ, который не требует подписания.
Но на сайте в данном документе присутствуют кнопки Подписать и Отказать.

![скрин2](https://github.com/diadoc/diadocsdk-1c-docs/assets/20082460/1c3c9a17-3a2b-4277-bdd5-1c00ec18aaa5)

Требует ли такой документ подписания или нет? На какую информацию ориентироваться?

**Comment by GilimkhanovDenis** [comment]
Добрый день

Вы можете подписать такой документ по своему желанию. Возможность подписать такой документ оставлена сознательно, так как иногда отправитель забывает запросить ответную подпись, а некоторым получателям важно иметь такую возможность

Из компоненты такие документы тоже можно подписать

**Comment by jakeqwert** [comment]
Правильно ли мы понимаем, что теперь любой неформализованный документ можно подписать, независимо от того требует он подписи или нет? Раньше такой возможности не было. Будет ли в случае документа не требующего подписи в штампе вторая подпись после подписания?

**Comment by GilimkhanovDenis** [comment]
Всё зависит от WorkflowId - есть те, для которых ответная подпись всегда нужна, есть те, для которых никогда не нужна, есть те. для которых ответная подпись по запросу отправителя. Для этого документа `WorkflowId = 1` - ответная подпись по запросу отправителя и для таких документов получатель может сформировать подпись даже если она не запрашивалась ([подробная таблица](https://developer.kontur.ru/docs/diadoc-api/docflows/Workflows.html))

Такая возможность была всегда (по крайней мере последние лет 5)

Пользуясь компонентой можно писать только бизнес логику когда вы хотите подписать документ (учёт суммы, даты документа, кто отправитель и т.п. ) - проверки, связанные с возможностью в принципе подписать документ в Диадок, пройдут в [PatchTask.AddToPatch(..., "Sign")](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/PatchTask.html#PatchTask.AddToPatch)

**Comment by jakeqwert** [comment]
Теперь все понятно, спасибо за консультацию!
