### ISSUE TITLE
Дополнительная подпись

### ISSUE THREAD

**Issue by SPS38** [diadoc/diadocsdk-1c-docs#987]
Добрый день!
Возможно ли каким то методом подписать входящий документ УПД подписью, но не отправлять его контрагенту?
Нужно будет отправить документ только после второй подписи бухгалтера

**Comment by GilimkhanovDenis** [comment]
Добрый день

Функциональность "согласующей" подписи в компоненте отсутствует

**Comment by SPS38** [comment]
Спасибо!

**Comment by GilimkhanovDenis** [comment]
В [5.54.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.54.0) добавили отправку согласующей подписи

Стоит учитывать, что для формализованных документов сначала формируется конечная подпись (и документ отправляется контрагенту) и только потом можно поставить согласующую (ограничение самого сервиса, COM-компонента на это не может повлиять)
