### ISSUE TITLE
Некорректное значение documentBase.Timestamp

### ISSUE THREAD

**Issue by X-BANZAJ** [diadoc/diadocsdk-1c-docs#988]
Доброго времени суток. 
Не понимаю один момент. Получаем события через  GetDocumentEventList и далее обрабатываем у себя. Причем у события имеется метка времени event.Timestamp и тут все нормально выводится как надо. Если же обратиться с documentBase.Timestamp то тут время выходит странное (на 5 часов меньше). Почему так?
Получается событие при подписании и отправке случилось 2024-01-25 09:56:30.000, а дата и время отправки документа в 2024-01-25 04:56:30.000

**Comment by GilimkhanovDenis** [comment]
Добрый день

В BoxEvent время приводится к текущему часовому поясу, а в DocumentBase - по UTC

**Comment by X-BANZAJ** [comment]
ясно, неожиданно

**Comment by GilimkhanovDenis** [comment]
Если и будем как-то менять эти поля, то скорее в BoxEvent появится время по UTC
