### ISSUE TITLE
Неполные данные CustomData в COMобъекте документов

### ISSUE THREAD

**Issue by MaximGlazunov** [diadoc/diadocsdk-1c-docs#989]
Добрый день.

В поле CustomData отображаются не все данные, которые указаны в документе.
Обнаружили на примере нескольких документов.
Если смотреть XML, то все данные на месте (в поле ИнфПолФХЖ1), но компонента возвращает не все (а в некоторых документах вообще ничего).
Причем поведение компоненты всегда одинаково для одного документа.
Примеры документов:
43a07a7b-368e-46dd-b89a-3a586862343033d38bce-16e7-43d9-a33d-45bd93a596b2 - возвращает одно значение из двух
816a5c3a-c0a1-4417-9749-1deed1419acb2ace4505-fdd9-4e52-a0ce-50dd038f52d3 - не возвращает ни одного значения из пяти

ID организации: 52c37243403c4354be3cb578fc056edf@diadoc.ru
Версия компоненты: COM x64 5.39.0.861

Подскажите, пожалуйста, с чем это связано? Может ли компонента вернуть больше одного значения?
Как это исправить?

**Comment by GilimkhanovDenis** [comment]
Добрый день

[DocumentBase](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html).CustomData - это информация НЕ из контента, а дополнительные мета-данные, которые были добавлены к документу

Для [43a07a7b-368e-46dd-b89a-3a586862343033d38bce-16e7-43d9-a33d-45bd93a596b2](https://diadoc.kontur.ru/52c37243-403c-4354-be3c-b578fc056edf/Document/Show?letterId=43a07a7b-368e-46dd-b89a-3a5868623430&documentId=33d38bce-16e7-43d9-a33d-45bd93a596b2) - это действительно только одно значение
Для [816a5c3a-c0a1-4417-9749-1deed1419acb2ace4505-fdd9-4e52-a0ce-50dd038f52d3](url) - ни одного значения не добавлялось

Если нужны значения из тэга `ИнфПолФХЖ1`, то искать их нужно в результате метода [DocumentBase.GetDynamicContent("Seller")](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html#DocumentBase.GetDynamicContent)

**Comment by MaximGlazunov** [comment]
Огромное спасибо, вижу необходимые данные.
