### ISSUE TITLE
Акт сверки

### ISSUE THREAD

**Issue by evgen421** [diadoc/diadocsdk-1c-docs#990]
Диадок COM/1C Addin SDK  AddIn x86 5.49.1.933

```
SendTask = Box.CreatePackageSendTask2();
SendTask.CounterAgentId = CounterAgentId;
Document = SendTask.AddDocument("ReconciliationAct", "default", "reconciliationact405_05_01_01");
...
Document.Content.ReconciliationActSenderTitle.Sender.OrganizationReference.BoxId = Box.Guid
Document.Content.ReconciliationActSenderTitle.Sender.OrganizationReference.Phone = "8(1234)256789"
...
SendTask.Send()
```

> PackageSendTask2.Send: ##100[Ошибка сервера Диадок]code:400, HTTP error: Invalid data UserContractData:
> /ReconciliationActSenderTitle/Sender/OrganizationReference: @Phone or @Email or @OtherContactInfo is required

Поле Phone заполнено, в чём проблема непонятно!

**Comment by GilimkhanovDenis** [comment]
Добрый день

Попробуйте указать дополнительно
`Document.Content.ReconciliationActSenderTitle.Sender.OrganizationReference.OtherContactInfo = " "` (заполнить значение пробелом)

**Comment by evgen421** [comment]
Получилось, спасибо.
