### ISSUE TITLE
Передать на согласование неформализованный документ (файл pdf)

### ISSUE THREAD

**Issue by Alkonig58** [diadoc/diadocsdk-1c-docs#991]
Добрый день, у вас есть пример в документации создание задачи "передача на согласование". 
Так вот, в этом примере создается задание для документа который уже есть в базе, не могли бы вы поправить этот пример если мне на согласование нужно отослать неформализованный файл pdf. Если мне этот файл сначала нужно отослать на сервер, то в каком виде, чтобы получить DocumentBase ?

Пример из документации:
------------------------------------------------

```
Процедура ОтправитьДокументНаПодписьВПодразделение(ИдентификаторДокумента, ИдентификаторПодразделения)
    Document = Organization.GetDocumentById(ИдентификаторДокумента)
    ResolutionRequestTask = DocumentBase.CreateResolutionRequestTask();
    // ResolutionRequestType определяет будет ли это запрос на согласование или передача на подпись
    // В данном случае - передача на подпись
    ResolutionRequestTask.ResolutionRequestType = "SignatureRequest";
    ResolutionRequestTask.TargetDepartmentId    = ИдентификаторПодразделения;
    ResolutionRequestTask.Send();
КонецПроцедуры
```

**Comment by GilimkhanovDenis** [comment]
Добрый день

Вам нужно [отправить документ](https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_post_document.html) с флагом `DelaySend = True` и потом для него создать запрос согласования. Примерно так:

```
Функция ОтправитьДокументы(Organization, Counteragent)
    SendTask = Organization.CreatePackageSendTask2();
    SendTask.CounterAgentId = Counteragent.Id;
    SendTask.DelaySend = True;
....
    Возврат SendTask.Send();
КонецФункции

dd_Package = ОтправитьДокументы(МояЯщик, ЯщикКонтрагента);
ResolutionRequestTask = dd_Package.CreateResolutionRequestTask();
...
```

**Comment by GilimkhanovDenis** [comment]
Если для разных документов отправленного пакета нужно разные запросы согласования создавать, то можно создавать задания согласования для отдельных элементов коллекции [dd_Package.Documents](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentPackage.html)

**Comment by Alkonig58** [comment]
Спасибо за помощь, все получилось.
