### ISSUE TITLE
Проблемы с подписанием входящих документов.

### ISSUE THREAD

**Issue by KrasnovaAnastasia** [diadoc/diadocsdk-1c-docs#992]
Добрый день! Просьба помочь.
Документ для подписания находим, но в процессе подписания выходит ошибка:
 _Ошибка подписания документов: {<Неизвестный модуль>(88)}: Поле объекта не обнаружено (UniversalTransferDocumentBuyerTitle)_

Прилагаю код подписания документа:

Если обДОкумент.RecipientResponseStatus = "WaitingForRecipientSignature" Тогда  
  PatchTask           = обОрганизация.CreatePatchTask();
  КоллекцияДокументов = PatchTask.AddToPatch(обДОкумент, "Sign");  
КонецЕсли;  

Если КоллекцияДокументов.Count() > 0 Тогда
  ДокументКоллекции                     = КоллекцияДокументов.GetItem(0);  
   КонтентДокумента                      = ДокументКоллекции.PatchContent.Content;
  ТитулПокупателя                       = КонтентДокумента.UniversalTransferDocumentBuyerTitle;
  ТитулПокупателя.DocumentCreator       = обОрганизация.Name;
  ТитулПокупателя.OperationContent      = "Принято без претензий"; 
  Подписанты                            = ТитулПокупателя.Signers.AddItems();  
  Подписанты.SignerReference.BoxId      = сИнтерфейс.ИдентификаторОрганизации; 
  Подписанты.SignerReference.CertificateThumbprint = Строка(сИнтерфейс.Сертификат);
  ДокументКоллекции.PatchContent.PowerOfAttorneyToAttach.UseDefault 
    = обОрганизация.MyEmployee.NeedToAttachPowerOfAttorney;
  PatchTask.Send();  
КонецЕсли;

**Comment by GilimkhanovDenis** [comment]
Добрый день

Предположу, что подписываете не УПД, и тогда в контенте не будет поля `UniversalTransferDocumentBuyerTitle`

Чтобы сказать точнее нужна ссылка на документ, который не получается подписать (значение поля `DocumentBase.PathURL`)

**Comment by KrasnovaAnastasia** [comment]
Добрый день!
По изначальному вопросу проблема решена: УПД подписывается.

НО имеется другая проблема:
в пакете документов документы со статусом "WaitingForRecipientSignature", но без титула покупателя (например: протокол согласования цен, спецификации, акты) - не подписываются.

Подскажите, пожалуйста, что необходимо использовать (код, метод...), чтобы подписать данные документы?

**Comment by GilimkhanovDenis** [comment]
А что значит "не подписываются" ? Если возникает ошибка, про которую пишете в самом начале, то это закономерно - для этих типов документов не нужно заполнять второй титул, так как это однотитульные документы. Для них создаётся обычная подпись (см. [пример](https://developer.kontur.ru/Docs/Diadoc/COM/HowTo/HowTo_reply_document.html))

**Comment by KrasnovaAnastasia** [comment]
С проблемой в самом начале мы разобрались, с титулом - подписываются.
А вот документы без титула - нет.
При подписании документа без титула покупателя, мы присваиваем PatchContent.PowerOfAttorneyToAttach.UseDefault = True. Документ не подписывается. Т.е. каждый раз из всего пакета подписывается только документ - с титулом. В чем может быть проблема?

**Comment by GilimkhanovDenis** [comment]
Какой документ не получается подписать?

**Comment by KrasnovaAnastasia** [comment]
Вот пакетный ИД 5fe71a3e-115c-43ab-9599-923766522f95, УПД пописано, а спецификация - нет.

**Comment by GilimkhanovDenis** [comment]
А в каком ящике этот пакет?

**Comment by KrasnovaAnastasia** [comment]
Если Вы про ИД организации, то вот: 7ae48ba4-bf6c-429a-859d-295dd1c2e585

**Comment by GilimkhanovDenis** [comment]
Можете показать полный код, который используете для подписания такого пакет? Добавляете ли вы документы по отдельности в PatchTask или кладёте весь пакет?

**Comment by KrasnovaAnastasia** [comment]
```
СчетчикДокументов = 0;
ДокументыПодписаны = Истина;
Пока СчетчикДокументов < КоличествоЭлементов Цикл
    обДОкумент = списокДокументы.GetItem(СчетчикДокументов);
    ИДСообщения = Лев(обДОкумент.DocumentId, 36); 
    Если ИДСообщения = сИнтерфейс.ИдентификаторДокумента Тогда
        //ПакетДокументов = обДОкумент.GetDocumentPackage();
        PatchTask = обОрганизация.CreatePatchTask();
        КоллекцияЭлементов = PatchTask.AddToPatch(обДОкумент, "Sign");
        Если КоллекцияЭлементов.Count() > 0 Тогда
            Для Каждого ЭлементКоллекции Из КоллекцияЭлементов Цикл
                КонтентДокумента = ЭлементКоллекции.PatchContent.Content;
                Если обДОкумент.TypeNamedId = "UniversalTransferDocument"
                ИЛИ обДОкумент.TypeNamedId = "XmlTorg12" Тогда
                    ТитулПокупателя                       = КонтентДокумента.UniversalTransferDocumentBuyerTitle;
                    ТитулПокупателя.DocumentCreator       = обОрганизация.Name;
                    ТитулПокупателя.OperationContent      = "Товары (работы, услуги, права) приняты без расхождений (претензий)";
                    Подписанты                            = ТитулПокупателя.Signers.AddItems();
                    Подписанты.SignerReference.BoxId      = сИнтерфейс.ИдентификаторОрганизации;
                    Подписанты.SignerReference.CertificateThumbprint = Строка(сИнтерфейс.Сертификат);
                    ЭлементКоллекции.PatchContent.PowerOfAttorneyToAttach.UseDefault = обОрганизация.MyEmployee.NeedToAttachPowerOfAttorney;
                Иначе
                    ЭлементКоллекции.PatchContent.PowerOfAttorneyToAttach.UseDefault = Истина;
                КонецЕсли;
                PatchTask.Send();
                Прервать;
            КонецЦикла;
        Иначе
            ДокументыПодписаны = Ложь;
        КонецЕсли;
    КонецЕсли;
    СчетчикДокументов = СчетчикДокументов + 1;
КонецЦикла;
```

**Comment by KrasnovaAnastasia** [comment]
Мы пробовали в PatchTask класть и пакет документов (получая их методом GetDocumentPackage()), и отдельно каждый документ - в любом случае не удаётся подписать документы, у которых нет титула покупателя.

**Comment by GilimkhanovDenis** [comment]
Не получается воспроизвести сценарий

Из того, что бросается в глаза - отправка патча происходит сразу после заполнения ответа для первого элемента вернувшейся коллекции.
В принципе, можно переписать примерно так

```
ДокументыПодписаны = Ложь;
PatchTask = обОрганизация.CreatePatchTask();

Для Каждого обДокумент Из списокДокументы Цикл
    ИДСообщения = Лев(обДОкумент.DocumentId, 36);
    Если ИДСообщения = сИнтерфейс.ИдентификаторДокумента Тогда
        КоллекцияЭлементов = PatchTask.AddToPatch(обДОкумент, "Sign");
        Для Каждого ЭлементКоллекции Из КоллекцияЭлементов Цикл
            PatchContent = ЭлементКоллекции.PatchContent;
            ПодписываемыйДокумент = ЭлементКоллекции.Document;
            PatchContent.PowerOfAttorneyToAttach.UseDefault = обОрганизация.MyEmployee.NeedToAttachPowerOfAttorney;

            Если ПодписываемыйДокумент.TypeNamedId = "UniversalTransferDocument"
            ИЛИ ПодписываемыйДокумент.TypeNamedId = "XmlTorg12" Тогда
                ТитулПокупателя                       = PatchContent.Content.UniversalTransferDocumentBuyerTitle;
                ТитулПокупателя.DocumentCreator       = обОрганизация.Name;
                ТитулПокупателя.OperationContent      = "Товары (работы, услуги, права) приняты без расхождений (претензий)";
                Подписанты                            = ТитулПокупателя.Signers.AddItems();
                Подписанты.SignerReference.BoxId      = сИнтерфейс.ИдентификаторОрганизации;
                Подписанты.SignerReference.CertificateThumbprint = Строка(сИнтерфейс.Сертификат);
            КонецЕсли;
        КонецЦикла;
    КонецЕсли;
КонецЦикла;

PatchTask.Send();
ДокументыПодписаны = Истина;
```

Если проблемные документы добавлять в PatchTask, то какая коллекция PatchItem'ов возвращается? Должно возвращаться такое:
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/34439383/3cca7abc-5a51-4064-8df6-7de82546bafb)


Возникает ли какая-то ошибка при отправке патча по ним?

Если установить поле `ЭлементКоллекции.GetDocumentAfterPatch = True`, то что возвращается в результате метода `PatchTask.Send()` ?

**Comment by GilimkhanovDenis** [comment]
Проблема не воспроизводится, дополнительных вводных нет. Закрываю обращение

Если проблема актуальна, то переоткрывайте
