### ISSUE TITLE
Ссылка на УПД в УКД

### ISSUE THREAD

**Issue by VladimirPozdeyev** [diadoc/diadocsdk-1c-docs#993]
Добрый день!
Создаю документ УКД через API Diadoc_5_44_0_907
CreatePackageSendTask2() и AddDocument("UniversalCorrectionDocument", "КСЧФДИС", "ucd736_05_01_02")
Хочу чтобы в данном пакете была ссылка на УПД.
Заметил что при отправке уточнения через веб интерфейс и создании корректировок в пакете 2 документа
УПД и УКД
Через GetDocuments() я нашел нужный мне УПД и знаю его ID
Как добавить найденный УПД в пакет 
Не нашел описания процедуры AddDocumentsToPacket(ID) 
Она устарела?

> Так же вопрос по ГТД в какое поле в Table.Items добавлять информацию о Стране и ГТД как это делается в УПД
> Item.CustomsDeclarations.AddCustomsDeclaration()
Вопрос по стране решен

Заранее спасибо!

**Comment by VladimirPozdeyev** [comment]
Вопрос по добавлению ГТД решил.
Добавил в Item
Новая строка = Item.AdditionalInfos.AddAdditionalInfo();
Новая строка.ID = "цифровой код страны происхождения";
Новая строка.Value=СтрокаДанных.КодСтраны;
Новая строка = Item.AdditionalInfos.AddAdditionalInfo();
Новая строка.ID = "краткое наименование страны происхождения";
Новая строка.Value=СтрокаДанных.НаименованиеСтраны;
Новая строка = Item.AdditionalInfos.AddAdditionalInfo();
Новая строка.ID = "регистрационный номер декларации на товары";
Новая строка.Value=СтрокаДанных.НомерГТД;

В печатной форме на сайте информация отображается корректно

Остался вопрос по ссылке на УПД

**Comment by GilimkhanovDenis** [comment]
Добрый день

Для связывания УКД и УПД воспользуйтесь методом [DocumentToSend.AddInitialDocument(DocumentID)](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentToSend.html#DocumentToSend.AddInitialDocument) при отправке УКД

Примерно так

```
SendTask = Organization.CreatePackageSendTask2();
SendTask.CounterAgentId = CounterAgentId;
Document = SendTask.AddDocument("UniversalCorrectionDocument", "КСЧФДИС", "ucd736_05_01_02");
Document.AddInitialDocument(УПД_ID);
```

**Comment by VladimirPozdeyev** [comment]
Да всё получилось.
До отправки и в черновиках ничего не отображалось.
Но если убрать флаг черновика, и отправить то в отправке всё отображается корректно.
