### ISSUE TITLE
Ссылка на УПД в УКД

### ISSUE THREAD

**Issue by VladimirPozdeyev** [diadoc/diadocsdk-1c-docs#994]
Добрый день!
Создаю документ УКД через API Diadoc_5_44_0_907
CreatePackageSendTask2() и AddDocument("UniversalCorrectionDocument", "КСЧФДИС", "ucd736_05_01_02")
Хочу чтобы в данном пакете была ссылка на УПД.
Заметил что при отправке уточнения через веб интерфейс и создании корректировок в пакете 2 документа
УПД и УКД
Через GetDocuments() я нашел нужный мне УПД и знаю его ID
Как добавить найденный УПД в пакет
Не нашел описания процедуры AddDocumentsToPacket(ID)
Она устарела?
Так же вопрос по ГТД в какое поле в Table.Items добавлять информацию о Стране и ГТД как это делается в УПД
Item.CustomsDeclarations.AddCustomsDeclaration()

Заранее спасибо!

**Comment by GilimkhanovDenis** [comment]
Закрываю как дубль #993
