### ISSUE TITLE
Как переместить закрытый пакет документов из исходящих в удаленные?

### ISSUE THREAD

**Issue by X-BANZAJ** [diadoc/diadocsdk-1c-docs#995]
Добрый день. Подскажите, как правильно перенести закрытый(подписание и отправка одной кнопкой при DelaySend=true) пакет документов в удаленные. Попробовал в цикле по ИД:
 
document = box.GetDocumentById(documentDiadocID)
document.Delete()       
         
но вышла ошибка "Документы закрытого пакета удаляются только всем пакетом. Для операции не передавайте documentId".

**Comment by GilimkhanovDenis** [comment]
Добрый день

Вам нужно получить сначала весь пакет, а потом вызвать метод Delete уже для него

```
dd_Package = dd_Document.GetDocumentPackage()
dd_Package.Delete()
```

**Comment by X-BANZAJ** [comment]
@GilimkhanovDenis, Денис примерно так, я правильно понял? Чет не выходит.
dd_Document= box.GetDocumentById(letterID + documentID)
dd_Package = dd_Document.GetDocumentPackage()
dd_Package.Delete()

**Comment by GilimkhanovDenis** [comment]
Да

**Comment by GilimkhanovDenis** [comment]
Хмм. похоже, что метод есть, но он ничего не делает

Значит. сейчас закрытые пакеты нельзя переместить в удалённые

**Comment by X-BANZAJ** [comment]
@GilimkhanovDenis , оО это как?) Нам нужно убрать доки из исходящих..

**Comment by GilimkhanovDenis** [comment]
Похоже, метод когда-то давно добавили в интерфейс, но не реализовали

В одном из ближайших релизов, думаю, сделаем

**Comment by X-BANZAJ** [comment]
Может есть какое-то временное решение? Не хотелось бы в ящике организации копить мусор, люди запутаются.

**Comment by GilimkhanovDenis** [comment]
С помощью компоненты временного решения не вижу. Можно через веб удалять - ссылка на документ есть в объекте [DocumentBase](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html) - поле PathURL

В ближайшем релизе добавим реализацию метода Delete (релиз предполагается на следующей неделе)

**Comment by GilimkhanovDenis** [comment]
Добрый день

исправили удаление документов в закрытых пакетах в релизе [5.50.0](https://developer.kontur.ru/Docs/Diadoc/COM/History/History.html#v5.50.0) ([ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html))
