### ISSUE TITLE
Внешняя компонента DiadocInvoiceAPI CreateObject()

### ISSUE THREAD

**Issue by Alkonig58** [diadoc/diadocsdk-1c-docs#996]
Добрый день.
Платформа: 8.3.23.1865
Реж. совместимости: 8.3.21

Задача: подключится на сервере и на клиенте через Addin.
1. Компонента загружается.
2. DiadocInvoiceApi = Новый("AddIn.DiadocAPI.DiadocInvoiceAPI") - объект создается.
3. DiadocApi = DiadocInvoiceApi.CreateObject();  DiadocApi = НЕОПРЕДЕЛЕНО

Вопрос: Почему метод CreateObject() возвращает "Неопределено" ?

Подробности на картинке:
![image](https://github.com/diadoc/diadocsdk-1c-docs/assets/110818615/4435b324-c2ca-4a4c-9e2f-b41d60c94297)

**Comment by GilimkhanovDenis** [comment]
Добрый день

Обычно такое происходит, если старая компонента не смогла полностью разрегистрироваться

Можете разрегистрировать старую  компоненту - в реестре не должно остаться её следов и после этого зарегистрировать новую

В https://github.com/diadoc/diadocsdk-1c-docs/issues/783 приводили алгоритм решения. Техподдержка, насколько мне известно, должна уметь решать подобные проблемы, попробуйте [обратиться](https://www.diadoc.ru/support)
