### ISSUE TITLE
Не отправляется приглашение с вложением (COM x86 5.49.1.933)

### ISSUE THREAD

**Issue by jakeqwert** [diadoc/diadocsdk-1c-docs#998]
Добрый день!
Отправляем приглашение с вложением контрагенту. 
Статус контрагента перед отправкой приглашения "IsRejectedByMe". 

Всегда использовали такой метод отправки (ПолныйПуть - полный путь к вложению):

AcquireCounteragentTask = Organization.CreateAcquireCounteragentTask(ПолныйПуть);   
AcquireCounteragentTask.CounteragentBoxId = CounteragentId; 
AcquireCounteragentTask.Inn 				= ИНН;
AcquireCounteragentTask.Message 			= Комментарий; 
AcquireCounteragentTask.FileName 			= ИмяФайла;
AcquireCounteragentTask.SignatureRequested  = истина; 
AcquireCounteragentTask.Send();

После установки новой версии компоненты 5.49.1.933, метод CreateAcquireCounteragentTask(ПолныйПуть) стал выполняться с ошибкой, приглашение не отправляется.
Если использовать CreateAcquireCounteragentTask() без передачи ПолныйПуть, а потом передавать полный путь к вложению через FileName приглашение отправляется, но уходит без вложения.

AcquireCounteragentTask = Organization.CreateAcquireCounteragentTask();   
AcquireCounteragentTask.FileName  = ПолныйПуть;

Помогите разобраться как отправить приглашение с вложением в данном случае.

**Comment by GilimkhanovDenis** [comment]
Добрый день

Какая ошибка возникает в `CreateAcquireCounteragentTask(ПолныйПуть)`?

Какая версия использовалась раньше?

**Comment by jakeqwert** [comment]
Ранее использовалась версия  компоненты 5.39.1 

Ошибка: Произошла исключительная ситуация (Box.CreateAcquireCounteragentTask): WIN32[0x00000002] "\\?\C:\Users\F0340708\AppData\Local\Temp\РСЃС…РѕРґСЏС‰РёРµСЃСЌР»РµРєС‚СЂРѕРЅРЅС‹РјСЃРѕРіР»Р°СЃРѕРІР°РЅРёРµРј_2024_РРЎРҐ_0009461_20.docx" The system cannot find the file specified.

Наименование файла на русском языке, в данной папке он есть.

**Comment by NickZubashevskiy** [comment]
Добрый день!
Вышел [релиз](https://developer.kontur.ru/Docs/Diadoc/COM/History/release_info/5_50_0.html) 5.50.0, где этот баг был устранен 
[Ссылки для скачивания](https://developer.kontur.ru/Docs/Diadoc/COM/Downloads.html)
