### ISSUE TITLE
Как получить причину отказа в подписании?

### ISSUE THREAD

**Issue by X-BANZAJ** [diadoc/diadocsdk-1c-docs#999]
Доброго времени суток.
Подскажите, как возможно получить комментарий, который оставил контрагент при отказе в подписании документа?

**Comment by GilimkhanovDenis** [comment]
Добрый день

[DocumentBase.GetAnyComment](https://developer.kontur.ru/Docs/Diadoc/COM/ComObjects/DocumentBase.html#DocumentBase.GetAnyComment)("SignatureRejectionComment")

**Comment by X-BANZAJ** [comment]
@GilimkhanovDenis, как всегда благодарю. Завтра попробую уже)

**Comment by X-BANZAJ** [comment]
@GilimkhanovDenis, Денис а коммент имеет ограничение по длине?

**Comment by GilimkhanovDenis** [comment]
@X-BANZAJ Отказы в подписи - XML, построенные в соответствие с [XSD](https://developer.kontur.ru/docs/diadoc-api/_downloads/014ca3549493fff5aaa673c5f60175a9/DP_UVUTOCH_1_985_00_01_03_01.xsd) (У Диадока [есть метод генерации](https://developer.kontur.ru/docs/diadoc-api/http/GenerateSignatureRejectionXml.html), в котором используется эта схема). Комментарий лежит в тэге `ТекстУведУточ`. В самой схеме ограничений на максимальную длину нет и в интеграции в первую очередь исходил бы из этого.

Возможно (я не знаю), ограничения есть где-то на стороне операторов ЭДО для какой-то внутренней оптимизации, но это, так или иначе, особенности реализации и завязываться на них не стоит
